### ISSUE TITLE
Data 를 줄이거나 덜 쌓이게 할 수 있나요?

### ISSUE THREAD

**Issue by youngclown** [naver/pinpoint#1043]
이것저것 모니터링 툴을 서버에 적용해보려다가, 찾게 되었는데요.
정말 많은 도움이 되고 있습니다!

서버에 올려서 돌려보고 있는데요. 질문을 드릴 게 있어서 글을 적게 되었습니다.

1. 1 분마다 대략 8G 가 데이터가 쌓이고 있는데, 해당 데이터를 줄일 수 있는 방법이 있나요.
Log 는 log4j 를 사용하므로 해당 저장 방식을 INFO 에서 ERROR 로 줄였으나,
Data 를 줄이는 방안이 있는지 궁금합니다.

2. tomcat 에서 MongoDB, Redis, Ehcache, Mysql 을 연결하여, 사용중입니다.
Redis 와 Mysql 은 자동으로 연결되는데, MongoDB 와 Ehcache 는 잡지 않네요.
어떤 경우에 잡히지 않고, 따로 잡을 수 있는 방안이 있는지 궁금합니다.

감사합니다.

**Comment by nstopkimsk** [comment]
1. 어떤 데이타인지 구체적으로 알려주시면 답변하는데 도움이 될 것 같습니다.  Pinpoint Agent의 log를 말씀하시는건지, Hbase에 쌓이는 데이타를 말씀하시는 건지, collector나 web의 log를 말씀하시는지 혹은 모두를 다 포함해서 말씀하시는 건지 알려주시면 구체적으로 말씀드릴 수 있을 것 같습니다. 

2. MongoDB, Ehcache는 현재 지원하고 있지 않습니다. 지원을 위해서는 별도의 plugin으로 만들어야 하는데요. v1.5 릴리즈까지는 구현하기 힘들 것 같습니다. 괜찮으시면 https://github.com/naver/pinpoint-plugin-sample 참고하셔서 직접 개발하실 수도 있습니다.

**Comment by youngclown** [comment]
네. collector 에 쌓이는 데이타를 줄일 수 있는 방안이 있는지 문의드렸습니다.

**Comment by koo-taejin** [comment]
@youngclown 
1분마다 8기가는  정상적인 상황은 아닌것 같습니다. 
(그정도면 저희가 의도하지 않았던 로그가 반복적으로 나타나야 가능할 것 같은데 혹시 말씀주신 로그파일에 반복되는 패턴의 로그가 있다면 잘라서 전달해주시면 보고 확인하도록 하겠습니다.)
