### ISSUE TITLE
Docker setup with no data

### ISSUE THREAD

**Issue by ha02148** [naver/pinpoint#1044]
Hi All,

Not sure if this is the right place for this question/issue.  I have setup hbase and pinpoint in one docker container.

HBase 1.0.1.1
Pinpoint 1.1.1

Hbase, pinpoint collector and web started without any error or issue.  Then I started my Tomcat with the agent and I can see it from the application drop down from pinpoint web.  However, there is no data and there are no rows in the following tables.

ApplicationMapStatisticsCallee
ApplicationMapStatisticsCaller
ApplicationMapStatisticsSelf

Also, there is no error in the logs with debug enable.

After I saw the [Dockerfile] (https://github.com/naver/pinpoint/blob/master/docker/pinpoint-hbase/Dockerfile) on github, I tried to start the container with --net=host.  It works and I got data.

I prefer not to use the --net=host.  Any idea on how to make it work without it?

Thanks.

**Comment by dawidmalina** [comment]
I have exactly the same issue. Did you change only hbase or all containers?

**Comment by ha02148** [comment]
I have everything in one container.  I finally got it working with the following when I start the container.

-p <id addr>:9994:9994 -p <ip addr>:9995-9996:9995-9996/udp

I forgot that it is also using udp ports.

**Comment by dawidmalina** [comment]
Works thanks. Probably this ticket can be closed:)
