### ISSUE TITLE
External agents

### ISSUE THREAD

**Issue by gleicon** [naver/pinpoint#108]
More a question than an issue: Is there any way to plug an external agent or data collector for a given app ? For instance, I'd like to plug a frontend beacon (https://github.com/gleicon/go-beacon) to create RUM data insite pinpoint or adapt pinba (http://pinba.org/) for PHP apps. The architecture seems great but I think it would take more than the regular java knowledge to plug them at the same level as the jvm agent (and external data sources may not even belong there). Thanks !

**Comment by Xylus** [comment]
Hi, thank you for a great question.
As I understand, it seems like you would like to add end-user monitoring (in the case of beacon), and/or add profiling support for PHP apps (in the case of Pinba).

**End-user monitoring**
End-user monitoring is in our TODO list, but we haven't finalized on how we would go about doing it. Transaction ID is generated once a request is received from front-most server so our current model would not support a direct per-request end-to-end tracing. A simplified ID scheme could be used to group end-user requests but nothing's been decided yet.

**Profiling PHP apps**
I am not familiar with Pinba, so please let me know if I'm talking nonsense from here on out. As I understand, Pinba PHP extension collects/sends trace data for requests to a MySQL backend for storage.
If this is the case, Pinba PHP extension could work as a Pinpoint agent for PHP apps if **a)** the trace data is structured in a way compatible with Pinpoint, **b)** these data could be sent to Pinpoint collector, and  **c)** it serializes them in a way expected by Pinpoint collector (currently using Thrift).
We don't have a developer's guide available yet but the above specs would be covered once it's ready.

If you would like to share any insights, please feel free to post them here.

Thank you.
