### ISSUE TITLE
어드민 메뉴와 CallStack 메뉴는 어떻게 접속하면 되나요? (How can i access to Admin/CallStack menu?)

### ISSUE THREAD

**Issue by james628** [naver/pinpoint#110]
HBase를 세팅한 후 Collector와 web을 정상적으로 동작시킨 후,
각 서비스별 톰캣에 agent를 넣고 구동하여 사용하고 있습니다.

다만 생성된 agentId를 삭제하고 싶어서 소스를 보니 AdminController내에 removeAgentId라는 RequestMapping이 존재하더구요.
어드민 페이지는 어떻게 접속하는지 궁금합니다.

또한 angularjs 소스를 보니 controller에 callstack관련된 소스가 있는데
webui메인페이지에서는 접근할 수 있는 방법이 없어서
callstack에 접근하는 방법도 궁금합니다.

감사합니다.

**Comment by koo-taejin** [comment]
안녕하세요.

현재 따로 admin페이지는 없습니다 :)
코드에서 보신것 처럼 rest api를 이용하여 agentId를 삭제할수 있습니다. 
코드에서 보셨다면 필요 파라미터 등을 다 이해하셨을거라고 판단해서 추가적인 설명인 생략하겠습니다.  (필요하면 말씀 부탁드립니다. )

추가적으로 callstack에 접급하는 방법은 다음과 같습니다. 
최초 서비스를 선택하면 서버맵과 함께 오른쪽위에 스캐터 차트가 보여지는데요. 
스캐터 차트의 하나의 점들은 하나의 요청을 뜻합니다. 
마우스로 원하는 영역만큼을 지정하면 자동으로 callstack페이지가 나오게 됩니다 ^^

감사합니다.

**Comment by james628** [comment]
답변 감사드립니다.
궁금한 점이 모두 해소되었습니다 :)

**Comment by nstopkimsk** [comment]
간단한 동영상 하나 만들어서 올릴 예정이에요 ^^
we are going to make a simple video clip.
