### ISSUE TITLE
pinpoint WEB에 아무런 데이터가 나오지 않는 현상

### ISSUE THREAD

**Issue by imjaebong** [naver/pinpoint#1130]
![default](https://cloud.githubusercontent.com/assets/15374786/10813949/d849b526-7e65-11e5-8bd2-1c1cba9b4bfe.JPG)

위 이미지와 같이 WEB화면 하단에 Reatime Active Thread Chart 부분에 CONNECTION_NOT_FOUND라는 메세지가 나오는데 어떻게 처리해야 하는지요?
그리고 DB에는 데이터가 쌓이고 있지만 화면에 아무런 데이터가 나오지 않습니다. 어떤 조치가 추가로 필요하나요?
![1](https://cloud.githubusercontent.com/assets/15374786/10813989/16ca5256-7e66-11e5-95ba-ce4599c999cd.JPG)

**Comment by koo-taejin** [comment]
RealTime 차트의 경우 개발중인 사항이기 때문에 위처럼 나오는 것이 정상적인 사항으로 판단하셔도 됩니다. 1.5.0 릴리즈 및 해당 기능개발에 보강이 완료되었다고 판단될때 기본설정을 바꾸어 놓을 예정입니다. 

스캐터차트나 서버맵이 보이지 않는 것은 톰캣이 받은 요청을 찾을수 없기 때문입니다. 
위 같은 상황이 발생하는 경우는 2가지입니다. 
1. 톰캣이 실제 요청을 받지 않은 경우 
2. 톰캣이 요청을 받고 데이터를 전달하였지만 콜렉터나 db에서 데이터를 획득하지 못한 경우
1번의 경우에는 agent의 rest api같은 호출을 통해 해결이 가능하지만, 2번의 경우에는 이전 이슈에서 말씀드린 것 처럼 콜렉터의 로그를 전달주셔야 합니다. 

파일업로드가 불가능하다면 koo.taejin@gmail.com으로 메일 주시면 확인해보겠습니다.

**Comment by imjaebong** [comment]
Linux에서 방화벽 처리를 TCP만 해서 발생했던 현상으로 
UDP를 방화벽 처리해서 정상적으로 화면 나오느거 확인했습니다.
감사합니다.
