### ISSUE TITLE
Response time miss match issue 

### ISSUE THREAD

**Issue by ZhuWanShan** [naver/pinpoint#1181]
Hi, 
 I found sometimes the response time in the transaction list are not match the Span detail, as the attached   picture, is there any miss understanding. and how can void this issue?

and the response time in the application summary page is also not same as in detail.

<img width="560" alt="response time miss match" src="https://cloud.githubusercontent.com/assets/4099865/11111516/d290abdc-8944-11e5-9728-68b49f4995ef.png">
![screenshot at nov 12 13-11-41](https://cloud.githubusercontent.com/assets/4099865/11111546/07dfc9d0-8945-11e5-9612-99c7b89fe6d1.png)

**Comment by ZhuWanShan** [comment]
The pinpoint version is 1.0.4.

**Comment by Xylus** [comment]
Hi ZhuWanShan,
Can't tell for sure just from your screenshots, but one case where this is possible is if the transaction above is a part of a larger transaction.
For example, if the transaction is A -> B -> C, and you've selected the B node and dragged it's scatter chart, the transaction list would show the part of transaction that started from the B node. The call tree however will display the whole thing (starting from the A node).
