### ISSUE TITLE
Hbase 내의 데이터 삭제 관련 질문드립니다.

### ISSUE THREAD

**Issue by james628** [naver/pinpoint#122]
안녕하세요.
Hbase내에 저장되는 데이터에 대해 한가지 궁금한 점이 있어서 질문 드립니다.

1. 특정 시점 이전의 request데이터를 지우는 방법이 궁금합니다.
2. 특정 URL으로 들어오는 requst에 해당하는 데이터를 저장하지 않거나 지우는 방법이 궁금합니다.

HBase command명령어로라도 지울수 있는 방법이 있다면 공유 부탁드립니다.
감사합니다.

**Comment by minwoo-jung** [comment]
1. 특정 시점 이전의 request데이터를 지우는 방법이 궁금합니다.

2.
