### ISSUE TITLE
collecter can not be initialized 

### ISSUE THREAD

**Issue by eros4349** [naver/pinpoint#1259]
OS : Red Hat Enterprise Linux Server release 6.6 64bit(Santiago)
jdk : jdk1.6.0_45, jdk1.7.0_79, jdk1.8.0_25
maven : apache-maven-3.2.5
hbase : pinpoint의 hbase 데몬은 통한 자동설치

pinpoint 빌드 (성공)
hbase 설치 및 시작 (성공)
hbase init (성공)

pinpoint 설치 중 문제 발생하여 문의드립니다.
(collecter can not be initialized #635에 동일한 문의가 올라와 있는데,
 수정 하신다고 나와있고, 이슈 픽스 되었는지는 보이지 않네요..)
collector 로그는 아래와 같습니다.

pinpoint/quickstart/logs
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.navercorp.pinpoint:pinpoint-quickstart-collector:war:1.5.0-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ com.navercorp.pinpoint:pinpoint-quickstart-collector:${maven.pinpoint.version}, /opt/pinpoint/quickstart/collector/pom.xml, line 11, column 14
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-war-plugin is missing. @ com.navercorp.pinpoint:pinpoint-quickstart-collector:${maven.pinpoint.version}, /opt/pinpoint/quickstart/collector/pom.xml, line 41, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Pinpoint Collector QuickStart 1.5.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.navercorp.pinpoint:pinpoint-collector:war:1.5.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.367 s
[INFO] Finished at: 2015-11-26T09:41:09+09:00
[INFO] Final Memory: 11M/80M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project pinpoint-quickstart-collector: Could not resolve dependencies for project com.navercorp.pinpoint:pinpoint-quickstart-collector:war:1.5.0-SNAPSHOT: Could not find artifact com.navercorp.pinpoint:pinpoint-collector:war:1.5.0-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by koo-taejin** [comment]
#635 이슈와는 연관이 없는 에러 입니다. 
제가 quickstart쪽 version을 변경하지 않아서 발생한 문제 같습니다. 
47082104567bd470abe14fd4da30f866bd54eae0 커밋을 통해서 수정을 했습니다. 

최신으로 업데이트 하셔서 다시한번 해보시겠어요?

**Comment by eros4349** [comment]
핀포인트 다시 다운로드 후 빌드부터 다시 하라는 말씀이신가요?

**Comment by koo-taejin** [comment]
빌드 다시하지 않으셔도 됩니다. 
quickstart부분만 재실행하시면 됩니다.

**Comment by eros4349** [comment]
동일한 에러 떨어집니다.
1.5.1 올려주시려고 하신거 같은데 에러에는 1.5.0 찍히네요...

[root@190 logs]# date
2015. 11. 26. (¸ñ) 13:15:35 KST
[root@190 logs]# ls -al 
ÇÕ°è 20
drwxr-xr-x.  3 root root 4096 2015-11-26 13:15 .
drwxr-xr-x. 12 root root 4096 2015-11-25 19:46 ..
drwxr-xr-x.  2 root root 4096 2015-11-26 12:58 pid
-rw-r--r--.  1 root root 2356 2015-11-26 12:58 quickstart.collector.log
-rw-r--r--.  1 root root 2297 2015-11-25 20:06 quickstart.web.log


INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.navercorp.pinpoint:pinpoint-quickstart-collector:war:1.5.0-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ com.navercorp.pinpoint:pinpoint-quickstart-collector:${maven.pinpoint.version}, /opt/pinpoint/quickstart/collector/pom.xml, line 11, column 14
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-war-plugin is missing. @ com.navercorp.pinpoint:pinpoint-quickstart-collector:${maven.pinpoint.version}, /opt/pinpoint/quickstart/collector/pom.xml, line 41, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Pinpoint Collector QuickStart 1.5.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.navercorp.pinpoint:pinpoint-collector:war:1.5.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.443 s
[INFO] Finished at: 2015-11-26T12:58:41+09:00
[INFO] Final Memory: 8M/80M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project pinpoint-quickstart-collector: Could not resolve dependencies for project com.navercorp.pinpoint:pinpoint-quickstart-collector:war:1.5.0-SNAPSHOT: Could not find artifact com.navercorp.pinpoint:pinpoint-collector:war:1.5.0-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
~

**Comment by koo-taejin** [comment]
현재 quickstart 를 사용하려고 하시는 head의 hash 값을 알려주시겠어요? 그러면 더 나은 지원을 해드릴수 있을것 같습니다.

**Comment by eros4349** [comment]
아래와 같습니다.
[root@190 bin]# md5sum /opt/pinpoint/quickstart/bin/start-collector.sh 
7b6f71d2bf031f8350bae240e7833e2b  /opt/pinpoint/quickstart/bin/start-collector.sh

**Comment by koo-taejin** [comment]
```git show-ref master ```
커맨드를 입력하여 획득한 값을 주시면 됩니다.

**Comment by eros4349** [comment]
도움 감사드립니다.

[root@190 bin]# git show-ref master
b1aaaf12087acbcda92ec1b1dcaba7c3da7d4ee1 refs/heads/master
b1aaaf12087acbcda92ec1b1dcaba7c3da7d4ee1 refs/remotes/origin/master

**Comment by koo-taejin** [comment]
![2015-11-26 15 08 32](https://cloud.githubusercontent.com/assets/10057874/11416292/9b25b064-944f-11e5-84aa-93225e58f972.PNG)

제가 최신으로 업데이트 하고 작업을 부탁드렸는데 업데이트가 안된것 같습니다. 
전달주신 hash값은 제가 commit한 이전의 hash를 가지고 있는것을 알수 있습니다. 

업데이트 하고 다시 해보기를 부탁드리겠습니다.

**Comment by eros4349** [comment]
업데이트 후 정상기동됩니다.

도움 감사드립니다.
