### ISSUE TITLE
How to see code level visibility graph?

### ISSUE THREAD

**Issue by gkhakare** [naver/pinpoint#1291]
I have deployed pinpoint-1.5.0 and started monitoring my tomcat.
I can see real time threads but can not see other graphs in details.
My Pinpoint URL is: http://52.90.255.207:8080/#/main/TestNowApp-Prod@TOMCAT/5m/2015-12-02-11-23-33

**Comment by Xylus** [comment]
Hi gkhakare, you can view the transaction list by dragging over the scatter chart at the top right.
However, it seems like there isn't any requests that were traced.

**Comment by gkhakare** [comment]
Thank You Xylus.
It has worked for me for version 1.1.0.
Anyhow I can not see scattered graph for 1.5.0 release. 
Regards,
Ganesh
