### ISSUE TITLE
OSGI pinpoint install guide

### ISSUE THREAD

**Issue by cowboy93** [naver/pinpoint#1320]
pinpoint 도 Java의 agent 기능을 사용하므로, OSGI 를 사용시 문제가 발생됩니다. 
````
-Datlassian.org.osgi.framework.bootdelegation=sun.,com.sun.,com.navercorp.*,org.apache.xerces.*
````
와 같이 아틀라시안 제품을 사용할 때에는 bootdelegation 에 추가를 해 주어야만 ClassNotFound 오류가 발생하지 않습니다. 

이 옵션은 start 하는 shell script에 Java Option 에 넣어 주시면 됩니다.

**Comment by nstopkimsk** [comment]
감사합니다.  이 내용 wiki의 FAQ로 옮겨도 될까요?

**Comment by cowboy93** [comment]
당연하죠. 
상관 없슴돠.
