### ISSUE TITLE
does back-end（web & collector）support cluster？

### ISSUE THREAD

**Issue by junfengcode** [naver/pinpoint#1336]
We hope the back-end  can load balancing
if can，how？
Thank you

Sorry, my English is very poor

**Comment by koo-taejin** [comment]
sorry :sob:
we do not support function of load balancing. 
and we have no plan to make this function yet.

**Comment by junfengcode** [comment]
Can use haproxy to implement ？ 
and what is the function of ‘package com.navercorp.pinpoint.collector.cluster’ ？

**Comment by koo-taejin** [comment]
Yes. you can haproxy. 
'com.navercorp.pinpoint.collector.cluster' package do connect web to agent.
It's largely irrelevant function of load balancing .

**Comment by junfengcode** [comment]
ok，Thank you very much
