### ISSUE TITLE
Actual ClientIP (RemoteAddr)

### ISSUE THREAD

**Issue by barneykim** [naver/pinpoint#137]
As you already know, If you are using a proxy server or the L7 equipment, the ClientIP(RemoteAddr) is the IP address of the Proxy or L7 equipment.
In this case, you must use the x-forwarded-for in the HTTP header.

61 line of ```StandardHostValveInvokeInterceptor``` are following:
```
final String remoteAddr = request.getRemoteAddr();
trace.recordRemoteAddress(remoteAddr);
```

I want change, as shown below.

```
final String remoteAddr = getRemoteAddr(request);
...
private String getRemoteAddr(HttpServletRequest request) {
    String remoteAddr = request.getHeader("x-forwarded-for");
    if (StringUtils.isBlank(remoteAddr)) {
        remoteAddr = request.getRemoteAddr();
    } else {
        remoteAddr = remoteAddr.split(",")[0].trim();
    }
   return remoteAddr;
}
```

**Comment by emeroad** [comment]
Good suggestion.
Will be included in next version(1.0.5-SNAPSHOT).
