### ISSUE TITLE
Supports newrelic agent

### ISSUE THREAD

**Issue by hey-jude** [naver/pinpoint#1379]
Newrelic supports so many languages, frameworks, servers via agents & plugin daemons.
If its data can be used, pinpoint can be used so many area naturally.

* newrelic agent/plugins cannot set server address, but it can set http proxy so servers can receive data by emuliting proxy server.

====
newrelic은 java뿐 아니라 수많은 언어, 프레임웍들의 에이전트와 플러그인이 공개되어 있습니다. 이를 직접 이용할 수 있다면 pinpoint도 자연스레 사용할 수 있는 영역이 넓어질 것으로 예상합니다.

아쉽게도 newrelic agent는 직접 서버 지정을 할 수는 없게 되어 있습니다만 설정에서 http proxy를 지정할 수는 있습니다. 이를 이용하면 손쉽게 pinpoint가 agent의 데이터를 읽어들일 수 있겠습니다.

**Comment by nstopkimsk** [comment]
NAVER - http://www.naver.com/
--------------------------------------------
김성관(sungkwan.kim@naverco...) 님은 현재 부재중입니다.</br>
보내신 메일 <[pinpoint] Supports newrelic agent (#1379)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
김성관(sungkwan.kim@naverco...) 님이 남기신 메시지 입니다.
--------------------------------------------
[Absence period : 2015-12-24 10:00 ~ 2015-12-31 23:59 GMT +09:00]<br>리프레쉬 휴가입니다. <br>Pinpoint는 Pinpoint DL로 문의주시기 바랍니다. 
--------------------------------------------

**Comment by nstopkimsk** [comment]
Thanks for your suggestion. But there are so many thins to be solved including legal issues, and also technically not easy.
