### ISSUE TITLE
Use regular expressions to exclude the url

### ISSUE THREAD

**Issue by barneykim** [naver/pinpoint#138]
When using the ```ExcludeUrlFilter```, I need to specify the Url to exclude.

```
public boolean filter(String requestURI) {
    for (String excludeUrl : this.excludeUrlList) {
        if (excludeUrl.equals(requestURI)) {
            return FILTERED;
        }
    }
    return false;
}
```

**pinpoint.config**
```
profiler.tomcat.excludeurl=/exclude/foo.html, /exclude/bar.html, /aa/exclude/foo.html
```

is it better to use regular expression?
I can use a regular expression as follows:

```
for (String excludeUrl : this.excludeUrlList) {
    if (Pattern.matches(excludeUrl, requestURI)) {
        return FILTERED;
    }
}
```

```
profiler.tomcat.excludeurl=/exclude/(.*), /(.*)/exclude/(.*)
```

**Comment by emeroad** [comment]
regular expression is too complicated.

I think the Ant-style seems to be easier.
- http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/util/AntPathMatcher.html

**Comment by barneykim** [comment]
:+1: agree, the Ant-style is easy to read and use.
