### ISSUE TITLE
How to reveal the call chain in custom plugin

### ISSUE THREAD

**Issue by majinkai** [naver/pinpoint#1395]
I have written plugin for [dubbo](http://github.com/alibaba/dubbo)(RPC)

there have three app:
app1(springboot)[httpclient 4.3]
app2(springboot)[dubbo 2.5.3] client
app3(springboot)[dubbo 2.5.3] server

#### Call chain:
app1  ---(with httpclient)--->  app2  ---(with dubbo RPC)--->  app3

#### in pinpoint web shows(depth 8):
select app1:
USER --> app1 --> app2
select app2:
USER --> app1 --> app2
select app3:
USER --> app1 --> app2 --> app3

#### Question

why RPC Client(app1/app2) could not show full chain.
RPC Server(app3) could show full chain.

#### Code

here is my plugin code: https://github.com/majinkai/pinpoint-plugin

**Comment by nstopkimsk** [comment]
@lioolli could you review this issue?

**Comment by majinkai** [comment]
when i add `RECORD_STATISTICS` to ServiceType, the call chain has show `dubbo server`

how to make `app3` and `ip:port(dubbo server)` as one node?

**Comment by majinkai** [comment]
![image](https://cloud.githubusercontent.com/assets/3540799/12089447/ca82ceb6-b31f-11e5-8629-34dd299ee7b1.png)

![image](https://cloud.githubusercontent.com/assets/3540799/12089486/4008ee36-b320-11e5-80f8-ca6525ab3713.png)

screenshot 1 cannot show full chain.
screenshot 2 was my wanted.

**Comment by lioolli** [comment]
Pinpoint finds caller - callee relation by matching caller's end point and callee's acceptor host.

In your plugin codes, you record end point in `DubboConsumerInterceptor`
```
  String endPoint = RpcContext.getContext().getRemoteAddressString(); 
  // RPC client have to record end point (server address) 
  recorder.recordEndPoint(endPoint); 
```

and acceptor host in `DubboProviderInterceptor`
```
  String serverHostName = rpcContext.getLocalHostName(); 

  if (serverHostName != null) { 
      recorder.recordAcceptorHost(serverHostName); 
  } else { 
      recorder.recordAcceptorHost(rpcContext.getLocalAddressString()); 
  } 
```

Please check if these values are equal.

**Comment by majinkai** [comment]
Thank you very much!!! Perfectly solved my problem.

I think we need more docs to help us write plugin.

Thanks again!

**Comment by nstopkimsk** [comment]
right. we're preparing more docs for plugin. Could you tell us what the most difficult point to write your plugin?  It's helpful for an effective docs.

**Comment by majinkai** [comment]
Better to wait for the release of the document, and then suggest it. Because there are too many places do not understand :)

**Comment by junfengcode** [comment]
we need more docs +1

**Comment by iforem** [comment]
@majinkai 

I'm sorry to ask you a question.
Follow your dubbo plug-in implementation, I developed a rpc plug-in，now I'm having trouble.
Call chain like this:
app1 --(rpc)--> app2 ---(rpc)---> app3
the trace data between app1&app2 is normal, but I can't get the trace data between app2 and app3.
The consumerInterceptor of app2 can't get the TRACE object:
Trace trace = traceContext.currentTraceObject();
the returned trace is NULL.
Any answer would be helpful plz.
BTW, do you have contact information such as email?
