### ISSUE TITLE
why use span.getAgentId() as caller host when parentApplicationType existed?

### ISSUE THREAD

**Issue by aximo** [naver/pinpoint#1409]
i think there is a bug in com.navercorp.pinpoint.collector.handler.SpanHandler.insertSpanStat(TSpan)

 final ServiceType parentApplicationType = registry.findServiceType(span.getParentApplicationType());
            statisticsHandler.updateCallee(span.getApplicationName(), applicationServiceType, span.getParentApplicationName(), parentApplicationType, span.getAgentId(), span.getElapsed(), isError);

you should not use span.getAgentId() as caller host

pls check it.

**Comment by nstopkimsk** [comment]
@emeroad could you check this?

**Comment by emeroad** [comment]
This is a limitation in Pinpoint. 
Trace granularity of N*N Agent is unsupported currently. 
It will however be improved in the future.
