### ISSUE TITLE
Replace amchart with d3

### ISSUE THREAD

**Issue by nstopkimsk** [naver/pinpoint#1410]
- main page
- inspector view

**Comment by nstopkimsk** [comment]
We would like to replace amchart  with d3, any d3 experts out there?

**Comment by dawidmalina** [comment]
@denzelsN @nstopkimsk any update about this?

**Comment by nstopkimsk** [comment]
Not yet started. @denzels  is focusing on issues related to real time charts.  after that we will consider this feature.

**Comment by mathi201028** [comment]
@nstopkimsk @denzelsN Any update replacing GO JS for server mapping real time charting?

**Comment by emeroad** [comment]
We have no plan yet.

**Comment by denzelsN** [comment]
GoJS and Amchart are different libraries.
Amchart is replacing the ChartJS.

**Comment by jiaqifeng** [comment]
@denzelsN You mean replace Amchart by using ChartJS? I saw in the main page right panel, the amchart is replaced, while in inspector page, it is still showing amCharts. So the job of replacing amCharts is half done? Any plan to replace amCharts all?

**Comment by emeroad** [comment]
Open source chart lack functionality.
So we have not yet decided on the chart replacement plan.

**Comment by jiaqifeng** [comment]
@emeroad What functionality? In inspector page, I used Chart.js. While it can show the 5 charts, while the 5 charts cannot show a tooltip (a boolean tip showing datasets at a time stamp) synchronized. Is this the feature lack? Is there any lack feature else?

**Comment by khushalwadakeAimia** [comment]
Hi Team,
Can you please mention this limitation in Licence or tool description as we cannot use it commercially without goJS lic. Also I would like know to if any changes expected in near future to overcome this issue.

Thanks,
Khushal wadake

**Comment by prashantnitt07** [comment]
hi Team ,
can be replace other name with below screen. 
actually we did not want to show right side in pinpoint view page
please suggest how to remove this 
![capture](https://user-images.githubusercontent.com/31304206/32952894-986eb1e0-cbd4-11e7-86cf-874b1d05beeb.PNG)

**Comment by denzelsN** [comment]
@prashantnitt07 
sorry. 
can not replace go.js yet. 
You have to buy a license to get rid of the phrase.

**Comment by simoelmou** [comment]
@denzelsN @emeroad Hello, is it still not possible to use Pinpoint in production or commercially without having a go.js license?

**Comment by denzelsN** [comment]
@simoelmou  Hi
We are now developing a UI that supports the new angular.
(https://naver.github.io/pinpoint/ui_v2.html)
The new UI source supports vis.js as well as go.js
