### ISSUE TITLE
Add MongoDB plugin

### ISSUE THREAD

**Issue by nstopkimsk** [naver/pinpoint#1415]

**Comment by nstopkimsk** [comment]
@lioolli

**Comment by cukal** [comment]
Are there still any plans to provide a mongodb plugin?

**Comment by gumutianqi** [comment]
why the mongodb plugin support be closed?

**Comment by daveLikePerf** [comment]
Mongodb에 대한 모듈 개발 작업을 다시 진행할 계획이 있는지요?

**Comment by dawidmalina** [comment]
I also think that support for mongodb would be very good advantage. Vote :+1:

**Comment by rainard** [comment]
do any plan to support mongodb ?

**Comment by RoySRose** [comment]
@rainard 
Yes, it's on the way.
Actually,  it's already on the snapshot, but some performance issue has come up and I'm on it.
I think a few more days for the patch to be merged.
