### ISSUE TITLE
agent->kafka->collector->elasticsearch

### ISSUE THREAD

**Issue by qifuren1985** [naver/pinpoint#1420]
I think this framework may be better:
agent->kafka->collector->elasticsearch

use kafka as a buffer, so collector can be deploy as cluster.
elasticsearch is easily to search, and can be easily integrated with kibana, grafana.

**Comment by qifuren1985** [comment]
stagemonitor.org write this article: https://www.elastic.co/blog/elasticsearch-as-a-time-series-data-store

**Comment by Xylus** [comment]
Hi qifuren1985,
Adding kafka did come up a few times internally, but we haven't decided to add it to the pipeline to keep it simple. Adding kafka also entails a lot of work as we'll have separate out connections for span/stat data (which points to kafka) and connections for real-time data (which needs a connection directly to the collector).
Also, there can already be multiple collectors if they're behind a l4.

Elastic search backend does look attractive - we'll take a closer look into this.
You can always experiment with it and throw us a PR as well! if you've got something going :)

Thanks.
