### ISSUE TITLE
is per-request_feature_guide.md too old?

### ISSUE THREAD

**Issue by aximo** [naver/pinpoint#1423]
Hi, I found the code logic is changed according the per-request_feature_guide.md:

the log tab in xxx/#/transactionList page is enabled if com.navercorp.pinpoint.thrift.dto.TSpan.loggingTransactionInfo is true, but the com.navercorp.pinpoint.profiler.context.DefaultSpanRecorder.recordLogging(LoggingInfo) method is not called at all the codes. so the loggingTransactionInfo  will be always false.

pls check it

**Comment by Xylus** [comment]
ping @minwoo-jung

**Comment by minwoo-jung** [comment]
You’re right. We will improve guide.
Pinpoint 1.5.0 or later, we improve button to decided enable/disable depending on wherether or not being logged.

You should implement interceptor for using logging appender. We also developed plugin for logging appdender internally.
 
Please refer to Pinpoint Profiler Plugin Sample. https://github.com/naver/pinpoint-plugin-sample.
This is interceptor example.


```
public class AppenderInterceptor implements AroundInterceptor0 {

    private final TraceContext traceContext;
    
    public AppenderInterceptor(TraceContext traceContext) {
        this.traceContext = traceContext;
    }

    @Override
    public void before(Object target) {
        Trace trace = traceContext.currentTraceObject();
        
        if (trace != null) {
            SpanRecorder recorder = trace.getSpanRecorder();
            recorder.recordLogging(LoggingInfo.LOGGED);
        }
    }

    @IgnoreMethod
    @Override
    public void after(Object target, Object result, Throwable throwable) {

    }
}
```
