### ISSUE TITLE
Could we exclude any profiles of some classes?

### ISSUE THREAD

**Issue by majinkai** [naver/pinpoint#1424]
For example, `Shiro` use redis to cache session objects.
It will profile many operations of redis with custom class `RedisManager`.
Could we exclude any profiles in `RedisManager.class`?

**Comment by Xylus** [comment]
Hi majinkai,
I don't think we have an option to exclude traces in the class level, but it does sound like a useful feature. We'll take a further look into this and get back to you.

In the mean time, there is an option to disable some predefinted traces within Redis : `profiler.redis.pipeline`, `profiler.redis.io` in *Pinpoint.config*. Please take a look at [RedisPlugin.java](/naver/pinpoint/blob/master/plugins/redis/src/main/java/com/navercorp/pinpoint/plugin/redis/RedisPlugin.java) to see exactly what classes/methods these options control.

**Comment by majinkai** [comment]
```
profiler.redis.pipeline=false
profiler.redis=false
profiler.redis.io=false
```

it also profiling many events for `Redis`

![](http://d.pcs.baidu.com/thumbnail/9b39cfedf0adf9e95edf4aea6abcd8b8?fid=1728372403-250528-1088071903785555&time=1452567600&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-36y0g4PVYjr62KD9%2fJmXPNt54vs%3d&expires=8h&chkbd=0&chkv=0&dp-logid=266366612507080823&dp-callid=0&size=c10000_u10000&quality=90)

**Comment by majinkai** [comment]
how to using `profiler.plugin.disable=`?

**Comment by Xylus** [comment]
`profiler.plugin.disable` option is a comma sepatated string of plugin FQCNs (`com.navercorp.pinpoint.plugin.redis.RedisPlugin` for example).

This will disable the whole of redis plugin if that's what you're looking for.
