### ISSUE TITLE
what's the way of collecting the information for the collector

### ISSUE THREAD

**Issue by lcbluestorm** [naver/pinpoint#1425]
Hello, what's the data source of collector, logging ,agent report or other? What's the  data the agent report? 
thank you!

**Comment by Xylus** [comment]
Hi LCBlueStorm,
I'm not entirely sure what you're asking. If you're wondering about the persistance layer, Pinpoint uses HBase to store all our data.
Please take a look at [architecture.md](/naver/pinpoint/blob/master/doc/dev-architecture.md) for more details.

Thanks

**Comment by LCBlueStorm** [comment]
Hi Xylus, thank for your answer and I'm sorry that I have not describe my question. I mean that  how the collector collect the information,such as CallStack, Request/Response Scatter statistic ,and so on. And what's the format of data(eg: CallStack data) that collector received.

**Comment by Xylus** [comment]
It would be too long to explain everything here, so I'll instead direct you to [Technical Overview](/naver/pinpoint/wiki/Technical-Overview-Of-Pinpoint). You'll be able to get an idea of how tracing works client side.
Data collected client-side are serialized using Thrift ([Trace.thrift](/naver/pinpoint/blob/master/thrift/src/main/thrift/Trace.thrift) for trace data, [Pinpoint.thrift](/naver/pinpoint/blob/master/thrift/src/main/thrift/Pinpoint.thrift) for others such as statistics) and sent via TCP/UDP to the collector.
The collector simply stores these data into HBase, and the web reads from here to display the UI.

**Comment by LCBlueStorm** [comment]
Thank you for answering my question patiently, and I have understand a lot from your answer.

best wishes

**Comment by LCBlueStorm** [comment]
I have read Technical Overview, and I am confused about the sentence ' A Span contains TraceIds'  in  section Data Structure in Pinpoint.

**Comment by Xylus** [comment]
Which part are you confused about?
Using the [diagram](/naver/pinpoint/master/doc/img/td_figure2.png), it's safe to say that each node generates a Span when they receive a RPC, and each of these Spans will have a TraceId associated with it.

Please let me know if it's something else you're asking :)

**Comment by LCBlueStorm** [comment]
what I understand is that a Span associated with a TraceId,but the sentence 'A Span contains TraceIds' means that a Span associated with lot of TraceIds.

**Comment by Xylus** [comment]
Ah I see what you;re saying. That is indeed confusing - it should be "Each Span contains a TraceId".
Will fix it asap.

Sorry about the confusion.

**Comment by LCBlueStorm** [comment]
![td_figure2](https://cloud.githubusercontent.com/assets/7836449/12260053/7e45d986-b954-11e5-9c00-1bcb3be1936f.png)
what i circled in red represent a Traceid？And each span associate with the Traced

**Comment by Xylus** [comment]
Yes, those are the TraceIds. But in the picture above, there are 4 different TraceIds (one for each Span).

**Comment by LCBlueStorm** [comment]
A Traceid contain a TxId,a SpanId and a pSpanId? The definition of Traced is  A collections of keys consisting of TransactionIds, SpanIds, and ParentSpanIds(maybe lot of TransactionIds, SpanIds, ParentSpanIds? ).

**Comment by Xylus** [comment]
Again, those should be singular :(
Thanks for clarifying the wording.

**Comment by LCBlueStorm** [comment]
Now I can understand the term Span, Traceid. Thank you for taking the time to answer my question.
And  term Trace(one) refer to a Transaction? A Trace consist of lot of Traceids?

**Comment by Xylus** [comment]
Yes :)
To be more precise, a Trace consists of multiple Spans (and each of these Spans contains a TraceId).

**Comment by LCBlueStorm** [comment]
Yes, the precise describe is very important,especially in the communications.
