### ISSUE TITLE
Why we need to set JAVA_6_HOME and JAVA_7_HOME?

### ISSUE THREAD

**Issue by qifuren1985** [naver/pinpoint#1436]
we can define maven-compiler-plugin in pom.xml to special java version:
```xml
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>2.0.2</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

java 8 is compatible with java 7 and java 6, why we need to set JAVA_6_HOME and JAVA_7_HOME? It's ok to just define JAVA_HOME?

On Mac OS, it's difficult to define a system level environment, we must modify /etc/launchd.conf and restart system.

**Comment by lioolli** [comment]
To prevent using JDK types or methods only available from java 7 or 8. Configuring source or target version cannot prevent it.

**Comment by lioolli** [comment]
But some target libraries are compiled with java 7 compiler. To compile and test plugins for them, we need java 7 too. We don't use java 8 for this for the same reason.

**Comment by qifuren1985** [comment]
```xml
   <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>2.0.2</version>
                <configuration>
                    <source>1.6</source>
                    <target>1.6</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
        </plugins>
    </build>
```
When you define source 1.6 and target 1.6 in pom.xml, and install jdk 1.8 in system, compiler will generate java 6 class code. You can use "javap -verbose xxx.class|grep major" to check it.

**Comment by emeroad** [comment]
Compile option provides binary-compatibility.
The purpose of JAVA_$VERSION_HOME is source-level compatibility.

ex:
```java
public void souceLevelCompatibilityCheck() {
      Random random = ThreadLocalRancom.current();
      // JDK 7 -> nothing happend
      // JDK 6 ->  throw NoClassDefFoundError();
}
```
