### ISSUE TITLE
InstrumentClass need addSetter method

### ISSUE THREAD

**Issue by majinkai** [naver/pinpoint#1439]
`RabbitMQ`  `com.rabbitmq.client.AMQP$BasicProperties`
setHeader is deprecated, and headers field is `Collections.unmodifiableMap`, so i want InstrumentClass interface add method `addSetter`

**Comment by Xylus** [comment]
@majinkai 
is this issue still relevant? One possible way to go around not having a setter would be to hook the method that calls the constructor/builder of `AMQP$BasicProperties` and inject Pinpoint headers there.
Is this a possibility?

**Comment by majinkai** [comment]
```java
transformTemplate.transform("com.rabbitmq.client.impl.ChannelN", new TransformCallback() {
    @Override
    public byte[] doInTransform(Instrumentor instrumentor, ClassLoader loader, String className, Class<?> classBeingRedefined, ProtectionDomain protectionDomain, byte[] classfileBuffer) throws InstrumentException {
        InstrumentClass target = instrumentor.getInstrumentClass(loader, className, classfileBuffer);

        final InstrumentMethod method = target.getDeclaredMethod("basicPublish", "java.lang.String", "java.lang.String", "boolean", "boolean", "com.rabbitmq.client.AMQP$BasicProperties", "byte[]");
        if (method != null) {
            method.addInterceptor(PUBLISHER_INTERCEPTOR_FQCN);
        }

        return target.toBytecode();
    }
});
```

Publisher excute `basicPublish` method with `AMQP$BasicProperties`.
Maybe I am not familiar with the use of the pinpoint.

**Comment by Xylus** [comment]
Is it possible to make an interceptor for `AMQP$BasicProperties`'s constructor?
It could check the 3rd argument `Map<String, Object> headers` (@before) and if it's not null, inject Pinpoint headers here.

This would however not work for calls with null headers...

**Comment by majinkai** [comment]
```java
public BasicProperties(
            String contentType,
            String contentEncoding,
            Map<String,Object> headers,
            Integer deliveryMode,
            Integer priority,
            String correlationId,
            String replyTo,
            String expiration,
            String messageId,
            Date timestamp,
            String type,
            String userId,
            String appId,
            String clusterId)
        {
            this.contentType = contentType;
            this.contentEncoding = contentEncoding;
            this.headers = headers==null ? null : Collections.unmodifiableMap(new HashMap<String,Object>(headers));
            this.deliveryMode = deliveryMode;
            this.priority = priority;
            this.correlationId = correlationId;
            this.replyTo = replyTo;
            this.expiration = expiration;
            this.messageId = messageId;
            this.timestamp = timestamp;
            this.type = type;
            this.userId = userId;
            this.appId = appId;
            this.clusterId = clusterId;
        }
```

This is `AMQP$BasicProperties`s constructor

**Comment by Xylus** [comment]
We've looked at the code/codegen for `RabbitMQ` but couldn't find a way to inject Pinpoint headers if the headers (or `BasicProperties`) is null.

We'll add `addSetter` to our `InstrumentClass` API per your request.
Thanks :)

**Comment by majinkai** [comment]
Thanks a lot.

**Comment by Xylus** [comment]
@majinkai code has been pushed to master.
Please take a look and open up a new issue if anything's wrong.
Thanks!

**Comment by majinkai** [comment]
It working for me, and i will open new issue if anything's wrong.
Thanks a lot again.
