### ISSUE TITLE
How to call an exist method fast?

### ISSUE THREAD

**Issue by qifuren1985** [naver/pinpoint#1440]
https://github.com/naver/pinpoint-plugin-sample/tree/master/plugin/src/main/java/com/navercorp/pinpoint/plugin/sample/_09_Adding_Getter can add a getter, but If the getter method already exist, it will call the getter method or replace the getter method? 
If we want to call an exist method, we can use java reflection, but it is slow. so how can we call a method fast in pinpoint?

**Comment by Xylus** [comment]
Adding a getter method happens at class loading time, and if the getter method already exists, I think it'll throw an exception internally and won't replace the existing getter (correct me if I'm wrong).
To avoid these kind of name collisions, we usually add the `_$PINPOINT$_` prefix to the getter method.

If you would like to call an existing method (I'm assuming from within the interceptor code), you can simply cast the object to it's appropriate type and call it's methods.
For example, in [_13_RPC_Client/SendRequestInterceptor](https://github.com/naver/pinpoint-plugin-sample/blob/master/plugin/src/main/java/com/navercorp/pinpoint/plugin/sample/_13_RPC_Client/SendRequestInterceptor.java), there's a cast `TargetClass13_Request request = (TargetClass13_Request) arg0;`. We can do this safely as we already know which method the interceptor is intercepting, and the type of the parameters are known before hand.
