### ISSUE TITLE
How the agent get the data that sent to collector

### ISSUE THREAD

**Issue by lcbluestorm** [naver/pinpoint#1442]
Hi,I have a question about the way that agent collect the data. Does the agent get the data that sent to collector from the application directly or parsing the logs of application and the send to the collector ?

**Comment by Xylus** [comment]
The collector receives the data directly from the agent.

**Comment by lcbluestorm** [comment]
sorry , maybe i have not describe my question clearly. I mean that how the agent get the data from the application? directly or others ?

**Comment by lcbluestorm** [comment]
We are doing a python-version agent, which get the data from python web application,and then send the data to the collector. Do you have some good advice for this?

**Comment by Xylus** [comment]
Ah sorry I've read your question wrong.

The agent currently injects trace code into class files directly at load time through bytecode instrumentation.
I don't think this is possible in Python. Best bet would probably be to provide an SDK that exposes the trace API. If anyone more versed in Python could pitch in, that'd be great.

**Comment by lcbluestorm** [comment]
Is the agent class file? For quickstart, I just see some configuration files? How the agent send the data to the collector?

**Comment by nstopkimsk** [comment]
Have you read the technical article ? https://github.com/naver/pinpoint/wiki/Technical-Overview-Of-Pinpoint

**Comment by kapilt** [comment]
i guess i'm missing the api here, but its pretty easy to get stack trace in python at introspection points at runtime, it does have overhead though depending on number of retrievals.
