### ISSUE TITLE
Pinpoint transaction api get 500 error

### ISSUE THREAD

**Issue by ZhuWanShan** [naver/pinpoint#1474]
[Archive.zip](https://github.com/naver/pinpoint/files/98700/Archive.zip)
When I checking the transaction detail, it's say download error,  and get 500 error of 
https://apm.coupang.net/transactionInfo.pinpoint?traceId=xxx-01%5E1453279851830%5E66&focusTimestamp=1453342255828&_=1453351207437

part of error content, full error report see attachment:

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalArgumentException: invalid depth. depth=6, cursor={depth=3, child=false, sibling=false, value={spanBo=SpanBo{version=0, agentId='product-matching-01', applicationId='product-matching-api', agentStartTime=1453279851830, traceAgentId='product-matching-01', traceAgentStartTime=1453279851830, traceTransactionSequence=66, spanId=-6564382486612040205, parentSpanId=-1, startTime=1453342247820, elapsed=7828, rpc='/api/v1/matching/candidates', serviceType=TOMCAT, endPoint='product-matching-api.coupang.net:80', apiId=-1, annotationBoList=null, flag=0, errCode=1, spanEventBoList=[SpanEventBo{version=0, agentId='product-matching-01', applicationId='product-matching-api', agentStartTime=1453279851830, traceAgentId='product-matching-01', traceAgentStartTime=1453279851830, traceTransactionSequence=66, spanId=-6564382486612040205, sequence=0, startElapsed=0, endElapsed=7828, rpc='null', serviceType=SPRING, destinationId='null', endPoint='null', apiId=-2, annotationBoList=[], depth=1, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage='null'}, SpanEventBo{version=0, agentId='product-matching-01', applicationId='product-matching-api', agentStartTime=1453279851830, traceAgentId='product-matching-01', traceAgentStartTime=1453279851830, traceTransactionSequence=66, spanId=-6564382486612040205, sequence=1, startElapsed=1, endElapsed=7826, rpc='null', serviceType=SPRING_BEAN, destinationId='null', endPoint='null', apiId=-56, annotationBoList=[], depth=2, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage='null'}, SpanEventBo{version=0, agentId='product-matching-01', applicationId='product-matching-api', agentStartTime=1453279851830, traceAgentId='product-matching-01', traceAgentStartTime=1453279851830, traceTransactionSequence=66, spanId=-6564382486612040205, sequence=2, startElapsed=1, endElapsed=7825, rpc='null', serviceType=SPRING_BEAN, destinationId='null', endPoint='null', apiId=47, annotationBoList=[], depth=3, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage='null'}, SpanEventBo{version=0, agentId='product-matching-01', applicationId='product-matching-api', agentStartTime=1453279851830, traceAgentId='product-matching-01', traceAgentStartTime=1453279851830, traceTransactionSequence=66, spanId=-6564382486612040205, sequence=3, startElapsed=7283, endElapsed=0, rpc='null', serviceType=SPRING_BEAN, destinationId='null', endPoint='null', apiId=-31, annotationBoList=[], depth=6, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage='null'}, SpanEventBo{version=0, agentId='product-matching-01', applicationId='product-matching-api', agentStartTime=1453279851830, traceAgentId='product-matching-01', traceAgentStartTime=1453279851830, traceTransactionSequence=66, spanId=-6564382486612040205, sequence=4, startElapsed=7283, endElapsed=0, rpc='null', serviceType=SPRING_BEAN, destinationId='null', endPoint='null', apiId=26, annotationBoList=[], depth=7, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage='null'}, SpanEventBo{version=0, agentId='product-matching-01', applicationId='product-matching-api', agentStartTime=1453279851830, traceAgentId='product-matching-01', traceAgentStartTime=1453279851830, traceTransactionSequence=66, spanId=-6564382486612040205, sequence=5, startElapsed=7283, endElapsed=0, rpc='null', serviceType=SPRING_BEAN, destinationId='null', endPoint='null', apiId=-23, annotationBoList=[], depth=-1, nextSpanId=-1, hasException=true, exceptionId=1, exceptionMessage=''Y512M' is not a valid barcode pattern'}, SpanEventBo{version=0, agentId='product-matching-01', applicationId='product-matching-api', agentStartTime=1453279851830, traceAgentId='product-matching-01', traceAgentStartTime=1453279851830, traceTransactionSequence=66, spanId=-6564382486612040205, sequence=6, startElapsed=7283, endElapsed=0, rpc='null', serviceType=SPRING_BEAN, destinationId='null', endPoint='null', apiId=-31, annotationBoList=[], depth=6, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage='null'}, SpanEventBo{version=0, agentId='product-matching-01', applicationId='product-matching-api', agentStartTime=1453279851830, traceAgentId='product-matching-01', traceAgentStartTime=1453279851830, traceTransactionSequence=66, spanId=-6564382486612040205, sequence=7, startElapsed=7283, endElapsed=0, rpc='null', serviceType=SPRING_BEAN, destinationId='null', endPoint='null', apiId=26, annotationBoList=[], depth=7, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage='null'}, SpanEventBo{version=0, agentId='product-matching-01', applicationId='product-matching-api', agentStartTime=1453279851830, traceAgentId='product-matching-01', traceAgentStartTime=1453279851830, traceTransactionSequence=66, spanId=-6564382486612040205, sequence=8, startElapsed=7283, endElapsed=0, rpc='null', serviceType=SPRING_BEAN, destinationId='null', endPoint='null', apiId=19, annotationBoList=[], depth=-1, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage='null'}, SpanEventBo{version

**Comment by nstopkimsk** [comment]
ping @jaehong-kim
