### ISSUE TITLE
pinpoint-quickstart-collector initialization failed. pid=36373 에러가 발생합니다.

### ISSUE THREAD

**Issue by zerstyu** [naver/pinpoint#1494]
안녕하세요? 
앞에 설치 및 maven으로 pinpoint 빌드까지 모두 성공하였습니다.
start-hbase.sh, init-hbase.sh 까지도 모두 돌았고요.
하지만 ./start-collector.sh 을 입력하면 180초까지 대기하다가 컬렉터 초기화에 실패를 하게 됩니다.
구글링을 해보니 비슷한 케이스가 몇 분 계신 것 같은데, 수정해서 배포된게 아닌가요?! 
다시 확인을 해주시면 감사하겠습니다.
저는 mac os x 환경에서 작업을 하였습니다.

**Comment by zerstyu** [comment]
해당 이슈는 maven을 이용해 pinpoint를 빌드를 제대로 하지 못해 생기는 오류였습니다. 제대로 확인하지 않고 다음을 진행해버려서 생겼던 실수네요.

**Comment by yifanyou** [comment]
what u said

**Comment by DevelopDestroyer** [comment]
Hi @yifanyou 
https://github.com/naver/pinpoint/issues/5238

FYI
