### ISSUE TITLE
pinpoint-agent can not work in resin  pro

### ISSUE THREAD

**Issue by junfengcode** [naver/pinpoint#1498]
【pinpoint-version】：1.5.2-SNAPSHOT (https://github.com/naver/pinpoint/commit/ac09671a48c0b57f74a81efa05fedf7330f7965d)
【resin-version】：3.1.12 pro (http://caucho.com/products/resin/download/3.1)
【Java-version】：1.7
【error】：java.lang.ClassNotFoundException: com.navercorp.pinpoint.common.trace.TraceMetadataProvider
【resin.conf】:
<jvm-arg>-javaagent:/full/path/to/pinpoint-bootstrap.jar</jvm-arg>

it looks like about classloading ,please help ,thank you~

**Comment by nstopkimsk** [comment]
Pinpoint doesn't yet support "resin".

**Comment by junfengcode** [comment]
@nstopkimsk ，Plan to support?

**Comment by nstopkimsk** [comment]
Not yet planed. We want this plugin to be contributed.
