### ISSUE TITLE
mvn install, but pinpoint-thrift issue.

### ISSUE THREAD

**Issue by paek** [naver/pinpoint#150]
mvn install -Dmaven.test.skip=true
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] pinpoint
[INFO] pinpoint-thrift
[INFO] pinpoint-commons
[INFO] pinpoint-bootstrap-core
[INFO] pinpoint-bootstrap
[INFO] pinpoint-rpc
[INFO] pinpoint-profiler
[INFO] pinpoint-profiler-optional
[INFO] pinpoint-agent-distribution
[INFO] pinpoint-collector
[INFO] pinpoint-web
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building pinpoint 1.0.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ pom ---
[INFO] Installing /home/yello/pinpoint/pom.xml to /home/yello/.m2/repository/com/navercorp/pinpoint/pom/1.0.4-SNAPSHOT/pom-1.0.4-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building pinpoint-thrift 1.0.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ pinpoint-thrift ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] skip non existing resourceDirectory /home/yello/pinpoint/thrift/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.0:compile (default-compile) @ pinpoint-thrift ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 61 source files to /home/yello/pinpoint/thrift/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] pinpoint ........................................... SUCCESS [  0.614 s]
[INFO] pinpoint-thrift .................................... FAILURE [  0.862 s]
[INFO] pinpoint-commons ................................... SKIPPED
[INFO] pinpoint-bootstrap-core ............................ SKIPPED
[INFO] pinpoint-bootstrap ................................. SKIPPED
[INFO] pinpoint-rpc ....................................... SKIPPED
[INFO] pinpoint-profiler .................................. SKIPPED
[INFO] pinpoint-profiler-optional ......................... SKIPPED
[INFO] pinpoint-agent-distribution ........................ SKIPPED
[INFO] pinpoint-collector ................................. SKIPPED
[INFO] pinpoint-web ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.616 s
[INFO] Finished at: 2015-02-02T12:04:44+09:00
[INFO] Final Memory: 23M/965M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile (default-compile) on project pinpoint-thrift: Compilation failure -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pinpoint-thrift

**Comment by Kisung** [comment]
유사한 내용이 인것 같은데 참고하시기 바랍니다.
https://github.com/naver/pinpoint/issues/99

**Comment by paek** [comment]
Java 1.6 을 설치해야 되는건지 헷깔리네요 
Kisung님이 알려주신 쓰레드를 보더라도 내용이 잘 이해가 안가는 상황이라...

**Comment by barneykim** [comment]
readme.md를 보면 설치시 요구사항은 다음과 같습니다.
* JDK 6 installed
* JDK 7+ installed
* Maven 3.2.x+ installed
* JAVA_6_HOME environment variable set to JDK 6 home directory.
* JAVA_7_HOME environment variable set to JDK 7+ home directory.

특히 JAVA_6_HOME 환경변수는 ```pinpoint/pom.xml```에 아래와 같이 정의되어 있어서 꼭 필요합니다.
```xml
<jdk.home>${env.JAVA_6_HOME}</jdk.home>
```

**Comment by emeroad** [comment]
http://dev2.prompt.co.kr/33 
어려우시면 여길하번 참조해보세요.

**Comment by tangyong** [comment]
the same as #175
