### ISSUE TITLE
Maven Build Failing

### ISSUE THREAD

**Issue by dynamicdeploy** [naver/pinpoint#1544]
I followed the quickstart and tried to build using the mvn command. The build failed. I have attached the debug file. Any help will be helpful.
[mvnfail.txt](https://github.com/naver/pinpoint/files/137214/mvnfail.txt)

**Comment by koo-taejin** [comment]
You can see required variables (JAVA_6_HOME, JAVA_7_HOME, JAVA_8_HOME) are not set. 

please refer to pinpoint installation page. (https://github.com/naver/pinpoint#installation)

**Comment by dynamicdeploy** [comment]
Thank you. I think that should be part of the QuickStart process too. I followed the quickstart process as you guys have recommended. Will try the instructions.

**Comment by Xylus** [comment]
Glad it worked out, please feel free to let us know if there's anything lacking from the guide.
