### ISSUE TITLE
decrease log level

### ISSUE THREAD

**Issue by geek182** [naver/pinpoint#1545]
how can i reduce the log level in client (pinpoint-client) and server (pinpoint-collect/ file: catalina.out) ?My tests  are running out of space because logger are writing a lot.

thanks for all !

**Comment by Xylus** [comment]
Hi,
For the agent, the *log4j.xml* is under `$PINPOINT_AGENT/lib`.

For the collector, you can set the log level by unzipping *pinpoint-collector-$VERSION.war*, modifying *log4j.xml* under `WEB-INF/classes`, then zipping it back up as a war file (If you downloaded the binary)
If you're building from source, you can just edit *log4j.xml* under `collector/src/main/resources` before building.

Let us know if you've more questions.
Thanks!

**Comment by geek182** [comment]
Great, thank you again.
