### ISSUE TITLE
Standalone application

### ISSUE THREAD

**Issue by geek182** [naver/pinpoint#1547]
Hi,i have a standalone Java application which I would like to monitor .
The application does not run in an application server. It just has a main method which connects to a database and performs some tasks using a defined interval (cron).
i see a lot of information on client "debug mode"  but on web server dont log anything, information about server like "Heap Usage" works fine.

**Comment by Xylus** [comment]
Hi geek182,
To trace transactions, you need a starting point. For WASes, these are usually the acceptor methods where a new transaction is started when a request is received.

For standalone applications, there are no predefined starting point to start transactions so you'll need to specify them manually. The `profiler.entrypoint` option in the agent's *pinpoint.config* file allow you to do this.

For example, if you''re running some method `foo.bar.MyClass.myMethod()` in intervals using cron, specifying `profiler.entrypoint=foo.bar.MyClass.myMethod` allows the agent to start a new transaction when this method is called. Methods that are called from this method (such as DB calls) are automatically traced so you'll only need to specify the starting method.

Let us know if you have more questions.
Thanks!

**Comment by geek182** [comment]
Thanks for your support, i will try and share my results.

**Comment by dongja3** [comment]
Hi,Xylus 
I open an new question about this, can you help to answer
