### ISSUE TITLE
Access pinpoint web error:Error during WebSocket handshake

### ISSUE THREAD

**Issue by guzy** [naver/pinpoint#1550]
When I access pinpoint web in the browser, I get error:`"agent/activeThread.pinpointws' failed: Error during WebSocket handshake: Unexpected response code: 404"`

**The environment:**
web&agent&collector:release 1.5.1
Tomcat:7.0.46

**The log about web:**
```
17:14:59 DEBUG(c.n.p.r.s.PinpointServerAcceptor   :282) newPingTimeout
17:14:59 DEBUG(c.n.p.r.s.PinpointServerAcceptor   :55 ) ping write success channel:[id: 0xc2635a87, /133.133.135.180:56651 => /133.133.135.180:9997]
17:14:59 DEBUG(c.n.p.r.c.PacketDecoder            :96 ) receive pong. [id: 0xc2635a87, /133.133.135.180:56651 => /133.133.135.180:9997]
17:14:59 DEBUG(c.n.p.r.s.DefaultPinpointServer    :418) DefaultPinpointServer@2adae263 handlePingPacket() started. packet:PingPacket{pingId:2(RUN_DUPLEX)}
17:14:59 DEBUG(c.n.p.w.c.c.WebClusterAcceptor     :105) ping received PingPacket{pingId:2(RUN_DUPLEX)} DefaultPinpointServer@2adae263(remote:/133.133.135.180:56651, state:RUN_DUPLEX) 
17:14:59 DEBUG(c.n.p.r.s.DefaultPinpointServer    :55 ) pong write success. channel:[id: 0xc2635a87, /133.133.135.180:56651 => /133.133.135.180:9997]
17:19:59 DEBUG(c.n.p.r.s.PinpointServerAcceptor   :282) newPingTimeout
17:19:59 DEBUG(c.n.p.r.s.PinpointServerAcceptor   :55 ) ping write success channel:[id: 0xc2635a87, /133.133.135.180:56651 => /133.133.135.180:9997]
17:19:59 DEBUG(c.n.p.r.c.PacketDecoder            :96 ) receive pong. [id: 0xc2635a87, /133.133.135.180:56651 => /133.133.135.180:9997]
17:19:59 DEBUG(c.n.p.r.s.DefaultPinpointServer    :418) DefaultPinpointServer@2adae263 handlePingPacket() started. packet:PingPacket{pingId:3(RUN_DUPLEX)}
17:19:59 DEBUG(c.n.p.w.c.c.WebClusterAcceptor     :105) ping received PingPacket{pingId:3(RUN_DUPLEX)} DefaultPinpointServer@2adae263(remote:/133.133.135.180:56651, state:RUN_DUPLEX) 
17:19:59 DEBUG(c.n.p.r.s.DefaultPinpointServer    :55 ) pong write success. channel:[id: 0xc2635a87, /133.133.135.180:56651 => /133.133.135.180:9997]
17:24:59 DEBUG(c.n.p.r.s.PinpointServerAcceptor   :282) newPingTimeout
17:24:59 DEBUG(c.n.p.r.s.PinpointServerAcceptor   :55 ) ping write success channel:[id: 0xc2635a87, /133.133.135.180:56651 => /133.133.135.180:9997]
17:24:59 DEBUG(c.n.p.r.c.PacketDecoder            :96 ) receive pong. [id: 0xc2635a87, /133.133.135.180:56651 => /133.133.135.180:9997]
17:24:59 DEBUG(c.n.p.r.s.DefaultPinpointServer    :418) DefaultPinpointServer@2adae263 handlePingPacket() started. packet:PingPacket{pingId:4(RUN_DUPLEX)}
17:24:59 DEBUG(c.n.p.w.c.c.WebClusterAcceptor     :105) ping received PingPacket{pingId:4(RUN_DUPLEX)} DefaultPinpointServer@2adae263(remote:/133.133.135.180:56651, state:RUN_DUPLEX) 
17:24:59 DEBUG(c.n.p.r.s.DefaultPinpointServer    :55 ) pong write success. channel:[id: 0xc2635a87, /133.133.135.180:56651 => /133.133.135.180:9997]
```
**The log about agent:**
`2016-02-24 17:24:22 [DEBUG](c.n.p.p.s.UdpDataSender            :166) Data sent. size:454, TAgentStatBatch(agentId:888888, startTimestamp:1456304510182, agentStats:[TAgentStat(timestamp:1456305837869, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:30864648, jvmMemoryHeapMax:727842816, jvmMemoryNonHeapUsed:38391664, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:3, jvmGcOldTime:981), cpuLoad:TCpuLoad(jvmCpuLoad:0.0020408163265306124, systemCpuLoad:0.014285714285714285), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0)), TAgentStat(timestamp:1456305842869, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:30917632, jvmMemoryHeapMax:727842816, jvmMemoryNonHeapUsed:38391664, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:3, jvmGcOldTime:981), cpuLoad:TCpuLoad(jvmCpuLoad:0.0020408163265306124, systemCpuLoad:0.030612244897959183), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0)), TAgentStat(timestamp:1456305847869, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:30918144, jvmMemoryHeapMax:727842816, jvmMemoryNonHeapUsed:38391664, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:3, jvmGcOldTime:981), cpuLoad:TCpuLoad(jvmCpuLoad:0.0, systemCpuLoad:0.004081632653061225), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0)), TAgentStat(timestamp:1456305852869, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:30973448, jvmMemoryHeapMax:727842816, jvmMemoryNonHeapUsed:38391664, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:3, jvmGcOldTime:981), cpuLoad:TCpuLoad(jvmCpuLoad:0.0020491803278688526, systemCpuLoad:0.0020491803278688526), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0)), TAgentStat(timestamp:1456305857869, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:30973960, jvmMemoryHeapMax:727842816, jvmMemoryNonHeapUsed:38391664, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:3, jvmGcOldTime:981), cpuLoad:TCpuLoad(jvmCpuLoad:0.002036659877800407, systemCpuLoad:0.004073319755600814), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0)), TAgentStat(timestamp:1456305862869, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:31030552, jvmMemoryHeapMax:727842816, jvmMemoryNonHeapUsed:38391664, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:3, jvmGcOldTime:981), cpuLoad:TCpuLoad(jvmCpuLoad:0.0020491803278688526, systemCpuLoad:0.006147540983606557), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0))])
2016-02-24 17:24:32 [DEBUG](c.n.p.r.c.PacketDecoder            :113) received ping. sending pong. [id: 0xe0090b37, /133.133.135.180:42427 => /133.133.135.180:9994]
2016-02-24 17:24:32 [DEBUG](c.n.p.r.c.PacketDecoder            :55 ) pong write success. channel:[id: 0xe0090b37, /133.133.135.180:42427 => /133.133.135.180:9994]
2016-02-24 17:24:34 [DEBUG](c.n.p.r.c.DefaultPinpointClientHandler:236) DefaultPinpointClientHandler@75f8accb writePing() started. channel:[id: 0xe0090b37, /133.133.135.180:42427 => /133.133.135.180:9994]
2016-02-24 17:24:34 [DEBUG](c.n.p.r.c.DefaultPinpointClientHandler:55 ) ping write success. channel:[id: 0xe0090b37, /133.133.135.180:42427 => /133.133.135.180:9994]
2016-02-24 17:24:34 [DEBUG](c.n.p.r.c.PacketDecoder            :96 ) receive pong. [id: 0xe0090b37, /133.133.135.180:42427 => /133.133.135.180:9994]
2016-02-24 17:24:52 [DEBUG](c.n.p.p.s.UdpDataSender            :166) Data sent. size:454, TAgentStatBatch(agentId:888888, startTimestamp:1456304510182, agentStats:[TAgentStat(timestamp:1456305867869, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:31203024, jvmMemoryHeapMax:727842816, jvmMemoryNonHeapUsed:38392064, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:3, jvmGcOldTime:981), cpuLoad:TCpuLoad(jvmCpuLoad:0.0, systemCpuLoad:0.010183299389002035), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0)), TAgentStat(timestamp:1456305872869, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:31289992, jvmMemoryHeapMax:727842816, jvmMemoryNonHeapUsed:38392064, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:3, jvmGcOldTime:981), cpuLoad:TCpuLoad(jvmCpuLoad:0.0020491803278688526, systemCpuLoad:0.00819672131147541), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0)), TAgentStat(timestamp:1456305877869, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:31305784, jvmMemoryHeapMax:727842816, jvmMemoryNonHeapUsed:38392064, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:3, jvmGcOldTime:981), cpuLoad:TCpuLoad(jvmCpuLoad:0.002036659877800407, systemCpuLoad:0.010183299389002035), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0)), TAgentStat(timestamp:1456305882869, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:31358624, jvmMemoryHeapMax:727842816, jvmMemoryNonHeapUsed:38392576, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:3, jvmGcOldTime:981), cpuLoad:TCpuLoad(jvmCpuLoad:0.0020491803278688526, systemCpuLoad:0.004098360655737705), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0)), TAgentStat(timestamp:1456305887869, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:31361592, jvmMemoryHeapMax:727842816, jvmMemoryNonHeapUsed:38392576, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:3, jvmGcOldTime:981), cpuLoad:TCpuLoad(jvmCpuLoad:0.0020408163265306124, systemCpuLoad:0.0020408163265306124), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0)), TAgentStat(timestamp:1456305892869, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:31418240, jvmMemoryHeapMax:727842816, jvmMemoryNonHeapUsed:38392576, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:3, jvmGcOldTime:981), cpuLoad:TCpuLoad(jvmCpuLoad:0.0020408163265306124, systemCpuLoad:0.006122448979591837), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0))])`
**The log about collector:**
`02-24 17:26:36 [DEBUG](c.n.p.c.c.z.ZookeeperLatestJobWorker:176) LeakDetector Start.
02-24 17:26:52 [DEBUG](c.n.p.c.h.AgentStatHandler         :67) Received AgentStats=TAgentStatBatch(agentId:888888, startTimestamp:1456304510182, agentStats:[TAgentStat(timestamp:1456305987869, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:32503464, jvmMemoryHeapMax:727842816, jvmMemoryNonHeapUsed:38400880, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:3, jvmGcOldTime:981), cpuLoad:TCpuLoad(jvmCpuLoad:0.0020408163265306124, systemCpuLoad:0.010204081632653062), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0)), TAgentStat(timestamp:1456305992869, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:32556256, jvmMemoryHeapMax:727842816, jvmMemoryNonHeapUsed:38401536, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:3, jvmGcOldTime:981), cpuLoad:TCpuLoad(jvmCpuLoad:0.002044989775051125, systemCpuLoad:0.00408997955010225), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0)), TAgentStat(timestamp:1456305997869, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:32556768, jvmMemoryHeapMax:727842816, jvmMemoryNonHeapUsed:38401536, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:3, jvmGcOldTime:981), cpuLoad:TCpuLoad(jvmCpuLoad:0.002044989775051125, systemCpuLoad:0.00408997955010225), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0)), TAgentStat(timestamp:1456306002869, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:32612064, jvmMemoryHeapMax:727842816, jvmMemoryNonHeapUsed:38401792, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:3, jvmGcOldTime:981), cpuLoad:TCpuLoad(jvmCpuLoad:0.002036659877800407, systemCpuLoad:0.006109979633401222), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0)), TAgentStat(timestamp:1456306007869, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:32612576, jvmMemoryHeapMax:727842816, jvmMemoryNonHeapUsed:38401792, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:3, jvmGcOldTime:981), cpuLoad:TCpuLoad(jvmCpuLoad:0.0, systemCpuLoad:0.004081632653061225), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0)), TAgentStat(timestamp:1456306012869, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:32669096, jvmMemoryHeapMax:727842816, jvmMemoryNonHeapUsed:38401792, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:3, jvmGcOldTime:981), cpuLoad:TCpuLoad(jvmCpuLoad:0.0020408163265306124, systemCpuLoad:0.004081632653061225), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0))])
02-24 17:26:56 [DEBUG](c.n.p.c.h.AgentStatHandler         :67) Received AgentStats=TAgentStatBatch(agentId:666666, startTimestamp:1456304511059, agentStats:[TAgentStat(timestamp:1456305991382, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:32103896, jvmMemoryHeapMax:727842816, jvmMemoryNonHeapUsed:38389984, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:3, jvmGcOldTime:875), cpuLoad:TCpuLoad(jvmCpuLoad:0.002044989775051125, systemCpuLoad:0.010224948875255624), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0)), TAgentStat(timestamp:1456305996382, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:32159456, jvmMemoryHeapMax:727842816, jvmMemoryNonHeapUsed:38389984, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:3, jvmGcOldTime:875), cpuLoad:TCpuLoad(jvmCpuLoad:0.002036659877800407, systemCpuLoad:0.004073319755600814), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0)), TAgentStat(timestamp:1456306001382, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:32159936, jvmMemoryHeapMax:727842816, jvmMemoryNonHeapUsed:38389984, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:3, jvmGcOldTime:875), cpuLoad:TCpuLoad(jvmCpuLoad:0.0020408163265306124, systemCpuLoad:0.004081632653061225), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0)), TAgentStat(timestamp:1456306006382, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:32217976, jvmMemoryHeapMax:727842816, jvmMemoryNonHeapUsed:38390240, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:3, jvmGcOldTime:875), cpuLoad:TCpuLoad(jvmCpuLoad:0.0, systemCpuLoad:0.00408997955010225), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0)), TAgentStat(timestamp:1456306011382, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:32223448, jvmMemoryHeapMax:727842816, jvmMemoryNonHeapUsed:38390240, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:3, jvmGcOldTime:875), cpuLoad:TCpuLoad(jvmCpuLoad:0.002036659877800407, systemCpuLoad:0.004073319755600814), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0)), TAgentStat(timestamp:1456306016382, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:32279024, jvmMemoryHeapMax:727842816, jvmMemoryNonHeapUsed:38390240, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:3, jvmGcOldTime:875), cpuLoad:TCpuLoad(jvmCpuLoad:0.002044989775051125, systemCpuLoad:0.010224948875255624), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0))])`

The screenshot is:
http://chuantu.biz/t2/28/1456306304x1965191027.jpg
http://chuantu.biz/t2/28/1456306330x1965191027.jpg
Thanks。

**Comment by koo-taejin** [comment]
A 404 Not Found Error means that the webpage simply does not exist with the URL entered.

If error message occurs while whole situation. then you need to check state of pinpoint-web.

Just occurs while to use websocket. 
I recommend to check http proxy server (ex) niginx, apache) in front of WAS. 
Each WAS is needed additional configuration to use http proxy server as a websocket proxy. 

please check it. thanks.
