### ISSUE TITLE
BUG: cannot compile 1.5.1

### ISSUE THREAD

**Issue by hamlet-lee** [naver/pinpoint#1556]
JAVA_6_HOME=d:/Java/jdk1.6.0_14
JAVA_7_HOME=d:/Java/jdk1.7.0_79
JAVA_8_HOME=d:/java/jdk1.8.0_65

mvn package -DskipTests=true

error message
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile (default-compile) on project pinpoint-bootstrap-core: Compilation failure: Compilation failure:
[ERROR] D:\Code\pinpoint\bootstrap-core\src\main\java\com\navercorp\pinpoint\bootstrap\instrument\GuardInstrumentContext.java:[66,44] 无法确定 <T>java.lang.Class<? extends T> 的类型参数；对于上限为 T,java.lang.Object,java.lang.Object 的类型变量 T，不存在唯一最大实例
[ERROR] D:\Code\pinpoint\bootstrap-core\src\main\java\com\navercorp\pinpoint\bootstrap\instrument\InstrumentorDelegate.java:[59,44] 无法确定 <T>java.lang.Class<? extends T> 的类型参数；对于上限为 T,java.lang.Object,java.lang.Object 的类型变量 T，不存在唯一最大实例
[ERROR] D:\Code\pinpoint\bootstrap-core\src\main\java\com\navercorp\pinpoint\bootstrap\instrument\GuardInstrumentor.java:[64,44] 无法确定 <T>java.lang.Class<? extends T> 的类型参数；对于上限为 T,java.lang.Object,java.lang.Object 的类型变量 T，不存在唯一最大实例
```

it can be translated to as: cannot decide the type argument of <T>java.lang.Class<? extends T> ; to the upper bound T,java.lang.Object,java.lang.Object 's type variable T, don not have a single maximum instance

**Comment by emeroad** [comment]
Do not use older JDK version.
I suggest  **Java SE Development Kit 6u45** version
 - http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase6-419409.html

**Comment by hamlet-lee** [comment]
thanks for your response!
I just found updating jdk1.6 to jdk1.6_45 works.
suggest you update the document of the project to explicitly require this version of jdk1.6

**Comment by nstopkimsk** [comment]
Thanks. 
I updated document that you suggested.
