### ISSUE TITLE
pinpoint-web-1.0.5 log error

### ISSUE THREAD

**Issue by goddessgod** [naver/pinpoint#1559]
hbase-0.94,pinpoint-1.0.5
the hbase run properly,the collector and web can startup  properly,
but the web log info:
Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (java.lang.SecurityException: 无法定位登录配置)

I can telent the localhost/127.0.0.1 2181.I can't find where the configuration is wrong。

**Comment by koo-taejin** [comment]
Error message shown when zookeeper do not use SASL authentication.
You can ignore message if additional error message not shown. 

* normal situation
```
[main-SendThread(localhost:2181)] zookeeper.ClientCnxn: Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
[main-SendThread(localhost:2181)] zookeeper.ClientCnxn: Socket connection established to localhost/127.0.0.1:2181, initiating session
```

* abnormal situation
```
[main-SendThread(localhost:2181):ClientCnxn$SendThread@975] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
[main-SendThread(localhost:2181):ClientCnxn$SendThread@1102] - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) 
        ...
```

thanks.

**Comment by goddessgod** [comment]
Thanks a lot.I have another question ,wheen the pinpoint support jboss server ?

**Comment by koo-taejin** [comment]
Unfortunately, I don't know when will Pinpoint support jboss plugin.  :sob:

please refer to it(#972).
