### ISSUE TITLE
Could Pinpoint trace multi-thread application?

### ISSUE THREAD

**Issue by peterxuxin** [naver/pinpoint#1572]
........................-----Req1----->  **HandleThread A**  -----Resp1----->  ......................
**RecvThread**................................................................................**SendThread** 
........................-----Req2----->  **HandleThread B**  -----Req2----->   ......................
RecvThread receives requests and puts them in a RecvMsgQueue(maybe just store some business data), and then HandleThreads will get message from RecvMsgQueue, at last the SendThread gets response messages from a SendMsgQueue and sends out.

Could Pinpoint trace the Req1 and Req2 as follow:
RecvThread_Method
........|
........|---- HandleThread Method
......................|
......................|---- SendThread Method

**Comment by Xylus** [comment]
As you've probably noticed, trace objects are stored in thread locals so they cannot automatically cross thread boundaries. That said, we can and do trace multi-threaded libraries using plugins (check [these](https://github.com/naver/pinpoint-plugin-sample/tree/master/plugin/src/main/java/com/navercorp/pinpoint/plugin/sample/_12_Asynchronous_Trace) out).

If you were to trace what you've described above, you could write a plugin that injects an async trace id into the Req object, and passes it over to the Recv, Handle, Send methods.

**Comment by peterxuxin** [comment]
OK. I will try it.
Thanks.
