### ISSUE TITLE
I want to get the  stack information of  method invocation.If there were any relevant methods?

### ISSUE THREAD

**Issue by Aaron-liuzl** [naver/pinpoint#1593]
If I do not use the plugin.if I can monitor all of the the class and get all the  method call information?

**Comment by Xylus** [comment]
Hi liuzl0218,
You can trace your own methods/classes by adding them to `profiler.include` or `profiler.entrypoint` in [pinpoint.config](https://github.com/naver/pinpoint/blob/master/agent/src/main/resources/pinpoint.config).
Please take a look at #1567 for more details.

Thanks!
