### ISSUE TITLE
How can i get all of the class from jvm with pinpoint?

### ISSUE THREAD

**Issue by Eilikce** [naver/pinpoint#1600]
How can i get all of the class in jvm?
I'm thinking about how the pinpoint get all of the userWebApp's class .
I'd like to make a plugin to intercept all methods of my WebApp .
by the way , is that will use much properties?

**Comment by Xylus** [comment]
Hi Eilikce,
Intercepting all methods in an application would be way too heavy and unnecessary (as most of the methods will be simply be internal method calls).
We do have an option to trace user-specified classes and methods already if that's what you're wondering.

**Comment by Eilikce** [comment]
Hi Xylus ,
I think i can make a new plugin to do this ,so I need the whole className from webApp. I have seen that pinpoint has got all of the className . Is there a way to get all of the classname from the webApp that pinpoint has got when I write my own plugin ?
