### ISSUE TITLE
why i can't find my test-app in the select of pinpoint-web?

### ISSUE THREAD

**Issue by bigsnapdragon** [naver/pinpoint#1601]
pinpoint、collector and web all builded in Eclipse and running,but why i can't find my test-app in the select combobox？
hbase.client.host=127.0.0.1
Moreover, -javaagent has configured as follows:

![t2](https://cloud.githubusercontent.com/assets/17841615/13766202/ccc837da-ea9a-11e5-81ed-d01765a86bf2.png)

![tu1](https://cloud.githubusercontent.com/assets/17841615/13766232/0bfd8f22-ea9b-11e5-8786-f89b9c41a78c.png)

**Comment by Xylus** [comment]
Hi bigsnapdragon,
We'll need more information to figure this one out. It could be due to a number of reasons, but let's start with the agent first (agent -> collector connection).

Could you check the agent log for any error? Or you could paste the log here.

**Comment by bigsnapdragon** [comment]
Thank you for your help! I had solved my question.  The question is: I run pinpoint-web used with eclipse, and the project name has no change. now i put pinpoint-web into the path:tomcat\webapps\ROOT\,  them I succed!
