### ISSUE TITLE
Does the pinpoint support an SQL statements of all SQL calls captured in the trace

### ISSUE THREAD

**Issue by guanlele** [naver/pinpoint#1604]
Can we configure pinpoint's transaction tracing feature to record slow SQL ?
@Xylus

**Comment by Xylus** [comment]
Hi guanlele, sorry for the late reply.
Are you looking for something like listing out top x slowest RPCs, or database queries?
If this is the case, we don't have this just yet, but we've started looking into this.
We'll let you know once we have something solid.

Thanks.

**Comment by guanlele** [comment]
Get it ,thanks for your reply.
