### ISSUE TITLE
Collect service information for Spring Boot applications

### ISSUE THREAD

**Issue by Xylus** [naver/pinpoint#1621]
Service information (loaded libraries) are not collected for Spring Boot applications except for cases where they are packaged as *war* files and are loaded on a container (such as Tomcat).

A lot of Spring Boot applications are run as an executable jar (or war), so it would be useful to collect these information in these cases as well.

**Comment by bwzhang2011** [comment]
+1, nice feature. as many projects prefer spring boot for integration.
