### ISSUE TITLE
the structure of tables storaged in hbase

### ISSUE THREAD

**Issue by liuzl0218** [naver/pinpoint#1632]
Hello,I saw 20 tables in hbase, like Traces,AgentEvent,HostApplicationMap and so on. But I can not understand totally the meaning of the tables.Is there some documents for the tables?
  Thank you!

**Comment by minwoo-jung** [comment]
Please ref to https://github.com/naver/pinpoint/blob/master/hbase/scripts/README.md.
We described them.

**Comment by liuzl0218** [comment]
Traces : Table for traced transactions
Whether can detailed introduction Traces?How to store the data.
Thank you.

**Comment by nstopkimsk** [comment]
You can refer the wiki (  https://github.com/naver/pinpoint/wiki ).
Plugin Development Guide and Technical Overview.
