### ISSUE TITLE
Have you some logical model about the data storaged in HBase?

### ISSUE THREAD

**Issue by bigsnapdragon** [naver/pinpoint#1633]
How about the data of pinpoint storaged in HBase? Have you some logical model?

**Comment by minwoo-jung** [comment]
We don't quite get what kind of logical model you're looking for.

But you could take a look at:
1. Schema ref : https://github.com/naver/pinpoint/blob/master/hbase/scripts/README.md
2. If you want to look at what is stored in which table, you should take a look at collector and web DAOs

You can probably figure out the overall data flow from above.
