### ISSUE TITLE
The transactionId printed in the log message

### ISSUE THREAD

**Issue by vwyuheng** [naver/pinpoint#1635]
When I am in accordance with this configuration,  didn't show up the log button，why？

1.first modified pinpoint.config log4j=true
   
2.pinpoint agent lib log4j.xml add
<param name = "ConversionPattern" value= "%d{yyyy-MM-dd HH:mm:ss} [%-5p](%-30c{1}) [TxId : %X{PtxId} , SpanId : %X{PspanId}] %m%n" />
3.modified pinpoint web config.
log.enable=true
log.page.url=translog.pinpoint
log.button.name=log

start web ,idn't show up the log button to me, why?

**Comment by minwoo-jung** [comment]
Please ref guide : https://github.com/naver/pinpoint/blob/master/doc/per-request_feature_guide.md
 3. expose log in Pinpoint web

Log button position moved lastest version.
![pinpoint_log_button](https://cloud.githubusercontent.com/assets/4557258/13914044/3aceb5e4-ef8f-11e5-8a98-627e715283c9.jpg)

we will change image in guide.

**Comment by vwyuheng** [comment]
tnks,This problem has been resolved, but When the log is written to the file how to position to the line, how are you  solve it?

**Comment by minwoo-jung** [comment]
Please refer log framework configuration. If you use log4j, you shoud PatternLayout configuration.

**Comment by wingyiu** [comment]
profiler.sampling.rate=1
