### ISSUE TITLE
Is PinPoint only use Thrift to compress the data ?

### ISSUE THREAD

**Issue by Eilikce** [naver/pinpoint#1640]
There is a doubt that how does Pinpoint use the Thrift ? I have read Command.thrift , Pinpoint.thrift and shared.thrift in the project , but I didn't find any 'service' in the script . I can't find the TSocket be used in the project except of the Plugins . 
Is that means PinPoint does not use the Thrift to implement RPC ? Is Pinpoint only use the Thrift's CompactProtocol to compress the data ?
Thanks for Pinpoint Team

**Comment by Xylus** [comment]
Hi Eilikce,
you're absolutely correct. We only use Thrift internally for data compression. We wrap this with custom header before sending off to the collector. The collector mirrors this by using Thrift for the final decompression of the received data.

**Comment by Eilikce** [comment]
@Xylus 
Thanks a lot .I'm just waiting the answer online .
