### ISSUE TITLE
We need to use some technology to replace the parts in the pinpoint

### ISSUE THREAD

**Issue by liuzl0218** [naver/pinpoint#1647]
![Uploading 1.JPG…]()
As shown in figure：
1.We use the pinpoint agent acquisition tracking data.I have modified the part of the agent code to make sure that I can monitor all of the classes and get all the information method call.
2.We use a Spark Streaming replace pinpiont colloector, to complete the processing of data.
3.We use ElasticSearch to store data, because it can quickly retrieve and gathering data.
4.To make the above changes, is to give the user the present gathering data and reports.
If you can give some advice, we do so is reasonable? 
Thank you!

**Comment by emeroad** [comment]
Pinpoint is an open source software.
Do whatever you want.
