### ISSUE TITLE
If pinpoint could catch the Execption from my webApp?

### ISSUE THREAD

**Issue by Eilikce** [naver/pinpoint#1656]
If Pinpoint could intercept the Execption from the webApp?Such as the Execptions thrown by JAVA and 400,500 errors when we request the web page.
I want to use pinpoint to catch the Exceptions and use these imformation .

Thanks for your team

**Comment by Xylus** [comment]
Hi Eilikce,
We don't do anything with exceptions thrown inside an application. We simply record them if they are propagated up to a method we're tracing.

Is there anything you would like to do with the exceptions you catch in particular?

**Comment by Eilikce** [comment]
Hi Xylus,
I just want get the record from my webApp . I had saw that pinpoint record the Java Exceptions ,but I didn't find the 400 , 404 or 500 errors be recorded by pinpoint when I request the webApp page . If pinpoint can record such as 500 errors and show on the pinpoint-web ?

Thanks for your help
