### ISSUE TITLE
We want to develop a plug-in, monitor tongweb

### ISSUE THREAD

**Issue by Aaron-liuzl** [naver/pinpoint#1675]
hello,
Tongweb is similar to the Tomcat server.Tongweb comes from TomEE.
We want to develop a plugin monitoring tongweb.
We find the corresponding class in tongweb and tomcat.Now, we are by modifying the tomcat plug-in in the class and method.
For example:
  1.org.apache.catalina.startup.Bootstrap
  2.RequestFacade
  3.org.apache.catalina.connector.Request
  4.org.apache.catalina.core.StandardHostValve
  5.org.apache.catalina.core.StandardService
  6.org.apache.catalina.connector.Connector
  7.org.apache.catalina.loader.WebappLoader
  8.org.apache.catalina.core.AsyncContextImpl
We replaced the above eight classes,but we don't see the relevant data in the web.Data is not into hbase or why we can't see the data?

**Comment by Xylus** [comment]
Hi liuzl0218,
It's difficult to figure out what's wrong without more information, especially without access to Tongweb, or the plugin source.

Take a look at the agent log for some clues on what's not working. You could also post the agent log here if you can so we can take a look at it to maybe give some pointers.

Also, please do take a look at our [plugin development guide](https://github.com/naver/pinpoint/wiki/Pinpoint-Plugin-Developer-Guide) if you haven't already.
Thanks!
