### ISSUE TITLE
Missing agent configuration for monitoring PostgreSQL database and inspection problems

### ISSUE THREAD

**Issue by guindous** [naver/pinpoint#1678]
Hi! I'm testing Pinpoint 1.5.2 monitoring an application that uses PostgreSQL as DBMS. Then I'm confused about the agent configuration. 
In agent pinpoint.config file there is no example section in relation with postgres. There is described configuration about MySQL, MariaDB, MSSQL, Oracle, CUBRID, DBCP and CASSANDRA. So looking the Postgres plugin source code and following the others dbms convention added this lines to pinpoint.config: 

```
profiler.jdbc.postgresql=true
profiler.jdbc.postgresql.setautocommit=true
profiler.jdbc.postgresql.commit=true
profiler.jdbc.postgresql.rollback=true
```

Then I started to monitor information about the app but pinpoint-web doesn't detect Postgres correctly. Shows "unknown^UNKNOWN_DB" in the main window. Then when I inspect a transaction I can see information about SQL queries for class "AbstractJdbc2Connection" but API says "UNKNOWN_DB(unknown)".

Is Postgres plugin working? Is a JDBC url plugin detection problem? Is a configuration issue?

Thanks for your support.

**Comment by nstopkimsk** [comment]
@lioolli Could you dig this ?

**Comment by michael-ancestor** [comment]
same problem........;-(

**Comment by michael-ancestor** [comment]
I'm solved~;-)

**Comment by guindous** [comment]
@michael-ancestor could you please tell us how do you solve it?

**Comment by michael-ancestor** [comment]
@guindous 
1.change postgresql jdbc driver ( Use 9.4.1208) 
 (https://github.com/pgjdbc/pgjdbc)
2.According to the mysql plugin,Rewrite the plugin
(Tip.Use PGStatement、PgStatement etc,.)

**Comment by pparth** [comment]
+1 . Same problem here.

**Comment by nstopkimsk** [comment]
@breadval Could you solve this issues?

**Comment by michael-ancestor** [comment]
1.change postgresql jdbc driver. ( Use 9.4.1208) 
(https://github.com/pgjdbc/pgjdbc)
2.According to the mysql plugin,Rewrite the plugin
(Tip.Use PGStatement、PgStatement etc,.)










At 2016-05-09 19:50:51, "guindous" <notifications@github.com> wrote:


@michael-ancestor could you please tell us how do you solve it?

**Comment by breadval** [comment]
@nstopkimsk I'm afraid that I don't hv enough time. I'll estimate my schedule.

**Comment by michael-ancestor** [comment]
@breadval 
Hi,my way is : 
1.change postgresql jdbc driver. ( Use 9.4.1208)
(https://github.com/pgjdbc/pgjdbc)
2.According to the mysql plugin,Rewrite the plugin
(Tip.Use PGStatement、PgStatement etc,.)

**Comment by breadval** [comment]
@guindous @pparth 
Which version of postgresql jdbc driver do you use?

Like @michael-ancestor said, I think you need to change jdbc version.
I've tested 9.3-1102-jdbc4 version.

**Comment by michael-ancestor** [comment]
@breadval I've tested pinpoint-1.5.2, [pom.xml] "postgresql jdbc driver" --> 9.1-901-1.jdbc4.
so,I has modified [com.navercorp.pinpoint.plugin.jdbc.postgresql.interceptor.PostgreSQLConnectionCreateInterceptor]
change point:
    // TODO [9.1-901-1.jdbc4] not found HostSpec[]
<img width="829" alt="2016-05-11 2 58 11" src="https://cloud.githubusercontent.com/assets/15785617/15172522/2bee699e-1789-11e6-8a06-69c62465d8eb.png">

    //@TargetConstructor({ "org.postgresql.util.HostSpec[]", "java.lang.String", "java.lang.String", "java.util.Properties", "java.lang.String" })

// TODO ADDED BY michael-ancestor
@TargetConstructor({ "java.lang.String", "int", "java.lang.String", "java.lang.String", "java.util.Properties", "java.lang.String" })

**Comment by guindous** [comment]
@breadval I'm using postgresql-9.1-902.jdbc3.jar . I will test 9.3-1102-jdbc4 and confirm if this fixes the problem. Anyway, default agent configuration file should include postgresql configuration options, isn't it? If you want, I could do a Pull Request with it.

**Comment by breadval** [comment]
@michael-ancestor thnx for your info. could you do a pull request? @guindous thnx, plz pull request.

**Comment by michael-ancestor** [comment]
@breadval ok, but .. I'm busy these days,but I won't forget submitting. ;-)

**Comment by guindous** [comment]
@michael-ancestor Did you do a pull request? So the issue could be closed. Thnx!
