### ISSUE TITLE
I got a 404 when I try to download the "hbase-create.hbase" file according to the  installation guide.

### ISSUE THREAD

**Issue by hxnan** [naver/pinpoint#1689]
I got a 404 when I try to download the "hbase-create.hbase" file according to the  installation guide.
The url is https://github.com/naver/pinpoint/blob/master/scripts
I fail to find this file in other dirs...
```
Creating Schemas

There are 2 scripts available to create tables for Pinpoint: hbase-create.hbase, and hbase-create-snappy.hbase. Use hbase-create-snappy.hbase for snappy compression (requires snappy), otherwise use hbase-create.hbase instead.

To run these scripts, feed them into the HBase shell like below:

$HBASE_HOME/bin/hbase shell hbase-create.hbase

See here for a complete list of scripts.
```

**Comment by nstopkimsk** [comment]
@koo-taejin please check this.

**Comment by hxnan** [comment]
Solve.
The current url is:
 https://github.com/naver/pinpoint/blob/master/pinpoint/hbase/scripts/

Maybe somebody can update the url in doc.

**Comment by koo-taejin** [comment]
I updated url. Thanks for reporting! :)
