### ISSUE TITLE
Support ActiveMQ java client

### ISSUE THREAD

**Issue by Xylus** [naver/pinpoint#1709]
Add plugin to support ActiveMQ java client tracing.

Queue / Topic names will be used for virtual queue nodes.

Initial implementation supports v5.1.0+ and clients that connect using TCP based transport (so embedded queues that are connected via VM transports are not traced).

Trace methods might need to be more detailed (such as for redeliveries and transactions/rollbacks. These should be added in the future if deemed important.

**Comment by dawidmalina** [comment]
@Xylus when do you plan to merge your changes to master branch?

**Comment by Xylus** [comment]
@dawidmalina Ironing out some issues, should be in there by tomorrow :)

**Comment by ruizlake** [comment]
i have some problem whit activemq plugin , icon of activemq cannot display 
![image](https://cloud.githubusercontent.com/assets/10740595/15203738/1a5ed87a-1839-11e6-9b8f-f61466dea981.png)

**Comment by Xylus** [comment]
@ruizlake looks like the image is missing. Could you check if you can access $PINPOINT_WEB_URL/images/servermap/ACTIVEMQ_CLIENT.png?

**Comment by ruizlake** [comment]
yes. i can access $PINPOINT_WEB_URL/images/servermap/ACTIVEMQ_CLIENT.png. but still it no working.All the configuration in accordance with the way you write https://github.com/Xylus/pinpoint/commit/0317a98996573a96bfecfc241ddc7c31ddab3361

**Comment by Xylus** [comment]
Looks like the minified version of js files were not committed, and I'm not sure if these need to be merged into the repository. I'll check with @denzelsN and add them if necessary.

In the mean time, you could make the following changes to manually update them:
```
in pinpoint.min.js, change
a.isWas===!1&&"USER"!==a.serviceType
to
a.isWas===!1&&a.isQueue===!1&&"USER"!==a.serviceType

in pinpoint-component.min.js, change
htIcons:{APACHE:"APACHE.png"
to
htIcons:{ACTIVEMQ_CLIENT:"ACTIVEMQ_CLIENT.png",APACHE:"APACHE.png"
```

Let me know if this doesn't work.

**Comment by ruizlake** [comment]
thank you very much! it success. i love you *_*

**Comment by Xylus** [comment]
@ruizlake Glad it worked out :)
Also, if you update the Web code to 1.6.0-SNAPSHOT (the current master), it should just work without the modification above.
Please give it a try and let us know if it doesn't work.

**Comment by ruizlake** [comment]
ok.If found in the use of bug, I will be the first time to reply to you. thanks again

**Comment by ruizlake** [comment]
With your help, I developed a plug-in called rocketmq.if you want i will show about this plugin
