### ISSUE TITLE
Why Search duration may not be greater than 2 days?

### ISSUE THREAD

**Issue by hxnan** [naver/pinpoint#1743]
Why Search duration may not be greater than 2 days?
If there is a great performmance hdfs , which configure I can modify to get a larger duration?

**Comment by Xylus** [comment]
Hi hxnan,
We limited the search duration to 2 days as we felt that the query time was taking a bit too long for complex services with extremely high request count.
However, if you'd like to allow for a larger duration, you could modify the limit in `DateLimiter.java` in the web module. This will allow you to search for a larger duration when querying with custom duration.

**Comment by hxnan** [comment]
Thanks a lot！
