### ISSUE TITLE
Eclipse remote debug problem

### ISSUE THREAD

**Issue by FishGel** [naver/pinpoint#1745]
After add pinpoint agent, when using eclipse remote debug , I cannot inspect the value of variables.
When I try to do so, I get the following error:

```
- "com.sun.jdi.InternalException: Got error code in reply:35 occurred retrieving 'this' from stack frame."
```

![image](https://cloud.githubusercontent.com/assets/7518880/15044302/561e3f0a-1306-11e6-801c-e69092a50f5c.png)

Below it's my test environment's tomcat config.

![2dc22e1a-697f-4d27-b797-78c36dc6beae](https://cloud.githubusercontent.com/assets/7518880/15044619/67f0c5e8-1308-11e6-8c27-6f44126a61f5.png)
IF I want to debug，only to remove the pinpoint agent config , any other way？

**Comment by emeroad** [comment]
Pinpoint changes the bytecode, It seems to cause debug problems.

**Comment by FishGel** [comment]
@emeroad  yes
