### ISSUE TITLE
BoF OSCON 2016 @Austin

### ISSUE THREAD

**Issue by Xylus** [naver/pinpoint#1754]
We're holding a Birds of a Feather session on May 18th 7pm in Meeting Room 5.

If anyone from the community is headed to Austin for OSCON and wishes to stop by, please let us know!
Feel free to post any questions you want so we can come prepared.

**Comment by nstopkimsk** [comment]
[pinpoint_OSCON_BoF.pdf](https://github.com/naver/pinpoint/files/265930/pinpoint_OSCON_BoF.pdf)

**Comment by Xylus** [comment]
Done!
