### ISSUE TITLE
Can the pinpoint-collector installation as cluster ?

### ISSUE THREAD

**Issue by Eilikce** [naver/pinpoint#1771]
Can the pinpoint-collector installation as cluster ?

I have found there is not only one pinpoint-collector in the Architecture image . The pinpoint-collector looks like a cluster.
I got some information from the pinpoint-collector.properties , but it seemed not what I want .

thanks for your team

**Comment by nstopkimsk** [comment]
@Eilikce please refer to https://groups.google.com/forum/#!searchin/pinpoint_user/collector/pinpoint_user/ff-Ufyl8Zvk/zCqCfKucBAAJ
