### ISSUE TITLE
Pinpoint   performance issues 

### ISSUE THREAD

**Issue by miaoxinchen123** [naver/pinpoint#1772]

**Comment by miaoxinchen123** [comment]
Our organisation had a performance test on pinpoint . If i put the pinpoint-collector and pinpoint-web in the same server of   the application . pinpoint used a lot of memory of the server .so can i deploy pinpoint-collector and pinpoint-web in the same server of application?

**Comment by emeroad** [comment]
Pinpiont team need a more detailed data and detailed environment.
We do not know what the problem.

**Comment by Xylus** [comment]
Probably not the best idea to put the collector and web all in the same server of the application that is being profiled. Both the collection and web serve multiple applications so it'd be best to keep them separate.
Or were you asking something else?

**Comment by jiaqifeng** [comment]
In my test, collector used 13G memory when pressure is a little high. So it's better to deploy pinpoint collector on another machine.
