### ISSUE TITLE
Can the pinpoint support struts ?

### ISSUE THREAD

**Issue by Eilikce** [naver/pinpoint#1776]
I have find that Spring is wrote in the Pinpoint Supported Modules , so could the Pinpoint support Struts ?
Or is there any plugin witch could make Pinpoint support struts ?

Thanks for your team

**Comment by emeroad** [comment]
Unfortunately, Pinpoint Team has no plan to support struts.

**Comment by Eilikce** [comment]
Oh , it seems that I have to find another way for my project .
