### ISSUE TITLE
quickstart/bin/start-hbase.sh error

### ISSUE THREAD

**Issue by fuchun** [naver/pinpoint#1784]
quickstart/bin/start-hbase.sh

HBase already installed. Starting hbase...
Error: Could not find or load main class org.apache.hadoop.hbase.util.HBaseConfTool
Error: Could not find or load main class org.apache.hadoop.hbase.zookeeper.ZKServerTool
starting master, logging to /data/pinpoint/quickstart/hbase/hbase-1.0.3/bin/../logs/hbase-root-master-AY1211020841143c65372.out
Error: Could not find or load main class org.apache.hadoop.hbase.master.HMaster
starting regionserver, logging to /data/pinpoint/quickstart/hbase/hbase-1.0.3/bin/../logs/hbase-root-1-regionserver-AY1211020841143c65372.out
Error: Could not find or load main class org.apache.hadoop.hbase.regionserver.HRegionServer

**Comment by rakesh0991** [comment]
Hi,
      i am getting same error.any update on this?

**Comment by boyunli** [comment]
I meet some question， anyone knows ...
