### ISSUE TITLE
Error retrieving main class from com.navercorp.pinpoint.common.util.SystemProperty

### ISSUE THREAD

**Issue by hxnan** [naver/pinpoint#1801]
I install a pinpoint-agent in SUSE LINUX 11;
The Agent can run ,the server can get data too;
But some error log has been found:
"Error retrieving main class from com.navercorp.pinpoint.common.util.SystemProperty"
.......
(c.n.p.p.i.URLClassLoaderHandler :66)Failed to load plugin class com.navercorp.pinpoint.plugin.spring.beans.interceptor.CreateBeanInstanceInterceptor with classLoader WebappClassLoader

**Comment by Xylus** [comment]
Hi hxnan,
The error's a WARN log saying the agent couldn't retrieve the main class from system properties. This usually happens on Java 1.6.0_24 or earlier versions (or if non Hotspot JVM is used)
The second issue will need further analysis.

Could you tell us your environment with a bit more detail? Java version/vendor, the type of application you're running etc.

**Comment by hxnan** [comment]
@Xylus 
I run pinpoint in tomcat server
```
Tomcat version: 7.0.61

Java version "1.8.0_71"
java (TM) SE Runtime Environment( build 1.8.0_71-b15)
Java HotSpot( TM) 64-Bit Server VM( build 25.71-b15, mixed mode)

$JAVA_HOME : /usr/java/jdk
```

**Comment by Xylus** [comment]
The application should be working without issue, not sure why it's not working.
Could you check the agent log and see if there's a system property with key "sun.java.command"?
The log should be 
```
[INFO ](c.n.p.p.DefaultAgent               :267) SystemProperties sun.java.command=abc
```
Also, you've added the vm arguments (-javaagent, -Dpinpoint.agentId, -Dpinpoint.applicationName) to *catalina.sh* file and used it to start Tomcat, right?

**Comment by hxnan** [comment]
@Xylus 
I think you get the point.
I find many info like :
```
[INFO ](c.n.p.p.DefaultAgent               :268) SystemProperties java.runtime.name=Java(TM) SE Runtime Environment
[INFO ](c.n.p.p.DefaultAgent               :268) SystemProperties sun.boot.library

```

But i can not find "SystemProperties sun.java.command".
Is there something wrong with the system environment PATH?

**Comment by hxnan** [comment]
@Xylus 
Close this issue pls .
I 'm sorry for my foolish.....
The folder of pinpoint-agent should be “chmod 755 -R ”

and pinpoint working correct right now.

**Comment by Xylus** [comment]
Awesome! Glad it worked out :)
Let us know if you have more question.
Thanks.
