### ISSUE TITLE
[Question]about pinpoint agent  

### ISSUE THREAD

**Issue by tangyong** [naver/pinpoint#181]
(I am sorry that maybe should not send the question here, but I can not login googlegroup)

about pinpoint agent  , I have some questions as following:

1 apart from tomcat, pinpoint agent can be attached into other appserver such as wildfly, webshpere,...

2 if my distributed app uses redis, mq..., these components's performance data can be collected too?

Thanks!

**Comment by nstopkimsk** [comment]
not yet support all you asked.  can you contribute that?
