### ISSUE TITLE
adding document for two systems interaction

### ISSUE THREAD

**Issue by tangyong** [naver/pinpoint#182]
Team,

I think that current quick-start is not enough for describing  two or more systems interaction. I request adding document to describe how to deploy and collect data from two systems with interaction, then, show the two systems's call relationship and call performance. 

For example,

System A depeneds on System B:  A--->B , then, deploying them into tomcat, at the time,  -Dpinpoint.agentId  and  -Dpinpoint.applicationName   should be what? ...

**Comment by nstopkimsk** [comment]
we are making the video clips that will include what you said.
thanks!!

**Comment by nstopkimsk** [comment]
I added video clip at https://github.com/naver/pinpoint/wiki.
