### ISSUE TITLE
Realtime Active Thread Chart 활성화시 따로 설정을 해주어야 하나요?

### ISSUE THREAD

**Issue by TaeSeong** [naver/pinpoint#1842]
![pinpoint](https://cloud.githubusercontent.com/assets/7597961/15992139/9d032ada-3100-11e6-840b-a9a04cb7c94c.png)

pinpoint 1.5.2 버전을 설치하였는데

Realtime Active Thread Chart가 화면에 나타나지 않네요

활성화 하려면 어떻게 해야되나요??

**Comment by TaeSeong** [comment]
잘못해서 close 되었네요 다시 open 합니다

**Comment by koo-taejin** [comment]
현재 선택되어 있으신 Last 5M TimeBar를 보시면, 왼쪽에 시계모양이 리얼타임을 뜻합니다.
이전의 액티스 스레드 차트만 리얼타임이였는데 1.5.2 부터는 스캐터 차트까지 리얼타임으로 제공하고 있어서 이를 완전히 분리한 것입니다.  참고하세요 

1.6.0 부터는 헷갈릴수도 있다고 판단하여 시계모양에서 REAL TIME이라는 글자로 변경되었습니다.

**Comment by TaeSeong** [comment]
이해되었습니다. 감사합니다.
