### ISSUE TITLE
Graphs in Pinpoint

### ISSUE THREAD

**Issue by vedantgoenka** [naver/pinpoint#1854]
Can the response time scatter graph be changed to any other view?

I'm looking for a graph which plots the current avg. response time of an API continuously over the time axis, so that I can see variations over multiple calls made to the API. Is there some way I can integrate this graph into pinpoint?

**Comment by Xylus** [comment]
Hi vedantgoenka,
Unfortunately, we currently don't have a simple way to switch out graphs.
An average response time graph of an API seems like it would require aggregation. These type of queries aren't really feasible to be done in real time using our current data model. That said, we're working on this and hopefully will be integrated soon.

**Comment by vedantgoenka** [comment]
I was thinking of using OpenTSDB for aggregation. So is there any way to write to OpenTSDB along with writing to HBase?
Alternatively, do you have write support to anything apart from HBase?

**Comment by Xylus** [comment]
You could definitely make use of OpenTSDB to store average response time metrics, but this would require additional coding in the collector.

We also only support HBase currently. We're still adding/changing a lot of stuff so we don't want to bring in any more complexity just yet. Additional backend support might be added in the future once things settle down.

**Comment by vedantgoenka** [comment]
Thanks for the tip.
I'm able to generate avg. response time graphs on Opentsdb now. Simply added a new method to push the required data points to opentsdb.

**Comment by tinabear** [comment]
@vedantgoenka would you mind sharing your method to expose data to opentsdb?

Thank you.
