### ISSUE TITLE
quickstart:HBase,Controller,WebUI can run successfully,but test app.sh take so long and fail at last

### ISSUE THREAD

**Issue by Downey-W** [naver/pinpoint#1862]
When run ./start-testapp.sh , it has no error.
![Uploading 73655E13-C17F-47F6-8855-59B4BFCCF816.png…]()
![Uploading FA6BFF01-06F7-4BF9-B7D1-BDF866BBC077.png…]()

like this:
starting pinpoint-quickstart-testapp. 790 /1000 sec(close wait limit).
starting pinpoint-quickstart-testapp. 795 /1000 sec(close wait limit).

at last:
starting pinpoint-quickstart-testapp. 1000 /1000 sec(close wait limit).
---pinpoint-quickstart-testapp initialization failed. pid=36444.---
./start-testapp.sh: line 178: kill: (36444) - No such process

Can anybody tell me why?How to fix it .

**Comment by deadjoe** [comment]
make sure to check the testapp's log which is in pinpoint/quickstart/logs.
And make sure there is no "testapp" already running in your previous operation. You can kill it before launch a new testapp instance.
