### ISSUE TITLE
No data inserted in hbase despite collector logs

### ISSUE THREAD

**Issue by bmuguet** [naver/pinpoint#187]
Hi,

Thanks for this hopefull APM.

The testapp works perfectly, but with my distant agent, the collector logs contains my app calls (see below), however the hbase seems empty.
Why the calls don't appear in hbase and web interface ?

Here's some collector logs : 
02-18 16:15:24 [DEBUG](c.n.p.c.d.h.HbaseMapStatisticsCalleeDao:139) flush baseMapStatisticsCalleeDao Increment:1
02-18 16:15:24 [TRACE](c.n.p.c.d.h.s.RowKeyMerge          :62) create increment row:CallRowKey{callApplicationName='QTG', callServiceType=1010, rowTimeSlot=1424272500000}, column:[ResponseColumnName{agentId='mas-01', columnSlotNumber=1000, callCount=1}]
02-18 16:15:24 [DEBUG](c.n.p.c.d.h.HbaseMapResponseTimeDao:131) flush HbaseMapResponseTimeDao Increment:1
02-18 16:21:08 [DEBUG](c.n.p.c.d.h.HbaseMapStatisticsCallerDao:87) [Caller] QTG (USER) mas-01 -> QTG (TOMCAT)[mas-01]
02-18 16:21:08 [DEBUG](c.n.p.c.d.h.HbaseMapStatisticsCalleeDao:88) [Callee] QTG (TOMCAT) <- QTG (USER)[mas-01]
02-18 16:21:08 [DEBUG](c.n.p.c.d.h.HbaseMapResponseTimeDao:86) [Received] QTG (TOMCAT)[mas-01]
02-18 16:21:09 [TRACE](c.n.p.c.d.h.s.RowKeyMerge          :62) create increment row:CallRowKey{callApplicationName='QTG', callServiceType=2, rowTimeSlot=1424272860000}, column:[CalleeColumnName{callerAgentId=mas-01, calleeServiceType=1010, calleeApplicationName='QTG', callHost='mas-01', columnSlotNumber=1000, callCount=1}]

Thanks for advance
Regards
Bertrand Muguet

**Comment by Xylus** [comment]
Hi Bertrand,
Your collector log seems fine and the agent seems to be working correctly.
The problem could be due to HBase not receiving/inserting data or the Web not being able to scan the necessary data correctly.

Could you check the HBase log and see if it's working correctly? Or the Web log to check if it's connected to HBase?

If you could post the HBase/Web logs here along with Pinpoint version (master or 1.0.4-RC), it would help us greatly in identifying the issue. 

Thanks!

**Comment by bmuguet** [comment]
Hi Xylus,

Thanks for you reply.
I completely reinstall hbase with the version 1.1.0, and my problem doesn't appear again.

My next problem is when deploying application war in jboss6. Agent is correctly loaded, but my war files don't deploy anymore, due to a "Context initialization failed java.lang.NullPointerException at com.navercorp.pinpoint.bootstrap.interceptor.InterceptorRegistry.getSimpleInterceptor...".
I'm currently searching the root cause of this one, and the compatibilty JBOSS/Pinpoint.

Regards
Bertrand.

**Comment by lioolli** [comment]
NAVER - http://www.naver.com/
--------------------------------------------
문종호(jongho.moon@navercor...) 님은 현재 부재중입니다.</br>
보내신 메일 <Re: [pinpoint] No data inserted in hbase despite collector logs (#187)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
문종호(jongho.moon@navercor...) 님이 남기신 메시지 입니다.
--------------------------------------------
[부재기간 : 2015-02-23 00:00 ~ 2015-02-27 23:59 GMT +09:00]<br>리프레시로 2/23 ~ 2/27 동안 자리를 비웁니다.<br>Pinpoint 관련 문의는 dl_labs_p_pinpoint@navercorp.com로 부탁드립니다.
--------------------------------------------

**Comment by Xylus** [comment]
We currently don't have support for JBoss, mostly just Tomcat for containers (for now).
We are trying hard to expand support on different web containers, but it will take some time - contributions would be awesome right about now :)

Please keep a look out as we add more web container support.
Thanks!
