### ISSUE TITLE
WEBUI： How to display the callstack?

### ISSUE THREAD

**Issue by judon001** [naver/pinpoint#1871]
Deploy 1.5.1 version, how to operate the display callstack?

**Comment by emeroad** [comment]
Hi ~
>Request/Response Scatter Chart - Visualize request count and response patterns over time to identify potential problems. Transactions can be selected for additional detail by dragging over the chart.

**Comment by judon001** [comment]
No request / response scatter Chart, Home page see only realtime active threads Chart.

**Comment by judon001** [comment]
@emeroad No request / response scatter Chart, Home page see only realtime active threads Chart.

**Comment by judon001** [comment]
@emeroad Already found,thanks you.
