### ISSUE TITLE
ERROR: Error: image naver/pinpoint-hbase not found

### ISSUE THREAD

**Issue by cgbspender** [naver/pinpoint#1874]
Clone of the current master branch.

`docker-compose up` fails with the following error:

```
Pulling pinpoint-hbase (naver/pinpoint-hbase:1.6.0-SNAPSHOT)...
Trying to pull repository docker.io/naver/pinpoint-hbase ... 
Pulling repository docker.io/naver/pinpoint-hbase
Error: image naver/pinpoint-hbase not found
ERROR: Error: image naver/pinpoint-hbase not found
```

**Comment by dawidmalina** [comment]
You need to build whole project in order to have snapshot version. Or you can use my images bu using this docker-compose file: https://github.com/dawidmalina/docker-pinpoint/blob/master/docker-compose.yml

**Comment by cgbspender** [comment]
Thanks, I'll give that a try.

**Comment by cgbspender** [comment]
Thanks @dawidmalina, that solved it.
