### ISSUE TITLE
quickstart: web UI Charts not Showing Time in the X-Axis(shows NAN)

### ISSUE THREAD

**Issue by sridhar4535** [naver/pinpoint#1876]
quickstart: web UI Load and Memory & Garbage Collector Charts are not Showing Time in the X-Axis for Tomcat Application.It shows NAN. If you hover over the chart I am able to see the Time. 
<img width="405" alt="screen shot 2016-06-24 at 6 32 37 pm" src="https://cloud.githubusercontent.com/assets/3582710/16353989/7643315e-3a3a-11e6-8254-749117d91cdf.png">
<img width="1128" alt="screen shot 2016-06-24 at 6 33 31 pm" src="https://cloud.githubusercontent.com/assets/3582710/16353990/76457108-3a3a-11e6-8bb8-ab1d458a10cf.png">
<img width="1101" alt="screen shot 2016-06-24 at 6 37 17 pm" src="https://cloud.githubusercontent.com/assets/3582710/16353991/8f129288-3a3a-11e6-976b-c9e717593c38.png">

**Comment by nstopkimsk** [comment]
which browser did you use?

**Comment by sridhar4535** [comment]
Firefox
