### ISSUE TITLE
Alarm: User Group

### ISSUE THREAD

**Issue by Allive1** [naver/pinpoint#1878]
I have Pinpoint Web Application setup on a Tomcat instance. It seems to be receives connections fine, but when I try to create a user group under the alarm section, I received "Exception occurred while trying to CRUD userGroup information". What could be the cause or where would be the best place to start troubleshooting?
![screen shot 2016-06-27 at 9 58 54 am](https://cloud.githubusercontent.com/assets/4907641/16382208/e6c1b7d8-3c4d-11e6-840e-0bc3dad94880.png)

**Comment by Xylus** [comment]
Hi Allive1,
We don't have alarms implemented out of the box as we didn't want to introduce a RDBMS dependency.
That said, we do have a guide on how to implement everything [here](https://github.com/naver/pinpoint/blob/master/doc/alarm.md#2-implementation--configuration).

Let us know if you have any more questions.
Thanks.

**Comment by Allive1** [comment]
Hello again,

The implementation guide was useful but I am still unsure of which route to take with regards of including the new implementation class. Would it be best to try extract the war file and add it that way or build the maven module as a standalone and add it that way?

**Comment by Xylus** [comment]
@Allive1
Sorry for the late reply, You could clone the project and implement the necessary classes, and build from source. This would be the easiest, but it would be hard to maintain going forward as custom source will be mixed in with the oss codebase.
A more preferable approach would to create a separate maven project and utilize maven-war-plugin [overlays](http://maven.apache.org/plugins/maven-war-plugin/overlays.html). This way, you could simply add the oss web as a dependency, and keep your custom implementation in the new project.

**Comment by Allive1** [comment]
Thanks. I was able to successfully build.

**Comment by nstopkimsk** [comment]
👍
