### ISSUE TITLE
Hbase storage capacity

### ISSUE THREAD

**Issue by vedantgoenka** [naver/pinpoint#1893]
How much data can the hbase store, or how long can it store data for?
Is there any mechanism of rewriting on old data, say, once space fills up?

**Comment by Xylus** [comment]
Hi vedantgoenka,
You'll find accurate answers to these by taking a look at the hbase documentation but to give you a quick run down:
Hbase is scalable, so there is practically no limit to how much data can be stored as long as you throw more hardware (region servers).
Data is stored until deleted (and after a major compaction), or once the time-to-live (TTL) has passed. Every key/value stored inside hbase has this value set upon Put (defaults to insertion timestamp but can be set manually). You can find the TTL values for Pinpoint [here](https://github.com/naver/pinpoint/blob/master/hbase/scripts/hbase-create-snappy.hbase).
Finally, I'm not aware of any mechanism of rewriting old data once space fills up. That said, you could possibly reduce the TTL so older data don't take up too much space.
