### ISSUE TITLE
Active Thread Chart를 보기 위해 필요한 설정?

### ISSUE THREAD

**Issue by white343** [naver/pinpoint#1896]
Pinpoint를 설치하고 서비스에 Agent를 설정하고 연결했습니다. Active Thread chart가 모두 Not found 가 나오는데 설정해주어야 할 값들을 Pinpoint, Tomcat 쪽 모두 좀 아려주시면 감사하겠습니다

**Comment by koo-taejin** [comment]
[pinpoint-collector.properties] (https://github.com/naver/pinpoint/blob/master/collector/src/main/resources/pinpoint-collector.properties),
[pinpoint-web.properties] 
(https://github.com/naver/pinpoint/blob/master/web/src/main/resources/pinpoint-web.properties)
 설정을 보면 주석으로 설명이 되어있습니다. ~

**Comment by white343** [comment]
잘되어 있네요 감사합니다 
# -------------------------------------------------------------------------------------------------
# The cluster related options are used to establish connections between the agent, collector, and web in order to send/receive data between them in real time.
# You may enable additional features using this option (Ex : RealTime Active Thread Chart).
# -------------------------------------------------------------------------------------------------
# Usage : Set the following options for collector/web components that reside in the same cluster in order to enable this feature.
# 1. cluster.enable (pinpoint-web.properties, pinpoint-collector.properties) - "true" to enable
# 2. cluster.zookeeper.address (pinpoint-web.properties, pinpoint-collector.properties) - address of the ZooKeeper instance that will be used to manage the cluster
# 3. cluster.web.tcp.port (pinpoint-web.properties) - any available port number (used to establish connection between web and collector)
# -------------------------------------------------------------------------------------------------
# Please be aware of the following:
#1. If the network between web, collector, and the agents are not stable, it is advisable not to use this feature.
#2. We recommend using the cluster.web.tcp.port option. However, in cases where the collector is unable to establish connection to the web, you may reverse this and make the web establish connection to the collector.
#   In this case, you must set cluster.connect.address (pinpoint-web.properties); and cluster.listen.ip, cluster.listen.port (pinpoint-collector.properties) accordingly.
cluster.enable=true
cluster.zookeeper.address=localhost
cluster.zookeeper.sessiontimeout=30000
cluster.listen.ip=
cluster.listen.port=
