### ISSUE TITLE
pinpoint1.6 maven build error

### ISSUE THREAD

**Issue by jsjung90** [naver/pinpoint#1898]
/pinpoint/collector/src/main/java/com/navercorp/pinpoint/collector/cluster/connection/CollectorClusterConnectionRepository.java:49: Undefined reference: java.util.concurrent.ConcurrentHashMap.KeySetView java.util.concurrent.ConcurrentHashMap.keySet()

[INFO] pinpoint ........................................... SUCCESS [  2.291 s]
[INFO] pinpoint-thrift .................................... SUCCESS [  2.266 s]
[INFO] pinpoint-commons ................................... SUCCESS [  3.342 s]
[INFO] pinpoint-commons-hbase ............................. SUCCESS [  2.837 s]
[INFO] pinpoint-commons-server ............................ SUCCESS [  1.911 s]
[INFO] pinpoint-bootstrap-core ............................ SUCCESS [  1.023 s]
[INFO] pinpoint-bootstrap ................................. SUCCESS [  0.476 s]
[INFO] pinpoint-rpc ....................................... SUCCESS [  0.535 s]
[INFO] pinpoint-profiler .................................. SUCCESS [  2.165 s]
[INFO] pinpoint-profiler-optional-parent .................. SUCCESS [  1.018 s]
[INFO] pinpoint-profiler-optional-jdk6 .................... SUCCESS [  0.533 s]
[INFO] pinpoint-profiler-optional-jdk7 .................... SUCCESS [  0.410 s]
[INFO] pinpoint-profiler-optional ......................... SUCCESS [  0.187 s]
[INFO] pinpoint-httpclient3-plugin ........................ SUCCESS [  0.638 s]
[INFO] pinpoint-httpclient4-plugin ........................ SUCCESS [  0.591 s]
[INFO] pinpoint-ning-asynchttpclient-plugin ............... SUCCESS [  0.477 s]
[INFO] pinpoint-gson-plugin ............................... SUCCESS [  0.414 s]
[INFO] pinpoint-cubrid-jdbc-driver-plugin ................. SUCCESS [  0.427 s]
[INFO] pinpoint-mysql-jdbc-driver-plugin .................. SUCCESS [  0.338 s]
[INFO] pinpoint-mariadb-jdbc-driver-plugin ................ SUCCESS [  0.449 s]
[INFO] pinpoint-postgresql-jdbc-driver-plugin ............. SUCCESS [  0.471 s]
[INFO] pinpoint-jtds-plugin ............................... SUCCESS [  0.492 s]
[INFO] pinpoint-oracle-jdbc-driver-plugin ................. SUCCESS [  0.422 s]
[INFO] pinpoint-commons-dbcp-plugin ....................... SUCCESS [  0.274 s]
[INFO] pinpoint-test ...................................... SUCCESS [  0.560 s]
[INFO] pinpoint-cassandra-driver-plugin ................... SUCCESS [  0.687 s]
[INFO] pinpoint-jdk-http-plugin ........................... SUCCESS [  0.250 s]
[INFO] pinpoint-redis-plugin .............................. SUCCESS [  0.354 s]
[INFO] pinpoint-tomcat-plugin ............................. SUCCESS [  0.606 s]
[INFO] pinpoint-json-lib-plugin ........................... SUCCESS [  0.471 s]
[INFO] pinpoint-jackson-plugin ............................ SUCCESS [  0.332 s]
[INFO] pinpoint-thrift-plugin ............................. SUCCESS [  0.532 s]
[INFO] pinpoint-user-plugin ............................... SUCCESS [  0.287 s]
[INFO] pinpoint-arcus-plugin .............................. SUCCESS [  0.483 s]
[INFO] pinpoint-google-httpclient-plugin .................. SUCCESS [  0.299 s]
[INFO] pinpoint-jetty-plugin .............................. SUCCESS [  0.312 s]
[INFO] pinpoint-spring-plugin ............................. SUCCESS [  0.287 s]
[INFO] pinpoint-spring-boot-plugin ........................ SUCCESS [  0.403 s]
[INFO] pinpoint-ibatis-plugin ............................. SUCCESS [  0.240 s]
[INFO] pinpoint-mybatis-plugin ............................ SUCCESS [  0.462 s]
[INFO] pinpoint-okhttp-plugin ............................. SUCCESS [  0.280 s]
[INFO] pinpoint-log4j-plugin .............................. SUCCESS [  0.658 s]
[INFO] pinpoint-logback-plugin ............................ SUCCESS [  0.230 s]
[INFO] pinpoint-dubbo-plugin .............................. SUCCESS [  0.522 s]
[INFO] pinpoint-activemq-client-plugin .................... SUCCESS [  0.339 s]
[INFO] pinpoint-plugins ................................... SUCCESS [  0.264 s]
[INFO] pinpoint-tools ..................................... SUCCESS [  0.582 s]
[INFO] pinpoint-agent-distribution ........................ SUCCESS [  7.313 s]
[INFO] pinpoint-collector ................................. FAILURE [  1.662 s]
[INFO] pinpoint-profiler-optional-jdk8 .................... SKIPPED
[INFO] pinpoint-web ....................................... SKIPPED
[INFO] pinpoint-hbase-distribution ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 44.158 s
[INFO] Finished at: 2016-07-08T10:47:05+09:00
[INFO] Final Memory: 61M/172M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.15:check (ensure-java-1.8-class-library) on project pinpoint-collector: Signature errors found. Verify them and ignore them with the proper annotation if needed. -> [Help 1]

위와 같은 build 오류가 발생합니다.

제 build 환경은 다음과 같습니다.

export JAVA_HOME=/usr/java/jdk1.8.0_92

export JAVA_6_HOME=/usr/java/jdk1.6.0_45

export JAVA_7_HOME=/usr/java/jdk1.8.0_92

export JAVA_8_HOME=/usr/java/jdk1.8.0_92

혹시 제가 뭔가 잘못 설정한 부분이 있을까요..?

**Comment by Xylus** [comment]
jsjun90님 안녕하세요,
animal-sniffer maven plugin에서 오류가 난 부분은 collector 바이너리의 jdk7 API 호환성이 깨져 발생한 것입니다.
Collector는 JAVA_7_HOME에 설정된 jdk를 사용하여 빌드되는데, 이 값이 jdk8로 설정되어있어 `ConcurrentHashMap.keySet()` 내부에 jdk8에서 추가된 `KeySetView` 심볼이 있어 호환성 체크가 깨지는 것 같습니다.
JAVA_7_HOME을 jdk7로 설정하시면 문제가 해결될 것 같습니다.

저희쪽 가이드에는 JAVA_7_HOME을 jdk7+ 라고 명시되어있는데, animal-sniffer 적용으로 이 부분을 수정해야 할 것 같습니다. 제보 감사드립니다.
