### ISSUE TITLE
Is Oracle Weblogic supported?

### ISSUE THREAD

**Issue by giovere** [naver/pinpoint#1899]
Is Weblogic application server supported or planned?

**Comment by Xylus** [comment]
Hi giovere,
We don't have support for Weblogic yet, nor is it planned for immediate future unfortunately.
You could however define manual entry points to start traces for now.
Take a look [here](https://groups.google.com/forum/#!topic/pinpoint_user/1IKtYGhmUyU).

**Comment by emeroad** [comment]
duplicated issue : #1895
