### ISSUE TITLE
Historical data retention period

### ISSUE THREAD

**Issue by judon001** [naver/pinpoint#1918]
How long does it take to preserve historical data by default,
Whether it can be adjusted

**Comment by Xylus** [comment]
Hi judon001,
You can adjust it by changing the hbase TTL values. They're currently set upon table creation via [hbase script](https://github.com/naver/pinpoint/blob/master/hbase/scripts/hbase-create.hbase) ([snappy](https://github.com/naver/pinpoint/blob/master/hbase/scripts/hbase-create-snappy.hbase)). Change the TTL values here to your liking.

**Comment by judon001** [comment]
@Xylus Thanks for the tip.

**Comment by irocks04** [comment]
Hi.

Is the unit for TTL in seconds or milliseconds?
