### ISSUE TITLE
Failed Responses

### ISSUE THREAD

**Issue by Allive1** [naver/pinpoint#1923]
We are bunch of developers working on ecommerce applications (from US) interested in using this tool for API monitoring.
 
We are a group of 3 Java developers, really loved the product that you’ve developed so far and are really interested to contribute it back to this community.
 
We would like to brain storm on the below enhancement and start working on/contrivute right away. Is it possible to have a quick conference call on this? (emails/group mails seems to slow us down and also us being in different time zones we think having a call may expedite responses)

http fail response codes should reflect as exceptions in web ui instead of pass

**Comment by Xylus** [comment]
followed up [here](https://groups.google.com/forum/#!topic/pinpoint_user/Vp1TG6yICdI)
