### ISSUE TITLE
Pinpoint Configuration in 1.6.0

### ISSUE THREAD

**Issue by Allive1** [naver/pinpoint#1924]
I am attempting use the alarm configuration in pinpoint version 1.6.0. The web portion builds and deploys fine, but I am unable to reach the configuration modal because the settings icon is unresponsive. Conversely, the same alarm implementation builds fine but crashes the deployment in version 1.5.2. Any suggestions?

**Comment by LEPF** [comment]
I have the same problem...

**Comment by minwoo-jung** [comment]
I got it. I will check

**Comment by minwoo-jung** [comment]
I don't understand your writing. What do you mean "but crashes the deployment in version 1.5.2"?
