### ISSUE TITLE
fail maven install

### ISSUE THREAD

**Issue by ruizlake** [naver/pinpoint#1939]
execute maven install -Dmaven.test.skip=true,
but when the execution fails here 
[INFO] Installed npm locally.
[INFO] 
[INFO] --- frontend-maven-plugin:1.0:npm (npm install) @ pinpoint-web ---
[INFO] Running 'npm install' in /Users/summer/Downloads/pinpoint/web/target

**Comment by Xylus** [comment]
Hi ruizlake,
we'll probably need more information about the error to try and figure out what's failing.
