### ISSUE TITLE
How to configure the deployment of the pinpoint-collector cluster？

### ISSUE THREAD

**Issue by bigsnapdragon** [naver/pinpoint#1943]
How to configure the deployment of the pinpoint-collector cluster？I see in the configuration file of pinpoint-collector.properties have this property "collector.l4.ip=",is  it used to configure the collector cluster? How does it work? what can i do?

**Comment by Xylus** [comment]
You can bind multiple pinpoint-collector instances behind a l4 to create a cluster.
The `collector.l4.ip` is simply there to allow the collector to ignore printing warning logs when health checks fail.
