### ISSUE TITLE
Can be deployed as this way？

### ISSUE THREAD

**Issue by bigsnapdragon** [naver/pinpoint#1949]
![-](https://cloud.githubusercontent.com/assets/17841615/17285016/68708ae2-57f2-11e6-94ea-f691ef5e481a.png)

As shown above, can be deployed in this way? If such a deployment,  will the data be repeated entry to Hbase?

**Comment by Xylus** [comment]
It'd be best to put the collector behind a l4 and configure the agents to connect to it.
