### ISSUE TITLE
'PermGen Usage' display wrong

### ISSUE THREAD

**Issue by junfengcode** [naver/pinpoint#1950]
hi，please help，is a bug or my use is not correct ?

【Versions】
pinpoint-backend：1.5.1 ~ 1.5.2
pinpoint-agent：1.5.1
JVM：1.7

【JVM ARGS Config】
-XX:PermSize=250m -XX:MaxPermSize=250m
 
【pinpoint display】
![default](https://cloud.githubusercontent.com/assets/1697789/17316635/40fe9646-58a8-11e6-974d-3f919e4341ad.png)

**Comment by Xylus** [comment]
Hi junfengcode,

The non-heap chart displays the non-heap usage/max of the JVM. This includes the permgen (for Java7), or the metaspace (for Java8), as well as other non-heap space such as code cache etc.

So while setting the `MaxPermSize` to 250M would mean the non-heap max will be greater than 250M, it does not necessarily mean the non-heap max would also be 250M.

**Comment by junfengcode** [comment]
Understand, thank you very much!  @Xylus
