### ISSUE TITLE
tomcat logs catalina.out

### ISSUE THREAD

**Issue by judon001** [naver/pinpoint#1951]
Pinpoint log output to catalina.out,  can configure does not output to this file ?

**Comment by emeroad** [comment]
Hello. 
Edit the log configuration file.
 - log dir : `$AGENT_DIR/lib/log4.xml`
 - Modify `<appender-ref ref="console"> : org.apache.log4j.ConsoleAppender`

**Comment by judon001** [comment]
@emeroad Thanks
