### ISSUE TITLE
 pinpoint-commons-hbase build FAILURE 

### ISSUE THREAD

**Issue by darkrain1990** [naver/pinpoint#1958]
Hi ,

I build  pinpoint1.5.1 and poinpoint1.5.2 failed in  pinpoint-commons-hbase build step. It seems same

compile problem in commons-hbase. I  have installed the following packages but it still not work.

Is there any thing wrong with my operation ? Thanks a  lot. 

> mvn install:install-file -Dfile=/midware/pinpoint/jar/zookeeper-3.4.5-cdh5.4.0.jar -DgroupId=org.apache.zookeeper -DartifactId=zookeeper -Dversion=3.4.5-cdh5.4.0 -Dpackaging=jar -DcreateChecksum=true

>mvn install:install-file -Dfile=/midware/pinpoint/jar/mariaDB4j-2.1.3.jar -DgroupId=ch.vorburger.mariaDB4j -DartifactId=mariaDB4j -Dversion=2.1.3 -Dpackaging=jar -DcreateChecksum=true

>mvn install:install-file -Dfile=/midware/pinpoint/jar/hbase-client-1.0.0-cdh5.4.0.jar -DgroupId=org.apache.hbase -DartifactId=hbase-client -Dversion=1.0.0-cdh5.4.0 -Dpackaging=jar -DcreateChecksum=true

>mvn install:install-file -Dfile=/data3/pinpoint/pinpoint-master/lib/hbase-0.90.3.jar -DgroupId=org.apache.hbase -DartifactId=hbase -Dversion=0.90.3 -Dpackaging=jar -DcreateChecksum=true

> export JAVA_6_HOME=/usr/java/jdk1.6.0_45
export JAVA_7_HOME=/usr/java/jdk1.7.0_79
export JAVA_8_HOME=/usr/java/jdk1.8.0_101
export JAVA_HOME=/usr/java/jdk1.7.0_79
export MAVEN_HOME=/midware/apache-maven-3.2.5
export PATH=$JAVA_7_HOME/bin:$PATH:$MAVEN_HOME/bin:$JAVA_7_HOME/jre/bin
export CLASS_PATH=.:$JAVA_7_HOME/lib/dt.jar:$JAVA_7_HOME/lib/tool.jar:$JAVA_7_HOME/jre/lib

```
[ERROR] /midware/pinpoint/pinpoint-1.5.1/commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HBaseTables.java:[21,35] error: cannot find symbol
[ERROR] /midware/pinpoint/pinpoint-1.5.1/commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/PooledHTableFactory.java:[59,60] error: cannot access User
[ERROR] /midware/pinpoint/pinpoint-1.5.1/commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/PooledHTableFactory.java:[82,29] error: cannot access TableName
[ERROR] /home/wlsadmin/.m2/repository/org/apache/hbase/hbase-client/1.0.0-cdh5.4.0/hbase-client-1.0.0-cdh5.4.0.jar(org/apache/hadoop/hbase/Abortable.class): warning: Cannot find annotation method 'value()' in type 'LimitedPrivate': class file for org.apache.hadoop.hbase.classification.InterfaceAudience not found
[ERROR] location: class HBaseTables
[ERROR] /midware/pinpoint/pinpoint-1.5.1/commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HBaseTables.java:[119,69] error: cannot find symbol
[ERROR] symbol:   variable Bytes
[ERROR] location: class HBaseTables
[ERROR] /midware/pinpoint/pinpoint-1.5.1/commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HBaseTables.java:[122,61] error: cannot find symbol
[ERROR] symbol:   variable Bytes
[ERROR] location: class HBaseTables
[ERROR] /midware/pinpoint/pinpoint-1.5.1/commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HBaseTables.java:[125,66] error: cannot find symbol
[ERROR] /midware/pinpoint/pinpoint-1.5.1/commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTemplate2.java:[303,22] error: cannot access CellScannable
[ERROR] /midware/pinpoint/pinpoint-1.5.1/commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseTemplate2.java:[326,22] error: cannot access HeapSize
```

[INFO] 
[INFO] pinpoint ........................................... SUCCESS [  0.770 s]
[INFO] pinpoint-thrift .................................... SUCCESS [  4.410 s]
[INFO] pinpoint-commons ................................... SUCCESS [  4.075 s]
[INFO] pinpoint-bootstrap-core ............................ SUCCESS [  2.497 s]
[INFO] pinpoint-bootstrap ................................. SUCCESS [  0.939 s]
[INFO] pinpoint-rpc ....................................... SUCCESS [  2.350 s]
[INFO] pinpoint-profiler .................................. SUCCESS [  3.800 s]
[INFO] pinpoint-profiler-optional ......................... SUCCESS [  0.913 s]
[INFO] pinpoint-httpclient3-plugin ........................ SUCCESS [  1.259 s]
[INFO] pinpoint-httpclient4-plugin ........................ SUCCESS [  1.506 s]
[INFO] pinpoint-ning-asynchttpclient-plugin ............... SUCCESS [  1.054 s]
[INFO] pinpoint-gson-plugin ............................... SUCCESS [  0.919 s]
[INFO] pinpoint-cubrid-jdbc-driver-plugin ................. SUCCESS [  1.223 s]
[INFO] pinpoint-mysql-jdbc-driver-plugin .................. SUCCESS [  0.833 s]
[INFO] pinpoint-postgresql-jdbc-driver-plugin ............. SUCCESS [  1.080 s]
[INFO] pinpoint-jtds-plugin ............................... SUCCESS [  0.804 s]
[INFO] pinpoint-oracle-jdbc-driver-plugin ................. SUCCESS [  1.167 s]
[INFO] pinpoint-commons-dbcp-plugin ....................... SUCCESS [  0.779 s]
[INFO] pinpoint-jdk-http-plugin ........................... SUCCESS [  0.777 s]
[INFO] pinpoint-redis-plugin .............................. SUCCESS [  1.271 s]
[INFO] pinpoint-test ...................................... SUCCESS [  1.647 s]
[INFO] pinpoint-tomcat-plugin ............................. SUCCESS [  1.127 s]
[INFO] pinpoint-json-lib-plugin ........................... SUCCESS [  0.959 s]
[INFO] pinpoint-jackson-plugin ............................ SUCCESS [  0.961 s]
[INFO] pinpoint-thrift-plugin ............................. SUCCESS [  1.780 s]
[INFO] pinpoint-user-plugin ............................... SUCCESS [  1.059 s]
[INFO] pinpoint-arcus-plugin .............................. SUCCESS [  1.174 s]
[INFO] pinpoint-google-httpclient-plugin .................. SUCCESS [  0.957 s]
[INFO] pinpoint-jetty-plugin .............................. SUCCESS [  1.194 s]
[INFO] pinpoint-spring-plugin ............................. SUCCESS [  1.143 s]
[INFO] pinpoint-spring-boot-plugin ........................ SUCCESS [  0.977 s]
[INFO] pinpoint-ibatis-plugin ............................. SUCCESS [  0.971 s]
[INFO] pinpoint-mybatis-plugin ............................ SUCCESS [  0.780 s]
[INFO] pinpoint-okhttp-plugin ............................. SUCCESS [  1.153 s]
[INFO] pinpoint-log4j-plugin .............................. SUCCESS [  0.964 s]
[INFO] pinpoint-logback-plugin ............................ SUCCESS [  0.810 s]
[INFO] pinpoint-plugins ................................... SUCCESS [  0.872 s]
[INFO] pinpoint-agent-distribution ........................ SUCCESS [  2.736 s]
[INFO] pinpoint-commons-hbase ............................. FAILURE [  1.669 s]
[INFO] pinpoint-collector ................................. SKIPPED
[INFO] pinpoint-web ....................................... SKIPPED
[INFO] pinpoint-integration-test-java8 .................... SKIPPED

**Comment by Xylus** [comment]
Hi darkrain1990,
Not 100% sure but it seems like hbase-client dependency is weird. Instead of manually installing them from file, could you delete them from the local maven repository and install pinpoint from scratch and let it download the depenencies?
