### ISSUE TITLE
web에서 agent 이름 삭제 안됩니다. 도와주세요.

### ISSUE THREAD

**Issue by msbell** [naver/pinpoint#1963]
applicationName 수정 후 다시 pinpointweb 띄우면 이전의 이름과 새로 등록한 이름 둘 다 나타나는데,
이전 이름을 없애려면 어떻게 해야하나요?
server reboot해도 안되는데, hbase 에서 지워야 하나요?

**Comment by emeroad** [comment]
아직 admin UI가 없습니다.

`com.navercorp.pinpoint.web.controller.AdminController` 
에 admin api가 있습니다.

/admin/removeAgentId.pinpoint 를 호출해서 삭제하시면됩니다.
