### ISSUE TITLE
에이전트로 등록한 앱의 일 평균 접속 수를 알 수 있을까요?

### ISSUE THREAD

**Issue by msbell** [naver/pinpoint#1975]
안녕하세요?

에이전트로 등록한 어플리케이션의 일 단위 
request/response transaction 수를 이용해서
혹은 다른 방법으로
일 평균 앱 접속 수를 도출할 수 있을까요?

감사합니다.

**Comment by koo-taejin** [comment]
현재 지원하고 있지 않은 기능이며, 빠른 시간내에 지원 될 것 같지는 않습니다. 
 
반드시 필요하신 기능이라면 직접 구현 하셔야 할 것 같네요 
혹시 구현하신다면 저희에게도 기여해주신다면 감사하겠습니다 ~
