### ISSUE TITLE
Change permain to agentmain

### ISSUE THREAD

**Issue by Eilikce** [naver/pinpoint#1978]
Because of my App can't restart usually , so I want to use pinpoint-agent when my App running.
I tried to change the method named 'permain' in PinpointBootStrap to 'agentmain' , and used the Agent-Class way to start the agent .
Although the pinpoint started successfully and showed that 'pinpoint agent started normally.' , I couldn't find the data in pinpoint-web when I request my App ...
If pinpoint-agent only can work in permain way ? If the pinpoint-agent have to start work before my App start ?

Thanks for your team

**Comment by Xylus** [comment]
Hi Eilikce,
We haven't tested our agent using agentmain.
If I had to guess, it might not work as intended as at the time of attaching the agent (after application start-up), application classes are already loaded. At this point, even if the class transformers are registered, application classes won't be instrumented as they are already loaded on the JVM.
Please let me know if this makes sense, or if you have any concerns.
Thanks!

**Comment by Eilikce** [comment]
Hi Xylus,
I have the same view with you . So it might mean that I have to stop trying to start up the Agent while my application running .
Thanks for your idea !
