### ISSUE TITLE
Profiler: Compilation failure - cannot access com.navercorp.pinpoint.common.server.bo.SpanFactory bad class file: com/navercorp/pinpoint/common/server/bo/SpanFactory.class(com/navercorp/pinpoint/common/server/bo:SpanFactory.class) class file has wrong version 52.0, should be 50.0

### ISSUE THREAD

**Issue by GOPALKRISHNAC** [naver/pinpoint#1989]
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /usr/local/pinpoint/profiler/src/main/java/com/navercorp/pinpoint/test/junit4/BasePinpointTest.java:[22,-1] cannot access com.navercorp.pinpoint.common.server.bo.SpanFactory
bad class file: com/navercorp/pinpoint/common/server/bo/SpanFactory.class(com/navercorp/pinpoint/common/server/bo:SpanFactory.class)
class file has wrong version 52.0, should be 50.0
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] pinpoint ........................................... SUCCESS [  1.720 s]
[INFO] pinpoint-thrift .................................... SUCCESS [  2.128 s]
[INFO] pinpoint-commons ................................... SUCCESS [  2.714 s]
[INFO] pinpoint-commons-hbase ............................. SUCCESS [  2.614 s]
[INFO] pinpoint-commons-server ............................ SUCCESS [  6.876 s]
[INFO] pinpoint-bootstrap-core ............................ SUCCESS [  6.814 s]
[INFO] pinpoint-bootstrap ................................. SUCCESS [  1.872 s]
[INFO] pinpoint-rpc ....................................... SUCCESS [  4.453 s]
[INFO] pinpoint-profiler .................................. FAILURE [  9.160 s]
[INFO] pinpoint-profiler-optional-parent .................. SKIPPED
[INFO] pinpoint-profiler-optional-jdk6 .................... SKIPPED
[INFO] pinpoint-profiler-optional-jdk7 .................... SKIPPED
[INFO] pinpoint-profiler-optional ......................... SKIPPED
[INFO] pinpoint-httpclient3-plugin ........................ SKIPPED
[INFO] pinpoint-httpclient4-plugin ........................ SKIPPED
[INFO] pinpoint-ning-asynchttpclient-plugin ............... SKIPPED
[INFO] pinpoint-gson-plugin ............................... SKIPPED
[INFO] pinpoint-cubrid-jdbc-driver-plugin ................. SKIPPED
[INFO] pinpoint-mysql-jdbc-driver-plugin .................. SKIPPED
[INFO] pinpoint-mariadb-jdbc-driver-plugin ................ SKIPPED
[INFO] pinpoint-postgresql-jdbc-driver-plugin ............. SKIPPED
[INFO] pinpoint-jtds-plugin ............................... SKIPPED
[INFO] pinpoint-oracle-jdbc-driver-plugin ................. SKIPPED
[INFO] pinpoint-commons-dbcp-plugin ....................... SKIPPED
[INFO] pinpoint-test ...................................... SKIPPED
[INFO] pinpoint-cassandra-driver-plugin ................... SKIPPED
[INFO] pinpoint-jdk-http-plugin ........................... SKIPPED
[INFO] pinpoint-redis-plugin .............................. SKIPPED
[INFO] pinpoint-tomcat-plugin ............................. SKIPPED
[INFO] pinpoint-json-lib-plugin ........................... SKIPPED
[INFO] pinpoint-jackson-plugin ............................ SKIPPED
[INFO] pinpoint-thrift-plugin ............................. SKIPPED
[INFO] pinpoint-user-plugin ............................... SKIPPED
[INFO] pinpoint-arcus-plugin .............................. SKIPPED
[INFO] pinpoint-google-httpclient-plugin .................. SKIPPED
[INFO] pinpoint-jetty-plugin .............................. SKIPPED
[INFO] pinpoint-spring-plugin ............................. SKIPPED
[INFO] pinpoint-spring-boot-plugin ........................ SKIPPED
[INFO] pinpoint-ibatis-plugin ............................. SKIPPED
[INFO] pinpoint-mybatis-plugin ............................ SKIPPED
[INFO] pinpoint-okhttp-plugin ............................. SKIPPED
[INFO] pinpoint-log4j-plugin .............................. SKIPPED
[INFO] pinpoint-logback-plugin ............................ SKIPPED
[INFO] pinpoint-dubbo-plugin .............................. SKIPPED
[INFO] pinpoint-activemq-client-plugin .................... SKIPPED
[INFO] pinpoint-plugins ................................... SKIPPED
[INFO] pinpoint-tools ..................................... SKIPPED
[INFO] pinpoint-agent-distribution ........................ SKIPPED
[INFO] pinpoint-collector ................................. SKIPPED
[INFO] pinpoint-profiler-optional-jdk8 .................... SKIPPED
[INFO] pinpoint-web ....................................... SKIPPED
[INFO] pinpoint-hbase-distribution ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 39.679 s
[INFO] Finished at: 2016-08-17T20:06:25+00:00
[INFO] Final Memory: 38M/141M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project pinpoint-profiler: Compilation failure
[ERROR] /usr/local/pinpoint/profiler/src/main/java/com/navercorp/pinpoint/test/junit4/BasePinpointTest.java:[22,-1] cannot access com.navercorp.pinpoint.common.server.bo.SpanFactory
[ERROR] bad class file: com/navercorp/pinpoint/common/server/bo/SpanFactory.class(com/navercorp/pinpoint/common/server/bo:SpanFactory.class)
[ERROR] class file has wrong version 52.0, should be 50.0
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project pinpoint-profiler: Compilation failure
/usr/local/pinpoint/profiler/src/main/java/com/navercorp/pinpoint/test/junit4/BasePinpointTest.java:[22,-1] cannot access com.navercorp.pinpoint.common.server.bo.SpanFactory
bad class file: com/navercorp/pinpoint/common/server/bo/SpanFactory.class(com/navercorp/pinpoint/common/server/bo:SpanFactory.class)
class file has wrong version 52.0, should be 50.0

        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
/usr/local/pinpoint/profiler/src/main/java/com/navercorp/pinpoint/test/junit4/BasePinpointTest.java:[22,-1] cannot access com.navercorp.pinpoint.common.server.bo.SpanFactory
bad class file: com/navercorp/pinpoint/common/server/bo/SpanFactory.class(com/navercorp/pinpoint/common/server/bo:SpanFactory.class)
class file has wrong version 52.0, should be 50.0

        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:972)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more

**Comment by GOPALKRISHNAC** [comment]
hey team,
it's urgent, any one can you please help us on this issue.
thanks

**Comment by Xylus** [comment]
Hi GOPALKRISHNAC,
It looks like javac version issue, but not exactly sure what's causing it here for you.
Are you building it from an IDE, or from command line?
And make sure you've set JAVA_6_HOME, JAVA_7_HOME, JAVA_8_HOME environment variables correctly.

Also, could you try doing a `mvn clean` before installing?

**Comment by GOPALKRISHNAC** [comment]
[root@rdperf1-cass-juggernaut2 pinpoint]# javac -version
javac 1.8.0_51
[root@rdperf1-cass-juggernaut2 pinpoint]# echo $JAVA_6_HOME
/usr/java/jdk1.6.0_45
[root@rdperf1-cass-juggernaut2 pinpoint]# echo $JAVA_7_HOME
/usr/java/jdk1.7.0_21
[root@rdperf1-cass-juggernaut2 pinpoint]# echo $JAVA_8_HOME
/usr/java/jdk1.8.0_51
[root@rdperf1-cass-juggernaut2 pinpoint]#

I'm running from command line and in the above i have given all Java home environment variables
I did mvn clean before i installing, still i'm s

**Comment by Xylus** [comment]
Could you go into the commons-server and profiler directory and run maven clean install with the -X flag and post the debug logs? If they're too long to post, feel free to shoot me an email.

**Comment by GOPALKRISHNAC** [comment]
Hi Emeroad,

As suggested, I ran - maven clean install with the -X flag, 
from commons-server - BUILD SUCCESS 
but when i tried from profiler directory - BUILD FAILURE
Please find the logs for that 
[profiler-mvnclean_BUILDFAILURE_log.txt](https://github.com/naver/pinpoint/files/495531/profiler-mvnclean_BUILDFAILURE_log.txt)

Please check this log and could you help us to fix this issue

Thanks
Gopala

**Comment by emeroad** [comment]
Our build is all okay.
Please check your build environment.

Travis CI build state is normal.
https://travis-ci.org/naver/pinpoint
