### ISSUE TITLE
Does it support monitoring Websphere classic & librity profile

### ISSUE THREAD

**Issue by waleedsaud** [naver/pinpoint#2029]
Does it support monitoring Websphere classic & librity profile .

**Comment by emeroad** [comment]
Unfortunately. Not supported yet.

But Thirdparty plugin is here.
https://github.com/sjmittal/pinpoint/tree/cpu_monitoring_fix/plugins/websphere/src/main/java/com/navercorp/pinpoint/plugin/websphere

**Comment by dawidmalina** [comment]
@emeroad I have asked @sjmittal I hope he will be so kind and will create pull request with this change

**Comment by sjmittal** [comment]
@dawidmalina is it possible you to just take the websphere plugin code and apply it to the local copy of pinpoint master and change the pom xml accordingly. This should be straightforward and you can have websphere plugin at your end.
So you need to copy pinpoint\plugins\websphere at your local copy and also merge pinpoint\plugins\pom.xml to have the following websphere artifacts in the maven build.
<module>websphere</module>
<dependency>
            <groupId>com.navercorp.pinpoint</groupId>
            <artifactId>pinpoint-websphere-plugin</artifactId>
            <version>${project.version}</version>
        </dependency>

**Comment by ViswanathSRIRAM** [comment]
@sjmittal  we are just trying pinpoint on websphere and not able to see any transactions being captured. Do this plugin support the transactions or only the cpu metrics?

**Comment by sjmittal** [comment]
@ViswanathSRIRAM websphere plugin supports transactions. CPU metrics are captured by pinpoint support for ibm java vm. If you are making web requests to webspehere app server you should see them on the pinpoint web.

**Comment by ViswanathSRIRAM** [comment]
@sjmittal  thanks for the inputs. I have tried the same and able to see it is capturing the transactions.. but i am getting the below exception.
java.lang.IllegalArgumentException: toServiceDescList not found. toServiceDescList:UNDEFINED
	at com.navercorp.pinpoint.web.filter.LinkFilter.<init>(LinkFilter.java:89)

I have taken the agent from the master and plugin from your repo, build and copied to plugin directory that i built with the master code. Hope that should work. Please let me know if i have to use your branch for the agent as well.

**Comment by ViswanathSRIRAM** [comment]
@sjmittal  I have taken the fresh copy from the master repo instead of 1.5 and then added websphere plugin. Then it worked fine.

**Comment by dawidmalina** [comment]
Can you guys create pull request to origin with this plugin?

**Comment by sjmittal** [comment]
@ViswanathSRIRAM I hope the plugin is working fine now. Best is to always pick latest from pinpoint repo and then add the plugin from my repo and build the whole thing. This way you have the latest fixes and features.
@dawidmalina  regarding issuing a PR, this is bit tricky as of now. I had forked master some 5 months back, Current state if my branch is that This branch is 6 commits ahead, 733 commits behind naver:master, but this also may change as I had added another plugin and did some fixes couple of months back sync up with pinpoint master that time. I suspect I may have lot of merge issues at hand when I try to issue a PR.

Also please check with @Xylus if they want this plugin as part of core repo. The plugin I have written just addresses the needs I had that time and is not as comprehensive as some other supported plugins like tomcat one.

I still best way right now is to just build pinpoint with websphere plugin from my repo. This is simplest. In case you face any issues doing that I am happy to help.

**Comment by Xylus** [comment]
@sjmittal Thanks for your work on the websphere plugin. As per the PR, we'd love to have the plugin be merged to into origin's master, but that is totally up to you. :)
If you'd be so kind to contribute your work on the Websphere plugin, I'm sure we can sort out any issue with merging.
Definitely let us know if this is something you'd like to pursue.

**Comment by sjmittal** [comment]
I have created the PR here https://github.com/naver/pinpoint/pull/2153
At the time of creation there were no conflicts, also I have added some of my notes.
It is a big pr with 120 files showing changes, many may be shown up due to merge.

Let me know in any case I can help.

**Comment by ViswanathSRIRAM** [comment]
@sjmittal Thanks for the comments. I see there were some communication issues. Since there is no proper handshake in UDP we were not able to know on client. Now I see the stats coming on the server. However I am not able to see the transactions. I am working on this currently. I will get back with my updates.

**Comment by wuyi5630** [comment]
Hi @sjmittal  , How to use websphere plugin? What is the more detail steps? Do you need to modify pinpoint.config?

**Comment by sjmittal** [comment]
@wuyi5630 To use webspehe just copy the websphere folder into the plugins directory.
Modify the pom xml of plugins directly to include this new plugin and then just build.
Then in websphere you need to add the pinpoint agent as specified on the pinpoint github. 
Now simply use your application and on pinpoint web you can see the traces to your server intercepted by this plugin.

Refer to thread above where some of the questions are answered by people using the plugin.
