### ISSUE TITLE
Tomcat agent not working

### ISSUE THREAD

**Issue by farhad-tarapore** [naver/pinpoint#2035]
Hi
I am using tomcat-8. I have placed the following jars in **/opt/tomcat/lib** folder

pinpoint-bootstrap-core-1.6.0-SNAPSHOT.jar
pinpoint-bootstrap-1.6.0-SNAPSHOT.jar

In the catalina.sh, I have added the following line

JAVA_OPTS="$JAVA_OPTS -javaagent:../lib/pinpoint-bootstrap-1.6.0-SNAPSHOT.jar -Dpinpoint.agentId=123 -Dpinpoint.applicationName=myapp"

When I start Tomcat, using sudo /opt/tomcat/bin/catalina.sh start &

I see the following in the logs

Error opening zip file or JAR manifest missing : ../lib/pinpoint-bootstrap-1.6.0-SNAPSHOT.jar
Error occurred during initialization of VM
agent library failed to init: instrument

I checked in the lib folder, the pintpoint-bootstrap jar unzips just fine (used unzip -l to list the files)

Please let me know what I need to do to get this working.
Thanks.

**Comment by olafgeibig** [comment]
Are you sure that relative file path is working? I got exactly the same error when I had a typo in my absolute path.

**Comment by Xylus** [comment]
Hi farhad-tarapore,
I think olafgeibig is right. try using an absolute path for -javaagent option.

**Comment by farhad-tarapore** [comment]
Hi, I tried the absolute path. Now it's throwing this error:

02-Sep-2016 03:54:41.602 INFO [main] com.navercorp.pinpoint.bootstrap.ClassPathResolver.findBootStrapCore **bootStrapCore not found**.
02-Sep-2016 03:54:41.604 SEVERE [main] com.navercorp.pinpoint.bootstrap.PinpointBootStrap.loadBootstrapCoreLib pinpoint-bootstrap-core-x.x.x(-SNAPSHOT).jar not found
*****************************************************************************
* Pinpoint Agent load failure
*****************************************************************************
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NoClassDefFoundError: com/navercorp/pinpoint/common/util/SimpleProperty
	at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.premain(PinpointBootStrap.java:55)
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.navercorp.pinpoint.common.util.SimpleProperty
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
FATAL ERROR in native method: processing of -javaagent failed


The pinpoint-bootstrap-core-1.6.0-SNAPSHOT.jar file is also present in the Tomcat/lib folder. Should I be adding the -cp (--classpath) argument to the JVM also? Which other jars are required for the agent to work?

**Comment by Xylus** [comment]
Ah, sorry I missed the first part of your original post.

> I am using tomcat-8. I have placed the following jars in /opt/tomcat/lib folder

>pinpoint-bootstrap-core-1.6.0-SNAPSHOT.jar
>pinpoint-bootstrap-1.6.0-SNAPSHOT.jar

You don't need to put anything into your tomcat/lib folder, so I would delete those files (and any other pinpoint related libraries if any) from tomcat/lib directory.

If you've built from source, take a look at *$PINPOINT/agent/target* directory. There should be:
* pinpoint-agent-1.6.0-SNAPSHOT folder
* pinpoint-agent-1.6.0-SNAPSHOT.tar.gz
* pinpoint-agent-1.6.0-SNAPSHOT.zip

Now you have 2 options, either to use the *pinpoint-agent-1.6.0-SNAPSHOT* folder directory, or to unzip either of the 2 zipped files to a location of your choice and use that folder. (let's call these location $AGENT_PATH)
Either way, you'll want to set *catalina.sh* as follows:
```
CATALINA_OPTS="$CATALINA_OPTS -javaagent:$AGENT_PATH/pinpoint-bootstrap-$VERSION.jar"
CATALINA_OPTS="$CATALINA_OPTS -Dpinpoint.agentId=$AGENT_ID"
CATALINA_OPTS="$CATALINA_OPTS -Dpinpoint.applicationName=$APPLICATION_NAME"
```

There is a detailed installation guide [here](https://github.com/naver/pinpoint/blob/master/doc/installation.md#pinpoint-agent) if you want more information.

**Comment by farhad-tarapore** [comment]
Yup, copying the folder and pointing the javaagent accordingly, helped. It's working now.

Thanks :)
