### ISSUE TITLE
How to configure complex application server map?

### ISSUE THREAD

**Issue by olafgeibig** [naver/pinpoint#2036]
I can't figure out how to configure my agents to create a server as shown on the README.md (three tomcats: front-web, backend-api, backen-web). If I configure same application but differen agent for each tomcat I get an aggregated view with one tomcat on the server map containing all the instances, e.g. tomcat1, tomcat2. If I configure different applications I get separated application views without any connection although they are calling each other.

Using 1.5.2 with Dawid Malina's docker images. OpenJDK 1.7, Tomcat 7.0.40.

**Comment by Xylus** [comment]
@olafgeibig 
Each node in the server map represents an application. So if you set up your 3 agents with the same application name, they'll be grouped up into a single node as you've observed.

Your second setup is probably what you want and it seems to be not working correctly. It looks like the nodes aren't connected properly in the main server map.

Could you check a couple of things?

1. Try dragging on the scatter chart, you'll be taken to the call stack view. In the call stack view, select a transaction and click on the *Server Map* tab there. Does it show up as you'd expect it to?
2. Could you post the collector log here after you make a few requests to your applications? 

Thanks.

**Comment by Xylus** [comment]
Please reopen the issue if you've more questions.
