### ISSUE TITLE
Pinpoint Web Interface

### ISSUE THREAD

**Issue by farhad-tarapore** [naver/pinpoint#2042]
Hi,
I'm seeing some errors in Chrome when using the web interface. I see 404 errors for the following 2 URLs

http://myserver:8080/configuration.pinpoint
and
http://myserver:8080/applications.pinpoint

I have deployed the pinpoint-web-1.6.0-SNAPSHOT.war to my /opt/tomcat/webapps folder.

I access the web interface with
http://myserver:8080/pinpoint-web-1.6.0-SNAPSHOT/#/main

If I try http://myserver:8080/pinpoint-web-1.6.0-SNAPSHOT/configuration.pinpoint, it works fine. So where do I need to set this path so it doesn't try to pick up configuration.pinpoint from the ROOT folder?

**Comment by Xylus** [comment]
Pinpoint web currently needs to be deployed as ROOT.
It's something we're trying to get fixed for a while now but we haven't actually got around to it yet.

Try deploying the web module as ROOT and let me know if it still doesn't work.
Thanks!
