### ISSUE TITLE
Settings button is not working

### ISSUE THREAD

**Issue by amitsanaye** [naver/pinpoint#2048]
Somehow "Settings" button on the right corner is not working.

Any idea why is it so ?

**Comment by amitsanaye** [comment]
I am using Pinpoint v1.6

**Comment by denzelsN** [comment]
It's now fixed.

**Comment by amitsanaye** [comment]
Thanks. I tried with the fresh build. Now setting button is working. 

But there is button called " View Servers". It is not working now. Nothing happened when I click on it.

**Comment by denzelsN** [comment]
Sorry.
