### ISSUE TITLE
How to check batch api && other server info ??

### ISSUE THREAD

**Issue by jojoldu** [naver/pinpoint#2050]
안녕하세요! 
현재 사내에 핀포인트를 도입하고자 테스트중인 개발자입니다.
핀포인트를 도입하는 과정에 궁금한점이 있어 issue 드립니다.

1. Http Reqeust 외에 Batch로 api 요청도 체크가 되는것인지?
 - 내부에서 30초마다 타 api 서버를 호출하는 기능이 있습니다. 캐시를 위해 있는 기능인데, 30초에 한번씩 api를 호출하는것도 체크가 되는것인지, 된다면 어떻게 설정하면 되는것인지 궁금합니다.

2. 여러 도메인의 서버들을 한번에 볼 수 있는것인지?
 - 예를 들어 a.com 이라는 웹서버가 있고 a.com은 api.a.com 으로 api를 호출합니다. api.a.com은 내부에서 redis나 memcached를 조회하는데, 이럴경우 a.com - api.a.com - 캐시DB 까지의 구성도를 핀포인트 WebUI 에서 한번에 조회가 가능한지 궁금합니다.
 - 기본 설정은 a.com - api.a.com 으로만 출력되고 있습니다.

감사합니다.

**Comment by koo-taejin** [comment]
안녕하세요

제가 이해한 바대로 설명을 드립니다. 
만약 제가 잘못 이해한점이 있다면 답글을 남겨주기를 부탁드립니다. 

1.  Http Reqeust 외에 Batch로 api 요청도 체크가 되는것인지? 
 핀포인트에서는 트랜젝션의 시작점을 직접 지정하실 수 있습니다.
 ```
#pinpoint.config
profiler.entrypoint=x.y.z.Class.method
```
위와 같이 설정할 경우, x.y.z.Class.method가 호출되면 Pinpoint agent에서 이를 트랜잭션의 시작점으로 인지하여 트레이스를 시작하게 됩니다.


2. 여러 도메인의 서버들을 한번에 볼 수 있는것인지?
 말씀주신 a.com - api.a.com - 캐시DB 까지의 구성도 를 한번에 조회 할 수 있습니다. 
단 이렇게 하려면 설명에 주신 a.com, api.a.com 양쪽 모두에 핀포인트 에이전트가 설치되어 있어야 합니다. api.a.com에 핀포인트가 설치되어 있는데 보여지지 않는다면 뎁스 설정을 확인 해 보기를 부탁드립니다. 
![2016-09-06 16 34 40](https://cloud.githubusercontent.com/assets/10057874/18265287/d4a0ee72-744f-11e6-8996-344f5d33697f.PNG)

도입후 좋은 사례 / 불편한 점 등이 있다면 공유를 해주신다면 정말 감사하겠습니다. 

구태진 드림

**Comment by jojoldu** [comment]
안녕하세요! 답변 감사합니다! 
말씀주신대로 depth 조절후 캐시DB까지 노출되는것 확인하였습니다!
한데 1번 질문의 추가 질문인데, 현재 batch api를 쏘는 메소드가 다수 있어 이들을 한번에 entry point에 등록하는 방법을 알고 싶습니다. (config 파일에 따르면 wildcard가 안된다고 되어있습니다. )

* 현재상황
  - Fetcher라는 인터페이스를 구현한 FetcherA, FetcherB, FetcherC가 있는데 이들이 각자 fetch() 메소드를 구현한 상태입니다.
  - Fetcher.fetch (인터페이스) 로 entry point에 등록하면 인식을 못하는것 같습니다.
  - 이럴 경우 일일이 하나하나의 메소드를 직접 입력을 다 해야하는것인지 궁금합니다.

**Comment by koo-taejin** [comment]
현재는 상위클래스의 메소드를 entry point 에 등록하는 기능은 없습니다. 
, 구분자로 다 입력해줘야 할 것 같습니다. 

해당 기능의 이후 지원여부도 현재로서는 말씀을 드리기가 어려울 것 같네요.

**Comment by jojoldu** [comment]
빠른답변 감사드립니다^^
말씀주신대로 , 구분자로 적용해보겠습니다
좋은 제품 제공해주셔서 감사합니다
좋은하루되세요!
