### ISSUE TITLE
Could you give an example on windows as follows?

### ISSUE THREAD

**Issue by hwt2016** [naver/pinpoint#2055]
Tomcat Example

Add -javaagent, -Dpinpoint.agentId, -Dpinpoint.applicationName to CATALINA_OPTS in the Tomcat startup script (catalina.sh).

CATALINA_OPTS="$CATALINA_OPTS -javaagent:$AGENT_PATH/pinpoint-bootstrap-$VERSION.jar"
CATALINA_OPTS="$CATALINA_OPTS -Dpinpoint.agentId=$AGENT_ID"
CATALINA_OPTS="$CATALINA_OPTS -Dpinpoint.applicationName=$APPLICATION_NAME"

**Comment by koo-taejin** [comment]
Hi hwt2016.

Keep in mind. 
Windows Tomcat is managed by catalina.bat.
and windows's using file separator '\' instead of linux '/'.

All others things good.

:)

**Comment by hwt2016** [comment]
thankyou

**Comment by Xylus** [comment]
Please reopen the issue if you have more questions.
