### ISSUE TITLE
How can I find Top SQL  by execution time?

### ISSUE THREAD

**Issue by terrydb5** [naver/pinpoint#2069]
I want to find the Top10 SQL from pinpoint hbase，how can I do that?

Thanks very much!

**Comment by Xylus** [comment]
Hi Terrydb5,
Aggregation on annotations, or anything for that matter, is currently not in. 
However, we think it is a key feature that we would like to include as soon as possible.

**Comment by terrydb5** [comment]
Xylux，thx。

does the SQL execution time are not saved?

**Comment by Xylus** [comment]
SQL execution times are indeed saved (if by SQL execution time you mean the execution time of `prepareStatement`s and `executeQuery`s).
What is currently not feasible to do is to map reduce on each unique SQLs for their execution times as this would require checking each and every span event stored.

We'll most likely end up implementing a separate aggregation pipeline to sort out these data before they're stored in hbase (but we're still a bit away).

**Comment by terrydb5** [comment]
sorry，may be my expression is not accurate。
my means "SQL execution time" is the SQL execution time-consuming。

If I want to develop this function myself，could you please give me some guidance，how can I get these data from collector before they're stored in hbase？

Thank you very much!

**Comment by Xylus** [comment]
So by SQL execution time, I think I understand what you're saying. But you have to remember that there may be multiple parts to querying from a database.
If a connection is made yet, should we include the time it took to create a connection part of the execution time? If PreparedStatement is used, should we include the time it took the connection to prepare the statement into the execution time as well? Or should we simply use the Statement's executeQuery execution time?
These are some of the points that need to be considered imo before defining what SQL execution time is.

As for the collector part, you'll want to look at `SpanHandler`. This is where all the spans are received, and each span contains span events which may or may not have SQL related annotations.
You'll have to check each and every span event for the SQL (which is btw probably mapped to an id) and aggregate them. This is an extremely heavy operation especially for the collector (of which there may be multiple instances of) handling thousands of spans per second and will not be feasible.
You're more than welcome to try but I wouldn't recommend integrating this directly into the collector.
(The separate aggregation pipeline I mentioned above would be something like using Storm to offload this from the collector but this would be a huge undertaking)

Or you could possibly set up your own MapReduce batch to periodically aggregate the SQL execution times.

**Comment by terrydb5** [comment]
@Xylus Thanks for your reply!
