### ISSUE TITLE
plugin service_type is undefined

### ISSUE THREAD

**Issue by clufeng** [naver/pinpoint#2074]
We were developing a motan (a rpc framework similar with dubbo) plugin recently. Followed the plugin development guide and the source code of dubbo plugin, we assigned a service type number 1911 for the rpc provider and 9912 for the consumer as blow. 
```
ServiceType MOTAN_PROVIDER_SERVICE_TYPE = ServiceTypeFactory.of(1911, "MOTAN_PROVIDER", RECORD_STATISTICS);
ServiceType MOTAN_CONSUMER_SERVICE_TYPE = ServiceTypeFactory.of(9912, "MOTAN_CONSUMER", RECORD_STATISTICS);

recorder.recordServiceType(MotanConstants.MOTAN_PROVIDER_SERVICE_TYPE);
recorder.recordServiceType(MotanConstants.MOTAN_CONSUMER_SERVICE_TYPE);

context.addServiceType(MotanConstants.MOTAN_PROVIDER_SERVICE_TYPE);
context.addServiceType(MotanConstants.MOTAN_CONSUMER_SERVICE_TYPE);

```
But after the plugin deployed, the display of the related records on the web ui is still “UNDEFINED”. Is there any further configuration or operation need to be done? Any comments would be highly appreciated.

**Comment by Xylus** [comment]
Hi clufeng,
Not 100% sure if this is the cause but make sure you add *com.navercorp.pinpoint.bootstrap.plugin.ProfilerPlugin*, and *com.navercorp.pinpoint.common.trace.TraceMetadataProvider* files under `src/main/resources/META-INF/services` directory, like [these](https://github.com/naver/pinpoint/tree/master/plugins/dubbo/src/main/resources/META-INF/services).

If you've done this already, make sure you rebuild everything (mvn clean install) and redeploy/restart web.

Let me know if the above doesn't work.
Thanks!

**Comment by clufeng** [comment]
thanks Xylus, The problem has been resolved

**Comment by Xylus** [comment]
Awesome, let me know if you have any more question.

**Comment by hepyu** [comment]
@clufeng @Xylus Has motan plugin added into the pp release version? I checked both motan and pinpoint in github, it seems not.
