### ISSUE TITLE
pinpoint-web can not work well

### ISSUE THREAD

**Issue by peaksnail** [naver/pinpoint#2081]
I use the lastest source code to build web project and start it.But now it looks like below.I can't click anything.But I am sure the http api application.pinpoint return the application list! Is there something wrong? And then I try to use version 1.5.2 but Nothing changed. The Hbase has changed?If so, How can I use it correctly?

![image](https://cloud.githubusercontent.com/assets/1744607/18350679/8c3115f2-7609-11e6-99c0-6bb2d5f1190f.png)

**Comment by Xylus** [comment]
Hmm, that is weird.
Reverting back to 1.5.2 doesn't work either, right?
I'm pretty sure you've probably done this already but could you try rebuilding everything?

If that doesn't work, try hard refreshing (ctrl-F5 I think) the UI maybe?

**Comment by maccloud42** [comment]
I had a similar problem on tomcat using tomcat manager to deploy. There are hardcoded URIs that assume a top level context ("/") deployment. Tomcat manager defaults context to the name of the war file i.e try /pinpoint-web-SNAPSHOT-1.6.0/application.pinpoint in another browser tab. The workaround was to deploy to toplevel context /

**Comment by emeroad** [comment]
related to : #1249
