### ISSUE TITLE
How can i find the  interface or method,  requests& TPS etc. thanks all.

### ISSUE THREAD

**Issue by vwyuheng** [naver/pinpoint#2088]
How can i find the  interface or method,  requests& TPS etc.

**Comment by Xylus** [comment]
Hi vwyuheng,
I'm not quite sure what you're looking for, could you explain it a bit more please?

**Comment by vwyuheng** [comment]
I want to find the total number of calls to the interface , the success of the number of times and the number of failures

**Comment by Xylus** [comment]
These features aren't implemented yet unfortunately.
But we have them high up on our priority list and would like to get them in as soon as possible.
