### ISSUE TITLE
Support for Weblogic applications

### ISSUE THREAD

**Issue by sarakavi** [naver/pinpoint#2097]
Any ETA on support to instrument weblogic applications

**Comment by Xylus** [comment]
@sarakavi none yet, but I think we're planning to add it next major release (no ETA yet)

**Comment by terrydb5** [comment]
@Xylus Great Job！
When is the next major release plan？

**Comment by Xylus** [comment]
@terrydb5 Nothing's done yet, still at the "planning" stage :)
Next major release would probably be after 1.6.1 (1.6.0 is set to release next month, 1.6.1 will mostly be bug fixes for changes made in 1.6.0 and will be released shortly after.
Plugins for various WASes is currently planned for the release after 1.6.1.

**Comment by Xylus** [comment]
We've got a PR in for Websphere plugin - #2153 (Name's a bit misleading)
We're looking to merge this in 1.6.1.

**Comment by prashantnitt07** [comment]
please add TIBCO BW plugin in next pinpoint version
