### ISSUE TITLE
수용할수 있는 최대 에이전트 개수가 얼마나 되는지 알 수 있을까요?

### ISSUE THREAD

**Issue by koreahsb** [naver/pinpoint#2098]
안녕하세요~ 이번에 pinpoint를 사용하다보니 궁금한 사항이 생겨 문의를 드립니다.

서버 사양이 충분하다고 가정하면 수집되는 최대 agent 개수가 얼마나 되는지 알 수 있을까요?

**Comment by emeroad** [comment]
고려해야 될 변수가 너무 많아서 정형화된 답변이 존재하지 않습니다.

사용중인 클러스터를 샘플로 말하자면 아래와 같습니다.
 - HBase 16 region server ( zookeeper 와 같은 기타 제외)
   - CPU : 12 core +
   - HDD disk : 10장
 - Agent 수 : 4000+ 
 - HBase TPS : wrtie 기준 18만 TPS 처리중
