### ISSUE TITLE
when Hystrix's fallback() method is called,succes or fail?

### ISSUE THREAD

**Issue by zcmjcd1** [naver/pinpoint#2101]
For version 1.6.0 ,when fallback()method is called ,it is regared as a success,but it's really a fail,how can I fix it?
Thanks

**Comment by Xylus** [comment]
@zcmjcd1 Looking into this currently and trying to come up with something to indicate that the fallback method has run.
Thanks for sharing!

**Comment by zcmjcd1** [comment]
Thank you!

**Comment by Xylus** [comment]
@zcmjcd1 
Hystrix should mostly indicate if a fallback method is run - #2109.
Please do test it out and let us know if anything looks weird.
Thanks!

**Comment by Xylus** [comment]
@zcmjcd1 Feel free to reopen the issue if it doesn't work.
