### ISSUE TITLE
Why Corrupted(waiting for packet) occur?

### ISSUE THREAD

**Issue by balotelli1011** [naver/pinpoint#2104]
And sometimes occurs Corrupted(invalid sequence)

please help.

**Comment by emeroad** [comment]
Maybe, UDP packet has been lost.
Check your network status and kernel UDP setting.

pinpoint-collector.properties
```
# change OS level read/write socket buffer size (for linux)
#sudo sysctl -w net.core.rmem_max=
#sudo sysctl -w net.core.wmem_max=
# check current values using: 
#$ /sbin/sysctl -a | grep -e rmem -e wmem
```

**Comment by balotelli1011** [comment]
I have installed more pinpoint-collector tomcat, and it never occurred. Thanks
