### ISSUE TITLE
Jboss plugin, no data

### ISSUE THREAD

**Issue by maccloud42** [naver/pinpoint#2112]
I brought in the jboss plugin from suraj to master and integrated all differences. I was able to see the wildfly 8.0.2.Final Agent in the browser but no data was displayed in the scatter chart. Data appeared to be recorded by the collector. Pinpoint-web was manually deployed with context / on tomcat otherwise the application would not be seen in the application drop down list. The tomcat plugin worked fine for the same test app.

Any suggestions, I'vre tried different versions of pinpoint with different wildfly versions
[configs.tar.gz](https://github.com/naver/pinpoint/files/503119/configs.tar.gz)

**Comment by Xylus** [comment]
We're currently reviewing the jboss plugin. It looks great, but some ironing out still needs to be done.
Will let you know once it's merged.

**Comment by maccloud42** [comment]
Thanks. Do you have a release date for 1.6.0/1.6.1 ?

**Comment by emeroad** [comment]
It will be included in the 1.6.0.

**Comment by suraj-raturi** [comment]
Hi @Xylus , @emeroad , 

Appreciate your team effort for looking into it, please let us know if any changes are require, happy to help.

Thanks

**Comment by suraj-raturi** [comment]
Hi @maccloud42 ,
Currently, Jboss plugin is compatible with Jboss EAP version - 6.4.x, We are in process of checking the compatibility with other versions as well.
Can you provide us agent and collector logs also?
I have looked into pinpoint.config file, please specify 
**profiler.applicationservertype=JBOSS** in that and let us know if it worked or not

**Comment by emeroad** [comment]
@suraj-raturi 
JBoss ModuleClassLoader behavior is very specialized.
Maybe we had to solve the problem of JBoss CL
But It has not been tested. Please wait.

**Comment by maccloud42** [comment]
JBOSS EAP 6.4 uses an Apache based web server. Wildfly uses undertow. This could explain the inconsistency. Would like a rough idea of time frame (hours, days weeks or months ?)

**Comment by maccloud42** [comment]
Hi guys, FYI I just tried the integration of the JBOSS plugin. Still no data for Wildfly 9.0.2 (no others tried). I tried it because I have a presentation next Wednesday and want pinpoint as a candidate APM. all the best, Andy.
