### ISSUE TITLE
Context "/" always assumed

### ISSUE THREAD

**Issue by maccloud42** [naver/pinpoint#2113]
I had a similar problem to #2081  on tomcat using tomcat manager to deploy. I could not choose an application. The problem is that there are hardcoded URIs that assume a top level context ("/") deployment. Tomcat manager defaults context to the name of the war file i.e  trying /pinpoint-web-SNAPSHOT-1.6.0/application.pinpoint returned the applications whereas the drop down was asking for /application.pinpoint which could not be found. The workaround was to deploy to toplevel context /

Context should be configurable

**Comment by Xylus** [comment]
You're right, it's been a known issue for quite a while :(
Still planning to do something about it.

**Comment by emeroad** [comment]
This issue is fixed in the next version(1.6.1).
