### ISSUE TITLE
cannot get Trace by traceContext.getCurrentTrace()

### ISSUE THREAD

**Issue by dearboll** [naver/pinpoint#2114]
Hi team, I am a newer for pinpoint and developing kafka plugin based 1.5.2. What I wanna do is just tracing the kafka client `send` (or `poll`) message to (from) kafka server. But I found that I couldn't get the trace via `traceContext.getCurrentTrace` method, only in my constructor interceptor could get the trace. 
<img width="918" alt="4258f3a98d856a3fe6d0e7b3d0d0c562" src="https://cloud.githubusercontent.com/assets/5729929/19044948/05ef41ca-89c9-11e6-8506-a7dbb008c934.png">method1 is the `send` interceptor and method2 is the `constructor` interceptor. The trouble is i cannot get the trace in send interceptor which shows NULL.

<img width="655" alt="711756089cb310fc0d6e9dcf62b33dd2" src="https://cloud.githubusercontent.com/assets/5729929/19045165/f742e4a0-89c9-11e6-98a6-36ae694999e9.png">

Thank you very much!

**Comment by emeroad** [comment]
Hi dearboll.

Perhaps, it seems that Span is not started.
Span is the root of the call stack.
First, you must start the Span.

**Comment by dearboll** [comment]
Hi emeroad.
I have found the reason why I cannot get the trace. My `Producer` and `Consumer` both extend `Thread`. When the `Producer` and `Consumer` do not extend `Thread,` I can get the trace correctly.
What is the reason about it?

**Comment by Xylus** [comment]
Looks like an asynchronous invocation issue.
Trace is currently stored inside a thread local so any crossing of thread boundary will lose track of the current trace. To propagate trace across thread boundaries, you'll have to inject it into some shared object so that the new thread can take this out and continue on tracing.

[Here](https://github.com/naver/pinpoint/wiki/Pinpoint-Plugin-Developer-Guide#24-asynchronous-task) is the detailed guide outlining this.

**Comment by dearboll** [comment]
Thanks all! I have traced the methods and shown the methods' descriptions in Pinpoint Web UI. But  when I add the image of my Kafka plugin, it cannot be shown in the server map. 
What's more, Kafka  in my APM project is regarded as a terminal like Redis, we do not matter the internal details of Kafka. 
So how can I make the icon shown in the server map?

**Comment by Xylus** [comment]
How is your ServiceType declared? It might need `ServiceTypeProperty.QUEUE`.
Take a look at #1708 for a bit more detail. Message queue support was added with ActiveMQ as reference, but it should work the same way for Kafka.
Also check out [ActiveMQMessageProducerSendInterceptor](../blob/master/plugins/activemq-client/src/main/java/com/navercorp/pinpoint/plugin/activemq/client/interceptor/ActiveMQMessageProducerSendInterceptor.java) for the producer interceptor, and [ActiveMQMessageConsumerDispatchInterceptor](../blob/master/plugins/activemq-client/src/main/java/com/navercorp/pinpoint/plugin/activemq/client/interceptor/ActiveMQMessageConsumerDispatchInterceptor.java) for the consumer interceptor.

Make special note of :

1. Pinpoint headers that get sent along with the message
2. What gets recorded by the producer and consumer interceptors through the `SpanEventRecorder.record*` method (especially *destinationId*, *endPoint*, *rpcName*, and *acceptorHost*)

For the icon issue, does `/images/icons/$KAFKA_SERVICE_TYPE.png` on the browser return the correct image? Or a 404?
