### ISSUE TITLE
Why "API-METADATA-NOT-FOUND" occurred?

### ISSUE THREAD

**Issue by balotelli1011** [naver/pinpoint#2132]
When I running pinpoint for about 7days or longer, opening the call stack, it will appear "API-METADATA-NOT-FOUND".
Btw, I have changed the TTL of hbase table.

**Comment by emeroad** [comment]
`API-METADATA` are stored in `ApiMetaData` Table.

If you change the TTL of `ApiMetaData` Table, It would have been deleted.
 - To set the TTL of *Metadata Table to long value.  (eg: 90days)

**Comment by balotelli1011** [comment]
Thanks a lot. Problem solved.

**Comment by 85668869** [comment]
May I ask how to solve the problem?

**Comment by dinesh4747** [comment]
Reference to the recent issue - #6496

@koo-taejin @jaehong-kim @emeroad @Xylus @jefry86 @yanpeng-ali @MarsZhu @minwoo-jung

It looks functional issue where "synchronizing the start time value of agent is not in sync whole it reaches collector server" Can someone please shed some light or definite pointers on how to solve API-METADATA-NOT-FOUND issue which is almost deteriorating my usage of pinpoint in my cloud system and it seems like @jefry86 mentioned very clearly that "the startTime value of metadata is different"

It would be really great and kind if someone could help me address this.
