### ISSUE TITLE
Monitor multiple application on the single page.

### ISSUE THREAD

**Issue by nakjunizm** [naver/pinpoint#2134]
Is there any way to make a screen with multiple applications?

Now I have to choose the application I want to monitor from "Application List".
It would be nice if I monitor all my applications on one page.

**Comment by Xylus** [comment]
Hi nakjunizm,
There's currently no way to view multiple applications at the same time.
However, if those applications are in any way connected (via RPC calls etc) to each other, they should all show up in the same server map.

**Comment by nakjunizm** [comment]
@Xylus 
Thanks for the reply. Yes they are shown on the same server map.
What I tried to do was seeing the realtime active thread chart of each application on the same page.
But I see  it's not available. Thanks anyway.

**Comment by Xylus** [comment]
@nakjunizm Ah I see, you can switch applications shown on the realtime active thread chart by clicking on the nodes.
But you have to unpin it first (default is pinned) by clicking ![pin](https://cloud.githubusercontent.com/assets/10057488/19259029/ab8dd7be-8fb8-11e6-83c2-c9ca553b18a3.PNG) on the top right corner of the realtime active thread chart.
