### ISSUE TITLE
When the pinpoint configuration is added to the following exception, remove the configuration is normal

### ISSUE THREAD

**Issue by vwyuheng** [naver/pinpoint#2141]
When the pinpoint configuration is added to the following exception, remove the configuration is normal,please help me, thanks!

error log follwing:
  
[error.txt](https://github.com/naver/pinpoint/files/522253/error.txt)

**Comment by Xylus** [comment]
Hi vwyuheng,
it looks more like an issue with jackson and wiring `ObjectMapper`.
What version of `org.codehaus.jackson:jackson-mapper-asl` are you using?

**Comment by vwyuheng** [comment]
mabe jackson-mapper-asl-1.9.5 and jackson-mapper-lgpl-1.4.0 conflict,

**Comment by Xylus** [comment]
When is the error occurring? Is this when you're attaching the agent to your web application?

**Comment by Xylus** [comment]
*jackson-mapper-lgpl-1.4.0* doesn't seem to have `serializationInclusion` property.
If you're setting this value in your *servlet-context.xml* like below, it'll throw the same error shown in your error log.
```
<bean id="objectMapper" class="org.codehaus.jackson.map.ObjectMapper">
    <property name="serializationInclusion" value="SOME_VALUE" />
</bean>
```

**Comment by vwyuheng** [comment]
fixed @Xylus thanks!
