### ISSUE TITLE
why my postgres DB show the "unknown ^UNKNOWN_DB" ? how to slove it ? please help me.

### ISSUE THREAD

**Issue by magicdogs** [naver/pinpoint#2157]
JDK use 1.8
pinpoint use 1.5.2

when i have change the postgres jdbc driver   postgresql-9.4.1208.jre7.jar , nothing DB can show the pages, postgresql-9.1-901.jdbc4.jar and postgresql-9.1-901.jdbc.jar  that the page show  unknown ^UNKNOWN_DB , thinks a lot ..

**Comment by Xylus** [comment]
Hi magicdogs,
I think #1678 is related to what you're experiencing, but I don't think a fix was ever merged.
To clarify, could you which of the postgres jdbc versions are not working (`postgresql-9.4.1208.jre7.jar`', `postgresql-9.1-901.jdbc4.jar`, `postgresql-9.1-901.jdbc.jar`)?
Or are all of them not working?

**Comment by magicdogs** [comment]
think for your help , I've change the postgre-driver(postgresql-9.3-1103.jdbc4.jar) , the problem have gone ,

**Comment by magicdogs** [comment]
today , i have testd the postgresql driver (postgresql-9.4.1208.jar) and  the main window can't show anything DBMS infomation , so i have rewrote the plugins  accroding to the source , just add some code can slove it ;
  just add transform 
org.postgresql.jdbc.PgConnection 
org.postgresql.jdbc.PgPreparedStatement

:)

**Comment by Xylus** [comment]
Oh awesome, would you like to make a pull request and get your fix merged?
