### ISSUE TITLE
What is this for???

### ISSUE THREAD

**Issue by balotelli1011** [naver/pinpoint#2161]
http://www.google-analytics.com/collect?

**Comment by Xylus** [comment]
Hi balotelli1011,
We added google analytics to collect user click events to better get a sense of how our users navigate through the UI.
The data collected allows us to improve user experience.
There's an option to disable this in *pinpoint-web.properties* if you're concerned.
```
config.sendUsage=true|false
```
Setting this to false should stop anything from being sent but we've just tested this and there seems to be a bug somewhere that stops this from working correctly right now.
We'll fix this for 1.6.0 release.

**Comment by balotelli1011** [comment]
Thanks a lot

**Comment by emeroad** [comment]
Fixed with commit :  https://github.com/naver/pinpoint/commit/c537c7774173b746c938bca6b4e7445c0d61b7bb
