### ISSUE TITLE
compile pinpoint web failed

### ISSUE THREAD

**Issue by xiaoerlyl** [naver/pinpoint#2172]
I try to compile pinpoint by maven, but it failed.

the error log on the console is: 

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project pinpoint-web: Failed to run task: 'npm install' failed. java.io.IOException: Cannot run program "E:\workplace\pinpoint\web\target\node\node.exe" (in directory "E:\workplace\pinpoint\web\target"): CreateProcess error=193, %1 不是有效的 Win32 应用程序。 -> [Help 1]

**Comment by xiaoerlyl** [comment]
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project pinpoint-web: Failed to run task: 'npm install' failed. java.io.IOException: Cannot run program "E:\workplace\pinpoint\web\target\node\node.exe" (in directory "E:\workplace\pinpoint\web\target"): CreateProcess error=193, %1 不是有效的 Win32 应用程序。 -> [Help 1]

**Comment by Xylus** [comment]
Hi xiaoerlyl, looks like your node installation might be corrupted (`com.github.eirslett:frontend-maven-plugin` downloads node and installs it locally).
Check if you can run *E:\workplace\pinpoint\web\target\node\node.exe* from command and if it doesn't work, try removing *E:\workplace\pinpoint\web\target\node* directory and building again.

**Comment by xiaoerlyl** [comment]
thanks a lot
