### ISSUE TITLE
Whether I can get the number of requests from users

### ISSUE THREAD

**Issue by hwt2016** [naver/pinpoint#2183]
For exampleTomcat==>mysql, I visited a database, but it was marked 2 times. One is to connect DB, another is to get the data,is it? Whether I can get the actual number of requests(one time)?Thanks a lot

**Comment by Xylus** [comment]
Hi hwt2016,
There is no simple way currently to do this (you could try modifying the mysql plugin to not trace the connect invocation).
The intention was to count the actual number of calls made to mysql (which creating a connection is a part of).
If you're using a connection pool, it should do what you're looking for once the pool is populated and the connections are recycled.

Also, if you're simply interested in the number of user requests made to Tomcat that hit mysql, you can right click on the edge from Tomcat -> MySql and select *Filter Transaction*. This will open up a filtered server map window and the number you're looking for should be shown on the User -> Tomcat edge.
