### ISSUE TITLE
about log directory logHome_IS_UNDEFINED

### ISSUE THREAD

**Issue by vwyuheng** [naver/pinpoint#2189]
When the application attach pinpoint, there will be a logHome_IS_UNDEFINED log directory, it will write the business systems log have also come in.  as follew:
![image](https://cloud.githubusercontent.com/assets/1711915/19670552/b218bf76-9a9a-11e6-89a2-b408a09d5ac7.png)

pinpoint version:1.6.0-snapshot

**Comment by nstopkimsk** [comment]
which WAS did you test with? WebLogic?

**Comment by vwyuheng** [comment]
is linux user name,i already know  the root cause ,The problem is caused by the logback.  thanks
