### ISSUE TITLE
Pinpoint Quickstart TestApp : Script start-testapp.sh failed when running with no error log

### ISSUE THREAD

**Issue by spouansi** [naver/pinpoint#2190]
Hi everyone,
After running Pinpoint Collector (quickstart/bin/start-collector.sh) and Pinpoint Web UI (quickstart/bin/start-web.sh), i tried to run Pinpoint TestApp (quickstart/bin/start-testapp.sh) but the shell script doesn't work as expected.
Please need help. Thanks.

Below the output console:

---check pinpoint-quickstart-testapp process status.---
---initialize pinpoint-quickstart-testapp logs.---
rm LOGS_DIR/quickstart.testapp.log.
rm /D/git/sda/apm/pinpoint-master/quickstart/logs/pid/quickstart.testapp.pid.
---initialize pinpoint-quickstart-testapp agent.---
---pinpoint-quickstart-testapp initialization started. pid=41912.---
starting pinpoint-quickstart-testapp. 0 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 5 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 10 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 15 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 20 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 25 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 30 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 35 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 40 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 45 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 50 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 55 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 60 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 65 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 70 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 75 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 80 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 85 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 90 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 95 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 100 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 105 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 110 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 115 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 120 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 125 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 130 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 135 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 140 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 145 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 150 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 155 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 160 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 165 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 170 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 175 /180 sec(close wait limit).
starting pinpoint-quickstart-testapp. 180 /180 sec(close wait limit).
---pinpoint-quickstart-testapp initialization failed. pid=41912.---
./start-testapp.sh: line 178: kill: (41912) - No such process

**Comment by koo-taejin** [comment]
Hi spouansi.

Log files are saved in ${QUICKSTART_HOME}/logs directory.
please refer to the log file (quickstart.agent.log, quickstart.testapp.log) to analyze it.

**Comment by spouansi** [comment]
Hi koo-taejin,

I have this error on the quickstart.testapp.log :

[INFO] BUILD FAILURE
[ERROR] Failed to execute goal org.apache.cxf:cxf-codegen-plugin:2.7.18:wsdl2java (generate-sources) on project pinpoint-quickstart-testapp: Execution generate-sources of goal org.apache.cxf:cxf-codegen-plugin:2.7.18:wsdl2java failed: org.apache.cxf.wsdl11.WSDLRuntimeException: Fail to create wsdl definition http://www.webservicex.net/globalweather.asmx?wsdl: WSDLException: faultCode=PARSER_ERROR: Problem parsing 'http://www.webservicex.net/globalweather.asmx?wsdl'.: java.net.UnknownHostException: www.webservicex.net: Unknown host www.webservicex.net -> [Help 1]

**Comment by koo-taejin** [comment]
There are two possiblities.
 1. www.webservicex.net could be temporarily unavailable or too busy
 2. www.webservicex.net may not be able to connect in your network.
please check it.
 
And I will delete source code which related to apache cxf in quickstart because can't build when can't connect www.webservicex.net situation.
