### ISSUE TITLE
How can i get all requests that are belong to 3s slow request, even 5s ?

### ISSUE THREAD

**Issue by stefli** [naver/pinpoint#2192]
I found that there are some slow requests (3s,even 5s) in the chart, but how to view the details of all those requests?

Anybody can tell me? thanks in advance.

**Comment by koo-taejin** [comment]
Hi stefli.

please refer to this video. (https://www.youtube.com/watch?v=U4EwnB34Dus )

**Comment by stefli** [comment]
Koo-taejin, it seems not what i want. You know, pinpoint uses colors to illustrate the different requests.
So i can find all error requests with red color in the chart. but how about slow requests? 5s requests? I can't see them in the chart.

If they are displayed in the chart, then i can select and view all those slow requests.

**Comment by emeroad** [comment]
Okay. I know weakness of Error Histogram.
We are prepared for this issue.
It will be complemented in next versions 
 - maybe 1.6.1

**Comment by Xylus** [comment]
Hi @stefli, what exactly is the feature you're looking for? Could you explain it in more detail?
We're all confused here in understanding the exact problem you're describing :)

**Comment by stefli** [comment]
@Xylus, there are 5 types of transactions(1s, 3s, 5s, Slow, Error), is there any way to see the details of each type.

**Comment by Xylus** [comment]
Ah I see, although we don't have a way to filter out the transactions by time, you can achieve what you're looking for by dragging on the scatter chart like in the screenshot below.
![scatter_chart](https://cloud.githubusercontent.com/assets/10057488/19762084/731d22be-9c73-11e6-849f-22fddb0a3506.PNG)
(Above is an example for selecting the transactions that took between 3s~5s)

**Comment by stefli** [comment]
@Xylus got it, thanks. 
I have tried this before, seems not equal to the real response time. I'll try some more tests.

**Comment by adiboy6** [comment]
Hi,

how can I raise an alert for all the slow requests?

**Comment by RoySRose** [comment]
@adiboy6 

please check the [docs](https://naver.github.io/pinpoint/alarm.html)

**Comment by adiboy6** [comment]
Hi @RoySRose ,
I want to find the requests(underlying APIs) which are taking time and then raise an alarm.
