### ISSUE TITLE
About the Google Analytics

### ISSUE THREAD

**Issue by pizhihui** [naver/pinpoint#2193]
I have two questions:
the first:
In the web project,Line 315 of the index.html file has to load the google-analytics.js file from the net.Why load the local file?The company's computers do not have Internet access,so the website is waiting.

the second:
In the browser,I can choose the time,but it prompts "Search duration may not be greater than 2 days",What's the meaning?The data in the hbase is not persistent?

Thanks!!

**Comment by Xylus** [comment]
Hi @pizhihui 
For the first question, so the google-analytics.js file is loaded from the server, but it looks like the code inside it loads javascript code from google.
There is also an option to turn off google analytics in *pinpoint-web.properties* - `config.sendUsage=false`. But this alone won't solve the problem as this just stops it from sending usage data and the js file would still be loaded. We'll try to see if we can completely stop the js file from being loaded if the option is set to false.
In the mean time, you could set `config.sendUsage=false` and remove the `<script src="scripts/extra/google-analytics.js?v=${buildTime}"></script>` from *index.html* to get it working I think.

For the second question, the data is persisted in hbase. It just means you cannot search for periods longer than 2 days. For example, you cannot search from 2016-10-20 to 2016-10-23, but you can search from 2016-10-20 to 2016-10-22.

Let me know if you have more questions

**Comment by pizhihui** [comment]
Thank you very much! 

Oh,I would also like to know how to debug the agent code when I am using the eclipse?

Thanks!!
