### ISSUE TITLE
npm install fail    ~~ 

### ISSUE THREAD

**Issue by jijoungsoo** [naver/pinpoint#2201]
[DEBUG] -- end configuration --
[INFO] Running 'npm install' in /home/jijs/pinpoint-master/web/target
[ERROR] npm ERR! Linux 3.19.0-32-generic
[ERROR] npm ERR! argv "/home/jijs/pinpoint-master/web/target/node/node" "/home/jijs/pinpoint-master/web/target/node/node_modules/npm/bin/npm-cli.js" "install"
[ERROR] npm ERR! node v5.11.1
[ERROR] npm ERR! npm  v3.9.6
[ERROR] npm ERR! path /home/jijs/.npm/path-is-absolute/1.0.1
[ERROR] npm ERR! code EACCES
[ERROR] npm ERR! errno -13
[ERROR] npm ERR! syscall mkdir
[ERROR] 
[ERROR] npm ERR! Error: EACCES: permission denied, mkdir '/home/jijs/.npm/path-is-absolute/1.0.1'
[ERROR] npm ERR!     at Error (native)
[ERROR] npm ERR!  { [Error: EACCES: permission denied, mkdir '/home/jijs/.npm/path-is-absolute/1.0.1']
[ERROR] npm ERR!   errno: -13,
[ERROR] npm ERR!   code: 'EACCES',
[ERROR] npm ERR!   syscall: 'mkdir',
[ERROR] npm ERR!   path: '/home/jijs/.npm/path-is-absolute/1.0.1',
[ERROR] npm ERR!   parent: 'grunt' }
[ERROR] npm ERR! 
[ERROR] npm ERR! Please try running this command again as root/Administrator.
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /home/jijs/pinpoint-master/web/target/npm-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:

**Comment by koo-taejin** [comment]
Hi jijoungsoo

Change the permission to npm's default directory or Change npm's default directory to another directory.

thanks.

**Comment by jijoungsoo** [comment]
고맙습니다. 퍼미션 바꾸니 잘되요.!! jijs@jijs-desktop ~/.npm $ sudo chown -R jijs:jijs .
