### ISSUE TITLE
Change default instrumentation engine to ASM

### ISSUE THREAD

**Issue by Xylus** [naver/pinpoint#2215]
Starting from 1.6.0, agent's bytecode instrumentation will use ASM instead of Javassist.

**Comment by Xylus** [comment]
merged via #2216

**Comment by otisg** [comment]
Btw. why did you decide on this change?

**Comment by Xylus** [comment]
Hi @otisg 
It was mostly due to performance/feature reasons, ASM seemed to offer better performance and faster startup time, and more features for the agent to expand upon.
