### ISSUE TITLE
Jboss plugin  can not recognize dubbo services 

### ISSUE THREAD

**Issue by AweiWoo** [naver/pinpoint#2237]
Hi,

I used jboss as web container , and dubbo as service invocation. Now the jboss plugin looks like can not recognize dubbo services . 

![qq 20161109090905](https://cloud.githubusercontent.com/assets/23348717/20123907/7a5cec32-a65d-11e6-858e-4ba6e7d76c51.png)

**Comment by Xylus** [comment]
Did you run the Dubbo service with Pinpoint agent on as well?

**Comment by AweiWoo** [comment]
Thanks for your reminding. I stoped  an agent and the problem appears again.
