### ISSUE TITLE
  the pinpoint-collector installation as cluster by nginx,but the realtime active thread chart display as follew?please help me,thank you!

### ISSUE THREAD

**Issue by vwyuheng** [naver/pinpoint#2241]
pinpoint version:1.6.0-SNAPSHOT
latest update
nginx config：
upstream 9995_udp_upstreams {
        server ip01:9995;
        server ip02:9995;
    }

   upstream 9996_udp_upstreams {
        server ip01:9996;
        server ip02:9996;
    }

    upstream tcp_upstreams {
        server ip01:9994;
        server ip02:9994;
    }

    server {
        listen 9995 udp;
        proxy_pass 9995_udp_upstreams;
        proxy_timeout 1s;
        proxy_responses 1;
    }

    server {
        listen 9996 udp;
        proxy_pass 9996_udp_upstreams;
        proxy_timeout 1s;
        proxy_responses 1;
    }

    server {
        listen 9994;
        proxy_pass tcp_upstreams;
        proxy_timeout 1s;
    }

pinpoint-collector config：
cluster node1：
  cluster.enable=true
cluster.zookeeper.address=ip：port
cluster.zookeeper.sessiontimeout=30000
cluster.listen.ip=ip1
cluster.listen.port=9997
cluster node2：
  cluster.enable=true
cluster.zookeeper.address=ip：port
cluster.zookeeper.sessiontimeout=30000
cluster.listen.ip=ip2
cluster.listen.port=9997

pinpoint-web config：
cluster.enable=true
cluster.web.tcp.port=9997

cluster.zookeeper.address=ip:port
cluster.zookeeper.sessiontimeout=30000
cluster.zookeeper.retry.interval=60000
cluster.connect.address=ip1,ip2

client config:
![image](https://cloud.githubusercontent.com/assets/1711915/20138612/5ac5b50c-a6bc-11e6-92d0-4d46016ca230.png)

but the realtime active thread chart is not work,the screenshot as follew:

![image](https://cloud.githubusercontent.com/assets/1711915/20161447/7e90ee44-a729-11e6-8f79-3945542cc21d.png)

![image](https://cloud.githubusercontent.com/assets/1711915/20161459/8f05045e-a729-11e6-856f-67b1e24cc3ec.png)

please help? thank you!

**Comment by koo-taejin** [comment]
Hi vwyuheng.

1. nginx
I have never experienced using proxy server in Collector.
And never felt the need using proxy server in Collector.

I have wonder why you apply proxy server in front of collector?

2. cluster configuration
There are redundant cluster configurations.
Please refer to the below guide.
```
# -------------------------------------------------------------------------------------------------
# The cluster related options are used to establish connections between the agent, collector, and web in order to send/receive data between them in real time.
# You may enable additional features using this option (Ex : RealTime Active Thread Chart).
# -------------------------------------------------------------------------------------------------
# Usage : Set the following options for collector/web components that reside in the same cluster in order to enable this feature.
# 1. cluster.enable (pinpoint-web.properties, pinpoint-collector.properties) - "true" to enable
# 2. cluster.zookeeper.address (pinpoint-web.properties, pinpoint-collector.properties) - address of the ZooKeeper instance that will be used to manage the cluster
# 3. cluster.web.tcp.port (pinpoint-web.properties) - any available port number (used to establish connection between web and collector)
# -------------------------------------------------------------------------------------------------
# Please be aware of the following:
#1. If the network between web, collector, and the agents are not stable, it is advisable not to use this feature.
#2. We recommend using the cluster.web.tcp.port option. However, in cases where the collector is unable to establish connection to the web, you may reverse this and make the web establish connection to the collector.
#   In this case, you must set cluster.connect.address (pinpoint-web.properties); and cluster.listen.ip, cluster.listen.port (pinpoint-collector.properties) accordingly.
```

**Comment by vwyuheng** [comment]
@koo-taejin fixed

**Comment by sbs081** [comment]
@vwyuheng how to fixed?

**Comment by SKingNight** [comment]
@vwyuheng how to fixed?
