### ISSUE TITLE
Does the Pinpoint 1.6 agent is compatible with pinpoint1.5?

### ISSUE THREAD

**Issue by yf5** [naver/pinpoint#2247]
Does the Pinpoint 1.6 agent is compatible with pinpoint1.5?Thanks!

**Comment by emeroad** [comment]
It is possible.

Here is a agent compatibility table:

Agent Version | Collector 1.0.x | Collector 1.1.x | Collector 1.5.x | Collector 1.6.x
------------- | --------------- | --------------- | --------------- | --------------- 
1.0.x | yes | yes | yes | yes
1.1.x | not tested | yes | yes | yes
1.5.x | no | no | yes | yes
1.6.x | no | no | not tested | yes

**Comment by DevotedTangLiu** [comment]
I used 1.6.0 agent and 1.5.2 collector and it worked

**Comment by koo-taejin** [comment]
@DevotedTangLiu 
In such you're environment, may be Realtime Active Thread Chart function do not work.
If possible, we recommends the collector module and web module higer than installed agent version

**Comment by DevotedTangLiu** [comment]
@koo-taejin 
Thanks I see
