### ISSUE TITLE
My Realtime Active Thread Chart display “NOT FOUND”

### ISSUE THREAD

**Issue by AweiWoo** [naver/pinpoint#2254]
Hi, 
 
My Realtime Active Thread Chart display “NOT FOUND” as follow:

![image](https://cloud.githubusercontent.com/assets/23348717/20292325/a245d05a-ab27-11e6-9115-852220875e92.png)

The parameter of  profiler.tcpdatasender.command.accept.enable default is true  and my agent is runing all time. 
My jboss version is 6 , and the JDK is 1.7

**Comment by emeroad** [comment]
Hi. 

ActiveThread feature requires additional settings.

Please refer to the below guide.
[pinpoint-collector.properties] (https://github.com/naver/pinpoint/blob/master/collector/src/main/resources/pinpoint-collector.properties),
[pinpoint-web.properties] 
(https://github.com/naver/pinpoint/blob/master/web/src/main/resources/pinpoint-web.properties)

```
# -------------------------------------------------------------------------------------------------
# The cluster related options are used to establish connections between the agent, collector, and web in order to send/receive data between them in real time.
# You may enable additional features using this option (Ex : RealTime Active Thread Chart).
# -------------------------------------------------------------------------------------------------
# Usage : Set the following options for collector/web components that reside in the same cluster in order to enable this feature.
# 1. cluster.enable (pinpoint-web.properties, pinpoint-collector.properties) - "true" to enable
# 2. cluster.zookeeper.address (pinpoint-web.properties, pinpoint-collector.properties) - address of the ZooKeeper instance that will be used to manage the cluster
# 3. cluster.web.tcp.port (pinpoint-web.properties) - any available port number (used to establish connection between web and collector)
# -------------------------------------------------------------------------------------------------
# Please be aware of the following:
#1. If the network between web, collector, and the agents are not stable, it is advisable not to use this feature.
#2. We recommend using the cluster.web.tcp.port option. However, in cases where the collector is unable to establish connection to the web, you may reverse this and make the web establish connection to the collector.
#   In this case, you must set cluster.connect.address (pinpoint-web.properties); and cluster.listen.ip, cluster.listen.port (pinpoint-collector.properties) accordingly.
cluster.enable=false
cluster.zookeeper.address=localhost
cluster.zookeeper.sessiontimeout=30000
cluster.listen.ip=
cluster.listen.port=
```

**Comment by AweiWoo** [comment]
I have checked my properties twice . Only difference is that I change the localhost to my IP address. Somebody said if I change my Jboss's JDK to 1.8  it will become ok , but my jboss6 can not to run normally when I used JDK1.8 . Is that a bug or our agent must running under JDK1.8 ?

**Comment by AweiWoo** [comment]
cluster.enable=true

**Comment by SKingNight** [comment]
config.show.activeThread=true
config.show.activeThreadDump=true
config.show.inspector.dataSource=true
