### ISSUE TITLE
Pinpoint Test App is not starting and couldn't able to start the Agent 

### ISSUE THREAD

**Issue by dinesh4747** [naver/pinpoint#2255]
Hi,

Thanks for your recent help xylus, i could successfully build pinpoint 
However I still facing some issue as follows

I could successfully run Hbase (start-hbase.sh/init-hbase.sh) and also able to start the start-collector.sh

But Failed start the start-testapp.sh with below mentioned exceptions 

[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.navercorp.pinpoint:pinpoint-quickstart-agent:jar:1.6.0-RC1
[WARNING] 'version' contains an expression but should be a constant. @ com.navercorp.pinpoint:pinpoint-quickstart-agent:${maven.pinpoint.version}, /Users/z0025g0/Downloads/pinpoint-master/quickstart/agent/pom.xml, line 10, column 14
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Pinpoint Agent QuickStart 1.6.0-RC1
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/2.4/maven-jar-plugin-2.4.pom
^M[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.530 s
[INFO] Finished at: 2016-11-15T14:42:18+05:30
[INFO] Final Memory: 13M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.apache.maven.plugins:maven-jar-plugin:2.4 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-jar-plugin:jar:2.4: Could not transfer artifact org.apache.maven.plugins:maven-jar-plugin:pom:2.4 from/to central (https://repo.maven.apache.org/maven2): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
objc[289]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home//bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
2016-11-15 14:42:18 [WARN ](com.navercorp.pinpoint.bootstrap.PinpointBootStrap) pinpoint-bootstrap-x.x.x(-SNAPSHOT).jar not found.
*****************************************************************************
* Pinpoint Agent load failure
*****************************************************************************
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NoClassDefFoundError: com/navercorp/pinpoint/common/util/SimpleProperty
        at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.premain(PinpointBootStrap.java:53)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: com.navercorp.pinpoint.common.util.SimpleProperty
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more
FATAL ERROR in native method: processing of -javaagent failed

Please find below my Agent path 

Agent path - /Users/z0025g0/Downloads/pinpoint-master/quickstart/agent/target/pinpoint-agent

Folder inside were -
-rwxr-xr-x@  1 z0025g0  DHC\Domain Users   8132 Sep  9 12:45 pinpoint.config
-rw-r--r--@  1 z0025g0  DHC\Domain Users  31797 Oct 16 16:36 pinpoint-bootstrap-1.6.0-RC1.jar
-rw-r--r--@  1 z0025g0  DHC\Domain Users   4475 Nov 14 15:30 pinpoint-quickstart-agent-1.6.0-SNAPSHOT
drwxr-xr-x@ 35 z0025g0  DHC\Domain Users   1190 Nov 14 15:30 plugin
drwxr-xr-x@ 20 z0025g0  DHC\Domain Users    680 Nov 14 15:30 lib
drwxr-xr-x@  5 z0025g0  DHC\Domain Users    170 Nov 14 15:30 boot
drwxr-xr-x@  3 z0025g0  DHC\Domain Users    102 Nov 15 12:21 log

I could see that everything was appears to be properly setup, however i couldnt start the testapp 

Could you please shed some lights into the same 

Appreciate your quick response on the same

**Comment by Xylus** [comment]
Hi @dinesh4747 
It looks like the same issue as the one before (#2253) which has to do with ssl certificates.

Try reading the links below and choose what looks to fit your specific environment best for the solution:
https://support.sonatype.com/hc/en-us/articles/213464948-How-to-trust-the-SSL-certificate-issued-by-the-HTTP-proxy-server-in-Nexus
http://commandlinefanatic.com/cgi-bin/showarticle.cgi?article=art032

**Comment by dinesh4747** [comment]
Hi Xylus,

From your above statement/reply it seems like a network issue (security access issue) ?

Could you confirm the same

**Comment by Xylus** [comment]
Yeh it does look like it (more of a ssl/tls issue related to certificates).
Unfortunately, I don't know what kind of environment you're working in (behind a corporate proxy? etc) so I can't point you to a solution :(

**Comment by dinesh4747** [comment]
Hi Xylus,

Yes I am beyond corporate security where I couldnt download some of the https (URL'S) while during compilation

But my BUILD have successfully passed as per the compilation logs below

thirdparty/maven-metadata-local.xml
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] pinpoint ........................................... SUCCESS [  0.963 s]
[INFO] pinpoint-thrift .................................... SUCCESS [  1.148 s]
[INFO] pinpoint-commons ................................... SUCCESS [  1.383 s]
[INFO] pinpoint-commons-hbase ............................. SUCCESS [  1.140 s]
[INFO] pinpoint-commons-server ............................ SUCCESS [  0.946 s]
[INFO] pinpoint-bootstrap-core ............................ SUCCESS [  0.323 s]
[INFO] pinpoint-bootstrap ................................. SUCCESS [  0.252 s]
[INFO] pinpoint-rpc ....................................... SUCCESS [  0.330 s]
[INFO] pinpoint-google-guava .............................. SUCCESS [  8.308 s]
[INFO] pinpoint-profiler .................................. SUCCESS [  0.697 s]
[INFO] pinpoint-profiler-optional-parent .................. SUCCESS [  0.344 s]
[INFO] pinpoint-profiler-optional-jdk6 .................... SUCCESS [  0.327 s]
[INFO] pinpoint-profiler-optional-jdk7 .................... SUCCESS [  0.308 s]
[INFO] pinpoint-profiler-optional ......................... SUCCESS [  0.226 s]
[INFO] pinpoint-httpclient3-plugin ........................ SUCCESS [  0.345 s]
[INFO] pinpoint-httpclient4-plugin ........................ SUCCESS [  0.338 s]
[INFO] pinpoint-ning-asynchttpclient-plugin ............... SUCCESS [  0.313 s]
[INFO] pinpoint-gson-plugin ............................... SUCCESS [  0.260 s]
[INFO] pinpoint-cubrid-jdbc-driver-plugin ................. SUCCESS [  0.241 s]
[INFO] pinpoint-mysql-jdbc-driver-plugin .................. SUCCESS [  0.237 s]
[INFO] pinpoint-mariadb-jdbc-driver-plugin ................ SUCCESS [  0.234 s]
[INFO] pinpoint-postgresql-jdbc-driver-plugin ............. SUCCESS [  0.250 s]
[INFO] pinpoint-jtds-plugin ............................... SUCCESS [  0.250 s]
[INFO] pinpoint-oracle-jdbc-driver-plugin ................. SUCCESS [  0.252 s]
[INFO] pinpoint-commons-dbcp-plugin ....................... SUCCESS [  0.249 s]
[INFO] pinpoint-test ...................................... SUCCESS [  0.416 s]
[INFO] pinpoint-cassandra-driver-plugin ................... SUCCESS [  0.366 s]
[INFO] pinpoint-jdk-http-plugin ........................... SUCCESS [  0.224 s]
[INFO] pinpoint-redis-plugin .............................. SUCCESS [  0.270 s]
[INFO] pinpoint-tomcat-plugin ............................. SUCCESS [  0.286 s]
[INFO] pinpoint-json-lib-plugin ........................... SUCCESS [  0.227 s]
[INFO] pinpoint-jackson-plugin ............................ SUCCESS [  0.213 s]
[INFO] pinpoint-thrift-plugin ............................. SUCCESS [  0.271 s]
[INFO] pinpoint-user-plugin ............................... SUCCESS [  0.226 s]
[INFO] pinpoint-arcus-plugin .............................. SUCCESS [  0.323 s]
[INFO] pinpoint-google-httpclient-plugin .................. SUCCESS [  0.257 s]
[INFO] pinpoint-jetty-plugin .............................. SUCCESS [  0.268 s]
[INFO] pinpoint-spring-plugin ............................. SUCCESS [  0.372 s]
[INFO] pinpoint-spring-boot-plugin ........................ SUCCESS [  0.230 s]
[INFO] pinpoint-ibatis-plugin ............................. SUCCESS [  0.237 s]
[INFO] pinpoint-mybatis-plugin ............................ SUCCESS [  0.228 s]
[INFO] pinpoint-okhttp-plugin ............................. SUCCESS [  0.250 s]
[INFO] pinpoint-log4j-plugin .............................. SUCCESS [  0.231 s]
[INFO] pinpoint-logback-plugin ............................ SUCCESS [  0.223 s]
[INFO] pinpoint-dubbo-plugin .............................. SUCCESS [  0.339 s]
[INFO] pinpoint-activemq-client-plugin .................... SUCCESS [  0.285 s]
[INFO] pinpoint-cxf-plugin ................................ SUCCESS [  0.356 s]
[INFO] pinpoint-hystrix-plugin ............................ SUCCESS [  0.267 s]
[INFO] pinpoint-jboss-plugin .............................. SUCCESS [  1.334 s]
[INFO] pinpoint-plugins ................................... SUCCESS [  0.243 s]
[INFO] pinpoint-bootstrap-core-optional ................... SUCCESS [  0.252 s]
[INFO] pinpoint-tools ..................................... SUCCESS [  0.681 s]
[INFO] pinpoint-agent-distribution ........................ SUCCESS [  3.672 s]
[INFO] pinpoint-collector ................................. SUCCESS [03:19 min]
[INFO] pinpoint-profiler-optional-jdk8 .................... SUCCESS [  0.364 s]
[INFO] pinpoint-web ....................................... SUCCESS [19:39 min]
[INFO] pinpoint-hbase-distribution ........................ SUCCESS [  0.195 s]
[INFO] pinpoint-thirdparty ................................ SUCCESS [  0.202 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23:33 min
[INFO] Finished at: 2016-11-14T22:59:37+05:30
[INFO] Final Memory: 198M/1453M
[INFO] ------------------------------------------------------------------------

If the Build happens to be successful from Maven then it should work fine that what i presume 

Even the start collector/Start-Init Hbase works fine and why I am getting this issue only while starting the webapp(Agent) even the Build is successful

Appreciate if you could explain me better , Thanks for your understanding and concern here

**Comment by Xylus** [comment]
@dinesh4747 
yeh, that is definitely weird.

Not 100% certain in this but my guess is that we defined maven central repository with http in our root pom.xml so for the build it worked fine.

The quickstart testapp (or any other quickstart modules) however does not inherit from this, so it might have defaulted to connect to maven central with https.
(Quickstart collector module might have been built successfully because it did not require maven jar plugin)
