### ISSUE TITLE
unable to connect to Amazon EMR 

### ISSUE THREAD

**Issue by kaverappa-ib** [naver/pinpoint#2256]
Hi i'm trying to connect pinpoint collect to hbase in Amazon EMR I chanced **hbase.client.host** to point to my hbase cluster and pointed zookeeper to the same and rebuild using mvn.

Note I'm using quickstart to run the collector.

**Comment by Xylus** [comment]
Hi @kaverappa-ib 
Could you post the relevant collector log with the connection errors please?

**Comment by kaverappa-ib** [comment]
![screenshot from 2016-11-16 13 26 19](https://cloud.githubusercontent.com/assets/15953628/20339144/bc9e5934-ac00-11e6-91c7-e1fe1479e138.png)

could you please brief me about pinpoint.collector.properties file 
these are my data

cluster.enable=true
cluster.zookeeper.address=54.196.2.100
cluster.zookeeper.sessiontimeout=30000
cluster.listen.ip=54.196.2.100
cluster.listen.port=2181

**Comment by Xylus** [comment]
Is your collector also up in AWS? How are your instances set up?

**Comment by kaverappa-ib** [comment]
yes I built it from the pinpoint repo

**Comment by Xylus** [comment]
From the log above, it looks like the collector's hbase client is trying to connect to *Pinpoint-test*. Is this the domain name of the instance that's hosting hbase?

**Comment by kaverappa-ib** [comment]
yes its the domain name

**Comment by kaverappa-ib** [comment]
could you please tell me the sets to connect to external hbase so that I can cross check if I have missed something

**Comment by Xylus** [comment]
You can set them in *hbase.properties* for both collector (`$QUICK_START/collector/src/main/resources/hbase.properties`) and web (`$QUICK_START/web/src/main/resources/hbase.properties*).

**Comment by kaverappa-ib** [comment]
I have update my hbase master there.
do I have to make change in pinpoint-collector.properties

**Comment by kaverappa-ib** [comment]
so that I point to zookeeper of the hbase cluster

**Comment by Xylus** [comment]
The cluster options in *pinpoint-collector.properties* is for real time communication. Could you set the `cluster.enable` option to false until we can get hbase connection working?

**Comment by kaverappa-ib** [comment]
link to complete log file https://docs.google.com/document/d/1wPLEFP_SPJsDuU9T156HtDTYCJeVv6nBaF4GBDz2n60/edit?usp=sharing

I changed cluster.enable to false remain the mvn build and tried to start collector but still fails

**Comment by Xylus** [comment]
The *Unable to determine local hostname -falling back to "localhost"* line from the log seems to point to domain resolution issues on AWS.
Please check your dns related settings in AWS.
