### ISSUE TITLE
Fix ASMClass.addDelegatorMethod()

### ISSUE THREAD

**Issue by jaehong-kim** [naver/pinpoint#2264]
Fixed an issue where Class generates invalid bytecode.

Caused by java.lang.ClassFormatError.

fix
* class name of INVOKESPECIAL.
* local variables of method.

Affects Plugin : nothing
 - addDelegatorMethod() API only uses the Naver internal platform.

**Comment by emeroad** [comment]
fixed version : 1.6.0-RC1
