### ISSUE TITLE
Problem viewing my app in pinpoint webui

### ISSUE THREAD

**Issue by karkaletsis** [naver/pinpoint#2273]
I have setup 1.6.4 version of pinpoint and install an agent in one of my apps. I can't see my app in webui (nothing to select from dropdown "select an application". 

As for the 2 wars installed, I can't see also any page in pinpoint-collector. Is it correct?
I don't see any error in tomcat when starting and deploying the two war files. I have also opened required ports on server as documented

You can find also the agent log 
[1-pinpoint.log.zip](https://github.com/naver/pinpoint/files/603830/1-pinpoint.log.zip)

Am I doing something wrong?

**Comment by Xylus** [comment]
Hi @karkaletsis 
Please double check the pinpoint version, we don't have 1.6.4 yet :)
From your agent log, it seems like the agent connected to the collector very late after retrying for a long time (after which the log ends so I'm not sure if anything got sent to the collector).
To ensure optimal operation, please ensure that your collector has started up successfully before starting your agent.

As for your question - *I can't see also any page in pinpoint-collector*, I don't fully understand your question as the collector doesn't have it's own UI.

Another thing to note is that Pinpoint web needs to be deployed as ROOT (https://github.com/naver/pinpoint/blob/master/doc/installation.md#installation-2)

**Comment by karkaletsis** [comment]
Thanks for your answer. It seems that both war files (collector and ui) have started successfully. As for the version I was refering to 1.6.0-RC2 (was a typo). 

I started:
hbase
tomcat with two wars

and my application with the agent enabled. 

What do you mean "The web module must also be deployed as a ROOT application." Isn't enough to drop it to webapps? I have to rename it to ROOT?

**Comment by karkaletsis** [comment]
The problem solved after I renamed the pinpoint-web to ROOT.war and deployed to my tomcat. Thanks !)

**Comment by Xylus** [comment]
Awesome, glad it worked out :+1:

**Comment by karkaletsis** [comment]
It worked, but I can't see for example call stack. I attach a screen to show you. How can I see the call stack, sql queries etc?
<img width="1015" alt="screen shot 2016-11-22 at 09 22 52" src="https://cloud.githubusercontent.com/assets/3229727/20514564/4abb01f2-b095-11e6-817f-42ea5b4ef15d.png">

**Comment by koo-taejin** [comment]
please refer to this video. (https://www.youtube.com/watch?v=U4EwnB34Dus )

**Comment by karkaletsis** [comment]
I have already seen it. I get in the bottom of the screen "Realtime Active Thread Chart" and it recommends me to set  profiler.tcpdatasender.command.accept.enable=true. But it is already set to my agent like this

**Comment by koo-taejin** [comment]
* Realtime Active Thread Chart
If you want to see "Realtime Active Thread Chart', then you need to click REALTIME Button. 
![1](https://cloud.githubusercontent.com/assets/10057874/20515020/cb113e6a-b0d2-11e6-930f-45b50d11e6ff.png)

* Call Stack 
If you wnat to see for example call stack. then you need to drag Scatter-Chart.
https://youtu.be/U4EwnB34Dus?t=195

**Comment by karkaletsis** [comment]
When I click Real Time Button I get this
<img width="1426" alt="screen shot 2016-11-22 at 10 46 26" src="https://cloud.githubusercontent.com/assets/3229727/20516818/f6a1b2e4-b0a0-11e6-9c7d-761fb9c24d73.png">

As I said you before I don't see something in the bottom of the screen (NOT FOUND) and I can see Scatter Chart also

**Comment by koo-taejin** [comment]
* Realtime Active Thread Chart
Please refer to the below guide.
 ```
# -------------------------------------------------------------------------------------------------
# The cluster related options are used to establish connections between the agent, collector, and web in order to send/receive data between them in real time.
# You may enable additional features using this option (Ex : RealTime Active Thread Chart).
# -------------------------------------------------------------------------------------------------
# Usage : Set the following options for collector/web components that reside in the same cluster in order to enable this feature.
# 1. cluster.enable (pinpoint-web.properties, pinpoint-collector.properties) - "true" to enable
# 2. cluster.zookeeper.address (pinpoint-web.properties, pinpoint-collector.properties) - address of the ZooKeeper instance that will be used to manage the cluster
# 3. cluster.web.tcp.port (pinpoint-web.properties) - any available port number (used to establish connection between web and collector)
# -------------------------------------------------------------------------------------------------
# Please be aware of the following:
#1. If the network between web, collector, and the agents are not stable, it is advisable not to use this feature.
#2. We recommend using the cluster.web.tcp.port option. However, in cases where the collector is unable to establish connection to the web, you may reverse this and make the web establish connection to the collector.
#   In this case, you must set cluster.connect.address (pinpoint-web.properties); and cluster.listen.ip, cluster.listen.port (pinpoint-collector.properties) accordingly.
```

* Call Stack 
As you can see KLEEMAAN no request received. Dot in Scatter chart means per request. 
So try again after making enough requests.

**Comment by karkaletsis** [comment]
Does it needed to change default values of the properties described? 
I have done enough requests to my application (at least 40). Do you think it is a configuration problem? 

I see lines like this in log

2016-11-22 09:10:44 [INFO ](c.n.p.w.c.ScatterChartController   ) Fetch scatterData time : 15ms

and also this

2016-11-22 09:11:16 [INFO ](c.n.p.w.w.ActiveThreadCountHandler ) ConnectionEstablished. session:StandardWebSocketSession[id=6, uri=/agent/activeThread.pinpointws]
2016-11-22 09:11:17 [INFO ](c.n.p.w.w.ActiveThreadCountHandler ) handleTextMessage. session:StandardWebSocketSession[id=6, uri=/agent/activeThread.pinpointws], remote:/46.177.88.243:55243, message:{"type":"REQUEST","command":"activeThreadCount","parameters":{"applicationName":"KLEEMANN"}}.
2016-11-22 09:11:17 [INFO ](c.n.p.w.w.ActiveThreadCountHandler ) unbindingResponseAggregator. session:StandardWebSocketSession[id=6, uri=/agent/activeThread.pinpointws], applicationName:null.
2016-11-22 09:11:17 [INFO ](c.n.p.w.w.ActiveThreadCountHandler ) bindingResponseAggregator. session:StandardWebSocketSession[id=6, uri=/agent/activeThread.pinpointws], applicationName:KLEEMANN.
2016-11-22 09:11:17 [INFO ](ActiveThreadCountResponseAggregator) addWebSocketSession. applicationName:KLEEMANN, webSocketSession:StandardWebSocketSession[id=6, uri=/agent/activeThread.pinpointws]
2016-11-22 09:11:17 [INFO ](c.n.p.w.w.ActiveThreadCountWorker  ) ActiveThreadCountWorker start. applicationName:KLEEMANN, agentId:2
**2016-11-22 09:11:17 [WARN ](c.n.p.w.c.ClusterManager           ) KLEEMANN/2/1479800165509 couldn't find agent.**

It seems that ClusterManager can't find agent

**Comment by koo-taejin** [comment]
Even if you have sent enough requests, it will not come out if there are no requests sent during selected time
And you're first log shows the network connection seems to be unstable,  check that part too.

Default zookeeper address setting is set to localhost in cluster configuration. 
If zookeepr is not located in localhost. Please change your setting.

**Comment by karkaletsis** [comment]
I haven't setup any additional for zookeeper. I have just deployed the two wars and started hbase.

**Comment by koo-taejin** [comment]
If you then do to use zookeeper which using in hbase.

**Comment by karkaletsis** [comment]
Unfortunately I can't make it work as expected.

**Comment by Xylus** [comment]
@karkaletsis Reading through the issue again, I'm not sure if I understand what you're looking for.
To clarify, are you looking for a way to view the call stack? or are you trying to get the realtime active thread charts working? Or is it both? :)

**Comment by karkaletsis** [comment]
I am trying to do both. And more general I am trying to see If I can use this tool for monitoring jvm performance and also see call stack and possible slow sql queries. Is it possible?

**Comment by Xylus** [comment]
Okay, let's tackle the call stack first.
In your first screenshot (not the real time one), there should be a scatter chart on the top right hand corner with green dots.
As koo-taejin said above, dragging on these dots will open up the transaction list window that contains information about these dots, including their call stack and sql queries.

**Comment by karkaletsis** [comment]
I see this screen 
<img width="1437" alt="screen shot 2016-11-23 at 10 45 29" src="https://cloud.githubusercontent.com/assets/3229727/20555308/06052ea4-b16a-11e6-95af-a881a35530cd.png">

I don't see the scatter chart there.

**Comment by nstopkimsk** [comment]
![2016-11-23 5 47 53](https://cloud.githubusercontent.com/assets/1729699/20555359/0321c766-b1a5-11e6-8f82-6b1bd9adf127.png)

**Comment by karkaletsis** [comment]
Ok, I found some data in the scatter chart after some requests and drag it over and then displayed the call stack. Thanks for helping on this. Can we check also the problem with displaying real data?

**Comment by koo-taejin** [comment]
Please refer to the below guide.
 ```
# -------------------------------------------------------------------------------------------------
# The cluster related options are used to establish connections between the agent, collector, and web in order to send/receive data between them in real time.
# You may enable additional features using this option (Ex : RealTime Active Thread Chart).
# -------------------------------------------------------------------------------------------------
# Usage : Set the following options for collector/web components that reside in the same cluster in order to enable this feature.
# 1. cluster.enable (pinpoint-web.properties, pinpoint-collector.properties) - "true" to enable
# 2. cluster.zookeeper.address (pinpoint-web.properties, pinpoint-collector.properties) - address of the ZooKeeper instance that will be used to manage the cluster
# 3. cluster.web.tcp.port (pinpoint-web.properties) - any available port number (used to establish connection between web and collector)
# -------------------------------------------------------------------------------------------------
# Please be aware of the following:
#1. If the network between web, collector, and the agents are not stable, it is advisable not to use this feature.
#2. We recommend using the cluster.web.tcp.port option. However, in cases where the collector is unable to establish connection to the web, you may reverse this and make the web establish connection to the collector.
#   In this case, you must set cluster.connect.address (pinpoint-web.properties); and cluster.listen.ip, cluster.listen.port (pinpoint-collector.properties) accordingly.
```

**Comment by karkaletsis** [comment]
The two webapps collector and web are in the same machine. The web application running the agent is in another network but this is stable

 Lets say that I have the following: 
Collector IP: 1.1.1.1
Web IP: 1.1.1.1
Web application with agent: 2.2.2.2

What I have to set to these properties? 

cluster.connect.address
cluster.listen.ip
cluster.listen.port

**Comment by koo-taejin** [comment]
#2. We recommend using the cluster.web.tcp.port option. However, in cases where the collector is unable to establish connection to the web, you may reverse this and make the web establish connection to the collector.
#   In this case, you must set cluster.connect.address (pinpoint-web.properties); and cluster.listen.ip, cluster.listen.port (pinpoint-collector.properties) accordingly.

**Comment by emeroad** [comment]
Pinpoint is not a commercial service.
We do not provide technical support.
**Look at the guide and solve the problem yourself.**
