### ISSUE TITLE
Error in logs when using alarms on Mysql

### ISSUE THREAD

**Issue by gitzalm** [naver/pinpoint#2279]
#### Description
I got some error logs when using alarms:

```
Error MySQL com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'date_time' in 'field list' (alarm)
```

I found in IBatis mapper /web/target/deploy/WEB-INF/classes/mapper/AgentStaticsMapper.xml:

```
INSERT INTO agent_statistics (date_time, agent_count)
```

Whereas in web/src/main/resources/sql/CreateTableStatement-mysql.sql there is:
```
CREATE TABLE `agent_statistics` (
        `agent_count` INT(10) UNSIGNED NOT NULL,
        `date_val`DATETIME NOT NULL,
        PRIMARY KEY (`date_val`)
);
```

Which of date_val ou date_time is the right value ?

I hope to find the fix for this before the coming great 1.6.0 release !

#### Environment
* Pinpoint version: 1.6.0-SNAPSHOT (current master)
* Linux CentOS
* Using alarms batch job on mysql

**Comment by Xylus** [comment]
@gitzalm Thanks for the bug report!

**Comment by koo-taejin** [comment]
@gitzalm  I fixed bad field name which related to AgentStatics. 
Thanks for the bug report! :)

**Comment by gitzalm** [comment]
Great, that was a quick fix.
