### ISSUE TITLE
Problem displaying sql queries - can't connect to db

### ISSUE THREAD

**Issue by karkaletsis** [naver/pinpoint#2283]
#### Description
I have setup an agent to a tomcat instance and try to collect some data. I can get data but the web ui informs me that the db is unknown and so when I go to call stack I don't have information about sql queries. Tomcat webapp is configured to connect with Mysql Database

#### Environment

* Pinpoint version: 1.6.0-RC2 
* OS: Ubuntu 12.04, Apache Tomcat 7, Mysql 5
* Additional details: Collector and Web installed in same machine

**Comment by emeroad** [comment]
Perhaps It seems to be related to #2013
 - #2013 Add support for MySQL connector 6 
Unfortunately, 6.x Mysql JDBC Driver is not supported yet.

Please let me know the version of Mysql driver you are using.

**Comment by karkaletsis** [comment]
We are using mysql-connector-java-5.1.23-bin.jar

**Comment by emeroad** [comment]
We do not know all types of Mysql JDBC Connection URL.
 - Connection URL sample : jdbc:mysql://1.2.3.4:5678/test_db  ~~
 - jdbc:mysql:loadbalance:~~~ <- Load balance support is incomplete yet. 

What type of URL do you use?
Is there any error log?

**Comment by karkaletsis** [comment]
jdbc:mysql://<ipaddress>/lf6100_dsth?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false

No some error log in collector logs
