### ISSUE TITLE
log link button can not work

### ISSUE THREAD

**Issue by zhangzhaoyu** [naver/pinpoint#2285]
#### Description

Hi, I am using pintpoint to trace my spring boot application. pinpoint is a really great application. In my case, I stored the detail logs into elasticsearch. I do everything as you say in ** per-request_feature_guide.md**, than I can get the log button, but when I click it, it can't open the destination url by the broswer. 

When I debug, I find the property **RecordSet.loggingTransactionInfo** is false. Because of it, I can not click the log button to show the detail logs.

Can you help me how to set the value of **RecordSet.loggingTransactionInfo** ? 
Thank you very much !!!

**Comment by minwoo-jung** [comment]
Hello 

Sorry! I'm not improve goude.

Pinpoint 1.5.0 or later, we improve button to decided enable/disable depending on wherether or not being logged.

You should implement interceptor for using logging appender. We also developed plugin for logging appdender internally.

Please refer to Pinpoint Profiler Plugin Sample. https://github.com/naver/pinpoint-plugin-sample.
This is interceptor example.

```
public class AppenderInterceptor implements AroundInterceptor0 {

    private final TraceContext traceContext;

    public AppenderInterceptor(TraceContext traceContext) {
        this.traceContext = traceContext;
    }

    @Override
    public void before(Object target) {
        Trace trace = traceContext.currentTraceObject();

        if (trace != null) {
            SpanRecorder recorder = trace.getSpanRecorder();
            recorder.recordLogging(LoggingInfo.LOGGED);
        }
    }

    @IgnoreMethod
    @Override
    public void after(Object target, Object result, Throwable throwable) {

    }
}
```

**Comment by minwoo-jung** [comment]
I updated guide.

**Comment by zhangzhaoyu** [comment]
Thank you for your prompt reply.
But I still confused. When I configured the file of **pinpoint.config** as below to use log4j as the log framework:
_log4j
profiler.log4j.logging.transactioninfo=true
logback
profiler.logback.logging.transactioninfo=false_
 
Than should I configure the pinpoint-agent log4j.xml file under the directory of **../pinpoint-agent-1.5.2/lib/log4j.xml** to print the MDC shared **Txid and PtxId** or I need to configure my own application's log4j.xml to print the **Txid and PtxId**？

In my application, I configured my own spring boot and dubbo based application's log4j.xml to the under style:
`
<Pattern >%d{HH:mm} %-5level %logger{36} - [TxId : %X{PtxId} , SpanId : %X{PspanId}] %msg%n</Pattern >
`

then I can get the TxId and PtxId in my own application's logger. for example 
@Controller
public class HelloController {
    private final static Logger LOG = LoggerFactory.getLogger(HelloController.class);

    @RequestMapping(value = "/hello", method = RequestMethod.GET)
    @ResponseBody
    public String sayHello() {
        LOG.info("sayHello-----------------------");
        annotationConsumerServiceFacade.callSayHello("zhangzhaoyu");
        return "say hello zhangzhaoyu";
    }
}
the code **LOG.info("sayHello-----------------------");** can print the Txid and PtxId as the declared log style. But when I just configured pinpoint agent log4j.xml, it can not work.

You just said **I should implement interceptor for using logging appender**, does it mean I need to refactor **pinpoint-log4j-plugin** . To  make the class of ** LoggingEventOfLog4jInterceptor implements AroundInterceptor0**  to record the debug info. Just by add the code:
```
if (trace != null) {
            SpanRecorder recorder = trace.getSpanRecorder();
            recorder.recordLogging(LoggingInfo.LOGGED);
 }
```
Can you give me some advice? Thank you very much !!!

**Comment by minwoo-jung** [comment]
I understanded your question^^

I recommand you should create new plugin project to generate interceptor for appender that you're using.
Because pinoint-log4j-pluin is only intercept LoggingEvent class.

You should intecept method of appender class configured in your log4j.xml file to decided enable/disable depending on wherether or not being logged.
You should find method to log for data of loggingEvent and intercept it.
You need to review code appender class. But you can easily find method.^^

**Comment by zhangzhaoyu** [comment]
I have read some source code of pinpoint-web last weekend.
The controller of **BusinessTransactionController** uses the class of **SpanService** to get the transactionInfo from Hbase. RecordSet.loggingTransactionInfo depends on SpanBo of the Transaction.

If I want to make the log button enable, I suppose I need to make the SpanBo's property of loggingTransactionInfo ture.
The pinpoint-agent collects the transaction data and send them to pinpoint-collector. So I need to update the plugin to enable the SpanBo's loggingTransactionInfo property as you said before.
`
if (trace != null) {
            SpanRecorder recorder = trace.getSpanRecorder();
            recorder.recordLogging(LoggingInfo.LOGGED);
 }
`
The trace info will be send to pinpoint-collector. 
Is what I'am saying  right?

If I am right, I don't know why I should to implement log4j's Appender in my own application. My own project's log was stored in elasticsearch. 
Does it mean I need to send the **LOGGED** flag information  to pinpoint-collector, before I stored the log information to elasticsearch?

**Comment by zhangzhaoyu** [comment]
I just tried to add the upper code into the spring-plugin like below:

```
public class BeanMethodInterceptor implements ApiIdAwareAroundInterceptor {

    private final PLogger logger = PLoggerFactory.getLogger(BeanMethodInterceptor.class);
    private final boolean isDebug = logger.isDebugEnabled();

    private final TraceContext traceContext;
    private final boolean markError;

    public BeanMethodInterceptor(TraceContext traceContext, boolean markError) {
        this.traceContext = traceContext;
        this.markError = markError;
    }
    
    @Override
    public void before(Object target, int apiId, Object[] args) {
        if (isDebug) {
            logger.beforeInterceptor(target, args);
        }

        final Trace trace = traceContext.currentTraceObject();
        if (trace == null) {
            logger.info("BeanMethodInterceptor.before ***+++ trace is null");
            return;
        }
        // TODO
        SpanRecorder recorder = trace.getSpanRecorder();
        recorder.recordLogging(LoggingInfo.LOGGED);
        logger.info("BeanMethodInterceptor.before ***+++");
        System.out.println("BeanMethodInterceptor.before ***+++");

        final SpanEventRecorder recorders = trace.traceBlockBegin();
        recorder.recordServiceType(SpringBeansConstants.SERVICE_TYPE);
    }
.......
}
``` 
Then, **excellently**, The log button on pinpoint-web can be clicked and opened another new browser page.

![screenshot from 2016-11-28 14 13 12](https://cloud.githubusercontent.com/assets/5105709/20658057/44ba72c6-b575-11e6-89c4-e2317f4de01d.png)

After clicked:

![screenshot from 2016-11-28 14 13 35](https://cloud.githubusercontent.com/assets/5105709/20658062/4b493f00-b575-11e6-89e2-6e515c143c12.png)

That's what I want. Thank you very much.

I think you can make the log button enable/unable feature be configured by the **pinpoint.config** file.
Just by configuring the "LOGGED" properties of each plugin.
Will you do it in the future for the new version?

**Comment by minwoo-jung** [comment]
1.
How are you saving your logs to elasticsearch? 
Are you implementing your own appender, or are you using some open source appender? Or are you parsing your local log files and sending them to elasticsearch manually?
If you can show me the code/class for the appender that saves logs to elastic search, I could take a look at it and tell you which methods to hook the interceptors. 

2.
I wouldn't recommend your current approach.
There is something you need to know - adding the `recorder.recordLogging(...)` to the bean interceptor will activate the log button in the web UI for every single trace, **including those that did not send it's log to elasticsearch**.
This will confuse the users as the log button will be active even for traces that didn't send their logs to elasticsearch. 

3.
Don't put too much stress into `LoggingInfo.LOGGED`. Just think of it as a boolean flag to indicate that a log has been recorded for now. Our future plan is to expand on this to record the log levels as well.
 
4.
I think adding the enable/disable configuration for each plugin to *pinpoint.config* would only confuse the users. Activating the log button depending on whether a trace sent it's log to a storage server, or not use log button and directly search for this log using the *transactionId* in logging server(ex. elasticsearch server) (which is our current approach) - is much less confusing than blindly leaving this to a configuration option for different plugins.

**Comment by zhangzhaoyu** [comment]
1. I just used the **[logstash-logback-encoder](https://github.com/logstash/logstash-logback-encoder)** to send log data to my logstash. The class of **net.logstash.logback.appender.LogstashTcpSocketAppender** was used. 
**logback.xml configuration** of my application:

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <appender name="stash" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
      <destination>127.0.0.1:4560</destination>

      <!-- encoder is required -->
      <encoder class="net.logstash.logback.encoder.LogstashEncoder" />
  </appender>

  <root level="DEBUG">
      <appender-ref ref="stash" />
  </root>
</configuration>
```

**logstash configuration**:

```
input {
      tcp {
      	    port => "4560"
	    codec => json_lines
      }
}
output {
	elasticsearch {
		      hosts => ["localhost:9200"]
		      user => elastic
		      password => changeme
		      }
  	stdout { codec => rubydebug }
}

```

2. I just understood you. My current implementation exists some problems. If I want to reform the class **LogstashTcpSocketAppender** to trace my own business log, what should I do to make the **pinpoint-collector** know I have traced the transaction? If I can not send the **recorder.recordLogging(...)** flag to **pinpoint**, how can I make the **log button** appear?

Can you get my question? Thank you a lot.

**Comment by minwoo-jung** [comment]
Ok I got it. I'll reply soon.

**Comment by minwoo-jung** [comment]
I reviewed code LogstashTcpSocketAppender class to find target method of interceptor 
I recommand method `protected void append(Event event)`.
But you should review code and debug this class at runtime because I'm not debug it and There may be a better method.
Here are tip. You would select method of child class better then method of parent class.

There is no need to change code at pinpoint-collector. You have only to do as follow guide.

**Comment by irocks04** [comment]
Hi ,
I went through the details and I am trying to implement to view the log button. If possible please let me know which method of parent class do i need to select? And is there a sample implementation for appender class that i can use?

Please correct me in terms of steps 
1) I need to implement interface aroundinterceptor0
2) I need to implement appender class and which method(?)

Sample classes if anyone has that can help me.

**Comment by zhangzhaoyu** [comment]
First, you need to make the collector know you have kept the details log.
Secondly, you need to config the pinpoint-web properties file.
```
recorder.recordLogging(LoggingInfo.LOGGED); is very important.
```
you can read the above message, which is  very detail and clear.
@irocks04
