### ISSUE TITLE
where is maven repository for pinpoint version 1.5.1

### ISSUE THREAD

**Issue by zhangyong-a** [naver/pinpoint#2291]
I want write my plugin,but not found pinpoint verson 1.5.1 in public repository. 

which maven repository  for you use?

Thank you

**Comment by koo-taejin** [comment]
Hi zhangyong-a

We do not deploy pinpoint to any public maven repositories.
If you want to devlope pinpoint plugin, I recommend that you build and install pinpoint in your local maven repository.

**Comment by zhangyong-a** [comment]
OK Thank you.

 

 

发件人: koo-taejin [mailto:notifications@github.com] 
发送时间: 2016年11月30日 13:10
收件人: naver/pinpoint
抄送: zhangyong-a; Author
主题: Re: [naver/pinpoint] where is maven repository for pinpoint version 1.5.1 (#2291)

 

Hi zhangyong-a

We do not deploy pinpoint to any public maven repositories.
If you want to devlope pinpoint plugin, I recommend that you build and install pinpoint in your local maven repository.
