### ISSUE TITLE
Why does a new Weblogic Plugin keeps using Tomcat icon?

### ISSUE THREAD

**Issue by jclu123** [naver/pinpoint#2293]
#### Description
I am creating a new plugin for Weblogic, and have updated the htIcon portion in jquery.ServerMap2.js:

'WEBLOGIC': 'WEBLOGIC.png',
'WEBLOGIC_GROUP': 'WEBLOGIC.png'
 
But my plugin continues to use the TOMCAT icon (and yes, I do have the WEBLOGIC servicetype defined and WEBLOGIC.png is added to both the icon and the servermap directories)

What else should I do to get the WEBLOGIC icon to show up?

#### Environment

* Pinpoint version: 1.5.2
* OS, WAS, affected library, etc:  My OS is Windows 10, Weblogic version is 10.3.6
* Additional details (e.g. how your collector/web is set up): I use quickstart to start up my web and collector after I rebuild with the new plugin as it is the most convenient way for me to run my dev cycle.

**Comment by jclu123** [comment]
An update...

An update:

I do get this from the agent log...
 ...DefaultClassNameMatcher{org/apache/catalina/connector/RequestFacade}
 ...DefaultClassNameMatcher{org/apache/catalina/connector/Request} 
 ...DefaultClassNameMatcher{org/apache/catalina/core/StandardHostValve} 
 ...DefaultClassNameMatcher{org/apache/catalina/core/StandardService} 
 ...DefaultClassNameMatcher{org/apache/catalina/connector/Connector} 
 ...DefaultClassNameMatcher{org/apache/catalina/loader/WebappLoader} 
 ...DefaultClassNameMatcher{org/apache/catalina/core/AsyncContextImpl} 
_[INFO ](c.n.p.p.u.ApplicationServerTypeResolver:78 ) Configured ApplicationServerType : TOMCAT_

While I don't believe TOMCAT classes are being loaded the log does say they are.  But in any case, the ApplicatonTypeDetector  for TOMCAT would certainly not have been satisfied because there is definitely not a  "catalina.home" in the system parameters.

I am pretty sure, however, the Weblogic ApplicationTypeDetector will detect true as its detect method is very simple (only looks for a REQUIRED_MAIN_CLASS)

**Comment by Xylus** [comment]
Hi @jclu123 
Are you using the quickstart agent for your weblogic application?
The *INFO Configured ApplicationServerType : TOMCAT* means that the `profiler.applicationservertype=TOMCAT` has been set in *pinpoint.config*. This option disables overrides the application type detection so this is why your application is showing up as TOMCAT.
The quickstart agent has this property set as it was only meant to be used with the quickstart's testapp.

If you're using the quickstart agent, either
1. Use the proper agent - should be under *$PINPOINT/agent/target/pinpoint-agent-$VERSION* 
2. Edit the quickstart agent's *pinpoint.config* by commenting out the `profiler.applicationservertype=TOMCAT` option

Please give the above a try and let me know how it goes.
Thanks

**Comment by jclu123** [comment]
Hi @Xylus 

Thanks for writing back.

I removed the profiler.applicationservertype=TOMCAT from pinpoint.config in the quickstart agent and did eliminate the TOMCAT icon from showing up, however, the WEB now uses the 
![image](https://cloud.githubusercontent.com/assets/22934575/20803540/98f422ca-b7bd-11e6-9e22-a3eccbab1332.png) icon instead of the weblogic icon I had put in /images/icon and /images/servermap

I did make sure that htIcon portion in jquery.ServerMap2.js is updated with my weblogic portion...

                    'USER': 'USER.png',
                    'USER_GROUP': 'USER.png',
		    'WEBLOGIC': 'WEBLOGIC.png',
                    'WEBLOGIC_GROUP': 'WEBLOGIC.png'
                },
But that didn't help.  i also noticed that on startup, the WEB does not load my WEBLOGIC.png from the servermap directory (i.e. there is NO 

.... GET /images/servermap/WEBLOGIC.png ....

In TOMCAT's access log while that log shows all other images in that directory being loaded in.

And the weblogic server is indeed being discovered since I do see this in the agent log

![image](https://cloud.githubusercontent.com/assets/22934575/20804261/39a91ff2-b7c0-11e6-9d6c-12ddac645902.png)

The worst part is,  without using the TOMCAT icon (i.e. not setting the profiler.applicationservertype parameter in pinpoint.config) PINPOINT is no longer profiling (i.e. no stack trace, no instrumentation is shown).

Is there something else that I am missing/not doing?

Thanks in advance

**Comment by Xylus** [comment]
For the image part, you'll have to rebuild pinpoint web after editing the `server-map2/jquery.ServerMap2.js` file. Give this a go and let me know if it works or not.

As for the Weblogic classes not being traced when *profiler.applicationservertype* is not set, it might happen if your Weblogic plugin is transforming the same classes as Tomcat (such as `org.apache.catalina.core.StandardHostValve` etc).
I'm not familiar with the classes in Weblogic, could you check if you're modifying the same classes in your Weblogic plugin as the ones in the Tomcat plugin? (You can check `com.navercorp.pinpoint.plugin.tomcat.TomcatPlugin` for this)

Please let me know of your findings.
Thanks!

**Comment by jclu123** [comment]
Hello sir:

After some looking around, I did manage to get part of weblogic working, that 1 out of 2 icon works and the tracing works.  So what is left is this particular puzzle...  Please see.

![image](https://cloud.githubusercontent.com/assets/22934575/20875153/68483f3c-ba86-11e6-9116-14aec494f7ba.png)


As you can see the small icon shows up, but the server map icon does not.  I did re-build the web portion after updating jquery.ServerMap2.js.  And I do see in **pinpoint-quickstart-web-1.5.2.war**   both a 25x25 png in the icon directory and a 80x40 png in the servermap directory.  Of course I also see the same in **pinpoint-web-1.5.2.war** as well.  

To be sure, I am still running everything from quickstart, and I have commented out _profiler.applicationservertype_ in **quickstart\agent\target\pinpoint-agent\pinpoint.confg**

Thank you very much for your help, I think we are getting pretty close.

**Comment by Xylus** [comment]
That looks very similar to what happens when the updated `jquery.serverMap2.js` isn't deployed properly. To make sure, could you open the Chrome Developer Tool and check the source for `'WEBLOGIC': 'WEBLOGIC.png'` code you've added?
(You might need to check `pinpoint-component.min.js` under *lib/js* if it's quickstart web)

**Comment by jclu123** [comment]
You are right, WEBLOGIC.png is NOT in pinpoint-component.min.js when running in quickstart mode.  

 

Thanks for pointing me in the right direction; any hints on how to fix?

**Comment by jclu123** [comment]
A follow up: I updated   ..\pinpoint-1.5.2\web\src\main\webapp\lib\js\pinpoint-component.min.js, to include "WEBLOGIC: "WEBLOGIC.png", rebuilt the entire distribution and now quickstart web works and the server icon shows up correctly.  

It looks like simply updating "..\pinpoint-1.5.2\web\src\main\webapp\components\server-map2\jquery.ServerMap2.js and adding the png files don't seem to be sufficient.  Going forward, should we modify pinpoint-component.min.js if we produce another plugin ?

Again, thanks for pointing me in the right direction.

**Comment by Xylus** [comment]
@jclu123 Thanks for your efforts. Very happy to hear you've worked out the issue.
Modifying `web\src\main\webapp\components\server-map2\jquery.ServerMap2.js` and rebuilding (`mvn clean package`) should be enough, as the javascript files are combined and minified during maven build.
Could you double check and see if you haven't missed the rebuilding step?

**Comment by jclu123** [comment]
I have used mvn install -Dmaven.test.skip=true to build and also  tried mvn package and neither seem to work; should I have done something else instead?

thank you

**Comment by Xylus** [comment]
@jclu123 Thanks for the update, we'll keep an eye out on maven building web issue.

**Comment by godwingrs22** [comment]
Hi @jclu123 ,
I'm also working on developing a sample weblogic plugin for pinpoint.
My weblogic plugin is able to detected by the pinpoint, but i coudn't trace the weblogic application requests.
Can you please tell me the weblogic class which you have used for request and response transformation?

I've used the below code for transformation which failed..

` transformTemplate.transform("**weblogic.servlet.http.AbstractAsyncServlet**", new TransformCallback() {
			@Override
			public byte[] doInTransform(Instrumentor instrumentor, ClassLoader classLoader, String className,
					Class<?> classBeingRedefined, ProtectionDomain protectionDomain, byte[] classfileBuffer)
							throws InstrumentException {
				InstrumentClass target = instrumentor.getInstrumentClass(classLoader, className, classfileBuffer);

				InstrumentMethod handleMethodEditorBuilder = target.getDeclaredMethod("service",
						"javax.servlet.http.HttpServletRequest", "javax.servlet.http.HttpServletResponse");
				if (handleMethodEditorBuilder != null) {
					handleMethodEditorBuilder
							.addInterceptor("it.sella.pinpoint.plugin.weblogic.interceptor.ServerHandleInterceptor");
					return target.toBytecode();
				}

				return target.toBytecode();
			}
		});`

Thanks,
Godwin

**Comment by andyspan** [comment]
@godwingrs22  webloigc 12c is very special！I'm also working on developing a sample weblogic plugin for pinpoint，it can work in weblogic 10 but not weblogic 12c
