### ISSUE TITLE
Call tree has no details about the transactions.

### ISSUE THREAD

**Issue by irocks04** [naver/pinpoint#2294]
#### Description

I can see other details like time line and server details but nothing comes under the call tree.
#### Environment

* Pinpoint version: 1.5.2 

I am using pinpoint 1.5.2 version for both web and collector and the same for agent. 
I can see all the other details except the call tree. 

Question: Does the call tree work only with tomcat based applications?

**Comment by koo-taejin** [comment]
Hi  irocks04 
Could you give me more detail info on your server? 
1. What it's running on and library stacks you're expecting to see get traced.
2. Application main screenshot. (Ex) please give me a screenshot of the same page as the following)
![ss_server-map](https://cloud.githubusercontent.com/assets/10057874/20744243/2da437f2-b71e-11e6-822c-e88415339291.png)

**Comment by irocks04** [comment]
![image](https://cloud.githubusercontent.com/assets/20955417/20748645/022bee84-b715-11e6-8c5e-4cdb5e900b03.png)

Hi, I have attached the screen shot and the logs doesn't show any information about the class. This is actually running as a micro service.

Logs provide all this information but nothing about class 

11-30 10:12:11 [DEBUG](c.n.p.c.h.SpanChunkHandler         :64) Received SpanChunk=TSpanChunk(agentId:2, applicationName:juggernautPerf1cass, agentStartTime:1480500596827, serviceType:1030, transactionId:00 01 DB A0 D9 A5 8B 2B 69, spanId:6279546049285046876, endPoint:rdperf1-cass-gw.altidev.net:80, spanEventList:[TSpanEvent(sequence:1882, startElapsed:680, endElapsed:1, serviceType:2101, endPoint:rdperf1-cass-percona.altidev.net:3336, annotations:[TAnnotation(key:20, value:<TAnnotationValue intStringStringValue:TIntStringStringValue(intValue:-3)>)], destinationId:realdoc_5776631304272627b6548e58, apiId:122), TSpanEvent(sequence:1883, startElapsed:681, serviceType:2100, endPoint:rdperf1-cass-percona.altidev.net:3336, annotations:[TAnnotation(key:20, value:<TAnnotationValue intStringStringValue:TIntStringStringValue(intValue:7)>)], destinationId:realdoc_5776631304272627b6548e58, apiId:-115), TSpanEvent(sequence:1884, startElapsed:681, endElapsed:2, serviceType:2101, endPoint:rdperf1-cass-percona.altidev.net:3336, annotations:[TAnnotation(key:20, value:<TAnnotationValue intStringStringValue:TIntStringStringValue(intValue:7, stringValue2:null, udaykumar.bhat@altisource.com, 2016-11-30 10:12:11.092, PAGE, bdae6842-b442-4464-8849-e72d265fcba6, 1.0, null, c5891db9-e932-4aa7-a6dd-52767200d390, {"pageNumber":77,"sourceFileId":"e2a89384-05e4-4990-94f5-f696a07...(314), udaykumar.bhat@altisource.com, 2016-11-30 10:12:11.092, null, {"filename":"e2a89384-05e4-4990-94f5-f696a07ce5f8_761.PNG","size...(122), e67ccec8-a1f3-43a6-ae23-0e7f5bc7d4ec, 54, ACTIVE, d17fcace-6556-4c9b-b8e7-5d592b9eecd5, null, bc474f07-fde0-4594-a7a0-c4989a3012cf)>)], destinationId:realdoc_5776631304272627b6548e58, apiId:-122), TSpanEvent(sequence:1885, startElapsed:683, endElapsed:1, serviceType:2101, endPoint:rdperf1-cass-percona.altidev.net:3336, annotations:[TAnnotation(key:20, value:<TAnnotationValue intStringStringValue:TIntStringStringValue(intValue:-3)>)], destinationId:realdoc_5776631304272627b6548e58, apiId:122), TSpanEvent(sequence:1886,

**Comment by koo-taejin** [comment]
Looks like everything is ok. 
I wonder how the CallStack page looks when dragging the scatter chart.

If you can't get any information in call stack page, please give me report which use the debugging feature of Chrome.

**Comment by irocks04** [comment]
Hi ,

No issues it worked fine i upgraded to 1.6 version. Just the web part and the call stack appeared. 
Can you help me with the link to create users and groups. I have executed both the sqls and created the tables. Also added details to jdbc.properties.
Once again thank you for looking into this.

**Comment by koo-taejin** [comment]
please refer to following guide page. 
https://github.com/naver/pinpoint/blob/master/doc/alarm.md#alarm

If you can't get enough information on the guid page, please report it

thanks.

**Comment by irocks04** [comment]
Thanks i am creating a separate issue which i found with amazon s3 client.
