### ISSUE TITLE
pinpoint install error 

### ISSUE THREAD

**Issue by doogie300** [naver/pinpoint#2297]
#### Description
pinpoint 설치 시 에러가 발생을 합니다. 잘 설치 진행중이다가 pinpoint-collector 부분에서 에러가 발생을 합니다.

#### Environment
Linux UCDemoSystem 2.6.32-642.3.1.el6.x86_64 #1 SMP Tue Jul 12 18:30:56 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

java : 1.7
maven : 3.3.9

.bash_profile
export JAVA_HOME=/opt/jdk1.7
export JAVA_6_HOME=/usr/local/jdk1.6.0_45
export JAVA_8_HOME=/opt/jdk1.8
export MAVEN_HOME=/home/pin/apache-maven-3.3.9
PATH=$PATH:$HOME/bin:$JAVA_HOME/bin:$MAVEN_HOME/bin

export PATH

#### Additional Info
INFO] pinpoint-agent-distribution ........................ SUCCESS [ 20.375 s]
[INFO] pinpoint-collector ................................. FAILURE [ 14.738 s]
[INFO] pinpoint-profiler-optional-jdk8 .................... SKIPPED
[INFO] pinpoint-web ....................................... SKIPPED
[INFO] pinpoint-hbase-distribution ........................ SKIPPED
[INFO] pinpoint-thirdparty ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:43 min
[INFO] Finished at: 2016-12-01T21:01:21+09:00
[INFO] Final Memory: 62M/591M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.15:check (ensure-java-1.7-class-library) on project pinpoint-collector: Signature errors found. Verify them and ignore them with the proper annotation if needed. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pinpoint-collector

**Comment by koo-taejin** [comment]
README.md 파일의 install 부분을 보면 JDK 6,7,8 모두  환경변수가 필요합니다. 
전달주신 부분에는 6, 8 만 포함이 되어있네요 
해당 부분 추가후 다시 시도해 보세요

**Comment by doogie300** [comment]
해결 했습니다. 감사합니다.
