### ISSUE TITLE
How to integrate pinpoint agent with windows machine.

### ISSUE THREAD

**Issue by irocks04** [naver/pinpoint#2301]
#### Environment

* Pinpoint version: 1.6
* OS : Windows 
* Additional details (e.g. how your collector/web is set up):

More relevantly how to plug this to a bat file which can start the agent

**Comment by irocks04** [comment]
I configured the agent and its started . Also i see that in the web UI.. but for some reason i don't see the data being collected. FYI.. this is a windows box on which the agent is running.

**Comment by koo-taejin** [comment]
@irocks04 
Using Windows does not cause the agent to behave differently.
If SPAN or STAT data is not stored, it is likely to be a UDP network problem.
Collector's log to Debug and check SpanHandler's log shows the agent information of the Windows installed.
