### ISSUE TITLE
quickstart/bin/start-collector.sh not initializing

### ISSUE THREAD

**Issue by tatonki1** [naver/pinpoint#2303]
I just pulled the latest pinpoint docker image - successfully ran the 1st two of these commands on my mac OS X device...

    2  quickstart/bin/start-hbase.sh 
    3  quickstart/bin/init-hbase.sh 
    4  quickstart/bin/start-collector.sh 

But the collector failed to initialize...

root@08eab01fb213:/pinpoint# quickstart/bin/start-collector.sh 
---check pinpoint-quickstart-collector process status.---
---initialize pinpoint-quickstart-collector logs.---
rm /pinpoint/quickstart/logs/quickstart.collector.log.
rm /pinpoint/quickstart/logs/pid/quickstart.collector.pid.
---pinpoint-quickstart-collector initialization started. pid=6620.---
starting pinpoint-quickstart-collector. 0 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 5 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 10 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 15 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 20 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 25 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 30 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 35 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 40 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 45 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 50 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 55 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 60 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 65 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 70 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 75 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 80 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 85 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 90 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 95 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 100 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 105 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 110 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 115 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 120 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 125 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 130 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 135 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 140 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 145 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 150 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 155 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 160 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 165 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 170 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 175 /180 sec(close wait limit).
starting pinpoint-quickstart-collector. 180 /180 sec(close wait limit).
---pinpoint-quickstart-collector initialization failed. pid=6620.---

Log file shows...

more quickstart/logs/quickstart.collector.log 
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.navercorp.pinpoint:pinpoint-quickstart-collector:war:1.5.2
[WARNING] 'version' contains an expression but should be a constant. @ com.navercorp.pinpoint:pinpoint-quickstart-collector:${maven.pinpoint.version}, /pinpoint/quicks
tart/collector/pom.xml, line 11, column 14
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-war-plugin is missing. @ com.navercorp.pinpoint:pinpoint-quickstart-collector:${maven.pinpo
int.version}, /pinpoint/quickstart/collector/pom.xml, line 41, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-war-plugin/2.2/maven-war-plugin-2.2.pom
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-war-plugin:2.2: Plugin org.apache.maven.plugins:maven-war-plugin:2.2 or one of its de
pendencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-war-plugin:jar:2.2
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/properties-maven-plugin/1.0-alpha-2/properties-maven-plugin-1.0-alpha-2.pom
[WARNING] Failed to retrieve plugin descriptor for org.codehaus.mojo:properties-maven-plugin:1.0-alpha-2: Plugin org.codehaus.mojo:properties-maven-plugin:1.0-alpha-2 
or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.codehaus.mojo:properties-maven-plugin:jar:1.0-alpha-2
Downloading: https://repo.maven.apache.org/maven2/org/apache/tomcat/maven/tomcat7-maven-plugin/2.2/tomcat7-maven-plugin-2.2.pom

I'm stuck, any help would be much appreciated!   thanks.

**Comment by nirlya** [comment]
Did you check your JAVA_X_HOME variable ?
You have to use the correct JDK path.

**Comment by tatonki1** [comment]
thanks for your response - the docker images have the following vars setup:

root@695c95012c93:/pinpoint# echo $JAVA_HOME
/usr/lib/jvm/jdk-8-oracle-x64
root@695c95012c93:/pinpoint# echo $JAVA_6_HOME
/usr/lib/jvm/jdk-6-oracle-x64
root@695c95012c93:/pinpoint# echo $JAVA_7_HOME
/usr/lib/jvm/jdk-8-oracle-x64
root@695c95012c93:/pinpoint# echo $JAVA_8_HOME
/usr/lib/jvm/jdk-8-oracle-x64

root@695c95012c93:/pinpoint# 
root@695c95012c93:/pinpoint# ls /usr/lib/jvm
jdk-6-oracle-x64  jdk-8-oracle-x64

**Comment by nirlya** [comment]
It seems to miss JDK7. Can you try with it ?

**Comment by koo-taejin** [comment]
Could you run with -X (debug flag) and post log please?
