### ISSUE TITLE
Transaction trace details export in json,xml,csv,other

### ISSUE THREAD

**Issue by ofauchon** [naver/pinpoint#2304]
Hi. 

I'm using Pinpoint RC2. 

I like the transaction trace details view from web interface, but it's not easy to archive when you find some interesting transaction.

Is there a button or direct link to download the trace details in json/xml/csv/other ?

Thanks

**Comment by Xylus** [comment]
@ofauchon Seems like a useful feature to have, although we don't have a dedicated feature for this.
In the mean time, you could copy the link to save/share it for later.

**Comment by gembez** [comment]
Hello @Xylus 

What would be the best way to export the transaction details from the hbase to a flat file in your opinion?

Thank you very much!

**Comment by Xylus** [comment]
Hi @gembez 
In my opinion, I wouldn't do it :) at least not directly from hbase to a flat file as trace data isn't stored in hbase in a nicely formatted readable form.
So this "export" will have to go through the web to make use of deserializers and mappers there. If I were to implement one, I'd probably use the same API used for the call stack, but instead return a nicely formatted json.

**Comment by AllenKings** [comment]
@Xylus so, do you have a api or other way to export the transactionList to csv?

**Comment by RoySRose** [comment]
Hello, @AllenKings 

Unfortunately, we don't any API to export the data. We have plans. But no hard dates.
