### ISSUE TITLE
jvm crash after use pinpoint a peroid

### ISSUE THREAD

**Issue by orzdj5173** [naver/pinpoint#2326]
#### Description
hi,I'm meeting a problem that jvm crash after use pinpoint a peroid.could you please tell me the reason,tks.
by the way ,I used java8 lambda like:
Map<Integer, List<Category>> groupByParent = categorys.stream().collect(Collectors.groupingBy(Category::getParentId));

#### Environment
Pinpoint version:1.5.2
os:centos 6.5 x64
tomcat:8.0.14
jdk:
java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)

#### some crash infomation
`*#
*# A fatal error has been detected by the Java Runtime Environment:
*#
*#  SIGSEGV (0xb) at pc=0x00000006c2eba910, pid=22567, tid=140296712070912
*#
*# JRE version: Java(TM) SE Runtime Environment (8.0_20-b26) (build 1.8.0_20-b26)
*# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.20-b23 mixed mode linux-amd64 compressed oops)
*# Problematic frame:
*# C  0x00000006c2eba910
*#
*# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
*#
*# If you would like to submit a bug report, please visit:
*#   http://bugreport.sun.com/bugreport/crash.jsp
*#

---------------  T H R E A D  ---------------

Current thread (0x00007f9894007800):  JavaThread "http-apr-8180-exec-2" daemon [_thread_in_Java, id=22646, stack(0x00007f995f9fa000,0x00007f995fafb000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 2 (SEGV_ACCERR), si_addr: 0x00000006c2eba910

Registers:
RAX=0x00000007b52fd980, RBX=0x00007f997661d850, RCX=0x00007f9978819e80, RDX=0x00000006c071df20
RSP=0x00007f995faf6130, RBP=0x0000000775230b88, RSI=0x00000007b52fd980, RDI=0x00000007c012ce90
R8 =0x00000000d80e3be4, R9 =0x00000000f6a850a2, R10=0x00000007b52fd980, R11=0x00007f997acd84a0
R12=0x0000000000000000, R13=0x00007f995faf6120, R14=0x00007f995faf61c8, R15=0x00007f9894007800
RIP=0x00000006c2eba910, EFLAGS=0x0000000000010246, CSGSFS=0x0000000000000033, ERR=0x0000000000000015
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007f995faf6130)
0x00007f995faf6130:   00007f995faf6268 00007f997af128b4
0x00007f995faf6140:   00007f995faf61b0 00007f99787a8710
0x00007f995faf6150:   00000007b4ef6fe0 00007f99787a8710
0x00007f995faf6160:   00000007b52fd980 00000006c071df58
0x00007f995faf6170:   00007f995faf6170 00007f995e2cdde6
0x00007f995faf6180:   00007f995faf61c8 00007f995e2cde68
0x00007f995faf6190:   0000000000000000 00007f995e2cddf8
0x00007f995faf61a0:   00007f995faf6160 00007f995faf61d0
0x00007f995faf61b0:   00007f995faf61d0 00007f997a843984
0x00007f995faf61c0:   00000007b52fd980 00000007b52fd7e8
0x00007f995faf61d0:   00007f996506f06c 0000000775259010
0x00007f995faf61e0:   0000000775258ff0 0000000000000000
0x00007f995faf61f0:   00007f996506f0a0 0000000000000000
0x00007f995faf6200:   00007f995faf6268 00007f99787a88b8
0x00007f995faf6210:   00007f99787a88b8 00000007b52fd7e8
0x00007f995faf6220:   0000000775259010 00007f995faf6228
0x00007f995faf6230:   00007f99648e2e2a 00007f995faf62d0
0x00007f995faf6240:   00007f996481f718 0000000000000000
0x00007f995faf6250:   00007f99648e3020 00007f995faf6218
0x00007f995faf6260:   00007f995faf62c8 00007f995faf6318
0x00007f995faf6270:   00007f99787a8710 0000000000000000
0x00007f995faf6280:   0000000000000000 0000000000000000
0x00007f995faf6290:   0000000000000000 0000000000000000
0x00007f995faf62a0:   00000006c2ca2a08 0000000000000000
0x00007f995faf62b0:   0000000000000000 0000000000000000
0x00007f995faf62c0:   00000007752369c0 00000006c05f0dc0
0x00007f995faf62d0:   00000006c3a7ba10 00007f995faf62d8
0x00007f995faf62e0:   00007f995ec250fe 00007f995faf6340
0x00007f995faf62f0:   00007f995ec253a8 0000000000000000
0x00007f995faf6300:   00007f995ec251a8 00007f995faf62c8
0x00007f995faf6310:   00007f995faf6350 00007f995faf6838
0x00007f995faf6320:   00007f997ac0f6dc 00000007752302b8

Instructions: (pc=0x00000006c2eba910)
0x00000006c2eba8f0:   0f 28 00 d8 ca a9 53 d8 00 00 00 00 00 00 00 00
0x00000006c2eba900:   00 00 00 00 00 00 00 00 00 00 00 00 bc a9 53 d8
0x00000006c2eba910:   15 00 00 00 00 00 00 00 0b f2 0a f8 26 75 5d d8
0x00000006c2eba920:   29 75 5d d8 00 00 00 00 3c 75 5d d8 56 79 a6 f6

Register to memory mapping:

RAX=0x00000007b52fd980 is an oop
com.dark.api.controller.CategoryController$$Lambda$8/856395178
 - klass: 'com/dark/api/controller/CategoryController$$Lambda$8'
RBX={method} {0x00007f997661d850} 'identity' '(Ljava/lang/Object;)Ljava/lang/Object;' in 'sun/invoke/util/ValueConversions'
RCX=0x00007f9978819e80 is at begin+12 in a stub
MethodHandle::interpreter_entry::_linkToStatic [0x00007f9978819e74, 0x00007f9978819e98[ (36 bytes)
RDX=0x00000006c071df20 is an oop
java.lang.invoke.MemberName
 - klass: 'java/lang/invoke/MemberName'
RSP=0x00007f995faf6130 is pointing into the stack for thread: 0x00007f9894007800
RBP=0x0000000775230b88 is an oop
[Ljava.lang.Object;
 - klass: 'java/lang/Object'[]
 - length: 1
RSI=0x00000007b52fd980 is an oop
com.dark.api.controller.CategoryController$$Lambda$8/856395178
 - klass: 'com/dark/api/controller/CategoryController$$Lambda$8'
RDI=0x00000007c012ce90 is pointing into metadata
R8 =0x00000000d80e3be4 is an unknown value
R9 =0x00000000f6a850a2 is an unknown value
R10=0x00000007b52fd980 is an oop
com.dark.api.controller.CategoryController$$Lambda$8/856395178
 - klass: 'com/dark/api/controller/CategoryController$$Lambda$8'
R11=0x00007f997acd84a0 is at entry_point+0 in (nmethod*)0x00007f997acd8350
R12=0x0000000000000000 is an unknown value
R13=0x00007f995faf6120 is pointing into the stack for thread: 0x00007f9894007800
R14=0x00007f995faf61c8 is pointing into the stack for thread: 0x00007f9894007800
R15=0x00007f9894007800 is a thread

Stack: [0x00007f995f9fa000,0x00007f995fafb000],  sp=0x00007f995faf6130,  free space=1008k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x00000006c2eba910`

**Comment by emeroad** [comment]
Old version of JVM is unstable.
1.8.0_40+ version is recommend.

**Comment by orzdj5173** [comment]
thank you,I replaced with jdk1.8.0_111,now work fine~
