### ISSUE TITLE
The CPU data did not show

### ISSUE THREAD

**Issue by TimeStarRipple** [naver/pinpoint#2330]
#### Description

I‘m listening to a spring boot project. Many requests are not shown. And the CPU data did not show, but other data can be displayed
#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):
ubuntu14.04
tomcat 8.0.32
collector, web 1.6.0-RC2
agent 1.6.0
jdk java-8-openjdk

#### Additional Info

[web photo](https://github.com/TimeStarRipple/note/blob/master/%E5%88%86%E5%B8%83%E5%BC%8F/images/bug1.png)
[bug](https://github.com/TimeStarRipple/note/blob/master/%E5%88%86%E5%B8%83%E5%BC%8F/images/bug2.png)

**Comment by Xylus** [comment]
I think cpu collection for open jdk is not working right now.
Could you try setting `profiler.jvm.vendor.name=Oracle` in *pinpoint.config* and see if it works?

**Comment by TimeStarRipple** [comment]
@Xylus 
Thank you very much, With your help I solve my problem

**Comment by Xylus** [comment]
@TimeStarRipple Thanks for testing this out - will fix in #2332
