### ISSUE TITLE
Maven Install bootstrap-core Errors

### ISSUE THREAD

**Issue by wpegg-dev** [naver/pinpoint#2346]
#### Description
Getting Compilation errors on bootstrap-core when running build

#### Environment

* Pinpoint version: 1.6
* OS, WAS, affected library, etc: Windows, bootstrap-core
* Additional details (e.g. how your collector/web is set up):
 * Maven 3.3.9
 * Java 6: jdk1.6.0_20 
 * Java 7: jdk1.7.0_40
 * Java 8: jdk1.8.0_45

#### Additional Info

Maven Install output:
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] C:\opt\PinPoint\pinpoint\bootstrap-core\src\main\java\com\navercorp\pinpoint\bootstrap\instrument\InstrumentorDe
legate.java:[59,44] type parameters of <T>java.lang.Class<? extends T> cannot be determined; no unique maximal instance
exists for type variable T with upper bounds T,java.lang.Object,java.lang.Object
[ERROR] C:\opt\PinPoint\pinpoint\bootstrap-core\src\main\java\com\navercorp\pinpoint\bootstrap\instrument\GuardInstrumen
tor.java:[64,44] type parameters of <T>java.lang.Class<? extends T> cannot be determined; no unique maximal instance exi
sts for type variable T with upper bounds T,java.lang.Object,java.lang.Object
[ERROR] C:\opt\PinPoint\pinpoint\bootstrap-core\src\main\java\com\navercorp\pinpoint\bootstrap\instrument\GuardInstrumen
tContext.java:[65,44] type parameters of <T>java.lang.Class<? extends T> cannot be determined; no unique maximal instanc
e exists for type variable T with upper bounds T,java.lang.Object,java.lang.Object
[INFO] 3 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] pinpoint ........................................... SUCCESS [  1.475 s]
[INFO] pinpoint-thrift .................................... SUCCESS [  8.557 s]
[INFO] pinpoint-commons ................................... SUCCESS [  5.763 s]
[INFO] pinpoint-commons-hbase ............................. SUCCESS [  6.560 s]
[INFO] pinpoint-commons-server ............................ SUCCESS [  7.190 s]
[INFO] pinpoint-bootstrap-core ............................ FAILURE [  1.887 s]
[INFO] pinpoint-bootstrap ................................. SKIPPED
[INFO] pinpoint-rpc ....................................... SKIPPED
[INFO] pinpoint-google-guava .............................. SKIPPED
[INFO] pinpoint-profiler .................................. SKIPPED
[INFO] pinpoint-profiler-optional-parent .................. SKIPPED
[INFO] pinpoint-profiler-optional-jdk6 .................... SKIPPED
[INFO] pinpoint-profiler-optional-jdk7 .................... SKIPPED
[INFO] pinpoint-profiler-optional ......................... SKIPPED
[INFO] pinpoint-httpclient3-plugin ........................ SKIPPED
[INFO] pinpoint-httpclient4-plugin ........................ SKIPPED
[INFO] pinpoint-ning-asynchttpclient-plugin ............... SKIPPED
[INFO] pinpoint-gson-plugin ............................... SKIPPED
[INFO] pinpoint-cubrid-jdbc-driver-plugin ................. SKIPPED
[INFO] pinpoint-mysql-jdbc-driver-plugin .................. SKIPPED
[INFO] pinpoint-mariadb-jdbc-driver-plugin ................ SKIPPED
[INFO] pinpoint-postgresql-jdbc-driver-plugin ............. SKIPPED
[INFO] pinpoint-jtds-plugin ............................... SKIPPED
[INFO] pinpoint-oracle-jdbc-driver-plugin ................. SKIPPED
[INFO] pinpoint-commons-dbcp-plugin ....................... SKIPPED
[INFO] pinpoint-test ...................................... SKIPPED
[INFO] pinpoint-cassandra-driver-plugin ................... SKIPPED
[INFO] pinpoint-jdk-http-plugin ........................... SKIPPED
[INFO] pinpoint-redis-plugin .............................. SKIPPED
[INFO] pinpoint-tomcat-plugin ............................. SKIPPED
[INFO] pinpoint-json-lib-plugin ........................... SKIPPED
[INFO] pinpoint-jackson-plugin ............................ SKIPPED
[INFO] pinpoint-thrift-plugin ............................. SKIPPED
[INFO] pinpoint-user-plugin ............................... SKIPPED
[INFO] pinpoint-arcus-plugin .............................. SKIPPED
[INFO] pinpoint-google-httpclient-plugin .................. SKIPPED
[INFO] pinpoint-jetty-plugin .............................. SKIPPED
[INFO] pinpoint-spring-plugin ............................. SKIPPED
[INFO] pinpoint-spring-boot-plugin ........................ SKIPPED
[INFO] pinpoint-ibatis-plugin ............................. SKIPPED
[INFO] pinpoint-mybatis-plugin ............................ SKIPPED
[INFO] pinpoint-okhttp-plugin ............................. SKIPPED
[INFO] pinpoint-log4j-plugin .............................. SKIPPED
[INFO] pinpoint-logback-plugin ............................ SKIPPED
[INFO] pinpoint-dubbo-plugin .............................. SKIPPED
[INFO] pinpoint-activemq-client-plugin .................... SKIPPED
[INFO] pinpoint-cxf-plugin ................................ SKIPPED
[INFO] pinpoint-hystrix-plugin ............................ SKIPPED
[INFO] pinpoint-jboss-plugin .............................. SKIPPED
[INFO] pinpoint-plugins ................................... SKIPPED
[INFO] pinpoint-bootstrap-core-optional ................... SKIPPED
[INFO] pinpoint-tools ..................................... SKIPPED
[INFO] pinpoint-agent-distribution ........................ SKIPPED
[INFO] pinpoint-collector ................................. SKIPPED
[INFO] pinpoint-profiler-optional-jdk8 .................... SKIPPED
[INFO] pinpoint-web ....................................... SKIPPED
[INFO] pinpoint-hbase-distribution ........................ SKIPPED
[INFO] pinpoint-thirdparty ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 32.684 s
[INFO] Finished at: 2016-12-14T10:17:50-05:00
[INFO] Final Memory: 39M/115M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project
 pinpoint-bootstrap-core: Compilation failure: Compilation failure:
[ERROR] C:\opt\PinPoint\pinpoint\bootstrap-core\src\main\java\com\navercorp\pinpoint\bootstrap\instrument\InstrumentorDe
legate.java:[59,44] type parameters of <T>java.lang.Class<? extends T> cannot be determined; no unique maximal instance
exists for type variable T with upper bounds T,java.lang.Object,java.lang.Object
[ERROR] C:\opt\PinPoint\pinpoint\bootstrap-core\src\main\java\com\navercorp\pinpoint\bootstrap\instrument\GuardInstrumen
tor.java:[64,44] type parameters of <T>java.lang.Class<? extends T> cannot be determined; no unique maximal instance exi
sts for type variable T with upper bounds T,java.lang.Object,java.lang.Object
[ERROR] C:\opt\PinPoint\pinpoint\bootstrap-core\src\main\java\com\navercorp\pinpoint\bootstrap\instrument\GuardInstrumen
tContext.java:[65,44] type parameters of <T>java.lang.Class<? extends T> cannot be determined; no unique maximal instanc
e exists for type variable T with upper bounds T,java.lang.Object,java.lang.Object
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pinpoint-bootstrap-core

**Comment by Xylus** [comment]
Hi @wpegg-dev 
Looks like a [bug](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6302954) in jdk 1.6.0_20.
Try it with a higher jdk 6 version, say something like jdk 1.6.0_45 (this one works).

**Comment by wpegg-dev** [comment]
@Xylus I updated to use the jdk you recommended and now it is failing on the first step:

[INFO] ------------------------------------------------------------------------
[INFO] Building pinpoint 1.6.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] pinpoint ........................................... FAILURE [  0.047 s]
[INFO] pinpoint-thrift .................................... SKIPPED
[INFO] pinpoint-commons ................................... SKIPPED
[INFO] pinpoint-commons-hbase ............................. SKIPPED
[INFO] pinpoint-commons-server ............................ SKIPPED
[INFO] pinpoint-bootstrap-core ............................ SKIPPED
[INFO] pinpoint-bootstrap ................................. SKIPPED
[INFO] pinpoint-rpc ....................................... SKIPPED
[INFO] pinpoint-google-guava .............................. SKIPPED
[INFO] pinpoint-profiler .................................. SKIPPED
[INFO] pinpoint-profiler-optional-parent .................. SKIPPED
[INFO] pinpoint-profiler-optional-jdk6 .................... SKIPPED
[INFO] pinpoint-profiler-optional-jdk7 .................... SKIPPED
[INFO] pinpoint-profiler-optional ......................... SKIPPED
[INFO] pinpoint-httpclient3-plugin ........................ SKIPPED
[INFO] pinpoint-httpclient4-plugin ........................ SKIPPED
[INFO] pinpoint-ning-asynchttpclient-plugin ............... SKIPPED
[INFO] pinpoint-gson-plugin ............................... SKIPPED
[INFO] pinpoint-cubrid-jdbc-driver-plugin ................. SKIPPED
[INFO] pinpoint-mysql-jdbc-driver-plugin .................. SKIPPED
[INFO] pinpoint-mariadb-jdbc-driver-plugin ................ SKIPPED
[INFO] pinpoint-postgresql-jdbc-driver-plugin ............. SKIPPED
[INFO] pinpoint-jtds-plugin ............................... SKIPPED
[INFO] pinpoint-oracle-jdbc-driver-plugin ................. SKIPPED
[INFO] pinpoint-commons-dbcp-plugin ....................... SKIPPED
[INFO] pinpoint-test ...................................... SKIPPED
[INFO] pinpoint-cassandra-driver-plugin ................... SKIPPED
[INFO] pinpoint-jdk-http-plugin ........................... SKIPPED
[INFO] pinpoint-redis-plugin .............................. SKIPPED
[INFO] pinpoint-tomcat-plugin ............................. SKIPPED
[INFO] pinpoint-json-lib-plugin ........................... SKIPPED
[INFO] pinpoint-jackson-plugin ............................ SKIPPED
[INFO] pinpoint-thrift-plugin ............................. SKIPPED
[INFO] pinpoint-user-plugin ............................... SKIPPED
[INFO] pinpoint-arcus-plugin .............................. SKIPPED
[INFO] pinpoint-google-httpclient-plugin .................. SKIPPED
[INFO] pinpoint-jetty-plugin .............................. SKIPPED
[INFO] pinpoint-spring-plugin ............................. SKIPPED
[INFO] pinpoint-spring-boot-plugin ........................ SKIPPED
[INFO] pinpoint-ibatis-plugin ............................. SKIPPED
[INFO] pinpoint-mybatis-plugin ............................ SKIPPED
[INFO] pinpoint-okhttp-plugin ............................. SKIPPED
[INFO] pinpoint-log4j-plugin .............................. SKIPPED
[INFO] pinpoint-logback-plugin ............................ SKIPPED
[INFO] pinpoint-dubbo-plugin .............................. SKIPPED
[INFO] pinpoint-activemq-client-plugin .................... SKIPPED
[INFO] pinpoint-cxf-plugin ................................ SKIPPED
[INFO] pinpoint-hystrix-plugin ............................ SKIPPED
[INFO] pinpoint-jboss-plugin .............................. SKIPPED
[INFO] pinpoint-plugins ................................... SKIPPED
[INFO] pinpoint-bootstrap-core-optional ................... SKIPPED
[INFO] pinpoint-tools ..................................... SKIPPED
[INFO] pinpoint-agent-distribution ........................ SKIPPED
[INFO] pinpoint-collector ................................. SKIPPED
[INFO] pinpoint-profiler-optional-jdk8 .................... SKIPPED
[INFO] pinpoint-web ....................................... SKIPPED
[INFO] pinpoint-hbase-distribution ........................ SKIPPED
[INFO] pinpoint-thirdparty ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.374 s
[INFO] Finished at: 2016-12-15T08:44:16-05:00
[INFO] Final Memory: 18M/61M
[INFO] ------------------------------------------------------------------------
[ERROR] Unknown lifecycle phase ".test.skip". You must specify a valid lifecycle phase or a goal in the format <plugin-p
refix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: valid
ate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, gen
erate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-cl
asses, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, d
eploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LifecyclePhaseNotFoundException

**Comment by Xylus** [comment]
Please try reinstalling your jdk 6. We've had reports where corrupt jdk installations giving out the same error.
