### ISSUE TITLE
Is there a bug in Jetty-Plugin about pinpoint.config?

### ISSUE THREAD

**Issue by Eilikce** [naver/pinpoint#2362]
#### Description

I have updated my pinpoint from 1.5.2 to 1.6 these days . I just find that the property in pinpoint.config named 'profiler.jetty.excludeurl' not works well when I use pinpoint to my Jetty App . I have wrote some URLs in my config file , but when I watch the pinpoint-web , these URLs were cought in my view.
I remember that in 1.5.2 this properties had good use to my App .
By the way , the same property in tomcat called 'profiler.tomcat.excludeurl' has been working well in my Tomcat App . So is there some error in the jetty-plugin of pinpoint 1.6 ?

#### Environment

* Pinpoint version: 1.6.0
* OS, WAS, affected library, etc: Windows7 Java7
* Additional details (e.g. how your collector/web is set up): use pinpoint with maven installed , not use the quick start .

#### Additional Info

Here is my config :
profiler.jetty.excludeUrl=/**/*.css,/**/*.js,/**/*.png,/**/*.ico,/**/*.jpg,/**/*.gif,/**/*.JPG,/**/*.swf
profiler.tomcat.excludeurl=/**/*.css,/**/*.js,/**/*.png,/**/*.ico,/**/*.jpg,/**/*.gif,/**/*.JPG,/**/*.swf

Here is some of my log :
2016-12-16 13:38:50 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.jetty.enable=true
2016-12-16 13:38:50 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.jetty.excludeurl=

2016-12-16 13:38:50 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.tomcat.excludeurl=/**/*.css,/**/*.js,/**/*.png,/**/*.ico,/**/*.jpg,/**/*.gif,/**/*.JPG,/**/*.swf

Thanks for your team , good luck

**Comment by Eilikce** [comment]
Oh , the config has been escaped when I subimt to github . There is one '/' separator in my config and logs .

**Comment by minwoo-jung** [comment]
Ok. I will check your issue.

**Comment by minwoo-jung** [comment]
There is bug. Jetty config key is spelled wrong.
profiler.jetty.excludeUrl -> profiler.jetty.excludeurl

I will fix spell soon.
