### ISSUE TITLE
Is there a way to use to mysql instead of default hbase for maintaining data?

### ISSUE THREAD

**Issue by irocks04** [naver/pinpoint#2363]
#### Description

  I have working set up with hbase as default but would like to know if there's a way to bypass hbase and have mysql instead.
#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by Xylus** [comment]
Hi @irocks04 
We currently don't offer anything other than hbase as the persistence layer. Maintaining multiple backends isn't feasible currently as our storage format is still evolving and having to maintain compatibility across all these will be too much work.
