### ISSUE TITLE
If I want to front-end and back-end exchange, access to the front-end users, I should be in the HTTP header to add what kind of information?

### ISSUE THREAD

**Issue by hwt2016** [naver/pinpoint#2370]
Whether to change the transcationld, to obtain the user's source information or quantity information？Thanks a lot

**Comment by Xylus** [comment]
Hi @hwt2016 
I don't quite understand your question and what you're trying to do.
But [this](https://github.com/naver/pinpoint/blob/master/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/Header.java) should give you an idea on the headers we use to trace over http calls.

**Comment by hwt2016** [comment]
I would like to know the PP agent marking the process, I should start from where
