### ISSUE TITLE
I would like to know the PP agent marking the process, I should start from where

### ISSUE THREAD

**Issue by hwt2016** [naver/pinpoint#2371]
I would like to know how pp agent is sending tracking data to the collector, I did not find in the PP agent module JAVA code.Could you provide some ideas?Thank you very much

**Comment by marcoblos** [comment]
I think that pinpoint-agent is just a packager to other projects.
If you want to see the code, looking for `pinpoint-bootstrap`, `pinpoint-commons`, `pinpoint-bootstrap-core`, `pinpoint-bootstrap-core-optional` and `pinpoint-plugins`.

Repeating I do not know this is a correct answer.

**Comment by Xylus** [comment]
Hi @hwt2016 
What @marcoblos said is exactly right.
If you'd like to dig in deeper, please take a look at *pinpoint-profiler*, as well as the packages @marcoblos mentioned.
[DefaultAgent](https://github.com/naver/pinpoint/blob/master/profiler/src/main/java/com/navercorp/pinpoint/profiler/DefaultAgent.java) should give you a nice place to start.
