### ISSUE TITLE
Developed a WEBLOGIC plugin based on TOMCAT but profiling is not working?

### ISSUE THREAD

**Issue by godwingrs22** [naver/pinpoint#2375]
#### Description
I'm in the process of writing a plugin for WEBLOGIC profiling.
I can able to detect the WEBLOGIC in the pinpoint agent, but the calls from the application are not being traced.
Can you please help me to rectify this problem?
I think the transformation and interceptor code i've added is not working..

`transformTemplate.transform("javax.servlet.http.HttpServlet", new TransformCallback() {
   @Override
     public byte[] doInTransform(Instrumentor instrumentor, ClassLoader classLoader, String className,
            Class<?> classBeingRedefined, ProtectionDomain protectionDomain, byte[] classfileBuffer)
                 throws InstrumentException {
            InstrumentClass target = instrumentor.getInstrumentClass(classLoader, className, classfileBuffer);

            InstrumentMethod handleMethodEditorBuilder = target.getDeclaredMethod("doGet",
                    "javax.servlet.http.HttpServletRequest", "javax.servlet.http.HttpServletResponse");
            if (handleMethodEditorBuilder != null) {
                handleMethodEditorBuilder
                    .addInterceptor("it.sella.pinpoint.plugin.weblogic.interceptor.ServerHandleInterceptor");
                return target.toBytecode();
            }
             return target.toBytecode();
        }
});`

#### Environment
* Pinpoint version:1.5.2
* OS, WAS, affected library, etc: OS:Windows 7, Weblogic: 10.3.6
* Additional details (e.g. how your collector/web is set up): I'm using quick-start to start my collector and web every time while i put the developed plugin in the necessary folder and rebuilt.

#### Additional Info
My plugin detects the weblogic server based on the ApplicationTypeDetector
`private static final String DEFAULT_BOOTSTRAP_MAIN = "weblogic.Server";`

**Comment by Xylus** [comment]
Hi @godwingrs22 
It looks like you're transforming a generic `HttpServlet` provided by the jdk. This will apply your weblogic-specific interceptor to `HttpServlet` even if a user isn't using WebLogic.
I'd first suggest finding and transforming another class, one that is provided by WebLogic.

If class transformation fails with the other class you've chosen to transform, please attach the agent log so we can take a closer look.
Thanks

**Comment by godwingrs22** [comment]
I was trying to transform the **weblogic.servlet.http.RequestResponseKey.class**
`transformTemplate.transform("weblogic.servlet.http.AbstractAsyncServlet", new TransformCallback() {
			@Override
			public byte[] doInTransform(Instrumentor instrumentor, ClassLoader classLoader, String className,
					Class<?> classBeingRedefined, ProtectionDomain protectionDomain, byte[] classfileBuffer)
							throws InstrumentException {
				InstrumentClass target = instrumentor.getInstrumentClass(classLoader, className, classfileBuffer);

				InstrumentMethod handleMethodEditorBuilder = target.getDeclaredMethod("doRequest","weblogic.servlet.http.RequestResponseKey");
				if (handleMethodEditorBuilder != null) {
					handleMethodEditorBuilder
							.addInterceptor("it.sella.pinpoint.plugin.weblogic.interceptor.ServerHandleInterceptor");
					return target.toBytecode();
				}

				return target.toBytecode();
			}
		});`

I've attached the pinpoint agent log for your reference.When i checked the log, it seems it can able to detect the server and can able to establish connection with the collector.
