### ISSUE TITLE
Number on ServerMap and Scatter Chart

### ISSUE THREAD

**Issue by Eilikce** [naver/pinpoint#2381]
When I watch the pinpoint-web view , I find that the number on ServerMap from USER to TOMCAT is 57 ,
the number on the Scatter Chart is Success 45 Failed 0 .
Why the number on ServerMap  is not equal to Success plus Failed on Scatter Chart ?

Thanks for your team

**Comment by Xylus** [comment]
Hi @Eilikce 
The number shown on the server map (and the response time summry chart) is slotted into minute-wide timeslot. So when you for example, query for the last 5 minutes of data at some time 11:05:50, the number shown on the server map will be the sum of requests received between 11:00:00 and 11:05:50.
The scatter chart on the other hand queries for data between 11:00:50 and 11:05:50.

So in the case above, the server map will have a higher number shown as it would include 50 seconds worth of requests from 11:00:00 to 11:00:50, whereas the scatter chart would not.

**Comment by Eilikce** [comment]
Oh ,  I see ~
Thanks a lot ~
