### ISSUE TITLE
How to use pinpoint with VSpare Center ?

### ISSUE THREAD

**Issue by phuongphally** [naver/pinpoint#2388]
I am news to java monitoring systems. 
But I can understand how to develop systems to monitor Vspare Center by using VSpare SDK. 

How can I use Pinpoint to monitoring VSpare Center ?

**Comment by Xylus** [comment]
Hi @phuongphally 
I have no idea what VSpare Center is so I can't tell you with full confidence, but we don't currently have support for VSpare Center.

**Comment by phuongphally** [comment]
I hope coming soon.
