### ISSUE TITLE
Does pinpoint support transaction/s view for non-http applications?

### ISSUE THREAD

**Issue by Sambhaji75** [naver/pinpoint#2443]
Pinpoint looks to be a great tool for monitoring and would like to use it for a Java application with no http/web interface. Does it show transaction count/s view for tcp requests?

**Comment by koo-taejin** [comment]
@Sambhaji75

Hi Sambhaji75 

We currently support non-http protocols such as thrift or dubbo.
But we do not support tcp tracing yet, and we do not yet considering about tcp tracing. 

thanks.
