### ISSUE TITLE
Why the active thread chart usually shows 0 ?

### ISSUE THREAD

**Issue by Eilikce** [naver/pinpoint#2449]
I use pinpoint for my tomcat app , why the data in the active thread chart usually shows 0 ?
The thread always should be 1 at least I think .
Is there any thing I got wrong ?

![qq 20170106180904](https://cloud.githubusercontent.com/assets/17841648/21714697/4fa9472c-d43b-11e6-8965-fed4af55c2ab.png)

**Comment by koo-taejin** [comment]
Hi Eilikce

Please show data such as a thread dump periodically extracted once every 10 seconds or active thread chart data from another APM.
I hope this is a question based on data that is not based on your thinking.
Unfortunately, there is no way I can know your thinking.

thanks.

**Comment by Eilikce** [comment]
Hi koo-taejin

I'm just not clear what the Active Thread defination is .
Are all of the running threads in my app can be called Active Thread ? Or only some of the threads can be called Active Thread .
Is there any condition for Active Thread ? What's the difference between common thread and Active Thread ?

**Comment by koo-taejin** [comment]
Active Thread is request processing thread.
So If tomcat handle three request, then Active Thread Chart shows 3. 

It seems that there is not enough indication about active thread.
I will include the explanation in the tooltip.

thanks.

**Comment by Eilikce** [comment]
As you said , if I request my tomcat app , the chart should shows at least 1 . 
But I always find 0 in my chart in fact .
There are many requests shown on the Scatter Chart in the same time .

![errorthread](https://cloud.githubusercontent.com/assets/17841648/21795704/e6113912-d73e-11e6-9e6a-62d731732e10.png)

**Comment by koo-taejin** [comment]
It shows all the sampled requests in the scatter chart,
The value of the Active Thread Chart shows a snapshot of a specific time.
The value should be different.

**Comment by emeroad** [comment]
Active Thread data is not **cumulative value.**
It is **current snapshot data.**

**Comment by emeroad** [comment]
Before asking questions, read the tooltip.
![image](https://cloud.githubusercontent.com/assets/7564547/21796156/1c921712-d74a-11e6-8c47-74ebfe4d6d81.png)

**Comment by koo-taejin** [comment]
@lawrencewu 
Active Thread Chart is timebased grapth.
So it show average value.
