### ISSUE TITLE
How do I get information on the operation of the user

### ISSUE THREAD

**Issue by kyzhouxu** [naver/pinpoint#2456]
#### Help!!!

How do I get information on the operation of the user through agent？
Can someone provide ideas or methods?
Thank you in advance.
#### Environment

* Pinpoint version:1.6.1

**Comment by Xylus** [comment]
I don't quite understand what it is you're trying to get. Could you explain in more detail please?

**Comment by kyzhouxu** [comment]
@Xylus First of all,thank you for your reply.
What I mean is how to get the user name or user ID etc....This user is the user logged into the monitored application.

**Comment by Xylus** [comment]
Hi @kyzhouxu 
Pinpoint doesn't collect user names or user ids logged on to the monitored application.
I think it's something that's too tightly coupled with the application for it to be something Pinpoint should handle.
