### ISSUE TITLE
Guava project use java16 or java17?

### ISSUE THREAD

**Issue by Eilikce** [naver/pinpoint#2457]
#### Description
The pom in guava project show the tag below
<properties>
        <jdk.version>1.6</jdk.version>
        <jdk.home>${env.JAVA_7_HOME}</jdk.home>
        <sniffer.artifactid>java16</sniffer.artifactid>
 </properties>

My ecliplse-mars2 always use java6 complie the code and make some error . Is this should be 1.7 in jdk.version and sniffer.artifactid ?

#### Environment

* Pinpoint version: 1.6.0
* OS, WAS, affected library, etc: windows eclipse-mars2
* Additional details (e.g. how your collector/web is set up):

#### Additional Info
![guavapom](https://cloud.githubusercontent.com/assets/17841648/21793096/5cbf9600-d729-11e6-890e-73aa1672c8be.png)
![qq 20170110114012](https://cloud.githubusercontent.com/assets/17841648/21793120/9703a842-d729-11e6-97a6-27c055651419.png)

**Comment by emeroad** [comment]
It is a right option.

We don't provide technical support for Eclipse.
Find eclipse option on the web.
 - etc : java language level, jdk option
