### ISSUE TITLE
Add agent to collect data

### ISSUE THREAD

**Issue by wuzhongli** [naver/pinpoint#2459]
I would like to add agent in the agent data collected by the monitoring of the application system is currently logged user data, how should I do

**Comment by emeroad** [comment]
Please read the Pinpoint-Plugin-Developer-Guide guide
https://github.com/naver/pinpoint/wiki/Pinpoint-Plugin-Developer-Guide

**Comment by wuzhongli** [comment]
@emeroad  I'm sorry I can't describe it right. I just want to know who sent the request

**Comment by emeroad** [comment]
What information can you define someone?
 - ex : cookie field, ip ~~~

Define the information meaning someone and record it.
 - Pinpoint is already recording cookie & ip information.

see the pinpoint.config & tomcat plugin

**Comment by wuzhongli** [comment]
This is because the framework of the special from the cookie and can not get user information
