### ISSUE TITLE
Dockerizing Pinpoint

### ISSUE THREAD

**Issue by nstopkimsk** [naver/pinpoint#246]
We would like to dokerize Pinpoint, any  Docker experts out there?

**Comment by jcrygier** [comment]
Hi...I had a go at this, but I'm no expert on Pinpoint / HBase / ZooKeeper, so I fell short on some of the networking bits.  I tried to break them out into 3 images: HBase, Collector, and Web.  Feel free to take a peek at my work (ignore the directories that don't start with pinpoint):

https://github.com/Ventiv-Technology/DockerManager/tree/master/sample-config/dockerfiles

**Comment by hoonmin** [comment]
@jcrygier Hi. Thank you for sharing!
I took a peek your sample and with small fixes I could run it successfully.
- invalid templates on `hbase.properties`: missing braces...
- currently, pinpoint-web should be on `webapps/ROOT`

So, could you fix it and send us a PR to manage it in the pinpoint project?
Then we can push them to docker hub as official pinpoint images.

**Comment by Xylus** [comment]
:+1:

**Comment by jcrygier** [comment]
Alright, I've fixed the templates for environment variables, and moved collector / web to run under ROOT.  Please review PR attached.

NOTE: I still was unsuccessful at running, but this looked much better than it did before.  I'm unsure if there is an issue with my test application...I will try to use the sample you provide when I get some free time.

**Comment by nstopkimsk** [comment]
jcrygler contributed this issue.
