### ISSUE TITLE
How can I switch pinpoint_agent  on/off  at the run-time?

### ISSUE THREAD

**Issue by fengpanpan** [naver/pinpoint#2462]
As I know, the profiler.enable = true/false  configuration  in pinpoint.config  can only  be read when user start  web container(or just with -javaagent parameter),   but  if it is possible I can change the switch status at run-time ?

And as extended,  is it possible that I can change some plugin 's switch at run-time ?

How should I do , please give me some help, thanks so much!

**Comment by Xylus** [comment]
Hi @fengpanpan 
We currently cannot dynamically change configurations at runtime, but this has been and still is on our todo list.

**Comment by fengpanpan** [comment]
@Xylus  thanks for your answer
can you tell me which version/release will  obtain this feature ?

**Comment by Xylus** [comment]
We don't have a set date for it yet unfortunately

**Comment by jacobsy** [comment]
Excuse me，Is the problem resolved? @Xylus @emeroad @fengpanpan

**Comment by minwoo-jung** [comment]
@jacobsy 
Unfortunately we don't have a set date for it yet.
