### ISSUE TITLE
Chart display wrong info when the agents are in the same version in the stat page.

### ISSUE THREAD

**Issue by huayaoyue6** [naver/pinpoint#2472]
#### Environment

* Pinpoint version: 1.5.2-1.6.0
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

#### Additional Info

Chart info display wrong when the agents are in the same version in the stat page.(stat.html)
When chose a value in the select options. There  will display a duplicate pie chart instead of changing percent value in the current one's .

**Comment by Xylus** [comment]
Hi @huayaoyue6 
I don't quite understand what's happening here. Our /stat.html seems to be working fine. Could you take a screenshot of what you're experiencing? (and possibly the browser you're using?)
Thanks.

**Comment by huayaoyue6** [comment]
# Chrome
![Chrome](https://cloud.githubusercontent.com/assets/6671110/21972640/de3738fc-dbf5-11e6-9aa3-db2a66e800ee.png)

# FireFox
![FireFox](https://cloud.githubusercontent.com/assets/6671110/21972641/de40d15a-dbf5-11e6-868a-b4e57a07df2d.png)

**Comment by emeroad** [comment]
There is no problem with 1.6.1.
Recommend version Up to 1.6.1.
