### ISSUE TITLE
Collector launched fine - test app and web do not.

### ISSUE THREAD

**Issue by tatonki1** [naver/pinpoint#2488]
#### Description
Keep getting timeouts on the test app and web start scripts; after the collector started fine.   It used to work, not sure what went wrong...any help would be appreciated.  Thanks. 

#### Environment
Mac 10.11.6
Apache Maven 3.3.9
Pinpoint - Latest Release (2016/11/21)

**Comment by koo-taejin** [comment]
Hi tatonki1

Each module log saved in  {$PINPOINT_HOME}/quickstart/logs.
Please post module log which not working.   

thanks.
