### ISSUE TITLE
quickstart-web initialization failed

### ISSUE THREAD

**Issue by zqzgit** [naver/pinpoint#2490]
starting pinpoint-quickstart-web. 175 /180 sec(close wait limit).
starting pinpoint-quickstart-web. 180 /180 sec(close wait limit).
---pinpoint-quickstart-web initialization failed. pid=19615.---

Can i hele you?Would you tell me what could cause this problem?

**Comment by koo-taejin** [comment]
Hi zqzgit

Each module log saved in  {$PINPOINT_HOME}/quickstart/logs.
Please post module log which not working.   

thanks.
