### ISSUE TITLE
Install on ARM processors

### ISSUE THREAD

**Issue by mappsys** [naver/pinpoint#2492]
Hi, i'm trying to deploy on an ARM (as Raspberry PI), but it seems there is no JDK6 version for ARM processors (only JRE6 and JDK7 and JDK8) on oracle's website [http://www.oracle.com/technetwork/java/embedded/downloads/javase/default-1934076.html](url)

Is there another way to use it? Can i use JRE6 instead? I'm new to Java, just trying to make it work. Tks

**Comment by emeroad** [comment]
Download or build elsewhere (use the x86 machine)
 - download link : https://github.com/naver/pinpoint/releases
