### ISSUE TITLE
Error occurred during initialization of VM

### ISSUE THREAD

**Issue by netidol** [naver/pinpoint#2494]
When I start my springboot app whit the agent（version 1.6.1），it have the error 

Failed to find Premain-Class manifest attribute in /usr/soft/code/pinpoint160/agent/target/pinpoint-agent-1.6.1-SNAPSHOT.jar
Error occurred during initialization of VM
agent library failed to init: instrument

and it can worked well whit version 1.6.0

**Comment by Xylus** [comment]
Hi @netidol 
The pinpoint agent's `-javaagent` option should be `-javaagent:/usr/soft/code/pinpoint160/agent/target/pinpoint-agent-1.6.1-SNAPSHOT/pinpoint-bootstrap-1.6.1-SNAPSHOT.jar`.
It looks like you've started with `-javaagent:/usr/soft/code/pinpoint160/agent/target/pinpoint-agent-1.6.1-SNAPSHOT.jar` from the error message.

**Comment by netidol** [comment]
oh! Thank you，I made a mistake
