### ISSUE TITLE
Agent log not coming up.

### ISSUE THREAD

**Issue by irocks04** [naver/pinpoint#2499]
#### Description

Agent deployed 1.6.0. After deploying the log file doesn't populate.
Rest everything is fine.. All the agent information is displayed in UI. 
Log4j.xml has the default values nothing changed there. 
How to get the log file?
#### Environment

* Pinpoint version: 1.6.0 Agent
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by minwoo-jung** [comment]
You can see logfile where package location of pinpoint agent.
ex) if pinpoint package location is /home/service/pinpoint/pinpoint-agent-1.6.0 file location is /home/service/pinpoint/pinpoint-agent-1.6.0/log
If you change configuration for log4j you see /home/service/pinpoint/pinpoint-agent-1.6.0/lib/log4j.xml

**Comment by irocks04** [comment]
Thanks for the reply. But it still doesn't show up . I tried searching in the package location of the agent. But the log doesn't come up at all.

**Comment by minwoo-jung** [comment]
Can you explain your environment in some detail?
 - ex) kind of WAS,
Cound you see your agent information in pinoint web UI?
Please ckeck log level in log4j.xml file.

**Comment by irocks04** [comment]
Hi,

This is RHEL environment.
I am able to see the agent in the WEB UI with all the transanctions.
i checked the log4j.xml and tried with default settings(INFO) but still log file doesn't come up.
I tried changing the value to something constant in log4j.xml ,even then the file is not showing up.( Also checked the permissions too )
I have one question: The network test when done shows success for tcp but not for udp. How does this matter.? Should the udp also work or is it sufficient if the tcp works?

**Comment by minwoo-jung** [comment]
If you can see all transaction in pinpoint web, You don't care about network status.

Please answer my question.

1 I wonder what you use platform, framework. please explain these.
ex) tomcat, spring boot, WAS, spring MVC ETC

2 Do you use default log4.xml file of pinoint agent?
If you edit log4j.xml file. show me your file.

3 can you see your application log operated with  pinoint agent?

**Comment by irocks04** [comment]
This worked after starting pinpoint with log4j path. Not sure y it doesn't
pick from the lib folder
