### ISSUE TITLE
HBase conf

### ISSUE THREAD

**Issue by YouriAndropov** [naver/pinpoint#2504]
Hi all,

I've been very interested in pinpoint, and did some test with it : my work is to do load tests.

Pinpoint works well, but it seems that HBase base conf is somewhat insufficient, it crashes from time to time, I have to restart it.

So, I had to increase HBase heap to 2 GB, add the "CMSClassUnloading" option to prevent full gc to happen, and set the "MaxMetaSpace" to 384 MB, but I'm still not sure that's enough. The JVM thoughput has increased from 90 to 99,8 %, but I'm still watching the JVM closely because it seems to retain lots of data in its old gen.

Did anyone else have to alter HBase JVM conf, and how ? I'm not sure a 2 GB heap will be enough.

**Comment by Xylus** [comment]
Hi @YouriAndropov 
If you're running hbase standalone (ie the one we use in our quickstart), it won't scale very well. I suggest looking into running hbase in distributed mode if you're trying to run Pinpoint in any scale.
How to set up hbase in distributed mode is beyond our scope so I can't help you much in this. That said, there are a lot of great articles out there on this very topic, and you can also install/manage hbase clusters using hbase management systems from Cloudera, Hortonworks, etc (this will save you a lot of time and trouble).
