### ISSUE TITLE
Could you tell me  when you would release the new version（1.6.1）？

### ISSUE THREAD

**Issue by andyspan** [naver/pinpoint#2519]
As our applications are deployed on WAS，we really need this plugin.

Could you tell me  when you would release the new version?

Thanks very much!

**Comment by Xylus** [comment]
Hi @andyspan 
I'm not too sure when 1.6.1 will be released, we don't have a date set for it yet.
Which plugin are you waiting for if you don't mind my asking?

**Comment by wuyi5630** [comment]
hi @Xylus , I'm waiting for webshphere plugin too

**Comment by andyspan** [comment]
hi, @Xylus  ,I'm very glad that you could answer my question,the  webshphere plugin is exactly what I want.

**Comment by Xylus** [comment]
Hi all,
The review for Websphere plugin #2153 is currently underway. Once it's merged, you'll be able to try it out before 1.6.1 release by building 1.6.1-SNAPSHOT from source :)

**Comment by andyspan** [comment]
@Xylus Thanks very much!
