### ISSUE TITLE
How to configure application in Pinpoint

### ISSUE THREAD

**Issue by PRIYANKAPANDEYTWO** [naver/pinpoint#2528]
#### Description
Hi Team,

As we know that while we start our Pinpoint one can feed trace data to Pinpoint using the TestApp UI, and check them using Pinpoint Web UI. My doubt is how one can replace the TestApp  with their own application to check the functionality more accurately.

#### Environment

* Pinpoint version:1.6.1
* Windows: 7

#### Additional Info
Attaching Screenshot what actual we want to be done once PinPoint Agent while this time we are having (ScreenShot having TESTAPP only)
![screenshot with testapp application](https://cloud.githubusercontent.com/assets/25005033/22248734/0b9c8948-e266-11e6-818b-5535b49a4377.png)
(ScreenShot where one can select different application)
 :-
![screenshot with different application](https://cloud.githubusercontent.com/assets/25005033/22248685/d6c224c6-e265-11e6-9866-ae221029c673.png)
)

Regards,
Priyanka Pandey

**Comment by Xylus** [comment]
Hi @PRIYANKAPANDEYTWO 
Please check our [installation guide](https://github.com/naver/pinpoint/blob/master/doc/installation.md), especially the part on Pinpoint agent.
Thanks.

**Comment by PRIYANKAPANDEYTWO** [comment]
Hi ,

Thanks i tried to do same Add -javaagent, -Dpinpoint.agentId, -Dpinpoint.applicationName to CATALINA_OPTS in the Tomcat startup script and then Start up Tomcat to start profiling my web application.But my localhost in Tomcat stop and start throwing error - "Address already in use:JVM_Bind" and when i run localhost:8085 i found that it's getting redirected to below attached Page.Please help me to resolve this issue:-
![tomcat not getting start while localhost redirecting to some other application](https://cloud.githubusercontent.com/assets/25005033/22288599/a96236d4-e31d-11e6-8031-5ee49c8e099d.png)
