### ISSUE TITLE
Any Plugin available for Apache Httpd Server (Web Server)

### ISSUE THREAD

**Issue by dinesh4747** [naver/pinpoint#2529]
HI All

I was looking on pinpoint plugin for Apache Http server which completely runs on native platform and not under any JVM

Is there any plugin available and can we integrate by configuring it in httpd.conf

Version - Apache/2.4.6

**Comment by Xylus** [comment]
Hi @dinesh4747 
I don't think we have a plugin for Apache Http server yet.

**Comment by prashantnitt07** [comment]
Any plan for add httpd web server plugin .
I am using : pinpinpoint version : 1.6.2

**Comment by emeroad** [comment]
There is no plan

See below for alternative feature
 - https://github.com/naver/pinpoint/blob/master/doc/proxy-http-header.md
