### ISSUE TITLE
Add support for Weblogic Plugin

### ISSUE THREAD

**Issue by andyspan** [naver/pinpoint#2557]
Weblogic Plugin Contribution
Link: [/plugins/weblogic](https://github.com/andyspan/pinpoint/tree/master/plugins/weblogic)
Target: pinpoint-weblogic-plugin-1.6.2-SNAPSHOT.jar
Supported Version: weblogic 10.* and weblogic 12.*

ServiceTypes: WEBLOGIC =1989,WEBLOGIC _METHOD=1992
Annotations:
Configurations:
profiler.weblogic.enable=
profiler.weblogic.bootstrap.main=
profiler.weblogic.excludeurl=

The plugin is verified on 12c and 10.3.6

Example：
![topo](https://cloud.githubusercontent.com/assets/24934896/22619831/0508cdbe-eb38-11e6-8ada-0321315532c7.png)

![calltree](https://cloud.githubusercontent.com/assets/24934896/22619832/0ae884f4-eb38-11e6-8eb3-b40cc94177c1.png)

**Comment by andyspan** [comment]
You could download the jar here.[Download](https://github.com/andyspan/pinpoint-weblogic-plugin/tree/master)

**Comment by liuhaiqingkevin** [comment]
hi,I'm trying to build and install your project with weblogic plugin.When I run "mvn clean install -Dmavn.test.skip=true",got error like this. Could you please do me a favor?

[INFO] pinpoint-jboss-plugin .............................. SUCCESS [ 31.417 s]
[INFO] pinpoint-vertx-plugin .............................. SUCCESS [  6.298 s]
[INFO] pinpoint-resin-plugin .............................. SUCCESS [  2.506 s]
[INFO] pinpoint-weblogic-plugin ........................... FAILURE [  1.083 s]
[INFO] pinpoint-plugins ................................... SKIPPED
[INFO] pinpoint-bootstrap-core-optional ................... SKIPPED
[INFO] pinpoint-tools ..................................... SKIPPED
[INFO] pinpoint-agent-distribution ........................ SKIPPED
[INFO] pinpoint-collector ................................. SKIPPED
[INFO] pinpoint-profiler-optional-jdk8 .................... SKIPPED
[INFO] pinpoint-web ....................................... SKIPPED
[INFO] pinpoint-hbase-distribution ........................ SKIPPED
[INFO] pinpoint-thirdparty ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:15 min
[INFO] Finished at: 2017-02-27T11:04:11+08:00
[INFO] Final Memory: 60M/836M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project pinpoint-weblogic-plugin: Compilation failure: Compilation failure:
[ERROR] /Users/lhq/pinpoint_test/pinpoint/plugins/weblogic/src/main/java/com/navercorp/pinpoint/plugin/weblogic/interceptor/ServletStubImplInterceptor.java:[25,32] ����� weblogic.servlet.internal ������
[ERROR] /Users/lhq/pinpoint_test/pinpoint/plugins/weblogic/src/main/java/com/navercorp/pinpoint/plugin/weblogic/interceptor/AbstractServerHandleInterceptor.java:[45,32] ����� weblogic.servlet.internal ������
[ERROR] /Users/lhq/pinpoint_test/pinpoint/plugins/weblogic/src/main/java/com/navercorp/pinpoint/plugin/weblogic/interceptor/ServletStubImplInterceptor.java:[40,14] �Ҳ�������
[ERROR] ���ţ� �� ServletRequestImpl
[ERROR] λ�ã� �� com.navercorp.pinpoint.plugin.weblogic.interceptor.ServletStubImplInterceptor
[ERROR] /Users/lhq/pinpoint_test/pinpoint/plugins/weblogic/src/main/java/com/navercorp/pinpoint/plugin/weblogic/interceptor/AbstractServerHandleInterceptor.java:[73,23] �Ҳ�������
[ERROR] ���ţ� �� ServletRequestImpl
[ERROR] λ�ã� �� com.navercorp.pinpoint.plugin.weblogic.interceptor.AbstractServerHandleInterceptor
[ERROR] /Users/lhq/pinpoint_test/pinpoint/plugins/weblogic/src/main/java/com/navercorp/pinpoint/plugin/weblogic/interceptor/AbstractServerHandleInterceptor.java:[191,35] �Ҳ�������
[ERROR] ���ţ� �� ServletRequestImpl
[ERROR] λ�ã� �� com.navercorp.pinpoint.plugin.weblogic.interceptor.AbstractServerHandleInterceptor
[ERROR] /Users/lhq/pinpoint_test/pinpoint/plugins/weblogic/src/main/java/com/navercorp/pinpoint/plugin/weblogic/interceptor/AbstractServerHandleInterceptor.java:[200,39] �Ҳ�������
[ERROR] ���ţ� �� ServletRequestImpl
[ERROR] λ�ã� �� com.navercorp.pinpoint.plugin.weblogic.interceptor.AbstractServerHandleInterceptor
[ERROR] /Users/lhq/pinpoint_test/pinpoint/plugins/weblogic/src/main/java/com/navercorp/pinpoint/plugin/weblogic/interceptor/AbstractServerHandleInterceptor.java:[244,57] �Ҳ�������
[ERROR] ���ţ� �� ServletRequestImpl
[ERROR] λ�ã� �� com.navercorp.pinpoint.plugin.weblogic.interceptor.AbstractServerHandleInterceptor
[ERROR] /Users/lhq/pinpoint_test/pinpoint/plugins/weblogic/src/main/java/com/navercorp/pinpoint/plugin/weblogic/interceptor/AbstractServerHandleInterceptor.java:[259,67] �Ҳ�������
[ERROR] ���ţ� �� ServletRequestImpl
[ERROR] λ�ã� �� com.navercorp.pinpoint.plugin.weblogic.interceptor.AbstractServerHandleInterceptor
[ERROR] /Users/lhq/pinpoint_test/pinpoint/plugins/weblogic/src/main/java/com/navercorp/pinpoint/plugin/weblogic/interceptor/AbstractServerHandleInterceptor.java:[280,47] �Ҳ�������
[ERROR] ���ţ� �� ServletRequestImpl
[ERROR] λ�ã� �� com.navercorp.pinpoint.plugin.weblogic.interceptor.AbstractServerHandleInterceptor
[ERROR] /Users/lhq/pinpoint_test/pinpoint/plugins/weblogic/src/main/java/com/navercorp/pinpoint/plugin/weblogic/interceptor/AbstractServerHandleInterceptor.java:[102,14] �Ҳ�������
[ERROR] ���ţ� �� ServletRequestImpl
[ERROR] λ�ã� �� com.navercorp.pinpoint.plugin.weblogic.interceptor.AbstractServerHandleInterceptor
[ERROR] /Users/lhq/pinpoint_test/pinpoint/plugins/weblogic/src/main/java/com/navercorp/pinpoint/plugin/weblogic/interceptor/AbstractServerHandleInterceptor.java:[173,18] �Ҳ�������
[ERROR] ���ţ� �� ServletRequestImpl
[ERROR] λ�ã� �� com.navercorp.pinpoint.plugin.weblogic.interceptor.AbstractServerHandleInterceptor
[ERROR] /Users/lhq/pinpoint_test/pinpoint/plugins/weblogic/src/main/java/com/navercorp/pinpoint/plugin/weblogic/interceptor/AbstractServerHandleInterceptor.java:[219,41] ���棺[deprecation] com.navercorp.pinpoint.bootstrap.util.StringUtils �е� drop(java.lang.String,int) �ѹ�ʱ
[ERROR] /Users/lhq/pinpoint_test/pinpoint/plugins/weblogic/src/main/java/com/navercorp/pinpoint/plugin/weblogic/interceptor/AbstractServerHandleInterceptor.java:[223,45] ���棺[deprecation] com.navercorp.pinpoint.bootstrap.util.StringUtils �е� drop(java.lang.String,int) �ѹ�ʱ
[ERROR] /Users/lhq/pinpoint_test/pinpoint/plugins/weblogic/src/main/java/com/navercorp/pinpoint/plugin/weblogic/interceptor/ServletStubImplInterceptor.java:[42,65] ����� weblogic.servlet.internal ������
[ERROR] /Users/lhq/pinpoint_test/pinpoint/plugins/weblogic/src/main/java/com/navercorp/pinpoint/plugin/weblogic/interceptor/ServletStubImplInterceptor.java:[45,16] �Ҳ�������
[ERROR] ���ţ� �� ServletRequestImpl
[ERROR] λ�ã� �� com.navercorp.pinpoint.plugin.weblogic.interceptor.ServletStubImplInterceptor
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pinpoint-weblogic-plugin
