### ISSUE TITLE
How to debug java agent of pinpoint

### ISSUE THREAD

**Issue by hehuang139** [naver/pinpoint#2558]
How can I debug pinpoint?
I use -javaagent option to install pinpoint, it's ok! but i want to know somethings about how pinpoint sends data to Hbase,and there were some problems i couldn't handle with. i want to debug the code,but java agent is different with normal java code.how can i debug code in eclipse IDE

**Comment by Xylus** [comment]
Hi @hehuang139 
You should be able to debug pinpoint agent through eclipse.
Simply import pinpoint into eclipse so you can set breakpoints and have the source code for debugging. You can then launch test applications and attach pinpoint agent by setting the vm options in debug configuration.
Remote debugging should also be possible.
