### ISSUE TITLE
2017-02-06 13:18:51 [WARN ](com.navercorp.pinpoint.bootstrap.AgentDirBaseClassPathResolver) pinpoint-commons-x.x.x(-SNAPSHOT).jar not found 2017-02-06 13:18:51 [WARN ](com.navercorp.pinpoint.bootstrap.PinpointBootStrap) Agent Directory Verify fail. skipping agent loading. *****************************************************************************

### ISSUE THREAD

**Issue by vinodhini1** [naver/pinpoint#2560]
#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by koo-taejin** [comment]
Please ask questions according to the format of the [guidelines](https://github.com/naver/pinpoint/blob/master/CONTRIBUTING.md).
