### ISSUE TITLE
PinPoint Error with : mvn install -Dmaven.test.skip=true 

### ISSUE THREAD

**Issue by knareshslk** [naver/pinpoint#2566]
I am geetinb build error in PINPOINT. 

OS: Window Server 2008 R2, 64- bit 

E:\pinpoint>mvn install -Dmaven.test.skip=true
[WARNING]
[WARNING] Some problems were encountered while building the effective settings
[WARNING] expected START_TAG or END_TAG not TEXT (position: TEXT seen ... artifa
cts.\n   |-->\n   | Default: ${user.home}/.m2/repository\n  <l... @53:5)  @ E:\S
oftwares\apache-maven-3.3.9\conf\settings.xml, line 53, column 5
[WARNING]
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] pinpoint
[INFO] pinpoint-annotations
[INFO] pinpoint-thrift
[INFO] pinpoint-commons
[INFO] pinpoint-bootstrap-core
[INFO] pinpoint-bootstrap
[INFO] pinpoint-rpc
[INFO] pinpoint-google-guava
[INFO] pinpoint-profiler
[INFO] pinpoint-commons-hbase
[INFO] pinpoint-commons-server
[INFO] pinpoint-profiler-test
[INFO] pinpoint-profiler-optional-parent
[INFO] pinpoint-profiler-optional-jdk6
[INFO] pinpoint-profiler-optional-jdk7
[INFO] pinpoint-profiler-optional
[INFO] pinpoint-httpclient3-plugin
[INFO] pinpoint-httpclient4-plugin
[INFO] pinpoint-ning-asynchttpclient-plugin
[INFO] pinpoint-gson-plugin
[INFO] pinpoint-cubrid-jdbc-driver-plugin
[INFO] pinpoint-mysql-jdbc-driver-plugin
[INFO] pinpoint-mariadb-jdbc-driver-plugin
[INFO] pinpoint-postgresql-jdbc-driver-plugin
[INFO] pinpoint-jtds-plugin
[INFO] pinpoint-oracle-jdbc-driver-plugin
[INFO] pinpoint-commons-dbcp-plugin
[INFO] pinpoint-commons-dbcp2-plugin
[INFO] pinpoint-hikaricp-plugin
[INFO] pinpoint-test
[INFO] pinpoint-cassandra-driver-plugin
[INFO] pinpoint-jdk-http-plugin
[INFO] pinpoint-redis-plugin
[INFO] pinpoint-tomcat-plugin
[INFO] pinpoint-json-lib-plugin
[INFO] pinpoint-jackson-plugin
[INFO] pinpoint-thrift-plugin
[INFO] pinpoint-user-plugin
[INFO] pinpoint-arcus-plugin
[INFO] pinpoint-google-httpclient-plugin
[INFO] pinpoint-jetty-plugin
[INFO] pinpoint-spring-plugin
[INFO] pinpoint-spring-boot-plugin
[INFO] pinpoint-ibatis-plugin
[INFO] pinpoint-mybatis-plugin
[INFO] pinpoint-okhttp-plugin
[INFO] pinpoint-log4j-plugin
[INFO] pinpoint-logback-plugin
[INFO] pinpoint-dubbo-plugin
[INFO] pinpoint-activemq-client-plugin
[INFO] pinpoint-cxf-plugin
[INFO] pinpoint-hystrix-plugin
[INFO] pinpoint-jboss-plugin
[INFO] pinpoint-vertx-plugin
[INFO] pinpoint-resin-plugin
[INFO] pinpoint-plugins
[INFO] pinpoint-bootstrap-core-optional
[INFO] pinpoint-tools
[INFO] pinpoint-agent-distribution
[INFO] pinpoint-collector
[INFO] pinpoint-profiler-optional-jdk8
[INFO] pinpoint-web
[INFO] pinpoint-hbase-distribution
[INFO] pinpoint-thirdparty
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building pinpoint 1.6.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-pinpoint-build-requireme
nts) @ pinpoint ---
[INFO]
[INFO] --- animal-sniffer-maven-plugin:1.15:check (ensure-java-1.6-class-library
) @ pinpoint ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.0
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ pinpoint ---
[INFO] Installing E:\pinpoint\pom.xml to C:\Users\vikas.kanchan\.m2\repository\c
om\navercorp\pinpoint\pinpoint\1.6.1-SNAPSHOT\pinpoint-1.6.1-SNAPSHOT.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building pinpoint-annotations 1.6.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-pinpoint-build-requireme
nts) @ pinpoint-annotations ---
[INFO]
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ pinpoint-a
nnotations ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] skip non existing resourceDirectory E:\pinpoint\annotations\src\main\reso
urces
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ pinpoint-anno
tations ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to E:\pinpoint\annotations\target\classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] pinpoint ........................................... SUCCESS [ 42.059 s]
[INFO] pinpoint-annotations ............................... FAILURE [  6.334 s]
[INFO] pinpoint-thrift .................................... SKIPPED
[INFO] pinpoint-commons ................................... SKIPPED
[INFO] pinpoint-bootstrap-core ............................ SKIPPED
[INFO] pinpoint-bootstrap ................................. SKIPPED
[INFO] pinpoint-rpc ....................................... SKIPPED
[INFO] pinpoint-google-guava .............................. SKIPPED
[INFO] pinpoint-profiler .................................. SKIPPED
[INFO] pinpoint-commons-hbase ............................. SKIPPED
[INFO] pinpoint-commons-server ............................ SKIPPED
[INFO] pinpoint-profiler-test ............................. SKIPPED
[INFO] pinpoint-profiler-optional-parent .................. SKIPPED
[INFO] pinpoint-profiler-optional-jdk6 .................... SKIPPED
[INFO] pinpoint-profiler-optional-jdk7 .................... SKIPPED
[INFO] pinpoint-profiler-optional ......................... SKIPPED
[INFO] pinpoint-httpclient3-plugin ........................ SKIPPED
[INFO] pinpoint-httpclient4-plugin ........................ SKIPPED
[INFO] pinpoint-ning-asynchttpclient-plugin ............... SKIPPED
[INFO] pinpoint-gson-plugin ............................... SKIPPED
[INFO] pinpoint-cubrid-jdbc-driver-plugin ................. SKIPPED
[INFO] pinpoint-mysql-jdbc-driver-plugin .................. SKIPPED
[INFO] pinpoint-mariadb-jdbc-driver-plugin ................ SKIPPED
[INFO] pinpoint-postgresql-jdbc-driver-plugin ............. SKIPPED
[INFO] pinpoint-jtds-plugin ............................... SKIPPED
[INFO] pinpoint-oracle-jdbc-driver-plugin ................. SKIPPED
[INFO] pinpoint-commons-dbcp-plugin ....................... SKIPPED
[INFO] pinpoint-commons-dbcp2-plugin ...................... SKIPPED
[INFO] pinpoint-hikaricp-plugin ........................... SKIPPED
[INFO] pinpoint-test ...................................... SKIPPED
[INFO] pinpoint-cassandra-driver-plugin ................... SKIPPED
[INFO] pinpoint-jdk-http-plugin ........................... SKIPPED
[INFO] pinpoint-redis-plugin .............................. SKIPPED
[INFO] pinpoint-tomcat-plugin ............................. SKIPPED
[INFO] pinpoint-json-lib-plugin ........................... SKIPPED
[INFO] pinpoint-jackson-plugin ............................ SKIPPED
[INFO] pinpoint-thrift-plugin ............................. SKIPPED
[INFO] pinpoint-user-plugin ............................... SKIPPED
[INFO] pinpoint-arcus-plugin .............................. SKIPPED
[INFO] pinpoint-google-httpclient-plugin .................. SKIPPED
[INFO] pinpoint-jetty-plugin .............................. SKIPPED
[INFO] pinpoint-spring-plugin ............................. SKIPPED
[INFO] pinpoint-spring-boot-plugin ........................ SKIPPED
[INFO] pinpoint-ibatis-plugin ............................. SKIPPED
[INFO] pinpoint-mybatis-plugin ............................ SKIPPED
[INFO] pinpoint-okhttp-plugin ............................. SKIPPED
[INFO] pinpoint-log4j-plugin .............................. SKIPPED
[INFO] pinpoint-logback-plugin ............................ SKIPPED
[INFO] pinpoint-dubbo-plugin .............................. SKIPPED
[INFO] pinpoint-activemq-client-plugin .................... SKIPPED
[INFO] pinpoint-cxf-plugin ................................ SKIPPED
[INFO] pinpoint-hystrix-plugin ............................ SKIPPED
[INFO] pinpoint-jboss-plugin .............................. SKIPPED
[INFO] pinpoint-vertx-plugin .............................. SKIPPED
[INFO] pinpoint-resin-plugin .............................. SKIPPED
[INFO] pinpoint-plugins ................................... SKIPPED
[INFO] pinpoint-bootstrap-core-optional ................... SKIPPED
[INFO] pinpoint-tools ..................................... SKIPPED
[INFO] pinpoint-agent-distribution ........................ SKIPPED
[INFO] pinpoint-collector ................................. SKIPPED
[INFO] pinpoint-profiler-optional-jdk8 .................... SKIPPED
[INFO] pinpoint-web ....................................... SKIPPED
[INFO] pinpoint-hbase-distribution ........................ SKIPPED
[INFO] pinpoint-thirdparty ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:17 min
[INFO] Finished at: 2017-02-07T10:12:07+05:30
[INFO] Final Memory: 30M/222M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
5.1:compile (default-compile) on project pinpoint-annotations: Compilation failu
re -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :pinpoint-annotations

**Comment by emeroad** [comment]
If you can not build, we recommend download.
 - download link : https://github.com/naver/pinpoint/releases

**Comment by knareshslk** [comment]
Is i need to follow same setps which is mentioned in below link?

https://github.com/naver/pinpoint/blob/master/quickstart/README.md
