### ISSUE TITLE
PinPoint Build Error : Help me... 

### ISSUE THREAD

**Issue by knareshslk** [naver/pinpoint#2571]
Pinpoint is not building, Please Help me...

E:\pinpoint-1.6.0\pinpoint-1.6.0\bootstrap-core\target\generated-sources\annotations
-O -g -deprecation -target 1.6 -source 1.6 -encoding UTF-8
[DEBUG] incrementalBuildHelper#beforeRebuildExecution
[INFO] Compiling 218 source files to E:\pinpoint-1.6.0\pinpoint-1.6.0\bootstrap-
core\target\classes
[DEBUG] incrementalBuildHelper#afterRebuildExecution
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] E:\pinpoint-1.6.0\pinpoint-1.6.0\bootstrap-core\src\main\java\com\naverc
orp\pinpoint\bootstrap\instrument\GuardInstrumentor.java:[64,44] type parameters
 of <T>java.lang.Class<? extends T> cannot be determined; no unique maximal inst
ance exists for type variable T with upper bounds T,java.lang.Object,java.lang.O
bject
[ERROR] E:\pinpoint-1.6.0\pinpoint-1.6.0\bootstrap-core\src\main\java\com\naverc
orp\pinpoint\bootstrap\instrument\GuardInstrumentContext.java:[65,44] type param
eters of <T>java.lang.Class<? extends T> cannot be determined; no unique maximal
 instance exists for type variable T with upper bounds T,java.lang.Object,java.l
ang.Object
[ERROR] E:\pinpoint-1.6.0\pinpoint-1.6.0\bootstrap-core\src\main\java\com\naverc
orp\pinpoint\bootstrap\instrument\InstrumentorDelegate.java:[59,44] type paramet
ers of <T>java.lang.Class<? extends T> cannot be determined; no unique maximal i
nstance exists for type variable T with upper bounds T,java.lang.Object,java.lan
g.Object
[INFO] 3 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] pinpoint ........................................... SUCCESS [  3.447 s]
[INFO] pinpoint-thrift .................................... SUCCESS [01:53 min]
[INFO] pinpoint-commons ................................... SUCCESS [03:14 min]
[INFO] pinpoint-commons-hbase ............................. SUCCESS [02:45 min]
[INFO] pinpoint-commons-server ............................ SUCCESS [ 36.698 s]
[INFO] pinpoint-bootstrap-core ............................ FAILURE [  3.482 s]
[INFO] pinpoint-bootstrap ................................. SKIPPED
[INFO] pinpoint-rpc ....................................... SKIPPED
[INFO] pinpoint-google-guava .............................. SKIPPED
[INFO] pinpoint-profiler .................................. SKIPPED
[INFO] pinpoint-profiler-optional-parent .................. SKIPPED
[INFO] pinpoint-profiler-optional-jdk6 .................... SKIPPED
[INFO] pinpoint-profiler-optional-jdk7 .................... SKIPPED
[INFO] pinpoint-profiler-optional ......................... SKIPPED
[INFO] pinpoint-httpclient3-plugin ........................ SKIPPED
[INFO] pinpoint-httpclient4-plugin ........................ SKIPPED
[INFO] pinpoint-ning-asynchttpclient-plugin ............... SKIPPED
[INFO] pinpoint-gson-plugin ............................... SKIPPED
[INFO] pinpoint-cubrid-jdbc-driver-plugin ................. SKIPPED
[INFO] pinpoint-mysql-jdbc-driver-plugin .................. SKIPPED
[INFO] pinpoint-mariadb-jdbc-driver-plugin ................ SKIPPED
[INFO] pinpoint-postgresql-jdbc-driver-plugin ............. SKIPPED
[INFO] pinpoint-jtds-plugin ............................... SKIPPED
[INFO] pinpoint-oracle-jdbc-driver-plugin ................. SKIPPED
[INFO] pinpoint-commons-dbcp-plugin ....................... SKIPPED
[INFO] pinpoint-test ...................................... SKIPPED
[INFO] pinpoint-cassandra-driver-plugin ................... SKIPPED
[INFO] pinpoint-jdk-http-plugin ........................... SKIPPED
[INFO] pinpoint-redis-plugin .............................. SKIPPED
[INFO] pinpoint-tomcat-plugin ............................. SKIPPED
[INFO] pinpoint-json-lib-plugin ........................... SKIPPED
[INFO] pinpoint-jackson-plugin ............................ SKIPPED
[INFO] pinpoint-thrift-plugin ............................. SKIPPED
[INFO] pinpoint-user-plugin ............................... SKIPPED
[INFO] pinpoint-arcus-plugin .............................. SKIPPED
[INFO] pinpoint-google-httpclient-plugin .................. SKIPPED
[INFO] pinpoint-jetty-plugin .............................. SKIPPED
[INFO] pinpoint-spring-plugin ............................. SKIPPED
[INFO] pinpoint-spring-boot-plugin ........................ SKIPPED
[INFO] pinpoint-ibatis-plugin ............................. SKIPPED
[INFO] pinpoint-mybatis-plugin ............................ SKIPPED
[INFO] pinpoint-okhttp-plugin ............................. SKIPPED
[INFO] pinpoint-log4j-plugin .............................. SKIPPED
[INFO] pinpoint-logback-plugin ............................ SKIPPED
[INFO] pinpoint-dubbo-plugin .............................. SKIPPED
[INFO] pinpoint-activemq-client-plugin .................... SKIPPED
[INFO] pinpoint-cxf-plugin ................................ SKIPPED
[INFO] pinpoint-hystrix-plugin ............................ SKIPPED
[INFO] pinpoint-jboss-plugin .............................. SKIPPED
[INFO] pinpoint-plugins ................................... SKIPPED
[INFO] pinpoint-bootstrap-core-optional ................... SKIPPED
[INFO] pinpoint-tools ..................................... SKIPPED
[INFO] pinpoint-agent-distribution ........................ SKIPPED
[INFO] pinpoint-collector ................................. SKIPPED
[INFO] pinpoint-profiler-optional-jdk8 .................... SKIPPED
[INFO] pinpoint-web ....................................... SKIPPED
[INFO] pinpoint-hbase-distribution ........................ SKIPPED
[INFO] pinpoint-thirdparty ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:41 min
[INFO] Finished at: 2017-02-07T17:08:22+05:30
[INFO] Final Memory: 42M/367M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
5.1:compile (default-compile) on project pinpoint-bootstrap-core: Compilation fa
ilure: Compilation failure:
[ERROR] E:\pinpoint-1.6.0\pinpoint-1.6.0\bootstrap-core\src\main\java\com\naverc
orp\pinpoint\bootstrap\instrument\GuardInstrumentor.java:[64,44] type parameters
 of <T>java.lang.Class<? extends T> cannot be determined; no unique maximal inst
ance exists for type variable T with upper bounds T,java.lang.Object,java.lang.O
bject
[ERROR] E:\pinpoint-1.6.0\pinpoint-1.6.0\bootstrap-core\src\main\java\com\naverc
orp\pinpoint\bootstrap\instrument\GuardInstrumentContext.java:[65,44] type param
eters of <T>java.lang.Class<? extends T> cannot be determined; no unique maximal
 instance exists for type variable T with upper bounds T,java.lang.Object,java.l
ang.Object
[ERROR] E:\pinpoint-1.6.0\pinpoint-1.6.0\bootstrap-core\src\main\java\com\naverc
orp\pinpoint\bootstrap\instrument\InstrumentorDelegate.java:[59,44] type paramet
ers of <T>java.lang.Class<? extends T> cannot be determined; no unique maximal i
nstance exists for type variable T with upper bounds T,java.lang.Object,java.lan
g.Object
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal o
rg.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on
 project pinpoint-bootstrap-core: Compilation failure
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThre
adedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compila
tion failure
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(Abstrac
tCompilerMojo.java:972)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.ja
va:129)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:207)
        ... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :pinpoint-bootstrap-core

E:\pinpoint-1.6.0\pinpoint-1.6.0>

**Comment by knareshslk** [comment]
Please Help me on this issue

**Comment by Xylus** [comment]
Hi @knareshslk 
Which jdk are you using to build? A quick google search turned out [this bug](http://bugs.java.com/view_bug.do?bug_id=6302954) which seems to be related to the issue.
Looks like it affects OpenJDK 6.
