### ISSUE TITLE
Change Collector module to Push data to TimeSeries DB like influx

### ISSUE THREAD

**Issue by JEnIUS85** [naver/pinpoint#2575]
Hi All,

My requirements are to push data into influx db rather than Hbase. Kindly let me know the best place to start with.

I would like to know few things in this regard 
a) Does the Pinpoint license allows me to modify the Collector module ?
b) if there is a technical documentation on Collector module then please specify, as i have failed to find one.

suggestions/feedback are welcome :)

**Comment by huayaoyue6** [comment]
I perfer only push metrics data to influxdb . After all , influxdb can use grafana to display data chart.

**Comment by JEnIUS85** [comment]
thanks emeroad for responding back.. :)
