### ISSUE TITLE
Issue in Install & Start HBase Process

### ISSUE THREAD

**Issue by knareshslk** [naver/pinpoint#2587]
Hi,

As per the guide line given in the below link, i have build Pinpoint using "mvn install -Dmaven.test.skip=true" command. It is got success all the projects. 

https://github.com/naver/pinpoint/blob/master/quickstart/README.md

After that i have downloaded Hbase for windows. and Rename the directory to hbase so that the final HBase directory looks like quickstart\hbase\hbase.

When i am trying to run below commond, its not working. Could you please help me, how to run these in commond prompt in window 2008 server. 

Download & Start - Run quickstart/bin/start-hbase.sh
Initialize Tables - Run quickstart/bin/init-hbase.sh
****

**Comment by knareshslk** [comment]
Please help on my issue. I am not able to progress on Pinpoint. Could you pls guide me how to run HBase on window2008 server

**Comment by koo-taejin** [comment]
Please refer to this [guide](https://github.com/naver/pinpoint/blob/master/quickstart/README.Win.en.md) on window environment.
However, this guide document has been tested only on windows 7 and 10, so it may not work on Windows server.

Quickstart does not guarantee support on Windows servers.
Sadly if it does not work, there is no way we can help.
