### ISSUE TITLE
Graphs always showing 'No Data'

### ISSUE THREAD

**Issue by ziccardi** [naver/pinpoint#2591]
#### Description
I am trying to monitor an application running on JBOSS EAS 6.3.

Here is a screenshot of what I get: https://ibin.co/3BnJHYPttjjx.png
As you can see, the graphs on the right always says 'No Data'.

On the other side, the server inspector works as you can see in this screenshot: https://ibin.co/3BnK4su9eVwM.png

There are no errors in the logs (no errors in the web/collector logs and no errors in the agent logs)

#### Environment

* Pinpoint version: 1.6.0
* OS: Ubuntu 12.04.5 LTS
* AS: Jboss EAS 6.3

The collector and web application are running in a tomcat container on a remote machine
MySQL is up and running with all the tables and the connection from the web app to the database works.
#### Additional Info

What else can I check to understand what's going wrong?

**Comment by ziccardi** [comment]
An update:
if I go click on realtime in the log this warning appear:

`[WARN ](c.n.p.w.c.ClusterManager           ) UPS/UPS-ETEAM/1486659029937 couldn't find agent.`

**Comment by ziccardi** [comment]
After setting `cluster.enable` to `true` in the pinpoint collector, the previous warning has disappeared.
However, the graphs are still empty.

`cluster.enable=true`

cluster.enable was already true by default in `pinpoint-web.properties` (web application)

**Comment by ziccardi** [comment]
Solved.
For some reason, with 

`profiler.jboss.traceEjb=true` 

the collector was sending only memory statistics to the server.

The problem has been solved by changing it to

`profiler.jboss.traceEjb=false`

**Comment by nike5** [comment]
I have the same problem on Apache ServiceMix 4.3.1. Pinpoint always shwoing 'No Data' .
OS: Windows 7, 
AS: Apache ServiceMix 4.3.1
