### ISSUE TITLE
Issue in PinPoint run commands 

### ISSUE THREAD

**Issue by knareshslk** [naver/pinpoint#2595]
I am getting below error while running "start-collector.cmd", "start-testapp.cmd", "start-web.cmd" Commands. Please help me. 

E:\pinpoint-1.6.0\pinpoint-1.6.0\quickstart\bin>start-collector.cmd
Invalid XSL format (or) file name.
"---pinpoint-quickstart-collector initialization start failed---"
"---pinpoint-quickstart-collector initialization failed. pid=.---"

E:\pinpoint-1.6.0\pinpoint-1.6.0\quickstart\bin>start-testapp.cmd
Invalid XSL format (or) file name.
"---pinpoint-quickstart-testapp initialization start failed---"
"---pinpoint-quickstart-testapp initialization failed. pid=.---"

E:\pinpoint-1.6.0\pinpoint-1.6.0\quickstart\bin>start-web.cmd
Invalid XSL format (or) file name.
"---pinpoint-quickstart-web initialization start failed---"
"---pinpoint-quickstart-web initialization failed. pid=.---"

**Comment by knareshslk** [comment]
Why this issue closed?

**Comment by emeroad** [comment]
We are not a technical support team.
Solve the problem yourself.


We recommend the following document.
- How To Ask Questions The Smart Way : 
http://catb.org/~esr/faqs/smart-questions.html
