### ISSUE TITLE
monitoring non servlet based applications

### ISSUE THREAD

**Issue by JEnIUS85** [naver/pinpoint#2597]
hi team,

I would like to know if pinpoint can support monitoring of "non-servlet" based applications. i have few applications in my project that are of this nature.

Some of them are built using "Spring-boot" framework and seems pinpoint supports that ( i feel it because i see springboot in plugin directory).
However, other non-servlet application of my project doesn't use "Spring-boot". Is it possible to provide "Custom Classes" as the starting point for Pinpoint agent to start monitoring

thanks in advance

**Comment by koo-taejin** [comment]
Hi JenlUS85 

If you want to trace unsupported modules you need to tell the agent which methods to trace by setting profiler.include or profiler.entrypoint in pinpoint.config (more details here).

thanks.

**Comment by JEnIUS85** [comment]
thanks Koo-taejin.  Hyperlink is missing in your response

**Comment by koo-taejin** [comment]
@JEnIUS85 i fixed it. thanks :)

**Comment by JEnIUS85** [comment]
thanks ... 
one quick doubt: i see only public method of a class can be specified to start the trace.. However, once the trace is started, will we be able to see other type of methods in trace (i.e. private, protected, etc..)

**Comment by koo-taejin** [comment]
This option can be applied regardless of the access modifier of the target.

**Comment by JEnIUS85** [comment]
:+1:
