### ISSUE TITLE
Pinpoint not showing data, all time is 'No Data'

### ISSUE THREAD

**Issue by nike5** [naver/pinpoint#2598]
Hi Pinpoint team,

I'm writing to you to reference issue #2591 , I have the same case.
In my problem Pinpoint all time showing 'No Data' in ServiceMix system. 
Is Pinpoint not working with ServiceMix? The agent showing data with machine (memory, cpu), but with application not.

Environment

* Pinpoint version: 1.5.3
* OS: Windows 7
* AS: Apache ServiceMix 4.3.1

**Comment by koo-taejin** [comment]
Hi nike5

The [link](https://github.com/naver/pinpoint#supported-modules) lists the modules we support.
ServiceMix is not supported.

If you want to trace unsupported modules you need to tell the agent which methods to trace by setting profiler.include or profiler.entrypoint in pinpoint.config (more details [here](https://groups.google.com/forum/#!msg/pinpoint_user/4FTXxcakkTM/fLm7wVbtAAAJ)).

thanks.
