### ISSUE TITLE
pinpoint 's plugins compatibility , ask for help.

### ISSUE THREAD

**Issue by magicdogs** [naver/pinpoint#2603]
I want to know pinpoint 's some plugins compatibility,such as redis,mysql,dubbo,tomcat,postgre 's plugins,which version's driver they can compatible, who can list the menu,thank 's alot.

**Comment by Xylus** [comment]
Hi @magicdogs 
I'm not too sure of jedis, dubbo, and postgresql versions but I think anything that was released reasonably recently should work. A recently released major version might not work.
MySQL connector - 5.x should work
Tomcat - 6+ (not sure about 5 but it's pretty old)

If something doesn't work with a version you're using please let us know.
Thanks!

**Comment by magicdogs** [comment]
@Xylus At first  thank for your help 
 i am using pinpoint-postgresql-jdbc-driver-plugin-1.6.0.jar into my application ,  the postgresql driver version is 9.1-901.jdbc4 ,  but the pinpoint collector UI show like this 
![image](https://cloud.githubusercontent.com/assets/22540413/22916050/b675df9e-f2b6-11e6-9575-39794f7e8bac.png) ,
 i had checked the application logs file,  i had checked the application logs file,  has found something error information , and i had compared postgre plugin 's code and the postgres driver 's code,
cause those problems the reason was PostgreSQLConnectionCreateInterceptor ' s @TargetConstructor({ "org.postgresql.util.HostSpec[]", "java.lang.String", "java.lang.String", "java.util.Properties", "java.lang.String" }), 
but in fact the postgres driver Jdbc4Connection seem like  this @TargetConstructor({ "java.lang.String", "int", "java.lang.String","java.lang.String", "java.util.Properties", "java.lang.String" }) ,  
though i had solved those problem, i think need to know pinpoint 's plugins compatibility, 
the best way is list all pinpoint  's plugins  compatibility information that can let us avoid to face those problem again , Thanks!

**Comment by Xylus** [comment]
@magicdogs Thanks for identifying the problem!
There is a known issue #2239 regarding postgresql 9.4.1207+, but looks like you've found another version that needs to be supported.
Thanks for testing this out.

I totally agree with you that supported versions need to be tested and displayed somewhere. It'll take a long time to test everything, but we'll hopefully add this information.
