### ISSUE TITLE
Questions about topology.

### ISSUE THREAD

**Issue by clearBird** [naver/pinpoint#2605]
Hi  Pinpoint team.
I have a questions,it's about topology.

Description
 Click on the topology of unknown application content,the right side of the graphics  has a paging function,but when click on the line, there is no paging function.
Is excuse me this paging didn't do?  or  have a solution?

This is problem screenshots.
![have paging](https://cloud.githubusercontent.com/assets/25739770/22878513/0d363bb4-f215-11e6-801a-45f7fdf9716d.png)
![no paging](https://cloud.githubusercontent.com/assets/25739770/22878512/0d32b598-f215-11e6-8705-89d6a5fb5a2c.png)

Thank you!

**Comment by Xylus** [comment]
Hi @clearBird 
They should both be paged, which version are you running?
Could you try the latest version from master and see if that fixes your issue?

**Comment by clearBird** [comment]
Now is version 1.6.0,the current version does‘t be paged.
Do you have a newer version?

**Comment by emeroad** [comment]
Hi @clearBird
Already fixed in 1.6.1-SNAPSHOT
