### ISSUE TITLE
PinPoint is not working

### ISSUE THREAD

**Issue by knareshslk** [naver/pinpoint#2610]
PinPoint is not working.....

Getting below pages..

![image](https://cloud.githubusercontent.com/assets/25608591/22922276/0b9a59c6-f2c3-11e6-9aea-cd9c8d6b55f6.png)

![image](https://cloud.githubusercontent.com/assets/25608591/22922249/ec4d22f6-f2c2-11e6-8b81-68abd3e21933.png)

**Comment by Xylus** [comment]
@knareshslk 
You have repeatedly ignored our request to follow the [guideline](https://github.com/naver/pinpoint/blob/master/CONTRIBUTING.md) when creating new issues.
We cannot help you unless you give us enough information for us to work with. Making a post with a screenshot of a 404 error does not tell us anything.
Please at least make an effort to describe what you have done and the environment in which you're working on. We even have a [template](https://github.com/naver/pinpoint/blob/master/ISSUE_TEMPLATE.md) for all this.
This goes to all your other issues as well.

Please take this as a final warning before we decide on the need to block you from the repository.
