### ISSUE TITLE
Help ! ! How should i do when i want use another ZooKeeper

### ISSUE THREAD

**Issue by koalton** [naver/pinpoint#2619]
#
In my server,there is already hava a zookeepr  running, so i config something blow :
1.{hbase_home}/conf/hbase-env.sh, add "export HBASE_MANAGES_ZK=false" at file end ;
2.{hbase_home}/conf/hbase-site.xml, the file is <configuration>
<property>
<name>hbase.rootdir</name>
<value>file:///data/hbase</value>
</property>
<property>
      <name>hbase.zookeeper.property.clientPort</name>
      <value>2181</value>
</property>
<property>
      <name>hbase.zookeeper.quorum</name>
      <value>localhost</value>
</property>
<property>
      <name>hbase.zookeeper.property.dataDir</name>
      <value>/usr/local/zookeeper/data</value>
</property>
<property>
      <name>hbase.cluster.distributed</name>
      <value>true</value>
</property>
</configuration>
3.pp-collector and pp-web 's hbase.properties add ZK config :hbase.client.host=localhost
hbase.client.port=2182.
and then ,my pp-web can not work well. In the catalina.out,it shows Opening socket connection to server localhost/127.0.0.1:2181

My pinpoint version is 1.6

**Comment by koo-taejin** [comment]
Hi koalton 

If you would like to use the existing zookeeper in HBASE, we suggest asking the HBASE community, which has more knowledge than us.

In addition, zookeeper is used to configure clusters within PINPOINT.
You can change the zookeeper address by changing the cluster.zookeeper.address (pinpoint-collector.properties, pinpoint-web.properties) setting.

thanks.

**Comment by koalton** [comment]
@koo-taejin  ,thanks your help.this problem i hava resolve it .
By the way ,would you like help me about another problem ? #2653

**Comment by iamlile** [comment]
Hi,koaltion, Would you like to tell me how to solve？ For example，how to config these:
cluster.zookeeper.address=
cluster.zookeeper.sessiontimeout=30000
cluster.listen.ip=
cluster.listen.port=

**Comment by koalton** [comment]
@iamlile  for a long time do not use pp and i forgot it ..sorry
