### ISSUE TITLE
How do I close the pinpoint console log?

### ISSUE THREAD

**Issue by chendisun** [naver/pinpoint#2624]
At present I am using the command "MVN install -Dmaven.test.skip=true" package, but I found that will print the console log records, when the large amount of the performance will drop, so I want to close the console log.

**Comment by Xylus** [comment]
The `mvn install -Dmaven.test.skip=true` command is for building pinpoint from source. You shouldn't need to run this often unless you're developing something.

Are you talking about the agent log that gets printed out when you run your application?
If this is the case, you can either change the log level of the agent by modifying *$PINPOINT_AGENT/lib/log4j.xml*, or specify maven profile when packaging the agent (for example, `mvn package -Prelease`) which packages *log4j.xml* with log level defaulted to INFO.

**Comment by chendisun** [comment]
thx, I solved it myself。

**Comment by chendisun** [comment]
thx, I solved it myself。
