### ISSUE TITLE
The issue  of  " java.lang.OutOfMemoryError: GC overhead limit exceeded " about agent 

### ISSUE THREAD

**Issue by Aires1208** [naver/pinpoint#2626]
#### Description
We simulated a scene about OOM of a SpringBoot app ,expect to throw an exception "java.lang.OutOfMemoryError: GC overhead limit exceeded" , and  start the service with the agent. 

It takes a long time to receive exception information, if multiple requests are made, the service hangs directly. 
But start the app without  agent command, the exception message will return quickly ！The agent affects the application to a certain extent ！

#### Environment

* Pinpoint version: 1.6.0
* OS, WAS, affected library, etc: Linux
* Additional details (e.g. how your collector/web is set up):

**Comment by emeroad** [comment]
Unfortunately. Pinpoint team does not provide technical support.
First, Analyze your application heap dump.
