### ISSUE TITLE
about pinpoint support docker

### ISSUE THREAD

**Issue by vwyuheng** [naver/pinpoint#2629]
Can pinpoint collector&web support docker deployment?

**Comment by Xylus** [comment]
Hi @vwyuheng 
I think several people have them running on docker. There's a [docker compose file](https://github.com/naver/pinpoint/blob/master/docker-compose.yml) on the repository if you'd like to take a look at it.
There's also some guides posted by others (links available [here](https://github.com/naver/pinpoint/wiki#resources-english)).

If anyone has any experience running pinpoint on docker, please feel free to pitch in.
