### ISSUE TITLE
Call Tracing between different JVM is not working 

### ISSUE THREAD

**Issue by dinesh4747** [naver/pinpoint#2631]
we have installed the Pinpoint agent on three JVM sitting on different servers A,B and C

All three pinpoint agent installation and collector communication is working fine, but we couldn't see the hits happening across tiers in a distributed way 

Only when we select the Independent JVM we can able to see that detailed calls of their JVM 

But on a ideal case when i select the system A --> It should display the distributed call tracing of all other systems calls to B and C as well when the request call flows from all the nodes from A<---->B<---->C

**Is there something we have missed out while configuring agent also like whether we need to mentioned the application names as same for all the different agents so that based on the common application name collector will aggregate the tracing calls?** 

Kindly let me know If I am missing something here

**Comment by dinesh4747** [comment]
CATALINA_OPTS="$CATALINA_OPTS -javaagent:$AGENT_PATH/pinpoint-bootstrap-1.6.0-RC1.jar"
CATALINA_OPTS="$CATALINA_OPTS -Dpinpoint.agentId=2727"
CATALINA_OPTS="$CATALINA_OPTS -Dpinpoint.applicationName=Ordersystem"

My Question is whether we need to mention the -Dpinpoint.applicationName as "Ordersystem for all my agents machine so that i would aggregate the call for all the unique agent ID and display it ins UI

**Comment by dinesh4747** [comment]
But In my case I have given different application names for all the agents - I want to understand on that is the reason why we couldnt see the distributed tracing stuff in web UI?

**Comment by Xylus** [comment]
Hi @dinesh4747 
Think application name as a logical grouping of servers.
So if A, B, and C are all running on different JVMs but have the same application deployed (ie serve the same purpose), you could group them up using the same application name (but with different agent ids). If A, B, and C are completely different from each other, you should give them different application names.
In the Web UI, servers with the same application name will be grouped together into a single node.

In your case, I'm guessing A, B, and C are all running different applications, so giving each of them different application names would be correct. The way you configured your agents should be fine.

Could you explain how servers A, B, and C are sending requests to each other? (http? thrift? etc)
A bit of detail (screenshots?) on how the server map is being rendered when you select A, B, and C's application name on the Web UI would be great as well.
Thanks!

**Comment by dinesh4747** [comment]
<img width="958" alt="screen shot 2017-02-21 at 2 08 52 pm" src="https://cloud.githubusercontent.com/assets/23452852/23157040/7db4e13a-f83f-11e6-8704-375ddca1828e.png">

**Comment by dinesh4747** [comment]
In which i see that GOA and ATP were the application JVM where we have installed pinpoint agents

Ideally calls goes in this way as follows:

USER---->GOA--->ATP (In both GOA and ATP JVM pinpoint agent were installed)

But if you see the server map that User is directly hitting the ATP but that's not the case whereas it should be like Only from user-->goa---> all the systems

**Comment by Xylus** [comment]
Ah I see your question now.

The `User --154,876--> ATP` is showing up because there are other servers (or clients) that are calling *ATP*.
Since you have Pinpoint agent installed in *ATP*, they will pick up all incoming RPCs whether they're from *GOA* or not.

To only display the transactions that have requests going from *GOA* to *ATP*, you can right-click on the edge between *GOA* and *ATP* and select "Filter Transactions".

Please let me know if anything doesn't make sense.

**Comment by dinesh4747** [comment]
Yes i have already filtered the transaction from GOA to ATP and could able ti see the stack 

As part of my test I am just hitting only GOA API which internally calls ATP and I except the same server map should be articulated in dashboards as well

But here it just displays like from users---->ATP which looks bit confusing 

What's happening here is User --(154,876)----->GOA----> ATP but it looks in other way in the dasboard

**Comment by Xylus** [comment]
So it seems like you have multiple instances of GOA servers running, with only 1 of them with the agent attached.
You should attach the agent to all of them to achieve what you're looking for.

**Comment by dinesh4747** [comment]
HI @Xylus - sure i shall try integrating agents in all the GOA JVM's and see how it leverages 

Thanks,
Dinesh N
