### ISSUE TITLE
pinpoint plugin like Dubbo，can someone help me？

### ISSUE THREAD

**Issue by linking12** [naver/pinpoint#2634]
Hi 
   i have write a plugin like Dubbo, this is a rpc framework in my company，my service type 1111,9132;
and the data has collected，but the web ui home page，consumer to provider linked has not appeared；
ServiceType：
```
 ServiceType   SALUKI_PROVIDER_SERVICE_TYPE = ServiceTypeFactory.of(1111,"SALUKI_PROVIDER", "SALUKI",RECORD_STATISTICS);
 ServiceType   SALUKI_CONSUMER_SERVICE_TYPE = ServiceTypeFactory.of(9132, "SALUKI_CONSUMER", "SALUKI",RECORD_STATISTICS);
 AnnotationKey SALUKI_ARGS_ANNOTATION_KEY   = AnnotationKeyFactory.of(92, "saluki.args");
 AnnotationKey SALUKI_RESULT_ANNOTATION_KEY = AnnotationKeyFactory.of(93, "saluki.result");
```

![image](https://cloud.githubusercontent.com/assets/4882172/23160566/f621ead8-f861-11e6-956c-640cff28b712.png)

and in server map，is appeared
![image](https://cloud.githubusercontent.com/assets/4882172/23160642/383e4c40-f862-11e6-9b42-efb2eddacc4b.png)

**Comment by Xylus** [comment]
Hi @linking12 
I think you might have gotten the provider and consumer mixed up. Consumer should be the one with 1xxx `ServiceType` code (SERVER), and the provider should be the one with 9xxx `ServiceType` code (RPC).

**Comment by linking12** [comment]
@Xylus 
dubbo like this，i think the code of plugin Interceptor is reverseed
```
 ServiceType DUBBO_PROVIDER_SERVICE_TYPE = ServiceTypeFactory.of(1110,"DUBBO_PROVIDER", RECORD_STATISTICS);
 ServiceType DUBBO_CONSUMER_SERVICE_TYPE =ServiceTypeFactory.of(9110,"DUBBO_CONSUMER", RECORD_STATISTICS);
```

Now，i have fix this problem，but have new one
![image](https://cloud.githubusercontent.com/assets/4882172/23196571/625d7652-f8f5-11e6-8c66-fc126b1c1c72.png)

why the provider applicationName is unknow group.
In ConsumerInterceptor i have report the remoteaddress as endPoint,and in ProviderInterceptor i have report service type.

ConsumerInterceptor
```
    String endPoint = getProviderServer();
     recorder.recordEndPoint(endPoint);
    recorder.recordDestinationId(endPoint);

```
ProviderInterceptor
```
       ServerInvocation invocation = (ServerInvocation) target;
        recorder.recordServiceType(SalukiConstants.SALUKI_PROVIDER_SERVICE_TYPE);
        recorder.recordRpcName(invocation.getRpcName());
        recorder.recordEndPoint(invocation.getLocalAddressString());
```

**Comment by Xylus** [comment]
Ah I see, it seems like I'm the one who had consumer and provider mixed up :)
If so, your previous interceptor code looked fine I think (not sure).
Either way, the consumer interceptor should be the one hooking the method that invokes the rpc, and the provider interceptor should be the one hooking the method that accepts the rpc.

Once this is sorted out, the provider interceptor should call `SpanRecorder.recordAcceptorHost()` and record the actual host that the client(consumer) used to make the rpc.

**Comment by linking12** [comment]
@Xylus Thanks 
I have saw this issues https://github.com/naver/pinpoint/issues/1395
The answer like yours.
I think is solve my problem
