### ISSUE TITLE
How to set pinpoint agent log level to WARN from DEBUG?

### ISSUE THREAD

**Issue by tinabear** [naver/pinpoint#2642]
Can I change the logging level to WARN by pinpoint.config file? Or have to change the code?

Thank you,

**Comment by koo-taejin** [comment]
Please refer to #1545.

**Comment by tinabear** [comment]
@koo-taejin I tried with changing logging level to ERROR for pinpoint agent by the file lib/log4j.xml. But there are still a lot of INFO messages in /var/log/syslog. It seems not work by only changing this file.

**Comment by koo-taejin** [comment]
Our default setting for log4j is not recorded in syslog.(record /logs/ directory) 
Check to confirm your syslog and log4j settings.
