### ISSUE TITLE
pinpoint-web use fat jar

### ISSUE THREAD

**Issue by linking12** [naver/pinpoint#2647]
Hi
    i think point-web use spring boot by fat jar is a good way，Is there any plan？

**Comment by emeroad** [comment]
We do not have a plan
  - The pinpoint should be deployed on any was server

**Comment by linking12** [comment]
@emeroad 
Thanks.
also,I have a question，can pinpoint team can support a doc about which api use jdk1.6 and jdk1.8?

**Comment by linking12** [comment]
i have find the way
