### ISSUE TITLE
Is okay to change AGENT_NAME_MAX_LEN value as we need?

### ISSUE THREAD

**Issue by tinabear** [naver/pinpoint#2655]
Possible to increase it to 40 locally? And build .jar files for our own environment.

Thank you,

**Comment by chenguoxi1985** [comment]
Hi tinabear,

I think it's ok. But You should build agent and collector together. Maybe web ...

**Comment by chenguoxi1985** [comment]
Hi tinabear,

 I would like to add, if you modify AGENT_NAME_MAX_LEN, old data in hbase will be invalid. Please see the two classes: TraceRowKeyDecoderV1/V2.  Pinpoint can not decode rowkey that AGENT_NAME_MAX_LEN changed.
