### ISSUE TITLE
Any Replacement suggestions for Go JS for real time server mapping charts? Thsi single road block stopping to use PP APM as open source .

### ISSUE THREAD

**Issue by mathi201028** [naver/pinpoint#2660]
Any Replacement suggestions for Go JS for real time server mapping charts? Thsi single road block stopping to use PP APM as open source .

#### Description
GO JS licensing limitation. Can be integrate with any free version real time chart drawing?

#### Environment
GO JS library and chart function

**Comment by Xylus** [comment]
Hi @mathi201028 
As far as we know, you are correct in that setting up your own internal Pinpoint cluster for anything other than evaluation purposes will require purchasing the license.

As to your question, we're not actively developing for an alternative as we unfortunately haven't found a suitable open source replacement.

**Comment by mathi201028** [comment]
Thanks Xylus, Unfortunately this leaving us product not used as GPL for commercial purpose.
