### ISSUE TITLE
The transactionList request  is waiting, and the log does not output exception information

### ISSUE THREAD

**Issue by enica** [naver/pinpoint#2661]
The transactionList request  is waiting, and the log does not output exception information
#### Description
The transactionList request  is waiting, and the log does not output exception information。
url: http://192.168.3.108:28080/#/transactionList/gtw@TOMCAT/2d/2017-03-03-09-21-57
logs:
`2017-03-03 10:10:44 [DEBUG](c.n.p.w.c.ScatterChartController   :129) query:TransactionMetadataQuery{queryConditionList=[QueryCondition [transactionId=TransactionId [gtw01^1487303071532^330], collectorAcceptorTime=1488421724351, responseTime=76], QueryCondition [transactionId=TransactionId [gtw01^1487303071532^329], collectorAcceptorTime=1488421724132, responseTime=649]]}
2017-03-03 10:10:47 [DEBUG](c.n.p.r.s.DefaultPinpointServer    :418) DefaultPinpointServer@3bfe8d9 handlePingPacket() started. packet:PingPacket{pingId:2499(RUN_DUPLEX)}
2017-03-03 10:10:47 [DEBUG](c.n.p.w.c.c.ClusterAcceptor        :105) ping received PingPacket{pingId:2499(RUN_DUPLEX)} DefaultPinpointServer@3bfe8d9(remote:/192.168.3.108:37783, state:RUN_DUPLEX) 
2017-03-03 10:10:47 [DEBUG](c.n.p.r.s.DefaultPinpointServer    :55 ) pong write success. channel:[id: 0xa6bcc89f, /192.168.3.108:37783 => /192.168.3.108:29997]`

#### Environment
* Pinpoint version:v1.6.0.
* redhat 6.5
* all servers install in one Virtual machine

**Comment by Xylus** [comment]
Hi @enica 
Please post a screenshot and/or provide the steps you took to encounter the issue (even if it's something as simple as dragging on the scatter chart).
The url you've provided is of a private network so we can't take a look at the issue.

**Comment by enica** [comment]
pic1-request page:
![o1a j1e64g3u bnp_ w68l](https://cloud.githubusercontent.com/assets/6247206/23643695/4328d9ea-033e-11e7-926d-3e99a00645bf.png)
pic2-web log:
![h__zzamb i8 ra8ikp 3988](https://cloud.githubusercontent.com/assets/6247206/23643708/5f2aae70-033e-11e7-9d82-822b4817d84f.png)

**Comment by enica** [comment]
Hi @Xylus 
Please help me analyze the reasons.

**Comment by denzelsN** [comment]
Hi @enica 
What is your browser? ie? chrome?
Can you capture error log in developer tool?

**Comment by enica** [comment]
Hi @denzelsN 
shift to a new server,reinstall.now it's ok.
thanks.
