### ISSUE TITLE
pp 1.6 web nodata

### ISSUE THREAD

**Issue by behinds** [naver/pinpoint#2663]

**Comment by behinds** [comment]
![image](https://cloud.githubusercontent.com/assets/21158480/23535608/62a0b118-fffa-11e6-9bd1-d2b8ed25c651.png)

**Comment by behinds** [comment]
weblogic 10.3.5
jdk 1.6.0_45
spring mvc

**Comment by Xylus** [comment]
Please reopen if you have anything to add.
