### ISSUE TITLE
Js format incorrect

### ISSUE THREAD

**Issue by huayaoyue6** [naver/pinpoint#2675]
#### Js format bug 

Parameters will not format correctly when containts  Double quotes , like sql or some else .
I thinks the [distributed-call-flow.directive.js](https://github.com/naver/pinpoint/blob/master/web/src/main/webapp/features/distributedCallFlow/distributed-call-flow.directive.js) function "argumentFormatter" or "removeTag" not handle this situation
#### Environment

* Pinpoint version: 1.5.2 - now 
* OS, WAS, affected library, etc: 
* Additional details (e.g. how your collector/web is set up):

**Comment by denzelsN** [comment]
Hi @huayaoyue6 
Thank you your bug report.
I will check this.

**Comment by denzelsN** [comment]
@huayaoyue6 
Can you show your screenshot?

**Comment by huayaoyue6** [comment]
![2017-03-08_1533283](https://cloud.githubusercontent.com/assets/6671110/23694613/cc872b1a-0415-11e7-85d3-d49002164dd3.png)

Actually,the two "Closed Parenthesis(>)" and data before it (? order by callTime desc limit ?,?") is a part of  html's element called "data-content" .but the js function "removeTag" does not handle the situation which parameters may containts "Double Quotes",so data after format also containts double quotes,so it break out origin html layout .

**Comment by denzelsN** [comment]
@huayaoyue6 
Can you show that response( raw text of transactionInfo.pinpoint request - only that sql part )?
If it is difficult to write on the here, send it by mail.( hyojong.song2015@navercorp.com )

**Comment by denzelsN** [comment]
@huayaoyue6 
I understood why that problem occurred.
Once I temporarily removed the popover feature in argument field to prevent that problem. ( https://github.com/naver/pinpoint/commit/ca5d1db88f2e57e25c57d3ab6a63070fa0ed7d36 )
I'll think about how to fix it.
