### ISSUE TITLE
[Question] Is there any way to disable the client temporarily?

### ISSUE THREAD

**Issue by stefli** [naver/pinpoint#2687]
Due to the pinpoint server is down temporarily, such as out of space. But all the clients continue to send data to server, and all requests are timeout. Many logs are created, impacted the client service.

So, is there any way to disable the client temporarily? Let it not to communicate with the pinpoint server. And can be enabled after issue been solved.

**Comment by Xylus** [comment]
Hi @stefli 
There unfortunately isn't a way to temporarily disable the client currently. As a workaround, you could try dropping the pinpoint agent's log level to WARN (or at least to INFO) for applications in production, which will drastically reduce the size of your log file.

**Comment by stefli** [comment]
@Xylus Thanks! That might be the proper way to reduce the impact.
But, I think this requirement is reasonable.

**Comment by Xylus** [comment]
@stefli 
Yup, I totally agree with you.

**Comment by Xylus** [comment]
@stefli 
If the hbase server goes down (or you need to shut it down temporarily), you can have the collector discard everything the agents send. The agent will continue to work as if nothing is wrong and there won't be any increase in log size.
You can enable this by setting the following options in *pinpoint-collector.properties* :
```
# Through an API over HTTP
collector.admin.password=password
collector.admin.api.rest.active=true
# Through JMX
collector.admin.api.jmx.active=true
```
Starting the collector with either of the options above will allow you to tell the collector (over HTTP, or over JMX) to receive messages from the agents but not attempt to store anything in HBase.

**Comment by stefli** [comment]
@Xylus i'll try this later, thanks.

**Comment by stefli** [comment]
@Xylus What's the key configuration of discarding the requests? jmx.active=true?
I have tried this, but it seems everything is normal as before. All the data still been inserted into hbase.

**Comment by koo-taejin** [comment]
@stefli 
If you enable this feature,
You can enable or disable saving HBase storage by using jmx operation.

![jmx](https://cloud.githubusercontent.com/assets/10057874/23934845/56a1211e-098b-11e7-87e6-08b81fa2d5ff.png)

**Comment by stefli** [comment]
@koo-taejin You mean we should use api or jmx to call the disableAccess to make it work.
Got it, thanks.
![image](https://cloud.githubusercontent.com/assets/56305/23934987/1e1a76f8-0984-11e7-8b5a-8a0da2f70063.png)

**Comment by koo-taejin** [comment]
@stefli ok thanks :)
