### ISSUE TITLE
Is there a way to link different tomcat in a topo map

### ISSUE THREAD

**Issue by zilingliyu** [naver/pinpoint#2691]
Hi,everyone:
In the introduction of the overview below a topology map, inside the tomcat (front-web) to another tomcat (backend-web / backend-api) is how to connect?

**Comment by Xylus** [comment]
Hi @zilingliyu 
I don't quite understand your question. Could you explain it with a bit more detail please?

**Comment by zilingliyu** [comment]
Thank you very much for replying me so quickly!
     I do not understand how these two tomcats connect together in the figure below.Specifically how to achieve, what is the principle? What files to configure?
![f6 0 gzy4r j 38tw2](https://cloud.githubusercontent.com/assets/26271856/23843930/0550c608-07fa-11e7-801b-b38e7d632940.png)

**Comment by justinhql** [comment]
Hi ,my system have four tomcats  and they linked by URL, i would like to know how to show them up in a topo map?

**Comment by emeroad** [comment]
Refer to the technical-overview 
 - https://github.com/naver/pinpoint/wiki/Technical-Overview-Of-Pinpoint
