### ISSUE TITLE
mvn install pinpoint error

### ISSUE THREAD

**Issue by ruizlake** [naver/pinpoint#2712]
[INFO] Reactor Summary:
[INFO] 
[INFO] pinpoint ........................................... SUCCESS [  1.730 s]
[INFO] pinpoint-annotations ............................... SUCCESS [  1.699 s]
[INFO] pinpoint-thrift .................................... SUCCESS [  0.694 s]
[INFO] pinpoint-commons ................................... SUCCESS [  3.485 s]
[INFO] pinpoint-bootstrap-core ............................ SUCCESS [  0.707 s]
[INFO] pinpoint-bootstrap ................................. SUCCESS [  0.378 s]
[INFO] pinpoint-rpc ....................................... SUCCESS [  0.723 s]
[INFO] pinpoint-profiler .................................. SUCCESS [  1.739 s]
[INFO] pinpoint-commons-hbase ............................. SUCCESS [  3.162 s]
[INFO] pinpoint-commons-server ............................ SUCCESS [  1.718 s]
[INFO] pinpoint-profiler-test ............................. SUCCESS [  0.858 s]
[INFO] pinpoint-profiler-optional-parent .................. SUCCESS [  0.722 s]
[INFO] pinpoint-profiler-optional-jdk6 .................... SUCCESS [  0.834 s]
[INFO] pinpoint-profiler-optional-jdk7 .................... SUCCESS [  0.431 s]
[INFO] pinpoint-profiler-optional ......................... SUCCESS [  0.221 s]
[INFO] pinpoint-httpclient3-plugin ........................ SUCCESS [  0.711 s]
[INFO] pinpoint-httpclient4-plugin ........................ SUCCESS [  0.451 s]
[INFO] pinpoint-ning-asynchttpclient-plugin ............... SUCCESS [  0.422 s]
[INFO] pinpoint-gson-plugin ............................... SUCCESS [  0.325 s]
[INFO] pinpoint-cubrid-jdbc-driver-plugin ................. SUCCESS [  0.456 s]
[INFO] pinpoint-mysql-jdbc-driver-plugin .................. SUCCESS [  0.297 s]
[INFO] pinpoint-mariadb-jdbc-driver-plugin ................ SUCCESS [  0.324 s]
[INFO] pinpoint-postgresql-jdbc-driver-plugin ............. SUCCESS [  0.284 s]
[INFO] pinpoint-jtds-plugin ............................... SUCCESS [  0.254 s]
[INFO] pinpoint-oracle-jdbc-driver-plugin ................. SUCCESS [  0.274 s]
[INFO] pinpoint-commons-dbcp-plugin ....................... SUCCESS [  0.282 s]
[INFO] pinpoint-commons-dbcp2-plugin ...................... SUCCESS [  0.421 s]
[INFO] pinpoint-hikaricp-plugin ........................... SUCCESS [  0.392 s]
[INFO] pinpoint-test ...................................... SUCCESS [  0.712 s]
[INFO] pinpoint-cassandra-driver-plugin ................... SUCCESS [  0.605 s]
[INFO] pinpoint-jdk-http-plugin ........................... SUCCESS [  0.246 s]
[INFO] pinpoint-redis-plugin .............................. SUCCESS [  0.335 s]
[INFO] pinpoint-tomcat-plugin ............................. SUCCESS [  0.388 s]
[INFO] pinpoint-json-lib-plugin ........................... SUCCESS [  0.253 s]
[INFO] pinpoint-jackson-plugin ............................ SUCCESS [  0.257 s]
[INFO] pinpoint-thrift-plugin ............................. SUCCESS [  0.317 s]
[INFO] pinpoint-user-plugin ............................... SUCCESS [  0.253 s]
[INFO] pinpoint-arcus-plugin .............................. SUCCESS [  0.516 s]
[INFO] pinpoint-google-httpclient-plugin .................. SUCCESS [  0.305 s]
[INFO] pinpoint-jetty-plugin .............................. SUCCESS [  0.387 s]
[INFO] pinpoint-spring-plugin ............................. SUCCESS [  0.456 s]
[INFO] pinpoint-spring-boot-plugin ........................ SUCCESS [  0.233 s]
[INFO] pinpoint-ibatis-plugin ............................. SUCCESS [  0.247 s]
[INFO] pinpoint-mybatis-plugin ............................ SUCCESS [  0.233 s]
[INFO] pinpoint-okhttp-plugin ............................. SUCCESS [  0.311 s]
[INFO] pinpoint-log4j-plugin .............................. SUCCESS [  0.248 s]
[INFO] pinpoint-logback-plugin ............................ SUCCESS [  0.240 s]
[INFO] pinpoint-dubbo-plugin .............................. SUCCESS [  0.546 s]
[INFO] pinpoint-activemq-client-plugin .................... SUCCESS [  0.417 s]
[INFO] pinpoint-cxf-plugin ................................ SUCCESS [  0.577 s]
[INFO] pinpoint-hystrix-plugin ............................ SUCCESS [  0.386 s]
[INFO] pinpoint-jboss-plugin .............................. SUCCESS [  2.936 s]
[INFO] pinpoint-vertx-plugin .............................. SUCCESS [  1.080 s]
[INFO] pinpoint-resin-plugin .............................. SUCCESS [  0.598 s]
[INFO] pinpoint-plugins ................................... SUCCESS [  0.319 s]
[INFO] pinpoint-bootstrap-core-optional ................... SUCCESS [  0.352 s]
[INFO] pinpoint-tools ..................................... SUCCESS [  0.668 s]
[INFO] pinpoint-agent-distribution ........................ SUCCESS [  5.855 s]
[INFO] pinpoint-collector ................................. FAILURE [  1.043 s]
[INFO] pinpoint-profiler-optional-jdk8 .................... SKIPPED
[INFO] pinpoint-web ....................................... SKIPPED
[INFO] pinpoint-hbase-distribution ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 46.575 s
[INFO] Finished at: 2017-03-15T11:29:29+08:00
[INFO] Final Memory: 65M/810M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project pinpoint-collector: Compilation failure -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project pinpoint-collector: Compilation failure
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:976)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pinpoint-collector

export JAVA_6_HOME=/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
export JAVA_7_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home
export JAVA_8_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home
export JAVA_HOME=$JAVA_8_HOME

**Comment by Xylus** [comment]
Hi @ruizlake 
Could you try building with maven debug flag (-X) and paste the error log please?
Thanks
