### ISSUE TITLE
Is there a way to get an end-to-end data stream based on TransactionId

### ISSUE THREAD

**Issue by zilingliyu** [naver/pinpoint#2713]
How to get an end-to-end flow based on a TransactionId, as shown in the following figure, according to TransactionId get a specific call process
![d44c8c10-0964-11e7-939e-52474f629051 1](https://cloud.githubusercontent.com/assets/26271856/23934929/972a51d6-0983-11e7-9842-1585d124a272.png)

**Comment by Xylus** [comment]
Hi @zilingliyu 
I'm not quite sure I understand your question. The distributed call flow above is for a single transaction (TransactionID : agentA1^1417590750449^19).
Please let me know if you're asking for something else.

**Comment by zilingliyu** [comment]
Yes, you understand very correct, I would like to use the api of this function and where should I find it ?

**Comment by Xylus** [comment]
We don't have an API that sends a nicely formatted json response for the call stack.
If you don't mind this, you can try out `/transactionInfo.pinpoint?traceId=$TRANSACTION_ID`.
