### ISSUE TITLE
 Does the applicationName support Chinese

### ISSUE THREAD

**Issue by ceeyangwen** [naver/pinpoint#2718]
I've changed IdValidateUtils.ID_PATTERN in order to make Agent's applicationName support Chinese,But,The Admin show display caller messy code.I have debuged the Collect and the find the bytes of insert hbase is right.But, the Admin query data is error.

**Comment by emeroad** [comment]
Sorry. We do not provide technical support for custom modifications.

Additionally, I did not consider multibyte for ApplicationName or AgentName.
