### ISSUE TITLE
pinpoint use hbase cluster can not work

### ISSUE THREAD

**Issue by xlingit** [naver/pinpoint#2734]
pinpoint user hbase cluster can not work. the hbase.client.host =ip1,ip2,ip3

**Comment by koo-taejin** [comment]
Hi xlingit 

I have tried connecting the hbase cluster to my test environment and confirmed that this format(ip1,ip2,ip3) is no problem at all.

The pinpoint hbase.client.host configuration is passed value to hbase.zookeeper.quorum without any changes.
If you continue to have problems, we recommend that you use HBaseClient directly to connect and debug your hbase cluster.

Additionally, please ask questions according to the format of the [guidelines](https://github.com/naver/pinpoint/blob/master/CONTRIBUTING.md).

Thanks

**Comment by xlingit** [comment]
my hbase  cluster installed  with hdp ,get the error is follow:
org.springframework.data.hadoop.hbase.HbaseSystemException: Failed 1 action: Unable to find region for #xuser20170316\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01Z\xEFK\x98\xE1\x00\x00\x00\x00\x00\x00\x00\x0D in Traces after 35 tries.: 1 time, ; nested exception is org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 1 action: Unable to find region for #xuser20170316\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01Z\xEFK\x98\xE1\x00\x00\x00\x00\x00\x00\x00\x0D in Traces after 35 tries.: 1 time, 
        at org.springframework.data.hadoop.hbase.HbaseUtils.convertHbaseException(HbaseUtils.java:42)
        at org.springframework.data.hadoop.hbase.HbaseTemplate.convertHbaseAccessException(HbaseTemplate.java:107)
        at org.springframework.data.hadoop.hbase.HbaseTemplate.execute(HbaseTemplate.java:68)
        at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.put(HbaseTemplate2.java:296)
        at com.navercorp.pinpoint.collector.dao.hbase.HbaseTraceDao.insert(HbaseTraceDao.java:99)
        at com.navercorp.pinpoint.collector.handler.SpanHandler.handleSimple(SpanHandler.java:75)
        at com.navercorp.pinpoint.collector.receiver.AbstractDispatchHandler.dispatchSendMessage(AbstractDispatchHandler.java:56)
        at com.navercorp.pinpoint.collector.receiver.DispatchHandlerWrapper.dispatchSendMessage(DispatchHandlerWrapper.java:49)
        at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:121)
        at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:100)
        at com.navercorp.pinpoint.collector.receiver.udp.PooledPacketWrap.run(PooledPacketWrap.java:45)
        at com.navercorp.pinpoint.collector.receiver.udp.TimingWrap.run(TimingWrap.java:43)
        at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver$1.run(UDPReceiver.java:183)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by koo-taejin** [comment]
I don't have minimal information such as which pinpoint version you are using, which hbase version you are using, how the table was created, how the zookeeper cluster was configured, and so on.

We have been testing for a long time and have confirmed that it works well with the version we currently recommend.

If you want help without giving me enough information, there is nothing I can do for you.
If you need help, let me know how to reproduce this issue. So I will help you as much as possible.

**Comment by xlingit** [comment]
pinpoint1.5.2  hbase1.1.2(HDP)   hbase is a cluster(zookeeper)

in the hbase master server ,hbase shell create the table
![image](https://cloud.githubusercontent.com/assets/10951542/24137411/974e07aa-0e4e-11e7-8627-25002abc790b.png)

hbsae ui look as:
![image](https://cloud.githubusercontent.com/assets/10951542/24137615/91910000-0e4f-11e7-854f-e13bfea9dcf1.png)

**Comment by koo-taejin** [comment]
The name of the table is used to find the RegionServer
It is recommended that you re-create the TABLE again if can access to the tables except Traces TABLE .
(If you can not connect to all the TABLE, you need to check the relationship between HBase and Zookeeper.)

If you are still having problems, I recommend using the Pinpoint Hbase version we recommend.
(If possible, use the latest Stable version of Pinpoint, 1.6.0.)
Your current Pinpoint, Hbase version combination is an environment we have not tested.

Please refer to the HBase compatibility table on the README page.

**Comment by xlingit** [comment]
the tables is **reloaded** to  HBase cluster on the **master node with shell**.

The related configuration like as:
1)hbase.properties (in the war collector/web,  collector/web/agent/zookeeper on one machine 172.16.1.171; HBase cluster on the other machines)
`hbase.client.host=172.16.1.25,172.16.1.26,172.16.1.27
hbase.client.port=2181
# hbase timeout option================
# hbase default:true
hbase.ipc.client.tcpnodelay=true
# hbase default:60000
hbase.rpc.timeout=10000
# hbase default:Integer.MAX_VALUE
hbase.client.operation.timeout=10000
# hbase socket read timeout. default: 200000
hbase.ipc.client.socket.timeout.read=20000
# socket write timeout. hbase default: 600000
hbase.ipc.client.socket.timeout.write=60000
# ==================
# hbase client thread pool option
hbase.client.thread.max=128
hbase.client.threadPool.queueSize=5120
# prestartAllCoreThreads
hbase.client.threadPool.prestart=false`

2)pinpoint-collector.properties (in the war collector)
`# tcp listen ip and port
collector.tcpListenIp=0.0.0.0
collector.tcpListenPort=9994
# number of tcp worker threads
collector.tcpWorkerThread=8
# capacity of tcp worker queue
collector.tcpWorkerQueueSize=1024
# udp listen ip and port
collector.udpStatListenIp=0.0.0.0
collector.udpStatListenPort=9995
collector.l4.ip=
# number of udp statworker threads
collector.udpStatWorkerThread=16
# capacity of udp statworker queue
collector.udpStatWorkerQueueSize=512
collector.udpStatSocketReceiveBufferSize=4194304
# span listen port ---------------------------------------------------------------------
collector.udpSpanListenIp=0.0.0.0
collector.udpSpanListenPort=9996
# number of udp spanworker threads
collector.udpSpanWorkerThread=32
# capacity of udp spanworker queue
collector.udpSpanWorkerQueueSize=1024
collector.udpSpanSocketReceiveBufferSize=4194304
# number of agent event worker threads
collector.agentEventWorker.threadSize=8
# capacity of agent event worker queue
collector.agentEventWorker.queueSize=1024
statistics.flushPeriod=1000
# enable cluster in socket manager.
cluster.enable=false
cluster.zookeeper.address=localhost
cluster.zookeeper.sessiontimeout=30000
cluster.listen.ip=
cluster.listen.port=
#collector.admin.password=
#collector.admin.api.rest.active=
#collector.admin.api.jmx.active=
collector.spanEvent.sequence.limit=10000`

3)pinpoint-web.properties(in the war web)
`#local
cluster.enable=false
cluster.web.tcp.port=9997
cluster.zookeeper.address=localhost
cluster.zookeeper.sessiontimeout=30000
cluster.zookeeper.retry.interval=60000
cluster.connect.address=
# FIXME - should be removed for proper authentication
admin.password=admin
#log site link (guide url : https://github.com/naver/pinpoint/blob/master/doc/per-request_feature_guide.md)
#log.enable=false
#log.page.url=
#log.button.name=
# Configuration
config.sendUsage=true
config.editUserInfo=true
web.hbase.selectSpans.limit=500
web.hbase.selectAllSpans.limit=500
web.activethread.activeAgent.duration.days=7`

4) pinpoint.config(agent)
`# Collector server  # 
###############################
profiler.collector.ip=172.16.1.171
# placeHolder support "${key}"
profiler.collector.span.ip=${profiler.collector.ip}
profiler.collector.span.port=9996
# placeHolder support "${key}"
profiler.collector.stat.ip=${profiler.collector.ip}
profiler.collector.stat.port=9995
# placeHolder support "${key}"
profiler.collector.tcp.ip=${profiler.collector.ip}
profiler.collector.tcp.port=9994
......`

5)catalina.sh
# Control Script for the CATALINA Server
CATALINA_OPTS="$CATALINA_OPTS -javaagent:/pp/pp-agent/pinpoint-bootstrap-1.5.2.jar"
CATALINA_OPTS="$CATALINA_OPTS -Dpinpoint.agentId=ppid"
CATALINA_OPTS="$CATALINA_OPTS -Dpinpoint.applicationName=ppname"

**Comment by koo-taejin** [comment]
please set you're zookeeper address to hbase.client.host.

and, we do not provide technical support. 
all of issue except pinpoint bug is yours.

**Comment by xlingit** [comment]
my zookeeper address to hbase.client.host= hostname1,hostname2,hostname3; 
my hbase cluster bulid with apache Ambari(HDP).

1)the hbase cluster **bulid with apache Ambari(HDP)** ,the pinpoint work can not work ;
2)Yesterday,i try to bulid **a new hbase cluster not with  apache Ambari** ,the pinpoint work.
3)are you try the  hbase cluster bulid with apache Ambari(HDP)?

thanks!

**Comment by koo-taejin** [comment]
I didn't have experience that building HBASE cluster using apache ambari.
We configured the cluster according to the recommendation of the CDH and confirmed that it worked well, 

thanks.
