### ISSUE TITLE
Incomplete traces on Tomcat and Pinpoint 1.6.0

### ISSUE THREAD

**Issue by ofauchon** [naver/pinpoint#2735]
I'm profiling a customer application, and some transactions have very minimal/partial call-stack :

![image](https://cloud.githubusercontent.com/assets/561441/24054148/83139b62-0b3b-11e7-8ba3-9ffac01f9e36.png)

It's like Pinpoint stops tracing after Servlet Invoke(Request request, Response response) is called.
That only appends for a couple of urls. Other urls of the application are properly traced.

I read somewhere that Pinpoint don't support tracing some classes (eg: Threads )
Is there a complete list of unsupported components/classes ? 

I suggest you could add a fake trace at the end of the call-stack to give some details of the tracing error.
"Trace stopped due to xxxxxx "

Do you have workarounds for such situation ?

Thanks 

Olivier

**Comment by Xylus** [comment]
Hi @ofauchon 
What should come after the `invoke()` method?

We have a list of supported libraries [here](https://github.com/naver/pinpoint#supported-modules), and anything that's not there will not be traced.
For the case above, whatever that gets invoked after Tomcat's `invoke()` method should be something that is not supported by Pinpoint (or is an asynchronous invocation), and is probably not a result of a tracing error.

Please let us know if this is not the case.

**Comment by ofauchon** [comment]
Hi Xylus. 

The analysis of the source code revealed that some URLs uses Java API for RESTful Services (JAX-RS),
 like this one : 

import javax.ws.rs.DefaultValue;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;
...

@GET
  @Path("mysearch/{options}")
  public Response mysearch(@PathParam("options") String options)
  {
		... do something 
		... return
  
  }


Do Pinpoint support this framework ? 

Thanks

**Comment by emeroad** [comment]
Not supported.
