### ISSUE TITLE
Could cause Memory Leaks problem? Help 

### ISSUE THREAD

**Issue by DevotedTangLiu** [naver/pinpoint#2736]
#### Description

Yesterday, our system did not work normally, after checking log files and java dump file, it seems
that pinpoint record to much data in memory and run out the memory.

As I checked with MAT, I seems that pinpoint record large sql and parameters in memory. How 
long will these datas kept in memory and when should it be freed? I have no idea frequency pinpoint
agent send data to collector.

How could I solve this problem? Please Help.
FYI.
![mat1](http://7xnl6z.com1.z0.glb.clouddn.com/1.png)
![mat2](http://7xnl6z.com1.z0.glb.clouddn.com/2.png)
![mat3](http://7xnl6z.com1.z0.glb.clouddn.com/3.png)

#### Environment

* Pinpoint version: 1.6.0
* CentOS

**Comment by emeroad** [comment]
It is recommended that you adjust the `profiler.jdbc.sqlcachesize` option.

### profiler.config
```
# Size of cache. Fixed maximum.
profiler.jdbc.sqlcachesize=1024
```

**Comment by DevotedTangLiu** [comment]
Thanks, not sure if it helps. Each span may just record a few sql strings.
