### ISSUE TITLE
Issue with the graph of Active Thread in inspector 

### ISSUE THREAD

**Issue by sbs081** [naver/pinpoint#2741]
Pinpoint version:1.6.1

![image](https://cloud.githubusercontent.com/assets/8540577/24228687/c108d3f0-0fb0-11e7-994e-c3e680500508.png)

The red line with the peak,but the value of red line is 0?

**Comment by denzelsN** [comment]
@sbs081 
This chart is stacked area chart. not line chart.
( https://www.amcharts.com/demos/stacked-area/ )

**Comment by sbs081** [comment]
@denzelsN OK,but I think the flame graphic or stacked column chart is better.
(https://www.amcharts.com/demos/stacked-column-chart/)
