### ISSUE TITLE
Plans on kubernetes integration

### ISSUE THREAD

**Issue by thekalinga** [naver/pinpoint#2744]
Is there a plan to integrate this with kubernetes deployment model, if possible integrate with prometheus (kubernetes time series database)?

**Comment by emeroad** [comment]
Unfortunately. Pinpoint has no plans to integrate with prometheus.

**Comment by thekalinga** [comment]
How about Kubernetes?

Since kubernetes is more or less open standard for container orchestration, it would be better to make developers life easy to work in k8s environment.

**Comment by nsilve** [comment]
Integration with kubernetes is a very good idea!

**Comment by huayaoyue6** [comment]
I think It's have some works to do before move to platforms based on docker .Becase the agetId is configed by hand in jvm's arg . It's right ? @emeroad

**Comment by emeroad** [comment]
@huayaoyue6  You are right.

Unfortunately, We have no experience about kubernetes.
I do not know what the kubernetes deployment model means.
 - If it means to deploy the pinpoint server component(eg: web, collector, hbase.. ). It is recommended to use the Docker.

**Comment by jiaqifeng** [comment]
@thekalinga 
I just search using google about what prometheus and heapster is. As I understand it about metrics, which is mainly about cpu/response time/memory usage that is common metrics for any app. While as I understand the value pinpoint brings is how your applications interact with each other. To use pinpont better is highly depend on what kind your app is but not depend on what your platform is mesos or k8s. I am also searching the best pointcut for pinpoint in container world. If you have any thought about it please share it!
@huayaoyue6 
I have add a environment variable for application name, and ip:port for agentId in mesos environment as jvm args which make life easier.
