### ISSUE TITLE
How would pinpoint-resin-plugin-1.6.1-RC1.jar be used directly on pinpoint-1.6.0?

### ISSUE THREAD

**Issue by xulongju** [naver/pinpoint#2753]
Dear:
  all
How would pinpoint-resin-plugin-1.6.1-RC1.jar be used directly on pinpoint-1.6.0?

**Comment by Xylus** [comment]
The agent should work by simply dropping the plugin jar into the *plugin* directory.
Keep in mind though that collector and web both have dependencies to plugins and you'll have to do the same for these (we recommend at least keeping collector and web updated to the most recent version).

**Comment by huayaoyue6** [comment]
Also, you have to update resin config what have metioned in resin plugin's README.

**Comment by xulongju** [comment]
Thank you, I will be under test
