### ISSUE TITLE
Transanctions doesn't show up in ( Fewer transactions are shown up ) 

### ISSUE THREAD

**Issue by irocks04** [naver/pinpoint#2775]
All of a sudden i don't see any transactions in any of the agents. I had set up on multiple environments but don't see any of the transactions. 

Question: Is there a restriction on the usage on pinpoint transactions, anything to do with licensing ?

#### Environment

* Pinpoint version: Agent 1.6.0 , Collector 1.6.0 and Web 1.6.0
* Linux
* Additional details (e.g. how your collector/web is set up): Collector and web are set up on different machines

**Comment by Xylus** [comment]
Hi @irocks04 
There is no restriction currently.
Please provide a bit more detail on what you're experiencing (such as the application in which you're running the agent on, the kinds of transactions that are not being traced, etc).
If your agents were working before and nothing's being traced all of a sudden, please tell us what changed (if at all).

**Comment by irocks04** [comment]
Sampling rate was set to 20 and that was the problem. I made it to 1 and it worked fine. Thank you
