### ISSUE TITLE
How to solve the problem of API-METADATA-NOT-FOUND?

### ISSUE THREAD

**Issue by xulongju** [naver/pinpoint#2776]
My steps:
1, hbase to clean up all the table data;
2, open the call stack, it will appear "API-METADATA-NOT-FOUND".
I can not reboot the pinpoint-agent at any time in the production environment.

**Comment by Xylus** [comment]
Hi @xulongju 
Agents send API metadata when they're transformed (usually during application startup when classes are loaded). So if you've deleted everything in hbase (including the ApiMetaData table), you won't have the API metadata available anymore and the web will display *API-METADATA-NOT-FOUND*.

**Comment by xulongju** [comment]
Retain the data in ApiMetaData, delete the other table data, the web will not appear API-METADATA-NOT-FOUND?

**Comment by Xylus** [comment]
That is correct. if you're to manually delete hbase data, I would advise you to keep the meta data tables and delete others first. AgentStat(V2) and Trace(s/V2) tables are usually the safest one to delete.
However, if storage space is an issue, I would instead advise you to adjust the TTL values instead of manually deleting data. Shortening the TTL value for Trace(s/V2) should yield you the most space.

**Comment by jiaqifeng** [comment]
@Xylus 
I also find in some situation that I have to clean the hbase but let some important app with agent keep running. I am considering adding a new command to agent to ask it to resend the agentInfo and apiMetadata. Also add an entry in web to control which agent should receive the command. Is this a good idea? Or any advice?

**Comment by dinesh4747** [comment]
Reference to the recent issue - #6496

@koo-taejin @jaehong-kim @emeroad @Xylus @jefry86 @yanpeng-ali  @minwoo-jung

It looks functional issue where "synchronizing the start time value of agent is not in sync whole it reaches collector server" Can someone please shed some light or definite pointers on how to solve API-METADATA-NOT-FOUND issue which is almost deteriorating my usage of pinpoint in my cloud system and it seems like @jefry86 mentioned very clearly that "the startTime value of metadata is different"

It would be really great and kind if someone could help me address this.
