### ISSUE TITLE
mysql servermap show no png

### ISSUE THREAD

**Issue by liliangfree** [naver/pinpoint#2798]
when i use pp colloct mysql message,but in pp-web,mysql do not show servermap png

hope you help me ,thank youwhen i use pp colloct mysql message,but in pp-web,mysql do not show servermap png

hope you help me ,thank you

**Comment by liliangfree** [comment]
![mysqlissue](https://cloud.githubusercontent.com/assets/5870167/24997421/321cd12c-2069-11e7-8516-9ae62b7fbfef.png)

when i use pp colloct mysql message,but in pp-web,mysql do not show servermap png

hope you help me ,thank you

**Comment by Xylus** [comment]
Hi @liliangfree 
Which mysql driver version are you using? Could it be related to #2013 ?

**Comment by yoyonho** [comment]
have u checked jdbc db name?
ex) jdbc:mysql://127.0.0.1:3306/**testdb**
I think need dbname to show mysql image.
