### ISSUE TITLE
pinpoint-web can not load js 

### ISSUE THREAD

**Issue by wenxin1234114** [naver/pinpoint#2814]
#### Description
I git clone codes from github ,maven compiled the pinpoint war package can work in my Mac laptop .
but I maven compiled in Centos ,the war package can not work ,the webpage see the attachment.
![ppt-error](https://cloud.githubusercontent.com/assets/3120131/25039551/a4b088be-2136-11e7-9447-2c5621181425.png)

#### Environment

* Pinpoint version:1.6.1
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by emeroad** [comment]
Pinpoints can only be deployed in root context.
- This issue is fixed in 1.7.0.

**Comment by emeroad** [comment]
Related Issues : #1249

**Comment by fuhongwei041** [comment]
i have the same error when i use 1.7.0-SNAPSHOT docker deployment.
