### ISSUE TITLE
Why Not Cassandra Instead of Hbase

### ISSUE THREAD

**Issue by jamroks** [naver/pinpoint#284]
Hi ,

 First of all thank you for this wonderfull project . It's been a long time waiting for a solid Open Source APM ( application performance management). i have been a user of New Relic and tested Appdynamics and i can say that Pinpoint is looking really really promising.  So kudos to all the team behind it !!!

 i have a question, it's not really an issue, but i just wanted to know if when designing the architecture, have you ever consider using any other data store solution ( except hbase ) ? if yes,  was Apache Cassandra in the list of contender ?  if yes then  why, what were the reason for choosing hbase instead of Cassandra for exemple was it a  technical issue, can you elaborate and the subject ? performance ? 

Thank you again for all the hard work 

Cheers

**Comment by emeroad** [comment]
Hi. jamroks

There is no technical issues.
Monitoring system was considered more important by Consistency of CAP theory.
HBase is hadoop family, which is advantage in integration with the hadoop subsystem.

**Comment by jamroks** [comment]
Hi,

 Ok i can understand the justification in regard to the CAP principle and Hadoop integration. 

Thanks

**Comment by jamroks** [comment]
The question has been answered. I close this issue
