### ISSUE TITLE
tomcat : Too many open files when install pinpoint ,it use too many linux 's file descriptor 

### ISSUE THREAD

**Issue by magicdogs** [naver/pinpoint#2841]
env:
    
   java version "1.8.0_121"
   Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
   Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

   springboot version : 1.4.0

  pinpoint version : pinpoint-bootstrap-1.6.0-SNAPSHOT

 linux os:
     42~14.04.1-Ubuntu SMP Fri May 13 17:27:22 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

ulimit -a :   open files default value 1024

when i had install pinpoint agent on my application,it work a piece of time, and then output log file had a lot of   'NoClassDefFoundError ' and 'Too many open files '  error , if i unstall pinpoint agent , it 's work fine , i don't know why ,  please help me to slove those problem , thanks a lot .

ERROR] [wedefend-gateway] 2017-04-18 14:44:04.764 [http-nio-8080-Acceptor-0] [] [] [] org.apache.tomcat.util.net.NioEndpoint - Socket accept failed
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:457)
	at java.lang.Thread.run(Thread.java:745)
[DEBUG] [wedefend-gateway] 2017-04-18 14:44:04.795 [DubboServerHandler-192.168.200.127:20880-thread-196] [] [] [] com.alibaba.dubbo.remoting.transport.DecodeHandler -  [DUBBO] Decode decodeable message com.alibaba.dubbo.rpc.protoc

![image](https://cloud.githubusercontent.com/assets/22540413/25169389/6d71a0e0-2519-11e7-97a0-3f407b34ed19.png)

![image](https://cloud.githubusercontent.com/assets/22540413/25169887/34b65b40-251b-11e7-8994-3c5ae71d6277.png)

fd command list info 
lsof -p pid

[2017-04191049.txt](https://github.com/naver/pinpoint/files/932629/2017-04191049.txt)

**Comment by magicdogs** [comment]
![image](https://cloud.githubusercontent.com/assets/22540413/25170047/c09a92fc-251b-11e7-86a8-de98f06f0b34.png)

all NoClassDefFoundError  class has been loaded in springboot

**Comment by jaehong-kim** [comment]
@magicdogs 
This is probably due to SNAPSHOT version.
In normal cases, processing for jar files can be duplicated up to a maximum of two times.
We recommend using version 1.6.1.

**Comment by magicdogs** [comment]
@jaehong-kim  
Thanks for your reply ， we had revise the system file descriptor limits number， and it  work normal , but some problem trouble me , i don' t know why pinpoint use too many file descriptor ,  has it leak file descriptor handle ?

**Comment by atul9911** [comment]
I am also facing the same issue.do anyone able to find any permanent solution??

**Comment by haifzhu** [comment]
We upgrade the pinpoint agent version to 1.7.1, but still the issue be exist.The pinpoint library be loaded for more than 4000 times and system fd be exhausted。

[root@gpcatalog-center-host ~]# lsof -p 17129 | grep pinpoint-dubbo-plugin | wc -l
4116
[root@gpcatalog-center-host ~]# lsof -p 17129 | wc -l
33310

**Comment by byronxie1984** [comment]
I am also facing the same issue. do anyone able to find any permanent solution?

**Comment by haifzhu** [comment]
But the issue still be exist!
