### ISSUE TITLE
JBOSS7 -->jboss-as-web-7.0.2.Final Error ---Help

### ISSUE THREAD

**Issue by clearBird** [naver/pinpoint#2850]
Hi team

 I configuration through the **jboss eap6** as required ，
![qq 20170421175530](https://cloud.githubusercontent.com/assets/25739770/25273002/8887126c-26bc-11e7-9291-7d955a94a4ac.png)
Monitoring the Jboss 7 version error as follows：

message

description The server encountered an internal error () that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: Servlet execution threw an exception
root cause

java.lang.NoClassDefFoundError: com/navercorp/pinpoint/bootstrap/interceptor/InterceptorInvokerHelper
	com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java)
	java.sql.DriverManager.getConnection(DriverManager.java:571)
	java.sql.DriverManager.getConnection(DriverManager.java:215)
	com.fzq.test.App.doGet(App.java:48)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:734)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
root cause

java.lang.ClassNotFoundException: com.navercorp.pinpoint.bootstrap.interceptor.InterceptorInvokerHelper from [Module "deployment.test.war:main" from Service Module Loader]
	org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:191)
	org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:361)
	org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:333)
	org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:310)
	org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:103)
	com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java)
	java.sql.DriverManager.getConnection(DriverManager.java:571)
	java.sql.DriverManager.getConnection(DriverManager.java:215)
	com.fzq.test.App.doGet(App.java:48)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:734)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:847)

**Comment by mabunixda** [comment]
@clearBird  did you configure the -Djboss.modules.system.pkgs=org.jboss.byteman,org.jboss.logmanager,com.navercorp.pinpoint.bootstrap,com.navercorp.pinpoint.common,com.navercorp.pinpoint.exception ?

**Comment by clearBird** [comment]
@mabunixda I configure the jboss according to it。
[https://github.com/naver/pinpoint/tree/master/plugins/jboss](url)

**Comment by clearBird** [comment]
@mabunixda  how is the configure ？-
 Djboss.modules.system.pkgs=org.jboss.byteman,org.jboss.logmanager,com.navercorp.pinpoint.bootstrap,com.navercorp.pinpoint.common,com.navercorp.pinpoint.exception ?

**Comment by mabunixda** [comment]
@clearBird  i thought you were missing those bootclasspath perhapbs because the jvm is not able to load those classes. 

What is your logout output on console? Is the pinpoint agent already logging data to the console? Which eap version are you running? You may hit [this bug](https://issues.jboss.org/browse/WFLY-1432)

**Comment by clearBird** [comment]
@mabunixda
   I am useing pinpoint1.6.1，The jboss version is jboss-eap-6.4.
   For the above problems.My configuration is as follows

**a)standalone.bat**
set "JAVA_OPTS=%JAVA_OPTS% -Djboss.modules.system.pkgs=org.jboss.byteman,org.jboss.logmanager -Djava.util.logging.manager=org.jboss.logmanager.LogManager 
-Xbootclasspath/p:F:\pp\Jboss\jboss-eap-6.4\modules\system\layers\base\org\jboss\logmanager\main\jboss-logmanager-1.5.4.Final-redhat-1.jar -Xbootclasspath/p:F:\pp\Jboss\jboss-eap-6.4\modules\system\layers\base\org\jboss\log4j\logmanager\main\log4j-jboss-logmanager-1.1.1.Final-redhat-1.jar
 -javaagent:F:\pp\pinpoint-agent-1.6.1\pinpoint-bootstrap-1.6.1.jar
 -Dpinpoint.agentId=pp161Jboss64 -Dpinpoint.applicationName=pp161Jboss64"

**b)domain.xml**
![ppe](https://cloud.githubusercontent.com/assets/25739770/25378897/ecae24e6-29dd-11e7-9354-fade449a2eb0.png)

**c)host.xml**
![pph](https://cloud.githubusercontent.com/assets/25739770/25378953/0a6e9fa6-29de-11e7-972a-0a3ceeac79af.png)
**d)pinpoint.config**
    profiler.instrument.engine=JAVASSIST
    profiler.applicationservertype=JBOSS

But，the question remains.Help me！

**Comment by clearBird** [comment]
supplement：
pinpoint.config：-->profiler.jboss.traceEjb=true

**Comment by clearBird** [comment]
@jaehong-kim  I have configured, but problems still exist！These information are configured in _standalone.bat_.

**Comment by felipepmdias** [comment]
@clearBird Did you solve this problem? I'm facing the same mistake
