### ISSUE TITLE
Tomcat version problem, unable to collect data to submit to the controller

### ISSUE THREAD

**Issue by swq499809608** [naver/pinpoint#2851]
Tomcat version problem, unable to collect data to submit to the controller
#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):
tomcat: version_7.0.65 
jdk: jdk1.7.0_80
pinpoint-agent: 1.6.1
pp-controller : 1.6.1
pp-web :1.6.1

#### Additional Info

Tomcat version problem, unable to collect data to submit to the controller

**Comment by kanhai001** [comment]
See if you are using the spring boot, if you use the reference # 2897
