### ISSUE TITLE
Pinpoint1.6.1 can't get jboss eap 6.4 data.

### ISSUE THREAD

**Issue by clearBird** [naver/pinpoint#2865]
hi team!
I am useing Pinpoint1.6.1.
I deployed  agent to jboss eap 6.4, start jboss, but I can't get jboss data.
![1](https://cloud.githubusercontent.com/assets/25739770/25463764/12758c84-2b2b-11e7-98fb-aa26c4890693.png)

**Comment by jonpri** [comment]
I have the same problem, the agent chargefully exist but I do not see data.
Java 1.7 for the agent and web app.

**Comment by clearBird** [comment]
@emeroad Can you help me? About this issue.

**Comment by emeroad** [comment]
@clearBird
Sorry. Pinpoint team have a high priority #2862 issue. 
The answer will be delayed.

**Comment by clearBird** [comment]
@emeroad  So，Pinpoint can't get jboss data at present, Isn't it?

**Comment by jonpri** [comment]
@clearBird  

You can share your configuration of the installation and the versions of java used.  
After running a test on a service in the agent node, nothing is displayed on the dashboard.


![dashboard](https://cloud.githubusercontent.com/assets/6160914/25484322/e63a567c-2b2f-11e7-965f-6fd4a6d48b26.JPG)

[vbox_eap01-pinpoint.zip](https://github.com/naver/pinpoint/files/961623/vbox_eap01-pinpoint.zip)

Best Regards,
JP

**Comment by clearBird** [comment]
My jdk versions is jdk1.7.0_71，jboss versions  jboss eap 6.4 .

**Comment by jonpri** [comment]
@clearBird Tranks. 
I have the same configuration only as for linux.
You share the configuration file of the agent, to look for possible differences.
I attach my configuration, in case you have time to look at it.  [pinpoint.config.zip](https://github.com/naver/pinpoint/files/970531/pinpoint.config.zip)
[standalone.conf.zip](https://github.com/naver/pinpoint/files/970538/standalone.conf.zip)

**Comment by clearBird** [comment]
@jonpri 
You can try it：

![54](https://cloud.githubusercontent.com/assets/25739770/25688990/4530e070-30b6-11e7-88bd-d6b5d6b649e0.jpg)
![547](https://cloud.githubusercontent.com/assets/25739770/25688995/4e545dd0-30b6-11e7-9b12-5e09a7b25d5b.jpg)
