### ISSUE TITLE
how to display memcache

### ISSUE THREAD

**Issue by xsbry** [naver/pinpoint#2868]
Hi,
    My application has memcache,but the server map don't display. Why?

**Comment by emeroad** [comment]
Read the Contribution Guide.

**Comment by wqtty** [comment]
@xsbry 
Did you find an answer for this? I'm having the same problem right now

**Comment by jaehong-kim** [comment]
@wqtty 
Pinpoint supports only spymemcached client.

**Comment by wqtty** [comment]
@jaehong-kim 
thanks
