### ISSUE TITLE
Issue in configuring tomat

### ISSUE THREAD

**Issue by KamathamHemadri** [naver/pinpoint#2869]
Hi,

I configured Tomcat sever by following the steps in present in above URL,now when i start the tomcat server it is picking the collector and web war files,now i don't know how to start the web and collector to see the requests,i checked in web folder present in pinpoint but there is no .cmd file,How to start Web and collector to see the java application requests.

Thanks.

**Comment by YouriAndropov** [comment]
Have you renamed the pinpoint-web.war file as ROOT.war ?
Start tomcat, then you can access pinpoint URL on http://<hostname>:8080/

**Comment by Xylus** [comment]
Hi @KamathamHemadri 
The *.cmd files you're looking for are probably for quickstart.
If you're deploying your own instances of collector and web to Tomcat, you do not need to run the *.cmd files.

So to start your collector/web, simply start Tomcat with collector/web war files deployed on them as @YouriAndropov said.

Please check the [installation guide](https://github.com/naver/pinpoint/blob/master/doc/installation.md) for more details, and let me know if you need anything clarified.
Thanks!
