### ISSUE TITLE
can I config item of profiler.collector.ip in env or configcenter without change the codes of agent

### ISSUE THREAD

**Issue by aximo** [naver/pinpoint#2895]
can I config item of profiler.collector.ip in env or configcenter without change the codes of agent?

**Comment by koo-taejin** [comment]
Hi aximo 

I don't know exactly what you mean by env or configcenter.
I can give you a better answer if you tell me a more about it.

Obviously, The only way to do this is to set it in the pinpoint.config file.

thanks

**Comment by aximo** [comment]
i deliver our application with embed pinpoint agent, when some users use my application, them must modify the pinpoint.config to re-config the ip. it is not friendly to application user.

so i want to pinpoint agent to read configs from envionment variables and pinpoint.config, and, the envionment variables will override the config item in pinpoint.config.

general, pinpoint agent can read configs from an url, so, we can maintain the configs in center place, which means configcenter.
