### ISSUE TITLE
From 1.5.2 upgrade to 1.6.1 no trace data！

### ISSUE THREAD

**Issue by kanhai001** [naver/pinpoint#2897]
hi team!
From 1.5.2 upgrade to 1.6.1, collector can not receive agent is 1.6.1 version of the trace data, can only receive agentinfo and jvm information data, agent is 1.5.2 version can be collected, what is this the reason?
#### Environment
jdk：1.7.0_79
system:linux 
springboot: spring boot 1.3.2
pinpoint: agent 1.6.1  ,collector 1.6.1  ,web 1.6.1
hbase:1.0.3

**Comment by kanhai001** [comment]
Find the reason, modify the agent pinpoint.config configuration profiler.tomcat.conditional.transform = false

# or SpringBoot's launchers.
# Set this to false to bypass this check entirely (such as when launching standalone applications running embedded Tomcat).

**Comment by wanghy8166** [comment]
mark
