### ISSUE TITLE
Answer：pinpoint 1.6.0 configure jboss eap 6

### ISSUE THREAD

**Issue by clearBird** [naver/pinpoint#2898]
I tried a number of times according to the configuration by the pinpoint team，them all failed.
but，I'm using a simple configuration，it is vary successful，thanks to my colleagues，they are vary good。

Configuration is as follows：My system win7

Configure file:**standalone.conf.bat** ,Only it.

![success](https://cloud.githubusercontent.com/assets/25739770/25689659/e8de7588-30bc-11e7-9adb-98730a997848.jpg)

set "JAVA_OPTS=%JAVA_OPTS% -Djboss.modules.system.pkgs=org.jboss.byteman,org.jboss.logmanager,com.navercorp.pinpoint.bootstrap,com.navercorp.pinpoint.common,com.navercorp.pinpoint.exception"
set "JAVA_OPTS=%JAVA_OPTS% -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
set "JAVA_OPTS=%JAVA_OPTS% -Xbootclasspath/p:F:\UAPM_2017\Jboss\jboss-eap-6.2\modules\system\layers\base\org\jboss\logmanager\main\jboss-logmanager-1.5.1.Final-redhat-1.jar"
set "JAVA_OPTS=%JAVA_OPTS% -javaagent:F:\UAPM_2017\uapmAgent\uapmAgent.jar"
set "JAVA_OPTS=%JAVA_OPTS% -Dpinpoint.applicationName=Jboss62_160" 
set "JAVA_OPTS=%JAVA_OPTS% -Dpinpoint.agentId=Jboss62_160"

**Comment by Xylus** [comment]
Hi @clearBird
Thanks for sharing a solution.
Is this different from the guide in jboss plugin README - https://github.com/naver/pinpoint/tree/master/plugins/jboss#standalone-mode-?
Or is it that *standalone.conf.bat* file should be configured in a Windows environment?

Either way, please feel free to update the README to include your solution.
Thanks!
