### ISSUE TITLE
nginx support

### ISSUE THREAD

**Issue by mabunixda** [naver/pinpoint#2899]
Hi,

did anybody already try to inject nginx an pinpoint agent implementation ? 
We would like to get also the reverse proxies into the metrics of pinpoint. We thought it might be possible using lua .

TIA

**Comment by devpage** [comment]
it seems interesting

**Comment by mabunixda** [comment]
Is there any documentation available about the data flow? 
I want to get into that topic to create a lua implementation for this ..

**Comment by jiaqifeng** [comment]
I have an advice. Maybe it is no need to code in  nginx side. You can add a special http header to record the nginx information such as ip and time to the upstream java application, and let java application to record the nginx info to collector which could add an virtual nginx node just like what message queue virtual node was added.

**Comment by mabunixda** [comment]
Ok - which headers would that be?

**Comment by mabunixda** [comment]
implemented in #3252 now ...
