### ISSUE TITLE
How to integrate websphere application server to pinpoint,Did pinpoint supports websphere and weblogic? 

### ISSUE THREAD

**Issue by KamathamHemadri** [naver/pinpoint#2901]
Hi,

How to integrate a websphere to pinpoint.
Did Pinpoint supports websphere and weblogic?

Thanks

**Comment by happycharlie** [comment]
I would like to know that as well...
Thanks a lot...

**Comment by ZhanChaoHan** [comment]
I would like to know that as well...
Thanks a lot...
