### ISSUE TITLE
Application not displaying on Web UI

### ISSUE THREAD

**Issue by tamaldey** [naver/pinpoint#2902]
Hello - 

I am new to pinpoint and currently facing problems setting it up. Here is the description of the problem and request help. This is a local set up on my machine and my application is written in Grails Framework (that is Groovy, Spring) based.

1. I have one tomcat instance that has my application deployed running on 9090. It also has the following pointed correctly.
    export CATALINA_OPTS="$CATALINA_OPTS -javaagent:$AGENT_PATH/pinpoint-agent-1.6.1/pinpoint-bootstrap-1.6.1.jar"
export CATALINA_OPTS="$CATALINA_OPTS -Dpinpoint.agentId=$AGENT_ID"
export CATALINA_OPTS="$CATALINA_OPTS -Dpinpoint.applicationName=$APPLICATION_NAME"

Assume all variables above have been replaced correctly. The above lines are inside the tomcat's catalina.sh

2. I have another instance of tomcat running on port 8080 where the following are deployed.
    pinpoint-collector-1.6.1.war
    pinpoint-web-1.6.1.war
   
   when I start this tomcat instance and go to http://localhost:8080/pinpoint-web-1.6.1
   It complains about the following:

   1. looks for icons and images folder directly under http://localhost:8080
   2. looks for the following : GET http://localhost:8080/applications.pinpoint 404 (Not Found)
 
3. I have installed Hbase in a standalone mode on the same local machine and as per documentation 
    (http://hbase.apache.org/book.html#quickstart)
    I do a bin/start-hbase.sh and then browse to http://localhost:16010

Please let me know how to view my application  in pinpoint that is deployed in Tomcat (step 1). 
The 'Select an application' drop down does not list my application.
I think I am missing something, will appreciate some help and pointer to documentation.

**Comment by Xylus** [comment]
Hi @tamaldey 
Pinpoint web needs to be deployed to ROOT context (approachable from `http://localhost:8080`) - https://github.com/naver/pinpoint/blob/master/doc/installation.md#installation-2
This requirement will no longer be necessary in the next release.
