### ISSUE TITLE
real time 1m marker causing issues when viewing transactions...needs to be reverted to 5m

### ISSUE THREAD

**Issue by teambullseye** [naver/pinpoint#2907]
#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by denzelsN** [comment]
@teambullseye 
Hi~
Sorry. I can't understand your issue.
Please explain more detail.
What is 1m marker?

**Comment by teambullseye** [comment]
Pinpoint version: 1.6.0
when realtime is selected and drag mouse over the scatter chart, call stack is not retrieved, getting popup with message 'Scatter data of parent window had been changed'

**Comment by denzelsN** [comment]
@teambullseye 
I can not reproduce your issue.
Do you know your OS, Browser version?

**Comment by teambullseye** [comment]
this is on Chrome Version 57.0.2987.133 (64-bit)......resetting the web/src/main/webapp/common/services/url-vo.service.js to 5m as adjusted numbers corrects the issue  

readablePeriod = "5m";
minutePeriod = 1;		 +				 minutePeriod = 5;
millisecondPeriod = 1 * 60 * 1000;		 +				 millisecondPeriod = 5 * 60 * 1000;

**Comment by denzelsN** [comment]
@teambullseye 
https://github.com/naver/pinpoint/commit/c2af632bca887560c66c6c54df427dd4605c5f5a
