### ISSUE TITLE
Question regarding the total request time, gap, and time.

### ISSUE THREAD

**Issue by ha02148** [naver/pinpoint#293]
Hi,

I'm looking at some of our requests and the method times do not add up.

See the following example.  The request time is 867.  The total of the gap and time is 864.  There is a difference of 3 ms.  

Thanks

![time](https://cloud.githubusercontent.com/assets/5472821/6965595/cb913290-d920-11e4-9b5b-057049f68aba.png)

**Comment by minwoo-jung** [comment]
답변하시는분 없으시면 제가 답변 할께요~
 
정민우 드림 
 
-----Original Message-----

**Comment by minwoo-jung** [comment]
Wow, you’ve really examined the figures in detail.^^

One possible explanation would be that another operation may have executed after the last method(executeMethod(HttpMethod method)).
ex) response message was processed or analyzed by http call. 

I’ll take a look at the calculation logic again just in case.
