### ISSUE TITLE
the log button is not work

### ISSUE THREAD

**Issue by aximo** [naver/pinpoint#2938]
i know there is a document [https://github.com/naver/pinpoint/blob/master/doc/per-request_feature_guide.md](https://github.com/naver/pinpoint/blob/master/doc/per-request_feature_guide.md), however,i follow the steps:
1. change the pinpoint.config
```
profiler.log4j.logging.transactioninfo=false
profiler.logback.logging.transactioninfo=true
```
2. enable the log in web config file 
```
log.enable=true
log.page.url=http://172.25.17.74:7070/logcenter/logs
log.button.name=logs
```

restart all applications, the result is:
the logs show the txid and span id
[TxId : sh-test-vender-service^1495182270744^7 , SpanId : -4785742948436261228]

but in the web, the log button is disabled
![image](https://cloud.githubusercontent.com/assets/5916314/26241075/fe7c1d0a-3cb5-11e7-9abd-9d1c294e56a4.png)

when i check the logs button, show this dialog:
![image](https://cloud.githubusercontent.com/assets/5916314/26241114/1b159018-3cb6-11e7-9063-9eb637318106.png)

i also see the transactionInfo.pinpoint api response:

![image](https://cloud.githubusercontent.com/assets/5916314/26241184/5b94a9e4-3cb6-11e7-970b-7e5abf980d4e.png)

so,is there any wrong?

**Comment by aximo** [comment]
i check the pinpoint codes, i found the method 
 named com.navercorp.pinpoint.profiler.context.recorder.DefaultSpanRecorder.recordLogging(LoggingInfo)  in https://github.com/naver/pinpoint/blob/60d6311a78b4f44c81c2ffc38f923ad9241b4faa/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/recorder/DefaultSpanRecorder.java  is not called in any other codes, so span.loggingTransactionInfo will always 0

**Comment by dayforward** [comment]
in the minwoo-jung' opinion, we should impletation the  AppenderInterceptor to enable perquest logging function.  the sample is below :

**Comment by dayforward** [comment]
in the opinion , we should implete the  AppenderInterceptor  like this  `public class AppenderInterceptor implements AroundInterceptor0 {

    private final TraceContext traceContext;

    public AppenderInterceptor(TraceContext traceContext) {
        this.traceContext = traceContext;
    }

    @Override
    public void before(Object target) {
        Trace trace = traceContext.currentTraceObject();

        if (trace != null) {
            SpanRecorder recorder = trace.getSpanRecorder();
            recorder.recordLogging(LoggingInfo.LOGGED);
        }
    }

    @IgnoreMethod
    @Override
    public void after(Object target, Object result, Throwable throwable) {

    }
}`   ,  and now we are going the implete per-request logging in a few days. the location is at  https://github.com/dayforward/pinpoint  welcome to receive advice from you!

**Comment by dayforward** [comment]
in  minwoo-jung' opinion , we should implete the AppenderInterceptor like this `public class AppenderInterceptor implements AroundInterceptor0 {

private final TraceContext traceContext;

public AppenderInterceptor(TraceContext traceContext) {
    this.traceContext = traceContext;
}

@Override
public void before(Object target) {
    Trace trace = traceContext.currentTraceObject();

    if (trace != null) {
        SpanRecorder recorder = trace.getSpanRecorder();
        recorder.recordLogging(LoggingInfo.LOGGED);
    }
}

@IgnoreMethod
@Override
public void after(Object target, Object result, Throwable throwable) {

}
}` , the link is https://github.com/naver/pinpoint/blob/e1ae68ac59d1818b447fdc892328e4f9aa3f32d3/doc/per-request_feature_guide.md and now we are going the implete per-request logging in a few days. the location is at https://github.com/dayforward/pinpoint welcome to receive advice from you!
