### ISSUE TITLE
Mixed view hangs with Firefox

### ISSUE THREAD

**Issue by ha02148** [naver/pinpoint#294]
Hi,

I'm using FF 36.0.4 and when I open the mixed view for a transaction, it hangs.

Thanks

![ff](https://cloud.githubusercontent.com/assets/5472821/6965769/ef1a8062-d921-11e4-9d11-38cb72902ccb.png)

**Comment by minwoo-jung** [comment]
We are mainly supporting chrome currently but we're looking to support other browsers as much as possible.
In the mean time, could you use chrome?
Thanks.

**Comment by ha02148** [comment]
Yes, I'm using Chrome and it is much faster than FF.  I did not find other issue with FF except this.

Thanks.
