### ISSUE TITLE
Djboss.modules.system.pkgs question

### ISSUE THREAD

**Issue by Eilikce** [naver/pinpoint#2954]
Why do we have to add the "Djboss.modules.system.pkgs" params to find the 3 jars when using Jboss ? 
Why it is not necessary in Tomcat ?

Is there any difference between Tomcat and Jboss ?

JAVA_OPTS="$JAVA_OPTS -Djboss.modules.system.pkgs=com.navercorp.pinpoint.bootstrap,
com.navercorp.pinpoint.common,com.navercorp.pinpoint.exception"

**Comment by emeroad** [comment]
Jboss and Tomcat are different implementation.
We do not know about Jboss internal implementation. 
Ask the jboss community.
