### ISSUE TITLE
How do I view thread stacks?

### ISSUE THREAD

**Issue by whscfan** [naver/pinpoint#2960]
Can you provide a way to view thread stacks?By default, there is no entry on the page.How do you configure these?Looking at the official website and github project, I didn't find the explanation (I probably didn't find it myself).Can you provide help or documentation for this?

**Comment by Xylus** [comment]
Hi @whscfan 
https://github.com/naver/pinpoint/wiki/FAQ#how-do-i-get-to-the-call-stack-view

**Comment by wadeLouis** [comment]
Thanks
