### ISSUE TITLE
Realtime Active Thread Chart 출력을 위한 방화벽 오픈 포트 확인

### ISSUE THREAD

**Issue by gogomasaru** [naver/pinpoint#2967]
JDK : 1.7.0.72
tomcat : 6.0.45
Quick start 가동

같은 pinpoint를 방화벽 있는 환경와 방화벽 없는 환경에서 접속 시 각각 아래 처럼 
Realtime Active Thread Chart가 정상 출력되거나 Closed connection이 나옵니다.

어떤 포트를 방화벽오픈해야 되는지 가이드 부탁드립니다.

![default](https://cloud.githubusercontent.com/assets/26616377/26540182/1497bc20-448b-11e7-9dc8-d49817c0ffa9.JPG)
![connect timeout](https://cloud.githubusercontent.com/assets/26616377/26540184/15e5aa4c-448b-11e7-9d3f-1ebda5a5e7b9.JPG)

이전에 가이드 해주신대로 오픈한 방화벽 입니다.
![image](https://cloud.githubusercontent.com/assets/26616377/26540282/921f1eea-448b-11e7-8308-9ee7caefa61e.png)

추가 collector / WEB 서버 별도일시 29997 오픈

**Comment by koo-taejin** [comment]
제가 알고 있는 port들은 다 언급이 되어 있는 것 같습니다. 

그렇지만 oollector / web 같은 경우 같은 장비라도 os나 ip 설정에 따라 외부로 나왔닥 들어오는 경우가 있어 
같은 장비에 있다고 하더라도 방화벽을 오픈하는 것이 좋을 것 같습니다. 

추가로, 1.7.0 부터 quickstart의 port를 29994 -> 9994, 29995 -> 9995, 29996 -> 9996, 29997 -> 9997 로 변경하였습니다.
