### ISSUE TITLE
알람 기능 설정중 질문합니다~

### ISSUE THREAD

**Issue by yunjaewon** [naver/pinpoint#2976]
* Pinpoint version:  1.5.2
* OS, WAS, affected library, etc:  JVM(1.8.0_74 (PARALLEL)) , WAS(TOMCAT  (Apache Tomcat/8.0.39) )

안녕하세요~ pinpoint를 매우 요긴하게 잘 사용하고 있는 개발자입니다

이번에 핀포인트를 이용하여 알람기능을 추가하려고 하는데, 
알람에 대한 설명서대로 
AlarmMessageSender 구현 및 bean 등록
batch properties 설정
MYSQL 서버 IP 주소 설정 & table 생성을 
마치고 알람에 대한 등록을 해보니 db에 쌓이지가 않고, 다른 화면을 이동했다가 다시오면
캐쉬에도 남아있지않는 것 같더라구요.

혹시 알람설정을 하려고하면 따로 db에 들어가는 로직을 직접 구현해야하는지,
아니면 제가 무언가 빠트린 부분이 있는지 궁금해서 글 올려봅니다!

**Comment by minwoo-jung** [comment]
알람 설정값을 DB하는 로직은 이미 구현이 되어있습니다.
MysqlAlarmDao가 제대로 동작이 되는지 디버깅을 해보는게 좋을 것 같습니다. 
혹시 UI나 서버에 문제가 될만한 로그가 남는다면 첨부해주세요.

참고로 quickstart를 사용하실 경우 MysqlAlarmDao는 bean으로 등록되지 않습니다.
