### ISSUE TITLE
 pinpoint-annotations  Compilation failure

### ISSUE THREAD

**Issue by ExtremeYu** [naver/pinpoint#2980]
on windows10 jdk 1.8 maven 3.3.9 pp 1.7.0 or 1.6.1 ,wether idea eclipse or cmd,  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project pinpoint-annotations: Compilation failure

![Uploading I4Z_1TEJXKHT{AJ_X(N)ZI6.png…]()
![Uploading }~_U{(T`1XBUQ)_W17N`PFL.png…]()

**Comment by ExtremeYu** [comment]
"C:\Program Files\Java\jdk1.8.0_102\bin\java" -Dmaven.multiModuleProjectDirectory=C:\Users\windo\Desktop\pinpoint-1.6.1 "-Dmaven.home=C:\Program Files\apache-maven-3.3.9-bin\apache-maven-3.3.9" "-Dclassworlds.conf=C:\Program Files\apache-maven-3.3.9-bin\apache-maven-3.3.9\bin\m2.conf" -Didea.launcher.port=7536 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.3\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\apache-maven-3.3.9-bin\apache-maven-3.3.9\boot\plexus-classworlds-2.5.2.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.3\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain org.codehaus.classworlds.Launcher -Didea.version=2016.3 -Dmaven.repo.local=K:\MAVEN_LOCAL_REP install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] pinpoint
[INFO] pinpoint-annotations
[INFO] pinpoint-thrift
[INFO] pinpoint-commons
[INFO] pinpoint-bootstrap-core
[INFO] pinpoint-bootstrap
[INFO] pinpoint-rpc
[INFO] pinpoint-profiler
[INFO] pinpoint-commons-hbase
[INFO] pinpoint-commons-server
[INFO] pinpoint-profiler-test
[INFO] pinpoint-profiler-optional-parent
[INFO] pinpoint-profiler-optional-jdk6
[INFO] pinpoint-profiler-optional-jdk7
[INFO] pinpoint-profiler-optional
[INFO] pinpoint-httpclient3-plugin
[INFO] pinpoint-httpclient4-plugin
[INFO] pinpoint-ning-asynchttpclient-plugin
[INFO] pinpoint-gson-plugin
[INFO] pinpoint-cubrid-jdbc-driver-plugin
[INFO] pinpoint-mysql-jdbc-driver-plugin
[INFO] pinpoint-mariadb-jdbc-driver-plugin
[INFO] pinpoint-postgresql-jdbc-driver-plugin
[INFO] pinpoint-jtds-plugin
[INFO] pinpoint-oracle-jdbc-driver-plugin
[INFO] pinpoint-commons-dbcp-plugin
[INFO] pinpoint-commons-dbcp2-plugin
[INFO] pinpoint-hikaricp-plugin
[INFO] pinpoint-test
[INFO] pinpoint-cassandra-driver-plugin
[INFO] pinpoint-jdk-http-plugin
[INFO] pinpoint-redis-plugin
[INFO] pinpoint-tomcat-plugin
[INFO] pinpoint-json-lib-plugin
[INFO] pinpoint-jackson-plugin
[INFO] pinpoint-thrift-plugin
[INFO] pinpoint-user-plugin
[INFO] pinpoint-arcus-plugin
[INFO] pinpoint-google-httpclient-plugin
[INFO] pinpoint-jetty-plugin
[INFO] pinpoint-spring-plugin
[INFO] pinpoint-spring-boot-plugin
[INFO] pinpoint-ibatis-plugin
[INFO] pinpoint-mybatis-plugin
[INFO] pinpoint-okhttp-plugin
[INFO] pinpoint-log4j-plugin
[INFO] pinpoint-logback-plugin
[INFO] pinpoint-dubbo-plugin
[INFO] pinpoint-activemq-client-plugin
[INFO] pinpoint-cxf-plugin
[INFO] pinpoint-hystrix-plugin
[INFO] pinpoint-jboss-plugin
[INFO] pinpoint-vertx-plugin
[INFO] pinpoint-resin-plugin
[INFO] pinpoint-plugins
[INFO] pinpoint-bootstrap-core-optional
[INFO] pinpoint-tools
[INFO] pinpoint-agent-distribution
[INFO] pinpoint-collector
[INFO] pinpoint-profiler-optional-jdk8
[INFO] pinpoint-web
[INFO] pinpoint-hbase-distribution
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building pinpoint 1.6.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-pinpoint-build-requirements) @ pinpoint ---
[WARNING] Rule 2: org.apache.maven.plugins.enforcer.RequireEnvironmentVariable failed with message:
Environment variable "JAVA_6_HOME" is required for this build.
[WARNING] Rule 3: org.apache.maven.plugins.enforcer.RequireEnvironmentVariable failed with message:
Environment variable "JAVA_7_HOME" is required for this build.
[WARNING] Rule 4: org.apache.maven.plugins.enforcer.RequireEnvironmentVariable failed with message:
Environment variable "JAVA_8_HOME" is required for this build.
[INFO] 
[INFO] --- animal-sniffer-maven-plugin:1.15:check (ensure-java-1.6-class-library) @ pinpoint ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.0
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ pinpoint ---
[INFO] Installing C:\Users\windo\Desktop\pinpoint-1.6.1\pom.xml to K:\MAVEN_LOCAL_REP\com\navercorp\pinpoint\pinpoint\1.6.1\pinpoint-1.6.1.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building pinpoint-annotations 1.6.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-pinpoint-build-requirements) @ pinpoint-annotations ---
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ pinpoint-annotations ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] skip non existing resourceDirectory C:\Users\windo\Desktop\pinpoint-1.6.1\annotations\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ pinpoint-annotations ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to C:\Users\windo\Desktop\pinpoint-1.6.1\annotations\target\classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] pinpoint ........................................... SUCCESS [  1.164 s]
[INFO] pinpoint-annotations ............................... FAILURE [  0.777 s]
[INFO] pinpoint-thrift .................................... SKIPPED
[INFO] pinpoint-commons ................................... SKIPPED
[INFO] pinpoint-bootstrap-core ............................ SKIPPED
[INFO] pinpoint-bootstrap ................................. SKIPPED
[INFO] pinpoint-rpc ....................................... SKIPPED
[INFO] pinpoint-profiler .................................. SKIPPED
[INFO] pinpoint-commons-hbase ............................. SKIPPED
[INFO] pinpoint-commons-server ............................ SKIPPED
[INFO] pinpoint-profiler-test ............................. SKIPPED
[INFO] pinpoint-profiler-optional-parent .................. SKIPPED
[INFO] pinpoint-profiler-optional-jdk6 .................... SKIPPED
[INFO] pinpoint-profiler-optional-jdk7 .................... SKIPPED
[INFO] pinpoint-profiler-optional ......................... SKIPPED
[INFO] pinpoint-httpclient3-plugin ........................ SKIPPED
[INFO] pinpoint-httpclient4-plugin ........................ SKIPPED
[INFO] pinpoint-ning-asynchttpclient-plugin ............... SKIPPED
[INFO] pinpoint-gson-plugin ............................... SKIPPED
[INFO] pinpoint-cubrid-jdbc-driver-plugin ................. SKIPPED
[INFO] pinpoint-mysql-jdbc-driver-plugin .................. SKIPPED
[INFO] pinpoint-mariadb-jdbc-driver-plugin ................ SKIPPED
[INFO] pinpoint-postgresql-jdbc-driver-plugin ............. SKIPPED
[INFO] pinpoint-jtds-plugin ............................... SKIPPED
[INFO] pinpoint-oracle-jdbc-driver-plugin ................. SKIPPED
[INFO] pinpoint-commons-dbcp-plugin ....................... SKIPPED
[INFO] pinpoint-commons-dbcp2-plugin ...................... SKIPPED
[INFO] pinpoint-hikaricp-plugin ........................... SKIPPED
[INFO] pinpoint-test ...................................... SKIPPED
[INFO] pinpoint-cassandra-driver-plugin ................... SKIPPED
[INFO] pinpoint-jdk-http-plugin ........................... SKIPPED
[INFO] pinpoint-redis-plugin .............................. SKIPPED
[INFO] pinpoint-tomcat-plugin ............................. SKIPPED
[INFO] pinpoint-json-lib-plugin ........................... SKIPPED
[INFO] pinpoint-jackson-plugin ............................ SKIPPED
[INFO] pinpoint-thrift-plugin ............................. SKIPPED
[INFO] pinpoint-user-plugin ............................... SKIPPED
[INFO] pinpoint-arcus-plugin .............................. SKIPPED
[INFO] pinpoint-google-httpclient-plugin .................. SKIPPED
[INFO] pinpoint-jetty-plugin .............................. SKIPPED
[INFO] pinpoint-spring-plugin ............................. SKIPPED
[INFO] pinpoint-spring-boot-plugin ........................ SKIPPED
[INFO] pinpoint-ibatis-plugin ............................. SKIPPED
[INFO] pinpoint-mybatis-plugin ............................ SKIPPED
[INFO] pinpoint-okhttp-plugin ............................. SKIPPED
[INFO] pinpoint-log4j-plugin .............................. SKIPPED
[INFO] pinpoint-logback-plugin ............................ SKIPPED
[INFO] pinpoint-dubbo-plugin .............................. SKIPPED
[INFO] pinpoint-activemq-client-plugin .................... SKIPPED
[INFO] pinpoint-cxf-plugin ................................ SKIPPED
[INFO] pinpoint-hystrix-plugin ............................ SKIPPED
[INFO] pinpoint-jboss-plugin .............................. SKIPPED
[INFO] pinpoint-vertx-plugin .............................. SKIPPED
[INFO] pinpoint-resin-plugin .............................. SKIPPED
[INFO] pinpoint-plugins ................................... SKIPPED
[INFO] pinpoint-bootstrap-core-optional ................... SKIPPED
[INFO] pinpoint-tools ..................................... SKIPPED
[INFO] pinpoint-agent-distribution ........................ SKIPPED
[INFO] pinpoint-collector ................................. SKIPPED
[INFO] pinpoint-profiler-optional-jdk8 .................... SKIPPED
[INFO] pinpoint-web ....................................... SKIPPED
[INFO] pinpoint-hbase-distribution ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.840 s
[INFO] Finished at: 2017-06-01T10:10:28+08:00
[INFO] Final Memory: 31M/342M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project pinpoint-annotations: Compilation failure -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pinpoint-annotations

Process finished with exit code 1

**Comment by emeroad** [comment]
Read the installation guide 
https://github.com/naver/pinpoint/blob/master/doc/installation.md
