### ISSUE TITLE
web ui show only one application and no arrow

### ISSUE THREAD

**Issue by snecker** [naver/pinpoint#2986]
I deploy the pinpoint with docker successfully.
then I add JVM options to a simple springboot demo and run it.
when I open pp-web and choice the application I just run,it shows only one node and nothing else

# environment
- OS: win7
- pinpoint:1.6.1
- SpringBoot:1.5.2

# JVM Options
```
-javaagent:E:\pinpoint-agent-1.6.1\pinpoint-bootstrap-1.6.1.jar -Dpinpoint.applicationName=testrest -Dpinpoint.agentId=testrest
```

# Demo
```java
public class TestRestJava {
	public static void main(String[] args) throws InterruptedException {
		RestTemplate restTemplate = new RestTemplate();

		while (true){
			Object obj =restTemplate.postForEntity("http://www.baidu.com",null,String.class);
			Thread.sleep(2000L);
		}
	}
}
```

# UI 
![image](https://cloud.githubusercontent.com/assets/4178594/26707130/0f454d72-4775-11e7-937f-eea35d427ed0.png)

# agent Log

[testrest-pinpoint.log.txt](https://github.com/naver/pinpoint/files/1046443/testrest-pinpoint.log.txt)

# collector Log

[pinpoint-collector.log.txt](https://github.com/naver/pinpoint/files/1046452/pinpoint-collector.log.txt)

am I missing something?

**Comment by Xylus** [comment]
Hi @snecker 
No trace is showing as there is no entry point to the application. A trace is initiated by a user request usually by WAS containers (or invocations of user-specified methods).
Since you're simply looping a HTTP call, there is nothing that will trigger a new trace.
