### ISSUE TITLE
Can input any character in period selector input control

### ISSUE THREAD

**Issue by superzhu** [naver/pinpoint#2995]
#### Description

One can input any character in period selector input control

#### Environment

* Pinpoint version: V1.6.0 or V1.6.1
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up): please see attached snapshot
![pinpointp](https://cloud.githubusercontent.com/assets/6111230/26714541/7742a832-47a4-11e7-9461-5ac8fe71aeea.png)

**Comment by Dark0096** [comment]
+1 
1.1.2 entering a number reflected that portion.
However, 1.6.1 is not reflected.

**Comment by denzelsN** [comment]
Sorry, Input is readonly.
You can enter the date only through the calendar. ( Timezone can change in configuration )
I will add readonly attribute.
