### ISSUE TITLE
Agent Connectivity issue using ELB for collector

### ISSUE THREAD

**Issue by sarakavi** [naver/pinpoint#3006]
#### Description
 We ran into an issue with agents connecting via collector ELB  , found out that agents having a persistent connection to a ELB IP (collector ) . If the ELB IP changes for any reasons  the agent does not automatically connect to the new ELB IP unless we restart the agent . In the pinpoint.config, Alias name for the ELB used and NOT the IP address

#### Environment

* Pinpoint version:1.6.0
* Amazon Linux-4.9.27-14.31., 
* Additional details two web ec2 behind a ALB, 2 collector EC2 on behind a ELB:

#### Question 
We cannot restart the agent every time the ELB IP changes , is there a way to make the ELB IP's transparent to agents

**Comment by dinesh4747** [comment]
I strongly doubt that whether AWS-ELB supports UDP protocol since agent does send span/trace event data through 9995/9996 UDP ports

**Comment by teambullseye** [comment]
we also see this issue....a full tcp conversion is required for AWS cloud elb to work with pinpoint we already submitted a pull request for this fix....we also just tested a successful fix for the DNS cache issue via the TCP connections but have not had time to start working on the UDP connection dns cache issue...we will submit pull request for the TCP dns cache fix

**Comment by teambullseye** [comment]
we have a fix for UPD also now.. we will be contributing in a couple of weeks after our internal approvals

**Comment by teambullseye** [comment]
another point around this you need to disable connection draining to fix part of this issue http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/config-conn-drain.html

**Comment by teambullseye** [comment]
also you may need to have your health check time decreased to register the instance as unhealthy faster so maybe every 10 seconds as apposed to 30 seconds etc.
