### ISSUE TITLE
Pinpoint collector performance when receiving more traffic from more than 100 JVM servers 

### ISSUE THREAD

**Issue by dinesh4747** [naver/pinpoint#3008]
Quick question here - currently we have on-boarded around 50 JVM servers to my collector box
we are planning to add another 50 more JVM's to the box
Is there any specific parameters in collector properties which would limit us on adding more JVM's ?
Like whether we need to increase any of the parameters in collector.properties to ensure good performance when more than 100 JVM send data to Collector box
great if could you share some context on this ?

**Comment by koo-taejin** [comment]
Hi dinesh4747

Thank you for using Pinpoint more actively.

Unfortunately, there is no option to limit agent count.
It's hard to know exactly because it differs from server spec or data transfer from agent. (In our case, we have on-boarded around thousands of agents to our's collector box.)

If the collector can not accept data, a RejectedException will be thrown in the collector log.
In this case, use the following options to change the settings according to the environment of the collector.

```
pinpoint-collector.properteis
# number of tcp worker threads
collector.tcpWorkerThread=128

# number of udp statworker threads
collector.udpStatWorkerThread=256

# number of udp spanworker threads
collector.udpSpanWorkerThread=256
```

In addition, you can put bulk the data from the collector to hbase using the following options:
It's a better performance for us. However, please be sure to test it because it may be different from situation. 

```
hbase.properties
# enable hbase async operation. default: false
hbase.client.async.enable=true
# the max number of the buffered asyncPut ops for each region. default:10000
hbase.client.async.in.queuesize=10000
# periodic asyncPut ops flush time. default:100
hbase.client.async.flush.period.ms=100
# the max number of the retry attempts before dropping the request. default:10
hbase.client.async.max.retries.in.queue=3
```

thanks.

**Comment by dinesh4747** [comment]
Hi @koo-taejin 

Thanks for the quick response 

I am seeing the below rejected exception on UDP Span in my collector logs 

2017-06-06 22:46:47 [WARN ](Pinpoint-UDP-Span                  ) RejectedExecutionCount=1113200
2017-06-06 22:46:47 [WARN ](Pinpoint-UDP-Span                  ) RejectedExecutionCount=1113300
2017-06-06 22:46:48 [WARN ](Pinpoint-UDP-Span                  ) RejectedExecutionCount=1113400
2017-06-06 22:46:48 [WARN ](Pinpoint-UDP-Span                  ) RejectedExecutionCount=1113500
2017-06-06 22:46:48 [WARN ](Pinpoint-UDP-Span                  ) RejectedExecutionCount=1113600
2017-06-06 22:46:48 [WARN ](Pinpoint-UDP-Span                  ) RejectedExecutionCount=1113700
2017-06-06 22:46:53 [WARN ](Pinpoint-UDP-Span                  ) RejectedExecutionCount=1113800

Kindly let me know whether this would be fixed on increasing the collector.udpSpanWorkerThread=256

**Comment by koo-taejin** [comment]
Try increasing the collector.udpSpanWorkerThread option, 
but if the exception still occurs, then it seems that the time to store in hbase has reached the limit.

In this case, I suggest to change the configuration to the bulk put type, 
and If the exception still occurs, then I recommend to increase the hbase.

thanks.

**Comment by dinesh4747** [comment]
Increase the Hbase in the sense - do you want me to increase the Heap size of Hbase 

In other terms I am also seeking for better options to get more write performance in Hbase 

Do you follow any best practices to on specific Hbase configuration to get good write performance?

**Comment by koo-taejin** [comment]
It means a way to increase the performance of Hbase. (like adding server, upgrading spec, tuning Hbase)

Hbase operate in the operation team, so I do not know best practice exactly.
So, Hbase best practice would be more helpful to ask the Hbase community

**Comment by vikasmsg** [comment]
Hi @dinesh4747 ,  please help me in hbase tuning
