### ISSUE TITLE
Pinpoint doesnt bringing up call that goes from JVM to Ldap server call

### ISSUE THREAD

**Issue by dinesh4747** [naver/pinpoint#3018]
In one of my application the login call goes to LDAP server for Authentication and then primarily hits the other Micro services after the authentication
I see that in pinpoint I dont see the call that goes JVM to LDAP server
Moreover this call is kind off Asynchronized invocation--->Hystrix call-->which calls to LDAP Server (Virtual IP - VIP)
so ideally from JVM whichever call outgoing calls should be tagged in pinpoint right?
Kindly let me know If I am missing something here

**Comment by dinesh4747** [comment]
Just want to understand few things here actually as below

a) Since its a LDAP call that come from the profiled JVM we are not getting it in the server map ?

b) Else like since its getting implemented through Hystrix call (Asynch call) due to which its not showing up?

c) finally Ldap have been hosted on Virtual IP with reverse proxy due to which it fails to display it in the server map ?
<img width="1413" alt="screen shot 2017-06-08 at 4 32 16 pm" src="https://user-images.githubusercontent.com/23452852/26925773-adcff0a8-4c68-11e7-8d6e-ded78ac75661.png">

**Comment by Xylus** [comment]
As discussed over gitter, the issue seems to be due to pinpoint not having ldap client support.
You could create a plugin for your ldap client if you'd like :)
