### ISSUE TITLE
Does pinpoint captures the request header of the profiled JVM

### ISSUE THREAD

**Issue by dinesh4747** [naver/pinpoint#3038]
Hi All,

Environment -

Web server - Apache Httpd server

App server - Tomcat container with spring boot

Platform - Linux 

Issue Statement - Does pinpoint captures the request header of the profiled JVM

whether we are capturing request headers as part of our JVM tracing

1) I see the request pattern is getting captured, but how about the request headers getting captured and presenting it in the console

2) Lets say we have 100's of request hit in your JVM and we if want to track specific request then there should be some unique value would be getting passed as part of each request from the web server to JVM through request headers

3) To give context In our apps we see the unique id being passed is correlationId and sessionId as part of each request call that comes in the headers

can we get the complete http request headers through the following option in pinpoint.config

# Hide pinpoint headers.
profiler.tomcat.hidepinpointheader=true
# URLs to exclude from tracing
profiler.tomcat.excludeurl=/aa/test.html, /bb/exclude.html
profiler.tomcat.tracerequestparam=true

# original IP address header
# https://en.wikipedia.org/wiki/X-Forwarded-For
#profiler.tomcat.realipheader=X-Forwarded-For
# nginx real ip header
#profiler.tomcat.realipheader=X-Real-IP
# optional parameter, If the header value is ${profiler.tomcat.realipemptyvalue}, Ignore header value.
#profiler.tomcat.realipemptyvalue=unknown

Or else we need to have some custom header method in pinpoint to get it traced for tomcat JVM 

Kindly let me know if I have misinterpreted anything here

**Comment by Xylus** [comment]
Hi @dinesh4747 
We don't trace http headers currently, although you could probably modify our existing plugins to achieve what you're looking for.
Also, the headers you'd like to trace should be configurable at the agent level so as to not collect everything.

**Comment by ari** [comment]
This would be very useful, although in our case we are using jetty.
