### ISSUE TITLE
Pinpoint can take the longest time to get the data?

### ISSUE THREAD

**Issue by zilingliyu** [naver/pinpoint#3043]
Hello everyone, I would like to ask if anyone knows pinpoint from the hbase to take the data there is no long time limit? I can only take the data within a month, more than a month no data, and if there is the longest time allocation Where can I set up?

**Comment by Xylus** [comment]
Hi @zilingliyu 
You can increase how long trace data is stored in hbase by increasing the TTL value for `TraceV2` table, or `Traces` table, depending on which one you're using.

**Comment by zilingliyu** [comment]
Hi @Xylus 
Traces table TTL corresponding to the 5184000, the actual response time is how much? How to convert?

**Comment by Xylus** [comment]
@zilingliyu I don't quite get what you mean by "the actual response time". If you mean the actual storage time (how long the data is stored), 5148000 is in seconds, which is 60 days.

**Comment by zilingliyu** [comment]
@Xylus Thank you very much,I got it.
