### ISSUE TITLE
Service performance compression test，QPS reduce 90% !  help !!!

### ISSUE THREAD

**Issue by wodedaidaibaobei** [naver/pinpoint#3061]
#### Description
My Tomcat service mainly involves Redis and Gson; 

When not use Pinpint ， the QPS  is about 2000 ;  Each request consumes about 200ms;

When use Pinpint ,the QPS is about  190  ;  Each request consumes about 6200ms;

I  saw the call_tree，ping() method costed about 1300ms；

#### Environment
redis : 2.6

**Comment by emeroad** [comment]
Check your log4.xml settings.
 - $PINPOINT_DIR/lib/log4.xml

**Comment by wodedaidaibaobei** [comment]
Perfect!!!  Your answer has solved my problem。I change the log level to ERROR, the project works near normally.
Just now I wrote a new test Demo , And the Demo is vary simple, just get a String from redis  and transform it to a Object; when not use PP ,the QPS is about 19000 . when use PP ,the QPS is about 14000;
Would  you give me some advice on how to minimize performance loss?
Thank you very much!!! @emeroad

**Comment by emeroad** [comment]
There is a trade-off between performance and data precision.
If performance is more important than data precision, Low sample rate is recommended.

$PINPOINT_DIR/pinpoint.config
```
    # 1 out of n transactions will be sampled where n is the rate. (20: 5%)
    profiler.sampling.rate=20 
```

**Comment by jxsking** [comment]
really usefull.
