### ISSUE TITLE
이메일 알람 error count에서 특정 Exception을 제외 할 수 있나요?

### ISSUE THREAD

**Issue by rasol89** [naver/pinpoint#3068]
#### Description

web 소스를 조금 고쳐서 이메일 알람을 구현 한 상태입니다.
근데 client side에서 발생시킨 broken pipe Exception이나 DB conncetion이 끊겨서 나는 Exception도 감지해서 이메일 알람이 와서 조금 곤란한 상태입니다.
혹시 내부 소스를 고쳐서 특정 Exception을 제외한 error count를 하게끔 설정 가능하려나요?

#### Environment

* Pinpoint version: 1.6.0
* OS, WAS, affected library, etc: centos, tomcat
* Additional details (e.g. how your collector/web is set up): web email alarm

**Comment by minwoo-jung** [comment]
exception 선택적으로 error 감지 여부를 결정하는 기능은 없습니다.
더욱이 분산환경에서 발생하는 네트워크 관련 exception은 error로 감지될수 있도록 신경을 쓰고 있습니다.

추가로 DB에 관련된 문제 분석시 참고하기에 좋은 글이 있어서 공유드립니다.
http://d2.naver.com/helloworld/5102792
