### ISSUE TITLE
Caused by: java.lang.NullPointerException  node.getNodeHistogram(); 

### ISSUE THREAD

**Issue by wjswk** [naver/pinpoint#3091]
getServerMapData.pinpoint?applicationName=carmreport&from=1498644581000&to=1498644881000&callerRange=1&calleeRange=1&serviceTypeName=TOMCAT&_=1498646990744

node.nodeHistogram the location of initialization value is not found;

![image](https://user-images.githubusercontent.com/11325233/27635020-25f6837e-5c38-11e7-93be-ac2b467fd479.png)

![image](https://user-images.githubusercontent.com/11325233/27635083-518eb7cc-5c38-11e7-8ccc-45558d827643.png)

![image](https://user-images.githubusercontent.com/11325233/27635054-3d9889aa-5c38-11e7-8d19-9a5866f40f0d.png)

**Comment by Xylus** [comment]
@wjswk The issue should be fixed in the master branch, please update to the latest build and give it another go.
Thanks

**Comment by wjswk** [comment]
@Xylus 1.7 do you have a stable version?

**Comment by Xylus** [comment]
No, the latest stable version is 1.6.2. 1.7.0 is not released yet.
