### ISSUE TITLE
error: Traces, TraceV2 tables do not exist

### ISSUE THREAD

**Issue by jorgheymans** [naver/pinpoint#3092]
#### Description
hbase "list" returns this:
```
Version 1.2.6, rUnknown, Mon May 29 02:25:32 CDT 2017

hbase(main):001:0> list
TABLE
AgentEvent
AgentInfo
AgentLifeCycle
AgentStatV2
ApiMetaData
ApplicationIndex
ApplicationMapStatisticsCallee_Ver2
ApplicationMapStatisticsCaller_Ver2
ApplicationMapStatisticsSelf_Ver2
ApplicationTraceIndex
HostApplicationMap_Ver2
SqlMetaData_Ver2
StringMetaData
TraceV2
14 row(s) in 0.3310 seconds

=> ["AgentEvent", "AgentInfo", "AgentLifeCycle", "AgentStatV2", "ApiMetaData", "ApplicationIndex", "ApplicationMapStatisticsCall                                 ee_Ver2", "ApplicationMapStatisticsCaller_Ver2", "ApplicationMapStatisticsSelf_Ver2", "ApplicationTraceIndex", "HostApplicationM                                 ap_Ver2", "SqlMetaData_Ver2", "StringMetaData", "TraceV2"]
```

but when i start tomcat pinpoint-web fails to start with this exception:

```

        ... 51 more
Caused by: java.lang.IllegalStateException: Traces, TraceV2 tables do not exist
        at com.navercorp.pinpoint.web.dao.hbase.HbaseTraceDaoFactory.getObject(HbaseTraceDaoFactory.java:69)
        at com.navercorp.pinpoint.web.dao.hbase.HbaseTraceDaoFactory.getObject(HbaseTraceDaoFactory.java:19)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySu                                 pport.java:168)

```

#### Environment
pinpoint 1.6.2

**Comment by jorgheymans** [comment]
it turns out to be a config error in  pinpoint-collector.properties

Both these entries should be set to v2 but are set to 'compatibilityMode'. In the docs it says 'dualwrite' even. Setting it v2 fixed the issue.

collector.experimental.span.format.compatibility.version=v2
collector.experimental.stat.format.compatibility.version=v2

**Comment by Xylus** [comment]
Hi @jorgheymans 
`Traces` and `AgentStat` tables are deprecated will be removed in 1.7.0 (the current master 1.7.0-SNAPSHOT already have them removed) so the master's hbase create table scripts do not have these.
(The `compatibilityMode` and `dualWrite` options are removed as well).

The installation guide would however be confusing for those who downloads stable binaries (just like your case) so I guess we should leave these tables in the scripts at least until 1.7.0 is released.
Thanks.
