### ISSUE TITLE
Collector and web about the configuration of cluster in what circumstances

### ISSUE THREAD

**Issue by hanrongsu** [naver/pinpoint#3105]
Hi,
Collector and web about the configuration of cluster in what circumstances, I do not quite understand, can you explain?

pinpoint-collector.properties
cluster.enable=true
cluster.zookeeper.address=
cluster.zookeeper.sessiontimeout=30000
cluster.listen.ip=
cluster.listen.port=

pinpoint-web.properties
cluster.enable=true
cluster.web.tcp.port=9997
cluster.zookeeper.address=
cluster.zookeeper.sessiontimeout=30000
cluster.zookeeper.retry.interval=60000
cluster.connect.address=

**Comment by koo-taejin** [comment]
Hi hanrongsu

You can find a description in [pinpoint-collector.properties](https://github.com/naver/pinpoint/blob/master/collector/src/main/resources/pinpoint-collector.properties) and [pinpoint-web.properties](https://github.com/naver/pinpoint/blob/master/web/src/main/resources/pinpoint-web.properties).

thanks
