### ISSUE TITLE
Pinpoint with SpringBoot with embedded Tomcat 8 captures only first request

### ISSUE THREAD

**Issue by jaykhimani** [naver/pinpoint#3107]
#### Description
I'm trying to integrate pinpoint with my Spring Boot 1.5.2 and 1.5.4 application deployed on embedded tomcat. As per the different post and issues, I've set `profiler.tomcat.conditional.transform=false` and also `profiler.applicationservertype=TOMCAT`. Setting this property allowed my application to be shown in the pinpoint web UI, but what I noticed is only the first request to my application (REST API) is traced and subsequent calls are not traced/collected. Below screenshot shows my application vm args on how javaagent is configured
![image](https://user-images.githubusercontent.com/460609/27843984-4626e372-611b-11e7-9816-587bee9d9a80.png)

Also the call stack for the first and only capture request doesn't include the Spring component/resources involved int the call.  (see below screenshot)
![image](https://user-images.githubusercontent.com/460609/27843967-05c272ce-611b-11e7-8d37-1fb20a084314.png)

Is there anything which I'm missing in configuration or is this a known bug or something?

#### Environment

* Pinpoint version: 1.6.2
* OS: macos Sierra & Ubuntu 16.04
* Additional details (e.g. how your collector/web is set up): Deployed pinpoint-web (as ROOT) and pinpoint-collector on Tomcat 8

**Comment by koo-taejin** [comment]
hi jaykhimani 

please check you're profiler.sampling.rate option in pinpoint.config
profiler.sampling.rate option governs how often the agent traces transactions. If you set this option to 2 the agent will trace once every 2 transactions (50% sampling), if you set it to 10 it'll trace once every 10 transaction (10% sampling) and default is 20. (5% sampling).

**Comment by jaykhimani** [comment]
Awesome, Thanks. It worked like a charm.

**Comment by Ajaya1997** [comment]
I'm trying to integrate pinpoint with my spring boot application but I'm getting some error please guide me.
![Screenshot (5)](https://user-images.githubusercontent.com/41962756/125191832-16ac6000-e262-11eb-9edb-0f4095a24e71.png)
![Screenshot (6)](https://user-images.githubusercontent.com/41962756/125191834-18762380-e262-11eb-87ee-187900c6fdcb.png)

**Comment by Ajaya1997** [comment]
Hi @koo-taejin 

I'm trying to configure the pinpoint with my spring boot application but I'm getting some error. P
![Screenshot (8)](https://user-images.githubusercontent.com/41962756/125192339-fb8f1f80-e264-11eb-9e4e-b4f2196d1b9a.png)
lease help me

**Comment by koo-taejin** [comment]
Hi @Ajaya1997 

Error logs show it has problem with connecting 127.0.0.1:9991.
Please check whether collector works well or not.

Thanks :)
