### ISSUE TITLE
hbase v Kafka

### ISSUE THREAD

**Issue by Claywd** [naver/pinpoint#3125]
More of a question. I was curious if the kafka plugin can be used to replace hbase and stream all the collected data into kafka topics.

**Comment by Xylus** [comment]
Hi @Claywd 
If you're talking about the 3rd party kafka plugin available [here](https://github.com/jiaqifeng/pinpoint/tree/dev-plugin-kafka/plugins/kafka), it won't do what you're looking for. What the kafka plugin (and other plugins in general) does is add tracing capability to pinpoint for their respective libraries.
To do what you're looking for, you'll probably have to modify the collector to direct everything it receives to kafka, or have agents stream everything into kafka. Both of which would require huge changes to the current system.
