### ISSUE TITLE
agent 사용시 catalina.out 로깅이 제대로 되지 않습니다

### ISSUE THREAD

**Issue by Hongura** [naver/pinpoint#3161]
#### Description

불필요한 logging을 막기 위해 logging.properties 를 사용하지 않고 있습니다
catalina.out 에 agent 를 사용하지 않으면 아래와 같이 노출되는데
```
Jul 14, 2017 3:34:21 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-8080"]
Jul 14, 2017 3:34:21 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-nio-8009"]
Jul 14, 2017 3:34:21 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 880 ms
```
agent 를 사용하면 해당 로그가 노출이 되지 않는 이유를 알수 있을까요?

logging.properties 를 쓰면 
```
14-Jul-2017 15:36:03.508 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
14-Jul-2017 15:36:03.520 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
14-Jul-2017 15:36:03.523 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 748 ms
```

으로 노출되긴 하지만 agent 를 사용 하는것 만으로 서버 설정을 변경하고 싶진 않습니다~
참고로 제가 사용하는 모니터링에서 'Server startup in" 을 로딩완료 메시지로 캐치하고 있어서
이런문의를 드리게 되었습니다

#### Environment

* Pinpoint version: 1.7.0
* OS, WAS, affected library, etc: CentOS 7.2 , Tomcat 8.0.45
* Additional details (e.g. how your collector/web is set up):
톰캣 기본 설정 + agent 만 셋업

**Comment by emeroad** [comment]
pinpoint에서도 jdk logging(Google guava, google guice)을 사용하는 부분이 있기 때문에
JDK 시작시 logging 설정이 없다면, 기본 JDK 설정을 세팅하고 가게 됩니다.

별도의 로그 포멧이 필요하다면 JDK logging 설정을 세팅하시기 바랍니다.
