### ISSUE TITLE
quickstart failed

### ISSUE THREAD

**Issue by sunyanyan** [naver/pinpoint#3172]
when  Run quickstart/bin/start-collector.sh    ... start-testapp.sh ....start-web.sh

"180 /180 sec(close wait limit)."

logs:
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/maven/wrapper/MavenWrapperMain : Unsupported major.minor version 51.0

###
system:OSX 10.12.1

bl05963:~ sts$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
bl05963:~ sts$ echo $JAVA_6_HOME
/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
bl05963:~ sts$ echo $JAVA_7_HOME
/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home
bl05963:~ sts$ echo $JAVA_8_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_141.jdk/Contents/Home

**Comment by Xylus** [comment]
Hi @sunyanyan 
The maven wrapper included with pinpoint uses maven version 3.3.9 which requires Java 7+ to be set for **JAVA_HOME** to run.
Please set your **JAVA_HOME** to your jdk 7+ directory.

If you cannot change your **JAVA_HOME**, you could download and install maven 3.2.5 and use that to build pinpoint instead.

On other note, we should probably add JDK 7+ **JAVA_HOME** requirement to our guides.
Thanks

**Comment by sunyanyan** [comment]
@Xylus  thx for help

but i change JAVA_HOME to 1.7 / 1.8 ,the logs still show "Unsupported major.minor version 51.0".

```
bg229567:~ sts$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_141.jdk/Contents/Home

bg229567:~ sts$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home
```
so i think maybe some config file use jdk1.6 ?

**Comment by huayaoyue6** [comment]
please check maven version . maven version show adopt to jdk version .
