### ISSUE TITLE
Plan to impletation of Per-request logging

### ISSUE THREAD

**Issue by dayforward** [naver/pinpoint#3177]
we are going to finish the Per-request logging based on tag of 1.6.2  of pinpoint project in about half a month.In our implementation, we target at collecting business log at the dir of log of tomcat.
Util now we've already implements most coding including collecting logs 
in agent, putting logs into hbase , and displaying in the webui. 
our new branch is located at https://github.com/dayforward/pinpoint
Welcome anyone inttresting in this to give advice. 
#### Environment

* Pinpoint version:1.6.2

**Comment by minwoo-jung** [comment]
looks good, good luck!

**Comment by dayforward** [comment]
[businesslog.zip](https://github.com/naver/pinpoint/files/1346109/businesslog.zip)
I'm sorry for this delayed patch for businesslog implementation; 
The patch is based on tag of 1.6.2 of pinpoint.  I'll be  very pleased if our community 
to accept the patch ,yet it needs lots of impovements in future. if not , I 'll keep on 
improve the patch ....

**Comment by dayforward** [comment]
@minwoo-jung, I've impleted an initial version of pre-request and already keeping up with the master branch. Would you please do an code review , thanks for your reply!

**Comment by minwoo-jung** [comment]
Hi @dayforward 
I got it. I will review and give you feedback.

**Comment by minwoo-jung** [comment]
Hi @dayforward

I reviewed your code at your repository. 
I should highly praise your efforts. I think you understand pinpoint core logic pretty well.

I'm tried to execute your per-request function. I wish you explain how to execute per-request implement function.
such as profiler.tomcatlog.dir property and log4j.xml configuration, and ConversionPattern.
**I think it would be best to add on sample project to your repository branch.**

And i want to see image in readme file , But image is broken link.

**Comment by dayforward** [comment]
Hi，Minwoo Jung
Sorry for my late reply for We have our Chinese New Year these days.
I've pushed an example in the github https://github.com/dayforward/pinpoint/tree/log4jexample_for_prerequest 
this is an tomcat project , and README is also pushed in the log4jexample_for_prerequest branch, thanks for your review.



sunyangzju@163.com
 
From: Minwoo Jung
Date: 2018-02-21 13:34
To: naver/pinpoint
CC: dayforward; Mention
Subject: Re: [naver/pinpoint] Plan to impletation of Per-request logging (#3177)
Hi @dayforward
I reviewed your code at your repository.
I should highly praise your efforts. I think you understand pinpoint core logic pretty well.
I'm tried to execute your per-request function. I wish you explain how to execute per-request implement function.
such as profiler.tomcatlog.dir property and log4j.xml configuration, and ConversionPattern.
I think it would be best to add on sample project to your repository branch.
And i want to see image in readme file , But image is broken link.

**Comment by minwoo-jung** [comment]
Hi~ @dayforward 
Ok I got it. I will try with guide.

**Comment by minwoo-jung** [comment]
Hi~ @dayforward

I want to express gratitude for your efforts.
We always thought such functionality was necessary.

But your implementation is different from what we thought.
Instead of reading from a log file, we hoped that log messages would be put into span data and sent to collector directly.
We also wish to minimize configuration as well, where the user would only need to set active or not(true/false).
Therefore, it will be hard to merge with how it's currently designed.
But if you would like to improve code to use in your system, I would gladly help you.
I will review your code and advice you as best I can.

I want to commend you for your work, and understanding the inner logic and implementing the functionality.

Thank you.
