### ISSUE TITLE
close agent's debug level log

### ISSUE THREAD

**Issue by zcc1234567** [naver/pinpoint#3179]
how can i close agent's debug level log?

#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by Xylus** [comment]
Hi @zcc1234567 
Are you looking to change the logging level? The *log4j.xml* for the agent is in *$AGENT_DIR/lib*.

**Comment by zcc1234567** [comment]
hi，@Xylus,thanks，I finded the file and changed the config,then it worked.
