### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by maskaiitd** [naver/pinpoint#3181]
<img width="1280" alt="screen shot 2017-07-22 at 9 56 25 am" src="https://user-images.githubusercontent.com/3132909/28492198-3f59a0c8-6ec4-11e7-986c-78519d8956c1.png">

**Comment by koo-taejin** [comment]
Please ask questions according to the format of the [guidelines](https://github.com/naver/pinpoint/blob/master/CONTRIBUTING.md).
