### ISSUE TITLE
mysql

### ISSUE THREAD

**Issue by scdxl** [naver/pinpoint#3184]
#### Description

  I have no idea of how to configure agent to collect the performance data of mysql. Could you tell how to modify the configuration of agent? Ths.
#### Environment

* Pinpoint version:1.6.2
* OS Red Hat Enterprise Linux Server release 6.8 (Santiago)

**Comment by Xylus** [comment]
Hi @scdxl 
We don't directly monitor mysql so there isn't a way to collect performance data of mysql instances.
Instead, we intercept calls made by the mysql jdbc client (applications) to trace query information and call statistics.

**Comment by scdxl** [comment]
Hi @Xylus 
Could you tell how can I intercept mysql calls? That's will be thankful you give me an example. Ths.

**Comment by Xylus** [comment]
They should automatically be traced without configuring anything. Are they not showing up in your server map / call stack?
(Note that support for mysql java connector 6+ has only been recently added to master and isn't available in 1.6.2)

**Comment by xbblq7n** [comment]
@Xylus Any plan on getting them on version 1.6.2?

**Comment by Xylus** [comment]
@xbblq7n We can't get them on version 1.6.2 as it's already been released. It'll however be included in the 1.7.0 release.
Of course, you can always build from master for 1.7.0-SNAPSHOT and use that.

**Comment by tedli** [comment]
It may be caused by `profiler.sampling.rate` in `pinpoint.config` which default value is `20`.
As the comment along with this said "1 out of n transactions will be sampled where n is the rate. (20: 5%)"

**Comment by xbblq7n** [comment]
@tedli Do you want to change the default value to 50 to get the SQL calls in PInpoint

**Comment by tedli** [comment]
@xbblq7n the sampling rate varies depending on everyone's business logic needs. I think it is significant to put the comment in a more conspicuous place like the `readme` doc to let ones who fresh to pinpiont know about it.
And I don't think alter to 50 means sampling more as it says "1 out of n", so if you want 50% sampling rate you can try altering 20 to 2.

P.S. if you speak Chinese, here is what I mean:
采样率取决于各家的业务逻辑，如果被采样的接口调用并发量非常大，那么高采样率开销太大了，搞不好 pinpoint 的 collector 都受不了，这种情况降低采样率得到的数据也非常有参考价值，反之，如果采样的接口总共也没几次调用，那么采样率很低的话，很有可能采样不到，或采到的数据参考价值很低。
而且改成 50 应该不是提高采样率，注释说的是 n 分之 1，想得到 50% 采样率的话，应该改成 2。

**Comment by xbblq7n** [comment]
@tedli Thanks
