### ISSUE TITLE
add RestTemplate plugin

### ISSUE THREAD

**Issue by koo-taejin** [naver/pinpoint#3192]
Add resttemplate plugin 

#### Description:
Resttemplate uses Http library for the actual connection.
Resttemplate plugin just record the method, it does not include operations for HTTP remote trace.

#### Result
Currently, Pinpoint show the internal http library, when a developer use RestTemplate to call http.
This task is easy to analyze because it displays the RestTemplate in the call stack.

In addition, if developer use a library that can not be traced internally such as Netty4ClientHttpRequestFactory, you can not see Http requests at all in the call stack,
When you activate resttemplate plugin, you can see http status code.

#### Additional Info
default setting is do not trace and record RestTemplate plugin

**Comment by conanhxb** [comment]
Is it possible to trace remote HTTP .call with resttemplate?

**Comment by koo-taejin** [comment]
hi conanhxb 

Impossible.
RestTemplate plugin has two functions.
1. keep trace with internal client when using Async call
2. Increase the visibility of connection between user code and actual http client.
To do remote tracing, you must use the httpclient library that is used in RestTemplate, which supports tracing.

thanks.

**Comment by conanhxb** [comment]
OK, thanks a lot .
