### ISSUE TITLE
New monitoring setup for JVM

### ISSUE THREAD

**Issue by Rishimin** [naver/pinpoint#3216]
HI,
We are planning to setup pinpoint in our test environment. So would like to know what are the steps to begin with. 
In which environment it needs to be installed?
Does collector and pinpoint web can be used in same server/Host?

Thanks

**Comment by Xylus** [comment]
Hi @Rishimin 
The [installation guide](https://github.com/naver/pinpoint/blob/master/doc/installation.md) should have everything you need to get started.
As for the collector/web, they should work in the same server/host,
Thanks.
