### ISSUE TITLE
When i choose REAL TIME at the top, error messages appear at the bottom

### ISSUE THREAD

**Issue by bingoogolapple** [naver/pinpoint#3223]
#### Description

* When i choose another time period, it's normal
* When i choose REAL TIME at the top, error messages appear at the bottom

#### Environment

* Pinpoint version: 1.6.2 and 1.7.0-SNAPSHOT
* 「Mac OS 10.12.5」 -> 「Docker 17.06.0-ce-mac19」 -> 「CentOS release 6.9 (Final)」
* This is my Chinese configuration notes。http://www.bingoogolapple.cn/#/Blog/BlogDetail/188

#### Additional Info

![image](https://user-images.githubusercontent.com/8949716/29020451-9a9a65c6-7b94-11e7-8a8c-3faa66784722.png)

**Comment by koo-taejin** [comment]
Hi bingoogolapple

This issue is related to the websocket.
please check you're websocket configuration.

**Comment by bingoogolapple** [comment]
* Solved by modifying the source code of WebSocketConfig.java

![image](https://user-images.githubusercontent.com/8949716/29257680-8376d5da-80e6-11e7-8908-dbe0dc6f8d8f.png)

Is there any other way to set AllowedOrigins values? For example, modify the configuration file

**Comment by koo-taejin** [comment]
Hi bingoogolapple

This feature is not currently available.
I did not feel the need for cross domain support, so did not consider the option.
Let's consider support for that feature.

thanks.

**Comment by koo-taejin** [comment]
@bingoogolapple 

Added config for allowedOrigins for websocket.  (https://github.com/naver/pinpoint/pull/3297#pullrequestreview-59766722)
You can set `websocket.allowedOrigins` in pinpoint-web.properties.

It is currently available in the master branch, and will be included in 1.7.0.

thanks

**Comment by bingoogolapple** [comment]
Thanks
