### ISSUE TITLE
SpanEventList in BufferedStorage limits the fixed size

### ISSUE THREAD

**Issue by piaoyingfeimeng** [naver/pinpoint#3226]
List<SpanEvent> flushData = null;
        storage.add(spanEvent);
        if (storage.size() >= bufferSize) {
            // data copy
            flushData = storage;
            storage = new ArrayList<SpanEvent>(bufferSize);
        }
        if (flushData != null) {
            final SpanChunk spanChunk = spanChunkFactory.create(flushData);
            if (isDebug) {
                logger.debug("[BufferedStorage] Flush span-chunk {}", spanChunk);
            }
            dataSender.send(spanChunk);
        }

**Comment by piaoyingfeimeng** [comment]
Each collection of data is the same

**Comment by koo-taejin** [comment]
Please ask questions according to the format of the [guidelines](https://github.com/naver/pinpoint/blob/master/CONTRIBUTING.md).

guidelines for contributing to this repository.
