### ISSUE TITLE
Alarm doesn't work

### ISSUE THREAD

**Issue by toxie641517** [naver/pinpoint#3239]
I have created an alarm ERROR COUNT TO CALLEE with threshold 1, and I make a few requests which will cause errors of my application.
Now I can see the error number from the web ui, but the alarm doesn't work at all. I have already make my custom AlarmMessageSender and build it again. I can see the log is 
 `ErrorCountToCalleeChecker result is false for application (MicroloanCore). value is 0. (threshold : 1).`

Very strange, the value is always 0 no matter how many error requests I sent, any help? Thanks a lot

**Comment by koo-taejin** [comment]
hi toxie641517 

Pinpoint checks the error for an exception in the transaction.
If the http response code is given as 500, the alarm condition may not be activated.

check it please.

thanks :)
