### ISSUE TITLE
why not push built stable images to hub.docker.com?

### ISSUE THREAD

**Issue by fuhongwei041** [naver/pinpoint#3242]
Pinpoint is a large sale program.  When I try to build it , I spent more than two hours. When I try to build docker images , I spent more than two weeks.  it's so  frustrating. So I simply think pinpoint is not a good project, haha. why not to improve it at end user perspective.

**Comment by emeroad** [comment]
Unfortunately, we are not experts in the docker.
Also, the docker is not our core issue, and we do not have enough time.
We are waiting for your contribution.
Good luck~

**Comment by minyk** [comment]
@fuhongwei041 pinpoint uses mvn docker plugin, so `mvn clean package docker:build -DskipTests` command is just enough. If you want to change image name and/or tag, see my repo: https://github.com/minyk/docker-pinpoint#custom

**Comment by kk17** [comment]
@emeroad It doesn't take much time to push the images to hub.docker.com. I think it more convenience for user to have official public docker images. @minyk mvn docker plugin version is to old which cause error when building with docker for mac [#218](https://github.com/spotify/docker-maven-plugin/issues/218)

**Comment by minyk** [comment]
@kk17 I built successfully at Feb, May and Sep 2017 using my macbook pro and latest Docker for Mac. Maybe docker version related issue? My Docker for Mac is `17.09.0-ce-mac35 (19611)`

**Comment by RoySRose** [comment]
@fuhongwei041 @kk17 
Checkout [pinpoint docker support](https://github.com/naver/pinpoint-docker)
