### ISSUE TITLE
Whether pinpoint provide public API?

### ISSUE THREAD

**Issue by WangHouLing** [naver/pinpoint#3245]
Hi,
Excuse me,I want to show data in my own way,but I'm not sure if pinpoint can provide api for me to use.

I will be grateful for any help you can provide.

@jart

**Comment by jart** [comment]
Aloha

**Comment by Xylus** [comment]
Hi all,
You're talking about a public API for tracing, right? We don't have a separate sdk for tracing right now, but we're planning to add one in the future.
Let me know if this is not what you're looking for.
Thanks!

**Comment by WangHouLing** [comment]
Thank you for considering my request. This may be not what I think about.  I'm so sorry I didn't make myself clear. 
I’m looking for a public API to display data. For example, I can use http request to get the data which the pinpoint web can display. I did't find a document about pinpoint web, please help me.
Thank you!

**Comment by Xylus** [comment]
@WangHouLing no worries, sorry I didn't get it the first time.
All of the APIs in pinpoint-web are open so you can do whatever you want with them, though it might be difficult to get everything you want since we don't have any documentation available for them.
However, feel free to use them however you'd like.

**Comment by WangHouLing** [comment]
@Xylus I see what you mean.Thank you for providing the requested information.

**Comment by Pudgedd** [comment]
@WangHouLing @Xylus  Hi, excuse me, I have the same problem. I wonder is there any API can get a complete call chain record by traceID.
I will be grateful for any help you can provide.
