### ISSUE TITLE
Is there a way to ignore some api call in the web ui

### ISSUE THREAD

**Issue by toxie641517** [naver/pinpoint#3246]
Hi, our app is under the nginx, so nginx will send many ping requests to our app, is there a way to ignore the ping call when collect the data? Thanks:)

**Comment by koo-taejin** [comment]
Hi toxie641517

if receive ping with a specific url, consider the profiler.{was}.excludeurl option in pinpoint.config.

**Comment by toxie641517** [comment]
hi, koo-taejin, thanks a lot:)
