### ISSUE TITLE
Add proxy HTTP header and monitoring

### ISSUE THREAD

**Issue by jaehong-kim** [naver/pinpoint#3252]
## Proxy HTTP Headers
pinpoint.config
~~~
profiler.proxy.http.header.enable=true
~~~

### Apache HTTP Server
* http://httpd.apache.org/docs/2.4/en/mod/mod_headers.html

~~~
<IfModule mod_jk.c>
...
RequestHeader set Pinpoint-ProxyApache "%t %D %i %b app=foo-bar"
...
</IfModule>
~~~

~~~
Pinpoint-ProxyApache: t=991424704447256 D=3775428 i=51 b=49 app=foo-bar
~~~

### Nginx
* http://nginx.org/en/docs/http/ngx_http_core_module.html
* http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header

~~~
server {
        listen       9080;
        server_name  localhost;

        location / {
            ...
            set $pinpoint_proxy_header "t=$msec D=$request_time app=foo-bar";
            proxy_set_header Pinpoint-ProxyNginx $pinpoint_proxy_header;
        }
...
}
~~~

~~~
Pinpoint-ProxyNginx: t=1504248328.423 D=0.123 app=foo-bar
~~~

### App
epoch and app information.
~~~
Pinpoint-ProxyApp: t=1502861340 app=foo-bar
~~~

#### Environment

* Pinpoint version: 1.7.0
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by jaehong-kim** [comment]
Applied to 1.7.0 snapshot version.
https://github.com/naver/pinpoint/blob/master/doc/proxy-http-header.md

**Comment by yjqg6666** [comment]
@jaehong-kim Multiple reverse proxy can not be supported. Any plan to support it. Multiple Pinpoint-Proxy* headers would be past, the agent in upstream app can parse the headers and order them.

**Comment by yjqg6666** [comment]
PR #6344 #6346 can solve it, but limited to two/three proxies in route. One use proxy nginx header, the other user proxy app header.
