### ISSUE TITLE
pinpoint agent log 들이 tomcat catalina.out 로그에도 찍힙니다

### ISSUE THREAD

**Issue by wj0924** [naver/pinpoint#3255]
#### Description
tomcat 서버를 모니터링 하기위해 pinpoint 를 설치했고 quick start 로 설치했습니다.
그런데 pinpoint agent 로그들이 catalina.out 로그 파일에 동시에 로깅이 되고있습니다.
별도로 설정한 부분은없고,  $pinpoint_agent_install_path/pinpoint.config 파일안에도 이렇다할 내용이없는것같습니다.
$pinpoint_agent_install_path/log 경로안에 쌓이고 있는 로그가 있기떄문에 catalina.out 로그에 동시에 중복로깅될필요가 없어보여서 남지않도록 하고싶은데  제가 혹시 설정을 못찾고 헤매고있는것인지 궁금합니다 ㅜㅜ

#### Environment

* Pinpoint version: 1.7
* OS, WAS, affected library, etc: centos 6.x 64bit 
* Additional details (e.g. how your collector/web is set up): agnet issue

**Comment by emeroad** [comment]
`#PINPOINT_DIR\lib\log4.xml`  의 ConsoleAppender 설정을 보시면 됩니다.
