### ISSUE TITLE
Condition that is always true

### ISSUE THREAD

**Issue by lifove** [naver/pinpoint#3256]
#### Description
Hi

In a recent snapshot, I've found a suspicious code in the following path:
rpc/src/main/java/com/navercorp/pinpoint/rpc/packet/stream/BasicStreamPacket.java

```
 22 public abstract class BasicStreamPacket implements StreamPacket {
...
 24     private static final byte[] EMPTY_PAYLOAD = new byte[0];
...
 32     public byte[] getPayload() {
 33         return EMPTY_PAYLOAD;
 34     }
...
 41     public String toString() {
 42         final StringBuilder sb = new StringBuilder();
 43         sb.append(this.getClass().getSimpleName());
 44         sb.append("{streamChannelId=").append(streamChannelId);
 45         sb.append(", ");
 46         if (getPayload() == null || getPayload() == EMPTY_PAYLOAD) {
 47             sb.append("payload=null");
 48         } else {
 49             sb.append("payloadLength=").append(getPayload().length);
 50         }
 51         sb.append('}');
 52         return sb.toString();
 53     }
```

In Line 46, getPayload() == EMPTY_PAYLOAD seems always true. Since the toString method is an abstract class, it might be overridden in other classes. However, a class like StreamCreateSuccessPacket does not implement/override toString. Since I don't have domain knowledge of this project, this might not be an issue. But I wanted to report this just in case.

Thanks!

**Comment by emeroad** [comment]
Your opinion is correct. I will fix it.
