### ISSUE TITLE
No data in Jetty

### ISSUE THREAD

**Issue by zmyer** [naver/pinpoint#3258]
Info
There is no data.

#### Description
When using in jetty, there is no data to show, how can I update pinpoint.config to deal with it
#### Environment
* Pinpoint version:1.5.2
* OS, WAS, affected library, etc: Window10
* Jetty: 9.0

**Comment by tedli** [comment]
@zmyer #3184 FYI.

**Comment by zmyer** [comment]
I have deal with it, thanks
