### ISSUE TITLE
Why UDPReceiver class receive method packet.getLength() == 0 is returned ?

### ISSUE THREAD

**Issue by clufeng** [naver/pinpoint#3261]
#### Description

Why `UDPReceiver` class  `receive` method  `packet.getLength() == 0 ` is returned ?  

Why not continue ? 

our scenes is LB health check will be send 0 length packet

#### Environment

* Pinpoint version: 1.6.2
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by emeroad** [comment]
I checked the UDPReceiver. It's a bug.

**Comment by clufeng** [comment]
Thanks for the reply

I read the code to modify to place, made a suggestion, you can take a look.
