### ISSUE TITLE
how to delete/remove application in the web ui ?

### ISSUE THREAD

**Issue by taoyantu** [naver/pinpoint#3267]
hello every one ,i have a problem .
i install a pinpoint agent for a application(tomcat) ,now ,i delete the tomcat .but in the pinpoint web ,the application also in it .how can i delete it from de web ?
who can help me!! thanks very much .

**Comment by taoyantu** [comment]
who can help me ~~~~ thanks every master !

**Comment by koo-taejin** [comment]
Please check out #2340

**Comment by taoyantu** [comment]
@koo-taejin   but i use /admin/removeApplicationName?applicationName=aaaaaa
it have error 
HTTP Status 404 - /admin/removeApplicationName
how to delete it ?

**Comment by koo-taejin** [comment]
https://github.com/naver/pinpoint/issues/2340#issuecomment-266917618
```
Note that you'll have to pass in an additional parameter password to call these admin APIs. The value is the one you configured in pinpoint-web.properties.
```
