### ISSUE TITLE
How to integrate PinPoint Web Admin and Cas(or other permission system)?

### ISSUE THREAD

**Issue by neulf** [naver/pinpoint#3268]
#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by Xylus** [comment]
Hi @neulf 
Pinpoint web does not enforce any security configuration so you're free to implement one however you see fit. The web module however has a spring-security dependency so it might be simplest to start from there.
But go with what you're most familiar with and/or what you're already using.
