### ISSUE TITLE
How to search the transaction in HBase according to the method name? 

### ISSUE THREAD

**Issue by stefli** [naver/pinpoint#3272]
Sometime, we want to find the transaction according to the method name, which table shoule i use? TraceV2, ApiMetaData, etc?

I have tried to use ApiMetaData with command:
scan 'ApiMetaData', LIMIT=>10, FILTER=>"ValueFilter(=,'substring:methodname')"

And then use the Timestamp to filter the requests in Web UI, but no record matched.

How to get the keyword(Maybe timestamp) in HBase, and use it to filter the request in Web UI.

**Comment by minwoo-jung** [comment]
Pinpoint save to ApiMetaData table.

please refer Api http://your domain/transactionInfo.pinpoint
BusinessTransactionController class process transactionInfo.pinpoint API.
You need to see or debugging HbaseApiMetaDataDao's method code called in transactionInfo.pinpoint logic.
