### ISSUE TITLE
mysql need in docker-compose

### ISSUE THREAD

**Issue by xbblq7n** [naver/pinpoint#3273]
Hi, 

I saw a docker-compose.yml file. In that we have **pinpoint-mysql**.. Why is that needed? was it placed purposefully there?

Can somebody please explain it?
@minwoo-jung @Xylus

**Comment by dawidmalina** [comment]
This was added as web ui need it if alarm manager is enabled. So basiclly it is not needed unless you want alarm manager.

**Comment by minwoo-jung** [comment]
dawidmalina is right.

**Comment by xbblq7n** [comment]
Thanks @dawidmalina
