### ISSUE TITLE
Need Help : Quick start Build failure

### ISSUE THREAD

**Issue by Mayank1907** [naver/pinpoint#3279]
#### Environment
OS: Windows 10,
Pinpoint version : 1.7

I am getting below Error while installing pinpoint for quickStart  using the command  **mvnw install -Dmaven.test.skip=true**

[INFO] Reactor Summary:
[INFO]
[INFO] pinpoint ........................................... SUCCESS [  4.075 s]
[INFO] pinpoint-annotations ............................... SUCCESS [  6.810 s]
[INFO] pinpoint-thrift .................................... SUCCESS [  7.568 s]
[INFO] pinpoint-commons ................................... SUCCESS [  9.819 s]
[INFO] pinpoint-bootstrap-core ............................ SUCCESS [  5.730 s]
[INFO] pinpoint-bootstrap ................................. SUCCESS [  1.869 s]
[INFO] pinpoint-rpc ....................................... SUCCESS [  4.483 s]
[INFO] pinpoint-profiler .................................. FAILURE [  5.796 s]
...........

Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project pinpoint-profiler: Compilation failure: Compilation failure:
[ERROR] F:\WORKSPACE\Pinpoint\pinpoint-master\profiler\src\main\java\com\navercorp\pinpoint\profiler\instrument\classreading\AnnotationMetadataVisitor.java:[29,47] no interface expected here
[ERROR] F:\WORKSPACE\Pinpoint\pinpoint-master\profiler\src\main\java\com\navercorp\pinpoint\profiler\instrument\ASMMethodNodeAdapter.java:[192,29] cannot find symbol
[ERROR] symbol  : constructor MethodInsnNode(int,java.lang.String,java.lang.String,java.lang.String,boolean)
[ERROR] location: class org.objectweb.asm.tree.MethodInsnNode

**Comment by ecamy** [comment]
I am also failure using quick start, but success using install guide. Link: https://github.com/naver/pinpoint/blob/master/doc/installation.md

**Comment by Xylus** [comment]
@Mayank1907 @ecamy Just tried out quickstart with master branch and it seems to be working fine.
Could you make sure you've cleaned (mvn clean) everything before installing if you've updated your local master with the latest from repo?
