### ISSUE TITLE
Dose it support DubboX?

### ISSUE THREAD

**Issue by YCLX** [naver/pinpoint#3280]
#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by Xylus** [comment]
Hi @YCLX 
I've never tried, but I don't think so.

@majinkai your input would be great! Thanks in advance

**Comment by majinkai** [comment]
it just does not support dubbox's REST feature.

**Comment by YCLX** [comment]
@majinkai @Xylus Thanks, Do you know how to add this plugin?

**Comment by Xylus** [comment]
@majinkai Thank you for your answer :)

@YCLX I think you'll have to make a plugin for DubboX (which would be lovely).
Please check out the [plugin development guide](https://github.com/naver/pinpoint/wiki/Pinpoint-Plugin-Developer-Guide) and take a look at other plugins for reference if you decide to create one.
