### ISSUE TITLE
Callstack not show

### ISSUE THREAD

**Issue by ecamy** [naver/pinpoint#3281]
I deployed pinpoint on windows 8 using pinpoint-1.5.2.  The whole project worked well except for call stack( shows in the panel named CallTree), It shows nothing when I select a trasaction.  Anyone know why?

**Comment by Xylus** [comment]
Hi @ecamy 
Please check your web log for exceptions when you select a transaction. If nothing seems to be wrong, please check your collector log (DEBUG level) to see if spans and span events are received/handled without error.
