### ISSUE TITLE
Does it Support SSH framework?

### ISSUE THREAD

**Issue by ecamy** [naver/pinpoint#3282]
#### Description

1. I can't see real time active thread chart at the bottom the main web
2. If I select a  transaction monitored, I can't see it's call tree. (***important)
3. can't add alarm,including user, group, etc.

Why? 

#### Environment
Win8
jdk1.7.0_80
pinpoint-1.5.2(collector,web,agent)
hbase-1.0.3

#### Monitoring web
J2EE Web(Struts2+Hibernate3)

**Comment by Xylus** [comment]
Hi @ecamy 
1. What does the active thread chart display?
2. If this is related to your issue #3281 let's continue there.
3. You need to set up mysql and configure web. Please take a look at [this](https://github.com/naver/pinpoint/blob/master/doc/alarm.md)

**Comment by ecamy** [comment]
Hi @Xylus , 
Thanks so much for your help.   Show nothing is only in version 1.5.2, including active thread chart and traction call tree view. When I use the version 1.6.1, all things works well.
