### ISSUE TITLE
Support Micro Service?How do it？

### ISSUE THREAD

**Issue by HaoChe17** [naver/pinpoint#3283]
#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by Xylus** [comment]
Hi @HaoChe17 
Please read the [guideline](https://github.com/naver/pinpoint/blob/master/CONTRIBUTING.md) and provide us more information when creating issues.
We can't help if you don't give us anything to work with.
Thanks.
