### ISSUE TITLE
Can we add SSL Certificates to Pinpoint web container to enable HTTPS

### ISSUE THREAD

**Issue by dinesh4747** [naver/pinpoint#3287]
we are planning to have SSL Ciphers to enable HTTPS (SSL Based Pinpoint Environment)

Few question as below -

1) Could you please let me whether is it ideal to have SSL for pinpoint website?

2) Whether integrating SSL files would have performance issue and will impact in determining the real time active chart and real time thread monitoring 

3) If yes SSL Cipher is still feasible, then which approach would be good ? 

Requesting you to take a review and share your thoughts on the same

**Comment by Xylus** [comment]
Hi @dinesh4747 
1. I don't think this is a question I can answer for you. If your company requires this, then yes you'll probably have to make connections over ssl/tls.
2. I personally don't think the performance impact would be an issue.
3. You'll have to set up your web server to accept https / wss connections (Please check your web server documentation on how to set this up). One part that might require change in pinpoint is where web sockets are created client-side (they're hard coded to use `ws://`, and you might to change this to `wss://` @denzels ).

**Comment by denzelsN** [comment]
The protocol for real time active chart is currently hard coded `ws://`.
I'll modify it to use 'ws: //' for 'http: //' and 'wss: //' for 'https: //'

**Comment by dinesh4747** [comment]
@denzelsN - Let me know when this change would be effective ?

can i get this change merged in current release 1.6.2 ?

**Comment by Xylus** [comment]
@dinesh4747 It cannot be merged into a version that's already released. You can build it from source once it's merged and ready.

**Comment by dinesh4747** [comment]
Thanks @Xylus - So in that case it would be available from next release 1.7.0 i presume

**Comment by cjk87927** [comment]
@dinesh4747 Did you configure successfully? 
I use nginx and change the ws to wss, but get 500 error
