### ISSUE TITLE
tomcat 메모리가 계속 증가하고 있습니다.

### ISSUE THREAD

**Issue by ed1216** [naver/pinpoint#3289]
#### Description
pinpoint 설치후 Tomcat memory가 계속 증가하고 있습니다.

tomcat memory의 힙메모리 설정이 제가 설정한 크기로 설정은 잘되어 있는걸로 
모니터링은 됩니다. 

pinpoint는 힙메모리만 사용하는 줄 알고 있었는대. 아닌가요? 
pinpoint에서 tomcat 메모리가 오버되지 않도록 설정하는 방법이 있을까요?

#### Environment
* Pinpoint version: 1.6.0
* OS, WAS, affected library, etc: 
  OS: WINDOW 2008 R2 Standard, tomcat 7.0.63, java 1.7.0_51

* Additional details (e.g. how your collector/web is set up):

#### Additional Info

-TOMCAT MEMORY CONFIG

-javaagent:D:\Pinpoint\pinpoint-bootstrap-1.6.0.jar
-Dpinpoint.agentId=IPCC-WALL1-1_SPhoneKR
-Dpinpoint.applicationName=IPCC-Test
-Dpinpoint:PermSize=128m
-Dpinpoint:MaxPermSize=128m
-XX:PermSize=512m
-XX:MaxPermSize=512m
-Xmx1024m
-Xms1024m

Inintail memory pool : 256MB
Maximum memory pool : 1024MB

**Comment by koo-taejin** [comment]
안녕하세요 

문의주신 사항이
1.  메모리의 증가율이 빨라졌다는 뜻인가요(지정한 Xmx 도달후 gc는 정상적으로 이루어지고 있지만, 이 간격이 줄어들었다는 것인가요?)
2. 지정한 Heap 사이즈 이상으로 memory를 차지하고 있다는 뜻인지요?

특히 전체 heap사이즈가 적게 설정되어 있는 상황이라면 1번 상황은 정상일 수 있습니다. 

먼저 heapdump를 추출하셔서 어떤 메모리가 많이 먹고 있는지 먼저 분석을 해보시고, 
핀포인트 때문이라면 heapdump를 전달주시면 이슈 분석에 도움이 될 것 같습니다. 

추가로 핀포인트는 javaagent이기 때문에 핀포인트 적용을 할 경우 약간의 메모리를 더 사용할수 밖에 없습니다. 
(perm과 heap을 나누는 기준은 jvm의 정책이라 저희가 heap에만 저장할수 있는 방법이 없습니다.)

**Comment by ed1216** [comment]
2.지정한 heap 사이즈 이상으로 memory를 차지합니다. 
(heap사이즈를 1G로 설정되어 있긴 합니다..
사용자도 적고 트래픽도 적은 사이트라. 개인적으로 적당하다고 생각은 됩니다.)

heap dump 추출해서 분석중인대.  가장많이 차지하는 영역의 tree에 보면 
pinpoint가 보입니다. pinpoint와 연관성이 있는게 맞을까요?

![image](https://user-images.githubusercontent.com/29034301/29866693-28b92708-8db4-11e7-8795-6af71c2bab24.png)
