### ISSUE TITLE
pinpoint run in spring-boot docker error

### ISSUE THREAD

**Issue by walterrenyan** [naver/pinpoint#3293]
In the docker jdk: 8 container integrated pinpoint error
```bash
Error opening zip file or JAR manifest missing: /pinpoint-agent/pinpoint-bootstrap-1.6.2.jar

Error occurred during initialization of VM

agent library failed to init: instrument
```
The document is sure to exist.
What is the problem?

**Comment by NikoTung** [comment]
@walterrenyan How did package the pinpoint the the container ? 

I came across this and solved by put the pinpoint into my project .In the Dockerfile, copy it to the container when build the project.

    RUN mkdir -p /pinpoint-agent
    COPY pinpoint-agent /pinpoint-agent


It seems that the zip or unzip process cause this issue.

**Comment by walterrenyan** [comment]
@NikoTung According to your method of implementation or error, the same as the original

**Comment by irocks04** [comment]
Hi I am facing same issue with Error opening zip file or JAR manifest missing : pinpoint-bootstrap-1.6.2.jar when starting the docker. Are there any steps that i need to follow to overcome this error. I have the web and the collector up and running as a docker service but when i try to wrap agent with an application running as docker i run into above error.

**Comment by RoySRose** [comment]
Hello, @irocks04

**Comment by huangchaobing** [comment]
@walterrenyan I inject  pinpoint-bootstrap-1.8.0.jar  into docker image of application microservice,also generates error:
      Error opening zip file or JAR manifest missing:/pinpoint-bootstrap-1.8.0.jar
      Error occurred during initialization of VM
      agent library failed to init: instrument

I want to know how to solve this problem?

**Comment by RoySRose** [comment]
Hello, @huangchaobing 

by looking at your error message
*Error opening zip file or JAR manifest missing:/pinpoint-bootstrap-1.8.0.jar*
it looks like you've misplaced the jar file.

**Comment by huangchaobing** [comment]
@RoySRose  oh,but I enter into my docker container,I can find  pinpoint-bootstrap-1.8.0.jar in docker root directory,so I don't how to settle out this problem.

**Comment by huangchaobing** [comment]
My dockerfile configuration file as follow:
FROM public-docker-virtual.artnj.zte.com.cn/java:openjdk-8u111-jre-alpine
MAINTAINER Devops
COPY @project.build.finalName@.jar /app.jar
COPY pinpoint.config /pinpoint.config
COPY pinpoint-bootstrap-1.8.0.jar /pinpoint-bootstrap-1.8.0.jar
RUN touch /app.jar && \
        touch /pinpoint.config && \
        touch /pinpoint-bootstrap-1.8.0.jar

CMD java -javaagent:/pinpoint-bootstrap-1.8.0.jar  -Dspring.profiles.active=docker -Dpinpoint.agentId=pinpoint-client-alert  -Dpinpoint.applicationName=pinpoint-client-alert  -jar /app.jar 
     
      when I start this micro-container with docker-compose,it generates  error info:

      Error opening zip file or JAR manifest missing:/pinpoint-bootstrap-1.8.0.jar
     Error occurred during initialization of VM
     agent library failed to init: instrument
