### ISSUE TITLE
whl agent's active thread is 0.3  , quit not undrstand

### ISSUE THREAD

**Issue by Damen2016** [naver/pinpoint#3301]
#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by Damen2016** [comment]
may  the number of active thread should be integer, how it could be 0.3

**Comment by koo-taejin** [comment]
It is the average value for the time between intervals, not the value of that time.

**Comment by Damen2016** [comment]
Thanks,koo-taejin.
another question, what agent's active threads  are used for ? Are these threads created by the agent in the tomcat?

**Comment by koo-taejin** [comment]
t is described in the tooltip. 
(Tooltip are located at the top right of the chart)

`active for serving a request.`

**Comment by Damen2016** [comment]
thanks, i get it.
