### ISSUE TITLE
Hbase specifies the namespace, pp error table not find

### ISSUE THREAD

**Issue by jacobsy** [naver/pinpoint#3304]
#### Description

Hbase allocated namespace，eg，xxx：AgentEvent，pp-collector、pp-web  how to configure？

#### Environment

* Pinpoint version:1.5.x
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by SKingNight** [comment]
It need to add some code in hbase table declare java file. And rebuild the jar file.
