### ISSUE TITLE
Pinpoint web UI can not display normally

### ISSUE THREAD

**Issue by WangHouLing** [naver/pinpoint#3309]
#### Description

I cloned pinpoint source code from github. Then, I installed Zookeeper, HBase and started them up. I ran `mvn clean install -DskipTests `, it compiled successfully. Pinpoint collector, and web started normally. But I access pinpoint web in the browser, it can not display normally.

#### Environment

* Pinpoint version:1.6.1
* OS:Centos7, version: "3.10.0-327.el7.x86_64", arch: "amd64", family: "unix"
* Tomcat version:8.5.41
* Maven version:Apache Maven 3.3.9

#### Additional Info

![image](https://user-images.githubusercontent.com/20981477/30049899-e74a2afc-924e-11e7-9772-9e2996174500.png)

Please help me! I will be grateful for any help you can provide.

**Comment by mrydy** [comment]
Maybe you can try another Browser such as Chrome or Safari.

**Comment by WangHouLing** [comment]
Thank you! I changed the browser, and web UI can display normally.
