### ISSUE TITLE
Hello!Accessories for five minutes, 20 minutes, 1 hour, 1 day service topology, why look at 12 hours service topology are display 192.168.2.101:20883 icon, it should display pd - user - the provider, what is this excuse me?

### ISSUE THREAD

**Issue by shijg** [naver/pinpoint#3319]
#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

#### Additional Info

![1](https://user-images.githubusercontent.com/29219192/30148342-9dcbfa30-93d5-11e7-96d8-cac18c8e5812.png)
![2](https://user-images.githubusercontent.com/29219192/30148340-9dc4a2f8-93d5-11e7-8928-ea3615933677.png)
![3](https://user-images.githubusercontent.com/29219192/30148341-9dc4d8b8-93d5-11e7-8f06-1d76ed45099d.png)
![111](https://user-images.githubusercontent.com/29219192/30148343-9dfc208e-93d5-11e7-85d5-4a7ba7bf13aa.png)

**Comment by shijg** [comment]
Those Numbers should correspond to the application's name, pd-user-provider

**Comment by emeroad** [comment]
Write the title clearly
