### ISSUE TITLE
Hello!Why does the user call the provider directly?In theory, no user directly requests the provider

### ISSUE THREAD

**Issue by shijg** [naver/pinpoint#3320]
#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

#### Additional Info

![4](https://user-images.githubusercontent.com/29219192/30152047-6c20f8a0-93e4-11e7-8d2b-6ccd3132a964.png)

**Comment by koo-taejin** [comment]
Hi @shijg
Please check out this #3285.
Thanks
