### ISSUE TITLE
Hi,Is pinpoint supporting websphere6.1?

### ISSUE THREAD

**Issue by ImmortalY** [naver/pinpoint#3322]
Is pinpoint supporting websphere6.1?

**Comment by ZhanChaoHan** [comment]
Is pinpoint supporting websphere7 ?

**Comment by ImmortalY** [comment]
@ZhanChaoHan 
yes,pinpoint supported websphere7 and 8.
I developed plugins to support websphere6.1

**Comment by ZhanChaoHan** [comment]
How to configure websphere agent ?

**Comment by jaehong-kim** [comment]
@ZhanChaoHan
There are no extra settings. 
Take a look at our installation guide(https://github.com/naver/pinpoint/blob/master/doc/installation.md)

**Comment by ZhanChaoHan** [comment]
@jaehong-kim 

CATALINA_OPTS =“$ CATALINA_OPTS -javaagent：$ AGENT_PATH / pinpoint-bootstrap- $ VERSION.jar”
CATALINA_OPTS =“$ CATALINA_OPTS -Dpinpoint.agentId = $ AGENT_ID”
CATALINA_OPTS =“$ CATALINA_OPTS -Dpinpoint.applicationName = $ APPLICATION_NAME”

How to configure these
thanks  a lot

**Comment by ZhanChaoHan** [comment]
how to Configuration this for the websphere

**Comment by ZhanChaoHan** [comment]
to The websphere console
or   startServer.sh?
