### ISSUE TITLE
How to debug PinPoint's source code?

### ISSUE THREAD

**Issue by fengnex** [naver/pinpoint#3323]
Could you please let me know how to debug PinPoint in an IDE, for example:
1. How to debug & run pinpoint agent in Eclipse or IDEA?
2. How to debug & run pinpoint collector in Eclipse or IDEA?
3. How to debug & run pinpoint Web Server in Eclipse or IDEA?
Thanks in advance!

**Comment by jiaqifeng** [comment]
My suggest is logging and currently the log output is really clear and useful.

**Comment by emeroad** [comment]
2, 3 :  Use the debug features of the IDE. It is the same as a normal java application.
1 : In addition, set the agent to the VM option.
![image](https://user-images.githubusercontent.com/7564547/30628169-a24b6a0c-9e0f-11e7-97ff-b27bc6378568.png)
