### ISSUE TITLE
Can URL be used as query condition to fetch corresponding trace data?

### ISSUE THREAD

**Issue by fengnex** [naver/pinpoint#3331]
This is not a bug report, it's a question OR suggestion:

Obviously people prefer to fetch certain URL's trace data when there are too many records, especially for those who are eager to find possible performance bottle-neck.

So I can't help know whether pp support querying specified URL's trace data, how and if it does?
OR are there and plans or comments if it doesn't support? Thanks.

**Comment by jiaqifeng** [comment]
In main page's topology map, you can right click a link and specify the url filter. But I can not figure out the right syntax of the filer pattern and feel it is no convenient so I give up at last.

**Comment by SKingNight** [comment]
This url filter can solve some scenes。but the filter has some problem also  ,such as search word like set get on line linked to redis, the result is not suitable, etc.
