### ISSUE TITLE
Datasource

### ISSUE THREAD

**Issue by christianorios** [naver/pinpoint#3335]
Hi, people.
Do I have to create a datasource in my Application Server (Jboss/Tomcat)?
Or does pinpoint-web use the information contained in applicationContext-datasource.xml ?

**Comment by koo-taejin** [comment]
hi christianorios

Regardless of applicationContext-datasource.xml, if you use datasource(DBCP, DBCP2, HikariCP) supported by the pinpoint, it will automatically find it.

thanks

**Comment by christianorios** [comment]
Ive got this error: 
"Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Cannot create JDBC driver of class 'com.mysql.jdbc.Driver' for connect URL 'mysql://127.0.0.1:3306/pinpoint?characterEncoding=UTF-8'"

**Comment by koo-taejin** [comment]
@christianorios 

Please check first, why can't to connect you're URL.
You can see information in DataSource, after connection established

thanks
