### ISSUE TITLE
Cause httpaysnclient timeoutError

### ISSUE THREAD

**Issue by sicheal** [naver/pinpoint#3342]
#### Description

jdk 1.7
org.apache.httpcomponents.httpasyncclient:4.1
org.apache.httpcomponents.httpclient:4.5

只要添加pinpoint，httpasyncclient请求经常失败，修改超时时间也没有用
取消pinpoint，httpasyncclient是没有问题的

#### Environment

* Pinpoint version: 1.6.2
* Httpclient version: org.apache.httpcomponents.httpclient 4.5
* Additional details (e.g. how your collector/web is set up):

**Comment by emeroad** [comment]
Sorry. Read the contribution guide.
- https://github.com/naver/pinpoint/blob/master/CONTRIBUTING.md

**Comment by tatumsu** [comment]
sicheal  请问下最后这个问题您找到解决方案了么？
