### ISSUE TITLE
application getting slow when running with pinpoint agent

### ISSUE THREAD

**Issue by ytfei** [naver/pinpoint#3343]
Env: 

pinpoint-agent 1.6.1, 
config: `pinpoint-real-env-lowoverhead-sample.config`

my app running with:
spring, dubbo, redis, mysql

My application is getting slow from tps 100 to tps 5 when running with pinpoint agent. I tried to use `pinpoint-real-env-lowoverhead-sample.config`, but it still not works. 

It seems lots of time is spent on redis operation: [screenshot](http://px-other.nos-eastchina1.126.net/pp-redis-issue.jpg), I checked the `pinpoint-real-env-lowoverhead-sample.config`, redis plugin seems have been disabled.

So I'd to know if I had miss something when configuring pinpoint agent.

**Comment by ankitsharan15** [comment]
Did you find any solution ?

**Comment by ankitsharan15** [comment]
@RoySRose 
For me the cpu usage goes like 300% causing application to go down . Also , starting java app also takes significant time.
I am using centos vm .

Any config changes or anything that i can use to make most of it without loss in performance.
Looking forward to hear from soon.

Thanks 
Ankit

**Comment by RoySRose** [comment]
@ankitsharan15 
Hm... I don't think there are any other things to do to reduce the CPU usage. As I've said pinpoint-agent hardly consumes CPU. But there were some cases such as the log level set to DEBUG, printing all the logs. Have you checked your log level?

**Comment by ankitsharan15** [comment]
@RoySRose 
It was running on debug mode .
Thanks for all the help.
Appreciate it .
