### ISSUE TITLE
Custom serviceType is 1920, but always use default 1000 ,why?

### ISSUE THREAD

**Issue by youwoa** [naver/pinpoint#3345]
[{"applicationName":"MyTestPP","serviceType":"TOMCAT","code":1010},{"applicationName":"gaeaServer","serviceType":"STAND_ALONE","code":1000}]

**Comment by Xylus** [comment]
@youwoa 
If you've developed a custom plugin for an application, you'll have to implement **ApplicationTypeDetector** to have the agent detect the service type.
[Here](https://github.com/naver/pinpoint/blob/master/plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/TomcatDetector.java) is an example for Tomcat.

**Comment by lins0621** [comment]
ok
