### ISSUE TITLE
Using profiler.include causes an infinite stacktrace

### ISSUE THREAD

**Issue by giacomolm** [naver/pinpoint#3349]
Hi guys, first of all congrats for this amazing project, it rocks! I was using the 1.6.1 version, and everything works as intended. I tried to deploy 1.6.2, with the same configurations, and when I try to reach my web application I get an infinite stack trace repeating this exception [1] . The webpage of my app doesn't load at all and I can stop the stacktrace only if I kill the app

In my case I have two tomcat, a standalone one (8.0.46) where I deployed pinpoint, and the second one (8.5) defined by a cargo maven profile where the agent is attached. 

And I get that exception only if I fill the _profiler.include_ option in pinpoint.config. In that case I am specifying a package with a wildcard. 

Am I doing something wrong?

[1]  Stacktrace
14.09.2017 08:57:37 WARN  http-nio-8080-exec-2 [DefaultTrace.traceBlockEnd:157] [DefaultTrace] Corrupted call stack found.
[INFO] [talledLocalContainer] com.navercorp.pinpoint.exception.PinpointException: not matched stack id. expected=-1, current=0
[INFO] [talledLocalContainer] 	at com.navercorp.pinpoint.profiler.context.DefaultTrace.traceBlockEnd(DefaultTrace.java:156)
[INFO] [talledLocalContainer] 	at com.navercorp.pinpoint.profiler.context.DefaultTrace.traceBlockEnd(DefaultTrace.java:131)
[INFO] [talledLocalContainer] 	at com.navercorp.pinpoint.bootstrap.interceptor.BasicMethodInterceptor.after(BasicMethodInterceptor.java:82)
[INFO] [talledLocalContainer] 	at com.navercorp.pinpoint.bootstrap.interceptor.ExceptionHandleAroundInterceptor.after(ExceptionHandleAroundInterceptor.java:44)
[INFO] [talledLocalContainer] 	at org.hippoecm.hst.container.XSSUrlFilter.containsMarkups(XSSUrlFilter.java:86)
[INFO] [talledLocalContainer] 	at org.hippoecm.hst.container.XSSUrlFilter.isValidRequest(XSSUrlFilter.java:66)
[INFO] [talledLocalContainer] 	at org.hippoecm.hst.container.XSSUrlFilter.doFilter(XSSUrlFilter.java:45)
[INFO] [talledLocalContainer] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
[INFO] [talledLocalContainer] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
[INFO] [talledLocalContainer] 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
[INFO] [talledLocalContainer] 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
[INFO] [talledLocalContainer] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
[INFO] [talledLocalContainer] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
[INFO] [talledLocalContainer] 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
[INFO] [talledLocalContainer] 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
[INFO] [talledLocalContainer] 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
[INFO] [talledLocalContainer] 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
[INFO] [talledLocalContainer] 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
[INFO] [talledLocalContainer] 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
[INFO] [talledLocalContainer] 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
[INFO] [talledLocalContainer] 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
[INFO] [talledLocalContainer] 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1100)
[INFO] [talledLocalContainer] 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:687)
[INFO] [talledLocalContainer] 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
[INFO] [talledLocalContainer] 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
[INFO] [talledLocalContainer] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[INFO] [talledLocalContainer] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[INFO] [talledLocalContainer] 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[INFO] [talledLocalContainer] 	at java.lang.Thread.run(Thread.java:748)

**Comment by jaehong-kim** [comment]
@giacomolm 
Could you pass the full log?

**Comment by giacomolm** [comment]
Hi @jaehong-kim, thanks for your reply, maybe I found the reason. In 1.6.2 I was using this setting
**profiler.callstack.max.depth**=-1

Reverting back to 64 is not giving that exception: what's the value to use to have unlimited depth?

**Comment by jaehong-kim** [comment]
@giacomolm 
It looks like an infinite loop due to cross reference.
