### ISSUE TITLE
Exception occurred while trying to CRUD userGroup information

### ISSUE THREAD

**Issue by GyaneshRahatekar** [naver/pinpoint#3355]
Hi All,

We are not able to create User/UserGroup in Pinpoint Console(1.6.2).
Need your help and we are using hbase.
Please suggest.

Error on Console:
Exception occurred while trying to CRUD userGroup information

#### Environment

* Pinpoint version:1.6.2
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by GyaneshRahatekar** [comment]
![image](https://user-images.githubusercontent.com/30924053/30480451-6207e618-9a37-11e7-917c-7f5a8d678422.png)

**Comment by Xylus** [comment]
Hi @GyaneshRahatekar 
User management is not provided out of the box. You'll have to implement the details. Please take a look at [this](https://github.com/naver/pinpoint/blob/master/doc/alarm.md) for more information.
