### ISSUE TITLE
No Data Collected

### ISSUE THREAD

**Issue by GyaneshRahatekar** [naver/pinpoint#3356]
HI Team,

We are using Pinpoint 1.6.2 and instrumented Java application.
We are not to be see data on the console

This is new setup and let us know if we need to enable anything at the collector.

* Pinpoint version:1.6.2
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by GyaneshRahatekar** [comment]
![image](https://user-images.githubusercontent.com/30924053/30480564-fc6eb222-9a37-11e7-9e93-52e333afa529.png)

**Comment by GyaneshRahatekar** [comment]
![image](https://user-images.githubusercontent.com/30924053/30480605-28a56890-9a38-11e7-8108-4cfc1e9d8eb4.png)

**Comment by GyaneshRahatekar** [comment]
But getting these data only

![image](https://user-images.githubusercontent.com/30924053/30480658-8c2f54f2-9a38-11e7-8428-3cb3400428d8.png)

**Comment by GyaneshRahatekar** [comment]
Hi All,

Please help us at the earliest as why we any transactions are not captured as shown in above screenshot

**Comment by GyaneshRahatekar** [comment]
Can you please share an checklist at agent/collector end that will help to narrowdown the issue.
like Ports/Properties

**Comment by sosojustdo** [comment]
you hbase and pinpoint-web pinpoint-collector just one server?
if dosen't please check zookeer address info configure with pinpoint-collector.properties，pinpoint-web.properties。

**Comment by GyaneshRahatekar** [comment]
Yes in one server.
In properties, it is pointing to localhost

**Comment by sosojustdo** [comment]
1：please check pinpoint web console ，you can select application?
2：If you can select application, and home page center show server icon？

**Comment by GyaneshRahatekar** [comment]
yes its shows application name but able to capture BT
![image](https://user-images.githubusercontent.com/30924053/30634448-c3838eaa-9e0c-11e7-9558-312329c17cc5.png)
![capture](https://user-images.githubusercontent.com/30924053/30634453-c830bbda-9e0c-11e7-86a1-9a2393911e78.JPG)

**Comment by sosojustdo** [comment]
1：Do you have observable pinpoint-collector pinpoint-web  error log？
2：pinpoint-agent with pinpoint.config set profiler.sampling.rate=1 you can try

**Comment by GyaneshRahatekar** [comment]
1 both the logs are not generated ,
2 This setting we have configured and restart the application  instance  getting same status .

**Comment by Xylus** [comment]
@GyaneshRahatekar 
What kind of application/WAS is **CISCO_CVP**?

**Comment by GyaneshRahatekar** [comment]
Its a Tomcat ( JAVA )
OS WINDOWS

**Comment by GyaneshRahatekar** [comment]
[CVP15_CALL_Server-pinpoint.log](https://github.com/naver/pinpoint/files/1341598/CVP15_CALL_Server-pinpoint.log)

**Comment by koo-taejin** [comment]
Sometimes pinpoint can not auto-detect applicationType.
I recommend you to try fixing your service type TOMCAT

```
# pinpoint.config
profiler.applicationservertype=TOMCAT
```

**Comment by jalja27** [comment]
Change the "Mode" option to "Java" in the "Startup" tab

**Comment by patricklbs** [comment]
Hello, I'm a new and I have the same problem, which tab do you mean please ? I'm not collect on inspector too. Thank's for you reply !

**Comment by patricklbs** [comment]
![image](https://user-images.githubusercontent.com/1314444/35923723-53a17600-0c21-11e8-8473-f139017e7ee9.png)

**Comment by patricklbs** [comment]
@Xylus Thank's a lot, the problem was that we had to wait :)

**Comment by newpant** [comment]
May be the UDP port of your collector was blocked by firewall, please check the log of agent.
