### ISSUE TITLE
How does Pinpoint mark a transaction error?

### ISSUE THREAD

**Issue by zhangzhaoyu** [naver/pinpoint#3365]
#### Description
Hi, Because I want to report the error message(maybe exception message), so I need to get all of the transactions with **fire tag** which were marked failed.

![screenshot from 2017-09-18 16 59 39](https://user-images.githubusercontent.com/5105709/30534915-c9bf4e56-9c92-11e7-9587-0eb36ac18e1c.png)

I read the source code of collector, I found `SpanHandler` and `SpanChunkHandler` with the below logic.
```java
 private void insertSpanStat(SpanBo span) {
        final ServiceType applicationServiceType = getApplicationServiceType(span);
        final ServiceType spanServiceType = registry.findServiceType(span.getServiceType());

        final boolean isError = span.getErrCode() != 0;
        int bugCheck = 0;
        if (span.getParentSpanId() == -1) {
            if (spanServiceType.isQueue()) {
                // create virtual queue node
                statisticsHandler.updateCaller(span.getAcceptorHost(), spanServiceType, span.getRemoteAddr(), span.getApplicationId(), applicationServiceType, span.getEndPoint(), span.getElapsed(), isError);

                statisticsHandler.updateCallee(span.getApplicationId(), applicationServiceType, span.getAcceptorHost(), spanServiceType, span.getAgentId(), span.getElapsed(), isError);
            } else {
                // create virtual user
                statisticsHandler.updateCaller(span.getApplicationId(), ServiceType.USER, span.getAgentId(), span.getApplicationId(), applicationServiceType, span.getAgentId(), span.getElapsed(), isError);

                // update the span information of the current node (self)
                statisticsHandler.updateCallee(span.getApplicationId(), applicationServiceType, span.getApplicationId(), ServiceType.USER, span.getAgentId(), span.getElapsed(), isError);
            }
            bugCheck++;
        }
.....
```

```java
for (SpanEventBo spanEvent : spanEventList) {
                    final ServiceType spanEventType = registry.findServiceType(spanEvent.getServiceType());

                    if (!spanEventType.isRecordStatistics()) {
                        continue;
                    }

                    // if terminal update statistics
                    final int elapsed = spanEvent.getEndElapsed();
                    final boolean hasException = spanEvent.hasException();

                    /*
                     * save information to draw a server map based on statistics
                     */
                    // save the information of caller (the spanevent that span called)
                    statisticsHandler.updateCaller(spanChunkBo.getApplicationId(), applicationServiceType, spanChunkBo.getAgentId(), spanEvent.getDestinationId(), spanEventType, spanEvent.getEndPoint(), elapsed, hasException);

                    // save the information of callee (the span that called spanevent)
                    statisticsHandler.updateCallee(spanEvent.getDestinationId(), spanEventType, spanChunkBo.getApplicationId(), applicationServiceType, spanChunkBo.getEndPoint(), elapsed, hasException);
                }
```
`SpanEventRecorder.recordException(boolean markError, Throwable throwable)` in plugins can mark a span event error and report the exception. In my application, if I use `try catch` to handle the exception, the transaction will not be marked error.  If a `RuntimeException` was catched by the `JVM`, the transaction will be marked error.
I don't know whether I am right or wrong about transaction error logic. Can you give me some advise about the below questions :
1.  Different between  `SpanHandler` and `SpanChunkHandler`
2. If I want to implement a plugin, in my plugin how can I mark the span or span event error to make the transaction failed ?

I used `SpanEventRecorder.recordException(boolean markError, Throwable throwable)` in my plugin to mark the span event error. I found out if the span event was in the first span of the transaction, the transaction was marked error. if the span event was not the first span, the transaction was not marked failed.

**Comment by Xylus** [comment]
Hi @zhangzhaoyu 
Any exceptions thrown will be marked as error if it's passed to `SpanEventRecorder.recordException(...)`. That means the exception has to be propagated up to a method that is traced by Pinpoint in order to be marked.
If you use `try catch` to handle the exception, it may or may not be marked as an error depending on whether or not there was a method traced by pinpoint that has recorded the exception further down the call stack.
Does this make sense?

1. The difference between **SpanHandler** and **SpanChunkHandler** is that **SpanHandler** handles spans (and span events within them) and **SpanChunkHandler** doesn't handle spans (only span events).
You can think of **SpanChunk** as a group of span events + minimal data to identify what their parent span is.
2. You simply call `SpanEventRecorder.recordException(...)`. Any transactions that have span events with exceptions marked this way will show up as an error (except exceptions handled by spring beans if configured using `profiler.spring.beans.mark.error`).
