### ISSUE TITLE
I want to know how  the Agent send the data to the Collotor ,What the core method is?  

### ISSUE THREAD

**Issue by AlphaIX** [naver/pinpoint#3367]
#### Description

Hi! This is the first time I've been exposed to the Pinpoint.  I want to know how the data is communicated between Agent and Collector.Your help is much appreciated.

#### Environment

* Pinpoint version:1.7.0 SNAPSHOT
* OS, WAS, affected library, etc:Mac OS 
* Additional details (e.g. how your collector/web is set up):

#### Additional Info

I will very appreciate for anyone who can help me know about the Module(pinpoint-profiler).
![2a5c76cc-a1b9-491b-9026-5f89e48e38f4](https://user-images.githubusercontent.com/32047892/30575252-273c9864-9d32-11e7-8deb-ee73f0c7866a.png)

**Comment by koo-taejin** [comment]
hi AlphaIX

I recommend viewing DefaultPinpointClientHandler class  and UdpDataSender class.
If you know netty, it will be easy to analyze the code.

thanks.

**Comment by AlphaIX** [comment]
Thank you every much！I think I should go first to know about the netty
