### ISSUE TITLE
Question: when will pp support angular 2?

### ISSUE THREAD

**Issue by fengnex** [naver/pinpoint#3373]
This's just a question.

Because pinpoint's road map mentioned that it will support angular 2 but no specified date.

**Comment by sosojustdo** [comment]
you can develope pinpoint plugin with angular 2; please refer link :https://github.com/naver/pinpoint/wiki#third-party-agentsplugins

**Comment by fengnex** [comment]
@sosojustdo 
Angular is Google's one front end framework, which has been used by pp and the version is v1.2.18, but you know it's many shortcomings, that's why pp's road map declared that it will support angular 2.

**Comment by emeroad** [comment]
We are preparing the angular2, But the schedule was not fixed.
