### ISSUE TITLE
pinpoint1.6.2 maven build--mvn install -Dmaven.test.skip=true

### ISSUE THREAD

**Issue by leechaun** [naver/pinpoint#3381]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.350 s
[INFO] Finished at: 2017-09-20T15:57:45+08:00
[INFO] Final Memory: 30M/304M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.
4.1:enforce (enforce-pinpoint-build-requirements) on project pinpoint: Some Enfo
rcer rules have failed. Look above for specific messages explaining why the rule
 failed. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception

F:\libs\pinpoint\pinpoint-1.6.2>

**Comment by Xylus** [comment]
> Look above for specific messages explaining why the rule failed.
