### ISSUE TITLE
Micro service base on DUBBO show entire chain

### ISSUE THREAD

**Issue by hzn6426** [naver/pinpoint#3385]
Our projects are base on micro service base on dubbo: web(spring-mvc+dubbo) deploy in tomcat ->inboke dubbo services ->mybatis->db. How i config the pinpoint show the entrie chain. i only config the web side project, the dubbo service chain lost in the node map, please help me, thanks!

**Comment by sosojustdo** [comment]
@hzn6426  I have same problem, For example invoke chain: api->dubbo->redis and mysql, just config pinpoint agent with api project tomcat server, but lost node map dubbo invoke redis or mysql.

**Comment by hzn6426** [comment]
@sosojustdo recently,I config all the relevant projects (web based tomcat,services based on dubbo), in the services shows the entire chain,For example A ,B , C service based on dubbo , web->A->B->C->redis(or mysql), pinpoint config all ABC service , it's show the entire dubbo chain in the A or B Or C mointor view.

**Comment by sosojustdo** [comment]
@hzn6426 
thank you point
Are you sure pinpoint just config with dubbo service project? web project don't config pinpoint?

**Comment by hzn6426** [comment]
@sosojustdo web and dubbo service all this about services(invoke chain) are configed the pinpoint, in the last invoked service ,you can see the entire invoke chain.

**Comment by xhuiinit** [comment]
@hzn6426  I have same problem, web->A->B->C->redis(or mysql), pinpoint config all. Have you solved it?

**Comment by Xylus** [comment]
Hi all,
Does the call stack view show the entire chain including dubbo services and mysql/redis? Or is that missing as well?
