### ISSUE TITLE
Plugin question

### ISSUE THREAD

**Issue by Super4You** [naver/pinpoint#3387]
Hello, Use pinponit to develop my own DB2 plugin, but the UI shows no images of DB2, only the database name and the ServiceType  such as: updev_DB2, no code can be found any more to resolve it！could you give me some advice？
![pinpoint](https://user-images.githubusercontent.com/25604732/30696120-18864e3c-9f0d-11e7-8e99-b53f74a1c6b5.png)

**Comment by denzelsN** [comment]
@Super4You 
Where can I find the db2 icon?

**Comment by Super4You** [comment]
Sorry,ServerType was named  started with DB2,but later it was suspected that the named problem，so change to IBMDB, where the UI  marked by the red box uponDev_IBMDB，The attached image is the IBMDB image added to the pinpoint-web！Thank you for your reply!
![icons](https://user-images.githubusercontent.com/25604732/30727649-23581dea-9f85-11e7-88c5-d72c53cdf113.png)
![servermap](https://user-images.githubusercontent.com/25604732/30727650-23583e9c-9f85-11e7-859d-642cdfe67aed.png)

**Comment by lvkang89** [comment]
please share the db2 plugin . I appreciate for it.

**Comment by Superizers** [comment]
> please share the db2 plugin . I appreciate for it.
If you need, you can contact me to provide it to you. My email address:liubinchn@126.com

**Comment by jsap2018** [comment]
@lvkang89 @Superizers would any of you be willing to share the db2 plugin with me? it would be greatly appreciated!

**Comment by Superizers** [comment]
> @lvkang89 @Superizers would any of you be willing to share the db2 plugin with me? it would be greatly appreciated!

 It’s my pleasure!but it is developed based on pinpoint 1.6 version, which is a very old version. Besides, the plug-in of different DB2 versions may need to deal with some classes separately. The current version has been greatly changed, probably only as a reference.If you need, you can contact me by email.

**Comment by snmsmanager** [comment]
#10707 Please check this
