### ISSUE TITLE
support to check available applicationName and agentId on the web

### ISSUE THREAD

**Issue by koo-taejin** [naver/pinpoint#3390]
#### Description
support to check available applicationName and agentId on the web

**Comment by mabunixda** [comment]
Is it possible to deactivate this feature if the installation is behind a proxy and/or the company does not want that this action is happening?

**Comment by koo-taejin** [comment]
@mabunixda 
I can't understand exactly what you say.

If you have not implemented AgentDownloadInfoDao class, it will be using GithubAgentDownloadInfoDao by default,
The problem does not occur if you do not click Installation tab.

So. it is a bit strange that it does not start tomcat because of this functionallity
