### ISSUE TITLE
HTTP status code with request failure.

### ISSUE THREAD

**Issue by jaehong-kim** [naver/pinpoint#3399]
#### Description

HTTP status code with request failure.
~~~
# HTTP status code with request failure.
# 1xx, 2xx, 3xx, 4xx, 5xx, 100, 101, 200, 201, ... 501, 502, 503, 504, 505
# e.g. profiler.http.status.code.errors=5xx, 401, 403
profiler.http.status.code.errors=5xx
~~~

#### Environment

* Pinpoint version: 1.7.0-SNAPSHOT
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by dinesh4747** [comment]
Hi @jaehong-kim 
Thanks for bringing this feature in place sooner than expected

**Comment by jaehong-kim** [comment]
Applied to 1.7.0 snapshot version.
https://github.com/naver/pinpoint/blob/master/doc/http-status-code-failure.md
