### ISSUE TITLE
Build dependencies return 500

### ISSUE THREAD

**Issue by cpresario** [naver/pinpoint#3402]
#### Description

Hi, I am trying to build pinpoint, but Im receiving a 500 return code.

maven return this:

Failed to transfer file: https://repository.jboss.org/nexus/content/repositories/thirdparty.releases/sun-jaxb/jaxb-api/2.1.4/jaxb-api-2.1.4.pom Return code is:500, ReasonPhrase: Server Error

#### Environment

* Pinpoint version: Latest
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by koo-taejin** [comment]
hi cpresario 

We also feel that the repository is often unstable. (I can't find alternative repository yet.)
I ask you to try it again. It seems to be working well now. 

If you fail again. then please check if you can connect to repository in your environment.

**Comment by cpresario** [comment]
Hi koo-taejin,

yes, I got it. Cheers!.
