### ISSUE TITLE
pinpoint Inspector Data Source (NOT FOUNT)

### ISSUE THREAD

**Issue by core279** [naver/pinpoint#3409]
#### Description

pinpoint 테스트 하는중입니다.
Data Source Chart 가 나오고 있지 않는데요. 왜 그렇고.. 어떤부분을 체크해야 하는지
감을못잡고 있어 문의드립니다~~

#### Environment

* Pinpoint version: 1.6.2
* OS, WAS, affected library, etc: CentOS
* Additional details (e.g. how your collector/web is set up):

#### Additional Info

![2017-09-27 10 48 42](https://user-images.githubusercontent.com/29620246/30892192-2877ed96-a372-11e7-82d0-c12a44ba380e.png)
![2017-09-27 10 50 24](https://user-images.githubusercontent.com/29620246/30892195-2d130214-a372-11e7-9991-29793227554e.png)

**Comment by koo-taejin** [comment]
안녕하세요 

MySql 과는 별개로 DataSource를 사용하여야(흔히 말하는 DBCP) 차트의 데이터가 쌓이게 됩니다. 
현재 지원하는 DataSource는 DBCP, DBCP2, HikariCP 등입니다.

**Comment by core279** [comment]
아하! 네 정말 감사합니다~

**Comment by jiuchongxiao** [comment]
@koo-taejin  can you see english?  i can not see ?
