### ISSUE TITLE
moment.tz.guess timezone is not correct at Chrome 61

### ISSUE THREAD

**Issue by chenlingmin** [naver/pinpoint#3418]
Help me!
It's only in my computer Chrome browser.

actual time is 2017-09-28 19:12:16, and the time for the HTTP request and response is also this.
But url and chart time is 2017-09-28 06:12:16.

I don't know what happened☹️. 
![image](https://user-images.githubusercontent.com/8233283/30963696-06ff5526-a414-11e7-9dc1-f5306eb68d95.png)

**Comment by chenlingmin** [comment]
this is Chrome test console
![image](https://user-images.githubusercontent.com/8233283/31372431-51ef0338-ad5b-11e7-94ce-a6fde3234445.png)

this is Safari test console
![image](https://user-images.githubusercontent.com/8233283/31372431-51ef0338-ad5b-11e7-94ce-a6fde3234445.png)

**Comment by denzelsN** [comment]
Would you check your OS timezone?
moment's timezone check logic : https://momentjs.com/timezone/docs/#/using-timezones/guessing-user-timezone/

**Comment by chenlingmin** [comment]
It is Asia/Shanghai

![image](https://user-images.githubusercontent.com/8233283/31480363-16226078-aee3-11e7-985b-21d29964c06d.png)

**Comment by denzelsN** [comment]
It's like this issue. https://github.com/moment/moment-timezone/issues/517
I'll check it out.

**Comment by chenlingmin** [comment]
Yeah. 👍
