### ISSUE TITLE
pinpoint can not recognize redis cluster

### ISSUE THREAD

**Issue by CHENTIANHAO123** [naver/pinpoint#3423]
my pinpoint version is 1.6.2,and can not show the redis resource,it just show the world "Unknown",
can some one help me to solve the problem? thanks!!

**Comment by jaehong-kim** [comment]
@CHENTIANHAO123 
Please tell me the type and version of redis client.

**Comment by CHENTIANHAO123** [comment]
Thanks for your reply, My jedis version is 2.9.0, I use below code to connect redis cluster.
`Set<HostAndPort> jedisClusterNodes = new HashSet<HostAndPort>();
jedisClusterNodes.add(new HostAndPort("***", 7000));
jedisClusterNodes.add(new HostAndPort("***", 7001));
jedisClusterNodes.add(new HostAndPort("***", 7002));
jedisClusterNodes.add(new HostAndPort("***", 7003));
jedisClusterNodes.add(new HostAndPort("***", 7004));
jedisClusterNodes.add(new HostAndPort("***", 7005));
JedisCluster jc = new JedisCluster(jedisClusterNodes);
jc.set("foo", "bar");
String value = jc.get("foo");`

**Comment by CHENTIANHAO123** [comment]
@jaehong-kim Thanks for your reply, My jedis version is 2.9.0, I use below code to connect redis cluster.
Set<HostAndPort> jedisClusterNodes = new HashSet<HostAndPort>(); 
jedisClusterNodes.add(new HostAndPort("***", 7000));
jedisClusterNodes.add(new HostAndPort("***", 7001));
jedisClusterNodes.add(new HostAndPort("***", 7002));
jedisClusterNodes.add(new HostAndPort("***", 7003));
jedisClusterNodes.add(new HostAndPort("***", 7004));
jedisClusterNodes.add(new HostAndPort("***", 7005));
JedisCluster jc = new JedisCluster(jedisClusterNodes);
jc.set("foo", "bar"); String value = jc.get("foo");

**Comment by jaehong-kim** [comment]
@CHENTIANHAO123 
The redis cluster is not yet supported.

**Comment by CHENTIANHAO123** [comment]
@jaehong-kim So sad....  May I know when agent can support redis cluster?

**Comment by jaehong-kim** [comment]
@CHENTIANHAO123 
I tried to reproduce it.
Even if you use JedisCluster, it is recognized as REDIS.
Please pass the entire log.
