### ISSUE TITLE
@Async 메소드 호출 부분 모니터링

### ISSUE THREAD

**Issue by jjc98** [naver/pinpoint#3426]
안녕하세요. Yahoo Japan 정종철입니다.
お疲れ様です。ヤフージャパンの鄭と申します。

그간 사내에서 직접적으로 도움 많이 받았는데, 이렇게 깃헙으로 문의 드리니 조금 묘한 기분이네요.
今まで社内で直接お問い合わせしましたが、今回ギットハブでお問い合わせしようと思ったら少し違和感を感じます。

앞으로 자주 문의드릴 것 같습니다. 잘 부탁드리겠습니다.
これからも時々にお問い合わせするかも知らないです。その時にはどうぞよろしくお願いします。

#### Description
＠Async 어노테이션을 통해서 비동기 멀티쓰레드 작업하는 부분이 있습니다.
＠Async アノテーションを利用して、非同期マルチスレッド作業する部分があります。

비동기 작업의 내부 동작 부분까지 모니터링하고 싶은데, Pinpoint 에서 현재 지원이 안되고 있나요?
非同期作業の内部ロジック部分までモニタリングしたいですけど、現在Pinpointにはこの部分が支援にできないですか？

또한, private method 부분도 표시가 안되는것 같은데, 이 부분을 볼 수 있는 방법은 없을까요?
ちなみに, private method部分も表示になってないみえますが、その部分をみる方法はありませんですか？

확인 부탁드립니다.
ご確認お願いします。

#### Environment
OS : 래드햇 계열 리눅스

#### Additional Info
FrameWork : Spring Boot 1.5.4.RELEASE
JDK : 1.8.0_144
Pinpoint Agent : pinpoint-bootstrap-1.6.3-SNAPSHOT

**Comment by Xylus** [comment]
@jjc98 종철님 안녕하세요!
이슈 등록해주셔서 감사합니다 ㅎㅎ 정말 반갑네요~

현재 Spring의 **@Async** 어노테이션을 통한 비동기 메소드 trace는 지원되고 있지 않습니다.
비동기 작업은 호출 thread에서 실행 thread로 **TraceContext**를 넘겨주는 작업이 필요해 현재는 플러그인 단에서 요 부분에 대한 지원이 추가되어야 합니다. (#3424)
Spring의 **@Async** 지원은 좋은 기능인거 같아 저희도 이 부분이 지원되면 좋을 것 같습니다.
혹시 관심 있으시다면 현재 저희 Spring 플러그인에 **@Async** 지원을 추가하셔서 PR 보내주시면 감사드리겠습니다!

private method는 Spring Bean 내부의 private method를 말씀하시는거라면 Spring 플러그인에서 Spring Bean 내부의 public (추가로 non-abstract, non-native, non-static) method들만 trace 하고 있어 현재로써는 아쉽게도 private method들은 trace 되지 않습니다. 우회적으로 private method에서 다른 spring bean의 public method를 호출한다면 이 부분을 trace하는 방법도 괜찮을 것 같습니다.

감사합니다.
