### ISSUE TITLE
Pinpoint Alarm

### ISSUE THREAD

**Issue by rajithawso2telco** [naver/pinpoint#3428]
#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

#### Additional Info

Pinpoint Alarm rules can't save. when refresh the page or click the app again the alarm rule will be deleted automatically.
![screenshot from 2017-10-09 12-05-21](https://user-images.githubusercontent.com/31986702/31327072-39cb2fe6-acea-11e7-8ac3-84e8a2c42425.png)
![screenshot from 2017-10-09 12-05-47](https://user-images.githubusercontent.com/31986702/31327071-39b8a29a-acea-11e7-92ed-01c9b5ace03b.png)

**Comment by Xylus** [comment]
Hi @rajithawso2telco 
In order to persist user groups and alarm configurations, you'll have to add mysql and implement the dao layer.
Please take a look at our [alarm guide](https://github.com/naver/pinpoint/blob/master/doc/alarm.md) for more details.
Thanks.
