### ISSUE TITLE
The xx?v=${buildTime} can't get the value

### ISSUE THREAD

**Issue by Pudgedd** [naver/pinpoint#3434]
#### Description
 
我在tomcat-7.0.82的ROOT目录下部署web，访问index的时候，所有的静态资源?v=${buildTime}都没有取到时间，（本应该是/lib/css/vendor.css?v=1495870880643，但实际上是/lib/css/vendor.css?v=${buildTime}），请问怎么回事呢？
#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by fengbenming** [comment]
怎么解决的？
