### ISSUE TITLE
alarm error

### ISSUE THREAD

**Issue by jack161641** [naver/pinpoint#3444]
#### Description

I want to configure alarms on application,but I get error when I create alarms item below,How can I do solve this error
#### Environment

* Pinpoint version:  1.7.0
* OS, WAS, affected library, etc: centos 7.2
* Additional details (e.g. how your collector/web is set up):

#### Additional Info

![snip20171017_4](https://user-images.githubusercontent.com/6339146/31649096-d87da7b2-b2d6-11e7-8310-65afa8d31484.png)
![snip20171017_5](https://user-images.githubusercontent.com/6339146/31649201-42c30cca-b2d7-11e7-9944-ac4164f59a8d.png)

**Comment by minwoo-jung** [comment]
Please see pinpoint web server log.

And I recommend use 1.6.2 version then using 1.7.0 SNAPSHOT version.
https://github.com/naver/pinpoint/tree/1.6.2

**Comment by jack161641** [comment]
error log below,Is it because there are no database connections configured?

2017-10-17 14:27:23 [DEBUG](c.n.p.w.d.U.insertUserGroup        :110) ==> Bindin
gLog: INSERT INTO user_group (id) VALUES ('alarm') 
2017-10-17 14:27:23 [ERROR](c.n.p.w.c.UserGroupController      :212) Exception occurred while trying to CRUD userGroup information
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception
 is java.sql.SQLException: Cannot create PoolableConnectionFactory (Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.)
### The error may involve com.navercorp.pinpoint.web.dao.UserGroupDao.insertUserGroup-Inline
### The error occurred while setting parameters
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException:
 Cannot create PoolableConnectionFactory (Communications link failure

**Comment by minwoo-jung** [comment]
OK. you should see database configuration.
Refer [document alarm](https://github.com/naver/pinpoint/blob/master/doc/alarm.md#3-configuring-mysql).

**Comment by jack161641** [comment]
Thanks
