### ISSUE TITLE
PinPoint installation on cluster 

### ISSUE THREAD

**Issue by prashantnitt07** [naver/pinpoint#3446]
hi ,
I want pinpoint install to cluster wise.  I have installation HBase database on 10.x.x.x on linux machine and one collector is running on different ip: 10.x.x.y .

what is step for installed pinpoint on cluster wise

**Comment by minwoo-jung** [comment]
Please ref [install document](https://github.com/naver/pinpoint/blob/master/doc/installation.md)

**Comment by minwoo-jung** [comment]
Leave a comment
