### ISSUE TITLE
Nginx connection don't close, Too many connection on Nginx server

### ISSUE THREAD

**Issue by swift1911** [naver/pinpoint#3455]
#### Description

Use Nginx proxy to pinpoint collector,Too many connection on Nginx server

#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):
Centos 6.7
Nginx 1.12.1

#### Additional Info

ss command result:
![image](https://user-images.githubusercontent.com/9301003/31766182-7843590c-b48c-11e7-9a69-7e7ff1c33915.png)

nginx config:
`
upstream pinpoint1.collector.esf.fdd {
        server s1-cat.esf.fdd:9994;
        server s2-cat.esf.fdd:9994;
}
upstream pinpoint2.collector.esf.fdd {
        server s1-cat.esf.fdd:9995;
        server s2-cat.esf.fdd:9995;
}

upstream pinpoint3.collector.esf.fdd {
        server s1-cat.esf.fdd:9996;
        server s2-cat.esf.fdd:9996;
}
server {
        listen 19994;
        proxy_pass pinpoint1.collector.esf.fdd;
}
server {
        listen 19995 udp;
        proxy_pass pinpoint2.collector.esf.fdd;
}
server {
        listen 19996 udp;
        proxy_pass pinpoint3.collector.esf.fdd;
}

user php;
worker_processes 24;
#worker_processes 32;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;
error_log  /data0/logs/nginx/error.log;

pid        logs/nginx.pid;

events {
    worker_connections 10240;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    fastcgi_buffer_size 128k;
    fastcgi_buffers 8 128k;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;
    log_format http-access '$time_iso8601 $status $request_length '
                        '$body_bytes_sent/$bytes_sent $http_host "$request" '
                        '"$http_referer" "$http_user_agent" "$http_x_forwarded_for" $remote_addr "$request_time" "$upstream_response_time" "$upstream_addr"';
    access_log /data0/logs/nginx/access.log http-access;

    sendfile    on;
    tcp_nopush  on;

    #keepalive_timeout       65;
    keepalive_timeout       0;
    client_header_timeout   120s;
    client_body_timeout     120s;
    send_timeout            120s;
    
    client_max_body_size    32m;
    client_body_buffer_size 512k;

    fastcgi_connect_timeout 15;
    fastcgi_read_timeout    120;
    fastcgi_send_timeout    120;

    gzip               on;
    gzip_disable       "msie6";
    gzip_min_length    500;
    gzip_vary          on;
    gzip_proxied       any;
    gzip_comp_level    6;
    gzip_buffers       16 8k;
    gzip_http_version  1.1;
    gzip_types         text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;

    include vhosts/http/*.conf;
    #include vhosts/*.conf;
}

stream {
        log_format myaccess '$remote_addr [$time_local] '
                 '$protocol $status $bytes_sent $bytes_received '
                 '$session_time "$upstream_addr" '
                 '"$upstream_bytes_sent" "$upstream_bytes_received" "$upstream_connect_time" ';
        access_log /data0/logs/nginx/nginx.log myaccess;

        include vhosts/pinpoint.collector.esf.fdd.conf;
}

`

**Comment by koo-taejin** [comment]
hi swift1911

I know that it uses more keepalive option, when using nginx as a proxy server.
please, check this part.

If you need more details help, I recommend to ask nginx community 
nginx community knows nginx configuration better than here. 

thanks.

**Comment by swift1911** [comment]
I use lvs instead , it solves my problem

**Comment by plutonji** [comment]
1. update nginx to 1.15.x
2. you must add `reuseport`: `listen xxxx udp reuseport;`
