### ISSUE TITLE
Could realy postgresql plugin work? 

### ISSUE THREAD

**Issue by xianleizheng** [naver/pinpoint#3459]
Could realy postgresql plugin work? 

#### Description
 all my project work well ,but I can't find my postgresql  picture on ServerMap, and I also can't find SQL in the trace , but i replace the postgres with mysql ,all work well and I can find mysql picture on ServerMap

#### Environment
spring,mybatis,redis,postgres,shiro

**Comment by Xylus** [comment]
Hi @xianleizheng 
What is your postgresql version and what pinpoint version are you using?
Postgresql plugin has been fixed quite a bit via #3159 but it isn't included in the latest version 1.6.2.

You can build from master branch and try it out if you'd like.

**Comment by xianleizheng** [comment]
postgresql's version :9.5,
postgresql jdbc version :9.4.1207
maven pom:
 <dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<version>9.4.1207</version>
		</dependency>
pinpoint version:1.6.3 debug,

**Comment by Xylus** [comment]
Thanks, you'll probably need to wait for 1.7.0 release (should be soon), or build it from source manually using the master branch.

**Comment by Xylus** [comment]
Please feel free to reopen if the issue still persists in master.
