### ISSUE TITLE
./mvnw install -Dmaven.test.skip=true

### ISSUE THREAD

**Issue by dkgnim** [naver/pinpoint#3460]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce (enforce-pinpoint-build-requirements) on project pinpoint: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]

**Comment by Xylus** [comment]
> Look above for specific messages explaining why the rule failed. -> [Help 1]
Also, https://github.com/naver/pinpoint/blob/master/CONTRIBUTING.md#issues
