### ISSUE TITLE
Something on the development of custom filtering rpc requests

### ISSUE THREAD

**Issue by SKingNight** [naver/pinpoint#3467]
Hello
  I am very interested in your project. And I am trying to make some changes to the Pinpoint web project, the current scatter support success and failed two filtering options only. I would like to make some custom development, in which to add some custom request address filtering, such as input an address filter out Select the time point on the address of the address and response time.
Pinpoint web project using augular-js development, I was trying to change it and find this system is more difficult to modify. Could you give me some suggestion to modify it, thank you so much
![image](https://user-images.githubusercontent.com/17975178/31875139-6738d2f6-b7ff-11e7-9554-8d008cfd5bc3.png)

**Comment by emeroad** [comment]
We are switching to the augular.js 2.
So we are postponing UI feature.
If you want to implement scatter chart filter, you can implement the node filter similar to the link filter.

**Comment by SKingNight** [comment]
@emeroad 
I will try it, thank you
