### ISSUE TITLE
TraceV2 folder  having space issues 

### ISSUE THREAD

**Issue by prashantnitt07** [naver/pinpoint#3470]
hi ,
traceV2 folder taking to much space . can be delete/remove for files in TraceV2 . 

please check below path and file  
/app/pinpoint/hbase/data/default/TraceV2

 Oct 16 17:26 8caf13381279f727e7fd4d940a731d66

**Comment by emeroad** [comment]
ref : #2546 How to delete old data in the HBase tables to save disk space?
