### ISSUE TITLE
Pinpoint collector in Cluster 

### ISSUE THREAD

**Issue by prashantnitt07** [naver/pinpoint#3472]
hi , 
I have two linux machine server . 10.x,x.y server have database(hbase) and 10.x.y.z have collector server.

what is config setup for web and pinpoint collector . please share detail

**Comment by koo-taejin** [comment]
hi prashantnitt07

If you look at the default settings (pinpoint-collector.properteis, hbase.properties, pinpoint-web.properties, hbase.properties)
You can see the contents of the approximate.

Please refer to the configuration files and make settings. 
If there are any areas that you do not understand, please ask them questions again.

Note that for the cluster.zookeeper.address configuration, you can use hbase's zookeeper if you do not use additional zookeeper.

thanks.
