### ISSUE TITLE
sampling flag NOT passed to async call

### ISSUE THREAD

**Issue by jiaqifeng** [naver/pinpoint#3477]
#### Description
In HystrixCommandQueueInterceptor and RequestStartAsyncInterceptor which setAsyncTraceId to the target only when traceContext.currentTraceObject() returns a DefaultTrace. Then when current trace is DisableTrace the asyncTraceId would NOT be set into target. And it will cause the child app record a new transaction for the un-sampling root transaction.
As I understand, the sampling flag should be passed through async calls.
While I just read the code and get this conclusion, and I will test it in real apps and update this issues later.

**Comment by Xylus** [comment]
@jiaqifeng Thanks for the heads up.
I'll do some testing around this as well.
Thanks again.

**Comment by jiaqifeng** [comment]
I have tested async servlet in Servlet 3.0 in tomcat 7. I found that pinpoint could not trace the operations executed in threads that application provided to run the async task. In this situation, pinpoint could only trace the operations in tomcat's request handler thread. So the problem I mentioned above does not matter in this case.

Hystrix tested. In A -> B, if a transaction is sampling in A, the sampling flag wont be passed to B and cause a new transaction in B. And this is a common logic for all async situations.

@Xylus How about add a sampling field to DefaultAsyncTraceId to pass the flag?
And I saw flags field in DefaultTraceId which is only passed but no logic depend on it. What is the flag suppose to present? If it is not used could I used it to save the sampling flag?

**Comment by Xylus** [comment]
@jiaqifeng Thanks for reporting.
I've tested it out as well and disabled traces are not getting propagated currently over thread boundaries via async trace.
It looks like we'll need a fix for this.

(On other note, the current async trace code has been overhauled for 1.7.0 (**AsyncContext** and **AsyncId** are used instead of **AsyncTraceId**) but the problem remains.)

**Comment by jiaqifeng** [comment]
@Xylus Yeah, I am working on 1.6.2 code base currently.

**Comment by jiaqifeng** [comment]
Also another things should be considered, when create a new trace in the async thread, IdGenerator should not be called to generate any new id. Or it will cause the tps statistic to be added up twice for one tx.
I am currently working on 1.6.2 which seems has bug on this.
So maybe we should not only pass samplingn flag but also pass id in async context.

**Comment by Xylus** [comment]
@jiaqifeng Doesn't async trace use the reserved `AtomicIdGenerator.UNTRACKED_ID`? (unless it's the API intended for vertx)

**Comment by jiaqifeng** [comment]
@Xylus I am working on 1.6.2 code base, and try to fix this issue. I found it's more complex than I thought.

I call ThreadLocalTraceFactory.disableSampling() in the async thread which cause the tps statistic increased twice. Now I think I should change ThreadLocalTraceFactory.continueAsyncTraceObject(), depends on AsyncTraceId.canSampled() and use UNTRACKED_ID to make things done. You are right.

I also try to pass the transactionId for sampled/unsampled through apps, then the unsampled could be linked together in logs by one transactionId.
