### ISSUE TITLE
How to calculate and get the result 'Gap' ?

### ISSUE THREAD

**Issue by lijunhaos** [naver/pinpoint#3482]
![gap](https://user-images.githubusercontent.com/21354698/31979128-a5291862-b90a-11e7-9063-6bc497df7e1a.png)

**Comment by lijunhaos** [comment]
The explain of 'Gap' on help documents is said: '**Time elapsed between the start of the previous method and entry of this method**', but I can't calculate and get the result.
Help me!  Thanks!

**Comment by Xylus** [comment]
Hi @lijunhaos 
You can calculate the gap by subtracting the start time of the current method by : 
a) parent's start time if the current method is the first child, or 
b) previous method's start time + exec if the current method is not the first child.

**Comment by lijunhaos** [comment]
ok，I got it. Thanks!
