### ISSUE TITLE
Question: How to use agent's docker image? thx

### ISSUE THREAD

**Issue by fengnex** [naver/pinpoint#3489]
This is not an issue, I just want to know:

How to use agent's docker image? thx!

**Comment by fengnex** [comment]
As a base image to let application build image on it?
Within application's image, specify agent's path to use agent, is such a way right?
Any other usages?

**Comment by dawidmalina** [comment]
I usually use volume from with docker compose
 Check my example: https://github.com/dawidmalina/docker-pinpoint/blob/master/docker-compose-example-app.yml

Hope this will help you.
