### ISSUE TITLE
activemq-client-plugin consumer trace not work on spring DefaultMessageListenerContainer

### ISSUE THREAD

**Issue by nickycheng** [naver/pinpoint#3495]
#### Description

the activemq-client-plugin lost trace info when spring using DefaultMessageListenerContainer.

#### Environment

* Pinpoint version:1.6.2
* OS, WAS, affected library, etc: centos 6/ tomcat 7 / jdk8
* Additional details (e.g. how your collector/web is set up): NA

#### Additional Info

When using DefaultMessageListenerContainer, in the class code that implements MessageLister, the tracing information is empty. The thread is not a thread generated by ActiveMq, but a thread created by spring itself to process message consumption.

**Comment by Xylus** [comment]
Hi @nickycheng 
Looks like you're right! The activemq-client-plugin currently seems to be missing trace propagation when the consumer asynchronously consumes (ie dequeue) the message from the message dispatch channel.
I'll try to get this fixed before 1.7.0 is released.
Thanks for reporting!

**Comment by Xylus** [comment]
@nickycheng 
A fix (hopefully) has been merged to master branch.
Could you try it out if possible? (You'll have to build master from source)

**Comment by nickycheng** [comment]
Thank you, it works!
