### ISSUE TITLE
What was the reason to have limited id to 24 chars?

### ISSUE THREAD

**Issue by dawidmalina** [naver/pinpoint#3504]
I was trying to deploy pinpoint agent with application deployed as pod in kubernetes cluster but i faced issue like this:
```
2017-10-31 13:51:33 [WARN ](com.navercorp.pinpoint.bootstrap.IdValidator) invalid Id. pinpoint.agentId can only contain [a-zA-Z0-9], '.', '-', '_'. maxLength:24 value:rancher-server-1784921979-qw1g1
```
Do you think it can be safely widen in https://github.com/naver/pinpoint/blob/master/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/IdValidator.java#L33

**Comment by emeroad** [comment]
We are limiting the size of the ID for performance and range scan.
In the future, we will change the agent id to the reference id.

**Comment by dawidmalina** [comment]
@emeroad any estimation when this future can be implemented? It will allow us to use pinpoint with microservices inside kubernetes which is very popular this days and for sure this will be very atractive addons for pinpoint.

**Comment by dawidmalina** [comment]
@emeroad od @Xylus maybe ability to define this limit via config file (where 24 chars will be default) could be nice compromise? I really propose to implement such change. I can drop a pull request but first would like to have yours opinion.

**Comment by emeroad** [comment]
The AgentId consists of row key in hbase, which affects performance.
Many changes are required for option support.
 - This change affects all components(web, collector, agent, flink, thrift datatype ~~)

We recommend that you shorten agentId to within 24 characters.
In my opinion, it would be better to use a shell script to create conversion rules.
 - We are converting the agentId in a shell script.

**Comment by emeroad** [comment]
The id assignment specification is as follows, and the specification may change in the future.

![image](https://user-images.githubusercontent.com/7564547/35029963-aabf540c-fba0-11e7-879d-4a30ecf8f3a2.png)

- draw io link : 
https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=collector-level-Id-allocation-specv2-spec.xml#R3Vpbb6s4EP41kXYfWgUIuTw27Tm752GlqunRnn10jAuogKkxbbK%2FfsdgE7CdlqYkzbaKVHt8%2F%2BbimTEj7zrd%2FMFQHv1FA5KM3HGwGXk3I9d1Ju4U%2FgnKtqbMHb8mhCwOZKcdYRX%2FSyRxLKllHJCi05FTmvA47xIxzTKCeYeGGKMv3W4PNOmumqOQGIQVRolJ%2FTsOeCSpzni8a%2FiTxGEkl577smGN8GPIaJnJ9Uau91D91c0pUnPJ%2FkWEAvrSInnfRt41o5TXpXRzTRKBrYKtHvd9T2uzb0Yy3meAWw94Rkkpj34fkQrYJAFgKYMyI5jEz8AOwFZsOUfZpdw93yrEXqKYk1WOsKi%2FgFSMvGXE0wRqDhRRkdd8eog3BNZeynUJ42Szd%2B9OgwhIGqEp4WwLXeQAV3FDCtlUVl92HFtIUtTilaIhKSNhM%2FEOJyhIqOyweQZsdyRPxOFBUCsAC87iLKyHiC3Bjmr4yix%2BKolqiLNmREJB%2FgT0CEfkLAD2Zp8G8MQA2ACEZMGVUHWo4QQVRYy7iMAh2fYXVMaq8o%2BoXPoNOCQwrIAGDSxIS4ZJR1k4YiHhLUEwAWwh5FsQUjRGEsRBtbr2ywKbXOGWxrC9vQrQWBU1Rb15OaptBfSJ%2FO5EzkybqD6yMVHFxebYvRg7HYCxm5j%2FapU%2FylbPZOvsS7DVn2psHfvHYuvMYOuKIIaj6vJlbbP348ZgOItoui5hT8s3jNwANs13NZvmGzZtbmHtfACbtjg%2F0Z%2BZou98DZM2XZxM9pXTOsxlVXFzd121mC6bJNudQZk%2B%2BUymG3ZqMpDBc72j3WOOY2H6NAFglkH8DMVQFH92nL2AVk50RsWWgY8Fv1Rj1kwNURTYQGuiKxCZMLO5kJqggWXkgxvNiet3GTQzPUHHtQiIzshDzKZjxih3BG9xUiHwYLjUFbCF6UAfBZmpZq9OCowZhawgYtvFIJZQI1qjQlDAFD2S7VlEGTPN%2BTxhlOGYYYYZ%2FqJK9VT0y1AW0BTUEqUCm2xd5C2lbWlsA36Ns02pzwF93R9qJPMU8PsG%2FD%2BLOmquBVhJK%2BI0hRvTHdOcMLhpKIjydQ8e1CfltEIZNOPS0ucerZNdg0huqBYIw%2FHjVRbclvy331scbPfZx9j%2FC7s9i8E6GrsHjP1MX%2Bg1D2p0kJ%2BkrEPHUfLt8J7IUdISMs70UO940p1o4vdzlIA3aNvqlosOhSEE73SlzMBI3WP7b7AzCiGb%2BgliSLXUOetQR18Wn6ov%2FqIr5ofqiz6R73yivri20OMIMjBU2lTp9%2FkEnMbLgZ7v7CsXnpZlcHsmTvfLRb%2FAduqPX93XRD%2FgO%2Fu7c18T0nrHB4us6el1XDHVcfpUipevZcgvCoYv8I6iu1avDcsPG1ZdFq%2BP7JLeCtp7HfHAM2L4cbZ%2FbNtJ%2FY7ihASNJ4xAb173ZvsebHjqmzF7wRl9JNc0gdjMu8loBj2XD3GSaCSUiHwJWD%2BwTAToS3HlxxglV7IhjYNALGN1GKoXXOFzt66%2Bjz2lzTWFtIRZjs1p0DNYBzkNQzjee1yDY2SlrRfGWaWlZ4c6EvpL2%2BzDjoR9ndmim7FTF8hgBt3y4FPZlfGqxJgUxddV5bnTZeHEMZ%2BQJhZR1Dl90HcHtndx4366rWKnO%2FJUxoykpBKUN%2B8nLWH940ZkvNKyEEK1FpQ6CwE8FV%2FrqGc9hrKw%2BtwBVx%2BF9FzlQhgFkeYZeVciyitFeNdz7L0ltVmn6MRJBScZrQUQlL5CQBQj4INoIwz2naIMk745uaOkjbU4vpGNlgh5trRx8wHSO4QIqrvviWpV33205X37Dw%3D%3D

**Comment by dawidmalina** [comment]
#3864
