### ISSUE TITLE
Spring boot ,unable to collect data to submit to the controller

### ISSUE THREAD

**Issue by jacobsy** [naver/pinpoint#3507]
#### Description

Unable to collect the trace data

#### Environment

jdk                          ：1.8.0_x
system                    ：linux
springboot             ：spring boot 1.3.3
Pinpoint version:    ：agent 1.5.2 ,collector 1.5.2 ,web 1.5.2
hbase                     ：1.0.3

#### Additional Info

Startup:
java -jar -javaagent:/usr/local/pinpoint-agent-1.5.2/pinpoint-bootstrap-1.5.2.jar 
-Dpinpoint.agentId=uni076_norten 
-Dpinpoint.applicationName=uni076_norten  ./norten.jar

![image](https://user-images.githubusercontent.com/2225457/32258684-e893e748-bef6-11e7-8328-86285f1e0f6b.png)

**Comment by jacobsy** [comment]
pp-agent log
[uni076_norten-pinpoint.log](https://github.com/naver/pinpoint/files/1433031/uni076_norten-pinpoint.log)

**Comment by jacobsy** [comment]
Debug log
[test_norten-pinpoint.log](https://github.com/naver/pinpoint/files/1433123/test_norten-pinpoint.log)

**Comment by Xylus** [comment]
Hi @jacobsy 
It looks like you have multiple dependencies on Tomcat, Undertow, Jboss, etc.
Which servlet container are you actually using/trying to trace with Spring Boot?

**Comment by Xylus** [comment]
Please feel free to reopen the issue for further discussion.

**Comment by vianppz** [comment]
I have the same problem, - - ！

java -Djava.security.egd=file:/dev/./urandom -javaagent:/pinpoint-agent/pinpoint-bootstrap-1.7.0-RC1.jar -Dpinpoint.agentId=spring-boot-app -Dpinpoint.applicationName=spring-boot-app -jar /app.war

![default](https://user-images.githubusercontent.com/9260334/33925347-b3f7de92-e014-11e7-8b2d-7903e64289db.png)

no information

**Comment by Xylus** [comment]
Hi @vianppz 
Are you running Tomcat in Spring Boot?
Also, do the stat charts in inspector view have data?

**Comment by vianppz** [comment]
@Xylus undertow to tomcat is ok,thk!

**Comment by Xylus** [comment]
@vianppz So you're running undertow on Spring Boot, right? 
If so, we don't support undertow - https://github.com/naver/pinpoint#supported-modules

**Comment by imvv1993** [comment]
@Xylus If your team can provide support for springboot+Undertow, thank you very much!
I don't want to use Pinpoint just because of this problem.

**Comment by imvv1993** [comment]
@Xylus Your project is excellent.
