### ISSUE TITLE
[HELP] the API-METADATA-NOT-FOUND problem

### ISSUE THREAD

**Issue by geniuszhe** [naver/pinpoint#351]
when I use agent to my application ,I got the callback is API-METADATA-NOT-FOUND. how can I sovle the problem ?
![20150421143643](https://cloud.githubusercontent.com/assets/10541171/7246754/e621fcd0-e833-11e4-9fd1-ce2ec02a81ba.png)

**Comment by Xylus** [comment]
Hi, 
It seems like the agent failed in sending the metadata to the collector. The agent sends the metadata right after it is loaded and retries a couple time if it fails. If there was a problem in the network, or if the hbase(or the collector) was not running properly during this time, the metadata is lost until the agent is restarted.
Restarting your agent and making sure the metadata are sent should solve the issue.

**Comment by geniuszhe** [comment]
Thank you, it's indeed help

**Comment by Xylus** [comment]
Awesome!
Let us know if you've got more questions.
