### ISSUE TITLE
Not synchronized to Web

### ISSUE THREAD

**Issue by zj4775** [naver/pinpoint#3517]
I use the 1.6.2 version ,I call my service，but when i open the pinpoint-web ,these data is not synchronized ,Occasionally can synchronized .But I use 1.5.2 version these data always can be synchronized  in real time ,why?

**Comment by toxie641517** [comment]
do you change the config in the agent? 

profiler.sampling.rate=1

**Comment by Functor10** [comment]
Maybe because your browser is not compatible or the version is too old, I just updated my Chrome then the pinpoint-web is working normally now.
