### ISSUE TITLE
Would you be so kind as to explain meaning of two fields sequence_count and timing_count in mysql table alarm_history of web

### ISSUE THREAD

**Issue by fengnex** [naver/pinpoint#3529]
Hello:

This is not a bug report, it's just a question.

There's no any document or comment about the two fields: sequence_count and timing_count in mysql table alarm_history in the web project, some people want to know their meanings and difference.

So, would you like explain them please? Thanks.

**Comment by minwoo-jung** [comment]
I updated guide for [transmission frequency](https://github.com/naver/pinpoint/commit/f3bd2a5e17739619ca8b63dca25b5d56614f785a)
