### ISSUE TITLE
Pinpoint Email notification configuration

### ISSUE THREAD

**Issue by GyaneshRahatekar** [naver/pinpoint#3534]
#### Environment

* Pinpoint version: 1.6.2
* OS, WAS, affected library, etc: NA
* Additional details (e.g. how your collector/web is set up): Single Mode with SQL DB

#### Additional Info
We have configure SQL DB for User Group and Alaram configuration  all are works fine need your support for EMAIL Notification and SMTP configuration

**Comment by GyaneshRahatekar** [comment]
we have configure pinpoint with SQL DB for user group creation and alarm but not able to configure Email notification . need your help and support to configure email notification ( SMTP ) .

**Comment by minwoo-jung** [comment]
Please ref https://github.com/naver/pinpoint/blob/master/doc/alarm.md.

Now email sender did not exist, We are consider adding default email sender with smtp.
