### ISSUE TITLE
Can I rename the table name in hbase?

### ISSUE THREAD

**Issue by toxie641517** [naver/pinpoint#3535]
hi, I have downloaded the hbase-create.hbase script, I wonder if I can rename the table name because our team is assigned only one namespace in hbase. Can I rename the hbase table name and reconfig in somewhere?  Thanks so much!!

**Comment by minwoo-jung** [comment]
Unfortunately, you simply couldn't change hbase table name. You see and edit [HbaseTables class](https://github.com/naver/pinpoint/blob/master/commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HBaseTables.java) / XxxDao class

**Comment by toxie641517** [comment]
@minwoo-jung thank you :)
