### ISSUE TITLE
How many calls type capture by Pinpoint

### ISSUE THREAD

**Issue by GyaneshRahatekar** [naver/pinpoint#3537]
Question 

#### Description
How many calls type captured by Pinpoint  

#### Environment
I have tested this tool with oracle java, default captured only serve-let calls
* Pinpoint version: 1.6.2
* OS, WAS, affected library, etc: NA
* Additional details (e.g. how your collector/web is set up): Single Node

#### Additional Info
Info require , how many types of call capture by Pinpoint  ? there is any way to capture all below calls
web Serice 
Pojo
Spring Bean
Ejb
JMS
Binary Remoting

**Comment by minwoo-jung** [comment]
Please ref [supported-modules](https://github.com/naver/pinpoint#supported-modules). We only support above list. 

If you want to profile another library or framewark, ref [Pinpoint Plugin Developer Guide](https://github.com/naver/pinpoint/wiki/Pinpoint-Plugin-Developer-Guide)
