### ISSUE TITLE
SMTP configuration for pinpoint alert 

### ISSUE THREAD

**Issue by prashantnitt07** [naver/pinpoint#3542]
Dear ,
I want to configure SMTP configuration with Pinpoint alert , what is steps or any document for SMTP configuration for linux machine .

Pinpoint version: 1.6.2

**Comment by minwoo-jung** [comment]
Please ref https://github.com/naver/pinpoint/blob/master/doc/alarm.md.

Now email sender did not exist, We are consider adding default email sender with smtp.
