### ISSUE TITLE
Cannot find naver/pinpoint docker image

### ISSUE THREAD

**Issue by insoz** [naver/pinpoint#3551]
docker-compose.yaml cannot pull docker image from docker.io.

I can't find naver namespace on hub.docker.com

**Comment by koo-taejin** [comment]
hi insoz 

There is no official docker image that we provide.
We recommend that you change the configuration of docker-compose.yml in the source code and build and use it.

for reference, it is no official docker image, but https://hub.docker.com/r/yous/pinpoint/ provided until 1.6.1.

**Comment by insoz** [comment]
OK , i get it .

If i want to change the zookeeper address in hbase,  how do i modify it?

**Comment by koo-taejin** [comment]
you can set variable in https://github.com/naver/pinpoint/blob/master/docker-compose.yml.

To change the zookeeper address, change the variables HBASE_HOST, HBASE_PORT, and CLUSTER_ZOOKEEPER_ADDRESS.

thanks.

**Comment by RoySRose** [comment]
@insoz 
[Official Docker Image](https://github.com/naver/pinpoint-docker) is now supported.
