### ISSUE TITLE
Can I deploy two collector?

### ISSUE THREAD

**Issue by toxie641517** [naver/pinpoint#3556]
Can I deploy two collector to balance? And set profiler.collector.ip=XXX,XXX, split by comma in the agent config? Thanks:)

**Comment by toxie641517** [comment]
Another question, can I use domain name in the profiler.collector.ip section, like profiler.collector.ip= www.google.cn/XXX?

**Comment by koo-taejin** [comment]
hi toxie641517 

You can expand the collector by deploying multiple collectors.

And It is possible to set profiler.collector.ip configuration as domain.
But, We do not support profiler.collector.ip configuration split by "," chracter.

thanks.

**Comment by toxie641517** [comment]
@koo-taejin thanks for your kindly reply. How can I support multiple collectors with using profiler.collector.ip, as it can only accept one ip, is there another way to config multiple collectors?

**Comment by koo-taejin** [comment]
Unfortunately, now only solution is having a domain.
If it is difficult to set it as an external server, 
I recommend to build proxy server in front of the collector or to edit the hosts file in local server.

It is not the same function as what you said, but I have planed about a substitute function.
But workload is large and I have not even decided whether to work or not.
When I start working, I will let you know in a comment.

**Comment by toxie641517** [comment]
@koo-taejin thank you :)

**Comment by guanlele** [comment]
lvs can be used to load balance the collectors,  both tcp and udp  are supported by lvs
