### ISSUE TITLE
Can not track the APIs of Thrift but Dubbo & mysql is unknown

### ISSUE THREAD

**Issue by jweikai** [naver/pinpoint#3558]
Hi, pinpoint team.
OS: CentOS release 6.7 (Final)
java version: 1.8.0_121
pinpoint: 1.6.2

I have two questions.

Firstly,I have a service named user-center-web which provides some APIs including Thrift and Dubbo.And I sure that they are both called normally.Strangely, In the diagram of pinpoint,there is only called informations of Dubbo.Why no Thrift?  
![image](https://user-images.githubusercontent.com/10485438/32882431-4997e9e6-caef-11e7-81d8-9255c953fd17.png)

But I can see the thrift interface call in my service log.
![image](https://user-images.githubusercontent.com/10485438/32882493-7cd3eddc-caef-11e7-8bfd-3e610bc9ea4b.png)

Here is the primary Thrift implement class of  my service user-center-web:
 
![image](https://user-images.githubusercontent.com/10485438/32882238-ae33b980-caee-11e7-8536-b8774b7fd7f5.png)

I thought it was not configured @Component, thrift interface did not load into. So I did the following.
![image](https://user-images.githubusercontent.com/10485438/32882378-205b0f86-caef-11e7-8062-fcc9bd263b83.png)
![image](https://user-images.githubusercontent.com/10485438/32883114-6c95df28-caf1-11e7-993a-6a4f8dbdd401.png)

 At the beginning ,I saw the log of pinpoint and found that it didn’t load the UserCenterApiImpl class. So, I changed the profiler.spring.beans.1.annotation like picture above. After changing and rebooting, I found that the log loaded the UserCenterApiImpl class normally.However ,there is still no Thrift called information in my diagram of pinpoint webui.

And another question, In the diagram of pinpoint, this should show the location of the MySQL, however,it shows UNKNOWN_DB, I’m puzzled?   
![image](https://user-images.githubusercontent.com/10485438/32882211-965691ac-caee-11e7-9c8a-a2a35997a4a0.png)

I have just changed two positions in my pinpoint.config.
The first palce , I set profiler.sampling.rate=1.
And secondly，as the following :
![image](https://user-images.githubusercontent.com/10485438/32882516-94551f1c-caef-11e7-8d47-dbf3037f18cd.png)
<mysql.version>5.1.35</mysql.version>

Thanks a lot.

**Comment by Xylus** [comment]
Hi @jweikai 
Thanks for the detailed explanation.

It looks like **UserCenterApiImpl** is a custom Thrift client implementation (not the auto-generated one that extends **TServiceClient**. If this is correct, Thrift calls won't be traced as Thrift plugin transforms these classes to generate traces. (Please refer to #329 for more details)

As for the *UNKNOWN_DB* issue, could you check your agent (debug-level) log to see if there's anything wrong? Or could you post the agent log (again, debug-level) that includes the part where jdbc driver creates connections?

Thanks

**Comment by jweikai** [comment]
thank you answer.
I read the entire issue before the question finished, but did not see your issue link.Today there is training, and then paste the results.
Thanks

**Comment by jweikai** [comment]
Hi @Xylus 
![image](https://user-images.githubusercontent.com/10485438/32940900-fb430282-cbbe-11e7-9645-4fe6063c7ac5.png)
![image](https://user-images.githubusercontent.com/10485438/32940912-00f4024e-cbbf-11e7-8e94-e29539d7c080.png)
It seems that my thrift interface should be tracked.

**Contrast another project**

Forgot to say before, if my upstream service is called via thrift, it will be traced.such that.
![image](https://user-images.githubusercontent.com/10485438/32941295-4718a1c0-cbc0-11e7-8ca4-0cc235553b10.png)
![image](https://user-images.githubusercontent.com/10485438/32941306-52522098-cbc0-11e7-9e54-f00c8d7885f0.png)

**Comment by jweikai** [comment]
Hi @Xylus 

This is because I cleared hbase data lead to it?
![image](https://user-images.githubusercontent.com/10485438/32942406-f269e176-cbc3-11e7-9bf3-99f6698cf810.png)

That mysql problem in the new pinpoint environment showed success. T_T
Thanks for your reply.

**Comment by Xylus** [comment]
@jweikai 
Hmm, I don't get it.
So you're trying to trace incoming Thrift calls (**UserCenterApi.Processor**)? Not Thrift client traces?

**Comment by jweikai** [comment]
Hi, @Xylus  
[qa-javaserver-2118874-pinpoint.log](https://github.com/naver/pinpoint/files/1484406/qa-javaserver-2118874-pinpoint.log)
Sorry, forgot to upload

**Comment by jweikai** [comment]
@Xylus 
mysql problem solve. https://github.com/naver/pinpoint/issues/3222

**Comment by Xylus** [comment]
@jweikai Glad to hear you've worked out the mysql issue.
For Thrift, are you trying to trace incoming calls? or outgoing calls?

**Comment by jweikai** [comment]
Hi, @Xylus 
Thanks for your support.
Sorry,sorry...   
My TL overridden org.apache.thrift.TBaseProcessor this class. Cause the data is not collected. All the problems have been solved. ^_^

**Comment by Xylus** [comment]
yay :+1:
