### ISSUE TITLE
Question for help

### ISSUE THREAD

**Issue by Super4You** [naver/pinpoint#3559]
Hello, When develop pinpoint plugin for HTTP framework of myself company,met a problem, receives the request and execute business are  asynchronous that use queue to realize, receives the request and the execute business thread  is not one thread.So that thead of receive the request  create "Trace" in the ThreadLocal for C3P0, DB2 plugin can't get,  the topology and call tree will not display properly, you encounter this kind of question will be how to deal with. Looking forward to reply.Thank you!

**Comment by Xylus** [comment]
Hi @Super4You 
Asynchronous trace propagation is not automatic, so you'll need to make a plugin for your specific library that invokes asynchronous methods to propagate traces over thread boundaries.
The idea behind this is to have the initiating thread's method to create **AsyncContext** (via `SpanEventRecorder.recordNextAsyncContext()`) and inject this into an object that will be passed on to the executing thread's method. This method will then use **AsyncContext** to create a trace to continue tracing.
You can check out other plugins that utilizes this to get a feel for how it works.
Thanks

**Comment by Super4You** [comment]
Hi,@Xylus
The pinpoint api that you recommend AsyncContext  and SpanEventRecorder.recordNextAsyncContext() are not exsit in 1.6.2.  Look up  the API that you said was available in 1.7.0.   What can I use in the 1.6.2? Thanks for your reply.

**Comment by Xylus** [comment]
For 1.6.2, you can use `Trace.getAsyncTraceId()` and `SpanEventRecorder.recordNextAsyncId()` variants. Note that these APIs are deprecated as of 1.7.0 in favor of the aforementioned `SpanEventRecorder.recordNextAsyncContext()`.

**Comment by Super4You** [comment]
OK,Thanks for your recommend ,and what time does 1.7.0+ release stable version，already forced to wait.Thanks for your reply.

**Comment by Xylus** [comment]
@Super4You 1.7.0 will be released in a week or 2 (The RC process is currently underway)

**Comment by Super4You** [comment]
I am very glad to communicate with you and have benefited a lot. Thank you again for your support.Wish you good luck and good health.
