### ISSUE TITLE
Liberty-Plugin 개발 시 classLoader 가 TraceMetadataProvider를 찾지 못하는 문제

### ISSUE THREAD

**Issue by core279** [naver/pinpoint#3560]
#### Description

안녕하세요.

IBM 의 Liberty-Plugin 개발 시 classLoader 가 TraceMetadataProvider를 찾지 못하는 문제가 있습니다.
Plugin 개발가이드 대로 plugin을 개발하였고. 아주 간단한 TestInterceptor를 만들어 테스트 하는 중.
아래와 같은 에러가 발생하였습니다.

[agent log : [liberty-agent01-pinpoint.log](https://github.com/naver/pinpoint/files/1479813/liberty-agent01-pinpoint.log)]

Exception 메세지를 보면,

Failed to load plugin class com.navercorp.pinpoint.plugin.liberty.interceptor.TestInterceptor with classLoader org.eclipse.osgi.internal.loader.EquinoxClassLoader@1e3bc718[com.ibm.ws.webcontainer:1.1.18.cl170320170927-1854(id=69)]
**Caused by: java.lang.ClassNotFoundException: com.navercorp.pinpoint.common.trace.TraceMetadataProvider cannot be found by com.ibm.ws.webcontainer_1.1.18.cl170320170927-1854**

여기에서 com.ibm.ws.webcontainer:1.1.18 은 interceptor 를 넣을 대상 클래스인 com.ibm.ws.webcontainer.WebContainer 를 담고 있는 jar파일입니다.

제가 구현한 ProfilePlugin의  addServerInterceptor 메소드는 아래와 같습니다. 여기의 **3.Add interceptor 에서 에러발생**

  ```
  private void addServerInterceptor(){

        transformTemplate.transform("com.ibm.ws.webcontainer.WebContainer", new TransformCallback() {
            @Override
            public byte[] doInTransform(Instrumentor instrumentor, ClassLoader classLoader, String className, Class<?> classBeingRedefined, ProtectionDomain protectionDomain, byte[] classfileBuffer) throws InstrumentException {

                // 1. Get InstrumentClass of the target class
                InstrumentClass target = instrumentor.getInstrumentClass(classLoader, className, classfileBuffer);

                // 2. Get InstrumentMethod of the target method.
                InstrumentMethod handleMethodEditorBuilder = target.getDeclaredMethod("handleRequest", "com.ibm.websphere.servlet.request.IRequest", "com.ibm.websphere.servlet.response.IResponse");

                if (handleMethodEditorBuilder != null) {
                    logger.info("getDeclaredMethod : true");

                    // 3. Add interceptor. The first argument is FQN of the interceptor class, followed by arguments for the interceptor's constructor.
                    handleMethodEditorBuilder.addInterceptor("com.navercorp.pinpoint.plugin.liberty.interceptor.TestInterceptor", va(LibertyConstants.LIBERTY));

                    // 4. Return resulting byte code.
                    return target.toBytecode();
                }else{
                    logger.info("getDeclaredMethod : false");
                }
                return target.toBytecode();
            }
        });
    }
```

Liberty 의 메인 클래스(com.ibm.ws.webcontainer.WebContainer)가 pinpoint 의 TraceMetadataProvider 를 찾지 못하고,  ClassNotFoundException 이 나는 현상은 도무지 이해되지 않습니다. 
TraceMetadataProvider 를 담고 있는 pinpoint-commons-1.6.2.jar 파일은 분명히 Liberty 프로세스의  lib path 에 포함되어 있다고 생각되기 때문입니다.
심지어는 pinpoint-commons-1.6.2.jar 파일을 JRE 의 lib/ext 에 카피를 해두어도  동일하고 ClassNotFound 가 발생했습니다.

Liberty 의 메인 클래스 타입인  org.eclipse.osgi.internal.loader.EquinoxClassLoader 의 특이점이 있는 것인지.. 아니면 다른 어떤 문제인지..

도움 말씀 좀 부탁드리겠습니다.

#### Environment

* Pinpoint version: 1.6.2
* OS, WAS, affected library, etc: IBM Liberty 17.0.0.3
* Additional details (e.g. how your collector/web is set up):

**Comment by emeroad** [comment]
에러메시지에 OSGI classLoader 가 보이는데.
 - org.eclipse.osgi.internal.loader.EquinoxClassLoader

OSGI의 class delegation 설정이 필요할수 있습니다.

보통 아래와 같은 설정이 필요한데. WAS 마다 설정은 다를수 있으니 관련 옵션을 찾아보시면 될것 같습니다. 
https://github.com/naver/pinpoint/wiki/FAQ#how-to-set-java-runtime-option-when-using-atlassian-osgi

OSGI 설정에 넣어야 될 패키지 명은 아래와 같습니다.
https://github.com/naver/pinpoint/tree/master/plugins/jboss
 - com.navercorp.pinpoint.bootstrap,com.navercorp.pinpoint.common,com.navercorp.pinpoint.exception"

**Comment by core279** [comment]
안녕하세요. 
말씀하신 부분을 찾아.
Liberty server (defaultServer) 에 bootstrap.properties 파일 생성후 org.osgi.framework.bootdelegation 옵션을 추가후.. 제가만든 interceptor가 로드되는것 까지 잘 확인되었습니다.
`org.osgi.framework.bootdelegation=com.navercorp.pinpoint.bootstrap.*,com.navercorp.pinpoint.common.*,com.navercorp.pinpoint.exception.*`
정말 감사드립니다. 덕분에 오늘은 야근을 안하겠군요! ㅎ
