### ISSUE TITLE
Can I config the slow count alarm request time?

### ISSUE THREAD

**Issue by WangHouLing** [naver/pinpoint#3566]
Hi,
#### Description
Excuse me, If I remember is not  incorrectly, the condition that triggers the slow count alarm is that the request time is longer than 5 seconds. I don't know if it's possible to configure this threshold time. In fact, different applications have different slow request time limits.
I will appreciate if you can help me.

#### Environment
* Pinpoint version: 1.6.2
* OS: Centos7

Thanks.

**Comment by minwoo-jung** [comment]
It couldn't configured threshold time for slow count alarm. 
Because slow count alarm logic is based on the statistics data of pinpoint agent. it is difficult to change standard of slow time.

**Comment by WangHouLing** [comment]
@minwoo-jung Ok, Thanks for your reply！
Will the default time of slow count alarm is 5 seconds?

**Comment by minwoo-jung** [comment]
Yes, you're right.

**Comment by WangHouLing** [comment]
Thank you.
Excuse me, If it is possible to change source code to achieve this function, could you provide a general overview to configured threshold time for slow count alarm by changing the source code? For example, If I need to change the code for the pinpoint agent or only need to change pinpoint web logical code? Please help me!
