### ISSUE TITLE
How can I disable the stdout output of the agent?

### ISSUE THREAD

**Issue by toxie641517** [naver/pinpoint#3572]
I have attached the pinpoint agent to our app when it starts, the command as follow, everything is fine
java -jar -Xms900m -Xmx900m -javaagent:./pinpoint-bootstrap-1.6.2.jar  XXXXX

But we find some debug logs comes out, how can we disable the console output of the agent? I search the pinpoint.config, but no clues. 
You can refer to the picture as follow:

![pic](https://user-images.githubusercontent.com/10704862/33010476-3ed05512-cda0-11e7-86c2-898f5451a211.png)

**Comment by emeroad** [comment]
ref : https://github.com/naver/pinpoint/wiki/FAQ#how-do-i-change-agents-log-level
