### ISSUE TITLE
HBase SocketException

### ISSUE THREAD

**Issue by mabunixda** [naver/pinpoint#3581]
pinpoint is running fine for a few weeks, but since a few days we can see the following behavior accessing a transaction detail. This behavior is for old - already working - and newer transactions.

I am running pinpoint within docker-containers and we did not update the containers for the last few weeks. They were once restarted because of a host security update ( ubuntu ) 2 weeks ago.

`web          | 2017-11-21 07:34:56 [WARN ](.n.p.w.c.ControllerExceptionHandler:52 ) Failed to execute controller methods. message:callTimeout=10000, callDuration=18220: row 'app2ï¿½ï¿½ï¿½lï¿½G,ï¿½ï¿½ï¿½ï¿½' on table 'SqlMetaData_Ver2' at region=SqlMetaData_Ver2,\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1492087928872.842688a0d9348b4a5915051294858967., hostname=31b52ca083ed,41681,1509976599220, seqNum=21585; nested exception is java.net.SocketTimeoutException: callTimeout=10000, callDuration=18220: row 'app2ï¿½ï¿½ï¿½lï¿½G,ï¿½ï¿½ï¿½ï¿½' on table 'SqlMetaData_Ver2' at region=SqlMetaData_Ver2,\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1492087928872.842688a0d9348b4a5915051294858967., hostname=31b52ca083ed,41681,1509976599220, seqNum=21585, request:{method=GET, heads={x-real-ip=[10.12.69.154], referer=[https://apm/index.html?vs=1511249974792], accept-language=[de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4,ru;q=0.2], cookie=[CSRF-TOKEN=4668b6c2a5fee4d11b2060fcf6818856866b4369c34c0e6ffeb88d2400f74dc0; iPlanetDirectoryPro=AQIC5wM2LY4SfczDg5INYmU9jn82UTLal7ixbnn5POWRpA4.*AAJTSQACMDIAAlNLABQtODcxMzgyMjUyMDE2MzMxNjM1NgACUzEAAjAx*; AMAuthCookie=AQIC5wM2LY4SfcxbP80Mr4B-ME68FvXbOaLQHRkYgjW1eQI.*AAJTSQACMDIAAlNLABMxMDY4MjcwODU2MjkwMDk2ODUwAAJTMQACMDE.*; amlbcookie=01; _gat=1; _ga=GA1.2.1774666974.1509349345; _gid=GA1.2.1246908017.1511248000], host=[apm], x-requested-with=[XMLHttpRequest], connection=[upgrade], x-forwarded-for=[10.12.69.154], accept-encoding=[gzip, deflate, br], accept=[application/json, text/javascript, */*; q=0.01], user-agent=[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36]}, parameters={spanId=[-7499226902913717306], traceId=[app2^1510001522899^699029], focusTimestamp=[1511247737987], agentId=[app2], _=[1511249975611]}, url=http://apm/transactionInfo.pinpoint}.
web          | com.navercorp.pinpoint.common.hbase.HbaseSystemException: callTimeout=10000, callDuration=18220: row 'app2ï¿½ï¿½ï¿½lï¿½G,ï¿½ï¿½ï¿½ï¿½' on table 'SqlMetaData_Ver2' at region=SqlMetaData_Ver2,\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1492087928872.842688a0d9348b4a5915051294858967., hostname=31b52ca083ed,41681,1509976599220, seqNum=21585; nested exception is java.net.SocketTimeoutException: callTimeout=10000, callDuration=18220: row 'app2ï¿½ï¿½ï¿½lï¿½G,ï¿½ï¿½ï¿½ï¿½' on table 'SqlMetaData_Ver2' at region=SqlMetaData_Ver2,\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1492087928872.842688a0d9348b4a5915051294858967., hostname=31b52ca083ed,41681,1509976599220, seqNum=21585
web          | 	at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.execute(HbaseTemplate2.java:775)
web          | 	at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.get(HbaseTemplate2.java:284)
web          | 	at com.navercorp.pinpoint.web.dao.hbase.HbaseSqlMetaDataDao.getSqlMetaData(HbaseSqlMetaDataDao.java:62)
web          | 	at com.navercorp.pinpoint.web.service.SpanServiceImpl$1.replacement(SpanServiceImpl.java:141)
web          | 	at com.navercorp.pinpoint.web.service.SpanServiceImpl.transitionAnnotation(SpanServiceImpl.java:119)
web          | 	at com.navercorp.pinpoint.web.service.SpanServiceImpl.transitionSqlId(SpanServiceImpl.java:124)
web          | 	at com.navercorp.pinpoint.web.service.SpanServiceImpl.selectSpan(SpanServiceImpl.java:103)
web          | 	at com.navercorp.pinpoint.web.controller.BusinessTransactionController.transactionInfo(BusinessTransactionController.java:98)
web          | 	at sun.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
web          | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
web          | 	at java.lang.reflect.Method.invoke(Method.java:498)
web          | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
web          | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
web          | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
web          | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
web          | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
web          | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
web          | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
web          | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
web          | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
web          | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
web          | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
web          | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
web          | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
web          | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
web          | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
web          | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
web          | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
web          | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
web          | 	at com.navercorp.pinpoint.web.servlet.NoCacheFilter.doFilter(NoCacheFilter.java:50)
web          | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
web          | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
web          | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
web          | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
web          | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
web          | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
web          | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
web          | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
web          | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
web          | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
web          | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
web          | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
web          | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
web          | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
web          | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
web          | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
web          | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
web          | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
web          | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
web          | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
web          | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
web          | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
web          | 	at java.lang.Thread.run(Thread.java:748)
web          | Caused by: java.net.SocketTimeoutException: callTimeout=10000, callDuration=18220: row 'app2ï¿½ï¿½ï¿½lï¿½G,ï¿½ï¿½ï¿½ï¿½' on table 'SqlMetaData_Ver2' at region=SqlMetaData_Ver2,\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1492087928872.842688a0d9348b4a5915051294858967., hostname=31b52ca083ed,41681,1509976599220, seqNum=21585
web          | 	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:169)
web          | 	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:865)
web          | 	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:831)
web          | 	at com.navercorp.pinpoint.common.hbase.HbaseTemplate2$4.doInTable(HbaseTemplate2.java:287)
web          | 	at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.execute(HbaseTemplate2.java:766)
web          | 	... 52 more
web          | Caused by: java.net.ConnectException: Connection refused
web          | 	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
web          | 	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
web          | 	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
web          | 	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:529)
web          | 	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:493)
web          | 	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.setupConnection(RpcClientImpl.java:416)
web          | 	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.setupIOstreams(RpcClientImpl.java:722)
web          | 	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.writeRequest(RpcClientImpl.java:906)
web          | 	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.tracedWriteRequest(RpcClientImpl.java:873)
web          | 	at org.apache.hadoop.hbase.ipc.RpcClientImpl.call(RpcClientImpl.java:1241)
web          | 	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:227)
web          | 	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:336)
web          | 	at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$BlockingStub.get(ClientProtos.java:34070)
web          | 	at org.apache.hadoop.hbase.client.HTable$3.call(HTable.java:857)
web          | 	at org.apache.hadoop.hbase.client.HTable$3.call(HTable.java:848)
web          | 	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:136)
web          | 	... 56 more
`

**Comment by Xylus** [comment]
Hi @mabunixda 
This looks like a hbase issue so you might get a better answer from the hbase community.
That said, maybe check if the machine running pinpoint web can resolve *31b52ca083ed* (hostname)? Pinpoint web must be able to resolve the hostnames of the region servers I think.
