### ISSUE TITLE
Can it support websphere8.5 and db2 9.7？

### ISSUE THREAD

**Issue by saver123sc** [naver/pinpoint#3592]
I have try it,but failed, it can't identified datasource and show the sql when running on the websphere8.5  server

**Comment by saver123sc** [comment]
the pinpoint version is 1.7.0-SNAPSHOT

**Comment by Xylus** [comment]
Hi @saver123sc,
By db2, are you talking about IBM db2 jdbc driver? If so, we don't support it currently.
