### ISSUE TITLE
Datasoure NOT FOUND in pp inspector view

### ISSUE THREAD

**Issue by ecamy** [naver/pinpoint#3594]
#### Description
 Hi, team,  we can see database icons and the number of connections. in the home page, but no found data source when I click the inspector, why?

#### Environment
pp-1.6.1
centos6.5
sqlserver2008 on windows

**Comment by ecamy** [comment]
Additionally, database connection pool: c3p0

**Comment by koo-taejin** [comment]
hi ecamy

We do not support c3p0.
The currently supported DataSource Plugins are dbcp, dbcp2, hikaricp.

thanks.
