### ISSUE TITLE
How to solve problem: API-METADATA-NOT-FOUND?

### ISSUE THREAD

**Issue by fengnex** [naver/pinpoint#3595]
After cleaning all hbase tables and recreating all tables and restarting web&collector, every seems OK, but later the error 'API-METADATA-NOT-FOUND' has been found.
So how to fix it? Restarting everything or better solution?

Please notify us how to solve it ASAP, thx!

**Comment by fengnex** [comment]
Is it necessary to restart ALL agents if there are hundreds of them?
Are there any other solutions?

**Comment by Xylus** [comment]
Hi @fengnex 
Meta data (APIs, SQLs, String values etc) are usually sent when a class is first transformed (API), or when a value is first traced (SQL, Strings), and these values are valid until the agent shuts down.
So if these data are deleted while the agent is still running, there is currently no way to retrieve them and the only solution is to restart the agents.

**Comment by fengnex** [comment]
@Xylus 
Thank you very much!

**Comment by yanpeng-ali** [comment]
@Xylus 
I have found the same problem. And I change the pinpoint  agent's source code to add a timer to the synchronize the metadata. 

Do you think it is fine? Thank you very much.

**Comment by Xylus** [comment]
@yanpeng-ali 
Yes, I think that is totally fine!

**Comment by yanpeng-ali** [comment]
@Xylus 

So, I make a pull request to merge the  metadata syn's source code, It is fine?

**Comment by Xylus** [comment]
@yanpeng-ali 
Ah, I thought you implemented it for your internal use and wasn't expecting a pull request.

One of the reasons why we held off on implementing something like this was because the memory footprint behind holding on to the metadata could be huge.
I'm sure it'll be fine for your use case, but I don't think keeping all metadata in memory is something we can merge into the code base.

**Comment by yanpeng-ali** [comment]
@Xylus 
Thank  you very much. I got it.

**Comment by MarsZhu** [comment]
> @Xylus
> Thank you very much. I got it.
I need your Features.Cloud you teach me to implement it?

**Comment by dinesh4747** [comment]
Reference to the recent issue - #6496

@koo-taejin @jaehong-kim @emeroad @Xylus @jefry86 @yanpeng-ali @MarsZhu @minwoo-jung 

It looks functional issue where "synchronizing the start time value of agent is not in sync whole it reaches collector server" Can someone please shed some light or definite pointers on how to solve API-METADATA-NOT-FOUND issue which is almost deteriorating my usage of pinpoint in my cloud system and it seems like @jefry86 mentioned very clearly that "the startTime value of metadata is different"

It would be really great and kind if someone could help me address this.
