### ISSUE TITLE
Pinpoint collected datas exploration 

### ISSUE THREAD

**Issue by ofauchon** [naver/pinpoint#3600]
Hi, 

I use pinpoint for performance testing. 

I'd like to process the collected datas between two dates to generate reports :  

- Number of transactions/span/spanevents
- HTTP status code and error statistics
- Top SQL queries, http url  
- ...

Do you have any advices for Pinpoint data exploration from other languages (python/go/other)? 

Thanks

Olivier.

**Comment by accumulatepig** [comment]
Pinpoint is a great tool that help us solve many production problems, but I also have the same request , I wanna get the slow url request or top sql ......  datas  to our monitor platform, So  is there the api to get the data or some way to do this , like diretor get from hbase  or  from pinpoint-web request url ...   ; pls give me some advices , thank you
