### ISSUE TITLE
Where is the docs for deployment and configuration and clustering?

### ISSUE THREAD

**Issue by waleedsaud** [naver/pinpoint#3603]
Where is the docs for deployment and configuration and clustering?
Basically there is no docs to operate and deploy pinpoint in production for admin/operator.

**Comment by Xylus** [comment]
Hi @waleedsaud 
The [installation](https://github.com/naver/pinpoint/blob/master/doc/installation.md) guide should help you set up pinpoint.
Is there anything more specific you're looking for?

**Comment by waleedsaud** [comment]
It unclear and missing too much details.

**Comment by Xylus** [comment]
I think this issue is unclear and missing too much detail.
Again, if you could be more specific about what you would like to see get added, perhaps due to some issue you've encountered while working with Pinpoint, it would be great.
