### ISSUE TITLE
mssql jdbc agent supported?

### ISSUE THREAD

**Issue by zone1511** [naver/pinpoint#3604]
from the project description, it mention mssql is supported, however, from the code, I didnt see there is agent for mssql.

**Comment by Xylus** [comment]
Hi @zone1511 
[This](https://github.com/naver/pinpoint/tree/master/plugins/jtds) is the plugin for mssql java driver.

**Comment by zone1511** [comment]
understand, any plan to support microsoft offical jdbc driver?

**Comment by Xylus** [comment]
Sounds like a good idea for 1.7.1!
