### ISSUE TITLE
Select all data transaction from Scatter Chart from directive.js function

### ISSUE THREAD

**Issue by xanderstephens125** [naver/pinpoint#3607]
I am looking for a way to select all the transactions present on the scatter chart at a given time upon button click. I think the onSelect: function( oDragAreaPosition, oDragXY ) on line 120 of scatter.directive.js would be a good place to start, but I am not sure how to populate the "fromX, toX" variables to select all data. 

Thank you

**Comment by denzelsN** [comment]
Hi @xanderstephens125 
The fromX and toX values you want are the time values in the URL.
So if you want to select all the transactions in the scatter chart, you can set the fromX and toX values as follows:


``` javascript
// if your url is `main/XXX@TOMCAT/20m/2017-12-06-10-00-00` 

var fromX = new Date("2017.12.06 10:00:00").getTime() - ( 20 * 60 * 1000 ); // 1512520800000
var toX = new Date("2017.12.06 10:00:00").getTime(); // 1512522000000
```

**Comment by xanderstephens125** [comment]
Thanks for your response. So I have the html/js setup in the following way but still do not get the transactionList to open when I click:

**sidebarTitle.html:**
<div class ="business-transactions-list">
    <span>
        <button type ="button" class="btn btn-success btn-xs" ng-click="showTransactions()"><span 
           class="glyphicon glyphicon-th-list"></span>&nbsp;&nbsp;Business Transactions
        </button>
    </span>
</div>

**sidebar-title.directive.js:**

function showBusinessTransactions(oDragAreaPosition, oDragXY){
                        var fromX = new Date("2017.12.06 10:00:00").getTime() - ( 20 * 60 * 1000 ); 
                        var toX = new Date("2017.12.06 10:00:00").getTime(); // 1512522000000
                        var partialURL = UrlVoService.isRealtime() && enableRealtime ? "realtime/" + UrlVoService.getQueryEndDateTime() : UrlVoService.getPartialURL( false, true );
                        var token = application + "|" + oDragXY.fromX + "|" + oDragXY.toX + "|" + oDragXY.fromY + "|" + oDragXY.toY + "|" + arguments[2];
                        
                        $window.open("#/transactionList/" + UrlVoService.getPartialURL(true, false), token);
                    }

**Comment by xanderstephens125** [comment]
Thank you for your response. I have the html/js setup in the following manor but still get no response on button click:

**sidebarTitle.html**

'<div class ="transactions-list">
        <span>
            <button type ="button" class="btn btn-success btn-xs" ng-
              click="showBusinessTransactions()">
                  <span class="glyphicon glyphicon-th-list"></span>
               &nbsp;&nbsp;Business Transactions
            </button>
        </span>
    </div>'
