### ISSUE TITLE
new realise 1.7.0-RC1 but it is given error page can’t be found

### ISSUE THREAD

**Issue by GyaneshRahatekar** [naver/pinpoint#3608]
[catalina.out.pdf](https://github.com/naver/pinpoint/files/1531213/catalina.out.pdf)

[catalina.out.pdf](https://github.com/naver/pinpoint/files/1531210/catalina.out.pdf)

Will try to check new realise 1.7.0-RC1 but it is given error page can’t be found

#### Description
New 1.7.0-RC1 realise given error 

#### Environment
* Pinpoint version: 1.7.0 RC1
* OS, WAS, affected library, etc: 
* Additional details (e.g. how your collector/web is set up): on one node

#### Additional Info
followed same step to install according to 1.6.2

**Comment by koo-taejin** [comment]
hi GyaneshRahatekar

It is related to this issue. #3580 

recommend using the current master branch rather than RC1.

thanks.
