### ISSUE TITLE
ui authentication and role based access

### ISSUE THREAD

**Issue by sadat-ali-khan** [naver/pinpoint#3623]
as the title asks , can we have :-

1./ ui authentication enables ? I read that there is a mysql backend used for this.

2./ also is role based access possible ?

regards
Sadat Ali Khan

**Comment by liaochente** [comment]
I need help,too

**Comment by minwoo-jung** [comment]
Unfortunately, Pinoint doesn't provided those function. 
Currently pinpoint only use userinfo to send alarm.
