### ISSUE TITLE
How to group applications？

### ISSUE THREAD

**Issue by yangmilestone** [naver/pinpoint#3628]
Hello, we have two different projects (A and B), A project has 10 service components, B has 8 service components, we monitor A and B respectively, when all the configurations are successful, the web UI "Application list" drop-down box appears 18 application options, is there any good way to press A, B group display application components?

**Comment by Xylus** [comment]
Hi @yangmilestone 
You can group agents by having them share the same application name.

For your case, agents in project A would have say `-Dpinpoint.applicationName=ProjectA`, and agents in project B would have `-Dpinpoint.applicationName=ProjectB`.
This will result in your server map having 2 nodes, **ProjectA** and **ProjectB**; where **ProjectA** having 10 agents, and **ProjectB** having 8 agents.

**Comment by yangmilestone** [comment]
ok thanks！

**Comment by anantsaraswat** [comment]
@Xylus  This is not working for me, It used to work till 1.8 but now we are running 2.2.2 using the docker-compose and services are not grouped according to the application name.

**Comment by maxime700** [comment]
Hello, 

I'm facing a similar "issue". 
I have an app that is compose of 10 microservices (docker containers). 
I would like to monitor 2 environments (dev and preprod) and see them as applicaitons in the drop down list. But I also would like to have 10 nodes for each of the applications in the server map. 

Is that possible? 

Thanks

**Comment by emeroad** [comment]
Unfortunately there is no grouping feature.
This feature will be added in pinpoint 4.0, which will be released in 2024.

Current Hierarchy :  ApplicationName/AgentID
4.0 Hierarchy :  ServiceName/ApplicationName/AgentID
eg) Cafe / APIGW / agent1 ~ 10

**Comment by maxime700** [comment]
Thank you @emeroad. 
I will pay attention to the version releases.
