### ISSUE TITLE
why pinpoint remove rocketmq plugin

### ISSUE THREAD

**Issue by jiuchongxiao** [naver/pinpoint#3630]
hello,i want to know why pinpoint remove rocketmq plugin? i see it had rocketmq plugin before 2years old .

**Comment by Xylus** [comment]
Hi @jiuchongxiao 
I don't think we ever had rocketmq plugin in our repository.
There is a PR for it (https://github.com/naver/pinpoint/pull/1783) but it needs issues fixed before it can be merged.

**Comment by jiuchongxiao** [comment]
Hi @Xylus 
thank you very much .
yes, you are right. but are you planning integration the plugin? and when?

**Comment by Xylus** [comment]
It would be great to have it in.
The PR is quite outdated, perhaps we could look into it again after 1.7.0 releases.

**Comment by jiuchongxiao** [comment]
@Xylus thank you !
