### ISSUE TITLE
Store data into mysql instead hbase

### ISSUE THREAD

**Issue by zhegexiaohuozi** [naver/pinpoint#3634]
How to instead hbase with some mysql protocol newSql db (such as [TiDB](https://github.com/pingcap/tidb)) ?

**Comment by koo-taejin** [comment]
hi zhegexiaohuozi 

It would be great if it did.
However, we do not currently have such a plan.
It would be great if you make it and pull request for us.

thanks.

**Comment by jiaqifeng** [comment]
This is really need some time to do it.
