### ISSUE TITLE
Ability to export/import call trees

### ISSUE THREAD

**Issue by rraziel** [naver/pinpoint#3637]
It would be very convenient to be able to export a call tree and reimport it on another machine, through a simple export/import entry in the menu.
We have cases where we have machines that have access to the infrastructure to generate the pinpoint data but the people who are going to analyze it are on a completely different site with no access.

**Comment by jiaqifeng** [comment]
As I know there is not such function in menu. On detail transaction page, the call tree info is just a json array from web server, you could just add a button on page to export such json array and save it.

**Comment by rraziel** [comment]
Would you be interested in such a PR?
Although the more useful aspect is the import itself.

**Comment by jiaqifeng** [comment]
I mainly code in Java but not js on web. If you just want to save the call tree occasionally, you can using debug tool of firefox/chrome and get the response of transactionInfo.pinpoint?traceId= in network tab which is a json of call tree.
