### ISSUE TITLE
could agent send stat and span through one udpSender?

### ISSUE THREAD

**Issue by jiaqifeng** [naver/pinpoint#3638]
Why pinpoint used 2 udp connection to send data? One for stat and one for span. Could I use one UDP connection to send them all?
If it's ok, will this need a lot changes of code? Or about how much work will it take? Any advice is welcome.

**Comment by koo-taejin** [comment]
hi jiaqifeng 

I think that there are many advantages of separating, such as allocating a thread size for each event, finding the cause when a problem occurs, or using buffer of each udp socket.

So, currently we do not have plan for it.

Changing the code is not difficult. 

in Profiler
create and share one UDPSender in ApplicationContext

in Collector
Put the SimpleHandlers in the SpanDispatchHandler and StatDispatchHandler into the new DispatchHandler.
You can include it as an argument to the DataReceiver.

thanks.

**Comment by jiaqifeng** [comment]
@koo-taejin 
Thanks so much. My apps and pinpoint are running on a public cloud provider. I am considering using DTLS to secure the packet, so using one udp connection may reduce some cost for negotiation and easy deployment. I have considered all packets send/receive through one tcp connection, but I am worried it may cost too much in agent side for heavy app workload or degrade performance badly.
