### ISSUE TITLE
Is there a way to get TraceId of one transcation?

### ISSUE THREAD

**Issue by toxie641517** [naver/pinpoint#3646]
hi, we have used pinpoint in our prod environment. One question is can we get **TraceId** that the agent generate? I tried to check the request header keys, but no data found. So how can we get the TraceId  from our own code? Thanks so much

**Comment by yanpeng-ali** [comment]
I think that maybe I can answer your question.
If your apps use the pinpoint agent,  then you can find the "Pinpoint-TraceID" in the request header keys when the one app calls anther one.
