### ISSUE TITLE
How can I delete the mapping between application name and agent id?

### ISSUE THREAD

**Issue by WangHouLing** [naver/pinpoint#3653]
#### Description

Hi all,
I changed the agent id of the duplicate agent, but I can see the agent already exits, how can I fix this? Maybe I can use pinpoint api to delete this mapping, but I didn't find documents about this.
Please help me, thank you.
#### Environment

* Pinpoint version:1.6.2
* OS, WAS, affected library, etc:centos7

#### Additional Info

![image](https://user-images.githubusercontent.com/20981477/34353811-658194dc-ea65-11e7-9725-34b8aa4f015d.png)

**Comment by Xylus** [comment]
Hi @WangHouLing 
Please take a look at https://github.com/naver/pinpoint/wiki/FAQ#how-do-i-delete-application-name-andor-agent-id-from-hbase
For your case, you can use the delete agent API (`/admin/removeAgentId.pinpoint`).

**Comment by WangHouLing** [comment]
@Xylus Thank you. I use this method delete agent successfully.
One more question, if I use `hbase-drop.hbase` delete hbase tables and then run `hbase-create.hbase`, whether I need to restart my application which is monitored by pinpoint?

**Comment by WangHouLing** [comment]
Thank you very much. I use delete agent API successfully.

**Comment by Xylus** [comment]
:+1:
