### ISSUE TITLE
inspector redis  not found

### ISSUE THREAD

**Issue by jiuchongxiao** [naver/pinpoint#3655]
hello,
why my inspector redis not found? who can answer me ,thanks

the detail 
![cusoik28i2ok um8f day6r](https://user-images.githubusercontent.com/13093730/34368486-4fb4b06e-eaef-11e7-8946-35096d03b880.png)
![default](https://user-images.githubusercontent.com/13093730/34368495-60d2901e-eaef-11e7-92a9-b15df64c3719.png)

**Comment by koo-taejin** [comment]
please refer this issue #3656
