### ISSUE TITLE
inspector mysql

### ISSUE THREAD

**Issue by jiuchongxiao** [naver/pinpoint#3656]
hello,
the mysql is not inspector?
![default](https://user-images.githubusercontent.com/13093730/34368538-cb575e56-eaef-11e7-89e5-68c15e756e80.png)
![default](https://user-images.githubusercontent.com/13093730/34368571-f1148cae-eaef-11e7-96d4-a8342f68f722.png)
![default](https://user-images.githubusercontent.com/13093730/34368576-fdced30a-eaef-11e7-94c1-095e1097775b.png)

**Comment by koo-taejin** [comment]
hi. jiuchongxiao

Inspector is active only where application running with pinpoint agent.
Mysql is connected in your application.
It is not running with pinpoint agent. 
Therefore, it does not show the information of the inspector.

thanks.

**Comment by jiuchongxiao** [comment]
@koo-taejin  hi ,my application is running and the agent is good.other is running well but the inspector redis and mysql are wrong.
the application inspector is well

**Comment by jiuchongxiao** [comment]
is it because my mysql connected jdbc?

**Comment by koo-taejin** [comment]
It does not matter that your mysql is connected via jdbc.
As I said above
Mysql is connected in your application.
It is not running with pinpoint agent.

**Comment by jiuchongxiao** [comment]
@koo-taejin  thank yo very much. i know tomcat/spring boot/dubbo how config the pinpoint agent,but i do not know the redis and mysql.could you help me?
