### ISSUE TITLE
Slow count alarm request time will not change?

### ISSUE THREAD

**Issue by cendongqi** [naver/pinpoint#3657]
Hi

#### Description
Excuse me, If I remember is not incorrectly, the condition that triggers the slow count alarm is that the request time is longer than 5 seconds. I don't know this threshold time is fixed, or changed with the statistics time of pinpoint agent. 
I will appreciate if you can help me.

#### Environment
* Pinpoint version: 1.7.0
* OS: CentOS 7

**Comment by minwoo-jung** [comment]
Hi @cendongqi 
Please ref https://github.com/naver/pinpoint/issues/3566.
