### ISSUE TITLE
About the plugin classloader

### ISSUE THREAD

**Issue by x1aliang** [naver/pinpoint#3673]
I think the purpose of pluginclassloader is to prevent the plugin's dependencies pollute the application's classpath. But in my test,  i still can access the plugin classes in application. Then I check the source, i find at `com.navercorp.pinpoint.profiler.instrument.classloading.URLClassLoaderHandler` line 77  `addPluginURLIfAbsent(ucl); `It seems that we add the plugin jar to application's classpath (appclassloader search path)。 why we do this？ why we dnt use a separate classloader to load the plugin and its dependencies?

**Comment by emeroad** [comment]
Due to the deadlock problem in JDK6, we do not use child classloader.
When jdk 6 is deprecated, it can be changed to child classloader.

**Comment by x1aliang** [comment]
Thanks, and another problem relate to this is when a delevelop a plugin, and my plugin has its own denpendencies where i deploy these plugins. I check the code, the note says ` * TODO Loading all plugins with a single class loader could cause class collisions.
 *      Also, with current implementation, plugins can use dependencies by putting them in the plugin directory too.
 *      But it can lead to dependency collision between plugins because they are loaded by a single class loader.
 *      
 *      How can we prevent this?
 *      A ClassLoader per plugin could do it but then we have to create "N of target class loader" x "N of plugin" class loaders.
 *      It seems too much. For now, Just leave it as it is. ` but in practice, i cant load my dependencies in runtime, when i trace the problem, i find out for each plugin, we use a new classloader to load that plugin. at ` ProfilerPluginLoader line 44       for (URL pluginJar : pluginJars) {

            final JarFile pluginJarFile = createJarFile(pluginJar);
            final List<String> pluginPackageList = getPluginPackage(pluginJarFile);

            final ClassNameFilter pluginFilterChain = createPluginFilterChain(pluginPackageList);

            final List<ProfilerPlugin> original = PluginLoader.load(ProfilerPlugin.class, new URL[] { pluginJar });` Then my question is when my plugin has its own dependencies where i should deploy these jars. 


And could you give me some reference about how JDK6 cause deadlock? thanks

**Comment by emeroad** [comment]
Unfortunately, there is no plan to support other lib dependencies in the plugin.
We recommend that you simplify the dependency of the plugin.
