### ISSUE TITLE
Agent is not throwing anything to the collector

### ISSUE THREAD

**Issue by asdad-emizzy** [naver/pinpoint#3675]
#### Description
 Pinpoint Collector, Web-UI, and HBase are installed on the same host.

#### Environment

* Pinpoint version: 1.6.2
* OS, WAS, affected library, etc: OS: AWS Linux using aws beanstalk with TOMCAT8
* Additional details (e.g. how your collector/web is set up):  Pinpoint Collector, Web-UI, and HBase are installed on the same host.

#### Additional Info:
pinpoint agent is properly installed, I think.
I didn't saw any issue on the logs of Catalina.out. the question is, what needs to check if the agent is working properly.

note : 

logs from pinpoint agent
2018-01-03 11:17:38 [INFO ](com.navercorp.pinpoint.bootstrap.PinpointStarter) pinpoint agent started normally.
2018-01-03 11:17:40 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.tomcat.enable=true
2018-01-03 11:17:40 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.tomcat.conditional.transform=true
2018-01-03 11:17:40 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.tomcat.hidepinpointheader=true
2018-01-03 11:17:40 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.tomcat.tracerequestparam=true
2018-01-03 11:17:40 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.tomcat.excludeurl=/aa/test.html, /bb/exclude.html
2018-01-03 11:17:40 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.tomcat.realipheader=null
2018-01-03 11:17:40 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.tomcat.realipemptyvalue=null
2018-01-03 11:17:40 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.tomcat.excludemethod=
03-Jan-2018 11:17:40.113 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.41
03-Jan-2018 11:17:40.116 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Feb 13 2017 20:49:48 UTC
03-Jan-2018 11:17:40.118 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.0.41.0
03-Jan-2018 11:17:40.118 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
03-Jan-2018 11:17:40.118 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.4.51-40.60.amzn1.x86_64
03-Jan-2018 11:17:40.118 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
03-Jan-2018 11:17:40.118 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/java/jdk1.8.0_151/jre
03-Jan-2018 11:17:40.118 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_151-b12
03-Jan-2018 11:17:40.118 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
03-Jan-2018 11:17:40.118 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/share/tomcat8
03-Jan-2018 11:17:40.118 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/share/tomcat8
03-Jan-2018 11:17:40.119 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -DJDBC_CONNECTION_STRING=
03-Jan-2018 11:17:40.119 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms256m
03-Jan-2018 11:17:40.119 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx256m
03-Jan-2018 11:17:40.119 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:MaxPermSize=64m
03-Jan-2018 11:17:40.119 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote
03-Jan-2018 11:17:40.119 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.port=9000
03-Jan-2018 11:17:40.119 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.ssl=false
03-Jan-2018 11:17:40.119 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
03-Jan-2018 11:17:40.119 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -javaagent:/opt/pinpoint/pinpoint-bootstrap-1.6.2.jar
03-Jan-2018 11:17:40.119 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dpinpoint.agentId=chatwebadminapi
03-Jan-2018 11:17:40.119 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dpinpoint.applicationName=chatwebadminapi
03-Jan-2018 11:17:40.119 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/share/tomcat8
03-Jan-2018 11:17:40.119 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/share/tomcat8
03-Jan-2018 11:17:40.119 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
03-Jan-2018 11:17:40.119 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.endorsed.dirs=
03-Jan-2018 11:17:40.120 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/var/cache/tomcat8/temp
03-Jan-2018 11:17:40.124 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/share/tomcat8/conf/logging.prope
rties
03-Jan-2018 11:17:40.124 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
03-Jan-2018 11:17:40.124 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in produc
tion environments was not found on the java.library.path: /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
03-Jan-2018 11:17:40.344 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
03-Jan-2018 11:17:40.356 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
03-Jan-2018 11:17:40.371 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
03-Jan-2018 11:17:40.375 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
03-Jan-2018 11:17:40.381 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 1122 ms
03-Jan-2018 11:17:40.427 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
03-Jan-2018 11:17:40.428 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.41
03-Jan-2018 11:17:40.448 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /var/lib/tomcat8/webapps/ROOT
03-Jan-2018 11:17:42.417 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging f
or this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
2018-01-03 11:17:42 DEBUG logging:27 - Logging Provider: org.jboss.logging.Log4jLoggerProvider

**Comment by Xylus** [comment]
Hi @asdad-emizzy 
The agent log is under $AGENT_DIR/log directory, if you could check it out and see if there's anything wrong.
You could also check the collector's catalina log to see if it's receiving anything.

**Comment by asdad-emizzy** [comment]
Right now, when restarting the tomcat8 apps. I often get an error of java.io.FileNotFoundException: for the pinpoint_agent_dir/log/appication_pinpoint.log (permission denied). For my workaround, I always create this manually and provide the proper permission for the agent to run normally. How to fix this?

**Comment by Xylus** [comment]
Looks like whatever user running the java process with pinpoint agent doesn't have permission to /opt/pinpoint directory?

**Comment by asdad-emizzy** [comment]
Hi Xylus,

Thanks for helping,
