### ISSUE TITLE
Opening Transaction List via URL

### ISSUE THREAD

**Issue by xanderstephens125** [naver/pinpoint#3682]
Is it possible to open transaction List data by only changing the URL? When I attempt to open the transaction list by appending to the URL I get the following error: 

"Scatter data of parent window had been changed.
so can't scan the data any more."

What flags/tokens are being passed to allow the transaction List to be called by the scatter chart? I have tried setting: bHasParent, bHasValidParam, and bHasTransactionInfo with no luck. 

Thank you for your time.

**Comment by 1314cc** [comment]
Can you tell me how to do it? We now also want to get access to the data from the pinpoint, including the number of requests URL, time
