### ISSUE TITLE
Is pinpoint support Python ?

### ISSUE THREAD

**Issue by prashantnitt07** [naver/pinpoint#3689]
Dear Team,
I want install Pinpoint APM on Python , it is support pinpoint APM. please reply

**Comment by prashantnitt07** [comment]
We need to instrument Python based application with APM , kindly let us know the support and how to instrument agent .

Python Version 2.7 uwsgi
Plat form CentOS
CA-APM 10.5.2

**Comment by koo-taejin** [comment]
hi prashantnitt07 

Currently, We do not support Python.
and We don't have a plan.

thanks.
