### ISSUE TITLE
What're the plan for pinpoint in 2018? What version will the next release be?

### ISSUE THREAD

**Issue by fengnex** [naver/pinpoint#3697]
This is not an issue and are just two questions.

**Comment by emeroad** [comment]
It is likely to be similar to the 2017 plan.
   - eg), realtime servermap, url statistics, heatmap scatter chart, hbase namespace support ~~

The next version is 1.7.2.

**Comment by geekMessi** [comment]
what is  "url statistics"? 
would u show the feature detailly?
