### ISSUE TITLE
pinpoint-flink.properties 

### ISSUE THREAD

**Issue by christianorios** [naver/pinpoint#3700]
Hi, I am configuring the new version 1.7.1 and I am reading the instructions in "https://github.com/naver/pinpoint/blob/master/doc/application-inspector.md", but I cant' find the file pinpoint-flink.properties.
Can you help me?
Thanks a lot.

**Comment by minwoo-jung** [comment]
Hi

If you click link [pinpoint-flink.properties](https://github.com/naver/pinpoint/blob/master/flink/src/main/resources/pinpoint-flink.properties) in application inspector guide you can see directory at the top of page to find file. 
**pinpoint/flink/src/main/resources/pinpoint-flink.properties**

**Comment by christianorios** [comment]
Hi minwoo-jung.  I mean where is the file in the server's filesystem. In flink's directory? Do I have to create it myself?
Thanks.

**Comment by minwoo-jung** [comment]
Maybe You would have downloaded pinpoint source to execute pinpoint. you should find file in your pinpoint-flink project folder.

**Comment by christianorios** [comment]
Yes, thanks, I've got it. Where is it suppose to be in my application server? I use Tomcat to deploy the pinpoint-web-1.7.2-SNAPSHOT.war
