### ISSUE TITLE
how to compile the pinpoint project

### ISSUE THREAD

**Issue by yale2** [naver/pinpoint#3708]
when I run mvn clean install -DskipTests command ,the project commons-hbase gives an error,and I don't know why.the error didn't tell me what's wrong?I config three jdk versions， is there anything else should I config? I don't have a hbase client locally;

**Comment by Xylus** [comment]
Hi @yale2 
Running maven with -X flag will give you more detail on why it failed.

**Comment by yale2** [comment]
ok,thanks! but there is another question.the same code I compile it on windows 10 and windows xp.it gives two different result.does the different system caused it？I just config three jdk version. nothing else .

**Comment by Xylus** [comment]
@yale2 They shouldn't give different results.
