### ISSUE TITLE
How to add Pinpoint user in alarm with version  v1.7.1?

### ISSUE THREAD

**Issue by chuanyi-fang** [naver/pinpoint#3711]
![alarm](https://user-images.githubusercontent.com/20055737/34940300-f470bb36-fa29-11e7-9b26-5f962c4406d8.png)
How to add Pinpoint user in alarm with version v1.7.1?

**Comment by minwoo-jung** [comment]
Please ref https://github.com/naver/pinpoint/blob/master/doc/alarm.md.

**Comment by chuanyi-fang** [comment]
![alarm2](https://user-images.githubusercontent.com/20055737/34967896-d18ca2c0-faa0-11e7-99b2-a63a132c5b22.png)

In version v1.7.1, there is not add button in the Pinpoint user ,like the attach file. How to add  Pinpoint user?

**Comment by denzelsN** [comment]
@chuanyi-fang 
Sorry it's bug.
I pushed a [commit]( https://github.com/naver/pinpoint/commit/ff25831adbbf8080c489ce216b5ea5e78330b87d )
( and the value of `editUserInfo`(system configuration) must be set to `true`. )

**Comment by SFHfeihong** [comment]
I have edit the file (bug fix 3711),but it doesn't show the button of add users.
