### ISSUE TITLE
ObjectFactory usage

### ISSUE THREAD

**Issue by geekMessi** [naver/pinpoint#3720]
"
**Therefore for a class X in a plugin, X in ProfilerPlugin and PinpointClassFileTransformer implementations and X in interceptor implementations are different. This makes it impossible for a transformer to pass an object whose type is defined in the plugin to a interceptor as it's constructor argument**
"
It is the description in the sample class "Sample_11_Configuration_And_ObjectRecipe".  What  confused me is the following content,  "**X in ProfilerPlugin and PinpointClassFileTransformer implementations and X in interceptor implementations are different**" .  I didn't get that meaning.

While I get some similar usage in the class "**SpringBeansPlugin**",  the "**beanTransformer** " instance is instantiated by "**BeanMethodTransformer beanTransformer = new BeanMethodTransformer(errorMark)**"   before passing it as the Interceptor constructor argument.  why not use "**ObjectFactory.byConstructor**"?

Would you please explain it  in detail?
Thank you for your time.

**Comment by Xylus** [comment]
Hi @geekMessi 

So for the **SpringBeansPlugin**, it is okay to instantiate **BeanMethodTransformer** over to SpringBeans interceptor (**PostProcessorInterceptor**, **ClassPathDefinitionScannerDoScanInterceptor**) as these interceptors do not directly reference **BeanMethodTransformer**. The interceptors all take in **TransformCallback** as their constructor argument, which is an interface in bootstrap module (which is added to the bootstrap class loader's search path) and should be visible to both the plugin class loader and for the lack of a better  name, "target class loader".
If the interceptors had **BeanMethodTransformer** as their constructor argument, then it would require an **ObjectFactory** just like the sample.

In contrast, **TargetBeanFilter** in **SpringBeansPlugin** is a class that will not be loaded by a common parent of plugin class loader and "target class loader", and thus needs **ObjectFactory** to work just like the sample code.

**Comment by geekMessi** [comment]
Thanks a lot @Xylus 
Your explanation is so clear. This frees me from confusion.
I get  the reason why **PinpointBootStrap** do  "**instrumentation.appendToBootstrapClassLoaderSearch**" at the bootStrap stage. 

Those interceptors  can interact with the **BeanMethodTransformer** object which is loaded by another ClassLoader through the interface **TransformCallback**  which is loaded by **BootstrapClassLoader**.

**Comment by Xylus** [comment]
@geekMessi That is absolutely correct :)
