### ISSUE TITLE
I get an error when i click User Group tag

### ISSUE THREAD

**Issue by anime8** [naver/pinpoint#3726]
#### Description
I get an error when i click User Group tag, 
![image](https://user-images.githubusercontent.com/17871765/35076944-bff85fa4-fc35-11e7-9b1c-c8b295c74f73.png)

#### Environment

* Pinpoint version: pinpoint-web-1.7.1
* centos 6.9  ,pinpoint-web-1.7.1.war ,pinpoint-collector-1.7.1.war  appache-tomcat-7 java1.8.0_131

#### Additional Info
hbase.properties
hbase.client.host=xx.xx.xx.xx,xx.xx.xx.xx,xx.xx.xx.xx
hbase.client.port=2181

Following is my jdbc configuration.
![image](https://user-images.githubusercontent.com/17871765/35077050-3d3a55da-fc36-11e7-8771-966d4afe070a.png)

I can't find any error in my log file.

**Comment by anime8** [comment]
I use another browser,  this issue haven't occur.

**Comment by denzelsN** [comment]
@anime8 
What browser do you use? And what browser did not get errors?

**Comment by anime8** [comment]
@denzelsN I get an error when i use Google Chrome .

**Comment by denzelsN** [comment]
@anime8 
Thank you. It's bug.
I pushed the [commit](https://github.com/naver/pinpoint/pull/3730/commits/759d3c5ff98b19860f1c5995f5bb76826fdd7d00)
