### ISSUE TITLE
[문의] JAVA8 환경에서 HeapUsage와 PermGen Usage 패턴이 동일할때

### ISSUE THREAD

**Issue by Jae-Young-Kim** [naver/pinpoint#3727]
#### Description
현재 기동중인 웹어플리케이션에서 Heap Usage 와 PermGen Usage의 Full GC 패턴이 똑같이 나옵니다.
JAVA8에서는 Permgen 영역이 metaspace로 바뀐것으로 아는데, 
Heap Usage와 PermGen Usage의 FGC패턴이 동일하게 표현되고 있는 것에 대한 의미가 궁금합니다.

#### Environment

* Pinpoint version: 1.6.2
* WAS : Tomcat 8.5.16
* JVM : 1.8.0_144(GC type PARALLEL)

**Comment by Xylus** [comment]
안녕하세요,
말씀하신데로 차트의 PermGen usage 이름을 Nonheap usage로 바꿀 필요가 있어 보입니다.
이 부분 수정하도록 하겠습니다. 감사합니다.

FGC 데이터는 FGC가 일어난 원인과는 상관 없이 FGC의 실행 건수/시간을 보여주고 있습니다.
따라서 allocation failure, metaspace gc threshold 초과, `System.gc()` 호출 등 어떤 이유에서든 FGC가 실행된 횟수와 시간을 보여주기 떄문에 두 차트의 FGC 패턴이 동일하게 표현됩니다.
(실제 2 차트 모두 동일한 데이터 소스를 보여줍니다)

추가로 궁금하신 점 있으시면 말씀 부탁드립니다.
감사합니다.

**Comment by Jae-Young-Kim** [comment]
답변 감사드립니다.  이슈는 닫도록 하겠습니다.
