### ISSUE TITLE
How to support kerberos ?  

### ISSUE THREAD

**Issue by DiligenceY** [naver/pinpoint#3737]
my hbase need kerberos ?
how to add id  in pinpoint ?

**Comment by koo-taejin** [comment]
hi DiligenceY

Currently, pinpoint  not providing kerberos authentication within hbase communications.
and, no plans to provide it.

It would be nice if you work on it and send a pull request if you can.

thanks.

**Comment by lengrongfu** [comment]
now it is supporting?
