### ISSUE TITLE
Agent in Windows

### ISSUE THREAD

**Issue by viniciusxyz** [naver/pinpoint#3739]
How can I use the Agent in a Tomcat on windows? Is there any tutorial or documentation for this?

**Comment by Xylus** [comment]
Hi @viniciusxyz 
It's the same as with any java application on any platform, set *-javaagent* accordingly, and pass in *-Dpinpoint.agentId* and *-Dpinpoint.applicationName* when you start Tomcat.
If you're running Tomcat as a Windows service, there should be a Java tab in Tomcat configuration window where you can set java options.
(Please refer to Tomcat website for more details on how to pass in vm options and arguments)
