### ISSUE TITLE
netstat doesn't exist for CentOS 7

### ISSUE THREAD

**Issue by lk95jofr** [naver/pinpoint#3743]
#### Description
On centOs7 the netstat is deprecated.
https://unix.stackexchange.com/questions/146190/commands-not-found-netstat-nmap-on-centos-7

#### Environment
CentOS 7

#### Additional Info
yum install net-tools

**Comment by koo-taejin** [comment]
hi lk95jofr

Thank you for a good issue.
Let's see if there is a command to replace netstat, lsof.
If there is no alternative command, we recommend install command 'yum install net-tools, etc..' as a failure log.

thanks.

**Comment by lk95jofr** [comment]
I guess that ss tool is the tool to be used
https://linux-audit.com/alternative-netstat-ss-tool/

**Comment by koo-taejin** [comment]
It also checks for the ss command.
but ss command seems to be for root user (default path : /sbin/ss), so I was looking for another way.

thanks :)

**Comment by koo-taejin** [comment]
I made a change to verify with url.
dependency of the command seemed to need constant management.

Thank you very much for letting me know about this issue.
