### ISSUE TITLE
SQL still can't be traced, help again!

### ISSUE THREAD

**Issue by ecamy** [naver/pinpoint#3744]
#### Description
Hi,teams, 
   Our SQL statements still can't be seen in our call stacks of pp-web, and also can't see mysql database on the main web.  We really want to see them to   go deep into performance by pp.  

    I also prepare a log txt  from agent as attached.  

   Also thanks for your new version and your hard work, it's easy to deploy and analysis performance problem. We are trying to use it in our workings. 

#### Environment
Environment
Pinpoint version: 1.7.0
Windows8 + Hbase1.2.6
ibase4j Framework+ Druid connect pool + Mysql database

[Uploading pp_ccj-pinpoint.txt…]()

**Comment by Xylus** [comment]
Hi @ecamy 
Your attachment doesn't seem to be valid.

Regarding your issue, I think it might be because we don't support ibase4j or Druid connection pool yet (but we'll have to take a look at the log to be sure).

**Comment by ecamy** [comment]
Hi, @Xylus  
please check as followed. thanks so much. 
[pp_ccj-pinpoint.txt](https://github.com/naver/pinpoint/files/1654319/pp_ccj-pinpoint.txt)

**Comment by Xylus** [comment]
@ecamy Thanks for the log.
I have checked druid connection pool and it seems to trace okay (unless you're calling mysql from a different thread via async invocations).
The issue might have to do with ibase4j and pinpoint not supporting it.
Best bet would be to try and debug your application with pinpoint agent attached and see what's happening in mysql plugin interceptors (which do get called btw from the log).

**Comment by ecamy** [comment]
Hi@Xylus ,
Heartfelt thanks again. I have submitted your advice to my colleague related. I can't debug these codes because of duty. Wish he can solve the issue following your guiding.
