### ISSUE TITLE
Closed connection.  Select node again. when i use a nginx as a proxy

### ISSUE THREAD

**Issue by anime8** [naver/pinpoint#3745]
#### Description
Closed connection.  Select node again. when i use a tenginx as a proxy. 
![image](https://user-images.githubusercontent.com/17871765/35254317-a9e3f834-0024-11e8-985c-184988c70e89.png)

#### Environment

* Pinpoint 1.6.2
* centos 6.9

#### Additional Info
I can't find any error information in log files. I click 'retry' button again, the same error information occurred. When i connect to pinpoint-web directly, no problem.

**Comment by koo-taejin** [comment]
hi anime8 

If there is no problem with the direct connection to pinpoint-web
Find out if there is a problem with the connection to tenginx.

We are not familiar with tenginx, it is difficult to help with the issue

thanks.

**Comment by anime8** [comment]
@koo-taejin 

OK, thank you.
