### ISSUE TITLE
Two tier java only record the first button click.

### ISSUE THREAD

**Issue by seaward** [naver/pinpoint#3753]
Two tier java only record the first button click.

#### Description
Tried to monitor a two tier (Swing) java program, but only the first button click was recorded, after that, no more click can be recorded.

#### Environment
OS:  Windows 7.
Collector: Java 1.8.0_40-b26 + Pinpoint 1.7.1 + HBase 1.4.0
Agent:   Java 1.6.0_34-b04 + Pinpoint 1.7.1

* Additional details:
Collector and Web deployed in tomcat 7.0.82;
In agent folder, pinpoint.config updated by adding one *fully qualified method name* after ```profiler.entrypoint=```.
The *Update* on web page was checked to refresh every 10 seconds for new trace, the monitored button was clicked more than 10 times (each click returned a report, which took over 3 seconds, button is disabled before return)

Tried:
1. Adding *fully qualified class name* after ```profiler.include=``` doesn't help recording more clicks;
2. Set ```profiler.io.buffering.enable=false``` has no effect.

#### Additional Info
Strangely, under agent directory, there is no path ```log``` nor file like ```xxxagent-pinpoint.log generated```.

**Comment by Xylus** [comment]
Hi @seaward 
That's a very novel use of pinpoint :)
Never had it attached to a Swing app before so I'm not entirely sure, but is your `profiler.sampling.rate` set to 1 in *pinpoint.config*?

**Comment by seaward** [comment]
Hi @Xylus,

Thanks for your reply.
Maybe I find the reason (Pinpoint agent cannot write to mapped drive?): The Swing app use ```subst``` to map its folder to drive K:, then run from it.  I update all .bat files to get rid of ```subst```, now every button click can be recorded.

### Issue:  
Still no log file generated in folder *log*. Can Swing app's log4j.properties file affect PinPoint agent?

### Swing APP Users:
The Swing app has login feature, user need to login before see other panels. How can I record by user?
Do I have to provide different  value for ```-Dpinpoint.agentId``` and ```-Dpinpoint.applicationName``` for different user? That sounds a mission impossible to me...  Cause now users just run same .bat file to use it.

### ?Sampling rate:
Yes, ```profiler.sampling.rate=1```, but that must be the default value, cause I didn't change that.
