### ISSUE TITLE
spring beans plugin cannot work when re-enable

### ISSUE THREAD

**Issue by ilawrencewu** [naver/pinpoint#3759]
#### Description
I run a simple SpringMVC demo using the default pinpoint.config, and then I set the  
 spring-beans 
###########################################################
 Profile spring-beans
profiler.spring.beans=false
, result is as expected.
then set profiler.spring.beans=true,
this time the SPRING-BEANS plugin did not work any more.
so, what's the matter?

#### Environment
a SpringMVC demo
Centos 6.x

**Comment by Xylus** [comment]
Hi @ilawrencewu 
Didn't quite get your question. Are you saying spring beans are not getting traced both when you set `profiler.spring.beans=false` and `profiler.spring.beans=true`?

Also, how are you wiring your beans? The default *pinpoint.config* only supports component-scanned controller, service, repository beans.

**Comment by ilawrencewu** [comment]
@Xylus   thank you for your reply.
when I set **profiler.spring.beans=false** the plugin did not work, this is as what expected, but then set **profiler.spring.beans=true** the plugin also did not work.

**Comment by ilawrencewu** [comment]
@Xylus  I found the reason, pls close this issue. Thanks

**Comment by Xylus** [comment]
@ilawrencewu Glad you've sorted out your issue.
If you don't mind, could you briefly explain what the problem was and how you got it working (if it's got to do with pinpoint)?
It would help users who experience similar issues in the future.
Thanks.
