### ISSUE TITLE
1.7.1 does not support okhttp 3.3.1

### ISSUE THREAD

**Issue by cxiaolng** [naver/pinpoint#3761]

**Comment by koo-taejin** [comment]
hi cxiaolng

I have tested the version of okhttp 3.3.1 with pinpoint 1.7.1
It was confirmed that it operates normally.

I can not solve this issue unless you give us additional information, such as how to use the okhttp, or agent's log of related okhttp.

thanks.

**Comment by cxiaolng** [comment]
Thanks for your reply.
I had solve the problem through to modify the plugin for okhttp.

![image](https://user-images.githubusercontent.com/3888018/35723449-3ec00138-0835-11e8-8c6a-d57a402eb03d.png)

**Comment by jaehong-kim** [comment]
@cxiaolng 
Good. 
It applies from okhttp version 3.0 to 3.3
