### ISSUE TITLE
I want to keep trace data in last month,what should i do?

### ISSUE THREAD

**Issue by aximo** [naver/pinpoint#3766]
#### Description

I want to just keep trace datas in last month, so i can economize store space. what should i do?
is there any batch job to delete the hbase datas?
or should i just delete some hbase table data by myself?

#### Environment

* Pinpoint version: 1.7.0-SNAPSHOT
* Hbase:   Pseudo-distributed

**Comment by Xylus** [comment]
Hi @aximo 
Please refer to https://github.com/naver/pinpoint/wiki/FAQ#hbase-is-taking-up-too-much-space-which-data-should-i-delete-first for setting the TTL, and keep in mind about the part on meta data tables.
If you reduce the TTL, any data past TTL will be gone from storage after the next major compaction.

**Comment by aximo** [comment]
good,thanks
