### ISSUE TITLE
How to record current login ID of APP and show it on Pinpoint-web?

### ISSUE THREAD

**Issue by seaward** [naver/pinpoint#3767]
My APP has authentication, user need to login to access it. We want the login ID to be recorded.
It's even better if we can record data by login IDs.

#### Use pinpoint-user-plugin?
I didn't find any entry in pinpoint.config:
1. what should be added to enable user-plugin? 
2. How to insert current login ID into it?
3. How to show the login ID in pinpoint-web page?

Or maybe I need to write a new plugin, then above questions also apply to my plugin.

#### Environment
OS: Windows 7.
Collector: Java 1.8.0_40-b26 + Pinpoint 1.7.1 + HBase 1.4.0
Agent: Java 1.6.0_34-b04 + Pinpoint 1.7.1

**Comment by minwoo-jung** [comment]
Hi

Yes If you develope plugin, you can record user id and view in pinpoint-web. 
please ref [plugin guide](https://github.com/naver/pinpoint/wiki/Pinpoint-Plugin-Developer-Guide), [example code](https://github.com/naver/pinpoint-plugin-sample)

**Comment by seaward** [comment]
Hi, minwoo-jung,

I have read the guide and example code, but no clue how to record user id.

For example, I have class ```com.my.User``` which has field "```public static int userId```" (Legacy code), how can I record the value of ```userId``` when tracing method calls in class ```com.my.action.ReportAction```?

I only found that current class' field can be recorded in example code [here](https://github.com/naver/pinpoint-plugin-sample/blob/master/plugin/src/main/java/com/navercorp/pinpoint/plugin/sample/_09_Adding_Getter/RecordFieldInterceptor.java).

Is there anyway I can write something like below to record it:
```    recorder.recordAttribute(SamplePluginConstants.ANNOTATION_KEY_MY_VALUE, "com.my.User.userId");```

**Comment by seaward** [comment]
Your last answer is not helpful to me...

**Comment by minwoo-jung** [comment]
@seaward 

Please see this [code](https://github.com/naver/pinpoint/blob/1507e0eac34210a49df900d843966fb3c47133aa/plugins/httpclient4/src/main/java/com/navercorp/pinpoint/plugin/httpclient4/interceptor/HttpClientConnectionManagerConnectMethodInterceptor.java)

You'are right. You shoud using api (recorder.recordAttribute)

**Comment by minwoo-jung** [comment]
Also [This example code](https://github.com/naver/pinpoint-plugin-sample/blob/master/plugin/src/main/java/com/navercorp/pinpoint/plugin/sample/_02_Injecting_Custom_Interceptor/RecordArgsAndReturnValueInterceptor.java) will be a great help to you.
