### ISSUE TITLE
why configuration  support nginx lost request_time

### ISSUE THREAD

**Issue by hexulin-miaomiao** [naver/pinpoint#3769]
set $http_pinpoint_proxy_header "t=$msec D=$request_time";
proxy_set_header Pinpoint-ProxyNginx $http_pinpoint_proxy_header;
i print the args   t and D  like this  result  
t=1517213021.624 D=0.000
t=1517213029.960 D=0.000
t=1517213036.308 D=0.000
t=1517213052.756 D=0.000
t=1517213086.684 D=0.000
t=1517213146.237 D=0.000
t=1517213736.516 D=0.000
i can not get the request_time
could you tell me why?
nginx  version  is 1.12.2
pinpoint version is 1.7.0
thanks

**Comment by jaehong-kim** [comment]
@hexulin-miaomiao 
If $ request_time 0, it is ignored.
