### ISSUE TITLE
Error opening zip file or JAR manifest missing 

### ISSUE THREAD

**Issue by prashantnitt07** [naver/pinpoint#3778]
Dear ,
we are getting below error for instantiating  pinpoint agent on tomcat 

Error opening zip file or JAR manifest missing : /app/pinpoint-agent/pinpoint-bootstrap-1.6.2.jar 
Error occurred during initialization of VM
agent library failed to init: instrument

please help , what is solution

**Comment by minwoo-jung** [comment]
Hi~

Please rebuild pinpoint. Maybe pinpoint-bootstrap-1.6.2.jar file don't have MANIFEST.MF file.

**Comment by chtompki** [comment]
I see the same issue with `pinpoint-bootstrap-1.7.1.jar` using:

```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

on tomcat. With:

```
-javaagent:/opt/pinpoint-agent/pinpoint-bootstrap-1.7.1.jar -Dpinpoint.agentId=test-agent -Dpinpoint.pinpoint.applicationName=my-app
```

In my `JAVA_OPTS`.

**Comment by chtompki** [comment]
I'll attempt the re-build option using the `tar.gz` out of the directory under `/agent/target` post build, and see how that goes.
