### ISSUE TITLE
未找到要求的 FROM 关键字

### ISSUE THREAD

**Issue by WJspring** [naver/pinpoint#3781]
#### Description
pinpoint sql 解析报错（未找到要求的 FROM 关键字），但应用sql解析正常，是否属于误报？请解答！thanks！
#### Environment

* Pinpoint version:1.6.2
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by huoqiangwa** [comment]
what are you talking about?
