### ISSUE TITLE
Can we config the “Search Depth” of the pinpoint please?

### ISSUE THREAD

**Issue by SmileAngel007** [naver/pinpoint#3782]
Since the defacult value of the “Search Depth” ranges 1-4 ,now we want to enlarge the picture of the web view,can we config the “Search Depth” to 1-10 or other bigger numbers and ensure the data displays correctly?? Thanks very much~~~I am a greenhand now , thanks again~~~

**Comment by Xylus** [comment]
Hi @SmileAngel007 
Changing search depth is something we have on our radar, but it has very strong implications on the UI (both design and performance) as well as server (it could bring a server down if the server map is sufficiently large enough).
We will probably look into it in the future but it won't be anytime soon.

In the mean time, if you're free to customize your own pinpoint web instance to support search depth greater than 4 if you'd like.

**Comment by SmileAngel007** [comment]
ok，get it ，thank you very much~

**Comment by SmileAngel007** [comment]
Whether we can use the hierarchical mechanism to realize the link of clicking any service to display the associated service, and finally splicing into a large image？

**Comment by Xylus** [comment]
@SmileAngel007 Yes, that would be great. Some way to expand the depth of a node without rendering the whole map again is exactly what we would love to have.
Unfortunately, I don't think our server map rendering library supports that, so it'll require an overhaul.

**Comment by SmileAngel007** [comment]
ok， thank you for your answer~
