### ISSUE TITLE
SpringBeansPlugin

### ISSUE THREAD

**Issue by geekMessi** [naver/pinpoint#3789]
Hi ,Sorry for bothering you again.
SpringBeansPlugin has provided two transform  way : 
1. COMPONENT_SCAN , transform when Spring‘s Class **ClassPathBeanDefinitionScanner** doScan, while at this monment  the beans class are not loaded by AppClassLoader.So **MatchableClassFileTransformerDispatcher** can add a dynamicTransformer to those class.
2. POST_PROCESSOR , transform when Spring's Class **AbstractAutowireCapableBeanFactory** createBeanInstance ,while at this monment the beans has been loaded. So The following step is retransforming.And then transform.

Are there any difference between those two ways?  While we cannot transform the bean defined in xml file with the default way COMPONENT_SCAN .
Are there any risk with combined use of those two way ? 

Thanks a lot.

**Comment by Xylus** [comment]
Hi @geekMessi 
*COMPONENT_SCAN* is for transforming beans registered using annotations (`@Controller`, @Component`, etc) discovered via packages defined in `<context-component-scan ...>`.
*POST_PROCESSOR* is for transforming beans registered in xml via `<bean ...`>.

So you'll have to configure them depending on how your beans are registered, and will even have to mix them both if your application is configured using both annotation and xml.
