### ISSUE TITLE
pinpoint-web user group page doesn't show phone number when i update the user‘s’ info

### ISSUE THREAD

**Issue by OTAKU-Wang** [naver/pinpoint#3799]
#### Description

When I update the user information, the user's information has been saved to the database. However, the user's phone number can not be displayed when editing again.
![](https://raw.githubusercontent.com/OTAKU-Wang/MarkdownPic/master/pinpoint/TIM%E5%9B%BE%E7%89%8720180205144024.png)
#### Environment

* Pinpoint version: 1.7.2-SNAPSHOT
* OS, WAS, affected library, etc: unbuntu 16.04
* Additional details (e.g. how your collector/web is set up):

#### Additional Info

https://github.com/naver/pinpoint/blob/f17dde245f66fa11f42662feaa1cf484c73fc366/web/src/main/webapp/features/configuration/userGroup/pinpoint-user.directive.js#L202
Changing the code `oPinpointUser.phone` to `oPinpointUser.phoneNumber` can solve the problem.

**Comment by minwoo-jung** [comment]
@denzelsN please check this issue.

**Comment by denzelsN** [comment]
@OTAKU-Wang 
Thanks :)
I fixed it.
