### ISSUE TITLE
pinpoint-web can't get the request record if it's not the first request after server started

### ISSUE THREAD

**Issue by meekoo** [naver/pinpoint#3802]
I have deployed pinpiont several days ago. but find one problem, after starting server and i posted request to it, then visit web i find this request. next to it i posted second request then visit web again，but can't find the second request ，i have try this many times.  I checked the log of agent, but no error.  help me please

**Comment by koo-taejin** [comment]
Might have to do with sampling rate.
Could you check profiler.sampling.rate in pinpoint.config?

**Comment by meekoo** [comment]
I modified this rate, it worked. Thanks a lot. By the way, if change this rate from 20 to 1 will Influence the server . Could you give me a suggestion. Thanks a lot!

**Comment by koo-taejin** [comment]
We are conducting performance tests on a daily basis,
Generally, it is estimated that overhead of about 3% occurs even if 100% sampling is performed.
However, depending on the situation,(server spec, the form of tracking, and whether or not it is async.) We can not know the exact value in your environment.

thanks.

**Comment by meekoo** [comment]
thanks for your answer.
