### ISSUE TITLE
pinpoint-web can't get the request record 

### ISSUE THREAD

**Issue by chuanyi-fang** [naver/pinpoint#3809]
**pinpoint-web can't get the request record ,but can get the TPS in the inspector.How to sovle it?**
![_20180206174046](https://user-images.githubusercontent.com/20055737/35852094-ea3e7e86-0b64-11e8-8785-3dc77f2a56d9.png)
![_20180206174024](https://user-images.githubusercontent.com/20055737/35852086-e5636070-0b64-11e8-9b90-bc8cb28e5e36.png)

**Comment by chuanyi-fang** [comment]
I found this error.What should I change the configuration to solve problem?
![_20180206185114](https://user-images.githubusercontent.com/20055737/35855655-cb965fee-0b6e-11e8-9853-81e7a6608f4b.png)

**Comment by koo-taejin** [comment]
hi chuanyi-fang

Please check if you can connect to this address.

Make sure that the target port is open or port is not blocked by a firewall, etc..,

thanks.

**Comment by chuanyi-fang** [comment]
I have checked the connect is done like above file.And I have closed all firewall.the target(10.139.11.24) port is opened.but the error (java.net.PortUnreachableException: ICMP Port Unreachable) also happen.
![_20180207103043](https://user-images.githubusercontent.com/20055737/35895395-341ae804-0bf2-11e8-8d79-af9d35d650ff.png)
![_20180207103146](https://user-images.githubusercontent.com/20055737/35895396-344bd0c2-0bf2-11e8-81aa-25045bd44e42.png)
![_20180207103217](https://user-images.githubusercontent.com/20055737/35895397-34813bfe-0bf2-11e8-9e17-cc857a0cb213.png)

**Comment by chuanyi-fang** [comment]
by your advice,I hava solve the question.thank you very much.
by the way,what mean is 'wasonly' button?

**Comment by koo-taejin** [comment]
please refer to this link #3179
