### ISSUE TITLE
is it enable to change target function arguments value?

### ISSUE THREAD

**Issue by lopiter** [naver/pinpoint#3811]
hi, i am developing plugin for kafka.

i have one question.

can i change target function arguments value in before method??

below code is my interceptor
```java
@Override
    public void before(Object target, Object[] args) {
        args[0] = "b";
    }
```

and below code is my target function
```java
public void print(String a) {
        System.out.print(a);
    }
```

i expected to that argument value is changed , but it's not working.

is there some way to change argument value??

**Comment by Xylus** [comment]
Hi @lopiter 
The above will not work as all you're doing in your interceptor is changing the object reference of args[0] to *"b"*. The original reference (the one in your target method) will still be pointing to the original value.
Furthermore, String is immutable so you can't mutate the state of String a in the target method.

If the argument to `print` was a mutable object (let's call it **A** with a `setValue(String value)` method), what you could have done was `(A) args[0].setValue("b")` in your interceptor code. But you can't do this to the `print` method above.

**Comment by lopiter** [comment]
Thank you for your explanation, @Xylus .
I understand what you said.
