### ISSUE TITLE
can't find any data in PP-web after deploying app with PP-agent in docker.

### ISSUE THREAD

**Issue by chuanyi-fang** [naver/pinpoint#3819]
I have deployed an app with agent in docker and pp-web、pp-collector in VM ,but it can't work like the 
 file. and It can monitor an app deployed  with agent  in VM.
**If the agent can't support in docker or what can I do to solve the problem.**

![_20180211093147](https://user-images.githubusercontent.com/20055737/36068361-aa082f1c-0f0e-11e8-97bf-6b0c8c110f02.png)
![_20180211093230](https://user-images.githubusercontent.com/20055737/36068362-aa3470f4-0f0e-11e8-8fd9-8835a819e6a6.png)

**Comment by chuanyi-fang** [comment]
I found this error in the pinpoint-collector log。
![_20180211160143](https://user-images.githubusercontent.com/20055737/36071165-f633b880-0f44-11e8-83e0-e29f57a15fb9.png)

**Comment by Xylus** [comment]
Hi @chuanyi-fang 
From the first screenshot, it looks like UDP packets aren't reaching your collector. Please check your docker configuration to allow this.
Furthermore, your second screenshot seems to indicate that channel properties aren't being populated (which should be set during handshake). I would suggest taking a look at your agent log as well as your collector's DEBUG log to see what's going on.

**Comment by RoySRose** [comment]
@chuanyi-fang 
I don't think this will help with after all this time. But just to let you know, [Official Docker Image](https://github.com/naver/pinpoint-docker) is now supported.
