### ISSUE TITLE
pinpoint-col

### ISSUE THREAD

**Issue by pengchen19881205** [naver/pinpoint#3820]
![default](https://user-images.githubusercontent.com/31526564/36084964-e5b006d6-0ffc-11e8-93bf-dae81da03025.png)

**Comment by pengchen19881205** [comment]
这个报错是什么问题？

**Comment by emeroad** [comment]
Read the contirbution guide 
 - https://github.com/naver/pinpoint/wiki/Pinpoint-Plugin-Developer-Guide#iii-plugin-contribution-guideline
