### ISSUE TITLE
Only first request to profiled application is shown

### ISSUE THREAD

**Issue by lamotik** [naver/pinpoint#3822]
#### Description

Hi, 

I'm using pinpoint with no changes to the agent, web or collector.
Web module deployed as ROOT (have also tried to change server.xml as described [here](http://www.baeldung.com/tomcat-root-application)). When I try to open my web application that is profiled, the first request to it is displayed in pinpoint web view almost immediately. But all other actions in my application (async or sync calls) are not displayed at all.

Small side errors (not so important for me)
- REAL TIME working (also this is seen in logs) in web module, but on UI it displays error
  > Closed Connection. Select node again.

  Possible error in log of pinpoint-web
  `[ERROR](o.s.w.s.s.s.DefaultHandshakeHandler) Handshake failed due to invalid Upgrade header: null`

- While starting pinpoint-web and pinpoint-collector getting error
  > Caused by: java.net.BindException: Address already in use

  about port 9997, but I've checked it is used only by this java process

#### Environment

* Pinpoint version: 1.7.1, all config files not changed (although I was trying to change some parameter like profiler.include); web and collector are deployed on tomcat 8.5.24 with open port 2107.
* OS, WAS, affected library, etc: my profiled web app is nothing special  jsp/sping/ws stack deployed to another Tomcat 8.0.20. Java version is 8, although, java env variables are set according to your installation guide. Here is config for adding java agent to tomcat with monitored web app:
> CATALINA_OPTS="$CATALINA_OPTS -javaagent:/opt/pinpoint/pinpoint-agent/pinpoint-bootstrap-1.7.1.jar"
> CATALINA_OPTS="$CATALINA_OPTS -Dpinpoint.agentId=RaveAgent"
> CATALINA_OPTS="$CATALINA_OPTS -Dpinpoint.applicationName=VERA"

* Additional details (e.g. how your collector/web is set up): no changes done

#### Additional Info

Attaching agent log:
[RaveAgent-pinpoint.log](https://github.com/naver/pinpoint/files/1717684/RaveAgent-pinpoint.log)
And pinpoint-web and -collector logs from Tomcat log directory:
[catalina.2018-02-12.log](https://github.com/naver/pinpoint/files/1717687/catalina.2018-02-12.log)
[localhost.2018-02-12.log](https://github.com/naver/pinpoint/files/1717688/localhost.2018-02-12.log)
[localhost_access_log.2018-02-12.txt](https://github.com/naver/pinpoint/files/1717689/localhost_access_log.2018-02-12.txt)
[stat.log](https://github.com/naver/pinpoint/files/1717690/stat.log)

**Comment by emeroad** [comment]
Perhaps this is a problem caused by the elastic beanstalk.
If you are using EBS, we recommend you refer to the issues below.
 - https://stackoverflow.com/questions/32610707/handshake-failed-due-to-invalid-upgrade-header-in-tomcat-deployed-in-ebs

**Comment by emeroad** [comment]
In addition, we recommend that you modify the sampling rate.

$AGENT_DIR/pinpoint.config
```
# 1 out of n transactions will be sampled where n is the rate. (20: 5%)
profiler.sampling.rate = 20
```

**Comment by koo-taejin** [comment]
hi lamotik 

Can know the following problems will not work properly.

`` `
// catalina.2018-02-12.log
12-Feb-2018 20: 54: 02.174 WARNING [main] org.apache.catalina.core.StandardContext.setPath A context path is either an empty string or start with a '/' and do not end with a '/' . The path [ROOT] does not meet these criteria and has been changed to [/ ROOT]
`` `

I suggest that you fix the problem and try again.

thanks.

**Comment by lamotik** [comment]
Hi guys,

thank you for your responses. 
`profiler.sampling.rate = 1`
was the exact solution!

I'm not using EBS, but I'll solution from @koo-taejin and will write about results

**Comment by lamotik** [comment]
Hi guys, 
The main point for me is to get most of call stack logs. As I understand, it is configured from pinpoint-agent/pinpoint.config. But looks like pinpoint is doing its job using just default config. Great job!

@koo-taejin, thank you very much for your finding, but unfortunately, it didn't help
after I've fixed this in server.xml. So now situation is next:
- error about port already in use dissappeared
- pinpoint-web renamed to ROOT.war
- no warnings related to path mismatch in catalina.out while starting - [catalina.log](https://github.com/naver/pinpoint/files/1720086/catalina.log)
- config in server.xml in Tomcat where pinpoint-web deployed:
`<Context path="" docBase="ROOT">`
`<WatchedResource>WEB-INF/web.xml</WatchedResource>`
`</Context>`
- error in chrome console - [chrome.log](https://github.com/naver/pinpoint/files/1720114/chrome.log)
- logs from apache proxy - [proxy.log](https://github.com/naver/pinpoint/files/1720110/proxy.log)
- apache proxy hhtpd.conf:
`ProxyPass / http://127.0.0.1:2107/`
`ProxyPassReverse / http://127.0.0.1:2107/`

**Comment by Xylus** [comment]
Hi @lamotik 
```
2018-02-13 14:35:26 [ERROR](o.s.w.s.s.s.DefaultHandshakeHandler) Handshake failed due to invalid Upgrade header: null
```
Perhaps you haven't set proxy for websocket?
https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html

**Comment by lamotik** [comment]
Exactly! Now I have, although it's not working even with `/ws/` or `/ws`. 
But I think that now I'm on the correct path. Thank you for assistance!

Part of httpd.conf file:
`ProxyPass /ws  ws://127.0.0.1:2107/`
`ProxyPassReverse /ws  ws://127.0.0.1:2107/`
`ProxyPass / http://127.0.0.1:2107/`
`ProxyPassReverse / http://127.0.0.1:2107/`

**Comment by lamotik** [comment]
Hi,
Solution in my case for CentOS 6 was next - 

1. Download Apache module sources from this [gist](https://gist.github.com/bodgit/80a2fb09170596589a03)

2. Follow installation instruction from this [post](https://stackoverflow.com/a/31255503/715022) on stackoverflow
