### ISSUE TITLE
Spring Boot with REST (JAX-RS): Unable to collect data

### ISSUE THREAD

**Issue by sirmad007** [naver/pinpoint#3823]
We have several servers based on SpringBoot and REST (JAX-RS).
i setup pinpoint and successfully started one of our servers with the pinpoint agent.
Than i submitted some REST requests to our server.

But in the webview i see no data at all

[RDBS_AGENT -pinpoint.log](https://github.com/naver/pinpoint/files/1720650/RDBS_AGENT.-pinpoint.log)

![image](https://user-images.githubusercontent.com/18436278/36160465-823eb72e-10e1-11e8-8be6-951c5a3ebe49.png)

**Comment by Xylus** [comment]
Hi @sirmad007 
From the log, it seems like the agent is not able to deduce the application type :
```
Main class could not be deduced, please set 'profiler.applicationservertype' in pinpoint.config.
If you're running on 1.6.0_24 or prior version of Java, consider upgrading to 1.6.0_25+.
If you're running Tomcat or Tomcat on Spring Boot, please set 'profiler.tomcat.conditional.transform' to false
If you're running Jboss, please set 'profiler.tomcat.conditional.transform' to false
```
Try setting *profiler.applicationservertype-SPRING_BOOT* and *profiler.tomcat.conditional.transform=false* in *pinpoint.config*.

However, even with the above change, I'm not sure your calls will be traced as I don't think we support jax-rs.
Do let us know if you give it a try.
Thanks.

**Comment by sirmad007** [comment]
i changed the configuration.
now i see a little data. but only 1 specific REST call is logged.
i am not sure why this works only for this REST interface but not for the others...
-> is it impossible to use pinpoint with REST calls or will it just not work automatically (do i have to implement some kind of plugin or Annotations ?)

![image](https://user-images.githubusercontent.com/18436278/36207718-2ab81386-1197-11e8-83de-6533db78b115.png)
![image](https://user-images.githubusercontent.com/18436278/36207733-3870e624-1197-11e8-8e18-9eb715c40260.png)
[RDBS_AGENT-pinpoint.log](https://github.com/naver/pinpoint/files/1724220/RDBS_AGENT-pinpoint.log)

**Comment by Xylus** [comment]
Hi @sirmad007 
Not sure if this is related, but try setting *profiler.sampling.rate=1* in *pinpoint.config*. From your logs, it looks like it's set to 20 which means 5% sampling (1 out of 20).
If the problem persists, please send us the agent log with log level set to DEBUG if possible.
Thanks

**Comment by sirmad007** [comment]
Thank you

setting profiler.sampling.rate=1 resolved most of my problems.
i am just wondering: Why is this the default?
