### ISSUE TITLE
Pinpoint configuration is not giving option to add Group Member & Pinpoint User

### ISSUE THREAD

**Issue by altiankur** [naver/pinpoint#3825]
#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

#### Additional Info

![capture](https://user-images.githubusercontent.com/35796721/36259626-c8345d98-1284-11e8-80b4-9de93171a0cd.PNG)

**Comment by denzelsN** [comment]
@altiankur  hi
Check your `editUserInfo` option in `pinpoint-web.properties`.
You can add new member when `editUserInfo` is true.

**Comment by altiankur** [comment]
@denzelsN Hi
Thanks for the reply, i have checked it, the option is 'true'.

**Comment by minwoo-jung** [comment]
@altiankur 
Please ref #3711. This issue is related to your question.
