### ISSUE TITLE
Akka-Http for Scala plugin

### ISSUE THREAD

**Issue by lopiter** [naver/pinpoint#3829]
Title: Akka-Http for Scala Plugin Contribution

Link: https://github.com/lopiter/pinpoint/tree/add-akka-http-plugin
Target: Akka-Http for Scala
Supported Version: 2.12:10.1.0-RC1 , 2.11:10.0.10 ( I tested these versions)
Description: AkkaHttp(https://doc.akka.io/docs/akka-http/current/index.html)

ServiceTypes: AKKA_HTTP_SERVER, AKKA_HTTP_SERVER_INTERNAL

**Comment by dawidmalina** [comment]
Are you going to create pull request?

**Comment by dawidmalina** [comment]
#1301

**Comment by junoyoon** [comment]
Created in #3834
