### ISSUE TITLE
could we break the limitation of max length of 24 for agent_id and application_name

### ISSUE THREAD

**Issue by snakedragon** [naver/pinpoint#3864]
we are using pp as our apm platform, now we felt the the max-length of 24 is too short, could we expand them to 128  if we carefully modify the hbase adpation layer?  what is the most unexpected result if we applying it?  could you give us some advice for this feature?

**Comment by geekMessi** [comment]
The most influence is the rowkey distribution in hbase.
The RangeOneByteSimpleHash should be constructed as following both in collector and web.

```java
    <bean id="traceV2Hasher" class="com.navercorp.pinpoint.common.hbase.distributor.RangeOneByteSimpleHash">
        <constructor-arg type="int" value="136"/>
        <constructor-arg type="int" value="144"/>
        <constructor-arg type="int" value="256"/>
    </bean>
```

**Comment by dawidmalina** [comment]
@snakedragon I would like to have the id longer as well but looks like this is not so easy.
