### ISSUE TITLE
It would be nice if there is a install guide from binary release.

### ISSUE THREAD

**Issue by heeyeonwiz** [naver/pinpoint#3865]
Hello,

Some users including me have troubles with building pinpoint from source code. I couldn't find install guide from pre-built binaries.
It would be nice if there is a install guide from binary release.

Many thanks.
Terry

**Comment by angeloudy** [comment]
Hi
I was having the same trouble but finally got it working. I am planning to write a documentation for new users.

**Comment by tandonraghav** [comment]
Hi,
I am also trying to build it, but no luck till now. Have set the Java variables but still not building.
Please share the steps you have used to make it work.

**Comment by RoySRose** [comment]
Hello, @heeyeonwiz @angeloudy  @tandonraghav.
Please take a look at http://naver.github.io/pinpoint/installation.html#building-pinpoint for the installation. If still have trouble with the build after looking at the docs. Please let me know the current situation. I'll check and try to make up the supplements.
@angeloudy I'll be really glad if you can share your documents and if you don't mind core supplements can be posted on the git page. http://naver.github.io/pinpoint/installation.html
