### ISSUE TITLE
Usability of timeline in inspector more

### ISSUE THREAD

**Issue by ari** [naver/pinpoint#3866]
In the inspector mode there is a green timeline across the top. It contains several elements that are mysterious to new users.

## Yellow dot
<img width="269" alt="screen shot 2018-02-28 at 10 07 25am" src="https://user-images.githubusercontent.com/27023/36760494-34e14386-1c6f-11e8-9196-a5c1a2d3c57c.png">

You can see a yellow dot which you can move by clicking in the timeline. Moving it changes the date-time in the field above, but seems to have no action on any graph. Either this UI device should be removed if it has no purpose or a tooltip on hover might explain its purpose.

## Date format

Dates are all formatted as 2018.02.28 09:51:37 which is quite hard to read. I suggest a more human friendly format.

    28 Feb 9:51:27am

The year is hidden if it is the current year. am/pm format is more natural. The leading 0 is hidden.

For dates which are today and yesterday, I suggest:

    today 9:47:23am

A tooltip on hover might display the full absolute date.

## Numbers in circles

<img width="199" alt="screen shot 2018-02-28 at 10 07 20am" src="https://user-images.githubusercontent.com/27023/36760702-00cd751e-1c70-11e8-9cb0-7f806fc322a8.png">

Those two little "1" in circles. No idea why they are there. A tooltip could be introduced to explain them.

## Moving time and date

There are several devices to select a start/end time and the range. In the menu you can choose "Last 5m, 20m, 1h", etc. However if I zoom in or out, or drag the start and end, they remain selected even though they are now wrong.

Visually this element is detached from the alternative zoom/move tools in the main window below. They should be brought together and interact with each other. "Last 5m" is a convenient shortcut, but it is just a shortcut and does not represent the current state of the view.

**Comment by denzelsN** [comment]
Thank you for your advice.
It will take some time, but I'll try to improve it.
