### ISSUE TITLE
Usability of navigation

### ISSUE THREAD

**Issue by ari** [naver/pinpoint#3867]
Discovering important parts of pinpoint is more difficult that it could be. In particular, until you discover the little "inspector" button, lots of functionality is hidden from new users. I propose some solutions. I use "main mode" to decribe the window that first appears when you log in. "Inspector mode" is the new window that opens when you press "inspector"

### Sidebar tree

In inspector mode the left sidebar shows applications and hosts in a tree. That tree has inconsistent sizing and indenting. If all fonts were the same size, then three levels of indent should show:

Application
 - host
    - app

This would allow all the applications to be listed down the left and not just one 'currently viewed' application. Navigation would then be simpler. For users with a lot of applications, the tree could be collapsible.

### Main mode navigation

In main mode (the first page you reach) the navigation is a dropdown at the top instead of down the left. By integrating the two views, the sidebar on the left is kept at all times and the top navigation eliminated.

### Main mode application panels

Main mode has four additional panels when viewing an application:

 - GoJS linked graph
 - response time scatter graph
 - response code bar chart
 - load bar chart

I propose these panels be brought directly into the inspector view with the existing graphs. That allows them to be larger and easier to see.

If the scrolling is thought to be a problem now this page has more graphs, then collapsible sections could be introduced. Pinpoint should remember your collapsed settings as you navigate between hosts.

### Main mode server panels

The advantage of merging main and inspector modes are that we already have navigation for hosts on the left. So it is simple enough to move the specific server/host graphs into the inspector view, as per the application panels above.

**Comment by denzelsN** [comment]
Thank you for your advice.
It will take some time, but I'll try to improve it.

**Comment by ari** [comment]
Although I don't have the time to learn the app and code a solution, is there anything I can do to break down the UX pieces into manageable tasks and assist in improving the usability without writing code? I suspect many people are turned away from pinpoint because of how obscure some of the most important features are to find in the UI.
