### ISSUE TITLE
1.7.1tracemap is not full compare with 1.6.0

### ISSUE THREAD

**Issue by wahaha001** [naver/pinpoint#3883]
the fellow pic is the tracemap with same request between two versions(1.6.0 \ 1.7.1) .

**Tracemap in 1.6.0 is correct, like this:**PIC1
![image](https://user-images.githubusercontent.com/22269869/37010014-59da358a-2124-11e8-901b-3237beebf93f.png)

**Tracemap in 1.7.1 is wrong, like this:**PIC2
![image](https://user-images.githubusercontent.com/22269869/37010430-74d3d600-2126-11e8-8f49-0ea89a0e3114.png)
PIC3:
![image](https://user-images.githubusercontent.com/22269869/37010508-d5f00990-2126-11e8-9054-62fe81618f0c.png)
(DON'T CARE THE REQUESTS NUMBERS)

ALL THE REQUESTS DATA HAS BEEN COLLECTED,BUT IS NOT CORRECT SHOWN IN ONE TRACEMAP!!

HOW TO FIX IT, ANY ONE CAN HELP??

**Comment by emeroad** [comment]
The question does not help to analyze the problem.
Analyze the pinpoint-web log

**Comment by koo-taejin** [comment]
The three picture's have different base and lookup times.
I would like to ask you again with a picture that has the same base and lookup time.

thanks.

**Comment by wahaha001** [comment]
*pic1:trace from app100006883(server ip:10.5.40.212) , can't see the
request to app100003240*
100006883-IP:10.5.40.212

*pic2:in the same time trace from app100003240,  we can see app100003240
received some requests.*
*pic3:check the trace detail from app100003240, we can see these requests
from ip:10.5.40.212(app100006883)*
100003240-sample trace detail:

​

*​why these request did not shown in one trace map??*
​

**Comment by koo-taejin** [comment]
I can't see images that you posted
please check it.
