### ISSUE TITLE
About rowKey design, MD5 or hash prefix 

### ISSUE THREAD

**Issue by ld000** [naver/pinpoint#3885]
hi, we are using pinpoint. And found HBase data is not evenly distributed in region server, cause some application has high QPS, some have low QPS.

so, I think set the applicationName and agentId in rowKey to MD5 and use HexStringSplit as SPLITALGO is better?

**Comment by emeroad** [comment]
Already we tested with different hash algorithms, but It has no effect.
We need validated data for patch.

**Comment by ld000** [comment]
We solve it. cuz we change the applicationName length and need to modify bucket config.
