### ISSUE TITLE
Pinpoint-web can't get request data and Heap usage data etc.

### ISSUE THREAD

**Issue by chuanyi-fang** [naver/pinpoint#3890]
the  application and agent deployed in window that can not collect data but only agent information.
the same   application and agent deployed in centos that can be collected, it's ok .
how to handle this problem?
agent's conf
[pinpoint.config.txt](https://github.com/naver/pinpoint/files/1795529/pinpoint.config.txt)
colletor' conf
[pinpoint-collector.properties.txt](https://github.com/naver/pinpoint/files/1795547/pinpoint-collector.properties.txt)
#3825 
-------------------------------------------------------------------------------------------------------------------
when I change the conf to  “profiler.statdatasender.transport.type=TCP” 、“profiler.spandatasender.transport.type=TCP ”、“collector.receiver.stat.tcp=true、“collector.receiver.span.tcp=true”，it's ok that  can get request data and Heap usage data etc.
so i doubt that it's UDP's problem.but I don't know how to handle this issue。
-------------------------------------------------------------------------------------------------------------------
what‘s mean with the log?
`2018-03-09 15:11:20 [WARN ](Pinpoint-UDP-Span-Receiver         ) DatagramSocket.setReceiveBufferSize() error. 4194304!=212992`

**Comment by koo-taejin** [comment]
hi chuanyi-fang

If the settings are the same, data will be collected. even in a Windows environment.
It is recommended that you first look at the network status of Window environment.

If it is not a network issue,
Look at the agent log and look for suspicious parts.

If you have a suspicious log, please post it here

thanks.

**Comment by chuanyi-fang** [comment]
when I use TCP to sent span and stat ,it's ok.so i think the network status that is ok.
------------------------------------------------------------
this is agent log,I can't find any suspicious parts.
[test0309-pinpoint.log.txt](https://github.com/naver/pinpoint/files/1796088/test0309-pinpoint.log.txt)

**Comment by koo-taejin** [comment]
If it behaves differently according to the network protocol (tcp, udp), maybe seem to network issue.
It would be better to check if there is anything that interferes with udp communication.(ex) firewall, .. )
