### ISSUE TITLE
When cancel the pinpoint user in the group member, it always displays loading. 

### ISSUE THREAD

**Issue by SFHfeihong** [naver/pinpoint#3898]
I use pinpoint-1.7.1.
OS:centos7

![pinpoint-1](https://user-images.githubusercontent.com/27404167/37378136-e25f93ba-2768-11e8-9074-ddb98bc0b363.png)

When i cancel the pinpoint user in the group member, the web page displays loading all the time.

![pinpoint-2](https://user-images.githubusercontent.com/27404167/37378244-5f160cae-2769-11e8-84ac-60221d485e6f.png)

**Comment by denzelsN** [comment]
@SFHfeihong 
It' bug. 
I fixed it.  https://github.com/naver/pinpoint/pull/3901
thank you :)

**Comment by SFHfeihong** [comment]
Thank you !
