### ISSUE TITLE
support netty ?

### ISSUE THREAD

**Issue by wupengyu** [naver/pinpoint#3903]
#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by wupengyu** [comment]
Pinpoint version: 1.7.1
linux

**Comment by wupengyu** [comment]
i‘m  spring+ netty ;    profiler.applicationservertype= ?

**Comment by emeroad** [comment]
The transport layer is not supported by pinpoint.
