### ISSUE TITLE
Pinpoint 1.7.1 WAS 내 MassageHandler 부분 문의드립니다.

### ISSUE THREAD

**Issue by joek8901** [naver/pinpoint#3913]
#### Description
pinpoint 를 이용해서 was 를 모니터링하고 있습니다.
기본적으로 http 로 인입되는 건 DB 연결까지 화면에 표기가 되는데요,
RabbitMQ 에 Handler 로 들어온 경우에는 스캐터차트에 아무것도 나오지 않습니다.
RabbitMQ Plugin 을 적용해야만 하나요? 아래와 같은 곳에 클래스랑 메서드 세팅했으나,
여전히 스캐터차트를 비롯해서 연결된 서비스가 나오진 않았습니다.
profiler.message.queue.client.handler.methods=

추가로 문의드리고 싶은건 application name / agentid 가 있는데, 
잘못등록된 것을 삭제처리할 수 있는지도 문의드립니다.

감사합니다!

#### Environment

* Pinpoint version: 1.7.1
* OS, WAS, affected library, etc: CentOS7.2 / Tomcat8.0
* Additional details (e.g. how your collector/web is set up): pinpoint

**Comment by Xylus** [comment]
@joek8901님 안녕하세요,
1.7.1 RabbitMQ 플러그인은 **DefaultConsumer**를 상속 받아 구현한 **Consumer**를 `Channel.basicConsume(...)`로 등록하고, 하위 **Consumer**가 `handleDelivery(...)` 메소드를 override 하여 `super.handleDelivery(...)`를 직접 호출하는 경우에만 트레이스가 됩니다.
대부분의 use-case에서는 트레이스가 되지 않을 것 같습니다.

1.7.2 부터는 이를 보완하기 위해 RabbitMQ 플러그인이 수정되었습니다. 아직 정식 출시되지 않았지만, 해당 수정사항은 현재 master branch에 들어가 있습니다. (#3887)
1.7.2 agent가 출시되거나, 가능하시다면 master branch를 빌드하시고 나온 agent를 사용해보시면 해당 이슈는 어느 정도 개선될 것 같습니다.

추가로 application name / agent id 삭제는 [요 내용](https://github.com/naver/pinpoint/wiki/FAQ#how-do-i-delete-application-name-andor-agent-id-from-hbase)을 참고하시면 됩니다.

감사합니다.

**Comment by joek8901** [comment]
답변 감사드립니다. 실제로 제가 사용했던 부분은 RabbitMQ Plugin 은 아니며,
profiler.message.queue.client.handler.methods=
이 부분입니다. 내용상으로는 사용자가 개발한 Queue Handler 에서도 쓸수 있는 것처럼 되어있어서
해당 부분으로 개발한 Class 를 넣었는데도 안되서, 문의를 드렸습니다.
답변 주신 부분으로는 RabbitMQ Plugin 사용 시 해소가 될 것으로 판단되는데요,
사용을 위해서 Maven Build 시 아래와 같은 에러가 발생합니다.
Pinpoint 전체를 내려받은 다음 eclipse 상에서 프로젝트 전체 install 을 수행했습니다.
build 관련된 내용이 따로 소개되어 있으면, 안내해주시면 감사하겠습니다.

[ERROR] Failed to execute goal on project pinpoint-bootstrap-core: Could not resolve dependencies for project com.navercorp.pinpoint:pinpoint-bootstrap-core:jar:1.7.2-SNAPSHOT: The following artifacts could not be resolved: com.navercorp.pinpoint:pinpoint-annotations:jar:1.7.2-SNAPSHOT, com.navercorp.pinpoint:pinpoint-commons:jar:1.7.2-SNAPSHOT: Could not find artifact com.navercorp.pinpoint:pinpoint-annotations:jar:1.7.2-SNAPSHOT in cloudera (https://repository.cloudera.com/artifactory/cloudera-repos/) -> [Help 1]

**Comment by Xylus** [comment]
maven 빌드는 https://github.com/naver/pinpoint/blob/master/doc/installation.md#building-pinpoint 에 소개되어 있습니다.

추가적으로 궁금하신 사항 있으시면 말씀 부탁드립니다.
감사합니다.
