### ISSUE TITLE
Confusion about apiId 

### ISSUE THREAD

**Issue by chengbinghan** [naver/pinpoint#3922]
pinpoint version:1.7.1
os: windows 7

I have a confusion about how apiId was created. ( apiId is recorded in spanevent)

As we can see, pinpoint  can trace method and each metdod (spanevent) has a apiId created by agent. you can see in the source code  at: 
com.navercorp.pinpoint.profiler.metadata.SimpleCache.java
//--------------------code--------------------start
public class SimpleCache<T> {
    private final AtomicInteger idGen;            //create an apiId by AtomicInteger each time .
    private final ConcurrentMap<T, Result> cache; // put apiId in this cache
.   ............
//--------------code------------------end

   A spanevent  object can represent a  a method that we invoked,   each  spanevent (method) has a apiId , as we can see the code which can create apiId  above , The first time we invoke a method ,the method will create a apiId and put it in cache. the second time  you invoke the method ,it will  get it from cache.  
and a spanevent will represents  method invoke message and  record it to  hbase. 

  so , there are something i  Confused,  for example,
 
the first time , you invoke a method (we just call it  m1)， and agent will create a spanevent for m1, also ,spanevent has a apiId create by SimpleCache.java and put it in cache.  We can assume the apiId is 1.
and the invoke trace message (spanevent) will be recorded in hbase.

the second time , we start the server (so the cache is empty), the agent restart,  then we invoke the m1, also m1 has a spanevent , and the spanevent has a apiId, because it create by  SimpleCache. and you don't known what numbet it is this time. maybe it is 2 this time.  also this time ,the spanevent data will be recorded in hbase.

so , as we can see , in hbase , some spanevent represents the method m1 invoke message. but the apiId is different for m1 . I want to known, how to handle it, because in pinpoint web project , we 'select' data from hbase.   for example we invoke redis by java, (use jedis lib to operate redis ) , but the redis api method ,such as : redis.clients.jedis.BinaryJedis.set(byte[] key, byte[] value) 
 has different apiId, i wonder how to Statistical 
 the data of redis method. because the apiId is different , if you restart the agent. as we can see there is no problem from pinpoint web UI from a Browser.

**Comment by Xylus** [comment]
Hi @chengbinghan 
Api id is tied to a single JVM lifecycle, and is stored along with agent id and agent start time.
So method m1 will have it's api id stored separately before and after a server restart.
