### ISSUE TITLE
AS/400 or SQL Server not supported?

### ISSUE THREAD

**Issue by JaviBeCl** [naver/pinpoint#3923]
As I have checked in [http://naver.github.io/pinpoint/], in the Supported Modules section, it seems both are not supported.

Is there any idea of supporting AS/400 or SQL Server in following releases?

    JDK 6+
    Tomcat 6/7/8, Jetty 8/9, JBoss EAP 6, Resin 4, Websphere 6/7/8
    Spring, Spring Boot (Embedded Tomcat, Jetty)
    Apache HTTP Client 3.x/4.x, JDK HttpConnector, GoogleHttpClient, OkHttpClient, NingAsyncHttpClient
    Thrift Client, Thrift Service, DUBBO PROVIDER, DUBBO CONSUMER
    **MySQL, Oracle, MSSQL, CUBRID,POSTGRESQL, MARIA**
    Arcus, Memcached, Redis, CASSANDRA
    iBATIS, MyBatis
    DBCP, DBCP2, HIKARICP
    gson, Jackson, Json Lib
    log4j, Logback

Thanks in advance.

**Comment by koo-taejin** [comment]
hi  JaviBeCl 

We have no plans to support AS/400 or SQL Server.
In addition, we are not familiar with AS/400 or SQL Server.
If you develop a plugin and contribute it, it will be a big help for us.

thanks.

**Comment by JaviBeCl** [comment]
Thanks a lot for the reply Koo.
