### ISSUE TITLE
MySQL showed as "unknown"

### ISSUE THREAD

**Issue by JaviBeCl** [naver/pinpoint#3924]
#### Description
pinPoint would be showing it is a MySQL connection, but it would not be showing its name.
Instead it recovers "Unknown"

#### Environment

* Pinpoint version: 1.7.1
* OS, WAS, affected library, etc: N/A
* Additional details (e.g. how your collector/web is set up): 

Thanks in advance.

**Comment by Xylus** [comment]
Hi @JaviBeCl 
This may or may not be related, but the database name is parsed using the jdbc url, ie `jdbc:mysql://xxx.xxx.xxx.xxx/$DATABASE`
If you don't have it set there then it'll show up as unknown.

If you have set it in your mysql jdbc url but the database name is showing UNKNOWN, please post/attach the full DEBUG log of your agent with logs generated from calling mysql?
The *log4j.xml* is in *$PINPOINT_AGENT/lib* directory.
Thanks.

**Comment by JaviBeCl** [comment]
Hi Xylus, 
First of all, thanks for your help.
Related to the jdbc url, it seems to be ok (jdbc:mysql://xxx.xxx.xxx.xxx/$DATABASE).

Talking about the DEBUG LOG, client seems to be reluctant to allow me to attach the log.
Is there anything else I could check?

What i have checked is this plugin class is having problems:

2018-03-27 07:07:49 [WARN ](.i.c.JarProfilerPluginClassInjector) Failed to load plugin class com.navercorp.pinpoint.plugin.jdbc.mysql.interceptor.MySQLConnectionCreateInterceptor with classLoader com.ibm.ws.bootstrap.ExtClassLoader@4039c9a9

**Comment by JaviBeCl** [comment]
Hi again @Xylus, 
I am now able to share logs ^^. Hope it helps.

[DSWAS85INTRANET-pinpoint.log](https://github.com/naver/pinpoint/files/1879446/DSWAS85INTRANET-pinpoint.log)
[DSWAS85SEDE-pinpoint.log](https://github.com/naver/pinpoint/files/1879447/DSWAS85SEDE-pinpoint.log)
[DSWAS85WWW-pinpoint.log](https://github.com/naver/pinpoint/files/1879448/DSWAS85WWW-pinpoint.log)

**Comment by RoySRose** [comment]
Hello @JaviBeCl 
I was looking into the logs and found ibm websphere classloader
 - com.ibm.ws.bootstrap.ExtClassLoader.loadClass

Maybe you can find some answers through [here](https://www.ibm.com/support/knowledgecenter/en/SSAW57_8.0.0/com.ibm.websphere.nd.doc/info/ae/ae/rtrb_classload_viewer.html#rtrb_classload_viewer__cnfexc)
The solution to this can be similar to #3560
Let me know if this helps
