### ISSUE TITLE
ExecutionPolicy under what circumstances, who can give an example to explain it?

### ISSUE THREAD

**Issue by jacksu** [naver/pinpoint#3928]
#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by Xylus** [comment]
Hi @jacksu 
ExecutionPolicy is closely related to interceptor scope.
You can check out the detail in [one of our samples](https://github.com/naver/pinpoint-plugin-sample/blob/master/plugin/src/main/java/com/navercorp/pinpoint/plugin/sample/_03_Interceptor_Scope__Prevent_Duplicated_Trace/Sample_03_Use_Interceptor_Scope_To_Prevent_Duplicated_Trace.java).

**Comment by jacksu** [comment]
@Xylus  thanks, I haved understand.
