### ISSUE TITLE
quickstart/bin/start-collector.sh is not working !

### ISSUE THREAD

**Issue by yltangpython** [naver/pinpoint#3935]
#### Description

My operate-system is centos 6.5 ，My JDK 6/7/8 is installed ，the pinpoint version is 1.7.2 , the hbase version is 1.2.6 .but
when I run quickstart/bin/start-collector.sh the error is below:

Mar 23, 2018 3:39:14 PM org.apache.catalina.startup.ContextConfig processAnnotationsJar
SEVERE: Unable to process Jar entry [module-info.class] from Jar [jar:file:/setup/pinpoint-master/quickstart/collector/target/deploy/WEB-INF/lib/asm-util-6.0.jar!/] for annotations
org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
        at org.apache.tomcat.util.bcel.classfile.Constant.readConstant(Constant.java:133)
        at org.apache.tomcat.util.bcel.classfile.ConstantPool.<init>(ConstantPool.java:60)

#### Environment

* Pinpoint version:1.7.2

[quickstart.collector.log](https://github.com/naver/pinpoint/files/1840567/quickstart.collector.log)

* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by minwoo-jung** [comment]
Hi 

I will test it.

**First of all please check java version.**
Most error with below log message causes java version. You chould use above java version then compiled version of pinpoint collector.
```
org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.navercorp.pinpoint.collector.dao.hbase.HbaseAgentEventDao] for bean with name 'hbaseAgentEventDao' defined in file [/setup/pinpoint-master/quickstart/collector/target/deploy/WEB-INF/classes/com/navercorp/pinpoint/collector/dao/hbase/HbaseAgentEventDao.class]: problem with class file or dependent class; nested exception is java.lang.UnsupportedClassVersionError: com/navercorp/pinpoint/collector/dao/hbase/HbaseAgentEventDao : Unsupported major.minor version 52.0 (unable to load class com.navercorp.pinpoint.collector.dao.hbase.HbaseAgentEventDao)
```
