### ISSUE TITLE
Plugin: creating intermediate virtual nodes

### ISSUE THREAD

**Issue by maartendeprez** [naver/pinpoint#3937]
Hello,

First off, I am quite new to pinpoint development, so forgive me if i missed something simple. Currently i am developing a java agent plugin and would like to create extra virtual nodes to represent logical steps in a transaction. My application receives requests from a number of scripts and connects to a few types of non-java applications to process them.

Outgoing connections are picked up by the jdk-http plugin, which registers only the destination (localhost + random port per request) and groups them together in an "unknown group". When i try to register a destination id during a preceding trace event, it generates extra nodes if the service type is set to TERMINAL, INCLUDE_DESTINATION_ID, but the jdk-http node group is connected to the main node in the application map instead of the outgoing nodes, even though the generated trace tree is correct (showing the jdk-http call as a subcall of the one my plugin intercepts). Is there a way to make it connect like this:

`User --> Application --> Server --> Http`

instead of:

```
User-->Application -->Server
        |------------>Http
```

Alternatively, what would be the correct way of suppressing the jdk-http nodes in this case?

I tried generating two connected transactions from one agent, which leads to the following:

```
User --> Application -|----->Http
            ^---------|
```

Additionally, is there a way to control how the user node is rendered? In this case it, the requests do not really come from human users, but from a limited number of scripts. It would be nice to be able to represent them individually, like this

```
Script 1 -->Application
Script 2 ------^  ^
Script 3 ---------|
```

Thanks in advance!

**Comment by Xylus** [comment]
Hi @maartendeprez 
Server map nodes represent process boundaries, and while what you're looking for might be possible, it would involve way too much hack.
I'm also unsure of the benefits virtual logical nodes would bring apart from the visual differences. (Let me know if I'm missing something crucial)

As per your second question, the *Application* does not know if a request has come from script 1, script 2, or script 3. The only way to separate incoming requests from the application's point of view is by it's end points (uri).
Splitting user nodes by end point could generate hundreds of user nodes and this wouldn't really be feasible, so we merge incoming requests (from an unknown source that does not have an agent installed) into a single *user* node.
If you would like to filter by end point, you can right-click on the `User ---> Application` edge and use **Filter Transaction Wizard**.

**Comment by maartendeprez** [comment]
Hi @Xylus. Thanks for your reply.

I understand and agree that "user" requests should be grouped together into one node by default. However, as i said, for my case they are more like TERMINAL (untraceable) parts of the application on the input side, so it would be nice to be able to create separate nodes by end point, just like the nodes on the outgoing side.

The most crucial part , however, is how the JDK-Http plugin enforces its end point even though my plugin has "better" information in an earlier call. While the JDK-Htpp plugin sees only a bunch of request URIs representing different end points because the destination port changes for every request, my plugin can set different destination IDs or end points based on the actual component that is going to be called. I could not find out how to override the info from the JDK plugin except by changing its source (changing or disabling what it records), which feels a bit like a hack.

So i guess my main question is if there is a way to override the end point from my plugin, so that no extra nodes are created for the end point created in JDK. If not, can it be disabled by a configuration option?

**Comment by Xylus** [comment]
Oh I see, if you have a customized plugin for your application's jdk http calls, you can definitely use that in place of the default jdk-http plugin.
This can be done by simply removing the jdk-http plugin from `$PINPOINT_AGENT/plugin` directory and throwing your own plugin in there.

A simpler way would have been to set the enable flag for jdk-http in *pinpoint.config*, but unfortunately, our jdk-http plugin doesn't have this option.
Feel free to code this in and throw us a PR if you'd like :)
