### ISSUE TITLE
Why the pinpoint web does not work perfectly?

### ISSUE THREAD

**Issue by yltangpython** [naver/pinpoint#3939]
![error](https://user-images.githubusercontent.com/21216967/37898716-1dfef070-311c-11e8-9b14-87fa6b712f41.png)

#### Description

In the web ,the “select an application ” can not be selected!

#### Environment

* Pinpoint version:1.7.1
OS: Centos 6.5 64bit
Hbase:1.2.6
Tomcat:apache-tomcat-8.5.29
JDK :1.8
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by ari** [comment]
I confirm this also happens for me sometimes and a reload fixes it. When it happens the html looks like this:
`<img ng-hide="hideFakeApplication" src="images/navbar_application_fake.png" style="position:absolute;left:0;top:5px;" class="">`

The option list in `<select class="application" ng-disabled="disableApplication" id="navbar_application">` is empty.

I see no errors in page requests or in js console, other than:

    Loading failed for the <script> with source “https://****/web/scripts/extra/google-analytics.js?v=1515052287560”.

A few more browser reloads and it works again. This is Firefox on OSX.

**Comment by Xylus** [comment]
Hi, @yltangpython thanks for reporting.
@ari thank you for your analysis. It'll help a lot in figuring this out.

We'll take a look at this.
cc @denzels

**Comment by denzelsN** [comment]
Hi, @yltangpython 
Check you browser ad-block plugin.
Most ad-block plugin is caused by blocking google-analytics loading.

@ari thank you for your analysis.
We're improving this problem.
