### ISSUE TITLE
Not able to add user

### ISSUE THREAD

**Issue by gauravrishi168** [naver/pinpoint#3941]
#### Description

Not able to add user.
#### Environment

* Pinpoint version: 1.7.1
* OS, WAS, affected library, etc: Linux , 3.10.0-514.el7.x86_64
* Additional details (e.g. how your collector/web is set up): added the war in /root/apache-tomcat-8.0.33/webapps/pinpoint-web-1.7.1

#### Additional Info

I am not able to add the user as it's giving an error.
![image](https://user-images.githubusercontent.com/16059475/37902084-e9661790-3110-11e8-9e9e-1de63129b573.png)

and edituserinfo is already set to true
[root@localhost pinpoint-web-1.7.1]# cat /root/apache-tomcat-8.0.33/webapps/pinpoint-web-1.7.1/WEB-INF/classes/pinpoint-web.properties |grep editUserInfo
**config.editUserInfo=true**
[root@localhost pinpoint-web-1.7.1]#

**Comment by minwoo-jung** [comment]
What version of the pinoint do you use?

Maybe your question is same https://github.com/naver/pinpoint/issues/3711.
