### ISSUE TITLE
Use of WebLogic Plugin

### ISSUE THREAD

**Issue by ing-arriola** [naver/pinpoint#3943]
#### Description

Hello; I am new to the use of Pinpoint; I have recently installed it and I want to monitor an application that is on a WebLogic server. My question is: In the following link you will find a Pinpoint agent:
https://github.com/naver/pinpoint/releases/tag/1.7.1
This agent should not be used and instead the WebLogic .jar must be placed only or this agent should be copied in any convenient place accompanied by the agent that is provided as a plug-in in the following link:
https://github.com/andyspan/pinpoint-weblogic-plugin/tree/master
I really feel confused with the topic of "plug-in", an explanation about it would be very helpful.
I appreciate in advance the help that could be given to me.
#### Environment

* Pinpoint version:1.7.1
* OS, WAS, affected library, etc: Ubuntu 16.04(Pinpoint is installed on this PC) , Weblogic 10.3.6 (Linux Server with Web App to be Monitored)

**Comment by Xylus** [comment]
Hi @ing-arriola 
First of all, to attach pinpoint agent to your application, you need to add it as a vm option (`-javaagent`).
ie `-javaagent:$PINPOINT_AGENT/pinpoint-bootstrap-$VERSION.jar`
Please take a look at http://naver.github.io/pinpoint/installation.html#installation-2 for more details.

The plugins can be added by placing them in `$PINPOINT_AGENT/plugin` directory. Though I don't think the weblogic plugin you';ve linked would work with 1.7.1.

**Comment by ing-arriola** [comment]
Hello Xylus!!
Thanks for your answer!!
Now it is clear to me how to use the plugin; but with respect to your comment on the version of Pinpoint that I am using, then another question arises.
What version of Pinpoint is recommended for the WebLogic plugin to work?
Will it be convenient to use version 1.6.0?

**Comment by Xylus** [comment]
We've never tested the weblogic plugin you've linked so I can't be sure but it seems like it was based off of 1.6.0.
We're currently working on reviewing/updating the weblogic plugin PR sent by the same author (#2570) but this is slated for 1.7.3.

**Comment by ing-arriola** [comment]
Thank you very much for your answer @Xylus !
Although it seems quite strange to me that the plugin exists and has not been used as you say in your comment. In any case I installed a virtual machine with ubuntu 16.04, hbase and hadoop; I will do tests with Pinpoint 1.6.0 that as you mentioned in your comment. Afterwards, I'll leave the results and the specific details of the java, hadoop, hbase, pinpoint and the agent you use in case it's useful to another person.
By the way I also find it interesting that this will be integrated in version 1.7.3 that I imagine will take a while to be available.

**Comment by Xylus** [comment]
Sounds good,
The release of 1.7.3 is still a way off, but there's an option to build from source once the PR gets merged if you'd like.

**Comment by ing-arriola** [comment]
Hello @Xylus 

As I promised, I share my details of OS versions and components used so that the WebLogic plugin works smoothly.
(Monitor PC whit PinPoint)
- SO: Ubutu Server or Ubuntu Desktop 16.04 
- Pinpoint: 1.6.0
- Hbase:1.2.2: Tutorial to Install at https://www.youtube.com/watch?v=zK39o0TMzFo&t=116s
- Hadoop:2.7.2: Tutorial to Install at https://www.youtube.com/watch?v=l1QmEPEAems&t=106s
- Java JDK-8u161
- Apache Tomcat 8.5.29

(PC with Java Web App to monitor)
- WebLogic 10.3.6
- Ubuntu 16.04; RedHat 6.5
- Java JDK-8u161

Thanks!!!

**Comment by Xylus** [comment]
Thanks for sharing @ing-arriola :+1:
