### ISSUE TITLE
Does Pinpoint support RocketMq now?

### ISSUE THREAD

**Issue by anime8** [naver/pinpoint#3961]
#### Description

I want to monitor RocketMq by use pinpoint, but i can't find the plugin about RocketMq. so, does Pinpoint support RocketMq now?

**Comment by RoySRose** [comment]
Hello, @anime8 
Please take a look at our [Supported Module List](http://naver.github.io/pinpoint/index.html#supported-modules-last-updated-20180401).
If it's not there I'm afraid Pinpoint does not support the module yet. But It would be great for RocketMq users and for the project if you could make a plugin for it and throw us a PR!
Have a nice day:)
