### ISSUE TITLE
Pinpoint- configuration support

### ISSUE THREAD

**Issue by gsmba6** [naver/pinpoint#3965]
#### Description
----> I've downloaded - pinpoint-collector-1.7.2-SNAPSHOT,pinpoint-web-1.7.2-SNAPSHOT,pinpoint-agent-1.7.2-SNAPSHOT.tar,hbase-1.2.6-bin.tar

----> without any modification I've started the HBASE and started the collected and web in TOMCAT version 9.0.6

---->  Agent I extracted and placed on the same folder where all the files located.

----> wrote one small JAVA program to wait for half an hour 

----> executed with the below command [java test -javaagent:/root/Documents/pinpointagent/pinpointagent.jar - DpinPoint.applicationaName=testapp -DpinPoint.agentId=count]
Note: program excuted successfully.

I've also ran the HBASE table creation and I could see the 15 tables in HBASE UI

#### Environment
ROOT user
Linux Lin 4.13.0-kali1-amd64

#### Additional Info

Now I'm struct and don't know how to move further could anyone support on this. thanks in advnce

**Comment by RoySRose** [comment]
Hello, @gsmba6 
correct me if I'm wrong.
1. You have completed setting up HBASE.
2. successfully executed PINPOINT-AGENT, PINPOINT-COLLECTOR, PINPOINT-WEB
3. small JAVA program running without any problems.

I believe there isn't anything else to take care of besides monitoring your application(in this case small JAVA program) through PINPOINT-WEB(for the installation of WEB, take a look at [here](http://naver.github.io/pinpoint/installation.html#4-pinpoint-web))
depending on the configuration that you configured for PINPOINT-WEB in TOMCAT. You can access PINPOINT-WEB and the first screen image that you see will be something like [this](http://naver.github.io/pinpoint/overview.html#overview).

**Comment by gsmba6** [comment]
@RoySRose thanks for the quick turn around.

My issue is the Pinpoint web is launching but i could able to see the application name or ID in the web. its plain.. my application drop down is disabled.

**Comment by RoySRose** [comment]
@gsmba6 
I don't think I can be a much help without any logs or further information. 
Since you have downloaded all 
- pinpoint-collector-1.7.2-SNAPSHOT
- pinpoint-web-1.7.2-SNAPSHOTpinpoint-agent-1.7.2-SNAPSHOT.tar,hbase-1.2.6-bin.tar

 Only thing that I can think of https://github.com/naver/pinpoint/issues/2273

**Comment by gsmba6** [comment]
@RoySRose - Issue resolved. 

I've appended the Tomcat - Catalina option in . sh file
But my Eclipse uses its own configuration where I gave the java agent details to VM arguments and the issue resolved and my agent appeared in web UI. 
I can monitor the transactions.
