### ISSUE TITLE
Alarm error

### ISSUE THREAD

**Issue by lilanlong** [naver/pinpoint#3968]
When adding alarm users, cell phone number can't be input into '-', but timed tasks must have '-' when obtaining numbers.

**Comment by minwoo-jung** [comment]
Spaces and other special characters are not allowed. cell phone is used to send alarm message.

**Comment by lilanlong** [comment]
![image](https://user-images.githubusercontent.com/18063071/38225085-c5e07c46-3725-11e8-9886-05695f0ebf81.png)

**Comment by lilanlong** [comment]
![image](https://user-images.githubusercontent.com/18063071/38225146-10552eac-3726-11e8-8719-07962c7ceb75.png)

**Comment by minwoo-jung** [comment]
`removeHyphenForPhoneNumberList` method is not for input UI.
If you want to input special characters, you edit and use on your own.

**Comment by lilanlong** [comment]
I understand, but the system does not allow me to enter '-' when the number is entered, but in the code, the number must contain '-' and only include '-', the cell phone number can be added to the set to send the alarm information.

**Comment by minwoo-jung** [comment]
@lilanlong 
Don't worry. removeHyphenForPhoneNumberList method is also not use in the whole pinpoint logic.
Therefore alarm executes properly.
But lest anyone should misunderstand, I will edit method name or logic to removeHyphenForPhoneNumberList method.

**Comment by lilanlong** [comment]
Thank you
