### ISSUE TITLE
???

### ISSUE THREAD

**Issue by EightMonth** [naver/pinpoint#3970]

**Comment by emeroad** [comment]
can you provide a reproducer ?

**Comment by EightMonth** [comment]
OK,First Thank you for your reply.
because my application have some informal dependency in long time ago, they also have log4j.xml. i think PINPOINT get log4j.xml by "classpath:log4j.xml". so problem is coming.
i should introduce my application final instruct,have two key file , bin and lib. run application by start.sh in bin. 
in lib dir is all of my jar and dependency, then my application have log4j.xml of informal dependency is startwith "B"xxx.jar, but my Application is start with "C"xxxx.jar or "D"xxxx.jar or later.
KEY TIME
because PINPOINT get log4j.xml by "classpath:log4j.xml", so PINPOINT got log4j.xml file is not my application log4j.xml and i can't control it . then my application wanna log output level is WARN or ERROR, PINPOINT got another log4j.xml, that log4j.xml file root level is DEBUG. finally my application is running after used PINPOINT,have so many DEBUG log, that's not my want.
I know that's not your question, but PINPOINT need a properties to change log output level.

**Comment by emeroad** [comment]
Is your application standalone java?
 - not WAS, Directly attatch to Botstrap classloader
generally, pinpoint uses $AGENT_DIR/lib/log4j.xml. Check this configuration file.

**Comment by EightMonth** [comment]
then, maybe I will get a result.
