### ISSUE TITLE
jar dependency in agent lib

### ISSUE THREAD

**Issue by chengbinghan** [naver/pinpoint#3994]
#### Environment
os: windows7 
jdk: jdk1.8
pinpoint version:1.7.1

Hi,

    I create my own agent plugin,and in my plugin ,I used a netty jar (version: 3.10.6 ) as a dependency jar.

   When i look the agent, I found in the directory:  ../agent/lib ,there are already a jar, the name is "netty-3.10.6.Final.jar" same with my dependency jar. so, when I package my agent plugin project to jar , I didn't package netty-3.10.6.Final.jar  into my plugin. then, the problem comes.

   when I put my plugin jar to ../agent/plugin/, And start up agent. I  got a class not define  Exception :

//Exception message........start
pinpoint start failed.
........
java.lang.NoClassDefFoundError:org.jboss.netty.XXXX.........
........
//Exception message........end

From the exception ,I realized that, we add the plugin jar to the directory: ../agent/plugin/, Class in the plugin can't access the (dependency) jar in directory:../agent/lib.

And，I did a simple test and confirmed my guess.

My confusion is that：
1、is my guess correct?

2、What should I do . then a plugin in the directory：‘ ../agent/plugin’ can access the class that in the directory:../agent/lib?

3、Add all the class in netty-3.10.6.Final.jar to my plugin jar is the only way to solve my problem?

 thanks

**Comment by koo-taejin** [comment]
hi chengbinghan 

The plugin limits external jar access as much as possible.
Therefore, jar files in agent/lib are inaccessible.

If you look at the source code of the *.Plugin.java, 
you can see that decides whether to transform it as a String.
After,check whether target class and method are included in classPath.
If it is included, the Interceptor will load it and execute it.

I wonder if you have imprted netty class in the Plugin.java section.

thanks.

**Comment by chengbinghan** [comment]
Hi,koo-taejin
Thank you for your reply.
 jar files in agent/lib are inaccessible, if i edit the MANIFEST.MF file in the XXX.jar/META-INF,or do somthing  that i can make it accessable？  otherwise , i have to add duplicate jar to  agent/plugin,Because of my needs。

thank!

**Comment by chengbinghan** [comment]
my nees is， class in agent/plugin can access class in agent/lib

**Comment by chengbinghan** [comment]
thanks
