### ISSUE TITLE
How to use https in pinpoint

### ISSUE THREAD

**Issue by cjk87927** [naver/pinpoint#3997]
I change the ws:// to wss:// but get the error 500. The server has no error print

Pinpoint Vserion : 1.6.2
nginx Vserion : 1.12.0
nginx conf :
` server {
        listen       443 ssl;
        server_name  monitor.xxxx.com;
	ssl on;
 	ssl_certificate        crt/server.crt;
 	ssl_certificate_key    crt/server.key;
	ssl_dhparam            crt/dhparam.pem; 
	ssl_client_certificate crt/ca.crt;
        ssl_verify_client on;
        ssl_prefer_server_ciphers on; 
        ssl_session_cache    shared:SSL:10m;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains;preload" always; 
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        keepalive_timeout 70;
        ssl_session_timeout 10m;

        #charset koi8-r;

        access_log  logs/pinpoint.log  main;

	
        error_page  404              /404.html;
	
	location /agent/ {
        	proxy_pass http://pinpoint_tomcat;
        	proxy_http_version 1.1;
        	proxy_set_header Upgrade $http_upgrade;
        	proxy_set_header Connection "upgrade";
    	}

        location / {
                 proxy_pass   http://pinpoint_tomcat;
        }

     }`

**Comment by emeroad** [comment]
We do not provide technical support.
