### ISSUE TITLE
[help]How to get the TraceId?

### ISSUE THREAD

**Issue by yanpeng-ali** [naver/pinpoint#4008]
I developed a SDK.jar, and in this jar how to get a Span's traceId？Cloud you tell me a better way？

**Comment by RoySRose** [comment]
If you think you need to develop a plug-in take a look at our [plug-in development guide](http://naver.github.io/pinpoint/plugindevguide.html)

**Comment by zuochangan** [comment]
@yanpeng-ali  you can add a util class which holds the  TraceContext instance in bootrap-core module. Since pinpoint append all bootstrap jar to bootstrap classloader, so you can access this util class in your SDK.  then you can the TraceContext instance
