### ISSUE TITLE
agent not support A tomcat running multiple services

### ISSUE THREAD

**Issue by tvzr** [naver/pinpoint#4009]
#### Description
There is a scenario where tomcat runs multiple services，e.g:
a tomcat  running {"service1","service2","service3"},but agent not support config multiple applicationName and agent on a tomcat.
#### Environment

* Pinpoint version: 1.7.1
* OS, WAS, affected library, etc: RHEL6.5

#### Additional Info
Agent can't running.

**Comment by emeroad** [comment]
We have no plans to support multi-applicationName.

**Comment by JackeyLee007** [comment]
@emeroad Do you mean pinpoint can not detect different services running on the same tomcat instance?
