### ISSUE TITLE
Any plan to intercept jdk ThreadPoolExecutor ?

### ISSUE THREAD

**Issue by dumbdonkey** [naver/pinpoint#4010]
Since async process always happens in another thread which mostly is provided by a thread pool.

if we interceptor threadPool, User won't need to care about Trace objects pass.

Is this idea reasonable? Or what unexpected result will we meet if we do this?

**Comment by emeroad** [comment]
Yes. this idea is very reasonable. I'm already thinking about it.
However, there is a problem that can cause too many traces.
Currently, I am thinking of ways to complement the drawbacks.

**Comment by zuochangan** [comment]
good news. I can't wait to use it.

**Comment by botaruibo** [comment]
@emeroad how about the progress

**Comment by linxiaobai** [comment]
@emeroad Are you starting to develop it? This feature is very useful to us.
I try to write a ThreadPoolExecutor plugin to enhance ThreadPoolExecutor class, but it didn't work，It seems that ThreadPoolExecutor class has been loaded into jvm before, and there is no transformation logic that triggers plugin?

**Comment by chkch** [comment]
@emeroad Is there any progress on this issue?

**Comment by Xxf9126** [comment]
> @emeroad在这个问题上有什么进展吗？
