### ISSUE TITLE
Multiple network cards

### ISSUE THREAD

**Issue by lilanlong** [naver/pinpoint#4029]
If there are multiple network cards on the server, there will be more than one ip. Is there anything to configure?

**Comment by RoySRose** [comment]
@lilanlong 
I don't think there is any. But why don't you try and share with us:)

**Comment by ing-arriola** [comment]
@lilanlong 
I share my case:
I have configured a server in a virtual machine which has an IP other than the IP of the Host computer in which it is located, in this case it is observed that I have two IPs in the same Host and could have more as more machines existed virtual Also if you have more than one network card there is nothing to configure, you only have to configure the IP address to which the Agent will refer when sending the data to the Collector. This is done in the agent's pinpoint.config file.

**Comment by RoySRose** [comment]
@ing-arriola 
Thanks for sharing:)
