### ISSUE TITLE
clear data

### ISSUE THREAD

**Issue by lilanlong** [naver/pinpoint#4043]
Can you only keep data for a period of time, such as a week?

**Comment by Xylus** [comment]
Hi @lilanlong 
You can specify TTL values for hbase, which will hold data only for the specified amount of time.
Please also take a look at https://github.com/naver/pinpoint/wiki/FAQ#hbase-is-taking-up-too-much-space-which-data-should-i-delete-first on which data are safe to delete or shorten the TTL.
