### ISSUE TITLE
 admin APIs don't work!

### ISSUE THREAD

**Issue by keets2012** [naver/pinpoint#4056]
hi,
    I use the following to delete unused agent, but it doesn't work at all.

` http://192.168.1.202:3080/admin/removeAgentId.pinpoint?applicationName=searcher&agentId=searcher-20180424174827&password=admin123`

![image](https://user-images.githubusercontent.com/13324388/39233671-a023f66a-48a3-11e8-8a0c-f3cbe6ff0f94.png)
 
![image](https://user-images.githubusercontent.com/13324388/39233688-b5d2b424-48a3-11e8-841f-8c2904d2dcbc.png)

thanks a lot.

**Comment by Xylus** [comment]
Hi @keets2012 
*searcher-20180424174827* is an application, not an agent. You're trying to delete an application using an API designed to delete an agent.

If you would like to get rid of *searcher-20180424174827*, you need to use `/removeApplicationName.pinpoint`.

**Comment by keets2012** [comment]
thx.
