### ISSUE TITLE
Adaptive sampling question

### ISSUE THREAD

**Issue by lanzuyou** [naver/pinpoint#4058]
There is a "Adaptive sampling" in the Dapper thesis. Can "Adaptive sampling" be used in "pinpoint"? If so, how to configure it? If not, do you have a plan?

**Comment by RoySRose** [comment]
@lanzuyou 
Hello, Pinpoint doesn't have "Adaptive sampling" features, yet. We've already had a review on this but yet our first priority. Maybe in the future, we will work on it.
