### ISSUE TITLE
jdk5 support

### ISSUE THREAD

**Issue by huangchen007** [naver/pinpoint#4059]
There is still a lot of jdk5 program live.
I wonder why pinpoint dont support it. Is there any technical difficulty ?
I think Jdk5 has had instrumentation Interface.

Looking forward your response. Thank you?

**Comment by emeroad** [comment]
It is too old JDK
We have no plans to support

**Comment by huangchen007** [comment]
Can you tell me why? Does it need a lot of huge work to do? 
I think it just need to involve jdk5 to compile. Maybe I'm wrong.

**Comment by emeroad** [comment]
I do not know because I was not interested in jdk 1.5.
Try it yourself to find out the problem.
