### ISSUE TITLE
No data for transactions or threads

### ISSUE THREAD

**Issue by gregpierro** [naver/pinpoint#4063]
#### Description
No data for transactions for 3 different Tomcat applications. Thread data shows zero. transaction data actually says No Data. I used the default pinpoint.config with mostly all the options set to true.
i attached logs for two of these cases. 

#### Environment
Tomcat 7 and 8 (Java 1.7 and 1.8 respectively). They are web based Java apps in Tomcat.

#### Additional Info

[log0426.zip](https://github.com/naver/pinpoint/files/1951387/log0426.zip)

**Comment by Xylus** [comment]
Hi @gregpierro 
It looks like you're using Tanuki wrapper to launch your Tomcat application, and the agent is not adding Tomcat transformers.
Try setting the following options in *pinpoint.config* and try again.
```
profiler.applicationservertype=TOMCAT
profiler.tomcat.conditional.transform=false
```

**Comment by gregpierro** [comment]
Hi Xylus, thanks for the prompt reply. i tried these settings but it did not seem to fix. One application uses Tanuki correct (appmanager), the glowroot JVM is using the tomcatW.exe startup shipped with Tomcat. but in both cases the problem persists with the settings you suggested.

**Comment by Xylus** [comment]
Hmm, could you provide agent logs with the above settings configured?
