### ISSUE TITLE
Configuring Pinpoint Agents for Redis and MySQL Server

### ISSUE THREAD

**Issue by maheswarisk** [naver/pinpoint#4071]
#### Description

Can someone help me with the steps to instrument redis and mysql server in pinpoint agent. 

#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by RoySRose** [comment]
@maheswarisk 
Well, the best place you can start with is our [installation guide](http://naver.github.io/pinpoint/installation.html)
and also you can look into our [quickstart guide](http://naver.github.io/pinpoint/quickstart.html) since it's really a small application running with pinpoint
