### ISSUE TITLE
It doesn't show all the hops it went through for each request

### ISSUE THREAD

**Issue by Ravidadi11** [naver/pinpoint#4072]
We need help to fix end - end to trail of my application. Where we are lagging on configuration for full detailed information about an application. My application visibility is like this :  
![capture](https://user-images.githubusercontent.com/38082483/39366413-7b05e9c4-4a51-11e8-93af-81b9e51b8cde.PNG)  but i am unable fetch the end - end hops data. I want my application like this picture.
![ss_server-map](https://user-images.githubusercontent.com/38082483/39366512-bb32f56e-4a51-11e8-9e37-2eb94fbce69a.png) . What configuration I need modify can you explain me in detail??? Please help me out.

#### Environment

* Pinpoint version: 1.7.1
* CentOs, Tomcat,spring boot,java.
* Additional details (e.g. how your collector/web is set up): collector and web are same server.

I want to trace my application fetching information from all the hops data.

Please help to configure my application correctly.
Thanks in advance.

**Comment by Xylus** [comment]
Hi @Ravidadi11 
What kind of RPC calls is *JournalValidator* making, and what library is it using to make those calls?
Maybe *JournalValidator* is making calls using libraries not supported by pinpoint.

**Comment by Ravidadi11** [comment]
Hi @Xylus 
We are using Rest call for data fetch and inbuilt we are using spring framework(latest version) for code.
Any solution please explain me in details.
thanks in advance

**Comment by Xylus** [comment]
"inbuilt" as in custom built http client for rest calls?
I ask because if you're using one of the http clients listed in our [supported modules](https://github.com/naver/pinpoint#supported-modules) list, then the calls should be traced.

Additionally, is there a thread switch before the rest call is made? (ie via Spring's `@Async` etc)

**Comment by Ravidadi11** [comment]
Hi @Xylus 
we are using org.springframework.http.HttpStatus & org.springframework.http.client.ClientHttpResponse for client response. 
Spring framework libraray will fetch all the hops data? or spring framework library cannot have this ability to show all the hops data?
&
one more question how to enable the Realtime active thread chart to my application?
can you tell me the configuration required to enable the realtime active thread chart.
thanks in advance.

**Comment by Ravidadi11** [comment]
Hi @Xylus 
* We are using Spring Boot but not using Embedded Tomcat. We are using our external tomcat for my application. Still it didn't show all the traced data it went through for each request. Please suggest any solution to fix my issue. its priority one.
&
* how to enable the Realtime active thread chart to my application?
can you tell me the configuration required to enable the realtime active thread chart.
thanks in advance.

**Comment by Xylus** [comment]
@Ravidadi11 
The HTTP client is where the http calls made to external services are traced. That is why I was asking which http client you were using. Please check if the http client you're using is in one of our supported modules list from above.
To enable real time active thread chart, you have to configure the `cluter.*` options (mostly the `cluster.zookeeper.address` option) in *pinpoint-web.properties* and *pinpoint-collector.properties*.

**Comment by Ravidadi11** [comment]
@Xylus 
We are using your supported modules like Spring, Spring Boot. Http calls we are using spring org.springframework.http.HttpStatus & org.springframework.http.client.ClientHttpResponse libraraies to fetch the data. Is it able to fetch all the hops data or not. But we are not using any Apache HTTP Client 3.x/4.x, JDK HttpConnector, GoogleHttpClient, OkHttpClient, NingAsyncHttpClient http libraries for http calls.
Thanks.

**Comment by Xylus** [comment]
@Ravidadi11 As far as I know, Spring internally uses a JDK's default http connector to make http requests (or was it apache's) if no other http client is set up. Would it be fair to assume this is the case?
If so, the http calls should be traced as we support both of these clients.

Could you attach a DEBUG log of your agent so that we can figure out what's going on?
Thanks.

**Comment by Ravidadi11** [comment]
@Xylus 
pinpoint-collector.properties configuration : 
cluster.enable=true
cluster.zookeeper.address=localhost
cluster.zookeeper.sessiontimeout=30000
cluster.listen.ip=
cluster.listen.port= 
which listen ip and port I should provide to the collector.(agent ip or web ip).
pinpoint-web.properties configuration : 
cluster.enable=true
cluster.web.tcp.port=9997
cluster.zookeeper.address=localhost
cluster.zookeeper.sessiontimeout=30000
cluster.zookeeper.retry.interval=60000
cluster.connect.address=
which cluster connect address should I give ???

Thanks.

**Comment by Ravidadi11** [comment]
Hi @Xylus 
I have tried with springboot without embedded tomcat.
I have tried in two ways .
1). I have written code and place two war files in tomcat container.
Using org.springframework.http.responseentity & org.springframework.web.client.resttemplate . while this time i didn't get any response from the another service which I called in one rest service. I captured an image 
![capture](https://user-images.githubusercontent.com/38082483/39775170-b2450c54-531a-11e8-8a94-e6bd430a0cce.PNG)
At this time pinpoint only tracing the one application data.
2).  I have written code and place two war files in tomcat container.
Using Apache HTTP Client libraray . while this time i get response from the another service which I called in one rest service. I captured an image 
![capturewithapache](https://user-images.githubusercontent.com/38082483/39775391-5b4704c4-531b-11e8-95be-039137ba8cc6.PNG)
At this time pinpoint is tracing each hop data.
!!!! Please can you suggest is spring framework http library have access to trace all hops data (OR) not ??? !!!!
Please help me out I want to explain to my seniors ASAP....!!!
If it is possible or not tell me and share me any documents with you to prove this.

Thank You @Xylus

**Comment by Xylus** [comment]
@Ravidadi11 
As said before, **RestTemplate** internally uses JDK's http connector by default and can be configured to use other http clients, such as Apache HTTP client.
Pinpoint supports both and the http calls should be traced properly.
To help figure out why it's not working for you, take a look at the DEBUG log of your agent, or post it here so that we can take a look at it.

**Comment by Ravidadi11** [comment]
@Xylus 
Can you please see this log file and give me some clarity about the tracing all hops data.
[750a97a2-pinpoint.log](https://github.com/naver/pinpoint/files/1987102/750a97a2-pinpoint.log)

&&&&

About real time active thread i have configured everything correctly. Still i am not getting the active thread chart in my pipoint UI . I captured an image please check once.

![real time active thread chart](https://user-images.githubusercontent.com/38082483/39806247-09a38580-5397-11e8-98bb-ba22bd8600d8.PNG)

Thanks.

**Comment by Xylus** [comment]
@Ravidadi11 
Couple things regarding the log you've posted.
1. Change the log level to DEBUG (it's currently in INFO). The agent's *log4j.xml* file is in `$PINPOINT_AGENT/lib` directory.
2. Have your collector running the whole time while generating the log. It's hard enough debugging without the connection logs polluting the log file.
3. You need to actually make the request you want to have traced so that it's logged. The current log looks like it only contains calls to index.jsp (ie `/`). You need to make the request that calls the REST service that is not showing up.

Finally, please check your log before posting and make sure it's got enough information for debugging, because otherwise, it's just wasting both our times.

**Comment by limsonmichael** [comment]
@Xylus 

We apologize for the lack of clarity in our queries. 
1) Attached are the logs for the JV service, DP service and collector with debug level enabled for the agents running on JV and DP service. The JV service is invoked first which in turn invokes the DP service.
The timestamp at which the JV service was invoked was "2018-05-09 18:28:53"
As mentioned earlier the behavior we are seeing is we only see individual calls made to each service, but not the server map or end to end trace of each call showing JV invoking the DP service.
[DP.txt](https://github.com/naver/pinpoint/files/1989191/DP.txt)
[JV.txt](https://github.com/naver/pinpoint/files/1989192/JV.txt)
[collector.txt](https://github.com/naver/pinpoint/files/1989193/collector.txt)

2) Regarding the "Active Thread Map" You mentioned enable the clutser option and specify zookeeper address. We do not have any zookeeper server in our pinpoint setup. Below is out topology for pinpoint.
Web and Collector running on same tomcat node and agents running on multiple services.
Is zookeeper required for a single node setup?

**Comment by Xylus** [comment]
Hi @limsonmichael @Ravidadi11 
No problem, thank you for the logs and clarification.
1. From the logs, it looks like JV is making https calls to DP service. Pinpoint's jdk http plugin currently transforms **HttpURLConnection** to trace (and propagate pinpoint headers) external http calls. The 3 methods it intercepts internally are `connect()`, `getInputStream()`, and `getOutputStream()`.  
When a non-https (simple http) call is made, everything is traced properly as expected. However when a https call is made, a **DelegateHttpsURLConnection** is used instead to make http calls, and while **DelegateHttpsURLConnection** is a (grand) child of **HttpURLConnection**, the `connect()` method we're intercepting in **HttpURLConnection** is overridden in the class hierarchy and so is never called.  
I'll get this issue sorted out and get it in for 1.8.0 release.  
In the mean time, you could either change the https call to http call, or configure Spring to use Apache HTTP client instead (if either of these are an option).

2. Hbase (including stand-alone) comes with zookeeper, so you could set *cluster.zookeeper.address* to wherever hbase is running and it should work.

Feel free to let me know if you have any questions.

**Comment by limsonmichael** [comment]
@Xylus 
Could you please let us know approximate time frame for 1.8.0 release?

**Comment by minwoo-jung** [comment]
Hi @limsonmichael
Sorry. We have not release plan yet.

**Comment by Xylus** [comment]
Hi @loudywen 
Please create a new issue regarding your question.
Also, posting your pinpoint version, http client version, explaining what is happening in your code, and what you're seeing/missing in pinpoint call stack would help a great deal.

**Comment by Xylus** [comment]
@limsonmichael @Ravidadi11 
Please let me know if you've tried out the fix from master and if anything does not work as expected.
Thanks.
