### ISSUE TITLE
Hi, please, Ive got this message in my logs, how do I fix it?

### ISSUE THREAD

**Issue by christianorios** [naver/pinpoint#4073]
My Pinpoint-web logs running under Tomcat:

 **__not send flink server. Because TcpDataSender is null__**

**Comment by minwoo-jung** [comment]
Hi @christianorios

There is not the possibility of print log message in pinpoint-web. Because those message exist only pinpoint collector class.
Please check your executing environment.

**Comment by RoySRose** [comment]
@christianorios 
In addition to what @minwoo-jung has written, the log you've mentioned can only be shown in pinpoint-collector's log.

If you are trying to set up the [application inspector feature](http://naver.github.io/pinpoint/applicationinspector.html) and let it running,
usually the log shows up when flink server can't be reached. So please check your flink server.

If you are not trying to use the feature, change the option in *properties* files as opposed to what the feature page is guiding.

**Comment by christianorios** [comment]
Ideed, it occurs in Tomcat's catalina.out log file.

**Comment by RoySRose** [comment]
@christianorios 
You need to upload/submit job flink/target/pinpoint-flink-job-1.7.2.jar file instead of flink/target/pinpoint-flink-1.7.2.jar.

**Comment by subusharma2001** [comment]
Hi,
Where i can get the pinpoint-flink-job-1.8.5.jar file if i'm using docker images deployment?

**Comment by emeroad** [comment]
@subusharma2001 
Opps...  :sleepy:
Unfortunately We do not deploy the pinpoint-fiink binary
If you want binary, run build

We will deploy the pinpoint-flink binary from the next version
