### ISSUE TITLE
NPE caused by dubbo plugin when dubbo consumer call exception

### ISSUE THREAD

**Issue by aiqing2171** [naver/pinpoint#4075]
Pinpoint version: master newest.

Hi @Xylus ,
I raised this issue as you mentioned in #3985.

> java.lang.NullPointerException: calleeApplicationName must not be null thrown in collector.
The second issue I think is caused by Dubbo plugin when an exception is thrown (Failed to invoke the method sendMt in the service ... in the trace log above). DubboConsumerInterceptor records destinationId only when no exception is thrown, so this will lead to NPE like above when the span event is handled by the collector. This should be fixed in a separate issue, so let's leave this out for now in this issue.

**Comment by Xylus** [comment]
@aiqing2171 Thanks for opening the issue.

**Comment by Xylus** [comment]
@aiqing2171 We've got some fixes in for Dubbo plugin which may or may not have fixed this issue. Please give it another try with 1.8.0 agent binary (should be release soon).
