### ISSUE TITLE
Login Screen

### ISSUE THREAD

**Issue by ing-arriola** [naver/pinpoint#4085]
#### Description

Hi, i'm wondering if Pinpoint has a Login Screen and ... if it does not have one, is this documentation enough to do it? 
https://naver.github.io/pinpoint/plugindevguide.html
Or do i need more documentation to implement this feature?
Any example of code or any additional documentation  it is going to help a lot.

I want to implement this because I want to restrict access to certain users, for which I suppose I also need a database ... which should be HBASE or any other such as MySQL?

Thanks in advance.
#### Environment

* Pinpoint version: 1.8.0 Snapshot
* OS, WAS, affected library, etc: Ubuntu Server 16.04, Tomcat 8, Hbase 1.2.2, Hadoop 2.7.2, Java 8
* Additional details (e.g. how your collector/web is set up): Collector/Web Deployed on Tomcat 8, Agent deployed on WebLogic 10.3.6

**Comment by minwoo-jung** [comment]
Hi @ing-arriola 
There is not guide for auth. You should see code pinpoint-web yourself. I think you should use spring security because pinpoint web is base on spring framework.

**Comment by ing-arriola** [comment]
Hi @minwoo-jung 
Spring Security.... I did not know about that ... but I find it very interesting that you have shared the information with me to start investigating the issue and implement the user validation screen.

## Thank you so much!!

**Comment by wikiios** [comment]
can pp-web 1.7.1 also implement login in the way of spring security?
THX

**Comment by minwoo-jung** [comment]
Hi @wikiios
Yes. it can implment base on 1.7.1 version.
