### ISSUE TITLE
Error while building pinpoint - maven compiler error

### ISSUE THREAD

**Issue by ChandrewR** [naver/pinpoint#4087]
I have downloaded the latest version available now. 
Getting below error while buiding:

[INFO] Building pinpoint 1.8.0-SNAPSHOT                                  [1/72]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-pinpoint-build-requirements) @ pinpoint ---
[INFO]
[INFO] --- animal-sniffer-maven-plugin:1.16:check (ensure-java-1.6-class-library) @ pinpoint ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.0
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ pinpoint ---
[INFO] Installing F:\Pinpoint\pinpoint-master\pom.xml to C:\Users\Chandrew\.m2\repository\com\navercorp\pinpoint\pinpoint\1.8.0-SNAPSHOT\pinpoint-1.8.0-SNAPSHOT.pom
[INFO]
[INFO] ------------< com.navercorp.pinpoint:pinpoint-annotations >-------------
[INFO] Building pinpoint-annotations 1.8.0-SNAPSHOT                      [2/72]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-pinpoint-build-requirements) @ pinpoint-annotations ---
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ pinpoint-annotations ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] skip non existing resourceDirectory F:\Pinpoint\pinpoint-master\annotations\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ pinpoint-annotations ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to F:\Pinpoint\pinpoint-master\annotations\target\classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] pinpoint 1.8.0-SNAPSHOT ............................ SUCCESS [  3.354 s]
[INFO] pinpoint-annotations ............................... FAILURE [  1.865 s]
[INFO] pinpoint-thrift .................................... SKIPPED
[INFO] pinpoint-commons ................................... SKIPPED
...
...
...
..
[INFO] pinpoint-hbase-distribution ........................ SKIPPED
[INFO] pinpoint-flink 1.8.0-SNAPSHOT ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.493 s
[INFO] Finished at: 2018-05-02T23:20:58+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project pinpoint-annotations: Compilation failure -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pinpoint-annotations

**Comment by Xylus** [comment]
Hi @ChandrewR 
Could you retry with the debug flag (-X) and see what it spits out?

**Comment by ChandrewR** [comment]
Thanks Xylus for your suggestion.Found the error in debug mode..It was my mistake. I didn't set the env variable for JAVA_6_HOME properly. I set that and i'm able to build successfully.

**Comment by rodrigocaballerohurtado** [comment]
Basically ensure all JAVA_X_HOME point to JDK instead of JRE and it should fix the issue
