### ISSUE TITLE
shouldn't `REGISTRY` be declared `volatile`?

### ISSUE THREAD

**Issue by D3Hunter** [naver/pinpoint#4092]
https://github.com/naver/pinpoint/blob/682a0e69f52b7eaf34dd6164f29761826e1ead21/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/registry/InterceptorRegistry.java#L31-L49

as `LOCK.lock` is not actually synchronizing `write to REGISTRY`(just `compareAndSet` another non-related variable), other thread may not see the newest update of `REGISTRY`, shouldn't it be declared `volatile`?

**Comment by emeroad** [comment]
Hi  `LOCK.lock` exists for security, not added for synchronization.

**Comment by D3Hunter** [comment]
what about the question `other thread may not see the newest update of REGISTRY, shouldn't it be declared volatile?`

**Comment by emeroad** [comment]
'bind()' does not have a race condition in multi-thread.

**Comment by D3Hunter** [comment]
oh, i'am reasoning in what i'am trying to implement, that is to add dynamic disable pinpoint support, in that case, `InterceptorRegistry.unbind`'ll an easy way to stop all interceptors and it should make sure `unbind REGISTRY` is visible to other threads.

**Comment by D3Hunter** [comment]
yes, `main` hasn't run yet at `bind` time.
thx
