### ISSUE TITLE
Pinpoint modifies the WebLogic LOG file ... can that be avoided? [Solved]

### ISSUE THREAD

**Issue by ing-arriola** [naver/pinpoint#4098]
#### Description

I have deployed the Pinpoint agent on a Server with WebLogic 10.3.6 and it has worked excellently to trace transactions which is one of my priorities but I have had the slight inconvenience with the WebLogic Log, this because the Pinpoint Agent is writing information relative to its functioning precisely in the Log of WebLogic ... that Log is used to diagnose certain problems and solutions to them and it is for that reason that it is not favorable for me that the Log of WebLogic is modified as part of the operation of Pinpoint .

My questions about the situation raised are then:

1. Is it possible for Pinpoint to write information related to its operation in another file?

2. Is it absolutely necessary for Pinpoint to write in the WebLogic Log or any other WAS that is being used ... or could I disable that writing in the Log without affecting the operation of Pinpoint?

3. The fact that Pinpoint writes in that Log is related to the Intrumentalization of code?
#### Environment

* Pinpoint version:1.8.0 SnapShot
* OS, WAS, affected library, etc:(Monitor with Collector and Web) Ubuntu 16.04, Hbase 2.22, Hadoop 2.7.2, Tomcat 8.5, Java 8
* Additional details (e.g. how your collector/web is set up): (WAS) WebLogic 10.3.6, Oracle Linux

**Comment by ing-arriola** [comment]
## I found the answer!!!

I have verified the Pinpoint code in a relatively deep detail, and I have found that it uses the Log4j framework, after that I modified the Log4j configuration file for the agent I was using, I deleted the element referring to the console writing and so on. same I have changed the level of Log from DEBUG to INFO. On the other hand I read the post of another person and I quote it here given that he refers to the performance detail when changing the level of DEBUG to INFO.

I attach my XML configuration file in case it is useful to another person.

**Comment by RoySRose** [comment]
@ing-arriola 
Good for you:)
I appreciate your sharing with us on the matter. Thank you.
