### ISSUE TITLE
It is not a big problem but it is a problem [pinpoint-web/dao/UserDao.java]

### ISSUE THREAD

**Issue by codelhf** [naver/pinpoint#4101]
package com.navercorp.pinpoint.web.dao;

import java.util.List;

import com.navercorp.pinpoint.web.vo.User;

/**
 * @author minwoo.jung
 */
public interface UserDao {

    void dropAndCreateUserTable();

    void insertUser(User user);

    void insertUserList(List<User> users);

    void deleteUser(User user);

    **List<User> selectUser();**

    List<User> selectUserByDepartment(String department);

    User selectUserByUserId(String userId);

    List<User> selectUserByUserName(String userName);

    void updateUser(User user);

}
   
    <select id="selectUserList" resultType="User">
        SELECT *
        FROM puser
    </select>

**Comment by minwoo-jung** [comment]
Hi @codelhf 
Thank you. I got it^^ I will fix it.
