### ISSUE TITLE
Monitor a JVM with more than one APM

### ISSUE THREAD

**Issue by ing-arriola** [naver/pinpoint#4107]
#### Description

I have an application that runs on a WAS Weblogic that is currently monitored with an APM called Applications Manager that I have not had the results I expected, for this reason I started to use Pinpoint but now I have the idea of comparing both APM's monitoring the same JVM, I have previously asked in this site about how to work with the Pinpoint agent in WebLogic and in the end I managed to solve it. Now the question is: It is possible to monitor a JVM with two or more APM tools, I have tried to do it but in WebLogic the ManagedServer that I am trying to monitor at the moment of starting adding the lines of the agents in the argument of the JVM, corrupts the Managed Server in such a way that the ManagedServer is unusable later.
#### Environment

* Pinpoint version:1.8.0 SnapShot
* OS, WAS, affected library, etc:(Monitor with Collector and Web) Ubuntu 16.04, Hbase 2.22, Hadoop 2.7.2, Tomcat 8.5, Java 8
* Additional details (e.g. how your collector/web is set up): (WAS) WebLogic 10.3.6, Oracle Linux

**Comment by RoySRose** [comment]
@ing-arriola 
There weren't such cases like this that I've heard of. So I'm afraid there aren't any comments that I can give you.

It'll be great to share the results with us for the strugglers who trying to set up a similar environment in the future.

**Comment by ing-arriola** [comment]
Hi @RoySRose 

Thanks for your answer, Definitely I will continue working on this topic and will share the results obtained.
