### ISSUE TITLE
collector RejectedExecutionException

### ISSUE THREAD

**Issue by yale2** [naver/pinpoint#4110]
#### Description
collector can start normal.but when i start an application with agent.it can't put anything into hbase.it gives a log like:RejectedExecutionException Casued Task com.navercorp.pinpoint.collector.monitor.MonitorExecutorService$InstrumentRunnable.........

#### Environment

* Pinpoint version: 1.6.2
* System: windows 10

**Comment by koo-taejin** [comment]
hi yale2 

please check out this issue  (#3008)

thanks.
