### ISSUE TITLE
Timeout on TcpDataSender (Openshift/Kubernetes)

### ISSUE THREAD

**Issue by LeSingeFou** [naver/pinpoint#4119]
Hi :)

#### Description
I try to pass pinpoint in Openshift. All is ok but i have timeout errors on the agent side and i don't know why. The connection between agent and collector seems like ok. Needs more specific ports?

Connection ok:

`2018-05-11 15:12:23 [DEBUG](.p.r.c.DefaultPinpointClientHandler) ping write success. channel:[id: 0x9adb8c03, /172.17.0.19:60466 => pinpoint-collector/172.30.122.105:9994]
2018-05-11 15:12:23 [DEBUG](c.n.p.r.c.PacketDecoder            ) receive pong. [id: 0x9adb8c03, /172.17.0.19:60466 => pinpoint-collector/172.30.122.105:9994]`

Error:
`2018-05-11 15:12:44 [INFO ](c.n.p.p.AgentInfoSender            ) Sending AgentInfo TAgentInfo(hostname:pinpoint-test-6-mw7tw, ip:172.17.0.19, ports:, agentId:app-in-docker, applicationName:app, serviceType:1010, pid:1, agentVersion:1.7.2, vmVersion:1.8.0_171, startTimestamp:1526051237821, serverMetaData:TServerMetaData(serverInfo:Apache Tomcat/8.5.30, vmArgs:[-Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties, -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager, -javaagent:/usr/local/pinpoint-agent/pinpoint-bootstrap-1.7.2.jar, -Dpinpoint.agentId=app-in-docker, -Dpinpoint.applicationName=app, -Djdk.tls.ephemeralDHKeySize=2048, -Djava.protocol.handler.pkgs=org.apache.catalina.webresources, -Dorg.apache.catalina.security.SecurityListener.UMASK=0027, -Dignore.endorsed.dirs=, -Dcatalina.base=/usr/local/tomcat, -Dcatalina.home=/usr/local/tomcat, -Djava.io.tmpdir=/usr/local/tomcat/temp], serviceInfos:[TServiceInfo(serviceName:Catalina/localhost/, serviceLibs:[jstl-api-1.2.jar, jackson-databind-2.4.4.jar, spring-webmvc-4.1.7.RELEASE.jar, jcl-over-slf4j-1.7.5.jar, jackson-annotations-2.4.0.jar, spring-context-4.1.7.RELEASE.jar, spring-expression-4.1.7.RELEASE.jar, httpcore-4.3.3.jar, jstl-impl-1.2.jar, spring-web-4.1.7.RELEASE.jar, jackson-core-2.4.4.jar, aopalliance-1.0.jar, spring-aop-4.1.7.RELEASE.jar, spring-core-4.1.7.RELEASE.jar, slf4j-api-1.7.5.jar, commons-io-2.4.jar, commons-codec-1.6.jar, commons-logging-1.1.3.jar, slf4j-log4j12-1.7.5.jar, log4j-1.2.17.jar, spring-beans-4.1.7.RELEASE.jar, standard-1.1.2.jar, httpclient-4.3.6.jar]), TServiceInfo(serviceName:Catalina/localhost/manager, serviceLibs:[]), TServiceInfo(serviceName:Catalina/localhost/docs, serviceLibs:[]), TServiceInfo(serviceName:Catalina/localhost/host-manager, serviceLibs:[])]), jvmInfo:TJvmInfo(version:0, vmVersion:1.8.0_171, gcType:PARALLEL))
2018-05-11 15:12:47 [WARN ](c.n.p.p.AgentInfoSender            ) request timed out while waiting for response.`

#### Environment
* Pinpoint version: 1.7.2
* Openshift 1.5.1

#### Additional Info

[Agent log](https://github.com/naver/pinpoint/files/1995880/app-in-docker-pinpoint.log)

[Agent pinpoint.config](https://github.com/naver/pinpoint/files/1995906/pinpoint.config.txt)

**Comment by koo-taejin** [comment]
hi LeSingeFou

This is not a network issue between (agent <-> collector), because it accepts pong messages.
If a timeout occurs only for a specific message. then It seems to be a problem of hbase.
Please check the hbase that is connected to the collector.

thanks.

**Comment by LeSingeFou** [comment]
Hi koo-taejin,

Thx for your response. In collector side, no error in logs. In debug mode i have that :

`2018-05-16 17:09:13 [DEBUG](o.a.h.h.i.RpcClientImpl            ) Use SIMPLE authentication for service ClientService, sasl=false
--
  | 2018-05-16 17:09:13 [DEBUG](o.a.h.h.i.RpcClientImpl            ) Not trying to connect to pinpoint-hbase/172.30.115.115:45108 this server is in the failed servers list
  | 2018-05-16 17:09:13 [DEBUG](o.a.h.h.s.o.a.z.ClientCnxn         ) Reading reply sessionid:0x16369e8bd0b0006, packet:: clientPath:null serverPath:null finished:false header:: 91,4  replyHeader:: 91,4068,0  request:: '/hbase/meta-region-server,F  response:: #ffffffff0001a726567696f6e7365727665723a3435313038ffffffd7ffffffd7ffffffa2ffffffcfffffffdd48ffffffcbffffff8350425546a1bae70696e706f696e742d686261736510ffffffb4ffffffe0218ffffffa2ffffff97ffffffa3ffffffcfffffffb62c100183,s{2134,2134,1526490261505,1526490261505,0,0,0,0,68,0,2134}
  | 2018-05-16 17:09:13 [DEBUG](o.a.h.h.s.o.a.z.ClientCnxn         ) Reading reply sessionid:0x16369e8bd0b0006, packet:: clientPath:null serverPath:null finished:false header:: 92,8  replyHeader:: 92,4068,0  request:: '/hbase,F  response:: v{'replication,'meta-region-server,'rs,'splitWAL,'backup-masters,'table-lock,'flush-table-proc,'region-in-transition,'online-snapshot,'master,'running,'recovering-regions,'draining,'namespace,'hbaseid,'table}
`

Log files :
[pinpoint-quickstart-1-nq6c0.log](https://github.com/naver/pinpoint/files/2010159/pinpoint-quickstart-1-nq6c0.log)
[pinpoint-hbase-6-wnh06.log](https://github.com/naver/pinpoint/files/2010160/pinpoint-hbase-6-wnh06.log)
[pinpoint-collector-1-zz069.log](https://github.com/naver/pinpoint/files/2010161/pinpoint-collector-1-zz069.log)

**Comment by LeSingeFou** [comment]
Hello,

I can understand that but i dont really know the pinpoint architecture ans maybe someone have a help. 
I would like share my kubernetes/Openshift pinpoint adaptation All are ready, i have just this problem.
So if you have tips to help me (like tools for debug or spécifications configuration) it's can be good.

Thanks

**Comment by simoelmou** [comment]
@LeSingeFou Hello, did you manage to make it work, please? I have the same problem.
