### ISSUE TITLE
Redis plugin pipeline generates excessive trace

### ISSUE THREAD

**Issue by mdw211126com** [naver/pinpoint#4123]
When enable the pipeline trace in Redis plugin, the plugin will generate one trace per command in the pipeline. Since the pipeline always sends the whole commands in one network call, trace the commands which in pipeline seems be meaningless.  Almost all traces display 'write 0ms read 0ms', which are very verbose when many commands are included in the pipeline.  So is it reasonable to remove the interception of the methods in pipeline and only intercept the methods which trigger a network call?

**Comment by RoySRose** [comment]
Hello, @mdw211126com 
I not really used to Redis. So I can't be the one who make the calls. But, If you think *removing the interception of the methods in the pipeline and ONLY intercept the methods which trigger a network call* is a better way for the Redis plugin. You can develop/upgrade the Redis plugin by seperating intercept method with configuration in `Pinpoint.config`. The community always welcome your contribution:)
