### ISSUE TITLE
Disabled Agent Log

### ISSUE THREAD

**Issue by cuixilong** [naver/pinpoint#4132]
In my Agent log，there is too many log like：
[WARN ](c.n.p.p.s.RetryQueue :55 ) discard retry message(RetryMessage{retryCount=3, maxRetryCount=3, bytes=62, messageDescription='TApiMetaData'})

I don't want this logs output，can I disabled the logs output? 
Thank you！

**Comment by RoySRose** [comment]
Hello, @cuixilong 
Why don't you try to change the log level to OFF or anything lower level.

**Comment by ing-arriola** [comment]
Hi @RoySRose and @cuixilong 

I think I've had an experience similar to the one discussed here; in my case, make a change to the log4j file that is located in the route:
AgentDirectory / lib / log4j.xml

You can review the  https://github.com/naver/pinpoint/issues/4098 theme where I have included the file to which I made the modification

Additionally I add some links in case you are not related to Log4J as in my case when I had the problem I mentioned before.

https://javapapers.com/log4j/log4j-levels/

https://javapapers.com/log4j/log4j-levels/

**Comment by cuixilong** [comment]
@RoySRose @ing-arriola 谢谢（Thank you）
