### ISSUE TITLE
Linux Pinpoint collector  BUILD FAILURE

### ISSUE THREAD

**Issue by pega10000** [naver/pinpoint#4143]
Linux Pinpoint collector  Build Failure !
How should I solve it?

[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.navercorp.pinpoint:pinpoint-quickstart-collector:war:1.8.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-war-plugin is missing. @ line 41, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] --------< com.navercorp.pinpoint:pinpoint-quickstart-collector >--------
[INFO] Building Pinpoint Collector QuickStart 1.8.0
[INFO] --------------------------------[ war ]---------------------------------
[WARNING] The POM for com.navercorp.pinpoint:pinpoint-collector:war:1.8.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.657 s
[INFO] Finished at: 2018-05-20T04:17:48+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project pinpoint-quickstart-collector: Could not resolve dependencies for project com.navercorp.pinpoint:pinpoint-quickstart-collector:war:1.8.0: Failure to find com.navercorp.pinpoint:pinpoint-collector:war:1.8.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

Pinpoint : 1.8.0
OS : CentOS 6.5

**Comment by RoySRose** [comment]
Hello, @pega10000 

I'm wondering how you approached to building the source, because from the pom.xml provided, doesn't build `com.navercorp.pinpoint:pinpoint-quickstart-collector`.
quickstart is not a part of Pinpoint. To get to know about [QuickStart](https://naver.github.io/pinpoint/quickstart.html)

So, try to build from the pom.xml provided. I bet it works:)
