### ISSUE TITLE
tomcat plugin confusion.

### ISSUE THREAD

**Issue by chengbinghan** [naver/pinpoint#4145]
os:win7
jdk1.8
pinpoint-version:1.7.1

Hi,
   thanks for open source project pinpoint, and your team. 
   I am using pinpoint in our company web container  Apusic. so my first job is to develop a new web plugin,  also  the new web plugin  is  very similar to tomcat plugin.
    
when i see the tomcat plugin,  I feel confusion about:  com.navercorp.pinpoint.plugin.tomcat.aspect.RequestFacadeAspect.java
And in tomcat plugin
//==============code start in tomcat plugin===============
//com.navercorp.pinpoint.plugin.tomcat.TomcatPlugin
          target.weave("com.navercorp.pinpoint.plugin.tomcat.aspect.RequestFacadeAspect");
          return target.toBytecode();
  //=============code end in tomcat plugin==============

what't the use of RequestFacadeAspect.java？
what is  the  mean of : target.weave("........RequestFacadeAspect")?

as we can see ，In addition to the tomcat plugin, other web container plugin also has similar code in each plugin.

thank very very very much.

**Comment by koo-taejin** [comment]
hi chengbinghan

Please refer to the following link to develop.
https://github.com/koo-taejin/pinpoint-plugin-sample

thanks.

**Comment by maojunling** [comment]
hi chengbinghan

Can you share the Apusic plug-in？
