### ISSUE TITLE
HELP wanted: how to transfer TraceId & SpanId when developing plugin for MyCat?

### ISSUE THREAD

**Issue by fengnex** [naver/pinpoint#4153]
https://github.com/MyCATApache/Mycat-Server

MyCat is an open source project, it's a database middle. Java applications use JDBC to access MyCat and look it as a database server, typically a MySQL server. MyCat then uses java client of MySQL to operate real background MySQL database.

Now the question is on how to transfer trace metadata, for example TraceId & SpanId, from JDBC plugin to MyCat plugin?

We need to modify JDBC plugin and let it not the TERMINAL and make MyCat's plugin as the TERMINAL, let JDBC plugin transfer trace metadata to MyCat's pinpoint plugin.

And how and where to transfer  trace metadata in JDBC's plugin?

**Comment by fengnex** [comment]
**MyCat's introductions:**
MyCAT is an Open-Source software, “a large database cluster” oriented to enterprises. MyCAT is an enforced database which is a replacement for MySQL and supports transaction and ACID. Regarded as MySQL cluster of enterprise database, MyCAT can take the place of expensive Oracle cluster. MyCAT is also a new type of database, which seems like a SQL Server integrated with the memory cache technology, NoSQL technology and HDFS big data. And as a new modern enterprise database product, MyCAT is combined with the traditional database and new distributed data warehouse. In a word, MyCAT is a fresh new middleware of database.

Mycat’s target is to smoothly migrate the current stand-alone database and applications to cloud side with low cost and to solve the bottleneck problem caused by the rapid growth of data storage and business scale.

**MyCat's main features:**
1. Supports SQL 92 standard
2. Supports MySQL cluster, used as a Proxy
3. Supports JDBC connection with ORACLE, DB2, SQL Server, simulated as normal MySQL Server connection
4. Supports MySQL cluster, percona cluster or mariadb cluster, providing high availability of data fragmentation clusters
5. Supports automatic failover and high availability
6. Supports separation of read and write, dual-master with multi-slave, single-master with multi-master of MySQL model
7. Supports global table, automatically fragment data into multiple nodes for efficient relational query
8. Supports the unique fragmentation strategy based on ER-relation for efficient relational query
9. Supports multiple platforms, easy deployment and implementation

**Comment by RoySRose** [comment]
Hello, @fengnex. I'm also trying to develop a plug-in myself.
Why don't you check out the [plugin development guide](http://naver.github.io/pinpoint/plugindevguide.html) and see if it helps you to answer your questions?

**Comment by fengnex** [comment]
@RoySRose I have checked it many times but still have the problem ...

**Comment by RoySRose** [comment]
@fengnex What could be the problem?

**Comment by fengnex** [comment]
@RoySRose How and where to transfer trace metadata, you know those TraceId, SpanId, etc, when develop plugins fro MyCat?
Thanks!

**Comment by RoySRose** [comment]
@fengnex 
**Where(Which Classes and Methods)** to transfer the metadata for MyCat is for the developer to find.
Why don't you take a look at CassandraPlugin.java file? The source code isn't too long and is easy to understand if have little knowledge of the Database.

**Comment by fengnex** [comment]
@RoySRose Thanks, Roy
I have read Cassandra's plugin code and it's a good example.

But I have still some questions if developing plugin for MyCat:
1. Modify MySQL's JDBC plugin to let it transfer TraceId, SpanId, etc, because applications use MySQL's jdbc to access MyCat.
Is it possible, how & where? Is it relevant with JDBC specification?
2. Intercept MyCat's codes using operating its background MySQL.

**Comment by RoySRose** [comment]
@fengnex 
As I've said earlier, I don't know about MyCat. So, maybe I'm not the one that should tell you if it's possible or not. But so far I know, MyCat is also written in Java, so I believe it will be possible.

I'm not sure this will help but I'll tell you anyway. I'm currently working on MongDB plugin. There is [MongoDB Java Driver](https://mongodb.github.io/mongo-java-driver/) for java users. I'm looking into this driver and try to find the Class/Methode to intercept.

Also for MyCat. I can't tell you where to intercept since I don't know about the system. You, have to FIND which Class/Method is fit for the interception. If it should be taken care of from JDBC, it is still possible, so try to find WHERE to intercepting. HOW to intercept it, is explained in the [plugin development guide](http://naver.github.io/pinpoint/plugindevguide.html), [examples are here](https://github.com/naver/pinpoint-plugin-sample), and try to look at other plugins for any active example.

**Comment by fengnex** [comment]
@RoySRose 
Thanks, Roy, you are actually welcomed very much.

I think I need to modify MySQL's JDBC plugin to let it transfer TraceId&SpanId to our new MyCat plugin because Java applications use the JDBC driver to access MyCat, but until now I still have no idea on how to modify the JDBC plugin to achieve it.
