### ISSUE TITLE
Pinpoint-web - To use PinPoint, enable cookies and JavaScript

### ISSUE THREAD

**Issue by jacobsy** [naver/pinpoint#4154]
#### Environment

* Pinpoint version: 1.6.x ,1.8.0-SNAPSHOT
* OS, WAS, affected library, etc: Win10
* Additional details (e.g. how your collector/web is set up):
Browsers: Google Chrome、IE
#### Additional Info

![image](https://user-images.githubusercontent.com/2225457/40462707-bd756ad0-5f43-11e8-9bde-499eb2ccc0b6.png)

**Comment by koo-taejin** [comment]
hi jacobsy

You could get such an error message by setting the was.
I recommend you to check was message and was configuration.

thanks.

**Comment by jacobsy** [comment]
hi koo-taejin
I encountered such an error when running the source code in the eclipse tomcat server. When the package was deployed to the tomcat run, there was no problem.
I found that the generated js file is empty in the eclipse deployment path, See the picture below,so I close this question first, I will check the ide setting!
thanks for your reminder.

![tim 20180525144459](https://user-images.githubusercontent.com/2225457/40530168-46f7ad0e-602a-11e8-8790-0288ec0f3e61.png)

**Comment by shenhongwei33** [comment]
> hi koo-taejin
> I encountered such an error when running the source code in the eclipse tomcat server. When the package was deployed to the tomcat run, there was no problem.
> I found that the generated js file is empty in the eclipse deployment path, See the picture below,so I close this question first, I will check the ide setting!
> thanks for your reminder.
> 
> ![tim 20180525144459](https://user-images.githubusercontent.com/2225457/40530168-46f7ad0e-602a-11e8-8790-0288ec0f3e61.png)

Hello! I also encountered the same problem after packaging in version 1.8.0. Have you solved it? Can you ask me how to solve it?

**Comment by shenhongwei33** [comment]
![image](https://user-images.githubusercontent.com/26289219/50063488-801d7c80-01e7-11e9-9307-539fe9a56054.png)

**Comment by zhongyong** [comment]
解决了吗？

**Comment by VIPJoey** [comment]
Hello! I also encountered the same problem after packaging in version 1.7.3. Have you solved it? Can you ask me how to solve it? @jacobsy
