### ISSUE TITLE
Q: can pinpoint agent still work after jboss hot deploy? 

### ISSUE THREAD

**Issue by aiqing2171** [naver/pinpoint#4155]
Sometimes we use jboss hot deploy, but pinpoint use javaagent do class transform, do we need to restart jboss?

**Comment by RoySRose** [comment]
Hello, @aiqing2171 
we didn't have any chance to run pinpoint on jboss hot deploy. I believe no one on the team has the perfect answer to your question. I'll appreciate if you'd try and share with the community:)
