### ISSUE TITLE
pinpoint web ui  has no login interfaces and has no permissions of the application

### ISSUE THREAD

**Issue by lmwanga** [naver/pinpoint#4156]
hello,koo-taejin
      Pinpoint is a good tool .It helps us to solve many problems. At present, our company prepares  to use pinpoint  for all projects. However, pinpoint cannot  configure the permissions of the application. For example,web ui has no login interface, if  we open the ui address ,we can see  all applications. But, we want to display the application by diffrent user. How can I  solution this problem?

**Comment by minwoo-jung** [comment]
Hi @lmwanga 

Unfortunately pinpoint doesn't provide authentication/authorization. You should implement function ourself. Please ref this [issue.](url)
