### ISSUE TITLE
pinpoint-docker running issue

### ISSUE THREAD

**Issue by torreso** [naver/pinpoint#4157]
I installed the pinpoint-docker
**The connection was successful using the docker-compose up -d command.**
However, if you use **docker-compose up -d** command after **docker-compose stop**, i can't connect to pinpoint-web.

How should we solve it?

[Error displayed]
HTTP Status 404 – Not Found
Type Status Report

Message /

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

Apache Tomcat/8.5.31

**Comment by RoySRose** [comment]
Hello, @torreso
If you haven't changed any configuration or changed it correctly in `.env` file.
Then it should work. Because since
*docker-compose stop* just stops all the containers and
*docker-compose up -d* starts all the containers, there isn't any place that can go wrong.
I've also tried what you have done **by using *docker-compose up -d* command after *docker-compose stop***. I can successfully access Pinpoint-Web. 
I recommend you to check the configuration if you had changed them.

**Comment by torreso** [comment]
@RoySRose  After running docker-compose stop, after running docker-compose up -d and checking the file in /usr/local/tomcat/webapps/ROOT/, only WEB-INF directory is left.

The pinpoint collector as well as the pinpoint collector are the same.

First, docker-compose up -d run..
root@02afef972d9f:/usr/local/tomcat/webapps/ROOT# ls
META-INF      common       favicon.png  images      pages      styles
WEB-INF       components   features     index.html  scripts
_danger.html  favicon.ico  fonts        lib         stat.html

docker stop and docker-compose up -d,
root@02afef972d9f:/usr/local/tomcat/webapps/ROOT# ls
WEB-INF

**Comment by RoySRose** [comment]
@torreso 
I think you should check what you have altered if there is any.
I've retested what you have listed.

First, `docker-compose pull && docker-compose up -d`
````
root@4cedfcdba0fa:/usr/local/tomcat# cd webapps/ROOT/
root@4cedfcdba0fa:/usr/local/tomcat/webapps/ROOT# ls
META-INF  WEB-INF  monitor
````

And then, `docker-compose stop` followed by `docker-compose up -d`
````
root@4cedfcdba0fa:/usr/local/tomcat/webapps# cd ROOT/
root@4cedfcdba0fa:/usr/local/tomcat/webapps/ROOT# ls
META-INF  WEB-INF  monitor
````
I get the same results.

Furthermore, shell scripts that are executed at runtime mostly only contains environment values.
nothing on the image itself is changed.

**Comment by reymont** [comment]
Maybe, this way can bring it up.
```sh
docker rm -f pinpoint-web
docker-compose up -d
```
