### ISSUE TITLE
Collector and webapp hbase configuration

### ISSUE THREAD

**Issue by cerealk** [naver/pinpoint#4166]
Hi everyone,
I'm trying to switch from hbase to google big table leveraging [hbase-bigtable drivers](https://cloud.google.com/bigtable/docs/bigtable-and-hbase).

I was wondering if it's possible to configure hbase connection on collector and webapp to hbase directly via hbase-site.xml: in this way no modification on code would be needed.

Thank you

**Comment by minwoo-jung** [comment]
Hi @cerealk

Unfortunately, we've never test it. And then we could not tell you that will work.
You should test in your enviroment. And If you could do that and share us,  I’d appreciate it.
