### ISSUE TITLE
Pinpoint lowers cpu usagent 

### ISSUE THREAD

**Issue by ruizlake** [naver/pinpoint#4167]
in my netty server not add pinpoint this picture show cpu used
![image](https://user-images.githubusercontent.com/10740595/40699735-b111279c-6408-11e8-9619-469a2dfc6faa.png)

and that is add pinpoint cpu use very low 
![image](https://user-images.githubusercontent.com/10740595/40699720-9a8cc36e-6408-11e8-8723-d7568c3d171b.png)

**Comment by RoySRose** [comment]
#3343 
I believe that isn't the case. check referred issue
