### ISSUE TITLE
Each click on the same URL can sometimes be displayed in real time

### ISSUE THREAD

**Issue by shmilyah** [naver/pinpoint#4176]
Each click on the same URL can sometimes be displayed in real time, and sometimes it can not display the current click record in real time. What parameters can be set to adjust?

**Comment by RoySRose** [comment]
Hello, @shmilyah.
I think you should take a look at the sampling rate in pinpoint.config file.

**Comment by ing-arriola** [comment]
Hell @RoySRose 

What is the recommended sampling rate to achieve the objective mentioned by @shmilyah  in his comment?

**Comment by RoySRose** [comment]
@ing-arriola 
Well... since @shmilyah's issue looks like(or so far I've understood) @shmilyah is trying to display all the events created. The sampling rate should be 1 (which stands for 100% of all transactions).
