### ISSUE TITLE
agent list를 얻어올 수는 없나요? 

### ISSUE THREAD

**Issue by mayjungheelee** [naver/pinpoint#4181]
`scatterFullScreenMode`를 주기적으로 긁어와 서비스 이상 징후를 빠르게 판단할 수 있는 지표를 자동화 하는 중에 있습니다.  
http://host/#/scatterFullScreenMode/application-name@service-type-name/realtime/date/agent-list1, agent-list2, agent-list3,...

url의 구성이 위와 같은 구조인데 application에 물려있는 에이전트 리스트를 읽어올 수 있는 API를 못찾고있습니다. 혹시 해당 기능을 제공 하지 않나요?

**Comment by mayjungheelee** [comment]
퀘스천 레이블 좀 달아주세요. 감사합니다 (__)

**Comment by benelog** [comment]
`http://{host}/getAgentList.pinpoint?application={appName}` 의 형식으로 호출가능합니다.

다른 Agent정보 관련 API의 명세는 [AgentInfoController](https://github.com/naver/pinpoint/blob/master/web/src/main/java/com/navercorp/pinpoint/web/controller/AgentInfoController.java)를 참조하실수 있습니다.
