### ISSUE TITLE
pinpont-collector config : cluster.listen.ip and port

### ISSUE THREAD

**Issue by zzfox** [naver/pinpoint#4197]
cluster.enable=true
cluster.zookeeper.address=localhost
cluster.zookeeper.sessiontimeout=30000
**cluster.listen.ip=
cluster.listen.port=**

How can I config the ip and port ?

**Comment by RoySRose** [comment]
@zzfox Please check the descriptions commented right above the values.
`cluster.listen.ip`, `cluster.listen.port` values are needed to be set for certain cases only.

**Comment by zzfox** [comment]
Thank you for reply.  The comments say that I need config like this? 
collector: 
cluster.listen.ip= 172.16.16.188
cluster.listen.port= 9997

web:
cluster.web.tcp.port= 9997
cluster.connect.address=172.16.16.188

**Comment by RoySRose** [comment]
Below was the description.
does your collector have problem establishing connection to the web? If not, Those value are not needed to be set. If they are, I think you are on the right track:)

```
#2. We recommend using the cluster.web.tcp.port option. However, in cases where the collector is unable to establish connection to the web, you may reverse this and make the web establish connection to the collector.
#   In this case, you must set cluster.connect.address (pinpoint-web.properties); and cluster.listen.ip, cluster.listen.port (pinpoint-collector.properties) accordingly.
```

**Comment by zzfox** [comment]
I got it , Thank you.
