### ISSUE TITLE
Pinpoint and applications in Docker

### ISSUE THREAD

**Issue by dwamara** [naver/pinpoint#4198]
#### Description
I have just installed Pinpoint via the Docker image and everything is working fine. I have several microservices that are each running inside docker containers, speaking to one another and I wanted to configure them be use Pinpoint and here are sample of my Docker file (I am using Payara Micro)

The parent image

> FROM airhacks/java
> MAINTAINER Daniel Wamara, dwitech.com
> 
> ENV PAYARA_VERSION 5.181
> ENV PAYARA_ARCHIVE payara-micro-${PAYARA_VERSION}
> 
> ENV INSTALL_DIR /opt
> COPY ${PAYARA_ARCHIVE}.jar ${INSTALL_DIR}
> COPY enable_pinpoint.txt ${INSTALL_DIR}
> 
> ENV PINPOINT_DIR /opt
> ENV PINPOINT_VERSION 1.7.3
> RUN mkdir ${INSTALL_DIR}/pinpoint-agent
> ADD pinpoint-agent-${PINPOINT_VERSION} ${INSTALL_DIR}/pinpoint-agent
> 
> ENV PAYARA_HOME ${INSTALL_DIR}
> ENV DEPLOYMENT_DIR ${PAYARA_HOME}
> 
> ENTRYPOINT java -jar ${PAYARA_ARCHIVE}.jar --logToFile ${INSTALL_DIR}/payara-server.log --postbootcommandfile ${INSTALL_DIR}/enable_pinpoint.txt --enableRequestTracing 5ms -javaagent:${INSTALL_DIR}/pinpoint-agent/pinpoint-bootstrap-${PINPOINT_VERSION}.jar -Dpinpoint.agentId=${PINPOINT_AGENT_ID} -Dpinpoint.applicationName=${PINPOINT_APPLICATION_NAME} --deploy ${ARCHIVE_NAME}
WORKDIR ${INSTALL_DIR}
> EXPOSE 8080 5900

The enable_pinpoint.txt contains one line
> create-jvm-options -javaagent:/opt/pinpoint-agent/pinpoint-bootstrap-1.7.3.jar

One of the microservices Dockerfile
> FROM dwitech-repo:5000/dwitech-payaramicro
> MAINTAINER Daniel Wamara, dwitech.com
> 
> ENV MODULE_NAME housing.homesharing
> 
> COPY ./target/${MODULE_NAME}.war ${DEPLOYMENT_DIR}
> ENV ARCHIVE_NAME ${MODULE_NAME}.war
> 
> ENV PINPOINT_AGENT_ID macosx-agent
> ENV PINPOINT_APPLICATION_NAME tf24-${MODULE_NAME}

Unfortunately Pinpoint doesn't seem to see the applications that are running. Is there anything that has to be configured in Pinpoint for that?

#### Environment
* Pinpoint version:1.7.3
* OS: Mac OSX 10.13.4 (17E202)
* WAS: Payara Micro 5.181
* Docker: Docker for Mac Version 18.05.0-ce-mac67 (25042) Edge channel

#### Additional Info
I don't even see any reference to pinpoint in the microservice startup log.

**Comment by RoySRose** [comment]
Hello, @dwamara.
As you can see in our [installation guide](https://naver.github.io/pinpoint/installation.html#installation-2), **only things that need to be set to attach `Pinpoint-Agent` to your application are**
 - javaagent 
 - Dpinpoint.agentId 
 - Dpinpoint.applicationName

I don't see anything critically suspicious with your dockerfile. I think the first thing you should check is whether `Pinpoint-Agent` successfully copied to the correct path in the container.

Also, If ENV variable from parent image can be used from the child image. Is Reverse direction also possible? (${DEPLOYMENT_DIR} is defined from parent and used at child, ${PINPOINT_AGENT_ID} is defined from child and used from parent. is this okay? I'm not sure...)

**Comment by dwamara** [comment]
Hi @RoySRose , 

The first thing I did when seeing it wasn't working was to check the running container to see if the agent was correctly copied and that was the case.

You can use a ENV variable from the child image in the parent. As you can see "ARCHIVE_NAME" is defined in the child image but used to deploy the archive in the parent. If it wasn't the case, I wouldn't have been able to deploy my services.

**Comment by RoySRose** [comment]
@dwamara 

Well, if ENV variable isn't the case and there is no problem with copied file of  `Pinpoint-Agent`.

**Comment by dwamara** [comment]
Checking the agent's config file, I realise that it specifies
> profiler.collector.ip=127.0.0.1
which copied in the container, will try to connect with the profiler inside the container as it is the "127.0.0.1", that should be the problem.

**Comment by RoySRose** [comment]
@dwamara, has the issue been settled?

I didn't think it was a configuration problem since you've mentioned there wasn't any reference on Pinpoint in the microservice startup log. 

But if it was the configuration issue, there are other several settings that you need to configure for the Pinpoint to get running.
One is what you've mentioned. Other's if you'd like to know Please check our [Installation guide](https://naver.github.io/pinpoint/installation.html#configuration). I've linked to one of them besides the one you've mentioned.

**Comment by dwamara** [comment]
I got it working, I had to change the order of the parameters of the ENTRYPOINT, it now looks like this
> ENTRYPOINT java -javaagent:${PINPOINT_DIR}/${PINPOINT_BOOTSTRAP} -Dpinpoint.agentId=${PINPOINT_AGENT_ID} -Dpinpoint.applicationName=${PINPOINT_APPLICATION_NAME}  -jar ${PAYARA_ARCHIVE} --logToFile ${INSTALL_DIR}/payara-server.log --postbootcommandfile ${INSTALL_DIR}/enable_pinpoint.txt --enableRequestTracing 5ms --deploy ${ARCHIVE_NAME}

The javaagent had to come just after the java command and not somewhere in the middle.

**Comment by RoySRose** [comment]
@dwamara 
Good for you. And thx for sharing the solution. I would never have guessed that would be the problem:)
