### ISSUE TITLE
mysql can not be found

### ISSUE THREAD

**Issue by xttyawei** [naver/pinpoint#4204]
in our application we use ibatis to connect mysql, but in the web page we can not find the connection to mysql, in another application the same mysql is found, while using jdbc to connect it.

ibatis

**Comment by RoySRose** [comment]
Hello, @xttyawei 
Actually, We do have Ibatis plug-in as you can see in the source code 
I think the first thing that you should check is `profiler.orm.ibatis` configuration under `Pinpoint.config`. It should be set to `true`.
As you can see [our supported modules](https://naver.github.io/pinpoint/index.html#supported-modules-last-updated-20180401) Ibatis is one of them.
