### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by loydjayme25** [naver/pinpoint#4210]
Good day, about the enhancement of the project. I am willing to submit my design for logo and icon.

**Comment by RoySRose** [comment]
Hello, @loydjayme25.

**Comment by loydjayme25** [comment]
@RoySRose  hello, how about this ?

**Comment by loydjayme25** [comment]
if you have any suggestions , pls do comment. Thanks !

![proposals](https://user-images.githubusercontent.com/37318022/41327708-068da1d4-6ef7-11e8-9cee-a0adf429797a.png)

**Comment by loydjayme25** [comment]
![1](https://user-images.githubusercontent.com/37318022/41327782-5630338c-6ef7-11e8-99a8-df6350d28153.png)

**Comment by loydjayme25** [comment]
![2](https://user-images.githubusercontent.com/37318022/41328598-6f17be3e-6efb-11e8-952a-90bf576ea536.png)

**Comment by RoySRose** [comment]
Hello, @loydjayme25 
First of all, Thank you for your interest and the contribution to the Pinpoint Community.
Our team has gone through the suggested designs and voted for it. 
I'm afraid I have to tell you that it was not chosen by a slight difference. We greatly appreciate the time you invested. When it comes the time that the logo has to be upgraded, We will remember your effort and try to contact you if it's okay for you.

**Comment by loydjayme25** [comment]
@RoySRose ill create another design and post it here soon, thank you for the response , well appreciated 👍
