### ISSUE TITLE
PHP Agent

### ISSUE THREAD

**Issue by ofauchon** [naver/pinpoint#4225]
Hi. 
I can see commits about a future PHP Agent ... 
Is there some work in progress for this agent (specifications, experimental code) ? 

I realy need this agnet and I'd like to contribute ..

What about writing a thrift driver for this Php Agent https://github.com/patrickallaert/php-apm ?

Thanks. 

Oliver

**Comment by emeroad** [comment]
Hi.
The PHP agent is being prepared. Please wait.

**Comment by ofauchon** [comment]
Glad to hear Php Agent is on the way. 
Could you tell us more about the roadmap ? 

Do you need testers ? 

Thanks

Olivier

**Comment by ofauchon** [comment]
Hi, 

Could you please tell us more about php agent (status / roadmap) 

Thanks

Olivier

**Comment by RoySRose** [comment]
Hello, @ofauchon 

Actually, pinpoint php agent is going to be released in anytime soon.
We are in the discussion on where to release the project.

By the way, I think agent tests will be needed for the team that is leading the project.
Hope that you can help them with it in the future.

I'll make sure you get the notice when the agent is open.

**Comment by xujunhai** [comment]
hi~ 

Could you tell me how it is going~

Thanks

**Comment by RoySRose** [comment]
@xujunhai 
It's getting ready to be open-sourced right now.
The exact date didn't come out yet. But I think it will be open in 1,2 weeks or so.
Currently, besides the opening schedule, Pinpoint PHP-Agent team and @ofauchon is contacting each other for the testing of the agent.

**Comment by xujunhai** [comment]
@RoySRose 
Thank you , i'm looking forward to it.

**Comment by ofauchon** [comment]
Hi

Do you have news for the release, please ? 

Olivier

**Comment by chenguoxi1985** [comment]
Hi RoySRose,

We are trying to the last step which make users compile our agent easily.

If anybody is interest of our agent, please leave message here. We'll send him a pre-release agent.

**Comment by xujunhai** [comment]
@chenguoxi1985 
i'm interest in it, can you send me a copy of the agent.

Thanks

**Comment by yhy-git** [comment]
@ChenGXQQ 
I'm also interested in the agent. Can you send me a copy of the agent?Thank you very much!

**Comment by ChenGXQQ** [comment]
@yhy-git Hi, the agent is public now. Please see here: https://github.com/naver/pinpoint-c-agent

**Comment by andforero** [comment]
Has someone managed to make php monitoring work? has performed the procedure
