### ISSUE TITLE
log4j 1.2.16 performance test issue

### ISSUE THREAD

**Issue by lawrencewu** [naver/pinpoint#4270]
#### Description
When doing the performance test, we find that the performance reduce lots of when adding the log4j 1.2.16, many threads are blocking, as below image shows.
![1](https://user-images.githubusercontent.com/6634942/41466866-aaa55d1c-70d6-11e8-8288-565b2717270a.jpg)

so.. upgrade this log4j to log4j2 ?

#### Environment

* Pinpoint version: 1.7.2

**Comment by geekMessi** [comment]
Log4j is the bottleneck in a pressure situation for it's sync lock appender.
The following example is particularly obvious and deteriorated.
```java
      //com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor#execute
        if (!offer) {
            if (isWarn) {
                logger.warn("{} Drop data. queue is full. size:{}", executorName, queue.size());
            }
        }
```
Just upgrades to log4j2.

**Comment by emeroad** [comment]
@lawrencewu 
Hi~
You are using the debug log level.
It is recommended to use debug level.

**Comment by lawrencewu** [comment]
@emeroad  seen from the picture, i guess this issue is something to do with class 'Slf4jPLoggerAdapter' which is under the profiler module.

**Comment by lawrencewu** [comment]
@emeroad  I'm having a try.
