### ISSUE TITLE
Add startup flag for agents running in containers to group them separately in Web UI

### ISSUE THREAD

**Issue by Xylus** [naver/pinpoint#4274]
#### Description
Agents are grouped by hostnames currently in Web UI (Server List and Inspector View). For agents running in containers, where containers may come and go and be scaled dynamically, this could generate an ever-growing number of groups, cluttering up the server list.
As a first attempt to fix this, we could add an optional agent option (eg *-Dpinpoint.container*) to tell the Web UI to drop hostname grouping for agents with this flag.
We could then see how this works out and maybe have values assigned to it in the future to build on it further.

**Comment by dawidmalina** [comment]
If we are talking about containers maybe we could move back to this topic: https://github.com/naver/pinpoint/issues/3504

What i was trying to do is use below setup in kubernetes:
`-Dpinpoint.agentId` as uniq pod id, ex `rancher-server-1784921979-qw1g1`
`-Dpinpoint.applicationName` as deployment name which can be used as gruping for one replicas (unique pods), ex `rancher-server`

**Comment by Xylus** [comment]
Hi @dawidmalina 
I'm not sure how I feel about mixing application name and agent id with values supplied by containers.
We could definitely add more container related options (such as pod id and deployment name you mentioned), but we're still figuring out what and how to best represent containers.
So I was looking to start off by adding a flag so we can at least tell if an agent is running in a container or not.

Please feel free to share your thoughts.
Thanks

**Comment by dawidmalina** [comment]
What I would like to achieve is to deploy pinpoint agent attached to applications deployed in kubernetes cluster.

Within cluster you have:
- `namespace` - this is kind of project (with multiple microservices)
- `deployment` - this is kind of application manifest (definition)
- `pod` - this is unique application instance deployed based on deployment manifest (definition)

So what I was trying to configure is:
- `-Dpinpoint.applicationName` to filled as deployment name, for example `myapp-server`
- `-Dpinpoint.agentId` to filled with value from pod name (same as hostname inside), for example `myapp-server-1784921979-qw1g1`

As we can have similar deployments withing different namespaces kubernetes adds extra random number (in this case `-1784921979-`) then you can have multiple replicas so kubernetes add also extra suffix (in this case `qw1g1`).

There is one more unique value that we could use as agentId called `uid` but it is still too long, for example `c3f6136-1ae7-11e8-a4d7-fedca556a4f9`.

What we could do is to have ability to force pinpoint to autogenerate agentId (to not change id lenght restrictions) and use only applicationName and maybe add new property like hostname or agentName which then can be used in UI.

What do you think?

**Comment by Xylus** [comment]
I think your configuration for *applicationName* and *agentId* make perfect sense, but like you mentioned in #3504, I can definitely see it going over 24 characters limit.
Instead of having pinpoint agent generate a random agent id, would it make sense to strip the deployment name part from the agent id? for example `myapp-server-1784921979-qw1g1` -> `1784921979-qw1g1`, since deployment name is used as the application name and is redundant.

**Comment by dawidmalina** [comment]
Good proposition 👍 I need to figure out how do this transformation within manifest as i would like to avoid extra script to start application (not modify existing manifests) and have loosely coupled manifests and pinpoint.

**Comment by dawidmalina** [comment]
BTW do you think we could extend agentId to 36 chars to comply with UUID string representations. It's 36 characters - 32 hex digits + 4 dashes.

**Comment by Xylus** [comment]
@dawidmalina 
We do have a plan to do something about the current 24 char limit, but with the amount of work it requires, and how it'd break backwards compatibility, it probably won't be implemented any time soon.

**Comment by dawidmalina** [comment]
@Xylus do we have a ticket to track this plan according agentId limit?

**Comment by Xylus** [comment]
@dawidmalina None yet unfortunately. We'll try to see if we can target it for a 1.9.x release.
