### ISSUE TITLE
Monitor application health issues

### ISSUE THREAD

**Issue by zqzgit** [naver/pinpoint#4282]
Is pinpoint now able to check the health status of monitoring applications?

**Comment by RoySRose** [comment]
Hello, @zqzgit 
What do you mean by health status of the application?

**Comment by zqzgit** [comment]
Pinpoint monitoring an application, the agent's health status can be obtained, but the agent's health status can not represent the health status of the application being monitored, how can I know whether the monitored application is healthy? Does pinpoint provide this feature?

**Comment by RoySRose** [comment]
Hello, @zqzgit 
Currently, Pinpoint doesn't have any standard or rule to check the health of the application being monitored.

**Comment by zqzgit** [comment]
Okay thank you
