### ISSUE TITLE
PinPoint compile success, but the target application configuration file didn't replace placeholder variable

### ISSUE THREAD

**Issue by hudalong** [naver/pinpoint#4287]
#### Description
I used my compute compile this project, it could be build success, but the application configure files can't replace placehold varialbe in target folder.

#### Environment

* Pinpoint version: 1.8.0
* OS, WAS, affected library, etc: WIN7, WIN_X64
* Additional details (e.g. how your collector/web is set up):
![qq 20180622105635](https://user-images.githubusercontent.com/9346269/41755746-77eb6436-760b-11e8-95b0-0d185966cf8e.png)
![f_22j48af _ 9kw s2200_e](https://user-images.githubusercontent.com/9346269/41755749-7a42ac08-760b-11e8-9ee2-f66c4c6fb129.png)

**Comment by Xylus** [comment]
Hi @hudalong 
The placeholder values are set at runtime, so you won't see the values replaced in the configuration files.
