### ISSUE TITLE
Data cleanup

### ISSUE THREAD

**Issue by ha02148** [naver/pinpoint#429]
Hi,

what is the best way to delete data that are older than certain days or less than a certain response time less?

Maybe a hbase shell query that I can use in a daily cron job.

Also, it would be great if the cleanup is build into the application.

Thanks,
Harry

**Comment by Xylus** [comment]
Hello,
We currently delete old data by:
1. running major compaction every week (cron job), which deletes any data older than the given ttl value.
2. altering the ttl value manually. Checkout the script below for the command on altering ttl values for tables:
```
#!/bin/sh
exec hbase shell <<EOF

disable 'AgentStat'
alter  'AgentStat', { NAME => 'S', TTL => 5184000}
enable 'AgentStat'

disable 'ApplicationMapStatisticsCallee'
alter 'ApplicationMapStatisticsCallee', { NAME => 'C', TTL => 5184000}
alter 'ApplicationMapStatisticsCallee', { NAME => 'D', TTL => 5184000}
enable 'ApplicationMapStatisticsCallee'

disable 'ApplicationMapStatisticsCaller'
alter 'ApplicationMapStatisticsCaller', { NAME => 'C', TTL => 5184000}
enable 'ApplicationMapStatisticsCaller'

disable 'ApplicationMapStatisticsSelf'
alter 'ApplicationMapStatisticsSelf', { NAME => 'C', TTL => 5184000}
enable 'ApplicationMapStatisticsSelf'

disable 'ApplicationStatistics'
alter 'ApplicationStatistics', { NAME => 'C', TTL => 5184000}
enable 'ApplicationStatistics'

disable 'ApplicationTraceIndex'
alter 'ApplicationTraceIndex', { NAME => 'I', TTL => 5184000} 
enable 'ApplicationTraceIndex'

disable 'HostApplicationMap'
alter 'HostApplicationMap', { NAME => 'M', TTL => 5184000}
enable 'HostApplicationMap'

disable 'HostApplicationMap_Ver2'
alter 'HostApplicationMap_Ver2', { NAME => 'M', TTL => 5184000}
enable 'HostApplicationMap_Ver2'

disable 'Traces'
alter 'Traces', { NAME => 'S', TTL => 5184000}
alter 'Traces', { NAME => 'A', TTL => 5184000}
alter 'Traces', { NAME => 'T', TTL => 5184000}
enable 'Traces'

EOF
```
You could probably set the ttl with an appropriate value and run major compaction as a daily cron job.

We currently don't have a separate way to delete data with response time less than a certain value, but I agree that it would be great to have some kind of data management built into the application.
It is however, not very high on our to-do list.

Thank you.

**Comment by ha02148** [comment]
Thank you.  I will try it.

**Comment by vikasmsg** [comment]
@Xylus Is there any other way to delete the old data ?

**Comment by auqf** [comment]
how to clean up the pinot data?
