### ISSUE TITLE
supported-browsers

### ISSUE THREAD

**Issue by yxz1025** [naver/pinpoint#4305]
![image](https://user-images.githubusercontent.com/6748654/41960504-72260054-7a22-11e8-959d-d0c4ae26b3cb.png)

**Comment by yxz1025** [comment]
this is 1.7.3-release version

**Comment by RoySRose** [comment]
Hello, @yxz1025 
This won't happen if you use the supported browsers for Pinpoint-Web.
If still does show above message, Please try to rebuild Pinpoint-Web.
No problem has been reported for 1.7.3.

**Comment by ighack** [comment]
I have same problem

**Comment by ighack** [comment]
check "Permission denied"
if you use nginx
