### ISSUE TITLE
Can't get trace data when I use consul

### ISSUE THREAD

**Issue by Kumilo** [naver/pinpoint#4310]
I use spring-cloud-consul to find my application, when called by the service-name,  like http://service-name/xxx/   pinpoint can't get the trace data。 but when use ip and port  (like http://ip:port/xxx/) to invoke my application. It's OK!    how can I get the trace data when I use spring-cloud-consul.

**Comment by Xylus** [comment]
Hi @Kumilo 
I think it could be because we do not have spring consul support? I'd imagine spring consul does some elaborate service discovery which would not be traced by pinpoint out of the box.
