### ISSUE TITLE
change AGENT_NAME_MAX_LEN cause error

### ISSUE THREAD

**Issue by zfaster** [naver/pinpoint#4312]
**What version of pinpoint are you using?**
v1.7.3

**Describe the bug**
when i change the param AGENT_NAME_MAX_LEN to 32 and APPLICATION_NAME_MAX_LEN remain 24 ,
com.navercorp.pinpoint.web.mapper.TraceIndexScatterMapper3#createDot the Dot reverseAcceptedTime read was 0, beacuse this
`long reverseAcceptedTime = BytesUtils.bytesToLong(cell.getRowArray(), cell.getRowOffset() + HBaseTables.APPLICATION_NAME_MAX_LEN + HBaseTables.APPLICATION_TRACE_INDEX_ROW_DISTRIBUTE_SIZE);
        `
there why use HBaseTables.APPLICATION_NAME_MAX_LEN  it is bug? i think there should use AGENT_NAME_MAX_LEN

my english no good,do you know what i mean?

**Comment by Xylus** [comment]
Hi @zfaster 
It might be a bug, though it may be the collector's serialization part that is the issue.
We'll look into it, thanks for reporting.

That said, I am not sure if changing **AGENT_NAME_MAX_LEN** to 32 is safe enough to ensure proper operation. (It will break any data that has been stored using the default length for one thing)
Please share your experience if you do decide to go with it anyway.

**Comment by zfaster** [comment]
I want to send http header Pinpoint-TraceID、Pinpoint-SpanID from my browser client , that i can trace from browser to server ,I need to  Pinpoint-TraceID unique so have to use uuid and change AGENT_NAME_MAX_LEN to 32, do you have some other suggest if i want to do this
