### ISSUE TITLE
when cursor across the column of response summary chart, data will flashing on the chart

### ISSUE THREAD

**Issue by bigsnapdragon** [naver/pinpoint#4324]
**What version of pinpoint are you using?**
v1.7.2 

**Description**
Open the topology page, when cursor across the column of response summary chart, data will flashing on the chart.

**What did you do to trigger the bug?**
Steps to reproduce, for example:
1. Open the topology page
2. Cursor across the column of response summary chart
3. Browser is Chrome  61.0.3163.91 （64bit ）

**Screenshots**
![qq 20180703151428](https://user-images.githubusercontent.com/17841615/42204863-71d9f3e6-7ed5-11e8-9fd9-9bd1acebc579.png)
![qq 20180703152349](https://user-images.githubusercontent.com/17841615/42204875-78aff4c2-7ed5-11e8-923b-f4a05f8b0d58.png)

**Comment by Xylus** [comment]
Hi @bigsnapdragon 
Thanks for the detailed report.
I think this issue might have been resolved in master (1.8.0-SNAPSHOT), but I'm not sure - @denzelsN ?
