### ISSUE TITLE
Why are the "Active Thread" and "Data Source" graphs empty?

### ISSUE THREAD

**Issue by WangHouLing** [naver/pinpoint#4335]
Hi all,
I installed pinpoint 1.6.2 version, when I select an agent on the left list, there are no data in the "Active Thread" and "Data Source" graphs, but another graphs have data.
**pinpoint version**: 1.6.2
**Project type**: springBoot
**OS**: centos 7
![image](https://user-images.githubusercontent.com/20981477/42270411-627d65a2-7fb3-11e8-9f70-a6f63ab4d9c1.png)
![image](https://user-images.githubusercontent.com/20981477/42270485-8f3c0d64-7fb3-11e8-97fc-8c1141f610da.png)

Is there any way to solve this problem?
Best regards!

**Comment by koo-taejin** [comment]
Hi WangHouLing

1. Please check this issue #2449
2. Please check you're datasource is supported in Pinpoint. (https://naver.github.io/pinpoint/)

thanks.

**Comment by WangHouLing** [comment]
I'm sorry to reply so late.
I have checked issue #2449, but in my condition, these two graphs are always in a state with no data.Is this situation normal?

**Comment by WangHouLing** [comment]
Sorry I misunderstood what you mean.
Do you mean setting the datasource configuration of pinpoint web?
If this is meant to say, my datasource is hbase. I install hbase, zookeeper and hadoop cluster.
**version**:
hbase: hbase-1.2.4
zookeeper: zookeeper-3.4.9
Hadoop: hadoop-2.6.5
pinpoint web hbase.properties:
```
hbase.client.host=XXX.XX.XX.199,XXX.XX.XX.200,XXX.XX.XX.201
hbase.client.port=2181

# hbase default:/hbase
hbase.zookeeper.znode.parent=/hbase

# hbase timeout option==================================================================================
# hbase default:true
hbase.ipc.client.tcpnodelay=true
# hbase default:60000
hbase.rpc.timeout=10000
# hbase default:Integer.MAX_VALUE
hbase.client.operation.timeout=10000

# hbase socket read timeout. default: 200000
hbase.ipc.client.socket.timeout.read=20000
# socket write timeout. hbase default: 600000
hbase.ipc.client.socket.timeout.write=30000

#==================================================================================
# hbase client thread pool option
hbase.client.thread.max=64
hbase.client.threadPool.queueSize=5120
# prestartAllCoreThreads
hbase.client.threadPool.prestart=false

#==================================================================================
# hbase parallel scan options
hbase.client.parallel.scan.enable=true
hbase.client.parallel.scan.maxthreads=64
hbase.client.parallel.scan.maxthreadsperscan=16
```

**Comment by koo-taejin** [comment]
Your PINPOINT web datasource has nothing to related with DataSource chart.
It means the DataSource used by your application datasource

**Comment by WangHouLing** [comment]
Ok, my applications datasources are redis and oracle.

**Comment by koo-taejin** [comment]
The DataSource supported by PINPOINT is HikariCP, DBCP. DBCP2. 

thanks.
