### ISSUE TITLE
pinpoint-tools-1.7.3.jar no main manifest attribute

### ISSUE THREAD

**Issue by imperio-wxm** [naver/pinpoint#4336]
**What version of pinpoint are you using?**
v1.7.3

**Describe your problem**
pinpoint-tools-1.7.3.jar

```java
java -jar pinpoint-tools-1.7.3.jar ../pinpoint.config 

no main manifest attribute, in pinpoint-tools-1.7.3.jar
```

```java
java -cp pinpoint-tools-1.7.3.jar com.navercorp.pinpoint.tools.NetworkAvailabilityChecker ../pinpoint.config

orkAvailabilityChecker ../pinpoint.config Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/thrift/TBase
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.thrift.TBase
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

**Comment by Xylus** [comment]
Hi @imperio-wxm 
Sorry for the late reply.
It looks like the version without classpaths and executable got assembled into the agent. We'll look into the issue.

In the mean time, please try running it via
```
java -cp "pinpoint-tools-1.7.3.jar;../lib/*;../boot/*" com.navercorp.pinpoint.tools.NetworkAvailabilityChecker ../pinpoint.config
```
Let me know if the above doesn't work.

Thanks.

**Comment by rambolijian** [comment]
Hi @Xylus 
I had try it with "`java -cp "pinpoint-tools-1.7.3.jar;../lib/*;../boot/*" com.navercorp.pinpoint.tools.NetworkAvailabilityChecker ../pinpoint.config`", 
but it's also failed. 

And I also try it with "`sh networktest.sh`"
It didn't work too. below is the detail info:

```
[root@ceshi122 script]# sh networktest.sh 
networktest.sh: line 2: $'\r': command not found
/..: No such file or directory
networktest.sh: line 5: $'\r': command not found
CLASSPATH=
Error: Could not find or load main class com.navercorp.pinpoint.tools.NetworkAvailabilityChecker
[root@ceshi122 script]# pwd
/root/pinpoint/pp-agent/script
```

could you take a look at it? Thanks a lot!

**Comment by Xylus** [comment]
@rambolijian 
I just tried running `java -cp "pinpoint-tools-1.7.3.jar;../lib/*;../boot/*" com.navercorp.pinpoint.tools.NetworkAvailabilityChecker ../pinpoint.config` and it seems to be working.
What does your error say?

As for the *networktest.sh*, it should work as well, but it seems like the script file you've got has '\r\n' for empty lines.
Try creating *networktest.sh* manually and copy-pasting the content directly and running it.

**Comment by rambolijian** [comment]
@Xylus 
when I run `pinpoint-tools-1.7.3.jar` or `networktest.sh`, it met the same error:

> [root@ceshi122 tools]# pwd
> /root/pinpoint/pp-agent/tools
> [root@ceshi122 tools]# java -cp "pinpoint-tools-1.7.3.jar;../lib/*;../boot/*" com.navercorp.pinpoint.tools.NetworkAvailabilityChecker ../pinpoint.config
> **Error: Could not find or load main class com.navercorp.pinpoint.tools.NetworkAvailabilityChecker**

**Comment by rambolijian** [comment]
@Xylus
Perfect! you are right. Now it is working. Thanks for your help very much.

**Comment by Xylus** [comment]
@rambolijian Glad it worked out :)
