### ISSUE TITLE
The datasource chart of agent-1.6.2 shows well, but it is no data for agent-1.7.0-SNAPSHOT and agent-1.7.3.

### ISSUE THREAD

**Issue by banbeishui** [naver/pinpoint#4340]
**What version of pinpoint are you using?**
The collector version is 1.7.0-SNAPSHOT, the agent version is 1.6.2/1.7.0-SNAPSHOT/1.7.3

**Describe your problem**
In the inspector page, the datasource chart of Oracle database shows well but the response time chart  has no data when agent version is 1.6.2 which I use. 
At other team, they use my collector, the agent version is 1.7.0-SNAPSHOT/1.7.3 and the database is MySQL, but the datasource chart has no data.  
We both use HIKARICP.
**Screenshots**
![image](https://user-images.githubusercontent.com/6970559/42309560-7e44e7b6-806b-11e8-898d-42ee73b6fa9b.png)
![image](https://user-images.githubusercontent.com/6970559/42309713-fb470690-806b-11e8-9736-3e4477fdc118.png)

**Comment by koo-taejin** [comment]
hi banbeishui 

We recommend that the collector and web module be the same or newer than the agent version.
And the unstable version is unstable, So can cause problems.
I recommand you solving above issuees and test again

thanks.

**Comment by banbeishui** [comment]
Hi, koo-taejin
The first screenshot of the version is 1.7.0-SNAPSHOT, including agent,collector,web. But the datasource chart still has no data.

**Comment by koo-taejin** [comment]
Unstable versions like SNAPSHOT have a lot of changes, so we have difficulty solving problem.
I recommand you using a stable version. and check this issue again.

thanks.
