### ISSUE TITLE
Inspector integration with Pinpoint

### ISSUE THREAD

**Issue by selvahari515** [naver/pinpoint#4342]
Hi, We have setup pinpoint-web, collector, and Hbase. We need to implement inspector with pinpoint. We need step by step procedure to implement this.

**Comment by RoySRose** [comment]
Hello, @selvahari515 

You don't have to do anything for the inspectors. Web, Collector, Agent would be enough.
IF you want to use the application inspector feature(which is little different from the one I've mentioned above) take a look at [here](https://naver.github.io/pinpoint/applicationinspector.html)
