### ISSUE TITLE
pinpoint agent with signed/encrypted Soap

### ISSUE THREAD

**Issue by vinni2973** [naver/pinpoint#4344]
Hello,
We have configured pinpoint agent for two applications which exchange informations in using signed and encrypted soap web services with Spring wss4j implementation. 
Is PinPoint able to trace such RPC ?
If it is the case, what are the configuration options to apply ?

 Yours sincerely

**Comment by Xylus** [comment]
Hi @vinni2973 
I'm afraid I don't have enough knowledge on soap/wss4j to give you a thorough answer.
But pinpoint doesn't have explicit support for either of them.
