### ISSUE TITLE
pinpoint-bootstrap-x.x.x(-SNAPSHOT).jar not found

### ISSUE THREAD

**Issue by fionaliupw** [naver/pinpoint#4353]
Description：
(com.navercorp.pinpoint.bootstrap.AgentDirBaseClassPathResolver) pinpoint-bootstrap-x.x.x(-SNAPSHOT).jar not found 
(com.navercorp.pinpoint.bootstrap.PinpointBootStrap) Agent Directory Verify fail. skipping agent loading. 

i have checked the agentpath config is ok, and network is also  accessable.

I need help, thanks.

**Comment by Xylus** [comment]
Hi @fionaliupw 
I can only tell you to check your *-javaagent* path with the information you have provided.
Please post according to the [Troubleshooting template](https://github.com/naver/pinpoint/issues/new?template=troubleshooting.md) with more information for us to help you better.
