### ISSUE TITLE
Unable to build pinpoint (in Windows 7)

### ISSUE THREAD

**Issue by aniksachdeva** [naver/pinpoint#4355]
Hi
I am not able to build pinpoint in Windows 7.

I got this error in the command line:

_C:\Users\Z003U7MH\Downloads\pinpoint-master> mvnw install -Prelease -Dmaven.test
.skip=true
Found "C:\Users\Z003U7MH\Downloads\pinpoint-master\.mvn\wrapper\maven-wrapper.ja
r"
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] pinpoint                                                           [pom]
[INFO] pinpoint-annotations                                               [jar]
[INFO] pinpoint-commons                                                   [jar]
[INFO] pinpoint-thrift                                                    [jar]
[INFO] pinpoint-bootstrap-core                                            [jar]
[INFO] pinpoint-bootstrap                                                 [jar]
[INFO] pinpoint-rpc                                                       [jar]
[INFO] pinpoint-profiler                                                  [jar]
[INFO] pinpoint-commons-hbase                                             [jar]
[INFO] pinpoint-commons-server                                            [jar]
[INFO] pinpoint-profiler-test                                             [jar]
[INFO] pinpoint-profiler-optional-parent                                  [pom]
[INFO] pinpoint-profiler-optional-jdk6                                    [jar]
[INFO] pinpoint-profiler-optional-jdk7                                    [jar]
[INFO] pinpoint-test                                                      [jar]
[INFO] pinpoint-profiler-optional-jdk8                                    [jar]
[INFO] pinpoint-profiler-optional-jdk9                                    [jar]
[INFO] pinpoint-profiler-optional                                         [pom]
[INFO] pinpoint-httpclient3-plugin                                        [jar]
[INFO] pinpoint-httpclient4-plugin                                        [jar]
[INFO] pinpoint-ning-asynchttpclient-plugin                               [jar]
[INFO] pinpoint-resttemplate-plugin                                       [jar]
[INFO] pinpoint-netty-plugin                                              [jar]
[INFO] pinpoint-gson-plugin                                               [jar]
[INFO] pinpoint-cubrid-jdbc-driver-plugin                                 [jar]
[INFO] pinpoint-mysql-jdbc-driver-plugin                                  [jar]
[INFO] pinpoint-mariadb-jdbc-driver-plugin                                [jar]
[INFO] pinpoint-postgresql-jdbc-driver-plugin                             [jar]
[INFO] pinpoint-jtds-plugin                                               [jar]
[INFO] pinpoint-oracle-jdbc-driver-plugin                                 [jar]
[INFO] pinpoint-commons-dbcp-plugin                                       [jar]
[INFO] pinpoint-commons-dbcp2-plugin                                      [jar]
[INFO] pinpoint-hikaricp-plugin                                           [jar]
[INFO] pinpoint-cassandra-driver-plugin                                   [jar]
[INFO] pinpoint-jdk-http-plugin                                           [jar]
[INFO] pinpoint-redis-plugin                                              [jar]
[INFO] pinpoint-tomcat-plugin                                             [jar]
[INFO] pinpoint-json-lib-plugin                                           [jar]
[INFO] pinpoint-jackson-plugin                                            [jar]
[INFO] pinpoint-thrift-plugin                                             [jar]
[INFO] pinpoint-user-plugin                                               [jar]
[INFO] pinpoint-arcus-plugin                                              [jar]
[INFO] pinpoint-google-httpclient-plugin                                  [jar]
[INFO] pinpoint-jetty-plugin                                              [jar]
[INFO] pinpoint-websphere-plugin                                          [jar]
[INFO] pinpoint-spring-plugin                                             [jar]
[INFO] pinpoint-spring-boot-plugin                                        [jar]
[INFO] pinpoint-ibatis-plugin                                             [jar]
[INFO] pinpoint-mybatis-plugin                                            [jar]
[INFO] pinpoint-okhttp-plugin                                             [jar]
[INFO] pinpoint-log4j-plugin                                              [jar]
[INFO] pinpoint-logback-plugin                                            [jar]
[INFO] pinpoint-dubbo-plugin                                              [jar]
[INFO] pinpoint-activemq-client-plugin                                    [jar]
[INFO] pinpoint-cxf-plugin                                                [jar]
[INFO] pinpoint-hystrix-plugin                                            [jar]
[INFO] pinpoint-jboss-plugin                                              [jar]
[INFO] pinpoint-vertx-plugin                                              [jar]
[INFO] pinpoint-resin-plugin                                              [jar]
[INFO] pinpoint-jsp-plugin                                                [jar]
[INFO] pinpoint-rxjava-plugin                                             [jar]
[INFO] pinpoint-rabbitmq-plugin                                           [jar]
[INFO] pinpoint-weblogic-plugin                                           [jar]
[INFO] pinpoint-php-plugin                                                [jar]
[INFO] pinpoint-plugins                                                   [pom]
[INFO] pinpoint-bootstrap-java9                                           [jar]
[INFO] pinpoint-bootstrap-core-optional                                   [jar]
[INFO] pinpoint-tools                                                     [jar]
[INFO] pinpoint-agent-distribution                                        [jar]
[INFO] pinpoint-collector                                                 [war]
[INFO] pinpoint-plugin-bom                                                [pom]
[INFO] pinpoint-web                                                       [war]
[INFO] pinpoint-hbase-distribution                                        [pom]
[INFO] pinpoint-flink                                                     [jar]
[INFO]
[INFO] ------------------< com.navercorp.pinpoint:pinpoint >-------------------
[INFO] Building pinpoint 1.8.0-SNAPSHOT                                  [1/74]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-pinpoint-build-requireme
nts) @ pinpoint ---
[INFO]
[INFO] --- animal-sniffer-maven-plugin:1.16:check (ensure-java-1.6-class-library
) @ pinpoint ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.0
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ pinpoint ---
[INFO] Installing C:\Users\Z003U7MH\Downloads\pinpoint-master\pom.xml to C:\User
s\Z003U7MH\.m2\repository\com\navercorp\pinpoint\pinpoint\1.8.0-SNAPSHOT\pinpoin
t-1.8.0-SNAPSHOT.pom
[INFO]
[INFO] ------------< com.navercorp.pinpoint:pinpoint-annotations >-------------
[INFO] Building pinpoint-annotations 1.8.0-SNAPSHOT                      [2/74]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-pinpoint-build-requireme
nts) @ pinpoint-annotations ---
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ pinpoint
-annotations ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] skip non existing resourceDirectory C:\Users\Z003U7MH\Downloads\pinpoint-
master\annotations\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ pinpoint-anno
tations ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to C:\Users\Z003U7MH\Downloads\pinpoint-master\a
nnotations\target\classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] pinpoint 1.8.0-SNAPSHOT ............................ SUCCESS [  1.581 s]
[INFO] pinpoint-annotations ............................... FAILURE [  0.959 s]
[INFO] pinpoint-commons ................................... SKIPPED
[INFO] pinpoint-thrift .................................... SKIPPED
[INFO] pinpoint-bootstrap-core ............................ SKIPPED
[INFO] pinpoint-bootstrap ................................. SKIPPED
[INFO] pinpoint-rpc ....................................... SKIPPED
[INFO] pinpoint-profiler .................................. SKIPPED
[INFO] pinpoint-commons-hbase ............................. SKIPPED
[INFO] pinpoint-commons-server ............................ SKIPPED
[INFO] pinpoint-profiler-test ............................. SKIPPED
[INFO] pinpoint-profiler-optional-parent .................. SKIPPED
[INFO] pinpoint-profiler-optional-jdk6 .................... SKIPPED
[INFO] pinpoint-profiler-optional-jdk7 .................... SKIPPED
[INFO] pinpoint-test ...................................... SKIPPED
[INFO] pinpoint-profiler-optional-jdk8 .................... SKIPPED
[INFO] pinpoint-profiler-optional-jdk9 .................... SKIPPED
[INFO] pinpoint-profiler-optional ......................... SKIPPED
[INFO] pinpoint-httpclient3-plugin ........................ SKIPPED
[INFO] pinpoint-httpclient4-plugin ........................ SKIPPED
[INFO] pinpoint-ning-asynchttpclient-plugin ............... SKIPPED
[INFO] pinpoint-resttemplate-plugin ....................... SKIPPED
[INFO] pinpoint-netty-plugin .............................. SKIPPED
[INFO] pinpoint-gson-plugin ............................... SKIPPED
[INFO] pinpoint-cubrid-jdbc-driver-plugin ................. SKIPPED
[INFO] pinpoint-mysql-jdbc-driver-plugin .................. SKIPPED
[INFO] pinpoint-mariadb-jdbc-driver-plugin ................ SKIPPED
[INFO] pinpoint-postgresql-jdbc-driver-plugin ............. SKIPPED
[INFO] pinpoint-jtds-plugin ............................... SKIPPED
[INFO] pinpoint-oracle-jdbc-driver-plugin ................. SKIPPED
[INFO] pinpoint-commons-dbcp-plugin ....................... SKIPPED
[INFO] pinpoint-commons-dbcp2-plugin ...................... SKIPPED
[INFO] pinpoint-hikaricp-plugin ........................... SKIPPED
[INFO] pinpoint-cassandra-driver-plugin ................... SKIPPED
[INFO] pinpoint-jdk-http-plugin ........................... SKIPPED
[INFO] pinpoint-redis-plugin .............................. SKIPPED
[INFO] pinpoint-tomcat-plugin ............................. SKIPPED
[INFO] pinpoint-json-lib-plugin ........................... SKIPPED
[INFO] pinpoint-jackson-plugin ............................ SKIPPED
[INFO] pinpoint-thrift-plugin ............................. SKIPPED
[INFO] pinpoint-user-plugin ............................... SKIPPED
[INFO] pinpoint-arcus-plugin .............................. SKIPPED
[INFO] pinpoint-google-httpclient-plugin .................. SKIPPED
[INFO] pinpoint-jetty-plugin .............................. SKIPPED
[INFO] pinpoint-websphere-plugin .......................... SKIPPED
[INFO] pinpoint-spring-plugin ............................. SKIPPED
[INFO] pinpoint-spring-boot-plugin ........................ SKIPPED
[INFO] pinpoint-ibatis-plugin ............................. SKIPPED
[INFO] pinpoint-mybatis-plugin ............................ SKIPPED
[INFO] pinpoint-okhttp-plugin ............................. SKIPPED
[INFO] pinpoint-log4j-plugin .............................. SKIPPED
[INFO] pinpoint-logback-plugin ............................ SKIPPED
[INFO] pinpoint-dubbo-plugin .............................. SKIPPED
[INFO] pinpoint-activemq-client-plugin .................... SKIPPED
[INFO] pinpoint-cxf-plugin ................................ SKIPPED
[INFO] pinpoint-hystrix-plugin ............................ SKIPPED
[INFO] pinpoint-jboss-plugin .............................. SKIPPED
[INFO] pinpoint-vertx-plugin .............................. SKIPPED
[INFO] pinpoint-resin-plugin .............................. SKIPPED
[INFO] pinpoint-jsp-plugin ................................ SKIPPED
[INFO] pinpoint-rxjava-plugin ............................. SKIPPED
[INFO] pinpoint-rabbitmq-plugin ........................... SKIPPED
[INFO] pinpoint-weblogic-plugin ........................... SKIPPED
[INFO] pinpoint-php-plugin ................................ SKIPPED
[INFO] pinpoint-plugins ................................... SKIPPED
[INFO] pinpoint-bootstrap-java9 ........................... SKIPPED
[INFO] pinpoint-bootstrap-core-optional ................... SKIPPED
[INFO] pinpoint-tools ..................................... SKIPPED
[INFO] pinpoint-agent-distribution ........................ SKIPPED
[INFO] pinpoint-collector ................................. SKIPPED
[INFO] pinpoint-plugin-bom ................................ SKIPPED
[INFO] pinpoint-web ....................................... SKIPPED
[INFO] pinpoint-hbase-distribution ........................ SKIPPED
[INFO] pinpoint-flink 1.8.0-SNAPSHOT ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.676 s
[INFO] Finished at: 2018-07-10T14:58:07+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
7.0:compile (default-compile) on project pinpoint-annotations: Compilation failu
re -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :pinpoint-annotations_

Kindly help me in resolving this issue.

**Comment by Xylus** [comment]
Hi @aniksachdeva 
Have you tried running maven with *-X* switch as the log says?
Also, please post according to the [Troubleshooting template](https://github.com/naver/pinpoint/issues/new?template=troubleshooting.md).
(Feel free to reopen the issue once you've edited your post)
