### ISSUE TITLE
How to check whether the app is finished or not which added pinpoint ?

### ISSUE THREAD

**Issue by xiaoshao** [naver/pinpoint#4362]
I am trying to use pinpoint in our env.  I added env ·JAVA_TOOL_OPTIONS=‘-javaagent=.....’· to enable pinpoint in our env.  We check the sevice is start or not with jps in the startup shell, But it is stuck in jps and our application can't startup.  What can I do to fix this?

**Comment by Xylus** [comment]
Hi @xiaoshao 
Try checking the agent / application log to see if anything's weird. The agent log is in *$PINPOINT_AGENT/log* directory.

**Comment by xiaoshao** [comment]
Thanks, I will check it.

**Comment by xiaoshao** [comment]
I have fixed that by change all the thread to daemon.
