### ISSUE TITLE
Why is there no Hbase plugin support?

### ISSUE THREAD

**Issue by VictorZeng** [naver/pinpoint#4367]
**Which module is your feature request related to?**
Plugin/Hbase

**Is your feature request related to a problem?**
A clear and concise description of what the problem is.

**Describe the solution you'd like**
Hbase GET/PUT/DELETE/SCAN etc

**Describe alternatives you've considered**

**Additional context**

**Comment by RoySRose** [comment]
Hello, @VictorZeng 

We hope that we can provide all the features. But unfortunately, it's not easy due to lack of time.
It would be GREAT for Pinpoint Community if you can make Hbase-plugin and share with us:)

**Comment by VictorZeng** [comment]
@RoySRose I will make the Hbase-plugin

**Comment by RoySRose** [comment]
@VictorZeng 
Oh! Perfect~! We are really looking forward to it~!
