### ISSUE TITLE
Pinpoint can only display the first request of the project

### ISSUE THREAD

**Issue by lz908580572** [naver/pinpoint#4378]
After installing Pinpoint 1.7.3 and deploying a test project,  I visit its addresses,  such as 
 http://10.100.xxx.xxx:8080/test and  http://10.100.xxx.xxx:8080, but pinpoint-web can only **display first request**, others after that can not be monitored. 
Only if I restart my test project,  pinpoint-web will display another **one** point.

![image](https://user-images.githubusercontent.com/41371380/42879136-2a12c97c-8ac2-11e8-9c91-d063da407ab5.png)

Hope to get help, thanks, and have a nice day.

---
Environment: 

Pinpoint 1.7.3 
hbase 1.2.6
jdk 8u171_linux_x64
CentOS 7.0

**Comment by koo-taejin** [comment]
please check this issue #3802
