### ISSUE TITLE
How to submit myself plugin to pinpoint

### ISSUE THREAD

**Issue by symark** [naver/pinpoint#4382]
I've finished a new plug-in for alibaba’s druid data source.

**Comment by RoySRose** [comment]
Hello @symark 

First of all, Thank you for our interest and contribution to Pinpoint Community:)

you can take a look in to [our contribution guide](http://naver.github.io/pinpoint/contribution.html) first. It may look a lot at the first glance. But most of them are probably taken care of if you are ready for the contribution:)

If you need any further help,  write here~ I'll follow you up~

**Comment by symark** [comment]
thx,i understand.
