### ISSUE TITLE
Upload file problem

### ISSUE THREAD

**Issue by symark** [naver/pinpoint#4387]
i use post of http to upload file,but a little of request be saved.another most requset not be saved in pinpoint. why?

**Comment by Xylus** [comment]
Hi @symark 
I don't understand what's going on. Could you explain it a bit more?

**Comment by symark** [comment]
If it's a post request, can it be logged?

**Comment by Xylus** [comment]
@symark Yes.

**Comment by symark** [comment]
but i wanna logged~~~~~~~

**Comment by Xylus** [comment]
Hi @symark 
It might have to do with the sampling rate. Please check [this](https://github.com/naver/pinpoint/wiki/FAQ#why-is-only-the-firstsome-of-the-requests-traced) section in the wiki, which just got added.
You'll have to set `profiler.sampling.rate=1` in your agent's *pinpoint.config* file to trace every request.

**Comment by symark** [comment]
thank you ,guy
