### ISSUE TITLE
Project Enhancement ( Logo )

### ISSUE THREAD

**Issue by debpedrano** [naver/pinpoint#4393]
I will be proposing you a logo for the project enhancement, the current one is awesome but give me chance to submit my design.

**Comment by debpedrano** [comment]
Can i update this? i am willing to submit my design. Please do reply

**Comment by RoySRose** [comment]
Hello, @debpedrano 

Well, it's an open-source project 
You can submit your design at your will.

But, please understand that I can't guarantee anything on it :)

**Comment by debpedrano** [comment]
@RoySRose  that would be fine, as long as you will accept my design and make it as a back-up logo for the project.

**Comment by RoySRose** [comment]
@debpedrano

As I've mentioned. I can't gurantee anything.
It's your free will, submitting the logo.

**Comment by RoySRose** [comment]
@debpedrano

As I've mentioned. I can't gurantee anything.
It's your free will, submitting the logo.

**Comment by RoySRose** [comment]
@debpedrano

As I've mentioned. I can't gurantee anything.
It's your free will, submitting the logo.
