### ISSUE TITLE
Pinpoin is only suport HTTP protocal to transfer message between server node?  if no .what i shoud do to make it  support dubbo protocal ?

### ISSUE THREAD

**Issue by zhaosongqiang** [naver/pinpoint#4397]
Pinpoin is only suport HTTP protocal to transfer message between server node?  if no .what i shoud do to make it  support dubbo protocal ?

**Comment by Xylus** [comment]
Hi @zhaosongqiang 
I'm not sure if the Dubbo plugin has support for dubbo protocol. If not, it won't propagate trace over to a different process without explicit support.
More specifically, trace data need to be encoded in the message (we include these data in the header for HTTP calls), which will require support from the Dubbo plugin.

So if you would like to support Dubbo protocol, you'll have to add this into the Dubbo plugin.
If you're willing to work on it, please take a look at the [plugin developer guide](http://naver.github.io/pinpoint/plugindevguide.html) and feel free to ask if you have any questions.

**Comment by zhaosongqiang** [comment]
ok,thank you. i got it . @Xylus
