### ISSUE TITLE
how to register spring bean for alarm after Implementing AlarmMessageSender

### ISSUE THREAD

**Issue by rambolijian** [naver/pinpoint#4400]
Hi pinpoint team,

Could you display the steps about how to register spring bean for alarm after Implementing AlarmMessageSender? I don't know how to do it.

Thanks a lot!

**Comment by minwoo-jung** [comment]
Hi @rambolijian 

you should register spring bean in [applicationContext-web.xml](https://github.com/naver/pinpoint/blob/master/web/src/main/resources/applicationContext-web.xml).

**Comment by rambolijian** [comment]
@minwoo-jung

Thank you very much!
