### ISSUE TITLE
Capture Java Thread ID

### ISSUE THREAD

**Issue by Ryner51** [naver/pinpoint#4403]
When running an application within a Web Container (i.e. Jetty), is there a way to capture the Java Thread Id in which the transaction was running on? I am looking to take transactions that have been identified as slow in PinPoint and trace them back to our Jetty logs using the Java Thread Id. This would be useful in tracking down any logs we have within our application to help further track down performance issues.

**Comment by Xylus** [comment]
Hi @Ryner51 
While we don't capture thread ids, you might find [this](http://naver.github.io/pinpoint/perrequestfeatureguide.html) useful.
What it does is add transaction ids and span ids to your log so that you can correlate what's shown in pinpoint back to your log.
