### ISSUE TITLE
Can Pinpoint work for TCP servers ??

### ISSUE THREAD

**Issue by TiMusBhardwaj** [naver/pinpoint#4409]
Many of the tracing tool have out of box support for Web Applications, but not for tcp servers.
They pass tracing id in http header.
How tracing id is passed in pinpoint ??
How can i configure it for tcp servers.??

**Comment by koo-taejin** [comment]
hi TiMusBhardwaj

Pinpoint not support to trace for native tcp socket. 
Pinpoint also passes the trace id via the header.
You can check to support what plugin via this link(https://github.com/naver/pinpoint#supported-modules) 

thanks.
