### ISSUE TITLE
AgentStat.jvmGcDetailed.gcNewTime error

### ISSUE THREAD

**Issue by yjqg6666** [naver/pinpoint#4414]
**What version of pinpoint are you using?**
master/v1.7.3/v1.7.2 etc.

**Describe the bug**
From /getAgentStat/jvmGcDetailed.pinpoint, the  gcNewTime always equals to gcNewCount

**Expected behavior**
gcNewTime & gcNewCount should be different.

**Comment by yjqg6666** [comment]
Fixed in PR naver/pinpoint#4415.

**Comment by Xylus** [comment]
@yjqg6666 Thanks for reporting and the fix!
