### ISSUE TITLE
Does any tools or code to direct  analysis the data stored in hbase

### ISSUE THREAD

**Issue by accumulatepig** [naver/pinpoint#4438]
I wanna get the calltree data from hbase directly and to integrate into our monitor platform ，does any way to  analysis the data stored in hbase ,thks

**Comment by RoySRose** [comment]
@accumulatepig 
We are considering this API and hope that this feature can be developed.
But for now, we have no resource to do this.
If you can make one and contribute to the community. It's always welcome and will be super great!

**Comment by accumulatepig** [comment]
ok ,thks
