### ISSUE TITLE
can't support Spring Boot(Embedded Undertow)?

### ISSUE THREAD

**Issue by rambolijian** [naver/pinpoint#4443]
Hi Pinpoint Team,

Thanks very much for your support.

Now, we use **Spring boot start with Undertow**. I want to monitor our application(Spring boot start with Undertow) with Pinpoint. But there aren't any requests in pinpoint-web, it's already registered to Pinpoint.
can't support "Spring Boot(Embedded Undertow)" module?

> `Pinpoint version: 1.7.3`

**Comment by dionatanribeiro** [comment]
Same problem here

**Comment by Xylus** [comment]
Hi @rambolijian @dionatanribeiro 
Undertow has just been merged a few days ago (#4446, #4447) and along with it, SpringBoot's embedded Undertow will be available in 1.8.0.

**Comment by emeroad** [comment]
duplicate : #1563

**Comment by rambolijian** [comment]
@Xylus @emeroad 

Can I ask when will you release 1.8.0? Because we want to wait for this version to support undertow. otherwise we will use tomcat instead of undertow.

Thanks again!

**Comment by Xylus** [comment]
@rambolijian RC version should be released very soon.
