### ISSUE TITLE
Add support to jetty

### ISSUE THREAD

**Issue by dawidmalina** [naver/pinpoint#446]
It would be.nice to have dedicated profiler for jetty same as we have for tomcat.

**Comment by nstopkimsk** [comment]
Thanks for your suggestion.  We have plan to support Jetty and jboss. 
but if there is anyone who want to implement is, that will be okay.

**Comment by dawidmalina** [comment]
Is there any guide howto do this. Maybe some small hello world example howto create new plugin.

**Comment by jaycjay** [comment]
Here's a [sample plug-in](https://github.com/lioolli/pinpoint-plugin-sample "plug-in sample") you can look at.

**Comment by dawidmalina** [comment]
:+1:
