### ISSUE TITLE
My application is not displayed as a node in Server Map

### ISSUE THREAD

**Issue by JasonRui** [naver/pinpoint#4466]
Hi, I developed a Plugin and Intercept a class's some method. 
I can see my application in the request's call stack. And I also made this method as a entry point.
How can I made my application a node in server map.

**Comment by RoySRose** [comment]
hello, @JasonRui 
Take a look at the [plugin development guide](https://naver.github.io/pinpoint/plugindevguide.html#4-adding-images)

**Comment by JasonRui** [comment]
If the method that I intercept do not have a HTTP/RPC request, and configuration is right, will it be displayed in server map?
