### ISSUE TITLE
The application list is empty sometimes

### ISSUE THREAD

**Issue by light0x000** [naver/pinpoint#4481]
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/29830476/43893147-8ccab5a8-9c00-11e8-8b51-a8b4cfc5e503.png">

**Comment by RoySRose** [comment]
Hello, @light0x000 
If it's the first time setting up Pinpoint. The list needs some time to show up after data starts to flow through the network.

**Comment by light0x000** [comment]
dd
