### ISSUE TITLE
How exactly the data transport from agent to pinpoint collector? 

### ISSUE THREAD

**Issue by g0ne150** [naver/pinpoint#4488]
When pinpoint agent send a TCP package to collector, there are 48 bits at front of serialized Thrift struct data.
Could you tell me where are they come from and what are they used for?
![image](https://user-images.githubusercontent.com/8351695/43950679-8a45a112-9cc3-11e8-84bc-dc6d72ca56ad.png)

**Comment by koo-taejin** [comment]
hi @g0ne150 

At the pinpoint, we define the packet for each role.
The data is related to the type of the packet.
(Ex) Send, Request, Response, Ping etc ...)

thanks.
