### ISSUE TITLE
Pinpoint-Docker installation failed while configuring Flink

### ISSUE THREAD

**Issue by sattishv** [naver/pinpoint#4490]
**What version of pinpoint are you using?**
I am using docker version of pinpoint by cloning the repo

**Describe your problem**
Docker installation failed throwing error in  Flink configuration.
My docker version:
 docker version
Client:
 Version:      17.06.2-ee-6
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   e75fdb8
 Built:        Mon Nov 27 22:44:50 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ee-6
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   e75fdb8
 Built:        Mon Nov 27 22:43:44 2017
 OS/Arch:      linux/amd64
 Experimental: false

**What have you done?**
git clone https://github.com/naver/pinpoint-docker.git
Clone was successful.
i initiated docker-compose pull && docker-compose up -d
It prompted 
"ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1."

Commented out #version: "3.6" in docker-compose.yml

later we got 
"ERROR: Invalid interpolation format for "jobmanager" option in service "services": "${FLINK_WEB_PORT:-8081}:8081""

**Screenshots**

**Logs**

**Additional context**

**Comment by RoySRose** [comment]
Hello, @sattishv 

It looks like your docker version doesn't support your docker-compose version. Please try to install the docker which support docker-compose 3.6. To get more information on this, check out the documents in the official Docker homepage.
About followed format ERROR. I think it will be also taken care of when you install the supported version.

**Comment by sattishv** [comment]
Hi team,

Thanks for the response. Will try with new version

Sattish.
