### ISSUE TITLE
what's difference between jvm and system cpu usage?

### ISSUE THREAD

**Issue by ITGrocery** [naver/pinpoint#4498]
The gc cpu usage contains in jvm or system cpu usage ?
![_20180813091447](https://user-images.githubusercontent.com/10252344/44008750-63490000-9ed9-11e8-86d5-b2fcfeecc1a5.png)

**Comment by Xylus** [comment]
Hi @ITGrocery 
It will be in both.
Garbage collection is done by the gc thread, which is from the java process, so it'll show up in jvm cpu usage.
System cpu usage includes everything (including the java process), so gc cpu usage will show up in both.
