### ISSUE TITLE
what‘s mean 'Unsampled Continuation'?

### ISSUE THREAD

**Issue by chuanyi-fang** [naver/pinpoint#4514]
what‘s mean 'U.C' 'U.N' 'S.C' 'S.N' 'Active Thread'?

**Comment by chuanyi-fang** [comment]
Thanks.I have know the mean of active thread #2449 .
However,I can't unserstand what‘s mean about 'U.C' 'U.N' 'S.C' 'S.N' by the "?" button's description.

**Comment by Xylus** [comment]
Ah sorry, it should've been the little "?" help button at the top-right corner of **transactions per second** chart, not the active thread chart.
Is this what you were looking at?

Either way, you can think of 'U.C' 'U.N' 'S.C' 'S.N' as ways we can categorize transactions, where every request received by an application can be categorized into 1 of them.
##### New vs Continuation
New - The request is from another application that does not have pinpoint agent installed. So the current application starts a new trace.
Continuation - The request is from another application that has pinpoint agent installed, so a trace has already started. The current application simply continues the trace.
##### Sampled vs Unsampled
Sampled - The transaction is traced.
Unsampled - The transaction is not traced.

So for example, unsampled continuation means the transaction started from another application (and it decided not to trace), and the request received by the application is a part of that transaction.

**Comment by chuanyi-fang** [comment]
Thanks for your comment.
And how to understand the ‘it decided not to trace ’?

**Comment by Xylus** [comment]
@chuanyi-fang 
It means that the application checked it's sampling rate and made the decision based on that. (ie, `profiler.sampling.rate=2` means it traces every 1 out of 2 transactions (50%).

**Comment by chuanyi-fang** [comment]
Thanks very much.
I understand .

**Comment by wingyiu** [comment]
not to trace means "not to send the data to collector and not store it"?

**Comment by Xylus** [comment]
@wingyiu 
It means to not generate any trace data at all (such as spans, span events etc), which consequently will not send anything to the collector and not store anything, so yes.

**Comment by chuanyi-fang** [comment]
How to know the sample rate of 'S.C' 'S.N' been shown in Line Chart?
("profiler.sampling.rate=2" is not what I ask .)

**Comment by Xylus** [comment]
@chuanyi-fang 
I'm not quite sure if this is what you're asking.
Are you asking if we can calculate the sampling rate of 'S.C' and 'S.N' from the chart? If so, then yes, given a large enough sample, just divide them from the total.

**Comment by chuanyi-fang** [comment]
Yes,but I think that “the sampling rate “ should be set in config file.
Isn’t it right?
I want to know where to set the config.

**Comment by chuanyi-fang** [comment]
“profiler.sampling.rate=2 means it traces every 1 out of 2 transactions (50%).”
What I want to know is “”the show sampling rate of 'S.C' and 'S.N' in  the chart”.

**Comment by Xylus** [comment]
I'm sorry, you lost me again heh
I don't understand what you mean by "the show sampling rate of 'S.C' and 'S.N' in the chart".

**Comment by chuanyi-fang** [comment]
For example,The request sum is 600, but 'S.N'  is show 0.1 in the chart.why is  shown 0.1  in the chart?
![image](https://user-images.githubusercontent.com/20055737/44377950-8b121a00-a531-11e8-975d-62b1b5519b1b.png)

**Comment by fionaliupw** [comment]
@Xylus Hi, a transaction started from the current application, and it was traced. Which category （'U.C' 'U.N' 'S.C' 'S.N'）does it belong to? Thank you.

**Comment by Xylus** [comment]
@fionaliupw That would be sampled new (S.N).
Thanks.

**Comment by fionaliupw** [comment]
> @fionaliupw That would be sampled new (S.N).
> Thanks.

Thanks.
