### ISSUE TITLE
Hello,One trace shows different images on two pages?

### ISSUE THREAD

**Issue by edoc1991** [naver/pinpoint#4519]
One trace in main page,show
![1](https://user-images.githubusercontent.com/5277735/44184996-63434080-a144-11e8-986f-a83c37cda6bd.jpg)

But,in server map,show
![2](https://user-images.githubusercontent.com/5277735/44185002-68a08b00-a144-11e8-97f8-1f2748ec7776.jpg)

Picture 1 show dubbo-profiderfunc10000 call dubbo-providerfunc20000 4 times,but Picture 1 show dubbo-profiderfunc10000 call dubbo-providerfunc20000 3 times and dubbo-providerfunc20000 call itself 1 time.
Actually,the picture 2 show the correct trace.

**Comment by RoySRose** [comment]
Hello, @edoc1991 
I don't know much about dubbo.
But I can tell you that the first server-map includes all 7 transactions and the second server-map only shows the map of the selected transaction.
