### ISSUE TITLE
A error request but not found exception in call tree

### ISSUE THREAD

**Issue by JasonRui** [naver/pinpoint#4522]
Hello, I found a error in my PinPoint dashboard. It is a request from user to Tomcat. But I do not found any exception in the call tree. The http.status.code is 200.

And my profiler.http.status.code.errors=5xx. I also checked my application's log and there is no exception thrown out.
Where is the error occurs?

**Comment by RoySRose** [comment]
Hello, @JasonRui 
If there was an error in the scatter chart. select the red dot(which is a failed transaction)
Then it will show the call tree that includes the exception.

**Comment by JasonRui** [comment]
It is exactly what I do, but i can not find any exception.
