### ISSUE TITLE
How to effectively extract application's exception information from collector?

### ISSUE THREAD

**Issue by fengnex** [naver/pinpoint#4525]
I want to extract application's exception from collector by using its class com.navercorp.pinpoint.collector.dao.hbase.HbaseTraceDaoV2, but SpanBo's below methods all return no any exception info even when there are real exceptions occur:
spanBo.hasException(), spanBo.getExceptionMessage(),spanBo.getExceptionClass(), spanBo.getErrCode()

So my question is how to application's exception message?

Collector seems a better place than web for such requirements, any response will be appreciated, thanks firstly.

**Comment by fengnex** [comment]
have found a way

**Comment by fengme** [comment]
Where and how do you prefer to extract such info?
It should be lightweight & quick

I hope to know your solution and will be concern the topic later, thanks.

**Comment by fengme** [comment]
It'e would be much better if we can get corresponding exception url, method, class name, etc.
