### ISSUE TITLE
why i can't get 'Pinpoint-TraceID' in header?

### ISSUE THREAD

**Issue by ITGrocery** [naver/pinpoint#4531]
In my company , we hope sending 'Pinpoint-TraceID' and request body to ELK,but i cann't get any pinpoint's header i d.What shouldo? Can you give me some suggestion?
Our application has been traced by pinpoint,we can see request record on pinpoint.

**Comment by Xylus** [comment]
Hi @ITGrocery 
Not sure if this is what you're looking for, but if you're using Tomcat, you could try setting `profiler.tomcat.hidepinpointheader=false` (default is true) in *pinpoint.config* file.

**Comment by ITGrocery** [comment]
Thanks,I see the profile of 'profiler.tomcat.hidepinpointheader' is false in my agent.
