### ISSUE TITLE
sqlserver jdbc didn't find in plugins

### ISSUE THREAD

**Issue by stoneLee81** [naver/pinpoint#4537]
pinpoint 1.7.3
In my project, the dubbo service connect to mysql & sqlserver databases, the mysql part showed in webui correctly, but sqlserver part didn't find in webui.
I didn't see the sqlserver jdbc in plugin, is that mean it didn't support it right now?

**Comment by Xylus** [comment]
Hi @stoneLee81 
There is a plugin for jtds java driver, but not for mssql-jdbc.
If you're using mssql-jdbc, then it isn't supported.
If you're using jtds, please provide us with the full agent DEBUG log.

**Comment by stoneLee81** [comment]
I used mssql-jdbc
