### ISSUE TITLE
how to query CallStack by transactionId in pinpoint-web 

### ISSUE THREAD

**Issue by LifeFly** [naver/pinpoint#4540]
in pinpoint-web  which page can query CallStack by transactionId?

**Comment by koo-taejin** [comment]
There is no page that can display information only with TransactionId.
This is because TransactionId alone can not display the desired information completely.

thanks.

**Comment by koo-taejin** [comment]
Unfortunately, We do not plan now.
It would be really nice if you developed and request it to us.

thanks.
