### ISSUE TITLE
Can application name contain special characters? such as @,#,$,%,*.......

### ISSUE THREAD

**Issue by hustcxx** [naver/pinpoint#4541]
When we configure on Tomcat or webShpere ,Can application name contain special characters? such as @,#,$,%,*.......

**Comment by koo-taejin** [comment]
Pinpoint's applicationName doest not support special characters.(character you mentioned)
Pinpoint's applicationName only support [a-zA-Z0-9], '.', '-', '_' character.

thanks.

**Comment by hustcxx** [comment]
How about application name length?

**Comment by hustcxx** [comment]
Thanks
