### ISSUE TITLE
My application run in docker , and in the pinpoint-web ,field "Cliend Ip " is docker's ip,why ?? isn't should be the request client ip?

### ISSUE THREAD

**Issue by hustcxx** [naver/pinpoint#4549]
My application run in docker ,and in the pinpoint-web ,field "Cliend Ip " is docker's ip,why ?? isn't should be the request client ip?
when my application doesn't run in the docker , in the pinpoint-web ,field "Cliend Ip " is the request client ip?

**Comment by koo-taejin** [comment]
hi @hustcxx 
Please check that proxy server accepts the request
If so, please adjust the * .realipheader options in your pinpoint.config.

thanks.

**Comment by hustcxx** [comment]
I should config the *.ealipheader option with  'X-Forwarded-For' or 'X-Real-IP' or all of two?

**Comment by koo-taejin** [comment]
Put the value for your environment.
