### ISSUE TITLE
local build fail with mvn clean install -Dmaven.test.skip=true

### ISSUE THREAD

**Issue by aximo** [naver/pinpoint#4555]
**What version of pinpoint are you using?**
master/1.8.0-SNAPSHOT

**Describe the bug**
build error if mvn clean install -Dmaven.test.skip=true

**What did you do to trigger the bug?**
Steps to reproduce, for example:
1.  git clone master br
2.  mvn clean install -Dmaven.test.skip=true
3. Failure to find com.navercorp.pinpoint:pinpoint-rpc:jar:tests:1.8.0-SNAPSHOT

**Expected behavior**
 mvn clean install -Dmaven.test.skip=true should be success in local build

**Logs**
```
[INFO] Reactor Summary:
[INFO]
[INFO] pinpoint 1.8.0-SNAPSHOT ............................ SUCCESS [  1.823 s]
[INFO] pinpoint-annotations ............................... SUCCESS [  3.018 s]
[INFO] pinpoint-commons ................................... SUCCESS [  9.292 s]
[INFO] pinpoint-thrift .................................... SUCCESS [  8.383 s]
[INFO] pinpoint-bootstrap-core ............................ SUCCESS [  5.334 s]
[INFO] pinpoint-bootstrap ................................. SUCCESS [  1.907 s]
[INFO] pinpoint-rpc ....................................... SUCCESS [  3.675 s]
[INFO] pinpoint-profiler .................................. FAILURE [  0.137 s]
[INFO] pinpoint-commons-hbase ............................. SKIPPED
[INFO] pinpoint-commons-server ............................ SKIPPED
[INFO] pinpoint-profiler-test ............................. SKIPPED

...

[ERROR] Failed to execute goal on project pinpoint-profiler: Could not resolve dependencies for project com.navercorp.pinpoint:pinpoint-profiler:jar:1.8.0-SNAPSHOT: Failure to find com.navercorp.pinpoint:pinpoint-rpc:jar:tests:1.8.0-SNAPSHOT 
```

I think you can move test codes in pinpoint-rpc to a new project , and then package as standard jar, and than depended by pinpoint-rpc/pinpoint-profiler

**Comment by koo-taejin** [comment]
please execute command `mvn clean install -DskipTests=true`

**Comment by aximo** [comment]
ok.
detail reason:
https://stackoverflow.com/questions/21933895/what-is-the-difference-between-dmaven-test-skip-exec-vs-dmaven-test-skip-tr

thanks @koo-taejin
