### ISSUE TITLE
What is different about this two method?

### ISSUE THREAD

**Issue by chuanyi-fang** [naver/pinpoint#4562]
In the class 'AgentStatController':
method:① getAgentStat ② getAgentStatChart
‘getAgentStatChart’ is used in the Application performance monitor page.
I don't know where to use the method of "getAgentStat ".
by the way ,where to use the method of "getAgentStatChartList"?

**Comment by Xylus** [comment]
Hi @chuanyi-fang 
One returns raw data points, and the other returns them in a format expected by the stat charts.
`getAgentStat()` isn't currently in use from the UI.
`getAgentStatChartList()` is used for data source chart.

**Comment by chuanyi-fang** [comment]
Is it fuIl gc that 'gcOldCount' in the class 'JvmGcBo'?

**Comment by Xylus** [comment]
Yup
