### ISSUE TITLE
How does TraceContext works?

### ISSUE THREAD

**Issue by JasonRui** [naver/pinpoint#4563]
Hi, I am studying the source code of Pinpoint. And I am confused by how ***TraceContext*** works.

First, is ***TraceContext*** related to a Thread? I mean using ThreadLocal.

Second, I know ***TraceContext*** is injected into methods that we try to profile. I am wondering How ***TraceContext*** is initialized?

**Comment by Xylus** [comment]
Hi @JasonRui 

**TraceContext** (in it's default implementation) manages traces via thread local, so while **TraceContext** isn't directly related to any one thread, it does provide an API to retrieve traces from a particular thread via the thread local.

**TraceContext** is a singleton, initialized when the agent starts up (through **TraceContextProvider**). The same **TraceContext** instance is injected into all the different interceptors. The interceptors will then ask this **TraceContext** object for traces stored in their executing thread's thread local.
