### ISSUE TITLE
the server map was error when the web server and database have the same name

### ISSUE THREAD

**Issue by zfaster** [naver/pinpoint#4574]
**What version of pinpoint are you using?**
v1.7.3

**Describe the bug**
when the tomcat and mysql have the same name ,the real time chart can not show , and select the server will location at mysql

**Expected behavior**
when select real time can show the real time chart on the server

**Screenshots**

![error](https://user-images.githubusercontent.com/8341790/44971209-4e114300-af87-11e8-9c24-d9f817025d32.png)

**Comment by koo-taejin** [comment]
hi @zfaster 

I did not understand your issue exactly.

1. If the names of tomcat and mysql are the same, does real time not work?
2. If mysql is clicked when tomcat and mysql have the same name, does realtime not work?

thanks.

**Comment by zfaster** [comment]
@koo-taejin 
the problem is If the names of tomcat and mysql are the same, does real time not work。
when I click real time button， will auto focus the mysql
I make a radio

[20180903_205204.zip](https://github.com/naver/pinpoint/files/2345606/20180903_205204.zip)

**Comment by zfaster** [comment]
@denzelsN  thank you I fixed it
