### ISSUE TITLE
How to change Realtime Active Thread Chart's default lable

### ISSUE THREAD

**Issue by ryshhxq** [naver/pinpoint#4584]
![image](https://user-images.githubusercontent.com/40416536/45080571-1f829c00-b130-11e8-82d2-d1536a405b1c.png)

How to change Realtime Active Thread Chart's default lable?
Default lable is 1s,3s,5s,Slow
I am want to change to 2s,4s,6s,Slow

thanks

**Comment by RoySRose** [comment]
Hello, @ryshhxq 

Changing the criteria of duration for transaction latency is not supported.
