### ISSUE TITLE
How to understand the FGC in Heap Usage chart

### ISSUE THREAD

**Issue by chuanyi-fang** [naver/pinpoint#4591]
How to understand the FGC in Heap Usage chart or PermGen Usage chart？
Is this FGC the same with the JVM‘s  FGC？And how to caculate  the FGC count and time in Heap Usage chart ？

![image](https://user-images.githubusercontent.com/20055737/45146572-bfeec400-b1f5-11e8-90b8-4603fb206d52.png)
I don't understand the mean about the image's FGC tip.

**Comment by Xylus** [comment]
Hi @chuanyi-fang 
The FGC is the same as JVM's FGC.
The Heap Usage chart will show them as orange bars like below:
![image](https://user-images.githubusercontent.com/10057488/45193732-8025ec00-b28a-11e8-9da4-2eb4bb081dbc.png)

**Comment by chuanyi-fang** [comment]
I found the FGC（shown in the heap usage chart）is sampling from the gcOldCount or gcOldTime (in the class JvmGcBo) by the method under .So i  think the FGC isn't the same as JVM's FGC.

----------------------------------------------------------------------------------------------------------------
/**
 * @author HyunGil Jeong
 */
@Component
public class **JvmGcSampler** implements AgentStatSampler<JvmGcBo, SampledJvmGc> {

    private static final DownSampler<Long> LONG_DOWN_SAMPLER = DownSamplers.getLongDownSampler(SampledJvmGc.UNCOLLECTED_VALUE);

    @Override
    public SampledJvmGc **sampleDataPoints**(int timeWindowIndex, long timestamp, List<JvmGcBo> dataPoints, JvmGcBo previousDataPoint) {
        JvmGcType jvmGcType = JvmGcType.UNKNOWN;
        List<Long> heapUseds = new ArrayList<>(dataPoints.size());
        List<Long> heapMaxes = new ArrayList<>(dataPoints.size());
        List<Long> nonHeapUseds = new ArrayList<>(dataPoints.size());
        List<Long> nonHeapMaxes = new ArrayList<>(dataPoints.size());
        List<Long> gcOldCounts = new ArrayList<>(dataPoints.size());
        List<Long> gcOldTimes = new ArrayList<>(dataPoints.size());
        // dataPoints are in descending order
        JvmGcBo previousBo = previousDataPoint;
        for (int i = dataPoints.size() - 1; i >= 0; --i) {
            JvmGcBo jvmGcBo = dataPoints.get(i);
            jvmGcType = jvmGcBo.getGcType();
            if (jvmGcBo.getHeapUsed() != JvmGcBo.UNCOLLECTED_VALUE) {
                heapUseds.add(jvmGcBo.getHeapUsed());
            }
            if (jvmGcBo.getHeapMax() != JvmGcBo.UNCOLLECTED_VALUE) {
                heapMaxes.add(jvmGcBo.getHeapMax());
            }
            if (jvmGcBo.getNonHeapUsed() != JvmGcBo.UNCOLLECTED_VALUE) {
                nonHeapUseds.add(jvmGcBo.getNonHeapUsed());
            }
            if (jvmGcBo.getNonHeapMax() != JvmGcBo.UNCOLLECTED_VALUE) {
                nonHeapMaxes.add(jvmGcBo.getNonHeapMax());
            }

            if (previousBo != null) {
                // Technically, this should not be needed as data should already be partitioned by their agent start
                // timestamp and should only contain data from a single jvm life cycle.
                // Added to maintain backwards compatibility for data that do not have agent start timestamp.
                if (checkJvmRestart(previousBo, jvmGcBo)) {
                    if (isGcCollected(jvmGcBo)) {
                        gcOldCounts.add(jvmGcBo.getGcOldCount());
                        gcOldTimes.add(jvmGcBo.getGcOldTime());
                    } else {
                        jvmGcBo.setGcOldCount(0L);
                        jvmGcBo.setGcOldTime(0L);
                    }
                } else {
                    if (isGcCollected(jvmGcBo) && isGcCollected(previousBo)) {
                        gcOldCounts.add(jvmGcBo.getGcOldCount() - previousBo.getGcOldCount());
                        gcOldTimes.add(jvmGcBo.getGcOldTime() - previousBo.getGcOldTime());
                    } else {
                        if (!isGcCollected(jvmGcBo)) {
                            jvmGcBo.setGcOldCount(previousBo.getGcOldCount());
                            jvmGcBo.setGcOldTime(previousBo.getGcOldTime());
                        }
                    }
                }
            } else {
                if (isGcCollected(jvmGcBo)) {
                    if (timeWindowIndex > 0) {
                        gcOldCounts.add(jvmGcBo.getGcOldCount());
                        gcOldTimes.add(jvmGcBo.getGcOldTime());
                    } else {
                        gcOldCounts.add(0L);
                        gcOldTimes.add(0L);
                    }
                }
            }
            previousBo = jvmGcBo;
        }
        SampledJvmGc sampledJvmGc = new SampledJvmGc();
        sampledJvmGc.setJvmGcType(jvmGcType);
        sampledJvmGc.setHeapUsed(createSampledPoint(timestamp, heapUseds));
        sampledJvmGc.setHeapMax(createSampledPoint(timestamp, heapMaxes));
        sampledJvmGc.setNonHeapUsed(createSampledPoint(timestamp, nonHeapUseds));
        sampledJvmGc.setNonHeapMax(createSampledPoint(timestamp, nonHeapMaxes));
        sampledJvmGc.setGcOldCount(createSampledPoint(timestamp, gcOldCounts));
        sampledJvmGc.setGcOldTime(createSampledPoint(timestamp, gcOldTimes));
        return sampledJvmGc;
    }
......

**Comment by Xylus** [comment]
**JvmGcBo**'s `gcOldCount` and `gcOldTime` hold the gc count and time that happened in the agent's JVM.
So the chart does show the agent JVM's gc count and time. Is this not what you were asking?

**Comment by chuanyi-fang** [comment]
Yes,
And i think JvmGcBo's gcOldCount and gcOldTime are Minor GC or Major GC,not the JVM's FULL GC.
Is it right about what i think?

**Comment by Xylus** [comment]
Yeh, that is actually a very good point.
They're gc counts from old so Major GC would technically be correct. I can definitely see how labeling them as Full GC would be confusing.
I think we should change the label to Major GC.
Thanks for reporting!

**Comment by chuanyi-fang** [comment]
Above the code I pasted,I can't understand the class JvmGcSampler' method "sampleDataPoints" is why to sample the gcOldCount and gcOldTime like this.

**Comment by Xylus** [comment]
It was done this way to cover cases where 1) the agent has been restarted (even multiple times) within the time period, and 2) multiple agents with the same agent id are running.
Add all this to the fact that older pinpoint agents did not send agent startTimestamp and we had to maintain backwards compatibility.

**Comment by chuanyi-fang** [comment]
Is pinpoint-agent to get gcOldCount and gcOldTime by "jstat"?
so gcOldCount and gcOldTime are  Cumulative,Is it right?

**Comment by Xylus** [comment]
No, the agent queries **GarbageCollectorMXBean** for gcOldCount and gcOldTime.
And yup, gcOldCount and gcOldTime are cumulative.
