### ISSUE TITLE
what the mean of startTimestamp in the class of JvmGcB

### ISSUE THREAD

**Issue by ZhibingYu** [naver/pinpoint#4592]
1、what the mean of startTimestamp in the class of JvmGcB.

![image](https://user-images.githubusercontent.com/18696409/45149433-1a8b1e80-b1fc-11e8-8b0d-86d355a89efc.png)

2、what the mean  of the method checkJvmRestart in the class of JvmGcSampler.

![image](https://user-images.githubusercontent.com/18696409/45149726-d5b3b780-b1fc-11e8-9f39-569cbeb67a20.png)

**Comment by Xylus** [comment]
Hi @ZhibingYu 
1. startTimestamp is the timestamp of when the agent started.
2. The method checks if the jvm has restarted between the 2 **JvmGcBo**s.

**Comment by ZhibingYu** [comment]
Due to agent startup is activated by application, Is the timestamp of when the agent stated the same of the timestamp of when the application stated?

**Comment by Xylus** [comment]
Mostly yes, the timestamp is taken during agent startup, right before the application's main is called.
