### ISSUE TITLE
Custom plugin not shown in the picture

### ISSUE THREAD

**Issue by koala775** [naver/pinpoint#4594]
As follows , the custom plugin data is collected
![image](https://user-images.githubusercontent.com/35438579/45153745-a5254b00-b207-11e8-9234-72d54808285a.png)
but , the plugin don't display in the following picture
![image](https://user-images.githubusercontent.com/35438579/45153997-9b501780-b208-11e8-9307-b440db1242b7.png)

**Comment by Xylus** [comment]
Hi @koala775 
Please check [this section](http://naver.github.io/pinpoint/plugindevguide.html#23-methods-invoking-a-remote-node) in our plugin developer guide.
