### ISSUE TITLE
AKKA HTTP Plugin don't send traces

### ISSUE THREAD

**Issue by ofauchon** [naver/pinpoint#4601]
**What version of pinpoint are you using?**
1.8.0-RC1 

**Describe your problem**

I can't get traces when using pinpoint agent on Akka HTTP Server.

**What have you done?**

1. Installed pinpoint 1.8.0-RC1 Web and Collector
2. Installed pinpoint 1.8.0-RC1 on target server
3. Add javaagent on HTTP AKKA Server :

export JAVA_OPTS="-javaagent:/opt/pinpoint/pinpoint-1.8.0-RC1/pinpoint-bootstrap-1.8.0-RC1.jar -Dpinpoint.agentId=SERVER01  -Dpinpoint.applicationName=APP01"

** Result **

- Pinpoint agent register correctly on pinpoint collector/web.
- No traces are sent to server. 

Thanks for your help. 

Olivier Fauchon

**Comment by koo-taejin** [comment]
hi @ofauchon 

If you could post your agent log which related AKKA HTTP that would help as well.

thanks.
