### ISSUE TITLE
about the gap time

### ISSUE THREAD

**Issue by zxfxpower** [naver/pinpoint#4603]
Guys ，I have a question about the gap time。
I understand what's gap time it is ,but I don't understand how it occur
for example：the gap time  between method A and  method B is 10 seconds, then what happened in that 10 seconds  ? it's synchronize lock? but i can't find  any synchronize lock, anything else?

**Comment by RoySRose** [comment]
Hello @zxfxpower, 
asynchronous could be the answer

**Comment by zxfxpower** [comment]
Hi @RoySRose 
Thanks for  you answer, but I don't find any asynchronous code ,it's all  sequence execute ,can you give an example ,please !

**Comment by RoySRose** [comment]
@zxfxpower 
asynchronous invocation was one of an example.
To clarify the term 'GAP', click on the `question mark` on the top right corner of the call stack.
Also, you should find what results the `gap` in your application. I can't find it for you.

**Comment by zxfxpower** [comment]
@RoySRose 
is it pinpoint miss asynchronous invocation call stack?

**Comment by RoySRose** [comment]
@zxfxpower 
If you are using the 1.8.0+ then pinpoint will probably trace asynchronous invocation calls
