### ISSUE TITLE
How to disable pinpoint-web to load online google front-end resources in intranet

### ISSUE THREAD

**Issue by ganpengyu** [naver/pinpoint#4622]
Pinpoint Web need to load some front-end resources from google，but pinpoint can not connect to internate in intranet enviroment. This cause the web page can not load success. How can I disable pinpoint web to load these online resources.

**Comment by denzelsN** [comment]
@ganpengyu  HI~
Modify the following options in the pinpoint-web.properies file:
`config.sendUsage=false`
The resource will be requested, but the page will be loaded.
