### ISSUE TITLE
application did not be traced

### ISSUE THREAD

**Issue by yale2** [naver/pinpoint#4623]
**What version of pinpoint are you using?**
pinpoint1.6.2

**Describe your problem**
when I start agent correctly,there is nothing shows in web UI. but I had send request locally

**What have you done?**
Steps you have taken to trigger the problem, for example:
1. start agent with 1.6.2
2. send a request from chrom .call my local service
3. nothing shows in web UI
4.my application is springboot project.but it is shown with image below.is there any configuration i should set?

**Screenshots**
![_20180914181105](https://user-images.githubusercontent.com/16750655/45544323-93682700-b849-11e8-9bcb-260022e3332b.png)

**Logs**
If applicable, please attach agent/collector/web DEBUG log that includes the part where you have 
no error log

**Comment by koo-taejin** [comment]
@yale2 
Take a look at our [FAQ](https://naver.github.io/pinpoint/faq.html#my-custom-jar-application-is-not-being-traced-help) on this.
