### ISSUE TITLE
how to output transactionId in my log

### ISSUE THREAD

**Issue by yale2** [naver/pinpoint#4626]
I want to associate a transaction with pinpoint. but in my application. I can't perceive which transaction it belongs. so I think I can output transactionId in my log ,and then ,I can associate a transaction with ELK. so, I can do this in before and after method of a plugin?

**Comment by minwoo-jung** [comment]
Hi @yale2 
This document will be helpful to you.
Please [this guide](https://github.com/naver/pinpoint/blob/master/doc/per-request_feature_guide.md)

**Comment by yale2** [comment]
@minwoo-jung  thanks!

**Comment by minwoo-jung** [comment]
@yale2 
Can you explain it more detail?
- show me the log4j.xml file
- show your logging code in your java class.
- log4j library version.

And 
I recommand to see your pinpoint agent log.

**Comment by yale2** [comment]
@minwoo-jung 
the project I use log4j with springboot is ok.this project is as dubbo consumer.
another project I use logback. but it not work fine. the TxIds and SpanIds in the log file are all null.
here is my configuration info

logback.xml

![logback](https://user-images.githubusercontent.com/16750655/45673536-7f7c3800-bb5d-11e8-8f9e-2eef0bcf1cf7.png)

application log

![log](https://user-images.githubusercontent.com/16750655/45673603-bb170200-bb5d-11e8-8d58-a7b01a7588c8.png)

when a request send to my application.the TxId and SpanId are both null.

**Comment by minwoo-jung** [comment]
DefaultPinpointClientHandler, PacketDecoder, UdpDataSender class are not correlated with [Per-request logging](https://github.com/naver/pinpoint/blob/master/doc/per-request_feature_guide.md). 
DefaultPinpointClientHandler, PacketDecoder, UdpDataSender logic execute in a different thread.

did you set this configuration?
```
###########################################################
# logback (guide url : https://github.com/naver/pinpoint/blob/master/doc/per-request_feature_guide.md)
###########################################################
profiler.logback.logging.transactioninfo=true
```

**Comment by yale2** [comment]
@minwoo-jung 
* yes,I set both log4j.transactioninfo and logback.transactioninfo=true

**Comment by minwoo-jung** [comment]
Can you explain it more detail?
- show me the logback.xml whole file, 
- show your logging code in your java class.
- logback.xml library version.
- explan using WAS, platform.

**Comment by yale2** [comment]
@minwoo-jung 

* logback.xml
> <configuration>
         <property name="APP_NAME" value="base" />
         <property name="LOG_MAX_HISTORY" value="30" />
         <property name="LOG_APP_NAME“ value="${APP_NAME}/app" />
         <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender" >
              <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoding">
                   <pattern>%d{yyyy-MM-dd HH:mm:SS} [%thread] %-5level %logger{50} [TxId:%X{PtxId} 
                      ,SpanId:%X{PspanId}] - %msg%n</pattern>
        .........
    <root level="DEBUG">
          <appender-ref ref="APP" />
          <appender-ref ref="STDOUT" />
    </root>
* I don't have any logging code in my java class.
* my logback library version is 1.2.3.My project is spring boot .I use maven provided
* my workging machine has no internet. there is some security management. so I can't provide the log 
  file. It's just logging TxId and SpanId in each log.but has no value.

THANKS!

**Comment by minwoo-jung** [comment]
I recommend that you see your agent log.
You should find warning log message for [LogbackPlugin](https://github.com/naver/pinpoint/blob/master/plugins/logback/src/main/java/com/navercorp/pinpoint/plugin/logback/LogbackPlugin.java).
If you find warning message. show me that.

And check your sampling rate in pinpoint.config file. 
```
profiler.sampling.rate=1
```

**Comment by yale2** [comment]
@minwoo-jung 
I saw logbackplugin put TxId and SpanId into MDC when I run my application in debug mode. and logbackplugin has info log message:
> LogbackPlugin config:LogbackConfig [logbackLoggingTransactionInfo=true]

and there is no warning log message in my log file.

**Comment by yale2** [comment]
@minwoo-jung 
I had found where I am wrong.
there must have logging message in my java class.then the feature works.I think this feature is useless for me. what I want is that I don't need to logging anything in my application.agent help me logging transactionId in  each request. do you have any idea?

**Comment by minwoo-jung** [comment]
I don't get what you mean.
