### ISSUE TITLE
can pinpoint  support weblogic?

### ISSUE THREAD

**Issue by cornyu** [naver/pinpoint#4636]
pinpoint now support list:
Tomcat 6/7/8, Jetty 8/9, JBoss EAP 6, Resin 4, Websphere 6/7/8, Vertx 3.3/3.4/3.5
• Spring, Spring Boot (Embedded Tomcat, Jetty)

**Comment by jaehong-kim** [comment]
@cornyu 
https://github.com/naver/pinpoint/tree/master/plugins/weblogic
