### ISSUE TITLE
Proxy monitoring using HTTP headers

### ISSUE THREAD

**Issue by NiLtheGazettE** [naver/pinpoint#4637]
after i add this configure into my httpd.conf ,i don't see the PROXY(xxx)  in the blow png
httpd.conf

<IfModule mod_jk.c>
...
RequestHeader set Pinpoint-ProxyApache "%t %D %i %b"
...
</IfModule>

![image](https://user-images.githubusercontent.com/42824562/45671975-84d78380-bb59-11e8-9728-d52fffeb9c74.png)

**Comment by jaehong-kim** [comment]
@NiLtheGazettE 
Has the HTTP header been added ?
Proxy monitoring requires an HTTP header(Pinpoint-ProxyApache).
