### ISSUE TITLE
How to specify proper agentId for applications running with docker and managedby k8s?

### ISSUE THREAD

**Issue by fengnex** [naver/pinpoint#4638]
You know there are more and more such applications:
1. Running in a docker container
2. K8s manages and might dispatch them anywhere & anytime

So we may want to know: 
How to respectively set proper agentId for different instances of certain application, otherwise one application's all instance will have the same agentId!

**Comment by fengnex** [comment]
PP's server-side applications, including web and collector, both run natively on Linux and are not releated with docker, ONLY pp's agents run within a docker container.

**Comment by fengnex** [comment]
@Xylus Thanks a lot, v1.6.2 is my pp server's version, would be so kind as to explain how to configure it in detail for the agent application?

**Comment by Xylus** [comment]
@fengnex 
Please bear in mind that I can't (and shouldn't) tell you how you should set your agent ids as this is something that you will have to decide.
All I can do is simply give some ideas as to how you might be able to configure your agent ids so that they don't produce duplicates.
One of them could be to take a look at the downward API, and choose some values to expose as environment variables. Then you can use those env variable to configure the agent id.

**Comment by dawidmalina** [comment]
I also interested in this topic as i didn't found solution for multiple replicas where you configure only single deployment. Issue that i have is https://github.com/naver/pinpoint/issues/3504

**Comment by dawidmalina** [comment]
I was trying to use pod name or pod id but the value is too long.

**Comment by fengnex** [comment]
@dawidmalina thx, and could you please introduce how you set different agentIds for different instances respectively?

I wonder if it is really necessary to manually set the ID for user,  and why the value cannot be generated automatically? Can anyone explain it?

**Comment by dawidmalina** [comment]
I did it via downward API but the problem is that in my case pod name or pod id are too long and agent will not start because of agent id limit. It's working with `replicas: 1` and short name provided manually.

**Comment by Xylus** [comment]
Could you do something like this to have different replicas have different agent id?
```
# if HOSTNAME or pod name(?) is "my-web-service-6cd47d4f78-sn2w9"

AGENT_ID_PREFIX="my-web"
AGENT_ID_SUFFIX="$(echo $HOSTNAME | rev | cut -d'-' -f-2 | rev)"
AGENT_ID="$AGENT_ID_PREFIX-$AGENT_ID_SUFFIX"

# AGENT_ID would then be "my-web-6cd47d4f78-sn2w9"
```
Though with the 24 character limit, **AGENT_ID_PREFIX** would be limited to 7 characters.
I don't know the exact spec for how the pod name(?) is generated, but if you feel like you can get away with just using `-sn2w9` then **AGENT_ID_PREFIX** could be longer - `my-web-service-sn2w9`.

**Comment by xiaofeng886521** [comment]
> You know there are more and more such applications:
> 
> 1. Running in a docker container
> 2. K8s manages and might dispatch them anywhere & anytime
> 
> So we may want to know:
> How to respectively set proper agentId for different instances of certain application, otherwise one application's all instance will have the same agentId!

兄弟这个问题解决了么

**Comment by xiaofeng886521** [comment]
解决了，但是是临时的 哈哈！ 我用传参的方式搞定的，例如把生成agentid的脚本和主命令写进shell里面用copy到镜像里  用entrypoint启动  shell脚本里面定义几个参数 $1 $2 等等  用k8s的command传参

**Comment by Xylus** [comment]
@xiaofeng886521 @dawidmalina @fengnex 
Would there be a fixed spec for pod names/ids? As in a guarantee that they'll be at most certain number of characters in length?
What we could do temporarily would be to increase the current limit of 24 characters for agent ids to something that could work with kubernetes.
Let me know what you all think.

**Comment by dawidmalina** [comment]
From my side we can use id of the pod which for sure is unique. It is UUID string so we need 36 characters.

**Comment by zzzhangqi** [comment]
> 我用传参的方式搞定的，例如把生成agentid的脚本和主命令写进shell里面用到复制到使用里点entrypoint启动shell脚本里面定义几个参数$ 1 $ 2等等用k8s的命令传参

多个pod时，可以选择取值pod的hostname。
我想问兄弟，你是怎么在k8s里部署起来的server端。
