### ISSUE TITLE
Update newly developed UI source

### ISSUE THREAD

**Issue by denzelsN** [naver/pinpoint#4640]
Redesign all UI code using new design and latest Angular Framework
 * support Angular 6
 * support vis.js
 * remove amcharts

**Comment by fengnex** [comment]
wonder when can it be finished?

**Comment by denzelsN** [comment]
@fanyeren 
You can test it now.
https://naver.github.io/pinpoint/ui_v2.html

**Comment by fengnex** [comment]
The actual contents in essence seem the same with those old versions' and could you please those main improvements, for example performances, etc?

I think many people may want to see comprehensive query including querying and analyzing all kinds of quality &  exception data across projects.

**Comment by denzelsN** [comment]
@fengex Thanks for your feedback
Although the new UI looks similar to what we had before, the entire client-side code has been rewritten.
It was getting increasingly difficult to extract performance and incrementally add new features with the previous code base,
and this is why we have decided to rewrite the client-side UI code (though we are still developing/testing it).

While this isn't immediately adding anything new feature-wise, we will able to add new features (such as those you've mentioned) and extract client-side performance more easily and a lot faster using the new code base going forward.
