### ISSUE TITLE
the Pinpoint-ProxyApp header if contains chinese name the show will error

### ISSUE THREAD

**Issue by zfaster** [naver/pinpoint#4647]
**What version of pinpoint are you using?**
v1.7.3

**Describe the bug**
![no_decoder](https://user-images.githubusercontent.com/8341790/45743343-6099a680-bc2e-11e8-904c-60bc3d190362.png)

when I add Pinpoint-ProxyApp header the data was encoder,I think when show the data it should decoder first

**Comment by emeroad** [comment]
The pinpoint does not handle http header encoding. 
Take a look at the WAS settings.
 - The standard header encoding is ISO-8859-1
    https://tools.ietf.org/html/rfc5987
