### ISSUE TITLE
High availability for collector  & web 

### ISSUE THREAD

**Issue by imperio-wxm** [naver/pinpoint#4648]
In my cluster，just have one Tomcat for collector  and web，How to config for High availability？

I want to deploy another collector & web  on a different machine.

Like this:

![image](https://user-images.githubusercontent.com/8111349/45743967-e10cd700-bc2f-11e8-888e-e5c395931ade.png)

**Comment by koo-taejin** [comment]
hi @imperio-wxm 

Use a solution(l7, proxy server, etc...) that allows for load balancing for multiple servers. 

thanks.

**Comment by imperio-wxm** [comment]
@koo-taejin 

thanks!
