### ISSUE TITLE
Application list remove if application not use

### ISSUE THREAD

**Issue by imperio-wxm** [naver/pinpoint#4649]
agent config:
-Dpinpoint.agentId=xxxx
-Dpinpoint.applicationName=test01

At the first time I run application, `test01`  in application list on WEB UI. However when stop this app and  offline forever, application list still has `test01`, can not auto remove.

![image](https://user-images.githubusercontent.com/8111349/45745177-cdaf3b00-bc32-11e8-8705-2f9a6d514674.png)

**Comment by Xylus** [comment]
Hi @imperio-wxm 
Please check out this [FAQ](https://naver.github.io/pinpoint/faq.html#how-do-i-delete-application-name-andor-agent-id-from-hbase)

**Comment by imperio-wxm** [comment]
@Xylus Thx.
