### ISSUE TITLE
how to get method name from apiId in spring plugin

### ISSUE THREAD

**Issue by johnhill-xu** [naver/pinpoint#4663]
I found method before & after in class BeanMethodInterceptor inputs just a int value called apiId.  but we can trace the spring method name in the web.
Could you pls tell me where apiId transfer to the method name and how? thank you,

**Comment by Xylus** [comment]
Hi @johnhill-xu 
Method signatures are mapped to an id (*apiId*), cached, and sent over to the collector the first time a method is transformed.
Collector stores this information in **ApiMetaData** table, which the web then queries to reconstruct the method signature.
