### ISSUE TITLE
bidirectional 옵션

### ISSUE THREAD

**Issue by Ju-S** [naver/pinpoint#4664]
bidirectional옵션이 설명을 적혀있는데 선택할 수 있는 곳이 어딘지 찾지를 못하고 있습니다. 서버에서 따로 설정을 하고 재기동해야 하나요?

**Comment by Xylus** [comment]
안녕하세요,
Depth 옵션 우측 화살표를 누르시면 나오는 박스 하단, Cancel 버튼 왼쪽에 있습니다.

![image](https://user-images.githubusercontent.com/10057488/45855156-ad45c480-bd89-11e8-8f3a-4f50a3914eb5.png)
