### ISSUE TITLE
no main manifest attribute, in tools/pinpoint-tools-1.7.3.jar

### ISSUE THREAD

**Issue by reymont** [naver/pinpoint#4668]
**What version of pinpoint are you using?**
v1.7.3

**Describe the bug**
no main manifest attribute, in tools/pinpoint-tools-1.7.3.jar

**What did you do to trigger the bug?**
Steps to reproduce, for example:
1. java -jar tools/pinpoint-tools-1.7.3.jar pinpoint.config

**Comment by RoySRose** [comment]
Hello @reymont 
try to follow [this instruction](http://naver.github.io/pinpoint/troubleshooting_network.html#only-for-pinpoint-v173)
I think you need to include the path to the config file.

**Comment by reymont** [comment]
Hi @RoySRose, I assigned the absolute path to config. The result was the same.

$ java -jar pinpoint-tools-1.7.3.jar /c/workspace/java/pinpoint/pinpoint-agent-1.7.3/pinpoint.config
no main manifest attribute, in pinpoint-tools-1.7.3.jar

Then, I check the MANIFEST.MF. There is no `Main-Class:` attribute in the MANIFEST.MF of pinpoint-tools-1.7.3.jar.

**Comment by RoySRose** [comment]
Hello, @reymont 
I think there was a misunderstanding on the release.

Will you try to run the test with the existing shell script just like other versions as [this guide](http://naver.github.io/pinpoint/troubleshooting_network.html#testing-with-binary-release)

I think it would work.(I've tried it)

However, if you face a `command not founde 2` error while running the script.
please overwrite it with below text OR download the file(change .txt -> .sh after download)
[networktest.txt](https://github.com/naver/pinpoint/files/2444665/networktest.txt)
There is a line seperator problem in the included shell script in the release1.7.3.

```
#! /bin/bash

WORKING_DIR=$(dirname "$0")
cd -P "$WORKING_DIR"/.. > /dev/null

CL_PATH=$(find . -name '*.jar' | tr "\n" :)
echo "CLASSPATH=$CL_PATH"

java -classpath $CL_PATH com.navercorp.pinpoint.tools.NetworkAvailabilityChecker pinpoint.config
```

**Comment by reymont** [comment]
Hi, @RoySRose . Finally, i run it in linux successfully. This shell isn't compatible with mingw64(git bash) in windows.
