### ISSUE TITLE
How to get traceid and use it in log (log4j/log4j2)

### ISSUE THREAD

**Issue by sunface** [naver/pinpoint#4669]
Our developers wants do some manually collecting  with logs, so we need get the trace id first , and then output it  with log4j/log4j2,   is there a way to easily do this ,maybe like skywalker? : )

**Comment by Xylus** [comment]
Hi @sunface 
Is [this](http://naver.github.io/pinpoint/perrequestfeatureguide.html#per-request-logging) what you're looking for?

**Comment by sunface** [comment]
It seems very similar to what i want, here is another question: in which version has this feature been supported? we are now using 1.7.0-snapshot now

**Comment by Xylus** [comment]
Since 1.1.2 I think. You'll be able to use it with 1.7.0-SNAPSHOT.

**Comment by sunface** [comment]
That's really helpful , thanks :) . In this doc,  only shows configuration for log4j and logback，so what about log4j2?

**Comment by Xylus** [comment]
I don't think we have this supported for log4j2 unfortunately.
If you'd like to make the plugin for log4j2 to have it supported and throw us a PR, that would be fantastic :)
