### ISSUE TITLE
How to trace my own method？

### ISSUE THREAD

**Issue by imperio-wxm** [naver/pinpoint#4670]
Just like SkyWalking, I want make my own method A in the stack just using a annotation.

There is any way in pinpoint? Because I can not make lots of plugins for my applications.

https://github.com/apache/incubator-skywalking/blob/v5.0.0-RC2/docs/en/Application-toolkit-trace.md

**Comment by RoySRose** [comment]
Hello, @imperio-wxm 

There is no feature to add methods to the stack by annotation in Pinpoint.
You need to create a plug-in.
However, there is a [simple plug-in generator](https://github.com/bbossgroups/pinpoint-plugin-generate) contributed by bboss group, if you'd like to consider.

**Comment by Xylus** [comment]
@imperio-wxm 
As @RoySRose said, we don't provide annotations for it (don't have sdks yet).
But you can set `profiler.entrypoint` option in *pinpoint.config* to trace custom methods.

**Comment by imperio-wxm** [comment]
@RoySRose @Xylus 

Thanks.

I read doc and make my a plugin, also set `profiler.entrypoint` for my methods like this:

```java
My custom jar application is not being traced. Help!
Pinpoint Agent need an entry point to start off a new trace for a transaction. This is usually done by various WAS plugins (such as Tomcat, Jetty, etc) in which a new trace is started when they receive an RPC request. For custom jar applications, you need to set this manually as the Agent does not have knowledge of when and where to start a trace. You can set this by configuring profiler.entrypoint in pinpoint.config file.
```

However, I think these methods are not flexible enough.
If I make a new plugin or add a new method, I must copy jar to all machine then edit agent's config and restart all apps include pinpoint-web、pinpoint-collector.

There is any way like ZipKin, I can entry my own span to my code and it can be tracing and show on WEB UI.
In this way,I just compile my own app jar and deploy it, will not affect other services.

```java
brave.Span span = tracing.tracer().newChild(tracing.tracer().currentSpan().context());
span.name("test-span").start();
span.tag("test-key", "test-value");
span.tag("name", username);
long parentId = span.context().parentId();
long spanId = tracing.tracer().currentSpan().context().spanId();
long traceId = tracing.tracer().currentSpan().context().traceId();
long traceIdHigh = tracing.tracer().currentSpan().context().traceIdHigh();
String traceIdString = tracing.tracer().currentSpan().context().traceIdString();
span.tag("parentId", String.valueOf(parentId));
span.tag("spanId", String.valueOf(spanId));
span.tag("traceId", String.valueOf(traceId));
span.tag("traceIdHigh", String.valueOf(traceIdHigh));
span.tag("traceIdString", String.valueOf(traceIdString));
span.tag("mvc.controller.class", "BackendController");
span.tag("mvc.controller.method", "printlnTest");
span.annotate("Method In");
printlnTest();
span.annotate("Method Out");
span.finish();
```

![image](https://user-images.githubusercontent.com/8111349/46184835-fd80d180-c309-11e8-8a12-79cc97e55be3.png)
