### ISSUE TITLE
[Solved][#Detailed Troubleshooting] Server Map (main servermap) not showing connections/relations with other modules

### ISSUE THREAD

**Issue by elzeron** [naver/pinpoint#4673]
### **Solved**
The issue I was having was my hbase version. I confused pinpoint's **1.2** version for hbase **2.1** latest release. To check your hbase version you can run the command 
> hbase version

![hbase version](https://user-images.githubusercontent.com/16352338/46206766-79275200-c2fb-11e8-9f93-43e97293e984.jpg)

 or if your $PATH is not set
> $HBASE_PATH/bin/hbase

**Working system**
![pinpoint solved](https://user-images.githubusercontent.com/16352338/46206820-ab38b400-c2fb-11e8-9149-26930e0949e2.jpg)

Note how the servermap is working and both charts at the right are now active
Note also that I changed the web container's path to the application but it's not the solution, it's just an extra

_I would recommend an hbase version check for other dyslexic people like me :P_

### **Issue Post**
Hello there, I do also have the same issue as https://github.com/naver/pinpoint/issues/4111. I decided to make a new post in order to be able to present the info in a more organized manner

### **Description**
Whenever I  access to the application main page I cannot see the servermap relation or connections with other modules / services. I can only see the one "Tomcat" icon and that's all. Also notice how the **Response Summary** and **Load** charts at the right do not have any data either.

I'm having some javascript errors too in the browser console, I'm thinking about de-minifying it and checking the error line in the javascript file to add it to this post, but I'm not sure if that's the real problem (Although it could be helpful to get to the real issue now that I think about it)
**Update** The javascript error details is in the next post: **Update N°1**. The code has been unminified.

I'm Using Tomcat 8 on an Oracle Linux 7 (with SELinux disabled), java JDK 1.8 and pinpoint 1.8.0 with HBase 1.2. I also tried Pinpoint 1.7.3 (Collector and Web) with the same results. Same with the agents, tried 1.8.0 and 1.7.3 agents. The errors are all the same

Also I've been reading that https://github.com/naver/pinpoint/issues/4111 issue and I've checked both **ApplicationMapStatisticsCallee_Ver2** and **ApplicationMapStatisticsCaller_Ver2** tables, even though I'm not sure if I've done it correcly, they seem to have info in them (Screenshots below)
 
### **Here are some Screenshots...**

This is the general view of the servermap. As you can see There's no data / links
![onelogin1](https://user-images.githubusercontent.com/16352338/46078283-13f02700-c16a-11e8-827c-ae8562daa8c0.jpg)

However if I select from the top right chart a transaction and then I select the server map from that transaction I can see the map relations
![onelogin2](https://user-images.githubusercontent.com/16352338/46078369-59145900-c16a-11e8-9bf3-541793e3e085.jpg)

As you can see there's also javascript errors in the browser console in the main server map but not in the specific transaction server map

Also, I found out that in the main server map, whenever I right click and the menu pops out, if I select a "Link Routing" option then the "check" icon disappears and doesn't appear anymore no matter what I click, until I reload the page (F5)

First time loading the page the menu seems fine
![onelogin3](https://user-images.githubusercontent.com/16352338/46078501-c1fbd100-c16a-11e8-86ad-022f8f5ba7a2.jpg)

When I click any option in the **Link Routing**  sub-menu, let's say... **Orthogonal** (Just an example) then the "Check Icon" disappears but there's no errors nor in the application logs neither in the browser console log
![onelogin4](https://user-images.githubusercontent.com/16352338/46078565-eeafe880-c16a-11e8-9f12-b4be8e5a6144.jpg)

If I reload the page (F5) the menu loads fine again but still no server map links
![onelogin3](https://user-images.githubusercontent.com/16352338/46078593-00918b80-c16b-11e8-9049-1381b9f78351.jpg)

ApplicationMapStatisticsCallee_Ver2
![applicationmapstatisticscallee_ver2](https://user-images.githubusercontent.com/16352338/46080540-97ad1200-c170-11e8-81fb-3af56a030498.jpg)

ApplicationMapStatisticsCaller_Ver2
![applicationmapstatisticscaller_ver2](https://user-images.githubusercontent.com/16352338/46080558-9e3b8980-c170-11e8-9dc7-a408cf76606f.jpg)

### **About Logs (Updated)**
The uploaded *.zip* logs consist in the Collector + Web + Whole Environment (Tomcat) logs while the Agent's log just consist in the single agent log.

**Collector Logs**
[Collector Logs.zip](https://github.com/naver/pinpoint/files/2420415/Collector.Logs.zip)
Structure
![collector log structure](https://user-images.githubusercontent.com/16352338/46087904-ac45d600-c181-11e8-8025-e4bb22afcbb7.jpg)
The main DEBUG logs should be located at the **catalina.out** file

**Agent Logs**
[Agent Logs.zip](https://github.com/naver/pinpoint/files/2420389/Agent.Logs.zip)
Structure
![agent log structure](https://user-images.githubusercontent.com/16352338/46088108-18c0d500-c182-11e8-80a8-8cb51eb5e5fd.jpg)
The Agent's log consist in just that file

**Keep in mind** that the logs **start** at the same time frame, but they may not end at the same time. Also keep in mind that the Agent's down time at the start of the log is due to the restart of the collector's system

### **Conclusion**
We are forced to deploy a big distributed system and this tool will help us understand how it works and fix any errors found in them but unfortunately we don't have the system developer's support due to internal fights (I know it's a lot of effort but this is part of our job so we **have** to do it). 
We are willing to comply until this error is solved. We really need this to be working to help us do our job more efficiently (and by "we" I mean just 2 guys haha). Any questions or additional info you need just let me know

**Comment by Xylus** [comment]
Hi @elzeron 
Thank you for your detailed explanation and analysis.

What is your hbase server (not the client) version?
I ask because your Hbase UI looks like it's from 2.x, and pinpoint officially only supports hbase 1.2.x. (https://github.com/naver/pinpoint#compatibility)

Just to make sure, I've tried running pinpoint (which uses hbase client 1.2.6) on hbase server 2.0.2 and was able to reproduce your exact issue.
(Maybe it's got something to do with `Table.increment(...)` API as this is what those 3 tables have in common?)
Either way, since hbase does not ensure compatibility over major version changes, please use hbase 1.2.x if you're using 2.x for your hbase installation.

Thanks.

**Comment by elzeron** [comment]
Thanks @Xylus for taking the time to analyze the issue. You saved us a lot of more days trying to figure it out, and now we can use this system to analyze the structure of our systems.
Do you think that an hbase version check on the web module would be useful?
Anyways I'm closing the issue with all the required steps to solve it for future users.

**Comment by Xylus** [comment]
@elzeron 
Glad it worked out. Thanks for taking the time to detail out your issue and share your troubleshooting efforts.
