### ISSUE TITLE
UDP bad length issue

### ISSUE THREAD

**Issue by arkyhuang** [naver/pinpoint#4675]
**What version of pinpoint are you using?**
master/v1.7.3/

**Describe your problem**
As deployed pinpoint collector, web and agent, we can not check data for the trace.
There is one issue displayed in tcpdump from collector as below:
16:45:04.468271 IP (tos 0x0, ttl 63, id 51771, offset 0, flags [+], proto UDP (17), length 1500)
    <ip>.50988 > pinpoint-server.net.palace-4: UDP, bad length 1993 > 1472
16:45:34.468320 IP (tos 0x0, ttl 63, id 51772, offset 0, flags [+], proto UDP (17), length 1500)
    <ip>.50988 > pinpoint-server.net.palace-4: UDP, bad length 1993 > 1472

I know this is a network issue but how can I handle it? Why it has happened?

**Comment by emeroad** [comment]
I'm not sure, but I think you should look at the issues below.
 - https://iota.stackexchange.com/questions/756/possible-udp-mtu-problems-udp-bad-length-1650-1368-in-tcpdump

**Comment by arkyhuang** [comment]
@emeroad Thanks. The issue had been fixed.
