### ISSUE TITLE
could we have a feature to query api-level statistic and histogram graph

### ISSUE THREAD

**Issue by snakedragon** [naver/pinpoint#4683]
**Which module is your feature request related to?**
UI

**Is your feature request related to a problem?**
we need a api-level statistic and histogram hisotry graph to sort the api online pressure and invoking freq

**Describe the solution you'd like**
maybe we should come up with a query page to provide this feature

**Describe alternatives you've considered**
provide a thrift or http interface to provide api-level query for statistic data

**Additional context**

**Comment by RoySRose** [comment]
Hello @snakedragon.

Love to have such features. But unfortunately, Pinpoint doesn't have any for the moment.
I'd be super glad if you could develop such a feature and send us a PR :)
