### ISSUE TITLE
How to trace Spring Scheduled Job

### ISSUE THREAD

**Issue by hasanfd** [naver/pinpoint#4695]
We are using springframework's scheduled jobs:

```
import org.springframework.scheduling.annotation.Scheduled;

@Service
class PinpointIs {
       
    @Transactional
    @Scheduled(cron = "0 0/1 * 1/1 * ? *")
    public void cool() {

    }
}
```

Is there any way to trace cool() method?

**Comment by Xylus** [comment]
Hi @hasanfd 
Sorry for the late reply.
Please check [this](https://naver.github.io/pinpoint/faq.html#my-custom-jar-application-is-not-being-traced-help) out and let me know if you have more questions.

**Comment by hasanfd** [comment]
Thanks, @Xylus. This will work for me.
I wonder, is there any way to filter out entry points? Since they don't have any path, it is hard to find their call stacks.
