### ISSUE TITLE
There are typo in doc/per-request_feature_guide.md

### ISSUE THREAD

**Issue by bbvch13531** [naver/pinpoint#4698]
There are typo in doc/per-request_feature_guide.md

line 288: `로그 메세지` -> `log message`  for consistency
line 289: `출려된` -> `출력된` typo
line 511: `추가되야` -> `추가돼야` typo

Also other spacing grammer errors exist.  
May I correct typo and send pull request?  
I already signed CLA.

**Comment by RoySRose** [comment]
Hello, @bbvch13531 

Of course, Go ahead. Let us know when you finish

**Comment by bbvch13531** [comment]
Hi @RoySRose, Thank you for your kind answer. 😃 
I send PR #4699. 
PTAL!
