### ISSUE TITLE
Split agent integration test module by jdk versions

### ISSUE THREAD

**Issue by Xylus** [naver/pinpoint#4708]
#### Description
Agent integration test module runs integration tests for plugins, and can only specify runtime java versions.
Integration tests themselves are compiled using jdk 6.
This is fine as we can still test libraries that require java 7+, but we cannot use jdk 7+ specific features directly inside the integration tests.

By separating these modules, we can specify which jdk to use to compile the integration tests as well.

**Comment by emeroad** [comment]
Resolve at #5596
