### ISSUE TITLE
run as -> maven build error 

### ISSUE THREAD

**Issue by pkyongse** [naver/pinpoint#4713]
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for hanatourair:JavaBot:war:0.0.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-war-plugin is missing. @ line 78, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (20 KB at 16.8 KB/sec)
[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (14 KB at 10.9 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.175 s
[INFO] Finished at: 2018-10-08T16:35:02+09:00
[INFO] Final Memory: 11M/115M
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'spring-boot' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\Yongse.Kim\.m2\repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

이렇게 뜨는데 에러설명사이트 가봐도 잘이해가안되요...

**Comment by koo-taejin** [comment]
안녕하세요 

이게 핀포인트 모듈이 맞는지요?
저희 모듈을 빌드할 경우 
전달주신 메시지가 나오지 않습니다. 
 "Some problems were encountered while building the effective model for hanatourair:JavaBot:war:0.0.1-SNAPSHOT" 
다시한번 확인하시기를 부탁 드립니다. 

감사합니다.

**Comment by pkyongse** [comment]
감사합니다!
