### ISSUE TITLE
How to get real ip address?

### ISSUE THREAD

**Issue by hustcxx** [naver/pinpoint#4715]
My application run in a   docker with highproxy balancer , and pinpoint _agent is also in docker.I have been changed  the config **.realipheader=X-Forwarded-for ,but I get client ip like '172.17.0.1',this is an address of   docker but not real ip address.I can't understand that .
Any people have good suggestions?

**Comment by hasanfd** [comment]
I think it's not related to pinpoint apm. It most likely related to docker networking. I suggest you read docker documentation about [networking](https://docs.docker.com/network/), especially host and bridge networking. You should put real IP address in the header(for instance to a key named 'X-Forwarded-for'), while the request going to docker networks over the actual network. Only then it makes sense to use pinpoint config for realipheader.
