### ISSUE TITLE
pp is support netty? 

### ISSUE THREAD

**Issue by god8816** [naver/pinpoint#4725]
pp is support netty?  but my netty program can't be monitored。 Please give me a demo.
https://github.com/lopiter/pinpoint/tree/add-kafka-plugin/plugins

**Comment by koo-taejin** [comment]
@god8816 

We do not  run demos.
Therefore, there is no url to forward you want.

netty is supported by the codec.
If you use an unsupported codec, it will not be traced.

Please check the issue. (#3211)

thanks.
