### ISSUE TITLE
Separate logging logic

### ISSUE THREAD

**Issue by imperio-wxm** [naver/pinpoint#4739]
I have two questions.

> I do not understand what logic should write in Controller？

There is no param about logs in `NeloLogForTransactionId` or I must call some method get retrieve logs by transactionId、spanId?

I just want when I click button, pre request logs can show on.

```java
@Controller
public class Nelo2LogController {

@RequestMapping(value = "/????")
public String NeloLogForTransactionId(@RequestParam (value= "transactionId", required=true) String transactionId,
				@RequestParam(value= "spanId" , required=false) String spanId,
				@RequestParam(value="time" , required=true) long time ) {
	// you should implement the logic to retrieve your agent’s logs.
}
```

![image](https://user-images.githubusercontent.com/8111349/46935691-7b750480-d08e-11e8-8d72-c9960679d5dc.png)

> Is normal for `SpanId` is negative number?

![image](https://user-images.githubusercontent.com/8111349/46935751-b5460b00-d08e-11e8-977c-2358edb62643.png)

**Comment by minwoo-jung** [comment]
@imperio-wxm
you should implement the logic to retrieve your agent’s logs.

ex) 
If you have logging system for log message. (ex. elasticsearch) you call search api by transactionId.
Or. If you only have log file. you look up log message yourself by transactionid. 

Therefore you should implement searching logic in log.
