### ISSUE TITLE
Cache layer for collecter & agent

### ISSUE THREAD

**Issue by imperio-wxm** [naver/pinpoint#4740]
**Which module is your feature request related to?**
collecter & agent

**Is your feature request related to a problem?**

About the availability of pinpoint. Agent report data to collector from network, there is no cache between them. If HBase shutdown or can not write data(compaction), the data will be lost.

The most obvious is when I shutdown my hbase and restart later, 
charts and data will be lost for a while, and never find back.

![image](https://user-images.githubusercontent.com/8111349/46940894-656e4080-d09c-11e8-98ed-0b57fbd8618e.png)

**Describe the solution you'd like**
There is any cache scheme like zipkin? Zipkin can use rabbitmq or kafka  between agent and collecter.

If storage not work and data still in MQ, we can find lost data from that.

![image](https://user-images.githubusercontent.com/8111349/46938586-bc711700-d096-11e8-81fa-c1a67f78ebe5.png)

**Comment by emeroad** [comment]
This is the intended architecture.
We do not want additional infrastructure and management costs.

If you need a cache layer, implement it in the collector.

**Comment by imperio-wxm** [comment]
@emeroad 

So It must lost data when hbase not work(like daily downtime maintenance: Each month do major compaction at night)?

I can not guarantee hbase 7x24 hours such as write so fast or region split or full gc.
However I should guarantee my monitor 7x24 hours.

**Comment by emeroad** [comment]
We did a major compaction on a weekend night, and there were no particular problems.

If you need 7*24 availability, consider hbase replication.

**Comment by imperio-wxm** [comment]
How about high availability for collecter?
Must write collecter ip in agent config,If collecter down all data will be lost.

Now I use HAProxy for two collecters, MQ can help decoupling. Agent not rely collecter so mach.

**Comment by emeroad** [comment]
Refer to the hbase manual.
- Cloudera AdministrationBackup and Disaster RecoveryData Replication
https://www.cloudera.com/documentation/enterprise/5-9-x/topics/cdh_bdr_hbase_replication.html
