### ISSUE TITLE
The response time in ScatterChart is not consistent with the time application consumption time.

### ISSUE THREAD

**Issue by baoshengzhu** [naver/pinpoint#4757]
The response time in ScatterChart is not consistent with the time application consumption time. In response, you can see dozens of s, the time may be 0-3 seconds, not so high.   thrift application, and the pinpoints version was 1.8

![image](https://user-images.githubusercontent.com/22464274/47020511-169fd400-d18c-11e8-891c-b95da641e350.png)

**Comment by Xylus** [comment]
Hi @baoshengzhu 
What is the scatter chart not consistent with? Could you post the relevant comparison data so that we can have a look?

**Comment by baoshengzhu** [comment]
The response time in the scatter diagram is not consistent with the elapsed time printed by the application log.
In addition, two related applications are all connected to pines-but the topology diagram does not show their previous call diagrams. Is there anything else to configure?

**Comment by baoshengzhu** [comment]
@Xylus

**Comment by Xylus** [comment]
@baoshengzhu 
Could you drag the inconsistent requests from the scatter chart and check their call stack to see if anything's not recorded properly?
If you find anything that isn't to your expectation, please post the call stack and tell us what you would expect them to be.
