### ISSUE TITLE
Response Time Chart and Response Time scatter chart data  was not same in the same time 

### ISSUE THREAD

**Issue by zfaster** [naver/pinpoint#4773]
in the same time why the Response Time max 136min but in the  scatter chart I can not find the request

![image](https://user-images.githubusercontent.com/8341790/47200392-95715880-d3a8-11e8-87d4-1bcf6035c492.png)
![image](https://user-images.githubusercontent.com/8341790/47200508-09136580-d3a9-11e8-964d-f98b5691c1af.png)

**Comment by RoySRose** [comment]
Hello, @zfaster 

I'm not really sure, yet. But I assume that the *response chart* shows the one that took 136.2M sec.
And *scatter chart* show the ones only up to 150,000ms. 
I'm not really sure. But somehow I get the feeling that it would.

@denzelsN can you please check the limit of y axis in *scatter chart*?
