### ISSUE TITLE
Kafka plugin configuration

### ISSUE THREAD

**Issue by 3W1H** [naver/pinpoint#4794]
How can i config the key “profiler.kafka.consumer.entryPoint" in the pinpoint.config file?  if I use the kafka of version-0.9 , can I still use the Kafka Plugin?

![image](https://user-images.githubusercontent.com/8038747/47422672-c3460b00-d7b5-11e8-9a93-4dc059bda709.png)

**Comment by 3W1H** [comment]
How can i config the key "profiler.kafka.consumer.entryPoint"

**Comment by koo-taejin** [comment]
hi @3W1H 

Pinpoint supports Kafka plugin from 0.11 .

In addition, you can set it to `profiler.kafka.consumer.entryPoint=packageName.clazzName.methodName` like ex).

thanks.

**Comment by 3W1H** [comment]
if I hava many classes or many methods to handle the kafka messages,  How can i config all these classes or methods?

**Comment by koo-taejin** [comment]
Currently, only one method can be set.
I will consider supporting multiple methods in the future.
