### ISSUE TITLE
The issue of pinpoint application information IP(IPV6)

### ISSUE THREAD

**Issue by rootyanghao** [naver/pinpoint#4806]
**What version of pinpoint are you using?**
master/v1.7.3/v1.7.2 etc.

**Describe the bug**
![default](https://user-images.githubusercontent.com/17381101/47556116-25cb1280-d940-11e8-95fc-77dec3969b18.png)

 It can be displayed as IPV4 
**What did you do to trigger the b

**Comment by baoshengzhu** [comment]
I also encountered the same problem , looking forward to the solution.

**Comment by emeroad** [comment]
Pinpoint uses the following method to obtain the Ip Address.

```java
NetworkUtils.getRepresentationHostIp()
```
https://github.com/naver/pinpoint/blob/master/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/util/NetworkUtils.java#L67

I hope you will try debugging on the target server.
