### ISSUE TITLE
net::ERR_CONNECTION_REFUSED  (Network Error ) 

### ISSUE THREAD

**Issue by lalitnandandiwakar** [naver/pinpoint#4812]
**What version of pinpoint are you using?**
master

**Describe your problem**
i Deploy In My Server 
login page is appear 
than we get error 
 
![screenshot 2018-10-26 14 45 01](https://user-images.githubusercontent.com/11966970/47633409-cead8380-db73-11e8-8088-ac213b6ff621.png)
Network Error 
**What have you done?**
Steps you have taken to trigger the problem, for example:
1. open web page 
(see collector log below)
4. No trace shows up in the web UI (see web log below)

Download the React DevTools for a better development experience: https://fb.me/react-devtools
styled-components.browser.esm.js:1706 Warning: The "extend" API will be removed in the upcoming v4.0 release. Use styled(StyledComponent) instead. You can find more information here: https://github.com/styled-components/styled-components/issues/1546
(anonymous) @ styled-components.browser.esm.js:1706
./node_modules/styled-components/dist/styled-components.browser.esm.js.once @ styled-components.browser.esm.js:402
get$$1 @ styled-components.browser.esm.js:1935
./src/modules/common/components/Button.tsx @ Button.tsx:110
__webpack_require__ @ bootstrap fa4ee1258954a9109f2e:707
fn @ bootstrap fa4ee1258954a9109f2e:112
./src/modules/common/components/ConfirmDialog.tsx @ Chooser.tsx:200
__webpack_require__ @ bootstrap fa4ee1258954a9109f2e:707
fn @ bootstrap fa4ee1258954a9109f2e:112
./src/modules/common/utils/confirmation/createConfirmation.tsx @ confirm.tsx:8
__webpack_require__ @ bootstrap fa4ee1258954a9109f2e:707
fn @ bootstrap fa4ee1258954a9109f2e:112
./src/modules/common/utils/confirmation/confirm.tsx @ confirm.tsx:1
__webpack_require__ @ bootstrap fa4ee1258954a9109f2e:707
fn @ bootstrap fa4ee1258954a9109f2e:112
./src/modules/common/utils/index.ts @ index.ts:1
__webpack_require__ @ bootstrap fa4ee1258954a9109f2e:707
fn @ bootstrap fa4ee1258954a9109f2e:112
./src/apolloClient.ts @ apolloClient.ts:1
__webpack_require__ @ bootstrap fa4ee1258954a9109f2e:707
fn @ bootstrap fa4ee1258954a9109f2e:112
./src/index.tsx @ index.tsx:1
__webpack_require__ @ bootstrap fa4ee1258954a9109f2e:707
fn @ bootstrap fa4ee1258954a9109f2e:112
0 @ routes.tsx:52
__webpack_require__ @ bootstrap fa4ee1258954a9109f2e:707
(anonymous) @ bootstrap fa4ee1258954a9109f2e:805
(anonymous) @ bootstrap fa4ee1258954a9109f2e:805
ApolloClient.js:62 Download the Apollo DevTools for a better development experience: https://chrome.google.com/webstore/detail/apollo-client-developer-t/jdkknkkbebbapilgoeccciglkfbmbnfm
client.js:77 WebSocket connection to 'ws://localhost:3300/subscriptions' failed: WebSocket is closed before the connection is established.
./node_modules/subscriptions-transport-ws/dist/client.js.SubscriptionClient.close @ client.js:77
(anonymous) @ client.js:415
setTimeout (async)
./node_modules/subscriptions-transport-ws/dist/client.js.SubscriptionClient.checkMaxConnectTimeout @ client.js:413
./node_modules/subscriptions-transport-ws/dist/client.js.SubscriptionClient.connect @ client.js:422
SubscriptionClient @ client.js:52
WebSocketLink @ webSocketLink.js:24
./src/apolloClient.ts @ apolloClient.ts:67
__webpack_require__ @ bootstrap fa4ee1258954a9109f2e:707
fn @ bootstrap fa4ee1258954a9109f2e:112
./src/index.tsx @ index.tsx:1
__webpack_require__ @ bootstrap fa4ee1258954a9109f2e:707
fn @ bootstrap fa4ee1258954a9109f2e:112
0 @ routes.tsx:52
__webpack_require__ @ bootstrap fa4ee1258954a9109f2e:707
(anonymous) @ bootstrap fa4ee1258954a9109f2e:805
(anonymous) @ bootstrap fa4ee1258954a9109f2e:805
client.js:77 WebSocket connection to 'ws://localhost:3300/subscriptions' failed: WebSocket is closed before the connection is established.
./node_modules/subscriptions-transport-ws/dist/client.js.SubscriptionClient.close @ client.js:77
(anonymous) @ client.js:415
setTimeout (async)
./node_modules/subscriptions-transport-ws/dist/client.js.SubscriptionClient.checkMaxConnectTimeout @ client.js:413
./node_modules/subscriptions-transport-ws/dist/client.js.SubscriptionClient.connect @ client.js:422
(anonymous) @ client.js:391
setTimeout (async)
./node_modules/subscriptions-transport-ws/dist/client.js.SubscriptionClient.tryReconnect @ client.js:390
./node_modules/subscriptions-transport-ws/dist/client.js.SubscriptionClient.close @ client.js:81
(anonymous) @ client.js:415
setTimeout (async)
./node_modules/subscriptions-transport-ws/dist/client.js.SubscriptionClient.checkMaxConnectTimeout @ client.js:413
./node_modules/subscriptions-transport-ws/dist/client.js.SubscriptionClient.connect @ client.js:422
SubscriptionClient @ client.js:52
WebSocketLink @ webSocketLink.js:24
./src/apolloClient.ts @ apolloClient.ts:67
__webpack_require__ @ bootstrap fa4ee1258954a9109f2e:707
fn @ bootstrap fa4ee1258954a9109f2e:112
./src/index.tsx @ index.tsx:1
__webpack_require__ @ bootstrap fa4ee1258954a9109f2e:707
fn @ bootstrap fa4ee1258954a9109f2e:112
0 @ routes.tsx:52
__webpack_require__ @ bootstrap fa4ee1258954a9109f2e:707
(anonymous) @ bootstrap fa4ee1258954a9109f2e:805
(anonymous) @ bootstrap fa4ee1258954a9109f2e:805
httpLink.js:87 OPTIONS http://localhost:3300/graphql net::ERR_CONNECTION_REFUSED
(anonymous) @ httpLink.js:87
Subscription @ Observable.js:179
subscribe @ Observable.js:258
(anonymous) @ index.js:20
Promise.then (async)
(anonymous) @ index.js:19
Subscription @ Observable.js:179
subscribe @ Observable.js:258
(anonymous) @ Observable.js:301
Subscription @ Observable.js:179
subscribe @ Observable.js:258
(anonymous) @ index.js:23
Subscription @ Observable.js:179
subscribe @ Observable.js:258
(anonymous) @ dedupLink.js:55
Subscription @ Observable.js:179
subscribe @ Observable.js:258
(anonymous) @ QueryManager.js:741
./node_modules/apollo-client/core/QueryManager.js.QueryManager.fetchRequest @ QueryManager.js:739
./node_modules/apollo-client/core/QueryManager.js.QueryManager.fetchQuery @ QueryManager.js:269
./node_modules/apollo-client/core/QueryManager.js.QueryManager.startQuery @ QueryManager.js:597
./node_modules/apollo-client/core/ObservableQuery.js.ObservableQuery.setUpQuery @ ObservableQuery.js:335
./node_modules/apollo-client/core/ObservableQuery.js.ObservableQuery.onSubscribe @ ObservableQuery.js:304
(anonymous) @ ObservableQuery.js:43
Subscription @ Observable.js:179
subscribe @ Observable.js:258
Query._this.startQuerySubscription @ react-apollo.browser.umd.js:334
./node_modules/react-apollo/react-apollo.browser.umd.js.Query.componentDidMount @ react-apollo.browser.umd.js:434
commitLifeCycles @ react-dom.development.js:14685
commitAllLifeCycles @ react-dom.development.js:15905
callCallback @ react-dom.development.js:145
invokeGuardedCallbackDev @ react-dom.development.js:195
invokeGuardedCallback @ react-dom.development.js:248
commitRoot @ react-dom.development.js:16075
completeRoot @ react-dom.development.js:17463
performWorkOnRoot @ react-dom.development.js:17391
performWork @ react-dom.development.js:17295
performSyncWork @ react-dom.development.js:17267
requestWork @ react-dom.development.js:17155
scheduleWork @ react-dom.development.js:16949
scheduleRootUpdate @ react-dom.development.js:17637
updateContainerAtExpirationTime @ react-dom.development.js:17664
updateContainer @ react-dom.development.js:17691
./node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:17957
(anonymous) @ react-dom.development.js:18097
unbatchedUpdates @ react-dom.development.js:17518
legacyRenderSubtreeIntoContainer @ react-dom.development.js:18093
render @ react-dom.development.js:18152
./src/index.tsx @ index.tsx:15
__webpack_require__ @ bootstrap fa4ee1258954a9109f2e:707
fn @ bootstrap fa4ee1258954a9109f2e:112
0 @ routes.tsx:52
__webpack_require__ @ bootstrap fa4ee1258954a9109f2e:707
(anonymous) @ bootstrap fa4ee1258954a9109f2e:805
(anonymous) @ bootstrap fa4ee1258954a9109f2e:805
35.190.149.31/:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: http://35.190.149.31:3002/static/media/erxes.098e5a36.woff2
35.190.149.31/:1 This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.
35.190.149.31/:1 [DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) <input class=​"sc-dUjcNx hJGvOX" placeholder=​"password" type=​"password" required value>​
26client.js:421 WebSocket connection to 'ws://localhost:3300/subscriptions' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
./node_modules/subscriptions-transport-ws/dist/client.js.SubscriptionClient.connect @ client.js:421
(anonymous) @ client.js:391

**Screenshots**
![screenshot 2018-10-26 14 45 01](https://user-images.githubusercontent.com/11966970/47633548-51364300-db74-11e8-8a64-e11a72736607.png)
![capture](https://user-images.githubusercontent.com/11966970/47633590-788d1000-db74-11e8-8064-2c11e008a5df.PNG)
![screenshot 2018-10-29 12 14 55](https://user-images.githubusercontent.com/11966970/47633642-a4a89100-db74-11e8-85fc-33e0c7229bc8.png)

**Logs**
client.js:421 WebSocket connection to 'ws://localhost:3300/subscriptions' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
./node_modules/subscriptions-transport-ws/dist/client.js.SubscriptionClient.connect @ client.js:421
(anonymous) @ client.js:391

**Additional context**
Add any other context about the problem here, such as affected library for agents, how your collector/web/hbase is set up if applicable.

**Comment by emeroad** [comment]
It seems like an issue not related to pinpoint.
