### ISSUE TITLE
A problem about "Buffer size cannot exceed 65507" in pinpoint-agent logs,The following is a report on this problem

### ISSUE THREAD

**Issue by YangchengwuGit** [naver/pinpoint#4815]
![6e087fe049ab3138ed0da9f001ce558e](https://user-images.githubusercontent.com/22573500/47638653-1cd57d80-db9a-11e8-8083-14ef8b648147.jpg)
![qq20181029-0](https://user-images.githubusercontent.com/22573500/47638658-20690480-db9a-11e8-9abf-0af3404804e4.jpg)

**Comment by emeroad** [comment]
pinpoint.config
```
# How many spans to store if buffering enabled.
profiler.io.buffering.buffersize=20
```
Try adjusting `profiler.io.buffering.buffersize` value

**Comment by YangchengwuGit** [comment]
> pinpoint.config
> 
> ```
> # How many spans to store if buffering enabled.
> profiler.io.buffering.buffersize=20
> ```
> Try adjusting `profiler.io.buffering.buffersize` value

what is mean of this parameters? how many can i set?could you give me a suggestion.

**Comment by YangchengwuGit** [comment]
> > pinpoint.config
> > ```
> > # How many spans to store if buffering enabled.
> > profiler.io.buffering.buffersize=20
> > ```
> > Try adjusting `profiler.io.buffering.buffersize` value
> 
> what is the mean of this parameters? how much can i set?could you give me a suggestion.

i set 100,200,1000, the result is the same as before.
![image](https://user-images.githubusercontent.com/22573500/47654548-034a2b00-dbc6-11e8-99d2-7ad8821aa9e5.png)

**Comment by koo-taejin** [comment]
hi @YangchengwuGit 

buffer size can not be increased more than 65k due to PacketSize of UDP.
If you have a lot of data, you have to reduce the size.
I would recommend reducing it to around 10.
If it still happens, reduce it to less.

thanks.

**Comment by YangchengwuGit** [comment]
> hi @YangchengwuGit
> 
> buffer size can not be increased more than 65k due to PacketSize of UDP.
> If you have a lot of data, you have to reduce the size.
> I would recommend reducing it to around 10.
> If it still happens, reduce it to less.
> 
> thanks.

hi @koo-taejin 
Do you mean changing the size of the parameter or the size of the data? 
I try to set 10 of the parameter ,almost the same result

**Comment by koo-taejin** [comment]
mean is changing the size of the parameter

If it still happens, reduce it to less.

**Comment by YangchengwuGit** [comment]
> mean is changing the size of the parameter
> 
> If it still happens, reduce it to less.
i reduce it to 2, the same result as before

**Comment by koo-taejin** [comment]
One trace data seems to be very large.
check which data is causing the above error, and disable the tracking of related data in the pinpoint.config.

Alternatively, changing UDP to TCP may be a solution.
In this case, the setting of the collector also needs to be changed.

**Comment by YangchengwuGit** [comment]
> One trace data seems to be very large.
> check which data is causing the above error, and disable the tracking of related data in the pinpoint.config.
> 
> Alternatively, changing UDP to TCP may be a solution.
> In this case, the setting of the collector also needs to be changed.

i find some parameter about changing UDP to TCP,is it possible to change the following parameters of the collector?
![image](https://user-images.githubusercontent.com/22573500/47699448-f07b3900-dc4d-11e8-8d0b-0b8141bb24ef.png)

**Comment by YangchengwuGit** [comment]
> One trace data seems to be very large.
> check which data is causing the above error, and disable the tracking of related data in the pinpoint.config.
> 
> Alternatively, changing UDP to TCP may be a solution.
> In this case, the setting of the collector also needs to be changed.
Is it necessary to modify the source code about to change UDP to TCP?

**Comment by koo-taejin** [comment]
You also need to change the following settings within pinpoint-collector.properties

```
collector.receiver.stat.tcp=false - > true
collector.receiver.stat.tcp.ip=0.0.0.0
collector.receiver.stat.tcp.port=9995

collector.receiver.span.tcp=false -> true
collector.receiver.span.tcp.ip=0.0.0.0
collector.receiver.span.tcp.port=9996
```

**Comment by YangchengwuGit** [comment]
> You also need to change the following settings within pinpoint-collector.properties
> 
> ```
> collector.receiver.stat.tcp=false - > true
> collector.receiver.stat.tcp.ip=0.0.0.0
> collector.receiver.stat.tcp.port=9995
> 
> collector.receiver.span.tcp=false -> true
> collector.receiver.span.tcp.ip=0.0.0.0
> collector.receiver.span.tcp.port=9996
> ```

I changed the following parameters, do I need to change the parameters of other configuration files?
![image](https://user-images.githubusercontent.com/22573500/47780490-74105500-dd36-11e8-8a2b-3a683997fe44.png)

**Comment by YangchengwuGit** [comment]
@koo-taejin thank you for your help ,there will be no mistake of ‘buffer size can not exceed 65507’ when i change udp to tcp.
But now there is another problem. Even when the content of a request is too much, part of the content can not be displayed. I also read the logs of agent and collector, but there are no errors.

**Comment by koo-taejin** [comment]
At first, I am glad that there is no error occurs.

I do not know the exact reason, but the Value of Annotation is too large, and it seems that there is a problem somewhere.
Please check that there are no exceptions on the web logs.

Although I do not know the perfect situation,
The Value of Annotaion is expected to exceed 65k.

In this case, It's very difficult to show these values in normal.


If possible, I would recommand you not to trace these data. 

If you have any further information, please post it to then  I'll analyze it again.

thanks.

**Comment by YangchengwuGit** [comment]
> At first, I am glad that there is no error occurs.
> 
> I do not know the exact reason, but the Value of Annotation is too large, and it seems that there is a problem somewhere.
> Please check that there are no exceptions on the web logs.
> 
> Although I do not know the perfect situation,
> The Value of Annotaion is expected to exceed 65k.
> 
> In this case, It's very difficult to show these values in normal.
> 
> If possible, I would recommand you not to trace these data.
> 
> If you have any further information, please post it to then I'll analyze it again.
> 
> thanks.

Let me introduce the current situation to you：

There is a long execution request, and there are more contents inside.

I pulled to the bottom of the page and found that some of the methods were not recorded.

That is to say, part of the data is missing. There is no error in the log. I don't know what caused it. Do you have any ideas or suggestions?

thanks.

![image](https://user-images.githubusercontent.com/22573500/47898391-a6de5880-deb0-11e8-99d4-a43489b7c888.png)
![image](https://user-images.githubusercontent.com/22573500/47898504-1bb19280-deb1-11e8-9cc2-73f9e78bdf08.png)

**Comment by koo-taejin** [comment]
* Is it because of the time you marked?

And then It is not a problem.
Please understand the exact meaning of gap exec, self first.

* Is the desired method not tracked?
In this case, I recommand to change log level of the agent and  check whether the trace is normal first.

**Comment by YangchengwuGit** [comment]
I understand the exact meaning of gap exec, self;

The logic of the program is probably as follows,the contents of the tag is missing.

The self time I marked may be the execution of missing parts.
![image](https://user-images.githubusercontent.com/22573500/47902838-bb751d80-debd-11e8-8b9c-f7c4e0ca1cc5.png)

**Comment by koo-taejin** [comment]
I do not know your code.
I do not know how many time used in your method .
I do not know  how long it will take if the method is not included or If the method is included.

I do not have a way to solve this issue because of the limited information.

I recommend you to change agent log level to debug and checking how's working agent. 

thanks.

**Comment by YangchengwuGit** [comment]
> I do not know your code.
> I do not know how many time used in your method .
> I do not know how long it will take if the method is not included or If the method is included.
> 
> I do not have a way to solve this issue because of the limited information.
> 
> I recommend you to change agent log level to debug and checking how's working agent.
> 
> thanks.

ok,I will try to change the level of agent.

If I don't understand anything, I'll ask you again.

thank you for your help.
