### ISSUE TITLE
 Are you going to support the monitoring of the netty http service in the future?

### ISSUE THREAD

**Issue by chengruyi** [naver/pinpoint#4822]
**Which module is your feature request related to?**
Plugin/UI etc

**Is your feature request related to a problem?**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by koo-taejin** [comment]
netty's client httpcodec is already supported.
But, the server httpcodec is not supported. And We don't  have a plan

I'd be glad if you could develop such a feature and send us a PR.

thanks.
