### ISSUE TITLE
How do I show some information in Argument column

### ISSUE THREAD

**Issue by ighack** [naver/pinpoint#4824]
In my PostArgumentConstants file
`public static final AnnotationKey POSTARGUMENT_ANNOTATION_KEY_INFO = AnnotationKeyFactory.of(998, "POST-ARGUMENT", VIEW_IN_RECORD_SET);`
In my PostArgumentInterceptor
` recorder.recordAttribute(PostArgumentConstants.POSTARGUMENT_ANNOTATION_KEY_INFO, json);
                recorder.recordAttribute(AnnotationKey.RETURN_DATA, json);`
but the first row doesn't work.

![image](http://bbs.chinaunix.net/data/attachment/forum/201810/31/104932iv1osspvjopg2s1s.png)

I remove second row,it nothing in Argument column

**Comment by RoySRose** [comment]
Hello, @ighack 
showing information in Arg column is related to AnnotationKey settings.
`VIEW_IN_RECORD_SET` is the one that triggers appearance of info in Arg column.

with the given details, I think there is no problem with the AnnotationKey settings.
I think it's just that `PostArgumentConstants.POSTARGUMENT_ANNOTATION_KEY_INFO` attribute wasn't recorded. 
or
maybe PostArgumentConstants.POSTARGUMENT_ANNOTATION_KEY_INFO annotation wasn't added in the context.
````java
// YOURTypeProvider
context.addAnnotationKey(PostArgumentConstants.POSTARGUMENT_ANNOTATION_KEY_INFO)
````

**Comment by ighack** [comment]
I have add in the context.
In my PostArgumentMetadataProvider
`context.addAnnotationKey(PostArgumentConstants.POSTARGUMENT_ANNOTATION_KEY_INFO);`

![image](http://bbs.chinaunix.net/data/attachment/forum/201810/31/113643d7q7gdaaaa3qzqqa.png)

**Comment by ighack** [comment]
PostArgumentConstants.java
`package com.navercorp.pinpoint.plugin.jzt;

import com.navercorp.pinpoint.common.trace.AnnotationKey;
import com.navercorp.pinpoint.common.trace.AnnotationKeyFactory;
import com.navercorp.pinpoint.common.trace.ServiceType;
import com.navercorp.pinpoint.common.trace.ServiceTypeFactory;

import static com.navercorp.pinpoint.common.trace.AnnotationKeyProperty.VIEW_IN_RECORD_SET;
import static com.navercorp.pinpoint.common.trace.ServiceTypeProperty.RECORD_STATISTICS;

public class PostArgumentConstants {
    public PostArgumentConstants(){}
    public static final ServiceType POSTARGUMENT_SERVICE_TYPE = ServiceTypeFactory.of(7998, "POSTARGUMENT","POSTARGUMENT", RECORD_STATISTICS);
    public static final AnnotationKey POSTARGUMENT_ANNOTATION_KEY_INFO = AnnotationKeyFactory.of(998, "POST-ARGUMENT", VIEW_IN_RECORD_SET);
}
`

PostArgumentMetadataProvider.java
`
import com.navercorp.pinpoint.common.trace.TraceMetadataProvider;
import com.navercorp.pinpoint.common.trace.TraceMetadataSetupContext;

public class PostArgumentMetadataProvider implements TraceMetadataProvider {
    @Override
    public void setup(TraceMetadataSetupContext context) {
        //设定当前插件的ServiceType，既插件的唯一身份
        context.addServiceType(PostArgumentConstants.POSTARGUMENT_SERVICE_TYPE);
        context.addAnnotationKey(PostArgumentConstants.POSTARGUMENT_ANNOTATION_KEY_INFO);
    }
}
`
PostArgumentPlugin.java
`package com.navercorp.pinpoint.plugin.jzt;

import com.navercorp.pinpoint.bootstrap.instrument.InstrumentClass;
import com.navercorp.pinpoint.bootstrap.instrument.InstrumentException;
import com.navercorp.pinpoint.bootstrap.instrument.InstrumentMethod;
import com.navercorp.pinpoint.bootstrap.instrument.Instrumentor;
import com.navercorp.pinpoint.bootstrap.instrument.MethodFilters;
import com.navercorp.pinpoint.bootstrap.instrument.transformer.TransformCallback;
import com.navercorp.pinpoint.bootstrap.instrument.transformer.TransformTemplate;
import com.navercorp.pinpoint.bootstrap.instrument.transformer.TransformTemplateAware;
import com.navercorp.pinpoint.bootstrap.logging.PLogger;
import com.navercorp.pinpoint.bootstrap.logging.PLoggerFactory;
import com.navercorp.pinpoint.bootstrap.plugin.ProfilerPlugin;
import com.navercorp.pinpoint.bootstrap.plugin.ProfilerPluginSetupContext;
import com.navercorp.pinpoint.common.trace.AnnotationKey;
import com.navercorp.pinpoint.common.trace.AnnotationKeyFactory;
import com.navercorp.pinpoint.common.trace.ServiceType;
import com.navercorp.pinpoint.common.trace.ServiceTypeFactory;

import java.security.ProtectionDomain;


public class PostArgumentPlugin implements ProfilerPlugin, TransformTemplateAware {

    private static final String POST_ARGUMENT = "POST_ARGUMENT";
    private final PLogger logger = PLoggerFactory.getLogger(this.getClass());
    private TransformTemplate transformTemplate;

    @Override
    public void setup(ProfilerPluginSetupContext context) {

        PostArgumentConfig config = new PostArgumentConfig(context.getConfig());

        if(config.isProfile()) {
            //Logger类被加载的时候，会注入这里new的TransformCallback，对这个类的实例在线程中的行为进行拦截
            transformTemplate.transform("com.jztcloud.postargument.PostArgument", new TransformCallback() {
                @Override
                public byte[] doInTransform(Instrumentor instrumentor, ClassLoader loader, String className, Class<?> classBeingRedefined, ProtectionDomain protectionDomain, byte[] classfileBuffer) throws InstrumentException {
                    InstrumentClass target = instrumentor.getInstrumentClass(loader, className, classfileBuffer); //找到所有名为info的方法
                    for (InstrumentMethod m : target.getDeclaredMethods(MethodFilters.name("show"))) {
                        ////注入Interceptor，在Logger类的实例执行info方法的时候会执行这个interceptor
                        m.addScopedInterceptor("com.navercorp.pinpoint.plugin.jzt.interceptor.PostArgumentInterceptor", POST_ARGUMENT);
                    }
                    return target.toBytecode();
                }
            });
        }
    }

    @Override
    public void setTransformTemplate(TransformTemplate transformTemplate) {
        this.transformTemplate = transformTemplate;
    }

}
`
PostArgumentInterceptor.java
`package com.navercorp.pinpoint.plugin.jzt.interceptor;

import com.navercorp.pinpoint.bootstrap.context.MethodDescriptor;
import com.navercorp.pinpoint.bootstrap.context.SpanEventRecorder;
import com.navercorp.pinpoint.bootstrap.context.Trace;
import com.navercorp.pinpoint.bootstrap.context.TraceContext;
import com.navercorp.pinpoint.bootstrap.interceptor.AroundInterceptor1;
import com.navercorp.pinpoint.bootstrap.interceptor.AroundInterceptor2;
import com.navercorp.pinpoint.bootstrap.logging.PLogger;
import com.navercorp.pinpoint.bootstrap.logging.PLoggerFactory;
import com.navercorp.pinpoint.common.trace.AnnotationKey;
import com.navercorp.pinpoint.plugin.jzt.PostArgumentConstants;
import com.navercorp.pinpoint.plugin.jzt.PostArgumentPlugin;
import com.fasterxml.jackson.databind.ObjectMapper;


public class PostArgumentInterceptor implements AroundInterceptor1 {
    private final TraceContext traceContext;
    private final MethodDescriptor descriptor;
    private final PLogger logger = PLoggerFactory.getLogger(getClass());

    public PostArgumentInterceptor(TraceContext traceContext, MethodDescriptor descriptor) {
        this.traceContext = traceContext;
        this.descriptor = descriptor;
    }

    @Override
    public void before(Object target, Object arg0) {
        if (logger.isDebugEnabled()) {
            logger.beforeInterceptor(target, new Object[] {arg0});
        }

        final Trace trace = traceContext.currentTraceObject();
        if (trace == null) {
            return;
        }

        trace.traceBlockBegin();

    }

    @Override
    public void after(Object target, Object arg0,Object result, Throwable throwable) {

        if (logger.isDebugEnabled()) {
            logger.afterInterceptor(target, new Object[] {arg0}, result, throwable);
        }

        final Trace trace = traceContext.currentTraceObject();
        if (trace == null) {
            return;
        }

        try {
            SpanEventRecorder recorder = trace.currentSpanEventRecorder();
            recorder.recordServiceType(PostArgumentConstants.POSTARGUMENT_SERVICE_TYPE);
            recorder.recordApi(descriptor,new Object[] {arg0});
            recorder.recordException(throwable);

            if (arg0 != null) {
                String json = (String)arg0;

//                try {
//                    ObjectMapper mapper = new ObjectMapper();
//                    if (arg0 instanceof String) {
//                        json = arg0.toString();
//                    } else if (arg0 instanceof Object) {
//                        json = mapper.writeValueAsString(arg0);
//                    }
//                } catch (Exception e) {
//                    logger.error(e.getMessage());
//                }
                recorder.recordAttribute(PostArgumentConstants.POSTARGUMENT_ANNOTATION_KEY_INFO, json);
                recorder.recordAttribute(AnnotationKey.RETURN_DATA, json);
            }
        } finally {
            trace.traceBlockEnd();
        }
    }

    //    private static boolean shouldTrace(Object[] args) {
//        return null != args && args.length > 0 && (args[0] instanceof String) && ((String) args[0]).indexOf("pinpoint_bizlog_name") > -1;
//    }


}
`

**Comment by RoySRose** [comment]
try replacing and let us know
```java
    public static final ServiceType POSTARGUMENT_SERVICE_TYPE = ServiceTypeFactory.of(7998, "POSTARGUMENT","POSTARGUMENT", RECORD_STATISTICS);

to

    public static final ServiceType POSTARGUMENT_SERVICE_TYPE = ServiceTypeFactory.of(7998, "POSTARGUMENT","POSTARGUMENT", VIEW_IN_RECORD_SET);
```

**Comment by ighack** [comment]
I have modify 
@RoySRose 
```
public static final ServiceType POSTARGUMENT_SERVICE_TYPE = ServiceTypeFactory.of(7998, "POSTARGUMENT","POSTARGUMENT", VIEW_IN_RECORD_SET);
```
but I get a error
```
Cannot resolve method 'of(int, java.lang.String, java.lang.String, com.navercorp.pinpoint.common.trace.AnnotationKeyProperty)'
```

**Comment by RoySRose** [comment]
Hello, @ighack 

I'm sorry. I've misread and misguided you.

I don't really see any problem with your code. 

Have you reinstalled and restarted the Pinpoint-Web after developing?

**Comment by denzelsN** [comment]
@RoySRose

**Comment by ighack** [comment]
I don't modify any code,just restarted the Pinpoint-Web on new environment
It works.

**Comment by RoySRose** [comment]
Thx for sharing
