### ISSUE TITLE
how to output transactionId in my log

### ISSUE THREAD

**Issue by wangwei0537** [naver/pinpoint#4828]
Here is my log output：
Catalina. Out
2018-09-06 12:34:49,084 [INFO] [catalina-exec-101] [XXXXXXXServiceImpl. Java: 58] - [TxId:, SpanId:] xxxxLog is exist.

TxId:, SpanId: unreachable
Java's logging plug-in is logback，why TxId and SpanId No values are output

**Comment by emeroad** [comment]
https://github.com/naver/pinpoint/blob/master/doc/per-request_feature_guide.md
