### ISSUE TITLE
I cannot find CallStack from UI, please help...

### ISSUE THREAD

**Issue by waterystone** [naver/pinpoint#4834]
i install pinpoint use quickstart( https://naver.github.io/pinpoint/1.7.3/quickstart.html ),the ServerMap is OK, BUT i cannot find the CallStack? Please help me...

![pinpoint](https://user-images.githubusercontent.com/7723467/47852281-400c6100-de16-11e8-8f42-32cd8c6c7285.png)

**Comment by waterystone** [comment]
OK, I find it...
Need to select some point in right top chart,like this:

![wx20181101-211128](https://user-images.githubusercontent.com/7723467/47853786-d3479580-de1a-11e8-9829-048a72e732f2.png)

**Comment by RoySRose** [comment]
Hello, @waterystone 

Yes, that's the way~ :)
