### ISSUE TITLE
SQL-ID not found

### ISSUE THREAD

**Issue by yale2** [naver/pinpoint#4842]
**What version of pinpoint are you using?**
master/v1.6.2.

**Describe your problem**
in web UI.I found SQL-ID not  found in almost all application. we use mysql.how was that happen .why the collector can not collect sql?do you have any idea?

**What have you done?**
Steps you have taken to trigger the problem, for example:
1. Launched application with agent
2. Tried tracing sql statement
4. SQL-ID not found shows up in the web UI 

we set log level as WARN .so there is no useful log.can you give some suggest about this.

**Comment by RoySRose** [comment]
Hello, @yale2 
why don't you try using the latest stable version such as v1.8.0
the latest version has much more coverage as you can expect.
Older versions may have not adopted the changes in mysql.

If it still has errors for v1.8.0. Please check the logs and let us know if there are any suspicious results.

**Comment by yale2** [comment]
ok,I'll try 1.8.0. thanks.

**Comment by ITGrocery** [comment]
We already have found the same problem!

**Comment by RoySRose** [comment]
Hello, @ITGrocery 

It happens when there isn't any metadata of the SQL.
which version of pinpoint are you using?
and is it happening for all SQLs that you tried to see on Pinpoint-web?

**Comment by ITGrocery** [comment]
No,one application found the problem ,the others don't have this problem.The data of 'SqlMetaData_Ver2' will be lost after two months, Can it will cause the problem?

**Comment by ITGrocery** [comment]
When I drop the table of 'SqlMetaData_Ver2' using command,the web page will show 'SQL-ID not found',but whe I restart the tomcat,the problem will dismiss.

**Comment by ITGrocery** [comment]
I found the reason, the application has runned at least half a year,but the data of 'SqlMetaData_Ver2' has already been valid.Can you will solve the problem in the future?

**Comment by StevenWangGitHub** [comment]
pinpoint怎么监控C#工程
