### ISSUE TITLE
Agent 가 시작되어 있는 상태에서 Collector/Web 을 시작할 경우 

### ISSUE THREAD

**Issue by cowboy93** [naver/pinpoint#485]
Agent 가 시작되어 있는 상태에서 Collector/Web 을 시작할 경우 
데이터는 수집 되지만,
AgentInfo 테이블에는 데이터가 들어가지 않네요. ~~~

**Comment by emeroad** [comment]
아직 pinpoint가 agent의 life cycle을 정확히 감지해내지 못하고 있습니다
 - ex: request가 1개 없으면 map에서 보이지 않는 문제

수정할 계획은 있으나 전반적으로 개선이 필요한 문제라 
좀더 시간이 걸릴듯합니다.

**Comment by cowboy93** [comment]
네...
혹시 내일 오전에 시간 되시면 같이 회의하시지요. 
랩장님 뵙기로 했습니다.
