### ISSUE TITLE
How could I add netty3.x dependency in pinpoint-bootstrap-core module ?

### ISSUE THREAD

**Issue by ganpengyu** [naver/pinpoint#4853]
I need to use netty3.x APIs in pinpoint-bootstrap-core module, then I add this dependency in pom.xml. But after `mvn package`, I can not found netty3.x.jar in $AGENT_HOME/lib directory.

I hava tried to add netty3.x.jar in $AGENT_HOME/lib manually, but it dosen't work.

What should I do ?

**Comment by RoySRose** [comment]
Hello, @ganpengyu 

I think this issue isn't relation with Pinpoint.
I think you should take it to Maven.
Hope you find a solution:)
