### ISSUE TITLE
can not visitor web UI, please help!!

### ISSUE THREAD

**Issue by waterystone** [naver/pinpoint#4865]
I download pinpoint-web-1.8.0.war from https://github.com/naver/pinpoint/releases/tag/1.8.0, and deploy it in tomcat-8.5.34。i change tomcat/conf/server.xml as follows:
`<Host name="localhost"  appBase="/opt/pinpoint/pinpoint-web/webapps" unpackWARs="true" autoDeploy="true">`

HBase is also started locally.

tomcat startup log OK, but return 404 when visitor http://localhost:8080/。What is the problem?

![wx20181106-210414](https://user-images.githubusercontent.com/7723467/48066103-a5da5d80-e207-11e8-86c3-800cb3d3c73b.png)

**Comment by RoySRose** [comment]
Hello, @waterystone 

This issue doesn't look like it concerns Pinpoint. 
You should check your tomcat configuration.

**Comment by dean-hu** [comment]
Hello,
I have the same problem,and later found the reason,
you need to name the directory under tomcat webapps as ROOT ，
as shown 
![image](https://user-images.githubusercontent.com/16026242/50631884-fad4ee80-0f80-11e9-9fb3-d773cb8d6e40.png)

**Comment by dean-hu** [comment]
@waterystone
