### ISSUE TITLE
Pinpoint 1.8 mail alarm, please help and help.

### ISSUE THREAD

**Issue by shaojielinux** [naver/pinpoint#4866]
Now I want to implement email alarm, I use version 1.8, but I try to download the source code can not compile, and ask you to help solve the problem of email alarm. Thank you all

**Comment by RoySRose** [comment]
Hello, @shaojielinux 

v1.8.0 is stable. There wasn't any report on the failure of compilation. So I believe there isn't any problem with compiling. you should check your local env.

about setting alarm. [check out here](https://naver.github.io/pinpoint/1.8.0/alarm.html)

**Comment by shaojielinux** [comment]
I use idea15 but the project can't compile. Do I still need to modify the pom file? Is there a detailed project compilation process?

**Comment by shaojielinux** [comment]
I use idea15 but the project can't compile. Do I still need to modify the pom file? Is there a detailed project compilation process?
<img width="294" alt="web" src="https://user-images.githubusercontent.com/28892865/48113560-5b53f200-e296-11e8-9120-934455bc6762.png">

**Comment by RoySRose** [comment]
Hello, @shaojielinux 

There is no need of modifying pom.xml.

There is an [installation guide](https://naver.github.io/pinpoint/installation.html)
But no detailed compilation guide. Because... compilation will be done by one click without any problem.

**Comment by shaojielinux** [comment]
I installed the war package, the default is not without the logic of sending mail? How do I add logic to send mail?

**Comment by RoySRose** [comment]
Hello, @shaojielinux 

check out the guides in the [homepage](http://naver.github.io/pinpoint/1.8.0/main.html#whats-new-in-180) for more features.
alarm guides are [here](https://naver.github.io/pinpoint/alarm.html)
