### ISSUE TITLE
Why Pinpoint don't support other data  storage (like elastic,oracle )

### ISSUE THREAD

**Issue by NiLtheGazettE** [naver/pinpoint#4872]
**Which module is your feature request related to?**
Plugin/UI etc

**Is your feature request related to a problem?**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by emeroad** [comment]
Multiple storage support requires a lot of time and resources.

But we do not have time and resources.

That's why it focuses on hbase.

**Comment by shaocongcong** [comment]
Why use a custom protocol (TCP)? Why not unified thrift?
