### ISSUE TITLE
Bug of ParallelCapablePinpointURLClassLoader : java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by geekMessi** [naver/pinpoint#4881]
**What version of pinpoint are you using?**
v1.7.2 

**Describe the bug**
![image](https://user-images.githubusercontent.com/24689521/48299730-39fc3b80-e50c-11e8-8883-1d78f70fecf1.png)

Precondition ： We replaced the log4j with log4j2 for log4j's poor performance and dead lock problem.

The bug occured while the classpath of application had the `Log4j2Plugins.dat`. The `PluginRegistry#decodeCacheFiles` will load the log4j2Plugins.dat by `loader.getResources(PluginProcessor.PLUGIN_CACHE_FILE)`. The code :
![image](https://user-images.githubusercontent.com/24689521/48300062-a299e700-e511-11e8-986c-2b8118ad6087.png)

But `ParallelCapablePinpointURLClassLoader#loadClass` broken the default extended classloader principle , the ParallelCapablePinpointURLClassLoader will load some filtered class self , not delegate to the parent classloader. While the proplem  came up,  the `ThrowablePatternConverter` would be loaded by ParallelCapablePinpointURLClassLoader and the successor of `ThrowablePatternConverter` , like `ExtendedWhitespaceThrowablePatternConverter`(org.springframework.boot.logging.log4j2)  may be loaded by ParallelCapablePinpointURLClassLoader's parent classloader.Then the NoClassDefFoundError would be throught out.

Is that Clear?

**Comment by emeroad** [comment]
@geekMessi hi
The class delegation policy is determined by `ProfilerLibs`.
 - https://github.com/naver/pinpoint/blob/master/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/classloader/ProfilerLibs.java
 - https://github.com/naver/pinpoint/blob/master/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/PinpointStarter.java#L148

Take a look at `ProfilerLibs`.

**Comment by geekMessi** [comment]
> @geekMessi hi
> The class delegation policy is determined by `ProfilerLibs`.
> 
> * https://github.com/naver/pinpoint/blob/master/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/classloader/ProfilerLibs.java
> * https://github.com/naver/pinpoint/blob/master/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/PinpointStarter.java#L148
> 
> Take a look at `ProfilerLibs`.
---------
 While I got  the `ParallelCapablePinpointURLClassLoader` delegation policy，and I modified the `ProfilerLibs` to adapte the `log4j2 ` lib.

**Comment by geekMessi** [comment]
The solution for this problem is that `ParallelCapablePinpointURLClassLoader` override the `getResources `method ,like this 
```java
 public Enumeration<URL> getResources(String name) throws IOException {
        try {
             //libClass.onLoadResource limit the resourceName,
            // eg : "META-INF/org/apache/logging/log4j/core/config/plugins/Log4j2Plugins.dat", 
            //          "org/slf4j/impl/StaticLoggerBinder.class"
            if (libClass.onLoadResource(name)) {
                return findResources(name);
            }
        } catch (IOException e) {
            //Ignore
        }
        return super.getResources(name);
    }
```

**Comment by emeroad** [comment]
Since pinpoint 1.8.0 The Agent ClassLoader becomes the child of Bootstrap Class Loader.

This behavior solves resource conflicts problem when deploying an application to System ClassLoader.

If you are deploying an application to the System ClassLoader, It is recommended to test with 1.8.0.

**Comment by geekMessi** [comment]
All right , I will have a try.  It looked like that I missed some good story about the new feature.
Thanks for your reply.
