### ISSUE TITLE
Can you please support mongodb?

### ISSUE THREAD

**Issue by rekaparathalwar** [naver/pinpoint#4885]
Can you please add support for MongoDB as well ?

**Comment by RoySRose** [comment]
Hello @rekaparathalwar 

mongoDB plugin is developed #1415 
and being refactored for performance issues. #4884

**Comment by rekaparathalwar** [comment]
Hi @RoySRose  Can you please let me know when it will be available for us to use please ?

**Comment by RoySRose** [comment]
Hello, @rekaparathalwar 

Well. #4884 PR review is almost done and I think any further fix is necessary in close future.
So, after that. You can clone the master and use it.
