### ISSUE TITLE
Proxy Server Config

### ISSUE THREAD

**Issue by imperio-wxm** [naver/pinpoint#4891]
e.g：
```java
  server {
        listen       9080;
        server_name  localhost;

        location / {
            ...
            set $pinpoint_proxy_header "t=$msec D=$request_time";
            proxy_set_header Pinpoint-ProxyNginx $pinpoint_proxy_header;
        }
  }
```

I want to add more info in proxy_set_header:
`$host:$server_port`, `$remote_addr` ,`$proxy_add_x_forwarded_for`

How to set `$pinpoint_proxy_header`, What is the key of these parameters? `t=`,`D=`

**Comment by Xylus** [comment]
Hi @imperio-wxm 
Please take a look at **[ProxyHttpHeaderParser](https://github.com/naver/pinpoint/blob/master/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/plugin/proxy/ProxyHttpHeaderParser.java)**. I think you can find the relevant information there.
