### ISSUE TITLE
Can't open the transaction list pop page

### ISSUE THREAD

**Issue by tiaroy** [naver/pinpoint#4894]
**What version of pinpoint are you using?**
master/v1.8.0  include 1.8.0 src, and release1.8.0 zip, and 1.8.0 docker

**Describe your problem**
I run pinpoin quickstart following the guideline.
I always get a problem when I try to open the transaction detail page to check the stack infomation.
Page always pop a message box with "There is no NG_ENABLE_DEBUG_INFO!quickapp^TOMCAT scatter data in parent window."
But in parent window, there is 59 success and 2 failed request show in the right-top graph.
And I can see the green dots in graph.

**What have you done?**
I validate the test-app, refresh the page, and I can see the success request is increasing in the pinpoint-web console.
So, tracking is working well.
And I can see the information for collector console log, it is working well.
Also, I can see the hbase, the data is increasing.

So, I try the "sourcecode compile", and "download the release files", and "use the official docker", all three mode, I got the same result.

**Screenshots**
<img width="1380" alt="screen shot 2018-11-16 at 9 49 50 am" src="https://user-images.githubusercontent.com/11780112/48593268-03e50e80-e987-11e8-9e0f-d9b05e22302c.png">

<img width="965" alt="screen shot 2018-11-16 at 9 49 35 am" src="https://user-images.githubusercontent.com/11780112/48593257-fb8cd380-e986-11e8-81d7-1d95c74716ca.png">

**Logs**
can't find log files

**Additional context**
My os is macOS 10.14.1

**Comment by tiaroy** [comment]
I met this issue on Chrome browser, (Version 70.0.3538.102 (Official Build) (64-bit))
I just try to use the safari, and it is fine. I can see the transaction detail on safari.

**Comment by denzelsN** [comment]
@tiaroy 
I could not reproduce your problem.
Have you ever updated angularjs?
'NG_ENABLE_DEBUG_INFO' is a phrase not found in 1.2.x
It seems to have been added since 1.3.x.
We did not test 1.3.x.

**Comment by tiaroy** [comment]
@denzelsN, do you mean my local angularjs? Maybe it is. 
But I don't know it is relative to Chrome browser.As I use docker to launch pinpoint-web.
I am fine to use Safari to view. 
It is great! Thank you.
