### ISSUE TITLE
I got two exceptions when I add some features in before() and after() method

### ISSUE THREAD

**Issue by ganpengyu** [naver/pinpoint#4903]
I only need to collect the request that carries the specified parameters. When I add the following code to the before() and after() methods of the class `com.navercorp.pinpoint.plugin.tomcat.interceptor.StandardHostValveInvokeInterceptor` in Tomcat plugin：

```java
if (!trace.canSampled()) {
    // .....
    return;
}
//  code I added begin
final HttpServletRequest request = (HttpServletRequest) args[0];
String tag = request.getHeader("isNeeded");
if (StringUtils.isEmpty(tag) && trace.isRoot()) {
    return;
}
//  code I added end
try {
} catch () {
} finally {
}
```
The above code indicates that if this is a Root request but does not carry the specified Header, then I will not collect it.

The Agent log will always have two exceptions, one is `not empty call stack`, another is `already closed trace`.

How should I avoid these two exceptions?

**Comment by emeroad** [comment]
This error message occurs because the life cycle of the trace object is not properly managed.

https://github.com/naver/pinpoint/blob/1.7.x/plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/StandardHostValveInvokeInterceptor.java#L197
I think your code should be in `StandardHostValveInvokeInterceptor.samplingEnable()`

**Comment by ganpengyu** [comment]
> This error message occurs because the life cycle of the trace object is not properly managed.
> 
> https://github.com/naver/pinpoint/blob/1.7.x/plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/StandardHostValveInvokeInterceptor.java#L197
> I think your code should be in `StandardHostValveInvokeInterceptor.samplingEnable()`

Thank you very much for your reply. I only need to track the request that carries the specified parameters, and this parameter will be removed when making other calls. So I have to make sure that the request is an entry, ie trace.isRoot() must return true. But in samplingEnable() I can only tell if I have carried the specified parameters. If this is not the entry point for a request, then my judgment will be wrong.

**Comment by emeroad** [comment]
https://github.com/naver/pinpoint/blob/1.7.x/plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/StandardHostValveInvokeInterceptor.java#L211

Maybe you should check `TraceId.isRoot()` before line 211.

```java 
        if (traceId != null) {
            // pseudocode
            if (traceId.isRoot() && checkTag()) {
                   Trace trace= traceCOntext.disableTraceObject();
             } else 
                // TODO Maybe we should decide to trace or not even if the sampling flag is true to prevent too many requests are traced.
                final Trace trace = traceContext.continueTraceObject(traceId);
                ~~~~~
````
