### ISSUE TITLE
agent端有选择的采集数据

### ISSUE THREAD

**Issue by ljx199** [naver/pinpoint#4915]
初学者，在多微服务应用中用到了consul的健康检查，导致pinpoint agent在采集数据时会采集到大量健康检查，想了解下关于agent端采集数据，实在哪一个类中屏蔽不需要的数据？谢谢

**Comment by yu412346928** [comment]
我使用springboot(内嵌tomct8)无法收集到信息。
软件版本如下：
hbase-1.2.6
pinpoint-agent-1.6.2
pinpoint-collector-1.6.2
pinpoint-web-1.6.2

测试项目：
tomcat7:  可以采集到信息
springboot-1.5.4(Embedded tomcat-8.5.15) ：无法采集到信息

**Comment by ITGrocery** [comment]
> 初学者，在多微服务应用中用到了consul的健康检查，导致pinpoint agent在采集数据时会采集到大量健康检查，想了解下关于agent端采集数据，实在哪一个类中屏蔽不需要的数据？谢谢

pinpoint-agent 中的 pinpoint.config 可以进行一些配置，具体得看你那些数据是哪些插件采集到的。

**Comment by RoySRose** [comment]
Hello, @ljx199 @yu412346928 @ITGrocery 

please note that when you write a comment on a GitHub issue,
by default, a notification email is sent to every participant and the maintainers

when your comment is not in english, you are essentially sending us messages in your own language, which we all can't understand.

please reconsider using just English. Thanks ;)

**Comment by RoySRose** [comment]
@ITGrocery 

Thanks, have a nice day~
