### ISSUE TITLE
Agent need not collect microservice's  healthCheck info

### ISSUE THREAD

**Issue by huangchaobing** [naver/pinpoint#4921]
When we develop microservice  with spring boot and spring cloud,we use pinpoint to collect request link data,if we don't want to collect microservice itself's healthCheck information,how to modify agent source?

**Comment by Xylus** [comment]
Hi @huangchaobing 
You can add your healthCheck urls to (if you're using Tomcat in Spring Boot) `profiler.tomcat.excludeurl` in *pinpoint.config*.

**Comment by huangchaobing** [comment]
@Xylus thanks,this question has been settled by your way.
