### ISSUE TITLE
it seems alarm not work

### ISSUE THREAD

**Issue by light0x000** [naver/pinpoint#4931]
### alarm rule
<img width="999" alt="image" src="https://user-images.githubusercontent.com/29830476/49219647-d8dece00-f40e-11e8-9880-6c16a3a6b4ad.png">

### batch.properties
```
#batch enable config
batch.enable=true
#batch server ip to execute batch
batch.server.ip=127.0.0.1
#flink server list
batch.flink.server=
```
### the error and slow request
<img width="1485" alt="image" src="https://user-images.githubusercontent.com/29830476/49220213-97e7b900-f410-11e8-902b-b6f081fa9548.png">

### I see the following line of code has never execute
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/29830476/49220103-39223f80-f410-11e8-9385-8e971a342afc.png">

**Comment by minwoo-jung** [comment]
@light0x000
Please ref https://github.com/naver/pinpoint/issues/1149

We will update guide for transmission frequency

**Comment by light0x000** [comment]
> @light0x000
> Please ref #1149
> 
> We will update guide for transmission frequency

emm,thanks.🙂️
I saw "transmission frequency" in the pinpoint documentation .
but now , alarm never triggered once

**Comment by light0x000** [comment]
> batch
Ok, I will try.😸

**Comment by minwoo-jung** [comment]
@light0x000
Thank you for your explanation.

I think you should see collector server log. 
You should find log for received method of com.navercorp.pinpoint.collector.dao.hbase.HbaseMapResponseTimeDao. 

```
    @Override
    public void received(String applicationName, ServiceType applicationServiceType, String agentId, int elapsed, boolean isError) {
        if (applicationName == null) {
            throw new NullPointerException("applicationName must not be null");
        }
        if (agentId == null) {
            throw new NullPointerException("agentId must not be null");
        }

        if (logger.isDebugEnabled()) {
            logger.debug("[Received] {} ({})[{}]", applicationName, applicationServiceType, agentId);
        }
```
You should check that ApplicationMapStatisticsSelf_Ver2 table data is normally stored.
 
Maybe you need to change log level to DEBUG.^^

**Comment by light0x000** [comment]
> @light0x000
> Thank you for your explanation.
> there are several ways to find cause problem.
> ### 1.
> 
> I think you should see collector server log.
> You should find log for received method of com.navercorp.pinpoint.collector.dao.hbase.HbaseMapResponseTimeDao.
> 
> ```
>     @Override
>     public void received(String applicationName, ServiceType applicationServiceType, String agentId, int elapsed, boolean isError) {
>         if (applicationName == null) {
>             throw new NullPointerException("applicationName must not be null");
>         }
>         if (agentId == null) {
>             throw new NullPointerException("agentId must not be null");
>         }
> 
>         if (logger.isDebugEnabled()) {
>             logger.debug("[Received] {} ({})[{}]", applicationName, applicationServiceType, agentId);
>         }
> ```
> 
> You should check that ApplicationMapStatisticsSelf_Ver2 table data is normally stored.
> 
> Maybe you need to change log level to DEBUG.^^
> ### 2
> 
> is server map clearly shown main page?
> Please ref #4673
> Please check [hbase version compatibility](https://github.com/naver/pinpoint#compatibility)

thank you, I have solved it! 
The cause is that the hbase version is not compatible. (my hbase version is 2.1)

by the way, 
i find the hbase.1.2.9 is also not compatibility.  hbase.1.2.7 is ok.

**Comment by minwoo-jung** [comment]
@light0x000
Congratulations to solve.^^ 
You explained problem well. So It's easy to answer.
