### ISSUE TITLE
How to detect the AsyncTrace Created By the Inner Interceptor of another plugin

### ISSUE THREAD

**Issue by geekMessi** [naver/pinpoint#4959]
Does the outer Interceptor  can detect the `AsyncContext`  created by the  Inner Interceptor `WrappedSpanEventRecorder#recordNextAsyncContext()` ?
While the inner interceptor and the outer interceptor belong to  different plugins,  they cannot share the scope or get the `AsyncContext` By ` AsyncContextAccessor`.

**Comment by Xylus** [comment]
Hi @geekMessi 
I don't fully understand your question. If you could provide more detail, it would help us a lot.

That said, trace propagation over thread boundaries are done by injecting `AsyncContext` into an object that is shared by the 2 threads. The interceptor on the caller creates and injects `AsyncContext` into this object, then the interceptor on the target takes `AsyncContext` out of the object and continues the trace.

**Comment by geekMessi** [comment]
![interceptor](https://user-images.githubusercontent.com/24689521/49560027-de2aa400-f94b-11e8-95d3-36491d200f67.png)

Or the OuterInterceptor just known that some innerceptors once created a AsyncContext in this Trace Span.

**Comment by emeroad** [comment]
Currently, AsyncContext does not support nested state.
I'm thinking about this problem, but I have not implemented it yet.
I think we can solve it in the future.
