### ISSUE TITLE
How do I chain multiple proxy

### ISSUE THREAD

**Issue by pbusquemdf** [naver/pinpoint#4960]
According to the wiki, we can add reference to a proxy (apache or an Nginx)  by setting an header in them.
https://github.com/naver/pinpoint/blob/master/doc/proxy-http-header.md

But what about a scenario where we chain multiple proxy?
Example
User -> WAF -> SSL Terminator -> Load Balancer -> Web Server -> App Server
How can we add information regarding such a chain of proxy from various vendors?

**Comment by emeroad** [comment]
We are planning to change the header handler to a plugin.
The header plugin can be used to change the desired header processing format.
