### ISSUE TITLE
Relation between tomcat not showing

### ISSUE THREAD

**Issue by pbusquemdf** [naver/pinpoint#4962]
**What version of pinpoint are you using?**
1.8.0

Our setup is the following
1 Web Server
2 front end (tomcat)
2 search engine (tomcat)
1 Security Manager  (tomcat)

Each of those 5 Tomcat servers are running the PinPoint agent and labeled accordingly (search have the same Application name, the front have have the same application name, etc).

Calls made to the security manager and Search engine are trapped by Pinpoint, appears but are not identified as their own application node, as shown in the demo.  They are all grouped as "Cloud" in the diagram.

Each of those call are made through the common httpClient 3.1 which is supported. Is there some other configuration that need to be done in order to link all other application node together?

**Comment by pbusquemdf** [comment]
![diagram](https://user-images.githubusercontent.com/15897881/49542583-06f75e80-f8a4-11e8-89f3-040037e14158.png)

**Comment by Xylus** [comment]
Hi @pbusquemdf 
All nodes should appear grouped by their application names in the server map without additional configuration.
There's definitely something going on here.

Could you post (or email me) the DEBUG log of your pinpoint-web containing the logs generated when you queried for the server map you posted?
(It should have logs like `Finding accept applications for ...`)
