### ISSUE TITLE
How can I dynamically change the loglevel in pinpoint

### ISSUE THREAD

**Issue by ljx199** [naver/pinpoint#4991]
I have seen the method of modifying parameter in agent-log4j.xml , however,This method is not what I need , How could I change the logLevel dynamically? Thank U!

**Comment by emeroad** [comment]
Currently, pinpoint does not support dynamic changes.

**Comment by ljx199** [comment]
1.Can you give me a general idea if I need to dynamically modify the log level?

2.In which class does pinpoint set the log level? Or in code, where does the program read the log level in the XML file?

Thank U!
