### ISSUE TITLE
no data shown on web UI(netty)

### ISSUE THREAD

**Issue by jiangshuaifeng** [naver/pinpoint#5003]

**Comment by jiangshuaifeng** [comment]
pinpoint version:1.8.0
pinpoint.config has be seted:
profiler.netty=true
profiler.netty.http=true
but its not work

**Comment by koo-taejin** [comment]
I didn't get enough information to help you. 
If you can give me a reproduce situation, I'll check it.

**Comment by jiangshuaifeng** [comment]
thanks。
I deployed agent and collector in the same machine,Two applications are configured in the same agent.
spring boot and netty
only spring boot was ok.
I don't know what's wrong. 
Is there a special configuration for netty? 
What kind of information do you need?

**Comment by jiangshuaifeng** [comment]
hi,koo-taejin
I have sent you an email. There's my application in it. 
Do you need additional information?
