### ISSUE TITLE
How should I add extra dependencies to pinpoint?

### ISSUE THREAD

**Issue by ganpengyu** [naver/pinpoint#5015]
I need to add a Kafka-Client dependency to the Pinpoint Agent. I added the configuration in the following three pom.xml files.

`parent pom.xml`

```xml
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-clients</artifactId>
            <version>0.11.0.3</version>
        </dependency>
    </dependencies>
</dependencyManagement>
```

`pinpoint-agent/pom.xml` and `pinpoint-bootstrap-core/pom.xml`

```xml
<dependencies>
    <dependency>
        <groupId>org.apache.kafka</groupId>
        <artifactId>kafka-clients</artifactId>
    </dependency>
</dependencies>
```

After the build is complete, kafka-clients-0.11.0.3.jar does exist in the lib directory of pinpoint-agent.

I created the Kafka Producer for sending data in the pinpoint-bootstrap-core project. But when the Pinpoint Agent starts, it is not prompted to find the class abount Kafka clients.

So I guess Pinpoint has additional requirements for adding dependencies. What should I do to successfully add Kafka-related dependencies?

TO PROJECT MANAGER：Please DO NOT close my question，I really can't find a solution, so come here to ask. THANKS!!!

**Comment by koo-taejin** [comment]
Please check following file.

`agent / src / assembly / distribution.xml`

**Comment by ganpengyu** [comment]
> Please check following file.
> 
> `agent / src / assembly / distribution.xml`

I tried to include kafka-client into boot directory and exclude it from lib directory，but agent still throw `java.lang.NoClassDefFoundError: org/apache/kafka/common/serialization/StringSerializer`。

```xml
<dependencySet>
  <includes>
    <include>......</include>
    <include>org.apache.kafka:kafka-clients</include>
  </includes>
  <outputDirectory>boot</outputDirectory>
</dependencySet>

<dependencySet>
  <excludes>
    <exclude>......</exclude>
    <exclude>org.apache.kafka:kafka-clients</exclude>
    <exclude>*:pom</exclude>
  </excludes>
  <outputDirectory>lib</outputDirectory>
  <useProjectArtifact>false</useProjectArtifact>
  <useTransitiveFiltering>true</useTransitiveFiltering>
</dependencySet>
```

**Comment by koo-taejin** [comment]
I misunderstood your question.

Including the jar file in the location is possible with maven configuration.
However, some code needs to be changed in order to actually run it.

Perhaps `com.navercorp.pinpoint.bootstrap.agentdir.AgentDirBaseClassPathResolver`
If you edit above class and related above class, you can do what you want.

**Comment by ganpengyu** [comment]
> I misunderstood your question.
> 
> Including the jar file in the location is possible with maven configuration.
> However, some code needs to be changed in order to actually run it.
> 
> Perhaps `com.navercorp.pinpoint.bootstrap.agentdir.AgentDirBaseClassPathResolver`
> If you edit above class and related above class, you can do what you want.

Yes, the new jar files in the `boot` directory need to be modified by the Class `AgentDirBaseClassPathResolver` to be loaded by the BootstrapClassLoader.

I have solved my problem, Thanks！

BTW，why is Pinpoint so designed? Isn't it possible to use other class loaders?

**Comment by emeroad** [comment]
Do not include application lib in the pinpoint.
Including application lib in a pinpoint will cause class conflict problem.

**Comment by ganpengyu** [comment]
> Do not include application lib in the pinpoint.
> Including application lib in a pinpoint will cause class conflict problem.

I am not going to put the application jar into the pinpoint. I want to add the way the pinpoint agent sends data to the collector, so I need to add the kafka jar to the boot directory.
