### ISSUE TITLE
How to decode data in Hbase into relational database or streaming database

### ISSUE THREAD

**Issue by GhotsboyD** [naver/pinpoint#5019]
Hello, I have successfully deployed the PinPoint project and want to do secondary development.
At present, I want to get the data stored by PinPoint in HBase, but I use a SQL statement in Hbase to find that the data is hexadecimal.
I would like to ask how to decode the hexadecimal encoded data stored by PinPoint in HBase.

Looking forward to your answer
thank you.

**Comment by emeroad** [comment]
Refer to the source code below.
 - https://github.com/naver/pinpoint/blob/master/web/src/main/java/com/navercorp/pinpoint/web/mapper/SqlMetaDataMapper.java
 - https://github.com/naver/pinpoint/blob/master/collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseSqlMetaDataDao.java

**Comment by dongjunwen** [comment]
@emeroad 上面大哥的意思很清楚，你这个没有参考价值啊。我看了代码，关键难点在查询出来的数据如何转换成正常格式。每个表的每一行每一列处理方式都不一样，感觉很难做到。能不能在后续版本里添加一个工具类或者添加兼容关系型数据库或者提供多种方式的API进行查询操作？

**Comment by minwoo-jung** [comment]
@dongjunwen
 Hello, please translate your issue into English for the community.

**Comment by kartikzheng** [comment]
> Refer to the source code below.
> 
> * https://github.com/naver/pinpoint/blob/master/web/src/main/java/com/navercorp/pinpoint/web/mapper/SqlMetaDataMapper.java
> * https://github.com/naver/pinpoint/blob/master/collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/HbaseSqlMetaDataDao.java

I have the same problem. Can I directly convert hexadecimal in hbase Shell? I tried toString and it didn't work

**Comment by minwoo-jung** [comment]
@kartikzheng 
It is not possible to view the data readable in the hbase shell.

**Comment by kartikzheng** [comment]
@minwoo-jung
In what ways can I view hbase data? thank you.

**Comment by minwoo-jung** [comment]
If you want to see specific data directly rather than in the web view, there is no other way than to see the dao structure and decode it directly as https://github.com/pinpoint-apm/pinpoint/issues/5019#issuecomment-448072668
