### ISSUE TITLE
To use pinpoin,enable cookies and JavaScript

### ISSUE THREAD

**Issue by shenhongwei33** [naver/pinpoint#5020]
**What version of pinpoint are you using?**
Pinpoint version: 1.8.0-SNAPSHOT
Win10 tomcat
Additional details (e.g. how your collector/web is set up): I downloaded the source code from the official website, and started it locally after the package was successfully packaged.
Browsers: Google Chrome

**Describe your problem**
When I type http://localhost:8080, I can't open the interface.
![image](https://user-images.githubusercontent.com/26289219/50127588-bf61d100-02ac-11e9-965c-a24ff1eb37f2.png)

**What have you done?**
Steps you have taken to trigger the problem, for example:
1. Packaged with the clean install -DskipTests=true -X command
2.Configure the web configuration file, put the web war package in the tomcat webapps path
3.Start tomcat

**Screenshots**

![image](https://user-images.githubusercontent.com/26289219/50127695-2aaba300-02ad-11e9-821f-710f6c7123ac.png)

**Additional context**
No output in the tomcat log.This is a bug in the browser output.What is the problem?
![image](https://user-images.githubusercontent.com/26289219/50128105-c38eee00-02ae-11e9-89c7-4263fa5ea4b8.png)

**Comment by zhongyong** [comment]
me too 
configuration

**Comment by VIPJoey** [comment]
me too, how to deal with it?
