### ISSUE TITLE
pinpoint-collector how to collect information in Http request header

### ISSUE THREAD

**Issue by ljx199** [naver/pinpoint#5022]
I'm going to add business keywords to the HTTP request header ，and I want to ask pinpoint-collector how to collect them.

**Comment by koo-taejin** [comment]
Pinpoint does not store custom header that user specified.

**Comment by huangchaobing** [comment]
@koo-taejin Source code of Pinpoint can collect request parameters,I want to know if I want to collect some  user specified request headers,what should I do or which class is modified I need to modify,thanks!

**Comment by koo-taejin** [comment]
@huangchaobing 

If you want to store custom header, then you need to modify the plugin's code.
https://github.com/koo-taejin/pinpoint-plugin-sample/tree/master/plugin/src/main/java/com/navercorp/pinpoint/plugin/sample
Here's a lot of help.

Personally, I do not recommend changing the code within a plugin or agent.

thanks.
