### ISSUE TITLE
Use of weblogic plugin

### ISSUE THREAD

**Issue by daronaldo** [naver/pinpoint#5024]
hello,I am new to use of Pinpoint; I have recently installed it and I want to monitor an application that is on a WebLogic server. my question is : in the following link u'll find out how to use weblogic plugin:
https://github.com/naver/pinpoint/tree/master/plugins/weblogic
but,It doesn’t work even if I did everything as the following link told.Could i use the pinpoint-weblogic-plugin-1.6.0.jar instead of pinpoint-bootstrap-$VERSION.jar?DO i set up agentId and applicationName on startWeblogic.sh?

**Comment by koo-taejin** [comment]
Take a look at how to use pinpoint.
Pinpoint agents must include a bootstrap jar.
