### ISSUE TITLE
In which source code can you find the "handle exception class" source code?

### ISSUE THREAD

**Issue by tonfay** [naver/pinpoint#5030]
Hello!
Because of a custom exception class in my project, and thrown.
Pinpoing also need to do a warning, but pinpoing has not been identified as an anomaly.
Q: where can I add the exception class。

Nothing below.

**Comment by koo-taejin** [comment]
If an exception occurs during the statement within the trace, an exception is displayed at the pinpoint.
However, Pinpoint does not display exception when if an exception is handled before passing the statement within the trace, or if an exception is thrown in a statement that the not trace.

**Comment by simoelmou** [comment]
@koo-taejin  what do you mean by "statement" because I handle the exception but it's displayed so the request is marked as failed.

**Comment by koo-taejin** [comment]
@simoelmou 

If the method below is the target method of the trace and the exception is handled within the method, no exception is recorded.
```
void traceMethod() {
	try {
		...
	catch (Exception e) }
	}
}
```

However, if an exception is caught outside of the  target method of the trace as shown below, an exception will be recorded.
```
void callMethod() {

	try {
		traceMethod()
	catch (Exception e) }
	}

}

void traceMethod() {
	throw runtimeException;
}

**Comment by simoelmou** [comment]
@koo-taejin But the traceMethod() exception is caught inside of callMethod() why would it be recorded, so let's say it's a JDBC exception then it would be caught inside of the callMethod() and it should not be recorded. Can you please give an example with two traced methods which one would throw an exception and the exception would not be displayed?

**Comment by koo-taejin** [comment]
@simoelmou 
This is a very difficult issue.
Some people may find it more problematic not to see exceptions thrown within the method.
To solve this, it would not be a good idea to make options for every method.

Actually, we have a lot of thnking that ScatterChart records a failed request when an exception occurs.
We are working  to solve this problem.
(One of these things is to view the http status code and record it as failed.)
