### ISSUE TITLE
Which task is sending mail?

### ISSUE THREAD

**Issue by gaoyaqiu** [naver/pinpoint#5035]
Which task is sending mail?
After the alarm is configured, the email is not received. There is no abnormality in the log. How to troubleshoot the problem?

![image](https://user-images.githubusercontent.com/8586794/50326374-fd692a00-0524-11e9-92fa-101163911e45.png)
![image](https://user-images.githubusercontent.com/8586794/50326387-0954ec00-0525-11e9-9193-034765ee834b.png)

**Comment by minwoo-jung** [comment]
Hello @gaoyaqiu

You should see batch log in pinpoint-web.
