### ISSUE TITLE
What' RPC mean in TSpanEvent?

### ISSUE THREAD

**Issue by shaocongcong** [naver/pinpoint#5041]
it's mean str'id or api'id?

**Comment by emeroad** [comment]
The RPC field in SpanEvent is a deprecated field.
It will be completely removed in the future.

https://github.com/naver/pinpoint/blob/master/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/SpanEvent.java#L138

**Comment by shaocongcong** [comment]
Thank you very much！
