### ISSUE TITLE
Corrupted(invalid sequence)

### ISSUE THREAD

**Issue by CHENTIANHAO123** [naver/pinpoint#5046]
Hello team,I found a lot of Corrupted(invalid sequence) and a lot of rejected log in collector.
Should I increase Hbase performance? And How to do?   thanks!

**Comment by Xylus** [comment]
Hi @CHENTIANHAO123 
You can horizontally scale hbase by adding more region servers (is you're running hbase in distributed mode).
Please check the hbase documentation on how to do this.
