### ISSUE TITLE
Group the request and report the call-chain by the request group. 

### ISSUE THREAD

**Issue by xiaoshao** [naver/pinpoint#5048]
**Which module is your feature request related to?**
ALL

**Is your feature request related to a problem?**
NO

**Describe the solution you'd like**
I found that the requests are grouped by the business in some apm product for example the dynatrace.

For example when the target app is based on spring mvc.
The requests are grouped by the handler methods which has RequestMapping annotations.
And report the call-chain data by the group.

**Describe alternatives you've considered**

**Additional context**

**Comment by xiaoshao** [comment]
hi guys, I am a java developer and I am interested in pinpoint. If pinpoint plan to accept my suggestion, I can contribute my code. thanks guys.  looking forward for your final decision.

**Comment by emeroad** [comment]
@xiaoshao Hi
I do not know what call-chain means.
Does this feature mean URL statistics?

Example Screenshot
https://github.com/slanatech/swagger-stats/raw/master/screenshots/methods.png?raw=true
![image](https://user-images.githubusercontent.com/7564547/50500675-41fd4400-0a96-11e9-98e7-d55d05cff10a.png)

**Comment by xiaoshao** [comment]
sorry, we named the call stack in pinpoint with call-chain.

Yes, I suggest to group the call stack with URL statistics.

For example there is some code in the Spring MVC as following.

```
@Controller
public class SecondController {

    @GetMapping("/address/{name}")
    @ResponseBody
    public List<String> address(@PathVariable("name") String name) {
        List<String> address = new ArrayList<>();
        address.add("first");
        address.add("second");
        return address;
    }
}
``` 

We can group the callstack all the request which is handled by the annotation of the method `address`, even more we can report the callstack by this to avoid that some handler is missed.

what do you think about it.

**Comment by emeroad** [comment]
We welcome your suggestions

I agree with your idea.
We have plans to aggregate statistical data into the RequestMapping annotations, 
but we do not have enough time to develop.

Below is our idea.
1. Use RequestMapping annotation.
    - When using real url, it is difficult to aggregate rest style url
       - eg: /book/{id}/
2. Unable to handle annotation in bytecode api
   - We will add API.
   - If the annotation data can be extracted to the runtime, API addition is unnecessary
3. Aggregation plan
    1. agent memory
    2. collector
      - Use the `Table.incrementColumnValue()` API of hbase
    3. flink
    **Not determined**
  4. Data type
    1. Histogram
        - Counts 1s, 3s, 5s
     2. total reponse time
    **Not determined**

**Comment by xiaoshao** [comment]
https://github.com/naver/pinpoint/pull/5054 is on the way
