### ISSUE TITLE
How show all entire chain of Micro Service？

### ISSUE THREAD

**Issue by jiazhiyuan** [naver/pinpoint#5057]
Our project is based on Micro Service. I config profiler.applicationservertype=SPRING_BOOT, but can not see any chain of Micro Service on website. Can you help me slove this problem?
![image](https://user-images.githubusercontent.com/15151382/50578897-d5f65380-0e7a-11e9-93c1-83b22fcb1af5.png)

**Comment by Xylus** [comment]
Hi @jiazhiyuan 
Please post using the [troubleshooting](https://github.com/naver/pinpoint/issues/new?template=troubleshooting.md) template.
Agent log and some description of what your spring boot application is doing and what you're expecting to see would help.
