### ISSUE TITLE
How to Change the Sampling Time and Frequency of Log Collection

### ISSUE THREAD

**Issue by ljx199** [naver/pinpoint#5058]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

**Comment by ljx199** [comment]
In the pinpoint web interface, I saw the optional sampling time and frequency in the load chart. I would like to ask which class files this is configured in

**Comment by RoySRose** [comment]
hello @ljx199 

the sampling rate of the transactions can be configured from Pinpoint configuration file.
But I assume you are talking about the duration of each transactions shown in the `load chart`.
The one with 1,3,5 seconds.
If this is what you're talking about, Pinpoint doesn't suppport configuration of this feature. Currently it's stuck to 1,3,5 secs.

**Comment by ljx199** [comment]
hello @RoySRose

thanks ，I want to ask you a question,where set 1,3,5 seconds in pinpoint？
Or is this configuration configured on the web front end?

**Comment by RoySRose** [comment]
@ljx199 as mentioned above. Pinpoint doesn't support configuration of this feature. Currently, You can't change it.
