### ISSUE TITLE
Uncaught ReferenceError: isSingleClick is not defined 1.8.1 web chrome browser

### ISSUE THREAD

**Issue by yin-bp** [naver/pinpoint#5087]
#### What version of pinpoint are you using?
master/v1.8.1/v1.9.0 and released 1.8.1.

#### Describe the bug
Uncaught ReferenceError: isSingleClick is not defined
    at SlickGrid.<anonymous> (pinpoint.js:12144)
    at c.notify (util-lib.min.js?v=1546477412991:15)
    at trigger (util-lib.min.js?v=1546477412991:16)
    at HTMLDivElement.handleDblClick (util-lib.min.js?v=1546477412991:17)
    at HTMLDivElement.dispatch (base-lib.min.js?v=1546477412991:2)
    at HTMLDivElement.b.dispatch (util-lib.min.js?v=1546477412991:15)
    at HTMLDivElement.q.handle (base-lib.min.js?v=1546477412991:2)
(anonymous) @ pinpoint.js:12144
notify @ util-lib.min.js?v=1546477412991:15
trigger @ util-lib.min.js?v=1546477412991:16
handleDblClick @ util-lib.min.js?v=1546477412991:17
dispatch @ base-lib.min.js?v=1546477412991:2
b.dispatch @ util-lib.min.js?v=1546477412991:15
q.handle @ base-lib.min.js?v=1546477412991:2

#### What did you do to trigger the bug?
![GitHub Logo](https://www.bbossgroups.com/include/bug.png)

**Comment by yin-bp** [comment]
Problem solved, Thanks.

**Comment by cribbstechnologies** [comment]
This is closed but I'm still seeing the problem in 1.8.4 downloaded on 6/27. Was this fix not included in this release or maybe it was lost during a merge? It looks okay in the 1.8.0 branch but it's definitely wrong in the file in the war that I downloaded.
https://github.com/denzelsN/pinpoint/blob/1.8.0/web/src/main/webapp/features/distributedCallFlow/distributed-call-flow.directive.js

**Comment by fionaliupw** [comment]
@emeroad Hi, i also seeing the same problem in 1.8.2. could you help to solve the problem? Thanks.

**Comment by fionaliupw** [comment]
Problem solved, thanks.
