### ISSUE TITLE
does pinpoint collect which services are so hot and show them? where can i get this info?

### ISSUE THREAD

**Issue by rambolijian** [naver/pinpoint#5095]
I want to know, pinpoint has collection function about hot service, and will show them?

because this will help us testing the hot service. have it?

thanks you very much!

**Comment by rambolijian** [comment]
anywhere will show the hot API services?

**Comment by minwoo-jung** [comment]
Unfortunately, pinpoint does not automatically detect hot servers. But you can use an alarm to detect it.
