### ISSUE TITLE
Whether pinpoint has the function of jvisual VM

### ISSUE THREAD

**Issue by kelvin0305** [naver/pinpoint#5113]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

**Comment by koo-taejin** [comment]
Some are there, some are not.
