### ISSUE TITLE
question about profiler.entrypoint

### ISSUE THREAD

**Issue by dongja3** [naver/pinpoint#5116]
in this post https://github.com/naver/pinpoint/issues/1547, I found 

> To trace transactions, you need a starting point. For WASes, these are usually the acceptor methods where a new transaction is started when a request is received.
> 
> For standalone applications, there are no predefined starting point to start transactions so you'll need to specify them manually. The profiler.entrypoint option in the agent's pinpoint.config file allow you to do this.
> 
> For example, if you''re running some method foo.bar.MyClass.myMethod() in intervals using cron, specifying profiler.entrypoint=foo.bar.MyClass.myMethod allows the agent to start a new transaction when this method is called. Methods that are called from this method (such as DB calls) are automatically traced so you'll only need to specify the starting method.

However,  if I specified foo.bar.MyClass.myMethod1, and in my code foo.bar.MyClass.myMethod1 calls foo.bar.MyClass.myMethod2, seems foo.bar.MyClass.myMethod2 will not be automatically traced. may I know which kind of method will be traced after I specify customized entrypoint?

**Comment by dongja3** [comment]
Hi, Pinpoint master?
Can you help to answer?

**Comment by RoySRose** [comment]
Hello, @dongja3 

[Here is the list](https://naver.github.io/pinpoint/main.html#full-list-of-supported-modules) that is traced

**Comment by dongja3** [comment]
Hello @RoySRose 
I understand, thanks for your answer.
