### ISSUE TITLE
does pinpoint support application written in C#? or other does ?

### ISSUE THREAD

**Issue by KarainYang** [naver/pinpoint#5121]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

**Comment by RoySRose** [comment]
Hello, @KarainYang 

Currently, Pinpoint supports applications written in PHP ([PHP-agent](https://github.com/naver/pinpoint-c-agent))

node.js-agent is on the way.
