### ISSUE TITLE
Does pinpont support spring-boot asynchronous threads?When can asynchronous threads be supported？

### ISSUE THREAD

**Issue by kelvin0305** [naver/pinpoint#5122]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

**Comment by Xylus** [comment]
@kelvin0305 
Are you talking about tracing `@Async` methods?
If so, it's been added 1.8.0, and the relevant configuration is [here](https://github.com/naver/pinpoint/blob/master/agent/src/main/resources-local/pinpoint.config#L726).
