### ISSUE TITLE
is it a bug or centos 6.5's problem

### ISSUE THREAD

**Issue by shotgun88** [naver/pinpoint#5125]
i have no idea why i can deploy agent on others machine(Centos 6.8 Final),but not this normal machine which System is Centos 6.5 Final.
i just as usual download the latest agent-1.8.1.tar.gz and tar -zxvf pinpoint-agent-1.8.1.tar.gz
and then fix pinpoint.config(profiler.collector.ip) and fix catalina.sh(add some configuration) on tomcat
when i start up the tomcat application the problem comes up
which the tomcat application is up with agent information also can access website
but the agent did not comes up logs even the collector can not detective agent's application on this Centos 6.5 Final machine.
howerver the others machine are work it out! 

please see problem's detail as attachment

![image](https://user-images.githubusercontent.com/42365630/51019623-891b2700-15b6-11e9-8958-f486ee413885.png)
![qq 20190111153200](https://user-images.githubusercontent.com/42365630/51019631-96381600-15b6-11e9-9cb7-4987a33debfa.png)
![qq 20190111153116](https://user-images.githubusercontent.com/42365630/51019638-9df7ba80-15b6-11e9-9766-fcf9312d9b29.png)

**Comment by Xylus** [comment]
Hi @shotgun88 
There's no `-javaagent` option set? (Or does jps option not show this?)

**Comment by shotgun88** [comment]
yes,i'm already add up -javaagent option set as below:
![w hhnnc0c j0 03pixqhw](https://user-images.githubusercontent.com/42365630/51098586-4bacd880-1806-11e9-9364-8e6a5df0cba9.png)
but the jps option didnt show up(so upset)
i dont know why i'm do the same option set on other mechine was fine,but not this mechine can not able to detect application .
all i can see the difference is the system was centos 6.5 Final...

**Comment by shotgun88** [comment]
and also the agent's log did not come up,so the agent's service was not turn on
so the key point was what reason lead to agent's not turn on
![t3 k lv839 yf u 2mh 6](https://user-images.githubusercontent.com/42365630/51099624-d4c70e00-180c-11e9-830a-23f2e4d4046e.png)

**Comment by koo-taejin** [comment]
Perhaps your CATALINA_OPT variable is supposed to be overwritten somewhere.
Resolve this issue first

**Comment by shotgun88** [comment]
could u please let me know where exactly to be overwritten?maybe give me some references?
i've check anywhere but i have no idea what exactly happened...

**Comment by Xylus** [comment]
If the `-agentpath:/opt/dynatrace/oneagent/...` an option for Dynatrace agent?
If so, maybe it's in conflict with pinpoint agent?
