### ISSUE TITLE
Unable to collect springboot info

### ISSUE THREAD

**Issue by allenhan** [naver/pinpoint#5127]
hi
  i cant not view the callback log but can view the performance log. i had also do with #2616 ,but it not work for me. 

   My Environment:

  os: centos 7
   jdk  : openjdk version "1.8.0_191"
  pinpoint :1.8.1

  
![image](https://user-images.githubusercontent.com/5449138/51022650-d0f27c00-15bf-11e9-919d-1901af548a22.png)

here is my log address
https://raw.githubusercontent.com/allenhan/log/master/10001-pinpoint.log

 looking forward to your reply.

**Comment by Xylus** [comment]
Hi @allenhan 
What kind of server (if at all) are you running on your spring boot application?

**Comment by Xylus** [comment]
@allenhan 
Please refer to [this](http://naver.github.io/pinpoint/faq.html#my-custom-jar-application-is-not-being-traced-help) FAQ.

**Comment by allenhan** [comment]
thanks.
i got it.
