### ISSUE TITLE
com.navercorp.pinpoint.rpc.PinpointSocketException: timeout

### ISSUE THREAD

**Issue by springClound-Wang** [naver/pinpoint#5136]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
master/v1.7.3/v1.7.2 etc.

#### What did you do to trigger the bug?
Steps to reproduce, for example:
1. Ran '...' with agent attached
2. '...' method invoked
3. '...' interceptor threw '...' exception

#### Logs
If applicable, please attach agent/collector/web DEBUG log that includes the code execution that led to the bug. In case of agents, including the start-up log may be of great help.

#### Additional context
Add any other context about the problem here, such as affected library for agents, how your collector/web/hbase is set up if applicable.

**Comment by Xylus** [comment]
Check your connection.
