### ISSUE TITLE
threadDump command

### ISSUE THREAD

**Issue by shaocongcong** [naver/pinpoint#5142]
I sent a threadDump command with Golang, 
code like this

```go
	var rePacket proto.Packet
	threadDump := command.NewTCommandThreadDump()
	threadDump.Type = 0

	transfer := command.NewTCommandTransfer()
	transfer.ApplicationName = "CCC"
	transfer.AgentId = "CCC-1"
	transfer.StartTime = &agentStartTimeTest
	transfer.Payload = thrift.Serialize(threadDump)

	applicationStreamCreate := proto.NewApplicationStreamCreate()
	applicationStreamCreate.Payload = thrift.Serialize(transfer)
	applicationStreamCreate.ChannelID = streamID
	rePacket = applicationStreamCreate

	body, err := rePacket.Encode()
	if err != nil {
		g.L.Warn("rePacket.Encode", zap.String("error", err.Error()))
		return err
	}

	if _, err := conn.Write(body); err != nil {
		g.L.Warn("conn.Write", zap.String("error", err.Error()))
		return err
	}
```

then recv agent response: APPLICATION_STREAM_CREATE_FAIL {{14 531 132}}, code is 132.
Can you tell me what's wrong？

**Comment by koo-taejin** [comment]
I do not know your code, so it is difficult to resolve you're issue. 

However, you can get error 132 code when do not have support for CommandType. (like TheadDump)

`com.navercorp.pinpoint.profiler.receiver.CommandDispatcher`
If you look at the code, it will help.

Additionally we are trying to add grpc to the transport layer and we are going to start this operation.
Development after to add grpc transport layer, may be a better choice.

thanks.

**Comment by shaocongcong** [comment]
Thank you for the response，when will the GRPC be released？

**Comment by koo-taejin** [comment]
Will begin soon.
However, I do not know when it will be completed.
