### ISSUE TITLE
How to pass the AsyncContext to the handler of the async task which has been started already?

### ISSUE THREAD

**Issue by ni-ze** [naver/pinpoint#5151]
### I am using the pinpoint 1.8.1, and write a plugin to enhance my own  frame. 

I got a question like this:
 
```java
public class KernelTaskScheduler implements  ApplicationListener {
    
    public void  onApplicationEvent (ApplicationEvent event){
        
         if (event instanceof ContextRefreshedEvent) {
    		ScheduledExecutorService schedule=...
			KernelTask task = ...
                
    		ScheduleCommand scheduleCommand=new ScheduleCommand(task,schedule) ;
	
    		schedule.scheduleAtFixedRate(....);
    	}   
    }
}
```

```java
public class ScheduleCommand implements Runnable{ 
	KernelTask task;
	ScheduledExecutorService schedule;
	public ScheduleCommand(KernelTask task,ScheduledExecutorService schedule)
	{
		this.task=task;
		this.schedule=schedule;
	}
	 
    public void run() {
        .....
    }
}
```

method **onApplicationEvent**  invoked when Context Refreshed, and ScheduleCommand also  will be  Instantiation, but **the traceContext is null at this moment**。 

when the request come from web, traceContext is not null, but it will not  Instantiate the 
 ScheduleCommand, becase event instanceof ContextRefreshedEvent is false. 

Therefore，the  field AsyncContext in ScheduleCommand  will alwalys  be null ! 

How to resove this problem?

**Comment by emeroad** [comment]
@ni-ze Hi~

I think you need something similar to SpringAsyncPlugin
AsyncContext must be injected into the ScheduleCommand to be propagated to other thread

https://github.com/naver/pinpoint/blob/master/plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/async/SpringAsyncPlugin.java#L75
 - AsyncExecutionInterceptor$1 and AsyncExecutionInterceptor$$Lambda$ are some kind of Runnable class.

**Comment by ni-ze** [comment]
@emeroad  I scaned the class AsyncExecutionInterceptor, but it does not work for me. The same point is they all have a Internal class, and we want to inject and propagete AsyncContext to Runnable class. But, in my case, the Runnable is runing before than injected.Becase onApplicationEvent method is invoked when spring context refreshed. But the TraceContext won't appear until a GET/POST request come from web.

**Comment by ni-ze** [comment]
I have seed the sample about how to inject and propagate the AsyncContext to another thread, but I am troubled by how to inject a running thread. so ,come here for asking help, thanks.
