### ISSUE TITLE
Does PinPoint can be used to profile Scone container

### ISSUE THREAD

**Issue by Sreekkanth** [naver/pinpoint#5153]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

I would like to profile Scone Container with pinPoint , does this supported container with pinpoint.

**Comment by RoySRose** [comment]
Hello, @Sreekkanth 

Pinpoint doesn't support profiling Scone containers.
