### ISSUE TITLE
Can pinpoint support jdk1.6.0_21

### ISSUE THREAD

**Issue by CHENTIANHAO123** [naver/pinpoint#5158]
Hello team,Can pinpoint support jdk1.6.0_21 ? thanks.

**Comment by Xylus** [comment]
Hi @CHENTIANHAO123 
Pinpoint agent should work on jdk 1.6.0_21, though you will have to set `profiler.applicationservertype` in *pinpoint.config* manually.

**Comment by CHENTIANHAO123** [comment]
@Xylus  Thanks for your reply.
what value should I set to profiler.applicationservertype in pinpoint.config?

**Comment by Xylus** [comment]
@CHENTIANHAO123 To whatever application it is that you're running - TOMCAT, SPRING_BOOT, JETTY, etc
You can take a look [ServiceType.java](https://github.com/naver/pinpoint/blob/master/commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java#L43) for some possible values (check the ones with codes between 1000 and 2000).
