### ISSUE TITLE
The question about Weblogic

### ISSUE THREAD

**Issue by zhoukaidian** [naver/pinpoint#5167]
#### What version of pinpoint are you using?
master/v1.8.0

#### Describe your problem**
When I use weblogic with pinpoint-1.8.0,  there is no topo and dotList Graph, and the ServiceType show “UNDEFINED”. But there are scatter data in the http response.

#### What have you done?
I just did the weblogic configuration step by step.
https://github.com/naver/pinpoint/tree/master/plugins/weblogic

#### Screenshots

![_20190123144313](https://user-images.githubusercontent.com/30787536/51588235-6fff6800-1f1e-11e9-9a29-b5b4a13bb305.png)
![1548226374 1](https://user-images.githubusercontent.com/30787536/51588304-b228a980-1f1e-11e9-958f-11aa3ceeaf19.png)

![_20190123144320](https://user-images.githubusercontent.com/30787536/51588245-74c41c00-1f1e-11e9-8721-991a18f4f9d2.png)

![_20190123144325](https://user-images.githubusercontent.com/30787536/51587909-4d208400-1f1d-11e9-81e5-c200ffc385e6.png)

#### Logs
no exception infos in agent log.

**Comment by Xylus** [comment]
Hi @zhoukaidian 
Could you post/mail me your agent DEBUG log?

**Comment by zhoukaidian** [comment]
Hi @Xylus 
Can you analyze the cause of the problem through the log?

**Comment by Xylus** [comment]
@zhoukaidian 
Sorry for the late reply.
You're right, the agent startup log seems okay.

What version is your pinpoint web/collector?

**Comment by Xylus** [comment]
Hmm... that is very weird then :(

Could you post/mail me your collector and web DEBUG log?
The collector log should include logs from when the agent connects and sends some trace data.
The web log should include logs from when you query the server map for *FECBS_CT* application.

Sorry for the inconvenience.
Thanks.
