### ISSUE TITLE
What others can be set in spanDataSenderSocketType？

### ISSUE THREAD

**Issue by chuanyi-fang** [naver/pinpoint#5183]
“profiler.spandatasender.socket.type=OIO” is setted in agent‘s pinpoint.config.
What others can be set in spanDataSenderSocketType？
For example，profiler.spandatasender.socket.type=NIO etc.

**Comment by koo-taejin** [comment]
You can choose OIO or NIO.
However, internal testing did not have a benefit, even with NIO.
So did not exposed the option.

thanks.

**Comment by emeroad** [comment]
NIO will be deprecated in the future. 
We do not recommend using it.
