### ISSUE TITLE
pinpoint mark a tracnsaction error,but the exception occured was handled

### ISSUE THREAD

**Issue by yale2** [naver/pinpoint#5185]
#### What version of pinpoint are you using?
master 1.6.2

#### Describe your problem**
in my spring bean method.An exception occured ,but I have handled the exception with catch method.so the business continues to execute.however,pinpoint still mark a transaction error.can you tell me why . I had set profiler.spring.beans.mark.error=false.

#### What have you done?
Steps you have taken to trigger the problem, for example:
1. set profiler.spring.beans.mark.error=false.
2. handle an exception with try-catch method.

#### Screenshots
![20190125104207](https://user-images.githubusercontent.com/16750655/51721723-ec648900-208d-11e9-8e3a-38f4d9189ad0.jpg)
![20190125110024](https://user-images.githubusercontent.com/16750655/51722465-6f86de80-2090-11e9-8510-8aea9e9a6a0d.png)

#### Logs
everything looks fine.

**Comment by RoySRose** [comment]
Hello, @yale2 

check #5030
and also, suggest to upgrade the agent to a higher version if there isn't any absolute reason to use 1.6.x
