### ISSUE TITLE
maven-compiler:3.1 error on project pinpoint-profiler-optional-jdk9

### ISSUE THREAD

**Issue by aldiyudhaa** [naver/pinpoint#5202]
Hi, i want to install pinpoint but i got this error 
[INFO] Compiling 1 source file to C:\Users\ALDI\Downloads\pinpoint-master\pinpoint-master\profiler-optional\profiler-optional-jdk9\target\classes
[DEBUG] incrementalBuildHelper#afterRebuildExecution
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for pinpoint 1.9.0-SNAPSHOT:
[INFO]
[INFO] pinpoint ........................................... SUCCESS [  2.032 s]
[INFO] pinpoint-annotations ............................... SUCCESS [  6.530 s]
[INFO] pinpoint-commons ................................... SUCCESS [ 14.201 s]
[INFO] pinpoint-thrift .................................... SUCCESS [ 23.159 s]
[INFO] pinpoint-grpc ...................................... SUCCESS [  9.027 s]
[INFO] pinpoint-bootstrap-core ............................ SUCCESS [ 15.768 s]
[INFO] pinpoint-bootstrap ................................. SUCCESS [  4.224 s]
[INFO] pinpoint-rpc ....................................... SUCCESS [  8.440 s]
[INFO] pinpoint-profiler .................................. SUCCESS [ 26.539 s]
[INFO] pinpoint-profiler-test ............................. SUCCESS [  5.862 s]
[INFO] pinpoint-profiler-optional-parent .................. SUCCESS [  1.127 s]
[INFO] pinpoint-profiler-optional-jdk6 .................... SUCCESS [  4.366 s]
[INFO] pinpoint-profiler-optional-jdk7 .................... SUCCESS [  6.048 s]
[INFO] pinpoint-test ...................................... SUCCESS [  5.413 s]
[INFO] pinpoint-profiler-optional-jdk8 .................... SUCCESS [  6.035 s]
**[INFO] pinpoint-profiler-optional-jdk9 .................... FAILURE** [  2.935 s]
[INFO] pinpoint-profiler-optional ......................... SKIPPED
[INFO] pinpoint-httpclient3-plugin ........................ SKIPPED
[INFO] pinpoint-httpclient4-plugin ........................ SKIPPED
[INFO] pinpoint-ning-asynchttpclient-plugin ............... SKIPPED
[INFO] pinpoint-resttemplate-plugin ....................... SKIPPED
[INFO] pinpoint-netty-plugin .............................. SKIPPED
[INFO] pinpoint-gson-plugin ............................... SKIPPED
[INFO] pinpoint-cubrid-jdbc-driver-plugin ................. SKIPPED
[INFO] pinpoint-mysql-jdbc-driver-plugin .................. SKIPPED
[INFO] pinpoint-mariadb-jdbc-driver-plugin ................ SKIPPED
[INFO] pinpoint-postgresql-jdbc-driver-plugin ............. SKIPPED
[INFO] pinpoint-jtds-plugin ............................... SKIPPED
[INFO] pinpoint-oracle-jdbc-driver-plugin ................. SKIPPED
[INFO] pinpoint-commons-dbcp-plugin ....................... SKIPPED
[INFO] pinpoint-commons-dbcp2-plugin ...................... SKIPPED
[INFO] pinpoint-hikaricp-plugin ........................... SKIPPED
[INFO] pinpoint-cassandra-driver-plugin ................... SKIPPED
[INFO] pinpoint-jdk-http-plugin ........................... SKIPPED
[INFO] pinpoint-commons-hbase ............................. SKIPPED
[INFO] pinpoint-commons-server ............................ SKIPPED
[INFO] pinpoint-redis-plugin .............................. SKIPPED
[INFO] pinpoint-redis-lettuce-plugin ...................... SKIPPED
[INFO] pinpoint-common-servlet ............................ SKIPPED
[INFO] pinpoint-tomcat-plugin ............................. SKIPPED
[INFO] pinpoint-json-lib-plugin ........................... SKIPPED
[INFO] pinpoint-jackson-plugin ............................ SKIPPED
[INFO] pinpoint-thrift-plugin ............................. SKIPPED
[INFO] pinpoint-user-plugin ............................... SKIPPED
[INFO] pinpoint-arcus-plugin .............................. SKIPPED
[INFO] pinpoint-google-httpclient-plugin .................. SKIPPED
[INFO] pinpoint-grpc-plugin ............................... SKIPPED
[INFO] pinpoint-jetty-plugin .............................. SKIPPED
[INFO] pinpoint-websphere-plugin .......................... SKIPPED
[INFO] pinpoint-spring-plugin ............................. SKIPPED
[INFO] pinpoint-spring-boot-plugin ........................ SKIPPED
[INFO] pinpoint-ibatis-plugin ............................. SKIPPED
[INFO] pinpoint-mybatis-plugin ............................ SKIPPED
[INFO] pinpoint-okhttp-plugin ............................. SKIPPED
[INFO] pinpoint-log4j-plugin .............................. SKIPPED
[INFO] pinpoint-logback-plugin ............................ SKIPPED
[INFO] pinpoint-dubbo-plugin .............................. SKIPPED
[INFO] pinpoint-activemq-client-plugin .................... SKIPPED
[INFO] pinpoint-cxf-plugin ................................ SKIPPED
[INFO] pinpoint-hystrix-plugin ............................ SKIPPED
[INFO] pinpoint-jboss-plugin .............................. SKIPPED
[INFO] pinpoint-vertx-plugin .............................. SKIPPED
[INFO] pinpoint-resin-plugin .............................. SKIPPED
[INFO] pinpoint-jsp-plugin ................................ SKIPPED
[INFO] pinpoint-rxjava-plugin ............................. SKIPPED
[INFO] pinpoint-rabbitmq-plugin ........................... SKIPPED
[INFO] pinpoint-weblogic-plugin ........................... SKIPPED
[INFO] pinpoint-php-plugin ................................ SKIPPED
[INFO] pinpoint-akka-http-plugin .......................... SKIPPED
[INFO] pinpoint-undertow-plugin ........................... SKIPPED
[INFO] pinpoint-undertow-servlet-plugin ................... SKIPPED
[INFO] pinpoint-kafka-plugin .............................. SKIPPED
[INFO] pinpoint-mongodb-driver-plugin ..................... SKIPPED
[INFO] pinpoint-fastjson-plugin ........................... SKIPPED
[INFO] pinpoint-druid-plugin .............................. SKIPPED
[INFO] pinpoint-hbase-plugin .............................. SKIPPED
[INFO] pinpoint-openwhisk-plugin .......................... SKIPPED
[INFO] pinpoint-plugins ................................... SKIPPED
[INFO] pinpoint-bootstrap-java7 ........................... SKIPPED
[INFO] pinpoint-bootstrap-java8 ........................... SKIPPED
[INFO] pinpoint-bootstrap-java9 ........................... SKIPPED
[INFO] pinpoint-tools ..................................... SKIPPED
[INFO] pinpoint-agent-distribution ........................ SKIPPED
[INFO] pinpoint-agent-it .................................. SKIPPED
[INFO] pinpoint-collector ................................. SKIPPED
[INFO] pinpoint-plugin-bom ................................ SKIPPED
[INFO] pinpoint-web ....................................... SKIPPED
[INFO] pinpoint-hbase-distribution ........................ SKIPPED
[INFO] pinpoint-flink ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:26 min
[INFO] Finished at: 2019-01-29T11:56:13+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] **Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project pinpoint-profiler-optional-jdk9: Compilation failure** -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project pinpoint-profiler-optional-jdk9: Compilation failure
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:39)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:122)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:55)
**Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure**
    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:862)
    at org.apache.maven.plugin.compiler.CompilerMojo.execute (CompilerMojo.java:129)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:39)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:122)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:55)
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pinpoint-profiler-optional-jdk9

here is my environment =
Found "C:\Users\ALDI\Downloads\pinpoint-master\pinpoint-master\.mvn\wrapper\maven-wrapper.jar"
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-25T01:41:47+07:00)
Maven home: C:\Users\ALDI\.m2\wrapper\dists\apache-maven-3.6.0-bin\2dakv70gp803gtm5ve1ufmvttn\apache-maven-3.6.0
Java version: 1.8.0_121, vendor: Oracle Corporation, runtime: C:\T24_SYAH3\3rdParty\java\jdk-8u121-windows-x64\jre
Default locale: en_ID, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

Actually i've tried with maven 3.5.3 but still doesn't work.
can i skip this module? pinpoint-profiler-optional-jdk9 because i used JDK-8 

Thank you.
Best regards,
Aldi

**Comment by pochand** [comment]
I have the same error.

I tried also to change the JAVA_HOME switching to the different versions.

I've installed the JDK 9.0.4.


[INFO] 1 error                                                                                                                                                                                                     [INFO] -------------------------------------------------------------                                                                                                                                               [INFO] ------------------------------------------------------------------------                                                                                                                                    [INFO] Reactor Summary:                                                                                                                                                                                            [INFO]                                                                                                                                                                                                             [INFO] pinpoint 1.9.0-SNAPSHOT ............................ SUCCESS [  2.317 s]                                                                                                                                    [INFO] pinpoint-annotations ............................... SUCCESS [  1.544 s]                                                                                                                                    [INFO] pinpoint-commons ................................... SUCCESS [  3.821 s]                                                                                                                                    [INFO] pinpoint-thrift .................................... SUCCESS [  4.668 s]                                                                                                                                    [INFO] pinpoint-grpc ...................................... SUCCESS [  7.685 s]                                                                                                                                    [INFO] pinpoint-bootstrap-core ............................ SUCCESS [  3.447 s]                                                                                                                                    [INFO] pinpoint-bootstrap ................................. SUCCESS [  0.545 s]                                                                                                                                    [INFO] pinpoint-rpc ....................................... SUCCESS [  2.543 s]                                                                                                                                    [INFO] pinpoint-profiler .................................. SUCCESS [ 13.209 s]                                                                                                                                    [INFO] pinpoint-profiler-test ............................. SUCCESS [  1.365 s]                                                                                                                                    [INFO] pinpoint-profiler-optional-parent .................. SUCCESS [  0.698 s]                                                                                                                                    [INFO] pinpoint-profiler-optional-jdk6 .................... SUCCESS [  0.790 s]                                                                                                                                    [INFO] pinpoint-profiler-optional-jdk7 .................... SUCCESS [  0.932 s]                                                                                                                                    [INFO] pinpoint-test ...................................... SUCCESS [  1.036 s]                                                                                                                                    [INFO] pinpoint-profiler-optional-jdk8 .................... SUCCESS [  1.298 s]                                                                                                                                    [INFO] pinpoint-profiler-optional-jdk9 .................... FAILURE [  1.782 s]                                                                                                                                    [INFO] pinpoint-profiler-optional ......................... SKIPPED                                                                                                                                                [INFO] pinpoint-httpclient3-plugin ........................ SKIPPED                                                                                                                                                [INFO] pinpoint-httpclient4-plugin ........................ SKIPPED                                                                                                                                                [INFO] pinpoint-ning-asynchttpclient-plugin ............... SKIPPED                                                                                                                                                [INFO] pinpoint-resttemplate-plugin ....................... SKIPPED                                                                                                                                                [INFO] pinpoint-netty-plugin .............................. SKIPPED                                                                                                                                                [INFO] pinpoint-gson-plugin ............................... SKIPPED                                                                                                                                                [INFO] pinpoint-cubrid-jdbc-driver-plugin ................. SKIPPED                                                                                                                                                [INFO] pinpoint-mysql-jdbc-driver-plugin .................. SKIPPED                                                                                                                                                [INFO] pinpoint-mariadb-jdbc-driver-plugin ................ SKIPPED                                                                                                                                                [INFO] pinpoint-postgresql-jdbc-driver-plugin ............. SKIPPED                                                                                                                                                [INFO] pinpoint-jtds-plugin ............................... SKIPPED                                                                                                                                                [INFO] pinpoint-oracle-jdbc-driver-plugin ................. SKIPPED                                                                                                                                                [INFO] pinpoint-commons-dbcp-plugin ....................... SKIPPED                                                                                                                                                [INFO] pinpoint-commons-dbcp2-plugin ...................... SKIPPED                                                                                                                                                [INFO] pinpoint-hikaricp-plugin ........................... SKIPPED                                                                                                                                                [INFO] pinpoint-cassandra-driver-plugin ................... SKIPPED                                                                                                                                                [INFO] pinpoint-jdk-http-plugin ........................... SKIPPED                                                                                                                                                [INFO] pinpoint-commons-hbase ............................. SKIPPED                                                                                                                                                [INFO] pinpoint-commons-server ............................ SKIPPED                                                                                                                                                [INFO] pinpoint-redis-plugin .............................. SKIPPED                                                                                                                                                [INFO] pinpoint-redis-lettuce-plugin ...................... SKIPPED                                                                                                                                                [INFO] pinpoint-common-servlet ............................ SKIPPED                                                                                                                                                [INFO] pinpoint-tomcat-plugin ............................. SKIPPED                                                                                                                                                [INFO] pinpoint-json-lib-plugin ........................... SKIPPED                                                                                                                                                [INFO] pinpoint-jackson-plugin ............................ SKIPPED                                                                                                                                                [INFO] pinpoint-thrift-plugin ............................. SKIPPED                                                                                                                                                [INFO] pinpoint-user-plugin ............................... SKIPPED                                                                                                                                                [INFO] pinpoint-arcus-plugin .............................. SKIPPED                                                                                                                                                [INFO] pinpoint-google-httpclient-plugin .................. SKIPPED                                                                                                                                                [INFO] pinpoint-grpc-plugin ............................... SKIPPED                                                                                                                                                [INFO] pinpoint-jetty-plugin .............................. SKIPPED                                                                                                                                                [INFO] pinpoint-websphere-plugin .......................... SKIPPED                                                                                                                                                [INFO] pinpoint-spring-plugin ............................. SKIPPED                                                                                                                                                [INFO] pinpoint-spring-boot-plugin ........................ SKIPPED                                                                                                                                                [INFO] pinpoint-ibatis-plugin ............................. SKIPPED                                                                                                                                                [INFO] pinpoint-mybatis-plugin ............................ SKIPPED                                                                                                                                                [INFO] pinpoint-okhttp-plugin ............................. SKIPPED                                                                                                                                                [INFO] pinpoint-log4j-plugin .............................. SKIPPED                                                                                                                                                [INFO] pinpoint-logback-plugin ............................ SKIPPED                                                                                                                                                [INFO] pinpoint-dubbo-plugin .............................. SKIPPED                                                                                                                                                [INFO] pinpoint-activemq-client-plugin .................... SKIPPED                                                                                                                                                [INFO] pinpoint-cxf-plugin ................................ SKIPPED                                                                                                                                                [INFO] pinpoint-hystrix-plugin ............................ SKIPPED                                                                                                                                                [INFO] pinpoint-jboss-plugin .............................. SKIPPED                                                                                                                                                [INFO] pinpoint-vertx-plugin .............................. SKIPPED                                                                                                                                                [INFO] pinpoint-resin-plugin .............................. SKIPPED                                                                                                                                                [INFO] pinpoint-jsp-plugin ................................ SKIPPED                                                                                                                                                [INFO] pinpoint-rxjava-plugin ............................. SKIPPED                                                                                                                                                [INFO] pinpoint-rabbitmq-plugin ........................... SKIPPED                                                                                                                                                [INFO] pinpoint-weblogic-plugin ........................... SKIPPED                                                                                                                                                [INFO] pinpoint-php-plugin ................................ SKIPPED                                                                                                                                                [INFO] pinpoint-akka-http-plugin .......................... SKIPPED                                                                                                                                                [INFO] pinpoint-undertow-plugin ........................... SKIPPED                                                                                                                                                [INFO] pinpoint-undertow-servlet-plugin ................... SKIPPED                                                                                                                                                [INFO] pinpoint-kafka-plugin .............................. SKIPPED                                                                                                                                                [INFO] pinpoint-mongodb-driver-plugin ..................... SKIPPED                                                                                                                                                [INFO] pinpoint-fastjson-plugin ........................... SKIPPED                                                                                                                                                [INFO] pinpoint-druid-plugin .............................. SKIPPED                                                                                                                                                [INFO] pinpoint-hbase-plugin .............................. SKIPPED                                                                                                                                                [INFO] pinpoint-openwhisk-plugin .......................... SKIPPED                                                                                                                                                [INFO] pinpoint-node-js-plugin ............................ SKIPPED                                                                                                                                                [INFO] pinpoint-plugins ................................... SKIPPED                                                                                                                                                [INFO] pinpoint-bootstrap-java7 ........................... SKIPPED                                                                                                                                                [INFO] pinpoint-bootstrap-java8 ........................... SKIPPED                                                                                                                                                [INFO] pinpoint-bootstrap-java9 ........................... SKIPPED                                                                                                                                                [INFO] pinpoint-tools ..................................... SKIPPED                                                                                                                                                [INFO] pinpoint-agent-distribution ........................ SKIPPED                                                                                                                                                [INFO] pinpoint-agent-it .................................. SKIPPED                                                                                                                                                [INFO] pinpoint-collector ................................. SKIPPED                                                                                                                                                [INFO] pinpoint-plugin-bom ................................ SKIPPED                                                                                                                                                [INFO] pinpoint-web ....................................... SKIPPED                                                                                                                                                [INFO] pinpoint-hbase-distribution ........................ SKIPPED                                                                                                                                                [INFO] pinpoint-flink 1.9.0-SNAPSHOT ...................... SKIPPED                                                                                                                                                [INFO] ------------------------------------------------------------------------                                                                                                                                    [INFO] BUILD FAILURE                                                                                                                                                                                               [INFO] ------------------------------------------------------------------------                                                                                                                                    [INFO] Total time: 49.521 s                                                                                                                                                                                        [INFO] Finished at: 2019-01-31T00:08:00+01:00                                                                                                                                                                      [INFO] ------------------------------------------------------------------------                                                                                                                                    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:testCompile (default-testCompile) on project pinpoint-profiler-optional-jdk9: Compilation failure                              [ERROR] C:\Users\Git\pinpoint\profiler-optional\profiler-optional-jdk9\src\test\java\com\navercorp\pinpoint\profiler\instrument\classloading\Java9DefineClassTest.java:[56,38]  error: cannot find symbol                                                                                                                                                                                          [ERROR]   symbol:   class Java9DefineClass                                                                                                                                                                         [ERROR]   location: class Java9DefineClassTest                                                                                                                                                                     [ERROR]                                                                                                                                                                                                            [ERROR] -> [Help 1]                                                                                                                                                                                                [ERROR]                                                                                                                                                                                                            [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.                                                                                                                                [ERROR] Re-run Maven using the -X switch to enable full debug logging.                                                                                                                                             [ERROR]                                                                                                                                                                                                            [ERROR] For more information about the errors and possible solutions, please read the following articles:                                                                                                          [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException                                                                                                                             [ERROR]                                                                                                                                                                                                            [ERROR] After correcting the problems, you can resume the build with the command                                                                                                                                   [ERROR]   mvn  -rf :pinpoint-profiler-optional-jdk9
--

**Comment by pochand** [comment]
Below my JDK versions:


C:\Program Files\Java\jdk1.6.0_45/

C:\Program Files\Java\jdk1.7.0_80/

C:\Program Files\Java\jdk1.8.0_191/

C:\Program Files\Java\jdk-9.0.4/

Could its helps?

Thanks

**Comment by tonylit** [comment]
hi，try install jdk10.

**Comment by SunMuxin** [comment]
I have the same error too.

**Comment by aravindhan87** [comment]
Anyone able to successfully pass this step. If so please share the solution. I am also stuck at the same place.

**Comment by minwoo-jung** [comment]
Hi @aravindhan87
please show me the your full log.

**Comment by Tharsalbird** [comment]
> Anyone able to successfully pass this step. If so please share the solution. I am also stuck at the same place.

I had the same problem and it ended up being a issue with my JAVA_9_HOME environment variable. After I fixed, all worked fine
