### ISSUE TITLE
If the collector couldn't receive StringMetaData when the agent was starting,It will cause API-METADATA-NOT-FOUND

### ISSUE THREAD

**Issue by MarsZhu** [naver/pinpoint#5204]
If the collector couldn't receive StringMetaData when the agent was starting,It will cause API-METADATA-NOT-FOUND。How to solve it?

**Comment by dinesh4747** [comment]
Reference to the recent issue - #6496

@koo-taejin @jaehong-kim @emeroad @Xylus @jefry86 -

It looks functional issue where "synchronizing the start time value of agent is not in sync whole it reaches collector server" Can someone please shed some light or definite pointers on how to solve API-METADATA-NOT-FOUND issue which is almost deteriorating my usage of pinpoint in my cloud system and it seems like @jefry86 mentioned very clearly that "the startTime value of metadata is different"

It would be really great and kind if someone could help me address this.
