### ISSUE TITLE
 Are there any alarm-related features in future updates?

### ISSUE THREAD

**Issue by DevelopDestroyer** [naver/pinpoint#5206]
[KR]
실질적인 메일 알람 기능 설정을 위해서는
현재는 별도로 pinpoint-web에서 개발자가 구현해 주어야하는 것으로 알고있습니다만,
추후 릴리즈 될 1.9 및 2.0에서 메일알람설정 자동화에 관련된 내용이 포함되어 있는지 궁금합니다.

예를들어 web-pinpoint 사이트 상에서 smtp와 같은 메일전송 환경을 세팅하고 관리자 이메일을 등록하는 기능, 또는 config파일 설정을 통해 기본적으로 이메일 알람을 별도 추가개발 없이 사용 가능하도록 하는 기능 등.. 어떠한 형태로든 현재 알람 서비스 기능이 추가적인 보완이 이루어질 계획이 있는지 궁금합니다.

감사합니다.

p.s) 혹시 추후 업데이트 버전 내용에 대해 훑어볼 수 있는 개발 노트나 문서가 있다면 확인할 수 있는 링크다면 참조 부탁드립니다 ^^;

[EN]
Currently we are aware that developer needs to implement with pinpoint-web separately in order to set email alram function in its practical way.
so.. I wonder if there is a development plan for features that complement these processes : mail manager function, Simple mail notification settings via config file, etc..

thank you

PS) I would also like to ask for the link to any documentation or dev note for future update by any chance. sincerely

**Comment by RoySRose** [comment]
Hello, @DevelopDestroyer 

please note that when you write a comment on a GitHub issue,
it's open to the community, it would be great if everyone can understand.
would be grateful if you can translate it.

please consider using just English. Thanks ;)

**Comment by RoySRose** [comment]
@DevelopDestroyer 

Few updates will be merged soon, #5052 , #5203

There aren't any developers note for the features planned.
