### ISSUE TITLE
Error on project pinpoint-httpclient3-plugin

### ISSUE THREAD

**Issue by blaize91** [naver/pinpoint#5239]
Hello,

I have the following error when compiling maven:

[ERROR] COMPILATION ERROR :                                                                                                                                                                      [INFO] -------------------------------------------------------------                                                                                                                             [ERROR] error: error reading C:\Users\blaize\.m2\repository\org\apache\httpcomponents\httpasyncclient\4.1.4\httpasyncclient-4.1.4.jar; error in opening zip file                              [ERROR] error: error reading C:\Users\blaize\.m2\repository\org\apache\httpcomponents\httpcore-nio\4.4.10\httpcore-nio-4.4.10.jar; error in opening zip file                                  [INFO] 2 errors                                                                                                                                                                                  [INFO] -------------------------------------------------------------                                                                                                                             [INFO] ------------------------------------------------------------------------                                                                                                                  [INFO] Reactor Summary:                                                                                                                                                                          [INFO]                                                                                                                                                                                           [INFO] pinpoint 1.9.0-SNAPSHOT ............................ SUCCESS [  4.545 s]                                                                                                                  [INFO] pinpoint-annotations ............................... SUCCESS [  4.629 s]                                                                                                                  [INFO] pinpoint-commons ................................... SUCCESS [  7.203 s]                                                                                                                  [INFO] pinpoint-thrift .................................... SUCCESS [  5.983 s]                                                                                                                  [INFO] pinpoint-grpc ...................................... SUCCESS [ 22.311 s]                                                                                                                  [INFO] pinpoint-bootstrap-core ............................ SUCCESS [  5.733 s]                                                                                                                  [INFO] pinpoint-bootstrap ................................. SUCCESS [  1.035 s]                                                                                                                  [INFO] pinpoint-rpc ....................................... SUCCESS [  4.557 s]                                                                                                                  [INFO] pinpoint-profiler .................................. SUCCESS [ 25.422 s]                                                                                                                  [INFO] pinpoint-profiler-test ............................. SUCCESS [  2.862 s]                                                                                                                  [INFO] pinpoint-profiler-optional-parent .................. SUCCESS [  1.319 s]                                                                                                                  [INFO] pinpoint-profiler-optional-jdk6 .................... SUCCESS [  1.544 s]                                                                                                                  [INFO] pinpoint-profiler-optional-jdk7 .................... SUCCESS [  2.258 s]                                                                                                                  [INFO] pinpoint-test ...................................... SUCCESS [  2.921 s]                                                                                                                  [INFO] pinpoint-profiler-optional-jdk8 .................... SUCCESS [  2.562 s]                                                                                                                  [INFO] pinpoint-profiler-optional-jdk9 .................... SUCCESS [  0.859 s]                                                                                                                  [INFO] pinpoint-profiler-optional ......................... SUCCESS [  0.109 s]                                                                                                                  [INFO] pinpoint-httpclient3-plugin ........................ FAILURE [  0.969 s]                                                                                                                  [INFO] pinpoint-httpclient4-plugin ........................ SKIPPED                                                                                                                              [INFO] pinpoint-ning-asynchttpclient-plugin ............... SKIPPED                                                                                                                              [INFO] pinpoint-resttemplate-plugin ....................... SKIPPED                                                                                                                              [INFO] pinpoint-netty-plugin .............................. SKIPPED                                                                                                                              [INFO] pinpoint-gson-plugin ............................... SKIPPED                                                                                                                              [INFO] pinpoint-cubrid-jdbc-driver-plugin ................. SKIPPED                                                                                                                              [INFO] pinpoint-mysql-jdbc-driver-plugin .................. SKIPPED                                                                                                                              [INFO] pinpoint-mariadb-jdbc-driver-plugin ................ SKIPPED                                                                                                                              [INFO] pinpoint-postgresql-jdbc-driver-plugin ............. SKIPPED                                                                                                                              [INFO] pinpoint-jtds-plugin ............................... SKIPPED                                                                                                                              [INFO] pinpoint-oracle-jdbc-driver-plugin ................. SKIPPED                                                                                                                              [INFO] pinpoint-commons-dbcp-plugin ....................... SKIPPED                                                                                                                              [INFO] pinpoint-commons-dbcp2-plugin ...................... SKIPPED                                                                                                                              [INFO] pinpoint-hikaricp-plugin ........................... SKIPPED                                                                                                                              [INFO] pinpoint-cassandra-driver-plugin ................... SKIPPED                                                                                                                              [INFO] pinpoint-jdk-http-plugin ........................... SKIPPED                                                                                                                              [INFO] pinpoint-commons-hbase ............................. SKIPPED                                                                                                                              [INFO] pinpoint-commons-server ............................ SKIPPED                                                                                                                              [INFO] pinpoint-redis-plugin .............................. SKIPPED                                                                                                                              [INFO] pinpoint-redis-lettuce-plugin ...................... SKIPPED                                                                                                                              [INFO] pinpoint-common-servlet ............................ SKIPPED                                                                                                                              [INFO] pinpoint-tomcat-plugin ............................. SKIPPED                                                                                                                              [INFO] pinpoint-json-lib-plugin ........................... SKIPPED                                                                                                                              [INFO] pinpoint-jackson-plugin ............................ SKIPPED                                                                                                                              [INFO] pinpoint-thrift-plugin ............................. SKIPPED                                                                                                                              [INFO] pinpoint-user-plugin ............................... SKIPPED                                                                                                                              [INFO] pinpoint-arcus-plugin .............................. SKIPPED                                                                                                                              [INFO] pinpoint-google-httpclient-plugin .................. SKIPPED                                                                                                                              [INFO] pinpoint-grpc-plugin ............................... SKIPPED                                                                                                                              [INFO] pinpoint-jetty-plugin .............................. SKIPPED                                                                                                                              [INFO] pinpoint-websphere-plugin .......................... SKIPPED                                                                                                                              [INFO] pinpoint-spring-plugin ............................. SKIPPED                                                                                                                              [INFO] pinpoint-spring-boot-plugin ........................ SKIPPED                                                                                                                              [INFO] pinpoint-ibatis-plugin ............................. SKIPPED                                                                                                                              [INFO] pinpoint-mybatis-plugin ............................ SKIPPED                                                                                                                              [INFO] pinpoint-okhttp-plugin ............................. SKIPPED                                                                                                                              [INFO] pinpoint-log4j-plugin .............................. SKIPPED                                                                                                                              [INFO] pinpoint-logback-plugin ............................ SKIPPED                                                                                                                              [INFO] pinpoint-dubbo-plugin .............................. SKIPPED                                                                                                                              [INFO] pinpoint-activemq-client-plugin .................... SKIPPED                                                                                                                              [INFO] pinpoint-cxf-plugin ................................ SKIPPED                                                                                                                              [INFO] pinpoint-hystrix-plugin ............................ SKIPPED                                                                                                                              [INFO] pinpoint-jboss-plugin .............................. SKIPPED                                                                                                                              [INFO] pinpoint-vertx-plugin .............................. SKIPPED                                                                                                                              [INFO] pinpoint-resin-plugin .............................. SKIPPED                                                                                                                              [INFO] pinpoint-jsp-plugin ................................ SKIPPED                                                                                                                              [INFO] pinpoint-rxjava-plugin ............................. SKIPPED                                                                                                                              [INFO] pinpoint-rabbitmq-plugin ........................... SKIPPED                                                                                                                              [INFO] pinpoint-weblogic-plugin ........................... SKIPPED                                                                                                                              [INFO] pinpoint-php-plugin ................................ SKIPPED                                                                                                                              [INFO] pinpoint-akka-http-plugin .......................... SKIPPED                                                                                                                              [INFO] pinpoint-undertow-plugin ........................... SKIPPED                                                                                                                              [INFO] pinpoint-undertow-servlet-plugin ................... SKIPPED                                                                                                                              [INFO] pinpoint-kafka-plugin .............................. SKIPPED                                                                                                                              [INFO] pinpoint-mongodb-driver-plugin ..................... SKIPPED                                                                                                                              [INFO] pinpoint-fastjson-plugin ........................... SKIPPED                                                                                                                              [INFO] pinpoint-druid-plugin .............................. SKIPPED                                                                                                                              [INFO] pinpoint-hbase-plugin .............................. SKIPPED                                                                                                                              [INFO] pinpoint-openwhisk-plugin .......................... SKIPPED                                                                                                                              [INFO] pinpoint-node-js-plugin ............................ SKIPPED                                                                                                                              [INFO] pinpoint-plugins ................................... SKIPPED                                                                                                                              [INFO] pinpoint-bootstrap-java7 ........................... SKIPPED                                                                                                                              [INFO] pinpoint-bootstrap-java8 ........................... SKIPPED                                                                                                                              [INFO] pinpoint-bootstrap-java9 ........................... SKIPPED                                                                                                                              [INFO] pinpoint-tools ..................................... SKIPPED                                                                                                                              [INFO] pinpoint-agent-distribution ........................ SKIPPED                                                                                                                              [INFO] pinpoint-agent-it .................................. SKIPPED                                                                                                                              [INFO] pinpoint-collector ................................. SKIPPED                                                                                                                              [INFO] pinpoint-plugin-bom ................................ SKIPPED                                                                                                                              [INFO] pinpoint-web ....................................... SKIPPED                                                                                                                              [INFO] pinpoint-hbase-distribution ........................ SKIPPED                                                                                                                              [INFO] pinpoint-flink 1.9.0-SNAPSHOT ...................... SKIPPED                                                                                                                              [INFO] ------------------------------------------------------------------------                                                                                                                  [INFO] BUILD FAILURE                                                                                                                                                                             [INFO] ------------------------------------------------------------------------                                                                                                                  [INFO] Total time: 01:39 min                                                                                                                                                                     [INFO] Finished at: 2019-02-13T00:46:32+01:00                                                                                                                                                    [INFO] ------------------------------------------------------------------------                                                                                                                  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project pinpoint-httpclient3-plugin: Compilation failure: Compilation failure:  [ERROR] error: error reading C:\Users\blaize\.m2\repository\org\apache\httpcomponents\httpasyncclient\4.1.4\httpasyncclient-4.1.4.jar; error in opening zip file                              [ERROR] error: error reading C:\Users\blaize\.m2\repository\org\apache\httpcomponents\httpcore-nio\4.4.10\httpcore-nio-4.4.10.jar; error in opening zip file                                  [ERROR] -> [Help 1]                                                                                                                                                                              org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project pinpoint-httpclient3-pl ugin: Compilation failure                                                                                                                                                                            at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)                                                                                                              at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)                                                                                                              at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)                                                                                                              at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)                                                                                     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)                                                                                      at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)                                                                        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)                                                                                                      at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)                                                                                                                               at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)                                                                                                                               at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)                                                                                                                                 at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)                                                                                                                                     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)                                                                                                                                      at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)                                                                                                                                        at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)                                                                                                                                  at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)                                                                                                                at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)                                                                                                        at java.lang.reflect.Method.invoke (Method.java:498)                                                                                                                                             at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)                                                                                                          at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)                                                                                                                  at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)                                                                                                        at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)                                                                                                                    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)                                                                                                                                  at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)                                                                                                                at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)                                                                                                        at java.lang.reflect.Method.invoke (Method.java:498)                                                                                                                                             at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:39)                                                                                                            at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:122)                                                                                                                   at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:55)                                                                                                                 Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure                                                                                                         at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1215)                                                                                                at org.apache.maven.plugin.compiler.CompilerMojo.execute (CompilerMojo.java:188)                                                                                                                 at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)                                                                                            at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)                                                                                                              at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)                                                                                                              at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)                                                                                                              at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)                                                                                     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)                                                                                      at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)                                                                        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)                                                                                                      at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)                                                                                                                               at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)                                                                                                                               at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)                                                                                                                                 at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)                                                                                                                                     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)                                                                                                                                      at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)                                                                                                                                        at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)                                                                                                                                  at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)                                                                                                                at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)                                                                                                        at java.lang.reflect.Method.invoke (Method.java:498)                                                                                                                                             at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)                                                                                                          at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)                                                                                                                  at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)                                                                                                        at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)                                                                                                                    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)                                                                                                                                  at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)                                                                                                                at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)                                                                                                        at java.lang.reflect.Method.invoke (Method.java:498)                                                                                                                                             at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:39)                                                                                                            at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:122)                                                                                                                   at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:55)                                                                                                                 [ERROR]                                                                                                                                                                                          [ERROR]                                                                                                                                                                                          [ERROR] For more information about the errors and possible solutions, please read the following articles:                                                                                        [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException                                                                                                           [ERROR]                                                                                                                                                                                          [ERROR] After correcting the problems, you can resume the build with the command                                                                                                                 [ERROR]   mvn  -rf :pinpoint-httpclient3-plugin
--

Does anyone have any suggestions?

Thanks a lot.

**Comment by emeroad** [comment]
C:\Users\blaize.m2\repository\org\apache\httpcomponents\httpasyncclient\4.1.4\httpasyncclient-4.1.4.jar; error in opening zip file [ERROR] error: error reading C:\Users\blaize.m2\repository\org\apache\httpcomponents\httpcore-nio\4.4.10\httpcore-nio-4.4.10.jar; error in opening zip file

Check your local repository.

**Comment by DevelopDestroyer** [comment]
Hi @blaize91 
Why don't you initializing about maven repository? and retry build.
