### ISSUE TITLE
Does Pinpoint support tranceid query?

### ISSUE THREAD

**Issue by dean-hu** [naver/pinpoint#5253]
Hello~

Would you like to ask if pinPoint supports tranceid query? Because the problem is checked, the call log of the entire link under the current tranceid needs to be performed according to the tranceid recorded in the log to analyze the cause of the error.

**Comment by RoySRose** [comment]
Hello, @dean-hu 

What do you mean by Pinpoint supporting traceid query?
Do you mean, can the users find out the traceids of certain transaction?

**Comment by dean-hu** [comment]
> Hello, @dean-hu
> 
> What do you mean by Pinpoint supporting traceid query?
> Do you mean, can the users find out the traceids of certain transaction?

Hello @RoySRose 

I would like to give an example, such as a request may access the a service, and then access to the B service, the identity of the request is trance_id, in the project by logging the trance_id, and then through the TRANCE_ID search log can query the entire link information of the request

**Comment by RoySRose** [comment]
@dean-hu 
By tranceId, you mean trace Id? right?
It would be TransactionIds in Pinpoint.

The call-stack itself is by transaction Id. 
You can filter it from servermap.
You can checkout various info from Pinpoint as described on the [homepage](https://naver.github.io/pinpoint/overview.html) or as below image.
![image](https://user-images.githubusercontent.com/20402016/53234824-c275a500-36d3-11e9-94d2-16532ca6ece3.png)

But there isn't any feature that you can search for one.
or any API open to retrieve any info from Pinpoint.
