### ISSUE TITLE
will hibernate plugin be added? 

### ISSUE THREAD

**Issue by meifamao** [naver/pinpoint#5255]
**Which module is your feature request related to?**
Plugin

**Is your feature request related to a problem?**
some web projects prefer ORM framework for hibernate

**Comment by DevelopDestroyer** [comment]
Hi @meifamao 
hibernate is already famous all over the world, but mybatis still prevails in Korea. As far as I know, some projects in Pinpoint already use mybatis. so, I think If they support hibernate, it is expected to take a lot of work.
