### ISSUE TITLE
Pinpoint agent not working for nested jars

### ISSUE THREAD

**Issue by simoelmou** [naver/pinpoint#5261]
#### What version of pinpoint are you using?
1.8.1

#### Describe the bug
There is an exception in the pinpoint agent logs, and it concerns Spring Cassandra library. In fact, Applications that communicate with Cassandra are not linked to each other and I think it's because of this exception.
For example normally the request flow is : 
App 1 > App 2 > Cassandra
but pinpoint web shows it like this : 
App 1
App 2 > Cassandra
So the traceId is lost between the App 1 and App 2

#### Logs
You can see the logs here: https://gist.github.com/simoelmou/7123f75eb341023750daf11675df4284

#### Additional context
I'm using version 1.8.0 for the Collector and Web.

**Comment by emeroad** [comment]
@simoelmou Hi! 
If the problem is Jar in the jar, the class scan does not seem to be normal.

> codeLocation:jar:file:/app.jar!/BOOT-INF/lib/cassandra-driver-core-3.4.0.jar!
```java
Transformer:com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate threw an exception. codeLocation:jar:file:/app.jar!/BOOT-INF/lib/cassandra-driver-core-3.4.0.jar!

java.lang.IllegalArgumentException: unknown scanner type classLoader:org.springframework.boot.loader.LaunchedURLClassLoader@2f66e802 
protectionDomain:ProtectionDomain  (jar:file:/app.jar!/BOOT-INF/lib/cassandra-driver-core-3.4.0.jar!/ <no signer certificates>)
```

**Comment by Xylus** [comment]
@simoelmou Thanks for reporting.
The bug should be reproducible when running an executable jar (including spring boot apps and other executable archives) and the agent opens a scanner to a class file.
Fix will be deployed soon.

**Comment by simoelmou** [comment]
@Xylus Is this why we don't see a connection between components that use Cassandra? like in the example, I showed above.

**Comment by Xylus** [comment]
@simoelmou Can't be sure without the full agent log, but my guess would be no, App 1 -> App 2 should be linked up even with the error above.
Are you using okhttp 2.x in App 1 to make calls to App 2?

**Comment by simoelmou** [comment]
@Xylus Actually we use Apache HTTP Client for calls between the apps, is it supported ?

**Comment by Xylus** [comment]
Yup, so App 1 -> App 2 should be linked up.
Could you post/mail me the agent DEBUG logs of App 1 and App 2? The logs should contain the startup log and the log produced from the App1 -> App2 -> Cassandra call.
Collector log should also be useful.
Thanks.

**Comment by simoelmou** [comment]
App1 logs: https://gist.github.com/simoelmou/caa1952c138a378a2b7171a2e23ec91e
App2 logs: https://gist.github.com/simoelmou/6d95fd36bed174188e628d54dbd91b03

@Xylus Sorry of late answer, here are the logs of the agents, Ignore the health and Prometheus endpoints in both apps, so to give more context, App1 calls the App2 using an endpoint you'll see in the logs which itself calls Cassandra but the App2 creates a new traceId so the two are never linked.

**Comment by Xylus** [comment]
@simoelmou Sorry it took a while to look through your log.
While I couldn't perfectly isolate each and every request log (too many going on at the same time), I haven't found anything in App1 making a call to App2.
Here's what I could make out.

#### App1
1. *primary-gateway* calls *App1(message-processor)* via `primary-message-processor-svc:8080/v1/primary/tpd`
2. *App1* continues the trace using the trace headers supplied by *primary-gateway*
3. *App1* sends a HTTP call to `inveni-service-tpdacquire-svc:8080`

#### App2
1. Some unknown application calls *App2* via 'primary-uid-manager-svc:8080/v1/primary/tpd/uid/criteria`
2. *App2* starts a new trace as no trace header is found in the HTTP request.
3. *App2* calls Cassandra

If the above is correct, the *App1* -> *App2* link will not be shown as *App1* is not calling *App2*.

Please let me know if either myself, or the log is missing something (such as the part where *App1* makes a HTTP call to *App2*).
Thanks.

**Comment by simoelmou** [comment]
The problem is that App1 does call App2 and we can see it the App1's main logs but we can't see it the agents logs. I'll check again if the logs are missing something..

**Comment by Xylus** [comment]
@simoelmou 
So the `primary-uid-manager-svc:8080/v1/primary/tpd/uid/criteria` received by *App2* is from *App1*, right?
If so, is *App1* making the call to *App2* from a different thread (ie not the request thread)?

**Comment by simoelmou** [comment]
@Xylus yes exactly App1 receives a call from the gateway using a thread, but when App1 calls App2 it uses another thread.

**Comment by Xylus** [comment]
@simoelmou Ah okay, so I think that's the problem.
Trace objects get stored in thread local so if there's a thread switch between the acceptor thread (which would have created the trace object) and the sender thread, then the traces from the sender thread will not get recorded as there isn't a trace object that they can attach to.
Usually, trace objects are propagated over thread boundaries via the plugins for libraries we support. But if you are making asynchronous calls manually in your code, say creating a **Runnable** and handing it over to your own **Executor**, then the trace object will not be propagated over the thread boundary.

How are you making the thread switch? We do have support for Spring's `@Async` if you're using this.

**Comment by simoelmou** [comment]
@Xylus We use the class CompletableFuture to make calls to App2 and we're handing it our own ThreadPoolExecutor. Is it possible to instrument on our own this class to send the traceId ?

**Comment by Xylus** [comment]
@simoelmou Gotcha, we don't have support for **CompletableFuture** (yet) unfortunately.

**Comment by simoelmou** [comment]
@Xylus How can we instrument it on our own, please ?

**Comment by Xylus** [comment]
@simoelmou You can check out the [plugin developer guide](http://naver.github.io/pinpoint/plugindevguide.html) to make a plugin for it if you'd like (**CompletableFuture** looks pretty hard to make a plugin).
You'll also have to modify **UnmodifiableClassFilter** class to not skip the internal jdk classes you'll be transforming if you do decide to make the plugin.
