### ISSUE TITLE
Pinpoint-Flags Meaning

### ISSUE THREAD

**Issue by geekMessi** [naver/pinpoint#5262]
As I known, Pinpoint-Flags Header is one of the Trace Context Header propagated by http-calls. And the
server received the Header populate it to TraceId.
But I didn't get the meaning of this Header ?

Thx

**Comment by emeroad** [comment]
Pinpoint-Flags is a reserved field for the future.
This filed has nothing to do now.

**Comment by geekMessi** [comment]
> Pinpoint-Flags is a reserved field for the future.
> This filed has nothing to do now.
 Got it .
