### ISSUE TITLE
transactionInfo.pinpoint throws NPE

### ISSUE THREAD

**Issue by yale2** [naver/pinpoint#5263]
#### What version of pinpoint are you using?
1.6.2

#### Describe your problem**
most application trace dose not work normally.web ui shows an ERROR.the ERROR shows java.lang.NullPointerException.It happened in our product enviroment,so I can not debug normally,I print log to trace the error,but the code throws exception looks normally,I don't know why.

#### What have you done?
Steps you have taken to trigger the problem, for example:
1. Launched application with agent
2. web ui shows that collector trace application normally
3. when I want see the detail transactionInfo,web ui show ERROR.

#### Screenshots

![_20190218101405](https://user-images.githubusercontent.com/16750655/53139889-f367b400-35c5-11e9-8279-65c0b74d1811.jpg)
![_20190221104602](https://user-images.githubusercontent.com/16750655/53139890-f367b400-35c5-11e9-95c6-0ba5ef03646e.jpg)
RecordFactory:156
![_20190221105101](https://user-images.githubusercontent.com/16750655/53140099-a2a48b00-35c6-11e9-872f-ac3c933f1b33.jpg)
It has print out record info normally
![_20190221104610](https://user-images.githubusercontent.com/16750655/53139892-f4004a80-35c5-11e9-884c-3e4c6021becb.jpg)

**Comment by koo-taejin** [comment]
@yale2 
We do not  technical support for past versions.
Please update to the latest version (1.8.3), if encounter the same problem, please ask us again.
