### ISSUE TITLE
Why pinpoint use so many final keyword?  

### ISSUE THREAD

**Issue by MarsZhu** [naver/pinpoint#5273]
Why pinpoint use so many final keyword?  Would it cause full GC?

**Comment by emeroad** [comment]
https://dzone.com/articles/all-about-finals

According to Joshua Bloch in Effective Java.:

> Immutable classes are easier to design, implement, and use than mutable classes. They are less prone to error and are more secure. Furthermore, an immutable object can be in exactly one state, the state in which it was created. Mutable objects, on the other hand, can have arbitrarily complex state spaces.

**Comment by MarsZhu** [comment]
thank you
