### ISSUE TITLE
How to add exception information when sending email?

### ISSUE THREAD

**Issue by cheneyjuu** [naver/pinpoint#5284]
I want get the exception information at alarm, and send that to user by email, how to do that?

**Comment by RoySRose** [comment]
Hello, @cheneyjuu 

Please check the [doc on the homepage](https://naver.github.io/pinpoint/alarm.html)

**Comment by DevelopDestroyer** [comment]
Hi @cheneyjuu 
FYI : https://naver.github.io/pinpoint/alarm.html

**Comment by cheneyjuu** [comment]
@RoySRose @DevelopDestroyer thanks for reply. I have already implemented the `void sendEmail(AlarmChecker checker, int sequenceCount)` method, but i want to get more information (ex. what exception be thrown at the application) when application have an error, when i get that, i'll send it by using email.

**Comment by minwoo-jung** [comment]
Hello @cheneyjuu

I understand you. 
Unfortunately, It seems hard to add exception information.
Because alarm logic only check stat data (ex) request count, error count). 

If you want to add exception data, you should develop new batch job.
New batch logic need to examine traces table data for all request.

**Comment by jiamine** [comment]
> Hello @cheneyjuu
> 
> I understand you.
> Unfortunately, It seems hard to add exception information.
> Because alarm logic only check stat data (ex) request count, error count).
> 
> If you want to add exception data, you should develop new batch job.
> New batch logic need to examine traces table data for all request.
how to add additional information (ex) exception trigger time about request count,error count and so on
How to add some  information to the alarm such as trigger time .
