### ISSUE TITLE
how to get the transactionId and spanId in web?

### ISSUE THREAD

**Issue by cheneyjuu** [naver/pinpoint#5287]
I use that for find exception information thrown by application and send it to users by using email. How to do that?

**Comment by RoySRose** [comment]
Currently, There isn't any easy way for this, since there aren't any API open for Pinpoint.

But, maybe utilizing [this function](https://naver.github.io/pinpoint/perrequestfeatureguide.html) may show you the way. (Maybe far way to go. But, looks possible.)

**Comment by cheneyjuu** [comment]
@RoySRose Thank you for reply.
