### ISSUE TITLE
Response Summary and user diagram don't show data

### ISSUE THREAD

**Issue by Cyyking** [naver/pinpoint#5289]
Response Summary and users picture don't show data in dashboard
![image](https://user-images.githubusercontent.com/16470319/53612912-44ebf080-3c0f-11e9-82cf-7f1bd6168e6f.png)

I checked getServerMapDataV2.pinpoint interface don't respond linkDataArray data
![image](https://user-images.githubusercontent.com/16470319/53612828-fdfdfb00-3c0e-11e9-8233-2003c7fca024.png)

How can resolve the problem?

**Comment by Xylus** [comment]
Hi @Cyyking 
What version of hbase are you using? This looks very similar to #4673

**Comment by Cyyking** [comment]
@Xylus I have checked the hbase's version is 2.1.0. i am going rebuild the hbase to 1.2.*. Thank for you help.

**Comment by Xylus** [comment]
@Cyyking Awesome, please let me know if it fixes (or doesn't) your issue.
Thanks.
