### ISSUE TITLE
how to set HistogramSchema.FAST_SCHEME?

### ISSUE THREAD

**Issue by waterystone** [naver/pinpoint#5292]
Hello, pinpoint-web use BaseHistogramSchema.NORMAL_SCHEMA(1s/3s/5s/Slow) as default, but the granularity is coarse. I want to use  BaseHistogramSchema.FAST_SCHEMA, how to set it? Tanks~~

![image](https://user-images.githubusercontent.com/7723467/53732789-f2822c80-3eb9-11e9-82a9-e8923285ec49.png)

**Comment by waterystone** [comment]
somebody?

**Comment by yjqg6666** [comment]
Interested on this question, too. Any update for the current release 2.0.4? @emeroad
