### ISSUE TITLE
How do ordinary methods display images？

### ISSUE THREAD

**Issue by sanxun0325** [naver/pinpoint#5294]
I've developed plug-ins for common methods in my application that don't display images after following the tutorial。

![image](https://user-images.githubusercontent.com/28588342/53776309-a4f4d680-3f30-11e9-9da7-e3a857d76a94.png)

**Comment by Xylus** [comment]
Hi @sanxun0325 
Ordinary methods don't require images as they are not rendered in the server map, so you can skip that part of the tutorial.

**Comment by sanxun0325** [comment]
HI @Xylus 
Thank you, I can understand that the general method does not support the display of images?
