### ISSUE TITLE
support for hbase 2.x

### ISSUE THREAD

**Issue by jicai** [naver/pinpoint#5297]
Are there any plans to support HBase 2.x ？ thank you！

**Comment by RoySRose** [comment]
@jicai There isn't any yet.

**Comment by emeroad** [comment]
Please replace the driver with hbase-2.0.

It will probably work normally.

**Comment by jicai** [comment]
@RoySRose  @emeroad  
Thank you for your reply.

**Comment by emeroad** [comment]
https://hbase.apache.org/book.html#hbase.versioning
> Client-Server wire protocol compatibility
Allows updating client and server out of sync.
> We could only allow upgrading the server first. I.e. the server would be backward compatible to an old client, that way new APIs are OK.
> Example: A user should be able to use an old client to connect to an upgraded cluster.

The hbase version policy is the same as above, but it does not know whether it will actually work.

**Comment by RoySRose** [comment]
Hello, @jicai 

Hbase2 support #5328 has been merged.
take a look at the [guide](https://naver.github.io/pinpoint/hbaseupgrade.html)

Love to hear your feedback
