### ISSUE TITLE
Dynamic change of hbase 2.0 driver

### ISSUE THREAD

**Issue by emeroad** [naver/pinpoint#5298]
### Support Plan
1. maven profile
 - https://stackoverflow.com/questions/38219771/override-the-dependency-version-used-at-runtime-from-command-line

2. maven property overwrite
 - https://stackoverflow.com/questions/13708738/how-to-get-a-command-line-property-to-overwrite-a-maven-property

**Comment by RoySRose** [comment]
support hbase2 as database
#5328
