### ISSUE TITLE
about chart library's licence (GoJS / amCharts)

### ISSUE THREAD

**Issue by rockeee** [naver/pinpoint#530]
안녕하세요 
적용 테스트중에 궁금한점이 생겨 문의드립니다.
ServerMap과 차트영역에서 사용되는 라이브러리 2가지가 보이는데요 (GoJS / amCahrts)
두 라이브러리 모두 유료고, 특히 ServerMap에는 'Not for distribution or production use' 문구가 있습니다.

상용환경에서 사용해도 문제가 없을까요?

**Comment by lioolli** [comment]
상용환경에서는 라이센스를 구매하셔야 합니다. 저희도 사내에서 운영중인 서버는 라이센스 구매해서 사용하고 있습니다.
