### ISSUE TITLE
Can pinpoint trace a waiting thread?

### ISSUE THREAD

**Issue by messi-gao** [naver/pinpoint#5300]
HI,I am tracing a very old project by using pinpoint these days,I met a problem like below:

1.When my application starts up,it creates some threads which will execute their ` run`  method.But in the run method,the thread will execute ` wait`  method to wait bussiness thread to notify.
` @Override
    public void run() {
        while (true) {
          this.wait();
         doBussinessRequest();
       }
}`

2.Then bussiness request comes up,it will execute thread in step 1 ` notify`  method,then the thread can continue do bussiness request.
`   public void bussinessRequest() {
          nofity();
}`

The quesition is that when the waiting thread wake up,there is no `Trace` which can be found.
I also try to set attachment in step 2,but when the thread also can not get the attachment,could you give me some advice,thank you.

**Comment by sanxun0325** [comment]
@messi-gao what?

**Comment by koo-taejin** [comment]
hi @messi-gao 

Following two settings maybe can help you.
```
// in pinpoint.config
profiler.entrypoint
profiler.include
```

thanks.

**Comment by sanxun0325** [comment]
@koo-taejin The specific function of these two configurations can be described？

**Comment by koo-taejin** [comment]
@sanxun0325  You can get more information through searching past issues.

**Comment by messi-gao** [comment]
@koo-taejin 
According to your advice,the current trace is as below,I have already trace first step thread:
![image](https://user-images.githubusercontent.com/24312100/53929391-94776400-40c8-11e9-9023-316227490134.png)

how can I combine bussiness thread and frist step thread that application inits into a trace?

thank you very much!

**Comment by koo-taejin** [comment]
@messi-gao 

To do what you want, you need to create your own plugin.
The following links will help.

https://github.com/naver/pinpoint-plugin-sample/tree/master/plugin/src/main/java/com/navercorp/pinpoint/plugin/sample/_12_Asynchronous_Trace

**Comment by messi-gao** [comment]
> @messi-gao
> 
> To do what you want, you need to create your own plugin.
> The following links will help.
> 
> https://github.com/naver/pinpoint-plugin-sample/tree/master/plugin/src/main/java/com/navercorp/pinpoint/plugin/sample/_12_Asynchronous_Trace

I have tried to do like in _12_Asynchronous_Trace，the question is that the attachment whick bussiness thread set can not get in firse step method.The reason may be bussiness thread uses nofity method but not like call a method normally.

I still have no good idea to solve the problem,may I should use profiler.entrypoint(in pinpoint.conf) and _12_Asynchronous_Trace together?

thank you very much!

**Comment by koo-taejin** [comment]
@messi-gao 

Maybe code you mentioned is not possible to trace  thread propagation.
If you use blockingQueueue instead of wait notify format, then you can trace  thread propagation through development guide. 

thanks. :)
