### ISSUE TITLE
pinpoint web report a java.io.IOException: Broken pipe  error

### ISSUE THREAD

**Issue by xttyawei** [naver/pinpoint#5303]
pinpoint 1.6.2   
i add an agent to pinpoint-1.6.2 web， and get error report 
![image](https://user-images.githubusercontent.com/40187665/53936633-7a984a00-40e5-11e9-9cc7-6c7e2e45c472.png)
![image](https://user-images.githubusercontent.com/40187665/53936666-969beb80-40e5-11e9-9096-591555bfa7e5.png)
![image](https://user-images.githubusercontent.com/40187665/53936685-b3d0ba00-40e5-11e9-98a0-6ce9c785e9b3.png)

**Comment by RoySRose** [comment]
@xttyawei 

Yeah, that what Pinpoint is for...
To check why/where your application's error occurred.

Now you can look for the reason for the exception on your app.
