### ISSUE TITLE
How to detect agent' performance load

### ISSUE THREAD

**Issue by fionaliupw** [naver/pinpoint#5304]
- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

Recently, the performance of the application has been degraded, and I want to detect the performance load of the agent itself and the network occupancy.

Help, what methods can we try?

**Comment by Xylus** [comment]
Hi @fionaliupw 
You could compare cpu/memory usage or gc logs to see if there's a huge difference with/without the agent.

A few things you might want to check and lessen the load -
1. Check agent's level - If the agent's log level is set to DEBUG, it'll print out a ton of logs and will affect performance especially in a high traffic environment. Definitely set this to INFO for production servers. The agent's *log4j.xml* file is in `$AGENT_DIR/lib` directory.
2. Change the agent's sampling rate - You might want to change `profiler.sampling.rate` value in *pinpoint.config* to a higher value (key is misleading btw). The value here means 1 in N samples, so `profiler.sampling.rate=1` is 100%, whereas `profiler.sampling.rate=20` is 5%.

**Comment by fionaliupw** [comment]
Hi @Xylus 
Thank you very much for your answer.

I am going to modify the sampling rate to 50% and monitor the CPU/memory of the application server.

Btw, Sometimes the inspector page appearred blank for a few seconds data . What caused this phenomenon? As shown below. Thanks.
![image](https://user-images.githubusercontent.com/26397343/53943620-69a50400-40f8-11e9-9eaa-851f64514d16.png)

**Comment by Xylus** [comment]
@fionaliupw 
It might be due to a number of reasons, such as UDP packet being lost, collector rejecting data due to overload (might want to tune `collector.receiver.*.worker.*` options in *pinpoint-collector.properties*, or `hbase.client.thread*` options in collector's *hbase.properties*), etc.
You might want to check your collector log and see if it's dropping any agent stat data from time to time.

**Comment by fionaliupw** [comment]
@Xylus Thank you for your help.
