### ISSUE TITLE
Not able to hook pinpoint agent to Jboss Appserver

### ISSUE THREAD

**Issue by sattishv** [naver/pinpoint#5309]
#### Prerequisites

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
1.8.2

#### Describe your problem**
Not able to attach pinpoint agent to Jboss server. Whenever we attach the agent the application got exited. We use tanuki wrapper configuration for shutdown and startup

#### What have you done?
Steps you have taken to trigger the problem, for example:
Added the JVM options listed in pinpoint Jboss plugins page
wrapper.java.additional.35=-Djboss.modules.system.pkgs=org.jboss.byteman,org.jboss.logmanager,com.navercorp.pinpoint.bootstrap,com.navercorp.pinpoint.common,com.navercorp.pinpoint.exception
wrapper.java.additional.36=-Djava.util.logging.manager=org.jboss.logmanager.LogManager
wrapper.java.additional.37=-Xbootclasspath/p:$JBOSS_HOME/modules/system/layers/base/org/jboss/logmanager/main/jboss-logmanager-$JBOSS_LOGMANAGER_VERSION.jar
wrapper.java.additional.38=-javaagent:/opt/pinpoint/pinpoint-bootstrap-1.8.2.jar
wrapper.java.additional.39=-Dpinpoint.agentId=sampleserv
wrapper.java.additional.40=-Dpinpoint.applicationName=CPS

Encountered failure while attaching the agent to our application deployed on JBoss

#### Logs
I2019/03/07 04:38:46 | 2019-03-07 04:38:46 [INFO ](com.navercorp.pinpoint.bootstrap.PinpointStarter) pinpoint agent started normally.
INFO   | jvm 1    | 2019/03/07 04:38:47 | WrapperManager: Initializing...
INFO   | jvm 1    | 2019/03/07 04:38:47 | WARNING: Failed to load the specified log manager class org.jboss.logmanager.LogManager
INFO   | jvm 1    | 2019/03/07 04:38:48 | WrapperSimpleApp: 
INFO   | jvm 1    | 2019/03/07 04:38:48 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2019/03/07 04:38:48 | WrapperSimpleApp Error: java.lang.NoClassDefFoundError: org/jboss/logmanager/Level
INFO   | jvm 1    | 2019/03/07 04:38:48 | WrapperSimpleApp Error: 	at java.lang.Class.forName0(Native Method)
INFO   | jvm 1    | 2019/03/07 04:38:48 | WrapperSimpleApp Error: 	at java.lang.Class.forName(Class.java:270)
INFO   | jvm 1    | 2019/03/07 04:38:48 | WrapperSimpleApp Error: 	at org.jboss.modules.Module.run(Module.java:260)
INFO   | jvm 1    | 2019/03/07 04:38:48 | WrapperSimpleApp Error: 	at org.jboss.modules.Main.main(Main.java:294)
INFO   | jvm 1    | 2019/03/07 04:38:48 | WrapperSimpleApp Error: 	at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source)
INFO   | jvm 1    | 2019/03/07 04:38:48 | WrapperSimpleApp Error: 	at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2019/03/07 04:38:48 | WrapperSimpleApp Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:290)
INFO   | jvm 1    | 2019/03/07 04:38:48 | WrapperSimpleApp Error: 	at java.lang.Thread.run(Thread.java:744)
INFO   | jvm 1    | 2019/03/07 04:38:48 | WrapperSimpleApp Error: Caused by: java.lang.ClassNotFoundException: org.jboss.logmanager.Level
INFO   | jvm 1    | 2019/03/07 04:38:48 | WrapperSimpleApp Error: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
INFO   | jvm 1    | 2019/03/07 04:38:48 | WrapperSimpleApp Error: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
INFO   | jvm 1    | 2019/03/07 04:38:48 | WrapperSimpleApp Error: 	at java.security.AccessController.doPrivileged(Native Method)
INFO   | jvm 1    | 2019/03/07 04:38:48 | WrapperSimpleApp Error: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
INFO   | jvm 1    | 2019/03/07 04:38:48 | WrapperSimpleApp Error: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
INFO   | jvm 1    | 2019/03/07 04:38:48 | WrapperSimpleApp Error: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
INFO   | jvm 1    | 2019/03/07 04:38:48 | WrapperSimpleApp Error: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
INFO   | jvm 1    | 2019/03/07 04:38:48 | WrapperSimpleApp Error: 	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:395)
INFO   | jvm 1    | 2019/03/07 04:38:48 | WrapperSimpleApp Error: 	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:120)
INFO   | jvm 1    | 2019/03/07 04:38:48 | WrapperSimpleApp Error: 	... 8 more
STATUS | wrapper  | 2019/03/07 04:38:50 | <-- Wrapper Stopped

#### Additional context
Even added profiler.applicationservertype=JBOSS in pinpoint.config

**Comment by Xylus** [comment]
Hi @sattishv 
Just checking, but are the `$JBOSS_HOME` and `$JBOSS_LOGMANAGER_VERSION` environment variables resolved properly?
If not, you can replace them with their actual absolute paths.
