### ISSUE TITLE
Can pinpoint support dotnetcore?

### ISSUE THREAD

**Issue by seanshi90** [naver/pinpoint#5312]
pinpoint is a greate APM tool for coding and analysis services, we have java and dotnetcore applications,
but now we can only use pinpoint in java, can we support dotnetcore? so we can see all lines of these applications.

**Comment by RoySRose** [comment]
@seanshi90 

Unfortunately, Pinpoint only support Java, PHP for now.
And node.js, maybe GO in the near future.
