### ISSUE TITLE
SocketState(NONE->BEING_CONNECT)

### ISSUE THREAD

**Issue by ighack** [naver/pinpoint#5314]
> 2019-03-08 13:02:41 [WARN ](c.n.p.r.c.DefaultPinpointClient    ) reconnectClientHandler:DefaultPinpointClientHandler@1dff20f6{channel=[id: 0xe997427f, /192.168.0.240:15944 => /192.168.0.238:19994]state=SocketState(NONE->BEING_CONNECT)},
> 2019-03-08 13:02:45 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='192.168.0.238', port=19994},
> 2019-03-08 13:02:45 [WARN ](c.n.p.r.c.DefaultPinpointClient    ) reconnectClientHandler:DefaultPinpointClientHandler@570da3c3{channel=[id: 0x0c8bc64e, /192.168.0.240:15952 => /192.168.0.238:19994]state=SocketState(NONE->BEING_CONNECT)},
> 2019-03-08 13:02:49 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='192.168.0.238', port=19994},
> 2019-03-08 13:02:49 [WARN ](c.n.p.r.c.DefaultPinpointClient    ) reconnectClientHandler:DefaultPinpointClientHandler@3db80af2{channel=[id: 0xe8f97d3a, /192.168.0.240:15962 => /192.168.0.238:19994]state=SocketState(NONE->BEING_CONNECT)},
> 2019-03-08 13:02:53 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='192.168.0.238', port=19994},
> 2019-03-08 13:02:53 [WARN ](c.n.p.r.c.DefaultPinpointClient    ) reconnectClientHandler:DefaultPinpointClientHandler@7314cbef{channel=[id: 0x0af129bf, /192.168.0.240:15974 => /192.168.0.238:19994]state=SocketState(NONE->BEING_CONNECT)},

what does it means?
My collector can receives data,I think everything is OK.

**Comment by koo-taejin** [comment]
hi @ighack 

19994 port is typically used in the flink module. 
It is recommended that you check that there is no problem with access from the collector to the flink module.

thanks :)

**Comment by ighack** [comment]
we don't use flink

**Comment by koo-taejin** [comment]
Attempting to connect from the collector is because the address is registered in the zookeeper connected to the collector. 
Please check who is registering the address on your zookeeper.

**Comment by ighack** [comment]
`WatchedEvent state:SyncConnected type:None path:null
[zk: localhost:2181(CONNECTED) 0] ls /
[zookeeper, pinpoint-cluster, hbase]
[zk: localhost:2181(CONNECTED) 1] ls /pinpoint-cluster
[web, collector]
[zk: localhost:2181(CONNECTED) 2] ls /pinpoint-cluster/collector
[27498@moniser, 27453@basappser2]
[zk: localhost:2181(CONNECTED) 3] ls /pinpoint-cluster/collector/27498@moniser
[]
[zk: localhost:2181(CONNECTED) 4] ls /pinpoint-cluster/collector/27453@basappser2
[]
[zk: localhost:2181(CONNECTED) 5] ls /pinpoint-cluster/web                       
[192.168.0.10:9997, 192.168.0.238:9997]
[zk: localhost:2181(CONNECTED) 6] ls /zookeeper           
[quota]
[zk: localhost:2181(CONNECTED) 7] ls /zookeeper/quota
[]
[zk: localhost:2181(CONNECTED) 8] ls /hbase
[replication, meta-region-server, rs, splitWAL, backup-masters, table-lock, flush-table-proc, region-in-transition, online-snapshot, switch, master, running, balancer, recoverin
g-regions, draining, namespace, hbaseid, table][zk: localhost:2181(CONNECTED) 9] 
`
I don't see any IP uses 19994

**Comment by ighack** [comment]
my program run in docker,I get that WARN.
but my program run in host,I don't get the WARN.

**Comment by koo-taejin** [comment]
You can see that the collector gets the address it wants to connect to in the following  collector's log 
Please check your collector logs to see where you get your address and to resolve the problem.
`
[INFO ] (...ZookeeperClusterManager) Handle register and remove Task. Current Address List
`

**Comment by ighack** [comment]
I found out if "program->nginx->collector", I get WARN
but "program->collector" I don't get WARN

```
stream{
        proxy_protocol_timeout 120s;
        log_format main '$remote_addr $remote_port - [$time_local] '
                                        '$status $bytes_sent $protocol $server_addr $server_port'
                                        '$proxy_protocol_addr $proxy_protocol_port';
        access_log logs/access.log main;
        upstream 9994_tcp_upstreams {
                #least_timefirst_byte; 
                #fail_timeout=15s; 
                server 192.168.0.238:9994 max_fails=5 fail_timeout=60s;
                server 192.168.0.10:9994 max_fails=5 fail_timeout=60s;
                #server 192.168.2.133:9994; 
        }
        upstream 9995_udp_upstreams {
                #least_timefirst_byte; 
                server 192.168.0.238:9995 max_fails=5 fail_timeout=60s;
                server 192.168.0.10:9995 max_fails=5 fail_timeout=60s;
                #server 192.168.2.133:9995; 
        }
        upstream 9996_udp_upstreams {
                #least_timefirst_byte; 
                server 192.168.0.238:9996 max_fails=5 fail_timeout=60s;
 server 192.168.0.10:9996 max_fails=5 fail_timeout=60s;
                #server 192.168.2.133:9996; 
        }

        server {
                listen 19994;
                proxy_pass 9994_tcp_upstreams;
                proxy_timeout 1s;
                proxy_connect_timeout 5s;
        }
        server {
                listen 19995 udp;
                proxy_pass 9995_udp_upstreams;
                proxy_timeout 1s;
                proxy_connect_timeout 5s;
                #proxy_responses1; 
        }
        server {
                listen 19996 udp;
                proxy_pass 9996_udp_upstreams;
                proxy_timeout 1s;
                proxy_connect_timeout 5s;
                #proxy_responses1; 
        }
	}
```

**Comment by ighack** [comment]
proxy_timeout 1s;
 proxy_connect_timeout 5s;

that is too short.
modify

 proxy_timeout 10s;
 proxy_connect_timeout 15s;

**Comment by koo-taejin** [comment]
Is the first log you passed to the agent log? 
Enter the exact address you are connecting to collector in the agent's settings. 
Maybe it's because the port changed when you use proxy and when you don't use proxy.

**Comment by ighack** [comment]
I think that is durability connecting between agent and collector.
When I set proxy_connect_timeout,nginx return timeout error to agent.
so agent need to reconnect collector.

**Comment by ighack** [comment]
```
2019-03-27 16:34:38 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='192.168.0.238', port=19994}
2019-03-27 16:34:38 [WARN ](c.n.p.r.c.DefaultPinpointClient    ) reconnectClientHandler:DefaultPinpointClientHandler@7847dda7{channel=[id: 0x6affe4f7, /192.168.0.10:33069 => /192.168
.0.238:19994]state=SocketState(NONE->BEING_CONNECT)}2019-03-27 16:34:46 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='192.168.0.238', port=19994}
2019-03-27 16:34:46 [WARN ](c.n.p.r.c.DefaultPinpointClient    ) reconnectClientHandler:DefaultPinpointClientHandler@809eb2f{channel=[id: 0xb9b527f6, /192.168.0.10:33087 => /192.168.
0.238:19994]state=SocketState(NONE->BEING_CONNECT)}2019-03-27 16:34:54 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='192.168.0.238', port=19994}
2019-03-27 16:34:54 [WARN ](c.n.p.r.c.DefaultPinpointClient    ) reconnectClientHandler:DefaultPinpointClientHandler@7d29ca96{channel=[id: 0x6b0ebfde, /192.168.0.10:33099 => /192.168
.0.238:19994]state=SocketState(NONE->BEING_CONNECT)}2019-03-27 16:35:02 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='192.168.0.238', port=19994}
2019-03-27 16:35:02 [WARN ](c.n.p.r.c.DefaultPinpointClient    ) reconnectClientHandler:DefaultPinpointClientHandler@5d1b952f{channel=[id: 0xf48dee9f, /192.168.0.10:33121 => /192.168
.0.238:19994]state=SocketState(NONE->BEING_CONNECT)}2019-03-27 16:35:11 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='192.168.0.238', port=19994}
2019-03-27 16:35:11 [WARN ](c.n.p.r.c.DefaultPinpointClient    ) reconnectClientHandler:DefaultPinpointClientHandler@24d2a018{channel=[id: 0xb885ece6, /192.168.0.10:33137 => /192.168
.0.238:19994]state=SocketState(NONE->BEING_CONNECT)}2019-03-27 16:35:19 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='192.168.0.238', port=19994}
2019-03-27 16:35:19 [WARN ](c.n.p.r.c.DefaultPinpointClient    ) reconnectClientHandler:DefaultPinpointClientHandler@49ea2e93{channel=[id: 0x8cecdede, /192.168.0.10:33171 => /192.168
.0.238:19994]state=SocketState(NONE->BEING_CONNECT)}2019-03-27 16:35:27 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='192.168.0.238', port=19994}
2019-03-27 16:35:27 [WARN ](c.n.p.r.c.DefaultPinpointClient    ) reconnectClientHandler:DefaultPinpointClientHandler@a4f2ba9{channel=[id: 0x3e261216, /192.168.0.10:33183 => /192.168.
0.238:19994]state=SocketState(NONE->BEING_CONNECT)}2019-03-27 16:35:35 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='192.168.0.238', port=19994}
2019-03-27 16:35:35 [WARN ](c.n.p.r.c.DefaultPinpointClient    ) reconnectClientHandler:DefaultPinpointClientHandler@1151a08d{channel=[id: 0xb407d956, /192.168.0.10:33205 => /192.168
.0.238:19994]state=SocketState(NONE->BEING_CONNECT)}
```

I also get WARN per 8s.
oh my god!!!!!

**Comment by ighack** [comment]
I remove 

> proxy_timeout 30s;
> proxy_connect_timeout 35s;
