### ISSUE TITLE
how to show callstack for pinpoint-1.8.2?

### ISSUE THREAD

**Issue by coderztf** [naver/pinpoint#5316]
I have buildt the source code for pinpoint-web-1.8.2 . However , there is not chart like https://github.com/naver/pinpoint/blob/master/doc/images/ss_server-map.png in the right of page . I only see two charts which are 'Response Summary' and 'Load'.

**Comment by RoySRose** [comment]
Hello, @coderztf 

Were there any transactions from your application?

**Comment by coderztf** [comment]
Maybe not. I deployed the TestApp

**Comment by RoySRose** [comment]
@coderztf 

Try to create any transactions. If you are testing with the QuickStart, click any of the links shown at the first page.
