### ISSUE TITLE
logs are not visible for all services

### ISSUE THREAD

**Issue by adiboy6** [naver/pinpoint#5319]
I'm unable to view the logs while the pinpoint web is running.
Its only showing the logs when for the applications.
please help me out

**Comment by Xylus** [comment]
Hi @adiboy6 
I don't quite understand your issue, could you explain what's happening with more detail?

**Comment by adiboy6** [comment]
I unable to check the logs for all the request in pinpoint web...
for example when I'm creating a user group, or a user

**Comment by Xylus** [comment]
Hmm okay, that does not help...
Could you create a new issue using [this template](https://github.com/naver/pinpoint/issues/new?template=troubleshooting.md) and fill it out with as much as detail as possible?
