### ISSUE TITLE
Can I manage Applications by group？

### ISSUE THREAD

**Issue by wuluotianqing** [naver/pinpoint#5320]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

**Comment by wuluotianqing** [comment]
In fact, our systems is composed of multiple micro-services. When I access many micro-services of the system, it's difficult to find applications that I want. Can I group applications on Pinpoint Web?

**Comment by Xylus** [comment]
Hi @wuluotianqing 
Grouping up applications at the UI level is something we're looking to add in the future.
Until then you could try adding applications to favorites by clicking on the cog-wheel button at the top right corner of the main page.

**Comment by wuluotianqing** [comment]
@Xylus Wow，It will be cool. So has been scheduled this feature on which version in the future?How long will it be waiting?

**Comment by Xylus** [comment]
@wuluotianqing Don't have a set schedule for it yet :( but we'll look into adding it soon!

**Comment by wuluotianqing** [comment]
@Xylus Fine ,Thanks~
