### ISSUE TITLE
How to modify pinpoint-agent log level

### ISSUE THREAD

**Issue by lanyuange** [naver/pinpoint#5327]
I'd like to pinpoint -agent log level to error, modified the log4j. XML file, and have no effect

**Comment by adiboy6** [comment]
how are you running this one?
did you change log4j to true and Logback to false in pinpoint.config of agent?

**Comment by lanyuange** [comment]
Yes, but no effect,and Modify the log4j.XML files for the error log level

pinpoint.config
profiler.log4j.logging.transactioninfo=ture
profiler.logback.logging.transactioninfo=false

log4j.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">
<log4j:configuration xmlns:log4j='http://jakarta.apache.org/log4j/'>

    <appender name="console" class="org.apache.log4j.ConsoleAppender">
        <param name="Threshold" value="ERROR"/>
        <layout class="org.apache.log4j.EnhancedPatternLayout">
            
            <param name="ConversionPattern" value="%d{yyyy-MM-dd HH:mm:ss} [%-5p](%-35.35c{1.}) %m%n"/>
        </layout>
    </appender>

    <appender name="dailyRollingFile" class="org.apache.log4j.DailyRollingFileAppender">
        <param name="file" value="${pinpoint.log}/${pinpoint.agentId}-pinpoint.log"/>
        <param name="Append" value="true"/>
        <param name="DatePattern" value="'.'yyyy-MM-dd"/>

        <layout class="org.apache.log4j.EnhancedPatternLayout">
            
            <param name="ConversionPattern" value="%d{yyyy-MM-dd HH:mm:ss} [%-5p](%-35.35c{1.}) %m%n"/>
        </layout>
    </appender>

    <appender name="rollingFile" class="org.apache.log4j.RollingFileAppender">
        <param name="file" value="${pinpoint.log}/${pinpoint.agentId}-pinpoint.log"/>
        <param name="append" value="true"/>
        <param name="maxFileSize" value="10MB"/>
        <param name="maxBackupIndex" value="20"/>
        <layout class="org.apache.log4j.EnhancedPatternLayout">
            
            <param name="ConversionPattern" value="%d{yyyy-MM-dd HH:mm:ss} [%-5p](%-35.35c{1.}) %m%n"/>
        </layout>
    </appender>

    <logger name="com.navercorp.pinpoint" additivity="false">
        <level value="ERROR"/>
        <appender-ref ref="console"/>
        <appender-ref ref="rollingFile"/>
    </logger>

    <root>
        <level value="ERROR"/>
        <appender-ref ref="rollingFile"/>
    </root>
</log4j:configuration>

**Comment by adiboy6** [comment]
@lanyuange 
are you running pinpoint using quickstart or the other one?

**Comment by lanyuange** [comment]
The other one

**Comment by adiboy6** [comment]
try changing in this one:
web/src/main/resources-local/log4j.xml

**Comment by Xylus** [comment]
Hi @lanyuange 
The agent's bootstrap log is logged to `System.out` and `System.err` and this isn't governed by the agent's *log4j.xml* settings as these are logged before the logging system is set up by the agent.
Could it be that the log you're seeing (in console, or wherever you've piped `System.out` to) is the bootstrap log?
(Bootstrap logs are logged from `com.navercorp.pinpoint.bootstrap` packages btw)

Logs that are affected by the agent's *log4j.xml* are written to a file under `$PINPOINT_AGENT/log` directory so you can check if the agent's log level is working or not.

Please let me know if this is not what you're experiencing.

**Comment by lanyuange** [comment]
Can I change the log level of the pinpoint to error when the application starts?

**Comment by Xylus** [comment]
Are you talking about the bootstrap log? or the agent log?

**Comment by lanyuange** [comment]
bootstrap log

**Comment by Xylus** [comment]
Ah, then currently no.
If you absolutely need this asap, then I'd suggest modifying **BootLogger.java** to fit your needs, rebuilding the agent and using it.

**Comment by lanyuange** [comment]
Thank you, now I know, I don’t absolutely need this.

**Comment by lanyuange** [comment]
I want to know when the official version of 1.8.2 can come out?

**Comment by lanyuange** [comment]
I want to know when the official version of 1.8.2 can come out?

**Comment by Xylus** [comment]
1.8.2 is already out :)
https://github.com/naver/pinpoint/releases/tag/1.8.2

**Comment by Xylus** [comment]
Looks like our main README isn't updated. Thanks for the reminder!

**Comment by lanyuange** [comment]
Thank you for your patience
