### ISSUE TITLE
why method args not viewed

### ISSUE THREAD

**Issue by ClamRen** [naver/pinpoint#5329]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

**Comment by RoySRose** [comment]
Hi @ClamRen 
I don't quite understand your issue, too little info.
can you explain with more detail?
