### ISSUE TITLE
Springboot + Dockers + PinpointAgent

### ISSUE THREAD

**Issue by manjunathsv1947** [naver/pinpoint#5338]
Due to architectural complications of our project setup, We choose not to follow pinpoint-docker steps described by naver for now.
I have 2 machines, both have docker(Docker version 17.09.0-ce, build afdb6d4) running.

Machine 1 is my Mac.
----------------------------------------------------
container is setup as below
**jar:** /opt/java/microservice/application.jar
**pinpoint:** /opt/java/pinpoint/
I start the application using below command:
_java  -javaagent:/opt/java/pinpoint/pinpoint-agent-1.8.1/pinpoint-bootstrap-1.8.1.jar -Dpinpoint.agentId=agent1 -Dpinpoint.applicationName=Application1 -jar /opt/java/microservices/application/jar/application.jar_

**Result**:Application comes up  successfully, But there are some warnings from pinpoint.
Please check [machine1_warnings.log](https://github.com/naver/pinpoint/files/2956257/machine1_warnings.log)
 
I had to set profiler.jdbc.oracle=false to get rid of the above warnings. and Application comes up successfully.

Machine 2 is a CentOS machine on our datacenter.
-----------------------------------------------------------
container is setup as below
**jar**: /opt/java/microservice/application.jar
**pinpoint**: /opt/java/pinpoint/
I start the application using below command:
_java  -javaagent:/opt/java/pinpoint/pinpoint-agent-1.8.1/pinpoint-bootstrap-1.8.1.jar -Dpinpoint.agentId=agent1 -Dpinpoint.applicationName=Application1 -jar /opt/java/microservices/application/jar/application.jar_

**Result**:Application fails to start with attached errors
[machine_2_Error_1.log](https://github.com/naver/pinpoint/files/2956274/machine_2_Error_1.log)

I  set profiler.jdbc.oracle=false and re-run the application. Application again fails with attached
errors [machine_2_error_2.log](https://github.com/naver/pinpoint/files/2956282/machine_2_error_2.log)

I am using same docker image in both the machines and the same version of pinpoint-agent.
**note**:  If I don't attach the -javaagent(pinpoint) argument. There is no issue!! Application in machine 2 comes up successfully.

Can you please help us understand the issue further?

**Comment by RoySRose** [comment]
Hello, @manjunathsv1947 

What are you trying to say?
If you are asking if it works?
YES! :)

**Comment by manjunathsv1947** [comment]
> Hello, @manjunathsv1947
> 
> What are you trying to say?
> If you are asking if it works?
> YES! :)

Hi, Sorry I was editing! Can you please reopen the issue to be addressed.
