### ISSUE TITLE
HttpClient4 request java.net.sockettimeoutException time out

### ISSUE THREAD

**Issue by pengzai123** [naver/pinpoint#5342]
#### What version of pinpoint are you using?
pinpoint-agent-1.8.0

#### Describe the bug
HttpClient4 request java.net.sockettimeoutException :33,000 milliseconds timeout on connection http-outgoing-0 [ACTIVE] [RequestId]: null

#### What did you do to trigger the bug?
Steps to reproduce, for example:
The httpclient 4.x request address appears
Final check, pinpoint. config settings
Profiler. apache. httpclient4. param = false
Profiler. apache. httpclient4. cookie = false
Profiler. apache. httpclient4. entity = false
Profiler. apache. httpclient4. entity. statuscode = false
Just normal

**Comment by pengzai170** [comment]
the some
