### ISSUE TITLE
pinpoint maven do not compile.

### ISSUE THREAD

**Issue by joses872** [naver/pinpoint#5349]
Hi, i'm having an issue compiling pinpoint.

i already set my environmet vars
############################################################
export JAVA_HOME=/opt/apm/jdk1.8.0_192
PATH=$PATH:$HOME/bin
export JAVA_6_HOME=/opt/apm/jdk1.6.0_45/bin
export JAVA_7_HOME=/opt/apm/jdk1.7.0_80/bin
export JAVA_8_HOME=/opt/apm/jdk1.8.0_192/bin
export JAVA_9_HOME=/opt/apm/jdk-9.0.4/bin
############################################################

but when i tried to compile the code i got the next error.
############################################################
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.navercorp.pinpoint:pinpoint-grpc:jar:1.9.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: io.grpc:grpc-stub:jar -> duplicate declaration of version ${grpc.version} @ co$
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: linux
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 4.15
[INFO] os.detected.version.major: 4
[INFO] os.detected.version.minor: 15
[INFO] os.detected.release: ubuntu
[INFO] os.detected.release.version: 18.04
[INFO] os.detected.release.like.ubuntu: true
[INFO] os.detected.release.like.debian: true
[INFO] os.detected.classifier: linux-x86_64
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] pinpoint                                                           [pom]
[INFO] pinpoint-annotations                                               [jar]
[INFO] pinpoint-commons                                                   [jar]
[INFO] pinpoint-thrift                                                    [jar]
[INFO] pinpoint-grpc                                                      [jar]
[INFO] pinpoint-bootstrap-core                                            [jar]
[INFO] pinpoint-bootstrap                                                 [jar]
[INFO] pinpoint-rpc                                                       [jar]
[INFO] pinpoint-plugins-loader                                            [jar]
[INFO] pinpoint-profiler                                                  [jar]
[INFO] pinpoint-profiler-test                                             [jar]
[INFO] pinpoint-profiler-optional-parent                                  [pom]
[INFO] pinpoint-profiler-optional-jdk6                                    [jar]
[INFO] pinpoint-profiler-optional-jdk7                                    [jar]
[INFO] pinpoint-test                                                      [jar]
[INFO] pinpoint-profiler-optional-jdk8                                    [jar]
[INFO] pinpoint-profiler-optional-jdk9                                    [jar]
[INFO] pinpoint-profiler-optional                                         [pom]
[INFO] pinpoint-plugins                                                   [pom]
[INFO] pinpoint-common-servlet                                            [jar]
[INFO] pinpoint-external-plugins                                          [jar]
[INFO] pinpoint-httpclient3-plugin                                        [jar]
[INFO] pinpoint-httpclient4-plugin                                        [jar]
[INFO] pinpoint-ning-asynchttpclient-plugin                               [jar]
[INFO] pinpoint-resttemplate-plugin                                       [jar]
[INFO] pinpoint-netty-plugin                                              [jar]
[INFO] pinpoint-gson-plugin                                               [jar]
[INFO] pinpoint-cubrid-jdbc-driver-plugin                                 [jar]
[INFO] pinpoint-mysql-jdbc-driver-plugin                                  [jar]
[INFO] pinpoint-mariadb-jdbc-driver-plugin                                [jar]
[INFO] pinpoint-postgresql-jdbc-driver-plugin                             [jar]
[INFO] pinpoint-jtds-plugin                                               [jar]
[INFO] pinpoint-oracle-jdbc-driver-plugin                                 [jar]
[INFO] pinpoint-commons-dbcp-plugin                                       [jar]
[INFO] pinpoint-commons-dbcp2-plugin                                      [jar]
[INFO] pinpoint-hikaricp-plugin                                           [jar]
[INFO] pinpoint-cassandra-driver-plugin                                   [jar]
[INFO] pinpoint-jdk-http-plugin                                           [jar]
[INFO] pinpoint-commons-hbase                                             [jar]
[INFO] pinpoint-commons-server                                            [jar]
[INFO] pinpoint-redis-plugin                                              [jar]
[INFO] pinpoint-redis-lettuce-plugin                                      [jar]
[INFO] pinpoint-jboss-plugin                                              [jar]
[INFO] pinpoint-tomcat-plugin                                             [jar]
[INFO] pinpoint-json-lib-plugin                                           [jar]
[INFO] pinpoint-jackson-plugin                                            [jar]
[INFO] pinpoint-thrift-plugin                                             [jar]
[INFO] pinpoint-user-plugin                                               [jar]
[INFO] pinpoint-arcus-plugin                                              [jar]
[INFO] pinpoint-google-httpclient-plugin                                  [jar]
[INFO] pinpoint-grpc-plugin                                               [jar]
[INFO] pinpoint-jetty-plugin                                              [jar]
[INFO] pinpoint-websphere-plugin                                          [jar]
[INFO] pinpoint-spring-plugin                                             [jar]
[INFO] pinpoint-spring-boot-plugin                                        [jar]
[INFO] pinpoint-ibatis-plugin                                             [jar]
[INFO] pinpoint-mybatis-plugin                                            [jar]
[INFO] pinpoint-okhttp-plugin                                             [jar]
[INFO] pinpoint-log4j-plugin                                              [jar]
[INFO] pinpoint-logback-plugin                                            [jar]
[INFO] pinpoint-dubbo-plugin                                              [jar]
[INFO] pinpoint-activemq-client-plugin                                    [jar]
[INFO] pinpoint-cxf-plugin                                                [jar]
[INFO] pinpoint-hystrix-plugin                                            [jar]
[INFO] pinpoint-vertx-plugin                                              [jar]
[INFO] pinpoint-resin-plugin                                              [jar]
[INFO] pinpoint-jsp-plugin                                                [jar]
[INFO] pinpoint-rxjava-plugin                                             [jar]
[INFO] pinpoint-rabbitmq-plugin                                           [jar]
[INFO] pinpoint-weblogic-plugin                                           [jar]
[INFO] pinpoint-akka-http-plugin                                          [jar]
[INFO] pinpoint-undertow-plugin                                           [jar]
[INFO] pinpoint-undertow-servlet-plugin                                   [jar]
[INFO] pinpoint-kafka-plugin                                              [jar]
[INFO] pinpoint-mongodb-driver-plugin                                     [jar]
[INFO] pinpoint-fastjson-plugin                                           [jar]
[INFO] pinpoint-druid-plugin                                              [jar]
[INFO] pinpoint-hbase-plugin                                              [jar]
[INFO] pinpoint-openwhisk-plugin                                          [jar]
[INFO] pinpoint-plugins-assembly                                          [pom]
[INFO] pinpoint-agent-proxy-common                                        [jar]
[INFO] pinpoint-agent-proxy-apache-plugin                                 [jar]
[INFO] pinpoint-agent-proxy-app-plugin                                    [jar]
[INFO] pinpoint-agent-proxy-nginx-plugin                                  [jar]
[INFO] pinpoint-agent-plugins                                             [pom]
[INFO] pinpoint-bootstrap-java7                                           [jar]
[INFO] pinpoint-bootstrap-java8                                           [jar]
[INFO] pinpoint-bootstrap-java9                                           [jar]
[INFO] pinpoint-tools                                                     [jar]
[INFO] pinpoint-agent-distribution                                        [jar]
[INFO] pinpoint-agent-it                                                  [jar]
[INFO] pinpoint-collector                                                 [war]
[INFO] pinpoint-plugin-bom                                                [pom]
[INFO] pinpoint-web                                                       [war]
[INFO] pinpoint-hbase-distribution                                        [pom]
[INFO] pinpoint-flink                                                     [jar]
[INFO]
[INFO] ------------------< com.navercorp.pinpoint:pinpoint >-------------------
[INFO] Building pinpoint 1.9.0-SNAPSHOT                                  [1/96]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-pinpoint-build-requirements) @ pinpoint ---
[INFO]
[INFO] --- animal-sniffer-maven-plugin:1.17:check (ensure-java-1.6-class-library) @ pinpoint ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.0
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ pinpoint ---
[INFO] Installing /opt/apm/pinpoint-master/pom.xml to /root/.m2/repository/com/navercorp/pinpoint/pinpoint/1.9.0-SNAPSHOT/pinpoint-1.9.0-SNAPSHOT.pom
[INFO]
[INFO] ------------< com.navercorp.pinpoint:pinpoint-annotations >-------------
[INFO] Building pinpoint-annotations 1.9.0-SNAPSHOT                      [2/96]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-pinpoint-build-requirements) @ pinpoint-annotations ---
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ pinpoint-annotations ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] skip non existing resourceDirectory /opt/apm/pinpoint-master/annotations/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ pinpoint-annotations ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /opt/apm/pinpoint-master/annotations/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] pinpoint 1.9.0-SNAPSHOT ............................ SUCCESS [  2.376 s]
[INFO] pinpoint-annotations ............................... FAILURE [  0.687 s]
[INFO] pinpoint-commons ................................... SKIPPED
[INFO] pinpoint-thrift .................................... SKIPPED
[INFO] pinpoint-grpc ...................................... SKIPPED
[INFO] pinpoint-bootstrap-core ............................ SKIPPED
[INFO] pinpoint-bootstrap ................................. SKIPPED
[INFO] pinpoint-rpc ....................................... SKIPPED
[INFO] pinpoint-plugins-loader ............................ SKIPPED
[INFO] pinpoint-profiler .................................. SKIPPED
[INFO] pinpoint-profiler-test ............................. SKIPPED
[INFO] pinpoint-profiler-optional-parent .................. SKIPPED
[INFO] pinpoint-profiler-optional-jdk6 .................... SKIPPED
[INFO] pinpoint-profiler-optional-jdk7 .................... SKIPPED
[INFO] pinpoint-test ...................................... SKIPPED
[INFO] pinpoint-profiler-optional-jdk8 .................... SKIPPED
[INFO] pinpoint-profiler-optional-jdk9 .................... SKIPPED
[INFO] pinpoint-profiler-optional ......................... SKIPPED
[INFO] pinpoint-plugins ................................... SKIPPED
[INFO] pinpoint-common-servlet ............................ SKIPPED
[INFO] pinpoint-external-plugins .......................... SKIPPED
[INFO] pinpoint-httpclient3-plugin ........................ SKIPPED
[INFO] pinpoint-httpclient4-plugin ........................ SKIPPED
[INFO] pinpoint-ning-asynchttpclient-plugin ............... SKIPPED
[INFO] pinpoint-resttemplate-plugin ....................... SKIPPED
[INFO] pinpoint-netty-plugin .............................. SKIPPED
[INFO] pinpoint-gson-plugin ............................... SKIPPED
[INFO] pinpoint-cubrid-jdbc-driver-plugin ................. SKIPPED
[INFO] pinpoint-mysql-jdbc-driver-plugin .................. SKIPPED
[INFO] pinpoint-mariadb-jdbc-driver-plugin ................ SKIPPED
[INFO] pinpoint-postgresql-jdbc-driver-plugin ............. SKIPPED
[INFO] pinpoint-jtds-plugin ............................... SKIPPED
[INFO] pinpoint-oracle-jdbc-driver-plugin ................. SKIPPED
[INFO] pinpoint-commons-dbcp-plugin ....................... SKIPPED
[INFO] pinpoint-commons-dbcp2-plugin ...................... SKIPPED
[INFO] pinpoint-hikaricp-plugin ........................... SKIPPED
[INFO] pinpoint-commons-dbcp2-plugin ...................... SKIPPED
[INFO] pinpoint-hikaricp-plugin ........................... SKIPPED
[INFO] pinpoint-cassandra-driver-plugin ................... SKIPPED
[INFO] pinpoint-jdk-http-plugin ........................... SKIPPED
[INFO] pinpoint-commons-hbase ............................. SKIPPED
[INFO] pinpoint-commons-server ............................ SKIPPED
[INFO] pinpoint-redis-plugin .............................. SKIPPED
[INFO] pinpoint-redis-lettuce-plugin ...................... SKIPPED
[INFO] pinpoint-jboss-plugin .............................. SKIPPED
[INFO] pinpoint-tomcat-plugin ............................. SKIPPED
[INFO] pinpoint-json-lib-plugin ........................... SKIPPED
[INFO] pinpoint-jackson-plugin ............................ SKIPPED
[INFO] pinpoint-thrift-plugin ............................. SKIPPED
[INFO] pinpoint-user-plugin ............................... SKIPPED
[INFO] pinpoint-arcus-plugin .............................. SKIPPED
[INFO] pinpoint-google-httpclient-plugin .................. SKIPPED
[INFO] pinpoint-grpc-plugin ............................... SKIPPED
[INFO] pinpoint-jetty-plugin .............................. SKIPPED
[INFO] pinpoint-websphere-plugin .......................... SKIPPED
[INFO] pinpoint-spring-plugin ............................. SKIPPED
[INFO] pinpoint-spring-boot-plugin ........................ SKIPPED
[INFO] pinpoint-ibatis-plugin ............................. SKIPPED
[INFO] pinpoint-mybatis-plugin ............................ SKIPPED
[INFO] pinpoint-okhttp-plugin ............................. SKIPPED
[INFO] pinpoint-log4j-plugin .............................. SKIPPED
[INFO] pinpoint-logback-plugin ............................ SKIPPED
[INFO] pinpoint-dubbo-plugin .............................. SKIPPED
[INFO] pinpoint-activemq-client-plugin .................... SKIPPED
[INFO] pinpoint-cxf-plugin ................................ SKIPPED
[INFO] pinpoint-hystrix-plugin ............................ SKIPPED
[INFO] pinpoint-vertx-plugin .............................. SKIPPED
[INFO] pinpoint-resin-plugin .............................. SKIPPED
[INFO] pinpoint-jsp-plugin ................................ SKIPPED
[INFO] pinpoint-rxjava-plugin ............................. SKIPPED
[INFO] pinpoint-rabbitmq-plugin ........................... SKIPPED
[INFO] pinpoint-weblogic-plugin ........................... SKIPPED
[INFO] pinpoint-akka-http-plugin .......................... SKIPPED
[INFO] pinpoint-undertow-plugin ........................... SKIPPED
[INFO] pinpoint-undertow-servlet-plugin ................... SKIPPED
[INFO] pinpoint-kafka-plugin .............................. SKIPPED
[INFO] pinpoint-mongodb-driver-plugin ..................... SKIPPED
[INFO] pinpoint-fastjson-plugin ........................... SKIPPED
[INFO] pinpoint-druid-plugin .............................. SKIPPED
[INFO] pinpoint-hbase-plugin .............................. SKIPPED
[INFO] pinpoint-openwhisk-plugin .......................... SKIPPED
[INFO] pinpoint-plugins-assembly .......................... SKIPPED
[INFO] pinpoint-agent-proxy-common ........................ SKIPPED
[INFO] pinpoint-agent-proxy-apache-plugin ................. SKIPPED
[INFO] pinpoint-agent-proxy-app-plugin .................... SKIPPED
[INFO] pinpoint-agent-proxy-nginx-plugin .................. SKIPPED
[INFO] pinpoint-agent-plugins ............................. SKIPPED
[INFO] pinpoint-bootstrap-java7 ........................... SKIPPED
[INFO] pinpoint-bootstrap-java8 ........................... SKIPPED
[INFO] pinpoint-bootstrap-java9 ........................... SKIPPED
[INFO] pinpoint-tools ..................................... SKIPPED
[INFO] pinpoint-agent-distribution ........................ SKIPPED
[INFO] pinpoint-agent-it .................................. SKIPPED
[INFO] pinpoint-collector ................................. SKIPPED
[INFO] pinpoint-plugin-bom ................................ SKIPPED
[INFO] pinpoint-web ....................................... SKIPPED
[INFO] pinpoint-hbase-distribution ........................ SKIPPED
[INFO] pinpoint-flink 1.9.0-SNAPSHOT ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.211 s
[INFO] Finished at: 2019-03-13T18:20:21Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project pinpoint-annotations: Compilation failure -> [$
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pinpoint-annotations

what am i doing wrong? can somebody help me or guide on what steps i have to do to achieve the install?

i took the steps from the quick start guide at pinpoint site. (https://naver.github.io/pinpoint/quickstart.html)

my environment is a vps with ubuntu 18.04.

thanks for your comments and help. NOTE i add a file with -X debug option.

[log.txt](https://github.com/naver/pinpoint/files/2963084/log.txt)

**Comment by DevelopDestroyer** [comment]
Hi @joses872 

[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.

Pinpoint may fail to build if the Maven version isn't appropriate. Check out the Maven version. ^^

**Comment by joses872** [comment]
hi thanks for your reply.

how the maven version is not appropiated if i'm using the mvnw file inside of the downloaded files?
i guess the mvn file in the folder it must compile.

wich version do i have to use to compile from git version 1.8.2-RC1? if somebody can help me please.

**Comment by Xylus** [comment]
Hi @joses872 
Please check your `JAVA_6_HOME`, `JAVA_7_HOME`, `JAVA_8_HOME`, and `JAVA_9_HOME` variables.
Usually, java homes are set excluding the bin directory.
You have them set including the bin directory, and due to this, maven compiler plugin looks to be invoking `javac` from : `/opt/apm/jdk1.6.0_45/bin/bin/javac`.

**Comment by karthikeayan** [comment]
I am also facing the exact same issue, tried checking out different tags like 1.7.3, no luck.

```
[centos@server pinpoint]$ ./mvnw --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Maven home: /home/centos/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9
Java version: 1.8.0_191, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.10.0-957.5.1.el7.x86_64", arch: "amd64", family: "unix"
```

**Comment by Xylus** [comment]
Hi @karthikeayan 
Any maven debug log?

**Comment by karthikeayan** [comment]
I did shutdown my ec2 instance, will give the debug log once I have the instance up and running.

However, I haven't find anything useful in the debug log as far as I remember.
