### ISSUE TITLE
pinpoint agent  windows  tomcat  start mode

### ISSUE THREAD

**Issue by xynhaha** [naver/pinpoint#5351]
I install pinpoint agent  monitor tomcat  when use modify catalina.bat  in windows , startup and monitor  all  is ok 
but when i  use  service.bat install  service regedit service ,then  tomcat8w.exe add  in java option   
-Dpinpoint.applicationName=
-Dpinpoint.agentId=
-javaagent:c:/pinpoint-agent/pinpoint-bootstrap-1.8.2.jar
not work 
must modify start mode from jvm to java.

how do i do when using jvm mode , what difference between mode jvm and java i think  java 
 environment  config something wrong
tks

**Comment by Xylus** [comment]
Hi @xynhaha 
This looks like a Tomcat windows service issue. Pinpoint agent is added using `-javaagent` option just like any other agents.
Please check how to add jvm arguments when running Tomcat in jvm mode.
