### ISSUE TITLE
application‘s stack log has some pinpoint-agent thread locked info

### ISSUE THREAD

**Issue by fionaliupw** [naver/pinpoint#5361]
pinpoint 1.8.0

 - question:
Slow active-threads occurred every day. Following is the application's stack log. There are two runnable threads about pinpoint agent. Please help to check Whether pinpoint-agent causes application's slow threads. Thank you very much.

- log info:

"Pinpoint-stat-monitor(13-0)" daemon prio=10 tid=0x00002aab68007000
nid=0x242c waiting on condition [0x00002aab6671b000]
   java.lang.Thread.State: TIMED_WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for  <0x00000006ca99ff28> (a
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.parkNanos
(LockSupport.java:196)
at java.util.concurrent.locks.AbstractQueuedSynchronizer
$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2025)
at java.util.concurrent.DelayQueue.take(DelayQueue.java:164)
at java.util.concurrent.ScheduledThreadPoolExecutor
$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:609)
at java.util.concurrent.ScheduledThreadPoolExecutor
$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:602)
at java.util.concurrent.ThreadPoolExecutor.getTask
(ThreadPoolExecutor.java:967)
at java.util.concurrent.ThreadPoolExecutor$Worker.run
(ThreadPoolExecutor.java:927)
at java.lang.Thread.run(Thread.java:682)

"Pinpoint-deadlock-monitor" daemon prio=10 tid=0x00002aab68006000
nid=0x242a waiting on condition [0x00002aab65c10000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
at java.lang.Thread.sleep(Native Method)
at
com.navercorp.pinpoint.profiler.monitor.DeadlockMonitorTask.waitNextTask
(DeadlockMonitorTask.java:164)
at com.navercorp.pinpoint.profiler.monitor.DeadlockMonitorTask.run
(DeadlockMonitorTask.java:52)
at java.lang.Thread.run(Thread.java:682)

"Pinpoint-AgentInfoSender-Timer" daemon prio=10 tid=0x00002aab68005000
nid=0x2429 in Object.wait() [0x00002aab65e12000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
at java.lang.Object.wait(Native Method)
- waiting on <0x00000006ca931520> (a java.util.TaskQueue)
at java.util.TimerThread.mainLoop(Timer.java:509)
- locked <0x00000006ca931520> (a java.util.TaskQueue)
at java.util.TimerThread.run(Timer.java:462)

"Pinpoint-UdpStatDataExecutor(12-0)" daemon prio=10 tid=0x000000004a4e6000
nid=0x2427 waiting on condition [0x00002aab66519000]
   java.lang.Thread.State: TIMED_WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for  <0x00000006ca956d08> (a
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.parkNanos
(LockSupport.java:196)
at java.util.concurrent.locks.AbstractQueuedSynchronizer
$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2025)
at java.util.concurrent.LinkedBlockingQueue.poll
(LinkedBlockingQueue.java:424)
at
com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.takeOne
(AsyncQueueingExecutor.java:127)
at
com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute
(AsyncQueueingExecutor.java:94)
at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.run
(AsyncQueueingExecutor.java:79)
at java.lang.Thread.run(Thread.java:682)

"Pinpoint-UdpSpanDataExecutor(11-0)" daemon prio=10 tid=0x000000004a56b000
nid=0x2426 waiting on condition [0x00002aab6691d000]
   java.lang.Thread.State: TIMED_WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for  <0x00000006ca97b270> (a
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.parkNanos
(LockSupport.java:196)
at java.util.concurrent.locks.AbstractQueuedSynchronizer
$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2025)
at java.util.concurrent.LinkedBlockingQueue.poll
(LinkedBlockingQueue.java:424)
at
com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.takeOne
(AsyncQueueingExecutor.java:127)
at
com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute
(AsyncQueueingExecutor.java:94)
at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.run
(AsyncQueueingExecutor.java:79)
at java.lang.Thread.run(Thread.java:682)

"Pinpoint-TcpDataSender(Default)-Executor(10-0)" daemon prio=10
tid=0x000000004a630000 nid=0x2425 waiting on condition [0x00002aab65b0f000]
   java.lang.Thread.State: TIMED_WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for  <0x00000006ca660048> (a
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.parkNanos
(LockSupport.java:196)
at java.util.concurrent.locks.AbstractQueuedSynchronizer
$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2025)
at java.util.concurrent.LinkedBlockingQueue.poll
(LinkedBlockingQueue.java:424)
at
com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.takeOne
(AsyncQueueingExecutor.java:127)
at
com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute
(AsyncQueueingExecutor.java:94)
at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.run
(AsyncQueueingExecutor.java:79)
at java.lang.Thread.run(Thread.java:682)

"Pinpoint-TcpDataSender(Default)-Timer(9-0)" daemon prio=10
tid=0x000000004a5d1800 nid=0x2424 waiting on condition [0x00002aab6661a000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
at java.lang.Thread.sleep(Native Method)
at org.jboss.netty.util.HashedWheelTimer$Worker.waitForNextTick
(HashedWheelTimer.java:445)
at org.jboss.netty.util.HashedWheelTimer$Worker.run
(HashedWheelTimer.java:364)
at org.jboss.netty.util.ThreadRenamingRunnable.run
(ThreadRenamingRunnable.java:108)
at java.lang.Thread.run(Thread.java:682)

"Pinpoint-PinpointClientHandler-Timer(8-0)" daemon prio=10
tid=0x000000004a3d2000 nid=0x2421 waiting on condition [0x00002aab66115000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
at java.lang.Thread.sleep(Native Method)
at org.jboss.netty.util.HashedWheelTimer$Worker.waitForNextTick
(HashedWheelTimer.java:445)
at org.jboss.netty.util.HashedWheelTimer$Worker.run
(HashedWheelTimer.java:364)
at org.jboss.netty.util.ThreadRenamingRunnable.run
(ThreadRenamingRunnable.java:108)
at java.lang.Thread.run(Thread.java:682)

"Pinpoint-Client-Worker(7-0)" daemon prio=10 tid=0x000000004a5e1000
nid=0x241c runnable [0x00002aab66014000]
   java.lang.Thread.State: RUNNABLE
at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:210)
at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:65)
at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:69)
- locked <0x00000006ca6600d8> (a sun.nio.ch.Util$2)
- locked <0x00000006ca6600f0> (a java.util.Collections
$UnmodifiableSet)
- locked <0x00000006ca660fe8> (a sun.nio.ch.EPollSelectorImpl)
at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:80)
at org.jboss.netty.channel.socket.nio.SelectorUtil.select
(SelectorUtil.java:68)
at org.jboss.netty.channel.socket.nio.AbstractNioSelector.select
(AbstractNioSelector.java:434)
at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run
(AbstractNioSelector.java:212)
at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run
(AbstractNioWorker.java:89)
at org.jboss.netty.channel.socket.nio.NioWorker.run
(NioWorker.java:178)
at org.jboss.netty.util.ThreadRenamingRunnable.run
(ThreadRenamingRunnable.java:108)
at org.jboss.netty.util.internal.DeadLockProofWorker$1.run
(DeadLockProofWorker.java:42)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask
(ThreadPoolExecutor.java:905)
at java.util.concurrent.ThreadPoolExecutor$Worker.run
(ThreadPoolExecutor.java:928)
at java.lang.Thread.run(Thread.java:682)

"Pinpoint-Client-Boss(6-0)" daemon prio=10 tid=0x000000004a59c000
nid=0x241b runnable [0x00002aab66317000]
   java.lang.Thread.State: RUNNABLE
at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:210)
at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:65)
at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:69)
- locked <0x00000006ca660150> (a sun.nio.ch.Util$2)
- locked <0x00000006ca660168> (a java.util.Collections
$UnmodifiableSet)
- locked <0x00000006ca661030> (a sun.nio.ch.EPollSelectorImpl)
at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:80)
at org.jboss.netty.channel.socket.nio.SelectorUtil.select
(SelectorUtil.java:68)
at org.jboss.netty.channel.socket.nio.AbstractNioSelector.select
(AbstractNioSelector.java:434)
at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run
(AbstractNioSelector.java:212)
at org.jboss.netty.channel.socket.nio.NioClientBoss.run
(NioClientBoss.java:42)
at org.jboss.netty.util.ThreadRenamingRunnable.run
(ThreadRenamingRunnable.java:108)
at org.jboss.netty.util.internal.DeadLockProofWorker$1.run
(DeadLockProofWorker.java:42)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask
(ThreadPoolExecutor.java:905)
at java.util.concurrent.ThreadPoolExecutor$Worker.run
(ThreadPoolExecutor.java:928)
at java.lang.Thread.run(Thread.java:682)

"Pinpoint-SocketFactory-Timer(5-0)" daemon prio=10 tid=0x000000004a64d800
nid=0x2419 waiting on condition [0x00002aab6681c000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
at java.lang.Thread.sleep(Native Method)
at org.jboss.netty.util.HashedWheelTimer$Worker.waitForNextTick
(HashedWheelTimer.java:445)
at org.jboss.netty.util.HashedWheelTimer$Worker.run
(HashedWheelTimer.java:364)
at org.jboss.netty.util.ThreadRenamingRunnable.run
(ThreadRenamingRunnable.java:108)
at java.lang.Thread.run(Thread.java:682)

**Comment by koo-taejin** [comment]
hi @fionaliupw 

The threaddump  does not seem to have any problems with the thread created by Pinpoint. 
Even if there is a problem, we cannot confirm it with the information you gave us. 

I recommand  you to look at the following article and find out exactly what kind of thread is wrong with it.

https://dzone.com/articles/how-analyze-java-thread-dumps

thanks.
