### ISSUE TITLE
Unable to get trace details in pinpoint web for jetty server

### ISSUE THREAD

**Issue by Swarup-git** [naver/pinpoint#5366]
Hi Team,

Thanks a lot for building this amazing tracing tool.
Till now I've followed all the installation steps in https://naver.github.io/pinpoint/installation.html and currently I'm able to monitor call traces for a local tomcat server.

However, when I'm trying to get details of a local jetty server, although I'm able to get JVM stats, no trace data is visible for the same. Attaching snapshot of pinpoint dashboard for the same.
![image](https://user-images.githubusercontent.com/39518445/54528020-b06ce680-49a1-11e9-9330-ed6411c7f0ea.png)

Can you please help me out here on the next steps in this case. I've tried to refer to this link, however, couldn't get much help on this. I'm a performance tester and do not have access to actual application code to do any changes.
https://github.com/naver/pinpoint/tree/master/plugins/jetty

Thanks in advance.
Kindly highlight for anything.

Regards,
Swarup

#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
master/v1.7.3/v1.7.2 etc.

#### Describe your problem**
A clear and concise description of what is not working.

#### What have you done?
Steps you have taken to trigger the problem, for example:
1. Launched '...' with agent
2. Tried tracing '...' (see agent log below)
3. Collector outputs trace log (see collector log below)
4. No trace shows up in the web UI (see web log below)

#### Logs
If applicable, please attach agent/collector/web DEBUG log that includes the part where you have encountered the problem. In case of agents, including the start-up log may be of great help.

#### Additional context
Add any other context about the problem here, such as affected library for agents, how your collector/web/hbase is set up if applicable.

**Comment by Xylus** [comment]
Hi @Swarup-git 
What version of Jetty are you using?
Also, could you post/send me the agent log in $PINPOINT_AGENT/log directory?

**Comment by Swarup-git** [comment]
Hi @Xylus ,
Thanks a lot for getting back to this.
PFB version details:
- Pinpoint version: 1.9.0
- Jetty version: 9.2.22.v20170606

The strange thing I'm noticing is that there's no log generated for this pinpoint agent (which I'm using for jetty) under $PINPOINT_AGENT directory. Can you please let me know where else to look for this log?

Also, PFB info which might be helpful for you to get the gist:
-  I've built pinpoint using the src file & using the steps mentioned in installation guideline. The command used to built is "./mvnw install -DskipTests=true". **root** credentials has been used for this.
- Then for tomcat, using the same root credentials, I've used below properties in catalina.sh & I'm able to see tomcat trace details in pinpoint web:
CATALINA_OPTS="$CATALINA_OPTS -javaagent:{location of pinpointAgent}/pinpoint-bootstrap-1.9.0-SNAPSHOT.jar"
CATALINA_OPTS="$CATALINA_OPTS -Dpinpoint.agentId=2"
CATALINA_OPTS="$CATALINA_OPTS -Dpinpoint.applicationName=tomcat"
- However, my jetty server runs with different system user, say X & I've placed the **pinpoint-agent-1.9.0-SNAPSHOT.tar.gz** from built pinpoints directory to X's directory.
- Extracted the contents and pasted below properties under java_opts of jetty config file:
"-javaagent:{location of this pinpointAgent}/pinpoint-bootstrap-1.9.0-SNAPSHOT.jar -Dpinpoint.agentId=1 -Dpinpoint.applicationName=Name"
- After this, I'm able to see JVM details in pinpoint web but as mentioned, nothing under traces.

Please reachout for anything.

**Comment by Xylus** [comment]
@Swarup-git 
The log should be generated under $PINPOINT_AGENT/log directory.
Before the log file is created however, you should be able to see pinpoint bootstrap logs printed in console (or wherever you've piped `System.out` to). You could check this to see if there's anything wrong.

Another thing to note is that you can share the same pinpoint agent installation directory between Tomcat and Jetty, though I think you've made them separate due to permissions.

That said, I've tried running the agent on Jetty 9.2.22.v20170606 on my machine and it seems to be working well.
If you could post the agent log (or bootstrap log if there is none), it would be helpful.
Thanks.

**Comment by Swarup-git** [comment]
Hi @Xylus,
PFA bootstrap.
It shows that agent started successfully. Kindly have a check.

To add up, Agent log file still doesn't comes under Agent directory.

Please guide.
[pinP_bootstrap.txt](https://github.com/naver/pinpoint/files/2987011/pinP_bootstrap.txt)

**Comment by Xylus** [comment]
Thanks for the log @Swarup-git 
There's this in your log:
```
2019-03-20 00:08:38 [INFO ](com.navercorp.pinpoint.bootstrap.PinpointStarter) pinpoint agent [com.navercorp.pinpoint.profiler.DefaultAgent] starting...
log4j:WARN No appenders could be found for logger (org.jboss.netty.channel.socket.nio.SelectorUtil).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

This might be weird but please check if there's *log4j.xml* file inside your `$PINPOINT_AGENT_FOR_JETTY/lib` directory.

**Comment by Swarup-git** [comment]
Hi @Xylus,

Thanks for checking this.
However, the log4j.xml is present in $PINPOINT_AGENT_FOR_JETTY/lib directory.

**Comment by Swarup-git** [comment]
Hi @Xylus,

There are few more lines in the bootstrap log under "pinpoint agent started normally":
log4j:WARN No appenders could be found for logger (root).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Is this because the pinpoint is built using 'root' & we're using other system user for this Jetty monitoring & sending the data to pinpoint collector which is run by 'root'?
Please advice on the needful.

**Comment by Xylus** [comment]
I think the "root" there means root appender.

That said, permission issue might be possible.
To check, could you try building pinpoint with the user running jetty, or [download](https://github.com/naver/pinpoint/releases) an agent binary and run using this?

**Comment by Swarup-git** [comment]
Hi @Xylus,

Thanks for your reply. 
Can you please let me know which agent version goes with pinpoint 1.9.0. 
My pinpoint version is that & I'm not able to locate same agent version in your shared download link

**Comment by Xylus** [comment]
Hi @Swarup-git 
You can use any agent version prior to 1.9.0-SNAPSHOT to connect to 1.9.0-SNAPSHOT collector.
So you might as well use the latest stable release, which is 1.8.2 - [link here](https://github.com/naver/pinpoint/releases/tag/1.8.2)

**Comment by Swarup-git** [comment]
Hi @Xylus,

I've tried with the v1.8.2 Agent, but still no luck.
Also, I had to force shutdown the hbase database once & after that when I've restarted everything, I'm not getting anything in pinpoint web. Even the earlier working tomcat stats are not visible either, neither any logs are getting generated for tomcat agent.
As I've checked the hbase logs, I could see below error is coming as part of hbase startup-2019-03-25 23:09:25,377 WARN  [localhost:59822.activeMasterManager] cleaner.CleanerChore: Can NOT create CleanerDelegate: org.apache.hadoop.hbase.master.snapshot.SnapshotLogCleaner
java.lang.NullPointerException
	at org.apache.hadoop.hbase.master.snapshot.SnapshotLogCleaner.init(SnapshotLogCleaner.java:74)
	at org.apache.hadoop.hbase.master.cleaner.CleanerChore.newFileCleaner(CleanerChore.java:121)
	at org.apache.hadoop.hbase.master.cleaner.CleanerChore.initCleanerChain(CleanerChore.java:98)
	at org.apache.hadoop.hbase.master.cleaner.CleanerChore.<init>(CleanerChore.java:77)
	at org.apache.hadoop.hbase.master.cleaner.CleanerChore.<init>(CleanerChore.java:57)
	at org.apache.hadoop.hbase.master.cleaner.LogCleaner.<init>(LogCleaner.java:49)
	at org.apache.hadoop.hbase.master.HMaster.startServiceThreads(HMaster.java:1146)
	at org.apache.hadoop.hbase.master.HMaster.finishActiveMasterInitialization(HMaster.java:726)
	at org.apache.hadoop.hbase.master.HMaster.access$600(HMaster.java:190)
	at org.apache.hadoop.hbase.master.HMaster$2.run(HMaster.java:1811)
	at java.lang.Thread.run(Thread.java:748)

Is this causing the issue now?
Please guide.
