### ISSUE TITLE
Can I trace java.lang and java.util methods ?

### ISSUE THREAD

**Issue by black-jack-j** [naver/pinpoint#5376]
- [x ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

I don't see calls like Stream.filter and so on. Is there any opportunity to include them ? If no, where I can see which methods from plain java are traced ?

**Comment by RoySRose** [comment]
Hello, @black-jack-j 

List of all libraries are here
https://naver.github.io/pinpoint/main.html#supported-modules

In which cases do you need to trace plain java?

If it's just a personal usage, check-out [plug-in development guide](https://naver.github.io/pinpoint/plugindevguide.html)

**Comment by emeroad** [comment]
@black-jack-j Hi~
The "java.*" package is protected by the UnmodifiableClassFilter

UnmodifiableClassFilter should also be modified to add functionality.
 - https://github.com/naver/pinpoint/blob/master/profiler/src/main/java/com/navercorp/pinpoint/profiler/UnmodifiableClassFilter.java

**Comment by black-jack-j** [comment]
Thanx a lot for making it clear to me!
