### ISSUE TITLE
Send email of the underlying APIs of the application which has more response time.

### ISSUE THREAD

**Issue by adiboy6** [naver/pinpoint#5386]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

I'd like to raise an alarm for the APIs whose response time is more and these are based upon the applications registered in PINPOINT

![Screenshot 2019-03-21 at 6 05 59 PM](https://user-images.githubusercontent.com/28995864/54752474-4acc6480-4c04-11e9-8d45-8c7d27ca4be6.png)

**Comment by Xylus** [comment]
Hi @adiboy6 
We don't currently support what you're looking for unfortunately. Statistical aggregation on APIs is what's missing, so you could implement what you're looking for using Flink (to make it scalable).
A simpler way that might work for you (if you don't have millions of traces in your pinpoint cluster) would be to simply create a batch that aggregates all APIs and have the alarm checker check on this.
Do note that in a high traffic environment, this won't work as the batch would take longer than it's interval.
