### ISSUE TITLE
why recorded arg can't be find from Call Tree when use private AnnotaionKey codes?

### ISSUE THREAD

**Issue by ClamRen** [naver/pinpoint#5425]
Definition AnnotaionKey codes:

public final class IceConstants {
    private IceConstants() {
    }

    public static final ServiceType ICE_PROVIDER_SERVICE_TYPE = ServiceTypeFactory.of(1900, "ICE_PROVIDER");
    public static final ServiceType ICE_CONSUMER_SERVICE_TYPE = ServiceTypeFactory.of(9900, "ICE_CONSUMER", RECORD_STATISTICS);
    public static final ServiceType ICE_PROVIDER_SERVICE_NO_STATISTICS_TYPE = ServiceTypeFactory.of(1901, "ICE");
    public static final AnnotationKey ICE_ARGS_ANNOTATION_KEY = AnnotationKeyFactory.of(900, "ice.args", VIEW_IN_RECORD_SET);
    public static final AnnotationKey ICE_RESULT_ANNOTATION_KEY = AnnotationKeyFactory.of(901, "ice.result", VIEW_IN_RECORD_SET);
    public static final AnnotationKey ICE_RPC_ANNOTATION_KEY = AnnotationKeyFactory.of(902, "ice.rpc", VIEW_IN_RECORD_SET);
    public static final AnnotationKey MY_ARGS_ANNOTATION_KEY = AnnotationKeyFactory.of(903, "myarg", VIEW_IN_RECORD_SET);

    public static final String META_DO_NOT_TRACE = "_ICE_DO_NOT_TRACE";
    public static final String META_TRANSACTION_ID = "_ICE_TRASACTION_ID";
    public static final String META_SPAN_ID = "_ICE_SPAN_ID";
    public static final String META_PARENT_SPAN_ID = "_ICE_PARENT_SPAN_ID";
    public static final String META_PARENT_APPLICATION_NAME = "_ICE_PARENT_APPLICATION_NAME";
    public static final String META_PARENT_APPLICATION_TYPE = "_ICE_PARENT_APPLICATION_TYPE";
    public static final String META_FLAGS = "_ICE_FLAGS";

    public static final String MONITOR_SERVICE_FQCN = "com";
}

public class IceTraceMetadataProvider implements TraceMetadataProvider {
    @Override
    public void setup(TraceMetadataSetupContext context) {
        context.addServiceType(IceConstants.ICE_PROVIDER_SERVICE_TYPE);
        context.addServiceType(IceConstants.ICE_CONSUMER_SERVICE_TYPE);
        context.addServiceType(IceConstants.ICE_PROVIDER_SERVICE_NO_STATISTICS_TYPE);
        context.addAnnotationKey(IceConstants.ICE_ARGS_ANNOTATION_KEY);
        context.addAnnotationKey(IceConstants.ICE_RESULT_ANNOTATION_KEY);
        context.addAnnotationKey(IceConstants.ICE_RPC_ANNOTATION_KEY);
        context.addAnnotationKey(IceConstants.MY_ARGS_ANNOTATION_KEY);
    }
}

@Override
    public void after(Object target, Object[] args, Object result, Throwable throwable)  {
        Trace trace = traceContext.currentTraceObject();
        SpanEventRecorder recorder = trace.currentSpanEventRecorder();

        recorder.recordApi(descriptor);

        StringBuilder argStr= new StringBuilder("ARG:");
        for (Object arg : args) {
            argStr.append(arg);
        }
        recorder.recordAttribute(IceConstants.ICE_ARGS_ANNOTATION_KEY, argStr.toString());
        recorder.recordAttribute(IceConstants.ICE_RESULT_ANNOTATION_KEY, result);
        if (throwable != null) {
            recorder.recordException(throwable);
        }
        ClientComm.acceptSemaphore.release();
    }

![Screenshot from 2019-03-27 16-32-02](https://user-images.githubusercontent.com/26928232/55061236-311c9880-50ae-11e9-97f1-2eb0786184a4.png)

**Comment by Xylus** [comment]
Do you want the annotation value to appear in the "argument" column next to "endWriteParams()"?
If so, you'll have to register **AnnotationKeyMatcher** to a **ServiceType**.
Please check out **HttpClient4TypeProvider** for an example.

**Comment by ClamRen** [comment]
Thr argument can be displayed, when I change public static final "ServiceType ICE_PROVIDER_SERVICE_TYPE = ServiceTypeFactory.of(1900, "ICE_PROVIDER");" to “public static final ServiceType ICE_PROVIDER_SERVICE_TYPE = ServiceTypeFactory.of(1900, "ICE_PROVIDER", RECORD_STATISTICS);“ .But my ServerMap have additional icon.
![Screenshot from 2019-03-27 18-23-43](https://user-images.githubusercontent.com/26928232/55068899-cd9a6700-50bd-11e9-9a41-4a3774969398.png)
The "0.0.0.0:4061" icon shouldn't be showed.  "0.0.0.0:4061" is the endpoint of "Cp4ccDecoder1".

            String endPoint = "0.0.0.0:4061";
            recorder.recordEndPoint(endPoint);
            recorder.recordDestinationId(endPoint);

**Comment by Xylus** [comment]
The code for creating the server map above can be found in **FilteredMapBuilder**, specifically the `addNodeFromSpanEvent(...)` method.
I'd suggest debugging this method, checking your span events to see why the unknown cloud node is being generated.
