### ISSUE TITLE
Could do you tell me what  UDP port-9996 is?

### ISSUE THREAD

**Issue by ighack** [naver/pinpoint#5426]
I have two collector in 192.168.0.238,192.168.0.10.
I use nginx in front of that.
when I use netstat,I found 483 connect to 9996.
like this:

> udp        0      0 192.168.0.238:17015     192.168.0.10:9996       ESTABLISHED 22115/nginx: worker 
> udp        0      0 192.168.0.238:17047     192.168.0.10:9996       ESTABLISHED 22115/nginx: worker 
> udp        0      0 192.168.0.238:17058     192.168.0.238:9996      ESTABLISHED 22115/nginx: worker 
> udp        0      0 192.168.0.238:17410     192.168.0.238:9996      ESTABLISHED 22115/nginx: worker 
> udp        0      0 192.168.0.238:17614     192.168.0.10:9996       ESTABLISHED 22115/nginx: worker 
> udp        0      0 192.168.0.238:17758     192.168.0.10:9996       ESTABLISHED 22115/nginx: worker 
> udp        0      0 192.168.0.238:17883     192.168.0.10:9996       ESTABLISHED 22115/nginx: worker 
> udp        0      0 192.168.0.238:17891     192.168.0.238:9996      ESTABLISHED 22115/nginx: worker 
> udp        0      0 192.168.0.238:18017     192.168.0.10:9996       ESTABLISHED 22115/nginx: worker 
> udp        0      0 192.168.0.238:18147     192.168.0.238:9996      ESTABLISHED 22115/nginx: worker 
> udp        0      0 192.168.0.238:18230     192.168.0.10:9996       ESTABLISHED 22115/nginx: worker 
> udp        0      0 192.168.0.238:18265     192.168.0.10:9996       ESTABLISHED 22115/nginx: worker 
> udp        0      0 192.168.0.238:18407     192.168.0.238:9996      ESTABLISHED 22115/nginx: worker 
> udp        0      0 192.168.0.238:19131     192.168.0.238:9996      ESTABLISHED 22115/nginx: worker 
> udp        0      0 192.168.0.238:19464     192.168.0.238:9996      ESTABLISHED 22115/nginx: worker 
> udp        0      0 192.168.0.238:19843     192.168.0.238:9996      ESTABLISHED 22115/nginx: worker 

but I only have 30 connect to 9994.
why?

**Comment by koo-taejin** [comment]
you can see role of udp  port  in pinpoint-collector.properties.

```
collector.receiver.span.udp.port=9996
```

**Comment by ighack** [comment]
I know that in pinpoint-collector.properties
but,I want to know why do I have too many connection on 9996 ?
tips:I only have a few connection on 9994.

**Comment by koo-taejin** [comment]
It depends on how you use proxy, or on agent connects rules. 
I think it is not pinpoint collector module problem with the .

**Comment by ighack** [comment]
> 192.168.0.10 62769 - [04/Apr/2019:08:43:02 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.11 64415 - [04/Apr/2019:08:43:02 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.243 27749 - [04/Apr/2019:08:43:02 +0800] 200 0 UDP 192.168.0.238 19995 
> 192.168.0.10 62769 - [04/Apr/2019:08:43:02 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.11 64415 - [04/Apr/2019:08:43:02 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.11 64415 - [04/Apr/2019:08:43:02 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.10 62769 - [04/Apr/2019:08:43:02 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.240 3803 - [04/Apr/2019:08:43:02 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.240 3803 - [04/Apr/2019:08:43:02 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.243 24589 - [04/Apr/2019:08:43:02 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.243 24589 - [04/Apr/2019:08:43:02 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.10 62769 - [04/Apr/2019:08:43:02 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.11 64415 - [04/Apr/2019:08:43:03 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.11 64415 - [04/Apr/2019:08:43:03 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.11 64415 - [04/Apr/2019:08:43:03 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.11 64415 - [04/Apr/2019:08:43:03 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.11 64415 - [04/Apr/2019:08:43:03 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.11 64415 - [04/Apr/2019:08:43:03 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.10 62769 - [04/Apr/2019:08:43:03 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.241 25129 - [04/Apr/2019:08:43:03 +0800] 200 0 UDP 192.168.0.238 19995 
> 192.168.0.11 64415 - [04/Apr/2019:08:43:03 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.10 62769 - [04/Apr/2019:08:43:03 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.231 63545 - [04/Apr/2019:08:43:03 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.231 63545 - [04/Apr/2019:08:43:03 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.240 42968 - [04/Apr/2019:08:43:03 +0800] 200 0 UDP 192.168.0.238 19995 
> 192.168.0.1 54875 - [04/Apr/2019:08:43:03 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.240 3803 - [04/Apr/2019:08:43:03 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.240 3803 - [04/Apr/2019:08:43:03 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.243 24589 - [04/Apr/2019:08:43:03 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.243 24589 - [04/Apr/2019:08:43:03 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.243 62289 - [04/Apr/2019:08:43:03 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.8 54003 - [04/Apr/2019:08:43:03 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.1 41885 - [04/Apr/2019:08:43:03 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.7 51775 - [04/Apr/2019:08:43:03 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.243 24589 - [04/Apr/2019:08:43:03 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.6 25737 - [04/Apr/2019:08:43:03 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.11 64415 - [04/Apr/2019:08:43:03 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.10 62769 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.244 54457 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.231 63545 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.10 62769 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.235 29763 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.235 29763 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.235 29763 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.236 64633 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.236 64633 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.236 64633 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.236 64633 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.236 64633 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.11 64415 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.238 3079 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.236 64633 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.236 64633 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.236 64633 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.236 64633 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.236 64633 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.11 64415 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.11 64415 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.235 29763 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.235 29763 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.235 29763 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.235 29763 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.235 29763 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.235 29763 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.235 29763 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.241 9620 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.251 50081 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.11 64415 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.236 64633 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.236 64633 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
> 192.168.0.236 64633 - [04/Apr/2019:08:43:04 +0800] 200 0 UDP 192.168.0.238 19996 
why do I have too many connect to 19996

19996 is my nginx listening
19996->9996

**Comment by koo-taejin** [comment]
Unfortunately, I don't know much about nginx. 
If there is a connection problem due to the pinpoint module, please send the correct data after analysis.
