### ISSUE TITLE
pinpoint + magento2 구성후 호출시 magento plugin이 별도로 필요한가요?

### ISSUE THREAD

**Issue by wasgosu** [naver/pinpoint#5427]
안녕하세요.. 
docker 로 pinpoint-php agent 구성후 magento2를 설치해서 연동 테스트를 하고 있습니다.
pinpoint 로 tomcat, php-fpm 기본 샘플로 제공된것들은 모두 정상적으로 잘 보여서.. magento2에 agent 모듈 빌드후 호출 테스트를 하고 있습니다.

magento2 자체 호출하면 200 호출 정상적으로 들어오는 상황인데, pinpoint 에서는 x-view로 호출이 확인되지 않습니다.

몇가지 테스트를 해본 결과를 아래 정리해봤습니다.

* 환경 : PHP 7.2.16, magent-2.3
* 질문
magento 연동하려면 pinpoint-plugin 을 구현해줘야지 호출되는 내용이 x-view에 출력되나요?

* 정리
1. pinpoint 에서 magento가 호출되지 않는 이유 (추론)
- pinpoint magento plugin 제공되지 않아서 발생되는 것으로 생각됨
- 기동시 php.ini -> pinpoint-agent.conf 파일에 기본제공되는 plugins 경로 지정 확인
- simulate 에서 제공되는 pinpoint-agent.conf 에 아래와 같이 nginx root 경로를 참고하라고 명시되있음
[PHP]
PluginEntryFile=plugins_create.php
(기본 설정) PluginRootDir=/root/pinpoint/pinpoint-c-agent/quickstart/php/web/plugins
(nginx root 설정) PluginRootDir={{nginx_root_path}}/plugins/

(변경 후 테스트)
- nginx root path /cjo/docs/vertical/pub 설정해도 제공되는 plugin이 없어서 동일하게 에러 발생
- magento plugin 생성이 필요한가요..??

**Comment by emeroad** [comment]
https://github.com/naver/pinpoint-c-agent
여기로 문의하시기 바랍니다.

**Comment by RoySRose** [comment]
@wasgosu 

And also I think you should post the issue in English. 
When posting to https://github.com/naver/pinpoint-c-agent
since they aren't gonna understand Korean.
