### ISSUE TITLE
pinpoint alarm getting agentid along with applicationid

### ISSUE THREAD

**Issue by rajendradodda** [naver/pinpoint#5431]
Hi Team,

Our requirement is to create an application alarm like ERROR COUNT increases threshold it should send email.

In the alarm email we want to send the exact agent id which crossed the  ERROR COUNT threshold.Now we can only get the application name only and not getting the exact agent Id to send in the email.

Please suggest a way to get agentid and its ip.

**Comment by minwoo-jung** [comment]
Unfortunately, count is stored using applicationId as key. 
So we can not extract agentId.

I think there is only way you can develop it yourself.
