### ISSUE TITLE
Is 1.8.3  a stable version?  

### ISSUE THREAD

**Issue by luolenny** [naver/pinpoint#5450]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

**Comment by koo-taejin** [comment]
yes 1.8.3 is stable version. :)
