### ISSUE TITLE
Not able to install pinpoint as no way to install java 9

### ISSUE THREAD

**Issue by karthikeayan** [naver/pinpoint#5452]
- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

I am trying to install pinpoint by following the quickstart guide.

When I run mvnw, getting this error,
`Environment variable "JAVA_9_HOME" is required for this build`

I am not able install Java 9 as support has ended for Java 9 and Oracle removed the download page for Java 9.

**Comment by emeroad** [comment]
https://www.oracle.com/technetwork/java/javase/archive-139210.html
Use the java archive page
