### ISSUE TITLE
dockerfile env agentId

### ISSUE THREAD

**Issue by guogyh** [naver/pinpoint#5453]
FROM ip:10080/sfcs/java-v3:latest

ADD target/*.jar app.jar

ENV PROFILE=idc

EXPOSE 10077

ENTRYPOINT ["java","-javaagent:/agent/pinpoint-bootstrap-1.6.1.jar","-Dpinpoint.agentId=${PROFILE}","-Dpinpoint.applicationName=gateway","-Dspring.profiles.active=${PROFILE}","-jar","/app.jar"]

this is my dockerfile, when i run this docker. Dspring.profiles.active=${PROFILE}" is Dspring.profiles.active=idc, but Dpinpoint.agentId=${PROFILE}", also Dpinpoint.agentId=${PROFILE}, how to slove it?  thanks a lot.

**Comment by RoySRose** [comment]
Hello, @guogyh

This issue is about using docker image. I think you should take this to the docker team.
For any examples that you can refer to our at our [docker repository](https://github.com/naver/pinpoint-docker)
