### ISSUE TITLE
pinpoint agent log with transaction id ans spanid

### ISSUE THREAD

**Issue by rajendradodda** [naver/pinpoint#5480]
I have implemented the Per-request logging to sample spring boot application using the link http://naver.github.io/pinpoint/perrequestfeatureguide.html#per-request-logging
 and I can able to get the transactionId and spanid in the application logs.But could not get any logs related to application in agent and no transactionId or spanid coming in agent logs.

Inorder to expose the logs to web, it is mentioned that you should implement the logic to retrieve your agent’s logs. But I don't see any logs w.r.t the application.

Please help configuring  the logs of application along with transactionId and span id in agent.

**Comment by minwoo-jung** [comment]
Hi @rajendradodda 

You should use per-request-logging function for all application. you should configure for all agent.

**Comment by rajendradodda** [comment]
We have configured the per-request-logging in one of the agent with the below settings :

pinpoint.proeprties : 
profiler.log4j.logging.transactioninfo=true

log4j.xml : 
Changed conversion pattern to below : 
<param name = "ConversionPattern" value= "%d{yyyy-MM-dd HH:mm:ss} [%-5p](%-35.35cc{1.}) [TxId : %X{PtxId} , SpanId : %X{PspanId}] %m%n" />

But Iam not getting the Txid ans spanId in the agent logs.
Sample agent log below : 
2019-04-03 20:06:27 [INFO ](int-TcpDataSender(Default)-Executorc) [TxId :  , SpanId : ] Pinpoint-TcpDataSender(Default)-Executor(14-0) stopped.
2019-04-03 20:06:27 [INFO ](.n.p.r.c.PinpointClientHandlerStatec) [TxId :  , SpanId : ] DefaultPinpointClientHandler@5b40ceb stateTo() completed. Socket state change success(updateWanted:BEING_CLOSE_BY_CLIENT ,before:RUN_DUPLEX ,current:BEING_CLOSE_BY_CLIENT).
2019-04-03 20:06:27 [INFO ](.p.r.c.DefaultPinpointClientHandlerc) [TxId :  , SpanId : ] DefaultPinpointClientHandler@5b40ceb channelClosed() started.
2019-04-03 20:06:27 [INFO ](.n.p.r.c.PinpointClientHandlerStatec) [TxId :  , SpanId : ] DefaultPinpointClientHandler@5b40ceb stateTo() completed. Socket state change success(updateWanted:CLOSED_BY_CLIENT ,before:BEING_CLOSE_BY_CLIENT ,current:CLOSED_BY_CLIENT).
2019-04-03 20:06:27 [INFO ](c.n.p.r.c.PinpointClientHandshaker c) [TxId :  , SpanId : ] PinpointClientHandshaker@618c5d94 handshakeAbort() started.
2019-04-03 20:06:27 [INFO ](c.n.p.r.c.PinpointClientHandshaker c) [TxId :  , SpanId : ] PinpointClientHandshaker@618c5d94 unexpected state
2019-04-03 20:06:27 [INFO ](c.n.p.p.r.CommandDispatcher        c) [TxId :  , SpanId : ] close() started
2019-04-03 20:06:27 [INFO ](c.n.p.p.r.CommandDispatcher        c) [TxId :  , SpanId : ] close() completed

But in the application logs its printing the TxId and Span Id.

INFO    2019-04-09 23:08:27,779 33716   com.example.log4j2demo.Log4j2DemoApplication    [http-nio-9085-exec-1]   [TxId : testagent^1554876468094^1 , SpanId : -6721829400363332471] employeesList:::[Employee [id=1, firstName=lokesh, lastName=gupta, email=howtodoinjava@gmail.com]]

Please help me getting the TxId ans SpanId in the agent logs as we are getting in the application logs.

**Comment by minwoo-jung** [comment]
TxId ans SpanId can not be output in agent logs. Because the agent log is not related to the application's thread. 
The contents of the agent log show the internal operation of the pinpoint.

**Comment by rajendradodda** [comment]
Thanks for the quick reply.

So what is the significance log button web-UI ?? We need to display the application logs only in WebUI if we enable logging using the below properties and writing controller endpoint which retrive logs for that particular traceid and spanid ?

log.enable= true
log.page.url=XXXX.pinpoint
log.button.name= log

**Comment by minwoo-jung** [comment]
Yes, That's all.
The significance log button is exposed with the following image.

![logButton](https://user-images.githubusercontent.com/4557258/56103767-6579cb00-5f6f-11e9-9590-c1f50e64a537.jpg)

**Comment by rajendradodda** [comment]
Hi 

I have used done the configuration like below pointing to my local endpoint as log page url:
log.enable= true
log.page.url=XXXX.pinpoint
log.button.name= log
 but nothing displayed as shown.Any additional configuration needed ? What the log button expecting from the endpoint in terms of data ? Which data format it is expecting ?

Can you please help here to populate the data on clicking the log button.

**Comment by minwoo-jung** [comment]
please ref [3. expose log in Pinpoint web](http://naver.github.io/pinpoint/perrequestfeatureguide.html#3-expose-log-in-pinpoint-web).

step 1 You should implement a controller that receives transactionId, spanId, transaction_start_time as parameters and retrieve the logs yourself. We do not yet provide a way to retrieve the logs.

**Comment by ighack** [comment]
> We have configured the per-request-logging in one of the agent with the below settings :
> 
> pinpoint.proeprties :
> profiler.log4j.logging.transactioninfo=true
> 
> log4j.xml :
> Changed conversion pattern to below :
> 
> But Iam not getting the Txid ans spanId in the agent logs.
> Sample agent log below :
> 2019-04-03 20:06:27 [INFO ](int-TcpDataSender(Default)-Executorc) [TxId : , SpanId : ] Pinpoint-TcpDataSender(Default)-Executor(14-0) stopped.
> 2019-04-03 20:06:27 [INFO ](.n.p.r.c.PinpointClientHandlerStatec) [TxId : , SpanId : ] DefaultPinpointClientHandler@5b40ceb stateTo() completed. Socket state change success(updateWanted:BEING_CLOSE_BY_CLIENT ,before:RUN_DUPLEX ,current:BEING_CLOSE_BY_CLIENT).
> 2019-04-03 20:06:27 [INFO ](.p.r.c.DefaultPinpointClientHandlerc) [TxId : , SpanId : ] DefaultPinpointClientHandler@5b40ceb channelClosed() started.
> 2019-04-03 20:06:27 [INFO ](.n.p.r.c.PinpointClientHandlerStatec) [TxId : , SpanId : ] DefaultPinpointClientHandler@5b40ceb stateTo() completed. Socket state change success(updateWanted:CLOSED_BY_CLIENT ,before:BEING_CLOSE_BY_CLIENT ,current:CLOSED_BY_CLIENT).
> 2019-04-03 20:06:27 [INFO ](c.n.p.r.c.PinpointClientHandshaker c) [TxId : , SpanId : ] PinpointClientHandshaker@618c5d94 handshakeAbort() started.
> 2019-04-03 20:06:27 [INFO ](c.n.p.r.c.PinpointClientHandshaker c) [TxId : , SpanId : ] PinpointClientHandshaker@618c5d94 unexpected state
> 2019-04-03 20:06:27 [INFO ](c.n.p.p.r.CommandDispatcher c) [TxId : , SpanId : ] close() started
> 2019-04-03 20:06:27 [INFO ](c.n.p.p.r.CommandDispatcher c) [TxId : , SpanId : ] close() completed
> 
> But in the application logs its printing the TxId and Span Id.
> 
> INFO 2019-04-09 23:08:27,779 33716 com.example.log4j2demo.Log4j2DemoApplication [http-nio-9085-exec-1] [TxId : testagent^1554876468094^1 , SpanId : -6721829400363332471] employeesList:::[Employee [id=1, firstName=lokesh, lastName=gupta, email=[howtodoinjava@gmail.com](mailto:howtodoinjava@gmail.com)]]
> 
> Please help me getting the TxId ans SpanId in the agent logs as we are getting in the application logs.

I have the same issues
