### ISSUE TITLE
The logPageUrl can not be opened by browser because the special character[^] in transactionId

### ISSUE THREAD

**Issue by DaigangLi** [naver/pinpoint#5488]
We know the transactionId contains a special character[^], when we want expose log in pinpoint web there is an issue has been happened. 

when I clicked this Logs button, the url [http://localhost:8080/trace/simple/firstPage?transactionId=simple-test-b^1555050672824^1&time=1555050690954] cannot 
be opened by browser.

![image](https://user-images.githubusercontent.com/44084843/56025427-ad68da00-5d44-11e9-8461-4dd352a04cbf.png)

so, we need encode this url before open a new window. 
alter the file that is named [transaction-detail.controller.js] and modify [viewLog] method to add encodeURI(url) like this:

`
if ( $scope.loggingTransactionInfo === false ) {
	        		$("#customLogPopup").find("h4").html("Notice").end().find("div.modal-body").html( $scope.logDisableMessage ).end().modal("show");
	        		return false;
	        	} else {
	        		window.open(encodeURI(url));
	        	}
`

**Comment by denzelsN** [comment]
@DaigangLi  
Thank you :)
I updated the code.
