### ISSUE TITLE
should we support log4j2?  we know log4j2 plug source has been committed but not be merged.

### ISSUE THREAD

**Issue by DaigangLi** [naver/pinpoint#5489]

**Comment by RoySRose** [comment]
Hello, @DaigangLi 

What do you mean by, "should you support log4j2?"
are you asking if you can contribute "log4j2 plug in?"

**Comment by DaigangLi** [comment]
hello,@RoySRose 
I'm so sorry that my expression is ambiguous. It means there have a pull[https://github.com/naver/pinpoint/pull/5405] for support log4j2 as a plugin.
Can you join this support？

**Comment by RoySRose** [comment]
Yes, @DaigangLi 

There currently is a PR, which is ongoing and @minwoo-jung is following up on this.
But unclear whether it's proceeding smoothly.

Do you have any proposal that can help or speed-up the PR?

**Comment by licoco** [comment]
@RoySRose Current problems

In the first log printing of multiple logs in a thread, the Transactionid is empty or the Transactionid of the last request of the same thread number is obtained. The second and subsequent logs are normal.

I haven't found the reason yet, maybe it's related to log4j2's MDC optimization or the code I wrote needs to be improved.

**Comment by licoco** [comment]
This problem has been bothering me for several days. I haven't located the cause yet. At present, plug-ins are blocked here.

**Comment by licoco** [comment]
@DaigangLi  You can also work with me to solve the above problem?

**Comment by minwoo-jung** [comment]
@licoco
did you debug it for your plug-in?
I think If you did not dubug it you could never solve this problems.
Why do I think this is not true of the sentence you say `The second and subsequent logs are normal.`.

The second and subsequent logs are normal.
> all output transactionId and spanId is not correct in log.

How do you analyze the problem?

**Comment by licoco** [comment]
@minwoo-jung  pinpoint log4j2 plugin  how to debug?   I debugged the sample project

**Comment by minwoo-jung** [comment]
Because you have source code for pinpoint-project, you should just specify a breakpoint at source code then the process stops.
For more information, see the intellij documentation.

**Comment by licoco** [comment]
@minwoo-jung 
I debugged the log4j2 plug-in and the log4j2 source code, and it was too late to enhance the code when Log4jLogEvent was created.

Log4j 2.11.2 source code

Log4jLogEvent.java
` 
private static StringMap createContextData(final List<Property> properties) {
        final StringMap reusable = ContextDataFactory.createContextData();
        return CONTEXT_DATA_INJECTOR.injectContextData(properties, reusable);
    }`



Log4jLogEvent method enhancement time is a little late, my understanding

**Comment by minwoo-jung** [comment]
@licoco

I think You seem to have found the cause of the problem.

But I don't understand what this sentence means.
> my understanding
If the enhanced ThreadContext is not found to have any other problems except a slight performance degradation, it will work properly. 
**it will work properly ?!**

**Comment by licoco** [comment]
@minwoo-jung  Log4jLogEvent intercepts too late. You can see how to create LogEvent code

I'm testing that ThreadConext works properly, and the performance degradation may need to be evaluated by your side. ThreadConext is a problem before the interception does not exist at the entrance.

**Comment by licoco** [comment]
@minwoo-jung  If you use ThreadContext, I'll submit the next code later.

**Comment by minwoo-jung** [comment]
@licoco
[I edited my comment,](https://github.com/naver/pinpoint/issues/5489#issuecomment-484385206) Please read it again.

Good luck~

**Comment by licoco** [comment]
@minwoo-jung 
 Log4j 2.7+  ContextData Injector and tell Log4j to use the injector instead of the default one by specifying a ContextData Injector Factory

2.1-2.6 does not support this implementation

But I don't think that's good enough to affect the end-user custom extension.

**Comment by licoco** [comment]
I haven't found a good way to modify the internal variable ContextData so far.

**Comment by minwoo-jung** [comment]
Hi @licoco
Did you do any further analysis after that?

@DaigangLi
If licoco says could not do it, can you proceed with the plugin development? I will help you.

**Comment by licoco** [comment]
> Hi @licoco
> Did you do any further analysis after that?
> 
> @DaigangLi
> If licoco says could not do it, can you proceed with the plugin development? I will help you.

Now using the org. apache. logging. log4j. ThreadContext implementation, no problems have been found. Has been used in some projects

**Comment by licoco** [comment]
No better implementation was found.

**Comment by yjqg6666** [comment]
@licoco how about injection into sub-classes of  org.apache.logging.log4j.core.impl.ThreadContextDataInjector.

**Comment by minwoo-jung** [comment]
Clean up the issue at # 5971.
