### ISSUE TITLE
Pinpoint for PCF Deployed spring-boot applications 

### ISSUE THREAD

**Issue by ManjunathSwamy** [naver/pinpoint#5497]

**Comment by ManjunathSwamy** [comment]
Does pinpoint support PCF deployed spring-boot applications? 

We are looking at adding pinpoint agent files on to PCF container using pre-runtime hook and setting JAVA_OPTS in pre-run. But this doesn't seem to be consistent, looking at the number of microservices. 

Can you please help us ?

**Comment by RoySRose** [comment]
Hello, @ManjunathSwamy 

PCF means Pivotal Cloud Foundry?
I'm sorry but we don't know much about PCF.

I know that Pinpoint is on various clouds and working quite well.
So I know it's possible. But, hard to advise you anything on PCF.
