### ISSUE TITLE
a question about weblogic

### ISSUE THREAD

**Issue by dushiyi** [naver/pinpoint#5499]
I modified my application's startWebLogic.sh by following the instructions at https://github.com/naver/pinpoint/tree/master/plugins/weblogic:
SAVE_JAVA_OPTIONS="${JAVA_OPTIONS} -javaagent:/u02/pinpoint/pinpoint-agent/pinpoint-bootstrap-1.8.0.jar -Dpinpoint.applicationName=Unified -Dpinpoint.agentId=Unified"

There was no exception after the application started, but the application was not found in pinpoint-web.
Please help me, thank you

**Comment by Xylus** [comment]
Hi @dushiyi
Please use the [troubleshooting template](https://github.com/naver/pinpoint/issues/new?template=troubleshooting.md) and fill out as much detail as possible.
There isn't enough information (such as logs) for us to work with to figure out what the issue is.

To start, please check the agent log to see if the agent started up well.

**Comment by dushiyi** [comment]
@Xylus 
The reason was found, the name of my application exceeded 24. The application could be displayed on pinpoint-web, but the data could not be displayed: (Success: 0, Failed: 0), I modified pinpoint.config:
Profiler.weblogic.enable=true or
Profiler.applicationservertype=WEBLOGIC, and profiler.tomcat.conditional.transform=false, everything is ok now. Please improve README.md about weblogic to help others, thank you again for your help.

**Comment by Xylus** [comment]
Hi @dushiyi 
Thanks for the update.
Yeh, we do have a limit on application name length (and agent id) so the agent will not start if either of these exceeds 24 characters.

`profiler.tomcat.conditional.transform` option shouldn't have anything to do with tracing weblogic. `profiler.applicationservertype=WEBLOGIC` also shouldn't affect weblogic traces, it merely sets the node type to *WEBLOGIC* if it isn't automatically detected.

Setting `profiler.weblogic.enable` to *false* will stop weblogic from being traced so yes, this should be set to *true* (which is the default).

**Comment by dushiyi** [comment]
@Xylus 
I modified pinpoint.config as per your suggestion and it is correct.thanks
