### ISSUE TITLE
CallTree Argument display problem

### ISSUE THREAD

**Issue by waterystone** [naver/pinpoint#5502]
![image](https://user-images.githubusercontent.com/7723467/56335098-bf77cc00-61cd-11e9-878b-c65daa01d850.png)

https://github.com/naver/pinpoint/blob/master/web/src/main/webapp/features/distributedCallFlow/distributed-call-flow.directive.js

![image](https://user-images.githubusercontent.com/7723467/56335147-f0580100-61cd-11e9-8855-82e048674b15.png)

"$gt" --> "&gt"

**Comment by denzelsN** [comment]
@waterystone 
thank you :)
