### ISSUE TITLE
Is there any way to pass AsyncContext by JSONObject ?

### ISSUE THREAD

**Issue by coderztf** [naver/pinpoint#5529]
I want to trace asynchronous tasks by my plugin . I noticed the _12_Asynchronous_Trace example and tried to make a plugin seems like the example plugin . I found that handler should obtain AsyncContext to relate to continuing traces . My problem is that I don't know how to pass AsyncContext by JSONObject ? Shared object for me is a JSONObject for me . 
I tried to convert AsyncContext to JSONObject directly by JSONObject utils , failed . 
Is there other way to convert AsyncContext to JSONObject or can I make a asyncContext manually in the handler thread with serveral necessary field?

this is part of my caller interceptor 

```
        try {
            Object eventWrapper = arg0;
            Field eventBodyField = eventWrapper.getClass().getDeclaredField("eventBody");
            eventBodyField.setAccessible(true);

            // 'eventBody' is the shared object between caller and handler
            String eventBody = (String) eventBodyField.get(eventWrapper);
            JSONObject jsonObject = JSON.parseObject(eventBody);

            // try to convert asyncContext to JSONObject
            jsonObject.put("asyncContext", JSONObject.parseObject(JSON.toJSONString(asyncContext)));

            eventBodyField.set(eventWrapper, jsonObject.toJSONString());
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }
```

this is part of my handler interceptor
```
        JSONObject event=JSON.parseObject(args[0].toString());
        JSONObject asyncContextJSON=event.getJSONObject("asyncContext");
        AsyncContext asyncContext= asyncContextJSON.toJavaObject(AsyncContext.class);
        return asyncContext;
```
In caller interceptor , `JSONObject.parseObject(JSON.toJSONString(asyncContext)));` executed failed due to recursive fields converted

I'm looking forward to your reply ! thx

**Comment by Xylus** [comment]
Hi @coderztf 
I don't think you can serialize **AsyncContext** into a string.
How is you handler getting invoked? Does the method signature only have a **String** as it's argument?
