### ISSUE TITLE
application calltree not display anything about sql and database.

### ISSUE THREAD

**Issue by a52yth** [naver/pinpoint#5530]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
master/v1.7.3/v1.7.3 etc.

#### Describe your problem**
only one application not display anything about sql and database.

#### What have you done?
Steps you have taken to trigger the problem, for example:
1. try to truncate_preserve the hbase and rebuild the application data,

**Comment by a52yth** [comment]
calltree only display 
queryForObject(String statementName, Object parameterObject)
 prepareStatement(String String)  but not have sql info

**Comment by Xylus** [comment]
Hi @a52yth 
Does it show *SQL-ID not found sqlId: xxx*?
If you truncated metadata tables (such as **SqlMetaData_Ver2**), then this can happen.
Please check out http://naver.github.io/pinpoint/faq.html#hbase-is-taking-up-too-much-space-which-data-should-i-delete-first for more info.

Let me know if this isn't related to your issue.

**Comment by a52yth** [comment]
Thank you for your attention.@Xylus
truncated hbase action after i cant't see sqlinfo .
right pic:http://i2.bvimg.com/685900/a8d8f5dd99beb98c.jpg
              http://i2.bvimg.com/685900/a8d8f5dd99beb98c.jpg

wrong pic: http://i2.bvimg.com/685900/827ea9585cf2e614.jpg
                 http://i2.bvimg.com/685900/7624cd6bccfbf543.jpg
Thanks again！

**Comment by Xylus** [comment]
@a52yth 
Has anything else changed apart from truncating hbase? Such as upgrading pinpoint agent, changing oracle jdbc driver version etc.
I ask because the issue doesn't seem to be related to hbase truncate (though I could be wrong).
