### ISSUE TITLE
Why the same trace showed in home page is different to server map ？

### ISSUE THREAD

**Issue by coderztf** [naver/pinpoint#5533]
#### Description
The same trace showed in home page is different to server map .
call trace is :
user -> app1 ->(with my cutomer plugin) app2

in the home page is this :
user -> app1

in the server map is this :
app1 -> app2

and the call tree is correctly showed

#### Environment

* Pinpoint version:1.8.2
* Additional details (e.g. how your collector/web is set up):my customer plugin is developed like dubbo plugin

#### Additional Info

there are the logs when I requested home page:
#### Description
The same trace showed in home page is different to server map .
call trace is :
user -> app1 ->(with my cutomer plugin) app2

in the home page is this :
user -> app1

in the server map is this :
app1 -> app2

and the call tree is correctly showed

#### Environment

* Pinpoint version:1.8.2
* Additional details (e.g. how your collector/web is set up):my customer plugin is developed like dubbo plugin

#### Additional Info

there are the logs when I requested home page:

> 2019-04-28 19:38:25 [INFO ](c.n.p.w.c.MapController            ) getServerMap() application:fake-1(SPRING_BOOT:1210) range:Range{from=1556450305000, to=1556451505000, range=1200000} searchOption:SearchOption{callerSearchDepth=4, calleeSearchDepth=4, linkSelectorType=UNIDIRECTIONAL, wasOnly=false}
> 2019-04-28 19:38:25 [DEBUG](c.n.p.w.s.MapServiceImpl           ) SelectApplicationMap
> 2019-04-28 19:38:25 [DEBUG](.p.w.s.m.UnidirectionalLinkSelector) Creating link data map for [fake-1(SPRING_BOOT:1210)]
> 2019-04-28 19:38:25 [INFO ](.p.w.s.m.UnidirectionalLinkSelector) outbound depth search start. callerDepth:0, calleeDepth:0, size:1, nodes:[fake-1(SPRING_BOOT:1210)]
> 2019-04-28 19:38:25 [DEBUG](.w.s.m.DefaultApplicationMapCreator) Finding Caller/Callee link data for fake-1(SPRING_BOOT:1210)
> 2019-04-28 19:38:25 [DEBUG](.w.s.m.DefaultApplicationMapCreator) Finding Caller link data for fake-1(SPRING_BOOT:1210)
> 2019-04-28 19:38:25 [DEBUG](.w.s.m.DefaultApplicationMapCreator) Found Caller. count=0, caller=fake-1(SPRING_BOOT:1210), depth=0
> 2019-04-28 19:38:25 [DEBUG](c.n.p.w.s.m.LinkSelectContext      ) callee depth overflow application:fake-1(SPRING_BOOT:1210) depth:0
> 2019-04-28 19:38:25 [DEBUG](w.s.m.DefaultApplicationsMapCreator) depth search. callerDepth : 0, calleeDepth : 0
> 2019-04-28 19:38:25 [INFO ](.p.w.s.m.UnidirectionalLinkSelector) outbound depth search end. callerDepth:0, calleeDepth:0
> 2019-04-28 19:38:25 [INFO ](.p.w.s.m.UnidirectionalLinkSelector) inbound depth search start. callerDepth:0, calleeDepth:0, size:1, nodes:[fake-1(SPRING_BOOT:1210)]
> 2019-04-28 19:38:25 [DEBUG](.w.s.m.DefaultApplicationMapCreator) Finding Caller/Callee link data for fake-1(SPRING_BOOT:1210)
> 2019-04-28 19:38:25 [DEBUG](c.n.p.w.s.m.LinkSelectContext      ) caller depth overflow application:fake-1(SPRING_BOOT:1210) depth:0
> 2019-04-28 19:38:25 [DEBUG](.w.s.m.DefaultApplicationMapCreator) Finding Callee link data for fake-1(SPRING_BOOT:1210)
> 2019-04-28 19:38:26 [DEBUG](.w.s.m.DefaultApplicationMapCreator) Found Callee. count=1, callee=fake-1(SPRING_BOOT:1210), depth=0
> 2019-04-28 19:38:26 [DEBUG](w.s.m.DefaultApplicationsMapCreator) depth search. callerDepth : 0, calleeDepth : 0
> 2019-04-28 19:38:26 [INFO ](.p.w.s.m.UnidirectionalLinkSelector) inbound depth search end. callerDepth:0, calleeDepth:0
> 2019-04-28 19:38:26 [INFO ](.p.w.s.m.UnidirectionalLinkSelector) outbound depth search start. callerDepth:1, calleeDepth:1, size:0, nodes:[]
> 2019-04-28 19:38:26 [INFO ](.p.w.s.m.UnidirectionalLinkSelector) outbound depth search end. callerDepth:1, calleeDepth:1
> 2019-04-28 19:38:26 [INFO ](.p.w.s.m.UnidirectionalLinkSelector) inbound depth search start. callerDepth:1, calleeDepth:1, size:1, nodes:[fake-1_SPRING_BOOT(USER:2)]
> 2019-04-28 19:38:26 [DEBUG](.w.s.m.DefaultApplicationMapCreator) Finding Caller/Callee link data for fake-1_SPRING_BOOT(USER:2)
> 2019-04-28 19:38:26 [DEBUG](c.n.p.w.s.m.LinkSelectContext      ) caller depth overflow application:fake-1_SPRING_BOOT(USER:2) depth:1
> 2019-04-28 19:38:26 [DEBUG](.w.s.m.DefaultApplicationMapCreator) Finding Callee link data for fake-1_SPRING_BOOT(USER:2)
> 2019-04-28 19:38:26 [DEBUG](.w.s.m.DefaultApplicationMapCreator) Found Callee. count=0, callee=fake-1_SPRING_BOOT(USER:2), depth=1
> 2019-04-28 19:38:26 [DEBUG](w.s.m.DefaultApplicationsMapCreator) depth search. callerDepth : 1, calleeDepth : 1
> 2019-04-28 19:38:26 [INFO ](.p.w.s.m.UnidirectionalLinkSelector) inbound depth search end. callerDepth:1, calleeDepth:1
> 2019-04-28 19:38:26 [INFO ](c.n.p.w.a.ApplicationMapBuilder    ) Building application map
> 2019-04-28 19:38:26 [INFO ](c.n.p.w.s.MapServiceImpl           ) ApplicationMap BuildTime: StopWatch 'ApplicationMap': running time (millis) = 988
> -----------------------------------------
> ms     %     Task name
> -----------------------------------------
> 00722  073%  ApplicationMap Hbase Io Fetch(Caller,Callee) Time
> 00266  027%  ApplicationMap MapBuilding(Response) Time
> 
> 2019-04-28 19:38:26 [INFO ](c.n.p.w.c.ScatterChartController   ) Fetch scatterData time : 226ms
>

**Comment by Xylus** [comment]
Hi @coderztf 
I don't understand what you mean by "home page"? Is this the server map displayed in the main page where you select your application?
Is the "server map" you mention the server map from the call stack view when you select a transaction?
Providing some screenshots would help out in understanding your issue.

Also, how is app1 calling app2?
Is app2 generating a span via your customer plugin? If so, how is the **ServiceType** defined here?
More details would be great. Thanks.

**Comment by coderztf** [comment]
thanks for reply .
u are right , the "home page" and "server map" means u said .
the screenshots pics as for "home page"
![image](https://user-images.githubusercontent.com/35209667/56880756-92120480-6a90-11e9-9a12-059c6319bf47.png)

the screenshots pics as for "server page"
![image](https://user-images.githubusercontent.com/35209667/56880765-9c340300-6a90-11e9-9d68-fa5c6b67b569.png)

the ServerType for app1
`ServiceTypeFactory.of(9915, "IFC_EVENT_PUBLISHER",RECORD_STATISTICS);`
and the ServerType for app2
`ServiceTypeFactory.of(1915, "IFC_EVENT_SUBSCRIBER",RECORD_STATISTICS);`

As for how is app1 calling app2 , it depends on the database and kafka , app1 stored data into database . Then there is task to push data in the database to kafka . App2 pulls data from kafka.
So , I want to make this process looks like a simple rpc calling by my customer plugin .  I add TransactionId , SpanId , ParentSpanId , ParentApplicationName , ParentApplicationType and Flags into the data which app1 sends to app2 . App2 generates TraceId according to that data .

**Comment by Xylus** [comment]
Thanks for the details.
The server map in the main page drawn based on caller/callee statistics and not individual span/span events (due to performance) so they might look different.
You might be able to emulate this by doing the following:
1. In the publisher's interceptor, invoke `SpanEventRecorder.setEndPoint(...)` with app2's address, then add this value to the data which app1 sends to app2.
2. In the subscriber's interceptor, read this value from the data that got sent to app2, and invoke `SpanEventRecorder.recordAcceptorHost(...)`.

Let me know of the result once you try this out.

**Comment by coderztf** [comment]
I'm sorry , it didn't work . 
I found `SpanEventRecorder.recordEndPoint(String endPoint)` but not `SpanEventRecorder.setEndPoint(...)` and invoked "recordEndPoint" in the publisher's interceptor .
Then invoked `SpanEventRecorder.recordAcceptorHost` in the subscriber's interceptor . Especially , I made the values of "recordEndPoint" and "recordAcceptorHost" are equal .

**Comment by Xylus** [comment]
Eck, my bad.
You're right, it's `SpanEventRecorder.recordEndPoint(...)` on the publisher's interceptor.
Also, in the subscriber's interceptor (where it creates the **Span**), it should be `SpanRecorder.recordAcceptorHost(...)`, which I'm guessing is what you've called?

Either way, I'm sorry it didn't work out. It's not a very normal use case.
Do you think you can debug your collector and web?
The relevant code should be `TraceService.insertAcceptorHost(SpanBo)` in the collector, and `RpcCallProcessor.replaceLinkData(LinkData, Range)` in the web (more specifically, check what goes on in it's `findAcceptApplications(...)` method).
Taking a look at what's getting stored and read would be helpful.

**Comment by coderztf** [comment]
hi ,@Xylus 
thx for you reply , I have debugged the collector and web according by your advise . 

the value of  relation item in the SpanBo'SpanEventList at method `com.navercorp.pinpoint.collector.service.TraceService#insertSpan`  sended by app1 is

> {version=0, sequence=4, startElapsed=4, endElapsed=223, serviceType=9915, destinationId=null, **endPoint=99.12.92.33**, apiId=-17, annotationBoList=[], depth=5, nextSpanId=-1507170764864238472, hasException=false, exceptionId=0, exceptionMessage=null, exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}

and the value of  relation item in the SpanBo'SpanEventList at method `com.navercorp.pinpoint.collector.service.TraceService#insertSpan`  sended by app2 is

> {version=0, sequence=0, startElapsed=12, endElapsed=3964, serviceType=1915, destinationId=null, **endPoint=null**, apiId=-11, annotationBoList=[], depth=1, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage=null, exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}

**"99.12.92.33" is app2's ip address**

why the endpoint of SpanEvent is different between spanBos ?

the value of SpanBo in app2 is

> SpanBo{version=0, agentId='0.22', applicationId='fake-2', agentStartTime=1556590652471, transactionId=TransactionId{agentId='0.2', agentStartTime=1556586404254, transactionSequence=5}, spanId=-1507170764864238472, parentSpanId=-4528326874535478931, parentApplicationId='fake-1', parentApplicationServiceType=1210, startTime=1556590678363, elapsed=3976, rpc='null', serviceType=1915, **endPoint='null'**, apiId=-11, annotationBoList=[], flag=0, errCode=1, spanEventBoList=[{version=0, sequence=0, startElapsed=12, endElapsed=3964, serviceType=1915, destinationId=null, endPoint=null, apiId=-11, annotationBoList=[], depth=1, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage=null, exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}, {version=0, sequence=1, startElapsed=17, endElapsed=3959, serviceType=5071, destinationId=null, endPoint=null, apiId=11, annotationBoList=[], depth=2, nextSpanId=-1, hasException=true, exceptionId=1, exceptionMessage=
> ### Error updating database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'ert' for key 'PRIMARY'
> ### The error may involve com.coderztf.apm.example.user.domain.UserInfo.insert-Inline
> ### The error oc...(714), exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}, {version=0, sequence=2, startElapsed=3022, endElapsed=131, serviceType=5071, destinationId=null, endPoint=null, apiId=-12, annotationBoList=[], depth=3, nextSpanId=-1, hasException=true, exceptionId=1, exceptionMessage=
> ### Error updating database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'ert' for key 'PRIMARY'
> ### The error may involve com.coderztf.apm.example.user.domain.UserInfo.insert-Inline
> ### The error oc...(714), exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}, {version=0, sequence=3, startElapsed=3022, endElapsed=131, serviceType=5510, destinationId=null, endPoint=null, apiId=-20, annotationBoList=[AnnotationBo{key=-30, value=-2, isAuthorized=true}], depth=4, nextSpanId=-1, hasException=true, exceptionId=1, exceptionMessage=
> ### Error updating database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'ert' for key 'PRIMARY'
> ### The error may involve com.coderztf.apm.example.user.domain.UserInfo.insert-Inline
> ### The error oc...(714), exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}, {version=0, sequence=4, startElapsed=3023, endElapsed=2, serviceType=2100, destinationId=apm-example, endPoint=99.12.92.30:3306, apiId=-30, annotationBoList=[AnnotationBo{key=20, value=TIntStringStringValue(intValue:-1), isAuthorized=true}], depth=5, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage=null, exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}, {version=0, sequence=5, startElapsed=3027, endElapsed=19, serviceType=2101, destinationId=apm-example, endPoint=99.12.92.30:3306, apiId=-26, annotationBoList=[AnnotationBo{key=20, value=TIntStringStringValue(intValue:-1, stringValue2:ert, 100), isAuthorized=true}], depth=-1, nextSpanId=-1, hasException=true, exceptionId=-1, exceptionMessage=Duplicate entry 'ert' for key 'PRIMARY', exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}], collectorAcceptTime=1556590550963, hasException=false, exceptionId=0, exceptionMessage='null', exceptionClass='null', applicationServiceType=1210, **acceptorHost='99.12.92.33', remoteAddr='99.12.92.33'**, loggingTransactionInfo=0}

please ignore the exceptionMessage in it . :)

On the other hand , I debugged the web , I found that `RpcCallProcessor.replaceLinkData(LinkData, Range)` didn't execute due to the size of `LinkDataMap` was 0 .

Is there wrong with my plugin when it sends data to collector ?
thx .

**Comment by Xylus** [comment]
Hi @coderztf 
Thanks for the follow up.
A couple of things I noticed in your data.
1. *app1*'s SpanEvent (9915) missing *destinationId*.  
  Set this to the same value as what you've set it to using `SpanEventRecorder.recordEndPoint(...)`, which would be `99.12.92.33` here. (apologize on my part for missing this out earlier)
2. *app2*'s Span (1915) missing *endPoint*, and having a wrong *remoteAddr*  .
  The span's *endPoint* should be set to the server(*app2*)'s address, and *remoteAddr* should be set to the client(*app1*)'s address.
3. *app2*'s SpanEvent (1915) would need it's own service type.  
  The span event in *app2* is using the same **ServiceType** as the span, so they both have `RECORD_STATISTICS` property. You might want to create a separate service type without this property, for example, `ServiceTypeFactory.of(1916, "IFC_EVENT_SUBSCRIBER_INTERNAL");` and use this for the span event.

Another suggestion would be to add port number for your addresses (eg `99.12.92.33:xxxx`).
Also, please take a look at [this](http://naver.github.io/pinpoint/plugindevguide.html#222-continue-transaction) and [this](http://naver.github.io/pinpoint/plugindevguide.html#23-methods-invoking-a-remote-node) part of the plugin developer guide for more details.

**Comment by coderztf** [comment]
thanks a lot ! @Xylus My plugin may be worked correctly .
I have another question that how to record parent SpanEvent info at the next Span ?
For example , I want to record some information about app1's SpanEvent at app2's interceptor . Are there some methods to help me get SpanEvent of parent span (app1) and could I flush the parent SpaneEvent data at the next span ?

**Comment by Xylus** [comment]
Well done :+1:
