### ISSUE TITLE
how to deploy pinpoint with two linux machine

### ISSUE THREAD

**Issue by bryanYao** [naver/pinpoint#5538]
i hava two linux machine, like ip 192.168.8.1 and 192.168.8.2

i deploy hbase on machine 192.168.8.1[single mode] ,pinpoint webUI and collector were deployed on machine 8.2; so i modified pinpoint webUI  configuration
hbase.properties
   hbase.client.host=192.168.8.1
pinpoint-web.properties
   cluster.zookeeper.address=192.168.8.1
I modified collector' configuration alse;

unfortunately i can't read data from hbase, until i deployed hbase on 192.168.8.2;  pinpoint workes.
so how to deploy with two machine? is there any wiki guide me ?

**Comment by koo-taejin** [comment]
hi @bryanYao 

You can use the hbase in the form you described, and I actually used that you described. 
It is recommended that you check whether there is a connection access restriction between hosts or if there is a missing setup in the collector module or web module.

thanks.
