### ISSUE TITLE
gojs in future release ?

### ISSUE THREAD

**Issue by ash2fast** [naver/pinpoint#5548]
#### Description
I can see many discussion around licence for gojs but is their any plan to get rid of gojs in future releases ? Maybe providing an options whether user wants to install with GOjs or other opensource library.

#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by RoySRose** [comment]
Hello, @ash2fast 

Yes, there is a plan for this.
It's almost implemented in [version 2](https://naver.github.io/pinpoint/ui_v2.html) of Pinpoint-Web. But no guide is open yet.

It will be open when version 2 becomes the default UI for Pinpoint.
And then, you will be able to choose other libraries.

@denzels 
Supplement above if there is anything.

**Comment by denzelsN** [comment]
Hello, @ash2fast 
In our next version of Pinpoint-Web, you can select `visjs` or `gojs`.

This selection is available from the source as follows:
https://github.com/naver/pinpoint/blob/master/web/src/main/webapp/v2/src/app/app.module.ts

You can check out the `visjs` implementation through the following guides.
https://naver.github.io/pinpoint/ui_v2.html

**Comment by ash2fast** [comment]
Thanks @RoySRose @denzelsN for the response. Will give a try to the new UI :).

**Comment by yjqg6666** [comment]
Is there any way to make UI V2 as the default one?

**Comment by RoySRose** [comment]
Eventually, V2 will be a default one. But I don't think go.js is fit for it.
Find the details here #1308
