### ISSUE TITLE
The call tree page displays abnormally in new UI.

### ISSUE THREAD

**Issue by messi-gao** [naver/pinpoint#5558]
I am trying to use new UI of Pinpoint.But the call tree page displays abnormally in new UI.Could you tell me something about it?

![image](https://user-images.githubusercontent.com/24312100/57133117-6e262a00-6dd4-11e9-8e70-5c05a02596c1.png)
![image](https://user-images.githubusercontent.com/24312100/57133139-7aaa8280-6dd4-11e9-99d7-b39be88bfb13.png)

**Comment by denzelsN** [comment]
Hi~ @messi-gao 
On the screen, it seems that the ag-grid package is not properly installed.
Could you show me the error log in the Inspector?
And were there any other errors in the build?

**Comment by messi-gao** [comment]
@denzelsN thank you,I have solved it.
