### ISSUE TITLE
Is it possible to monitor SpringCloudGateway with pinpoint?

### ISSUE THREAD

**Issue by shaohq** [naver/pinpoint#5561]
I tried to use pinpoint with spring cloud, it works fine for sprint boot apps, but with spring cloud gateway, I can find the app in pinpoint Application List, I can use Inspector to look into the jvm metrics of the spring cloud gateway, but I can't view any transaction log that are going through spring cloud gateway.

Does any one tested spring cloud gateway with pinpoint before?

Thanks!

**Comment by shaohq** [comment]
duplicate to #5267

**Comment by Roronoa-Zoro** [comment]
I found there's code in 1.9.0-snapshot for spring cloud gateway, when will pinpoint release this version?
