### ISSUE TITLE
Server map does not show completely in mixed view page of new UI.

### ISSUE THREAD

**Issue by messi-gao** [naver/pinpoint#5565]
These two images are same data that show between old UI and new UI.As you can see,in old UI,the server map can show "Air Low Fare Search" and "Air Ancillaries Bundle Availability".But in new UI,it only shows the total count but does not show the detail info.
Could you tell me how to solve this problem? Thank you very much !
![image](https://user-images.githubusercontent.com/24312100/57274236-33224000-70cd-11e9-9fbb-602c4f0a0b7d.png)
![image](https://user-images.githubusercontent.com/24312100/57274249-47fed380-70cd-11e9-8134-83ab3d10ddde.png)

**Comment by denzelsN** [comment]
HI~ @messi-gao 
You can see the ungrouped node by right-clicking on the server map and releasing the merge item.

**Comment by messi-gao** [comment]
> HI~ @messi-gao
> You can see the ungrouped node by right-clicking on the server map and releasing the merge item.

@denzelsN  Right-clicking on the server map only works in the home page,but does not work in other page.

![image](https://user-images.githubusercontent.com/24312100/57342209-5fdb6380-7170-11e9-8d08-4b9e7ddff6fe.png)
home page works.
![image](https://user-images.githubusercontent.com/24312100/57342231-75508d80-7170-11e9-8b8b-77b4e86e3738.png)
transactionList page does not work.
![image](https://user-images.githubusercontent.com/24312100/57342263-9add9700-7170-11e9-8609-f2face45ce10.png)
transactionView does not work.

**Comment by denzelsN** [comment]
@messi-gao 
I forgot about transactionList and transactionView. 
I'll fix it. 
Thank you. :)

**Comment by messi-gao** [comment]
> @messi-gao
> I forgot about transactionList and transactionView.
> I'll fix it.
> Thank you. :)

@denzelsN If you fix it,please tell me. Thank you very mush.

**Comment by denzelsN** [comment]
@messi-gao 
Fixed it.

**Comment by messi-gao** [comment]
> @messi-gao
> Fixed it.

My local code from the tag:1.8.3,I am trying to modify the three files you metion.But when complile the code,there are some complile error.Could you modify the code based on code of the tag:1.8.3?

**Comment by denzelsN** [comment]
@messi-gao 
Change follow code in `server-map-for-transaction-list-container.component.ts` and `server-map-for-transaction-view-container.component.ts`:
But the context popup will open in a strange position. 

```` javascript
// before
onContextClickBackground(coord: ICoordinate): void {
        this.dynamicPopupService.openPopup({
            data: this.mapData,
            coord,
            component: ServerMapContextPopupContainerComponent
        }, {
            resolver: this.componentFactoryResolver,
            injector: this.injector
        });
}
// after
onContextClickBackground(coord: ICoordinate): void {
        this.dynamicPopupService.openPopup({
            data: this.mapData,
            coord,
            component: ServerMapContextPopupContainerComponent
        });
}
`````

**Comment by messi-gao** [comment]
@denzelsN 
It is a pity that I can not find the code of onContextClickBackground as you metioned .The link is as below:

server-map-for-transaction-list-container.component.ts in tag:1.8.3
https://github.com/naver/pinpoint/blob/7294fb60a30b6e7a4b587068f7f03d29274f0339/web/src/main/webapp/v2/src/app/core/components/server-map/server-map-for-transaction-list-container.component.ts#L88

server-map-for-transaction-view-container.component.ts in tag:1.8.3
https://github.com/naver/pinpoint/blob/7294fb60a30b6e7a4b587068f7f03d29274f0339/web/src/main/webapp/v2/src/app/core/components/server-map/server-map-for-transaction-view-container.component.ts#L53

**Comment by denzelsN** [comment]
@messi-gao 
Use [updated code](https://github.com/naver/pinpoint/commit/313eb55b01b27f68f6f1573cd6ba6cf88c1a4203).

**Comment by messi-gao** [comment]
You may not understand my meannings,I will show the error to you.
After changing the three files,There are compile error in` server-map-for-transaction-list-container.component.ts` and `server-map-for-transaction-view-container.component.ts`.The erro code is `this.dynamicPopupService.openPopup` function,it needs only one parameter,but after you modify it,it needs two parameters.
![image](https://user-images.githubusercontent.com/24312100/57352634-8f9e6180-7198-11e9-95b3-79744b127f9c.png)
complie error

![image](https://user-images.githubusercontent.com/24312100/57352704-c4121d80-7198-11e9-8c4e-52438f513644.png)
dynamic-popup.service.ts openPopup function in tag:1.8.3.

**Comment by denzelsN** [comment]
@messi-gao 
So, I comment about it. 
> Remove second parameter ( before --> after )
https://github.com/naver/pinpoint/issues/5565#issuecomment-490344802

**Comment by messi-gao** [comment]
@denzelsN You are right.I have saw it.As you say,The context popup will open in a strange position.I hope it could open in a normal position in Pinpoint next release.Thank you!
