### ISSUE TITLE
Task com.navercorp.pinpoint.common.hbase.parallel.ScanTask@7a37ef33 rejected from java.util.concurrent.ThreadPoolExecutor

### ISSUE THREAD

**Issue by fionaliupw** [naver/pinpoint#5568]
#### What version of pinpoint are you using?
pinpoint-1.8.0

#### Describe your problem**
There is a prohibition mark on the upper right on the scatter chart，and has the following prompt error:
Error!
Task com.navercorp.pinpoint.common.hbase.parallel.ScanTask@7a37ef33 rejected from java.util.concurrent.ThreadPoolExecutor@1fe3f36c[Running, pool size = 128, active threads = 128, queued tasks = 8192, completed tasks = 265664972]
![image](https://user-images.githubusercontent.com/26397343/57287765-d0d83800-70ea-11e9-9894-92b8b1328583.png)
![image](https://user-images.githubusercontent.com/26397343/57287810-e3527180-70ea-11e9-982c-638cf019bd9c.png)

#### What have you done?
Steps you have taken to trigger the problem, for example:
1. tried tracing the collector'gc log
![image](https://user-images.githubusercontent.com/26397343/57287915-109f1f80-70eb-11e9-9294-cf42e9f3ada3.png)

#### Logs
Error!
Task com.navercorp.pinpoint.common.hbase.parallel.ScanTask@7a37ef33 rejected from java.util.concurrent.ThreadPoolExecutor@1fe3f36c[Running, pool size = 128, active threads = 128, queued tasks = 8192, completed tasks = 265664972]

**Comment by Xylus** [comment]
Hi @fionaliupw 
Looks like the work queue for parallel scan is full.
If your hbase calls are taking a bit of time, you might want to reduce `hbase.client.parallel.scan.maxthreadsperscan` in pinpoint-web's *hbase.properties*, or disable parallel scan by setting `hbase.client.parallel.scan.enable=false` in the same file.
