### ISSUE TITLE
The top nodes in [Response Time Scatter Chart] can not be seleted in new UI.

### ISSUE THREAD

**Issue by messi-gao** [naver/pinpoint#5572]
![image](https://user-images.githubusercontent.com/24312100/57345669-450feb80-717e-11e9-98d3-98d1bc3118a8.png)
The top nodes which take time more than 10000ms can not be seleted and other nodes can be selected.
@denzelsN

**Comment by denzelsN** [comment]
@messi-gao 
It is not bug. This is what I intend to do.
If you want to select a request that takes more than 10,000 ms, you can modify the value on the y-axis. 
<img width="47" alt="스크린샷 2019-05-08 오후 4 26 40" src="https://user-images.githubusercontent.com/11496446/57357537-17429b00-71ae-11e9-8313-ed5eddbcf6f7.png">

If Scatter-chart does not display a request that takes more than 10,000 ms, The user may not even know that such a request has occurred.
The reason why it is displayed in the Chart but not selected by drag is that requests that are not relevant to the user's intention may be selected if there are many requests greater than 10,000ms.

**Comment by messi-gao** [comment]
@denzelsN I understand your meaning.But in the old UI,even when the request greater than 10,000ms,it can be selected.
![image](https://user-images.githubusercontent.com/24312100/57357802-67b5fa80-71a6-11e9-9c1e-fc6ad9831706.png)

**Comment by denzelsN** [comment]
@messi-gao 
Yeah, you're right. I changed the UI and made a new logic. Do you think you're comfortable with the old ways?

**Comment by messi-gao** [comment]
@denzelsN I am e comfortable with the old ways.
As a user,he or she can select the nodes that show on the chart.If the nodes can not be selected,the system can pop up a tooltip to tell user click 
![image](https://user-images.githubusercontent.com/24312100/57358528-33dbd480-71a8-11e9-9085-30cc0aaef00a.png)

**Comment by denzelsN** [comment]
@messi-gao 
Thanks for the feedback. :)
First, I'll try to modify the method of selection to the old ways.
And I'll think about a more clear way.

**Comment by messi-gao** [comment]
@denzelsN Waiting for your good news,thank you!

**Comment by denzelsN** [comment]
@messi-gao 
I changed it to the old way.

**Comment by messi-gao** [comment]
It has some compile error after modify scatter-chart.class.ts in tag:1.8.3.
![image](https://user-images.githubusercontent.com/24312100/57440060-e29c1580-7279-11e9-890d-a66398094b72.png)

ERROR in src/app/core/components/scatter-chart/class/scatter-chart-transaction-type-manager.class.ts(1,10): error TS2305: Module '"C:/myworkspace/openjaw-pinpoint/web/src/main/webapp/v2/src/app/core/components/scatter-ch
art/class/scatter-chart.class"' has no exported member 'ITypeInfo'.
src/app/core/components/scatter-chart/class/scatter-chart.class.ts(198,102): error TS2339: Property 'getDefaultTransactionTypeInfo' does not exist on type 'typeof ScatterChartTransactionTypeManager'.
src/app/core/components/scatter-chart/class/scatter-chart.class.ts(241,26): error TS2339: Property 'reset' does not exist on type 'ScatterChartTransactionTypeManager'.
src/app/core/components/scatter-chart/scatter-chart.component.ts(5,24): error TS2305: Module '"C:/myworkspace/openjaw-pinpoint/web/src/main/webapp/v2/src/app/core/components/scatter-chart/class/scatter-chart.class"' has
no exported member 'ITypeInfo'.
src/app/core/components/scatter-chart/scatter-chart.component.ts(47,45): error TS2554: Expected 12 arguments, but got 13.

**Comment by denzelsN** [comment]
@messi-gao 
I tested it at 1.8.3. I'm fine. 
Check again.
