### ISSUE TITLE
mongodb plugin can not supprot spring-data-mongo?

### ISSUE THREAD

**Issue by zfaster** [naver/pinpoint#5578]
pinpoint version :1.8.3

jar version:
![image](https://user-images.githubusercontent.com/8341790/57371179-a3f85380-71c4-11e9-8d8c-01248f5334dd.png)
![image](https://user-images.githubusercontent.com/8341790/57371184-ac508e80-71c4-11e9-9a47-10cfe35eecf3.png)

code:

![image](https://user-images.githubusercontent.com/8341790/57371292-f76aa180-71c4-11e9-9ef3-aed59fdf870a.png)

trace:

![image](https://user-images.githubusercontent.com/8341790/57371333-0c473500-71c5-11e9-8d43-ff301cbfc11c.png)

spring-data-mongo not support??

**Comment by RoySRose** [comment]
Hello, @zfaster 

Since spring-data-mongo just wraps monogodb-driver. It is supported.
check out here https://github.com/naver/pinpoint/issues/5282#issuecomment-468183073

**Comment by zfaster** [comment]
thank you reply @RoySRose 
Are you sure? but I found it can not trace,use mongoTemplate.
I read the issue，found I have the same problem，when MongoClient it can trace but mongoTemplate is failed ， something I use wrong?

**Comment by zfaster** [comment]
@RoySRose 
I think I found the problem。
when I use spring-data-mongodb-1.10.12.RELEASE
the spring inner code:
![image](https://user-images.githubusercontent.com/8341790/57423720-b798ce00-7247-11e9-8a4a-fd72acfecd60.png)

but spring-data-mongodb-2.0.8.RELEASE
the spring  inner code:
![image](https://user-images.githubusercontent.com/8341790/57423745-d13a1580-7247-11e9-8831-1e5e201f5e11.png)

I think it only support for spring-data-mongodb-2.x ?

**Comment by RoySRose** [comment]
@zfaster 

Nice point!! 
I think that can be the reason. On my test, I've used spring-data-mongodb-2.x.
If spring-data-mongodb-1.x uses DBCollection from `mongo-java-driver 2.x`
Maybe after this PR #5435 , it also may work!

**Comment by zfaster** [comment]
@RoySRose  spring-data-mongodb-1.x use is mongodb-driver-3.x , do you consider to support it in the future?

**Comment by RoySRose** [comment]
@zfaster 

I think you are getting the other way around.

isn't it as below?
`spring-data-mongodb 1.x` , `mongodb-driver-2.x`
`spring-data-mongodb 2.x` , `mongodb-driver-3.x`

Pinpoint Mongo-plugin already supports `mongodb-driver-3.x`, so `spring-data-mongodb 2.x` follows.
But not yet support `mongodb-driver-2.x`. which would be the reason `spring-data-mongodb 1.x` is not instrumented.

Since PR #5435 is to support `mongodb-driver-2.x`, I think  `spring-data-mongodb 1.x` will be also taken care of.

Tell me if I've got something wrong.

**Comment by zfaster** [comment]
@RoySRose 
I think you are worng,  
my project use spring-data-mongodb-1.10.12.RELEASE.jar
dependency mongodb-driver-3.4.3.jar

![image](https://user-images.githubusercontent.com/8341790/57430240-a65cbb00-7261-11e9-99c7-2f3d01a6fbbe.png)

I try to modify plugin code , add DBCollection wapper

`
 private void addSessionTransformerForDBCollection3_0_X(final MongoConfig config) {
        TransformCallback transformCallback = new TransformCallback() {

            @Override
            public byte[] doInTransform(Instrumentor instrumentor, ClassLoader loader, String className, Class<?> classBeingRedefined, ProtectionDomain protectionDomain, byte[] classfileBuffer) throws InstrumentException {
                final InstrumentClass target = instrumentor.getInstrumentClass(loader, className, classfileBuffer);

                if (!target.isInterceptable()) {
                    return null;
                }

                target.addField("com.navercorp.pinpoint.bootstrap.plugin.jdbc.DatabaseInfoAccessor");

                for (InstrumentMethod method : target.getDeclaredMethods(MethodFilters.chain(MethodFilters.modifier(Modifier.PUBLIC), MethodFilters.name(getMethodlistRForDBCollection3_0_x())))) {
                    method.addScopedInterceptor("com.navercorp.pinpoint.plugin.mongo.interceptor.MongoRSessionInterceptor", va(config.isCollectJson(), config.istraceBsonBindValue()), MONGO_SCOPE, ExecutionPolicy.BOUNDARY);
                }

                for (InstrumentMethod method : target.getDeclaredMethods(MethodFilters.chain(MethodFilters.modifier(Modifier.PUBLIC), MethodFilters.name(getMethodlistCUDForDBCollection3_0_x())))) {
                    method.addScopedInterceptor("com.navercorp.pinpoint.plugin.mongo.interceptor.MongoCUDSessionInterceptor", va(config.isCollectJson(), config.istraceBsonBindValue()), MONGO_SCOPE, ExecutionPolicy.BOUNDARY);
                }
                return target.toBytecode();
            }
        };

        // java driver 3.0.0 ~ 3.6.4
        transformTemplate.transform("com.mongodb.DBCollection", transformCallback);
    }`

I found it work ！but have some bug need to fix~
![image](https://user-images.githubusercontent.com/8341790/57430427-3bf84a80-7262-11e9-96b3-f8b0265de85d.png)

**Comment by RoySRose** [comment]
@zfaster 

Then, it's nothing to do with the version of mongodb-driver.
It only depends on the difference in Collections, whether it's `DBCollection` or `MongoCollection`

Still, as quoted above PR #5435 takes care of `DbCollection` in the plugin.
If the PR is merged, I think spring-data-mongodb 1.x also will be supported.

**Comment by zfaster** [comment]
@RoySRose 
I simple change code, and it now support for spring-data-mongodb-1.x ,but not support for mongodb-driver-2.x

this is my change:

`private void addSessionTransformerForDBCollection3_0_X(final MongoConfig config) {
        TransformCallback transformCallback = new TransformCallback() {

            @Override
            public byte[] doInTransform(Instrumentor instrumentor, ClassLoader loader, String className, Class<?> classBeingRedefined, ProtectionDomain protectionDomain, byte[] classfileBuffer) throws InstrumentException {
                final InstrumentClass target = instrumentor.getInstrumentClass(loader, className, classfileBuffer);

                if (!target.isInterceptable()) {
                    return null;
                }
                //ignore if mongodb2.x
                if(target.hasField("_db")){
                    return null;
                }
                target.addField("com.navercorp.pinpoint.bootstrap.plugin.jdbc.DatabaseInfoAccessor");

                for (InstrumentMethod method : target.getDeclaredMethods(MethodFilters.chain(MethodFilters.modifier(Modifier.PUBLIC), MethodFilters.name(getMethodlistRForDBCollection3_0_x())))) {
                    method.addScopedInterceptor("com.navercorp.pinpoint.plugin.mongo.interceptor.MongoRSessionInterceptor", va(config.isCollectJson(), config.istraceBsonBindValue()), MONGO_SCOPE, ExecutionPolicy.BOUNDARY);
                }

                for (InstrumentMethod method : target.getDeclaredMethods(MethodFilters.chain(MethodFilters.modifier(Modifier.PUBLIC), MethodFilters.name(getMethodlistCUDForDBCollection3_0_x())))) {
                    method.addScopedInterceptor("com.navercorp.pinpoint.plugin.mongo.interceptor.MongoCUDSessionInterceptor", va(config.isCollectJson(), config.istraceBsonBindValue()), MONGO_SCOPE, ExecutionPolicy.BOUNDARY);
                }

                return target.toBytecode();
            }
        };

        // java driver 3.0.0 ~ 3.6.4
        transformTemplate.transform("com.mongodb.DBCollection", transformCallback);
    }`


`public final class DatabaseInfoUtils {
    private DatabaseInfoUtils() {
    }

    public static DatabaseInfo getDatabaseInfo(Object target, DatabaseInfo defaultDatabaseInfo) {
        if (target instanceof DatabaseInfoAccessor) {
            final DatabaseInfo databaseInfo = ((DatabaseInfoAccessor) target)._$PINPOINT$_getDatabaseInfo();
            if (databaseInfo != null) {
                return databaseInfo;
            }
        }
        if(target instanceof DBCollection){
            Mongo mongo = ((DBCollection)target).getDB().getMongo();
            if(mongo instanceof DatabaseInfoAccessor){
                final DatabaseInfo databaseInfo = ((DatabaseInfoAccessor) mongo)._$PINPOINT$_getDatabaseInfo();
                if (databaseInfo != null) {
                    return new MongoDatabaseInfo(databaseInfo.getType(), databaseInfo.getExecuteQueryType()
                            , databaseInfo.getRealUrl(), databaseInfo.getUrl(), databaseInfo.getHost(), ((DBCollection)target).getDB().getName()
                            ,  ((DBCollection)target).getName(), ((MongoDatabaseInfo) databaseInfo).getReadPreference(), ((MongoDatabaseInfo) databaseInfo).getWriteConcern());

                }
            }
        }
        return defaultDatabaseInfo;
    }

}`
![image](https://user-images.githubusercontent.com/8341790/57498743-b16e2480-730f-11e9-8a4b-53a5e6cc6c53.png)

maybe it change not good,but trace is work fine,  do you think this change have hidden bug?

**Comment by RoySRose** [comment]
@zfaster 

Yes, maybe some of these codes should become a part of the plug-in in PR #5435.
Since Mongo java driver 2.x uses DBCollection. I believe `spring-data-mongodb 1.x` will work after the PR is merged.

**Comment by zfaster** [comment]
thank you @RoySRose
