### ISSUE TITLE
why  calllist  broken when next step is redis op?

### ISSUE THREAD

**Issue by rainard** [naver/pinpoint#5585]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
master/v1.8.1 etc.

#### Describe the bug
why reids calllist broken as screenshot ? 

* jedis 2.7.3 
* pp 1.8.1
 
---
if redis op next to  spring_bean , this error occurs frequently,see pic 3

#### Screenshots
* error pic
![image](https://user-images.githubusercontent.com/30309517/57499282-c2b83080-7311-11e9-835b-1c7d6470a334.png)
 * normal pic
![image](https://user-images.githubusercontent.com/30309517/57499456-58ec5680-7312-11e9-91df-0362709caf49.png)

* redis op next to sping_bean op
![image](https://user-images.githubusercontent.com/30309517/57499743-5b02e500-7313-11e9-8b8f-e812fc76d5bf.png)

**Comment by Xylus** [comment]
Hi @rainard 
Corrupted call stacks usually indicate packet loss between agent and collector, or that collector's hbase work queue is full. (You can check the latter by checking the collector's *stat.log* for `name=spanReceiverExecutor.rejected` value)

Please let me know if you find out that both of these aren't what's causing your issue.
Thanks.

**Comment by rainard** [comment]
I have no idea about the first step ,but I check stat.log,it's nomal .
after all ,I modify  `/com/navercorp/pinpoint/web/calltree/span/SpanCallTree.java`  as below ,it work !
dose it any problem?
![image](https://user-images.githubusercontent.com/30309517/58849532-3e14c400-86bd-11e9-8cc2-8025bfc0edba.png)
