### ISSUE TITLE
Corrupted(waiting for packet)

### ISSUE THREAD

**Issue by zhangiicc** [naver/pinpoint#5600]
I usually find an error node from my calltree called 'Corrupted(invalid sequence)' .
pinpoint version:1.8.3
I have referred to the issues:
![image](https://user-images.githubusercontent.com/30918699/57672858-6411f000-764c-11e9-9a12-bfdf4622f19e.png)
[Uploading stat.log…]()
[Uploading 584869cf4d-6v2dq-pinpoint.log…]()

Is it beyond the limit of hbase?

**Comment by zhangiicc** [comment]
Whether pinpoint supports kubernetes ，this agent is in pods

**Comment by Xylus** [comment]
Hi @zhangiicc 
Pinpoint should work on applications running in kubernetes.
Udp packet loss between the agent and the collector can cause corrupted call stack, as well as collector's worker queue being full.

To see if the collector's worker queue is full, check the *stat.log* file of your collector. It will print out a report with `name=spanReceiverExecutor.rejected` with a count on rejected span count.
If this number increases significantly (compared to `spanReceiverExecutor.submitted` count) every minute, then you might want to increase your collector's `collector.receiver.span.worker.queueSize` in *pinpoint-collector.properties*. Or you might have to scale out your hbase.
If the collector's worker queue is not full, then you might want to see if your network is stable for udp transports.

Lastly however, if there's a certain pattern in these corrupted call stacks, such as them showing up 100% only in certain APIs (following a specific code path), then it may be due a bug in one of our plugins. If this is the case, you might want to check your agent log for errors, or tell us which part of the code path is always being corrupted so we can take a closer look.
