### ISSUE TITLE
is it possible to separate different redis in diagram?

### ISSUE THREAD

**Issue by xiaotuanyu120** [naver/pinpoint#5604]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [yes ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

 we have multiple mysql and redis for different usage, but it seems like pinpoint will combine these together in diagram and just tag a number of instance on the service logo.

so is it possible we can manually modify it?

for example one redis is for session keep and another is for cache

**Comment by Xylus** [comment]
Hi @xiaotuanyu120 
You can right click on white background of the server map to bring up a menu.
Under "Node Setting", there should be an option to "Merge MYSQL" etc, which are enabled by default.
Try disabling these to see if you get what you're looking for.

**Comment by xiaotuanyu120** [comment]
> Hi @xiaotuanyu120
> You can right click on white background of the server map to bring up a menu.
> Under "Node Setting", there should be an option to "Merge MYSQL" etc, which are enabled by default.
> Try disabling these to see if you get what you're looking for.

okay，   I'll try it.
