### ISSUE TITLE
Hello, you can only query for 2 days at most, I want to check the time period of 5 days at a time, can it be realized? 

### ISSUE THREAD

**Issue by fangfuhaomin** [naver/pinpoint#5611]
pinpoint 1.8
It will take at least five days to solve the problem,
Can you tell me how to modify the data saving time.
thank you

**Comment by RoySRose** [comment]
Hello, @fangfuhaomin 

Please check FAQ
https://naver.github.io/pinpoint/faq.html#hbase-is-taking-up-too-much-space-which-data-should-i-delete-first
