### ISSUE TITLE
How to configure pinpoint agent to send stats on tcp

### ISSUE THREAD

**Issue by immusk** [naver/pinpoint#5618]
#### Prerequisites
- [yes ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
master/v1.8.3

#### Describe your problem**
I want my agent to send stats on tcp only

#### What have you done?
Steps you have taken to trigger the problem, for example:
1. have updated the config on the agent to enable TCP instead of UDP
`profiler.spandatasender.transport.type=TCP
profiler.statdatasender.transport.type=TCP`
2. restarted my agent, but still I see that agent is listening on UDP
[root@test-pinpoint xxxxxxx:/mnt1/test-pinpoint/new-agent] ss -nlp | grep 999
udp    UNCONN     0      0        :::9995                 :::*                   users:(("java",pid=9168,fd=342))
udp    UNCONN     0      0        :::9996                 :::*                   users:(("java",pid=9168,fd=341))
tcp    LISTEN     0      50       :::9994                 :::*                   users:(("java",pid=9168,fd=340))

I want the agent to send stats only on TCP, how can I configure it.

Please suggest

**Comment by koo-taejin** [comment]
hi @immusk 

To use TCP, you must modify the settings in the Agent module and in the Collector module. 

* agent 
You only need to modify the part of the agent that you recorded. 

* collector 
You must change the following settings within the point-collector.properties: 
```
collector.receiver.stat.tcp
collector.receiver.span.tcp
```

You can use both tcp and udp, and you can use only one tcp or udp. 
Please modify the enable setting to suit your environment.

thanks.

**Comment by immusk** [comment]
@koo-taejin 

I have configured agent and collector to point to TCP 

now I am able to get the instance stats where the agent is running
But Application stats are missing
I have my agent running on tomcat server and I am able to see the stats of the instance on which my tomcat server is running
but not able to see any tomcat application stats

please suggest if I am missing anything here

<img width="1440" alt="Screenshot 2019-05-22 at 2 17 14 PM" src="https://user-images.githubusercontent.com/8833971/58160798-c72f0280-7c9c-11e9-9e94-cc97ef5b1f74.png">

<img width="1436" alt="Screenshot 2019-05-22 at 2 15 57 PM" src="https://user-images.githubusercontent.com/8833971/58160453-250f1a80-7c9c-11e9-87cf-457072813f58.png">

**Comment by koo-taejin** [comment]
@immusk 

I am sure that the stat data is normal by looking at the inspector you posted. 
stat data uses 9995 port, span (as you say 'application stat') uses 9996 port. 

It doesn't seem to be a problem with tcp or udp, because i can show inspector data.

It is expected to be one of the following issues. 
1.sampling rate : sampling rate'profiler.sampling.rate' 
(1 out of n transactions will be sampled where n is the rate.)
2. The server map or scatter chart needs to be requested from the Tomcat before it can be seen to the user. 
Please make sure you sent the request.

**Comment by immusk** [comment]
@koo-taejin 

I am getting stats of instance,
do you mean I am getting this from port 9995 and 
application stats(response summary, load etc) which I am not getting are from port 9996?

also 

can you please suggest how can I configure this
`profiler.sampling.rate` - I have updated the value to 5, but no luck
`server map or scatter chart needs to be requested from the Tomcat before it can be seen to the user`

**Comment by Xylus** [comment]
@immusk @koo-taejin 
Sorry I should've posted this earlier.
There is currently a bug where agent span data cannot be sent over TCP.
This has been fixed in 1.8.x branch via #5524 , but is not part of 1.8.3 release.

We'll need a 1.8.4 release for this fix.

**Comment by immusk** [comment]
@koo-taejin @Xylus built the agent from 1.8.x now span stats are coming up.
Thanks alottt

**Comment by Xylus** [comment]
@immusk Thanks for testing it out and letting us know.
If you encounter any further problem, please do let us know.

**Comment by koo-taejin** [comment]
hi @immusk 
Have released [1.8.4](https://github.com/naver/pinpoint/releases/tag/1.8.4) version which has been solved for this issue.
