### ISSUE TITLE
Can springcloud use this?

### ISSUE THREAD

**Issue by qq297910962** [naver/pinpoint#5620]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

**Comment by RoySRose** [comment]
Hello, @qq297910962 

We are not sure If all tools of Spring Cloud will be supported.
Some will, and the rest of them, I think maybe partly.

If you can try and share the result.
It would be GREAT!
