### ISSUE TITLE
ServerMap and TimeLine does not show normally in [transactionDetail] page of new UI.

### ISSUE THREAD

**Issue by messi-gao** [naver/pinpoint#5623]
step 1: Go to the callTree view of transactionDetail page.
![image](https://user-images.githubusercontent.com/24312100/58222219-dae37300-7d47-11e9-8624-c0c9fa13f0db.png)

step 2:Click the ServerMap.The page does not show normally.But if you refresh the page,the page becomes to normally.
![image](https://user-images.githubusercontent.com/24312100/58222273-11b98900-7d48-11e9-804e-7748adc3ddc5.png)

step 3:Click the TimeLine.The page leaves a big white space in the bottom.But if you refresh the page,the page becomes to normally.
![image](https://user-images.githubusercontent.com/24312100/58222340-4c232600-7d48-11e9-8a90-a4e9153867bd.png)

@denzels

**Comment by messi-gao** [comment]
@denzelsN 
The problem of step2 has been fixed.But the problem of step3 still exists.
![image](https://user-images.githubusercontent.com/24312100/59168724-95a5aa80-8b69-11e9-91a3-6ed4c952717a.png)

if you refresh the page above,the TimeLine page becomes to normal.Then you click the servermap,you will find the servermap page becomes unnormal.
![image](https://user-images.githubusercontent.com/24312100/59168847-2a100d00-8b6a-11e9-8a53-4e1509cfe74e.png)
![image](https://user-images.githubusercontent.com/24312100/59168864-37c59280-8b6a-11e9-93ef-4126dc3d32d4.png)

**Comment by denzelsN** [comment]
@messi-gao 
I can't reproduce the bug you talked about.
What's your browser?

**Comment by messi-gao** [comment]
@denzelsN 
Google Chrome
Version 73.0.3683.103 (Official Build) (64-bit)

This is my code :

<div class="l-content-section">
    <pp-transaction-short-info-container></pp-transaction-short-info-container>
    <div class="l-middle-tool-box">
        <pp-transaction-detail-menu-container></pp-transaction-detail-menu-container>
        <pp-transaction-search-container [hidden]="!isCallTreeView()"></pp-transaction-search-container>
        <div>
            <button class="fas fa-external-link-alt l-middle-tool-box-tip" (click)="onOpenTransactionDetailPage()"></button>
            &nbsp;
            <button class="fas fa-question-circle l-middle-tool-box-tip" (click)="onShowHelp($event)"></button>
        </div>
    </div>
    <div class="l-component-wrapper">
        <pp-call-tree-container></pp-call-tree-container>
        <pp-server-map-for-transaction-list-container style="height: calc(100% - 84px)"
            [hidden]="isSameType('serverMap') === false"
        ></pp-server-map-for-transaction-list-container>
        <ng-container *ngIf="isSameType('timeline')">
            <pp-transaction-timeline-container></pp-transaction-timeline-container>
        </ng-container>
    </div>
    <pp-film-for-disable *ngIf="useDisable" [zIndex]="9" [marginWidth]="0"></pp-film-for-disable>    
    <pp-loading [showLoading]="showLoading" [zIndex]="10"></pp-loading>
</div>

My Pinpoint version is 1.8.3,and I find some code difference between us,If I change your code,the page can not be displayed.
my code:
![image](https://user-images.githubusercontent.com/24312100/59176245-11641f00-8b8b-11e9-8906-108e83eefbf9.png)

your code:
![image](https://user-images.githubusercontent.com/24312100/59176292-2c369380-8b8b-11e9-87c8-bdaee8bcffc3.png)

If I change your code,error:
![image](https://user-images.githubusercontent.com/24312100/59176467-b8e15180-8b8b-11e9-8cbe-9a74da10114b.png)

**Comment by denzelsN** [comment]
@messi-gao 
Use the following code to remove bugs from the 1.8.3 :
```` html
<ng-container *ngIf="isSameType('serverMap')">
   <pp-server-map-for-transaction-list-container
     style="height: calc(100% - 84px)"
  ></pp-server-map-for-transaction-list-container>
</ng-container>
````

**Comment by messi-gao** [comment]
@denzelsN 
Thank you for your reply! The transactionList page has worked well.
But the transactionDetail page still has the same problem.
![image](https://user-images.githubusercontent.com/24312100/59180174-cbad5380-8b96-11e9-97b1-c7285988f727.png)

**Comment by denzelsN** [comment]
@messi-gao 
Thank you.  I fixed it.

**Comment by messi-gao** [comment]
@denzelsN 
You may forget that my local code version is 1.8.3,the pp-server-map-others-container of your code occurs error,could you give me the code based 1.8.3?

error based your code:
![image](https://user-images.githubusercontent.com/24312100/59236971-f8ab4600-8c2a-11e9-85ab-3e871d34c17f.png)

**Comment by denzelsN** [comment]
@messi-gao 
It's similar to the code above.

```` html
<!--
<ng-container *ngIf="isSameType('serverMap')">
            <pp-server-map-others-container [sourceType]="'TRANSACTION_LIST'"></pp-server-map-others-container>
</ng-container>
-->
<ng-container *ngIf="isSameType('serverMap')">
   <pp-server-map-for-transaction-list-container></pp-server-map-for-transaction-list-container>
</ng-container>
````

**Comment by messi-gao** [comment]
@denzelsN 
I have tested the like code like yours,but it still has some error:

![image](https://user-images.githubusercontent.com/24312100/59237504-285b4d80-8c2d-11e9-87e6-3187660b33e9.png)

![image](https://user-images.githubusercontent.com/24312100/59237572-593b8280-8c2d-11e9-93b6-7f9ccbbf7140.png)

my code:
<div class="l-content-section">
    <pp-transaction-short-info-container></pp-transaction-short-info-container>
    <div class="l-tab-menu-options l-middle-tool-box">
        <pp-transaction-detail-menu-for-detail-container></pp-transaction-detail-menu-for-detail-container>
        <pp-transaction-search-container [hidden]="isHiddenSearchComponent()"></pp-transaction-search-container>
        <div>
            <button class="fas fa-question-circle l-middle-tool-box-tip" (click)="onShowHelp($event)"></button>
        </div>
    </div>
    <div class="l-component-wrapper">
        <pp-call-tree-container></pp-call-tree-container>
        <ng-container *ngIf="isSameType('serverMap')">
            <pp-server-map-for-transaction-list-container></pp-server-map-for-transaction-list-container>
        </ng-container>
        <ng-container *ngIf="isSameType('timeline')">
            <pp-transaction-timeline-container></pp-transaction-timeline-container>
        </ng-container>
    </div>
</div>

**Comment by denzelsN** [comment]
@messi-gao 
add  following code to `transaction-detail-contents-container.compoennt.ts`
```` javascript 
isSameType(type: string): boolean {
      return this.currentViewType === type;
}
````

**Comment by messi-gao** [comment]
@denzelsN 
Thank you for reply! It works now!
