### ISSUE TITLE
Trace EJB for Weblogics 

### ISSUE THREAD

**Issue by aman4387** [naver/pinpoint#5641]
**Which module is your feature request related to?**
Weblogics  Plugin

**Is your feature request related to a problem?**
Pinpoint agent unable to capture internal ejb or remote EJB  calls

I am using pinpoint for weblogic profiling where i am to track the java bean and methods for web-services calls after profiling the classes in config file but when there is direct remote EJB call from client pinpoint not showing the call

**Comment by hongfangan** [comment]
I also encounter this problem，how to resolve it？

**Comment by emeroad** [comment]
The webloginc plugin does not support the remote EJB.

The remote EJB tracking requires RMI instrumentation.
However, this is not currently implemented.
Contributions are welcome, we have no plan to do this yet.
