### ISSUE TITLE
Use a java program to periodically call httpclient to request an application running in tomcat. Both of them were loaded with probes and found that the topology maps were not connected together.

### ISSUE THREAD

**Issue by chkch** [naver/pinpoint#5656]
Use a java program to periodically call httpclient to request an application running in tomcat. Both of them were loaded with probes and found that the topology maps were not connected together.

**Comment by Xylus** [comment]
Hi @chkch 
Please use the [troubleshooting](https://github.com/naver/pinpoint/issues/new?template=troubleshooting.md) template and include more detail.
