### ISSUE TITLE
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M2:enforce 

### ISSUE THREAD

**Issue by carlgan** [naver/pinpoint#5685]
#### Prerequisites
windows 7 64bit  
java 1.8 
#### What version of pinpoint are you using?
master/v1.7.3/

#### Describe your problem**
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M2:enforce 

#### What have you done?
Steps you have taken to trigger the problem, for example:
1.  run command      ./mvnw install -Dmaven.test.skip=true

#### Logs
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.315 s
[INFO] Finished at: 2019-06-11T16:31:38+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M2:enforce (enforce-pinpoint-build-requirements) on project pinpoi
nt: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by carlgan** [comment]
http://cwiki.apache.org/confluencee/display/MAVEN/MojoExecutionException
I have read the website but don't get the any solution usefully

**Comment by koo-taejin** [comment]
hi @carlgan 
You can get more detail information using the method shown in the error log. 
```
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```
And I recommend that you view whole log, not just the last log.

thanks.

**Comment by liyang1518** [comment]
> http://cwiki.apache.org/confluencee/display/MAVEN/MojoExecutionException
> I have read the website but don't get the any solution usefully

I have encountered the same problem. The link you gave has expired, who can help me.

**Comment by madalion** [comment]
Hi,Do you have resolve this problem?I got this question too

**Comment by koo-taejin** [comment]
@madalion 
You have to explain the environment of Maven in detail so that I can give you help.
If possible, it would be best if you could explain the situation that can be reproduced.

thanks :)

**Comment by zcgewu** [comment]
报这个错是这个插件强制做了配置检查
`<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>${plugin.enforcer.version}</version>
                <executions>
                    <execution>
                        <id>enforce-pinpoint-build-requirements</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <requireMavenVersion>
                                    <version>3.5</version>
                                </requireMavenVersion>
                                <requireJavaVersion>
                                    <version>1.8</version>
                                </requireJavaVersion>
                                <requireEnvironmentVariable>
                                    <variableName>JAVA_HOME</variableName>
                                </requireEnvironmentVariable>
                                <requireEnvironmentVariable>
                                    <variableName>JAVA_6_HOME</variableName>
                                </requireEnvironmentVariable>
                                <requireEnvironmentVariable>
                                    <variableName>JAVA_7_HOME</variableName>
                                </requireEnvironmentVariable>
                                <requireEnvironmentVariable>
                                    <variableName>JAVA_8_HOME</variableName>
                                </requireEnvironmentVariable>
                                <requireEnvironmentVariable>
                                    <variableName>JAVA_9_HOME</variableName>
                                </requireEnvironmentVariable>
                            </rules>
                            <fail>true</fail>
                        </configuration>
                    </execution>
                </executions>
            </plugin>`

配置上java各版本的环境变量

export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home
export JAVA_6_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home
export JAVA_7_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home
export JAVA_8_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home
export JAVA_9_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home

**Comment by ChrisZhangJin** [comment]
yes that's right.  It got rid of the maven error by deleting this plugin in the pom.xml


> 报这个错是这个插件强制做了配置检查 `<plugin> <groupId>org.apache.maven.plugins</groupId> <artifactId>maven-enforcer-plugin</artifactId> <version>${plugin.enforcer.version}</version> <executions> <execution> <id>enforce-pinpoint-build-requirements</id> <phase>validate</phase> <goals> <goal>enforce</goal> </goals> <configuration> <rules> <requireMavenVersion> <version>3.5</version> </requireMavenVersion> <requireJavaVersion> <version>1.8</version> </requireJavaVersion> <requireEnvironmentVariable> <variableName>JAVA_HOME</variableName> </requireEnvironmentVariable> <requireEnvironmentVariable> <variableName>JAVA_6_HOME</variableName> </requireEnvironmentVariable> <requireEnvironmentVariable> <variableName>JAVA_7_HOME</variableName> </requireEnvironmentVariable> <requireEnvironmentVariable> <variableName>JAVA_8_HOME</variableName> </requireEnvironmentVariable> <requireEnvironmentVariable> <variableName>JAVA_9_HOME</variableName> </requireEnvironmentVariable> </rules> <fail>true</fail> </configuration> </execution> </executions> </plugin>`
> 
> 配置上java各版本的环境变量
> 
> export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home export JAVA_6_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home export JAVA_7_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home export JAVA_8_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home export JAVA_9_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home
