### ISSUE TITLE
Since each service refers to Agent, can it be put in one place so that all Catalina can load the remote probe?

### ISSUE THREAD

**Issue by zhang-wenfu** [naver/pinpoint#5689]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

Can we put Agent on a server and let the services on other servers that need Agent come to this server to get jar?

**Comment by Xylus** [comment]
Hi @zhang-wenfu 
Sorry for the late reply.
Yes, you can share the agent jar between multiple applications as long as you launch the applications with different agent ids.
Do note that since you're sharing a single agent jar, the agent configuration (*pinpoint.config*) is also shared.
