### ISSUE TITLE
About Webflux and the server map

### ISSUE THREAD

**Issue by jc-lab** [naver/pinpoint#5696]
안녕하세요.
pinpoint를 설치하고 2개의 서비스(gateway, backend-1)에 pinpoint agent를 연결했습니다.
그런데 사용법에 대해 질문이 있습니다.

1. 서버맵..
일단 applicationName은 서비스의 이름이라고 알고 있는데 gateway, backend-1 이런식으로 하는게 맞나요? 일단 그렇게 설정했는데..
pinpoint 메인화면에서 꼭 하나의 application을 선택하도록 되어있습니다.
만약 모든 서비스를 한번에 보려면 (서버맵을 보려면) 다른 작업을 해야 하나요?
사진 추가했습니다.
![image](https://user-images.githubusercontent.com/30275706/59553139-b9cf1480-8fcb-11e9-9969-bbf7b235a8da.png)
이렇게 각 1개의 서비스만 동시에 볼 수 있습니다.

2. Webflux가 1.9.0-SNAPSHOT버전 (github master branch)에 지원되는거 같은데 아직 작동은 안하는건가요? spring-cloud-gateway 사용중인데 트레픽을 인식하지 못합니다.

**Comment by RoySRose** [comment]
Hello, @jc-lab 

please note that when you post an issue on Github,
it's open to the community, and it would be great if everyone can understand.
All contributors would be grateful if you can translate it in English.

Please consider using just English afterward. Thanks ;)

**Comment by jc-lab** [comment]
I installed pinpoint and connected pinpoint agent to two services (gateway, backend-1).
But I have a question about usage.

Server map ..
I understood that the applicationName is the name of the service.
e.g. gateway, backend-1. It is correct?

The pinpoint can select one application from the main screen.
Do I have to do anything else if I want to see all the services at once (to see the server map)?
Photo added.
(IMAGE)
Only one service can be viewed at the same time.

Webflux seems to be supported in version 1.9.0-SNAPSHOT (github master branch), but does not work yet? I am using spring-cloud-gateway, but I do not recognize the traffic.

**Comment by emeroad** [comment]
1. If there is a call between the two servers, both servers are displayed.

2. Unfortunately, Mono or Flux is not supported yet.

**Comment by RoySRose** [comment]
Hello, @jc-lab 

Change the depth to get a deeper view within the servermap

![image](https://user-images.githubusercontent.com/20402016/59660890-94692300-91e4-11e9-8cca-1797cddf035a.png)

**Comment by jc-lab** [comment]
@RoySRose @emeroad
Thanks for answer.
Maybe it is because the webflux gateway did not recognize it.
But the 1.9.0-SNAPSHOT version says that it supports webflux, is not it?

**Comment by RoySRose** [comment]
@jc-lab 

SNAPSHOT versions may not be stable since all the members in the team are actively committing on the `master` branch. Also *webflux plugin* has been merged #5482 recently and may have some shortages.
