### ISSUE TITLE
pinpoint dubbo2.7.0 plugin

### ISSUE THREAD

**Issue by qq295190549** [naver/pinpoint#5697]
Developed dubbo2.7.0 plugin, but the consumer web page does not display the producer's DUBBO icon and service name
![image](https://user-images.githubusercontent.com/17867113/59562474-e59bda00-905f-11e9-9b55-613837dc070f.png)，
But the producer side shows that the call chain is correct.
![微信截图_20190616180810](https://user-images.githubusercontent.com/17867113/59572195-073ba680-90de-11e9-8245-1a998e42eff0.png)

**Comment by qq295190549** [comment]
代码如下：
    public static final ServiceType DUBBO_PROVIDER_SERVICE_TYPE = ServiceTypeFactory.of(1999, "APACHE_DUBBO_PROVIDER", RECORD_STATISTICS);
    public static final ServiceType DUBBO_CONSUMER_SERVICE_TYPE = ServiceTypeFactory.of(9997, "APACHE_DUBBO_CONSUMER", RECORD_STATISTICS);
    public static final ServiceType DUBBO_PROVIDER_SERVICE_NO_STATISTICS_TYPE = ServiceTypeFactory.of(9999, "APACHE_DUBBO");
    public static final AnnotationKey DUBBO_ARGS_ANNOTATION_KEY = AnnotationKeyFactory.of(997, "apache.dubbo.args");
    public static final AnnotationKey DUBBO_RESULT_ANNOTATION_KEY = AnnotationKeyFactory.of(998, "apache.dubbo.result");
    public static final AnnotationKey DUBBO_RPC_ANNOTATION_KEY = AnnotationKeyFactory.of(999, "apache.dubbo.rpc", VIEW_IN_RECORD_SET);

**Comment by Xylus** [comment]
Hi @qq295190549 
It's because the application itself is a Spring Boot application, and you're using Dubbo on top of it.
It's similar to when you're using Embedded Tomcat on top of Spring Boot, the application type will be Spring Boot instead of Tomcat.

If you would like to override this and manually set the application type to be Dubbo, you can uncomment `profiler.applicationservertype` option in *pinpoint.config* and set it to `APACHE_DUBBO_PROVIDER` like below:
```
profiler.applicationservertype=APACHE_DUBBO_PROVIDER
```

**Comment by qq295190549** [comment]
> Hi @qq295190549
> It's because the application itself is a Spring Boot application, and you're using Dubbo on top of it.
> It's similar to when you're using Embedded Tomcat on top of Spring Boot, the application type will be Spring Boot instead of Tomcat.
> 
> If you would like to override this and manually set the application type to be Dubbo, you can uncomment `profiler.applicationservertype` option in _pinpoint.config_ and set it to `APACHE_DUBBO_PROVIDER` like below:
> 
> ```
> profiler.applicationservertype=APACHE_DUBBO_PROVIDER
> ```

I tried to configure profiler.applicationservertype=APACHE_DUBBO_PROVIDER, the service icon is changed to DUBBO, but the serviceType displayed by the caller is UNKNOWN, and the callee is also configured with the pinpoint agent. How can I solve the problem that serviceType is UNKNOWN?

**Comment by Xylus** [comment]
Hmm, have you restarted collector and web after building your plugin? 
Also, have you added the images to the web as mentioned [here](http://naver.github.io/pinpoint/plugindevguide.html#4-adding-images)?

It would also help if you could check your logs or debug your agent/web to see why it's showing up as UNKNOWN.

**Comment by qq295190549** [comment]
> Hmm, have you restarted collector and web after building your plugin?
> Also, have you added the images to the web as mentioned [here](http://naver.github.io/pinpoint/plugindevguide.html#4-adding-images)?
> 
> It would also help if you could check your logs or debug your agent/web to see why it's showing up as UNKNOWN.

Hi @Xylus 
The developed plugin will be placed in the web/collector WEB-INFO/lib directory and the agent plugin directory, and restarted. The web has also added images. Now the service should not be able to identify what type of project, and the serviceType is UNKNOWN. I want to know how pinpoint judges the type of service of the callee. Where is the source code? I can look at the source code.
![image](https://user-images.githubusercontent.com/17867113/59577365-06af0a00-90f6-11e9-800e-a6f44fbff7ac.png)

**Comment by Xylus** [comment]
The main server map identifies the service type of the callee by checking the acceptor host of the callee's span in [RpcCallProcessor](https://github.com/naver/pinpoint/blob/master/web/src/main/java/com/navercorp/pinpoint/web/service/map/processor/RpcCallProcessor.java).
Please take a look at [this comment](https://github.com/naver/pinpoint/issues/1395#issuecomment-168874826) for reference.

It would also be best to debug the **RpcCallProcessor** when querying the server map and take a look at your data.

**Comment by qq295190549** [comment]
> The main server map identifies the service type of the callee by checking the acceptor host of the callee's span in [RpcCallProcessor](https://github.com/naver/pinpoint/blob/master/web/src/main/java/com/navercorp/pinpoint/web/service/map/processor/RpcCallProcessor.java).
> Please take a look at [this comment](https://github.com/naver/pinpoint/issues/1395#issuecomment-168874826) for reference.
> 
> It would also be best to debug the **RpcCallProcessor** when querying the server map and take a look at your data.

Thank you, I will try

**Comment by qq295190549** [comment]
Hi @Xylus 
Has been resolved, the reason is that when the server has docker, dubbo rpcContext.getLocalAddressString () gets the ip for the docker0 network card ip, not the eth0 network card ip, resulting in the web can not match.

**Comment by Xylus** [comment]
@qq295190549 
Awesome! Thanks for testing it all out and sharing your findings.
