### ISSUE TITLE
Vertx plugin to support 3.7.0 

### ISSUE THREAD

**Issue by barrycheng** [naver/pinpoint#5704]
Vertx HTTP Server/Client.

Currently supports vertx.io 3.3.x, 3.4.1, 3.4.2, 3.5.0

I use a gateway use Vertx 3.7.0, pinpoint not work well.

**Comment by jaehong-kim** [comment]
@barrycheng 

Please refer to settings. [permalink](https://github.com/naver/pinpoint/blob/24b98e8f53f9eb2a5b8b6e69630f287a7fddbc61/agent/src/main/resources-release/pinpoint.config#L344)
~~~
# Set HttpServerRequestHandler method name. The argument is io.vertx.core.http.HttpServerRequest.
# Vert.x 3.6 ~ 3.7
profiler.vertx.http.server.request-handler.method.name=io.vertx.ext.web.impl.RouterImpl.handle
# Vert.x 3.5
# profiler.vertx.http.server.request-handler.method.name=io.vertx.ext.web.impl.RouterImpl.accept
~~~

**Comment by barrycheng** [comment]
I change the pinpoint agent config, but no change.

The application is gravitee-gateway V1.26.1
https://github.com/gravitee-io/gravitee-gateway

The start command is
java -Djava.net.preferIPv4Stack=true -Xms512m -Xmx512m -Djava.awt.headless=true -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -javaagent:/opt/graviteeio-gateway-1.26.1/boot/jetty-alpn-agent-2.0.9.jar -javaagent:/pinpoint-agent-1.8.4/pinpoint-bootstrap-1.8.4.jar -Dpinpoint.agentId=APIM -Dpinpoint.applicationName=APIM -Dvertx.disableFileCaching=true -Dvertx.disableFileCPResolving=true -Dvertx.disableContextTiming=true -Dvertx.disableWebsockets=true -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.SLF4JLogDelegateFactory -cp /opt/graviteeio-gateway-1.26.1/lib/gravitee-gateway-standalone-bootstrap-1.26.1.jar io.gravitee.gateway.standalone.boostrap.Bootstrap

**Comment by jaehong-kim** [comment]
@barrycheng 

1. Do you use Vert.x HTTP Server ?
If Vert.x HTTP Server is not used, it will not be tracked.
2. Do you use a router ?
e.g.
~~~
HttpServer server = vertx.createHttpServer();
Router router = Router.router(vertx);
router.route().handler(routingContext -> {
  // This handler will be called for every request
  HttpServerResponse response = routingContext.response();
  response.putHeader("content-type", "text/plain");

  // Write to the response and end it
  response.end("Hello World from Vert.x-Web!");
});
server.requestHandler(router).listen(8080);
~~~
If you are not using a router, change the settings.
Set the method name of your HttpServerRequestHandler implementation.

**Comment by barrycheng** [comment]
I set the method name, now it works.But it does not show the service being invoked ( Servlet Stack ).

![UAC](https://user-images.githubusercontent.com/8085838/60002995-5a909480-969c-11e9-8e09-348689ce2cd8.png)

**Comment by jaehong-kim** [comment]
@barrycheng 
Which HttpClient is used ?

**Comment by barrycheng** [comment]
@jaehong-kim 
The gravitee depend on org.apache.httpcomponents:httpclient:4.5.7

![HTTP](https://user-images.githubusercontent.com/8085838/60009615-c678fa00-96a8-11e9-8e87-ead8cb1be442.png)

**Comment by jaehong-kim** [comment]
@barrycheng 
Did you set profiler.vertx.handler.base-packages ?

~~~
# Track Vertx.runOnContext() & Vertx.executeBlocking().
# Sets the base packages that implements io.vertx.core.Handler.
profiler.vertx.handler.base-packages=
# e.g. com.service.handler, com.server.http.handler
~~~

**Comment by barrycheng** [comment]
@jaehong-kim
It wasn't set before, but when it was set, nothing changed.
