### ISSUE TITLE
When does HBase2.0  upgrade，

### ISSUE THREAD

**Issue by yanceyZhang** [naver/pinpoint#5705]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

**Comment by RoySRose** [comment]
Hello, @yanceyZhang 

Here is the [guide](http://naver.github.io/pinpoint/hbaseupgrade.html)

It already merged in the master branch. and will be included in v1.9.0 release.
