### ISSUE TITLE
V2 build

### ISSUE THREAD

**Issue by VidushaZ** [naver/pinpoint#5706]
Hi 

To where should I copy build files to affect the changes made in V2 development environment? 
Sorry I am new to Angular. 

Thank You!

**Comment by denzelsN** [comment]
@VidushaZ 
Hi.

You can check in `web/src/main/webapp/v2` folder.

**Comment by VidushaZ** [comment]
@denzelsN 
Yes, I run a build from there and found chunk files in /web/target/deploy/v2 
what I ask is none of these affect when I open V2 from browser http://0.0.0.0:28080/v2 
but the changes are working fine in development which is running on 4200 port default.

**Comment by denzelsN** [comment]
@VidushaZ 
Run command `npm build:watch` in `web/src/main/webapp/v2`.

**Comment by VidushaZ** [comment]
@denzelsN How do I run V2 in production mode? I did a build using build:real and I have no idea where to copy those build files. Plus when I restart the web.sh my changes get revert back. Please help.

**Comment by denzelsN** [comment]
@VidushaZ 
If you build with `-Pv2` option.( mvn clean install -DskipTests -Pv2)
You can access through  `http://yourhost:yourport/v2`

**Comment by VidushaZ** [comment]
@denzels Ah! It works now. Thank you very much. I'm closing this.

**Comment by VidushaZ** [comment]
@denzelsN Hi one more question please. It still says the V2 is running on development mode. How do I get it to production mode?

**Comment by denzelsN** [comment]
@VidushaZ 
What's the development mode? How does it work?

**Comment by VidushaZ** [comment]
@denzelsN In chrome console it says Angular is running in the development mode. I want V2 to run on production mode. is it possible? because in mvn clean install -DskipTests -Pv2, It runs ng build pinpoint --base-href /v2/ without --production

**Comment by denzelsN** [comment]
@VidushaZ 
Okay. I understand what you're saying.
It's not in production mode because it's still under development.
If you want to build in production mode, modify the 530 line `run build` in web/pom.xml file with `run build:real`.

**Comment by VidushaZ** [comment]
Ok I got it Thank you very much.  now I am closing this one.
