### ISSUE TITLE
how to trace queue invocation，such as LinkedBlockingQueue？

### ISSUE THREAD

**Issue by VIPJoey** [naver/pinpoint#5709]
My code just like this。

// make a queue （TraceDataWrapper can pass trace information within my pinpoint plugin.）
private LinkedBlockingQueue<TraceDataWrapper<Person>> queues = new LinkedBlockingQueue<>(100);

// method A , put My Wrapper  Object to the queue
queues.put(TraceDataWrapper.of(person));

// method B ( after spring bean init），fork one thread to deal with the real object
        new Thread(() -> {
            while(true) {
                try {
                    Thread.sleep(1000);
                    Person p = queues.take().value();
                    personDao.save(p); //  this method didn't show in pinpoint web UI.
                } catch (Throwable e) {
                    e.printStackTrace();
                }
            }
        }).start();

I have wrote a plugin of pinpoint, and I am sure that I can get the traceId after the method TraceDataWrapper.value() be invoked，but any information can't be showed in pinpoint web UI, how to trace the next method **personDao.save(p);**  or any idea？

![image](https://user-images.githubusercontent.com/21004236/59670672-e151f700-91ee-11e9-942a-ee5bd1179c64.png)

Look forward to your reply. thanks。

**Comment by emeroad** [comment]
It is recommended to use the ThreadPoolExecutor rather than using the Thread.

Pinpoint already supports TaskExecutor of Spring
Using the TaskExector or referencing the plugin code will help you solve your problem.

https://github.com/naver/pinpoint/blob/master/plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/async/SpringAsyncPlugin.java

https://github.com/naver/pinpoint/blob/master/plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/async/SpringAsyncConfig.java#L29
```java
    private static final String[] DEFAULT_ASYNC_TASK_EXECUTOR = {
            "org.springframework.scheduling.concurrent.ConcurrentTaskExecutor",
            "org.springframework.core.task.SimpleAsyncTaskExecutor",
            "org.springframework.scheduling.quartz.SimpleThreadPoolTaskExecutor",
            "org.springframework.core.task.support.TaskExecutorAdapter",
            "org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor",
            "org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler",
            "org.springframework.jca.work.WorkManagerTaskExecutor",
            "org.springframework.scheduling.commonj.WorkManagerTaskExecutor"
    };
```

**Comment by emeroad** [comment]
Pseudocode
ThreadPoolExecutor actually works like this
```java
    public void dispatch() {
        // method B ( after spring bean init），fork one thread to deal with the real object
        new Thread(() -> {
            while(true) {
                try {
                    Thread.sleep(1000);
                    TraceDataWrapper dataWrapperRunnable = queues.take();
                    // Implement personDao.save() in run()
                    dataWrapperRunnable.run();
                } catch (Throwable e) {
                    e.printStackTrace();
                }
            }
        }).start();


    }

    public class TraceDataWrapper implements Runnable {
        private PersonDao personDao;
        private Person p;

        @Override
        public void run() {
            // asyncContext start
            personDao.save(p); // this method didn't show in pinpoint web UI.
            // asyncContext end
        }
    }
```

**Comment by VIPJoey** [comment]
Thank you for your reply。It seems the best way was to use ThreadPoolExecutor rather than queue before I have found out effective solution。But it will change a lot of code in some projects to abandon  the field LinkedBlockingQueue in my situation。

**Comment by VIPJoey** [comment]
That's so embarrassing, I seem to have misunderstood what you mean. AsyncContext is work for me. I change my code to pass AsyncContext to the dealing thread, it can trace the invocation completely。

My code just like this。

// make a queue （TraceDataWrapper will be use to store the asyncContext.）
private LinkedBlockingQueue<TraceDataWrapper> queues = new LinkedBlockingQueue<>(100);

// method A , put My Wrapper Object to the queue，the method “of” will be intercept
queues.put(TraceDataWrapper.of(person));

// method B ( after spring bean init），fork one thread to deal with the real object
        new Thread(() -> {
            while(true) {
                try {
                    Thread.sleep(1000);
                    // We should wrap the real operation in order to trace the whole invocation 
                    queues.take().run((t) -> {
                        save(t.getName()); // real operation 
                    });
                } catch (Throwable e) {
                    e.printStackTrace();
                }
            }
        }).start();

![image](https://user-images.githubusercontent.com/21004236/59827541-8c87bb00-936b-11e9-86ff-f23f265472a5.png)

It works! Thanks again.

**Comment by emeroad** [comment]
:+1 That's cool.
