### ISSUE TITLE
The chart can not show back when you hide all legend(Min,Avg,Max) in inspect page of new UI.

### ISSUE THREAD

**Issue by messi-gao** [naver/pinpoint#5722]
1.Show normally.
![image](https://user-images.githubusercontent.com/24312100/59829101-1422f900-936f-11e9-86af-459babeeee04.png)

2.Then hide all legend(Min,Avg,Max),then chart can not show back whatever you click any legend.
![image](https://user-images.githubusercontent.com/24312100/59829247-7d0a7100-936f-11e9-92e5-4912f6ad039f.png)

@denzelsN

**Comment by binDongKim** [comment]
@messi-gao We have migrated the chart library from `Chart.js` to `billboard.js` on the inspector page lately and I confirmed there’s no such issue on the current charts so I recommend you to fetch the master(latest) commit and use the feature.

**Comment by messi-gao** [comment]
@binDongKim I think the mater is not a stable version,most people should not use master code,could you fix it by tag 1.8.3?

**Comment by messi-gao** [comment]
@binDongKim

**Comment by messi-gao** [comment]
@binDongKim

**Comment by binDongKim** [comment]
I've inspected this issue and found out it would require quite a lot of resources to handle it. And as I stated above, since it's already resolved with a new library and we are planning on shipping it on 1.9.0 version, hope you enjoy the feature fully with it. Sorry for your inconvenience.
