### ISSUE TITLE
which version support Alarm mail functions? 1.7 or 1.8 ?

### ISSUE THREAD

**Issue by tanrui988** [naver/pinpoint#5735]
now i'm using 1.7 ,but i can't implement mail notification.  thanks.

**Comment by RoySRose** [comment]
If you are trying to set the alarms. You need to follow the instruction in the documents of the specific version.

please check the version of the document
![image](https://user-images.githubusercontent.com/20402016/60087271-a82dff80-9777-11e9-96bb-345688a87419.png)
