### ISSUE TITLE
someone can help provide new maven repository for 1.9.0-SNAPSHOT? thanks

### ISSUE THREAD

**Issue by tanrui988** [naver/pinpoint#5742]
i can't download dependencies .

<parent>
        <groupId>com.navercorp.pinpoint</groupId>
        <artifactId>pinpoint</artifactId>
        <version>1.9.0-SNAPSHOT</version>
    </parent>

**Comment by Xylus** [comment]
Hi @tanrui988 
Pinpoint isn't uploaded to maven central as it isn't meant to be used as a library/dependency.
May I ask what you're trying to do? It would help us help you better.

**Comment by tanrui988** [comment]
mistake.sorry.
