### ISSUE TITLE
add plugins ,take issue:java.lang.IllegalArgumentException: schema not equals

### ISSUE THREAD

**Issue by xiaojinde** [naver/pinpoint#5747]
add kafka plugins,servicetype： ServiceTypeFactory.of(8998, "CAMEL_SERVICE");
send trace successfully!but through web look,take error:
schema not equals. this=TimeHistogram{timeStamp=1561544100000, Histogram{schema={typeCode=1, fastSlot=HistogramSlot{slotTime=100, slotType=FAST, slotName='100ms'}, normalSlot=HistogramSlot{slotTime=300, slotType=NORMAL, slotName='300ms'}, slowSlot=HistogramSlot{slotTime=500, slotType=SLOW, slotName='500ms'}, verySlowSlot=HistogramSlot{slotTime=0, slotType=VERY_SLOW, slotName='Slow'}, errorSlot=HistogramSlot{slotTime=-1, slotType=ERROR, slotName='Error'}, fastErrorSlot=HistogramSlot{slotTime=-100, slotType=FAST_ERROR, slotName='100ms'}, normalErrorSlot=HistogramSlot{slotTime=-300, slotType=NORMAL_ERROR, slotName='300ms'}, slowErrorSlot=HistogramSlot{slotTime=-500, slotType=SLOW_ERROR, slotName='500ms'}, verySlowErrorSlot=HistogramSlot{slotTime=-999, slotType=VERY_SLOW_ERROR, slotName='Slow'}}, fastCount=0, normalCount=0, slowCount=0, verySlowCount=0, errorCount=0, fastErrorCount=0, normalErrorCount=0, slowErrorCount=0, verySlowErrorCount=0}}, histogram=TimeHistogram{timeStamp=1561544100000, Histogram{schema={typeCode=2, fastSlot=HistogramSlot{slotTime=1000, slotType=FAST, slotName='1s'}, normalSlot=HistogramSlot{slotTime=3000, slotType=NORMAL, slotName='3s'}, slowSlot=HistogramSlot{slotTime=5000, slotType=SLOW, slotName='5s'}, verySlowSlot=HistogramSlot{slotTime=0, slotType=VERY_SLOW, slotName='Slow'}, errorSlot=HistogramSlot{slotTime=-1, slotType=ERROR, slotName='Error'}, fastErrorSlot=HistogramSlot{slotTime=-1000, slotType=FAST_ERROR, slotName='1s'}, normalErrorSlot=HistogramSlot{slotTime=-3000, slotType=NORMAL_ERROR, slotName='3s'}, slowErrorSlot=HistogramSlot{slotTime=-5000, slotType=SLOW_ERROR, slotName='5s'}, verySlowErrorSlot=HistogramSlot{slotTime=-9999, slotType=VERY_SLOW_ERROR, slotName='Slow'}}, fastCount=0, normalCount=0, slowCount=0, verySlowCount=1, errorCount=0, fastErrorCount=0, normalErrorCount=0, slowErrorCount=0, verySlowErrorCount=0}}

at com.navercorp.pinpoint.web.applicationmap.histogram.Histogram.add(Histogram.java:204)
        at com.navercorp.pinpoint.web.applicationmap.rawdata.LinkCallData.addCallData(LinkCallData.java:90)
        at com.navercorp.pinpoint.web.applicationmap.rawdata.LinkCallDataMap.addCallData(LinkCallDataMap.java:53)
        at com.navercorp.pinpoint.web.service.map.VirtualLinkHandler.fillEmulationLink(VirtualLinkHandler.java:152)
        at com.navercorp.pinpoint.web.service.map.VirtualLinkHandler.processVirtualLinks(VirtualLinkHandler.java:78)
        at com.navercorp.pinpoint.web.service.map.UnidirectionalLinkSelector.select(UnidirectionalLinkSelector.java:94)
        at com.navercorp.pinpoint.web.service.MapServiceImpl.selectApplicationMap(MapServiceImpl.java:106)
        at com.navercorp.pinpoint.web.controller.MapController.selectApplicationMap(MapController.java:218)

please help me !

**Comment by emeroad** [comment]
Dynamic changes of the histogram schema are not recommended.
```
Histogram{schema={typeCode=1,
Histogram{schema={typeCode=2, 
```
The typeCode of the histogram must be the same.

It looks like you have dynamically changed the schema, or you have some old data. 
Clear your historical data.

**Comment by xiaojinde** [comment]
scan 'HostApplicationMap_Ver2'; when invoke kafka ,it can dynamic add data to this table.but i don't add code to add the application.where can auto add application? I use 'FrameObject',will it bring impact?
the add data:
\x02jianrongtest05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x column=M:\x1C127.0.0.1:9092\x1C127.0.0.1:9092!\xD4, timestamp=1561606124008, value=                                                                                               
 03\xF2\x7F\xFF\xFE\x94i\x069\xFF                                                                                                                                                                                                               
 \x02jianrongtest05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x column=M:\x1C127.0.0.1:9092\x1Cjianrongtest02\x03\xF2, timestamp=1561606124008, value=                                                                                            
 03\xF2\x7F\xFF\xFE\x94i\x069\xFF

the code:
  SpanEventRecorder recorder = trace.traceBlockBegin();
                recorder.recordServiceType(8998);
                TraceId nextId = trace.getTraceId().getNextTraceId();
                recorder.recordNextSpanId(nextId.getSpanId());
                recorder.attachFrameObject(KafkaConstants.CAMEL_KAFKA_FLAG);
.......
   String flag = (String)trace.currentSpanEventRecorder().getFrameObject();
            if(KafkaConstants.CAMEL_KAFKA_FLAG.equalsIgnoreCase(flag)){
                return;
            }

**Comment by xiaojinde** [comment]
please help look

**Comment by emeroad** [comment]
`attachFrameObject()` does not affect the histogram.

The histogram schma is automatically selected by the serviceCode.
 - https://github.com/naver/pinpoint/blob/master/commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceTypeCategory.java#L30

`CACHE_LIBRARY`(8000 ~ 8999) uses FAST_SCHEMA, and histogram statistics are automatically generated from the collector.

The histogram data is generated by Span.
- https://github.com/naver/pinpoint/blob/master/collector/src/main/java/com/navercorp/pinpoint/collector/service/TraceService.java#L74
```java
            /*
             * save information to draw a server map based on statistics
             */
            // save the information of caller (the spanevent that called span)
            statisticsService.updateCaller(applicationId, applicationServiceType, agentId, spanEventApplicationName, spanEventType, spanEventEndPoint, elapsed, hasException);

            // save the information of callee (the span that spanevent called)
            statisticsService.updateCallee(spanEventApplicationName, spanEventType, applicationId, applicationServiceType, endPoint, elapsed, hasException);
        }
````
I'm not sure what the problem is.
Please debug the above source code

**Comment by xiaojinde** [comment]
Thank you .we delete the code,can work normally.i don't know if there are any problems?

< /* if (this.schema != histogram.schema) {
            throw new IllegalArgumentException("schema not equals. this=" + this + ", histogram=" + histogram);

        }*/>
