### ISSUE TITLE
The show of full GC of in new UI is incorrect.

### ISSUE THREAD

**Issue by messi-gao** [naver/pinpoint#5751]
The same data show in old UI and new UI:

Old UI:
![image](https://user-images.githubusercontent.com/24312100/60251843-e2c0a500-98fb-11e9-9101-097464423489.png)

new UI:
![image](https://user-images.githubusercontent.com/24312100/60251892-f704a200-98fb-11e9-8f4f-d1711f51b35e.png)

in new UI,the time of full gc is incorrect.

@denzelsN

**Comment by messi-gao** [comment]
@binDongKim Could you look up this issure?

**Comment by binDongKim** [comment]
@messi-gao I’ll look into it in a couple days.

**Comment by messi-gao** [comment]
@binDongKim

**Comment by binDongKim** [comment]
I've inspected this issue and found out there's no difference in implementation between the old UI and the new one so there shouldn't be any incorrection on rendering. Plus, there has been a big change on the inspector chart codes so I highly recommend you to use the latest one. Thanks.

**Comment by messi-gao** [comment]
@binDongKim
