### ISSUE TITLE
how to avoid tracing some static resources url

### ISSUE THREAD

**Issue by zhangxing1990** [naver/pinpoint#5758]
Hello.
I'm wondering that how to avoid tracing some url,such as **.css,**.js and so on.It is no necessary to trace static resources url in my cases.
Could u tell me how to do it?Thanks.

**Comment by emeroad** [comment]
@zhangxing1990 hi
https://github.com/naver/pinpoint/blob/master/agent/src/main/resources-local/pinpoint.config#L230
```
# URLs to exclude from tracing.
# Support ant style pattern. e.g. /aa/*.html, /??/exclude.html
profiler.tomcat.excludeurl=/aa/test.html, /bb/exclude.html
```
Use the profiler.xxxx.excludeurl option
