### ISSUE TITLE
Open discussions for openhouse

### ISSUE THREAD

**Issue by koo-taejin** [naver/pinpoint#5778]
## Topic 1. How to enable even more collection of data 
How to enable even more collection of data (more tags, more logs) for debugging a prod issue without new code or new deploy.    --- by  José Carlos Chávez

<br><br>
## Topic 2. Sampling Rate & Target

Pinpoint applies the same sampling rate for all requests.
If there is an application which has request frequency as below, there will be difficulties in tracking the most problematic request.

Request Type | Number of Request | Sampling Rate | Probability of Problem
----|-----|-----|-----
requestA | 70000 |  1%   | 0.0002% 
requestB |    5000 |  1% | 0.0002%
reuqestC |    2000 |  1% | 0.5%
requestD | 10 |  1% | 2%

n this case, the most needed information for the user would be requestD.
I would like to discuss whether we can take care of this problem.

<br><br>
## Topic 3. How to manage Plugins

With more plug-ins, management costs are increasing in the following reasons. 

1. Check for new versions of support and  compatibility
2. Change and add core api
3. Increasing test time 

I think it would be nice to share how you manage it, and discuss any difficulties you may have.

<br><br>
## Topic 4. How to trace message queue. 

Distributed tracing of message queue differs from previous. (especially Kafka)

#### Client Side
```
// general form 
Client -----> Server (TraceA)  -> Trace

// kafka form
send message -> kafka server -> (Unknown target)
                               -> (Unknown target)
                               -> (Unknown target)
                               -> (Unknown target)
                               .. can't predict how many.

```
 talk about 
1. How can I conclude that the transaction is the end?
2. how to show it. (show all, ↓visible, show some  ↓lost info )

#### Server Side
```
// general form 
------> Server. (start trace)

// kafka form
               poll multi messages
kafka server <--------------  (message1,message2,message3,message4,e..)

```
talk about
1.  which message do we have trace ?
2.  In this case, how do show them for client side and server side?

**Comment by jcchavezs** [comment]
Regarding point 2, have a look at https://people.mpi-sws.org/~jcmace/papers/lascasas2018weighted.pdf

**Comment by RoySRose** [comment]
@jcchavezs please share the link :)

**Comment by koo-taejin** [comment]
@jcchavezs thanks for you're sharing :)
