### ISSUE TITLE
I can't start collector with error message "Apache Maven (mvn) required."

### ISSUE THREAD

**Issue by eungmo** [naver/pinpoint#5780]
#### Environment

* Pinpoint version: 1.8.4
* OS, WAS, affected library, etc: Windows 10 pro x64, HBase 1.2.6
* Additional details (e.g. how your collector/web is set up):

#### Additional Info

I followed "Quick Start Guid" from the README.md
(https://naver.github.io/pinpoint/quickstart.html#start-pinpoint-daemons)

I installed Hbase very well and initialize tables with 2 commends.
And then, I tried to execute 'collector'.

- quickstart\bin\start-collector.cmd

but it provides an error message "Apache Maven (mvn) required."
As a result, quickstart.cmd try to find "..\\..\mvnw.cmd".
And the file is exist.

And I installed Apache Maven in my computer, but it provides the same error message.

Can anybody check this issue?
Or, do I have to install Pinpoint in Linux?

**Comment by RoySRose** [comment]
Please check Maven installation or installed directory on 
> "Apache Maven (mvn) required."

and..
No, Pinpoint does not only have to be installed from Linux.

**Comment by eungmo** [comment]
I passed the issue.

Previously I command it at the project location like 'C:\Users\xxxx\pinpoint-1.8.4\pinpoint-1.8.4'.
And the command was 'quickstart\bin\start-collector.cmd'.

It's works after I just command 'start-collector.cmd' at the location 'C:\Users\xxxx\pinpoint-1.8.4\pinpoint-1.8.4\quickstart\bin'.

**Comment by RoySRose** [comment]
great :)
