### ISSUE TITLE
I cannot execute collector

### ISSUE THREAD

**Issue by eungmo** [naver/pinpoint#5783]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
v1.8.4 release

#### Describe your problem**
I tried execute collector, but the new cmd window is automaticlly closed.

#### What have you done?
Basically, I followed the 'Quick Start Guide' from README.md.
1. Downloaded pinpoint from the github release page.
2. And, downloaded again the hbase 1.2.6
3. Extract and rename the hbase.
4. Put the directory like 'quickstart\hbase\hbase'
5. add environment value 'C:\Windows\System32\wbem' to path
6. Open cmd as administrator cd C:\Users\user\pinpoint-1.8.4
7. quickstart\bin\start-hbase.cmd
8. quickstart\bin\init-hbase.cmd
9. cd quickstart\bin
10. start-collector.cmd

#### Logs
If applicable, please attach agent/collector/web DEBUG log that includes the part where you have encountered the problem. In case of agents, including the start-up log may be of great help.

#### Additional context
Add any other context about the problem here, such as affected library for agents, how your collector/web/hbase is set up if applicable.
[quickstart.collector.log](https://github.com/naver/pinpoint/files/3391133/quickstart.collector.log)

Just my OS is Windows 10 Pro x64.
And, I have enough resources such as CPU, RAM, Disk.

**Comment by RoySRose** [comment]
```
[INFO] --------------------------------[ war ]---------------------------------
[WARNING] The POM for com.navercorp.pinpoint:pinpoint-collector:war:1.8.4 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.843 s
[INFO] Finished at: 2019-07-15T15:54:39+09:00
[INFO] ------------------------------------------------------------------------
```

looks like WAR is missing.
