### ISSUE TITLE
manual query to pinpoint hbase

### ISSUE THREAD

**Issue by harissutanrafiq** [naver/pinpoint#5790]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

sometime i need search string for all transaction

iam using ponpoint docker, and modify docker-compose.yml

`#zookeepers
  zoo1:
    image: zookeeper:3.4
    ports:
      - 2188:2181
    restart: always
    hostname: zoo1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - pinpoint

  zoo2:
    image: zookeeper:3.4
    restart: always
    hostname: zoo2
    ports:
      - 2189:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
    networks:
      - pinpoint

  zoo3:
    image: zookeeper:3.4
    restart: always
    hostname: zoo3
    ports:
      - 2199:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
    networks:
      - pinpoint`

i try connect to pinpoint hbase using simple python

`import hbase

zk = 'localhost:2188,localhost:2189,localhost:2199'

if __name__ == '__main__':
    with hbase.ConnectionPool(zk).connect() as conn:
        table = conn['AgentInfo']['Info']
        for row in table.scan():
            print(row)
    exit()`

and throw error

File "hbase_py.py", line 6, in <module>
    with hbase.ConnectionPool(zk).connect() as conn:
  File "/usr/local/lib/python3.4/dist-packages/hbase/connection.py", line 258, in connect
    return Connection(self._on_conn_close, self._zkquorum)
  File "/usr/local/lib/python3.4/dist-packages/hbase/connection.py", line 89, in __init__
    self._client = client.Client(zkquorum)
  File "/usr/local/lib/python3.4/dist-packages/hbase/client/client.py", line 145, in __init__
    self._master_service = services.MasterService(zkquorum)
  File "/usr/local/lib/python3.4/dist-packages/hbase/services/services.py", line 86, in __init__
    super(MasterService, self).__init__(None, None)
  File "/usr/local/lib/python3.4/dist-packages/hbase/services/services.py", line 32, in __init__
    self._rebuild_request()
  File "/usr/local/lib/python3.4/dist-packages/hbase/services/services.py", line 89, in _rebuild_request
    self._host, self._port = zookeeper.get_master(self._zkquorum)
  File "/usr/local/lib/python3.4/dist-packages/hbase/services/zookeeper.py", line 40, in get_master
    return _get_address(zkquorum, PATH_MASTER, timeout, retries)
  File "/usr/local/lib/python3.4/dist-packages/hbase/services/zookeeper.py", line 99, in _get_address
    'ZooKeeper does not contain a %s node.' % path
hbase.exceptions.NoSuchZookeeperNodeError: ZooKeeper does not contain a /hbase/master node.

any suggestion, how i can connect to hbase. and maybe on next release version we can search string from all transaction

thanks

**Comment by RoySRose** [comment]
Hello, @harissutanrafiq 

We don't use any query to access hbase.
I know there are several users who would like to use a similar function as this.
But currently, there isn't any. 

If you get to know an easy way for this. Please share with the community

**Comment by emeroad** [comment]
Direct access to the hbase is not recommended.
Reasons for this
1. The data stored in the hbase is binary. Reading data requires complex decoding.
2. Specifications of binaryformat may change in the future
3. Hbase has the advantage of scalability, but its query capability is poor, so there will be very little that can be done through queries.

## Recommended Architecture
1. Flink layer
- Works with the search engine (such as ES) on the flink.
- Create search index in flink and save it in search engine
2. Collector layer
- Works with the search engine in the collector.
- The structure is similar to the flink module.
- Advantage : simplie
- Disadvantage  : The collector does not provide distributed stream processing, So search engines need to store more data, or they need more processing power.
