### ISSUE TITLE
want to see all kafka consumers's link

### ISSUE THREAD

**Issue by xiaojinde** [naver/pinpoint#5793]
hi, i have a problem, please help me!
when more kafka consumers to consumer the same topic message,the pinpoint web only show one consumer.how to let show all consumers's link?

**Comment by koo-taejin** [comment]
hi @xiaojinde 

Please explain in detail. 

```
ex)
environment you're system (with or without pinpoint on each server)
current server map image, expected serve map image 
agent log that can show kafka node, agent log that can't show kafka node
etc ..
``` 

Please post the detailed description.

**Comment by koo-taejin** [comment]
@xiaojinde 

There is a lack of support for queue service such as kafka. 
In particular, if the message goes to multiple consumers, 
it can may not be all traced due to the problem of internal structure.

If you  post the detailed description. then i can check more detail 

thanks.

**Comment by xiaojinde** [comment]
@koo-taejin
![this is kafka link](https://user-images.githubusercontent.com/21004236/61452660-e42b3d80-a98e-11e9-9c08-71db29c1d94d.png)
the topic of kafka_ppoint_test,have two kafka consumers ,jianrongtest05 and jianrongtest02,but it only show the jianrongtest05.please look how to show two consumers

**Comment by koo-taejin** [comment]
@xiaojinde 

I succeeded in reproducing the problem.
I am looking for a way to resolve it.
If any progress, then I will post comment .

thanks.

**Comment by xiaojinde** [comment]
@koo-taejin

ok, thanks!

**Comment by koo-taejin** [comment]
@xiaojinde 

I did the work and the related issue is #5807  

Please test it when it becomes Merge in the master branch.

**Comment by xiaojinde** [comment]
@koo-taejin
ok,thank you.
i have modified this issue.we can share the solution.
