### ISSUE TITLE
Proposal to remove com.sun:tools dependencies

### ISSUE THREAD

**Issue by gwagdalf** [naver/pinpoint#5797]
**Which module is your feature request related to?**
pinpoint-jboss-plugin

**Is your feature request related to a problem?**
Among the modules of pinpoint, pinpoint-jboss-plugin has a dependency on com.sun.tools with the following dependency.
```
pinpoint-jboss-plugin
  org.jboss.as:jboss-as-security:7.2.0.Final
   org.jboss.as:jboss-as-clustering-infinispan:7.2.0.Final
     com.sun: tools: 1.6
```

**Describe the solution you'd like**
My company is using zulu jdk as a java license issue.
Since zulu jdk doesn't support the com.sun.~ module, I am building pinpoint by manually removing it.

Other open sources doesn't use com.sun module for license problem.
I suggest that Pinpoint also removes com.sun.tools dependency.

At least for future support of the java 11 version, I hope this issue is addressed.

**Additional context**
We can also see the following comments in the zipkin source code.

https://github.com/openzipkin/zipkin/blob/78e7edcb844d9e61696a76587e7cb023054c5261/pom.xml#L413
`<!-- or die! com.sun.tools.javac.api.JavacTool -->`

I'd like you to consider it again.

**Comment by emeroad** [comment]
```
[INFO] com.navercorp.pinpoint:pinpoint-jboss-plugin:jar:1.9.0-SNAPSHOT
[INFO] +- com.navercorp.pinpoint:pinpoint-bootstrap-core:jar:1.9.0-SNAPSHOT:provided <-- all provided scope
[INFO] |  +- com.navercorp.pinpoint:pinpoint-annotations:jar:1.9.0-SNAPSHOT:provided
[INFO] |  \- com.navercorp.pinpoint:pinpoint-commons:jar:1.9.0-SNAPSHOT:provided
[INFO] +- org.jboss.as:jboss-as-security:jar:7.2.0.Final:provided
[INFO] |  +- org.jboss.msc:jboss-msc:jar:1.0.4.GA:provided
[INFO] |  +- org.jboss.as:jboss-as-domain-management:jar:7.2.0.Final:provided
[INFO] |  |  +- org.jboss:jboss-common-core:jar:2.2.17.GA:provided
[INFO] |  |  +- org.jboss.as:jboss-as-controller:jar:7.2.0.Final:provided
[INFO] |  |  |  +- org.jboss.as:jboss-as-controller-client:jar:7.2.0.Final:provided
[INFO] |  |  |  \- org.jboss:staxmapper:jar:1.1.0.Final:provided
[INFO] |  |  \- org.jboss:jboss-dmr:jar:1.1.6.Final:provided
[INFO] |  +- org.jboss.as:jboss-as-server:jar:7.2.0.Final:provided
[INFO] |  |  +- org.jboss.as:jboss-as-domain-http-interface:jar:7.2.0.Final:provided
[INFO] |  |  |  \- org.jboss.com.sun.httpserver:httpserver:jar:1.0.1.Final:provided
[INFO] |  |  +- org.jboss.as:jboss-as-deployment-repository:jar:7.2.0.Final:provided
[INFO] |  |  |  \- org.jboss.as:jboss-as-protocol:jar:7.2.0.Final:provided
[INFO] |  |  |     \- org.jboss.xnio:xnio-nio:jar:3.0.7.GA:provided
[INFO] |  |  +- org.jboss.as:jboss-as-platform-mbean:jar:7.2.0.Final:provided
[INFO] |  |  +- org.jboss.as:jboss-as-process-controller:jar:7.2.0.Final:provided
[INFO] |  |  |  \- system:jdk-tools:jar:jdk:system   <--- system scope
```

The maven-scope of jdk-tools is in use of the system scope, so there is no problem.

1. pinpoint-jboss-plugin does not include or refer to jdk-tools.
2. All dependencies of pinpoint-jboss-plugin use provided-scope and required only for compilation.
For these reasons, I don't know if I should fix this problem.

Are jboss-plugin compilation not working in zulu jdk?
If you have an error log, please attach it.

**Comment by gwagdalf** [comment]
First of all, thank you for your quick reply.

When I come to work on Monday, 
I will contact if there is no license problem with provided scope usage.

**Comment by gwagdalf** [comment]
Since com.sun: tools module is not included in azul zulu JDK, I misunderstood as commercial licenses.

However  I find it is a GPL 2.0 License.
https://mvnrepository.com/artifact/com.sun/tools/1.7.0.13

The misunderstanding is resolved and I'm closing issue.
