### ISSUE TITLE
Real time No of Requests in High level c

### ISSUE THREAD

**Issue by VidushaZ** [naver/pinpoint#5802]
Hi,

Is it possible to see realtime No of requests in High level connectivity diagram when it's on Realtime mode?

Also I have another question on V2 where I can't see update option (refresh page). Is it under development or have a better way?

Regards!

**Comment by RoySRose** [comment]
Helloo, @VidushaZ 

You can check out what you can see with 'RealTime' from [live demo](http://125.209.240.10:10123/).

and [here is the guide](https://naver.github.io/pinpoint/ui_v2.html) showing you how you can change it to V2

**Comment by VidushaZ** [comment]
@RoySRose Hii,

Yes I already checked it and even in live demo It's not counting realtime requests on the Flow diagram. What I asked is whether it is possible to do it. 
Regarding V2 yes I already have running V2 but there is no update option there. btw Is there a live demo for V2?

**Comment by RoySRose** [comment]
>Yes I already checked it and even in live demo It's not counting realtime requests on the Flow diagram. What I asked is whether it is possible to do it.

What is Flow diagram? We don't use the term `Flow Diagram`. Please let me know what you are trying to point to.

> Regarding V2 yes I already have running V2 but there is no update option there.

what do you mean by update option?

> btw Is there a live demo for V2?

We are planning to change the demo to V2, but yet there are few bugs in V2, so we're waiting

**Comment by RoySRose** [comment]
@VidushaZ

>Yes I already checked it and even in live demo It's not counting realtime requests on the Flow diagram. What I asked is whether it is possible to do it.

What is Flow diagram? We don't use the term `Flow Diagram`. Please let me know what you are trying to point to.

> Regarding V2 yes I already have running V2 but there is no update option there.

what do you mean by update option?

> btw Is there a live demo for V2?

We are planning to change the demo to V2, but yet there are few bugs in V2, so we're waiting

**Comment by VidushaZ** [comment]
![image](https://user-images.githubusercontent.com/34154568/61768779-0c3ef480-ae06-11e9-8def-0d7fa993ff3f.png)

^Flow Diagram I mentioned 
I asked is it possible to see these numbers change in real time mode.  

![image](https://user-images.githubusercontent.com/34154568/61768881-46a89180-ae06-11e9-9c35-8ccb444972ce.png)

^I can't see this option in V2.

**Comment by RoySRose** [comment]
Oh, the `servermap`. `servermap` is the term we use.
Well, if you select `REALTIME` and the servermap will show you the number of transaction in other charts. But will NOT update on the `servermap` due to some issues.
@binDongKim, may be working on some solution on this.

@binDongKim 
Can you check above `update` option for v2?
