### ISSUE TITLE
set profiler.enable=false is not working

### ISSUE THREAD

**Issue by miqi770** [naver/pinpoint#5809]
as I understand it, this config will disable all pinpoint-agent function, right?
but I go through the DefaultProfilerConfig class there is no reference of isProfileEnable() method in it.

So this is a new feature which is not implemented yet, right ?

BTW, I'm using pinpoint 1.8.3 version

**Comment by RoySRose** [comment]
@miqi770

Looking at the history, it's not like a new feature which is not implemented yet.
It looks like it's a feature that was removed.

When I think about it. What's the use of Pinpoint-agent, if it's not instrumenting anything.

**Comment by miqi770** [comment]
@RoySRose 
OK, I got it that, if somone want to disable pinpoint-agent , just do NOT config -javaagent parameter~~~

**Comment by RoySRose** [comment]
@miqi770 

Yes, I think that would be best for now.
