### ISSUE TITLE
Is there a document telling which version of plugin jar that pinpoint support

### ISSUE THREAD

**Issue by zlp1992** [naver/pinpoint#5813]
Like rabbitmq plugin, which version of rabbitmq client can pinpoint support?  Same as tomcat and other plugin

**Comment by koo-taejin** [comment]
hi @zlp1992 

You could see to support version each plugin in this [link](https://github.com/naver/pinpoint/blob/master/doc/modules.md).

thanks.  :)

**Comment by zlp1992** [comment]
cool
