### ISSUE TITLE
MongoDB not support 

### ISSUE THREAD

**Issue by 1298391314** [naver/pinpoint#5817]
#### Prerequisites
pinpoint version is v1.8.4 , and the java driver info as below :
spring-data-mongodb:1.10.9
mongo-java-driver:3.4.3

but it didn't work

![image](https://user-images.githubusercontent.com/10303010/62263337-6ebf7280-b44e-11e9-83d0-dce16b5f3fed.png)

**Comment by RoySRose** [comment]
@1298391314 

Didn't see this issue.
I don't have time to take a deep dive into this.
Take a look at below issues.

https://github.com/naver/pinpoint/pull/5435
https://github.com/naver/pinpoint/issues/5578
