### ISSUE TITLE
Is the new web ui (Angular Framework used) finished

### ISSUE THREAD

**Issue by promise06** [naver/pinpoint#5821]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

**Comment by Xylus** [comment]
Hi @promise06 
I think it's still under development, but usable.
You can give it a try if you'd like - http://naver.github.io/pinpoint/ui_v2.html
