### ISSUE TITLE
Memory leak after long run

### ISSUE THREAD

**Issue by vector090** [naver/pinpoint#5823]
- [v] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
1.8.3

#### Describe the bug
Memory slowly accumulates and does not shrink by GC, which is more obvious when application runs over a month.

#### What did you do to trigger the bug?
Keep application running for over a month, and observe its JVM usage.

#### Expected behavior
GC should fully reclaim heap memory.

#### Screenshots

![image2019-8-2_13-49-6](https://user-images.githubusercontent.com/3281148/62349965-d8fe1300-b533-11e9-8c81-c0d5cce0690b.png)

#### Logs
N/A

#### Additional context
Memory Analyzer shows a great amount of DelayedShutdownHook introduced by Pinpoint-shutdown-hook.

**Comment by emeroad** [comment]
@vector090 Hi~
Could you give me a heap-dump?
 - mail : wd.kang@navercorp.com

**Comment by vector090** [comment]
> @vector090 Hi~
> Could you provide me a heap-dump?
> 
> * mail : [wd.kang@navercorp.com](mailto:wd.kang@navercorp.com)

One moment please

**Comment by vector090** [comment]
> @vector090 Hi~
> Could you provide me a heap-dump?
> 
> * mail : [wd.kang@navercorp.com](mailto:wd.kang@navercorp.com)

Sent. Please kindly check.

**Comment by emeroad** [comment]
In my opinion, this is not the pinpoint bug.
The thread of the pinpoint has a pinpoint-xxx prefix.
![image](https://user-images.githubusercontent.com/7564547/62354025-e2dd4180-b546-11e9-9b0d-de2a82876e38.png)

`DelayedShutdownHook-for-java.util.concurrent.Executors$DelegatedExecutorService` 
This thread is created by MoreExecutors in guava.
https://github.com/google/guava/blob/master/guava/src/com/google/common/util/concurrent/MoreExecutors.java#L263

It seems to be an executors leak of application, so check your code.

**Comment by vector090** [comment]
Working on it.

**Comment by vector090** [comment]
The root cause should should be elastic-job 2.0.0 
Thanks.
