### ISSUE TITLE
SpanDecoderV0 getting negative values for firstSpanEventSequence

### ISSUE THREAD

**Issue by Lobo75** [naver/pinpoint#5840]
I have a tomcat instance running and I'm seeing a lot of IllegalStateExceptions "sequence overflow agentId" when looking at the traces.  It's being caused by firstSpanEventSequence having a negative value at line 403 in SpanDecoderV0.java

Looking for some help to determine what would cause the firstSpanEventSequence to have that negative value.  See the attachment for the full error. 

Pinpoint Version:

Agent, collector 1.9.0-SNAPSHOT
hbase-2.1.5
flink-1.8.0

Running on REHL 7.x
Collector is on tomcat 9.0.20

All components, collector, flink, hbase run on one server.  Tomcat instance with the agent is on a different server.

Not every collected trace has  the issue.  I do not know at this time what to do to recreate it on demand but more than half of them have the error.

[PinpointSpanError.txt](https://github.com/naver/pinpoint/files/3477574/PinpointSpanError.txt)

Thanks.

**Comment by Xylus** [comment]
Hi @Lobo75 
Could you post DEBUG logs for **agent** and **collector** for the traces that resulted in sequence overflow?
(Please send them to hyungil.jeong@navercorp.com instead if you prefer)

The log4j.xml for the agent is in `$PINPOINT_AGENT/lib` directory.
Thanks

**Comment by emeroad** [comment]
If there are too many SpanEvent, the sequence may overflow.
In case of sequence overflow, Pinpoint discards SpanEvent.

1. Reduce the number of APIs to track.
2. Check out the code below.
 - https://github.com/naver/pinpoint/blob/master/collector/src/main/java/com/navercorp/pinpoint/collector/dao/hbase/filter/SequenceSpanEventFilter.java#L52
 - https://github.com/naver/pinpoint/blob/master/commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/grpc/GrpcSpanFactory.java#L310

**Comment by Lobo75** [comment]
@Xylus I will directly email the debug logs to you.  Thanks.

I am aggressively tracing an application and will back off the number if items I am tracking.  Thank you for pointing me to those two code samples, I will have a look at them.

**Comment by Xylus** [comment]
@Lobo75 Thanks for the log.
As @emeroad said, the sequence is overflowing.
Sequence is a **short** so it can overflow if there's too many span events.

Might want to reduce what you're tracing as that many span events will be hard to navigate through even if they're shown properly in the UI.
Thanks.

**Comment by Lobo75** [comment]
I will reduce the number of items traced.  Thanks for  your help.
