### ISSUE TITLE
The error of agent monitors HBase plugin

### ISSUE THREAD

**Issue by ZhibingYu** [naver/pinpoint#5848]
my agent version is v1.8.4。java version is 1.8。mosts of time the agent run in the right way。but my project got an error  when agent monitors HBase plugin ，the agent thrown an excepton like this：
java.lang.LinkageError: loader constraint violation: when resolving interface method "com.navercorp.pinpoint.bootstrap.context.SpanEventRecorder.recordServiceType(Lcom/navercorp/pinpoint/common/trace/ServiceType;)V" the class loader (instance of org/apache/catalina/loader/WebappClassLoader) of the current class, com/navercorp/pinpoint/plugin/hbase/interceptor/HbaseTableMethodInterceptor, and the class loader (instance of <bootloader>) for the method's defining class, com/navercorp/pinpoint/bootstrap/context/SpanEventRecorder, have different Class objects for the type com/navercorp/pinpoint/common/trace/ServiceType used in the signatureat com.navercorp.pinpoint.plugin.hbase.interceptor.HbaseTableMethodInterceptor.doInBeforeTrace(HbaseTableMethodInterceptor.java:54)

I'm looking forward to your help

**Comment by emeroad** [comment]
There is not enough information to debug.

I need the below information for debug.
1. Full stack trace (do not omit the middle)
2. Tomcat version
3. Jdk version
4. hbase client version
5. pinpoint log file

**Comment by ZhibingYu** [comment]
1、Full stack trace see pinpoint log file
2、Tomcat version：8.0.36
3、jdk version: jdk 1.8.0_151
4、hbase client version：1.2.6.1
[ppwebIns20190617-pinpoint.log](https://github.com/naver/pinpoint/files/3490971/ppwebIns20190617-pinpoint.log)

**Comment by emeroad** [comment]
If you install the pinpoint on the pinpoint-web
you must use the same version

Because the pinpoint and the pinpoint-web share API & LIB.
You must use the same version to avoid problems.

**Comment by emeroad** [comment]
#6011
