### ISSUE TITLE
call stack lost part of method call

### ISSUE THREAD

**Issue by magichan** [naver/pinpoint#5855]
## What version of pinpoint are you using?
v1.7.5

#### Describe the bug

the call stack of pinpoint don't match the actual code. some method in the project never show up in the call stack even it it on the software running logic and code.

#### What did you do to trigger the bug?

1. run JPetStore with pinpoint,  [JpetStore repo](https://github.com/mybatis/jpetstore-6/) and the [my change](https://github.com/magichan/JPetStore-PinPoint) for running pinpoint 

2. add item to cart, one operation of JPetStore.
![image](https://user-images.githubusercontent.com/9430353/62834918-348f7580-bc85-11e9-9f74-3e4ddb7b8046.png)

3. call stack of the operation 

![image](https://user-images.githubusercontent.com/9430353/62834957-92bc5880-bc85-11e9-9032-3aabd9efa227.png)

At first, I think it is right, but after checking it, I find the call of `cart.containsItemId(..)` and `cart.addItem(....)` is missing, compared with the [code](https://github.com/magichan/JPetStore-PinPoint/blob/378bcb0d7498848951fa362bb027373258abd51a/src/main/java/org/mybatis/jpetstore/web/actions/CartActionBean.java#L68) of this operation. 
```java
  public Resolution addItemToCart() {
    if (cart.containsItemId(workingItemId)) {
      cart.incrementQuantityByItemId(workingItemId);
    } else {
      // isInStock is a "real-time" property that must be updated
      // every time an item is added to the cart, even if other
      // item details are cached.
      boolean isInStock = catalogService.isItemInStock(workingItemId);
      Item item = catalogService.getItem(workingItemId);
      cart.addItem(item, isInStock);
    }

    return new ForwardResolution(VIEW_CART);
  }

```

Then I check all stacks , I find all method under [domain](https://github.com/magichan/JPetStore-PinPoint/tree/378bcb0d7498848951fa362bb027373258abd51a/src/main/java/org/mybatis/jpetstore/domain) package and [action](https://github.com/magichan/JPetStore-PinPoint/tree/378bcb0d7498848951fa362bb027373258abd51a/src/main/java/org/mybatis/jpetstore/web/actions) package don't show up in the call stack.

The missing information is also important to me. So Could you tell me why the pinpoint tool don't trace methods under `domain` and `action` package and What I can do to improve it? 

Thank you very much.

#### Expected behavior

Call stack including the call to methods under domain package and action package.

**Comment by Xylus** [comment]
Hi @magichan 
Pinpoint does not trace every single method invocation as that will result in way too much information and a gigantic call stack that is hard to navigate through.
So Pinpoint tries to only trace methods that are most relevant to the user.

If you would like to trace other, additional methods, you can set the `profiler.entrypoint` option in *pinpoint.config* file.

Let me know if you have more questions.
Thanks.

**Comment by magichan** [comment]
Thank you. I will check it.

**Comment by magichan** [comment]
@Xylus Thank you for help, after changing the `profiler.entrypoint ` and `profiler.include`, I get these information.
