### ISSUE TITLE
gap spend time

### ISSUE THREAD

**Issue by wujinbiao94** [naver/pinpoint#5869]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

question：

![1565692659027](https://user-images.githubusercontent.com/17756240/62935456-c28c6d00-bdf9-11e9-803e-0e04a7154fe6.jpg)
The time-consuming normal value of this method is 0. Why do you occasionally appear tens of ms? I don't know where it is time consuming. Is it because the thread switching takes time?

**Comment by Xylus** [comment]
Hi @wujinbiao94 
We cannot know what is causing the gap time of 20ms.
What the call tree does show is that there's something taking 20ms to run after `getNextComicId(...)` finishes and `getComicIndex(...)` starts.
(The `getNextComicId(...)` and `getComicIndex(...)` methods themselves are all very fast, finishing in less than 1ms)
