### ISSUE TITLE
Add a attribute into all record that generated by method of project

### ISSUE THREAD

**Issue by magichan** [naver/pinpoint#5886]
Hi, I try to add a attribute into all record that generated by method of project, by plugin features of pinpoint. 

I don't know the class and methods of the project, but the plugin mechanism need me specify which specific class needs to be transformed. 
![image](https://user-images.githubusercontent.com/9430353/63222412-e83ebb00-c1d9-11e9-8be0-305bc1c97734.png)

What can I do to achieve my goal?

**Comment by emeroad** [comment]
You can use `MatchableTransformTemplate`.

sample 
https://github.com/naver/pinpoint/blob/master/plugins/vertx/src/main/java/com/navercorp/pinpoint/plugin/vertx/VertxPlugin.java#L162
