### ISSUE TITLE
is gRPC currently available?

### ISSUE THREAD

**Issue by ParkHanbum** [naver/pinpoint#5894]
I wrote a sample code for send packet to pinpoint-agent by using gRPC. it did refer gRPC example code and the ppt presented at the pinpoint meeting. but it did not work. 

I wonder gRPC is available for now?

following is codes that i wrote;
```
  int main(int argc, char** argv) {
~         int port = atoi(argv[1]);
~
~         ClientContext context;
~         google::protobuf::Empty empty;
~         PSpanMessage msg;
+         PSpan span = msg.span();
+         span.set_starttime(999999);
+         span.set_elapsed(10);
+
+         std::string host = "localhost:" + std::to_string(port);
+         std::cout << host << std::endl;
+         std::shared_ptr<Channel> channel = grpc::CreateChannel(host, grpc::InsecureChannelCredentials());
+         std::unique_ptr<Span::Stub> SpanStub = Span::NewStub(channel);
+
+         std::unique_ptr<::grpc::ClientWriterInterface<PSpanMessage>> stream = SpanStub->SendSpan(&context, &empty);
+
+         stream->Write(msg);
+         stream->WritesDone();

    return 0;
  }
```

and following is debug message shown from collector;
```
[INFO] [talledLocalContainer] 2019-08-19 11:23:10 [ERROR](c.n.p.r.c.ServerPacketDecoder      :85 ) invalid packetType received. packetType:18720, channel:[id: 0x28041189, /0:0:0:0:0:0:0:1:50616 :> /0:0:0:0:0:0:0:1:9994]
[INFO] [talledLocalContainer] 2019-08-19 11:23:10 [ERROR](c.n.p.r.c.ServerPacketDecoder      :85 ) invalid packetType received. packetType:10784, channel:[id: 0x28041189, /0:0:0:0:0:0:0:1:50616 :> /0:0:0:0:0:0:0:1:9994]
[INFO] [talledLocalContainer] 2019-08-19 11:23:10 [ERROR](c.n.p.r.c.ServerPacketDecoder      :85 ) invalid packetType received. packetType:18516, channel:[id: 0x28041189, /0:0:0:0:0:0:0:1:50616 :> /0:0:0:0:0:0:0:1:9994]
[INFO] [talledLocalContainer] 2019-08-19 11:23:10 [ERROR](c.n.p.r.c.ServerPacketDecoder      :85 ) invalid packetType received. packetType:21584, channel:[id: 0x28041189, /0:0:0:0:0:0:0:1:50616 :> /0:0:0:0:0:0:0:1:9994]
[INFO] [talledLocalContainer] 2019-08-19 11:23:10 [ERROR](c.n.p.r.c.ServerPacketDecoder      :85 ) invalid packetType received. packetType:12082, channel:[id: 0x28041189, /0:0:0:0:0:0:0:1:50616 :> /0:0:0:0:0:0:0:1:9994]
[INFO] [talledLocalContainer] 2019-08-19 11:23:10 [ERROR](c.n.p.r.c.ServerPacketDecoder      :85 ) invalid packetType received. packetType:11824, channel:[id: 0x28041189, /0:0:0:0:0:0:0:1:50616 :> /0:0:0:0:0:0:0:1:9994]
[INFO] [talledLocalContainer] 2019-08-19 11:23:10 [ERROR](c.n.p.r.c.ServerPacketDecoder      :85 ) invalid packetType received. packetType:3338, channel:[id: 0x28041189, /0:0:0:0:0:0:0:1:50616 :> /0:0:0:0:0:0:0:1:9994]
[INFO] [talledLocalContainer] 2019-08-19 11:23:10 [ERROR](c.n.p.r.c.ServerPacketDecoder      :85 ) invalid packetType received. packetType:3338, channel:[id: 0x28041189, /0:0:0:0:0:0:0:1:50616 :> /0:0:0:0:0:0:0:1:9994]    
```

I have one question, used 9993 ports in ppt, but in my case 9993 ports are not responding. Why is that?

**Comment by RoySRose** [comment]
Hello, @ParkHanbum 

I think you need to recheck the [architecture](http://naver.github.io/pinpoint/main.html) first

Pinpoint-agent doesn't receive anything from the targeted application. It is *attached to* the targeted application(written in java, or PHP, soon few more) and sends collected data to Pinpoint-Collector. Since your code looks like it's in C++.

Hope this will be the answer to your question.

**Comment by emeroad** [comment]
9993 Port is not a secure channel.
Currently, only plaintext is supported.

**Comment by eeliu** [comment]
Where can I find some examples of agent about how to use grpc，and which port is available for grpc ？

**Comment by dwkang** [comment]
```c++
GrpcTransporter (PinpointConfig& config,
                         opentracing::SystemTime tracer_start_time)
                : config_(config),
                  tracer_start_time_(tracer_start_time) {

            std::ostringstream agent_out, span_out;

            agent_out << config_.grpc_host << ":" << config_.grpc_agent_port;
            agent_channel_ = grpc::CreateChannel(agent_out.str(), grpc::InsecureChannelCredentials());
            agent_stub_ = v1::Agent::NewStub(agent_channel_);

            span_out << config_.grpc_host << ":" << config_.grpc_span_port;
            span_channel_ = grpc::CreateChannel(span_out.str(), grpc::InsecureChannelCredentials());
            span_stub_ = v1::Span::NewStub(span_channel_);

            SendAgentInfoRequest();
        }
```

**Comment by emeroad** [comment]
@ParkHanbum
No problem when using InsecureChannelCredentials.

Please check the collector configuration and use the latest master branch as possible.

**Comment by emeroad** [comment]
@eeliu
Unfortunately, the pinpoint-cpp project is not yet open source.

I recommend referring to the grpc sample code.
- https://github.com/grpc/grpc/tree/master/examples/cpp

**Comment by ParkHanbum** [comment]
> 
> 
> Istio sample
> 
> ```c++
> GrpcTransporter (PinpointConfig& config,
>                          opentracing::SystemTime tracer_start_time)
>                 : config_(config),
>                   tracer_start_time_(tracer_start_time) {
> 
>             std::ostringstream agent_out, span_out;
> 
>             agent_out << config_.grpc_host << ":" << config_.grpc_agent_port;
>             agent_channel_ = grpc::CreateChannel(agent_out.str(), grpc::InsecureChannelCredentials());
>             agent_stub_ = v1::Agent::NewStub(agent_channel_);
> 
>             span_out << config_.grpc_host << ":" << config_.grpc_span_port;
>             span_channel_ = grpc::CreateChannel(span_out.str(), grpc::InsecureChannelCredentials());
>             span_stub_ = v1::Span::NewStub(span_channel_);
> 
>             SendAgentInfoRequest();
>         }
> ```

where can I found this source codes?

**Comment by ParkHanbum** [comment]
I used proto files that located under grpc/src/main/proto/
is this correct?

**Comment by emeroad** [comment]
@ParkHanbum Right~

**Comment by congim** [comment]
@emeroad   Excuse me, when will the GRPC be officially released?

**Comment by ParkHanbum** [comment]
solved by : https://github.com/naver/pinpoint/issues/5995
