### ISSUE TITLE
When would version 1.8.5 be released?

### ISSUE THREAD

**Issue by yjqg6666** [naver/pinpoint#5896]
I just found that milestone 1.8.5 had been completed, https://github.com/naver/pinpoint/milestone/23. 
And milestone 1.9.0 had also been started. 
From the release page, release 1.8.5 could not be found. 
When would it be released? Thanks for the reply in advance.

**Comment by koo-taejin** [comment]
hi @yjqg6666 

Pinpoint team is  going to release v1.8.5 not too far away.(within 2weeks)
And also have a plan to release 1.9.0-RC1 within a month.

thanks.

**Comment by yjqg6666** [comment]
Good to know. Thanks a lot.
