### ISSUE TITLE
Heap Usage

### ISSUE THREAD

**Issue by tonfay** [naver/pinpoint#5905]
Excuse me, what are the meanings of Heap Usage and non-heap Usage in inspector?What does it stand for?

![image](https://user-images.githubusercontent.com/19604131/63481837-6694a900-c4c9-11e9-8f10-9eb1825b8de6.png)

**Comment by RoySRose** [comment]
@tonfay 

Please, place your mouse over the question mark at top right of each graph

**Comment by tonfay** [comment]
> @tonfay
> 
> Please, place your mouse over the question mark at top right of each graph

hello!
Can I understand the Heap Usage as the Usage of the Heap (young/old) and the non-heap Usage as perm?

**Comment by RoySRose** [comment]
@tonfay 

Sometimes it can be very easy if you look at the source code :)

Heap is from

https://docs.oracle.com/javase/7/docs/api/java/lang/management/MemoryMXBean.html#getHeapMemoryUsage()

Non-Heap is from 

https://docs.oracle.com/javase/7/docs/api/java/lang/management/MemoryMXBean.html#getNonHeapMemoryUsage()

**Comment by tonfay** [comment]
> @tonfay
> 
> Sometimes it can be very easy if you look at the source code :)
> 
> Heap is from
> 
> https://docs.oracle.com/javase/7/docs/api/java/lang/management/MemoryMXBean.html#getHeapMemoryUsage()
> 
> Non-Heap is from
> 
> https://docs.oracle.com/javase/7/docs/api/java/lang/management/MemoryMXBean.html#getNonHeapMemoryUsage()

tks very much!
