### ISSUE TITLE
How to delete agent

### ISSUE THREAD

**Issue by tonfay** [naver/pinpoint#5922]
How to delete agent?

![image](https://user-images.githubusercontent.com/19604131/63746599-caf3a600-c8d7-11e9-8c72-6edd1f7deac0.png)

**Comment by Xylus** [comment]
Hi, please refer to [this](http://naver.github.io/pinpoint/faq.html#how-do-i-delete-application-name-andor-agent-id-from-hbase).

**Comment by tonfay** [comment]
tks
