### ISSUE TITLE
Pinpoint to Hbase Distributed mode

### ISSUE THREAD

**Issue by VidushaZ** [naver/pinpoint#5924]
Hi,

I installed Hbase in distributed mode. 
Hbase is started and init hbase also worked. but collector is not started saying " server has closed socket, closing socket connection and attempting.."
Is there any additional config to do in collector? 

Thank You!

**Comment by emeroad** [comment]
Hi 
refer to http://naver.github.io/pinpoint/installation.html#hbase-region-servers-hostname-resolution
