### ISSUE TITLE
use aliyun mns service exception

### ISSUE THREAD

**Issue by tinet-zhoujiang** [naver/pinpoint#5929]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**
<img width="852" alt="屏幕快照 2019-08-28 11 35 48" src="https://user-images.githubusercontent.com/29974754/63824010-49a81c00-c988-11e9-8136-e4f0012b60a1.png">

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

aliyun mns service reject my request,because the request message with some message like Pinpoint-TraceID、Pinpoint-SpanID。
i want to know that is there some ways to skip or resolve this question

**Comment by emeroad** [comment]
According to #4882 issue, it seems that aliyun sdk solved the problem.

Upgrade version of aliyun sdk or Disable the pinpoint plugin that aliyun sdk is using.
