### ISSUE TITLE
if i use pinpoint to monitor other server docker container ,but I can not get connect from pinpoint web ?please tell me how to solve this issue

### ISSUE THREAD

**Issue by johnsonliu33** [naver/pinpoint#5934]
#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by koo-taejin** [comment]
hi @johnsonliu33 

I don't understand your question.
Please tell me the questions in as much detail as possible.

In addition, please fill in the above template that require.

thanks.
