### ISSUE TITLE
Need help with Quickstart + MySQL Persist setup

### ISSUE THREAD

**Issue by parameswarank** [naver/pinpoint#5935]
#### Description
Quickstart not connecting to MySQL after setting DB details on jdbc.properties
 
#### Environment

* Pinpoint version: v1.8.4
* MySQL: 5.7.27-1.el7.x86_64

#### Additional Info

I used this guide (https://naver.github.io/pinpoint/quickstart.html) for quickstart setup and everything works except MySQL connection. I loaded DB schema and all but not working.
Do we have any docs for enabling MySQL connection? Please point me in right direction.

**Comment by Xylus** [comment]
Hi @parameswarank 
If you take a look at quickstart web's [applicationContext-dao-config.xml](../blob/master/quickstart/web/src/main/resources/applicationContext-dao-config.xml), you'll notice that it's scanning `com.navercorp.pinpoint.web.dao.memory` and registering memory DAOs.

You'll need to modify this (to look similar to Pinpoint web's [applicationContext-dao-config.xml](../blob/master/web/src/main/resources/applicationContext-dao-config.xml)) and get the actual MySQL DAOs wired up, and modify the quickstart web's *jdbc.properties* accordingly as well.
