### ISSUE TITLE
how to add additional information for exception such as trigger time?

### ISSUE THREAD

**Issue by jiamine** [naver/pinpoint#5937]
[PINPOINT-release] SLOW RATE Alarm for m-s0 Service. #1

Rule : SLOW RATE
SLOW RATE value is 50% during the past 5 mins.(Threshold : 10%)
http://pinpoint.com
My mailbox received an exception message alarm like the above,But I feel that this amount of information is too small.
so , i want to add additional information for exception such as trigger time.
What should I do？thanks！！！

**Comment by minwoo-jung** [comment]
Hi @jiamine

Please review [AlarmMailTemplate class cread body method](https://github.com/naver/pinpoint/blob/master/web/src/main/java/com/navercorp/pinpoint/web/alarm/AlarmMailTemplate.java)

**Comment by jiamine** [comment]
> Hi @jiamine
> 
> Please review [AlarmMailTemplate class cread body method](https://github.com/naver/pinpoint/blob/master/web/src/main/java/com/navercorp/pinpoint/web/alarm/AlarmMailTemplate.java)

thank you !!!!
