### ISSUE TITLE
pinpoint-collector-1.8.4.war not starting 

### ISSUE THREAD

**Issue by krishnakumar9113** [naver/pinpoint#5944]
Hi ,

I am trying to setup pinpoint 1.8.4 ,which is the latest stable version.

I am able to setup HBase 1.2.7 version using cygwin, I am able to see Hbase Web Console in http://localhost:16010/master-status
I have also executed scripts/hbase-create.hbase and all tables are set in Hbase.

I didnt build the binaries ,I have directly downlaoded from https://github.com/naver/pinpoint/releases

But when i try to deploy pinpoint-collector-1.8.4.war in apache-tomcat-8.0.12, I am getting the following error

Enviornment used 

1.OS: Microsoft Windows 10 Enterprise 
2.Java 8 SDK- JAVA_HOME and JAVA8_HOME are set as Enviornment variables.
3.Web Container-apache-tomcat-8.0.12

Kindly help in resolving the error. 
PLease let me know if any other info is needed.

Thanks 
Krishna
![pin-collector_error](https://user-images.githubusercontent.com/12150188/63996618-ccacac00-cb19-11e9-8ae3-e5e4051bcd02.png)

**Comment by krishnakumar9113** [comment]
Hi ,
I have managed to find out that Tomcat version 8.0.12 is root cause, based on the below issue 
https://github.com/naver/pinpoint/issues/5039

Thanks 
Krishna Kumar

**Comment by emeroad** [comment]
👍 good~
