### ISSUE TITLE
no topology at homepage

### ISSUE THREAD

**Issue by spenxu** [naver/pinpoint#5947]
Hey pinpoint team :
why there is no topology at homepage while at server map has?
![image](https://user-images.githubusercontent.com/29301435/64088056-3d4e0580-cd72-11e9-9890-58048f4cbda4.png)
![image](https://user-images.githubusercontent.com/29301435/64088079-5a82d400-cd72-11e9-819d-986bf8c31655.png)

**Comment by emeroad** [comment]
Is there no log on the server?
Check the error logs of web and collector

**Comment by Xylus** [comment]
Hi @spenxu 
Not sure if this is the cause, but it looks very similar to #4673.
If you're using HBase 2.x, you'll have to upgrade hbase client to 2.x (instructions [here](http://naver.github.io/pinpoint/hbaseupgrade.html)), or use hbase 1.x as recommended.

**Comment by spenxu** [comment]
> Hi @spenxu
> Not sure if this is the cause, but it looks very similar to #4673.
> If you're using HBase 2.x, you'll have to upgrade hbase client to 2.x (instructions [here](http://naver.github.io/pinpoint/hbaseupgrade.html)), or use hbase 1.x as recommended.
