### ISSUE TITLE
Can you provide  Reactor plug-ins?

### ISSUE THREAD

**Issue by crab890715** [naver/pinpoint#5949]
[https://projectreactor.io/](url)

**Comment by RoySRose** [comment]
Hello, @crab890715 

We don't have any plans yet. 
It would be great if you can contribute a plug-in. 
It's not that complicated.

Let me know if you're up to it. I'll help you out.

**Comment by yjqg6666** [comment]
Now it's supported in master ? @RoySRose

**Comment by RoySRose** [comment]
Hello, @yjqg6666

may I ask you where you've got the idea that it's supported from now on?

**Comment by yjqg6666** [comment]
https://github.com/naver/pinpoint/pull/6226  and https://github.com/naver/pinpoint/tree/master/plugins/reactor/src/main/java/com/navercorp/pinpoint/plugin/reactor

**Comment by RoySRose** [comment]
Since `Spring Webflux` depends on `reactor-core`
https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux-reactive-libraries

Yes, I think it would be supported soon. 

I think plugin creator, @jaehong-kim might give you a better answer.

**Comment by yjqg6666** [comment]
@jaehong-kim any update or info?

**Comment by dinesh4747** [comment]
@emeroad @koo-taejin @Xylus @RoySRose @jaehong-kim - In context to this thread and associated below list of issues

a) #6352
b) https://github.com/naver/pinpoint/issues/5782

Just wanted to understand and clarity on whether the current/latest version of Pinpoint (2RC2) supports flux and mono calls or not ?
