### ISSUE TITLE
install pinpoint via k8s ,it shows (c.n.p.p.s.RetryQueue ) discard retry message(RetryMessage{retryCount=3, maxRetryCount=3, bytes=50, messageDescription='ApiMetaData'})

### ISSUE THREAD

**Issue by Rookie-Shy** [naver/pinpoint#5962]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

**Comment by Rookie-Shy** [comment]
the web ui has no data

**Comment by RoySRose** [comment]
Hello, @Rookie-Shy 

I think you need to debug it with the logs. 

As you can see quickstart from  https://github.com/naver/pinpoint-docker 
works perfectly which means the docker images have no problem.

**Comment by Rookie-Shy** [comment]
Dear Roy,


Thanks for your reply.


the url https://github.com/naver/pinpoint-docker is the way of installation via docker-compose.


In my opinion , there are  a huge different between docker-compose and k8s while install pinpoint .


could you provide the install scripts via k8s?


Thanks very much.


Best Regards.




------------------ 原始邮件 ------------------
发件人: "Roy Kim"<notifications@github.com>;
发送时间: 2019年9月10日(星期二) 下午2:20
收件人: "naver/pinpoint"<pinpoint@noreply.github.com>;
抄送: "随遇而安"<389157477@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [naver/pinpoint] install pinpoint via k8s ,it shows(c.n.p.p.s.RetryQueue ) discard retry message(RetryMessage{retryCount=3,maxRetryCount=3, bytes=50, messageDescription='ApiMetaData'}) (#5962)




Hello, @Rookie-Shy
 
I think you need to debug it with the logs.
 
As you can see quickstart from  https://github.com/naver/pinpoint-docker
 works perfectly which means the docker images have no problem.

**Comment by RoySRose** [comment]
I've tried running pinpoint on k8s a few months ago.

I can't promise you any dates since I'm already on a few things, but I'll see what I can do.

Will comment here for any updates

**Comment by Rookie-Shy** [comment]
was it work well on k8s ? I am expecting your update.


  Best Regards.


------------------ 原始邮件 ------------------
发件人: "Roy Kim"<notifications@github.com>;
发送时间: 2019年9月10日(星期二) 下午2:37
收件人: "naver/pinpoint"<pinpoint@noreply.github.com>;
抄送: "随遇而安"<389157477@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [naver/pinpoint] install pinpoint via k8s ,it shows(c.n.p.p.s.RetryQueue ) discard retry message(RetryMessage{retryCount=3,maxRetryCount=3, bytes=50, messageDescription='ApiMetaData'}) (#5962)




I've tried running pinpoint on k8s a few months ago.
 
I can't promise you any dates since I'm already on a few things, but I'll see what I can do.
 
Will comment here for any updates
