### ISSUE TITLE
dubbo server,don't show Icon！

### ISSUE THREAD

**Issue by xiaojinde** [naver/pinpoint#5964]
![image](https://user-images.githubusercontent.com/25930934/64239901-a466e800-cf33-11e9-850e-6b5a409cdad7.png)
we build service with virtual ip on the same linux server.different service use different ip.but the agent    send host ip to collector,and the dubbo provider send the virtual ip to collector.may be this cause the dubbo server icon don't show.
the code is :
agent send:
`  final InetAddress thisIp = InetAddress.getLocalHost();
   hostIp = thisIp.getHostAddress();`

dubbo provider send:
`  String host = localAddress == null ? null : 
            localAddress.getAddress() == null ? localAddress.getHostName() 
                    : NetUtils.filterLocalHost(localAddress.getAddress().getHostAddress());
        if (host == null || host.length() == 0) {
            return NetUtils.getLocalHost();
        }`

**Comment by emeroad** [comment]
#5879 Dubbo plugin is missing the remote address 
It seems to be related to the above issue.

This problem is fixed in 1.8.5 and 1.9.0.

**Comment by xiaojinde** [comment]
@emeroad hi,don't like this.i have remote address.i here ,it don't show icon.the virtual ip isn't same the hostip.
i use 1.8.4,i see the code like has modified.

**Comment by emeroad** [comment]
the remote address of #5876 means Pinpoint-Host header.

Include the caller address in the trace header(Pinpoint~~) because it cannot be mapped to the IP where a proxy exists, such as L4.
The problem has been fixed in 1.8.5, so test with 1.8.5.

**Comment by xiaojinde** [comment]
@emeroad ok,i wait 1.8.5 release.
