### ISSUE TITLE
RestApi  Documentation

### ISSUE THREAD

**Issue by krishnakumar9113** [naver/pinpoint#5967]
Hi,

Kindly let me know whether there any documentation and steps/procedures/templates to invoke REST apis that fetch data from Hbase database.

Thanks and Regards
Krishna Kumar G

**Comment by RoySRose** [comment]
Hello, @krishnakumar9113 

Nope, not yet.
Hope there is one.

**Comment by arpit1305** [comment]
Hello, Any planns to add REST API interface to fetch information from Pinpoint?
