### ISSUE TITLE
Log4j2 plugin

### ISSUE THREAD

**Issue by emeroad** [naver/pinpoint#5971]
Add Log4j2 pluign

**Comment by yjqg6666** [comment]
You may review PR #5969. Agent-IT need to be checked.

**Comment by minwoo-jung** [comment]
@yjqg6666
OK I will improve #5969 issue. 
Because #5969 code have some problems. 
The reason is described in detail in issue #5489.

**Comment by yjqg6666** [comment]
Agent-IT, updated. 
Now the test code not working with log4j 2.5+(2.5 included). But it's working with all my applications.

When debugging with Intellij Idea, it's stucking after:

> 019-09-06 16:00:35 [INFO ](com.navercorp.pinpoint.bootstrap.PinpointStarter) pinpoint agent started normally.
> Listening for transport dt_socket at address: 1296
> 2019-09-06 16:00:38 [WARN ](c.n.p.p.AgentInfoSender            ) request timed out while waiting for response.

**Comment by emeroad** [comment]
![image](https://user-images.githubusercontent.com/7564547/64411493-41f32080-d0c8-11e9-9c55-8b239c657f75.png)
@yjqg6666 Hi~
Attatch the remote debugger

**Comment by yjqg6666** [comment]
Working on it.

**Comment by emeroad** [comment]
👍  Good

**Comment by yjqg6666** [comment]
Just revisited the log4j2 code, the instrument class should be the impl. classes of org.apache.logging.log4j.spi.ExtendedLogger.  org.apache.logging.log4j.core.async.AsyncLogger has been transformed in the PR code. Just some refactoring will work for all.

**Comment by yjqg6666** [comment]
Update: now it's working for log4j2 2.0~2.12.0.  I will check why the latest version version 2.12.1 is not working.

**Comment by yjqg6666** [comment]
Now all the versions of log4j2 are supported. Almost rewriten, pls. review the PR.

**Comment by minwoo-jung** [comment]
@yjqg6666

First of all I thank you for your hard work.^^
I also analyzed to find the class to be profiled.

I think LogEventFactory's implementation class is most appropriate.
- org.apache.logging.log4j.core.impl.DefaultLogEventFactory
- org.apache.logging.log4j.core.impl.ReusableLogEventFactory
I haven't tested it yet, but it won't cause any problems. 
There is no need to enter the target class from the user in pinpoint.config.

**Comment by yjqg6666** [comment]
Thanks for your reply. Good to know. I will wait for the official support for log4j2. 

It's configurable, coz some app. have their own implementation for the logger interface. The default configuration should be ok for the most of the users.

**Comment by minwoo-jung** [comment]
@yjqg6666 
I will push the code soon. The test is already done.

**Comment by minwoo-jung** [comment]
Hi @yjqg6666


I've completed development and is about to merge the code. 

As I developed, I tested using the test code([Log4j2IT.java](https://github.com/naver/pinpoint/pull/5969/files#diff-8a28cbda5efb63472a655aade82fc3d3)) you developed.
Your code is all good except for the profiler target class. 
Also the code that checks the libaray version of the code you committed in the past gave us a new idea.
Although not used by the log4j2 plugin, this is a good idea to help develop other plugins.

**Your test code will be ready to use without modification.
This is because you executed the Log4j2IT code with debugging yourself.
If you modify the test code and send me a PR after merge [My code](https://github.com/naver/pinpoint/pull/5405), I would like to merge.
Can you send me a PR? If you don't want, I'll push the code myself.^^**

**Comment by yjqg6666** [comment]
So glad that it's done and would be available in the stable version 1.8.5.

**Comment by minwoo-jung** [comment]
@yjqg6666
After build check,  I will merge.
I've already run the log4j2 plugin test several times in my application and it should be fine.
But can you test it in your application to double check it?

**Comment by yjqg6666** [comment]
It's not working with [async logger](https://logging.apache.org/log4j/2.x/manual/async.html). 
It can be enabled by setting 
```
-DLog4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector
-Dlog4j2.contextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector
```
and addition of dependency below
```
        <dependency>
            <groupId>com.lmax</groupId>
            <artifactId>disruptor</artifactId>
            <version>3.4.2</version>
        </dependency>
```

It's working in other situations.

**Comment by yjqg6666** [comment]
@minwoo-jung You can test it with [my simplified repo ](https://github.com/yjqg6666/verify-project) .

**Comment by minwoo-jung** [comment]
@yjqg6666
i tested asyncappender syncappender.
I didn't know all aync function for log4j2 new feature.

i will analysis all async.

**Comment by yjqg6666** [comment]
ThreadContext is fetched when this method is called.

> org.apache.logging.log4j.core.async.AsyncLogger#initTranslator(org.apache.logging.log4j.core.async.RingBufferLogEventTranslator, java.lang.String, java.lang.StackTraceElement, org.apache.logging.log4j.Level, org.apache.logging.log4j.Marker, org.apache.logging.log4j.message.Message, java.lang.Throwable)

**Comment by yjqg6666** [comment]
Add additional target class ?

**Comment by minwoo-jung** [comment]
@yjqg6666 

I'm sorry. Today I have no time to look further. I will see and tell you tomorrow.

**Comment by minwoo-jung** [comment]
Hi @yjqg6666


I found a way to support async Logger. [commit](https://github.com/naver/pinpoint/commit/47b75b10425869d29ca1d5532bdbd4b39677c878)
We will be able to support all cases.
I've already tested it on versions 2.11 and 2.7 and it worked fine.

There are two things I would like to suggest.
1. I hope you double check in your application. And let me know the result.

2. Now we have to develop test code for using async Logger, How about you do it?

To give you a hint.. 
use JvmArgument annotation. and add custom log4j2 configuration file.

**If you take a long time or do not understand, I will do it myself. please answer about my question.^^**
```
@RunWith(PinpointPluginTestSuite.class)
@PinpointAgent(AgentPath.PATH)
@PinpointConfig("pinpoint-spring-bean-test.config")
@JvmArgument("-Dlog4j.configuration=com/navercorp/pinpoint/log4j2/log4j2-forAysncLogger.xml -DLog4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector -Dlog4j2.contextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector")
@Dependency({"org.apache.logging.log4j:log4j-core:[2.0,)", "com.lmax:disruptor:[3.4.2]"})
public class Log4j2ForAsyncLoggerIT {

    @Test
    public void test() {
        Logger logger = LogManager.getLogger();
        logger.error("for log4j2 plugin test");

        Assert.assertNotNull(ThreadContext.get("PtxId"));
        Assert.assertNotNull(ThreadContext.get("PspanId"));
    }
}
```

**Comment by yjqg6666** [comment]
You could just push your test code. It's fine.　I will check it soon.

**Comment by yjqg6666** [comment]
It works like a charm. Waiting for the port to the stable version.

**Comment by minwoo-jung** [comment]
@yjqg6666
good! I will check your test code.
Your code doesn't seem to have a problem, so I merge it.

**Comment by minwoo-jung** [comment]
@yjqg6666
good! I will check your test code.
Your code doesn't seem to have a problem, so I merge it.

**Comment by yjqg6666** [comment]
I backport-ed to 1.8.x and checked.

**Comment by minwoo-jung** [comment]
@yjqg6666
Good! You make everything work smooth.^^
Have you ever tested log4j2 using 1.8.5-snapshot in your application?

**Comment by minwoo-jung** [comment]
I'll double check using your  branch 1.8.x-log4j2-pr in our project. 
Sometimes it can't work because of changes in internal apis.

**Comment by minwoo-jung** [comment]
@yjqg6666
Now let's close the issue.

Thank you for your hard work and contribution.
The response and follow up was so fast that it was so good.^^
