### ISSUE TITLE
where can i get the code of test-pinpoint-demo?

### ISSUE THREAD

**Issue by jicai** [naver/pinpoint#5972]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

where can i get the code of test-pinpoint-demo? 
thank you.

**Comment by RoySRose** [comment]
Hello, @jicai 

what do you mean by test-pinpoint-demo

**Comment by jicai** [comment]
@RoySRose 
http://125.209.240.10:10123/#/main
is the project of APIGateway，Shopping-Api，Shoppping-Order open source？

**Comment by RoySRose** [comment]
@jicai 

Oh. the demo source code isn't currently an opensource.

@Xylus 
any plans?

**Comment by Xylus** [comment]
@jicai Can you access https://github.com/Xylus/pinpoint-demo-apps?
It's set to public so you'll be able to clone and play around with it.

**Comment by jicai** [comment]
@Xylus 
I got it, Thank you.
