### ISSUE TITLE
How to trace my custom jar application by new plugin

### ISSUE THREAD

**Issue by Zhiqfu** [naver/pinpoint#5982]
I want to monitor my custom jar with pinpoint plugin. The jar is a self-design container. Processes are always there.
my custom jar work as that:

while (isRuning) {
         A.handle();
        Thread.sleep(this.lSleepTime);
}

Class A {
  handle(){
     B b = new B();
     b.deal();

    C c = new C();
     c.deal();
  }
}

Class B {
  deal(){
     D d = new D();
     d.deal();
  }
}

Class C {
  deal(){
     do something;
  }
}

Class D {
  deal(){
     do something;
  }
}

I want to trace A.handle() B.deal() C.deal() D.deal().
What should I do?
How do I design this plugin?

**Comment by RoySRose** [comment]
Hello, @Zhiqfu 

first of all, I suggest you take a look at the [plugin development guide](https://naver.github.io/pinpoint/plugindevguide.html)

If you'd like to trace all 
>A.handle() B.deal() C.deal() D.deal().
Then, you need to instrument all of those functions.

**Comment by Xylus** [comment]
@Zhiqfu Also check [this](http://naver.github.io/pinpoint/faq.html#my-custom-jar-application-is-not-being-traced-help) out.
