### ISSUE TITLE
why duplicated span found? and the call stack is missing same thing

### ISSUE THREAD

**Issue by xunchangguo** [naver/pinpoint#5994]
why duplicated span found? and the call stack is missing same thing

in the log i see this:
map.FilteredMapBuilder       : duplicated span found:SpanBo{version=0, agentId='b1432f4d4fe1', applicationId='md_apisdk', agentStartTime=1567562427314, transactionId=TransactionId{agentId='5cb23c0d6ee0', agentStartTime=1568685102813, transactionSequence=624}, spanId=-4224448863847012507, parentSpanId=7357715800274294314, parentApplicationId='itm_ssopro', parentApplicationServiceType=1110, startTime=1568686786265, elapsed=40, rpc='CarrierInterfaceService:searchCarrier', serviceType=1110, endPoint='10.229.255.74:24243', apiId=-435, annotationBoList=[AnnotationBo{key=13, value=ApiMetaDataBo{agentId='b1432f4d4fe1', startTime=1567562427314, apiId=-435, apiInfo='Dubbo Provider Process', lineNumber=-1, methodTypeEnum=WEB_REQUEST}, isAuthorized=true}, AnnotationBo{key=10015, value=Dubbo Provider Process, isAuthorized=true}], flag=0, errCode=0, spanEventBoList=[{version=0, sequence=0, startElapsed=0, endElapsed=40, serviceType=9111, destinationId=null, endPoint=null, apiId=434, annotationBoList=[AnnotationBo{key=90, value=[Ljava.lang.Object;@76ae44ff, isAuthorized=true}, AnnotationBo{key=91, value=RpcResult [result=Result [code=0, msg=success, success=true, red...(21826), isAuthorized=true}, AnnotationBo{key=92, value=CarrierInterfaceService:searchCarrier, isAuthorized=true}, AnnotationBo{key=13, value=ApiMetaDataBo{agentId='b1432f4d4fe1', startTime=1567562427314, apiId=434, apiInfo='com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(com.alibaba.dubbo.rpc.Invocation invocation)', lineNumber=76, methodTypeEnum=DEFAULT}, isAuthorized=true}, AnnotationBo{key=12, value=com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(com.alibaba.dubbo.rpc.Invocation invocation):76, isAuthorized=true}], depth=1, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage=null, exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}, {version=0, sequence=1, startElapsed=0, endElapsed=38, serviceType=5071, destinationId=null, endPoint=null, apiId=15, annotationBoList=[AnnotationBo{key=13, value=ApiMetaDataBo{agentId='b1432f4d4fe1', startTime=1567562427314, apiId=15, apiInfo='com.camelot.mdapi.sdk.service.carrier.adapter.CarrierInterfaceServiceAdapter.searchCarrier(java.lang.Integer sourceSystem, java.lang.String carrierCode, java.lang.String carrierName, java.lang.Integer blacklistFlag, java.lang.String socialCreditCode, java.lang.String legalPerson, java.lang.String bankAccount, java.lang.String contact, java.lang.String phone, java.lang.Long operatingPeriod, java.lang.Integer useStatus, java.util.List carrierCodeList)', lineNumber=228, methodTypeEnum=DEFAULT}, isAuthorized=true}, AnnotationBo{key=12, value=com.camelot.mdapi.sdk.service.carrier.adapter.CarrierInterfaceServiceAdapter.searchCarrier(java.lang.Integer sourceSystem, java.lang.String carrierCode, java.lang.String carrierName, java.lang.Integer blacklistFlag, java.lang.String socialCreditCode, java.lang.String legalPerson, java.lang.String bankAccount, java.lang.String contact, java.lang.String phone, java.lang.Long operatingPeriod, java.lang.Integer useStatus, java.util.List carrierCodeList):228, isAuthorized=true}], depth=2, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage=null, exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}, {version=0, sequence=2, startElapsed=0, endElapsed=4, serviceType=5071, destinationId=null, endPoint=null, apiId=186, annotationBoList=[AnnotationBo{key=13, value=ApiMetaDataBo{agentId='b1432f4d4fe1', startTime=1567562427314, apiId=186, apiInfo='com.camelot.md.common.redis.RedisClient.get(java.lang.String key, com.camelot.md.common.enums.redis.DBTypeEnum type)', lineNumber=131, methodTypeEnum=DEFAULT}, isAuthorized=true}, AnnotationBo{key=12, value=com.camelot.md.common.redis.RedisClient.get(java.lang.String key, com.camelot.md.common.enums.redis.DBTypeEnum type):131, isAuthorized=true}], depth=3, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage=null, exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}, {version=0, sequence=3, startElapsed=0, endElapsed=3, serviceType=5071, destinationId=null, endPoint=null, apiId=-198, annotationBoList=[AnnotationBo{key=13, value=ApiMetaDataBo{agentId='b1432f4d4fe1', startTime=1567562427314, apiId=-198, apiInfo='com.camelot.md.common.redis.RedisClient.getJedis(com.camelot.md.common.enums.redis.DBTypeEnum dbType)', lineNumber=616, methodTypeEnum=DEFAULT}, isAuthorized=true}, AnnotationBo{key=12, value=com.camelot.md.common.redis.RedisClient.getJedis(com.camelot.md.common.enums.redis.DBTypeEnum dbType):616, isAuthorized=true}], depth=4, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage=null, exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}, {version=0, sequence=4, startElapsed=0, endElapsed=2, serviceType=8200, destinationId=REDIS, endPoint=10.118.159.22:36468, apiId=333, annotationBoList=[AnnotationBo{key=310, value=com.navercorp.pinpoint.common.util.IntBooleanIntBooleanValue@5a3f4e3c, isAuthorized=true}, AnnotationBo{key=13, value=ApiMetaDataBo{agentId='b1432f4d4fe1', startTime=1567562427314, apiId=333, apiInfo='redis.clients.jedis.BinaryJedis.select(int index)', lineNumber=421, methodTypeEnum=DEFAULT}, isAuthorized=true}, AnnotationBo{key=12, value=redis.clients.jedis.BinaryJedis.select(int index):421, isAuthorized=true}], depth=5, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage=null, exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}, {version=0, sequence=5, startElapsed=2, endElapsed=0, serviceType=8200, destinationId=REDIS, endPoint=10.118.159.22:36468, apiId=397, annotationBoList=[AnnotationBo{key=310, value=com.navercorp.pinpoint.common.util.IntBooleanIntBooleanValue@588c95c4, isAuthorized=true}, AnnotationBo{key=13, value=ApiMetaDataBo{agentId='b1432f4d4fe1', startTime=1567562427314, apiId=397, apiInfo='redis.clients.jedis.BinaryJedis.isConnected()', lineNumber=2802, methodTypeEnum=DEFAULT}, isAuthorized=true}, AnnotationBo{key=12, value=redis.clients.jedis.BinaryJedis.isConnected():2802, isAuthorized=true}], depth=-1, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage=null, exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}, {version=0, sequence=6, startElapsed=2, endElapsed=1, serviceType=8200, destinationId=REDIS, endPoint=10.118.159.22:36468, apiId=333, annotationBoList=[AnnotationBo{key=310, value=com.navercorp.pinpoint.common.util.IntBooleanIntBooleanValue@3087df0b, isAuthorized=true}, AnnotationBo{key=13, value=ApiMetaDataBo{agentId='b1432f4d4fe1', startTime=1567562427314, apiId=333, apiInfo='redis.clients.jedis.BinaryJedis.select(int index)', lineNumber=421, methodTypeEnum=DEFAULT}, isAuthorized=true}, AnnotationBo{key=12, value=redis.clients.jedis.BinaryJedis.select(int index):421, isAuthorized=true}], depth=-1, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage=null, exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}, {version=0, sequence=7, startElapsed=3, endElapsed=1, serviceType=8200, destinationId=REDIS, endPoint=10.118.159.22:36468, apiId=-209, annotationBoList=[AnnotationBo{key=310, value=com.navercorp.pinpoint.common.util.IntBooleanIntBooleanValue@7de6d23e, isAuthorized=true}, AnnotationBo{key=13, value=ApiMetaDataBo{agentId='b1432f4d4fe1', startTime=1567562427314, apiId=-209, apiInfo='redis.clients.jedis.Jedis.get(java.lang.String key)', lineNumber=96, methodTypeEnum=DEFAULT}, isAuthorized=true}, AnnotationBo{key=12, value=redis.clients.jedis.Jedis.get(java.lang.String key):96, isAuthorized=true}], depth=4, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage=null, exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}, {version=0, sequence=8, startElapsed=4, endElapsed=0, serviceType=5071, destinationId=null, endPoint=null, apiId=196, annotationBoList=[AnnotationBo{key=13, value=ApiMetaDataBo{agentId='b1432f4d4fe1', startTime=1567562427314, apiId=196, apiInfo='com.camelot.md.common.redis.RedisClient.returnResource(redis.clients.jedis.Jedis jedis)', lineNumber=587, methodTypeEnum=DEFAULT}, isAuthorized=true}, AnnotationBo{key=12, value=com.camelot.md.common.redis.RedisClient.returnResource(redis.clients.jedis.Jedis jedis):587, isAuthorized=true}], depth=-1, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage=null, exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}, {version=0, sequence=9, startElapsed=4, endElapsed=31, serviceType=9110, destinationId=10.229.255.73:24242, endPoint=10.229.255.73:24242, apiId=203, annotationBoList=[AnnotationBo{key=90, value=[Ljava.lang.Object;@14eb988a, isAuthorized=true}, AnnotationBo{key=91, value=RpcResult [result=[CarrierDTO [carrierCode=10, carrierName=杭州益嘉物...(30734), isAuthorized=true}, AnnotationBo{key=13, value=ApiMetaDataBo{agentId='b1432f4d4fe1', startTime=1567562427314, apiId=203, apiInfo='com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(com.alibaba.dubbo.rpc.Invocation inv)', lineNumber=128, methodTypeEnum=DEFAULT}, isAuthorized=true}, AnnotationBo{key=12, value=com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(com.alibaba.dubbo.rpc.Invocation inv):128, isAuthorized=true}], depth=3, nextSpanId=-8706965128890433063, hasException=false, exceptionId=0, exceptionMessage=null, exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}, {version=0, sequence=10, startElapsed=35, endElapsed=2, serviceType=5071, destinationId=null, endPoint=null, apiId=186, annotationBoList=[AnnotationBo{key=13, value=ApiMetaDataBo{agentId='b1432f4d4fe1', startTime=1567562427314, apiId=186, apiInfo='com.camelot.md.common.redis.RedisClient.get(java.lang.String key, com.camelot.md.common.enums.redis.DBTypeEnum type)', lineNumber=131, methodTypeEnum=DEFAULT}, isAuthorized=true}, AnnotationBo{key=12, value=com.camelot.md.common.redis.RedisClient.get(java.lang.String key, com.camelot.md.common.enums.redis.DBTypeEnum type):131, isAuthorized=true}], depth=-1, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage=null, exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}, {version=0, sequence=11, startElapsed=35, endElapsed=1, serviceType=5071, destinationId=null, endPoint=null, apiId=-198, annotationBoList=[AnnotationBo{key=13, value=ApiMetaDataBo{agentId='b1432f4d4fe1', startTime=1567562427314, apiId=-198, apiInfo='com.camelot.md.common.redis.RedisClient.getJedis(com.camelot.md.common.enums.redis.DBTypeEnum dbType)', lineNumber=616, methodTypeEnum=DEFAULT}, isAuthorized=true}, AnnotationBo{key=12, value=com.camelot.md.common.redis.RedisClient.getJedis(com.camelot.md.common.enums.redis.DBTypeEnum dbType):616, isAuthorized=true}], depth=4, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage=null, exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}, {version=0, sequence=12, startElapsed=35, endElapsed=0, serviceType=8200, destinationId=REDIS, endPoint=10.118.159.22:36468, apiId=333, annotationBoList=[AnnotationBo{key=310, value=com.navercorp.pinpoint.common.util.IntBooleanIntBooleanValue@5d883d10, isAuthorized=true}, AnnotationBo{key=13, value=ApiMetaDataBo{agentId='b1432f4d4fe1', startTime=1567562427314, apiId=333, apiInfo='redis.clients.jedis.BinaryJedis.select(int index)', lineNumber=421, methodTypeEnum=DEFAULT}, isAuthorized=true}, AnnotationBo{key=12, value=redis.clients.jedis.BinaryJedis.select(int index):421, isAuthorized=true}], depth=5, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage=null, exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}, {version=0, sequence=13, startElapsed=35, endElapsed=0, serviceType=8200, destinationId=REDIS, endPoint=10.118.159.22:36468, apiId=397, annotationBoList=[AnnotationBo{key=310, value=com.navercorp.pinpoint.common.util.IntBooleanIntBooleanValue@6196a1d0, isAuthorized=true}, AnnotationBo{key=13, value=ApiMetaDataBo{agentId='b1432f4d4fe1', startTime=1567562427314, apiId=397, apiInfo='redis.clients.jedis.BinaryJedis.isConnected()', lineNumber=2802, methodTypeEnum=DEFAULT}, isAuthorized=true}, AnnotationBo{key=12, value=redis.clients.jedis.BinaryJedis.isConnected():2802, isAuthorized=true}], depth=-1, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage=null, exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}, {version=0, sequence=14, startElapsed=36, endElapsed=0, serviceType=8200, destinationId=REDIS, endPoint=10.118.159.22:36468, apiId=333, annotationBoList=[AnnotationBo{key=310, value=com.navercorp.pinpoint.common.util.IntBooleanIntBooleanValue@6f67556e, isAuthorized=true}, AnnotationBo{key=13, value=ApiMetaDataBo{agentId='b1432f4d4fe1', startTime=1567562427314, apiId=333, apiInfo='redis.clients.jedis.BinaryJedis.select(int index)', lineNumber=421, methodTypeEnum=DEFAULT}, isAuthorized=true}, AnnotationBo{key=12, value=redis.clients.jedis.BinaryJedis.select(int index):421, isAuthorized=true}], depth=-1, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage=null, exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}, {version=0, sequence=15, startElapsed=36, endElapsed=1, serviceType=8200, destinationId=REDIS, endPoint=10.118.159.22:36468, apiId=-209, annotationBoList=[AnnotationBo{key=310, value=com.navercorp.pinpoint.common.util.IntBooleanIntBooleanValue@245b1d9e, isAuthorized=true}, AnnotationBo{key=13, value=ApiMetaDataBo{agentId='b1432f4d4fe1', startTime=1567562427314, apiId=-209, apiInfo='redis.clients.jedis.Jedis.get(java.lang.String key)', lineNumber=96, methodTypeEnum=DEFAULT}, isAuthorized=true}, AnnotationBo{key=12, value=redis.clients.jedis.Jedis.get(java.lang.String key):96, isAuthorized=true}], depth=4, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage=null, exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}, {version=0, sequence=16, startElapsed=37, endElapsed=0, serviceType=5071, destinationId=null, endPoint=null, apiId=196, annotationBoList=[AnnotationBo{key=13, value=ApiMetaDataBo{agentId='b1432f4d4fe1', startTime=1567562427314, apiId=196, apiInfo='com.camelot.md.common.redis.RedisClient.returnResource(redis.clients.jedis.Jedis jedis)', lineNumber=587, methodTypeEnum=DEFAULT}, isAuthorized=true}, AnnotationBo{key=12, value=com.camelot.md.common.redis.RedisClient.returnResource(redis.clients.jedis.Jedis jedis):587, isAuthorized=true}], depth=-1, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage=null, exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}, {version=0, sequence=17, startElapsed=38, endElapsed=1, serviceType=5013, destinationId=null, endPoint=null, apiId=448, annotationBoList=[AnnotationBo{key=9003, value=25799, isAuthorized=true}, AnnotationBo{key=13, value=ApiMetaDataBo{agentId='b1432f4d4fe1', startTime=1567562427314, apiId=448, apiInfo='com.alibaba.fastjson.JSON.toJSONString(java.lang.Object object)', lineNumber=382, methodTypeEnum=DEFAULT}, isAuthorized=true}, AnnotationBo{key=12, value=com.alibaba.fastjson.JSON.toJSONString(java.lang.Object object):382, isAuthorized=true}], depth=2, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage=null, exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}, {version=0, sequence=18, startElapsed=39, endElapsed=0, serviceType=5013, destinationId=null, endPoint=null, apiId=448, annotationBoList=[AnnotationBo{key=9003, value=18, isAuthorized=true}, AnnotationBo{key=13, value=ApiMetaDataBo{agentId='b1432f4d4fe1', startTime=1567562427314, apiId=448, apiInfo='com.alibaba.fastjson.JSON.toJSONString(java.lang.Object object)', lineNumber=382, methodTypeEnum=DEFAULT}, isAuthorized=true}, AnnotationBo{key=12, value=com.alibaba.fastjson.JSON.toJSONString(java.lang.Object object):382, isAuthorized=true}], depth=-1, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage=null, exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}, {version=0, sequence=19, startElapsed=39, endElapsed=0, serviceType=5013, destinationId=null, endPoint=null, apiId=448, annotationBoList=[AnnotationBo{key=9003, value=1529, isAuthorized=true}, AnnotationBo{key=13, value=ApiMetaDataBo{agentId='b1432f4d4fe1', startTime=1567562427314, apiId=448, apiInfo='com.alibaba.fastjson.JSON.toJSONString(java.lang.Object object)', lineNumber=382, methodTypeEnum=DEFAULT}, isAuthorized=true}, AnnotationBo{key=12, value=com.alibaba.fastjson.JSON.toJSONString(java.lang.Object object):382, isAuthorized=true}], depth=-1, nextSpanId=-1, hasException=false, exceptionId=0, exceptionMessage=null, exceptionClass=null, asyncId=-1, nextAsyncId=-1, asyncSequence=-1}], collectorAcceptTime=1568686629836, hasException=false, exceptionId=0, exceptionMessage='null', exceptionClass='null', applicationServiceType=1010, acceptorHost='10.229.255.74:24243', remoteAddr='10.255.0.11:55888', loggingTransactionInfo=0}

**Comment by xunchangguo** [comment]
any body hear

**Comment by emeroad** [comment]
This log can occur if the span-id is a duplicate.
the span-id has a long range(2^64), so it is generally not duplicated,
 - long 8 bytes -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807.
If this problem continues to occur, something is wrong.
If it happens very rarely, there is no problem.

https://github.com/naver/pinpoint/blob/master/web/src/main/java/com/navercorp/pinpoint/web/service/map/FilteredMapBuilder.java#L162
```
    private Map<Long, SpanBo> checkDuplicatedSpanId(List<SpanBo> transaction) {
        final Map<Long, SpanBo> transactionSpanMap = new HashMap<>();
        for (SpanBo span : transaction) {
            final SpanBo old = transactionSpanMap.put(span.getSpanId(), span);
            if (old != null) {
                logger.warn("duplicated span found:{}", old);
            }
        }
        return transactionSpanMap;
    }
```

**Comment by xunchangguo** [comment]
@emeroad thank u for you quickly replay
I saw in com.navercorp.pinpoint.bootstrap.context.SpanId.java  this java 
`private static long createSpanId(Random seed) {
        long id = seed.nextLong();
        while (id == NULL) {
            id = seed.nextLong();
        }
        return id;
    }`

the span id is is use java.util.Random to generate. how this can ensure no duplicate span-id generate？
thank you!

**Comment by xunchangguo** [comment]
@emeroad thank u for you quickly replay
I saw in com.navercorp.pinpoint.bootstrap.context.SpanId.java this java
`privatestatic long createSpanId(Random seed) {
     long id = seed.nextLong(); 
     while (id == NULL) { 
         id = seed.nextLong(); 
     }
     return id; 
}
` 

the span id is is use java.util.Random to generate. how this can ensure no duplicate span-id generate？especially in more than one agent，eg：in distribute system
thank you!

**Comment by Xylus** [comment]
Hi @xunchangguo 
As far as I know, pinpoint's access path does not require span ids to be globally unique, only that they are unique within a single transaction.
In a distributed system, duplicate span ids can very well be generated, but this should be okay as long as the collision isn't happening within a single transaction (this should only happen very rarely).
Transaction ids on the other hand need to be globally unique, which is why it is not simply a 64bit long value.

**Comment by xunchangguo** [comment]
thank u!
