### ISSUE TITLE
Corrupted(lost packet, invalid sequence) 

### ISSUE THREAD

**Issue by fionaliupw** [naver/pinpoint#6007]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

collector:1.8.1
web.18.1
agent:1.7.2

- question
I found  the error :Corrupted(lost packet, invalid sequence)  from calltree. 
From the issue #5600 , i check the following info: 
_collector.receiver.span.worker.queueSize_ in pinpoint-collector.properties is 4096.
stat.log is as following.

Need to increase the worker queueSize?

Thank you.

- stat.log
2019-09-19 09:47:33 [INFO ](c.n.p.c.StateReport                )
type=GAUGE, name=spanReceiverExecutor.completed, value=30073924564
2019-09-19 09:47:33 [INFO ](c.n.p.c.StateReport                )
type=GAUGE, name=spanReceiverExecutor.running, value=1
2019-09-19 09:47:33 [INFO ](c.n.p.c.StateReport                )
type=GAUGE, name=statReceiverExecutor.completed, value=31669869
2019-09-19 09:47:33 [INFO ](c.n.p.c.StateReport                )
type=GAUGE, name=statReceiverExecutor.running, value=0
2019-09-19 09:47:33 [INFO ](c.n.p.c.StateReport                )
type=METER, name=baseDataReceiverWorker.rejected, count=42321,
mean_rate=0.00435581412757024, m1=2.976463198511169E-296,
m5=9.370859266954124E-60, m15=1.0654063518313215E-20,
rate_unit=events/second
2019-09-19 09:47:33 [INFO ](c.n.p.c.StateReport                )
type=METER, name=baseDataReceiverWorker.submitted, count=11221601,
mean_rate=1.15496345024355, m1=2.3776013086568084, m5=2.542931646440672,
m15=2.7470087189167187, rate_unit=events/second
2019-09-19 09:47:33 [INFO ](c.n.p.c.StateReport                )
type=METER, name=spanReceiverExecutor.rejected, count=2930904,
mean_rate=0.30165811563634404, m1=2.964393875E-314,
m5=1.9992100035748813E-96, m15=2.1673772847022338E-32,
rate_unit=events/second
2019-09-19 09:47:33 [INFO ](c.n.p.c.StateReport                )
type=METER, name=spanReceiverExecutor.submitted, count=30076855472,
mean_rate=3095.607207180676, m1=7839.423560305877, m5=7830.869193546291,
m15=7748.639417002164, rate_unit=events/second
2019-09-19 09:47:33 [INFO ](c.n.p.c.StateReport                )
type=METER, name=statReceiverExecutor.rejected, count=0, mean_rate=0.0,
m1=0.0, m5=0.0, m15=0.0, rate_unit=events/second
2019-09-19 09:47:33 [INFO ](c.n.p.c.StateReport                )
type=METER, name=statReceiverExecutor.submitted, count=31669869,
mean_rate=3.259565351245565, m1=3.6904650538019395, m5=3.69895171446854,
m15=3.6991573875655623, rate_unit=events/second
2019-09-19 09:47:33 [INFO ](c.n.p.c.StateReport                )
type=TIMER, name=baseDataReceiverWorker.dispatchDuration, count=11179280,
min=0.009679, max=0.735414, mean=0.02416030195164621,
stddev=0.020356990714111612, median=0.018625, p75=0.025426999999999998,
p95=0.048561, p98=0.094165, p99=0.110413, p999=0.258808,
mean_rate=1.1506076363586757, m1=2.377601098787431, m5=2.542909892350519,
m15=2.7469950118916584, rate_unit=events/second, duration_unit=milliseconds
2019-09-19 09:47:33 [INFO ](c.n.p.c.StateReport                )
type=TIMER, name=baseDataReceiverWorker.duration, count=11179280,
min=0.795057, max=1268.4895549999999, mean=20.717214700421867,
stddev=73.20644415944214, median=1.5182, p75=2.286883, p95=152.151525,
p98=289.552353, p99=385.096031, p999=718.4056469999999,
mean_rate=1.1506076363159354, m1=2.37778810486036, m5=2.5431092624912064,
m15=2.747084867245342, rate_unit=events/second, duration_unit=milliseconds
2019-09-19 09:47:33 [INFO ](c.n.p.c.StateReport                )
type=TIMER, name=spanReceiverExecutor.dispatchDuration, count=30073924572,
min=0.0015019999999999999, max=12.197218999999999, mean=0.2626153562514069,
stddev=0.8546814749398955, median=0.026806999999999997,
p75=0.11270799999999999, p95=1.251806, p98=2.817868, p99=3.744869,
p999=12.197218999999999, mean_rate=3095.305548984131, m1=7839.441796719689,
m5=7830.873155603057, m15=7748.641163355057, rate_unit=events/second,
duration_unit=milliseconds
2019-09-19 09:47:33 [INFO ](c.n.p.c.StateReport                )
type=TIMER, name=spanReceiverExecutor.duration, count=30073924573,
min=0.021515, max=12.182765, mean=0.17769032691342937,
stddev=0.24723531294268158, median=0.08363899999999999,
p75=0.29773099999999997, p95=0.527272, p98=0.613831, p99=0.778117,
p999=1.0347309999999998, mean_rate=3095.305548949893, m1=7839.452884920552,
m5=7830.874550500013, m15=7748.640583594111, rate_unit=events/second,
duration_unit=milliseconds
2019-09-19 09:47:33 [INFO ](c.n.p.c.StateReport                )
type=TIMER, name=statReceiverExecutor.dispatchDuration, count=31669869,
min=0.012031, max=1.140163, mean=0.04055246837494057,
stddev=0.08519580378081307, median=0.022067999999999997, p75=0.030428,
p95=0.092066, p98=0.22883399999999998, p99=0.521057, p999=0.754002,
mean_rate=3.2595653504228284, m1=3.6904650538019395, m5=3.69895171446854,
m15=3.6991573875655623, rate_unit=events/second, duration_unit=milliseconds
2019-09-19 09:47:33 [INFO ](c.n.p.c.StateReport                )
type=TIMER, name=statReceiverExecutor.duration, count=31669869,
min=0.420214, max=36.579302, mean=0.9946613991580979,
stddev=0.46631819400778773, median=0.875382, p75=1.1311579999999999,
p95=1.708048, p98=2.8960079999999997, p99=3.112419, p999=3.65469,
mean_rate=3.2595653502922617, m1=3.6904650538019395, m5=3.69895171446854,
m15=3.6991573875655623, rate_unit=events/second, duration_unit=milliseconds

2019-09-19 09:48:33 [INFO ](c.n.p.c.StateReport                )
type=GAUGE, name=spanReceiverExecutor.running, value=1
2019-09-19 09:48:33 [INFO ](c.n.p.c.StateReport                )
type=GAUGE, name=statReceiverExecutor.completed, value=31670091
2019-09-19 09:48:33 [INFO ](c.n.p.c.StateReport                )
type=GAUGE, name=statReceiverExecutor.running, value=0
2019-09-19 09:48:33 [INFO ](c.n.p.c.StateReport                )
type=METER, name=baseDataReceiverWorker.rejected, count=42321,
mean_rate=0.004355787214947416, m1=1.0949796181356535E-296,
m5=7.672210664621135E-60, m15=9.966950840352542E-21,
rate_unit=events/second
2019-09-19 09:48:33 [INFO ](c.n.p.c.StateReport                )
type=METER, name=baseDataReceiverWorker.submitted, count=11221761,
mean_rate=1.1549727818558366, m1=2.594051586089391, m5=2.57738637145221,
m15=2.7461283882545757, rate_unit=events/second
2019-09-19 09:48:33 [INFO ](c.n.p.c.StateReport                )
type=METER, name=spanReceiverExecutor.rejected, count=2930904,
mean_rate=0.30165625182541517, m1=2.964393875E-314,
m5=1.6368147117878973E-96, m15=2.0275965890378007E-32,
rate_unit=events/second
2019-09-19 09:48:33 [INFO ](c.n.p.c.StateReport                )
type=METER, name=spanReceiverExecutor.submitted, count=30077338325,
mean_rate=3095.637777271001, m1=8006.179658721837, m5=7875.066542079965,
m15=7769.37552158343, rate_unit=events/second
2019-09-19 09:48:33 [INFO ](c.n.p.c.StateReport                )
type=METER, name=statReceiverExecutor.rejected, count=0, mean_rate=0.0,
m1=0.0, m5=0.0, m15=0.0, rate_unit=events/second
2019-09-19 09:48:33 [INFO ](c.n.p.c.StateReport                )
type=METER, name=statReceiverExecutor.submitted, count=31670091,
mean_rate=3.2595680606303863, m1=3.6911785458910784, m5=3.699000586111253,
m15=3.6991981923378674, rate_unit=events/second
2019-09-19 09:48:33 [INFO ](c.n.p.c.StateReport                )
type=TIMER, name=baseDataReceiverWorker.dispatchDuration, count=11179440,
min=0.009679, max=0.735414, mean=0.029309764689053004,
stddev=0.03089054751338058, median=0.020787, p75=0.030549999999999997,
p95=0.057801, p98=0.119223, p99=0.180855, p999=0.30771499999999996,
mean_rate=1.1506169948205367, m1=2.594051508882762, m5=2.577368560709597,
m15=2.746115565236887, rate_unit=events/second, duration_unit=milliseconds
2019-09-19 09:48:33 [INFO ](c.n.p.c.StateReport                )
type=TIMER, name=baseDataReceiverWorker.duration, count=11179440,
min=0.795057, max=1268.4895549999999, mean=14.034306472270499,
stddev=56.96738982906958, median=1.6058839999999999, p75=2.189288,
p95=88.80629499999999, p98=209.443017, p99=312.462465,
p999=481.61555899999996, mean_rate=1.1506169947219056,
m1=2.594120304572367, m5=2.577531791175023, m15=2.7461996255479004,
rate_unit=events/second, duration_unit=milliseconds
2019-09-19 09:48:33 [INFO ](c.n.p.c.StateReport                )
type=TIMER, name=spanReceiverExecutor.dispatchDuration, count=30074407452,
min=0.001175, max=6.924989999999999, mean=0.31293937725585746,
stddev=0.690692505270765, median=0.035649, p75=0.222432, p95=1.799928,
p98=3.0320929999999997, p99=3.5828819999999997, p999=4.918788999999999,
mean_rate=3095.336123345034, m1=8006.297740147163, m5=7875.075227607255,
m15=7769.37778053855, rate_unit=events/second, duration_unit=milliseconds
2019-09-19 09:48:33 [INFO ](c.n.p.c.StateReport                )
type=TIMER, name=spanReceiverExecutor.duration, count=30074407453,
min=0.021515, max=12.182765, mean=0.19469674355824393,
stddev=0.3082009506170936, median=0.083687, p75=0.287884, p95=0.604285,
p98=0.83734, p99=0.9434899999999999, p999=4.7342249999999995,
mean_rate=3095.3361231613458, m1=8006.312792655105, m5=7875.076980969128,
m15=7769.377310119569, rate_unit=events/second, duration_unit=milliseconds
2019-09-19 09:48:33 [INFO ](c.n.p.c.StateReport                )
type=TIMER, name=statReceiverExecutor.dispatchDuration, count=31670091,
min=0.011482, max=2.117073, mean=0.044241834458307386,
stddev=0.1388009204437695, median=0.024409999999999998, p75=0.034536,
p95=0.072575, p98=0.130912, p99=0.7516459999999999, p999=2.117073,
mean_rate=3.25956805912516, m1=3.6911785458910784, m5=3.699000586111253,
m15=3.6991981923378674, rate_unit=events/second, duration_unit=milliseconds
2019-09-19 09:48:33 [INFO ](c.n.p.c.StateReport                )
type=TIMER, name=statReceiverExecutor.duration, count=31670091,
min=0.392704, max=36.579302, mean=1.1144871542766415,
stddev=1.4516553870700837, median=0.92679, p75=1.153092, p95=1.740113,
p98=2.8960079999999997, p99=3.333814, p999=22.414369999999998,
mean_rate=3.2595680588786866, m1=3.6911785458910784, m5=3.699000586111253,
m15=3.6991981923378674, rate_unit=events/second, duration_unit=milliseconds

**Comment by xunchangguo** [comment]
collector rejected
in stat.log
 name=spanReceiverExecutor.rejected, count=2930904,

**Comment by fionaliupw** [comment]
> collector rejected
> in stat.log
> name=spanReceiverExecutor.rejected, count=2930904,
Thank you for your answer.
Whether it indicates that collector.receiver.span.worker.queueSize need to be adjusted?
need to refer to the CPU and memory for parameter adjustment?

**Comment by fionaliupw** [comment]
Every collectors's stat.log shows spanReceiverExecutor.rejected. If I increase the worker queuesize, whether the loader of hbase also be increased? @xunchangguo 
Thanks.

**Comment by fionaliupw** [comment]
Every collectors's stat.log shows spanReceiverExecutor.rejected. If I increase the worker queuesize, whether the loader of hbase also be increased?
