### ISSUE TITLE
query the transactionList is very slow on producting enviroment

### ISSUE THREAD

**Issue by zhouhuicong** [naver/pinpoint#6012]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

I use docker deploy  pinpoint1.8.3   in  the  testing and producting environment 
when i query transactionList  in testing environment  the query is fast .but on the producting environment  the some query is very slow. 
so I  get into  the hbase docker and hbase shell query table . the result is : 
testing environment query the  TraceV2  size 8G
count 'TraceV2', {INTERVAL => 100000, CACHE => 500000}

10269536 row(s) in 116.7560 seconds   

producting environment  query  the  TraceV2  size 63G 
23612868 row(s) in  1063.6250 seconds

Is this normal? I can't find out a detailed link map in 15 minutes now on the  producting environment . It's too slow. Is there any optimization plan?

**Comment by emeroad** [comment]
Can you tell me the number of agents and applcation?

ServerMap query performance is independent of TraceTable size.

ServerMap query speed is related to the number of agents and search depth.
  - Basically, HBase performance is the most important factor.

Our optimization plan is as follows.
### Optimization plan
1. Add application-based statistics to reduce disk reads.
   (Currently based on agent statistics)
  - eg
         agent : 1000 node
         application : 100 node
         before : 1000 queries are required to complete serveramp
         after : 100 queries are required to complete serveramp
2. Add a tier group above the application group
 - Improve query condition
3. Enhance asynchronous read of hbase (requires hbase2.0) to reduce IO latency.

When searching for long time ranges, it is recommended to reduce the search depth.

**Comment by zhouhuicong** [comment]
we have 66 agents 
I search depth is 4  and time range is in  1 hour , 
if  i  Make a major merge , Will it improve efficiency?

**Comment by zhouhuicong** [comment]
> Can you tell me the number of agents and applcation?
> 
> ServerMap query performance is independent of TraceTable size.
> 
> ServerMap query speed is related to the number of agents and search depth and time range
>   - Basically, HBase performance is the most important factor.
> 
> Our optimization plan is as follows.
> 
> ### Optimization plan
> 1. Add application-based statistics to reduce disk reads.
>       (Currently based on agent statistics)
>      - eg
>             agent : 1000 node
>             application : 100 node
>             before : 1000 queries are required to complete serveramp
>             after : 100 queries are required to complete serveramp
> 2. Add a tier group above the application group
> 
> * Improve query condition
> 
> 1. Enhance asynchronous read of hbase (requires hbase2.0) to reduce IO latency.
> 
> When searching for long time ranges, it is recommended to reduce the search depth.

we have 66 agents
I search depth is 4 and time range is in 1 hour ,
if i Make a major merge , Will it improve efficiency?

**Comment by emeroad** [comment]
66 agents are very very small size. hbase performance check and tuning are recommended.

**Comment by Xylus** [comment]
Also, the bottleneck could be on the rendering side for complex server maps.
Check your web log for something like
```
[INFO ](c.n.p.w.s.MapServiceImpl           ) ApplicationMap BuildTime: StopWatch 'ApplicationMap': running time (millis) = 1048
-----------------------------------------
ms     %     Task name
-----------------------------------------
00837  080%  ApplicationMap Hbase Io Fetch(Caller,Callee) Time
00211  020%  ApplicationMap MapBuilding(Response) Time
```

If the time taken here is not very long, the browser might be taking too long to render the server map.
If the time taken here is long, or the log isn't printed at all, then it's the server that's taking a long time to respond - in which case, please look into what @emeroad has suggested.

**Comment by zhouhuicong** [comment]
由于生产环境，无法连接外网，造成字体无法渲染，现在的解决办法是删除 index.html页面里的 	<link href='//fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'> 。
Because of the production environment, the font cannot be rendered due to the inability to connect to the external network. The solution now is to delete <link href='//fonts.googleapis.com/css?Family=Lato'rel='stylesheet'type='text/css'> from the index.html page.

**Comment by zhouhuicong** [comment]
> Also, the bottleneck could be on the rendering side for complex server maps.
> Check your web log for something like
> 
> ```
> [INFO ](c.n.p.w.s.MapServiceImpl           ) ApplicationMap BuildTime: StopWatch 'ApplicationMap': running time (millis) = 1048
> -----------------------------------------
> ms     %     Task name
> -----------------------------------------
> 00837  080%  ApplicationMap Hbase Io Fetch(Caller,Callee) Time
> 00211  020%  ApplicationMap MapBuilding(Response) Time
> ```
> 
> If the time taken here is not very long, the browser might be taking too long to render the server map.
> If the time taken here is long, or the log isn't printed at all, then it's the server that's taking a long time to respond - in which case, please look into what @emeroad has suggested.

Thanks very much， the problem is  page rendering
