### ISSUE TITLE
Whether pinpoint can track microservices based on ServiceComb architecture？

### ISSUE THREAD

**Issue by JangNum** [naver/pinpoint#6017]
I want to monitor a microservice system based on ServiceComb by pinpoint. Do I need to re-write a  plugin for that?

**Comment by RoySRose** [comment]
Hello, @JangNum 

I'm not sure. But after searching for ServiceComb, I noticed that the framework uses spring cloud. If it's the case, it' may have some shortage of tracing with Pinpoint. 

refer #5267

**Comment by JangNum** [comment]
> Hello, @JangNum
> 
> I'm not sure. But after searching for ServiceComb, I noticed that the framework uses spring cloud. If it's the case, it' may have some shortage of tracing with Pinpoint.
> 
> refering #5267

Thanks for your reply.I hava solved it by writing a plugin for ServiceComb.
