### ISSUE TITLE
Call thirdparty web service return 403 after applying pinpoint

### ISSUE THREAD

**Issue by pengsili** [naver/pinpoint#6028]
Hi.
In our code,we will call a thirdparty web service . But after we applied pinpoint-agent to our application, the call to this web service always returned 403. After we removed pinpoint-agent, it resumed. In my understand, pinpoint will add something to header for each request.If not added these things to header, it should work normally.So can i set ignore tracing this url or method?
I saw there were some configrations like profiler.tomcat.excludeurl and profiler.tomcat.excludemethod. But seems profiler.tomcat.excludeurl not work for calling thirdparty url. And profiler.tomcat.excludemethod only support HTTP Request methods like POST or PUT.
Please kindly help.Thanks

**Comment by Xylus** [comment]
Hi @pengsili 
I don't think we have a way to exclude urls on the client side, but this looks like a useful feature to have.
In the mean time, you could disable tracing http clients via *pinpoint.config*.

**Comment by pengsili** [comment]
Hi @Xylus 
Thanks for your reply. We don`t want to disable all http tracing.Just want to exclude this one.  If we can develop customized plugin ourselves to exclude some methods or urls?

**Comment by Xylus** [comment]
@pengsili Yes, that is definitely possible, and would be the better way to solve your issue if you're able to modify the plugin.
Also, if you're up for it, it'd be great if you can generalize this by making a config option in *pinpoint.config* and make it available to all http client plugins, then throw us a PR :)

**Comment by pengsili** [comment]
Hi @Xylus 
We have found the root cause.
pinpoint-traceid:2^1569291346971^1
As you see,this header has special symbol '^'. This thirdparty service regards some special symbols as attack and refuse this call.
Current we are planning to develop a plugin to ignore tracing some customized urls.But actually we hope to trace this web service calls.
I wonder if it is a good way to add special symbols in header. And will Pinpoint do enhancement about this ? Because not only me will encounter this issue.
Thanks

**Comment by emeroad** [comment]
@pengsili 
Unfortunately, this change does not guarantee compatibility.
If you change the spec of TraceId, older agents cannot accept the changed ID.

**Comment by pengsili** [comment]
Hi emeroad,
  In my understand, i change the TraceId when sending http request to thirdparty web service, and change the TraceId back after get response. And then will send the trace information to collector. Seems there is no compatibility issue. 
Thanks

**Comment by emeroad** [comment]
https://github.com/naver/pinpoint/blob/dae088acdc169c908f8247a830b25c377303a81a/plugins/httpclient3/src/main/java/com/navercorp/pinpoint/plugin/httpclient3/interceptor/HttpMethodBaseExecuteMethodInterceptor.java#L147
Sorry, I missed your filtering code. I agree with you.

I think it's better to delete all pinpoint-header.
Is there a reason you didn't delete it?
