### ISSUE TITLE
Alarm trigger is not accurate，how  to check it?

### ISSUE THREAD

**Issue by fionaliupw** [naver/pinpoint#6033]
PINPOINT v1.8.1

 - INFO:
my application's  alarm rule: ERROR RATE= 10%.
But the scatter data is as following.
![image](https://user-images.githubusercontent.com/26397343/65736033-3a91c680-e10c-11e9-82ba-f497a13e1097.png)

From the above data, alarm was not accurate, and how can i check it or what could be the cause of it?

Thanks.

**Comment by minwoo-jung** [comment]
@fionaliupw 
Look at the log when the alarm goes off. Set log level to debug.
