### ISSUE TITLE
Secured communication between agents and collector

### ISSUE THREAD

**Issue by estebangit** [naver/pinpoint#6038]
Hello,
Is there a way, or have you plans, to set secure communication between agents and the collector?
Regards

**Comment by koo-taejin** [comment]
hi @estebangit 

Pinpoint team have plan that will support TLS secure connection enable feature in version 1.9.1.

thanks. :)

**Comment by estebangit** [comment]
Hi @koo-taejin 
Excellent!
Have you any idea about when this release will be available?
Regards
