### ISSUE TITLE
Not getting code level execution detail (missing stack trace)

### ISSUE THREAD

**Issue by theepan** [naver/pinpoint#6045]
I am using 1.8.5.

I am not seeing how much time it took to execute each method in a stack trace order.

All it shows is servlet method, not my methods:
 
invoke(Request request, Response response)
 - execute(HttpState state, HttpConnection conn)
   - http.entity
   - http.status.code
   -  http.io

**Comment by Xylus** [comment]
Hi @theepan 
Pinpoint by default only traces methods specified in plugins. You can however, specify custom methods you'd like to trace by setting `profiler.entrypoint` in *pinpoint.config*.

On another note, if the methods you're looking to trace are from classes managed by spring, you can get them traced more easily by configuring `profiler.spring.beans.*` options in *pinpoint.config*.
