### ISSUE TITLE
Remove Inactive Host

### ISSUE THREAD

**Issue by harissutanrafiq** [naver/pinpoint#6047]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

Hii All

i love pinpoint and now is already deployed on my production enviroment,
my server is autoscale, instance will up and down anytime, thats make my pinpoint dashboard is dirty, can i remove inactive hosts withoud wait 30day ..? for example every 2 day..?

thanks

**Comment by Xylus** [comment]
Hi @harissutanrafiq 
There's an [API](https://github.com/naver/pinpoint/blob/master/web/src/main/java/com/navercorp/pinpoint/web/controller/AdminController.java#L77) in Pinpoint Web to delete any agents that were not active for the last n days (30 default) - `/admin/removeInactiveAgents.pinpoint`, request parameter : `durationDays`.
You can call this API periodically for housekeeping.

Also, perhaps a more relevant point to your issue, you might want to add `-Dpinpoint.container` option when launching agents running in a containerized environment. This will clean up the agent list in the inspector view by filtering out agents that were not alive during the queried time period.

**Comment by harissutanrafiq** [comment]
thanks @xylus , ah i will try you suggestion and i will reply soon

**Comment by harissutanrafiq** [comment]
@Xylus 
i try this url
http://myip:8079/admin/removeInactiveAgents.pinpoint?applicationName=xxx&password=xxx
and respon is OK

but inactive host is stilll there
![alfagit](https://user-images.githubusercontent.com/33673320/66456692-7af02d80-ea98-11e9-9015-1e9a4303b572.jpg)

**Comment by Xylus** [comment]
The API removes agents that were not active for the past 30 days. (The Realtime Active Thread Chart shows all agents that were active in the last 7 days, so I'm guessing none of them were removed).
Please refer to [this] (https://github.com/naver/pinpoint/issues/6064#issuecomment-540291276) for a workaround.
Thanks

**Comment by harissutanrafiq** [comment]
thanks @Xylus i will try build from source code, i hope one day pinpoint will support golang too
