### ISSUE TITLE
Will Pinpoint 1.8.4 supports JDK 12? 

### ISSUE THREAD

**Issue by josephthanaraja** [naver/pinpoint#6056]
Will Pinpoint 1.8.4 supports JDK 12? We are trying to deploy the docker-compose into Kubernetes box and able to deploy eventhing and getting the Agent information but AgentStatV2 doesnt have any data. Do we need any specific setup for that?

**Comment by RoySRose** [comment]
Hello, @josephthanaraja 

> Will Pinpoint 1.8.4 supports JDK 12?
Will Pinpoint supports JDK 12? Yes, eventually it will one day.
Will Pinpoint 1.8.4 supports JDK 12? No, we will not backport older versions to support hight JDKs, But 1.8.4 may already have no problem(not sure) with JDK 12.

> Do we need any specific setup for that?
No, usually there is no setup difference. I don't think this is relevant to your problem, But if you are using container please look at the [installation guide](https://naver.github.io/pinpoint/installation.html#installation-2) 
on `-Dpinpoint.container` option

**Comment by Xylus** [comment]
In addition to what @RoySRose said, it might be due to something as simple as a missing entry for JDK 12 in [JvmVersion](https://github.com/naver/pinpoint/blob/master/commons/src/main/java/com/navercorp/pinpoint/common/util/JvmVersion.java) class.
We haven't yet tested thoroughly on JDK 12 so I can't guarantee this, but you could try adding an entry for Java 12 in **JvmVersion**, build the agent and see if it works without a problem.

**Comment by josephthanaraja** [comment]
Appreciate your help!!.
I have tried the Options1as suggested above but no luck. Agent container is running fine as per the logs but Collector container (trying with Quickstart application) is not collecting the data - AgentStatV2 doesn't have any data. I will try the second option as well

**Comment by josephthanaraja** [comment]
Also could you please update me when 1.9.0 Version(Staple) is available to use.

**Comment by RoySRose** [comment]
>Also could you please update me when 1.9.0 Version(Staple) is available to use

Not sure, it keeps getting delayed for a few reasons. 
No hard dates, but in several weeks, I assume.

**Comment by emeroad** [comment]
If you are in a hurry, you can upgrade asm-x.x.jar.

https://mvnrepository.com/artifact/org.ow2.asm/asm/7.1
$PINPOINT_DIR/lib/asm-x.x.jar -> asm.7.1.jar

**Comment by josephthanaraja** [comment]
I am specifically looking for the below issue. Do you think will it solve this issue?.
Issue is :- IN KUBERNETES --> Agent container is running fine as per the logs but Collector container (trying with Quickstart sample application) is not collecting the data - AgentStatV2 doesn't have any data. But I am seeing only the Agent information in the web but no tracing info or other informations.

**Comment by josephthanaraja** [comment]
Any suggestions?
