### ISSUE TITLE
How to clean up useless pinpoint agentID

### ISSUE THREAD

**Issue by bjddd192** [naver/pinpoint#6064]
my app deployment by docker, use containerID as pinpoint agentID, after multiple deployments, It produces a lot of useless pinpoint agentID, I want to know how to remove them.
thank you.

**Comment by Xylus** [comment]
Hi @bjddd192 
Please refer to #6047

**Comment by bjddd192** [comment]
thank you very much.
I'm using this url, for example:
`http://10.234.6.87:8079/admin/removeInactiveAgents.pinpoint?durationDays=3`
this request returns `Missing password.`
I have a password, but how do I login?

**Comment by Xylus** [comment]
Password should be in your *pinpoint-web.properties* file under the *admin.password* property (default: admin).

Just add it as a request parameter (eg ?password=admin) on your request above and it should work.

**Comment by bjddd192** [comment]
`http://10.234.6.87:8079/admin/removeInactiveAgents.pinpoint?durationDays=3&password=admin`
It worked, but this request returns `duration may not be less than 30 days`.
Can only clean up data from a month ago?

**Comment by bjddd192** [comment]
`http://10.234.6.87:8079/admin/removeInactiveAgents.pinpoint?password=admin`
the default is OK.

**Comment by Xylus** [comment]
There's a check to safeguard from too short of a duration when removing the agents.
You can modify [this](https://github.com/naver/pinpoint/blob/master/web/src/main/java/com/navercorp/pinpoint/web/service/AdminServiceImpl.java#L48) line in **AdminServiceImpl** to change the minimum value for the parameter.

**Comment by bjddd192** [comment]
Thank you very much. Best regards.
