### ISSUE TITLE
JDBC connectionPool Stats

### ISSUE THREAD

**Issue by asasisekar** [naver/pinpoint#6072]
I would like to know if java apm agent supports/captures  jdbc connection pool metrics for application running on tomcat container. Please advise.

**Comment by koo-taejin** [comment]
hi @asasisekar 

If you use DBCP, DBCP2, HIKARICP, and DRUID as a library for managing DB connection pools.
You can see information from the agent's inspector.
If you don't use below things. then You can not see information. 

thanks.

**Comment by asasisekar** [comment]
Hi @koo-taejin 
App is using the HIKARICP datasource for connection pools.
In agent inspector, No Data collected under Data Source charts.

**Comment by koo-taejin** [comment]
@asasisekar 

Please check the hikaricp setting is enabled in the pinpoint.config.

If it's activated but you can't see it,
Change the log level of the pinpoint agent to DEBUG.
And check the agent's logs that is related with HikariCP.

As a result, if you think it's a problem with pinpoint, please post the log and reproducibility method together.

thanks.
