### ISSUE TITLE
Provide indicators for request per endpoint

### ISSUE THREAD

**Issue by joongsoo** [naver/pinpoint#6074]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

----

I think it would be good to provide analytical data such as `response rate per endpoint`, `request count per endpoint` like newrelic.

Does Pinpoint have a plan like this?

**Comment by RoySRose** [comment]
Hello, @joongsoo 

We do have plans for this and also other statistic reports. But with limited resources, there isn't a due date for this.

Love to see any contributions on this
