### ISSUE TITLE
why remove TRANSACTION_ID from mdc when trace == null

### ISSUE THREAD

**Issue by lhl4546** [naver/pinpoint#6075]
in LoggingEventOfLogbackInterceptor.java，there is some code like 
> Trace trace = traceContext.currentTraceObject();
        if (trace == null) {
            MDC.remove(TRANSACTION_ID);
            MDC.remove(SPAN_ID);
> 
my question is why remove TRANSACTION_ID here when trace == null？
thanks

**Comment by minwoo-jung** [comment]
Because the thread is recycled, the threadlocal value may remain.
And there is no transaction ID and span ID unless it is a tracing transaction.

**Comment by lhl4546** [comment]
Thanks for reply, but how can we pass TRANSACTION_ID from one thread which is in tracing transaction to another different thread, because there is no traceContext in the different thread so my TRANSACTION_ID will be removed

**Comment by minwoo-jung** [comment]
I didn't understand exactly what you were wondering.

If you're curious about tracing asynchronous logic, please ref [plugin guide](http://naver.github.io/pinpoint/plugindevguide.html#24-asynchronous-task)
