### ISSUE TITLE
Tracing CompletableFuture and ThreadPool Async Calls

### ISSUE THREAD

**Issue by AlphaWang** [naver/pinpoint#6095]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

Hi team,
The projects in my company are using `CompletableFuture.runAsync()` & `ThreadPoolExecutor` widely, but seems currently pinpoint cannot trace these kinds of async call, do we have plan to support it in future?

Not sure if we have a document to declare which kind of async calls are supported for now? As I know we support Spring `@Async`, anything else?

**Comment by emeroad** [comment]
Currently `@Async` is supported.
The pinpoint supports the following Spring Executor
```java
    private static final String[] DEFAULT_ASYNC_TASK_EXECUTOR = {
            "org.springframework.scheduling.concurrent.ConcurrentTaskExecutor",
            "org.springframework.core.task.SimpleAsyncTaskExecutor",
            "org.springframework.scheduling.quartz.SimpleThreadPoolTaskExecutor",
            "org.springframework.core.task.support.TaskExecutorAdapter",
            "org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor",
            "org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler",
            "org.springframework.jca.work.WorkManagerTaskExecutor",
            "org.springframework.scheduling.commonj.WorkManagerTaskExecutor"
    };
```
https://github.com/naver/pinpoint/issues/6095

**Comment by AlphaWang** [comment]
Thank you @emeroad . Do we have plan to support CompletableFuture?
