### ISSUE TITLE
Excluding classes from stack

### ISSUE THREAD

**Issue by davide-parini** [naver/pinpoint#6099]
I know that classes can be profiled with `profiler.include` property. I am interested in profiling all the classes of my Foo organization with a configuration like `profiler.include=org.foo.*`. After setting this up, I notice that a particular method is called many and many times (something like a logging utility I have developed, that I don't need to profile) and that it is flooding my call stacks in pinpoint with hundreds of useless entries. This makes the whole call stack useless, and causes a huge waste of disk space!

Is there a way to filter out a particular class or method? i would like to profile everything in `org.foo.*` except `org.foo.UselessUtil`.

**Comment by davide-parini** [comment]
No way to do this?

**Comment by RoySRose** [comment]
Hello, @davide-parini 
Currently, I don't think there isn't any by looking at the code (ProfilableClassFilter.java and some related files)

I think the feature can be easily added with a few modifications. 
It would be a good place to start contribution :)

**Comment by emeroad** [comment]
I think it's better to set the options in more detail.

`org.foo.*` -> `org.foo.service.acount.*,org.foo.controller.user.*`

**Comment by davide-parini** [comment]
Thank you @RoySRose, I think i will start contributing then. :-)

**Comment by davide-parini** [comment]
> 
> 
> I think it's better to set the options in more detail.
> 
> `org.foo.*` -> `org.foo.service.acount.*,org.foo.controller.user.*`

That would be preferable but "whitelisting" packages is not a solution in our case. We have to much variety and new packages popping out. The risk of lacking something is too high.
