### ISSUE TITLE
Issue to Build Pinpoin-flink Job

### ISSUE THREAD

**Issue by josephthanaraja** [naver/pinpoint#6100]
Team,
I am trying to setup the flink job for my docker container and as part of it trying to build the pinpoint-flink-job Jar (build) but maven is not able to download the dependencies from the below paths(No path is available with navercorp). Could you please help me here to get flink jar or solve the Maven build with proper repo path. Appreciate your help!.

http://jcenter.bintray.com/com/navercorp/pinpoint
https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/com/navercorp
http://jcenter.bintray.com/com/navercorp/pinpoint
ttps://repository.jboss.org/nexus/content/repositories/thirdparty-releases/com/navercorp

Reference:-
https://github.com/naver/pinpoint-docker (Flink Configuration)
https://github.com/naver/pinpoint/blob/master/doc/application-inspector.md#application-inspector

**E. Build Pinpoint-flink and run the streaming job file created under target directory on the flink server.**

**Comment by josephthanaraja** [comment]
Can anyone help on this issue

**Comment by josephthanaraja** [comment]
do you have the proper URL to download the flink jar or build it from the GIUT repo using proper Maven repo path?

**Comment by emeroad** [comment]
First, you need to build the root.pom of the pinpoint.
After building, use `$ PINPOINT_DIR\flink\target\pinpoint-flink-job-XXX.jar`.

**Comment by josephthanaraja** [comment]
yes that is how I am trying to run the root pom file but not able to download any Pinpoint related jars from the above path. Even not able to see those "NAVERCORP" folder in those repo if I go manually to that path.

http://jcenter.bintray.com/com/navercorp/pinpoint
https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/com/navercorp
http://jcenter.bintray.com/com/navercorp/pinpoint

**Comment by josephthanaraja** [comment]
Any update or can i get Flink jar for 1.8.4 version?

**Comment by RoySRose** [comment]
@josephthanaraja 

What do you mean by navercorp folder?
I don't think building flink module requires such dependencies. 

It will be helpful if we can see the logs.

**Comment by josephthanaraja** [comment]
Parent and flink pom file has the dependency for those repo's (downloaded pinpoint 1.8.x).


 <parent>
        <artifactId>pinpoint</artifactId>
        <groupId>com.navercorp.pinpoint</groupId>
        <version>1.8.6-SNAPSHOT</version>
    </parent>


Example Maven Build Log:-
[INFO] Downloading from : http://repository.cloudera.com/artifactory/cloudera-repos/com/navercorp/pinpoint/pinpoint-collector/1.8.6-SNAPSHOT/pinpoint-collector-1.8.6-SNAPSHOT.pom
[INFO] Downloading from : http://maven.springframework.org/release/com/navercorp/pinpoint/pinpoint-collector/1.8.6-SNAPSHOT/pinpoint-collector-1.8.6-SNAPSHOT.pom
[INFO] Downloading from : http://repo.spring.io/libs-release-remote/com/navercorp/pinpoint/pinpoint-collector/1.8.6-SNAPSHOT/pinpoint-collector-1.8.6-SNAPSHOT.pom
[INFO] Downloading from : http://jcenter.bintray.com/com/navercorp/pinpoint/pinpoint-collector/1.8.6-SNAPSHOT/pinpoint-collector-1.8.6-SNAPSHOT.pom
[INFO] Downloading from : https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/com/navercorp/pinpoint/pinpoint-collector/1.8.6-SNAPSHOT/pinpoint-collector-1.8.6-SNAPSHOT.pom

**Comment by josephthanaraja** [comment]
did you get a chance to verify this issue
