### ISSUE TITLE
Does pinpoint supports Glassfish applications

### ISSUE THREAD

**Issue by immusk** [naver/pinpoint#6116]
Hi
@koo-taejin  

added the pinpoint agent on the glassfish server, can see the agent in the web, but not able to trace any data from it.

can you please suggest, do we require any other configuration to be changed?

**Comment by immusk** [comment]
I am getting the instance stats in inspector, but nothing related to transactions.
please find the attached config file, that is being used.
[pinpoint-config.txt](https://github.com/naver/pinpoint/files/3771019/pinpoint-config.txt)

**Comment by RoySRose** [comment]
@immusk

about only on the glassfish.
I'm not 100% sure. But so far I know, it's not supported yet.

**Comment by singhimayank** [comment]
@RoySRose any plans of it being supported in the near future, and is there any workaround using which i could get stats of my java application hosted on glassfish ?

**Comment by RoySRose** [comment]
@singhimayank 

no plans yet for the near future
