### ISSUE TITLE
pinpoint web latency issue

### ISSUE THREAD

**Issue by sg-h** [naver/pinpoint#6122]
안녕하세요 

pinpoint 1.7.1(web&collector) release 버전을 사용 중입니다

약 50개의 어플리케이션을 1년 정도 사용 중이며 그 사이 collector 데이터가 많아지고 

DB(hbase)에 쌓이는 양이 많아져서인지 web에서 application list가 늦게(3초~5초) 뜨는 현상과

5분 단위 트래킹 시 특정 application에서 타임아웃 혹은 아주 느리게 조회되는 현상이 있습니다

데이터가 많은 application이 아닌데도 말이죠..

별도로 데이터를 삭제하는 정책은 없는데 이 경우 효율적으로 개선할 수 있는 방법이 있을까요?

바쁘시겠지만 여유 되시면 답변 부탁드리겠습니다

감사합니다

------------------

Hello

I'm using pinpoint 1.7.1 (web & collector) release

We have been using about 50 applications for about a year with a lot of collector data in between.

If the amount of accumulation in the DB (hbase) increases, the application list appears late (3 to 5 seconds) on the web.

When tracking for 5 minutes, there is a timeout or a very slow query in a specific application.

Even though it's not an application with lots of data ...

There is no policy to delete data separately, but is there an effective way to improve it?

Busy but please reply if you can

Thank you

**Comment by emeroad** [comment]
아래를 확인해보세요

1. hbase majorcomption 수행 여부 점검
 - https://github.com/naver/pinpoint/blob/master/doc/faq.md#hbase-is-taking-up-too-much-space-which-data-should-i-delete-first
 - 데이터 파일 머지를 위해(읽기 성능에 관여) 주당 한번은 필요함
2. hbase의 성능 확인
 - memory, gc, cpu. etc...
3. web의 성능 확인
 - memory, gc, cpu. etc...

**Comment by sg-h** [comment]
서버 리소스에 대한 이슈는 없어서 첫번째 항목 한번 살펴 보겠습니다
감사합니다

**Comment by RoySRose** [comment]
@sg-h 

Please translate your questions in English for the community. Thank you
