### ISSUE TITLE
Agent NOT RUNNING when Setting up Collector&web in Windows , Hbase in Linux

### ISSUE THREAD

**Issue by krishnakumar9113** [naver/pinpoint#6125]
Hi,
I have set up Collector and web in Win 10 64bit machine using Apache Tomcat 9.0 , and Hbase was running in RedHatLinux.
When i start the Apache , all the success logs are popping up and running succesfully.

When i start the agent with a spring boot application , its failing with the below messages.PFA logs.txt [Agent Logs]

[logs.txt](https://github.com/naver/pinpoint/files/3771612/logs.txt)

Is there any predefined steps for configuring collector&web in one environment and HBase in another. 
I have set the below properties to REdhat Linux system IP
1.hbase.client.host in hbase.properties
2.cluster.zookeeper.address in pinpoint-web.properties,pinpoint-collector.properties

Because when i ran collector and web in win 10 with hbase in the same system using Cygwin ,its working fine.

**Comment by zifeihan** [comment]
> Hi,
> I have set up Collector and web in Win 10 64bit machine using Apache Tomcat 9.0 , and Hbase was running in RedHatLinux.
> When i start the Apache , all the success logs are popping up and running succesfully.
> 
> When i start the agent with a spring boot application , its failing with the below messages.PFA logs.txt [Agent Logs]
> 
> [logs.txt](https://github.com/naver/pinpoint/files/3771612/logs.txt)
> 
> Is there any predefined steps for configuring collector&web in one environment and HBase in another.
> I have set the below properties to REdhat Linux system IP
> 1.hbase.client.host in hbase.properties
> 2.cluster.zookeeper.address in pinpoint-web.properties,pinpoint-collector.properties
> 
> Because when i ran collector and web in win 10 with hbase in the same system using Cygwin ,its working fine.

your agent can't connect the collector server. please check your pinpoint.config "profiler.collector.ip" configuration correct ,or your collector service are working normally.
