### ISSUE TITLE
Unable to see call link

### ISSUE THREAD

**Issue by storm0816** [naver/pinpoint#6127]
Just after installation, several services have been added, but the call link cannot be seen.

![image](https://user-images.githubusercontent.com/23227952/67666481-d716e500-f9a6-11e9-90ce-8ea4168bdbe6.png)

**Comment by RoySRose** [comment]
@storm0816 

is Pinpoint-agent attached to all of your services?

**Comment by storm0816** [comment]
> @storm0816
> 
> is Pinpoint-agent attached to all of your services?

Thank you for your reply.

Already installed. Do you have any special settings? Our program is spring cloud application

**Comment by storm0816** [comment]
@RoySRose 
Thank you for your reply.
Already installed. Do you have any special settings? Our program is spring cloud application

**Comment by RoySRose** [comment]
@storm0816 

Please check this issue if it concerns yours #5696
