### ISSUE TITLE
Could you convert the collector to spring boot application or add only spring actuator?

### ISSUE THREAD

**Issue by gwagdalf** [naver/pinpoint#6129]
Today's deview presentation was so good. 
I could feel the craftsmanship digging deep into the observability area.

It was suggested at the end of the presentation and it's feedback was positive.

Could you convert the collector to **spring boot application** or add only **spring actuator**?

If so, setting monitor of the pinpoint-collector will be very easy.

**Comment by RoySRose** [comment]
@gwagdalf 

Thank you for listening to our presentation, hope it helped you in some way.
As mentioned at the last of the presentation. We have plans to convert to spring boot application. 
Since the next release is imminent, we are considering to be applied to the release after the next one.
