### ISSUE TITLE
Servicenow integration 

### ISSUE THREAD

**Issue by rguptarg** [naver/pinpoint#6131]
Hi Team,

We are planning to implement PINPOINT in our infra for APM. so we want PINPOINT integration with Service now for ticketing. 

So please let me, is it possible at PINPOINT end. can we forwards SNMP traps to any other tools ?

**Comment by RoySRose** [comment]
Hello, @rguptarg 

I didn't know `Servicenow` until you mentioned it.
Maybe in the future, but currently, we don't provide any kind of services.
