### ISSUE TITLE
Many requests in the catalina.out log file are wrong when Tomcat is monitored by pinpoint, but the wrong requests are not found in pinpoint monitoring？

### ISSUE THREAD

**Issue by 11628** [naver/pinpoint#6135]
Many requests in the catalina.out log file are wrong when Tomcat is monitored by pinpoint, but the wrong requests are not found in pinpoint monitoring.

for example：
2019-10-31 07:59:31.341 INFO  [] [] smnyl.xxap.intg.service.impl.ApInvoicesInterfaceIntgServiceImpl - processInvoiceAndJounal  Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool

**Comment by Xylus** [comment]
Hi @11628 
Are these wrong requests showing up as success?
If so, if you're using Spring and catching these errors in your Spring beans (ie controller, service, components etc), you might need to set `profiler.spring.beans.mark.error` to `true` in your agent's *pinpoint.config* file.
The default `profiler.spring.beans.mark.error=false` will not mark any requests that threw an exception but was handled in spring beans (ie. caught and not rethrown) as they are seen as properly handled.

**Comment by 11628** [comment]
@Xylus Thank you. I'll try it.
