### ISSUE TITLE
Pinpoint 1.8.5 with SpringBoot embedded Tomcat 8 captures only internal request, BUT not multi-application http call tracing

### ISSUE THREAD

**Issue by gotoworld** [naver/pinpoint#6139]
#### Enviroment:
Pinpoint: 1.8.5
Jdk: 1.8
Springboot: 2.0.6.RELEASE
docker: 18.09.6
kuberneters: 1.14
BaseDockerImage: apline+JDK8

#### Describe your problem**
Pinpoint 1.8.5 with SpringBoot embedded Tomcat 8 captures only internal request, BUT not multi-application http call tracing

Only show single application internal request, as below
![image](https://user-images.githubusercontent.com/8605471/68098083-b0503580-fef5-11e9-83da-439b54acd23c.png)

we have 23 applications in cluster,  they call each other by http interface (springboot), BUT not show the tracing map in the graph,  does that mean Pinpoint not support the invoke between multiple application when it use https interface (Springboot) ? 

* What we expect is below, as Pinpoint office sample showing:
![image](https://user-images.githubusercontent.com/8605471/68098309-ee9a2480-fef6-11e9-9d12-393781cb7b3a.png)

**Comment by koo-taejin** [comment]
hi @gotoworld 

Target applications must also have a pinpoint agent installed to enable remote traceability.

Please check it first.

thanks :)

**Comment by gotoworld** [comment]
> hi @gotoworld
> 
> Target applications must also have a pinpoint agent installed to enable remote traceability.
> 
> Please check it first.
> 
> thanks :)

--------------------------------------------------------------------------------------------------
Thanks a lot :)

Actually the target application have been installed pinpoint agent too.  all 23 applications are all installed.

now below showing the trace for application service-usercenter, which is the target of service-account.
![image](https://user-images.githubusercontent.com/8605471/68658656-d10d3080-0570-11ea-8b02-2a46ca82a3a3.png)

**Comment by gotoworld** [comment]
Pinpoint 1.8.5 with SpringBoot embedded Tomcat 8 captures only internal request, BUT not multi-application with http call tracing

**Comment by jaehong-kim** [comment]
@gotoworld 
Which HTTP client do you use?

**Comment by gotoworld** [comment]
> @gotoworld
> Which HTTP client do you use?

SpringBoot with Feign

**Comment by gotoworld** [comment]
Pinpoint with SpringBoot with embedded Tomcat 8 captures only first request

**Comment by gotoworld** [comment]
Pinpoint Server Map only show single application,  which is architecture by springboot (http calling, feign)

**Comment by jaehong-kim** [comment]
@gotoworld 
Feign [apache httpclient ?](https://github.com/OpenFeign/feign/tree/master/httpclient)

**Comment by gotoworld** [comment]
> @gotoworld
> Feign [apache httpclient ?](https://github.com/OpenFeign/feign/tree/master/httpclient)

yes,  as follow:

<artifactId>httpclient</artifactId>
<groupId>org.apache.httpcomponents</groupId>

**Comment by jaehong-kim** [comment]
@gotoworld 
Feign HttpClient(ApacheHttpClient) is traced.
![apache-httpclient-1](https://user-images.githubusercontent.com/10043788/74502756-e8720600-4f31-11ea-80d1-0d046c9019ac.PNG)

Please check the Call Stack.
