### ISSUE TITLE
[question] Would the collector & web of version 1.9 be compatible with the agents of version 1.8.5+

### ISSUE THREAD

**Issue by yjqg6666** [naver/pinpoint#6140]
Would the collector & web of version 1.9 be compatible with the agents of version 1.8.5+ for partial update?  And the compatibility table could be updated.

**Comment by koo-taejin** [comment]
hi @yjqg6666 

Collector and web can handle agent that version is lower than it.
It is our policy.
So what you're comment is supported.

1.9.x hasn't been released yet, so we'll update it when it's released.

thanks. :)
