### ISSUE TITLE
pinpoint specification inquiry

### ISSUE THREAD

**Issue by SOMINSUB** [naver/pinpoint#6141]
translated
https://github.com/naver/pinpoint/issues/6141#issuecomment-549656934

original query
```
안녕하세요.

pinpoint 1.7.3 을 설치 및 테스트하려고 하는 중 궁금한 사항이 생겨 질문을 올립니다.
( https://naver.github.io/pinpoint/1.7.3/quickstart.html )

설치 요구 사항 중 아래와 같이 jdk 6~8까지 모두 설치되어야 한다고 나와있습니다. 

Requirements
In order to build Pinpoint, the following requirements must be met:
JDK 6 installed (jdk1.6.0_45 recommended)
JDK 7 installed (jdk1.7.0_80 recommended)
JDK 8 installed
JAVA_HOME environment variable set to JDK 7+ home directory.
JAVA_6_HOME environment variable set to JDK 6 home directory.
JAVA_7_HOME environment variable set to JDK 7 home directory.
JAVA_8_HOME environment variable set to JDK 8 home directory.
QuickStart supports Linux, OSX, and Windows.

(문서와 달리 JDK 9 도 설치해야하는 것 같습니다.)

여기서 궁금한 점은 pinpoint agent side에서도 jdk 6 ~ 8을 설치해야하는지 입니다.
https://github.com/naver/pinpoint/blob/master/doc/plugin-dev-guide.md
https://github.com/naver/pinpoint/blob/master/doc/techdetail.md  를 확인해보아도 명확하게 모르겠네요..

업무 중에 바쁘시겟지만, 여유가 되시고 답변이 가능한 부분라면 답변 부탁드립니다.

감사합니다.
```

**Comment by RoySRose** [comment]
@SOMINSUB 

Hello, please translate your issue into English for the community.

I think the document is not updated for 1.8.4.
You don't have to install any additional JDK for the agent side.

Thank you :)

**Comment by SOMINSUB** [comment]
@RoySRose 
The guide document states that JDK 6 ~ 9 is a required installation. 
I'm curious about why it's a JDK 6 ~ 9 mandatory installation.

Can't I install and use only one JDK on the collector and agent side?
For example, run with only JDK 8 only one.

If possible, please provide a technical answer.

Thank you.

**Comment by emeroad** [comment]
Multiple JVMs are required to ensure full binary compatibility.

If installation is difficult, just download the binary file.
https://github.com/naver/pinpoint/releases

**Comment by SOMINSUB** [comment]
@emeroad 
Thank you for your reply.
