### ISSUE TITLE
pinpoint already supports log4j2, "per-request logging" how to configure log4j2?

### ISSUE THREAD

**Issue by wajika** [naver/pinpoint#6143]
I configured log4j2.xml, but it didn't work
http://naver.github.io/pinpoint/perrequestfeatureguide.html#per-request-logging

log4j2.xml
```

<Appenders>
	<RollingRandomAccessFile name="run" fileName="${LOG_HOME}/run.log" filePattern="${LOG_HOME}/run.%d{yyyy-MM-dd}-%i.log.gz" append="true">
	<PatternLayout pattern="%d{yyyy-MM-dd HH:mm:ss} [TxId : %X{PtxId} , SpanId : %X{PspanId}] %m%n""/>
</Appenders>
```

**Comment by minwoo-jung** [comment]
@wajika
Hi~ What version do you use?
log4j2 has been supported since version 1.8.5.

**Comment by wajika** [comment]
> @wajika
> Hi~ What version do you use?
> log4j2 has been supported since version 1.8.5.

I use version 1.8.5

**Comment by wajika** [comment]
I added pinpoint-log4j2-plugin in Java code and used [txid:% X {ptxid}, spanid:% X {pspanid}] in log4j2.xml.
Ptxid and Pspanid are empty in the output log file

```
                <dependency>
                   <groupId>pinpoint</groupId>
                   <artifactId>pinpoint-log4j2-plugin</artifactId>
                   <version>1.8.5</version>
                </dependency>

```

**Comment by wajika** [comment]
Does plugin not support the Json Layout function?     
        ```
         <JsonLayout compact="true" eventEol ="true" complete="true">
                                <KeyValuePair key="timestamp" value="$${date:yyyy-MM-dd HH:mm:ss}" />
                                <KeyValuePair key="TxId" value="%X{PtxId}" />
                                <KeyValuePair key="SpanId" value="%X{PspanId}" />
                        </JsonLayout>
```

**Comment by minwoo-jung** [comment]
@wajika
I will take a look for jsonLayout.

**Comment by wajika** [comment]
@minwoo-jung
I have tested logback.xml and log4j2.xml respectively, and have successfully printed traceid.
However, some packages are still null, and both null and non null are printed together.

**Comment by minwoo-jung** [comment]
@wajika
If some logic doesn't print, you should see if the pinpoint tracing in the logic process.
Inferring only by the name of TaskConfig, you should check whether it is asynchronous logic and whether it is a library that supports asynchronous tracing.

And did you check sampling rate?

If possible, you might want to debug the log4j2 interceptor.

**Comment by wajika** [comment]
@minwoo-jung

I see other people printing traceids in this way
`<PatternLayout pattern="%d{yyyy-MM-dd HH:mm:ss} [%-5p](%-30c{1}) [${sys:pinpoint.applicationName} TxId : ${ctx:PtxId} , SpanId : ${ctx:PspanId}] %m%n"/>`
Does it mean that all the pinpoint memory data information can be obtained in the PatternLayout block?

I put ${ctx:PtxId}, ${ctx:PspanId}, and the output log file is still null.
I have an idea, if traceid has been generated in pinpoint, why can't I directly output the exception information of pinpoint to log4j2.xml(log file path).

```
eg.
<PatternLayout pattern="%d{yyyy-MM-dd HH:mm:ss} [%-5p](%-30c{1}) [${sys:pinpoint.applicationName} TxId : ${sys:pinpoint.PtxId} , SpanId : ${sys:pinpoint.PspanId}] %m%n"/>
```

**Comment by wajika** [comment]
Simply put, I want to write the abnormal information obtained by pinpoint to the log file via javaagent.

**Comment by minwoo-jung** [comment]
${sys:pinpoint.PspanId}. ${sys:pinpoint.PtxId} This will not print.
PspanId and PtxId can only be output to the thread traced by the pinpoint.

**Comment by wajika** [comment]
@minwoo-jung 
${sys:pinpoint.PspanId} and ${sys: pinpoint. Ptxid} is just my assumption.

I don't understand. traceid has been saved in MDC.
Then use `< patternlayout pattern = "% d {yyyy m m DD HH: mm: SS} [% - 5p] (% - 30C {1}) [txid:% X {ptxid}, spanid:% X {pspanid}]% m% n" "/ >`
Why do ptxid and pspanid still output null values?
What changes do I need to make to my Javacode?
