### ISSUE TITLE
SPRING_BEAN plugin traces too many traces on Gpath of groovy.

### ISSUE THREAD

**Issue by messi-gao** [naver/pinpoint#6162]
We use [Gpath ](https://groovy-lang.org/processing-xml.html#_gpath)of groovy to operate XML.
In the call tree page,there are many traces about getProperty() and getMetaClass(),Could you give me some advices not to trace them,it really takes much space but useless.

![image](https://user-images.githubusercontent.com/24312100/68461771-026ebf00-0246-11ea-8723-0f294cae02e8.png)

**Comment by minwoo-jung** [comment]
Unfortunately,
If you profiled with profiler.spring.beans = true in the pinpoint config file, you can't reduce the profiling times. 

If I look at the stack, it doesn't seem to be a very important class, so you can remove that class from profiling. Check the following settings in the pinpoint config file.
```

# Examples
# profiler.spring.beans.1.scope=component-scan
# profiler.spring.beans.1.base-packages=com.foo, com.bar
# profiler.spring.beans.1.name.pattern=.*Foo, regex:.*Bar, antstyle:*Controller
# profiler.spring.beans.1.class.pattern=
# profiler.spring.beans.1.annotation=org.springframework.stereotype.Controller,org.springframework.stereotype.Service,org.springframework.stereotype.Repository
#
# profiler.spring.beans.2.scope=post-processor
# profiler.spring.beans.2.base-packages=com.foo
# profiler.spring.beans.2.name.pattern=
# profiler.spring.beans.2.class.pattern=antstyle:com.foo.repository.*Repository, antstyle:com.foo.Service.Main*
# profiler.spring.beans.2.annotation=

profiler.spring.beans.1.scope=component-scan
profiler.spring.beans.1.base-packages=
profiler.spring.beans.1.name.pattern=
profiler.spring.beans.1.class.pattern=
profiler.spring.beans.1.annotation=org.springframework.stereotype.Controller,org.springframework.stereotype.Service,org.springframework.stereotype.Repository

```

To reduce the number of profiling, you must implement the interceptor yourself and use the scope function.
