### ISSUE TITLE
Direct buffer and Mapped Buffer

### ISSUE THREAD

**Issue by tonfay** [naver/pinpoint#6183]
Direct buffer count chart
Direct buffer memory chart
Mapped Buffer Count chart
Mapped Buffer Memory  chart

What do these four views mean?

**Comment by koo-taejin** [comment]
Please check this [link](https://stackoverflow.com/questions/15657837/what-is-mapped-buffer-pool-direct-buffer-pool-and-how-to-increase-their-size)
