### ISSUE TITLE
Fully Changed UI

### ISSUE THREAD

**Issue by koo-taejin** [naver/pinpoint#6184]
#### description
* servermap
![servermap](https://user-images.githubusercontent.com/10057874/68727830-dae27280-0608-11ea-9e98-c5c904f6b98c.jpg)

* distributed calltree
![callstack](https://user-images.githubusercontent.com/10057874/68727854-ee8dd900-0608-11ea-8185-f2fc2fd101fe.jpg)

* inspector
![inspector](https://user-images.githubusercontent.com/10057874/68727863-f483ba00-0608-11ea-99f8-217aa6329d14.jpg)

---

#### Initialization
- #4640
#### Features
- #4849
- #4861
- #4975
- #5051
- #5159
- #5446 
- #5448
- #5470
- #5493
- #5572
- #5642
- #5667
#### Bug Fixes
- #4718
- #4946
- #4955
- #4984
- #5001
- #5068
- #5087
- #5321
- #5565
- #5623
- #5658
- #6130
#### Performance Improvements
- #4871
#### Code Refactoring
- #5307
#### Chores
- #4839
- #5420

**Comment by 52766365** [comment]
新UI了嘛 ？ 我部署后没感觉界面和颜色有变化呀

**Comment by koo-taejin** [comment]
@52766365 

Sorry we don't know Chinese.
