### ISSUE TITLE
How collect detail heap usage?

### ISSUE THREAD

**Issue by joongsoo** [naver/pinpoint#6185]
Pinpoint is provide heap usage in inspector.
But inspector is not provide detail heap usage like new, old gen ussage.
Is possible collect to detail usage?

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

**Comment by koo-taejin** [comment]
@joongsoo 

We are already collecting that data.

https://github.com/naver/pinpoint/blob/master/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/grpc/GrpcStatMessageConverter.java#L155

But we do not show.
It is still difficult to determine whether it is good to show this information.

thanks.

**Comment by joongsoo** [comment]
Thanks for your kind reply. close this issue.
