### ISSUE TITLE
Can you provide a description of the data structure?

### ISSUE THREAD

**Issue by jefry86** [naver/pinpoint#6189]
I am going to use grpc to develop go agent,Can you provide a description of the data structure?

**Comment by koo-taejin** [comment]
hi @jefry86 

Wow, It's a great suggetion :).

The data structure is located at:

https://github.com/naver/pinpoint/tree/master/grpc/src/main/proto

Span can send to port 9993

Stat can send to port 9992

Agent and Metadata can send to port  9991.

Please feel free to let me know if I can help you.
I'll try to help as much as I can.

If you are successful in passing data to the collector using go language, please share that example and it will be very helpful for us.

thanks. :)

**Comment by jefry86** [comment]
> hi @jefry86
> 
> Wow, It's a great suggetion :).
> 
> The data structure is located at:
> 
> https://github.com/naver/pinpoint/tree/master/grpc/src/main/proto
> 
> Span can send to port 9993
> 
> Stat can send to port 9992
> 
> Agent and Metadata can send to port 9991.
> 
> Please feel free to let me know if I can help you.
> I'll try to help as much as I can.
> 
> If you are successful in passing data to the collector using go language, please share that example and it will be very helpful for us.
> 
> thanks. :)

I have find grpc proto file；
Can you provide a description of the field?

**Comment by koo-taejin** [comment]
@jefry86 

Checking [pinpoint_plugin_development_guide.pdf](https://github.com/naver/pinpoint/files/3844799/pinpoint_plugin_development_guide.pdf) link may help 

For now, it's good to focus on local tracing.
In addition, if you send Span, SpanEvent first, and confirm that it is successfully traced, you may want to proceed with AgentInfo or Metdata work.

// Span => 20p
  ServiceType => 24p

// SpanEvent => 18p
   ServiceType => 24p
  AnnotationKey => 24p
  Sequence & Depth => 9p

![스팬이벤트](https://user-images.githubusercontent.com/10057874/68830210-6681ff00-06ee-11ea-8b1d-cf4ac50af21d.png)

Please feel free to let me know if I can help you.

thanks.

**Comment by jefry86** [comment]
@koo-taejin 
Thanks.
