### ISSUE TITLE
druid apitype show as "UNDEFINED" 

### ISSUE THREAD

**Issue by fionaliupw** [naver/pinpoint#6192]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

In my environment, callstack shows druid apitype is "UNDEFINED", not "DRUID".

Why ? If some data lost caused this issue?

Thank you.
![image](https://user-images.githubusercontent.com/26397343/68822077-e9915e00-06ca-11ea-920d-8deac53b756b.png)

**Comment by koo-taejin** [comment]
@fionaliupw 

Please check if the web version is 1.8.1+

thanks. :)

**Comment by emeroad** [comment]
Also check that the collector supports driud.
