### ISSUE TITLE
pinpoint-quickstart-web 에서 SMS 구현

### ISSUE THREAD

**Issue by leehowon** [naver/pinpoint#6209]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

안녕하세요
SMS 를 전송해야 하는 요구사항이 생겨서 SmsSender 를 직접 구현했습니다.
java 파일을 pinpoint/quickstart/web/src/main/java/... 위치에 넣어놓고 `start-web.sh` 실행하면 메이븐에서 클래스패스 문제로 컴파일이 되지 않네요.
어떻게 하면 좋을까요..?

**Comment by minwoo-jung** [comment]
@leehowon 
Hello, please translate your issue into English for the community.

Please show the log message.

**Comment by leehowon** [comment]
@minwoo-jung 
Sorry.
I solved it follow steps.

1. Add class `CustomSMSSender` into directory `$PINPOINT_HOME/web/src/.../alarm/`
2. build `pinpoint-web`
      1. `$ cd $PINPOINT_HOME/web`
      2. `$ ../mvnw install -DskipTests=true`
3. add bean `CustomSMSSender` to `applicationContext-batch.xml` from `pinpoint-quickstart-web`
4. start `pinpoint-quickstart-web`
