### ISSUE TITLE
Avoid agent restart upon collector restart

### ISSUE THREAD

**Issue by davide-parini** [naver/pinpoint#6220]
Hello, I see that after a collector restart, I need to restart all the monitored applications as well. If not, collector will not collect data again. Am I missing some configuration to prevent this? We are monitoring tens of application so this is quite an issue. I'm using pinpoint 1.8.5 for both collector and agents.

**Comment by minwoo-jung** [comment]
@davide-parini
Does it mean that the agent cannot reconnect with the collector when the collector is restarted?

**Comment by davide-parini** [comment]
Thank you @minwoo-jung, and sorry for being too generic with my question. I mean that traces are not collected properly until all agents are restarted. I can see a kind of "anonymous" trace, filled with API-METADATA-NOT-FOUND. Is there any way to workaround the need to restart?

**Comment by minwoo-jung** [comment]
1 Show the pinpoint log generated by the agent even though the collector is running.

2. 







If the agent is restarted while the collector is in the shutdown state, problems may occur. This is because the metadata of the agent is not saved.

**Comment by davide-parini** [comment]
I'm afraid our case is the second one.

So, to my understanding, in order for everything to work properly, the only requirement is that during agent startup the collector is running. If the collector is then restarted, no issues should happen, because agent metadata has already been stored in the collector database. Am i correct?

**Comment by minwoo-jung** [comment]
@davide-parini
Yes. You're right.

**Comment by dinesh4747** [comment]
Reference to the recent issue - https://github.com/naver/pinpoint/issues/6496

@koo-taejin @jaehong-kim @emeroad @Xylus @jefry86 - 

It looks functional issue where "synchronizing the start time value of agent is not in sync whole it reaches collector server" Can someone please shed some light or definite pointers on how to solve API-METADATA-NOT-FOUND issue which is almost deteriorating my usage of pinpoint in my cloud system and it seems like @jefry86 mentioned very clearly that "the startTime value of metadata is different"

It would be really great and kind if someone could help me address this.
