### ISSUE TITLE
Which version increases log4j2

### ISSUE THREAD

**Issue by tonfay** [naver/pinpoint#6237]
hi
Which version adds log4j2?
Is version 1.8.2 already supported?

I read this document and found that log4j2 is supported, but it does not say which version is supported
http://naver.github.io/pinpoint/perrequestfeatureguide.html#per-request-logging

**Comment by minwoo-jung** [comment]
Hi @tonfay 
It is supported from version 1.8.5.

**Comment by tonfay** [comment]
@minwoo-jung 
tks
