### ISSUE TITLE
API-METADATA-NOT-FOUND

### ISSUE THREAD

**Issue by jefry86** [naver/pinpoint#6238]
ApiMeta data:
Request PApiMetaData=apiId: 52 apiInfo: "Servlet Process" line: -1 type: 100

Span  data:
version: 1 transactionId { agentStartTime: 1574683461815 sequence:
4574 } spanId: -6752218818390780500 parentSpanId: -1 startTime: 1574752094545 elapsed: 27 apiId: 52 serviceType: 1010 acceptEvent { rpc: "/actuator/prometheus" endPoint: "10.22.31.91" remoteAddr: "10.22.31.81" } annotation { key: 46 value { intValue: 200 } } spanEvent { depth: 1 endElapsed: 27 serviceType: 1011 apiId: 51 } spanEvent { sequence: 1 depth: 2 startElapsed: 1 endElapsed: 26 serviceType: 5051 apiId: 20 } applicationServiceType: 1210 

Pinpoinot Ui's Method column shows API-METADATA-NOT-FOUND

**Comment by koo-taejin** [comment]
hi @jefry86 

If you delete Hbase data after requesting ApiMetadata, you can experience a  situation mentioned.
If not, please post the log if you can see an error message while putting the ApiMetadata in the collector.

thanks :)

**Comment by emeroad** [comment]
To simplify development, use API-TAG Annotation 
https://github.com/naver/pinpoint/blob/master/commons/src/main/java/com/navercorp/pinpoint/common/trace/AnnotationKey.java#L167
 - Just assign a string to the annotation.
```java
//    @Deprecated  // moved apiId to spanEvent and span. dump by int
//    API_DID(10, "API-DID"),
//    @Deprecated  // you should remove static API code. Use only API-DID. dump by int
//    API_ID(11, "API-ID"),
    // Dump api by string.
    AnnotationKey API = AnnotationKeyFactory.of(12, "API");
    AnnotationKey API_METADATA = AnnotationKeyFactory.of(13, "API-METADATA");
    AnnotationKey RETURN_DATA = AnnotationKeyFactory.of(14, "RETURN_DATA", VIEW_IN_RECORD_SET);
    AnnotationKey API_TAG = AnnotationKeyFactory.of(10015, "API-TAG");

```

**Comment by jefry86** [comment]
@koo-taejin @emeroad  thinks,I have found the solution to the problem, the startTime value of metadata is different

**Comment by dinesh4747** [comment]
@jefry86 @koo-taejin @emeroad  - I am facing the same issue API-METADATA-NOT-FOUND and It would be really if could you elaborate on how to make startTime value of metadata same, likewise what was the fixed you did which helped solving this.

Thanks for your extended help @jefry86 @koo-taejin @emeroad

**Comment by dinesh4747** [comment]
@koo-taejin @jefry86 - can someone pls show some direction on how to fix the api meta data not found issue... it would be really great if someone could share some insights to resolve it... @emeroad

**Comment by dinesh4747** [comment]
@jefry86 - It would be really great and helpful if you could shed some lights on how did you solve the issue " the startTime value of metadata is different",  As I am encountering the similar issue which blocks my critical deployments. https://github.com/naver/pinpoint/issues/6496

Appreciate your time and extended support here. @koo-taejin @emeroad

**Comment by dinesh4747** [comment]
@koo-taejin @jaehong-kim @emeroad @Xylus @jefry86 - Can someone please shed some light or definite pointers on how to solve API-METADATA-NOT-FOUND issue which is almost deteriorating my usage of pinpoint in my cloud system and it seems like @jefry86  mentioned very clearly that "the startTime value of metadata is different" 

It would be really great and kind if someone could help me address this.
