### ISSUE TITLE
Add User authentication for web component

### ISSUE THREAD

**Issue by JangNum** [naver/pinpoint#6240]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

I want to add user authentication to the web component of pinpoint by rewriting the source code, how should it be achieved?

**Comment by minwoo-jung** [comment]
Hello @JangNum 
duplicated issue #4085

**Comment by JangNum** [comment]
> Hello @JangNum
> duplicated issue #4085

thanks for your reply
