### ISSUE TITLE
Add CompletableFuture Plugin

### ISSUE THREAD

**Issue by jaehong-kim** [naver/pinpoint#6244]
## Add CompletableFuture Plugin
It is for tracking java.util.concurrent.CompletableFuture objects.

**Comment by dinesh4747** [comment]
@jaehong-kim  - Does this require any specific config change to impose completablefuture plugin tracing? and we are also using Executors.newWorkStealingPool thread executor - I had tried with latest version without much luck - Any insights would be highly appreciated
