### ISSUE TITLE
pinpoint-Realtime Active Thread Chart 显示 NOT FOUND

### ISSUE THREAD

**Issue by 52766365** [naver/pinpoint#6247]
![微信图片_20191127150726](https://user-images.githubusercontent.com/20806983/69783234-0ca12f00-11ee-11ea-8810-89a1cf412369.jpg)
![QQ图片20191128144859](https://user-images.githubusercontent.com/20806983/69783450-876a4a00-11ee-11ea-8b67-3a1ed78b7ed7.png)
版本1.8.4
想问下这个实时活动线程图数据存在那张表里，或者调用了什么端口，为何会NOT FOUND

**Comment by RoySRose** [comment]
Hello, @52766365 

please note that when you write a comment on a GitHub issue,
it's open to the community, it would be great if everyone can understand.
All contributors would be grateful if you can translate it.

please consider using just English. Thanks ;)
