### ISSUE TITLE
New web ui is not showing up after upgrading to 2-0 release

### ISSUE THREAD

**Issue by immusk** [naver/pinpoint#6252]
Hi Team

@koo-taejin 

after upgrading to 2-0 Release Version.
Still I am seeing old UI of web, I am not seeing the new web version in UI, which you have specified in the release notes.

can you please help here.

Thanks

**Comment by koo-taejin** [comment]
hi @immusk 

Do you use your own builds?  or use the war file uploaded in the release notes?

If you build your own, you must use the -Pv2 option at build time.
(ex: mvnw install -Pv2)
After all builds have been completed, connect to url with `/v2`.

If you use the uploaded war file, it seems that the currently uploaded file is uploaded without the v2 function.
I will inform you when it is changed.

thanks :)

**Comment by koo-taejin** [comment]
@immusk 

I have been changed war file in the release notes.

thanks.

**Comment by immusk** [comment]
@koo-taejin it worked, able to see the new UI now.

**Comment by koo-taejin** [comment]
@immusk 

If you have any problems, please report it.

thanks. :)

**Comment by dinesh4747** [comment]
@koo-taejin - I have just downloaded the war file from release notes yesterday, but i couldn't see the new WEB UI. whether I need to /v2 to get it. Even i tried hitting url like http://localhost:8080/v2/

But that didnt help, great if you could help me on that.

**Comment by koo-taejin** [comment]
hi @dinesh4747 

![rc war2](https://user-images.githubusercontent.com/10057874/70596888-4df00080-1c2a-11ea-96cb-efc75d0f938d.jpg)

I checked with release version and it works fine.

If you have a context path, test it by including it.

thanks

**Comment by dinesh4747** [comment]
@koo-taejin -  Thanks for your quick response, In which xml file (whether i need to add it in applicationContext-web.xml) I need to include and test it .

**Comment by dinesh4747** [comment]
@koo-taejin - My bad I am not hitting with right end point and now issue is fixed as i could able to access the newer version of web via http://localhost:8080/v2/main/

Nevertheless Thanks @koo-taejin for helping me out on this

**Comment by koo-taejin** [comment]
@dinesh4747 I am glad to hear that. :)
