### ISSUE TITLE
Any update on pinpoint supporting Nodejs

### ISSUE THREAD

**Issue by immusk** [naver/pinpoint#6256]
Hi Team,

Do we have any update on the pinpoint supporting Nodejs

Thanks 😄

**Comment by RoySRose** [comment]
Hello, @immusk 

Well, actually it's not an update. But, it's planned to be open-sourced before the end of the year.

**Comment by immusk** [comment]
@RoySRose 

Thanks, waiting for it to be released... 😄

**Comment by RoySRose** [comment]
@immusk 
Follow us on [twitter](https://twitter.com/Pinpoint_APM). You can get the latest new on Pinpoint.

**Comment by dinesh4747** [comment]
@RoySRose - Any updates on official release about Node.js plugin

**Comment by RoySRose** [comment]
Hello, @dinesh4747 

Well, the last plan I've heard was release in early Jan.

@intojun any updates?

**Comment by dinesh4747** [comment]
@RoySRose @immusk  - can someone pls share the latest update on the availability of nodejs plugin
