### ISSUE TITLE
 why the Application node shows “UNKNOWN GROUP” in server map view?

### ISSUE THREAD

**Issue by JangNum** [naver/pinpoint#6265]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

The Application Node has pulled up the pinpoint agent process,and the collector address in pinpoint.config also is right. But the application node shows “UNKNOWN GROUP” in server map view,why?

**Comment by minwoo-jung** [comment]
The causes can be many.
It would be nice to show us more information.

The first thing I think is that the metadata of the agent may not be saved properly.
First look at the logs of the agent and collector.

**Comment by nikhilpatil29** [comment]
I am facing the same issue.
