### ISSUE TITLE
how to trace the vertx application business node

### ISSUE THREAD

**Issue by zifeihan** [naver/pinpoint#6271]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

hello, i use vertx offical example to test vertx plugin(link:https://github.com/vert-x3/vertx-examples/tree/master/spring-examples/spring-example). but the trace detail don’t have application business node. eg: no have spring service node, as follows. what can i do for the pinpoint  trace the business node. 
![image](https://user-images.githubusercontent.com/16839929/70110838-43ae8f00-168b-11ea-83bd-56be6a846cd2.png)
![image](https://user-images.githubusercontent.com/16839929/70110913-8cfede80-168b-11ea-9ede-1abdcda45fbe.png)

**Comment by jaehong-kim** [comment]
@zifeihan 
Good setting
* profiler.vertx.bootstrap.main
* profiler.vertx.handler.base-packages

Recommended setting
* profiler.vertx.http.server.request-handler.method.name
  * ServerVerticle(https://github.com/vert-x3/vertx-examples/blob/master/spring-examples/spring-example/src/main/java/io/vertx/examples/spring/verticle/ServerVerticle.java) is difficult to configure because it uses lambda functions.
  * StaticServer(https://github.com/vert-x3/vertx-examples/blob/master/spring-examples/springboot-example/src/main/java/io/vertx/example/StaticServer.java) is a more common pattern.
Use the default setting depending on your version of Vert.x.

**Comment by zifeihan** [comment]
> @zifeihan
> Good setting
> 
> * profiler.vertx.bootstrap.main
> * profiler.vertx.handler.base-packages
> 
> Recommended setting
> 
> * profiler.vertx.http.server.request-handler.method.name
>   
>   * ServerVerticle(https://github.com/vert-x3/vertx-examples/blob/master/spring-examples/spring-example/src/main/java/io/vertx/examples/spring/verticle/ServerVerticle.java) is difficult to configure because it uses lambda functions.
>   * StaticServer(https://github.com/vert-x3/vertx-examples/blob/master/spring-examples/springboot-example/src/main/java/io/vertx/example/StaticServer.java) is a more common pattern.
>     Use the default setting depending on your version of Vert.x.

sorry, my fault ,this setting, "profiler.vertx.http.server.request-handler.method.name=io.vertx.examples.spring.verticle.RouterImpl.handle" in (https://github.com/zifeihan/vertx-examples/blob/master/spring-examples/spring-example/src/main/java/io/vertx/examples/spring/verticle/RouterImpl.java), i notice (https://github.com/vert-x3/vertx-examples/blob/master/spring-examples/spring-example/src/main/java/io/vertx/examples/spring/verticle/ServerVerticle.java) is lambda functions, so    i rewrited the code. i think the root is pinpoint no enhance vertx "event bus"  of can‘t trace business.  other suggestion of trace async thread, i think we can enhance Runnable instance and "java.util.concurrent.ThreadPoolExecutor", through trigger function  instrumentation.retransformClasses(Class.forName("java.util.concurrent.ThreadPoolExecutor")) ,we can enhance java.util.concurrent.ThreadPoolExecutor.
