### ISSUE TITLE
Display memory pool

### ISSUE THREAD

**Issue by dawidmalina** [naver/pinpoint#628]
Add ability to display memory pool not only heap and non heap memory usage.

**Comment by dawidmalina** [comment]
Links that can help:
http://jansipke.nl/getting-metrics-from-the-java-virtual-machine-jvm/
https://github.com/stagemonitor/stagemonitor/blob/master/stagemonitor-jvm/src/main/java/org/stagemonitor/jvm/JvmPlugin.java

**Comment by dawidmalina** [comment]
Thx. I will also migrate com.codahale.metrics to io.dropwizard.metrics version 3.1.2

**Comment by dawidmalina** [comment]
Finally I decided to gather not only usage metrics but rather dedicated values (max and use). What I would like to propose is to get rid of heap non heap and instead use this new (or at least add this new):
- New Generation values (`jvmPoolNewGenUsed`, `jvmPoolNewGenMax`) combined with GC values (`jvmGcNewCount`, `jvmGcNewTime`) on one graph.
- Old Generation values (`jvmPoolOldGenUsed`, `jvmPoolOldGenMax`) combined with GC values (`jvmGcOldCount`, `jvmGcOldTime`) on one graph.
- Survivor Space values (`jvmPoolSurvivorSpaceUsed`, `jvmPoolSurvivorSpaceMax`) on one graph.
- Perm Generation values (`jvmPoolPermGenUsed`, `jvmPoolPermGenMax`) on one graph (if java < 1.8).
- Metaspace values (`jvmPoolMetaspaceUsed`, `jvmPoolMetaspaceMax`) on one graph (if java >= 1.8).
- CodeCache values (`jvmPoolCodeCacheUsed`, `jvmPoolCodeCacheMax`) on one graph.

**Comment by dawidmalina** [comment]
@denzelsN do you think gui part will be complecated? Backend part is already merged.

**Comment by denzelsN** [comment]
sorry. I'll check. and discuss with UX designers.

**Comment by Xylus** [comment]
@dawidmalina It looks like the code for storing (collector) and reading (web) from hbase is not implemented yet.
There's a plan to overhaul `AgentStat` after 1.5.2 is released (within a week or two). It will be a good idea to implement the backend code then as well.

**Comment by Xylus** [comment]
Backend + API implemented in 1.6.0 - #1533
