### ISSUE TITLE
I can not package ,I tryed update the project ,rebuild ,but not work . 

### ISSUE THREAD

**Issue by RowinaDu** [naver/pinpoint#6307]
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.8.0:npm (npm install) on project pinpoint-web: Failed to run task: 'npm install' failed. java.io.IOException:
Cannot run program "D:\apm\pinpoint\node_install\node-v10.16.3\node\node.exe" (in directory "D:\apm\pinpoint\web\target"): CreateProcess error=193, %1 不是有效的 Win32 应用程序。 -> [He
lp 1]

**Comment by minwoo-jung** [comment]
@RowinaDu
Displaying the full log will help you find the problem.

and please ref : #3810 #6300

**Comment by geekMessi** [comment]
What's the problem with that bug ? I encountered the same issue that I complied failed suddenly !
@minwoo-jung

**Comment by minwoo-jung** [comment]
@geekMessi @RowinaDu
What version of pinpoint are you using?

**Comment by minwoo-jung** [comment]
@geekMessi
I don't know what the exact cause is, but we think it is caused by the low frontend-maven-plugin version.
**Displaying the full log will help you find the problem**

**Comment by geekMessi** [comment]
> I don't know what the exact cause is, but we think it is caused by the low frontend-maven-plugin version.
@minwoo-jung 
That's the detail log of compiling.
```
[WARNING] npm WARN deprecated json3@3.2.6: Please use the native JSON object instead of JSON 3
[WARNING] npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
[WARNING] npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
[ERROR] npm ERR! Linux 2.6.32-573.7.1.el6.x86_64
[ERROR] npm ERR! argv "/home/wpd/.gitlab-runner/builds/ae2980d9/0/XXX/pinpoint/web/target/node/node" "/home/wpd/.gitlab-runner/builds/ae2980d9/0/XXX/pinpoint/web/target/node/node_modules/npm/bin/npm-cli.js" "install"
[ERROR] npm ERR! node v5.11.1
[ERROR] npm ERR! npm  v3.9.6
[ERROR] npm ERR! code EMISSINGARG
[ERROR] 
[ERROR] npm ERR! typeerror Error: Missing required argument #1
[ERROR] npm ERR! typeerror     at andLogAndFinish (/home/wpd/.gitlab-runner/builds/ae2980d9/0/XXX/pinpoint/web/target/node/node_modules/npm/lib/fetch-package-metadata.js:31:3)
[ERROR] npm ERR! typeerror     at fetchPackageMetadata (/home/wpd/.gitlab-runner/builds/ae2980d9/0/XXX/pinpoint/web/target/node/node_modules/npm/lib/fetch-package-metadata.js:51:22)
[ERROR] npm ERR! typeerror     at resolveWithNewModule (/home/wpd/.gitlab-runner/builds/ae2980d9/0/XXX/pinpoint/web/target/node/node_modules/npm/lib/install/deps.js:490:12)
[ERROR] npm ERR! typeerror     at /home/wpd/.gitlab-runner/builds/ae2980d9/0/XXX/pinpoint/web/target/node/node_modules/npm/lib/install/deps.js:491:7
[ERROR] npm ERR! typeerror     at /home/wpd/.gitlab-runner/builds/ae2980d9/0/XXX/pinpoint/web/target/node/node_modules/npm/node_modules/iferr/index.js:13:50
[ERROR] npm ERR! typeerror     at /home/wpd/.gitlab-runner/builds/ae2980d9/0/XXX/pinpoint/web/target/node/node_modules/npm/lib/fetch-package-metadata.js:37:12
[ERROR] npm ERR! typeerror     at addRequestedAndFinish (/home/wpd/.gitlab-runner/builds/ae2980d9/0/XXX/pinpoint/web/target/node/node_modules/npm/lib/fetch-package-metadata.js:67:5)
[ERROR] npm ERR! typeerror     at returnAndAddMetadata (/home/wpd/.gitlab-runner/builds/ae2980d9/0/XXX/pinpoint/web/target/node/node_modules/npm/lib/fetch-package-metadata.js:121:7)
[ERROR] npm ERR! typeerror     at pickVersionFromRegistryDocument (/home/wpd/.gitlab-runner/builds/ae2980d9/0/XXX/pinpoint/web/target/node/node_modules/npm/lib/fetch-package-metadata.js:138:20)
[ERROR] npm ERR! typeerror     at /home/wpd/.gitlab-runner/builds/ae2980d9/0/XXX/pinpoint/web/target/node/node_modules/npm/node_modules/iferr/index.js:13:50
[ERROR] npm ERR! typeerror This is an error with npm itself. Please report this error at:
[ERROR] npm ERR! typeerror     <http://github.com/npm/npm/issues>
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /home/wpd/.gitlab-runner/builds/ae2980d9/0/XXX/pinpoint/web/target/npm-debug.log
```

**Comment by minwoo-jung** [comment]
@geekMessi 
The version of frontend-maven-plugin used by version 1.7 is too low.
I don't know the exact cause, but if you use a lower version, the build may suddenly fail.

Refer to [this commit](https://github.com/naver/pinpoint/commit/7be6c498fde141664bd44d95bc5e5ee62cae91ca#diff-eef89535a29b4a95a42d9de83cb53681) and build your own version.

**Comment by geekMessi** [comment]
> @geekMessi
> The version of frontend-maven-plugin used by version 1.7 is too low.
> I don't know the exact cause, but if you use a lower version, the build may suddenly fail.
> 
> Refer to [this commit](https://github.com/naver/pinpoint/commit/7be6c498fde141664bd44d95bc5e5ee62cae91ca#diff-eef89535a29b4a95a42d9de83cb53681) and modify the version and build it yourself.

It works .

**Comment by minwoo-jung** [comment]
@geekMessi
The next version will work with the higher version.
