### ISSUE TITLE
Does Pinpoint support Consul and Couchbase

### ISSUE THREAD

**Issue by dinesh4747** [naver/pinpoint#6311]
Hi Team/@koo-taejin @emeroad 

Could you please confirm whether Pinpoint does support tracing of below components:

1) Consul (Equivalent to spring cloud gateway/Zuul)

2) Couchbase (Similar to Memcached or Redis) - Just primarily looking for tracing a client like how pinpoint does for cassandra/oracle 

Any direction in this regard would be highly appreciated.

**Comment by emeroad** [comment]
Contributions are welcome, we have no plan to do this yet.

**Comment by dinesh4747** [comment]
Sure, I would take a look into plugin development and certainly reach out to your guys for more direction.
