### ISSUE TITLE
window启动错误  ClassNotFoundException：com.naver.pinpoint.common.util.CodeSourceUtils

### ISSUE THREAD

**Issue by kevinzpw** [naver/pinpoint#6315]
1. 

- 

#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

**Comment by minwoo-jung** [comment]
@kevinzpw
Please ask questions in English. 
Explain in detail what happens.

**Comment by kevinzpw** [comment]
hello：
I turn on the pinpoint in the window environment 
Error in Windows 7 environment：
ClassNotFoundException：com.naver.pinpoint.common.util.CodeSourceUtils

The native Java environment is normal，The package was downloaded from the official website。
Please help me thank you

**Comment by kevinzpw** [comment]
hello：
I turn on the pinpoint in the window environment
Error in Windows 7 environment：
ClassNotFoundException：com.naver.pinpoint.common.util.CodeSourceUtils

The native Java environment is normal，The package was downloaded from the official website。
Please help me thank you
