### ISSUE TITLE
Can pinpoint works with dynatrace concurrently

### ISSUE THREAD

**Issue by huangcheng1977** [naver/pinpoint#6323]

**Comment by minwoo-jung** [comment]
@huangcheng1977
It is not recommended to use it with pinpoint.
The main reason is that classes change dynamically.
If you work with other APMs, you are very likely to encounter problems.

**Comment by huangcheng1977** [comment]
Thanks

发自我的iPhone

在 2019年12月17日，10:52，Minwoo Jung <notifications@github.com> 写道：

﻿

@huangcheng1977<https://github.com/huangcheng1977>
It is not recommended to use it with pinpoint.
The main reason is that classes change dynamically.
If you work with other APMs, you are very likely to encounter problems.

**Comment by RoySRose** [comment]
Hello, @huangcheng1977 

May I ask you why you are trying to use Pinpoint with Dynatrace?
Are there any core reasons using both concurrently?

Happy to hear reasons from the real-world~

**Comment by huangcheng1977** [comment]
Because most developer has used to using pinpoint already.so they want two tools exists concurrently.and also we can not afford to buy enough dt license.we want all the application be monitored.so pinpoint is necessary for us
发自我的iPhone

在 2019年12月17日，17:07，Roy Kim <notifications@github.com> 写道：

﻿

Hello, @huangcheng1977<https://github.com/huangcheng1977>

May I ask you why you are trying to use Pinpoint with Dynatrace?
Are there any core reasons using both concurrently?

Happy to hear reasons from the real-world~

**Comment by RoySRose** [comment]
@huangcheng1977 
Thank you for sharing the news :)
Good new always cheer the team up.
Have a nice day~

**Comment by huangcheng1977** [comment]
Could you tell me why the two tools can not exists concurrently, Does there any solution to resolve this problem?

**Comment by RoySRose** [comment]
As @minwoo-jung have explained. It is not recommended.
Dynamic changes in classes are **LIKELY** encounter the problem.

You can always try at your will :)
Hope you can share the results if you do.
