### ISSUE TITLE
Pinpoint1.5.2 fails to monitor redis failures

### ISSUE THREAD

**Issue by zhangdanyang95** [naver/pinpoint#6329]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

Pinpoint1.5.2 fails to monitor redis failures，
The agent configured according to the steps of agent installation has no corresponding error alarm after encountering redis suspension.

**Comment by koo-taejin** [comment]
hi @zhangdanyang95 

We don't know that 
the pinpoint didn't show exception in the call stack,
or pinpoint didn't show error in the servermap,
or pinpoint didn't send alarm .

If possible, please provide a detailed description of the situation and how to make reproducibility.

thanks :)
