### ISSUE TITLE
[Question] Thrift version compatibility with pinpoint

### ISSUE THREAD

**Issue by yjqg6666** [naver/pinpoint#6333]
Which version of thrift is recommended and compatible with pinpoint 1.8.5? 
And what about pinpoint 2.0.0-rc1?  
From the contributed installation script,  https://github.com/naver/pinpoint/blob/master/thrift/install-thrift-linux.sh#L5, it's 0.10.0.  
 Is it compatible with the latest version v0.13.0?

**Comment by emeroad** [comment]
The same version as pom.xml is recommended.

> Is it compatible with the latest version v0.13.0?
- Even if the versions are mixed, there is no problem with wire protocol compatibility.

Tthrift version was not unified. I will clean up the dependencies.

**Comment by yjqg6666** [comment]
https://github.com/naver/pinpoint/issues/4751 indicates that it's 0.11.0. Any update now?

**Comment by yjqg6666** [comment]
https://github.com/naver/pinpoint/blob/1.8.x/pom.xml#L673  and https://github.com/naver/pinpoint/blob/1.8.x/pom.xml#L112.  

I get it now. Thanks for the flash response.
