### ISSUE TITLE
HBase client 1.2.6.1 -> 1.2.12 

### ISSUE THREAD

**Issue by koo-taejin** [naver/pinpoint#6339]
#### related issue
#4841
https://github.com/apache/hbase/commit/b6fcc8458002ac8fb5b9f2e93783eb282607fd9b

#### description 
Pinpoint keeps 1.2.6.1 version due to a performance issue.
I think it was solved by the above patch.
So, apply a new version to the pinpoint.

**Comment by koo-taejin** [comment]
have completed via #6340

**Comment by emeroad** [comment]
https://issues.apache.org/jira/browse/HBASE-21196
https://issues.apache.org/jira/browse/HBASE-21428?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel
