### ISSUE TITLE
Build error on pinpoint-agent-distribution 2.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by Lobo75** [naver/pinpoint#6347]
I downloaded the latest snapshot yesterday and cannot seem to get past a build error on the pinpoint-agent-distribution.  

The error was:

 [ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:4.0.0:revision (get-the-git-infos) on project pinpoint-agent: Could not complete Mojo execution...: Error: Could not get HEAD Ref, are you sure you have set the dotGitDirectory property of this plugin to a valid path? -> [Help 1]

I tried an edit on the pom.xml and added <dotGitDirectory>${basedir}/.git</dotGitDirectory> and verified that directory existed.

Same error.   Any suggestions on how to get past that error?

Attached is the mvn debug log at the time of the error.

Thanks.
[pinpoint-master.builderror.debug.trimed.log](https://github.com/naver/pinpoint/files/3984762/pinpoint-master.builderror.debug.trimed.log)

**Comment by dinesh4747** [comment]
@emeroad - Encountering the same failure as similar as above and build fails [INFO] pinpoint-agent-distribution ........................ FAILURE [  3.404 s]


[INFO] pinpoint-tools ..................................... SUCCESS [  1.462 s]
[INFO] pinpoint-agent-distribution ........................ FAILURE [  3.404 s]
[INFO] pinpoint-agent-it .................................. SKIPPED
[INFO] pinpoint-agent-it8 ................................. SKIPPED
[INFO] pinpoint-collector ................................. SKIPPED
[INFO] pinpoint-plugin-bom ................................ SKIPPED
[INFO] pinpoint-web ....................................... SKIPPED
[INFO] pinpoint-hbase-distribution ........................ SKIPPED
[INFO] pinpoint-hbase-schema-definition ................... SKIPPED
[INFO] pinpoint-hbase-schema .............................. SKIPPED
[INFO] pinpoint-hbase-schema-manager ...................... SKIPPED
[INFO] pinpoint-flink ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:54 min
[INFO] Finished at: 2019-12-23T17:38:49+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.1.1:single (make-distribution) on project pinpoint-agent: Execution make-distribution of goal org.apache.maven.plugins:maven-assembly-plugin:3.1.1:single failed: group id '533506962' is too big ( > 2097151 ). Use STAR or POSIX extensions to overcome this limit -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :pinpoint-agent

**Comment by emeroad** [comment]
@dinesh4747 hi
Maven assembly-plugin “group id '1377585961' is too big” error
https://stackoverflow.com/questions/33819438/maven-assembly-plugin-group-id-1377585961-is-too-big-error
I think it's different from the first issue.

Is your build environment Mac?
- $PINPONT_DIR/agent/pom.xml 
  `<tarLongFileMode>posix</tarLongFileMode>`  
Please retry with posix option.
