### ISSUE TITLE
Pinpoint monitoring showed that the system CPU and the actual mismatch

### ISSUE THREAD

**Issue by chai-zhenhua** [naver/pinpoint#6365]
As shown in the following figure, I saw pinpoint showed the system CPU utilization rate reached 100%, but I looked at the monitoring data of the machine, and the use of top command to see for a long time, the actual system CPU has not significantly increased not to say 100%, I want to ask, what is the general reason for this?

**Comment by chai-zhenhua** [comment]
![image](https://user-images.githubusercontent.com/52958356/71508837-1f2d8780-28c4-11ea-9030-197ba93e0082.png)

**Comment by chai-zhenhua** [comment]
![屏幕快照 2019-12-27 下午4 01 26的副本](https://user-images.githubusercontent.com/52958356/71508873-3bc9bf80-28c4-11ea-817b-a7c2f6391461.png)

**Comment by chai-zhenhua** [comment]
![屏幕快照 2019-12-27 下午4 17 12](https://user-images.githubusercontent.com/52958356/71508916-6156c900-28c4-11ea-81b3-a9ebaac4c8d3.png)

**Comment by emeroad** [comment]
Pinpoint performance information uses JDK standard MBean API, so Perf data is accurate.
https://github.com/naver/pinpoint/blob/master/profiler-optional/profiler-optional-jdk7/src/main/java/com/navercorp/pinpoint/profiler/monitor/metric/cpu/oracle/DefaultCpuLoadMetric.java#L39

**Comment by emeroad** [comment]
This issue may be the monitoring granularity problem.
Pinpoint collects information every five seconds, so it can catch more accurate information.

## Why One Second Matters When Monitoring Applications
https://www.instana.com/blog/one-second-matters-monitoring-applications/

**Comment by chai-zhenhua** [comment]
Even if the monitoring value time is different and the system CPU is at 100% for a long time, our monitoring system cannot see any abnormality. We have carefully checked and found that there is no other problem with the system itself and there is no application that USES too much CPU. The difference between 1% and 100% is very obvious, don't you think?
