### ISSUE TITLE
Alarm notifications not received

### ISSUE THREAD

**Issue by nehabisen-git** [naver/pinpoint#6372]
I want to configure email alarms for Pinpoint, I have followed all steps mentioned here : https://github.com/naver/pinpoint/blob/master/doc/alarm.md
but alarms are not being received. 

**Environment:**
Pinpoint version: 2.0.0-Snapshot. Downloaded latest code from github on 5th December 19 since the latest released version 1.8.5 is missing few Java classes(ex. DefaultAlarmMessageSender.java, MailSender.java) and xml configuration in web component.
OS Version :  CentOS Linux 7 (Core)
Apache-tomcat version: 8.0.30
MySQL version :  5.5.64-MariaDB MariaDB Server
HBase version : 1.4.10

Additional Information : The alarm configuration is being populated into db table - "alarm_rule" and alarm_history table is empty. The cron expression is set to be triggered every 3 minutes for batch job.

There are no errors in logs Please let me know if I need to share any other information.
Any help will be appreciated.

**Comment by minwoo-jung** [comment]
It is recommended that you do some debugging yourself.

When the alarm batch is run, show the full log and I will look at it as well.
