### ISSUE TITLE
PHP Dev App With Pinpoint APM

### ISSUE THREAD

**Issue by anilvaja** [naver/pinpoint#6384]
We have prepared the entire code and installged PHP agent outside the docker,
also configured the collector config file. with collector IP. and port for the application as per requirement, bust still just app shows not any kind of php app tracking.
How it could be track php app ?

**Comment by RoySRose** [comment]
Hello, @anilvaja 
I think this issue can be posted https://github.com/naver/pinpoint-c-agent
which is the PHP-agent repository
