### ISSUE TITLE
Pinpoint Alarm integration to Slack or MS teams or other messaging platform

### ISSUE THREAD

**Issue by asdad-emizzy** [naver/pinpoint#6388]
**Which module is your feature request related to?**
Pinpoint/Alarm

**Is your feature request related to a problem?**
A clear and concise description of what the problem is.

**Describe the solution you'd like**
Does the team have a plan to have integration to any messaging platform like Slack or MS Teams with regards to the Alarms module?

**Describe alternatives you've considered**

**Additional context**

**Comment by emeroad** [comment]
@asdad-emizzy Hello~
There is no plan to integrate with the direct messaging platform
But we will provide WEB-API like Webhook
