### ISSUE TITLE
mvn <goals> -rf :pinpoint-agent Help me.

### ISSUE THREAD

**Issue by hyunwoo11** [naver/pinpoint#6400]
I couldn't figure out how to solve the problem.

cmd command : mvnw.cmd install -DskipTests=true

![오류 사진](https://user-images.githubusercontent.com/41004219/71956580-dfa15c80-322e-11ea-8c41-f21439923c0f.PNG)

**Comment by RoySRose** [comment]
Hello, @hyunwoo11 

It would be good to follow the instructions by Maven as shown in the screenshot to solve the problem.
Try to check what pops up with -X switch for full debug logging.

**Comment by Lobo75** [comment]
It's broken, I have followed the directions and put in a ticket myself, see 6416 and it's closed ticket 6347 that did not resolve the problem, just changed the nature of the failure.

**Comment by emeroad** [comment]
Duplicate #6416
