### ISSUE TITLE
Remove useless `serverAcceptor` in flink job to prevent thread from leaking

### ISSUE THREAD

**Issue by tankilo** [naver/pinpoint#6413]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
master

#### Describe the bug
In `pinpoint\flink\src\main\resources\applicationContext-flink.xml`, there is an useless `serverAcceptor`. 
```
<!-- TCPReceiver related Beans -->
    <bean id="serverAcceptor" class="com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor"/>
```

#### What did you do to trigger the bug?
Submit job and cancel it, then take a threaddump.

#### Expected behavior
No threads created by the job should be left.

#### Screenshots

![image](https://user-images.githubusercontent.com/10413284/72218965-b577d380-357b-11ea-8d06-2bee75dc8cc5.png)

**Comment by minwoo-jung** [comment]
@tankilo 
Ok I'll check it. 
Tell me which pinpoint version to use.

**Comment by tankilo** [comment]
@minwoo-jung In fact, i found this problem in 1.7.3 and i reproduced it in master branch.  Before `serverAcceptor`, there is a comment `<!-- TCPReceiver related Beans -->`. But TCPReceiver create PinpointServerAcceptor itself, so i think this one in xml is useless.

**Comment by minwoo-jung** [comment]
@tankilo 
The detailed analysis is good!
I also completed the analysis and tested it. Simply delete the bean declaration.
You did a good analysis, so do you want to ask for a PR? I will merge.
