### ISSUE TITLE
Compile issues with 2.0.RC2 after issue #6347 was closed

### ISSUE THREAD

**Issue by Lobo75** [naver/pinpoint#6416]
Hello, I opened Issue #6347 last month as saw it was fixed so I downloaded on 1/9/2020 V2.0.0-RC2.  It appeared to have a change for the failed pom.  Perhaps I'm wrong and should have just grabbed the master branch ?

Well for that RC2 the build fails, same place but a different error.  I started from scratch, cleared out my .m2 cache and ran the build.  Attached is the debug log.  Fails with:

Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.1.1:single (make-internal) on project pinpoint-agent: Failed to create assembly: Error adding file to archive: /mnt/d5cbc532-dea2-48dd-a1e2-632f3df423c4/pinpoint-2.0.0-RC2/agent/target/build.info

Thanks.
[pinpoint-rc2.builderrors.log](https://github.com/naver/pinpoint/files/4054553/pinpoint-rc2.builderrors.log)

**Comment by emeroad** [comment]
@Lobo75 Thank you for reporting
When using the downloaded image, the build seems to fail.
Fixed the build to be successful in the download image.

**Comment by emeroad** [comment]
Related issue : #6347
