### ISSUE TITLE
RabbitMQ can not show all topology 

### ISSUE THREAD

**Issue by zhouhuicong** [naver/pinpoint#6417]
I using pinpoint v1.8.3 . but I can not find the rabbitmq topology .  Only the topology of downstream consumers can be found, and the upstream relationship cannot be revealed.
I also set the profiler.rabbitmq.client.consumer.classes=xxxxxx(my own class )
How can I solve this problem.

![1](https://user-images.githubusercontent.com/40559605/72408144-e551f180-379c-11ea-9100-3ca755c49ca2.png)

**Comment by zhouhuicong** [comment]
one trace through rabbitmq but split two trace #4463 ，this is issue not help me

**Comment by koo-taejin** [comment]
hi @zhouhuicong 

If you want to keep track of sending requests to RabbitMQ,
First make sure that the setting is included. `profiler.rabbitmq.client.producer.enable = true`

Even if you include this setting but still don't see it
Then check if the RabbitMQ version is supported by Pinpoint.
(https://github.com/naver/pinpoint/blob/master/doc/modules.md)

If you are not included about both of these things, 
please check that it's send a request within the flow in entryPoint. 


Please post a detailed description of the process of sending a message from the entry point and log with debug level in that situation.

thanks :)

**Comment by zhouhuicong** [comment]
> hi @zhouhuicong
> 
> If you want to keep track of sending requests to RabbitMQ,
> First make sure that the setting is included. `profiler.rabbitmq.client.producer.enable = true`
> 
> Even if you include this setting but still don't see it
> Then check if the RabbitMQ version is supported by Pinpoint.
> (https://github.com/naver/pinpoint/blob/master/doc/modules.md)
> 
> If you are not included about both of these things,
> please check that it's send a request within the flow in entryPoint.
> 
> Please post a detailed description of the process of sending a message from the entry point and log with debug level in that situation.
> 
> thanks :)

Status of node rabbit
     [{rabbitmq_management,"RabbitMQ Management Console","3.7.13"},
      {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.7.13"},
      {rabbitmq_management_agent,"RabbitMQ Management Agent","3.7.13"},
      {rabbit,"RabbitMQ","3.7.13"},
      {rabbit_common,
          "Modules shared by rabbitmq-server and r### **rabbitmq-erlang-client**",  ， 
this  rabbitmq-erlang-client ， the pinpoint is not Support  ？
