### ISSUE TITLE
Get hbase data

### ISSUE THREAD

**Issue by kevinzpw** [naver/pinpoint#6423]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

HI 
I want to obtain the pinpoint data of hbase,but I found that the data cf in TraceV2 was converted
I used 1.6.03 version ,The hbase data looks like this  column=S:\x00\x08yjzh\x1A192.168.20.54\xDB\xDF\xF3-v{\x1E\xA5\xA3H\xC2
How do I get the column name

**Comment by emeroad** [comment]
Pinpoint stores data through binary encoding.
Therefore, you must decode to read the value

See the code below.
https://github.com/naver/pinpoint/blob/master/commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/SpanDecoderV0.java#L121

**Comment by emeroad** [comment]
https://github.com/naver/pinpoint/blob/master/commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseColumnFamily.java#L147
```java
public static final Trace TRACE_V2_SPAN = new Trace(HbaseTable.TRACE_V2, Bytes.toBytes("S"));
```
CF(ColumnFamilyName) is "S"

**Comment by kevinzpw** [comment]
> https://github.com/naver/pinpoint/blob/master/commons-hbase/src/main/java/com/navercorp/pinpoint/common/hbase/HbaseColumnFamily.java#L147
> 
> ```java
> 公共 静态 最终 痕量 TRACE_V2_SPAN  =  新 跟踪（HbaseTable 。 TRACE_V2，字节。 toBytes（ “小号”））;
> ```
> 
> CF（ColumnFamilyName）为“ S”
thank you 
I know his column name is S ，or E ........ What I want to know is the column name below the column family and the rowkey
