### ISSUE TITLE
how to load all data in the transactionList while open?

### ISSUE THREAD

**Issue by taylorshrey** [naver/pinpoint#6435]
- step1: I choose all the data in pinpoint at below
![pic@1](https://user-images.githubusercontent.com/19928714/72601684-db70ef80-3950-11ea-9912-f72b6fe8d8ad.png)
- step2: open the transactionList  page
- step3: click more to load more data,but it is too slow. 
![pic@2](https://user-images.githubusercontent.com/19928714/72601683-dad85900-3950-11ea-8e15-989223350854.png)

i have more than 1,900,000 data to load , but it add 100 each time after my click "more".
is there any way to sovle it ?

**Comment by koo-taejin** [comment]
hi @AllenKings 

I don't think loading all transaction in browser is no good idea.

I think that browser can not stand, If you've loaded 1.9 million requests.

I recommend you to use Filter Wizard or Success/Fail or Time to look for request you want .

thanks :)

**Comment by AllenKings** [comment]
@koo-taejin  So, how can i export these data from pinpoint? Do you have a good solution?

**Comment by AllenKings** [comment]
Is there any settings can change the "more" click to load more data every time, it is 100 now?
