### ISSUE TITLE
Connecting to Google GCP BigTable instead of hbase

### ISSUE THREAD

**Issue by praveen12bnitt** [naver/pinpoint#6441]
We started using pinpoint recently and was very impressed. We deploy our application on Google cloud. Google cloud provides a hosted BigTable solution and it supports the hbase Java client.

Check this link from Google
https://cloud.google.com/bigtable/docs/hbase-differences

I was wondering if we can point collector to big table, we can reduce a significant maintenance work involved. Let me know what u guys think ?

**Comment by minwoo-jung** [comment]
Although pinpoint does not officially support bigtable,  It might be a good idea to try it.
If the current code does not work perfectly, you may want to consider developing a separate dao part.

**Comment by praveen12bnitt** [comment]
Cool. I am willing to contribute. I wanted to check with you all first
before attempting to spend time. If you think it's a good idea, I will
proceed further. Thanks for you feedback.

**Comment by emeroad** [comment]
https://cloud.google.com/bigtable/docs/hbase-bigtable
> The client is compatible with versions 1.0.x, 1.1.x, 1.2.x, and 1.3.x of the HBase API.

I think if you change to Bigtable-driver, it will work.
https://cloud.google.com/bigtable/docs/reference/libraries#client-libraries-install-java
```
<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>google-cloud-bigtable</artifactId>
  <version>1.9.1</version>
</dependency>
```
