### ISSUE TITLE
UUID resolution in SQL Bind Values

### ISSUE THREAD

**Issue by ledben** [naver/pinpoint#6446]
Hi,

Could you explain us why en UUID value is not displayed in the SQL Window ?

Thanks a lot !

Benoit L.

![UUIDSqlBinding](https://user-images.githubusercontent.com/5944553/72900309-ee583b00-3d27-11ea-8d70-0bb776bca18f.png)

**Comment by emeroad** [comment]
@ledben Thank you for reporting
I added the UUID type in 2.0.0.
