### ISSUE TITLE
URL error included in the guide.

### ISSUE THREAD

**Issue by dawoori** [naver/pinpoint#6468]
There seems to be a problem with this address in the document.

`doc/resources.md`
![1](https://user-images.githubusercontent.com/48546277/73607602-8e9d4200-45fb-11ea-8301-15363198f98a.png)

`web/src/main/angualr/src/app/core/components/configuration-help/configuration-help-container.component.html`
![2](https://user-images.githubusercontent.com/48546277/73607617-bc828680-45fb-11ea-8fc2-fc79157296ba.png)

`Result`
![3](https://user-images.githubusercontent.com/48546277/73607626-de7c0900-45fb-11ea-9e84-c8aba0912d50.png)

**Comment by RoySRose** [comment]
@dawoori 

Thank you for the notice. 
I have removed old links that no longer are suitable for acquiring info.

Also, I suggest you look at the documents on our [official homepage](https://naver.github.io/pinpoint/main.html) :)
