### ISSUE TITLE
Vertx router blockingHandler  Unable to get data。

### ISSUE THREAD

**Issue by 1103036128** [naver/pinpoint#6477]
pinpoint 1.8.4 
vertx: 3.7.0

![image](https://user-images.githubusercontent.com/35803296/73823669-bd056200-4833-11ea-821d-ce01b946025c.png)

I can't get data for asynchronous execution
MY CODE:
router.get("/health").blockingHandler(new ItemController(vertx)::healthDataSource,false);// health

**Comment by 1103036128** [comment]
pinpoint.config
![image](https://user-images.githubusercontent.com/35803296/73822224-9560ca80-4830-11ea-8f36-b7e16826851f.png)
Are there any examples that 'Sets the base packages that implements io.vertx.core.Handler.'

**Comment by 1103036128** [comment]
Some one help me!

**Comment by 1103036128** [comment]
public class ItemController implements Handler<RoutingContext>{
       @Override
	public void handle(RoutingContext event) {
		// TODO Auto-generated method stub
		healthDataSource(event);;
	}
}

**Comment by 1103036128** [comment]
`router.get("/health").blockingHandler(new ItemController(),false);// health`

**Comment by 1103036128** [comment]
This Code: 
router.get(parent+"/health").handler(new ItemController(vertx)::healthDataSource);// health
![image](https://user-images.githubusercontent.com/35803296/73824764-acee8200-4835-11ea-992e-ff82bbc2a2be.png)

**Comment by 1103036128** [comment]
如何让我配置的blockingHandler 异步也能显示出来
How to make my configured blockinghandler asynchronously displayed

**Comment by jaehong-kim** [comment]
@1103036128 
This article may be helpful. - https://github.com/naver/pinpoint/blob/master/plugins/vertx/README.md

**Comment by 1103036128** [comment]
How to make asynchronous route be tracked by pinpoint
```
router.route().blockingHandler(routingContext -> {

  // Do something that might take some time synchronously
  service.doSomethingThatBlocks();

  // Now call the next handler
  routingContext.next();

});
```

**Comment by 1103036128** [comment]
> @1103036128
> This article may be helpful. - https://github.com/naver/pinpoint/blob/master/plugins/vertx/README.md

Yes, I did, but it didn't work

**Comment by jaehong-kim** [comment]
@1103036128 
PR the demo or code you can run.
