### ISSUE TITLE
Which Java multithreaded concurrent library does pinpoint support to collect? Are there any examples

### ISSUE THREAD

**Issue by 1103036128** [naver/pinpoint#6484]
```
ExecutorService executorService = Executors.newFixedThreadPool(3);
List<Callable<Object>> searchTasks = new ArrayList<Callable<Object>>(); 
Callable<Object> shopCall =  new ShopCall(slug,type,jsonObject);
List<Future<Object>> futures = executorService.invokeAll(searchTasks,20, TimeUnit.SECONDS);
jsonObject.put("shop", futures.get(0).get());
```
Pinpoint Unable to get link executed in java thread！

**Comment by 1103036128** [comment]
like [https://github.com/naver/pinpoint/issues/380](url)

**Comment by 1103036128** [comment]
some one help me

**Comment by 1103036128** [comment]
Is there a java thread example that can be collected by pinpoint

**Comment by 1103036128** [comment]
Which Java multithreaded concurrent library does pinpoint support to collect? Are there any examples.
@jaehong-kim

**Comment by 1103036128** [comment]
@koo-taejin

**Comment by jaehong-kim** [comment]
@1103036128 
Does not support ExecutorService class tracing.

**Comment by 1103036128** [comment]
Which Java multithreaded concurrent library does pinpoint support to collect? Are there any examples?
Thanks!
@jaehong-kim
