### ISSUE TITLE
Pinpoint points to unknown component which is taking huge response time in application

### ISSUE THREAD

**Issue by dhavaltrivedi** [naver/pinpoint#6492]
- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
master/v1.8.5.

#### Describe your problem**
Pinpoint GUI shows the number of requests going out from the particular application is to unknown. How to check what is unknown here? is it some machine which is not traceable or is it some API Call? How could one derive what unknown is?

#### What have you done?
Steps you have taken to trigger the problem, for example:
1. Launched '...' with agent
2. Load the application and check the calls going out from the application. 
[Pinpoint_unknown_issue.docx](https://github.com/naver/pinpoint/files/4180527/Pinpoint_unknown_issue.docx)
4. No trace shows up in the web UI (see web log below)

#### Logs
If applicable, please attach agent/collector/web DEBUG log that includes the part where you have encountered the problem. In case of agents, including the start-up log may be of great help.

#### Additional context
Add any other context about the problem here, such as affected library for agents, how your collector/web/hbase is set up if applicable.

**Comment by minwoo-jung** [comment]
You can think of an unknown node as an application where the agent is not running.
An unknown node can appear when calling a remote server with rpc, http calls. You can check whether the call can be traced by looking at the list of supported plugins.

**Comment by dhavaltrivedi** [comment]
Hi Minwoo, Thank you for the response. Is there any way I can check the API details in the transaction flow where pinpoint is not configured? Basically I would like to know the hosts or the API calls which are making those calls.

**Comment by minwoo-jung** [comment]
There is no way to know the api call stack in an unknown server to which the pinpoint agent does not apply.^^

**Comment by emeroad** [comment]
@dhavaltrivedi
This problem is usually caused by a bug in the plugin.
If the plug-in cannot get the information it needs to track, it will mark it as Unknown. (eg: url)
Debug the plugin that caused the problem and fix the bug.

Contributions are welcome,

**Comment by minwoo-jung** [comment]
@dhavaltrivedi
You are not finding a plugin to analyze.
Don't just look at the servermap, look at the call tree for that transaction.
Find out where the target is marked as unknown, and check the plugin for analysis.
