### ISSUE TITLE
Data source connection usage rate's calculation method

### ISSUE THREAD

**Issue by fionaliupw** [naver/pinpoint#6497]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

I used the datasource connection usage alarm on my application，but I was a little confused about its calculation method. From tips，I got the usage is TotalActive/TotalMax. And my question is  what TotalActive and TotalMax mean. 

I used druid pool, my app's druid pool max-active-connection is 100，but from inspector datasource data, it shows TotalMax is 40 and TotalActive is 2. Why druid pool's max-active-connection is 100, but the TotalMax is only 40？

Thank you.

**Comment by emeroad** [comment]
https://github.com/naver/pinpoint/blob/master/plugins/druid/src/main/java/com/navercorp/pinpoint/plugin/druid/DruidDataSourceMonitor.java#L77

```java
    @Override
    public int getMaxConnectionSize() {
        if (dataSource != null) {
            return dataSource.getMaxActive();
        }
        return -1;
    }
```
Pinpoint uses the DruidDataSource.getMaxActive() API for TotalMax.
If there is a bug in this code, colud you fix it?

Contributions are always welcome.
