### ISSUE TITLE
Questions about the meaning of properties in the SpanEvent class

### ISSUE THREAD

**Issue by JangNum** [naver/pinpoint#6500]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

What do the startElapsed and endElapsed properties in the SpanEvent class represent?

**Comment by koo-taejin** [comment]
hi @JangNum 

StartElapsed is the relative start time from the base point.
EndElapsed is the relative end time from the base point.
(Usually, the base point is Span or first SpanEvent of the SpanChunk.)

Explain briefly,

```
If Span started at 1:35:05

and SpanEvent(called 'A') is started at 1:35:07,
and SpanEvent(called 'A') is done at 1:35:09,

### result
'A' SpanEvent's startElapsed is 2000 ((1:35:07 -  1:35:05) * millis)
'A' SpanEvent's endElapsed is 4000 ((1:35:09  -  1:35:05) * millis)
```


The following source is related with this issue.
`com.navercorp.pinpoint.profiler.context.compress.GrpcSpanProcessorV2#postProcess`

thanks :)

**Comment by Chao-Zeng** [comment]
I check the code, the base point is the last SpanEvent's startTime. the logic have changed?
```java
final long startTime = spanEvent.getStartTime();
final long startElapsedTime = startTime - keyTime;
pSpanEvent.setStartElapsed((int) startElapsedTime);
keyTime = startTime;
```

**Comment by koo-taejin** [comment]
@Chao-Zeng 
You are right. 
It is based on the prev SpanEvent's starttime.
If there is no prev object, then Span's starttime is basetime.
