### ISSUE TITLE
Deleting old data: Possibilities and Estimated Overhead

### ISSUE THREAD

**Issue by martinstraesser** [naver/pinpoint#6526]
Hello,
I have limited memory capabilities on my machines and want to ask what is the best way to delete old monitoring data from Pinpoint? I found the related issues #429 and #2546 which suggest that setting the TTL value in Hbase would be only way to do it.

My problem is:
I want to delete all monitoring data older than x minutes automatically.

My questions are:

1. Is there another/better way than #429/#2546 to delete / clean up old data in Pinpoint automatically?
2. If not, is there a significant overhead of this cleanup and will it affect Pinpoints performance?
3. What does the term "major compaction" means in this context? In which intervals does it work?

Thanks for any help and experiences :)

**Comment by emeroad** [comment]
> 1. ~~
 - Major compaction is the best way.

> 2. 3 ~~
- See the hbase document
71.7.7. Compaction
https://hbase.apache.org/book.html#compaction

**Comment by auqf** [comment]
but the space can not release, how to fix it?
