### ISSUE TITLE
After adding pinpoint, springboot application can not startup and hs_err_pid file generated

### ISSUE THREAD

**Issue by DuoyueBa** [naver/pinpoint#6532]
#### Prerequisites
I do not find out similar problem. I want to monitor my springboot application, so I import pinpoint. But after adding pinpoint, springboot can not startup. And hs_err_pid is generated.

#### What version of pinpoint are you using?
master/v1.8.5

#### Describe your problem**
I want to monitor my springboot application, so I import pinpoint. But after adding pinpoint, springboot can not startup. And hs_err_pid is generated. Before importing pinpoint, my application runs normally.

#### What have you done?
Steps you have taken to trigger the problem, for example:
1. Import pinpoint and Launched my application with agent

`java -jar -Xms2048m -Xmx2048m -XX:-OmitStackTraceInFastThrow -javaagent:/opt/local/pinpoint_agent/pinpoint-bootstrap-1.8.5.jar -Dpinpoint.applicationName=manager-prod -Dpinpoint.agentId=geek_manager_prod_bjd01 skynet-manager-*.jar &`

2. Then application crashes and hs_err_pid 
[hs_err_pid30164.log](https://github.com/naver/pinpoint/files/4244891/hs_err_pid30164.log)
[hs_err_pid30242.log](https://github.com/naver/pinpoint/files/4244892/hs_err_pid30242.log)

generated

#### Logs
I tried several times, and generated hs_err_pid files are different. I attached two hs_err_pid files.

#### Additional context
Add any other context about the problem here, such as affected library for agents, how your collector/web/hbase is set up if applicable.

**Comment by emeroad** [comment]
Old JDK has too many bugs.
I recommend the latest version of JDK.
 - Minimum recommendations : jdk 8 update40+

- https://bugs.openjdk.java.net/browse/JDK-8068884
- http://www.oracle.com/technetwork/java/javase/2col/8u40-bugfixes-2423829.html
- http://www.oracle.com/technetwork/java/javase/8u40-relnotes-2389089.html

**Comment by DuoyueBa** [comment]
Our jdk is 
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

Is there anybody to report similar problem? we can not upgrade jdk in short time.
