### ISSUE TITLE
transactionList is loading 

### ISSUE THREAD

**Issue by xiaoxinxin85** [naver/pinpoint#6540]
HI:
     Today, I deployed pinpoint。 When i visit "http://x.x.x.x/#/transactionList/Pay-fintech-receipt@TOMCAT/20m/2020-02-26-16-10-41"，it is always loading。How can i resolve it ?
![image](https://user-images.githubusercontent.com/24424783/75325820-71832880-58b4-11ea-917a-23470cb5bcd0.png)

**Comment by xiaoxinxin85** [comment]
![loading](https://user-images.githubusercontent.com/24424783/75325915-a1323080-58b4-11ea-99d9-e9a31d3df1e0.png)

**Comment by koo-taejin** [comment]
hi @xiaoxinxin85 

There will be an request that has error on that page.

If you refer to following link, the you can check all request on that page. 
Please post request that has error in xhr tab and error message. 

https://developers.google.com/web/tools/chrome-devtools/network

thanks :)

**Comment by xiaoxinxin85** [comment]
HI，koo-taejin：
Below are screenshots of all requests：
![1](https://user-images.githubusercontent.com/24424783/75330303-d2622f00-58bb-11ea-99a6-873c591bbdde.png)
![2](https://user-images.githubusercontent.com/24424783/75330317-d8f0a680-58bb-11ea-89a4-ecd46f375e7a.png)
![3](https://user-images.githubusercontent.com/24424783/75330328-dc842d80-58bb-11ea-8171-26d2d67612e3.png)
![4](https://user-images.githubusercontent.com/24424783/75330336-e0b04b00-58bb-11ea-83fe-851b8e26583f.png)
![5](https://user-images.githubusercontent.com/24424783/75330341-e4dc6880-58bb-11ea-93e7-ad86973d7bcd.png)
![6](https://user-images.githubusercontent.com/24424783/75330350-e7d75900-58bb-11ea-8a8c-6dce25b6c2a7.png)

**Comment by koo-taejin** [comment]
It  might be related with this issue (#6324)
Please retry with 2.0.0-RC4 version.
