### ISSUE TITLE
Does Envoy support is available in latest release 2RC4 ?

### ISSUE THREAD

**Issue by dinesh4747** [naver/pinpoint#6541]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

**Comment by koo-taejin** [comment]
hi @dinesh4747 

Envoy will be not supported in v2.0.0-RC4 and v2.0.0.
However, it is expected to be available within the first half of this year 

thanks :)
