### ISSUE TITLE
Issues with deploying Agent on JBoss 7 & Windows

### ISSUE THREAD

**Issue by zzxx53** [naver/pinpoint#6547]
- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
v1.8.5

#### Describe your problem**
When starting JBoss, the Agent shuts itself down and takes down JBoss with it. 

#### What have you done?
The following changes were made to standalone.bat, following guides from https://github.com/naver/pinpoint/tree/master/plugins/jboss#pinpoint-jboss-plugin-configuration and https://github.com/naver/pinpoint/issues/972#issuecomment-219488721
set "JAVA_OPTS=-Djboss.modules.system.pkgs=org.jboss.byteman,org.jboss.logmanager,com.navercorp.pinpoint.bootstrap,com.navercorp.pinpoint.common,com.navercorp.pinpoint.exception %JAVA_OPTS%"
set "JAVA_OPTS=-Djava.util.logging.manager=org.jboss.logmanager.LogManager %JAVA_OPTS%"
set "JAVA_OPTS=-Xbootclasspath/p:D:/jboss-as-7.1.3.Final/modules/org/jboss/logmanager/main/jboss-logmanager-1.3.2.Final.jar %JAVA_OPTS%"
set "JAVA_OPTS=-Xbootclasspath/p:D:/jboss-as-7.1.3.Final/modules/org/jboss/logmanager/log4j/main/jboss-logmanager-log4j-1.0.0.GA.jar %JAVA_OPTS%"
set "JAVA_OPTS=-Xbootclasspath/p:D:/jboss-as-7.1.1.Final/modules/org/apache/log4j/main/log4j-1.2.16.jar %JAVA_OPTS%"
set "JAVA_OPTS=-javaagent:D:\jboss-as-7.1.3.Final\pinpoint\pinpoint-bootstrap-1.8.5.jar %JAVA_OPTS%"
set "JAVA_OPTS=-Dpinpoint.agentId=TEST_API_1 %JAVA_OPTS%"
set "JAVA_OPTS=-Dpinpoint.applicationName=TEST_API_SERVER %JAVA_OPTS%"

And the jar files were placed in the location indicated. 

In pinpoint.config I changed two settings, profiler.collector.ip and profiler.application.namespace; all other settings were left as default. The same values worked for another Tomcat server we have. Pinpoint Collector, Pinpoint Web and hbase are running on a separate Linux server and seems to work fine. 

#### Logs
I didn't see any exceptions in the Pinpoint logs. JBoss didn't log anything before it shut itself down. 
Pinpoint log: pastebin.com/DiuZJ3sn

**Comment by zzxx53** [comment]
Solved it - turns out to be the order of adding things to JAVA_OPTS. I was prepending to the variable instead of appending to it. 

This is what worked for me: 
set "JAVA_OPTS=%JAVA_OPTS% -Djboss.modules.system.pkgs=org.jboss.byteman,org.jboss.logmanager,com.navercorp.pinpoint.bootstrap,com.navercorp.pinpoint.common,com.navercorp.pinpoint.exception"
set "JAVA_OPTS=%JAVA_OPTS% -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
set "JAVA_OPTS=%JAVA_OPTS% -Xbootclasspath/p:D:/jboss-as-7.1.3.Final/modules/org/jboss/logmanager/main/jboss-logmanager-1.3.2.Final.jar"
set "JAVA_OPTS=%JAVA_OPTS% -Xbootclasspath/p:D:/jboss-as-7.1.3.Final/modules/org/jboss/logmanager/log4j/main/jboss-logmanager-log4j-1.0.0.GA.jar"
set "JAVA_OPTS=%JAVA_OPTS% -Xbootclasspath/p:D:/jboss-as-7.1.1.Final/modules/org/apache/log4j/main/log4j-1.2.16.jar"
set "JAVA_OPTS=%JAVA_OPTS% -javaagent:D:\jboss-as-7.1.3.Final\pinpoint\pinpoint-bootstrap-1.8.5.jar"
set "JAVA_OPTS=%JAVA_OPTS% -Dpinpoint.agentId=TEST_API_1"
set "JAVA_OPTS=%JAVA_OPTS% -Dpinpoint.applicationName=TEST_API_SERVER"

**Comment by koo-taejin** [comment]
Thank you for sharing your solution. :)
