### ISSUE TITLE
version 1.8.5 weblogin typology map

### ISSUE THREAD

**Issue by aviranmz** [naver/pinpoint#6549]
Hi,

I have 3 type of java application all of them are weblogic.
i add to each:
  -javaagent:/users/uscc-pinpointagent/pinpoint-agent-1.8.5//pinpoint-bootstrap-1.8.5.jar 
![image](https://user-images.githubusercontent.com/34619740/75489765-88f90900-59bb-11ea-8340-dd583097fed8.png)

&& -> per each 

  -Dpinpoint.agentId=App1 -Dpinpoint.applicationName=monitorUsage
  -Dpinpoint.agentId=App2 -Dpinpoint.applicationName=monitorUsage
  -Dpinpoint.agentId=App3 -Dpinpoint.applicationName=monitorUsage

as you can see i set all to weblogin (each server has its on config)

But when i select the monitorUsage group from the DDL its show all of them as i server with the 4 in the left corner.
Why it does not show each server as a stand alone - they are calling each other

the config: (default values)

#
# Pinpoint agent configuration
#

###########################################################
# Collector server                                        # 
###########################################################
profiler.collector.ip=100.100.30.91
.......
.......
.......
.......
.......
###########################################################
# Weblogic
###########################################################
profiler.weblogic.enable=true

.......
.......

**Comment by jaehong-kim** [comment]
@aviranmz 
Set the applicationName differently depending on the type.
