### ISSUE TITLE
윈도우에서 tomcat 구동시 로그 수집이 안됩니다.

### ISSUE THREAD

**Issue by kimnamgil** [naver/pinpoint#6552]
윈도우 tomcat 8에서 서비스를 구동중입니다.
collector 는 리눅스 서버에 설치되어 있습니다.
webui 에서 윈도우에 설정된 tomcat 인스턴스의 정보는 보입니다.
inspector 에서도 cpu, memory 등의 정보는 수집이 되고 있습니다.

그런데 http request에 의한 로그가 보이지 않습니다.
포트는 TCP, UDP 모두 열려있습니다.

참고로, test용 app은 정상적으로 http request 정보가 수집 됩니다.

무엇을 확인하면 좋을까요?

**Comment by minwoo-jung** [comment]
Hello~ @kimnamgil  
Please write in English

If you can't see the servermap, look for strange logs in the agent and collector logs.
