### ISSUE TITLE
PINPOINT Threshold Settings by Resource?

### ISSUE THREAD

**Issue by okddu** [naver/pinpoint#6559]
Is there any guide explaining the screen to set real time SMS / EMAIL threshold among PINPOINT functions?
(PINPOINT 기능중 실시간 SMS/EMAIL 임계치설정하는 화면을 설명해주는 가이드는 없나요?)

**Comment by RoySRose** [comment]
Hello, @okddu 

There is one on the [homepage](https://naver.github.io/pinpoint/alarm.html)
If you're looking for a more sophisticated guide. There isn't one. 
Guides are also welcome to contribute

**Comment by okddu** [comment]
Hi!!  @RoySRose 
thank you!! 
Is this guide the best? Haven't you seen a better guide?
