### ISSUE TITLE
No data collected for a Spring Boot application

### ISSUE THREAD

**Issue by devnewton** [naver/pinpoint#6563]
#### Prerequisites

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
1.8.5

#### Describe your problem**
I have setup an [pinpoint-docker](https://github.com/naver/pinpoint-docker) instance to monitor a Spring Boot application.

All dashboard are empty with "No data collected" message.

#### What have you done?
Steps you have taken to trigger the problem, for example:
1. Started [pinpoint-docker](https://github.com/naver/pinpoint-docker)
2. Started a Spring Boot application (as an executable war) with pinpoint agent attached
3. The application shows up into the web UI.
4. No trace shows up in the web UI ("No data collected" message.)

#### Screenshots
![image](https://user-images.githubusercontent.com/1859457/75889868-d5b26900-5e2d-11ea-8d60-9d3558da2a44.png)

#### Logs

[agent.zip](https://github.com/naver/pinpoint/files/4287917/agent.zip)

**Comment by jaehong-kim** [comment]
@devnewton 
Did you send a request to the server?
If so, what kind of request do you send?
HTTP or Websocket?

**Comment by devnewton** [comment]
I send some simple http requests (GET and POST).

**Comment by kumar4sun** [comment]
I am seeing the same issue and keep on seeing
 Info
There is no data.

Sent multiple request to the springboot app but no luck

**Comment by jaehong-kim** [comment]
@devnewton @kumar4sun 
Please retry with version 2.0.1.
https://github.com/naver/pinpoint/releases/tag/v2.0.1

**Comment by kumar4sun** [comment]
@devnewton newer version has lots of issues and i am not even able to bing up the containers.

**Comment by RoySRose** [comment]
Hello, @kumar4sun 
If you were using images from https://github.com/naver/pinpoint-docker
There were some issues with the images and now solved with few contributors.
You can try it again. and if you find any more issues you can post an issue at `pinpoint-docker` repository.

**Comment by ChenXiaoTemp** [comment]
I found that,if you use pinpoint docker , you need use profiler.transport.module=THRIFT and you need change the configuration of exposed ports of pinpoint-collector in  pinpont-docker/docker-compose.yaml to expose 9994,9995,9996 with tcp and udp protocol

The pinpoint agent default use GRPC , I do not kown why it can not work, I try to detect whether the port for GRPC port is open , I found if I use `nc -vuz localhost 9993` on the docker host machinne, it tells succefully, but if I use IP (i.e. `nc -vuz my-ip 9993`) then it failed.

I do not know why 

But I changed to thrift and expose 9994,9995,9996 it works.

**Comment by ChenXiaoTemp** [comment]
I use 2.0.1 version

**Comment by RoySRose** [comment]
Thank you for the sharing @ChenXiaoTemp. 

But exposing thrift port should not be the issue for docker image v.1.8.5.
Since the default protocol has been changed since v2.0.0
