### ISSUE TITLE
Maven build Error(pinpoint-web FAILURE)

### ISSUE THREAD

**Issue by crown-choi** [naver/pinpoint#6569]
Hello, I'm getting the following error 
How can I solve this problem?

mvn -version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-18T02:33:14+08:00)
Maven home: /app/apache-maven-3.5.4
Java version: 1.8.0_242, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1062.12.1.el7.x86_64", arch: "amd64", family: "unix"

Java -version
export JAVA_HOME=/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64
export JAVA_6_HOME=/lib/jvm/java-1.6.0-openjdk-1.6.0.41.x86_64
export JAVA_7_HOME=/lib/jvm/java-1.7.0-openjdk-1.7.0.251-2.6.21.0.el7_7.x86_64
export JAVA_8_HOME=/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64
export JAVA_9_HOME=/app/java-se-9-ri/jdk-9

--------------------------------------------------------------------

[INFO] pinpoint-netty-plugin-it ........................... SUCCESS [  1.205 s]
[INFO] pinpoint-ning-aysncclient-plugin-it ................ SUCCESS [  1.221 s]
[INFO] pinpoint-okhttp-plugin-it .......................... SUCCESS [  1.420 s]
[INFO] pinpoint-thrift-plugin-it .......................... SUCCESS [  1.946 s]
[INFO] pinpoint-rabbitmq-plugin-it ........................ SUCCESS [  5.007 s]
[INFO] pinpoint-rxjava-plugin-it .......................... SUCCESS [  1.536 s]
[INFO] pinpoint-spring-plugin-it .......................... SUCCESS [  1.562 s]
[INFO] pinpoint-web ....................................... FAILURE [33:46 min]
[INFO] pinpoint-hbase-distribution ........................ SKIPPED
[INFO] pinpoint-hbase-schema-definition ................... SKIPPED
[INFO] pinpoint-hbase-schema .............................. SKIPPED
[INFO] pinpoint-hbase-schema-manager ...................... SKIPPED
[INFO] pinpoint-flink 2.0.0-SNAPSHOT ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 37:42 min
[INFO] Finished at: 2020-03-06T08:50:32+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.9.0:npm (npm run build) on project pinpoint-web: Failed to run task: 'npm run build:real' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 137 (Exit value: 137) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pinpoint-web

**Comment by koo-taejin** [comment]
hi @crown-choi 

Exit value 137 means out of memory.
This may be caused by insufficient memory.

Old 2.0.0-SNAPSHOT version was needed a lot of memory for building web module. 
The latest version 2.0.0-SNAPSHOT version(master) had resolved this issue.


* If do not use latest 2.0.0-SNAPSHOT version
 -> to use latest 2.0.0-SNAPSHOT version
 
* If use latest 2.0.0-SNAPSHOT version
 -> extending memory in build environment.

thanks :)
