### ISSUE TITLE
navbar_application_fake.png

### ISSUE THREAD

**Issue by pillaimichael1976** [naver/pinpoint#657]
I am not able to see 'Application Select' select box. Instead there is a fake box which is an image. (navbar_application_fake.png)

**Comment by Xylus** [comment]
Hi,
if the Pinpoint Web cannot connect to Hbase, or if there are no agent data, the application select box remains unselectable.

Not entirely sure if this is the issue here, but please check your Pinpoint Web log and see if it's connected to Hbase.

**Comment by xxxatt** [comment]
I have got the same issue.

The agent data has been stored into Hbase. e.g. scan 'AgentInfo' I can see the results. 

And here is some of the logs from Pinpoint web (sorry for replacing the real host names/ips). 

16:11:03 INFO (c.n.p.c.h.PooledHTableFactory      :67 ) create HConnectionThreadPoolExecutor poolSize:128, workerQueueMaxSize:5120
16:11:03 WARN (o.a.h.u.NativeCodeLoader           :62 ) Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16:11:03 INFO (o.a.h.h.z.RecoverableZooKeeper     :121) Process identifier=hconnection-0x4edb2441 connecting to ZooKeeper ensemble=xxx.xxx.xxx.167:2181,xxx.xxx.xxx.166:2181,xxx.xxx.xxx.168:2181
16:11:03 INFO (o.a.z.ZooKeeper                    :100) Client environment:zookeeper.version=3.4.5-cdh5.4.0--1, built on 04/21/2015 19:12 GMT
16:11:03 INFO (o.a.z.ZooKeeper                    :100) Client environment:host.name=xxx-05
16:11:03 INFO (o.a.z.ZooKeeper                    :100) Client environment:java.version=1.7.0_45
16:11:03 INFO (o.a.z.ZooKeeper                    :100) Client environment:java.vendor=Oracle Corporation
16:11:03 INFO (o.a.z.ZooKeeper                    :100) Client environment:java.home=/opt/program/jdk1.7.0_45/jre
16:11:03 INFO (o.a.z.ZooKeeper                    :100) Client environment:java.class.path=/opt/program/tomcat/bin/bootstrap.jar:/opt/program/pinpoint-web-1.5.0-SNAPSHOT/bin/tomcat-juli.jar
16:11:03 INFO (o.a.z.ZooKeeper                    :100) Client environment:java.library.path=/home/xxx/.rvm/usr/lib:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
16:11:03 INFO (o.a.z.ZooKeeper                    :100) Client environment:java.io.tmpdir=/opt/program/pinpoint-web-1.5.0-SNAPSHOT/temp
16:11:03 INFO (o.a.z.ZooKeeper                    :100) Client environment:java.compiler=<NA>
16:11:03 INFO (o.a.z.ZooKeeper                    :100) Client environment:os.name=Linux
16:11:03 INFO (o.a.z.ZooKeeper                    :100) Client environment:os.arch=amd64
16:11:03 INFO (o.a.z.ZooKeeper                    :100) Client environment:os.version=2.6.32-504.12.2.el6.x86_64
16:11:03 INFO (o.a.z.ZooKeeper                    :100) Client environment:user.name=xxx
16:11:03 INFO (o.a.z.ZooKeeper                    :100) Client environment:user.home=/home/xxx
16:11:03 INFO (o.a.z.ZooKeeper                    :100) Client environment:user.dir=/opt/program/pinpoint-web-1.5.0-SNAPSHOT/logs
16:11:03 INFO (o.a.z.ZooKeeper                    :438) Initiating client connection, connectString=xxx.xxx.xxx.167:2181,xxx.xxx.xxx.166:2181,xxx.xxx.xxx.168:2181 sessionTimeout=90000 watcher=hconnection-0x4edb24410x0, quorum=xxx.xxx.xxx.167:2181,xxx.xxx.xxx.166:2181,xxx.xxx.xxx.168:2181, baseZNode=/hbase
16:11:03 INFO (o.a.z.ClientCnxn                   :975) Opening socket connection to server xxx-06/xxx.xxx.xxx.xxx:2181. Will not attempt to authenticate using SASL (unknown error)
16:11:03 INFO (o.a.z.ClientCnxn                   :852) Socket connection established to xxx-06/xxx.xxx.xxx.168:2181, initiating session
16:11:03 INFO (o.a.z.ClientCnxn                   :1235) Session establishment complete on server xxx-06/xxx.xxx.xxx.168:2181, sessionid = 0x24ddc0d3d6f4922, negotiated timeout = 60000

......

16:11:04 INFO (o.s.b.f.c.PropertiesFactoryBean    :172) Loading properties file from class path resource [pinpoint-web.properties]
16:11:05 INFO (o.a.h.h.z.RecoverableZooKeeper     :121) Process identifier=hconnection-0x2f013dc0 connecting to ZooKeeper ensemble=xxx.xxx.xxx.167:2181,xxx.xxx.xxx.166:2181,xxx.xxx.xxx.168:2181
16:11:05 INFO (o.a.z.ZooKeeper                    :438) Initiating client connection, connectString=xxx.xxx.xxx.167:2181,xxx.xxx.xxx.166:2181,xxx.xxx.xxx.168:2181 sessionTimeout=90000 watcher=hconnection-0x2f013dc00x0, quorum=xxx.xxx.xxx.167:2181,xxx.xxx.xxx.166:2181,xxx.xxx.xxx.168:2181, baseZNode=/hbase
16:11:05 INFO (o.a.z.ClientCnxn                   :975) Opening socket connection to server xxx-06/xxx.xxx.xxx.168:2181. Will not attempt to authenticate using SASL (unknown error)
16:11:05 INFO (o.a.z.ClientCnxn                   :852) Socket connection established to xxx-06/xxx.xxx.xxx.168:2181, initiating session
16:11:05 INFO (o.a.z.ClientCnxn                   :1235) Session establishment complete on server xxx-06/xxx.xxx.xxx.168:2181, sessionid = 0x24ddc0d3d6f4923, negotiated timeout = 60000
16:11:05 INFO (o.s.c.e.EhCacheManagerFactoryBean  :110) Initializing EhCache CacheManager
16:11:05 INFO (c.n.p.w.c.WebConfig                :59 ) WebConfig [clusterEnable=false, clusterTcpPort=9995, clusterZookeeperAddress=127.0.0.1:22213, clusterZookeeperSessionTimeout=3000]
16:11:05 INFO (c.n.p.w.s.PinpointSocketManager    :71 ) PinpointSocketManager enable false.
16:11:05 WARN (w.d.h.HbaseSqlMetaDataCompatibility:40 ) SqlMetaData table exists. Recommend that only use SqlMetaData_Ver2 table.
16:11:05 INFO (o.s.w.c.ContextLoader              :313) Root WebApplicationContext: initialization completed in 3795 ms
16:11:05 INFO (o.s.w.s.DispatcherServlet          :454) FrameworkServlet 'pinpoint-web': initialization started

**Comment by Xylus** [comment]
Could you try invoking `/applications.pinpoint` on your Pinpoint web instance and post the response?
ex `http://$PINPOINT_WEB_URL/applications.pinpoint`

**Comment by xxxatt** [comment]
http://m-dev05:8080/applications.pinpoint

here is the response:

[{"applicationName":"message-interfaces","serviceType":"TOMCAT","code":1010}]

**Comment by xxxatt** [comment]
![2015-06-24 9 56 39](https://cloud.githubusercontent.com/assets/4192997/8321285/781039ea-1a57-11e5-84dc-7d5fa7ceb96c.png)

there is also a javascript error, see the screenshot.

**Comment by Xylus** [comment]
Thanks for the screenshot.
It seems related to an issue fixed in 00330ce9017a690499576b5052a763f213d541f6.

Could you try again with the latest source?

**Comment by xxxatt** [comment]
Thanks, I re-build with the latest source and the issue has been fixed.
