### ISSUE TITLE
SQL-ID not found appears in the transaction List

### ISSUE THREAD

**Issue by cbn123** [naver/pinpoint#6576]
hello:
    My English is not very good, the expression may not be so clear, please forgive me!

    pinpoint version is v17.3
    hbase version  is v1.2.6
    zookeeper version  is v3.5.5 

    I modified the TTL time value of SqlMetaData_Ver2 table of HBASE library, because it takes up a lot of memory space for me, so I set it to 1day for him.
    Then when I checked the transaction List, I found that the transaction List could not display SQL, and the sql-id not found sqlId:-1 was displayed
    I searched the various log files and found no error!
    I tried to restart all the servers, but it didn't work!
    The reason for cleaning up SqlMetaData_Ver2 is that it grows to 13gb of memory per week.Six months ago, that size had never exceeded 1 gigabyte.

                                                                                                                                thanks

**Comment by emeroad** [comment]
The TTL of XXX-META-DATA must be longer than the agent lifetime.
Therefore, do not set the TTL too short or clear the table.

> The reason for cleaning up SqlMetaData_Ver2 is that it grows to 13gb of memory per week.Six months ago, that size had never exceeded 1 gigabyte.
1. Adjust the flush option of Hbase.
  - http://hadoop-hbase.blogspot.com/2014/07/about-hbase-flushes-and-compactions.html
2. Run the flush command periodically. 
  - https://github.com/naver/pinpoint/blob/master/hbase/scripts/hbase-flush-table.hbase
     I recommend linux batch shell.

**Comment by unc1** [comment]
I am running into this issue. I use to be able to see the SQL statements in each transaction and now it shows SQL-ID not found sqlId:2. I flushed the hbase tables, but that didn't work. Oh also, the DB is not large at all 250MB.
