### ISSUE TITLE
Some suggestions about the V2 UI

### ISSUE THREAD

**Issue by tankilo** [naver/pinpoint#6588]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

When we have thousands of records (here is 4780) in hbase table `ApplicatoinIndex`, the request `applications.pinpoint` to load data for applicationname dropdown will cost about 10s to 20s.(How about your perfomance?)

Based on the above facts, i feel two differences between v1 UI and v2 UI.

1. In V1 UI，when the request `applications.pinpoint` is executing, users can see the web interface framework
![image](https://user-images.githubusercontent.com/10413284/76483523-2e978800-6452-11ea-8e74-49e228e5d7f0.png)
But now the page is blank.
![image](https://user-images.githubusercontent.com/10413284/76483567-4c64ed00-6452-11ea-80de-cb3a9c19f7bb.png)

2. Page `transactionList` will also trigger appliations.pinpoint request (Though i didn't see the dropdown)， keep users waiting longer. But in V1 UI, it won't.
![image](https://user-images.githubusercontent.com/10413284/76483580-5686eb80-6452-11ea-9d9f-b15528a688cf.png)

**Comment by emeroad** [comment]
![image](https://user-images.githubusercontent.com/7564547/76485002-90f68580-645e-11ea-8f97-adc6f3d079e0.png)
![image](https://user-images.githubusercontent.com/7564547/76485151-01050b80-645f-11ea-97d4-143e3abf04c4.png)

We have over 2000 applications.
 the query speed is also less than 1 second.

**Comment by tankilo** [comment]
Thx, i will check why request is so slow here.

**Comment by tankilo** [comment]
@emeroad It turns out be that some of our applications have too much columns in one row. Our application will use new agentId if process restart. The agentId format contains timestamp.

**Comment by binDongKim** [comment]
@tankilo Since the first page starts with the application list(the  dropdown), I designed it like this but as you pointed out, the blank page without any indicator(such as loading) is likely to give a bad experience. I'm planning on redesigning the flow.
