### ISSUE TITLE
Confusion with Flink configuration

### ISSUE THREAD

**Issue by kumar4sun** [naver/pinpoint#6597]
Hi i am new to pintpoint and stated to play round with the tool. I am using Docker images to bring up the Pinpoint app. While following the instruction i am stuck with the instruction provided for Flink Configuration. The thing that i am not clear is where to build the Jar for the job or where do i get the source to build the jar. Is this as simple as creating an executable jar and uploading at Pinpoint as new Job?
Also the steps to configure our own docker container running the app for monitoring is not clear. Any assistance would be of great help.

**Comment by minwoo-jung** [comment]
@kumar4sun 
First look at the guide document
the job jar file can be obtained directly from the release note page. Or
when you build the pinpoint code yourself, a job jar file is created under the flink project.
