### ISSUE TITLE
Hbase is failing to start

### ISSUE THREAD

**Issue by kumar4sun** [naver/pinpoint#6606]
HBase while bringing up the containers is erroring out due to following : -

hbase-1.2.6/lib/jruby-complete-1.6.8.jar
hbase-1.2.6/lib/spymemcached-2.11.6.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0     78      0 --:--:-- --:--:-- --:--:--    78
starting master, logging to /opt/hbase/hbase-1.2.6/logs/hbase--master-33842653d6db.out
OpenJDK 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
2020-03-13 18:05:19,640 WARN  [main] util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
SyntaxError: /opt/hbase/hbase-create.hbase:1: syntax error, unexpected ':'

404: Not Found
   ^
    load at org/jruby/RubyKernel.java:1087
  (root) at /opt/hbase/hbase-1.2.6/bin/hirb.rb:177

**Comment by RoySRose** [comment]
Hello @kumar4sun, Some issues were found due to the change of naming rule in version.
it's being taken care of. I'm still testing a few more things. Check here for details #naver/pinpoint-docker#43
