### ISSUE TITLE
Provide SDK for operating HBase storage data

### ISSUE THREAD

**Issue by chkch** [naver/pinpoint#6611]
Hi, @koo-taejin :
Is it possible to write an SDK for manipulating the data stored in HBase, I think this can release the creative thinking of the user, and can bring many unexpected surprises in the data dimension.

I think this should be a handy task for you.

**Comment by tankilo** [comment]
In fact ,i've created one for myself at weekends. 

Pinpoint code have two dao for one hbase table.
At collector side, dao is used for inserting data.
At Web side, dao is used for querying.
![image](https://user-images.githubusercontent.com/10413284/76837370-672dcc00-686d-11ea-89f7-01b92a2d8751.png)

I found that it is really not convenient when you want to query some data without depending on pinpoint-web or pinpoint-collector.

So i write a project that mixed these two types of dao, it's not an elegant way, but it  meets my need. I may opensource it recently.

Fundamentally，pinpoint team need to [refactor code and extract  a module specifically for hbase data operations] and [both collector and web depend on it].

**Comment by chkch** [comment]
@tankilo Good, expect you to open source it, which will bring great convenience to users

**Comment by RoySRose** [comment]
@tankilo 
I'm also very interested in the subject. 
Hope you can share your knowledge with the community~

**Comment by RoySRose** [comment]
@tankilo 
Do you think you can share some of your efforts?

**Comment by chkch** [comment]
@tankilo May I ask if the project is currently open source, I ca n’t wait to experience it !

**Comment by chkch** [comment]
@emeroad Please give some attention to this issue

**Comment by RoySRose** [comment]
@chkch,
it looks like we need attention from @tankilo
