### ISSUE TITLE
io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: fff4fffd06

### ISSUE THREAD

**Issue by alanjiang** [naver/pinpoint#6612]
The collector server failed with the error log as below:

io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: fff4fffd06

Could you give me some suggestions? Thanks.

**Comment by alanjiang** [comment]
![image](https://user-images.githubusercontent.com/8122752/76838278-f5ef1880-686e-11ea-9fe9-a82c1262ec47.png)

**Comment by emeroad** [comment]
Check the agent port and collector port.

I think you are sending the wrong data.
eg) Connect to grpc port by thrift

**Comment by alanjiang** [comment]
> Check the agent port and collector port.
> 
> I think you are sending the wrong data.
> eg) Connect to grpc port by thrift

Thank you very much, now i try it.
