### ISSUE TITLE
[question] What would be the problem if the transactionSequence(long type) in transactionId overflows.

### ISSUE THREAD

**Issue by yjqg6666** [naver/pinpoint#6615]
The transactionId is composed of agentId, agent boot time and an increased long type number. What problems it would be if the long number overflows when too many rpc calls occured to one instance?

**Comment by emeroad** [comment]
**long range**
 - 2^63 ~ 2^63 – 1 -> -9223372036854775808 ~ 9223372036854775807

The long range is very very  large, so that doesn't happen.
