### ISSUE TITLE
Hi, PinPoint In the latest version (2.0.1) is support to Dubbo 2.7.x?

### ISSUE THREAD

**Issue by kenneth-hao** [naver/pinpoint#6619]

**Comment by RoySRose** [comment]
You can always check here 
http://naver.github.io/pinpoint/2.0.1/main.html#supported-modules

**Comment by kenneth-hao** [comment]
Thanks for reply.  I've already seen it. 
The document description does not support.

But this issue seems to have done?

**Comment by kenneth-hao** [comment]
So sorry, Forget this: 
https://github.com/naver/pinpoint/pull/5748

**Comment by RoySRose** [comment]
well... the document is based on automated test results.
recently integration test code is on the progress of modification.
So, it might be left out. or not yet supported.
If you can test it and share the result with the community. It would be great.

**Comment by FlourishingWorld** [comment]
so, it support dubbo 2.7?
pinpoint 1.8.5 seems not.

**Comment by FlourishingWorld** [comment]
我刚测试过了，pinpoint 2.0.1支持apache dubbo 2.7.x，太棒了。

**Comment by RoySRose** [comment]
Thanks, @FlourishingWorld for the info that it's working.

It would be better if it was in English for everyone else in the community :)

**Comment by kenneth-hao** [comment]
> 我刚测试过了，pinpoint 2.0.1支持apache dubbo 2.7.x，太棒了。

非常感谢！

**Comment by zhouhuicong** [comment]
my app dubbo version is 2.7.7 .  The Pinpoint  2.0.3 can not support this dubbo version
