### ISSUE TITLE
Collector must start before agent starting?

### ISSUE THREAD

**Issue by kichigai** [naver/pinpoint#6629]
Agent not registered after reboot collector with data clear.

How can agent registering without application restart.

**Comment by koo-taejin** [comment]
@kichigai 
I didn't understand extactly this issue. 
Please explain in as much detail as possible.

thanks

**Comment by kichigai** [comment]
@koo-taejin 
사용을 잘못 한 것이겠지만,
Pinpoint Agent 가 구동되어 있는 상태에서 Pinpoint Collector Server 를 재시작하면서 Hbase 및 Zookeepr 의 데이터를 초기화해서 구동하게되었을때 Pinpoint Agent 가 설정되어 있는 Application Web 서버를 재시작하지 않고 Agent 가 Collector 에 등록되도록 할 수 있냐는 문의였습니다.

**Comment by koo-taejin** [comment]
일단은 콜렉터가 재시작한다고 해서, Hbase나 Zookeeper의 데이터가 초기화 되지는 않습니다. 이런 경우라면 에이전트는 자동으로 재연결이 되게 되고 문제없이 사용 할 수 있습니다. 
그렇지만 직접 Hbase의 데이터를 삭제하셨다면 여러가지 데이터가 지워지기 때문에 재연결은 되겠지만, 데이터 확인이 어렵게 되는 경우가 많습니다.

**Comment by kichigai** [comment]
확인해주셔서 고맙습니다.
