### ISSUE TITLE
Logging path ignored

### ISSUE THREAD

**Issue by davide-parini** [naver/pinpoint#6640]
Running pinpoint 2.0.1.

The agent always logs in "logs" folder under the agent path, ignoring the value set with `-Dpinpoint.log`.

It seems that this is hardcoded in `com.navercorp.pinpoint.bootstrap.agentdir.AgentDirectory`:
![image](https://user-images.githubusercontent.com/38081480/77540718-e3469600-6ea3-11ea-93dc-6a3b1a42e58f.png)
...
![image](https://user-images.githubusercontent.com/38081480/77540750-f22d4880-6ea3-11ea-9b3f-76567a38f56c.png)
And than used to set a system property in `com.navercorp.pinpoint.bootstrap.PinpointStarter`, overriding any value set with `-Dpinpoint.log`:
![image](https://user-images.githubusercontent.com/38081480/77541006-5b14c080-6ea4-11ea-8643-f3169940750f.png)

**Comment by emeroad** [comment]
Currently, the pinpoint cannot change the logpath.
-Dpinpoint.log option was not intended.

**Comment by davide-parini** [comment]
Ok thank you @emeroad.

**Comment by emeroad** [comment]
If you need this feature, please contribute
We always welcome contributions.
