### ISSUE TITLE
No link between spring cloud gateway and any other microservices

### ISSUE THREAD

**Issue by stephen-liu1974** [naver/pinpoint#6642]
#### What version of pinpoint are you using?
pinpoint-docker-2.0.1 and pinpoint-agent-2.0.1

#### Describe your problem**
No link between Spring Cloud Gateway and any other applications, but the links among the other applications are OK. 

#### What have you done?
Steps you have taken to trigger the problem, for example:
1. Start pinpoint with pinpoint-docker-2.0.1 and launched spring cloud gateway app and other spring cloud app with pinpoint-agent.
2. Looks like anything ok and no exception is thrown after all startup.
3. Gateway app can be shown in pinpoint and really forwarded requests to other applications.
4. For Spring Cloud Gateway app, the only one link is from USER, the other applications have link from USER directly.

#### Screenshots
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/16795326/77614746-a690a280-6f68-11ea-92b5-377e414f0088.png">

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/16795326/77614776-bdcf9000-6f68-11ea-8054-b03cdc2ca36f.png">

**Comment by minwoo-jung** [comment]
Hi @stephen-liu1974
First, you need to check whether the library used when calling other services in spring cloud gateway is a plugin provided by pinpoint.

If it is included in pinpoint plugin but cannot be traced, please see the agent log and share any errors or unusual logs.

**Comment by stephen-liu1974** [comment]
Hi @minwoo-jung 

First, I got all the plugins from official release (2.0.1) tar and no any changes. here are plugins which related to Spring.
<img width="538" alt="image" src="https://user-images.githubusercontent.com/16795326/77774459-0fba0800-7086-11ea-8563-e56b8de2465b.png">

Second, I searched the two log files in attached zip and didn't find any ERROR or WARN. 
[logs.zip](https://github.com/naver/pinpoint/files/4394574/logs.zip)

Third, please see the following three screenshots, still no link between gateway and application(upms). And I found all the traceids were different even if it was from the same request. Actually,  I only sent three http requests from browser and all responded successfully.  
BTW,  from the second screenshot, gateway has five records with the same tx_id. from the third one, upms app has three records with the same tx_id also.

<img width="913" alt="image" src="https://user-images.githubusercontent.com/16795326/77775452-83a8e000-7087-11ea-9a00-e06c68747779.png">

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/16795326/77775556-a935e980-7087-11ea-96c9-af87e90823ad.png">

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/16795326/77775665-d5516a80-7087-11ea-9955-d2aa876a7387.png">

**Comment by stephen-liu1974** [comment]
Hi @minwoo-jung 

I remember the gateway app can't be found in web console when I used pinpoint-1.8.5, but for pinpoint-2.0.1 it is located in web console, whether it proves the plugins I am using is right.
Thank you for your help.

**Comment by minwoo-jung** [comment]
@stephen-liu1974
Unfortunately, the plugin has not been provided to track all requests of the spring cloud gateway. 
The webflux plugin also needs to be supplemented more, and it is also necessary to analyze the spring cloud gateway and provide additional plugins.
There is a webflux plugin, but not yet enough to track all requests from the spring cloud gateway.

I think it will take some time to fully track the spring cloud gateway.
