### ISSUE TITLE
Check the maxPoolSize 

### ISSUE THREAD

**Issue by VidushaZ** [naver/pinpoint#6646]
Hi pinpoint team,
Hope you guys are doing fine.

I get this exception in logs > 

2020-03-26 19:53:03 [WARN ](spanReceiverExecutor               ) The executor uses finite bounds for both maximum threads and work queue capacity, and is saturated. Check the maxPoolSize, queueCapacity, and HBase options in the configuration. maxPoolSize=6024, rejectedCount=201200

I tried increasing maxPoolsize in config but still no luck. 
This is my config looks like :
![pinpoint collector config](https://user-images.githubusercontent.com/34154568/77664817-c34acb80-6fa4-11ea-9fa0-9936ee054262.JPG)

I also want to know if it's possible to **distribute load using multiple collectors.** 

My transaction feed also looks like this. 
![pinpoint transactions](https://user-images.githubusercontent.com/34154568/77665082-276d8f80-6fa5-11ea-8db4-3cca1d7c17d6.JPG)

Regards

**Comment by minwoo-jung** [comment]
Hi @VidushaZ
I also want to know if it's possible to distribute load using multiple collectors.
-> It's unfortunate that I can't give you any good advice, but I think it would be helpful to look at this issue.
