### ISSUE TITLE
Distribute load using multiple collectors?

### ISSUE THREAD

**Issue by VidushaZ** [naver/pinpoint#6659]
Hi Pinpoint team,

Is it possible to distribute load using multiple collectors? any additional configuration to do?
I tried increasing max pool size and stuffs in collector config. but it seems not enough. Please help!

This is my config.

![image](https://user-images.githubusercontent.com/34154568/77889093-ee763900-728a-11ea-984c-aa077f486798.png)

Regards.

**Comment by emeroad** [comment]
Yes. Basically the collector is stateless.
Horizontal Scaling is not a problem.
I recommend deploying a load balancer in front of the collector.

**Comment by VidushaZ** [comment]
@emeroad Will it be possible to do with a software like Nginx? Or It will have to be a hardware load balancer?
