### ISSUE TITLE
Pinpoint integration Failed with Akka-Actor Runs in Scala

### ISSUE THREAD

**Issue by dinesh4747** [naver/pinpoint#6673]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

I wanted to integrate pinpoint with micro service running on scala based Akka-actor model and I tried running with below argument but it failed as "Error: Could not find or load main class scala"

Scala arguments - **java -javaagent:/Users/dnithya/agent/pinpoint-agent-2.0.1/pinpoint-bootstrap-2.0.1.jar -Dpinpoint.agentId=carbon-id -Dpinpoint.applicationName=stream scala build.jar** 

1. I could see plugins available for Akka-actor but wanted to confirm whether it supports scala language or not
2. Is there any separate config i need to configure for scala ?

**Comment by dinesh4747** [comment]
@koo-taejin - Could you please shed some light here, I see a PR and plugin available for akka-actor for scala and I wanted to confirm that and direct me If I am configuring the parameters differently

1. I could see your contributions on the PR for **Akka-Http for Scala** Plugin Contribution - https://github.com/naver/pinpoint/pull/3834 
2. **code base** - https://github.com/lopiter/pinpoint/blob/add-akka-http-plugin/plugins/akka-http/src/main/java/com/navercorp/pinpoint/plugin/akka/http/AkkaHttpPlugin.java#L107

**Comment by dinesh4747** [comment]
@emeroad - can someone help me on clarifying whether it supports akka-actor in scala ?

**Comment by koo-taejin** [comment]
hi @dinesh4747 

You can use pinpoint with `-javaagent` command, even if use Scala.
Akka-http can be traced by changing the parameter settings, but Pinpoint does not support akka-actor tracking.

thanks :)
