### ISSUE TITLE
not able to get applications.pinpointlist

### ISSUE THREAD

**Issue by vikasmsg** [naver/pinpoint#6674]
![Screenshot 2020-04-02 at 7 09 41 PM](https://user-images.githubusercontent.com/37859740/78267641-d15c9700-7524-11ea-8bcb-3afb139fbe6f.png)

I got this issue. i am not geting any error. Can you please help us to resolve this.

**Comment by RoySRose** [comment]
Hello, @vikasmsg 

are you using Pinpoint through AWS?
I think I can see aws in the link.

**Comment by vikasmsg** [comment]
aws custom server.

**Comment by emeroad** [comment]
Stat api is very slow, so be aware of the following:
1. The timeout of WebServer or WAS must be long.
2. WAS must have enough heap memory.

**Comment by vikasmsg** [comment]
how much heap memory ?

**Comment by emeroad** [comment]
The heap memory depends on the number of agents.
Increase heap memory when OOM occurs when calling API.

**Comment by vikasmsg** [comment]
I have only one agent

**Comment by vikasmsg** [comment]
from where web takes the data for this api?

**Comment by vikasmsg** [comment]
I have assigned 5GB ram to this pod but still same error.

**Comment by emeroad** [comment]
Agent number is too small, so I don't think it's the problem above.
Check the logs on your web server.

**Comment by vikasmsg** [comment]
This problem was solved . The issue was with hbase server.

**Comment by RoySRose** [comment]
@vikasmsg 
Do you think you can share what kind of problem was with the hbase server?
It can help the community and others who are/will experiencing similar problems
