### ISSUE TITLE
I want to use the Java hbase client to get the data in hbase, but I don't know the data encoding

### ISSUE THREAD

**Issue by xinlan** [naver/pinpoint#6676]
I want to use the Java hbase client to get the data in hbase, but I don't know the data encoding

**Comment by ccuwangjun** [comment]
wao

**Comment by emeroad** [comment]
https://github.com/naver/pinpoint/tree/master/web/src/main/java/com/navercorp/pinpoint/web/dao/hbase
Refer to the hbase package.
