### ISSUE TITLE
how to NON-HTTP Service Trace

### ISSUE THREAD

**Issue by itzmehs** [naver/pinpoint#6688]
Hello.
First thank you for your support.

I would like to trace for non-http service.
I've using scouter and trace non-http service with configured below 

_trace_auto_service_enabled=false
_trace_auto_service_backstack_enabled=true
hook_service_patterns=comn.batch.framework.launcher.WebAppJobLauncher.runJob
hook_method_access_public_enabled=true
hook_method_access_private_enabled=true
hook_method_access_protected_enabled=true
hook_method_access_none_enabled=false
hook_method_ignore_prefixes=get,set

I tired to trace non-http service with using pinpoint which options like that :

profiler.entrypoint=comn.batch.framework.launcher.WebAppJobLauncher.runJob

runJob is Method. 

But, pinpoint has couldn't trace anythings.

how can I trace non-http service ?

**Comment by itzmehs** [comment]
Sorry. I sovled it.
it's work after add config in release/pinpoint-env.config with profiler.entrypoint=comn.batch.framework.launcher.WebAppJobLauncher.runJob

thank you for read.

**Comment by RoySRose** [comment]
Great :) 
Pinpoint needs a certain entry-point, if Pinpoint-Agent isn't attached ahead.
