### ISSUE TITLE
Is it possible to add a slider

### ISSUE THREAD

**Issue by chengruyi** [naver/pinpoint#6690]
![image](https://user-images.githubusercontent.com/10740595/78853044-84ab1b80-7a50-11ea-981d-ac0bf9a302a7.png)

**Comment by chengruyi** [comment]
Sometimes the method name and argument  is very long and I have to copy it

**Comment by chengruyi** [comment]
thx!!!

**Comment by RoySRose** [comment]
Hello, @chengruyi 

What do you mean by slider?
The tab is already dynamically changeable. 

We concern that sometimes the depth of the call stack is too long to display(same effect with very log method name)
Do you have any good idea for this?

**Comment by chengruyi** [comment]
I turned off the record attribute length limit

**Comment by chengruyi** [comment]
I mean Argument can slide

**Comment by chengruyi** [comment]
![image](https://user-images.githubusercontent.com/10740595/78871042-ae2c6d00-7a79-11ea-8646-af3869e0ec52.png)

**Comment by RoySRose** [comment]
oh.. you mean. one column already exceeds the width of the window itself.
So you are suggesting to add a slide for a certain column, in this case, argument?

Have you ever saw UI that you've suggested on other systems? or anywhere?

**Comment by chengruyi** [comment]
Yes i think you get what i mean

**Comment by RoySRose** [comment]
@chengruyi 

Have you ever saw UI that you've suggested on other systems? or anywhere?
I'm not a UI expert, but the only design I can think of is not good enough

**Comment by chengruyi** [comment]
Sorry i haven't seen it
