### ISSUE TITLE
Input Query View won't change When change the Server

### ISSUE THREAD

**Issue by HuHaichun** [naver/pinpoint#6691]
I'm using new released Pinpoint 2.0.1
One of my backend common service is Redis including 2 servers. 
![image](https://user-images.githubusercontent.com/38070049/78853682-0c455a00-7a52-11ea-85af-5f3f50d4c588.png)

I click the drop box on the left-top of the website, two servers are listed. When I choose one of them , the Input application source listed below won't change. This won't help to trace the applications which connect to each different server. Hope to improve.
![image](https://user-images.githubusercontent.com/38070049/78853845-79f18600-7a52-11ea-9d2b-1c2825409da1.png)
![image](https://user-images.githubusercontent.com/38070049/78853963-c3da6c00-7a52-11ea-9926-e7f6cbbc2f3f.png)

**Comment by HuHaichun** [comment]
No response or feedback ？：(

**Comment by RoySRose** [comment]
@HuHaichun 
You are right. I've checked the behavior with my tests too.
I agree that it would be better if your suggestions were applied to the Pinpoint.

**Comment by HuHaichun** [comment]
Is it possible to apply to the Pinpoint?
