### ISSUE TITLE
1.8.5 update 2.0.1

### ISSUE THREAD

**Issue by jinnery** [naver/pinpoint#6701]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

I'm  from 1.8.5 update to 2.01 .
first: document there are many error.  the  "pinpoint-grpc-collector.properties " file should be pinpoint-collector-grpc.properties。 
se## Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

I'm  from 1.8.5 update to 2.01 .
first: document there are many error.  the  "pinpoint-grpc-collector.properties " file should be pinpoint-collector-grpc.properties。 
second: the pinpoint-collector/WEB-INF/classes/profiles/release/pinpoint-collector-env.properties must be modify ：‘’pinpoint.zookeeper.address=‘’
third：After upgrading my agent must be reboot。else the web can't view
the third Question  very important。if don't solve i can't upgrade

**Comment by RoySRose** [comment]
Hello, @jinnery 
Thank you for your interest in Pinpoint.
If there are typos in the document. Please make a pull request and contribute your work :)

The third one is not currently possible.
