### ISSUE TITLE
Pinpoint-agent-2.0.1 did not record http request.

### ISSUE THREAD

**Issue by yuchenzhen** [naver/pinpoint#6702]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [Y] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

I have check the simliar issue which is cause by the pinpoint.config profiler.sampling.rate setting . But my setting is  profiler.sampling.rate = 1 . It seems that's not the same problem.

#### What version of pinpoint are you using?
master/v2.0
pinpoint-collector-2.0.1.war
pinpoint-agent-2.0.1.tar.gz
hbase-1.2.12-bin.tar.gz
apache-tomcat-8.0.36.tar.gz

#### Describe the bug
Pinpoint-agent-2.0.1 did not record http request.  I set up a demo web server and send simple Http request . Only the first request does the pinpoint-agent record. After the first request , I send many http request but it did not record it .

![image](https://user-images.githubusercontent.com/16936490/79033643-7bea4f00-7be2-11ea-9679-a668137b3df9.png)

 But pintpoint-agent debug log show me that "  TraceID not exist. canSampled is false. skip trace. requestUrl:/test, remoteAddr: xxx.xx.xx.xxx"
![image](https://user-images.githubusercontent.com/16936490/79033608-04b4bb00-7be2-11ea-9cee-57580eb54ce7.png)

When I set request Header Pinpoint-Sampled: s1 , It still show me the same debug info . 
![image](https://user-images.githubusercontent.com/16936490/79033597-f23a8180-7be1-11ea-9460-1ca423be8274.png)

I look into pinpoint-web . I find that jvm monitor works fine. 

![image](https://user-images.githubusercontent.com/16936490/79033592-e3ec6580-7be1-11ea-9846-f17b9998dec4.png)

#### What did you do to trigger the bug?
Steps to reproduce, for example:
here is my pinpoint.config
```
# Allow sampling.
profiler.sampling.enable=true

# 1 out of n transactions will be sampled where n is the rate. (1: 100%, 20: 5%)
profiler.sampling.rate=1

# Permits per second, if throughput is 0, it is unlimited.
# "New" is a transaction that is newly traced.
profiler.sampling.new.throughput=0
# "Continue" is a transaction that is already being tracked.
profiler.sampling.continue.throughput=0
```

My web server is a simple tomcat server . I don't think that is a problem.

#### Logs
If applicable, please attach agent/collector/web DEBUG log that includes the code execution that led to the bug. In case of agents, including the start-up log may be of great help.

#### Additional context
Add any other context about the problem here, such as affected library for agents, how your collector/web/hbase is set up if applicable.

**Comment by koo-taejin** [comment]
hi @yuchenzhen 

I think you changed the resources/pinpoint.config setting, not /{$env}/pinpoint-env.config.

Please, check above issue at following link, 
https://github.com/naver/pinpoint/blob/master/doc/installation.md#profiles-2

thanks :)

**Comment by yuchenzhen** [comment]
> hi @yuchenzhen
> 
> I think you changed the resources/pinpoint.config setting, not /{$env}/pinpoint-env.config.
> 
> Please, check above issue at following link,
> https://github.com/naver/pinpoint/blob/master/doc/installation.md#profiles-2
> 
> thanks :)

thank you !!  I did not realise that in version 2.0+ , the profile.config has been moved in the /profiles/release/ location .
