### ISSUE TITLE
 Delete HBASE data and customize RDBMS

### ISSUE THREAD

**Issue by hwoh99** [naver/pinpoint#6711]
Hi. I am a Korean developer.
I'm not good at English, but all questions are English, so I ask in English.
Please answer in Korean.

I am using Pinpoint and the data is infinitely accumulated in Hbase. 
This will be a problem someday.

I want to delete the old data.
and I also want to replace Hbase with RDBMS.

**Comment by koo-taejin** [comment]
hi @hwoh99 

Please use translator :)

Pinpoint does not have a way to convert HBase data to RDBMS.
If you want to cleanup old data, to use Hbase TTL.

thanks :)

**Comment by RoySRose** [comment]
@hwoh99 

Currently, it's not possible to replace HBase with any other Database.
But all the interfaces are ready, you can develop one and contribute to the community. 
It will be awsome!

**Comment by hwoh99** [comment]
Thank you for answer.
