### ISSUE TITLE
quickstart-web.sh error

### ISSUE THREAD

**Issue by hatemyselfandyouall** [naver/pinpoint#6714]
#### Describe the bug
I run quick-start/bin/start-web.sh，and get a error,this is error log

#### Logs
`starting pinpoint-quickstart-web. 0 /180 sec(close wait limit).
starting pinpoint-quickstart-web. 175 /180 sec(close wait limit).
starting pinpoint-quickstart-web. 180 /180 sec(close wait limit).
---pinpoint-quickstart-web initialization failed. pid=31163.---
quickstart/bin/start-web.sh: line 146: kill: (31163) - No such process`

`cat quickstart/logs/quickstart.web.log      
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.navercorp.pinpoint:pinpoint-quickstart-web:war:2.0.2-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ com.navercorp.pinpoint:pinpoint-quickstart-web:${maven.pinpoint.version}, /opt/pinpoint-master/quickstart/web/pom.xml, line 11, column 14
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-war-plugin is missing. @ com.navercorp.pinpoint:pinpoint-quickstart-web:${maven.pinpoint.version}, /opt/pinpoint-master/quickstart/web/pom.xml, line 30, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] -----------< com.navercorp.pinpoint:pinpoint-quickstart-web >-----------
[INFO] Building Pinpoint Web QuickStart 2.0.2-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[WARNING] The POM for com.navercorp.pinpoint:pinpoint-web:war:2.0.2-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.278 s
[INFO] Finished at: 2020-04-15T11:28:51+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project pinpoint-quickstart-web: Could not resolve dependencies for project com.navercorp.pinpoint:pinpoint-quickstart-web:war:2.0.2-SNAPSHOT: Could not find artifact com.navercorp.pinpoint:pinpoint-web:war:2.0.2-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException`
#### Additional context
what should I do to solve this error

**Comment by koo-taejin** [comment]
@hatemyselfandyouall 

Logs let us know that Maven can not find dependency.

Please check you have builded whole project, before run Quickstart.

thanks :)

**Comment by hatemyselfandyouall** [comment]
> @hatemyselfandyouall
> 
> Logs let us know that Maven can not find dependency.
> 
> Please check you have builded whole project, before run Quickstart.
> 
> thanks :)

thank you for your help
