### ISSUE TITLE
dubbo 2.7.1  consumer side does not show the provider, but in provider side, consumer can be shown

### ISSUE THREAD

**Issue by wangran123** [naver/pinpoint#6716]
#### What version of pinpoint are you using?
agent 2.0.1
collector 1.7.2
web 1.7.2

#### Describe your problem**
dubbo 2.7.1  consumer side does not show the provider, but in provider side, consumer can be shown

#### What have you done?
1.i saw consumer and provider agent log, but nothing found

2.i found that in the single request's server map ui, the request map can be shown normally

#### Screenshots
Service A ui(dubbo consumer):
1. consumer doesn't show the provider:
![image](https://user-images.githubusercontent.com/6057464/79309428-d9f19c00-7f2c-11ea-95e0-973490bb5254.png)
Serivce B ui(dubbo provider):
2.provider show the consumer:
![image](https://user-images.githubusercontent.com/6057464/79309579-1a511a00-7f2d-11ea-99f2-2007fbc8c635.png)
3.in the Service A(consumer) single request Server Map ui, the request map and service b(provider) can be shown normally
![image](https://user-images.githubusercontent.com/6057464/79310079-f04c2780-7f2d-11ea-93a0-5b1b07222077.png)

I want the consumer side to show the provider side, what should I do?

**Comment by RoySRose** [comment]
Hello, @wangran123 

Please check version compatibility 
http://naver.github.io/pinpoint/2.0.1/main.html#upgrade-consideration

**Comment by wangran123** [comment]
i updated all componets to 2.0.1, and it's work find. Thanks a lot
