### ISSUE TITLE
could give me some suggestion,if i want to develop a simple golang agent?

### ISSUE THREAD

**Issue by monkeyming** [naver/pinpoint#6727]
our code need a golang agent

**Comment by RoySRose** [comment]
Check the homepage first
https://naver.github.io/pinpoint/overview.html
https://naver.github.io/pinpoint/techdetail.html

This page may help you get some ideas

**Comment by monkeyming** [comment]
> Check the homepage first
> https://naver.github.io/pinpoint/overview.html
> https://naver.github.io/pinpoint/techdetail.html
> 
> This page may help you get some ideas

thanks! I had read .
