### ISSUE TITLE
plugins-it-jdbc-test cause compilation failure.

### ISSUE THREAD

**Issue by yjqg6666** [naver/pinpoint#6746]
#### What version of pinpoint are you using?
master/v2.0.2.

#### Describe the bug
run `./mvnw clean source:jar install` and got the following error:

>  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project pinpoint-plugin-it-jdbc-test: Compilation failure: Compilation failure: 
> [ERROR] /Users/user/code/pinpoint/plugins-it/plugins-it-jdbc-test/src/main/java/com/navercorp/pinpoint/pluginit/jdbc/template/DriverManagerDataSource.java:[10,7] error: DriverManagerDataSource is not abstract and does not override abstract method getParentLogger() in CommonDataSource
> [ERROR] /Users/user/code/pinpoint/plugins-it/plugins-it-jdbc-test/src/main/java/com/navercorp/pinpoint/pluginit/jdbc/template/TransactionDataSource.java:[29,7] error: TransactionDataSource is not abstract and does not override abstract method getParentLogger() in CommonDataSource
> [ERROR] /Users/user/code/pinpoint/plugins-it/plugins-it-jdbc-test/src/main/java/com/navercorp/pinpoint/pluginit/jdbc/template/TransactionDataSource.java:[131,18] error: UnclosedConnection is not abstract and does not override abstract method getNetworkTimeout() in Connection

#### What did you do to trigger the bug?
Compile the new version from the source code at git tag v2.0.2.

#### Expected behavior
No error and successful compilation.

#### Extra:

- failed on MacOs Catalina 10.15.4 (19E287) and JDK OpenJDK 1.8.0_222
- failed on Linux  Kernel 5.4.32 and JDK OpenJDK 1.8.0_232

#### Workaround
Skip the compilation for test source code. It's strange that it works only in linux not in macos. But still hope that this issue can be fixed.
`./mvnw clean source:jar install -Dmaven.test.skip=true`

**Comment by emeroad** [comment]
https://naver.github.io/pinpoint/installation.html#2-building-pinpoint-optional

JDK6 is required for compilation.
I recommend installing JDK6

**Comment by yjqg6666** [comment]
The environment is OK. The version 1.8.5 can be build successfully.

` for i in `env |grep JAVA`;do n=$(echo $i|cut -d"=" -f1);p=$(echo $i|cut -d"=" -f2);echo -e "\n\n"$n;$p/bin/java -version;done`

> JAVA_11_HOME
> openjdk version "11.0.5" 2019-10-15
> OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
> OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)
> 
> JAVA_6_HOME
> java version "1.6.0_45"
> Java(TM) SE Runtime Environment (build 1.6.0_45-b06)
> Java HotSpot(TM) 64-Bit Server VM (build 20.45-b01, mixed mode)
> 
> JAVA_7_HOME
> java version "1.7.0_80"
> Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
> Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
> 
> JAVA_8_HOME
> openjdk version "1.8.0_232"
> OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
> OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)
> 
> JAVA_9_HOME
> openjdk version "9"
> OpenJDK Runtime Environment (build 9+181)
> OpenJDK 64-Bit Server VM (build 9+181, mixed mode)
> 
> JAVA_HOME
> openjdk version "1.8.0_232"
> OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
> OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)
>

**Comment by yjqg6666** [comment]
I checked JDK6/javax.sql.CommonDataSource interface which has no getParentLogger() method. The getParaentLogger() method is added since JDK 1.7.  Should i set the JAVA_HOME to JDK1.6 ?

**Comment by yjqg6666** [comment]
I figure out why it's not working. Since no jdk 1.6 for MacOS, JAVA_6_HOME is set to JDK7.
