### ISSUE TITLE
"Done" button is blocked with (0/0) followed. The "Done" button is at the top of filteredMap page

### ISSUE THREAD

**Issue by guzy** [naver/pinpoint#675]
When I right-click the link between user and tomcat, choose "Filter Transaction", I would be blocked at "Done", which is the button at the top of page. Behind the "Done" element is " (0/0)". Who can tell me why is ‘(0/0)’ here?
Many thanks.
![filtermap-error](https://cloud.githubusercontent.com/assets/5031962/8399491/1fdcc04c-1e42-11e5-9701-e00efa85d06a.jpg)

**Comment by guzy** [comment]
I solved the above problem by building with the latest code in git, not in releases. But I got another problem:
When I right-click the link between user and tomcat, choose "Filter Transaction", but I was blocked at "Done". Behind the "Done" element is "<span class="ng-binding ng-hide" ng-show="oTimeSliderVoService.getCount() && oTimeSliderVoService.getTotal()"> (0/0)</span>". Who can tell me why is ‘(0/0)’ here?

**Comment by Xylus** [comment]
Hi guzy, thanks for the detailed explanation.
We'll take a look at the issue and follow up if we find out anything.

**Comment by Xylus** [comment]
Seems like a bug on our end.
Issue reported to @denzels, he'll push a fix for it soon.

Thank you very much for reporting!

**Comment by Xylus** [comment]
loading icon bug fixed, closing issue.
If you've more questions, feel free to reopen the issue.

Thanks again.
