### ISSUE TITLE
how can i get the nginx request time

### ISSUE THREAD

**Issue by MarsYoung** [naver/pinpoint#6772]
$request_time:
request processing time in seconds with a milliseconds resolution; time elapsed between the first bytes were read from the client and the log write after the last bytes were sent to the client.

So, how can we get the  param D  when the api server begin to process ?
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

**Comment by MarsYoung** [comment]
may be we need a nginx plugin to collector data

**Comment by koo-taejin** [comment]
hi @MarsYoung 

Please check you can solve this issue via this [link].(https://github.com/naver/pinpoint/blob/master/doc/proxy-http-header.md)

thanks :)

**Comment by minwoo-jung** [comment]
The link has been changed as below.
- https://pinpoint-apm.gitbook.io/pinpoint/documents/proxy-http-header#proxy-monitoring-using-http-headers
