### ISSUE TITLE
nacos registry question

### ISSUE THREAD

**Issue by xiaofeng886521** [naver/pinpoint#6776]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

when we use the Nacos registry , the gateway data is not displayed in the pinpoint

**Comment by koo-taejin** [comment]
hi @xiaofeng886521 

Pinpoint does not support Nacos plugin. 
If you could make a Nacos plugin and contribute to us, it would be very helpful for us.

thanks :)
