### ISSUE TITLE
how can i use the async thread plugin

### ISSUE THREAD

**Issue by Xxf9126** [naver/pinpoint#6777]
I added a thread pool to the filter for requesting downstream projects，
But I cannot trace the request，Can this plugin solve my problem and How to use it ? thanks !!!

**Comment by jaehong-kim** [comment]
@Xxf9126 

* What version of pinpoint are you using?
* Describe your problem - Please tell me more.

**Comment by Xxf9126** [comment]
> @Xxf9126
> 
> * What version of pinpoint are you using?
> * Describe your problem - Please tell me more.

The version is 2.0.2

![image](https://user-images.githubusercontent.com/47099845/81654308-10590300-9468-11ea-98ef-9b7423993b90.png)

![image](https://user-images.githubusercontent.com/47099845/81654456-2797f080-9468-11ea-938b-bf168cbb7057.png)

the ServerMap cannot show call downstream project

**Comment by jaehong-kim** [comment]
@Xxf9126 
Made README in Thread Plugin.
https://github.com/naver/pinpoint/blob/master/plugins/thread/README.md

**Comment by Xxf9126** [comment]
> @Xxf9126
> Made README in Thread Plugin.
> https://github.com/naver/pinpoint/blob/master/plugins/thread/README.md

Sorry, it doesn't work，I still can't see the downstream project call。

![image](https://user-images.githubusercontent.com/47099845/82010314-54d0e280-96a4-11ea-812f-36a9197b4ecb.png)

![image](https://user-images.githubusercontent.com/47099845/82010352-70d48400-96a4-11ea-925c-80609c5a113f.png)

![image](https://user-images.githubusercontent.com/47099845/82010440-aed1a800-96a4-11ea-94c6-caf70d320370.png)

**Comment by jaehong-kim** [comment]
@Xxf9126 
Use only the package name.
Please try again.
~~~
profiler.thread.match.package=com.hc.threadpool.core.bean
~~~

**Comment by Xxf9126** [comment]
> @Xxf9126
> Use only the package name.
> Please try again.
> 
> ```
> profiler.thread.match.package=com.hc.threadpool.core.bean
> ```


Thank you very much for your answer, it solved my problem .Thanks ！！！
