### ISSUE TITLE
CompletableFuture worked not as expected in version 2.0.2  ?

### ISSUE THREAD

**Issue by feixueck** [naver/pinpoint#6778]
i test pinpoint v2.0.2  ,this version has the `CompletableFuture` plugin. so i make a test vs the ThreadPlugin, but seems completafuture dose not work as well, the trace graph of completable not fold up ,and not has "Asynchronous Invocation" tag like the thread plugin .is it has bug?
![image](https://user-images.githubusercontent.com/7973084/81497781-432dba80-92f3-11ea-9a59-edd2efd2f657.png)

**Comment by jaehong-kim** [comment]
@feixueck 
* CompletableFuture.complete(Object object) seems to have been executed in the main thread.
* CompletableFuture constructors should not be tracked.
  * Have you modified something?

**Comment by feixueck** [comment]
@jaehong-kim 
 * yes ,i add the constructors to the CompletableFuture just like the "thread" module 
* i want to known ,is this plugin not completed yet? 
* (and i add the supplyAsync interceptor,like below)
![image](https://user-images.githubusercontent.com/7973084/81643133-899c2a00-9457-11ea-8d9b-ecd3d54f4ab5.png)

**Comment by jaehong-kim** [comment]
@feixueck 
Good job.
When completed, please PR.

**Comment by yjqg6666** [comment]
@feixueck Any update for this one.

**Comment by dinesh4747** [comment]
@feixueck  - Any update on this completableFuture change - It would be really great if you could raise the PR

**Comment by feixueck** [comment]
i will commit when completed .

**Comment by dinesh4747** [comment]
@feixueck  - Any specific config change required to enable completableFuture plugin - Since I have been trying this 2.0.3 version and I couldn't trace any CF classes and Async invocation call sequence at all. Any insights on this @jaehong-kim @yjqg6666

**Comment by ZPerling** [comment]
> i will commit when completed .

any update for this commit? thanks
