### ISSUE TITLE
The CallStack is limited to the controller method only

### ISSUE THREAD

**Issue by DebarghoC** [naver/pinpoint#6780]
For a simple service call, the callstack is limited to the controller only.

**Comment by koo-taejin** [comment]
hi @DebarghoC 

If your application does not use library that Pinpoint plugin supports in controller, Pinpoint does not track down it.
If you want to track down it, Please consider using `profiler.include` setting.

thanks :)

**Comment by DebarghoC** [comment]
@koo-taejin  Thanks for the info. It is a Spring boot application and the controller has references to service and helper classes. I suppose that is included.
Also if you could point me to some doc for using profiler.include that would be helpful

**Comment by koo-taejin** [comment]
@DebarghoC 
We do not have any other documentations for this setting, except for the description in pinpoint.config.
Probably, this comment(https://github.com/naver/pinpoint/issues/6352#issuecomment-570488220) can help you.
