### ISSUE TITLE
Rejected count 

### ISSUE THREAD

**Issue by VidushaZ** [naver/pinpoint#6788]
Hi Pinpoint team,

If I lose any transaction will it be taking as a rejected one in collector log or Is there any threshold to show it in logs? My problem is here I can see some spaces between transactions but I don't see any rejected count value in collector though. Is it normal or am I losing transactions here?

![image](https://user-images.githubusercontent.com/34154568/81885230-891aa500-95b7-11ea-8d0a-be51f57b6ddf.png)

Regards.

**Comment by koo-taejin** [comment]
hi @VidushaZ 

I don't understand exactly what any transaction are lost.

The collector receives parts of the transaction, and the collector cannot see if there is a problem with the received message.

I have not seen such a selective tracking at Pinpoint yet like your space.
I think it would be a good idea to check whether the response was like an actual scatter chart image using the access log.

thanks :)

**Comment by VidushaZ** [comment]
@koo-taejin  Hi Thanx for your reply. Usually this happens when zookeeper stopped responding and if the collector cannot handle huge load etc. Since there are no logs named Rejected counts I assume there is nothing to be worry here. I will look in to check actual scatter chart image using the access log. I am closing this and thanx again.
