### ISSUE TITLE
FilterWizard for ApplicationNode

### ISSUE THREAD

**Issue by emeroad** [naver/pinpoint#6790]
https://github.com/naver/pinpoint/pull/6769 Add FilterWizard to the application node

![image](https://user-images.githubusercontent.com/7564547/81896482-a8cdbf80-95ef-11ea-8840-8dfb2ee9d8d3.png)

@yjqg6666
Thank you for your contribution

**Comment by yjqg6666** [comment]
@emeroad This PR #6768  is related to filtering, you may check for merge.
