### ISSUE TITLE
How can I override pinpoint collector ip address with JVM parameters?

### ISSUE THREAD

**Issue by cagri387** [naver/pinpoint#6796]
In pinpoint agent 1.7.3 it was possible to override collector ip address with this parameter:
`-Dpinpoint.profiler.collector.ip=xx.xx.xx.xx`

After I upgraded pinpoint and pinpoint agent version to 2.0.1. I expected that same behaviour can still be applied, and tried to change collector addresses  by adding same line to environment variables but it didn't work.

Is it still possible to change collector ip address via JVM parameters in 2.0.1 version?

P.S: I know I can use a custom profile but I just want to change collector.ip address without changing or adding any file.

**Comment by emeroad** [comment]
https://github.com/naver/pinpoint/issues/6760
Please refer to this issue.

**Comment by cagri387** [comment]
So this feature will be available in the next releases then. thx
