### ISSUE TITLE
JVM time increased after pinpoint agent

### ISSUE THREAD

**Issue by vikasmsg** [naver/pinpoint#6797]
Hi Team,

We are testing Pinpoint apm related changes i
we observe a significant increase in time taken to load the application.

Before PinPoint: (JVM running for 32.047)
level:INFO loggerFqcn:org.apache.commons.logging.LogAdapter$Log4jLog threadId:1 @timestamp:May 14th 2020, 13:12:48.084 source.class:org.springframework.boot.StartupInfoLogger source.file:StartupInfoLogger.java source.line:61 source.method:logStarted message:Started XmlApplication in 22.802 seconds (JVM running for 32.047) threadPriority:5 tag.logtype:application tag.env:mwstaging tag.service_name:cbs-xml log.file.path:/data/log/cbs-xml/mwstaging_cbs-deployment-85bc76b7d8-gmmn2-error-info-cbs-xml_application.log thread:main instant.epochSecond:1,589,442,166 instant.nanoOfSecond:304,000,000 loggerName:com.gateway.xml.XmlApplication fields.hostname:workernode-k8s-v1-10024180 @version:1 endOfBatch:false _id:b09AE3IBmeT0RB3Ox3jI _type:doc _index:mwstaging_cbs-gateway-xml_application-2020.05.14 _score: -

http://jenkins.paytmpb.io/job/CBS-Gateway/job/cbs-gateway-pipeline/job/staging_profile/13/consoleFull

After PinPoint changes: (JVM running for 63.131)
level:INFO loggerFqcn:org.apache.commons.logging.LogAdapter$Log4jLog threadId:1 @timestamp:May 14th 2020, 15:22:58.974 source.class:org.springframework.boot.StartupInfoLogger source.file:StartupInfoLogger.java source.line:61 source.method:logStarted message:Started XmlApplication in 39.299 seconds (JVM running for 63.131) threadPriority:5 tag.logtype:application tag.env:mwstaging tag.service_name:cbs-xml log.file.path:/data/log/cbs-xml/mwstaging_cbs-deployment-599f8f976d-597ch-error-info-cbs-xml_application.log thread:main

Can you please provide us a solution

**Comment by emeroad** [comment]
Check the agent log level

**Comment by vikasmsg** [comment]
Agent log level is INFO.

**Comment by Ashukla81992** [comment]
@emeroad @jaehong-kim can you please guide us in this issue.

**Comment by emeroad** [comment]
If your code base is too large, or if you track too many classes, Start time may be slow.
Reduce the scope of `spring-beans` & `user defined classes` option.
