### ISSUE TITLE
Message not print when exception occurs

### ISSUE THREAD

**Issue by vikasmsg** [naver/pinpoint#6804]
![Screenshot 2020-05-19 at 8 31 34 PM](https://user-images.githubusercontent.com/37859740/82342936-d52e7500-9a0f-11ea-8715-67565f651b0e.png)

We are not getting error message of exceptions. Can you please help 

My code screenshot
![image](https://user-images.githubusercontent.com/37859740/82343119-11fa6c00-9a10-11ea-9089-83d59e50d0fd.png)

**Comment by jaehong-kim** [comment]
@vikasmsg 
Please check the configuration file.
~~~
# HTTP status code with request failure.
# 1xx, 2xx, 3xx, 4xx, 5xx, 100, 101, 200, 201, ... 501, 502, 503, 504, 505
# e.g. profiler.http.status.code.errors=5xx, 401, 403
profiler.http.status.code.errors=5xx
~~~

**Comment by vikasmsg** [comment]
Hi @jaehong-kim i have added 400 code in profiler.http.status.code.errors & its working perfectly fine. But the problem is that the request is failed if 400 occurs but it doesn't print any log error message why this 400 occurs.

**Comment by vikasmsg** [comment]
@RoySRose @emeroad Can you please help here ?
