### ISSUE TITLE
Pinpoint dashboard for webflux service not displaying springboot downstream service 

### ISSUE THREAD

**Issue by Ashukla81992** [naver/pinpoint#6807]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
master/v1.7.3/v1.7.2 etc.

#### Describe your problem**
A clear and concise description of what is not working.

#### What have you done?
Steps you have taken to trigger the problem, for example:
1. Launched '...' with agent
2. Tried tracing '...' (see agent log below)
3. Collector outputs trace log (see collector log below)
4. No trace shows up in the web UI (see web log below)

#### Logs
If applicable, please attach agent/collector/web DEBUG log that includes the part where you have encountered the problem. In case of agents, including the start-up log may be of great help.

#### Additional context
We have incorporated pinpoint java agent in our application (ServiceA)  which is using webflux and webclient for downstream calls, there are two downstream services 1. Spring Webflux application (ServiceB)  2. Spring boot application (ServiceC) , 
both of them have implemented pinpoint.

We are able to see  (ServiceB) in ServiceA's pinpoint dashboard but not able to see ServiceC
we are able to see incoming calls in ServiceC pinpoint transactions (but not able to see ServiceA in the ServiceC's pinpoint dashboard)

**Comment by Ashukla81992** [comment]
2020-05-21 10:49:33 [DEBUG](p.j.i.WriteValueAsStringInterceptor) AFTER com.fasterxml.jackson.databind.ObjectMapper  args:(ClaimsHolder) result:{"iss":"lms-service","Client-Id":"CBS_GATEWAY"}
2020-05-21 10:54:34 [DEBUG](p.j.i.WriteValueAsStringInterceptor) AFTER com.fasterxml.jackson.databind.ObjectMapper  args:(ClaimsHolder) result:{"iss":"lms-service **(ServiceC)** ","Client-Id":"CBS_GATEWAY"}

Logs in pinpoint in cbs-gateway-xml **(ServiceA)**

**Comment by jaehong-kim** [comment]
@Ashukla81992 
Spring WebFlux is supported from version 2.0.2.
Please apply version 2.0.2.

**Comment by Ashukla81992** [comment]
Ya I am working with 2.0.2 only

**Comment by Ashukla81992** [comment]
@jaehong-kim I am using version 2.0.2
and if we are using aync call that is not using the response then we are not able to see the downstream.
but if we are using the response we are able to see the downstream on the dashboard

**Comment by vikasmsg** [comment]
@jaehong-kim Please update on this?

**Comment by vikasmsg** [comment]
@emeroad Please help to resolve this.

**Comment by emeroad** [comment]
There is not enough information to solve the problem.
Please reproducing a bug and provide it.

**Comment by vikasmsg** [comment]
@Ashukla81992 Can you please recreate a bug.

**Comment by Ashukla81992** [comment]
@emeroad 
Below is the code,
in case of Check1 things are working and I am able to see downstream on Pinpoint dashboard
but in case of Check2 it is not working and we are not able to see anything on Pinpoint  dashboard

public Mono<Result> work(final XXml value, String category) throws Exception {
       
            Mono<?> responseDtoMono = xRequestProcessor.processRequest(value);
String o ;
            responseDtoMono = responseDtoMono.map(t -> {
                ResponseDto responseDto = (ResponseDto)t;
                if (Check1.equals(category))) {
                    if (Objects.nonNull(responseDto) && Objects.nonNull(responseDto.getResponse())
                            && StringUtils.isNotEmpty(responseDto.getResponse().getObjectString())) {
                         o = responseDto.getResponse().getObjectString();
         
                } else if (Check2.equals(category)) {
                    if (Objects.nonNull(responseDto) && Objects.nonNull(responseDto.getResponse())
                            && StringUtils.isNotEmpty(responseDto.getResponse().getObjectString())) {
                        o = responseDto.getResponse().getObjectString();
                    }
                }
                return new BasicValidationResult(true,null);
            }).doOnCancel(new Runnable() {
                @Override
                public void run() {
                }
            });
            if (Check2.equals(category)) {
                responseDtoMono.subscribe(rr -> {
                    log.debug("Got response={} async", rr);
                });
                return Mono.just(new BasicValidationResult(true,null));
            }
            return responseDtoMono.map(t -> {
                Result vr = (Result) t;
                return vr;
            });
        } else {
            return Mono.just(new BasicResult(true, null));
        }
}

**Comment by vikasmsg** [comment]
@emeroad Can you please help, As we are blocked due to this issue.

**Comment by emeroad** [comment]
Sorry. It is too difficult to find the problem with the above code.
Please provide a working spring boot sample project

**Comment by Ashukla81992** [comment]
@emeroad This is a case of async call from web Client, where we are doing fire and forget call.

In case, when we are expending result as an when it comes after an async call, things are working fine

**Comment by vikasmsg** [comment]
@emeroad Please help here.
