### ISSUE TITLE
Which table should I drop with Hbase TTL?

### ISSUE THREAD

**Issue by hwoh99** [naver/pinpoint#6813]
Hi.
Pinpoints have accumulated too much historical data.
I want to clear old data using Hbase's TTL feature.
Please tell me the table to be deleted.

**Comment by emeroad** [comment]
Please refer to FAQ : https://naver.github.io/pinpoint/faq.html#hbase-is-taking-up-too-much-space-which-data-should-i-delete-first

**Comment by itnikita** [comment]
404

**Comment by minwoo-jung** [comment]
@itnikita 
https://pinpoint-apm.github.io/pinpoint/2.2.0/faq.html#hbase-is-taking-up-too-much-space-which-data-should-i-delete-first
