### ISSUE TITLE
Issue while creating GCP load balancer service using Thrift  to front end Pinpoint Collector 

### ISSUE THREAD

**Issue by varun-krishna** [naver/pinpoint#6818]
Version - pinpoint-collector-2.0.2 

Present setup - Having Pinpoint collector on Google cloud platform , would want to create a load balancer service in GCP as front end my pinpoint collector . 

But the issue is, i can create either a TCP or UDP based Load balancer but since we are using Thrift and need a combination of both TCP and UDP which GCP Load balancer wont support . 

Any workaround , solution here will be greatly appreciated. @koo-taejin @emeroad

**Comment by emeroad** [comment]
In Pinpoint 2.0.0+, the transport layer was changed to gRPC.

As far as I know, the GCP loadbalancer supports grpc.
If you use 2.0.0+, I think there will be no problem.

**Comment by varun-krishna** [comment]
Yes , agreed . But, contemplating use of Thrift, as facing issues (https://github.com/naver/pinpoint/issues/6816) with grpc.
