### ISSUE TITLE
Pinpoint 1.8 agent is not started normally 

### ISSUE THREAD

**Issue by HanishRamc** [naver/pinpoint#6819]
I’m new to pinpoint APM.
I having issue with attaching pinpoint agent for any running application.

#### What version of pinpoint are you using?
Pinpoint 1.8

#### Describe the issue

I setup pinpoint in multiple VMS and agent with 1.8 trying to attach the collector running in remote.

I tried with tomcat 9  weblogic 12,spring boot application and stand-alone none of them able to attach to collector.

Whereas if I run java -javaagent -version command ,it could attach to collector but for the applications it is not showing any info and attach to collector.
Kindly advise what could be problem.

Regards
Ram

**Comment by yjqg6666** [comment]
@HanishRamc  You may check this out https://github.com/naver/pinpoint/blob/1.8.x/doc/installation.md#installation-2

**Comment by HanishRamc** [comment]
@yjqg6666 , Thanks for the details. I followed the same page, I will try troubleshoot with agent logs and share the status soon.

**Comment by HanishRamc** [comment]
Found the problem. The same server dyntrace oneagent was running and enable so there is a conflict.

After uninstalling oneagent it works fine
