### ISSUE TITLE
what is the mean about http.io 

### ISSUE THREAD

**Issue by zhouhuicong** [naver/pinpoint#6824]
What is the cause ，http.io write 9609ms ？  How to locate this problem 

![微信图片_20200527152337](https://user-images.githubusercontent.com/40559605/82991085-ba6f8800-a02f-11ea-8181-1b74b9f11831.jpg)

**Comment by jaehong-kim** [comment]
@zhouhuicong 
Requests that take longer to respond.
Check CPU or Memory usage.
There may be various causes.
