### ISSUE TITLE
Build version 2.0.3-SNAPSHOT in mac stuck, nothing output

### ISSUE THREAD

**Issue by zlp1992** [naver/pinpoint#6839]
I clone the source and follow http://naver.github.io/pinpoint/installation.html. Then run `./mvnw install -DskipTests=true`，nothing happens and no output. Seems it stucks, anyone know?

**Comment by ga-ram** [comment]
It works fine with me.
It should start like the image below.

<img width="641" alt="Screen Shot 2020-06-01 at 9 43 44 AM" src="https://user-images.githubusercontent.com/3798235/83366836-78a65f00-a3ec-11ea-92c6-4977bbaa8ff7.png">

**Comment by zlp1992** [comment]
it works,  just wait more minutes and logs output
