### ISSUE TITLE
Does PinPoint work with the Java daemon?

### ISSUE THREAD

**Issue by hwoh99** [naver/pinpoint#6841]
Pinpoint has been successfully integrated with the Tomcat service.
This time I want to integrate Pinpoint with a running daemon using the main method of pure Java on the server.
However, the span data does not appear on the graph.
Are there any settings that need to be added more than WAS integration settings?

**Comment by emeroad** [comment]
https://github.com/naver/pinpoint/blob/master/agent/src/main/resources/profiles/release/pinpoint-env.config#L210
`profiler.entrypoint=${java_demon_entrpypoint}`
Would you like to try this option?

**Comment by hwoh99** [comment]
Thank you.
The problem was solved in the way you said.
