### ISSUE TITLE
Jenkins CI support

### ISSUE THREAD

**Issue by HanishRamc** [naver/pinpoint#6842]
Hi,

I'm new to pinpoint and i was trying to find any option to integrate pinpoint apm as part of jenkins integration 
Here our requirement is to take snapshot of pinpoint tracing results against jenkins build and analyze and compare the results .

I am interested to know if there is any plugin or workaround that we can apply
Kindly let me know on these following,
1) Report generation i.e html or pdf format report generation for the trace events
2) Any rest api to perform some action in pinpoint apm
3) any option to export metrics to elasticsearch or other db type.

Thanks
Ram

**Comment by emeroad** [comment]
Pinpoint does not have this function

Contributions are welcome

**Comment by HanishRamc** [comment]
Thanks for confirming.
