### ISSUE TITLE
error during running quickstart script start-collector.sh

### ISSUE THREAD

**Issue by nagpalavi** [naver/pinpoint#6847]
[ERROR] Failed to execute goal on project pinpoint-quickstart-collector: Could not resolve dependencies for project com.navercorp.pinpoint:pinpoint-quickstart-collector:war:2.0.3-SNAPSHOT: Could not find artifact com.navercorp.pinpoint:pinpoint-collector:war:2.0.3-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by erinyees** [comment]
Did you install **All Java version from 6 to 9** ? I got this message when I only use Java 8.

**Comment by waterlove88** [comment]
[ERROR] Failed to execute goal on project pinpoint-quickstart-collector: Could not resolve dependencies for project com.navercorp.pinpoint:pinpoint-quickstart-collector:war:2.1.0-SNAPSHOT: Could not find artifact com.navercorp.pinpoint:pinpoint-collector:war:2.1.0-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

------------------------------------------------------------------------------------------------------------

./mvnw install -DskipTests=true -> build success

./quickstart/bin/start-collector.sh -> build failure

------------------------------------------------------------------------------------------------------------

my environment setting

OS : OS X(macOS Catalina 10.15.6)

JAVA : ~/.bash_profile
export JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
export PATH=${PATH}:$JAVA_HOME

export JAVA_6_HOME=/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
export PATH=${PATH}:$JAVA_6_HOME

export JAVA_7_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home
export PATH=${PATH}:$JAVA_7_HOME

export JAVA_8_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
export PATH=${PATH}:$JAVA_8_HOME

export JAVA_9_HOME=/Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home
export PATH=${PATH}:$JAVA_9_HOME

**Comment by emeroad** [comment]
https://github.com/naver/pinpoint/issues/7022 Change Collector to Spring-boot
https://github.com/naver/pinpoint/issues/7034 Change Web to Spring-boot

In 2.1.0, web and collector are being converted to spring-boot. 
So, the quick start does not work.

Can you help me fix the quick start?
Contributions are always welcome.

**Comment by waterlove88** [comment]
change quickstart.version 2.1.0-SNAPSHOT to 1.8.5-SNAPSHOT

The same problem occurs.

[ERROR] Failed to execute goal on project pinpoint-quickstart-collector: Could not resolve dependencies for project com.navercorp.pinpoint:pinpoint-quickstart-collector:war:1.8.5-SNAPSHOT: Could not find artifact com.navercorp.pinpoint:pinpoint-collector:war:1.8.5-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by koo-taejin** [comment]
hi @waterlove88 

Quickstart could start after entire build of project.
You can get the guide via https://github.com/naver/pinpoint/blob/1.8.5/quickstart/README.md.

Please check this part again.

thanks :)

**Comment by waterlove88** [comment]
@emeroad @koo-taejin 

Thank you for answer.

I solved it using docker.

However, there is an issue that the call-tree cannot be seen when using the peaksnail/pinpoint-node-agent.

Thank you.
