### ISSUE TITLE
how to use flink components

### ISSUE THREAD

**Issue by ccdxwh** [naver/pinpoint#6855]
my env desc：
pinpoint version ：2.0.2
deploy model：
host：A         collctor1：9994   hbase1  flink1
host：B         collctor2 ：9994  hbase2  flink2
host：C         collctor3 ：9994  hbase3  flink3

we have a nginx【19994，19995，19996：which will stream  proxy to collector 9994，9995，9996】

but  when i use the flink....jar[version:2.0.2]
it open failed  duiring check  the filnk health,which will cause the alarm can't execut.
so  we  want to know ,how to use flink componets  in pinpoint:2.0.2
can you give me some guide
thanks a lot

![image](https://user-images.githubusercontent.com/19932891/83516010-e182f980-a508-11ea-9d2c-6ad5f2b42645.png)

**Comment by ccdxwh** [comment]
i have give up

**Comment by minwoo-jung** [comment]
Hi @ccdxwh
please ref : https://github.com/naver/pinpoint/blob/master/doc/application-inspector.md#4-monitoring-streaming-jobs
