### ISSUE TITLE
Database top  queries view might be interesting

### ISSUE THREAD

**Issue by HanishRamc** [naver/pinpoint#6857]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

Currently in pinpoint web UI, call tree view has methods and list of SQL queries were executed as part a span . To quickly understand top queries I noticed there is no view.
Manually I need to go through individual span to understand queries performance.

It would be great if there is a view for database top queries and it's stats.

Kindly advise if there is any and if no any plans to implement in near future.

Regards
Ramc

**Comment by ofauchon** [comment]
Hi. 

I have the same difficulties analyzing Pinpoint datas.
It takes a long time and it's not efficient. 
 
Top Queries views  would be usefull. 

But an API and UI with SQL-like filters on traces/span would be awesome.

Examples what I would like to do from a "Explorer" view: 

- select count(entry_url), entry_url from trace where start_time < 10m and execution_time >10s  group by entry_url; 
- select from trace where agent_id like "webserver%" and execution_time>2s
- select count(traces), url order by execution_time"
- select from span where type=sql and sql_query like "%update%" order by time LIMIT 10

I hope there are plans for an exploring / querying feature. 

Olivier

**Comment by HanishRamc** [comment]
Hi ,  just a quick question , If there is no plan to implement as part of PINPOINT roadmap I would like to spend time to implement this feature. , I havent tried to look further on implementation so someone guide me which are classes  to be modified to have top SQL queries count for global view and trace level SQL queries table. 

Regards
Ramc
