### ISSUE TITLE
the agent Inspector just show ‘JVM/System CPU Usage’，other items  just spin，the version is 2.0.2

### ISSUE THREAD

**Issue by Lasthuman911** [naver/pinpoint#6859]
other items just spin，i open the chrom Network view ，it shows 11‘s errors just like ’t.slice(...).map(...).flat is not a function‘
pinpoint version:2.0.2
hbase version:1.2.12
agent version:2.0.2

**Comment by binDongKim** [comment]
Would you mind showing me the data displayed in the chrome network tab?

**Comment by Lasthuman911** [comment]
thanks,i upgrade chrome version to 88.3.xxx to sloved this problem，the old version is
 63.xxxx

**Comment by binDongKim** [comment]
Glad to hear that. Since we support only modern browsers, that may have caused the issue.
