### ISSUE TITLE
After restarting the application, the JVM information is lost:

### ISSUE THREAD

**Issue by chenbaochao** [naver/pinpoint#6867]
After restarting the application, the JVM information is lost: 
![image](https://user-images.githubusercontent.com/23637914/83603988-f1054f80-a5a7-11ea-92ae-3101091442fc.png)

![image](https://user-images.githubusercontent.com/23637914/83604024-037f8900-a5a8-11ea-8168-ba20a201f08c.png)

pinpoint version:1.7.3

**Comment by chenbaochao** [comment]
help me

**Comment by minwoo-jung** [comment]
you need to see log of pinpoint agent or pinpoint collector.
