### ISSUE TITLE
I cat not get the mule data from pinpoint 2.0.2

### ISSUE THREAD

**Issue by willinghuang** [naver/pinpoint#6879]
I have a problem.My environmental information is：
**JDK:** java version "1.8.0_171"
**Middleware :** mule-standalone-3.7.0
**Boot file configuration information：**
 add pinpoint config
wrapper.java.additional.20=-javaagent:/work/pinpointagent/pinpoint-bootstrap-2.0.2.jar
wrapper.java.additional.21=-Dpinpoint.applicationName=gateway
wrapper.java.additional.22=-Dpinpoint.agentId=10.8.1.9
**Problem:**
I can see ApplicationName = gateway on the console of pinpoint。At the same time, I can also collect server information of 10.8.1.9, such as VM/System CPU Usage, Non Heap Usage, Heap Usage, etc。However, I just can't collect the request data and call link information reported by the agent。Response Time Scatter Chart have nothing。

I hope someone can help me ,Thanks very much!

**Comment by emeroad** [comment]
Mule are not currently supported.
The plugin is needed to support this.
See the Plugin Guide.
- http://naver.github.io/pinpoint/2.0.2/plugindevguide.html

**Comment by willinghuang** [comment]
> Mule are not currently supported.
> The plugin is needed to support this.
> See the Plugin Guide.
> 
> * http://naver.github.io/pinpoint/2.0.2/plugindevguide.html
Thanks very much,I hope that It can support mule soon.

**Comment by Rnic** [comment]
@willinghuang  hi, i also had the same problem when i used pinpoint with mule-standalone, can u got any solution now?
