### ISSUE TITLE
Problem installing pinpoint 2.0.2

### ISSUE THREAD

**Issue by ofauchon** [naver/pinpoint#6880]
#### Prerequisites
I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?

Pinpoint 2.0.2
apache-tomcat-8.5.43
hbase-1.3.5 (standalone)
openjdk version "1.8.0_191"

#### Describe your problem**

Pinpoint web + collector webapplication don't start. 
Error reported by tomcat in catalina*.log

#### What have you done?

(Upgrade from a previous working pinpoint 1.8.4 server)

* Delete all datas from hbase datadir 
* Delete all datas from hbase zookeeper datadir 

cd $TOMCAT
./bin/shutdown.sh
rm ../logs/*
rm -fr tomcat/webapps/*
cp pinpoint-web-2.0.2.war  $TOMCAT/webapps/ROOT.war
cp pinpoint-collector-2.0.2.war $TOMCAT/webapps/
echo "export JAVA_OPTS="-Dpinpoint.zookeeper.address=127.0.0.1"' >> setenv.sh
./bin/startup.sh

#### Screenshots
N/A

#### Logs
04-Jun-2020 13:47:56.882 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 346 ms
04-Jun-2020 13:47:56.900 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
04-Jun-2020 13:47:56.900 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.43
04-Jun-2020 13:47:56.916 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/opt/pinpoint/apach
e-tomcat-8.5.43/webapps/pinpoint-collector-2.0.2.war]
04-Jun-2020 13:48:01.475 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TL
Ds. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning
 can improve startup time and JSP compilation time.
04-Jun-2020 13:48:07.543 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/opt/pinpoint/a
pache-tomcat-8.5.43/webapps/pinpoint-collector-2.0.2.war] has finished in [10,626] ms
04-Jun-2020 13:48:07.544 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/opt/pinpoint/apach
e-tomcat-8.5.43/webapps/ROOT.war]
04-Jun-2020 13:48:12.279 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
04-Jun-2020 13:48:16.441 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
04-Jun-2020 13:48:16.441 **SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors**
04-Jun-2020 13:48:16.570 WARNING [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [localhost-startStop-1-SendThread(127.0.0.1:2181)] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ClientCnxnSocketNIO.cleanup(ClientCnxnSocketNIO.java:230)
 org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ClientCnxn$SendThread.cleanup(ClientCnxn.java:1185)
 org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1122)
04-Jun-2020 13:48:16.572 WARNING [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [localhost-startStop-1-SendThread(localhost.localdomain:2181)] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 org.apache.zookeeper.ClientCnxnSocketNIO.cleanup(ClientCnxnSocketNIO.java:230)
 org.apache.zookeeper.ClientCnxn$SendThread.cleanup(ClientCnxn.java:1246)
 org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1182)
04-Jun-2020 13:48:16.579 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/opt/pinpoint/apache-tomcat-8.5.43/webapps/ROOT.war] has finished in [9,035] ms
04-Jun-2020 13:48:16.580 INFO [localhost-startStop-1-SendThread(localhost.localdomain:2181)] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [org.apache.zookeeper.server.ZooTrace]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.apache.zookeeper.server.ZooTrace]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
                at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1380)
                at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1368)
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1220)
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1182)
                at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1188)
0404-Jun-2020 13:48:16.589 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-9090"]
04-Jun-2020 13:48:16.631 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
04-Jun-2020 13:48:16.641 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 19759 ms
04-Jun-2020 13:48:16.643 INFO [localhost-startStop-1-SendThread(127.0.0.1:2181)] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [org.apache.hadoop.hbase.shaded.org.apache.zookeeper.server.ZooTrace]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.apache.hadoop.hbase.shaded.org.apache.zookeeper.server.ZooTrace]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
                at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1380)
                at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1368)
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1220)
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1182)
                at org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1128)

**Comment by ofauchon** [comment]
Thanks, I'll test with increasing log level with logging.properties.

Do I need a standalone Zookeeper Server, or HBase provides Zookeeper services ? 
In this case, is export JAVA_OPTS="-Dpinpoint.zookeeper.address=127.0.0.1" the correct 
setting ? 

Thanks

**Comment by santhosh-git** [comment]
I am also facing the same issue, Please suggest

**Comment by ofauchon** [comment]
<context-param>
       <param-name>webAppRootKey</param-name>
       <param-value>SomeUniqueValue</param-value>
</context-param>

**Comment by santhosh-git** [comment]
Your solution worked @ofauchon
