### ISSUE TITLE
TraceV2.SpanBo.parentApplicationId & parentApplicationServiceType not saved to HBase

### ISSUE THREAD

**Issue by yjqg6666** [naver/pinpoint#6899]
#### What version of pinpoint are you using?
master/2.0.2

#### What did you do to trigger the bug?
In the web module, the SpanBo retrived from HBase via SpanService , the parentApplicationId property of SpanBo is always null and the parentApplicationServiceType property of SpanBo is always 0. 

https://github.com/naver/pinpoint/blob/47d0149d61b1fc676094ecf4ab479b49408b54fa/web/src/main/java/com/navercorp/pinpoint/web/service/SpanServiceImpl.java#L102

https://github.com/naver/pinpoint/blob/47d0149d61b1fc676094ecf4ab479b49408b54fa/commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/SpanBo.java#L42-L43

From the collector side, the SpanBo is encoded into ByteBuffer without parentApplicationId and parentApplicationServiceType included.

https://github.com/naver/pinpoint/blob/e271749912e33665d8c1d2b58050c3788b2390d9/commons-server/src/main/java/com/navercorp/pinpoint/common/server/bo/serializer/trace/v2/SpanEncoderV0.java#L130-L206

#### Expected behavior
The parentApplicationId and parentApplicationServiceType of SpanBo should be set and now can only be set back through parentSpanId. Are the two properties left out intentionally for space and performance? Could it be a bug or feature?

**Comment by emeroad** [comment]
This behavior is by feature.

**Comment by yjqg6666** [comment]
Two more questions, any difference between SpanBo and SpanChunkBo? com.navercorp.pinpoint.collector.dao.hbase.HbaseTraceDaoV2 have two insert methods, insert and insertSpanChunk.  Is insertSpanChunk used to append data to existing transaction trace data?

**Comment by emeroad** [comment]
SpanChunk is a sub-slice of Span and is a container for multiple spanevents.

SpanChunk is used to chunk a large amount of spanevnt.

-------

eg) Send 1000 spanEvents
pan 
  |-spanEvent : 1000 

--------------

Span * 1
|- spanEvent : 100
SpanChunk   * 9
|- spanEvent :  100

~~~

**Comment by yjqg6666** [comment]
Got it and thanks a lot for the help.
