### ISSUE TITLE
Pinpoint Web Application not initialized due to pinpoint apm hbase ApplicationIndex Table not found

### ISSUE THREAD

**Issue by srikanthtummala** [naver/pinpoint#6900]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

_______

#### What version of pinpoint are you using?
v2.0.2

_______

#### **Problem -1:**
========
1. I want to store **hbase data** into host VM instead of Docker container.
2. To store **hbase data** into VM repository, I mapped docker container   **hbase data**  data repository (**/home/pinpoint/hbase/data**) to host VM repository (**/opt/hbase/data**) in **volumes** section under **pinpoint-hbase** service in  docker-compose.yaml file.
3. When I mapped the volumes between docker container and host, Pinpoint-web application not able to initialize by throwing below excretion.

 _stacktrace=com.navercorp.pinpoint.common.hbase.HbaseSystemException: ApplicationIndex; nested exception is org.apache.hadoop.hbase.TableNotFoundException: ApplicationIndex
        at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.execute(HbaseTemplate2.java:763)
        at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.find(HbaseTemplate2.java:190)
        at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.find(HbaseTemplate2.java:219)
        at com.navercorp.pinpoint.web.dao.hbase.HbaseApplicationIndexDao.selectAllApplicationNames(HbaseApplicationIndexDao.java:74)
        at com.navercorp.pinpoint.web.service.CommonServiceImpl.selectAllApplicationNames(CommonServiceImpl.java:42)
        at com.navercorp.pinpoint.web.controller.MainController.getApplicationGroup(MainController.java:49)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)_
 

4. When I revoke the volume  mappings, Application is back to running state.

#### **Problem -2:**
========
1. All the data in hbase database erased once I we shutdown application using docker compose with default (**/home/pinpoint/hbase**) volume mapping configuration in docker-copose.yml file.
2. I am unable to retrieve the  data once I restarted.
3. Above resulted loss of data and restart Pinpoint Agents once again.

_______

#### **Problem -1:**
========
Steps to reproduce, for example:
1. Open **docker-compose.yml** with your favorite editor in Pinpoint parent/base folder.
2.  Disable/comment **_- /home/pinpoint/hbase_** under **volumes** in **pinpoint-hbase service** and add **- /opt/pinpoint/hbase/data:/home/pinpoint/hbase/data** or  **- /opt/pinpoint/hbase:/home/pinpoint/hbase** instead in docker-compose.yml .
3. Start the Pinpoint application using docker compose (docker-compose up -d).
4. Open Pinpoint application in browser.  You will notice that application startup stuck at **_applicationList.pinpoint_**.
5. Now check the the **pinpoint-web** application logs. (docker logs pinpont-web), to find exception details.

#### **Problem -2:**
========
1. Start the application using docker compose(docker-compose up -d).
2. Connect pinpoint agents to pinpoint server and feed some tracing data.
3. Shutdown whole pinpoint application using docker compose(docker-compose down).
4. Again start the application using docker compose(docker-compose up -d).

Now you see that old data is missing.

_______

#### Expected behavior
When we map hbase  data volumes between docker container and host VM, pinpoint should run without any issues

_______

#### Screenshots
![image](https://user-images.githubusercontent.com/1146579/84257154-34663d80-ab15-11ea-8e70-8ad32fc7ab8e.png)
![image](https://user-images.githubusercontent.com/1146579/84261807-ba39b700-ab1c-11ea-873e-737bf8e994e5.png)

_______

#### Logs
[pinpoint-web.log](https://github.com/naver/pinpoint/files/4757933/pinpoint-web.log)
[pinpoint-hbase.log](https://github.com/naver/pinpoint/files/4757934/pinpoint-hbase.log)

**Comment by RoySRose** [comment]
Hello, @srikanthtummala 

This is something to do with the docker and the containers. 
For issue 1 
You should check if the ports are open for the containers. and also you need to get to know more about how to use them.

For issue 2
It's about storing data when using the database as containers.

Both issues are not about Pinpoint. so I don't think we can help much on this.
By the way. Take a look the docker files for Pinpoint 
http://github.com/naver/pinpoint-docker

This may help you to get on the track.
