### ISSUE TITLE
when some method called exception, pinpoint desnot show more  printstack

### ISSUE THREAD

**Issue by chenglin321** [naver/pinpoint#6902]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
2.0.2

#### Describe the bug
when some method called exception, pinpoint desnot show more  printstack

![3A698839-C0A7-4338-8AD1-5350BF582BC1](https://user-images.githubusercontent.com/3918176/84350326-af9a2300-abeb-11ea-9e4c-7ba83b49daac.png)

The content has less printstack ,but i want more printstack information

nested exception is org.apache.ibatis.exceptions.PersistenceException: ### Error querying database. Cause: java.lang.IllegalArgumentException: Mapped Statements collection does not contain value for s_i18n.selectCountByParams ### Cause: java.lang.Illegal...(357)

**Comment by emeroad** [comment]
Too long strings that are too long are being truncated
Stacktrace will be supported in the future
