### ISSUE TITLE
Why do gap columns always take too long?

### ISSUE THREAD

**Issue by gaoyangk** [naver/pinpoint#6904]
In the process of use, it is found that the irregular Gap column takes too long。
I tried a lot of ways and didn't find a reasonable explanation
I've been bothered for a long time. Have you ever encountered similar  problems?

**Comment by RoySRose** [comment]
Hello, @gaoyangk 

What do you mean by ' irregular Gap column takes too long。'?

**Comment by gaoyangk** [comment]
![微信截图_20200612183600](https://user-images.githubusercontent.com/24651715/84625934-c6f04d80-af16-11ea-9572-3f5efb690d77.png)
Like this

**Comment by RoySRose** [comment]
Here is the explanation for the gap column
You can check what's going on from the start of the previous method up to the entry of this method.

![image](https://user-images.githubusercontent.com/20402016/84626548-39b1f680-af20-11ea-8c6d-152bcb14e413.png)

**Comment by gaoyangk** [comment]
I know what gap column means, but I don't know why it happens
