### ISSUE TITLE
Network ports and protocol between Agent and Collector Pinpoint 2.0.2

### ISSUE THREAD

**Issue by ofauchon** [naver/pinpoint#6905]
Hi. 

I have to deal with firewall security between the Collector and Agents (Pinpoint 2.0.2)

Could you please tell me the complete lists of ports and protocol to be opened between the two 
security zones ? 

Thanks 

Olivier

**Comment by RoySRose** [comment]
Hello @ofauchon 

you can check here for the necessary ports
https://naver.github.io/pinpoint/installation.html#configuration-2
