### ISSUE TITLE
Log button cannot be clicked

### ISSUE THREAD

**Issue by gaofeng36599** [naver/pinpoint#6917]
I change the pinpoint- web.properties The configuration file and Log button have come out, but they can't be clicked. Is there any problem or lack of configuration?
log.enable=true
log.page.url=*****
log.button.name=log

**Comment by emeroad** [comment]
See this link
https://github.com/naver/pinpoint/blob/master/doc/per-request_feature_guide.md

**Comment by gaofeng36599** [comment]
By address: https://github.com/naver/pinpoint/pull/5984/files It has been solved. thank.

Can you explain the function of the following code？
public class AppenderInterceptor implements AroundInterceptor0 {

    private final TraceContext traceContext;

    public AppenderInterceptor(TraceContext traceContext) {
        this.traceContext = traceContext;
    }

    @Override
    public void before(Object target) {
        Trace trace = traceContext.currentTraceObject();

        if (trace != null) {
            SpanRecorder recorder = trace.getSpanRecorder();
            recorder.recordLogging(LoggingInfo.LOGGED);
        }
    }

    @IgnoreMethod
    @Override
    public void after(Object target, Object result, Throwable throwable) {

    }
}

**Comment by minwoo-jung** [comment]
hello @gaofeng36599 
This is an interceptor for recording whether to log by profiling the appender class of the log library.
