### ISSUE TITLE
2.0.2版本连接agent读取配置错误

### ISSUE THREAD

**Issue by 1657486787** [naver/pinpoint#6927]
2.0.2版本连接agent读取配置错误，配置文件已经改为其他ip地址了
profiler.transport.grpc.collector.ip=192.168.1.201
profiler.collector.ip=192.168.1.201，
但是读取到的还是127.0.0.1

**Comment by Lasthuman911** [comment]
是改的profile/release下面的配置文件么？

**Comment by yjqg6666** [comment]
是的  在没有设置 -Dspring.profiles.active={YOUR_PROFILE}的情况下 默认使用release.  请尽量使用英文，机翻一下也好。 http://naver.github.io/pinpoint/2.0.2/installation.html#5-pinpoint-agent
