### ISSUE TITLE
Rename the config file

### ISSUE THREAD

**Issue by emeroad** [naver/pinpoint#6938]
The design of the configuration name policy is not good.
Change the frequently modified file to pinpoint.config.

pinpoint.config -> pinpoint-root.config
pinpoint-env.config -> pinpoint.config

## 2.0.x
```
$PINPOINT_AGENT_HOME 
+- pinpoint.config
+-/profiles
  +-/local
     +- pinpoint-env.config
  +-/release
     +- pinpoint-env.config
```

## 2.1.0+
```
$PINPOINT_AGENT_HOME 
+- pinpoint-root.config
+-/profiles
  +-/local
     +- pinpoint.config
  +-/release
     +- pinpoint.config
```

**Comment by simple0426** [comment]
its a bad idea, for the duplicate item(for example: profiler.transport.grpc.collector.ip),which has effect?
