### ISSUE TITLE
springcloud gateway

### ISSUE THREAD

**Issue by Lasthuman911** [naver/pinpoint#6940]
pinpoint version: 2.0.2.   i user this version,but i found the springcloud gateway page didn't show any request diagram，is this a bug or pinpoint just does't support springcloud gateway?

**Comment by lobsterHe** [comment]
I encountered the same problem, how can I solve the problem of spring-cloud-gateway?

**Comment by jaehong-kim** [comment]
@Lasthuman911 @lobsterHe 
Improvement work is underway.
I would like source code or PR for reproduction.

**Comment by yjqg6666** [comment]
Waiting for the complete support.

**Comment by yjqg6666** [comment]
Could i expect that it would be available in the future release 2.1.0?

**Comment by dinesh4747** [comment]
Also when can we expect 2.1.0 release any tentative timelines @jaehong-kim

**Comment by fushiqinghuan111** [comment]
I still found this problem in version 2.2.2 spring cloud gateway
