### ISSUE TITLE
[Question] support pinpoint web deployment under example.com/pinpoint/

### ISSUE THREAD

**Issue by yjqg6666** [naver/pinpoint#6968]
Version: 2.0.3
Question: If i want to deploy the web part of pinpoint under example.com/pinpoint and make all the request urls prefixed with /pinpoint, how could I make it working?

After some googling on angular, tried to change _"ng build pinpoint --prod"_ to _"ng build pinpoint --prod --base-href /pinpoint/ --deploy-url /pinpoint/"_, to change from _Path: ""_  to _Path:"pinpoint"_ at https://github.com/naver/pinpoint/blob/master/web/src/main/angular/src/app/app.routing.ts#L10. Now the assets and *.pinpoint request URLs are under /pinpoint but all the UI pages are blank or get 404 errors.

The blank page, ex. example.com/pinpoint/ got console error like the following:
![image](https://user-images.githubusercontent.com/1879641/86220376-19d43100-bbb6-11ea-8d76-ab77faac78b5.png)

The URLs ex. example.com/pinpoint/main, example.com/pinpoint/main/app-name-prod@SPRING_BOOT/5m/2020-07-01-15-23-48 get 404 errors.

Question: What else should I do or any other actions should i take instead?

**Comment by emeroad** [comment]
Currently, pinpoint does not support context-path.
Root-context(/) is recommended.

Contributions are always welcome.
