### ISSUE TITLE
Not able to display a correct server mapping

### ISSUE THREAD

**Issue by wilmereca** [naver/pinpoint#6969]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
master/v2.0.3

#### Describe your problem**

PP dashboard it is not displaying the agent mapping

#### What have you done?

1. I launched pinpoint v2.0.3 following https://github.com/naver/pinpoint-docker procedures, so I have all my PP components in docker containers, 
2. Deployed PP agents in my app containers, with a profile pointing to collector's IP address.
3. PP Agents params:

    -javaagent:/mountPath/pinpoint-agent/pinpoint-bootstrap-2.0.3.jar
    -Dpinpoint.agentId=example-api-a
    -Dpinpoint.applicationName=api-a-example -Dpinpoint.container=applicationname
    -Dpinpoint.profiler.profiles.active=customprofile
4. Follow "Separate Logging Per Request guide" (http://naver.github.io/pinpoint/perrequestfeatureguide.html#2-how-to-configure), in order to gather transactions ID in my logs agents. (screenshot)

./profile/customprofile/pinpoint-env.config

###########################################################
# log4j (guide url : https://github.com/naver/pinpoint/blob/master/doc/per-request_feature_guide.md)
###########################################################
profiler.log4j.logging.transactioninfo=true

./profile/customprofile/log4j.xml

<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">
<log4j:configuration xmlns:log4j='http://jakarta.apache.org/log4j/'>

    <appender name="console" class="org.apache.log4j.ConsoleAppender">
        <param name="Threshold" value="WARN"/>
        <layout class="org.apache.log4j.EnhancedPatternLayout">
            
            <param name = "ConversionPattern" value= "%d{yyyy-MM-dd HH:mm:ss} [%-5p](%-30c{1}) [TxId : %X{PtxId} , SpanId : %X{PspanId}] %m%n" />
        </layout>
    </appender>

    <appender name="dailyRollingFile" class="org.apache.log4j.DailyRollingFileAppender">
        <param name="file" value="${pinpoint.log}/${pinpoint.agentId}/pinpoint.log"/>
        <param name="Append" value="true"/>
        <param name="DatePattern" value="'.'yyyy-MM-dd"/>

        <layout class="org.apache.log4j.EnhancedPatternLayout">
            
            <param name = "ConversionPattern" value= "%d{yyyy-MM-dd HH:mm:ss} [%-5p](%-30c{1}) [TxId : %X{PtxId} , SpanId : %X{PspanId}] %m%n" />
        </layout>
    </appender>

    <appender name="rollingFile" class="org.apache.log4j.RollingFileAppender">
        <param name="file" value="${pinpoint.log}/${pinpoint.agentId}-pinpoint.log"/>
        <param name="append" value="true"/>
        <param name="maxFileSize" value="10MB"/>
        <param name="maxBackupIndex" value="20"/>
        <layout class="org.apache.log4j.EnhancedPatternLayout">
            
            <param name = "ConversionPattern" value= "%d{yyyy-MM-dd HH:mm:ss} [%-5p](%-30c{1}) [TxId : %X{PtxId} , SpanId : %X{PspanId}] %m%n" />
        </layout>
    </appender>

    <logger name="com.navercorp.pinpoint" additivity="false">
        <level value="INFO"/>
        <appender-ref ref="console"/>
        <appender-ref ref="rollingFile"/>
    </logger>

    <root>
        <level value="INFO"/>
        <appender-ref ref="console"/>
        <appender-ref ref="rollingFile"/>
    </root>

</log4j:configuration>

**APPLICATION LOGS**

2020-07-01 18:53:52 [http-nio-9012-exec-9] INFO  a.c.i.p.c.RequestResponseInterceptor:46 - Request: {
  "uri" : "https://example.com/api/v1/appname/appname?from=2020-06-01&to=",
  "method" : "GET",
  "headers" : {
    "Accept" : [ "application/json, application/*+json" ],
    "Content-Type" : [ "application/json" ],
    "userId" : [ "XXX" ],
    "clientId" : [ "XXX" ],
    "channelId" : [ "I" ],
    "Content-Length" : [ "0" ],
    "X-B3-TraceId" : [ "xxxxx" ],
    "X-B3-SpanId" : [ "xxxxxx" ],
    "X-B3-ParentSpanId" : [ "xxxxxxxx" ],
    "X-B3-Sampled" : [ "0" ]
  },
  "body" : null
}
2020-07-01 18:53:52 [http-nio-9012-exec-9] INFO  a.c.i.p.c.RequestResponseInterceptor:61 - Response: {
  "statusCode" : 200,
  "statusText" : "OK",
  "headers" : {
    "Content-Type" : [ "application/json" ],
    "Transfer-Encoding" : [ "chunked" ],
    "Date" : [ "Wed, 01 Jul 2020 18:53:52 GMT" ],
    "Set-Cookie" : [ "a75f1c8165aa13c9053f4b18be291ee7=60effd62f33f7e00c62e50bf9d1ce9d9; path=/; HttpOnly; Secure" ],
    "Cache-control" : [ "private" ]
  },
  "body" : [ ],
  "milliseconds" : 32
}

#### Screenshots

This should be showing agent mapping, and all the other's API behind that BFF

![image](https://user-images.githubusercontent.com/49953897/86283740-e85c6500-bbb7-11ea-8d64-0d2504839fac.png)

**Comment by koo-taejin** [comment]
hi @wilmereca 

It is difficult to understand your question accurately.
Could you give us more detailed description to solve it.

Additionally, the option of `-Dpinpoint.container=` supports true/false.
(you posted `-Dpinpoint.container=applicationname`)

thanks :)

**Comment by wilmereca** [comment]
Thanks @koo-taejin, basically the problem is that pinpoint is not able to display or do connections/relations, as you can see in the image bff-profiles does show input connection, but is not able to display it's relation with lower layers, in this case, behind that bff is an API,..

I knew about some related case [https://github.com/naver/pinpoint/issues/4673](url) but I currently running a supported HBASE which is 1.2.6...

**Comment by koo-taejin** [comment]
@wilmereca 
Pinpoint can show library that supported by Pinpoint. 
If the link is via an unsupported lib, it is normal that it does not appear.

I recommend that you check the situation.

thanks :)
