### ISSUE TITLE
Can I use pinpoint to trace HBase itself？

### ISSUE THREAD

**Issue by Joseph295** [naver/pinpoint#6981]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

**Comment by RoySRose** [comment]
@Joseph295 

Yes, [here](https://naver.github.io/pinpoint/2.0.3/main.html#supported-modules) you can see the list that Pinpoint can trace.

**Comment by emeroad** [comment]
Pinpoint does not support hbase cluster monitoring.

Use apache ambari or cloudera manager.

**Comment by Joseph295** [comment]
> Pinpoint does not support hbase cluster monitoring.
> 
> Use apache ambari or cloudera manager.

What about trace?

**Comment by Joseph295** [comment]
> @Joseph295
> 
> Yes, [here](https://naver.github.io/pinpoint/2.0.3/main.html#supported-modules) you can see the list that Pinpoint can trace.

Thanks, but I wanna trace hbase server
