### ISSUE TITLE
The topology diagram of pinpoint 2.0.2 cannot show related services

### ISSUE THREAD

**Issue by bingfengxiyang** [naver/pinpoint#6984]
Environment version: pinpoint, 2.0.2 hbase:1.6.0 ,java.1.8.5

Problem: the pinpoint topology map only shows a selected service, while the associated services such as mysql, redis and other services can not be displayed. A lot of information can not be solved by searching, and the ports dup9995 and 9996 are connected. Please solve your doubts. Thank you very much
![86729983-a2444d00-c060-11ea-9172-7e2322c18b51](https://user-images.githubusercontent.com/15306157/86863192-4b408580-c0fd-11ea-974f-9d968df5b872.png)
![86730076-bbe59480-c060-11ea-8507-4da9ccc7e544](https://user-images.githubusercontent.com/15306157/86863196-4f6ca300-c0fd-11ea-978b-a058607aec23.png)

The phenomenon is shown in the figure above

**Comment by bingfengxiyang** [comment]
![image](https://user-images.githubusercontent.com/15306157/86864925-a1fb8e80-c100-11ea-88e2-06057cb94161.png)
Response Summary  and  Load   have  no data ，please ，thanks

**Comment by bingfengxiyang** [comment]
The problem has been resolved because of the HBase version

**Comment by XDongo** [comment]
which version will go wrong？
