### ISSUE TITLE
Pinpoint agent load issue | Spring Boot - MSNext micro service

### ISSUE THREAD

**Issue by NishantRajak** [naver/pinpoint#6993]
#### What version of pinpoint are you using?
Pinpoint - 2.0.2

#### Describe your problem**
I am trying to onboard a spring boot micro service with pinpoint and getting below error message:

2020-07-08 12:20:09 [INFO   ](com.navercorp.pinpoint.bootstrap.PinpointBootStrap) pinpoint agentArgs:null |  
-- | --
  | 2020-07-08 12:20:09 [INFO   ](com.navercorp.pinpoint.bootstrap.PinpointBootStrap)   PinpointBootStrap.ClassLoader:null
  | 2020-07-08 12:20:09 [INFO   ](com.navercorp.pinpoint.bootstrap.PinpointBootStrap)   ContextClassLoader:sun.misc.Launcher$AppClassLoader@18b4aac2
  | 2020-07-08 12:20:09 [INFO   ](com.navercorp.pinpoint.bootstrap.agentdir.JavaAgentPathResolver$ClassAgentPathFinder)   agentPath:/opt/pinpoint/pinpoint-agent-2.0.2/pinpoint-bootstrap-2.0.2.jar
  | 2020-07-08 12:20:09 [INFO ](com.navercorp.pinpoint.bootstrap.PinpointBootStrap)   JavaAgentPath:/opt/pinpoint/pinpoint-agent-2.0.2/pinpoint-bootstrap-2.0.2.jar
  | 2020-07-08 12:20:09 [INFO   ](com.navercorp.pinpoint.bootstrap.agentdir.AgentDirBaseClassPathResolver)   Agent original-path:/opt/pinpoint/pinpoint-agent-2.0.2
  | 2020-07-08 12:20:09 [INFO   ](com.navercorp.pinpoint.bootstrap.agentdir.AgentDirBaseClassPathResolver)   Agent canonical-path:/opt/pinpoint/pinpoint-agent-2.0.2
  | 2020-07-08 12:20:09 [INFO   ](com.navercorp.pinpoint.bootstrap.agentdir.BootDir) boot is empty
  | 2020-07-08 12:20:09 [WARN   ](com.navercorp.pinpoint.bootstrap.PinpointBootStrap) AgentDir resolve fail   Caused by:files
  | java.lang.NullPointerException: files
  | at   com.navercorp.pinpoint.bootstrap.agentdir.Assert.requireNonNull(Assert.java:28)
  | at com.navercorp.pinpoint.bootstrap.agentdir.FileUtils.toURLs(FileUtils.java:79)
  | at   com.navercorp.pinpoint.bootstrap.agentdir.AgentDirBaseClassPathResolver.toURLs(AgentDirBaseClassPathResolver.java:172)
  | at com.navercorp.pinpoint.bootstrap.agentdir.AgentDirBaseClassPathResolver.resolveLib(AgentDirBaseClassPathResolver.java:157)
  | at   com.navercorp.pinpoint.bootstrap.agentdir.AgentDirBaseClassPathResolver.resolve(AgentDirBaseClassPathResolver.java:84)
  | at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.resolveAgentDir(PinpointBootStrap.java:100)
  | at   com.navercorp.pinpoint.bootstrap.PinpointBootStrap.premain(PinpointBootStrap.java:69)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at   sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at   sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
  | at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
  |  
  | 2020-07-08 12:20:09 [WARN   ](com.navercorp.pinpoint.bootstrap.PinpointBootStrap) Agent Directory Verify   fail. skipping agent loading.
  | *****************************************************************************
  | * Pinpoint Agent load failure
  | *****************************************************************************

**Comment by koo-taejin** [comment]
hi @NishantRajak 

The Pinpoint Agent directory has the following structure.
```
HOME 
	/boot
	/lib
	/plugin
	/logs
        /profiles.
```
Log message that you posted shows message `boot is empty`.
I recommend that you check if jar files are included in boot directory normally.

thanks :)

**Comment by NishantRajak** [comment]
Hi @koo-taejin ,
Thanks for reply. we have boot directory and jar files present.

Do we need to pass agent directory path explicitly?
Or is this something related to permission or access issue ?
Please advise.

Thanks & Regards

**Comment by koo-taejin** [comment]
@NishantRajak 

If you specify the location of bootstrap.jar as follows, the paths you see in the log are created based on it.
```
-javaagent:${AGENT_PATH}/pinpoint-bootstrap.jar
```

I think that it is not problem if files have read access permission.

If it can be reproduced, there will be no difficulty in solving it. I don't know how to reproduce it.

If you have any doubts, please let me know and it would be very helpful.

thanks :)

**Comment by NishantRajak** [comment]
Hi @koo-taejin ,
Thanks for your support and kind advice. We found the issue, it was due to corrupt file system. We moved the agent directory to other location and we are able to boot now. Thank you so much.

Regards,
Nishant

**Comment by koo-taejin** [comment]
@NishantRajak 
I am happy to hear that.

Thanks :)
