### ISSUE TITLE
Application Does Not Appear in Web UI

### ISSUE THREAD

**Issue by richie-b** [naver/pinpoint#6997]
- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
2.0.2

#### Describe your problem**
I have started the quickstart collector, web UI and test-app running on Windows Server 2016.
I am however unable to view any transactions in the Web UI, the Test Application was never discovered in the application list.
I get the same result when I use my own collector, web UI and agents.

I also checked the logs in quickstart/logs, no errors were found.
How can I troubleshoot this?

#### What have you done?
Steps you have taken to trigger the problem, for example:
Tried looking for errors in quickstart/logs

#### Logs
If applicable, please attach agent/collector/web DEBUG log that includes the part where you have encountered the problem. In case of agents, including the start-up log may be of great help.

#### Additional context
Add any other context about the problem here, such as affected library for agents, how your collector/web/hbase is set up if applicable.

**Comment by koo-taejin** [comment]
hi @richie-b 

I understood that Pinpoint shows application, but doesn't show transaction.
If it is right, You can see transaction if testapp receives request.

Please check it again, after you access testapp(http://{address}:28081)

thanks :)

**Comment by richie-b** [comment]
Hi @koo-taejin  I have already tried sending many transactions from the test app on localhost:28081 but nothing shows on the web GUI.

The  application does not appear in the list either. I have tried refreshing several times after creating transactions.

**Comment by koo-taejin** [comment]
@richie-b 

Please post collector's log.
If I found out what I have to check, then I am going to let you know it.

**Comment by richie-b** [comment]
[quickstart.collector.log](https://github.com/naver/pinpoint/files/4903007/quickstart.collector.log)
[quickstart.testapp.log](https://github.com/naver/pinpoint/files/4903008/quickstart.testapp.log)
[quickstart.web.log](https://github.com/naver/pinpoint/files/4903009/quickstart.web.log)

**Comment by koo-taejin** [comment]
@richie-b 

If you set environment variable like this (`SPRING_PROFILES_ACTIVE=local`), then you can set log level to low.
After this, Please retry Quickstart and post log again.

**Comment by richie-b** [comment]
@koo-taejin I created the SPRING_PROFILES_ACTIVE environment variable however I was not sure what to edit in the log4j file (quickstart\collector\target\war\work\com.navercorp.pinpoint\pinpoint-collector\WEB-INF\classes\profiles\release\log4j.xml)

I attached the new log
[quickstart.collector.log](https://github.com/naver/pinpoint/files/4922149/quickstart.collector.log)

**Comment by richie-b** [comment]
@koo-taejin did the logs show anything different? I cannot keep this setting because it affects my application.

**Comment by koo-taejin** [comment]
@richie-b 

I have checked that it works well in the various environments I have.

Unfortunately, it is difficult to analyze the problem with the log you uploaded.

Pinpoint team has plan to move Quickstart to spring-boot.
Probably, it seems to can complete this job until next month.

Please try again after this job.

thanks :)
