### ISSUE TITLE
Why the Data Source cannot be displayed

### ISSUE THREAD

**Issue by 52766365** [naver/pinpoint#7004]
Hi,
Why the Data Source cannot be displayed, what files need to be configured
Please help me solve this problem.I would appreciate it if you can help me!

Description
![DataSource](https://user-images.githubusercontent.com/20806983/87267853-65160a00-c4fb-11ea-92db-b3eceb4a888c.png)

**Comment by 52766365** [comment]
![DataSource](https://user-images.githubusercontent.com/20806983/87267923-9bec2000-c4fb-11ea-9257-fb42a05515bf.png)

**Comment by koo-taejin** [comment]
hi @52766365 

Please check Pinpoint supports DataSource or Dbcp that you used.
If it does not show even though it is supported, check the agent log to find the problem.

thanks :)

**Comment by 52766365** [comment]
> 嗨@ 52766365
> 
> 请检查Pinpoint支持您使用的DataSource或Dbcp。
> 如果即使支持它也没有显示，请检查代理日志以查找问题。
> 
> 谢谢 ：）



> hi @52766365
> 
> Please check Pinpoint supports DataSource or Dbcp that you used.
> If it does not show even though it is supported, check the agent log to find the problem.
> 
> thanks :)

Does the data source data connection monitoring support DB2 database?
