### ISSUE TITLE
Failed to run collector in idea

### ISSUE THREAD

**Issue by tankilo** [naver/pinpoint#7011]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

I updated code recently and found that i can't run collector as before in IDEA.

I can use `Maven` to compile project successfully in IDEA. But if i run application in IDEA, the following error will be raised.

![image](https://user-images.githubusercontent.com/10413284/87372594-8ee23600-c5ba-11ea-874f-98db056641c2.png)

![image](https://user-images.githubusercontent.com/10413284/87372666-bcc77a80-c5ba-11ea-8873-b1a7ab4e17a1.png)

![image](https://user-images.githubusercontent.com/10413284/87372682-c4871f00-c5ba-11ea-9d2f-78a675443872.png)
![image](https://user-images.githubusercontent.com/10413284/87372687-c94bd300-c5ba-11ea-94f1-7f7ec03fd58c.png)

**Comment by tankilo** [comment]
This problem will happened at both my labtop and destop pc.

**Comment by koo-taejin** [comment]
hi @tankilo 

I configured the project by initializing it. I was also met the same error.
In my case, the error  disappeared after I add pinpoint-profiler-optional-jdk9 module to the read line marked.
Please try it. 

![add module1](https://user-images.githubusercontent.com/10057874/87381232-2d789200-c5cf-11ea-9b08-7ffffafcd85d.png)

thanks :)

**Comment by koo-taejin** [comment]
@tankilo 

If not, please check if 9 is normally applied to the dependency of the actual project.
As in my image, if 8 is the default, there may be a dependency that is different from the language level.

![빌드2](https://user-images.githubusercontent.com/10057874/87387466-c0b8c400-c5dd-11ea-95f1-bcb66f131dfc.jpg)

**Comment by tankilo** [comment]
Hello, it seems that i've already configured IDEA just like you said, but i still meet problems. 

![image](https://user-images.githubusercontent.com/10413284/87393186-5ead8e00-c5e0-11ea-9bec-62396cd9ca0c.png)

![image](https://user-images.githubusercontent.com/10413284/87393304-8b61a580-c5e0-11ea-8c87-396a4e13f806.png)

```
--add-exports=java.base/jdk.internal.loader=ALL-UNNAMED --add-exports=java.base/jdk.internal.module=ALL-UNNAMED --add-exports=java.base/jdk.internal.misc=ALL-UNNAMED
```

**Comment by tankilo** [comment]
I import pinpoint code as `Maven` project into IDEA, IDEA auto set the above configuration. I didn't change them.

**Comment by koo-taejin** [comment]
As I mentioned, please check dependencies tab not sources tab.

module sdk 1.8 was my default. 
![dependencies](https://user-images.githubusercontent.com/10057874/87395608-97536480-c5ec-11ea-8b10-33151be0bca3.png)

**Comment by tankilo** [comment]
Thank you. I find out why i can't start the application.

I don't why language level is 9 , but idea choes jdk 8 as the module jdk.
![image](https://user-images.githubusercontent.com/10413284/87395582-2f008500-c5e4-11ea-9bc9-a939d23e885b.png)

**Comment by tankilo** [comment]
We comment at the same time. Thanks for your detailed explanation.

**Comment by 1121076248** [comment]
good,but i bisits webapp is 404,url:http://localhost:8080/

**Comment by koo-taejin** [comment]
@1121076248 
Collector module doen not have any http page.
Please check whether collector works well by using agent.  
thanks :)

**Comment by 1121076248** [comment]
@koo-taejin thanks,  i hbase is not connect，but i deploy to linux server, i can access it 。I want to try  Upgrade to Hbase2.0
