### ISSUE TITLE
How do we pass TraceID across other application services to get the distributed tracing context 

### ISSUE THREAD

**Issue by dinesh4747** [naver/pinpoint#7015]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

Just curious and to get the fundamendals right  - How do we pass TraceID across other application services to get the distributed tracing context 

I am under the impression that Pinpoint propagates traceid over the HTTP headers and If yes then any specific pinpoint variable we pass along with the request header ?

@yjqg6666 @emeroad @koo-taejin

**Comment by dinesh4747** [comment]
Can someone please help advice on this ?

**Comment by emeroad** [comment]
See this article
http://naver.github.io/pinpoint/plugindevguide.html
