### ISSUE TITLE
How can I exclude healthcheck url in springboot ?

### ISSUE THREAD

**Issue by ksh901016** [naver/pinpoint#7020]
I saw the similar issue in github. (https://github.com/naver/pinpoint/issues/5942). but I couldn't getthe answer.

I'm using Pinpoint 2.0.1 and spring boot. => collect requests well.
I want to exclude certain url. (ex. healthcheck, actuator)

I set up the configuration as below,but it continues to be collected.
profiler.tomcat.enable=true
profiler.tomcat.conditional.transform=false
profiler.tomcat.excludeurl=/healthcheck, /actuator/**
profiler.springboot.enable=true

Is there anything else I need to set up or check?

**Comment by jaehong-kim** [comment]
@ksh901016 
It depends on which spring-boot-starter you use.
If spring-boot-starter-webflux is used, it must be configured in Reactor Netty.
profiler.reactor-netty.server.excludeurl=

**Comment by ksh901016** [comment]
I use spring-boot-starter-web. So how do I set it up? 
Should I set it differently from the below? 
=> profiler.tomcat.excludeurl=/healthcheck, /actuator/**
