### ISSUE TITLE
Using log4j2 in agent

### ISSUE THREAD

**Issue by davide-parini** [naver/pinpoint#7027]
Are you planning to upgrate do log4j2 on profiler module also? If so, when? We experienced a severe service disruption because of a lock starvation in log4j caused by Pinpoint logging.

It seems that the issue is log4j itself, and not how you use it, as described for instance here: https://bz.apache.org/bugzilla/show_bug.cgi?id=57714

Thank you very much for your work!

**Comment by emeroad** [comment]
Thanks for reporting

Please attach detailed information such as stack traces and problem analysis reports.

Analysis is not possible with current information.

**Comment by davide-parini** [comment]
We are using Pinpoint 2.0.1 to monitor an application running on JBoss EAP 6.3 with Oracle JRE 1.7.0-161. I can't share production thread dumps, but the analysis with fastthread.io brought up this:

![image](https://user-images.githubusercontent.com/38081480/87762110-dbc04980-c812-11ea-8b8f-3f8e680f1570.png)

![image](https://user-images.githubusercontent.com/38081480/87762564-9f411d80-c813-11ea-9165-edeb602c21b7.png)

And this is where the log4j logger was blocking all other 32 threads:

![image](https://user-images.githubusercontent.com/38081480/87762825-052da500-c814-11ea-8c45-95c2e9945a0d.png)

In know, that log in `AbstractHttpClientExecuteMethodInterceptor` happens only if `com.navercorp.pinpoint` is set to DEBUG, that is something that should be avoided in a production environment. But given the known locking issues with log4j i think it could be a safer option to migrate to log4j2.

What do you think @emeroad?

**Comment by emeroad** [comment]
DEBUG level is not recommended in production environment.

Change the log level to INFO.

`$PINPOINT_HOME/profiles/{PROFILE_VALUE}/log4.xml`

**Comment by davide-parini** [comment]
Thank you @emeroad, this is what we did.

So there won't be any upgrade to log4j2 in future releases?

**Comment by emeroad** [comment]
It's not a problem with log4
If there are many logs, log4j2 is also blocked

**Comment by davide-parini** [comment]
Ok thank you for your feedback!
