### ISSUE TITLE
MultiTenant Support

### ISSUE THREAD

**Issue by praveen12bnitt** [naver/pinpoint#7042]
**Which module is your feature request related to?**
pinpoint-collector and web

**Is your feature request related to a problem?**
We plan to run pinpoint in our internal environment as well as external. To reduce the deployment complexity, we wanted to have 1 instance of pinpoint deployment (web, zookeeker, collector and hbase) and share it multiple agents from different environments. Like DEV, REGRESSION, PE, STAGE, CUST1-PROD, CUST2-PROD etc.  Is this possible?

Some of the challenges that i see is
* How can a single hbase store data from multiple agents? 
* Today the landing page shows a list of applications. Filtering on a multi tenant env will be challenging.

**Describe the solution you'd like**
* The way we split data should change right? May be have a tenant code prefix to all the row identifiers ?
* Make changes in agent, controller and web to use tenant as a key and send it while saving, retrieving data 
* Make the UI aware of tenant. 

Let me know what you think about this idea?

**Comment by praveen12bnitt** [comment]
For scaling, we can also deploy 1..n collector for each tenant. But they all push data to the same hbase. Our biggest challenge is to manage hbase and if i can reduce the number of hbase instance it will make all of our life easier.

**Comment by emeroad** [comment]
https://github.com/naver/pinpoint/blob/master/web/src/main/resources/hbase-root.properties#L8
```
# hbase namespace to use default:default
hbase.namespace=default
```

Pinpoint can support multi-tenant using hbase namespace.
https://hbase.apache.org/book.html#_namespace

**Comment by praveen12bnitt** [comment]
Unfortunately Bigatable does not support it. So I am still stuck.

https://cloud.google.com/bigtable/docs/hbase-differences

Is it easy to implement the suggestion they have given in the link ?

**Comment by yjqg6666** [comment]
@praveen12bnitt You may append the ENV to the application name to differentiate runtime environment, i.e. applicationA at UAT env. -> pinpoint.applicationName=applicationA-uat . But still namespace is the recommended way.
