### ISSUE TITLE
Google BigTable, grpc version and multi tenant

### ISSUE THREAD

**Issue by praveen12bnitt** [naver/pinpoint#7043]
Pinpoint team,
First of all, many congratulations for building such a great product. I am playing around with pinpoint for 3 months and the amount of data this captures and the plugins it has it awesome. Thanks for building it for the open source community.

We are currently evaluating pinpoint as our APM tool for both our internal and external deployment. We have deployment pinpoint in many env and very happy with the monitoring capabilities of it. The number 1 problem that we get into is, managing the hbase cluster. Because of the amount of data that our application produces, managing hbase is becoming very difficult. The make things easier for us, we reduced the TTL to just  1 day and even with that we see our hbase constantly crashing. It might be be pinpoint's problem or hbase problem. The lack of hbase expertise in our organization might be the reason. 

So instead of managing our own hbase cluster, can we use a managed service like Google's BigTable. That is why i created the below ticket couple of months ago to see if we can integrate with google's bigtable.
https://github.com/naver/pinpoint/issues/6441

So i took up the challenge and started making changes.  

**grpc version**
The first hurdle that i faced was grpc version. The bigtable java libraries that google gives uses the most recent version of grpc.  I believe pinpoint is still using `1.14.0`. This version was released on July 2018. My initial reaction was, if support for grpc was introduced in pinpoint 2.0, why is pinpoint still using this very old version. Then i realized that this might be because of support for Java 6. grpc 1.14 was the last version to support java 6. Is my guess correct?

We run our application on java 8. So this was not a requirement for us. So i did not give up and started making changes in the pom to upgrade grpc to 1.26.x. With few changes here and there, i was able to upgrade it successfully.  :). If you think we can drop support for java 1.6, i will create a PR to upgrade grcp to 1.26.x

**google bigtable libraries**
After upgrading grpc, i included the bigtable client libraries.
<dependency>
            <groupId>com.google.cloud.bigtable</groupId>
            <artifactId>bigtable-hbase-1.x</artifactId>
            <version>1.14.1</version>
</dependency>

After this, i made few changes to the com.navercorp.pinpoint.common.hbase.HbaseConfigurationFactoryBean and managed to successfully collect to google big data and dump the traces. :)

So this has given me a lot of confidence that its technically possible to connect pinpoint to google bigtable and our biggest maintance nightmare can be solved. If you all agree that we can support google bigtable as a *supported* database, i will work with you to make the necessary changes to merge the changes in. 

**multi tenant**
The other topic is multi tenant. If we decide to go with Google BigTable, having support for multi tenant will also be a key change to keep the cost optimal.  I created a separate ticket  https://github.com/naver/pinpoint/issues/7042 to discuss more about multi tenant support in pinpoint.

**Comment by emeroad** [comment]
**grpc**
> Then i realized that this might be because of support for Java 6. grpc 1.14 was the last version to support java 6. Is my guess correct?

Yes.  Pinpoint will support jdk6 for the time being.

**google bigtable libraries**
Try using shaded version (bigtable-hbase-1.x-shaded).
Shaded lib contains all dependencies.
https://cloud.google.com/bigtable/docs/upgrading-clients

**Comment by praveen12bnitt** [comment]
The problem is grpc is a common dependency between Bigatable and pinpoint
grpc. So I am not sure how it's going to help. I am still going to set into
a conflict situation

**Comment by yjqg6666** [comment]
@praveen12bnitt You may append the ENV to the application name to differentiate runtime environment, i.e. applicationA at UAT env. -> pinpoint.applicationName=applicationA-uat . But still namespace is the recommended way.
