### ISSUE TITLE
How can I add/modify agent profiler?

### ISSUE THREAD

**Issue by catto-coder** [naver/pinpoint#7054]
I need to add some features when profiling from an agent. I'm using release version 2.0.1.

I have tried to track the codes from the collector modules, from TraceService but only ended up in com.navercorp.pinpoint.grpc.server.StreamExecutorServerInterceptor on run() method. I cannot find where the data was passed.

I think maybe the data was scraped from profiler module? I tried to read the code, however, I think it will help me a lot if I know what architecture is used in profiler module.

The question is, where should I add the code if I want to modify the profiling feature? What is the architecture used in profiler module?

Thank you in advance

**Comment by RoySRose** [comment]
Hello, @catto-coder 

please check the homepage for the information you need, such as [architecture](http://naver.github.io/pinpoint/2.0.4/overview.html) and few more are there.

If you are collecting metric data, the code will be under profile, if you are talking about tracing data it will be under the corresponding plugin.
