### ISSUE TITLE
Usage of ApplicationName in Microservice Architecture

### ISSUE THREAD

**Issue by stephan-klein** [naver/pinpoint#7055]
[x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

I want to trace an Application consisting of multiple components (Microservice Architecture) with Pinpoint. Basically there is 

1. A NGINX Proxy including static Javascript Files which use
2. A Bunch of Java/Spring based Microservices on the Backend.

Its clear to me all Microservices need to include the Pinpoint Agent and need a unique _pinpoint.agentId_. But what should be set for _pinpoint.applicationName_ ? Should they share the same applicationName or a different one ? Or what would be the benefits/disadvantages of using the same applicationName or a different one if both is possible?

**Comment by RoySRose** [comment]
Hello, @stephan-klein 

[This document](http://naver.github.io/pinpoint/2.0.4/installation.html#installation-2) is closest to what you are looking for. 
I think the doc is clear enough. But if you are still confused after reading it, you can always try it out with some samples.
Additionally, it would be **PERFECT** if you can share the result with the community.

**Comment by stephan-klein** [comment]
@RoySRose 
The linked document tells the following about ApplicationName:

> -Dpinpoint.applicationName - groups a number of identical application instances as a single service

and

> and all applications that share the same pinpoint.applicationName are treated as multiple instances of a single service.

If im interpreting this strictly, the different components of my application (the microservices) should not share the same applicationName, because they are in no way **identical** application instances (every component has their own purpose, different code)

If im interpreting this loosely, i could say all components are instances of the same application.

Summarized, its still not clear to me.

Maybe i will try both setups and see how pinpoint behaves. Of course any experience from a real life setup would help.

**Comment by RoySRose** [comment]
@stephan-klein 

Actually, there wasn't any report on the unclearness of the guide until now.
If you do have better words for it, we are open to any suggestion on wording :)

However, your strictly interpreting is correct, and actually there can be identical application instances (same purpose, same codes) in microservices. It when you cluster the server.

To help you clear things. You can check our demo. There isn't any application that shares the same `applicationName` in the shopping service, only the ones with different 'applicationName' for each instance. If there are 5 instances that share the same 'applicationName', the node will be displayed as below

![image](https://user-images.githubusercontent.com/20402016/88535563-1b720700-d045-11ea-8d8c-6527f1fedc1c.png)

**Comment by stephan-klein** [comment]
thanks @RoySRose . its clear now.
