### ISSUE TITLE
ElasticSearch plugin does not support multiple nodes

### ISSUE THREAD

**Issue by devcco** [naver/pinpoint#7073]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
master/v2.0.2

#### Describe the bug
When I configure single node, Pinpoint can recognize the Server Map of ElasticSearch。
![image](https://user-images.githubusercontent.com/9484545/89140911-953e4f00-d575-11ea-9ccf-4d44e9628c3b.png)
When I configure multiple nodes, Pinpoint can't recognize the Server Map of ElasticSearch。
![image](https://user-images.githubusercontent.com/9484545/89140998-d7679080-d575-11ea-9c57-4d3564feeb71.png)

#### What did you do to trigger the bug?
application.properties
```properties
# single node
spring.elasticsearch.rest.ip-address=10.254.5.102:9200
# multiple nodes
spring.elasticsearch.rest.ip-address=10.254.5.102:9200,10.254.5.107:9201,10.254.5.108:9201
```

#### Expected behavior
ElasticSearch multiple nodes and single node should be the same
#### Screenshots
![image](https://user-images.githubusercontent.com/9484545/89140911-953e4f00-d575-11ea-9ccf-4d44e9628c3b.png)

**Comment by emiling** [comment]
Hello, @devcco I'm going to look into it.
Can I know which version of Elasticsearch is used in your project?

**Comment by devcco** [comment]
> Hello, @devcco I'm going to look into it.
> Can I know which version of Elasticsearch is used in your project?

Thanks,I am using ElasticSearch 7.8.0.

**Comment by RoySRose** [comment]
Hello, 

@emiling 
Great! Thanks for your contribution, 

@devcco
So, your version of ElasticSearch itself is 7.8.0?
How about you Elasticsearch java client? Which do you use and it's version is?

**Comment by devcco** [comment]
> How about you Elasticsearch java client? Which do you use and it's version is?
Q: So, your version of ElasticSearch itself is 7.8.0?
A: yes.
Q: How about you Elasticsearch java client? Which do you use and it's version is?
A: I'm using RestHighLevelClient 7.8.0

pom.xml:
```xml
        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
           <version>7.8.0</version>
        </dependency>

        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>elasticsearch-rest-high-level-client</artifactId>
           <version>7.8.0</version>
        </dependency>

        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>elasticsearch-rest-client</artifactId>
            <version>7.8.0</version>
        </dependency>
```
ESconfig.java
```java
@Configuration
@Slf4j
public class ElasticSearchConfig {

    @Value("${spring.elasticsearch.rest.scheme}")
    private String scheme;

    @Value("${spring.elasticsearch.rest.ip-address}")
    private List<String> ipAddressList;

    @Bean
    RestHighLevelClient elasticsearchClient() {
        return new RestHighLevelClient(RestClient.builder(this.createHttpHost()));
    }

    /**
     * 创建 HttpHost 对象
     *
     * @return 返回 HttpHost 对象数组
     */
    private HttpHost[] createHttpHost() {
        Asserts.check(!CollectionUtils.isEmpty(ipAddressList), "ElasticSearch cluster ip address cannot empty");
        HttpHost[] httpHosts = new HttpHost[ipAddressList.size()];
        for (int i = 0, len = ipAddressList.size(); i < len; i++) {
            String ipAddress = ipAddressList.get(i);
            String[] values = ipAddress.split(":");
            String ip = values[0];
            int port = Integer.parseInt(values[1]);
            // 创建 HttpHost
            log.info("Initialize the elasticSearch - {}:{}", ip, port);
            httpHosts[i] = new HttpHost(ip, port, scheme);
        }
        return httpHosts;
    }
}
```

application.properties
```properties
spring.elasticsearch.rest.scheme=http
spring.elasticsearch.rest.ip-address=10.254.5.102:9200,10.254.5.107:9201,10.254.5.108:9201
```
xxxServiceImpl
```java
@Autowired
private RestHighLevelClient restHighLevelClient;
```

**Comment by RoySRose** [comment]
@devcco got it.
@emiling Then I think you need to dig into `elasticsearch-rest-high-level-client 7.8.0` to solve the problem.
