### ISSUE TITLE
Add armeria plugin

### ISSUE THREAD

**Issue by heowc** [naver/pinpoint#7076]
**Which module is your feature request related to?**
Plugin

**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
Add [line/armeria](https://github.com/line/armeria) plugin

**Comment by heowc** [comment]
/cc @trustin
I don't know the details yet, but I'm going to try this. 🤔

**Comment by trustin** [comment]
That's an awesome news! I hope you enjoy the contribution process and eventually convince the team to migrate to Armeria. 😉

**Comment by RoySRose** [comment]
Hello, @heowc 

Many people are looking forward to it.

**Comment by eonezhang** [comment]
could  the community plan to support this feature?

**Comment by koo-taejin** [comment]
@eonezhang 
Pinpoint has no plans to support this yet.

@heowc 
Please let us know progress of this issue.

**Comment by heowc** [comment]
> @heowc
> Please let us know progress of this issue.

I've been very busy recently and the response was late. 😭
As I just said, I'm very busy lately, so I don't think I can proceed with this issue. Sorry.

**Comment by koo-taejin** [comment]
@heowc  Thanks for having checked it. :)
