### ISSUE TITLE
I would like to be able to manually delete the instance

### ISSUE THREAD

**Issue by abingpow** [naver/pinpoint#7084]
![QQ截图20200806104823](https://user-images.githubusercontent.com/30452566/89485004-607b0380-d7d2-11ea-8fb3-dd4149f29e20.png)
Can you add the operation of manually deleting agent?As for the screenshot, it has been August, but the instance in June stopped long ago. The dependency is still running, and there is no way to solve it.

**Comment by ga-ram** [comment]
As far as I know, you can 
1) go to the settings menu on the top right,
2) select Administration > Agent Management,
3) search your application name,
4) delete your agent by clicking the red trash can icon 

![Screen Shot 2020-08-06 at 1 58 11 PM](https://user-images.githubusercontent.com/3798235/89492839-8b268580-d7ed-11ea-87a3-957d48679616.png)

**Comment by abingpow** [comment]
thanks for ga-ram reply. But I used version 1.8.3, and I did not find this function on the configuration page. Does version 1.8.3 not support it?
![aaaa](https://user-images.githubusercontent.com/30452566/89517792-d4d29880-d80c-11ea-94f6-4d60eb2018b9.png)

**Comment by ga-ram** [comment]
I'm not very familiar with version 1.8.3.
Would you try this on your web browser?
http://{your_pinpoint_address}/admin/removeAgentId.pinpoint?applicationName=model&agentId=model-7051

**Comment by abingpow** [comment]
Thank you very much for ga-ram's reply. It is indeed effective. It has been deleted successfully. ^_^
