### ISSUE TITLE
Do i need to use both grpc and thirft to send data from agent (profiler) to collector?

### ISSUE THREAD

**Issue by catto-coder** [naver/pinpoint#7088]
Hi.
I'm currently trying to add more scraped data from profiler besides the existing span, agentStat, etc

I see that I need to send the data to the collector via a port either using grpc or thrift (correct me if I'm wrong)

As I'm writing the codes to make this work, I see that there is some code that states that only grpc/thrift needed, but another code at another place set for both to work.

Do I need to use both or just one of them?

**Comment by emeroad** [comment]
Thrift will be deprecated in the future.
You only need to implement grpc.
