### ISSUE TITLE
pinpoint 2.0.3 no display on web UI

### ISSUE THREAD

**Issue by jj-vicente** [naver/pinpoint#7099]
hi,

I have installed pinpoint 2.0.3 in Linux 6 and installed on Tomcat 7.0.72. I have created 2 tomcat instances, 1 for Collector and 1 for Web UI. tomcat is running fine both instances, however, when  deploying collector/web jar files and configured per installation I get white page URL accessing the Web UI. All ports on the servers iptables are open. I don't see any related error on collector/web logs. could anyone encounter this? 

![image](https://user-images.githubusercontent.com/67358754/89931724-e4871e00-dc0c-11ea-845f-96200975376b.png)

**Comment by emeroad** [comment]
Pinpoint-web does not support context-path

Recommended root-context
> /ppweb203 -> /

**Comment by ChakraverthyK** [comment]
Any update for on the issue fix. Even I am facing the similar issue

**Comment by jj-vicente** [comment]
@ChakraverthyK rename pinpointweb.war to ROOT.war

**Comment by ChakraverthyK** [comment]
Yes I have already renamed that as well

**Comment by ChakraverthyK** [comment]
> @ChakraverthyK rename pinpointweb.war to ROOT.war

Pls let me know if we can connect some time so that you can help with me on the issue fix

**Comment by jj-vicente** [comment]
@ChakraverthyK try accessing now without the context-path ex. http://<IP>:8080

**Comment by ChakraverthyK** [comment]
Yes, I tried this now, But no luck :(

**Comment by ChakraverthyK** [comment]
<img width="960" alt="Pinpoint_Snap" src="https://user-images.githubusercontent.com/38877600/91954757-de71f200-ed1f-11ea-95de-ae42608bc45f.PNG">
URL For Pinpoint-Web: http://localhost:8185/main
I am unable to find TestApp within Pinpoint Web now, and also TestApp is not launching in 28081 port.

And URL for TestApp is: http://localhost:8185/pinpoint-quickstart-testapp-2.0.3/

Am I missing something here?

**Comment by ChakraverthyK** [comment]
Issue is resolved after building through Maven all the dependencies.
