### ISSUE TITLE
After I install the pinpoint2.0.3 ，no Data for Response Summary and Load。the main page only one app name。no map

### ISSUE THREAD

**Issue by caicha** [naver/pinpoint#7104]
can anybody tell me why？thanks

**Comment by caicha** [comment]
![result](https://user-images.githubusercontent.com/16550895/89999915-0bebf280-dcc2-11ea-8c88-306ac2ce4ec7.png)

**Comment by emeroad** [comment]
Check the HBase compatibility table.

There may be a problem when using hbase 2.0.

**Comment by caicha** [comment]
Hello friend, The following version of HBase I installed, is there any problem! Thank you!


hbase(main):022:0* hbase version
2.3.0, re0e1382705c59d3fb3ad8f5bff720a9dc7120fb8, Mon Jul&nbsp; 6 22:27:43 UTC 2020
Took 0.0005 seconds&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
NoMethodError: undefined method `hbase' for main:Object


PS: And the follow three tables are empty! I checked the log, No abnormal log was found.
ApplicationMapStatisticsCallee_Ver2、ApplicationMapStatisticsCaller_Ver2、ApplicationMapStatisticsSelf_Ver2









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "naver/pinpoint"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月14日(星期五) 下午3:29
收件人:&nbsp;"naver/pinpoint"<pinpoint@noreply.github.com&gt;;
抄送:&nbsp;"987445363"<987445363@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [naver/pinpoint] After I install the pinpoint2.0.3 ，no Data for Response Summary and Load。the main page only one app name。no map (#7104)





 
Check the HBase compatibility table.
 
There may be a problem when using hbase 2.0.

**Comment by caicha** [comment]
hbase1.2.7 can work！
