### ISSUE TITLE
Running application experienced unexpected agent shutdown & connected

### ISSUE THREAD

**Issue by yjqg6666** [naver/pinpoint#7111]
A long-time running application experienced unexpected pinpoint agent shutdown/connected. From the agent log, only the new log were found. **_What might be the cause?_**

agent log(no shutdown-related log):
> 2020-08-12 23:20:59 [INFO ](c.n.p.p.DefaultAgent               ) AgentOption:DefaultAgentOption{...
> 2020-08-12 23:20:59 [INFO ](c.n.p.p.l.Slf4jLoggerBinder        ) PLoggerFactory.initialize() bind:com.navercorp.pinpoint.profiler.logging.Slf4jLoggerBinder cl:ParallelClassLoader@140435067{name='pinpoint.agent'}
> 2020-08-12 23:20:59 [INFO ](c.n.p.p.u.SystemPropertyDumper     ) SystemProperties java.runtime.name=OpenJDK Runtime Environment
> 2020-08-12 23:20:59 [INFO ](c.n.p.p.u.SystemPropertyDumper     ) SystemProperties profiler.undertow.excludeurl=/**/*.svg,/favicon.ico,/**/*.png,/app-name/actuator/health,/metrics,/**/*.jpg,/**/*.jpeg,/**/*.css,/**/*.js
> 2020-08-12 23:20:59 [INFO ](c.n.p.p.u.SystemPropertyDumper     ) SystemProperties sun.boot.library.path=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64
> 2020-08-12 23:20:59 [INFO ](c.n.p.p.u.SystemPropertyDumper     ) SystemProperties java.vm.version=25.181-b13
> 2020-08-12 23:20:59 [INFO ](c.n.p.p.u.SystemPropertyDumper     ) SystemProperties profiler.tomcat.excludeurl=/**/*.svg,/favicon.ico,/**/*.png,/app-name/actuator/health,/metrics,/**/*.jpg,/**/*.jpeg,/**/*.css,/**/*.js
> 2020-08-12 23:20:59 [INFO ](c.n.p.p.u.SystemPropertyDumper     ) SystemProperties java.vm.vendor=Oracle Corporation
> 2020-08-12 23:20:59 [INFO ](c.n.p.p.u.SystemPropertyDumper     ) SystemProperties java.vendor.url=http://java.oracle.com/
> 2020-08-12 23:20:59 [INFO ](c.n.p.p.u.SystemPropertyDumper     ) SystemProperties path.separator=:

![image](https://user-images.githubusercontent.com/1879641/90237494-ed6b3000-de56-11ea-99cf-cce30f072cc7.png)
![image](https://user-images.githubusercontent.com/1879641/90237512-f78d2e80-de56-11ea-8fe7-6011ce832f63.png)
![image](https://user-images.githubusercontent.com/1879641/90237654-31f6cb80-de57-11ea-8681-e11f3607a0db.png)

**Comment by emeroad** [comment]
Is the tcp disconnected? Or JVM crash(shutdown)?

**Comment by yjqg6666** [comment]
JVM was still running. So it might be a connection issue cause the established connection disconnected.

**Comment by yjqg6666** [comment]
Update: just checked the jvm process by "ps -p pid -o lstart,etime" and confirmed the crash of the jvm. Thanks for the help.

**Comment by emeroad** [comment]
Tcp disconnect is most likely a network issue.
-e.g) L4 timeout, Collector restart

In problem situation, gRpc tends to not print a log if the problem recovers,
For detailed analysis of the problem, should change the grpc log level to debug.
