### ISSUE TITLE
Pinpoint-Web cannot import common.hbase.HbaseTableConstants

### ISSUE THREAD

**Issue by imbf** [naver/pinpoint#7119]
![image](https://user-images.githubusercontent.com/47495187/90337470-9fecef80-e01d-11ea-8f7e-4315a8d1f31e.png)

As shown in the picture above

Pinpoint-web cannot import common.hbase.HbaseTalbeConstants

So I can't start pinpoint-web in local

Could you rename HbaseTableConstatns to HbaseTableConstants in pinpoint-common-hbase-2.1.0-SNAPSHOT.jar

**Comment by yjqg6666** [comment]
From your IDEA view, the import package is not used, i think you may make a PR for the line deletion.

**Comment by imbf** [comment]
It was my mistake because I did not clean and build the dependencies after rebase in the master branch of upstream!!

haha… 

The source code of the pinpoint web is the latest commit, while the project dependencies (pinpoint - hbase) are built from past commits.

**Comment by imbf** [comment]
Thank you Pinpoint!
