### ISSUE TITLE
does pinpoint send data to google

### ISSUE THREAD

**Issue by AlexDingSZ** [naver/pinpoint#7121]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
master/v1.7.3/v1.7.2 etc.

#### What did you do to trigger the bug?
does pinpoint send data to google?

GET http://www.google-analytics.com/r/collect?v=1&_v=j83&a=2035790534&t=event&_s=11&dl=http%3A%2F%2F192.168.128.110%2F&dp=%2Fmain&ul=zh-cn&de=UTF-8&dt=PINPOINT&sd=24-bit&sr=1920x1080&vp=1920x513&je=0&ec=main&ea=Select%20Period&el=20m&_u=SACAAEAB~&jid=2033717359&gjid=1656362684&cid=838110754.1597636020&tid=UA-57786344-1&_gid=1268796023.1597636020&_r=1&z=1456788077 HTTP/1.1
Host: www.google-analytics.com
Proxy-Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
Accept: image/webp,image/apng,image/*,*/*;q=0.8
Referer: http://192.168.128.110:8080/main/pet_zhcz-bgt-draft-audit@SPRING_BOOT/5m/2020-08-17-14-35-38
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,und;q=0.8,en;q=0.7

**Comment by AlexDingSZ** [comment]
delete the code in pinpoint web file index.html

<script> (function(i, s, o, g, r, a, m) { i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function() { (i[r].q = i[r].q || []).push(arguments) }, i[r].l = 1 * new Date(); a = s.createElement(o), m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m) })(window, document, 'script', 'http://192.168.128.110:8080/analytics.js', 'ga'); ga('create', 'UA-57786344-1', 'auto'); </script>

pinpoint doesn't send data to google anymore

**Comment by RoySRose** [comment]
https://naver.github.io/pinpoint/faq.html#why-do-i-see-ui-send-requests-to-httpswwwgoogle-analyticscomcollect
