### ISSUE TITLE
pinpoint 2.0.3 ： Agent management can not remove application！！！ can any tell me why？thanks

### ISSUE THREAD

**Issue by caicha** [naver/pinpoint#7122]

**Comment by caicha** [comment]
![agent management](https://user-images.githubusercontent.com/16550895/90375402-7d071d80-e0a7-11ea-98b6-5519e3d51208.png)

**Comment by yjqg6666** [comment]
From the network request/response, error response was found "Missing password". From the UI part, no place to provide password. So i thought the function need some UI update to allow user to provide password.

**Comment by yjqg6666** [comment]
You can get the GET request URL from DevTools and append &password=REPLACE_WITH_YOUR_PASSWORD to the request url.

**Comment by caicha** [comment]
it works. And how can I set the username and password for my pinpoint-web. thanks！

> You can get the GET request URL from DevTools and append &password=REPLACE_WITH_YOUR_PASSWORD to the request url.

**Comment by yjqg6666** [comment]
https://github.com/naver/pinpoint/blob/master/web/src/main/resources/pinpoint-web-root.properties#L27 
> admin.password=admin

**Comment by yjqg6666** [comment]
In released versions, it's in a different file https://github.com/naver/pinpoint/blob/v2.0.4/web/src/main/resources/pinpoint-web.properties#L27 .

**Comment by caicha** [comment]
> https://github.com/naver/pinpoint/blob/master/web/src/main/resources/pinpoint-web-root.properties#L27
> 
> > admin.password=admin

The application was successfully deleted by including the password in the URL. Now my inpoint-web does not require login authentication, I want to set up an authentication interface for pinpoint web. What should I do? Thanks!

**Comment by binDongKim** [comment]
@caicha It seems to be missing an interface for entering the password in the page. Planning on adding it. Thanks for the report :)

@yjqg6666 Thanks for your help

**Comment by caicha** [comment]
> @caicha It seems to be missing an interface for entering the password in the page. Planning on adding it. Thanks for the report :)
> 
> @yjqg6666 Thanks for your help

OK! Thank you very much!

**Comment by koo-taejin** [comment]
@caicha 

Unfortunately, for now, Pinpoint does not support authentication.
Dongbin is gonna make what Dongbin said. 

thanks :)

**Comment by caicha** [comment]
> @caicha
> 
> Unfortunately, for now, Pinpoint does not support authentication.
> Dongbin is gonna make what Dongbin said.
> 
> thanks :)

hope to support it as soon as possible. Pinpoint is a good product！thanks！

**Comment by yjqg6666** [comment]
@binDongKim thanks and waiting for the update. Application/agent deletion from the UI is a useful feature. I used to delete them by directly call url, it would be so much better through UI.

**Comment by binDongKim** [comment]
Resolved by https://github.com/naver/pinpoint/pull/7140
