### ISSUE TITLE
Alarm smtp config，The password  is clear text.（alarm.mail.server.password=）.Can the password be set in other ways, such as ciphertext in the database! thanks!

### ISSUE THREAD

**Issue by caicha** [naver/pinpoint#7126]
![alarm smtp config](https://user-images.githubusercontent.com/16550895/90481733-daad6f80-e164-11ea-905b-220d75343944.png)

**Comment by emeroad** [comment]
Pinpoint can override the property with -Dxxx from 2.1.0.
```
java -jar -Dalarm.mail.sever.password=1234 pinpoint-web-boot-$VERSION.jar
```

See Externalized Configuration feature of spring-boot
https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-application-property-files

**Comment by caicha** [comment]
> Pinpoint can override the property with -Dxxx from 2.1.0.
> 
> ```
> java -jar -Dalarm.mail.sever.password=1234 pinpoint-web-boot-$VERSION.jar
> ```
> 
> See Externalized Configuration feature of spring-boot
> https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-application-property-files

ok！thank you very much！

**Comment by emeroad** [comment]
This feature depends on spring framework, so I think 2.0.x is also possible.
