### ISSUE TITLE
pinpoint 2.0.3 ：  The sampling rate was found to be incorrect after my tests. is it my configuration error? can anyone tells me why? thanks!!!

### ISSUE THREAD

**Issue by caicha** [naver/pinpoint#7141]
when i set profiler.sampling.enable=true and profiler.sampling.rate=1 or 5 or 10 or 20. Ten transactions were sent, and only one transaction be sampled.

**Comment by caicha** [comment]
![sampling](https://user-images.githubusercontent.com/16550895/90710097-38aa9600-e2d0-11ea-889e-fe89bea66e9f.png)

**Comment by Zoey-dot** [comment]
profiler.sampling.rate=: 1=100%  2 = 50%   4 = 25%   10 =10%   20 = 5%
Change the "sampling.rate" in the two configuration files respectively and recomplile. The two configuration files are as follows: “pinpoint-env.config” in “profiles\release”  and “rofiles\local”.
https://github.com/naver/pinpoint/blob/master/agent/src/main/resources/profiles/local/pinpoint.config#L60
https://github.com/naver/pinpoint/blob/master/agent/src/main/resources/profiles/release/pinpoint.config#L60

**Comment by caicha** [comment]
> profiler.sampling.rate=: 1=100% 2 = 50% 4 = 25% 10 =10% 20 = 5%
> Change the "sampling.rate" in the two configuration files respectively and recomplile. The two configuration files are as follows: “pinpoint-env.config” in “profiles\release” and “rofiles\local”.
> https://github.com/naver/pinpoint/blob/master/agent/src/main/resources/profiles/local/pinpoint.config#L60
> https://github.com/naver/pinpoint/blob/master/agent/src/main/resources/profiles/release/pinpoint.config#L60

Now  the  configuration works. And I hava anther question:  the sever map is：App1->App2->App3. If i Set App1's  profiler.sampling.rate=1. Set the App2's  profiler.sampling.rate=1 or 20, and my test result is that App2‘s sampling rate is the same。

**Comment by koo-taejin** [comment]
hi @caicha 

According to the transaction tracking policy, if there is a trace that already traced, the request would be traced.
For above reason, if front application sampling policy is 100%, then all applications that receive requests from it would all track down request.

thanks :)

**Comment by caicha** [comment]
> hi @caicha
> 
> According to the transaction tracking policy, if there is a trace that already traced, the request would be traced.
> For above reason, if front application sampling policy is 100%, then all applications that receive requests from it would all track down request.
> 
> thanks :)

Thank you very much!
