### ISSUE TITLE
PinPoint For SpringBoot,Use Redis Lua:io.lettuce.core.RedisCommandExecutionException: NOSCRIPT No matching script. Please use EVAL.

### ISSUE THREAD

**Issue by koudaiDemon** [naver/pinpoint#7145]
Error Can Be Filter When Use PinPoint? This Error is try catch by spring code.

**Comment by dengliming** [comment]
I don't quite understand what you mean

**Comment by koudaiDemon** [comment]
Sorry, my description may not be clear, I hope that the Pinpoint r can support the filtering special exception, when I use the PINPOINT R for APM monitoring, if the A method calls The B method, The B method throws the exception, but the A method has the exception capture, then the request Pinpoint r will be considered as the exception.

**Comment by RoySRose** [comment]
Hello, @koudaiDemon 

Currently, http status code is captured. 
I'm not sure if I've understood you correctly, I think with #7254 merged, pinpoint will be able to capture what you're trying to say.

To be sure...
What do you mean by Pinpoint R? We don't have Pinpoint R-agent yet.

**Comment by koudaiDemon** [comment]
Thanks, ”PinPoint R“  is faulty by translation software，I think #7254 has solved my problem。
