### ISSUE TITLE
where is pinpoint-collector-boot-2.1.0-SNAPSHOT.jar

### ISSUE THREAD

**Issue by Benzion18** [naver/pinpoint#7188]
Hi,

From https://naver.github.io/pinpoint/installation.html#installation 
**_java -jar -Dpinpoint.zookeeper.address=localhost pinpoint-collector-boot-2.1.0-SNAPSHOT.jar_**
From https://naver.github.io/pinpoint/installation.html#installation-1  
**_java -jar -Dpinpoint.zookeeper.address=localhost pinpoint-web-boot-2.1.0-SNAPSHOT.jar_**

Where can I download these jars?

**Comment by RoySRose** [comment]
Hello, @Benzion18 

It's under target/deploy folder when you build the project.
Also as you can guess with the name of the `jar`, the release isn't yet released.

**Comment by Benzion18** [comment]
Thanks for a quick response. The problem is that our environment is behind proxy and while trying to build, we fail on trying to access maven url. Can we just copy the whole installation, unpack it and run, without need to build it?
