### ISSUE TITLE
Live demo is not accessible.

### ISSUE THREAD

**Issue by yjqg6666** [naver/pinpoint#7191]
Live demo address http://125.209.240.10:10123/main/ApiGateway@SPRING_BOOT/5m?inbound=1&outbound=4&wasOnly=false&bidirectional=false is not accessible. 

Tried http://125.209.240.10:10123/configuration.pinpoint from three different locations and failed.
All the pings from different location timeout.
![image](https://user-images.githubusercontent.com/1879641/91687354-1814f280-eb92-11ea-9465-2a34e34b6c41.png)

**Comment by koo-taejin** [comment]
hi @yjqg6666 

thanks for your reporting. 
I am going to check it. 

thanks :)

**Comment by koo-taejin** [comment]
@yjqg6666 

It might be going to take around 1 day.
I ll let you know when this job is finished. 

thanks :)

**Comment by yjqg6666** [comment]
@koo-taejin Thanks for the update.

**Comment by koo-taejin** [comment]
Live demo is working now :)

Thanks, for your reporting.
