### ISSUE TITLE
Can install pinpoint behind proxy

### ISSUE THREAD

**Issue by Benzion18** [naver/pinpoint#7194]
Hi,

Our environment is behind proxy and while trying to build, we fail on trying to access maven url. Can we just copy the whole installation, unpack it and run, without need to build it?

**Comment by koo-taejin** [comment]
hi @Benzion18 

This is possible by installing in Maven offline mode after copy whole library in mave local repository.
But I am not sure that installing NPM is possible.

Simple way is that install Pinpoint another environment 
And copy collector and web jar to your environment.

thanks :)

**Comment by RoySRose** [comment]
>without need to build it?

Simply. use the files in the [release](https://github.com/naver/pinpoint/releases/tag/v2.0.4)

**Comment by Benzion18** [comment]
Hi,

I found how to work behind proxy. In mvnw file add this line: 
export MAVEN_OPTS="-Dhttp.proxyHost=<my proxy host> -Dhttp.proxyPort=<my proxy port> -Dhttps.proxyHost=<my proxy host> -Dhttps.proxyPort=<my proxy port> "

But it failed further because the build requires java 9 and I have a problem to install it on my env.

**Comment by RoySRose** [comment]
@Benzion18 

>But it failed further because the build requires java 9 and I have a problem to install it on my env.

Just to let you know.
Yes, you will need java 9 to build it. But you won't need java 9 to use it.
