### ISSUE TITLE
deploy collect problem

### ISSUE THREAD

**Issue by catlovefish** [naver/pinpoint#7210]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grpcAgentReceiver' defined in class path resource [applicationContext
-collector-grpc.xml]: Invocation of init method failed; nested exception is java.io.IOException: Failed to bind

![image](https://user-images.githubusercontent.com/16644926/92067174-4125c500-edd6-11ea-98c6-e3490adba046.png)

**Comment by minwoo-jung** [comment]
Hello @catlovefish
What version are you using?

Show more error stacks below.
Add a profile if you haven't added it when starting the collector.

**Comment by emeroad** [comment]
`java.io.IOException: Failed to bind` <- Check if the 9991 port is in use.
