### ISSUE TITLE
Server map not showing correctly on main page.

### ISSUE THREAD

**Issue by dv-morais** [naver/pinpoint#7215]
#### What version of pinpoint are you using?
2.0.4

#### Describe your problem**
Server map not showing correctly when in 'main' page... but it shows correctly when selected individually at the 'transactionList' page

#### What have you done?
Tried to re-check configs for errors.

#### Screenshots
![image](https://user-images.githubusercontent.com/57958197/92019895-b6898b00-ed2d-11ea-92e3-80d418934c05.png)
![image](https://user-images.githubusercontent.com/57958197/92020155-1a13b880-ed2e-11ea-84bb-6b9256fdbfff.png)

**Comment by minwoo-jung** [comment]
Hi @dv-morais
If there is no special error message from the collector or web, and you are using hbase version 2.0 or higher, try to build the hbase client version according to the hbase server version.
please ref : 
https://naver.github.io/pinpoint/hbaseupgrade.html

**Comment by dv-morais** [comment]
It worked!

First I tried to build with the up-to-date shaded client lib... didnt work

then I did with the recommended lib version (2.1.1) and it worked...

Thank you!
