### ISSUE TITLE
missing: pinpoint-collector-boot-*-SNAPSHOT.jar pinpoint-web-boot-*-SNAPSHOT.jar

### ISSUE THREAD

**Issue by Benzion18** [naver/pinpoint#7216]
Hi,

On https://naver.github.io/pinpoint/installation.html#installation you mention files **pinpoint-collector-boot-2.1.0-SNAPSHOT.jar** and **pinpoint-web-boot-2.1.0-SNAPSHOT.jar**, but these files are missing among the downloadable ones. Plz advise.

**Comment by minwoo-jung** [comment]
Hi @Benzion18 

Prior to release, no executable file is provided for the snapshot version. 
It is recommended to use the release version,
If you want to use the snapshot version, you have to build it yourself.

**Comment by Benzion18** [comment]
Can you plz give a link to release versions of these 2 jars.

**Comment by minwoo-jung** [comment]
Download it here. https://github.com/naver/pinpoint/releases

**Comment by Benzion18** [comment]
In your link there are no pinpoint-collector-boot-*.jar and pinpoint-web-boot-*.jar
