### ISSUE TITLE
There are no pinpoint-collector-boot-.jar and pinpoint-web-boot-.jar files in releases link

### ISSUE THREAD

**Issue by Benzion18** [naver/pinpoint#7218]
Download it here. https://github.com/naver/pinpoint/releases

_Originally posted by @minwoo-jung in https://github.com/naver/pinpoint/issues/7216#issuecomment-686864046_

In your link there are no pinpoint-collector-boot-.jar and pinpoint-web-boot-.jar

**Comment by minwoo-jung** [comment]
The packaging file based on spring boot is provided from version 2.1.0. Version 2.1.0 is in preparation for release.
