### ISSUE TITLE
What time does the “PROXY(NGINX)” in the invocation chain details refer to?

### ISSUE THREAD

**Issue by abingpow** [naver/pinpoint#7224]
![QQ图片20200907144509](https://user-images.githubusercontent.com/30452566/92356477-c67fe100-f118-11ea-96ed-ca3c8515475d.png)
In the Call chain details “Call Tree”, how is the “PROXY(NGINX)” time on line 3 calculated?
What is the specific time period?
Why is this time larger than the overall execution time?

**Comment by jaehong-kim** [comment]
@abingpow 
See this [article](https://github.com/naver/pinpoint/blob/master/doc/proxy-http-header.md).
