### ISSUE TITLE
compatibility question

### ISSUE THREAD

**Issue by yjqg6666** [naver/pinpoint#7252]
compatibility on 2.1.0/2.0.x/1.8.x agent with 2.0.x collector and 2.1.x web? Would it be some problem when not all collectors are upgraded from 2.0.x to 2.1.0 ?

**Comment by emeroad** [comment]
To use 2.1.0 agent, 2.1.0 collector is required.

There is a change in the specification of the handshake between agent and collector.
- https://github.com/naver/pinpoint/issues/6952

**Comment by yjqg6666** [comment]
Thanks for the quick reply.

**Comment by yjqg6666** [comment]
@emeroad  I checked the changes introduced by #6952 using the following command:
`git log --grep="#6952" master --stat=256 |grep '|' |cut -d"|" -f1 |sort |uniq`

>  collector/src/main/java/com/navercorp/pinpoint/collector/receiver/grpc/service/command/GrpcCommandService.java
>  collector/src/test/java/com/navercorp/pinpoint/collector/receiver/grpc/command/GrpcCommandServiceTest.java
>  commons-server/src/test/java/com/navercorp/pinpoint/common/server/bo/grpc/CollectorGrpcSpanFactoryTest.java
>  grpc/src/main/java/com/navercorp/pinpoint/grpc/Header.java
>  grpc/src/main/java/com/navercorp/pinpoint/grpc/client/SupportCommandCodeClientInterceptor.java
>  grpc/src/main/java/com/navercorp/pinpoint/grpc/server/AgentHeaderReader.java
>  grpc/src/main/proto/Service.proto
>  profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcCommandService.java
>  profiler/src/main/java/com/navercorp/pinpoint/profiler/receiver/grpc/GrpcCommandService.java

And find out that they are all gRpc-related. What if the Thrift transport is used other than gRpc? i think it would cause issue in this case. Are there any other changes may affect compatibility?
