### ISSUE TITLE
request timed out while waiting for response

### ISSUE THREAD

**Issue by Mosicol** [naver/pinpoint#7261]
version:2.1.0
Agent:
error:
web application directory [/usr/local/tomcat2/webapps/pinpoint-agent-2.1.0] has finished in [435] ms
13-Sep-2020 20:19:49.397 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8098"]
13-Sep-2020 20:19:49.405 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-9009"]
13-Sep-2020 20:19:49.407 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 504 ms
09-13 20:19:50.050 [nfoSender-Timer] WARN  c.n.p.p.AgentInfoSender                  -- request timed out while waiting for response.
09-13 20:19:53.053 [nfoSender-Timer] WARN  c.n.p.p.AgentInfoSender                  -- request timed out while waiting for response.
09-13 20:19:56.056 [nfoSender-Timer] WARN  c.n.p.p.AgentInfoSender                  -- request timed out while waiting for response.
09-13 20:19:59.059 [nfoSender-Timer] WARN  c.n.p.p.AgentInfoSender                  -- request timed out while waiting for response.
09-13 20:20:02.002 [nfoSender-Timer] WARN  c.n.p.p.AgentInfoSender                  -- request timed out while waiting for response.

**Comment by yjqg6666** [comment]
check your collector log for errors and also network connectivity between the agent and your collector.
