### ISSUE TITLE
agent log4j2 config file rolling

### ISSUE THREAD

**Issue by yjqg6666** [naver/pinpoint#7269]
#### What version of pinpoint are you using?
master/2.1.0

#### Describe the bug
The backupsize property in log4j2.xml of the agent module is unused. The log file would be rolling based on date, if large volume of log data per day may have some issue. Checked https://logging.apache.org/log4j/2.x/manual/appenders.html#RollingFileAppender for reference and did not find backupsize property. Checked the web module, the backupsize property is used by SizeBasedTriggeringPolicy. Please correct me if i'm wrong.

https://github.com/naver/pinpoint/blob/master/agent/src/main/resources/profiles/release/log4j2.xml#L7 and https://github.com/naver/pinpoint/blob/master/agent/src/main/resources/profiles/release/log4j2.xml#L23-L26

**Comment by emeroad** [comment]
You are right. It seems to be a mistake.
The old version of Log4j2 does not support SizeBasedTriggeringPolicy,
so this configuration was deleted, but the backupsize property is missing.

**Comment by yjqg6666** [comment]
Just made a PR #7273 for it. @emeroad

**Comment by yjqg6666** [comment]
Using SizeBasedTriggeringPolicy should be ok now from Pinpoint version 2.1.0 and afterwards.

**Comment by emeroad** [comment]
Thank you for your contributions
