### ISSUE TITLE
please Is there any plan to integrate Kubernetes

### ISSUE THREAD

**Issue by zzzhangqi** [naver/pinpoint#7277]
- **please Is there any plan to integrate Kubernetes**。
- I haven't been able to deploy in Kubernetes lately, so I hope you can give me some guidance. Thank you very much!

**Comment by RoySRose** [comment]
Hello, @zzzhangqi 

yes, I'm working on it with helm. It will be soon

**Comment by zzzhangqi** [comment]
> Hello, @zzzhangqi
> 
> yes, I'm working on it with helm. It will be soon

Could you tell me the approximate time
