### ISSUE TITLE
I want to see Pinpoint Call Stack in my custom jar like tomcat.

### ISSUE THREAD

**Issue by seocho2360** [naver/pinpoint#7280]
I want to see Pinpoint Call Stack in my custom jar like tomcat.
I added an entry point to pinpoint.config to keep track of the custom jar.
However, not all functions I added are being traced.

Can you figure out how to keep track of all methods like tomcat?

Please check the attached photo.

![agentserver](https://user-images.githubusercontent.com/69448843/93854748-4305e880-fcf1-11ea-86da-fd38c92ba745.PNG)
<img width="819" alt="tomcat" src="https://user-images.githubusercontent.com/69448843/93854750-44371580-fcf1-11ea-9c3c-04a66619f483.PNG">

**Comment by koo-taejin** [comment]
hi @seocho2360 

Please refer to this [link](https://naver.github.io/pinpoint/faq.html#my-custom-jar-application-is-not-being-traced-help).

thanks :)

**Comment by seocho2360** [comment]
> hi @seocho2360
> 
> Please refer to this [link](https://naver.github.io/pinpoint/faq.html#my-custom-jar-application-is-not-being-traced-help).
> 
> thanks :)


The link has already been verified, i was set this by configuring profiler.entrypoint in pinpoint.config file.
However, custom jar application and WAS plugin look different.
I want to trace all methods like WAS plugin.

Is it impossible to automatically track all methods like WAS plugin?
Do all methods need to be entered in profiler.entrypoint for tracking?


Why are other methods currently entered in the callstack not visible..?

please answer about my question.
thanks :)

**Comment by koo-taejin** [comment]
@seocho2360 

WAS does not trace whole method. 
Pinpoint traces method that each Plugin already picked up.

If you want to trace other  method, then you could trace it via 'profiler.include' option in pinpoint.config.

thanks :)

**Comment by seocho2360** [comment]
> @seocho2360
> 
> WAS does not trace whole method.
> Pinpoint traces method that each Plugin already picked up.
> 
> If you want to trace other method, then you could trace it via 'profiler.include' option in pinpoint.config.
> 
> thanks :)

i'm sorry. i don't know what you tell me
Could you explain in detail ?
