### ISSUE TITLE
Problem with i18n

### ISSUE THREAD

**Issue by philippe-granet** [naver/pinpoint#7301]
#### What version of pinpoint are you using?
2.1.0

#### Describe the bug
When browser is not in english, it display key instead of value
#### Screenshots
![image](https://user-images.githubusercontent.com/5667657/94573503-722cd480-0272-11eb-9180-c555c225ef48.png)

#### Logs
In Google Chrome console, with french navigator:
/assets/i18n/fr.json:1 Failed to load resource: the server responded with a status of 404 ()

#### Possible solution
Use english labels by default if label does not exist for the current navigator language

**Comment by binDongKim** [comment]
I missed setting the default option in fallback like your case. It's fixed by https://github.com/naver/pinpoint/pull/7317

Thanks for your report.
