### ISSUE TITLE
How to differentiate separate applications

### ISSUE THREAD

**Issue by ha02148** [naver/pinpoint#738]
Hi,

We have multiple war files/applications on our server such as the following.

www.test.com/app1
www.test.com/app2
www.test.com/app3

How can we separate the apps or filter on the frontend?

Thanks

**Comment by Xylus** [comment]
Hi, we currently do not manage multiple applications deployed on a single server instance separately as the logical boundary of a single Pinpoint agent is its host application.

You can however filter requests by url pattern (eg `/app1/*`, `/app2/*`) using the *Filter Wizard* on the Server Map. Right click on the edge leading to the server hosting the war files and select *Filter Transaction Wizard* to apply filter.

Thanks

**Comment by ha02148** [comment]
I just found out about the filter option today.  Very usefully.

Thanks

**Comment by Xylus** [comment]
:smile:
