### ISSUE TITLE
안녕하세요 pinpoint QuickStart 진행중 막히는 부분이 생겨 질문드립니다 ㅠㅠ

### ISSUE THREAD

**Issue by yangbongsoo** [naver/pinpoint#750]
우선 저는 windows에서 실행하려고 합니다. 

1. Requirements 작업 

![java6home](https://cloud.githubusercontent.com/assets/7060510/8783798/08808cc6-2f59-11e5-9891-16a1219140fb.PNG)
![java7home](https://cloud.githubusercontent.com/assets/7060510/8783799/0886cfb4-2f59-11e5-8cd6-645bf48014d2.PNG)
![javahome](https://cloud.githubusercontent.com/assets/7060510/8783800/08884506-2f59-11e5-8ded-57eca0b18888.PNG)
![maven](https://cloud.githubusercontent.com/assets/7060510/8783801/088bbf06-2f59-11e5-8eab-8a534a66abe2.PNG)
원래 기존에 있던 JAVA_HOME (JDK1.7)이 있어서 그대로 두고 JAVA_6_HOME, JAVA_7_HOME(JAVA_HOME과 일치) 시스템변수추가했습니다. 
2. Starting 
![pinpoint](https://cloud.githubusercontent.com/assets/7060510/8783855/7336625c-2f59-11e5-8332-058b40021874.PNG)

Pinpoint 설치는 완료했습니다. 
3. Install & Start HBase (여기서 문제 발생) 
![hbase](https://cloud.githubusercontent.com/assets/7060510/8783877/95439f04-2f59-11e5-874b-dbc70f3ff788.PNG)
(1) 먼저 제가 hbase를 알려주신 곳에서 다운받고 unzip했습니다. 

'Rename the directory to hbase so that the final HBase directory looks like quickstart\hbase\hbase' 이문장을 자체 해석하여(짧은 영어ㅠ) 
(2) 알집에서 푼 디렉토리의 이름을 hbase로 변경하 복사하여 
![quickstart hbase](https://cloud.githubusercontent.com/assets/7060510/8783956/1460d1d0-2f5a-11e5-84aa-bab6d816a548.PNG)
(3) PinPoint 디렉토리의 quickstart 디렉토리안에 hbase디렉토리를 붙여넣었습니다. 

그리고 Download & Start - Run quickstart/bin/start-hbase.sh를 보고서 
![1](https://cloud.githubusercontent.com/assets/7060510/8783982/4d997b28-2f5a-11e5-9433-87086ab2f519.PNG)

cd quickstart/bin 으로 간 다음에 start-hbase.sh 를 했는데 오류가 발생했습니다. 
hbase 위치가 잘못된거 같은 느낌이 들지만 정확한 이유를 몰라서 이렇게 글을 남기게 되었습니다 ㅠ

**Comment by koo-taejin** [comment]
윈도우는 해당 문서 읽고 해보시기 부탁드립니다. 
(https://github.com/naver/pinpoint/blob/master/quickstart/README.Win.ko.md)
윈도우 관련 커맨드 명령은 .cmd 파일들입니다 :)

**Comment by nstopkimsk** [comment]
이런 질문은 user group으로 해도 좋을 것 같아요. 
https://groups.google.com/forum/#!forum/pinpoint_user

**Comment by yangbongsoo** [comment]
오 ㅋㅋ 알려주셔서 감사합니다
