### ISSUE TITLE
improve alarm

### ISSUE THREAD

**Issue by minwoo-jung** [naver/pinpoint#762]
The alarm functionality is already usable as is, and if you would like to use it, all you need to do is uncomment the related configuration files.
However, the UI is still in its infant form and a lot may change in the next release - so you might want to keep this in mind.

Although the alarm functionality is there, this issue was created to further enhance the usability, and design of the alarm system as below:
1. The current UI is primitive and we would like to improve its usablity and design - all the current JSP files will be removed and the UI will be made dynamic like the other pages in our Web UI.
2. We have plans to add user authentication, and meld the alarm system in. To make this transition easier, the curent alarm tables will be modified to be more extendable.

Our plan is to complete the alarm system improvement and merge it into 1.5.0-SNAPSHOT by September.
However, we currently do not have a set release schedule for 1.5.0.

**Comment by xxxatt** [comment]
Seems the alarm function is not ready yet? The AlarmController is hidden now.

**Comment by minwoo-jung** [comment]
@xxxatt 
please refer to the outline above.

**Comment by xxxatt** [comment]
@minwoo-jung 
thank you for the update, will have a try :)

**Comment by minwoo-jung** [comment]
alarm guide doc : https://github.com/naver/pinpoint/blob/master/doc/alarm.md
