### ISSUE TITLE
Web Pinpoint does not see applications

### ISSUE THREAD

**Issue by mklynx** [naver/pinpoint#795]
Hi

I have the Collector and 4 agents running. I see information in my HBASE database.

hbase(main):001:0> scan 'ApplicationIndex'
ROW                                          COLUMN+CELL
 gLogCredMgtAPI                              column=Agents:1, timestamp=1438236227285, value=\x03\xF2
 gLogCredMgtAPI                              column=Agents:2, timestamp=1438240840533, value=\x03\xF2
 gLoginCredMgtAPI                            column=Agents:3, timestamp=1438242397180, value=\x03\xF2
 gLoginCredMgtAPI                            column=Agents:4, timestamp=1438242662590, value=\x03\xF2
2 row(s) in 0.2160 seconds

Both the WEB and de COLLECTOR are pointing to the same database. But when i get the webpage from the WEB application i can not choose any application i want to see.

No errors when i start tomcat and the WEB app.
I used the already compiled version 1.1.0 from your site.

Marcel Koert

**Comment by Xylus** [comment]
Issue resolved in [Google groups](https://groups.google.com/forum/#!topic/pinpoint_user/ao-hgoeB_k8).
