### ISSUE TITLE
Can you explain hbase table?

### ISSUE THREAD

**Issue by youtome** [naver/pinpoint#797]
hbase 각 테이블의 설명을 부탁드립니다.

테이블의 TTL이 몇가지로 나눠지고 있는데요. 각 기간이 비율로 맞춰줘야 하는것인지 아니면 무조건 일부 테이블의 CF만 줄일수 있는것인지 궁금합니다.

감사합니다.

**Comment by nstopkimsk** [comment]
Yes. We will do that.

**Comment by minwoo-jung** [comment]
I added comment for hbase table and TTL.

**Comment by minwoo-jung** [comment]
https://github.com/naver/pinpoint/blob/master/scripts/README.md
