### ISSUE TITLE
I would like to know whether pinpoint support jdk8 app？ 

### ISSUE THREAD

**Issue by binque** [naver/pinpoint#800]
I would like to know whether pinpoint support jdk8 app？

**Comment by nstopkimsk** [comment]
jdk8 will be supported by v1.5.0.

**Comment by dawidmalina** [comment]
When version 1.1.1 (or 1.5.0) will be released?

**Comment by emeroad** [comment]
1.1.1 will be released on August.
1.5.0(develop version) is not yet.

**Comment by dawidmalina** [comment]
:thumbsup:

**Comment by dawidmalina** [comment]
When exactly 1.1.1 will be released?

**Comment by nstopkimsk** [comment]
NAVER - http://www.naver.com/
--------------------------------------------
김성관(sungkwan.kim@naverco...) 님은 현재 부재중입니다.</br>
보내신 메일 <Re: [pinpoint] I would like to know whether pinpoint support jdk8 app？  (#800)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
김성관(sungkwan.kim@naverco...) 님이 남기신 메시지 입니다.
--------------------------------------------
[Absence period : 2015-08-24 10:00 ~ 2015-08-25 19:00 GMT +09:00]<br>교육으로 부재중입니다. 급한용무는 김진녕님께 요청부탁드립니다
--------------------------------------------

**Comment by Xylus** [comment]
We're planning to release 1.1.1 in 2 weeks.

**Comment by nstopkimsk** [comment]
we have released today (2015.9.9).
