### ISSUE TITLE
Can you support configurable depth at pinpoint web?

### ISSUE THREAD

**Issue by youtome** [naver/pinpoint#918]
안녕하세요. 대상 서비스가 매우 많은 경우에 기본값인 2가 너무 많은 컴포넌트를 보여주게 되어서 불편합니다.

기본값을 설정할 수 있도록 해주시면 좋을것 같습니다.

**Comment by youtome** [comment]
아래 코드를 수정해서 수동으로 변경하였습니다.
scripts/services/ServerMapDao.js - > 28, 29라인에 2를 원하는 값으로 수정한다.
scripts/directives/navbar.js -> 18라인에 DEFAULT_RANGE값을 2에서 원하는 값로 수정한다.

**Comment by denzelsN** [comment]
설정 화면에 해당 값을 수정할 수 있도록 작업 할 예정인데요. 
작업 우선순위 때문에 아직 작업을 못하고 있네요. 
1.5 버젼 릴리즈 시 추가하도록 하겠습니다.

**Comment by denzelsN** [comment]
설정화면에 depth 설정이 가능하도록 추가했습니다.  ( 1.5v )
권한 기능이 추가되기전까지는 브라우저의 localStorage에 설정을 저장합니다.
