### ISSUE TITLE
[Bug] Increase CPU load average when exclude url added

### ISSUE THREAD

**Issue by loslch** [naver/pinpoint#98]
Hi Pinpointer.

I'm ChangHun from NHN Entertainment.

First of all, I want give you thanks for this great project. I've installed Pinpoint last week for my project, then I got whole server status and request time at a glance. So, I can fix weak point of my service by pinpoint's favor.

However, I added exclude url for avoiding catch tomcat status monitoring request, at last weekend. The problem happened that CPU load and memory usage was increased. Because tomcat's threads was explosive increased. I don't know why this problem happened. I attached screenshot below for helping your understand. Please check it out.

![thread](https://cloud.githubusercontent.com/assets/498711/5714749/5c43593e-9b10-11e4-8374-bb882b4b5f9e.png)
![load_avg](https://cloud.githubusercontent.com/assets/498711/5714748/5c4270d2-9b10-11e4-9f18-3d22197b2a82.png)

I did change ```profiler.tomcat.excludeurl=/monitor/l7check.html``` to ```profiler.tomcat.excludeurl=/monitor/l7check.html,/managerAgent/getInfo``` of pinpoint.config file. I installed pinpoint 1.0.3.

Best regards,
ChangHun

**Comment by emeroad** [comment]
Thank you for your reporting.

Did not find problems in filtering code.

- [ExcludeUrlFilter.java](https://github.com/naver/pinpoint/blob/master/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/config/ExcludeUrlFilter.java)
 
Perhaps the application bug...
 
This issue is discussed in the company(nhn ent) e-mail

**Comment by loslch** [comment]
I made a mistake on my pinpoint settings. Thank you for your kindly response.

**Comment by minwoo-jung** [comment]
Hello ChangHun

We find bug for timer thread leak when agent could not connect continuously collector server.
We will fix bug in the near future.

thank you.
minwoo jung

**Comment by minwoo-jung** [comment]
This issue is known issue.
we was fixed bug already 1.0.4-SNAPSHOT.
I close this issue.
