### ISSUE TITLE
commons maven Compile error 

### ISSUE THREAD

**Issue by cowboy93** [naver/pinpoint#99]
안녕하세요 ?
commons 프로젝트 메이븐 install 실행시 다음과 같은 오류가 발생합니다. 
확인 부탁 드립니다. 

Failed to execute goal on project pinpoint-commons: Could not resolve dependencies for project com.navercorp.pinpoint:pinpoint-commons:jar:1.0.4-SNAPSHOT: Failed to collect dependencies for [com.navercorp.pinpoint:pinpoint-thrift:jar:1.0.4-SNAPSHOT (provided), org.apache.hadoop:hadoop-common:jar:2.0.0-cdh4.5.0 (compile?), org.apache.hadoop:hadoop-core:jar:2.0.0-mr1-cdh4.5.0 (compile?), org.apache.hbase:hbase:jar:0.94.6-cdh4.5.0 (compile?), com.sematext.hbasewd:hbasewd:jar:0.1.0 (compile?), org.apache.thrift:libthrift:jar:0.9.1 (compile?), org.springframework:spring-core:jar:3.2.3.RELEASE (compile?), org.springframework:spring-orm:jar:3.2.3.RELEASE (compile?), org.springframework.data:spring-data-hadoop:jar:1.0.2.RELEASE (compile?), org.codehaus.jackson:jackson-core-asl:jar:1.9.13 (compile?), org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13 (compile?), org.codehaus.jackson:jackson-xc:jar:1.9.13 (compile?), org.codehaus.jackson:jackson-jaxrs:jar:1.9.13 (compile?), org.slf4j:slf4j-api:jar:1.7.5 (compile?), org.slf4j:jcl-over-slf4j:jar:1.7.5 (test), org.slf4j:slf4j-log4j12:jar:1.7.5 (test), log4j:log4j:jar:1.2.16 (test), junit:junit:jar:4.8.2 (test), org.hamcrest:hamcrest-library:jar:1.3 (test), org.mockito:mockito-all:jar:1.8.4 (test)]: Failed to read artifact descriptor for com.navercorp.pinpoint:pinpoint-thrift:jar:1.0.4-SNAPSHOT: Could not find artifact com.navercorp.pinpoint:pom:pom:1.0.4-SNAPSHOT in cubrid.release.repository (http://maven.cubrid.org) -> [Help 1]

**Comment by lioolli** [comment]
commons만 단독으로 빌드하셔서 parent pom을 찾지 못한 것으로 추측됩니다. 
프로젝트 루트에서 전체 빌드를 해 보시고 안 되면 다시 말씀해 주세요~

**Comment by cowboy93** [comment]
루트 프로젝트에서 전체빌드하다가 commons 에서 오류 발생해서 
commons만 별도로 빌드하다가 오류난 것 보내드린겁니다. 

추가로 제 maven 저장소에는 검색해봐도 튜브리드가 전혀 없네요.

**Comment by cowboy93** [comment]
아침에 모든 Maven Repo를 지우고 해 봤는데도 잘 안되네요. 

추천하는 개발툴 환경 및 각종 툴의 버전등을 확인하고 싶습니다.

**Comment by lioolli** [comment]
에러 메시지 마지막 부분을 보면

Failed to read artifact descriptor for com.navercorp.pinpoint:pinpoint-thrift:jar:1.0.4-SNAPSHOT: Could not find artifact com.navercorp.pinpoint:pom:pom:1.0.4-SNAPSHOT in cubrid.release.repository 

pinpoint 의 parent pom인 com.navercorp.pinpoint:pom:pom:1.0.4-SNAPSHOT을 cubrid.release.repository에서 찾지 못했다는 것입니다. pinpoint의 빌드 결과몰은 현재 어떠한 리파지토리에도 등록되어 있지 않습니다. 빌드하면서 로컬에 직접 install 해서 사용하고 있습니다. cubrid.release.repository에서 찾아야 할 이유가 없습니다. 그래서 parent pom이 로컬에 install 되지 않은 것 같다고 말씀을 드린 것입니다.

프로젝트 루트에서 mvn install을 실행하신 후, 로컬 리파지토리에 com/navercorp/pinpoint/pom/1.0.4-SNAPSHOT/pom-1.0.4-SNAPSHOT.pom 파일이 존재하는지 확인 부탁드립니다.

**Comment by lioolli** [comment]
참고로 maven은 3.x를 사용하고 있으며(제 PC에는 3.0.5가 설치되어 있습니다) 2.x에서도 문제 없이 빌드되는 것을 확인했습니다.

**Comment by cowboy93** [comment]
저도 왜 큐브리드를 찾는지 모르겠으나 
말씀하신대로 루트에서 mvn install 을 실행하니 commons는 넘어가네요.
rpc쪽에서 테스트 오류나서 테스트 빼고 
$ mvn install -Dmaven.test.skip=true
이렇게 실행하니 다음과 같이 추가 오류가 나네요. 

미리 지속적인 follow up  감사합니다. 


[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] pinpoint ........................................... SUCCESS [  0.244 s]
[INFO] pinpoint-thrift .................................... SUCCESS [  1.184 s]
[INFO] pinpoint-commons ................................... SUCCESS [  1.808 s]
[INFO] pinpoint-bootstrap-core ............................ SUCCESS [  0.151 s]
[INFO] pinpoint-bootstrap ................................. SUCCESS [ 20.473 s]
[INFO] pinpoint-rpc ....................................... SUCCESS [  1.182 s]
[INFO] pinpoint-profiler .................................. SUCCESS [ 47.425 s]
[INFO] pinpoint-profiler-optional ......................... FAILURE [  0.051 s]
[INFO] pinpoint-agent-distribution ........................ SKIPPED
[INFO] pinpoint-collector ................................. SKIPPED
[INFO] pinpoint-web ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:12 min
[INFO] Finished at: 2015-01-14T11:19:36+09:00
[INFO] Final Memory: 25M/98M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile (default-compile) on project pinpoint-profiler-optional: Compilation failure -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pinpoint-profiler-optional

**Comment by koo-taejin** [comment]
아래 설명 참고 부탁드립니다. 

JDK 7+ and JAVA_7_HOME environment variable are required to build profiler-optional. If you choose to build each module separately, you may do so with JDK 6.

**Comment by Xylus** [comment]
installation guide에 해당 내용이 빠져있어 가이드가 명확하게 전달되지 않은 것 같습니다.
해당 내용 가이드에 추가하겠습니다.

제보 감사드립니다!

**Comment by emeroad** [comment]
[QuickStart](https://github.com/naver/pinpoint/blob/master/quickstart/README.md) 를 보시면 됩니다.

**Comment by cowboy93** [comment]
$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

이렇게 나오네요. 

Quick start 에도 자세한 설명이 없어서 문의 드린겁니다. ^^;

**Comment by lioolli** [comment]
pinpoint는 JDK6에서도 동작해야 하기 때문에 기본적으로 JDK6를 사용해 빌드 하고 있습니다.
다만 실행 환경이 JDK7일 때, JDK7에서 제공하는 유용한 기능들을 사용하기 위해서 profiler-optional이라는 프로젝트를 별도로 분리해 두었고, 이 프로젝트는 JDK7으로 빌드해야 합니다. 

하나의 maven 프로젝트에서 모듈 별로 다른 버전의 java 컴파일러를 사용해야 하기 위해서는 java 컴파일러의 위치를 지정해 주는 방법밖에 없습니다. 그래서 profiler-optional을 빌드할 때에는 JAVA_7_HOME이라는 환경변수를 사용하고 있습니다.

정리하면, JDK7(또는 그 이상)을 설치하시고 JAVA_7_HOME이라는 환경변수에 JDK7 디렉터리 경로를 설정해 두시면 profiler-optional을 빌드하실 수 있습니다.

**Comment by cowboy93** [comment]
아 그렇군요. 
상세한 설명 감사합니다. 

$ /usr/libexec/java_home -v 1.7
/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home
$ export JAVA_7_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home

맥 개발자들을 위해서 이 설명도 가이드에 넣어 주시면 좋을 듯 합니다. 

잘 도와주셔서 컴파일은 완료 되었습니다.
[INFO] 
[INFO] pinpoint ........................................... SUCCESS [  0.247 s]
[INFO] pinpoint-thrift .................................... SUCCESS [  1.238 s]
[INFO] pinpoint-commons ................................... SUCCESS [  1.825 s]
[INFO] pinpoint-bootstrap-core ............................ SUCCESS [  0.152 s]
[INFO] pinpoint-bootstrap ................................. SUCCESS [  0.475 s]
[INFO] pinpoint-rpc ....................................... SUCCESS [  0.171 s]
[INFO] pinpoint-profiler .................................. SUCCESS [  0.411 s]
[INFO] pinpoint-profiler-optional ......................... SUCCESS [  1.106 s]
[INFO] pinpoint-agent-distribution ........................ SUCCESS [01:12 min]
[INFO] pinpoint-collector ................................. SUCCESS [ 16.408 s]
[INFO] pinpoint-web ....................................... SUCCESS [ 54.974 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:29 min
[INFO] Finished at: 2015-01-14T12:00:14+09:00
[INFO] Final Memory: 33M/94M
[INFO] ------------------------------------------------------------------------

감사합니다.
